{
  "abstract": [
    {
      "text": "Name specifier constants provide access to the different names associated with a font.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTFont"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/name-specifier-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Name Specifier Constants"
  },
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFont": {
      "abstract": [
        {
          "text": "A font object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFont"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFont"
        }
      ],
      "role": "symbol",
      "title": "CTFont",
      "type": "topic",
      "url": "/documentation/coretext/ctfont"
    },
    "doc://com.apple.coretext/documentation/CoreText/font-feature-constants": {
      "abstract": [
        {
          "text": "These constants provide keys to font feature dictionary values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/font-feature-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Font Feature Constants",
      "type": "topic",
      "url": "/documentation/coretext/font-feature-constants"
    },
    "doc://com.apple.coretext/documentation/CoreText/font-variation-axis-dictionary-keys": {
      "abstract": [
        {
          "text": "These constants provide keys to font variation axis dictionary values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/font-variation-axis-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Font Variation Axis Dictionary Keys",
      "type": "topic",
      "url": "/documentation/coretext/font-variation-axis-dictionary-keys"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontCopyrightNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontCopyrightNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontCopyrightNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontCopyrightNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontCopyrightNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontcopyrightnamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontDescriptionNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontDescriptionNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontDescriptionNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDescriptionNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontDescriptionNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontdescriptionnamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontDesignerNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontDesignerNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontDesignerNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDesignerNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontDesignerNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontdesignernamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontDesignerURLNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontDesignerURLNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontDesignerURLNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDesignerURLNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontDesignerURLNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontdesignerurlnamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFamilyNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFamilyNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFamilyNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfamilynamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFullNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFullNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFullNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFullNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFullNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfullnamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontLicenseNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontLicenseNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontLicenseNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontLicenseNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontLicenseNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontlicensenamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontLicenseURLNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontLicenseURLNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontLicenseURLNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontLicenseURLNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontLicenseURLNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontlicenseurlnamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontManufacturerNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontManufacturerNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontManufacturerNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManufacturerNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontManufacturerNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontmanufacturernamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontPostScriptCIDNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontPostScriptCIDNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontPostScriptCIDNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontPostScriptCIDNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontPostScriptCIDNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontpostscriptcidnamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontPostScriptNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontPostScriptNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontPostScriptNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontPostScriptNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontPostScriptNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontpostscriptnamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontSampleTextNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontSampleTextNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontSampleTextNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontSampleTextNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontSampleTextNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontsampletextnamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontStyleNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontStyleNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontStyleNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontStyleNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontStyleNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontstylenamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontSubFamilyNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontSubFamilyNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontSubFamilyNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontSubFamilyNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontSubFamilyNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontsubfamilynamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTrademarkNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTrademarkNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTrademarkNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTrademarkNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTrademarkNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttrademarknamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontUniqueNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontUniqueNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontUniqueNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUniqueNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontUniqueNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontuniquenamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontVendorURLNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontVendorURLNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontVendorURLNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontVendorURLNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontVendorURLNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontvendorurlnamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontVersionNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontVersionNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontVersionNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontVersionNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontVersionNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontversionnamekey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Global-Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/font-variation-axis-dictionary-keys",
        "doc://com.apple.coretext/documentation/CoreText/font-feature-constants"
      ],
      "title": "Global Variables"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/kCTFontCopyrightNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontSubFamilyNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontStyleNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontUniqueNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFullNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontVersionNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontPostScriptNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTrademarkNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontManufacturerNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontDesignerNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontDescriptionNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontVendorURLNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontDesignerURLNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontLicenseNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontLicenseURLNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontSampleTextNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontPostScriptCIDNameKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/kCTFontCopyrightNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontSubFamilyNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontStyleNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontUniqueNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFullNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontVersionNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontPostScriptNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTrademarkNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontManufacturerNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontDesignerNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontDescriptionNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontVendorURLNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontDesignerURLNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontLicenseNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontLicenseURLNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontSampleTextNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontPostScriptCIDNameKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Global-Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/font-variation-axis-dictionary-keys",
                "doc://com.apple.coretext/documentation/CoreText/font-feature-constants"
              ],
              "title": "Global Variables"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontCopyrightNameKey/title",
          "value": "kCTFontCopyrightNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontCopyrightNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontCopyrightNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVendorURLNameKey/title",
          "value": "kCTFontVendorURLNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVendorURLNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontVendorURLNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontPostScriptCIDNameKey/title",
          "value": "kCTFontPostScriptCIDNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontPostScriptCIDNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontPostScriptCIDNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontUniqueNameKey/title",
          "value": "kCTFontUniqueNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontUniqueNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUniqueNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDesignerNameKey/title",
          "value": "kCTFontDesignerNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDesignerNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDesignerNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDescriptionNameKey/title",
          "value": "kCTFontDescriptionNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDescriptionNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDescriptionNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontSubFamilyNameKey/title",
          "value": "kCTFontSubFamilyNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontSubFamilyNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontSubFamilyNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFullNameKey/title",
          "value": "kCTFontFullNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFullNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFullNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVersionNameKey/title",
          "value": "kCTFontVersionNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVersionNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontVersionNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontStyleNameKey/title",
          "value": "kCTFontStyleNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontStyleNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontStyleNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDesignerURLNameKey/title",
          "value": "kCTFontDesignerURLNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDesignerURLNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDesignerURLNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/title",
          "value": "CTFontRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontPostScriptNameKey/title",
          "value": "kCTFontPostScriptNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontPostScriptNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontPostScriptNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTrademarkNameKey/title",
          "value": "kCTFontTrademarkNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTrademarkNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTrademarkNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontLicenseNameKey/title",
          "value": "kCTFontLicenseNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontLicenseNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontLicenseNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontSampleTextNameKey/title",
          "value": "kCTFontSampleTextNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontSampleTextNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontSampleTextNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFamilyNameKey/title",
          "value": "kCTFontFamilyNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFamilyNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFamilyNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontManufacturerNameKey/title",
          "value": "kCTFontManufacturerNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontManufacturerNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManufacturerNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontLicenseURLNameKey/title",
          "value": "kCTFontLicenseURLNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontLicenseURLNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontLicenseURLNameKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/name-specifier-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/name-specifier-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
