{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/SFNTLookupTablePtr"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@SFNTLookupTablePtr",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SFNTLookupTablePtr"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SFNTLookupTablePtr"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "SFNTLookupTablePtr"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SFNTLookupTablePtr"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/SFNTLookupTable",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@SFNTLookupTable",
              "text": "SFNTLookupTable"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/BslnBaselineClass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BslnBaselineClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/BslnBaselineClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BslnBaselineClass"
        }
      ],
      "role": "symbol",
      "title": "BslnBaselineClass",
      "type": "topic",
      "url": "/documentation/coretext/bslnbaselineclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/BslnBaselineRecord": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BslnBaselineRecord"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/BslnBaselineRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BslnBaselineRecord"
        }
      ],
      "role": "symbol",
      "title": "BslnBaselineRecord",
      "type": "topic",
      "url": "/documentation/coretext/bslnbaselinerecord"
    },
    "doc://com.apple.coretext/documentation/CoreText/BslnTableFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BslnTableFormat"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/BslnTableFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BslnTableFormat"
        }
      ],
      "role": "symbol",
      "title": "BslnTableFormat",
      "type": "topic",
      "url": "/documentation/coretext/bslntableformat"
    },
    "doc://com.apple.coretext/documentation/CoreText/BslnTablePtr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BslnTablePtr"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/BslnTablePtr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BslnTablePtr"
        }
      ],
      "role": "symbol",
      "title": "BslnTablePtr",
      "type": "topic",
      "url": "/documentation/coretext/bslntableptr"
    },
    "doc://com.apple.coretext/documentation/CoreText/FontLanguageCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FontLanguageCode"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/FontLanguageCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FontLanguageCode"
        }
      ],
      "role": "symbol",
      "title": "FontLanguageCode",
      "type": "topic",
      "url": "/documentation/coretext/fontlanguagecode"
    },
    "doc://com.apple.coretext/documentation/CoreText/FontNameCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FontNameCode"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/FontNameCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FontNameCode"
        }
      ],
      "role": "symbol",
      "title": "FontNameCode",
      "type": "topic",
      "url": "/documentation/coretext/fontnamecode"
    },
    "doc://com.apple.coretext/documentation/CoreText/FontPlatformCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FontPlatformCode"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/FontPlatformCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FontPlatformCode"
        }
      ],
      "role": "symbol",
      "title": "FontPlatformCode",
      "type": "topic",
      "url": "/documentation/coretext/fontplatformcode"
    },
    "doc://com.apple.coretext/documentation/CoreText/FontScriptCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FontScriptCode"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/FontScriptCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FontScriptCode"
        }
      ],
      "role": "symbol",
      "title": "FontScriptCode",
      "type": "topic",
      "url": "/documentation/coretext/fontscriptcode"
    },
    "doc://com.apple.coretext/documentation/CoreText/JustPCActionType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JustPCActionType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/JustPCActionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JustPCActionType"
        }
      ],
      "role": "symbol",
      "title": "JustPCActionType",
      "type": "topic",
      "url": "/documentation/coretext/justpcactiontype"
    },
    "doc://com.apple.coretext/documentation/CoreText/JustPCUnconditionalAddAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JustPCUnconditionalAddAction"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/JustPCUnconditionalAddAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JustPCUnconditionalAddAction"
        }
      ],
      "role": "symbol",
      "title": "JustPCUnconditionalAddAction",
      "type": "topic",
      "url": "/documentation/coretext/justpcunconditionaladdaction"
    },
    "doc://com.apple.coretext/documentation/CoreText/JustificationFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JustificationFlags"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/JustificationFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JustificationFlags"
        }
      ],
      "role": "symbol",
      "title": "JustificationFlags",
      "type": "topic",
      "url": "/documentation/coretext/justificationflags"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernArrayOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "KernArrayOffset"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernArrayOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "KernArrayOffset"
        }
      ],
      "role": "symbol",
      "title": "KernArrayOffset",
      "type": "topic",
      "url": "/documentation/coretext/kernarrayoffset"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernKerningValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "KernKerningValue"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernKerningValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "KernKerningValue"
        }
      ],
      "role": "symbol",
      "title": "KernKerningValue",
      "type": "topic",
      "url": "/documentation/coretext/kernkerningvalue"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernOffsetTablePtr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "KernOffsetTablePtr"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernOffsetTablePtr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "KernOffsetTablePtr"
        }
      ],
      "role": "symbol",
      "title": "KernOffsetTablePtr",
      "type": "topic",
      "url": "/documentation/coretext/kernoffsettableptr"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernOrderedListEntryPtr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "KernOrderedListEntryPtr"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernOrderedListEntryPtr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "KernOrderedListEntryPtr"
        }
      ],
      "role": "symbol",
      "title": "KernOrderedListEntryPtr",
      "type": "topic",
      "url": "/documentation/coretext/kernorderedlistentryptr"
    },
    "doc://com.apple.coretext/documentation/CoreText/SFNTLookupTable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFNTLookupTable"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/SFNTLookupTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFNTLookupTable"
        }
      ],
      "role": "symbol",
      "title": "SFNTLookupTable",
      "type": "topic",
      "url": "/documentation/coretext/sfntlookuptable"
    },
    "doc://com.apple.coretext/documentation/CoreText/SFNTLookupTablePtr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFNTLookupTablePtr"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/SFNTLookupTablePtr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFNTLookupTablePtr"
        }
      ],
      "role": "symbol",
      "title": "SFNTLookupTablePtr",
      "type": "topic",
      "url": "/documentation/coretext/sfntlookuptableptr"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Aliases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/BslnBaselineClass",
        "doc://com.apple.coretext/documentation/CoreText/BslnBaselineRecord",
        "doc://com.apple.coretext/documentation/CoreText/BslnTableFormat",
        "doc://com.apple.coretext/documentation/CoreText/BslnTablePtr",
        "doc://com.apple.coretext/documentation/CoreText/FontLanguageCode",
        "doc://com.apple.coretext/documentation/CoreText/FontNameCode",
        "doc://com.apple.coretext/documentation/CoreText/FontPlatformCode",
        "doc://com.apple.coretext/documentation/CoreText/FontScriptCode",
        "doc://com.apple.coretext/documentation/CoreText/JustPCActionType",
        "doc://com.apple.coretext/documentation/CoreText/JustPCUnconditionalAddAction",
        "doc://com.apple.coretext/documentation/CoreText/JustificationFlags",
        "doc://com.apple.coretext/documentation/CoreText/KernArrayOffset",
        "doc://com.apple.coretext/documentation/CoreText/KernKerningValue",
        "doc://com.apple.coretext/documentation/CoreText/KernOffsetTablePtr",
        "doc://com.apple.coretext/documentation/CoreText/KernOrderedListEntryPtr"
      ],
      "title": "Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SFNTLookupTablePtr"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFNTLookupTablePtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFNTLookupTablePtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Type-Aliases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/BslnBaselineClass",
                "doc://com.apple.coretext/documentation/CoreText/BslnBaselineRecord",
                "doc://com.apple.coretext/documentation/CoreText/BslnTableFormat",
                "doc://com.apple.coretext/documentation/CoreText/BslnTablePtr",
                "doc://com.apple.coretext/documentation/CoreText/FontLanguageCode",
                "doc://com.apple.coretext/documentation/CoreText/FontNameCode",
                "doc://com.apple.coretext/documentation/CoreText/FontPlatformCode",
                "doc://com.apple.coretext/documentation/CoreText/FontScriptCode",
                "doc://com.apple.coretext/documentation/CoreText/JustPCActionType",
                "doc://com.apple.coretext/documentation/CoreText/JustPCUnconditionalAddAction",
                "doc://com.apple.coretext/documentation/CoreText/JustificationFlags",
                "doc://com.apple.coretext/documentation/CoreText/KernArrayOffset",
                "doc://com.apple.coretext/documentation/CoreText/KernKerningValue",
                "doc://com.apple.coretext/documentation/CoreText/KernOffsetTablePtr",
                "doc://com.apple.coretext/documentation/CoreText/KernOrderedListEntryPtr"
              ],
              "title": "Type Aliases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/SFNTLookupTable",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@SFNTLookupTable",
                    "text": "SFNTLookupTable"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "SFNTLookupTablePtr"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernKerningValue/title",
          "value": "KernKerningValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernKerningValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "KernKerningValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernKerningValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "KernKerningValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1FontNameCode/title",
          "value": "FontNameCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1FontNameCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FontNameCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1FontNameCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FontNameCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnTableFormat/title",
          "value": "BslnTableFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnTableFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnTableFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnTableFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnTableFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCActionType/title",
          "value": "JustPCActionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCActionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JustPCActionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCActionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JustPCActionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupTablePtr/title",
          "value": "SFNTLookupTablePtr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupTablePtr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFNTLookupTablePtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupTablePtr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFNTLookupTablePtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnBaselineClass/title",
          "value": "BslnBaselineClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnBaselineClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnBaselineClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnBaselineClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnBaselineClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnTablePtr/title",
          "value": "BslnTablePtr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnTablePtr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnTablePtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnTablePtr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnTablePtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernOrderedListEntryPtr/title",
          "value": "KernOrderedListEntryPtr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernOrderedListEntryPtr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "KernOrderedListEntryPtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernOrderedListEntryPtr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "KernOrderedListEntryPtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1FontScriptCode/title",
          "value": "FontScriptCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1FontScriptCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FontScriptCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1FontScriptCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FontScriptCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1FontPlatformCode/title",
          "value": "FontPlatformCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1FontPlatformCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FontPlatformCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1FontPlatformCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FontPlatformCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernOffsetTablePtr/title",
          "value": "KernOffsetTablePtr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernOffsetTablePtr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "KernOffsetTablePtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernOffsetTablePtr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "KernOffsetTablePtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustificationFlags/title",
          "value": "JustificationFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustificationFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JustificationFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustificationFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JustificationFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCUnconditionalAddAction/title",
          "value": "JustPCUnconditionalAddAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCUnconditionalAddAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JustPCUnconditionalAddAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCUnconditionalAddAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JustPCUnconditionalAddAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernArrayOffset/title",
          "value": "KernArrayOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernArrayOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "KernArrayOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernArrayOffset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "KernArrayOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1FontLanguageCode/title",
          "value": "FontLanguageCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1FontLanguageCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FontLanguageCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1FontLanguageCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FontLanguageCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupTable/title",
          "value": "SFNTLookupTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFNTLookupTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupTable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFNTLookupTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnBaselineRecord/title",
          "value": "BslnBaselineRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnBaselineRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnBaselineRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnBaselineRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnBaselineRecord"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/sfntlookuptableptr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/sfntlookuptableptr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
