{
  "abstract": [
    {
      "text": "These constants represent string attribute names.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/styling-attributed-strings"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/string-attribute-name-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "String Attribute Name Constants"
  },
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyle": {
      "abstract": [
        {
          "text": "Underline style specifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTUnderlineStyle"
        }
      ],
      "role": "symbol",
      "title": "CTUnderlineStyle",
      "type": "topic",
      "url": "/documentation/coretext/ctunderlinestyle"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers": {
      "abstract": [
        {
          "text": "Underline style modifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTUnderlineStyleModifiers"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTUnderlineStyleModifiers"
        }
      ],
      "role": "symbol",
      "title": "CTUnderlineStyleModifiers",
      "type": "topic",
      "url": "/documentation/coretext/ctunderlinestylemodifiers"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTBaselineOffsetAttributeName": {
      "abstract": [
        {
          "text": "Vertical offset for text position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTBaselineOffsetAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTBaselineOffsetAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTBaselineOffsetAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTBaselineOffsetAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctbaselineoffsetattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTCharacterShapeAttributeName": {
      "abstract": [
        {
          "text": "Controls glyph selection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTCharacterShapeAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTCharacterShapeAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTCharacterShapeAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTCharacterShapeAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctcharactershapeattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontAttributeName": {
      "abstract": [
        {
          "text": "The font of the text to which this attribute applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTFontAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctfontattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTForegroundColorAttributeName": {
      "abstract": [
        {
          "text": "The foreground color of the text to which this attribute applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTForegroundColorAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTForegroundColorAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTForegroundColorAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTForegroundColorAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctforegroundcolorattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTForegroundColorFromContextAttributeName": {
      "abstract": [
        {
          "text": "Sets a foreground color using the context’s fill color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTForegroundColorFromContextAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTForegroundColorFromContextAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTForegroundColorFromContextAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTForegroundColorFromContextAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctforegroundcolorfromcontextattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTGlyphInfoAttributeName": {
      "abstract": [
        {
          "text": "The glyph info object to apply to the text associated with this attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTGlyphInfoAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTGlyphInfoAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTGlyphInfoAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTGlyphInfoAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctglyphinfoattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTKernAttributeName": {
      "abstract": [
        {
          "text": "The amount to kern the next character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTKernAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTKernAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTKernAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTKernAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctkernattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTLigatureAttributeName": {
      "abstract": [
        {
          "text": "The type of ligatures to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTLigatureAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTLigatureAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTLigatureAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTLigatureAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctligatureattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTParagraphStyleAttributeName": {
      "abstract": [
        {
          "text": "The paragraph style of the text to which this attribute applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTParagraphStyleAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTParagraphStyleAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctparagraphstyleattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTRunDelegateAttributeName": {
      "abstract": [
        {
          "text": "The run-delegate object to apply to an attribute range of the string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTRunDelegateAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTRunDelegateAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRunDelegateAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTRunDelegateAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctrundelegateattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTStrokeColorAttributeName": {
      "abstract": [
        {
          "text": "The stroke color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTStrokeColorAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTStrokeColorAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTStrokeColorAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTStrokeColorAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctstrokecolorattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTStrokeWidthAttributeName": {
      "abstract": [
        {
          "text": "The stroke width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTStrokeWidthAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTStrokeWidthAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTStrokeWidthAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTStrokeWidthAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctstrokewidthattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTSuperscriptAttributeName": {
      "abstract": [
        {
          "text": "Controls vertical text positioning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTSuperscriptAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTSuperscriptAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTSuperscriptAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTSuperscriptAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctsuperscriptattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTTrackingAttributeName": {
      "abstract": [
        {
          "text": "The tracking for the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTTrackingAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTTrackingAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTTrackingAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTTrackingAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kcttrackingattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTUnderlineColorAttributeName": {
      "abstract": [
        {
          "text": "The underline color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTUnderlineColorAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTUnderlineColorAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTUnderlineColorAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTUnderlineColorAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctunderlinecolorattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTUnderlineStyleAttributeName": {
      "abstract": [
        {
          "text": "The style of underlining, to be applied at render time, for the text to which this attribute applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTUnderlineStyleAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTUnderlineStyleAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTUnderlineStyleAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTUnderlineStyleAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctunderlinestyleattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTVerticalFormsAttributeName": {
      "abstract": [
        {
          "text": "The orientation of the glyphs in the text to which this attribute applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTVerticalFormsAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTVerticalFormsAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTVerticalFormsAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTVerticalFormsAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctverticalformsattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/styling-attributed-strings": {
      "abstract": [
        {
          "text": "Attributes to which Core Text responds when placed in a ",
          "type": "text"
        },
        {
          "code": "CFAttributedString",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/styling-attributed-strings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Styling Attributed Strings",
      "type": "topic",
      "url": "/documentation/coretext/styling-attributed-strings"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyle",
        "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/kCTCharacterShapeAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTKernAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTLigatureAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTForegroundColorAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTForegroundColorFromContextAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTParagraphStyleAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTStrokeWidthAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTStrokeColorAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTSuperscriptAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTUnderlineColorAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTUnderlineStyleAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTVerticalFormsAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTGlyphInfoAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTRunDelegateAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTBaselineOffsetAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTTrackingAttributeName"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/kCTCharacterShapeAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTKernAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTLigatureAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTForegroundColorAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTForegroundColorFromContextAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTParagraphStyleAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTStrokeWidthAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTStrokeColorAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTSuperscriptAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTUnderlineColorAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTUnderlineStyleAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTVerticalFormsAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTGlyphInfoAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTRunDelegateAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTBaselineOffsetAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTTrackingAttributeName"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyle",
                "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTStrokeWidthAttributeName/title",
          "value": "kCTStrokeWidthAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTStrokeWidthAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTStrokeWidthAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTVerticalFormsAttributeName/title",
          "value": "kCTVerticalFormsAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTVerticalFormsAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTVerticalFormsAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTTrackingAttributeName/title",
          "value": "kCTTrackingAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTTrackingAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTTrackingAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTUnderlineColorAttributeName/title",
          "value": "kCTUnderlineColorAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTUnderlineColorAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTUnderlineColorAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineOffsetAttributeName/title",
          "value": "kCTBaselineOffsetAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineOffsetAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTBaselineOffsetAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTStrokeColorAttributeName/title",
          "value": "kCTStrokeColorAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTStrokeColorAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTStrokeColorAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTRunDelegateAttributeName/title",
          "value": "kCTRunDelegateAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTRunDelegateAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRunDelegateAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTGlyphInfoAttributeName/title",
          "value": "kCTGlyphInfoAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTGlyphInfoAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTGlyphInfoAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTUnderlineStyleAttributeName/title",
          "value": "kCTUnderlineStyleAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTUnderlineStyleAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTUnderlineStyleAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTParagraphStyleAttributeName/title",
          "value": "kCTParagraphStyleAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTParagraphStyleAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontAttributeName/title",
          "value": "kCTFontAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTSuperscriptAttributeName/title",
          "value": "kCTSuperscriptAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTSuperscriptAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTSuperscriptAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTCharacterShapeAttributeName/title",
          "value": "kCTCharacterShapeAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTCharacterShapeAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTCharacterShapeAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers/title",
          "value": "CTUnderlineStyleModifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTUnderlineStyleModifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTUnderlineStyleModifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTKernAttributeName/title",
          "value": "kCTKernAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTKernAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTKernAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTForegroundColorFromContextAttributeName/title",
          "value": "kCTForegroundColorFromContextAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTForegroundColorFromContextAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTForegroundColorFromContextAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTForegroundColorAttributeName/title",
          "value": "kCTForegroundColorAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTForegroundColorAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTForegroundColorAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTLigatureAttributeName/title",
          "value": "kCTLigatureAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTLigatureAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTLigatureAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyle/title",
          "value": "CTUnderlineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTUnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTUnderlineStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/string-attribute-name-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/string-attribute-name-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
