{
  "abstract": [
    {
      "text": "Attributes to which Core Text responds when placed in a ",
      "type": "text"
    },
    {
      "code": "CFAttributedString",
      "type": "codeVoice"
    },
    {
      "text": " object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/styling-attributed-strings"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Styling Attributed Strings"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This reference document describes the attributes to which Core Text responds when the attributes are placed in a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfattributedstring-s1s",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyle": {
      "abstract": [
        {
          "text": "Underline style specifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTUnderlineStyle"
        }
      ],
      "role": "symbol",
      "title": "CTUnderlineStyle",
      "type": "topic",
      "url": "/documentation/coretext/ctunderlinestyle"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers": {
      "abstract": [
        {
          "text": "Underline style modifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTUnderlineStyleModifiers"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTUnderlineStyleModifiers"
        }
      ],
      "role": "symbol",
      "title": "CTUnderlineStyleModifiers",
      "type": "topic",
      "url": "/documentation/coretext/ctunderlinestylemodifiers"
    },
    "doc://com.apple.coretext/documentation/CoreText/core-text-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/core-text-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Text Constants",
      "type": "topic",
      "url": "/documentation/coretext/core-text-constants"
    },
    "doc://com.apple.coretext/documentation/CoreText/core-text-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/core-text-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Text Data Types",
      "type": "topic",
      "url": "/documentation/coretext/core-text-data-types"
    },
    "doc://com.apple.coretext/documentation/CoreText/core-text-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/core-text-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Text Enumerations",
      "type": "topic",
      "url": "/documentation/coretext/core-text-enumerations"
    },
    "doc://com.apple.coretext/documentation/CoreText/core-text-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/core-text-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Text Functions",
      "type": "topic",
      "url": "/documentation/coretext/core-text-functions"
    },
    "doc://com.apple.coretext/documentation/CoreText/core-text-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/core-text-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Text Structures",
      "type": "topic",
      "url": "/documentation/coretext/core-text-structures"
    },
    "doc://com.apple.coretext/documentation/CoreText/sfnt-support": {
      "abstract": [],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/sfnt-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SFNT Support",
      "type": "topic",
      "url": "/documentation/coretext/sfnt-support"
    },
    "doc://com.apple.coretext/documentation/CoreText/string-attribute-name-constants": {
      "abstract": [
        {
          "text": "These constants represent string attribute names.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/string-attribute-name-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "String Attribute Name Constants",
      "type": "topic",
      "url": "/documentation/coretext/string-attribute-name-constants"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfattributedstring-s1s": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfattributedstring-s1s",
      "kind": "article",
      "role": "article",
      "title": "CFAttributedString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfattributedstring-s1s"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/core-text-structures",
        "doc://com.apple.coretext/documentation/CoreText/core-text-enumerations",
        "doc://com.apple.coretext/documentation/CoreText/core-text-constants",
        "doc://com.apple.coretext/documentation/CoreText/core-text-functions",
        "doc://com.apple.coretext/documentation/CoreText/core-text-data-types",
        "doc://com.apple.coretext/documentation/CoreText/sfnt-support"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/string-attribute-name-constants",
        "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyle",
        "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/string-attribute-name-constants",
                "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyle",
                "doc://com.apple.coretext/documentation/CoreText/CTUnderlineStyleModifiers"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/core-text-structures",
                "doc://com.apple.coretext/documentation/CoreText/core-text-enumerations",
                "doc://com.apple.coretext/documentation/CoreText/core-text-constants",
                "doc://com.apple.coretext/documentation/CoreText/core-text-functions",
                "doc://com.apple.coretext/documentation/CoreText/core-text-data-types",
                "doc://com.apple.coretext/documentation/CoreText/sfnt-support"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers/title",
          "value": "CTUnderlineStyleModifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTUnderlineStyleModifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyleModifiers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTUnderlineStyleModifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyle/title",
          "value": "CTUnderlineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTUnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTUnderlineStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTUnderlineStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/styling-attributed-strings"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/styling-attributed-strings"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
