{
  "abstract": [
    {
      "text": "Activate the session and start delivering events to an event handler.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessorySession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessorySession/activate(on:eventHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ASAccessorySession(im)activateWithQueue:eventHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "activate"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "on"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@dispatch_queue_t",
        "text": "dispatch_queue_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "eventHandler"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ASAccessoryEvent",
        "text": "ASAccessoryEvent"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AccessorySetupKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "activateWithQueue:eventHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "activate(on:eventHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "activate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "on"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "queue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@dispatch_queue_t",
              "text": "dispatch_queue_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "eventHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessoryEvent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ASAccessoryEvent",
              "text": "ASAccessoryEvent"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The dispatch the session uses to deliver events to ",
                  "type": "text"
                },
                {
                  "code": "eventHandler",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "queue"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A closure or block that receives events generated by the session. Each callback to the event handler provides an ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessoryEvent",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " as a parameter, and expects no return value.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "eventHandler"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/discovering-and-configuring-accessories"
      ]
    }
  ],
  "references": {
    "discovering-configuring-accessories-PageImage-card.png": {
      "alt": "An illustration that shows Bluetooth and Wi-Fi devices communicating.",
      "identifier": "discovering-configuring-accessories-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ab9450c2b7948ffea221e483d1b210d3/discovering-configuring-accessories-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/50cc817a2ebceed40a67b891238dd603/discovering-configuring-accessories-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit": {
      "abstract": [
        {
          "text": "Enable privacy-preserving discovery and configuration of accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AccessorySetupKit",
      "type": "topic",
      "url": "/documentation/accessorysetupkit"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessoryEvent": {
      "abstract": [
        {
          "text": "Properties of an event encountered during accessory discovery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAccessoryEvent"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessoryEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAccessoryEvent"
        }
      ],
      "role": "symbol",
      "title": "ASAccessoryEvent",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asaccessoryevent"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessorySession": {
      "abstract": [
        {
          "text": "A class to coordinate accessory discovery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAccessorySession"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessorySession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAccessorySession"
        }
      ],
      "role": "symbol",
      "title": "ASAccessorySession",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asaccessorysession"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessorySession/activate(on:eventHandler:)": {
      "abstract": [
        {
          "text": "Activate the session and start delivering events to an event handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "on"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "eventHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ASAccessoryEvent",
          "text": "ASAccessoryEvent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessorySession/activate(on:eventHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activateWithQueue:eventHandler:"
        }
      ],
      "role": "symbol",
      "title": "activate(on:eventHandler:)",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asaccessorysession/activate(on:eventhandler:)"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessorySession/invalidate()": {
      "abstract": [
        {
          "text": "Invalidate the session by stopping any operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessorySession/invalidate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidate"
        }
      ],
      "role": "symbol",
      "title": "invalidate()",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asaccessorysession/invalidate()"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/discovering-and-configuring-accessories": {
      "abstract": [
        {
          "text": "Detect nearby accessories and facilitate their setup.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/discovering-and-configuring-accessories",
      "images": [
        {
          "identifier": "discovering-configuring-accessories-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Discovering and configuring accessories",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/discovering-and-configuring-accessories"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t": {
      "abstract": [
        {
          "text": "A lightweight object to which your application submits blocks for subsequent execution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "dispatch_queue_t",
      "type": "topic",
      "url": "/documentation/Dispatch/dispatch_queue_t"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-session-life-cycle",
      "generated": true,
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessorySession/invalidate()"
      ],
      "title": "Managing the session life cycle"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "activateWithQueue:eventHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "activateWithQueue:eventHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit",
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessorySession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-session-life-cycle",
              "generated": true,
              "identifiers": [
                "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessorySession/invalidate()"
              ],
              "title": "Managing the session life cycle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "activateWithQueue:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@dispatch_queue_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@dispatch_queue_t",
                    "text": "dispatch_queue_t"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "queue"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "eventHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessoryEvent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ASAccessoryEvent",
                    "text": "ASAccessoryEvent"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "event"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "eventHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The dispatch the session uses to deliver events to ",
                        "type": "text"
                      },
                      {
                        "code": "eventHandler",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "queue"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A closure or block that receives events generated by the session. Each callback to the event handler provides an ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessoryEvent",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " as a parameter, and expects no return value.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "eventHandler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessorySession~1activate(on:eventHandler:)/title",
          "value": "activateWithQueue:eventHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessorySession~1activate(on:eventHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "activateWithQueue:eventHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessoryEvent/title",
          "value": "ASAccessoryEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessoryEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAccessoryEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessoryEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAccessoryEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessorySession~1invalidate()/title",
          "value": "invalidate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessorySession~1invalidate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invalidate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessorySession/title",
          "value": "ASAccessorySession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessorySession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAccessorySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessorySession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAccessorySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@dispatch_queue_t/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue",
              "text": "NSObject<OS_dispatch_queue>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "dispatch_queue_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessorysetupkit/asaccessorysession/activate(on:eventhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accessorysetupkit/asaccessorysession/activate(on:eventhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
