{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/hourMinuteSecond"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSDatePickerElementFlags@NSDatePickerElementFlagHourMinuteSecond",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "hourMinuteSecond"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSDatePicker",
        "text": "NSDatePicker"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSDatePickerElementFlags",
        "text": "ElementFlags"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSDatePickerElementFlagHourMinuteSecond"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "hourMinuteSecond"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "hourMinuteSecond"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSDatePicker",
              "text": "NSDatePicker"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSDatePickerElementFlags",
              "text": "ElementFlags"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker": {
      "abstract": [
        {
          "text": "A display of a calendar date with controls for editing the date value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDatePicker"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDatePicker"
        }
      ],
      "role": "symbol",
      "title": "NSDatePicker",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags": {
      "abstract": [
        {
          "text": "Constants that specify the date and time elements displayed by the picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ElementFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ElementFlags"
        }
      ],
      "role": "symbol",
      "title": "NSDatePicker.ElementFlags",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/elementflags"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/era": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "era"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDatePicker",
          "text": "NSDatePicker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDatePickerElementFlags",
          "text": "ElementFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/era",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDatePickerElementFlagEra"
        }
      ],
      "role": "symbol",
      "title": "era",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/elementflags/era"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/hourMinute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hourMinute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDatePicker",
          "text": "NSDatePicker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDatePickerElementFlags",
          "text": "ElementFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/hourMinute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDatePickerElementFlagHourMinute"
        }
      ],
      "role": "symbol",
      "title": "hourMinute",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/elementflags/hourminute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/hourMinuteSecond": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hourMinuteSecond"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDatePicker",
          "text": "NSDatePicker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDatePickerElementFlags",
          "text": "ElementFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/hourMinuteSecond",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDatePickerElementFlagHourMinuteSecond"
        }
      ],
      "role": "symbol",
      "title": "hourMinuteSecond",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/elementflags/hourminutesecond"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/timeZone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeZone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDatePicker",
          "text": "NSDatePicker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDatePickerElementFlags",
          "text": "ElementFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/timeZone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDatePickerElementFlagTimeZone"
        }
      ],
      "role": "symbol",
      "title": "timeZone",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/elementflags/timezone"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/yearMonth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yearMonth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDatePicker",
          "text": "NSDatePicker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDatePickerElementFlags",
          "text": "ElementFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/yearMonth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDatePickerElementFlagYearMonth"
        }
      ],
      "role": "symbol",
      "title": "yearMonth",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/elementflags/yearmonth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/yearMonthDay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yearMonthDay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDatePicker",
          "text": "NSDatePicker"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDatePickerElementFlags",
          "text": "ElementFlags"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/yearMonthDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDatePickerElementFlagYearMonthDay"
        }
      ],
      "role": "symbol",
      "title": "yearMonthDay",
      "type": "topic",
      "url": "/documentation/appkit/nsdatepicker/elementflags/yearmonthday"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/era",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/hourMinute",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/timeZone",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/yearMonth",
        "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/yearMonthDay"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSDatePickerElementFlagHourMinuteSecond"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlagHourMinuteSecond"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/era",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/hourMinute",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/timeZone",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/yearMonth",
                "doc://com.apple.appkit/documentation/AppKit/NSDatePicker/ElementFlags/yearMonthDay"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSDatePickerElementFlagHourMinuteSecond"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1yearMonth/title",
          "value": "NSDatePickerElementFlagYearMonth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1yearMonth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlagYearMonth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1timeZone/title",
          "value": "NSDatePickerElementFlagTimeZone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1timeZone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlagTimeZone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags/title",
          "value": "NSDatePickerElementFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker/title",
          "value": "NSDatePicker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1yearMonthDay/title",
          "value": "NSDatePickerElementFlagYearMonthDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1yearMonthDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlagYearMonthDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1hourMinute/title",
          "value": "NSDatePickerElementFlagHourMinute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1hourMinute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlagHourMinute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1era/title",
          "value": "NSDatePickerElementFlagEra"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1era/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlagEra"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1hourMinuteSecond/title",
          "value": "NSDatePickerElementFlagHourMinuteSecond"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDatePicker~1ElementFlags~1hourMinuteSecond/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDatePickerElementFlagHourMinuteSecond"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdatepicker/elementflags/hourminutesecond"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsdatepicker/elementflags/hourminutesecond"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
