{"abstract":[{"text":"A Boolean value that controls whether single-line text fields tighten intercharacter spacing before truncating the text.","type":"text"}],"variants":[{"paths":["/documentation/appkit/nstextfield/allowsdefaulttighteningfortruncation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nstextfield/allowsdefaulttighteningfortruncation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSTextField/allowsDefaultTighteningForTruncation"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsDefaultTighteningForTruncation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The text field ignores this property when its value is an attributed string.","type":"text"}]}],"kind":"content"}],"seeAlsoSections":[{"title":"Configuring Line Wrapping","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextField/lineBreakStrategy","doc://com.apple.appkit/documentation/AppKit/NSTextField/maximumNumberOfLines"],"anchor":"Configuring-Line-Wrapping","generated":true}],"metadata":{"role":"symbol","modules":[{"name":"AppKit"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)NSTextField(py)allowsDefaultTighteningForTruncation","navigatorTitle":[{"kind":"identifier","text":"allowsDefaultTighteningForTruncation"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsDefaultTighteningForTruncation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":[{"introducedAt":"10.11","unavailable":false,"name":"macOS","deprecated":false,"beta":false}],"symbolKind":"property","title":"allowsDefaultTighteningForTruncation"},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTextField"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTextField/lineBreakStrategy":{"role":"symbol","abstract":[{"type":"text","text":"The strategy that the system uses to break lines when laying out multiple lines of text."}],"title":"lineBreakStrategy","kind":"symbol","url":"/documentation/appkit/nstextfield/linebreakstrategy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineBreakStrategy"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSParagraphStyle","kind":"typeIdentifier","text":"NSParagraphStyle"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSLineBreakStrategy","kind":"typeIdentifier","text":"LineBreakStrategy"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField/lineBreakStrategy","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lineBreakStrategy"}]},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSTextField":{"title":"NSTextField","navigatorTitle":[{"text":"NSTextField","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField","role":"symbol","url":"/documentation/appkit/nstextfield","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTextField","kind":"identifier"}],"abstract":[{"text":"Text the user can select or edit to send an action message to a target when the user presses the Return key.","type":"text"}]},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSTextField/maximumNumberOfLines":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maximumNumberOfLines"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField/maximumNumberOfLines","abstract":[{"text":"The maximum number of lines a wrapping text field displays before clipping or truncating the text.","type":"text"}],"type":"topic","title":"maximumNumberOfLines","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"maximumNumberOfLines"}],"url":"/documentation/appkit/nstextfield/maximumnumberoflines","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTextField/allowsDefaultTighteningForTruncation":{"role":"symbol","abstract":[{"type":"text","text":"A Boolean value that controls whether single-line text fields tighten intercharacter spacing before truncating the text."}],"title":"allowsDefaultTighteningForTruncation","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"allowsDefaultTighteningForTruncation"}],"url":"/documentation/appkit/nstextfield/allowsdefaulttighteningfortruncation","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField/allowsDefaultTighteningForTruncation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsDefaultTighteningForTruncation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.11"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"allowsDefaultTighteningForTruncation","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"allowsDefaultTighteningForTruncation"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTextField"]]},"path":"/hierarchy","op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Configuring Line Wrapping","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextField/lineBreakStrategy","doc://com.apple.appkit/documentation/AppKit/NSTextField/maximumNumberOfLines"],"generated":true,"anchor":"Configuring-Line-Wrapping"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"allowsDefaultTighteningForTruncation","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1lineBreakStrategy/title","value":"lineBreakStrategy","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1lineBreakStrategy/fragments","value":[{"kind":"identifier","text":"lineBreakStrategy"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/title","value":"NSTextField","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/fragments","value":[{"kind":"identifier","text":"NSTextField"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/navigatorTitle","value":[{"text":"NSTextField","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1maximumNumberOfLines/title","value":"maximumNumberOfLines","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1maximumNumberOfLines/fragments","value":[{"kind":"identifier","text":"maximumNumberOfLines"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1allowsDefaultTighteningForTruncation/title","value":"allowsDefaultTighteningForTruncation","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1allowsDefaultTighteningForTruncation/fragments","value":[{"text":"allowsDefaultTighteningForTruncation","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}