{"variants":[{"paths":["/documentation/appkit/nstextfield/bezelstyle-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nstextfield/bezelstyle-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSTextField/bezelStyle-swift.property","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bezelStyle"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTextField","text":"NSTextField"},{"kind":"text","text":"."},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField/BezelStyle-swift.enum","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextFieldBezelStyle","text":"BezelStyle"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"inlineContent":[{"text":"To enable a bezel for a text field, set ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField/isBezeled","type":"reference"},{"text":" to ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference"},{"text":", then set the bezel style. See ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField/BezelStyle-swift.enum","type":"reference","isActive":true},{"text":" for available bezel styles.","type":"text"}],"type":"paragraph"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"When you set this property to ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField/BezelStyle-swift.enum/roundedBezel","type":"reference"},{"text":", the text field doesn’t wrap the text. It displays using a single line.","type":"text"}],"type":"paragraph"}],"name":"Note","type":"aside","style":"note"}]}],"kind":"symbol","seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextField/backgroundColor","doc://com.apple.appkit/documentation/AppKit/NSTextField/drawsBackground","doc://com.apple.appkit/documentation/AppKit/NSTextField/isBezeled","doc://com.apple.appkit/documentation/AppKit/NSTextField/BezelStyle-swift.enum"],"title":"Controlling the Background","anchor":"Controlling-the-Background"}],"metadata":{"title":"bezelStyle","role":"symbol","platforms":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bezelStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTextField","text":"NSTextField"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextFieldBezelStyle","text":"BezelStyle"}],"modules":[{"name":"AppKit"}],"externalID":"c:objc(cs)NSTextField(py)bezelStyle","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"bezelStyle"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTextField"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The text field’s bezel style, square or rounded."}],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSTextField/backgroundColor":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSColor","preciseIdentifier":"c:objc(cs)NSColor"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"backgroundColor"}],"role":"symbol","title":"backgroundColor","abstract":[{"text":"The color of the background the text field’s cell draws behind the text.","type":"text"}],"url":"/documentation/appkit/nstextfield/backgroundcolor","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField/backgroundColor"},"doc://com.apple.appkit/documentation/AppKit/NSTextField/BezelStyle-swift.enum/roundedBezel":{"type":"topic","navigatorTitle":[{"text":"NSTextFieldRoundedBezel","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField/BezelStyle-swift.enum/roundedBezel","url":"/documentation/appkit/nstextfield/bezelstyle-swift.enum/roundedbezel","abstract":[{"text":"A style that draws a bezel with rounded corners around a single-line text field.","type":"text"}],"title":"NSTextField.BezelStyle.roundedBezel","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"roundedBezel","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTextField/BezelStyle-swift.enum":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField/BezelStyle-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BezelStyle"}],"type":"topic","abstract":[{"type":"text","text":"The style of bezel the text field displays."}],"url":"/documentation/appkit/nstextfield/bezelstyle-swift.enum","title":"NSTextField.BezelStyle","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"BezelStyle","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSTextField/bezelStyle-swift.property":{"navigatorTitle":[{"kind":"identifier","text":"bezelStyle"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bezelStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTextField","text":"NSTextField"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextFieldBezelStyle","text":"BezelStyle"}],"url":"/documentation/appkit/nstextfield/bezelstyle-swift.property","title":"bezelStyle","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField/bezelStyle-swift.property","role":"symbol","abstract":[{"type":"text","text":"The text field’s bezel style, square or rounded."}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSTextField":{"title":"NSTextField","navigatorTitle":[{"text":"NSTextField","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField","role":"symbol","url":"/documentation/appkit/nstextfield","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTextField","kind":"identifier"}],"abstract":[{"text":"Text the user can select or edit to send an action message to a target when the user presses the Return key.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSTextField/drawsBackground":{"navigatorTitle":[{"text":"drawsBackground","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"drawsBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"/documentation/appkit/nstextfield/drawsbackground","title":"drawsBackground","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField/drawsBackground","role":"symbol","abstract":[{"type":"text","text":"A Boolean value that controls whether the text field’s cell draws a background color behind the text."}]},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.appkit/documentation/AppKit/NSTextField/isBezeled":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField/isBezeled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isBezeled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[{"type":"text","text":"A Boolean value that controls whether the text field draws a bezeled background around its contents."}],"url":"/documentation/appkit/nstextfield/isbezeled","title":"isBezeled","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bezeled"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"name":"macOS","unavailable":false,"deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"value":"bezelStyle","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"bezelStyle"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSTextField"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSTextField/backgroundColor","doc://com.apple.appkit/documentation/AppKit/NSTextField/drawsBackground","doc://com.apple.appkit/documentation/AppKit/NSTextField/isBezeled","doc://com.apple.appkit/documentation/AppKit/NSTextField/BezelStyle-swift.enum"],"anchor":"Controlling-the-Background","title":"Controlling the Background","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSTextFieldBezelStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextFieldBezelStyle","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTextField/BezelStyle-swift.enum"},{"text":" ","kind":"text"},{"text":"bezelStyle","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1backgroundColor/title","value":"backgroundColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1backgroundColor/fragments","value":[{"kind":"identifier","text":"backgroundColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1BezelStyle-swift.enum~1roundedBezel/title","value":"NSTextFieldRoundedBezel"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1BezelStyle-swift.enum~1roundedBezel/fragments","value":[{"kind":"identifier","text":"NSTextFieldRoundedBezel"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1BezelStyle-swift.enum/title","value":"NSTextFieldBezelStyle"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1BezelStyle-swift.enum/fragments","value":[{"kind":"identifier","text":"NSTextFieldBezelStyle"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1BezelStyle-swift.enum/navigatorTitle","value":[{"text":"NSTextFieldBezelStyle","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1bezelStyle-swift.property/title","value":"bezelStyle"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1bezelStyle-swift.property/fragments","value":[{"text":"bezelStyle","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/title","value":"NSTextField"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/fragments","op":"replace","value":[{"kind":"identifier","text":"NSTextField"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSTextField"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1drawsBackground/title","op":"replace","value":"drawsBackground"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1drawsBackground/fragments","op":"replace","value":[{"kind":"identifier","text":"drawsBackground"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1isBezeled/title","op":"replace","value":"bezeled"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextField~1isBezeled/fragments","op":"replace","value":[{"text":"bezeled","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}