{
  "abstract": [
    {
      "text": "The identifier for the domain managed by the current file provider.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileproviderui/documentation/FileProviderUI",
        "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionContext"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionContext/domainIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)FPUIActionExtensionContext(py)domainIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "domainIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSFileProviderDomainIdentifier",
        "text": "NSFileProviderDomainIdentifier"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "File Provider UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "domainIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "domainIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "domainIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSFileProviderDomainIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSFileProviderDomainIdentifier",
              "text": "NSFileProviderDomainIdentifier"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/FileProvider/NSFileProviderDomainIdentifier": {
      "abstract": [
        {
          "text": "A unique identifier for a file provider’s domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderDomainIdentifier"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/FileProvider/NSFileProviderDomainIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFileProviderDomainIdentifier",
      "type": "topic",
      "url": "/documentation/FileProvider/NSFileProviderDomainIdentifier"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI": {
      "abstract": [
        {
          "text": "Add actions to the document browser’s context menu.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider UI",
      "type": "topic",
      "url": "/documentation/fileproviderui"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionContext": {
      "abstract": [
        {
          "text": "An extension context provided to File Provider UI extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FPUIActionExtensionContext"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FPUIActionExtensionContext"
        }
      ],
      "role": "symbol",
      "title": "FPUIActionExtensionContext",
      "type": "topic",
      "url": "/documentation/fileproviderui/fpuiactionextensioncontext"
    },
    "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionContext/domainIdentifier": {
      "abstract": [
        {
          "text": "The identifier for the domain managed by the current file provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "domainIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFileProviderDomainIdentifier",
          "text": "NSFileProviderDomainIdentifier"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionContext/domainIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "domainIdentifier"
        }
      ],
      "role": "symbol",
      "title": "domainIdentifier",
      "type": "topic",
      "url": "/documentation/fileproviderui/fpuiactionextensioncontext/domainidentifier"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSFileProviderDomainIdentifier": {
      "abstract": [
        {
          "text": "A unique identifier for a file provider’s domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderDomainIdentifier"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSFileProviderDomainIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFileProviderDomainIdentifier",
      "type": "topic",
      "url": "/documentation/FileProvider/NSFileProviderDomainIdentifier"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identifying-the-Domain",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/FileProvider/NSFileProviderDomainIdentifier"
      ],
      "title": "Identifying the Domain"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "domainIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "domainIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.fileproviderui/documentation/FileProviderUI",
                "doc://com.apple.fileproviderui/documentation/FileProviderUI/FPUIActionExtensionContext"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Identifying-the-Domain",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/FileProvider/NSFileProviderDomainIdentifier"
              ],
              "title": "Identifying the Domain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSFileProviderDomainIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSFileProviderDomainIdentifier",
                    "text": "NSFileProviderDomainIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "domainIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionContext~1domainIdentifier/title",
          "value": "domainIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionContext~1domainIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "domainIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionContext/title",
          "value": "FPUIActionExtensionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FPUIActionExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileproviderui~1documentation~1FileProviderUI~1FPUIActionExtensionContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FPUIActionExtensionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1FileProvider~1NSFileProviderDomainIdentifier/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "NSFileProviderDomainIdentifier"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSFileProviderDomainIdentifier/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "NSFileProviderDomainIdentifier"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileproviderui/fpuiactionextensioncontext/domainidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileproviderui/fpuiactionextensioncontext/domainidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
