{
  "abstract": [
    {
      "text": "The connection attempt timed out.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/timedOut"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MCErrorCode@MCErrorTimedOut",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "timedOut"
      }
    ],
    "modules": [
      {
        "name": "Multipeer Connectivity"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MCErrorTimedOut"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MCError.Code.timedOut"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "timedOut"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity": {
      "abstract": [
        {
          "text": "Support peer-to-peer connectivity and the discovery of nearby devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity",
      "kind": "symbol",
      "role": "collection",
      "title": "Multipeer Connectivity",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MCError"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MCError"
        }
      ],
      "role": "symbol",
      "title": "MCError",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcerror"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code": {
      "abstract": [
        {
          "text": "Error codes found in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCErrorDomain",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " error domain ",
          "type": "text"
        },
        {
          "code": "NSError",
          "type": "codeVoice"
        },
        {
          "text": " objects returned by methods in the Multipeer Connectivity framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MCError.Code",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcerror/code"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/cancelled": {
      "abstract": [
        {
          "text": "The operation was cancelled by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MCErrorCancelled"
        }
      ],
      "role": "symbol",
      "title": "MCError.Code.cancelled",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcerror/code/cancelled"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/invalidParameter": {
      "abstract": [
        {
          "text": "Your app passed an invalid value as a parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameter"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/invalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MCErrorInvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "MCError.Code.invalidParameter",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcerror/code/invalidparameter"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/notConnected": {
      "abstract": [
        {
          "text": "Your app attempted to send data to a peer that is not connected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notConnected"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/notConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MCErrorNotConnected"
        }
      ],
      "role": "symbol",
      "title": "MCError.Code.notConnected",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcerror/code/notconnected"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/timedOut": {
      "abstract": [
        {
          "text": "The connection attempt timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timedOut"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/timedOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MCErrorTimedOut"
        }
      ],
      "role": "symbol",
      "title": "MCError.Code.timedOut",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcerror/code/timedout"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unavailable": {
      "abstract": [
        {
          "text": "Multipeer connectivity is currently unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unavailable"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MCErrorUnavailable"
        }
      ],
      "role": "symbol",
      "title": "MCError.Code.unavailable",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcerror/code/unavailable"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unknown": {
      "abstract": [
        {
          "text": "An unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MCErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "MCError.Code.unknown",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcerror/code/unknown"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unsupported": {
      "abstract": [
        {
          "text": "The operation is unsupported. For example, this error is returned if you call ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCSession/sendResource(at:withName:toPeer:withCompletionHandler:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " with a URL that is neither a local file nor a web URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MCErrorUnsupported"
        }
      ],
      "role": "symbol",
      "title": "MCError.Code.unsupported",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcerror/code/unsupported"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCErrorDomain": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "NSError",
          "type": "codeVoice"
        },
        {
          "text": " domain constant. If the ",
          "type": "text"
        },
        {
          "code": "domain",
          "type": "codeVoice"
        },
        {
          "text": " value for an ",
          "type": "text"
        },
        {
          "code": "NSError",
          "type": "codeVoice"
        },
        {
          "text": " object is equal to ",
          "type": "text"
        },
        {
          "code": "MCErrorDomain",
          "type": "codeVoice"
        },
        {
          "text": ", then the error was produced by the Multipeer Connectivity framework itself, as opposed to a lower-level framework on which it depends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MCErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MCErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "MCErrorDomain",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcerrordomain"
    },
    "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCSession/sendResource(at:withName:toPeer:withCompletionHandler:)": {
      "abstract": [
        {
          "text": "Sends the contents of a URL to a peer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendResource"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toPeer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MCPeerID",
          "text": "MCPeerID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withCompletionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSProgress",
          "text": "Progress"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCSession/sendResource(at:withName:toPeer:withCompletionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendResourceAtURL:withName:toPeer:withCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "sendResource(at:withName:toPeer:withCompletionHandler:)",
      "type": "topic",
      "url": "/documentation/multipeerconnectivity/mcsession/sendresource(at:withname:topeer:withcompletionhandler:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unknown",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/notConnected",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/invalidParameter",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unsupported",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/cancelled",
        "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unavailable"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MCErrorTimedOut"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCErrorTimedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity",
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unknown",
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/notConnected",
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/invalidParameter",
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unsupported",
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/cancelled",
                "doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unavailable"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MCErrorTimedOut"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1unknown/title",
          "value": "MCErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCSession~1sendResource(at:withName:toPeer:withCompletionHandler:)/title",
          "value": "sendResourceAtURL:withName:toPeer:withCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCSession~1sendResource(at:withName:toPeer:withCompletionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sendResourceAtURL:withName:toPeer:withCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1notConnected/title",
          "value": "MCErrorNotConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1notConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCErrorNotConnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCErrorDomain/title",
          "value": "MCErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1timedOut/title",
          "value": "MCErrorTimedOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1timedOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCErrorTimedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1unsupported/title",
          "value": "MCErrorUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1unsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCErrorUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1unavailable/title",
          "value": "MCErrorUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1unavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCErrorUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code/title",
          "value": "MCErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MCErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1invalidParameter/title",
          "value": "MCErrorInvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1invalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCErrorInvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1cancelled/title",
          "value": "MCErrorCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MCErrorCancelled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/multipeerconnectivity/mcerror/code/timedout"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/multipeerconnectivity/mcerror/code/timedout"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
