{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unavailable"},"abstract":[{"text":"Multipeer connectivity is currently unavailable.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity","doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError","doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"platforms":[{"beta":false,"deprecated":false,"introducedAt":"7.0","name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"7.0","name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"10.10","name":"macOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"10.0","name":"tvOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"1.0","name":"visionOS","unavailable":false}],"navigatorTitle":[{"kind":"identifier","text":"MCErrorUnavailable"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unavailable"}],"externalID":"c:@E@MCErrorCode@MCErrorUnavailable","symbolKind":"case","role":"symbol","title":"MCError.Code.unavailable","modules":[{"name":"Multipeer Connectivity"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unavailable","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"}],"seeAlsoSections":[{"title":"Constants","identifiers":["doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unknown","doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/notConnected","doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/invalidParameter","doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unsupported","doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/timedOut","doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/cancelled"],"generated":true,"anchor":"Constants"}],"variants":[{"paths":["/documentation/multipeerconnectivity/mcerror/code/unavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/multipeerconnectivity/mcerror/code/unavailable"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/invalidParameter":{"url":"/documentation/multipeerconnectivity/mcerror/code/invalidparameter","abstract":[{"text":"Your app passed an invalid value as a parameter.","type":"text"}],"navigatorTitle":[{"text":"MCErrorInvalidParameter","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidParameter","kind":"identifier"}],"type":"topic","title":"MCError.Code.invalidParameter","identifier":"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/invalidParameter"},"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/timedOut":{"title":"MCError.Code.timedOut","abstract":[{"text":"The connection attempt timed out.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timedOut","kind":"identifier"}],"url":"/documentation/multipeerconnectivity/mcerror/code/timedout","navigatorTitle":[{"text":"MCErrorTimedOut","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/timedOut","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","title":"Technologies","role":"overview","abstract":[{"text":"","type":"text"}],"url":"/documentation/technologies"},"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unsupported":{"kind":"symbol","navigatorTitle":[{"text":"MCErrorUnsupported","kind":"identifier"}],"identifier":"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unsupported","abstract":[{"type":"text","text":"The operation is unsupported. For example, this error is returned if you call "},{"type":"reference","identifier":"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCSession/sendResource(at:withName:toPeer:withCompletionHandler:)","isActive":true},{"type":"text","text":" with a URL that is neither a local file nor a web URL."}],"url":"/documentation/multipeerconnectivity/mcerror/code/unsupported","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unsupported","kind":"identifier"}],"title":"MCError.Code.unsupported"},"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/cancelled":{"title":"MCError.Code.cancelled","type":"topic","identifier":"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/cancelled","navigatorTitle":[{"kind":"identifier","text":"MCErrorCancelled"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"abstract":[{"text":"The operation was cancelled by the user.","type":"text"}],"url":"/documentation/multipeerconnectivity/mcerror/code/cancelled","role":"symbol"},"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unknown":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCErrorUnknown"}],"identifier":"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unknown","abstract":[{"text":"An unknown error occurred.","type":"text"}],"url":"/documentation/multipeerconnectivity/mcerror/code/unknown","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"title":"MCError.Code.unknown"},"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity":{"type":"topic","identifier":"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity","url":"/documentation/multipeerconnectivity","kind":"symbol","abstract":[{"text":"Support peer-to-peer connectivity and the discovery of nearby devices.","type":"text"}],"title":"Multipeer Connectivity","role":"collection"},"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError":{"kind":"symbol","abstract":[],"url":"/documentation/multipeerconnectivity/mcerror","title":"MCError","type":"topic","identifier":"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError","navigatorTitle":[{"kind":"identifier","text":"MCError"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCError"}],"role":"symbol"},"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unavailable":{"url":"/documentation/multipeerconnectivity/mcerror/code/unavailable","abstract":[{"text":"Multipeer connectivity is currently unavailable.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MCErrorUnavailable"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unavailable"}],"type":"topic","title":"MCError.Code.unavailable","identifier":"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unavailable"},"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code":{"title":"MCError.Code","type":"topic","identifier":"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"abstract":[{"text":"Error codes found in ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCErrorDomain"},{"text":" error domain ","type":"text"},{"code":"NSError","type":"codeVoice"},{"type":"text","text":" objects returned by methods in the Multipeer Connectivity framework."}],"url":"/documentation/multipeerconnectivity/mcerror/code","role":"symbol"},"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/notConnected":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MCErrorNotConnected"}],"identifier":"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/notConnected","abstract":[{"type":"text","text":"Your app attempted to send data to a peer that is not connected."}],"url":"/documentation/multipeerconnectivity/mcerror/code/notconnected","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notConnected"}],"title":"MCError.Code.notConnected"},"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCSession/sendResource(at:withName:toPeer:withCompletionHandler:)":{"navigatorTitle":[{"text":"sendResourceAtURL:withName:toPeer:withCompletionHandler:","kind":"identifier"}],"abstract":[{"type":"text","text":"Sends the contents of a URL to a peer."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendResource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"toPeer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MCPeerID","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MCPeerID"},{"text":", ","kind":"text"},{"text":"withCompletionHandler","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?) -> ","kind":"text"},{"text":"Progress","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSProgress"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","title":"sendResource(at:withName:toPeer:withCompletionHandler:)","identifier":"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCSession/sendResource(at:withName:toPeer:withCompletionHandler:)","url":"/documentation/multipeerconnectivity/mcsession/sendresource(at:withname:topeer:withcompletionhandler:)","kind":"symbol"},"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCErrorDomain":{"url":"/documentation/multipeerconnectivity/mcerrordomain","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"NSError"},{"type":"text","text":" domain constant. If the "},{"type":"codeVoice","code":"domain"},{"type":"text","text":" value for an "},{"type":"codeVoice","code":"NSError"},{"type":"text","text":" object is equal to "},{"type":"codeVoice","code":"MCErrorDomain"},{"type":"text","text":", then the error was produced by the Multipeer Connectivity framework itself, as opposed to a lower-level framework on which it depends."}],"navigatorTitle":[{"kind":"identifier","text":"MCErrorDomain"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"MCErrorDomain"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","title":"MCErrorDomain","identifier":"doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCErrorDomain"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"7.0","deprecated":false,"name":"iOS","beta":false,"unavailable":false},{"introducedAt":"7.0","deprecated":false,"name":"iPadOS","beta":false,"unavailable":false},{"introducedAt":"13.1","deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false},{"introducedAt":"10.10","deprecated":false,"name":"macOS","beta":false,"unavailable":false},{"introducedAt":"10.0","deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"beta":false,"unavailable":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"/metadata/title","value":"MCErrorUnavailable"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"MCErrorUnavailable","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity","doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code"]]}},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unknown","doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/notConnected","doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/invalidParameter","doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/unsupported","doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/timedOut","doc://com.apple.multipeerconnectivity/documentation/MultipeerConnectivity/MCError/Code/cancelled"],"generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"MCErrorUnavailable","kind":"identifier"}],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1invalidParameter/title","value":"MCErrorInvalidParameter","op":"replace"},{"path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1invalidParameter/fragments","value":[{"text":"MCErrorInvalidParameter","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1timedOut/title","value":"MCErrorTimedOut","op":"replace"},{"path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1timedOut/fragments","value":[{"kind":"identifier","text":"MCErrorTimedOut"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1unsupported/title","value":"MCErrorUnsupported","op":"replace"},{"path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1unsupported/fragments","value":[{"text":"MCErrorUnsupported","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1cancelled/title","value":"MCErrorCancelled","op":"replace"},{"path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1cancelled/fragments","value":[{"kind":"identifier","text":"MCErrorCancelled"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1unknown/title","value":"MCErrorUnknown","op":"replace"},{"path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1unknown/fragments","value":[{"kind":"identifier","text":"MCErrorUnknown"}],"op":"replace"},{"value":"MCErrorUnavailable","path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1unavailable/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCErrorUnavailable"}],"path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1unavailable/fragments","op":"replace"},{"value":"MCErrorCode","path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code/title","op":"replace"},{"value":[{"text":"MCErrorCode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MCErrorCode"}],"path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code/navigatorTitle","op":"replace"},{"value":"MCErrorNotConnected","path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1notConnected/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCErrorNotConnected"}],"path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCError~1Code~1notConnected/fragments","op":"replace"},{"value":"sendResourceAtURL:withName:toPeer:withCompletionHandler:","path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCSession~1sendResource(at:withName:toPeer:withCompletionHandler:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendResourceAtURL:withName:toPeer:withCompletionHandler:"}],"path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCSession~1sendResource(at:withName:toPeer:withCompletionHandler:)/fragments","op":"replace"},{"value":"MCErrorDomain","path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCErrorDomain/title","op":"replace"},{"value":[{"kind":"identifier","text":"MCErrorDomain"}],"path":"/references/doc:~1~1com.apple.multipeerconnectivity~1documentation~1MultipeerConnectivity~1MCErrorDomain/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}