{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget/setAttributedStringValue(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PDFAnnotationTextWidget(im)setAttributedStringValue:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setAttributedStringValue"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSAttributedString",
        "text": "NSAttributedString"
      },
      {
        "kind": "text",
        "text": "!)"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setAttributedStringValue:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setAttributedStringValue(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setAttributedStringValue"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "value"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSAttributedString",
              "text": "NSAttributedString"
            },
            {
              "kind": "text",
              "text": "!)"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "PDFAnnotationTextWidget",
          "type": "codeVoice"
        },
        {
          "text": " object allows you to manage the appearance and content of text fields.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFAnnotationTextWidget"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFAnnotationTextWidget"
        }
      ],
      "role": "symbol",
      "title": "PDFAnnotationTextWidget",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationtextwidget"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget/attributedStringValue()": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedStringValue"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget/attributedStringValue()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributedStringValue"
        }
      ],
      "role": "symbol",
      "title": "attributedStringValue()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationtextwidget/attributedstringvalue()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget/isMultiline()": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isMultiline"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget/isMultiline()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isMultiline"
        }
      ],
      "role": "symbol",
      "title": "isMultiline()",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationtextwidget/ismultiline()"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget/setAttributedStringValue(_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAttributedStringValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget/setAttributedStringValue(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAttributedStringValue:"
        }
      ],
      "role": "symbol",
      "title": "setAttributedStringValue(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationtextwidget/setattributedstringvalue(_:)"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget/setIsMultiline(_:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setIsMultiline"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget/setIsMultiline(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setIsMultiline:"
        }
      ],
      "role": "symbol",
      "title": "setIsMultiline(_:)",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfannotationtextwidget/setismultiline(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString": {
      "abstract": [
        {
          "text": "A string of text that manages data, layout, and stylistic information for ranges of characters to support rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedString",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget/attributedStringValue()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget/isMultiline()",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget/setIsMultiline(_:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.12",
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setAttributedStringValue:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setAttributedStringValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget/attributedStringValue()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget/isMultiline()",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFAnnotationTextWidget/setIsMultiline(_:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setAttributedStringValue:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSAttributedString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSAttributedString",
                    "text": "NSAttributedString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "value"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget~1attributedStringValue()/title",
          "value": "attributedStringValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget~1attributedStringValue()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "attributedStringValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget~1setAttributedStringValue(_:)/title",
          "value": "setAttributedStringValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget~1setAttributedStringValue(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setAttributedStringValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget/title",
          "value": "PDFAnnotationTextWidget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationTextWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFAnnotationTextWidget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget~1setIsMultiline(_:)/title",
          "value": "setIsMultiline:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget~1setIsMultiline(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setIsMultiline:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget~1isMultiline()/title",
          "value": "isMultiline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFAnnotationTextWidget~1isMultiline()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isMultiline"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfannotationtextwidget/setattributedstringvalue(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfannotationtextwidget/setattributedstringvalue(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
