{
  "abstract": [
    {
      "text": "Disables the scene reconstruction feature.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARConfiguration/SceneReconstruction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARSceneReconstruction/ARSceneReconstructionNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ARSceneReconstruction@ARSceneReconstructionNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "ARSceneReconstructionNone"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARSceneReconstructionNone"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "ARSceneReconstructionNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "ARSceneReconstructionNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARConfiguration/SceneReconstruction": {
      "abstract": [
        {
          "text": "Options that enable ARKit to detect the shape of the physical environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SceneReconstruction"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARConfiguration/SceneReconstruction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SceneReconstruction"
        }
      ],
      "role": "symbol",
      "title": "ARConfiguration.SceneReconstruction",
      "type": "topic",
      "url": "/documentation/arkit/arconfiguration/scenereconstruction"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARConfiguration/SceneReconstruction/mesh": {
      "abstract": [
        {
          "text": "A polygonal mesh approximation of the physical environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mesh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARConfiguration",
          "text": "ARConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARSceneReconstruction",
          "text": "SceneReconstruction"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARConfiguration/SceneReconstruction/mesh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSceneReconstructionMesh"
        }
      ],
      "role": "symbol",
      "title": "mesh",
      "type": "topic",
      "url": "/documentation/arkit/arconfiguration/scenereconstruction/mesh"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARConfiguration/SceneReconstruction/meshWithClassification": {
      "abstract": [
        {
          "text": "An approximate shape of the physical environment, including classification of the real-world objects within it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "meshWithClassification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARConfiguration",
          "text": "ARConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARSceneReconstruction",
          "text": "SceneReconstruction"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARConfiguration/SceneReconstruction/meshWithClassification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSceneReconstructionMeshWithClassification"
        }
      ],
      "role": "symbol",
      "title": "meshWithClassification",
      "type": "topic",
      "url": "/documentation/arkit/arconfiguration/scenereconstruction/meshwithclassification"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSceneReconstruction/ARSceneReconstructionNone": {
      "abstract": [
        {
          "text": "Disables the scene reconstruction feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ARSceneReconstructionNone"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSceneReconstruction/ARSceneReconstructionNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARSceneReconstructionNone",
      "type": "topic",
      "url": "/documentation/arkit/arscenereconstruction/arscenereconstructionnone"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Modeling-the-Environment",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARConfiguration/SceneReconstruction/mesh",
        "doc://com.apple.arkit/documentation/ARKit/ARConfiguration/SceneReconstruction/meshWithClassification"
      ],
      "title": "Modeling the Environment"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARConfiguration~1SceneReconstruction~1meshWithClassification/title",
          "value": "ARSceneReconstructionMeshWithClassification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARConfiguration~1SceneReconstruction~1meshWithClassification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSceneReconstructionMeshWithClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARConfiguration~1SceneReconstruction/title",
          "value": "ARSceneReconstruction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARConfiguration~1SceneReconstruction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSceneReconstruction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARConfiguration~1SceneReconstruction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSceneReconstruction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARConfiguration~1SceneReconstruction~1mesh/title",
          "value": "ARSceneReconstructionMesh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARConfiguration~1SceneReconstruction~1mesh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSceneReconstructionMesh"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arscenereconstruction/arscenereconstructionnone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
