{
  "abstract": [
    {
      "text": "The size and format constraints for an image feature.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML",
        "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription/imageConstraint"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreML",
    "externalID": "c:objc(cs)MLFeatureDescription(py)imageConstraint",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "imageConstraint"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MLImageConstraint",
        "text": "MLImageConstraint"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "imageConstraint"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "imageConstraint"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "imageConstraint"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageConstraint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MLImageConstraint",
              "text": "MLImageConstraint"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLDictionaryConstraint": {
      "abstract": [
        {
          "text": "The constraint on the keys for a dictionary feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLDictionaryConstraint"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLDictionaryConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLDictionaryConstraint"
        }
      ],
      "role": "symbol",
      "title": "MLDictionaryConstraint",
      "type": "topic",
      "url": "/documentation/coreml/mldictionaryconstraint"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription": {
      "abstract": [
        {
          "text": "The name, type, and constraints of an input or output feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLFeatureDescription"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLFeatureDescription"
        }
      ],
      "role": "symbol",
      "title": "MLFeatureDescription",
      "type": "topic",
      "url": "/documentation/coreml/mlfeaturedescription"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription/dictionaryConstraint": {
      "abstract": [
        {
          "text": "The constraint for a dictionary feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dictionaryConstraint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLDictionaryConstraint",
          "text": "MLDictionaryConstraint"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription/dictionaryConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dictionaryConstraint"
        }
      ],
      "role": "symbol",
      "title": "dictionaryConstraint",
      "type": "topic",
      "url": "/documentation/coreml/mlfeaturedescription/dictionaryconstraint"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription/imageConstraint": {
      "abstract": [
        {
          "text": "The size and format constraints for an image feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageConstraint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLImageConstraint",
          "text": "MLImageConstraint"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription/imageConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageConstraint"
        }
      ],
      "role": "symbol",
      "title": "imageConstraint",
      "type": "topic",
      "url": "/documentation/coreml/mlfeaturedescription/imageconstraint"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription/multiArrayConstraint": {
      "abstract": [
        {
          "text": "The constraints on a multidimensional array feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiArrayConstraint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLMultiArrayConstraint",
          "text": "MLMultiArrayConstraint"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription/multiArrayConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "multiArrayConstraint"
        }
      ],
      "role": "symbol",
      "title": "multiArrayConstraint",
      "type": "topic",
      "url": "/documentation/coreml/mlfeaturedescription/multiarrayconstraint"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription/sequenceConstraint": {
      "abstract": [
        {
          "text": "The constraints for a sequence feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sequenceConstraint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLSequenceConstraint",
          "text": "MLSequenceConstraint"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription/sequenceConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sequenceConstraint"
        }
      ],
      "role": "symbol",
      "title": "sequenceConstraint",
      "type": "topic",
      "url": "/documentation/coreml/mlfeaturedescription/sequenceconstraint"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLImageConstraint": {
      "abstract": [
        {
          "text": "The width, height, and pixel format constraints of an image feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLImageConstraint"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLImageConstraint"
        }
      ],
      "role": "symbol",
      "title": "MLImageConstraint",
      "type": "topic",
      "url": "/documentation/coreml/mlimageconstraint"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayConstraint": {
      "abstract": [
        {
          "text": "The shape and data type constraints for a multidimensional array feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLMultiArrayConstraint"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLMultiArrayConstraint"
        }
      ],
      "role": "symbol",
      "title": "MLMultiArrayConstraint",
      "type": "topic",
      "url": "/documentation/coreml/mlmultiarrayconstraint"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLSequenceConstraint": {
      "abstract": [
        {
          "text": "The constraints for a sequence feature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLSequenceConstraint"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLSequenceConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLSequenceConstraint"
        }
      ],
      "role": "symbol",
      "title": "MLSequenceConstraint",
      "type": "topic",
      "url": "/documentation/coreml/mlsequenceconstraint"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Feature-Constraints",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLImageConstraint",
        "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription/dictionaryConstraint",
        "doc://com.apple.coreml/documentation/CoreML/MLDictionaryConstraint",
        "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription/multiArrayConstraint",
        "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayConstraint",
        "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription/sequenceConstraint",
        "doc://com.apple.coreml/documentation/CoreML/MLSequenceConstraint"
      ],
      "title": "Accessing Feature Constraints"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "imageConstraint"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreml/documentation/CoreML",
                "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Feature-Constraints",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLImageConstraint",
                "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription/dictionaryConstraint",
                "doc://com.apple.coreml/documentation/CoreML/MLDictionaryConstraint",
                "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription/multiArrayConstraint",
                "doc://com.apple.coreml/documentation/CoreML/MLMultiArrayConstraint",
                "doc://com.apple.coreml/documentation/CoreML/MLFeatureDescription/sequenceConstraint",
                "doc://com.apple.coreml/documentation/CoreML/MLSequenceConstraint"
              ],
              "title": "Accessing Feature Constraints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.coreml/documentation/CoreML/MLImageConstraint",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MLImageConstraint",
                    "text": "MLImageConstraint"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "imageConstraint"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageConstraint/title",
          "value": "MLImageConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLImageConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLImageConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLImageConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLSequenceConstraint/title",
          "value": "MLSequenceConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLSequenceConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLSequenceConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLSequenceConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLSequenceConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureDescription/title",
          "value": "MLFeatureDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLDictionaryConstraint/title",
          "value": "MLDictionaryConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLDictionaryConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLDictionaryConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLDictionaryConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLDictionaryConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureDescription~1imageConstraint/title",
          "value": "imageConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureDescription~1imageConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayConstraint/title",
          "value": "MLMultiArrayConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArrayConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLMultiArrayConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLMultiArrayConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureDescription~1sequenceConstraint/title",
          "value": "sequenceConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureDescription~1sequenceConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sequenceConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureDescription~1multiArrayConstraint/title",
          "value": "multiArrayConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureDescription~1multiArrayConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "multiArrayConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureDescription~1dictionaryConstraint/title",
          "value": "dictionaryConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureDescription~1dictionaryConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dictionaryConstraint"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlfeaturedescription/imageconstraint"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreml/mlfeaturedescription/imageconstraint"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
