{"abstract":[{"text":"Deletes content from the insertion point to the end of the current line.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteToEndOfLine","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToEndOfLine(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteBackward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteBackwardByDecomposingPreviousCharacter(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteForward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToBeginningOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToBeginningOfParagraph(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToEndOfParagraph(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteWordBackward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteWordForward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/yank(_:)"],"generated":true,"title":"Deleting Content","anchor":"Deleting-Content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["/documentation/appkit/nsstandardkeybindingresponding/deletetoendofline(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsstandardkeybindingresponding/deletetoendofline(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"symbolKind":"method","role":"symbol","externalID":"c:objc(pl)NSStandardKeyBindingResponding(im)deleteToEndOfLine:","platforms":[{"beta":false,"deprecated":false,"name":"macOS","unavailable":false}],"title":"deleteToEndOfLine(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteToEndOfLine"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"modules":[{"name":"AppKit"}],"navigatorTitle":[{"kind":"identifier","text":"deleteToEndOfLine:"}]},"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToEndOfParagraph(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToEndOfParagraph(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/deletetoendofparagraph(_:)","title":"deleteToEndOfParagraph(_:)","abstract":[{"text":"Deletes content from the insertion point to the end of the current paragraph.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"deleteToEndOfParagraph:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteToEndOfParagraph","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}],"kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteWordForward(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteWordForward(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/deletewordforward(_:)","title":"deleteWordForward(_:)","abstract":[],"navigatorTitle":[{"text":"deleteWordForward:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteWordForward"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToBeginningOfLine(_:)":{"kind":"symbol","abstract":[{"text":"Deletes content from the insertion point to the beginning of the current line.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"deleteToBeginningOfLine:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteToBeginningOfLine"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToBeginningOfLine(_:)","title":"deleteToBeginningOfLine(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/deletetobeginningofline(_:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToEndOfLine(_:)":{"kind":"symbol","abstract":[{"type":"text","text":"Deletes content from the insertion point to the end of the current line."}],"navigatorTitle":[{"kind":"identifier","text":"deleteToEndOfLine:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deleteToEndOfLine","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToEndOfLine(_:)","title":"deleteToEndOfLine(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/deletetoendofline(_:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToBeginningOfParagraph(_:)":{"kind":"symbol","abstract":[{"type":"text","text":"Deletes content from the insertion point to the beginning of the current paragraph."}],"navigatorTitle":[{"kind":"identifier","text":"deleteToBeginningOfParagraph:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deleteToBeginningOfParagraph","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToBeginningOfParagraph(_:)","title":"deleteToBeginningOfParagraph(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/deletetobeginningofparagraph(_:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/yank(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/yank(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/yank(_:)","title":"yank(_:)","abstract":[{"text":"Deletes the current selection, placing it in a temporary buffer, such as the Clipboard.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"yank:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"yank"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteWordBackward(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteWordBackward(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/deletewordbackward(_:)","title":"deleteWordBackward(_:)","abstract":[{"text":"Deletes the word preceding the current insertion point.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"deleteWordBackward:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteWordBackward","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}],"kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteBackwardByDecomposingPreviousCharacter(_:)":{"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"deleteBackwardByDecomposingPreviousCharacter:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deleteBackwardByDecomposingPreviousCharacter"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteBackwardByDecomposingPreviousCharacter(_:)","title":"deleteBackwardByDecomposingPreviousCharacter(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/deletebackwardbydecomposingpreviouscharacter(_:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteBackward(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteBackward(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/deletebackward(_:)","title":"deleteBackward(_:)","abstract":[{"text":"Deletes content moving backward from the current insertion point.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"deleteBackward:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteBackward","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}],"kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteForward(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteForward"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"deleteForward:"}],"abstract":[],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteForward(_:)","type":"topic","url":"/documentation/appkit/nsstandardkeybindingresponding/deleteforward(_:)","title":"deleteForward(_:)","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"name":"macOS","deprecated":false,"unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"deleteToEndOfLine:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteToEndOfLine:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"anchor":"Deleting-Content","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteBackward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteBackwardByDecomposingPreviousCharacter(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteForward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToBeginningOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToBeginningOfParagraph(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToEndOfParagraph(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteWordBackward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteWordForward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/yank(_:)"],"title":"Deleting Content"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"deleteToEndOfLine:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"]}]},"path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToEndOfParagraph(_:)/title","value":"deleteToEndOfParagraph:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToEndOfParagraph(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteToEndOfParagraph:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteWordForward(_:)/title","value":"deleteWordForward:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteWordForward(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteWordForward:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToBeginningOfLine(_:)/title","value":"deleteToBeginningOfLine:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToBeginningOfLine(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"deleteToBeginningOfLine:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToEndOfLine(_:)/title","value":"deleteToEndOfLine:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToEndOfLine(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteToEndOfLine:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToBeginningOfParagraph(_:)/title","value":"deleteToBeginningOfParagraph:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToBeginningOfParagraph(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"deleteToBeginningOfParagraph:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1yank(_:)/title","op":"replace","value":"yank:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1yank(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"yank:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title","op":"replace","value":"NSStandardKeyBindingResponding"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments","op":"replace","value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteWordBackward(_:)/title","op":"replace","value":"deleteWordBackward:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteWordBackward(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"deleteWordBackward:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteBackwardByDecomposingPreviousCharacter(_:)/title","op":"replace","value":"deleteBackwardByDecomposingPreviousCharacter:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteBackwardByDecomposingPreviousCharacter(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteBackwardByDecomposingPreviousCharacter:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteBackward(_:)/title","op":"replace","value":"deleteBackward:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteBackward(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteBackward:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteForward(_:)/title","op":"replace","value":"deleteForward:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteForward(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteForward:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}