{"sections":[],"seeAlsoSections":[{"anchor":"Deleting-Content","title":"Deleting Content","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteBackward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteBackwardByDecomposingPreviousCharacter(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToBeginningOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToBeginningOfParagraph(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToEndOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToEndOfParagraph(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteWordBackward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteWordForward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/yank(_:)"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/deleteforward(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/deleteforward(_:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deleteForward"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"deleteForward:","kind":"identifier"}],"externalID":"c:objc(pl)NSStandardKeyBindingResponding(im)deleteForward:","roleHeading":"Instance Method","title":"deleteForward(_:)","modules":[{"name":"AppKit"}],"role":"symbol","platforms":[{"name":"macOS","deprecated":false,"unavailable":false,"beta":false}],"symbolKind":"method"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteForward(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteForward"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteWordBackward(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteWordBackward(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/deletewordbackward(_:)","title":"deleteWordBackward(_:)","abstract":[{"text":"Deletes the word preceding the current insertion point.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"deleteWordBackward:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteWordBackward","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}],"kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToBeginningOfParagraph(_:)":{"kind":"symbol","abstract":[{"type":"text","text":"Deletes content from the insertion point to the beginning of the current paragraph."}],"navigatorTitle":[{"kind":"identifier","text":"deleteToBeginningOfParagraph:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deleteToBeginningOfParagraph","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToBeginningOfParagraph(_:)","title":"deleteToBeginningOfParagraph(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/deletetobeginningofparagraph(_:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToEndOfParagraph(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToEndOfParagraph(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/deletetoendofparagraph(_:)","title":"deleteToEndOfParagraph(_:)","abstract":[{"text":"Deletes content from the insertion point to the end of the current paragraph.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"deleteToEndOfParagraph:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteToEndOfParagraph","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}],"kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToEndOfLine(_:)":{"kind":"symbol","abstract":[{"type":"text","text":"Deletes content from the insertion point to the end of the current line."}],"navigatorTitle":[{"kind":"identifier","text":"deleteToEndOfLine:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deleteToEndOfLine","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToEndOfLine(_:)","title":"deleteToEndOfLine(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/deletetoendofline(_:)","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteWordForward(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteWordForward(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/deletewordforward(_:)","title":"deleteWordForward(_:)","abstract":[],"navigatorTitle":[{"text":"deleteWordForward:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteWordForward"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteBackward(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteBackward(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/deletebackward(_:)","title":"deleteBackward(_:)","abstract":[{"text":"Deletes content moving backward from the current insertion point.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"deleteBackward:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteBackward","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}],"kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteBackwardByDecomposingPreviousCharacter(_:)":{"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"deleteBackwardByDecomposingPreviousCharacter:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deleteBackwardByDecomposingPreviousCharacter"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteBackwardByDecomposingPreviousCharacter(_:)","title":"deleteBackwardByDecomposingPreviousCharacter(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/deletebackwardbydecomposingpreviouscharacter(_:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToBeginningOfLine(_:)":{"kind":"symbol","abstract":[{"text":"Deletes content from the insertion point to the beginning of the current line.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"deleteToBeginningOfLine:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteToBeginningOfLine"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToBeginningOfLine(_:)","title":"deleteToBeginningOfLine(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/deletetobeginningofline(_:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/yank(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/yank(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/yank(_:)","title":"yank(_:)","abstract":[{"text":"Deletes the current selection, placing it in a temporary buffer, such as the Clipboard.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"yank:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"yank"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteForward(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteForward"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"deleteForward:"}],"abstract":[],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteForward(_:)","type":"topic","url":"/documentation/appkit/nsstandardkeybindingresponding/deleteforward(_:)","title":"deleteForward(_:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"deleteForward:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"deleteForward:","kind":"identifier"}]},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"title":"Deleting Content","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteBackward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteBackwardByDecomposingPreviousCharacter(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToBeginningOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToBeginningOfParagraph(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToEndOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToEndOfParagraph(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteWordBackward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteWordForward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/yank(_:)"],"anchor":"Deleting-Content"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"deleteForward:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteWordBackward(_:)/title","value":"deleteWordBackward:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteWordBackward(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"deleteWordBackward:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToBeginningOfParagraph(_:)/title","value":"deleteToBeginningOfParagraph:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToBeginningOfParagraph(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteToBeginningOfParagraph:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToEndOfParagraph(_:)/title","value":"deleteToEndOfParagraph:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToEndOfParagraph(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"deleteToEndOfParagraph:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToEndOfLine(_:)/title","value":"deleteToEndOfLine:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToEndOfLine(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteToEndOfLine:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteWordForward(_:)/title","value":"deleteWordForward:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteWordForward(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteWordForward:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteBackward(_:)/title","value":"deleteBackward:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteBackward(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteBackward:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteBackwardByDecomposingPreviousCharacter(_:)/title","value":"deleteBackwardByDecomposingPreviousCharacter:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteBackwardByDecomposingPreviousCharacter(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteBackwardByDecomposingPreviousCharacter:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title","value":"NSStandardKeyBindingResponding"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments","value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle","value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToBeginningOfLine(_:)/title","value":"deleteToBeginningOfLine:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToBeginningOfLine(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteToBeginningOfLine:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1yank(_:)/title","value":"yank:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1yank(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"yank:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteForward(_:)/title","value":"deleteForward:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteForward(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteForward:"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}