{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertText"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"insertString"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"insertString","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The string to insert in the responder."}]}]}]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertBacktab(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertContainerBreak(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertDoubleQuoteIgnoringSubstitution(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertLineBreak(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertNewline(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertNewlineIgnoringFieldEditor(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertParagraphSeparator(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertSingleQuoteIgnoringSubstitution(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertTab(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertTabIgnoringFieldEditor(_:)"],"anchor":"Inserting-Content","title":"Inserting Content"}],"metadata":{"modules":[{"name":"AppKit"}],"symbolKind":"method","externalID":"c:objc(pl)NSStandardKeyBindingResponding(im)insertText:","roleHeading":"Instance Method","platforms":[{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"navigatorTitle":[{"kind":"identifier","text":"insertText:"}],"title":"insertText(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertText"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}]},"abstract":[{"type":"text","text":"Inserts the text you specify."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertText(_:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/inserttext(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/inserttext(_:)"]}],"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertText(_:)":{"url":"/documentation/appkit/nsstandardkeybindingresponding/inserttext(_:)","kind":"symbol","navigatorTitle":[{"text":"insertText:","kind":"identifier"}],"abstract":[{"text":"Inserts the text you specify.","type":"text"}],"title":"insertText(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertText"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertText(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertDoubleQuoteIgnoringSubstitution(_:)":{"url":"/documentation/appkit/nsstandardkeybindingresponding/insertdoublequoteignoringsubstitution(_:)","kind":"symbol","navigatorTitle":[{"text":"insertDoubleQuoteIgnoringSubstitution:","kind":"identifier"}],"abstract":[{"type":"text","text":"Inserts a double quotation mark without substituting a curly quotation mark."}],"title":"insertDoubleQuoteIgnoringSubstitution(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertDoubleQuoteIgnoringSubstitution"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertDoubleQuoteIgnoringSubstitution(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertLineBreak(_:)":{"navigatorTitle":[{"text":"insertLineBreak:","kind":"identifier"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/insertlinebreak(_:)","role":"symbol","title":"insertLineBreak(_:)","abstract":[{"type":"text","text":"Inserts a line break character."}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertLineBreak(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insertLineBreak","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertNewline(_:)":{"url":"/documentation/appkit/nsstandardkeybindingresponding/insertnewline(_:)","kind":"symbol","navigatorTitle":[{"text":"insertNewline:","kind":"identifier"}],"abstract":[{"type":"text","text":"Inserts a newline character."}],"title":"insertNewline(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insertNewline","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertNewline(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertBacktab(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertBacktab"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"title":"insertBacktab(_:)","type":"topic","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertBacktab(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/insertbacktab(_:)","abstract":[{"text":"Inserts a backtab character.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"insertBacktab:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertTab(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertTab"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"title":"insertTab(_:)","type":"topic","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertTab(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/inserttab(_:)","abstract":[{"type":"text","text":"Inserts a tab character."}],"kind":"symbol","navigatorTitle":[{"text":"insertTab:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertParagraphSeparator(_:)":{"navigatorTitle":[{"text":"insertParagraphSeparator:","kind":"identifier"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/insertparagraphseparator(_:)","role":"symbol","title":"insertParagraphSeparator(_:)","abstract":[{"type":"text","text":"Inserts a paragraph separator."}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertParagraphSeparator(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insertParagraphSeparator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertTabIgnoringFieldEditor(_:)":{"title":"insertTabIgnoringFieldEditor(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insertTabIgnoringFieldEditor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertTabIgnoringFieldEditor(_:)","abstract":[],"url":"/documentation/appkit/nsstandardkeybindingresponding/inserttabignoringfieldeditor(_:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"insertTabIgnoringFieldEditor:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertSingleQuoteIgnoringSubstitution(_:)":{"title":"insertSingleQuoteIgnoringSubstitution(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"insertSingleQuoteIgnoringSubstitution","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertSingleQuoteIgnoringSubstitution(_:)","abstract":[],"url":"/documentation/appkit/nsstandardkeybindingresponding/insertsinglequoteignoringsubstitution(_:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"insertSingleQuoteIgnoringSubstitution:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertNewlineIgnoringFieldEditor(_:)":{"url":"/documentation/appkit/nsstandardkeybindingresponding/insertnewlineignoringfieldeditor(_:)","kind":"symbol","navigatorTitle":[{"text":"insertNewlineIgnoringFieldEditor:","kind":"identifier"}],"abstract":[{"type":"text","text":"Inserts a newline character without invoking the field editor’s normal handling to end editing."}],"title":"insertNewlineIgnoringFieldEditor(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insertNewlineIgnoringFieldEditor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertNewlineIgnoringFieldEditor(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertContainerBreak(_:)":{"title":"insertContainerBreak(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertContainerBreak"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertContainerBreak(_:)","abstract":[{"type":"text","text":"Inserts a container break, such as a new page break."}],"url":"/documentation/appkit/nsstandardkeybindingresponding/insertcontainerbreak(_:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"insertContainerBreak:","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"macOS","deprecated":false,"unavailable":false,"beta":false}],"path":"/metadata/platforms","op":"replace"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"insertText:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"insertText:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"op":"replace","path":"/hierarchy"},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertBacktab(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertContainerBreak(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertDoubleQuoteIgnoringSubstitution(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertLineBreak(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertNewline(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertNewlineIgnoringFieldEditor(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertParagraphSeparator(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertSingleQuoteIgnoringSubstitution(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertTab(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/insertTabIgnoringFieldEditor(_:)"],"anchor":"Inserting-Content","title":"Inserting Content"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"insertText:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"insertString","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"insertString","content":[{"inlineContent":[{"type":"text","text":"The string to insert in the responder."}],"type":"paragraph"}]}]},"path":"/primaryContentSections/1","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertText(_:)/title","value":"insertText:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertText(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"insertText:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertDoubleQuoteIgnoringSubstitution(_:)/title","value":"insertDoubleQuoteIgnoringSubstitution:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertDoubleQuoteIgnoringSubstitution(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertDoubleQuoteIgnoringSubstitution:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertLineBreak(_:)/title","value":"insertLineBreak:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertLineBreak(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"insertLineBreak:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title","value":"NSStandardKeyBindingResponding"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments","value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle","value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertNewline(_:)/title","value":"insertNewline:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertNewline(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"insertNewline:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertBacktab(_:)/title","value":"insertBacktab:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertBacktab(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"insertBacktab:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertTab(_:)/title","value":"insertTab:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertTab(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"insertTab:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertParagraphSeparator(_:)/title","value":"insertParagraphSeparator:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertParagraphSeparator(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertParagraphSeparator:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertTabIgnoringFieldEditor(_:)/title","value":"insertTabIgnoringFieldEditor:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertTabIgnoringFieldEditor(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertTabIgnoringFieldEditor:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertSingleQuoteIgnoringSubstitution(_:)/title","value":"insertSingleQuoteIgnoringSubstitution:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertSingleQuoteIgnoringSubstitution(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertSingleQuoteIgnoringSubstitution:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertNewlineIgnoringFieldEditor(_:)/title","value":"insertNewlineIgnoringFieldEditor:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertNewlineIgnoringFieldEditor(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"insertNewlineIgnoringFieldEditor:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertContainerBreak(_:)/title","value":"insertContainerBreak:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1insertContainerBreak(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertContainerBreak:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}