{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/makebasewritingdirectionrighttoleft(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/makebasewritingdirectionrighttoleft(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeBaseWritingDirectionRightToLeft","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"seeAlsoSections":[{"anchor":"Supporting-Writing-Directions","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeBaseWritingDirectionLeftToRight(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeBaseWritingDirectionNatural(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeTextWritingDirectionLeftToRight(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeTextWritingDirectionNatural(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeTextWritingDirectionRightToLeft(_:)"],"generated":true,"title":"Supporting Writing Directions"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeBaseWritingDirectionRightToLeft(_:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"metadata":{"title":"makeBaseWritingDirectionRightToLeft(_:)","externalID":"c:objc(pl)NSStandardKeyBindingResponding(im)makeBaseWritingDirectionRightToLeft:","navigatorTitle":[{"kind":"identifier","text":"makeBaseWritingDirectionRightToLeft:"}],"platforms":[{"introducedAt":"10.6","unavailable":false,"beta":false,"deprecated":false,"name":"macOS"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeBaseWritingDirectionRightToLeft"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"modules":[{"name":"AppKit"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method"},"sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeTextWritingDirectionLeftToRight(_:)":{"type":"topic","role":"symbol","title":"makeTextWritingDirectionLeftToRight(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/maketextwritingdirectionlefttoright(_:)","navigatorTitle":[{"text":"makeTextWritingDirectionLeftToRight:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeTextWritingDirectionLeftToRight(_:)","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeTextWritingDirectionLeftToRight","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeTextWritingDirectionRightToLeft(_:)":{"abstract":[],"url":"/documentation/appkit/nsstandardkeybindingresponding/maketextwritingdirectionrighttoleft(_:)","kind":"symbol","role":"symbol","title":"makeTextWritingDirectionRightToLeft(_:)","navigatorTitle":[{"text":"makeTextWritingDirectionRightToLeft:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeTextWritingDirectionRightToLeft(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeTextWritingDirectionRightToLeft","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeTextWritingDirectionNatural(_:)":{"abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeTextWritingDirectionNatural(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeTextWritingDirectionNatural","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"title":"makeTextWritingDirectionNatural(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/maketextwritingdirectionnatural(_:)","navigatorTitle":[{"text":"makeTextWritingDirectionNatural:","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeBaseWritingDirectionNatural(_:)":{"title":"makeBaseWritingDirectionNatural(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/makebasewritingdirectionnatural(_:)","type":"topic","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeBaseWritingDirectionNatural(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeBaseWritingDirectionNatural","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"makeBaseWritingDirectionNatural:","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeBaseWritingDirectionRightToLeft(_:)":{"title":"makeBaseWritingDirectionRightToLeft(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/makebasewritingdirectionrighttoleft(_:)","type":"topic","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeBaseWritingDirectionRightToLeft(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeBaseWritingDirectionRightToLeft","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"makeBaseWritingDirectionRightToLeft:","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeBaseWritingDirectionLeftToRight(_:)":{"abstract":[],"url":"/documentation/appkit/nsstandardkeybindingresponding/makebasewritingdirectionlefttoright(_:)","kind":"symbol","role":"symbol","title":"makeBaseWritingDirectionLeftToRight(_:)","navigatorTitle":[{"text":"makeBaseWritingDirectionLeftToRight:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeBaseWritingDirectionLeftToRight(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeBaseWritingDirectionLeftToRight","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"name":"macOS","introducedAt":"10.6","unavailable":false,"deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"makeBaseWritingDirectionRightToLeft:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"makeBaseWritingDirectionRightToLeft:"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeBaseWritingDirectionLeftToRight(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeBaseWritingDirectionNatural(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeTextWritingDirectionLeftToRight(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeTextWritingDirectionNatural(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/makeTextWritingDirectionRightToLeft(_:)"],"anchor":"Supporting-Writing-Directions","title":"Supporting Writing Directions"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"makeBaseWritingDirectionRightToLeft:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"value":"makeTextWritingDirectionLeftToRight:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1makeTextWritingDirectionLeftToRight(_:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"makeTextWritingDirectionLeftToRight:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1makeTextWritingDirectionLeftToRight(_:)/fragments","op":"replace"},{"value":"makeTextWritingDirectionRightToLeft:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1makeTextWritingDirectionRightToLeft(_:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"makeTextWritingDirectionRightToLeft:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1makeTextWritingDirectionRightToLeft(_:)/fragments","op":"replace"},{"value":"makeTextWritingDirectionNatural:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1makeTextWritingDirectionNatural(_:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"makeTextWritingDirectionNatural:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1makeTextWritingDirectionNatural(_:)/fragments","op":"replace"},{"value":"makeBaseWritingDirectionNatural:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1makeBaseWritingDirectionNatural(_:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"makeBaseWritingDirectionNatural:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1makeBaseWritingDirectionNatural(_:)/fragments","op":"replace"},{"value":"makeBaseWritingDirectionRightToLeft:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1makeBaseWritingDirectionRightToLeft(_:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"makeBaseWritingDirectionRightToLeft:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1makeBaseWritingDirectionRightToLeft(_:)/fragments","op":"replace"},{"value":"NSStandardKeyBindingResponding","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments","op":"replace"},{"value":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle","op":"replace"},{"value":"makeBaseWritingDirectionLeftToRight:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1makeBaseWritingDirectionLeftToRight(_:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"makeBaseWritingDirectionLeftToRight:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1makeBaseWritingDirectionLeftToRight(_:)/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}