{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveWordBackwardAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]}],"kind":"symbol","identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordBackwardAndModifySelection(_:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"AppKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveWordBackwardAndModifySelection"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"platforms":[{"name":"macOS","unavailable":false,"deprecated":false,"beta":false}],"navigatorTitle":[{"kind":"identifier","text":"moveWordBackwardAndModifySelection:"}],"roleHeading":"Instance Method","title":"moveWordBackwardAndModifySelection(_:)","externalID":"c:objc(pl)NSStandardKeyBindingResponding(im)moveWordBackwardAndModifySelection:","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/movewordbackwardandmodifyselection(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/movewordbackwardandmodifyselection(_:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"anchor":"Moving-the-Selection-by-Word-Boundaries","generated":true,"title":"Moving the Selection by Word Boundaries","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordBackward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordForward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordForwardAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordLeft(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordLeftAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordRight(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordRightAndModifySelection(_:)"]}],"sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordBackward(_:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"moveWordBackward:","kind":"identifier"}],"title":"moveWordBackward(_:)","abstract":[],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordBackward(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveWordBackward","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movewordbackward(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordRightAndModifySelection(_:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"moveWordRightAndModifySelection:","kind":"identifier"}],"title":"moveWordRightAndModifySelection(_:)","abstract":[],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordRightAndModifySelection(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"moveWordRightAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movewordrightandmodifyselection(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordBackwardAndModifySelection(_:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"moveWordBackwardAndModifySelection:","kind":"identifier"}],"title":"moveWordBackwardAndModifySelection(_:)","abstract":[],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordBackwardAndModifySelection(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"moveWordBackwardAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movewordbackwardandmodifyselection(_:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordForwardAndModifySelection(_:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"moveWordForwardAndModifySelection:","kind":"identifier"}],"title":"moveWordForwardAndModifySelection(_:)","abstract":[],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordForwardAndModifySelection(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveWordForwardAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movewordforwardandmodifyselection(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordForward(_:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"moveWordForward:","kind":"identifier"}],"title":"moveWordForward(_:)","abstract":[],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordForward(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveWordForward","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movewordforward(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordRight(_:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"moveWordRight:","kind":"identifier"}],"title":"moveWordRight(_:)","abstract":[],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordRight(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveWordRight","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movewordright(_:)"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordLeft(_:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"moveWordLeft:"}],"title":"moveWordLeft(_:)","abstract":[],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordLeft(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveWordLeft","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movewordleft(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordLeftAndModifySelection(_:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"moveWordLeftAndModifySelection:","kind":"identifier"}],"title":"moveWordLeftAndModifySelection(_:)","abstract":[],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordLeftAndModifySelection(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveWordLeftAndModifySelection"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movewordleftandmodifyselection(_:)"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"macOS","unavailable":false,"deprecated":false,"beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"moveWordBackwardAndModifySelection:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"moveWordBackwardAndModifySelection:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordBackward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordForward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordForwardAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordLeft(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordLeftAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordRight(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveWordRightAndModifySelection(_:)"],"generated":true,"anchor":"Moving-the-Selection-by-Word-Boundaries","title":"Moving the Selection by Word Boundaries"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"moveWordBackwardAndModifySelection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveWordBackward(_:)/title","value":"moveWordBackward:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveWordBackward(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveWordBackward:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveWordRightAndModifySelection(_:)/title","value":"moveWordRightAndModifySelection:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveWordRightAndModifySelection(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveWordRightAndModifySelection:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveWordBackwardAndModifySelection(_:)/title","value":"moveWordBackwardAndModifySelection:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveWordBackwardAndModifySelection(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"moveWordBackwardAndModifySelection:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title","value":"NSStandardKeyBindingResponding"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments","value":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle","value":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveWordForwardAndModifySelection(_:)/title","value":"moveWordForwardAndModifySelection:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveWordForwardAndModifySelection(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"moveWordForwardAndModifySelection:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveWordForward(_:)/title","op":"replace","value":"moveWordForward:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveWordForward(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveWordForward:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveWordRight(_:)/title","op":"replace","value":"moveWordRight:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveWordRight(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveWordRight:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveWordLeft(_:)/title","op":"replace","value":"moveWordLeft:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveWordLeft(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveWordLeft:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveWordLeftAndModifySelection(_:)/title","op":"replace","value":"moveWordLeftAndModifySelection:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveWordLeftAndModifySelection(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveWordLeftAndModifySelection:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}