{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfDocument(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfDocumentAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfDocumentAndModifySelection(_:)"],"anchor":"Moving-the-Selection-in-Documents","title":"Moving the Selection in Documents"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/movetoendofdocument(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/movetoendofdocument(_:)"]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfDocument(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToEndOfDocument"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"platforms":["macOS"]}]}],"metadata":{"navigatorTitle":[{"text":"moveToEndOfDocument:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"AppKit"}],"platforms":[{"deprecated":false,"name":"macOS","beta":false,"unavailable":false}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToEndOfDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"symbolKind":"method","title":"moveToEndOfDocument(_:)","externalID":"c:objc(pl)NSStandardKeyBindingResponding(im)moveToEndOfDocument:","role":"symbol"},"kind":"symbol","references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfDocumentAndModifySelection(_:)":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToEndOfDocumentAndModifySelection"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfDocumentAndModifySelection(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"moveToEndOfDocumentAndModifySelection:"}],"type":"topic","title":"moveToEndOfDocumentAndModifySelection(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/movetoendofdocumentandmodifyselection(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfDocument(_:)":{"kind":"symbol","title":"moveToEndOfDocument(_:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfDocument(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/movetoendofdocument(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToEndOfDocument"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"moveToEndOfDocument:"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfDocumentAndModifySelection(_:)":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToBeginningOfDocumentAndModifySelection"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfDocumentAndModifySelection(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"moveToBeginningOfDocumentAndModifySelection:"}],"type":"topic","title":"moveToBeginningOfDocumentAndModifySelection(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/movetobeginningofdocumentandmodifyselection(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfDocument(_:)":{"kind":"symbol","title":"moveToBeginningOfDocument(_:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfDocument(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/movetobeginningofdocument(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToBeginningOfDocument"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"moveToBeginningOfDocument:"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"op":"replace","value":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"moveToEndOfDocument:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"moveToEndOfDocument:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Moving-the-Selection-in-Documents","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfDocument(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfDocumentAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfDocumentAndModifySelection(_:)"],"title":"Moving the Selection in Documents"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"moveToEndOfDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfDocumentAndModifySelection(_:)/title","op":"replace","value":"moveToEndOfDocumentAndModifySelection:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfDocumentAndModifySelection(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"moveToEndOfDocumentAndModifySelection:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfDocument(_:)/title","op":"replace","value":"moveToEndOfDocument:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfDocument(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"moveToEndOfDocument:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfDocumentAndModifySelection(_:)/title","op":"replace","value":"moveToBeginningOfDocumentAndModifySelection:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfDocumentAndModifySelection(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"moveToBeginningOfDocumentAndModifySelection:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfDocument(_:)/title","op":"replace","value":"moveToBeginningOfDocument:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfDocument(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"moveToBeginningOfDocument:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title","op":"replace","value":"NSStandardKeyBindingResponding"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments","op":"replace","value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle","op":"replace","value":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}