{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"moveToBeginningOfLineAndModifySelection:"}],"title":"moveToBeginningOfLineAndModifySelection(_:)","modules":[{"name":"AppKit"}],"symbolKind":"method","role":"symbol","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToBeginningOfLineAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"externalID":"c:objc(pl)NSStandardKeyBindingResponding(im)moveToBeginningOfLineAndModifySelection:","roleHeading":"Instance Method"},"variants":[{"paths":["/documentation/appkit/nsstandardkeybindingresponding/movetobeginningoflineandmodifyselection(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsstandardkeybindingresponding/movetobeginningoflineandmodifyselection(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfLineAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToLeftEndOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToLeftEndOfLineAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToRightEndOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToRightEndOfLineAndModifySelection(_:)"],"title":"Moving the Selection in Lines of Text","anchor":"Moving-the-Selection-in-Lines-of-Text","generated":true}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfLineAndModifySelection(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToBeginningOfLineAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfLine(_:)":{"kind":"symbol","title":"moveToBeginningOfLine(_:)","navigatorTitle":[{"text":"moveToBeginningOfLine:","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfLine(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToBeginningOfLine"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"role":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding/movetobeginningofline(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfLineAndModifySelection(_:)":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfLineAndModifySelection(_:)","abstract":[],"title":"moveToBeginningOfLineAndModifySelection(_:)","navigatorTitle":[{"text":"moveToBeginningOfLineAndModifySelection:","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToBeginningOfLineAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movetobeginningoflineandmodifyselection(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToLeftEndOfLineAndModifySelection(_:)":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToLeftEndOfLineAndModifySelection(_:)","abstract":[],"title":"moveToLeftEndOfLineAndModifySelection(_:)","navigatorTitle":[{"text":"moveToLeftEndOfLineAndModifySelection:","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToLeftEndOfLineAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movetoleftendoflineandmodifyselection(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToRightEndOfLine(_:)":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToRightEndOfLine(_:)","abstract":[],"title":"moveToRightEndOfLine(_:)","navigatorTitle":[{"text":"moveToRightEndOfLine:","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToRightEndOfLine","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movetorightendofline(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToRightEndOfLineAndModifySelection(_:)":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToRightEndOfLineAndModifySelection(_:)","abstract":[],"title":"moveToRightEndOfLineAndModifySelection(_:)","navigatorTitle":[{"kind":"identifier","text":"moveToRightEndOfLineAndModifySelection:"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToRightEndOfLineAndModifySelection"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movetorightendoflineandmodifyselection(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToLeftEndOfLine(_:)":{"kind":"symbol","title":"moveToLeftEndOfLine(_:)","navigatorTitle":[{"text":"moveToLeftEndOfLine:","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToLeftEndOfLine(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToLeftEndOfLine"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"role":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding/movetoleftendofline(_:)"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfLineAndModifySelection(_:)":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfLineAndModifySelection(_:)","abstract":[],"title":"moveToEndOfLineAndModifySelection(_:)","navigatorTitle":[{"text":"moveToEndOfLineAndModifySelection:","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToEndOfLineAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movetoendoflineandmodifyselection(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfLine(_:)":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfLine(_:)","abstract":[],"title":"moveToEndOfLine(_:)","navigatorTitle":[{"text":"moveToEndOfLine:","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToEndOfLine","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movetoendofline(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"path":"/metadata/platforms"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"moveToBeginningOfLineAndModifySelection:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveToBeginningOfLineAndModifySelection:"}],"op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"anchor":"Moving-the-Selection-in-Lines-of-Text","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfLineAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToLeftEndOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToLeftEndOfLineAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToRightEndOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToRightEndOfLineAndModifySelection(_:)"],"title":"Moving the Selection in Lines of Text","generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"moveToBeginningOfLineAndModifySelection:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":"moveToBeginningOfLine:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfLine(_:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveToBeginningOfLine:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfLine(_:)/fragments","op":"replace"},{"value":"moveToBeginningOfLineAndModifySelection:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfLineAndModifySelection(_:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveToBeginningOfLineAndModifySelection:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfLineAndModifySelection(_:)/fragments","op":"replace"},{"value":"moveToLeftEndOfLineAndModifySelection:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToLeftEndOfLineAndModifySelection(_:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"moveToLeftEndOfLineAndModifySelection:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToLeftEndOfLineAndModifySelection(_:)/fragments","op":"replace"},{"value":"moveToRightEndOfLine:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToRightEndOfLine(_:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveToRightEndOfLine:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToRightEndOfLine(_:)/fragments","op":"replace"},{"value":"moveToRightEndOfLineAndModifySelection:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToRightEndOfLineAndModifySelection(_:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"moveToRightEndOfLineAndModifySelection:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToRightEndOfLineAndModifySelection(_:)/fragments","op":"replace"},{"value":"NSStandardKeyBindingResponding","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle","op":"replace"},{"value":"moveToLeftEndOfLine:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToLeftEndOfLine(_:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"moveToLeftEndOfLine:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToLeftEndOfLine(_:)/fragments","op":"replace"},{"value":"moveToEndOfLineAndModifySelection:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfLineAndModifySelection(_:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"moveToEndOfLineAndModifySelection:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfLineAndModifySelection(_:)/fragments","op":"replace"},{"value":"moveToEndOfLine:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfLine(_:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveToEndOfLine:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfLine(_:)/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}