{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveRightAndModifySelection(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/moverightandmodifyselection(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/moverightandmodifyselection(_:)"]}],"sections":[],"metadata":{"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:objc(pl)NSStandardKeyBindingResponding(im)moveRightAndModifySelection:","modules":[{"name":"AppKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveRightAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"title":"moveRightAndModifySelection(_:)","platforms":[{"name":"macOS","beta":false,"unavailable":false,"deprecated":false}],"navigatorTitle":[{"text":"moveRightAndModifySelection:","kind":"identifier"}]},"seeAlsoSections":[{"title":"Modifying the Selection","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveBackwardAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveDownAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveForwardAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveLeftAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveUpAndModifySelection(_:)"],"generated":true,"anchor":"Modifying-the-Selection"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"abstract":[{"type":"text","text":"Extends the selection to include the content to the right of the current selection."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveRightAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveForwardAndModifySelection(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"moveForwardAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveForwardAndModifySelection(_:)","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"moveForwardAndModifySelection:","kind":"identifier"}],"title":"moveForwardAndModifySelection(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/moveforwardandmodifyselection(_:)","abstract":[{"text":"Extends the selection to include the content after the current selection.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveUpAndModifySelection(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"moveUpAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveUpAndModifySelection(_:)","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"moveUpAndModifySelection:"}],"title":"moveUpAndModifySelection(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/moveupandmodifyselection(_:)","abstract":[{"text":"Extends the selection to include the content above the current selection.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveBackwardAndModifySelection(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"moveBackwardAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveBackwardAndModifySelection(_:)","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"moveBackwardAndModifySelection:"}],"title":"moveBackwardAndModifySelection(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/movebackwardandmodifyselection(_:)","abstract":[{"text":"Extends the selection to include the content before the current selection.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveRightAndModifySelection(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"moveRightAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveRightAndModifySelection(_:)","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"moveRightAndModifySelection:","kind":"identifier"}],"title":"moveRightAndModifySelection(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/moverightandmodifyselection(_:)","abstract":[{"text":"Extends the selection to include the content to the right of the current selection.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveLeftAndModifySelection(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"moveLeftAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveLeftAndModifySelection(_:)","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"moveLeftAndModifySelection:","kind":"identifier"}],"title":"moveLeftAndModifySelection(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/moveleftandmodifyselection(_:)","abstract":[{"text":"Extends the selection to include the content to the left of the current selection.","type":"text"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveDownAndModifySelection(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"moveDownAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveDownAndModifySelection(_:)","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"moveDownAndModifySelection:","kind":"identifier"}],"title":"moveDownAndModifySelection(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/movedownandmodifyselection(_:)","abstract":[{"text":"Extends the selection to include the content below the current selection.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":false,"name":"macOS","beta":false}],"op":"replace","path":"/metadata/platforms"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"moveRightAndModifySelection:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveRightAndModifySelection:"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Modifying the Selection","anchor":"Modifying-the-Selection","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveBackwardAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveDownAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveForwardAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveLeftAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveUpAndModifySelection(_:)"],"generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"moveRightAndModifySelection:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveForwardAndModifySelection(_:)/title","op":"replace","value":"moveForwardAndModifySelection:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveForwardAndModifySelection(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"moveForwardAndModifySelection:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveUpAndModifySelection(_:)/title","op":"replace","value":"moveUpAndModifySelection:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveUpAndModifySelection(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveUpAndModifySelection:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveBackwardAndModifySelection(_:)/title","op":"replace","value":"moveBackwardAndModifySelection:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveBackwardAndModifySelection:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveBackwardAndModifySelection(_:)/fragments"},{"op":"replace","value":"NSStandardKeyBindingResponding","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle"},{"op":"replace","value":"moveRightAndModifySelection:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveRightAndModifySelection(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveRightAndModifySelection:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveRightAndModifySelection(_:)/fragments"},{"op":"replace","value":"moveLeftAndModifySelection:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveLeftAndModifySelection(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveLeftAndModifySelection:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveLeftAndModifySelection(_:)/fragments"},{"op":"replace","value":"moveDownAndModifySelection:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveDownAndModifySelection(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"moveDownAndModifySelection:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveDownAndModifySelection(_:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}