{"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"sections":[],"seeAlsoSections":[{"generated":true,"anchor":"Moving-the-Selection-in-Paragraphs","title":"Moving the Selection in Paragraphs","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveParagraphBackwardAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveParagraphForwardAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfParagraph(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfParagraph(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfParagraphAndModifySelection(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"platforms":[{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"title":"moveToBeginningOfParagraphAndModifySelection(_:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"moveToBeginningOfParagraphAndModifySelection:"}],"externalID":"c:objc(pl)NSStandardKeyBindingResponding(im)moveToBeginningOfParagraphAndModifySelection:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToBeginningOfParagraphAndModifySelection"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"modules":[{"name":"AppKit"}],"role":"symbol","roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToBeginningOfParagraphAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"platforms":["macOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/movetobeginningofparagraphandmodifyselection(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/movetobeginningofparagraphandmodifyselection(_:)"]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfParagraphAndModifySelection(_:)","interfaceLanguage":"swift"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfParagraph(_:)":{"title":"moveToEndOfParagraph(_:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfParagraph(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"moveToEndOfParagraph","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"moveToEndOfParagraph:","kind":"identifier"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movetoendofparagraph(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveParagraphForwardAndModifySelection(_:)":{"title":"moveParagraphForwardAndModifySelection(_:)","role":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding/moveparagraphforwardandmodifyselection(_:)","navigatorTitle":[{"text":"moveParagraphForwardAndModifySelection:","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveParagraphForwardAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveParagraphForwardAndModifySelection(_:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveParagraphBackwardAndModifySelection(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveParagraphBackwardAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/moveparagraphbackwardandmodifyselection(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveParagraphBackwardAndModifySelection(_:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"moveParagraphBackwardAndModifySelection:","kind":"identifier"}],"type":"topic","abstract":[],"title":"moveParagraphBackwardAndModifySelection(_:)"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfParagraph(_:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToBeginningOfParagraph","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"abstract":[],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfParagraph(_:)","navigatorTitle":[{"text":"moveToBeginningOfParagraph:","kind":"identifier"}],"title":"moveToBeginningOfParagraph(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/movetobeginningofparagraph(_:)","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfParagraphAndModifySelection(_:)":{"role":"symbol","navigatorTitle":[{"text":"moveToEndOfParagraphAndModifySelection:","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moveToEndOfParagraphAndModifySelection"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfParagraphAndModifySelection(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/movetoendofparagraphandmodifyselection(_:)","title":"moveToEndOfParagraphAndModifySelection(_:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfParagraphAndModifySelection(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToBeginningOfParagraphAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movetobeginningofparagraphandmodifyselection(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfParagraphAndModifySelection(_:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"moveToBeginningOfParagraphAndModifySelection:","kind":"identifier"}],"type":"topic","abstract":[],"title":"moveToBeginningOfParagraphAndModifySelection(_:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"moveToBeginningOfParagraphAndModifySelection:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"moveToBeginningOfParagraphAndModifySelection:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Moving-the-Selection-in-Paragraphs","generated":true,"title":"Moving the Selection in Paragraphs","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveParagraphBackwardAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveParagraphForwardAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfParagraph(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfParagraph(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfParagraphAndModifySelection(_:)"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"moveToBeginningOfParagraphAndModifySelection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfParagraph(_:)/title","value":"moveToEndOfParagraph:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfParagraph(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"moveToEndOfParagraph:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveParagraphForwardAndModifySelection(_:)/title","value":"moveParagraphForwardAndModifySelection:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveParagraphForwardAndModifySelection(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"moveParagraphForwardAndModifySelection:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title","value":"NSStandardKeyBindingResponding","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments","value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle","value":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveParagraphBackwardAndModifySelection(_:)/title","value":"moveParagraphBackwardAndModifySelection:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveParagraphBackwardAndModifySelection(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"moveParagraphBackwardAndModifySelection:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfParagraph(_:)/title","value":"moveToBeginningOfParagraph:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfParagraph(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveToBeginningOfParagraph:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfParagraphAndModifySelection(_:)/title","value":"moveToEndOfParagraphAndModifySelection:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfParagraphAndModifySelection(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"moveToEndOfParagraphAndModifySelection:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfParagraphAndModifySelection(_:)/title","value":"moveToBeginningOfParagraphAndModifySelection:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfParagraphAndModifySelection(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"moveToBeginningOfParagraphAndModifySelection:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}