{"seeAlsoSections":[{"title":"Moving the Selection in Documents","anchor":"Moving-the-Selection-in-Documents","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfDocumentAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfDocument(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfDocumentAndModifySelection(_:)"],"generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"kind":"symbol","identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfDocument(_:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["/documentation/appkit/nsstandardkeybindingresponding/movetobeginningofdocument(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsstandardkeybindingresponding/movetobeginningofdocument(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToBeginningOfDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"}],"metadata":{"platforms":[{"beta":false,"name":"macOS","deprecated":false,"unavailable":false}],"externalID":"c:objc(pl)NSStandardKeyBindingResponding(im)moveToBeginningOfDocument:","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"moveToBeginningOfDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"symbolKind":"method","modules":[{"name":"AppKit"}],"title":"moveToBeginningOfDocument(_:)","navigatorTitle":[{"text":"moveToBeginningOfDocument:","kind":"identifier"}]},"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfDocument(_:)":{"kind":"symbol","title":"moveToEndOfDocument(_:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfDocument(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/movetoendofdocument(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToEndOfDocument"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"moveToEndOfDocument:"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfDocumentAndModifySelection(_:)":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToBeginningOfDocumentAndModifySelection"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfDocumentAndModifySelection(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"moveToBeginningOfDocumentAndModifySelection:"}],"type":"topic","title":"moveToBeginningOfDocumentAndModifySelection(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/movetobeginningofdocumentandmodifyselection(_:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfDocumentAndModifySelection(_:)":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToEndOfDocumentAndModifySelection"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfDocumentAndModifySelection(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"moveToEndOfDocumentAndModifySelection:"}],"type":"topic","title":"moveToEndOfDocumentAndModifySelection(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/movetoendofdocumentandmodifyselection(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfDocument(_:)":{"kind":"symbol","title":"moveToBeginningOfDocument(_:)","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfDocument(_:)","url":"/documentation/appkit/nsstandardkeybindingresponding/movetobeginningofdocument(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToBeginningOfDocument"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"moveToBeginningOfDocument:"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"path":"/metadata/title","value":"moveToBeginningOfDocument:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"moveToBeginningOfDocument:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfDocumentAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfDocument(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfDocumentAndModifySelection(_:)"],"anchor":"Moving-the-Selection-in-Documents","generated":true,"title":"Moving the Selection in Documents"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"moveToBeginningOfDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfDocument(_:)/title","value":"moveToEndOfDocument:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfDocument(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveToEndOfDocument:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title","value":"NSStandardKeyBindingResponding","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments","value":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle","value":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfDocumentAndModifySelection(_:)/title","value":"moveToBeginningOfDocumentAndModifySelection:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfDocumentAndModifySelection(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"moveToBeginningOfDocumentAndModifySelection:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfDocumentAndModifySelection(_:)/title","value":"moveToEndOfDocumentAndModifySelection:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfDocumentAndModifySelection(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveToEndOfDocumentAndModifySelection:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfDocument(_:)/title","value":"moveToBeginningOfDocument:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfDocument(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveToBeginningOfDocument:"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}