{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"variants":[{"paths":["/documentation/appkit/nsstandardkeybindingresponding/movetoendoflineandmodifyselection(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsstandardkeybindingresponding/movetoendoflineandmodifyselection(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfLineAndModifySelection(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","seeAlsoSections":[{"anchor":"Moving-the-Selection-in-Lines-of-Text","title":"Moving the Selection in Lines of Text","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfLineAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToLeftEndOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToLeftEndOfLineAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToRightEndOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToRightEndOfLineAndModifySelection(_:)"],"generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToEndOfLineAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}]}],"kind":"declarations"}],"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"moveToEndOfLineAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"moveToEndOfLineAndModifySelection:","kind":"identifier"}],"modules":[{"name":"AppKit"}],"externalID":"c:objc(pl)NSStandardKeyBindingResponding(im)moveToEndOfLineAndModifySelection:","title":"moveToEndOfLineAndModifySelection(_:)","platforms":[{"unavailable":false,"deprecated":false,"name":"macOS","beta":false}],"symbolKind":"method"},"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfLineAndModifySelection(_:)":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfLineAndModifySelection(_:)","abstract":[],"title":"moveToBeginningOfLineAndModifySelection(_:)","navigatorTitle":[{"text":"moveToBeginningOfLineAndModifySelection:","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToBeginningOfLineAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movetobeginningoflineandmodifyselection(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToRightEndOfLine(_:)":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToRightEndOfLine(_:)","abstract":[],"title":"moveToRightEndOfLine(_:)","navigatorTitle":[{"text":"moveToRightEndOfLine:","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToRightEndOfLine","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movetorightendofline(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfLine(_:)":{"kind":"symbol","title":"moveToBeginningOfLine(_:)","navigatorTitle":[{"text":"moveToBeginningOfLine:","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfLine(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToBeginningOfLine"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"role":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding/movetobeginningofline(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfLine(_:)":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfLine(_:)","abstract":[],"title":"moveToEndOfLine(_:)","navigatorTitle":[{"text":"moveToEndOfLine:","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToEndOfLine","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movetoendofline(_:)"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToRightEndOfLineAndModifySelection(_:)":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToRightEndOfLineAndModifySelection(_:)","abstract":[],"title":"moveToRightEndOfLineAndModifySelection(_:)","navigatorTitle":[{"kind":"identifier","text":"moveToRightEndOfLineAndModifySelection:"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToRightEndOfLineAndModifySelection"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movetorightendoflineandmodifyselection(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToLeftEndOfLineAndModifySelection(_:)":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToLeftEndOfLineAndModifySelection(_:)","abstract":[],"title":"moveToLeftEndOfLineAndModifySelection(_:)","navigatorTitle":[{"text":"moveToLeftEndOfLineAndModifySelection:","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToLeftEndOfLineAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movetoleftendoflineandmodifyselection(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToLeftEndOfLine(_:)":{"kind":"symbol","title":"moveToLeftEndOfLine(_:)","navigatorTitle":[{"text":"moveToLeftEndOfLine:","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToLeftEndOfLine(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveToLeftEndOfLine"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"role":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding/movetoleftendofline(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfLineAndModifySelection(_:)":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfLineAndModifySelection(_:)","abstract":[],"title":"moveToEndOfLineAndModifySelection(_:)","navigatorTitle":[{"text":"moveToEndOfLineAndModifySelection:","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveToEndOfLineAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/movetoendoflineandmodifyselection(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"macOS","deprecated":false,"unavailable":false,"beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"moveToEndOfLineAndModifySelection:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"moveToEndOfLineAndModifySelection:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Moving the Selection in Lines of Text","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToBeginningOfLineAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToEndOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToLeftEndOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToLeftEndOfLineAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToRightEndOfLine(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveToRightEndOfLineAndModifySelection(_:)"],"anchor":"Moving-the-Selection-in-Lines-of-Text"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"moveToEndOfLineAndModifySelection:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":"moveToBeginningOfLineAndModifySelection:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfLineAndModifySelection(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"moveToBeginningOfLineAndModifySelection:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfLineAndModifySelection(_:)/fragments"},{"value":"NSStandardKeyBindingResponding","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title"},{"value":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments"},{"value":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle"},{"value":"moveToRightEndOfLine:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToRightEndOfLine(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"moveToRightEndOfLine:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToRightEndOfLine(_:)/fragments"},{"value":"moveToBeginningOfLine:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfLine(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveToBeginningOfLine:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToBeginningOfLine(_:)/fragments"},{"value":"moveToEndOfLine:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfLine(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveToEndOfLine:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfLine(_:)/fragments"},{"value":"moveToRightEndOfLineAndModifySelection:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToRightEndOfLineAndModifySelection(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"moveToRightEndOfLineAndModifySelection:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToRightEndOfLineAndModifySelection(_:)/fragments"},{"value":"moveToLeftEndOfLineAndModifySelection:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToLeftEndOfLineAndModifySelection(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveToLeftEndOfLineAndModifySelection:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToLeftEndOfLineAndModifySelection(_:)/fragments"},{"value":"moveToLeftEndOfLine:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToLeftEndOfLine(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveToLeftEndOfLine:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToLeftEndOfLine(_:)/fragments"},{"value":"moveToEndOfLineAndModifySelection:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfLineAndModifySelection(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveToEndOfLineAndModifySelection:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveToEndOfLineAndModifySelection(_:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}