{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveForward(_:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveForward"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]}],"kind":"declarations"}],"metadata":{"platforms":[{"name":"macOS","beta":false,"deprecated":false,"unavailable":false}],"navigatorTitle":[{"kind":"identifier","text":"moveForward:"}],"roleHeading":"Instance Method","externalID":"c:objc(pl)NSStandardKeyBindingResponding(im)moveForward:","symbolKind":"method","modules":[{"name":"AppKit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveForward"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"title":"moveForward(_:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/moveforward(_:)"]},{"paths":["/documentation/appkit/nsstandardkeybindingresponding/moveforward(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveBackward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveDown(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveLeft(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveRight(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveUp(_:)"],"title":"Moving the Insertion Pointer","generated":true,"anchor":"Moving-the-Insertion-Pointer"}],"sections":[],"abstract":[{"text":"Moves the insertion pointer forward in the current content.","type":"text"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveForward(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveForward"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveForward(_:)","navigatorTitle":[{"kind":"identifier","text":"moveForward:"}],"role":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding/moveforward(_:)","abstract":[{"type":"text","text":"Moves the insertion pointer forward in the current content."}],"title":"moveForward(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveRight(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveRight"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveRight(_:)","navigatorTitle":[{"kind":"identifier","text":"moveRight:"}],"role":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding/moveright(_:)","abstract":[{"type":"text","text":"Moves the insertion pointer right in the current content."}],"title":"moveRight(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveUp(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveUp"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveUp(_:)","navigatorTitle":[{"kind":"identifier","text":"moveUp:"}],"role":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding/moveup(_:)","abstract":[{"type":"text","text":"Moves the insertion pointer up in the current content."}],"title":"moveUp(_:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveBackward(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moveBackward"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveBackward(_:)","navigatorTitle":[{"kind":"identifier","text":"moveBackward:"}],"role":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding/movebackward(_:)","abstract":[{"type":"text","text":"Moves the insertion pointer backward in the current content."}],"title":"moveBackward(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveDown(_:)":{"type":"topic","role":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding/movedown(_:)","navigatorTitle":[{"kind":"identifier","text":"moveDown:"}],"title":"moveDown(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveDown","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveDown(_:)","kind":"symbol","abstract":[{"text":"Moves the insertion pointer down in the current content.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveLeft(_:)":{"type":"topic","role":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding/moveleft(_:)","navigatorTitle":[{"kind":"identifier","text":"moveLeft:"}],"title":"moveLeft(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveLeft","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveLeft(_:)","kind":"symbol","abstract":[{"text":"Moves the insertion pointer left in the current content.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"moveForward:","op":"replace"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveForward:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Moving-the-Insertion-Pointer","title":"Moving the Insertion Pointer","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveBackward(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveDown(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveLeft(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveRight(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/moveUp(_:)"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"moveForward:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"moveForward:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveForward(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"moveForward:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveForward(_:)/fragments"},{"op":"replace","value":"moveRight:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveRight(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveRight:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveRight(_:)/fragments"},{"op":"replace","value":"moveUp:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveUp(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"moveUp:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveUp(_:)/fragments"},{"op":"replace","value":"moveBackward:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveBackward(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moveBackward:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveBackward(_:)/fragments"},{"op":"replace","value":"NSStandardKeyBindingResponding","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title"},{"op":"replace","value":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments"},{"op":"replace","value":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle"},{"op":"replace","value":"moveDown:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveDown(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"moveDown:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveDown(_:)/fragments"},{"op":"replace","value":"moveLeft:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveLeft(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"moveLeft:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1moveLeft(_:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}