{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"text":"Moves the visible content region up by a page, and extends the current selection.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/pageupandmodifyselection(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/pageupandmodifyselection(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/pageUpAndModifySelection(_:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"seeAlsoSections":[{"title":"Scrolling Content","anchor":"Scrolling-Content","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollPageDown(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollPageUp(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollLineDown(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollLineUp(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollToBeginningOfDocument(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollToEndOfDocument(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/pageDown(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/pageUp(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/pageDownAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/centerSelectionInVisibleArea(_:)"],"generated":true}],"metadata":{"modules":[{"name":"AppKit"}],"title":"pageUpAndModifySelection(_:)","symbolKind":"method","navigatorTitle":[{"text":"pageUpAndModifySelection:","kind":"identifier"}],"externalID":"c:objc(pl)NSStandardKeyBindingResponding(im)pageUpAndModifySelection:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageUpAndModifySelection"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","platforms":[{"beta":false,"name":"macOS","deprecated":false,"unavailable":false}]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pageUpAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/centerSelectionInVisibleArea(_:)":{"url":"/documentation/appkit/nsstandardkeybindingresponding/centerselectioninvisiblearea(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"centerSelectionInVisibleArea:"}],"role":"symbol","type":"topic","title":"centerSelectionInVisibleArea(_:)","abstract":[{"type":"text","text":"Moves the visible content region so the current selection is visually centered."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"centerSelectionInVisibleArea"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/centerSelectionInVisibleArea(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollLineDown(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollLineDown(_:)","navigatorTitle":[{"kind":"identifier","text":"scrollLineDown:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollLineDown"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"title":"scrollLineDown(_:)","role":"symbol","abstract":[{"type":"text","text":"Scrolls the content down by a line."}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nsstandardkeybindingresponding/scrolllinedown(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/pageDown(_:)":{"url":"/documentation/appkit/nsstandardkeybindingresponding/pagedown(_:)","kind":"symbol","navigatorTitle":[{"text":"pageDown:","kind":"identifier"}],"role":"symbol","type":"topic","title":"pageDown(_:)","abstract":[{"text":"Moves the visible content region down by a page.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageDown","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/pageDown(_:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollPageUp(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollPageUp(_:)","navigatorTitle":[{"text":"scrollPageUp:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollPageUp","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"title":"scrollPageUp(_:)","role":"symbol","abstract":[{"text":"Scrolls the content up by a page.","type":"text"}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nsstandardkeybindingresponding/scrollpageup(_:)"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollLineUp(_:)":{"kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding/scrolllineup(_:)","title":"scrollLineUp(_:)","navigatorTitle":[{"text":"scrollLineUp:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollLineUp","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"type":"topic","abstract":[{"text":"Scrolls the content up by a line.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollLineUp(_:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/pageUp(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageUp"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/pageup(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/pageUp(_:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pageUp:"}],"type":"topic","abstract":[{"text":"Moves the visible content region up by a page.","type":"text"}],"title":"pageUp(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollToBeginningOfDocument(_:)":{"abstract":[{"text":"Scrolls the content to the beginning of the document.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollToBeginningOfDocument","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/scrolltobeginningofdocument(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollToBeginningOfDocument(_:)","role":"symbol","navigatorTitle":[{"text":"scrollToBeginningOfDocument:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"scrollToBeginningOfDocument(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollToEndOfDocument(_:)":{"url":"/documentation/appkit/nsstandardkeybindingresponding/scrolltoendofdocument(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"scrollToEndOfDocument:"}],"role":"symbol","type":"topic","title":"scrollToEndOfDocument(_:)","abstract":[{"text":"Scrolls the content to the end of the document.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollToEndOfDocument"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollToEndOfDocument(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/pageUpAndModifySelection(_:)":{"kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding/pageupandmodifyselection(_:)","title":"pageUpAndModifySelection(_:)","navigatorTitle":[{"text":"pageUpAndModifySelection:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageUpAndModifySelection","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"type":"topic","abstract":[{"text":"Moves the visible content region up by a page, and extends the current selection.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/pageUpAndModifySelection(_:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollPageDown(_:)":{"url":"/documentation/appkit/nsstandardkeybindingresponding/scrollpagedown(_:)","title":"scrollPageDown(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollPageDown","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"scrollPageDown:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollPageDown(_:)","abstract":[{"text":"Scrolls the content down by a page.","type":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/pageDownAndModifySelection(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageDownAndModifySelection"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/pagedownandmodifyselection(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/pageDownAndModifySelection(_:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pageDownAndModifySelection:"}],"type":"topic","abstract":[{"text":"Moves the visible content region down by a page, and extends the current selection.","type":"text"}],"title":"pageDownAndModifySelection(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"pageUpAndModifySelection:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"pageUpAndModifySelection:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"title":"Scrolling Content","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollPageDown(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollPageUp(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollLineDown(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollLineUp(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollToBeginningOfDocument(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/scrollToEndOfDocument(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/pageDown(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/pageUp(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/pageDownAndModifySelection(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/centerSelectionInVisibleArea(_:)"],"anchor":"Scrolling-Content"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"pageUpAndModifySelection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1centerSelectionInVisibleArea(_:)/title","value":"centerSelectionInVisibleArea:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1centerSelectionInVisibleArea(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"centerSelectionInVisibleArea:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1scrollLineDown(_:)/title","value":"scrollLineDown:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1scrollLineDown(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"scrollLineDown:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1pageDown(_:)/title","value":"pageDown:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1pageDown(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"pageDown:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1scrollPageUp(_:)/title","value":"scrollPageUp:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1scrollPageUp(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollPageUp:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1scrollLineUp(_:)/title","value":"scrollLineUp:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1scrollLineUp(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"scrollLineUp:","kind":"identifier"}]},{"value":"pageUp:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1pageUp(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pageUp:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1pageUp(_:)/fragments"},{"value":"scrollToBeginningOfDocument:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1scrollToBeginningOfDocument(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"scrollToBeginningOfDocument:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1scrollToBeginningOfDocument(_:)/fragments"},{"value":"NSStandardKeyBindingResponding","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title"},{"value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments"},{"value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle"},{"value":"scrollToEndOfDocument:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1scrollToEndOfDocument(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollToEndOfDocument:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1scrollToEndOfDocument(_:)/fragments"},{"value":"pageUpAndModifySelection:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1pageUpAndModifySelection(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pageUpAndModifySelection:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1pageUpAndModifySelection(_:)/fragments"},{"value":"scrollPageDown:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1scrollPageDown(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"scrollPageDown:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1scrollPageDown(_:)/fragments"},{"value":"pageDownAndModifySelection:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1pageDownAndModifySelection(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"pageDownAndModifySelection:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1pageDownAndModifySelection(_:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}