{"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/setMark(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToMark(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/swapWithMark(_:)"],"title":"Supporting Marked Selections","anchor":"Supporting-Marked-Selections","generated":true}],"variants":[{"paths":["/documentation/appkit/nsstandardkeybindingresponding/selecttomark(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsstandardkeybindingresponding/selecttomark(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectToMark","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"AppKit"}],"title":"selectToMark(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectToMark"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"symbolKind":"method","platforms":[{"unavailable":false,"deprecated":false,"name":"macOS","beta":false}],"role":"symbol","externalID":"c:objc(pl)NSStandardKeyBindingResponding(im)selectToMark:","navigatorTitle":[{"kind":"identifier","text":"selectToMark:"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/selectToMark(_:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/swapWithMark(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swapWithMark","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"title":"swapWithMark(_:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"swapWithMark:","kind":"identifier"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/swapwithmark(_:)","abstract":[],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/swapWithMark(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToMark(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteToMark","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"title":"deleteToMark(_:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"deleteToMark:","kind":"identifier"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/deletetomark(_:)","abstract":[],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToMark(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/selectToMark(_:)":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/selectToMark(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectToMark","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"selectToMark:","kind":"identifier"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/selecttomark(_:)","title":"selectToMark(_:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/setMark(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMark","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"title":"setMark(_:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"setMark:","kind":"identifier"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/setmark(_:)","abstract":[],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/setMark(_:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"deprecated":false,"name":"macOS","beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"selectToMark:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"selectToMark:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Supporting-Marked-Selections","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/setMark(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/deleteToMark(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/swapWithMark(_:)"],"generated":true,"title":"Supporting Marked Selections"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"selectToMark:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1swapWithMark(_:)/title","op":"replace","value":"swapWithMark:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1swapWithMark(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"swapWithMark:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToMark(_:)/title","op":"replace","value":"deleteToMark:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1deleteToMark(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"deleteToMark:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1selectToMark(_:)/title","op":"replace","value":"selectToMark:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1selectToMark(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"selectToMark:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title","op":"replace","value":"NSStandardKeyBindingResponding"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments","op":"replace","value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle","op":"replace","value":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1setMark(_:)/title","op":"replace","value":"setMark:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1setMark(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMark:"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}