{"seeAlsoSections":[{"anchor":"Transposing-Elements","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/transposeWords(_:)"],"title":"Transposing Elements","generated":true}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/transpose(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/transpose(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsstandardkeybindingresponding/transpose(_:)"]}],"abstract":[{"text":"Transposes the content around the current selection.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transpose","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"languages":["swift"]}]}],"metadata":{"platforms":[{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transpose"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"roleHeading":"Instance Method","externalID":"c:objc(pl)NSStandardKeyBindingResponding(im)transpose:","modules":[{"name":"AppKit"}],"title":"transpose(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"transpose:"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/transpose(_:)":{"abstract":[{"type":"text","text":"Transposes the content around the current selection."}],"url":"/documentation/appkit/nsstandardkeybindingresponding/transpose(_:)","kind":"symbol","role":"symbol","title":"transpose(_:)","navigatorTitle":[{"text":"transpose:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/transpose(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transpose","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/transposeWords(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transposeWords","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/transposeWords(_:)","abstract":[{"type":"text","text":"Transposes the words around the current selection."}],"type":"topic","title":"transposeWords(_:)","kind":"symbol","navigatorTitle":[{"text":"transposeWords:","kind":"identifier"}],"url":"/documentation/appkit/nsstandardkeybindingresponding/transposewords(_:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"transpose:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transpose:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"path":"/hierarchy"},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"anchor":"Transposing-Elements","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/transposeWords(_:)"],"title":"Transposing Elements"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"transpose:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title","value":"NSStandardKeyBindingResponding"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments","value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle","value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1transpose(_:)/title","value":"transpose:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1transpose(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"transpose:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1transposeWords(_:)/title","value":"transposeWords:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1transposeWords(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transposeWords:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}