{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/uppercaseWord(_:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uppercaseWord","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"title":"uppercaseWord(_:)","navigatorTitle":[{"text":"uppercaseWord:","kind":"identifier"}],"role":"symbol","modules":[{"name":"AppKit"}],"platforms":[{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}],"roleHeading":"Instance Method","externalID":"c:objc(pl)NSStandardKeyBindingResponding(im)uppercaseWord:","symbolKind":"method"},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/capitalizeWord(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/changeCaseOfLetter(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/lowercaseWord(_:)"],"title":"Changing Capitalization","generated":true,"anchor":"Changing-Capitalization"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["/documentation/appkit/nsstandardkeybindingresponding/uppercaseword(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsstandardkeybindingresponding/uppercaseword(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uppercaseWord","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}]}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/capitalizeWord(_:)":{"url":"/documentation/appkit/nsstandardkeybindingresponding/capitalizeword(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/capitalizeWord(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"capitalizeWord","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"title":"capitalizeWord(_:)","kind":"symbol","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"capitalizeWord:"}]},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/lowercaseWord(_:)":{"url":"/documentation/appkit/nsstandardkeybindingresponding/lowercaseword(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/lowercaseWord(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lowercaseWord","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"title":"lowercaseWord(_:)","kind":"symbol","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"lowercaseWord:"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/uppercaseWord(_:)":{"url":"/documentation/appkit/nsstandardkeybindingresponding/uppercaseword(_:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/uppercaseWord(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uppercaseWord","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"title":"uppercaseWord(_:)","kind":"symbol","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"uppercaseWord:"}]},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/changeCaseOfLetter(_:)":{"role":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding/changecaseofletter(_:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeCaseOfLetter"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/changeCaseOfLetter(_:)","navigatorTitle":[{"kind":"identifier","text":"changeCaseOfLetter:"}],"title":"changeCaseOfLetter(_:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"uppercaseWord:"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"uppercaseWord:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"title":"Changing Capitalization","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/capitalizeWord(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/changeCaseOfLetter(_:)","doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding/lowercaseWord(_:)"],"anchor":"Changing-Capitalization"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"uppercaseWord:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1capitalizeWord(_:)/title","value":"capitalizeWord:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1capitalizeWord(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"capitalizeWord:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title","value":"NSStandardKeyBindingResponding"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments","value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle","value":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1lowercaseWord(_:)/title","value":"lowercaseWord:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lowercaseWord:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1lowercaseWord(_:)/fragments"},{"op":"replace","value":"uppercaseWord:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1uppercaseWord(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"uppercaseWord:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1uppercaseWord(_:)/fragments"},{"op":"replace","value":"changeCaseOfLetter:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1changeCaseOfLetter(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeCaseOfLetter:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding~1changeCaseOfLetter(_:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}