{
  "abstract": [
    {
      "text": "Returns an authorization object initialized with the specified flags, rights and environment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation",
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/authorization(with:rights:environment:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SFAuthorization(cm)authorizationWithFlags:rights:environment:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "authorization"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "with"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AuthorizationFlags",
        "text": "AuthorizationFlags"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "rights"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AuthorizationRights",
        "text": "AuthorizationRights"
      },
      {
        "kind": "text",
        "text": ">!, "
      },
      {
        "kind": "externalParam",
        "text": "environment"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AuthorizationEnvironment",
        "text": "AuthorizationEnvironment"
      },
      {
        "kind": "text",
        "text": ">!) -> "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "!"
      }
    ],
    "modules": [
      {
        "name": "Security Foundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "authorizationWithFlags:rights:environment:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "authorization(with:rights:environment:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "authorization"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@AuthorizationFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AuthorizationFlags",
              "text": "AuthorizationFlags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "rights"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@AuthorizationRights",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AuthorizationRights",
              "text": "AuthorizationRights"
            },
            {
              "kind": "text",
              "text": ">!, "
            },
            {
              "kind": "externalParam",
              "text": "environment"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@AuthorizationEnvironment",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AuthorizationEnvironment",
              "text": "AuthorizationEnvironment"
            },
            {
              "kind": "text",
              "text": ">!) -> "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "!"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A bit mask for specifying authorization options. Use the following option sets:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "Pass the constant ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/kAuthorizationFlagDefaults",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " if no options are necessary.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "Specify the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/extendRights",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " mask to request rights. You can also specify the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/interactionAllowed",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " mask to allow user interaction.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "Specify the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/partialRights",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " and ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/extendRights",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " masks to request partial rights. You can also specify the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/interactionAllowed",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " mask to allow user interaction.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "Specify the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/preAuthorize",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " and ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/extendRights",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " masks to preauthorize rights.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "Specify the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/destroyRights",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " mask to prevent the Security framework from preserving the rights obtained during this call.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                }
              ],
              "type": "unorderedList"
            }
          ],
          "name": "flags"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to a set of authorization rights you create. Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " if the application requires no rights at this time.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rights"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Data used when authorizing or preauthorizing rights. In macOS 10.3 and later, you can pass icon or prompt data to be used in the authentication dialog box. Possible values for this parameter are listed in ",
                  "type": "text"
                },
                {
                  "code": "Security.framework/Headers/AuthorizationTags.h",
                  "type": "codeVoice"
                },
                {
                  "text": ". The data passed in this parameter is not stored in the authorization reference; it is used only during authorization. If you are not passing any data in this parameter, pass the constant ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Security/kAuthorizationEmptyEnvironment",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "environment"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Return-value",
          "level": 2,
          "text": "Return value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The authorization object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Normally, such initialization is not required, as you pass in flags, rights, and environmental data when you request authorization.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/destroyRights": {
      "abstract": [
        {
          "text": "A flag that instructs the Security Server to revoke authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destroyRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/destroyRights",
      "kind": "symbol",
      "role": "symbol",
      "title": "destroyRights",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationFlags/destroyRights"
    },
    "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/extendRights": {
      "abstract": [
        {
          "text": "A flag that permits the Security Server to attempt to grant the rights requested.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/extendRights",
      "kind": "symbol",
      "role": "symbol",
      "title": "extendRights",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationFlags/extendRights"
    },
    "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/interactionAllowed": {
      "abstract": [
        {
          "text": "A flag that permits user interaction as needed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interactionAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/interactionAllowed",
      "kind": "symbol",
      "role": "symbol",
      "title": "interactionAllowed",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationFlags/interactionAllowed"
    },
    "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/kAuthorizationFlagDefaults": {
      "abstract": [
        {
          "text": "An empty flag set that you use as a placeholder when you don’t want any of the other flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAuthorizationFlagDefaults"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/kAuthorizationFlagDefaults",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAuthorizationFlagDefaults",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationFlags/kAuthorizationFlagDefaults"
    },
    "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/partialRights": {
      "abstract": [
        {
          "text": "A flag that permits the Security Server to grant rights on an individual basis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "partialRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/partialRights",
      "kind": "symbol",
      "role": "symbol",
      "title": "partialRights",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationFlags/partialRights"
    },
    "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/preAuthorize": {
      "abstract": [
        {
          "text": "A flag that instructs the Security Server to preauthorize the rights requested.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preAuthorize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/preAuthorize",
      "kind": "symbol",
      "role": "symbol",
      "title": "preAuthorize",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationFlags/preAuthorize"
    },
    "doc://com.apple.documentation/documentation/Security/kAuthorizationEmptyEnvironment": {
      "abstract": [
        {
          "text": "A constant you use in functions with an environment parameter if you have no environment data to provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "#define"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationEmptyEnvironment"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/kAuthorizationEmptyEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAuthorizationEmptyEnvironment",
      "type": "topic",
      "url": "/documentation/Security/kAuthorizationEmptyEnvironment"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation": {
      "abstract": [
        {
          "text": "Restrict a user’s access to particular features in your Mac app or daemon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "Security Foundation",
      "type": "topic",
      "url": "/documentation/securityfoundation"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization": {
      "abstract": [
        {
          "text": "A class that allows you to restrict a user’s access to particular features in your Mac app or daemon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFAuthorization"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFAuthorization"
        }
      ],
      "role": "symbol",
      "title": "SFAuthorization",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/authorization()": {
      "abstract": [
        {
          "text": "Returns an authorization object initialized with a default environment, flags, and rights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorization"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/authorization()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorization"
        }
      ],
      "role": "symbol",
      "title": "authorization()",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization/authorization()"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/authorization(with:rights:environment:)": {
      "abstract": [
        {
          "text": "Returns an authorization object initialized with the specified flags, rights and environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRights",
          "text": "AuthorizationRights"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "environment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationEnvironment",
          "text": "AuthorizationEnvironment"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/authorization(with:rights:environment:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorizationWithFlags:rights:environment:"
        }
      ],
      "role": "symbol",
      "title": "authorization(with:rights:environment:)",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization/authorization(with:rights:environment:)"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/init()": {
      "abstract": [
        {
          "text": "Initializes an authorization object with default environment, flags, and rights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!()"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization/init()"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/init(flags:rights:environment:)": {
      "abstract": [
        {
          "text": "Initializes an authorization object with the specified flags, rights, and environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRights",
          "text": "AuthorizationRights"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "environment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationEnvironment",
          "text": "AuthorizationEnvironment"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/init(flags:rights:environment:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFlags:rights:environment:"
        }
      ],
      "role": "symbol",
      "title": "init(flags:rights:environment:)",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization/init(flags:rights:environment:)"
    },
    "doc://com.externally.resolved.symbol/c:@E@AuthorizationFlags": {
      "abstract": [
        {
          "text": "The flags used to specify authorization options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationFlags"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@AuthorizationFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationFlags",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationFlags"
    },
    "doc://com.externally.resolved.symbol/c:@T@AuthorizationEnvironment": {
      "abstract": [
        {
          "text": "An authorization item set designated to hold environment information relevant to authorization decisions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationEnvironment"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AuthorizationItemSet",
          "text": "AuthorizationItemSet"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@AuthorizationEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationEnvironment",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationEnvironment"
    },
    "doc://com.externally.resolved.symbol/c:@T@AuthorizationRights": {
      "abstract": [
        {
          "text": "An authorization item set designated to represent a set of rights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationRights"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AuthorizationItemSet",
          "text": "AuthorizationItemSet"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@AuthorizationRights",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationRights",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationRights"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Allocating-and-initializing-an-authorization-object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/authorization()",
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/init()",
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/init(flags:rights:environment:)"
      ],
      "title": "Allocating and initializing an authorization object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "authorizationWithFlags:rights:environment:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "authorizationWithFlags:rights:environment:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.securityfoundation/documentation/SecurityFoundation",
                "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Allocating-and-initializing-an-authorization-object",
              "generated": true,
              "identifiers": [
                "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/authorization()",
                "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/init()",
                "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/init(flags:rights:environment:)"
              ],
              "title": "Allocating and initializing an authorization object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "authorizationWithFlags:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@E@AuthorizationFlags",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@AuthorizationFlags",
                    "text": "AuthorizationFlags"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "flags"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "rights:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@AuthorizationRights",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AuthorizationRights",
                    "text": "AuthorizationRights"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "rights"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "environment:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@AuthorizationEnvironment",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AuthorizationEnvironment",
                    "text": "AuthorizationEnvironment"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "environment"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A bit mask for specifying authorization options. Use the following option sets:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "text": "Pass the constant ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/kAuthorizationFlagDefaults",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " if no options are necessary.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "text": "Specify the ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/extendRights",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " mask to request rights. You can also specify the ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/interactionAllowed",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " mask to allow user interaction.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "text": "Specify the ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/partialRights",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " and ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/extendRights",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " masks to request partial rights. You can also specify the ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/interactionAllowed",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " mask to allow user interaction.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "text": "Specify the ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/preAuthorize",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " and ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/extendRights",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " masks to preauthorize rights.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "text": "Specify the ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/destroyRights",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " mask to prevent the Security framework from preserving the rights obtained during this call.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      }
                    ],
                    "type": "unorderedList"
                  }
                ],
                "name": "flags"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to a set of authorization rights you create. Pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if the application requires no rights at this time.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "rights"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Data used when authorizing or preauthorizing rights. In macOS 10.3 and later, you can pass icon or prompt data to be used in the authentication dialog box. Possible values for this parameter are listed in ",
                        "type": "text"
                      },
                      {
                        "code": "Security.framework/Headers/AuthorizationTags.h",
                        "type": "codeVoice"
                      },
                      {
                        "text": ". The data passed in this parameter is not stored in the authorization reference; it is used only during authorization. If you are not passing any data in this parameter, pass the constant ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/Security/kAuthorizationEmptyEnvironment",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "environment"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization/title",
          "value": "SFAuthorization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1interactionAllowed/title",
          "value": "kAuthorizationFlagInteractionAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1interactionAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlagInteractionAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@AuthorizationFlags/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AuthorizationFlags"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UInt32",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1partialRights/title",
          "value": "kAuthorizationFlagPartialRights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1partialRights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlagPartialRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1destroyRights/title",
          "value": "kAuthorizationFlagDestroyRights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1destroyRights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlagDestroyRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1authorization()/title",
          "value": "authorization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1authorization()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "authorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1init(flags:rights:environment:)/title",
          "value": "initWithFlags:rights:environment:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1init(flags:rights:environment:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFlags:rights:environment:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1extendRights/title",
          "value": "kAuthorizationFlagExtendRights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1extendRights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlagExtendRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@AuthorizationRights/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@AuthorizationItemSet",
              "text": "AuthorizationItemSet"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AuthorizationRights"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@AuthorizationEnvironment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@AuthorizationItemSet",
              "text": "AuthorizationItemSet"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AuthorizationEnvironment"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1preAuthorize/title",
          "value": "kAuthorizationFlagPreAuthorize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1preAuthorize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlagPreAuthorize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1authorization(with:rights:environment:)/title",
          "value": "authorizationWithFlags:rights:environment:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1authorization(with:rights:environment:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "authorizationWithFlags:rights:environment:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/securityfoundation/sfauthorization/authorization(with:rights:environment:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/securityfoundation/sfauthorization/authorization(with:rights:environment:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
