{
  "abstract": [
    {
      "text": "Initializes an authorization object with default environment, flags, and rights.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation",
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/init()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SFAuthorization(im)init",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "!()"
      }
    ],
    "modules": [
      {
        "name": "Security Foundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "init"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "!()"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation": {
      "abstract": [
        {
          "text": "Restrict a user’s access to particular features in your Mac app or daemon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "Security Foundation",
      "type": "topic",
      "url": "/documentation/securityfoundation"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization": {
      "abstract": [
        {
          "text": "A class that allows you to restrict a user’s access to particular features in your Mac app or daemon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFAuthorization"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFAuthorization"
        }
      ],
      "role": "symbol",
      "title": "SFAuthorization",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/authorization()": {
      "abstract": [
        {
          "text": "Returns an authorization object initialized with a default environment, flags, and rights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorization"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/authorization()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorization"
        }
      ],
      "role": "symbol",
      "title": "authorization()",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization/authorization()"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/authorization(with:rights:environment:)": {
      "abstract": [
        {
          "text": "Returns an authorization object initialized with the specified flags, rights and environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRights",
          "text": "AuthorizationRights"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "environment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationEnvironment",
          "text": "AuthorizationEnvironment"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/authorization(with:rights:environment:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorizationWithFlags:rights:environment:"
        }
      ],
      "role": "symbol",
      "title": "authorization(with:rights:environment:)",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization/authorization(with:rights:environment:)"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/init()": {
      "abstract": [
        {
          "text": "Initializes an authorization object with default environment, flags, and rights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!()"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization/init()"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/init(flags:rights:environment:)": {
      "abstract": [
        {
          "text": "Initializes an authorization object with the specified flags, rights, and environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "!("
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRights",
          "text": "AuthorizationRights"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "environment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationEnvironment",
          "text": "AuthorizationEnvironment"
        },
        {
          "kind": "text",
          "text": ">!)"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/init(flags:rights:environment:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFlags:rights:environment:"
        }
      ],
      "role": "symbol",
      "title": "init(flags:rights:environment:)",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization/init(flags:rights:environment:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Allocating-and-initializing-an-authorization-object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/authorization()",
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/authorization(with:rights:environment:)",
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/init(flags:rights:environment:)"
      ],
      "title": "Allocating and initializing an authorization object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.securityfoundation/documentation/SecurityFoundation",
                "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Allocating-and-initializing-an-authorization-object",
              "generated": true,
              "identifiers": [
                "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/authorization()",
                "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/authorization(with:rights:environment:)",
                "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/init(flags:rights:environment:)"
              ],
              "title": "Allocating and initializing an authorization object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "init"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1init(flags:rights:environment:)/title",
          "value": "initWithFlags:rights:environment:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1init(flags:rights:environment:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFlags:rights:environment:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization/title",
          "value": "SFAuthorization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1authorization()/title",
          "value": "authorization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1authorization()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "authorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1authorization(with:rights:environment:)/title",
          "value": "authorizationWithFlags:rights:environment:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1authorization(with:rights:environment:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "authorizationWithFlags:rights:environment:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/securityfoundation/sfauthorization/init()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/securityfoundation/sfauthorization/init()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
