{
  "abstract": [
    {
      "text": "Authorizes and preauthorizes rights to access a privileged operation and returns the granted rights.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/obtain(withRights:flags:environment:authorizedRights:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation",
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/permitWithRights:flags:environment:authorizedRights:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SFAuthorization(im)permitWithRights:flags:environment:authorizedRights:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "permitWithRights:flags:environment:authorizedRights:"
      }
    ],
    "modules": [
      {
        "name": "Security Foundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "permitWithRights:flags:environment:authorizedRights:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.5",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "permitWithRights:flags:environment:authorizedRights:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "permitWithRights:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@AuthorizationRights",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AuthorizationRights",
              "text": "AuthorizationRights"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "rights"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "flags:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@AuthorizationFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AuthorizationFlags",
              "text": "AuthorizationFlags"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "environment:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@AuthorizationEnvironment",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AuthorizationEnvironment",
              "text": "AuthorizationEnvironment"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "environment"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "authorizedRights:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@AuthorizationRights",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AuthorizationRights",
              "text": "AuthorizationRights"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "authorizedRights"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to a set of authorization rights you create. Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " if the application requires no rights at this time.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rights"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A bit mask for specifying authorization options. Use the following option sets:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "Pass the constant ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/kAuthorizationFlagDefaults",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " if no options are necessary.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "Specify the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/extendRights",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " mask to request rights. You can also specify the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/interactionAllowed",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " mask to allow user interaction.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "Specify the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/partialRights",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " and ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/extendRights",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " masks to request partial rights. You can also specify the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/interactionAllowed",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " mask to allow user interaction.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "Specify the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/preAuthorize",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " and ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/extendRights",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " masks to preauthorize rights.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                },
                {
                  "content": [
                    {
                      "inlineContent": [
                        {
                          "text": "Specify the ",
                          "type": "text"
                        },
                        {
                          "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/destroyRights",
                          "isActive": true,
                          "type": "reference"
                        },
                        {
                          "text": " mask to prevent the Security framework from preserving the rights obtained during this call.",
                          "type": "text"
                        }
                      ],
                      "type": "paragraph"
                    }
                  ]
                }
              ],
              "type": "unorderedList"
            }
          ],
          "name": "flags"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Data used when authorizing or preauthorizing rights. In macOS 10.3 and later, you can pass icon or prompt data to be used in the authentication dialog box. Possible values for this parameter are listed in ",
                  "type": "text"
                },
                {
                  "code": "Security/AuthorizationTags.h",
                  "type": "codeVoice"
                },
                {
                  "text": ". If you are not passing any data in this parameter, pass the constant ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Security/kAuthorizationEmptyEnvironment",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "environment"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to a newly allocated ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationRights",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " structure. On return, this structure contains the rights granted by the Security framework. If you do not require this information, pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ". If you specify the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/preAuthorize",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " mask in the ",
                  "type": "text"
                },
                {
                  "code": "flags",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter, the method returns all the requested rights, including those not granted, but the flags of the rights that could not be preauthorized include the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Security/kAuthorizationFlagCanNotPreAuthorize",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " bit. Free the memory associated with this set of rights by calling the Authorization Services function ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFreeItemSet(_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "authorizedRights"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "There are three main reasons to use this method. The first reason is to preauthorize rights by specifying the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/preAuthorize",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/interactionAllowed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/extendRights",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " masks as authorization options. Preauthorization is most useful when a right has a zero timeout. For example, you can preauthorize in the application and if it succeeds, call the helper tool and request authorization. This eliminates calling the helper tool if the Security framework cannot later authorize the specified rights.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The second reason to use this method is to authorize rights before performing a privileged operation by specifying the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/interactionAllowed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/extendRights",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " masks as authorization options.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The third reason to use this method is to authorize partial rights. By specifying the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/partialRights",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/interactionAllowed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/extendRights",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " masks as authorization options, the Security framework grants all rights it can authorize. On return, the authorized set contains all the rights.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you do not specify the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/partialRights",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " mask and the Security framework denies at least one right, then the status of this method on return is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/errAuthorizationDenied",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you do not specify the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/interactionAllowed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " mask and the Security framework requires user interaction, then the status of this method on return is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/errAuthorizationInteractionNotAllowed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you specify the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/interactionAllowed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " mask and the user cancels the authentication process, then the status of this method on return is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Security/errAuthorizationCanceled",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Special-considerations",
          "level": 3,
          "text": "Special considerations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "authorizedRights",
              "type": "codeVoice"
            },
            {
              "text": " parameter is not supported in OS X v10.3; use the Authorization Services function ",
              "type": "text"
            },
            {
              "code": "AuthorizationCopyRights",
              "type": "codeVoice"
            },
            {
              "text": " instead. In OS X v10.3 there is an error in the signature in the header file for this parameter. If you pass this argument as (AuthorizationRights **)",
              "type": "text"
            },
            {
              "code": "authorizedRights",
              "type": "codeVoice"
            },
            {
              "text": ", as shown in this document, it works as described.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/destroyRights": {
      "abstract": [
        {
          "text": "A flag that instructs the Security Server to revoke authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destroyRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/destroyRights",
      "kind": "symbol",
      "role": "symbol",
      "title": "destroyRights",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationFlags/destroyRights"
    },
    "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/extendRights": {
      "abstract": [
        {
          "text": "A flag that permits the Security Server to attempt to grant the rights requested.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/extendRights",
      "kind": "symbol",
      "role": "symbol",
      "title": "extendRights",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationFlags/extendRights"
    },
    "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/interactionAllowed": {
      "abstract": [
        {
          "text": "A flag that permits user interaction as needed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interactionAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/interactionAllowed",
      "kind": "symbol",
      "role": "symbol",
      "title": "interactionAllowed",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationFlags/interactionAllowed"
    },
    "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/kAuthorizationFlagDefaults": {
      "abstract": [
        {
          "text": "An empty flag set that you use as a placeholder when you don’t want any of the other flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAuthorizationFlagDefaults"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/kAuthorizationFlagDefaults",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAuthorizationFlagDefaults",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationFlags/kAuthorizationFlagDefaults"
    },
    "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/partialRights": {
      "abstract": [
        {
          "text": "A flag that permits the Security Server to grant rights on an individual basis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "partialRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/partialRights",
      "kind": "symbol",
      "role": "symbol",
      "title": "partialRights",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationFlags/partialRights"
    },
    "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/preAuthorize": {
      "abstract": [
        {
          "text": "A flag that instructs the Security Server to preauthorize the rights requested.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preAuthorize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFlags/preAuthorize",
      "kind": "symbol",
      "role": "symbol",
      "title": "preAuthorize",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationFlags/preAuthorize"
    },
    "doc://com.apple.documentation/documentation/Security/AuthorizationFreeItemSet(_:)": {
      "abstract": [
        {
          "text": "Frees the memory associated with a set of authorization items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationFreeItemSet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "set"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AuthorizationItemSet",
          "text": "AuthorizationItemSet"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationFreeItemSet(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationFreeItemSet(_:)",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationFreeItemSet(_:)"
    },
    "doc://com.apple.documentation/documentation/Security/AuthorizationRights": {
      "abstract": [
        {
          "text": "An authorization item set designated to represent a set of rights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationRights"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AuthorizationItemSet",
          "text": "AuthorizationItemSet"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/AuthorizationRights",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationRights",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationRights"
    },
    "doc://com.apple.documentation/documentation/Security/errAuthorizationCanceled": {
      "abstract": [
        {
          "text": "The user canceled the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationCanceled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/errAuthorizationCanceled",
      "kind": "symbol",
      "role": "symbol",
      "title": "errAuthorizationCanceled",
      "type": "topic",
      "url": "/documentation/Security/errAuthorizationCanceled"
    },
    "doc://com.apple.documentation/documentation/Security/errAuthorizationDenied": {
      "abstract": [
        {
          "text": "The Security Server denied authorization for one or more requested rights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/errAuthorizationDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "errAuthorizationDenied",
      "type": "topic",
      "url": "/documentation/Security/errAuthorizationDenied"
    },
    "doc://com.apple.documentation/documentation/Security/errAuthorizationInteractionNotAllowed": {
      "abstract": [
        {
          "text": "The Security Server denied authorization because no user interaction is allowed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationInteractionNotAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/errAuthorizationInteractionNotAllowed",
      "kind": "symbol",
      "role": "symbol",
      "title": "errAuthorizationInteractionNotAllowed",
      "type": "topic",
      "url": "/documentation/Security/errAuthorizationInteractionNotAllowed"
    },
    "doc://com.apple.documentation/documentation/Security/kAuthorizationEmptyEnvironment": {
      "abstract": [
        {
          "text": "A constant you use in functions with an environment parameter if you have no environment data to provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "#define"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationEmptyEnvironment"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/kAuthorizationEmptyEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAuthorizationEmptyEnvironment",
      "type": "topic",
      "url": "/documentation/Security/kAuthorizationEmptyEnvironment"
    },
    "doc://com.apple.documentation/documentation/Security/kAuthorizationFlagCanNotPreAuthorize": {
      "abstract": [
        {
          "text": "Indicates the Security Server could not preauthorizethe right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAuthorizationFlagCanNotPreAuthorize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Security/kAuthorizationFlagCanNotPreAuthorize",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAuthorizationFlagCanNotPreAuthorize",
      "type": "topic",
      "url": "/documentation/Security/kAuthorizationFlagCanNotPreAuthorize"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation": {
      "abstract": [
        {
          "text": "Restrict a user’s access to particular features in your Mac app or daemon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "Security Foundation",
      "type": "topic",
      "url": "/documentation/securityfoundation"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization": {
      "abstract": [
        {
          "text": "A class that allows you to restrict a user’s access to particular features in your Mac app or daemon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFAuthorization"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFAuthorization"
        }
      ],
      "role": "symbol",
      "title": "SFAuthorization",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/obtain(withRight:flags:)": {
      "abstract": [
        {
          "text": "Authorizes and preauthorizes one specific right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "obtain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationString",
          "text": "AuthorizationString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/obtain(withRight:flags:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "obtainWithRight:flags:error:"
        }
      ],
      "role": "symbol",
      "title": "obtain(withRight:flags:)",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization/obtain(withright:flags:)"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/obtain(withRights:flags:environment:authorizedRights:)": {
      "abstract": [
        {
          "text": "Authorizes and preauthorizes rights to access a privileged operation and returns the granted rights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "obtain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRights",
          "text": "AuthorizationRights"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "environment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationEnvironment",
          "text": "AuthorizationEnvironment"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "authorizedRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRights",
          "text": "AuthorizationRights"
        },
        {
          "kind": "text",
          "text": ">?>!) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/obtain(withRights:flags:environment:authorizedRights:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "obtainWithRights:flags:environment:authorizedRights:error:"
        }
      ],
      "role": "symbol",
      "title": "obtain(withRights:flags:environment:authorizedRights:)",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization/obtain(withrights:flags:environment:authorizedrights:)"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/permitWithRight:flags:": {
      "abstract": [
        {
          "text": "Authorizes and preauthorizes one specific right.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "permitWithRight:flags:"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/permitWithRight:flags:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "permitWithRight:flags:"
        }
      ],
      "role": "symbol",
      "title": "permitWithRight:flags:",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization/permitwithright:flags:"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/permitWithRights:flags:environment:authorizedRights:": {
      "abstract": [
        {
          "text": "Authorizes and preauthorizes rights to access a privileged operation and returns the granted rights.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "permitWithRights:flags:environment:authorizedRights:"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/permitWithRights:flags:environment:authorizedRights:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "permitWithRights:flags:environment:authorizedRights:"
        }
      ],
      "role": "symbol",
      "title": "permitWithRights:flags:environment:authorizedRights:",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization/permitwithrights:flags:environment:authorizedrights:"
    },
    "doc://com.externally.resolved.symbol/c:@E@AuthorizationFlags": {
      "abstract": [
        {
          "text": "The flags used to specify authorization options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationFlags"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@AuthorizationFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationFlags",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationFlags"
    },
    "doc://com.externally.resolved.symbol/c:@T@AuthorizationEnvironment": {
      "abstract": [
        {
          "text": "An authorization item set designated to hold environment information relevant to authorization decisions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationEnvironment"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AuthorizationItemSet",
          "text": "AuthorizationItemSet"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@AuthorizationEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationEnvironment",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationEnvironment"
    },
    "doc://com.externally.resolved.symbol/c:@T@AuthorizationRights": {
      "abstract": [
        {
          "text": "An authorization item set designated to represent a set of rights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationRights"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AuthorizationItemSet",
          "text": "AuthorizationItemSet"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@AuthorizationRights",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationRights",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationRights"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Authorizing-rights",
      "generated": true,
      "identifiers": [
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/obtain(withRights:flags:environment:authorizedRights:)",
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/permitWithRight:flags:",
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/obtain(withRight:flags:)"
      ],
      "title": "Authorizing rights"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFreeItemSet(_:)/title",
          "value": "AuthorizationFreeItemSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFreeItemSet(_:)/fragments",
          "value": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AuthorizationFreeItemSet"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@AuthorizationItemSet",
              "text": "AuthorizationItemSet"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "set"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1obtain(withRight:flags:)/title",
          "value": "obtainWithRight:flags:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1obtain(withRight:flags:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "obtainWithRight:flags:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1interactionAllowed/title",
          "value": "kAuthorizationFlagInteractionAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1interactionAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlagInteractionAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1extendRights/title",
          "value": "kAuthorizationFlagExtendRights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1extendRights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlagExtendRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1destroyRights/title",
          "value": "kAuthorizationFlagDestroyRights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1destroyRights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlagDestroyRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization/title",
          "value": "SFAuthorization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@AuthorizationRights/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@AuthorizationItemSet",
              "text": "AuthorizationItemSet"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AuthorizationRights"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationRights/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@AuthorizationItemSet",
              "text": "AuthorizationItemSet"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AuthorizationRights"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1errAuthorizationDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@AuthorizationEnvironment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@AuthorizationItemSet",
              "text": "AuthorizationItemSet"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AuthorizationEnvironment"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@AuthorizationFlags/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AuthorizationFlags"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UInt32",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1errAuthorizationCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1preAuthorize/title",
          "value": "kAuthorizationFlagPreAuthorize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1preAuthorize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlagPreAuthorize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1partialRights/title",
          "value": "kAuthorizationFlagPartialRights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1AuthorizationFlags~1partialRights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlagPartialRights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1obtain(withRights:flags:environment:authorizedRights:)/title",
          "value": "obtainWithRights:flags:environment:authorizedRights:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1obtain(withRights:flags:environment:authorizedRights:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "obtainWithRights:flags:environment:authorizedRights:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1errAuthorizationInteractionNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationInteractionNotAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Security~1kAuthorizationFlagCanNotPreAuthorize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlagCanNotPreAuthorize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/securityfoundation/sfauthorization/permitwithrights:flags:environment:authorizedrights:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
