{
  "abstract": [
    {
      "text": "Authorizes and preauthorizes one specific right.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/obtain(withRight:flags:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation",
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/permitWithRight:flags:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SFAuthorization(im)permitWithRight:flags:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "permitWithRight:flags:"
      }
    ],
    "modules": [
      {
        "name": "Security Foundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "permitWithRight:flags:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.5",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "permitWithRight:flags:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "permitWithRight:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@AuthorizationString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AuthorizationString",
              "text": "AuthorizationString"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "rightName"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "flags:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@AuthorizationFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AuthorizationFlags",
              "text": "AuthorizationFlags"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of an authorization right.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rightName"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A bit mask for specifying authorization options. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/permitWithRights:flags:environment:authorizedRights:",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for details about possible flag values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "flags"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method to authorize or preauthorize a single right.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation": {
      "abstract": [
        {
          "text": "Restrict a user’s access to particular features in your Mac app or daemon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "Security Foundation",
      "type": "topic",
      "url": "/documentation/securityfoundation"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization": {
      "abstract": [
        {
          "text": "A class that allows you to restrict a user’s access to particular features in your Mac app or daemon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFAuthorization"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFAuthorization"
        }
      ],
      "role": "symbol",
      "title": "SFAuthorization",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/obtain(withRight:flags:)": {
      "abstract": [
        {
          "text": "Authorizes and preauthorizes one specific right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "obtain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationString",
          "text": "AuthorizationString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/obtain(withRight:flags:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "obtainWithRight:flags:error:"
        }
      ],
      "role": "symbol",
      "title": "obtain(withRight:flags:)",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization/obtain(withright:flags:)"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/obtain(withRights:flags:environment:authorizedRights:)": {
      "abstract": [
        {
          "text": "Authorizes and preauthorizes rights to access a privileged operation and returns the granted rights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "obtain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRights",
          "text": "AuthorizationRights"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AuthorizationFlags",
          "text": "AuthorizationFlags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "environment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationEnvironment",
          "text": "AuthorizationEnvironment"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "externalParam",
          "text": "authorizedRights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRights",
          "text": "AuthorizationRights"
        },
        {
          "kind": "text",
          "text": ">?>!) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/obtain(withRights:flags:environment:authorizedRights:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "obtainWithRights:flags:environment:authorizedRights:error:"
        }
      ],
      "role": "symbol",
      "title": "obtain(withRights:flags:environment:authorizedRights:)",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization/obtain(withrights:flags:environment:authorizedrights:)"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/permitWithRight:flags:": {
      "abstract": [
        {
          "text": "Authorizes and preauthorizes one specific right.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "permitWithRight:flags:"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/permitWithRight:flags:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "permitWithRight:flags:"
        }
      ],
      "role": "symbol",
      "title": "permitWithRight:flags:",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization/permitwithright:flags:"
    },
    "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/permitWithRights:flags:environment:authorizedRights:": {
      "abstract": [
        {
          "text": "Authorizes and preauthorizes rights to access a privileged operation and returns the granted rights.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "permitWithRights:flags:environment:authorizedRights:"
        }
      ],
      "identifier": "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/permitWithRights:flags:environment:authorizedRights:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "permitWithRights:flags:environment:authorizedRights:"
        }
      ],
      "role": "symbol",
      "title": "permitWithRights:flags:environment:authorizedRights:",
      "type": "topic",
      "url": "/documentation/securityfoundation/sfauthorization/permitwithrights:flags:environment:authorizedrights:"
    },
    "doc://com.externally.resolved.symbol/c:@E@AuthorizationFlags": {
      "abstract": [
        {
          "text": "The flags used to specify authorization options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationFlags"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@AuthorizationFlags",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationFlags",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationFlags"
    },
    "doc://com.externally.resolved.symbol/c:@T@AuthorizationString": {
      "abstract": [
        {
          "text": "A zero-terminated string in UTF-8 encoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationString"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@AuthorizationString",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationString",
      "type": "topic",
      "url": "/documentation/Security/AuthorizationString"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Authorizing-rights",
      "generated": true,
      "identifiers": [
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/permitWithRights:flags:environment:authorizedRights:",
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/obtain(withRights:flags:environment:authorizedRights:)",
        "doc://com.apple.securityfoundation/documentation/SecurityFoundation/SFAuthorization/obtain(withRight:flags:)"
      ],
      "title": "Authorizing rights"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@AuthorizationFlags/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AuthorizationFlags"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UInt32",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1obtain(withRights:flags:environment:authorizedRights:)/title",
          "value": "obtainWithRights:flags:environment:authorizedRights:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1obtain(withRights:flags:environment:authorizedRights:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "obtainWithRights:flags:environment:authorizedRights:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@AuthorizationString/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "AuthorizationString"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization/title",
          "value": "SFAuthorization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1obtain(withRight:flags:)/title",
          "value": "obtainWithRight:flags:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityfoundation~1documentation~1SecurityFoundation~1SFAuthorization~1obtain(withRight:flags:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "obtainWithRight:flags:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/securityfoundation/sfauthorization/permitwithright:flags:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
