{
  "abstract": [
    {
      "text": "An elaborated title that explains the purpose of the key command.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/discoverabilityTitle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIKeyCommand(py)discoverabilityTitle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "discoverabilityTitle"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "discoverabilityTitle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "discoverabilityTitle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "discoverabilityTitle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system uses this property to display information about the command. In iOS, the system displays this title in the discoverability heads-up display (HUD). If this property is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", the HUD displays the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICommand/title",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In Mac apps built with Mac Catalyst, the system displays the discoverability title as a tooltip.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICommand/title": {
      "abstract": [
        {
          "text": "The command’s title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICommand/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/uikit/uicommand/title"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand": {
      "abstract": [
        {
          "text": "An object that specifies a key press perform on a hardware keyboard and the resulting action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIKeyCommand"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyCommand"
        }
      ],
      "role": "symbol",
      "title": "UIKeyCommand",
      "type": "topic",
      "url": "/documentation/uikit/uikeycommand"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/action": {
      "abstract": [
        {
          "text": "The command’s action-method selector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/action",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "action"
        }
      ],
      "role": "symbol",
      "title": "action",
      "type": "topic",
      "url": "/documentation/uikit/uikeycommand/action"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/attributes": {
      "abstract": [
        {
          "text": "The attributes indicating the style of the key command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMenuElement",
          "text": "UIMenuElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIMenuElementAttributes",
          "text": "Attributes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/attributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributes"
        }
      ],
      "role": "symbol",
      "title": "attributes",
      "type": "topic",
      "url": "/documentation/uikit/uikeycommand/attributes"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/discoverabilityTitle": {
      "abstract": [
        {
          "text": "An elaborated title that explains the purpose of the key command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discoverabilityTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/discoverabilityTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "discoverabilityTitle"
        }
      ],
      "role": "symbol",
      "title": "discoverabilityTitle",
      "type": "topic",
      "url": "/documentation/uikit/uikeycommand/discoverabilitytitle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/image": {
      "abstract": [
        {
          "text": "The key command’s image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/uikit/uikeycommand/image"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/input": {
      "abstract": [
        {
          "text": "The string of characters corresponding to the keys that must be pressed to match this key command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "input"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/input",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "input"
        }
      ],
      "role": "symbol",
      "title": "input",
      "type": "topic",
      "url": "/documentation/uikit/uikeycommand/input"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/modifierFlags": {
      "abstract": [
        {
          "text": "The bit mask of modifier flags that must be pressed to match this key command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modifierFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIKeyModifierFlags",
          "text": "UIKeyModifierFlags"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/modifierFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "modifierFlags"
        }
      ],
      "role": "symbol",
      "title": "modifierFlags",
      "type": "topic",
      "url": "/documentation/uikit/uikeycommand/modifierflags"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/state": {
      "abstract": [
        {
          "text": "The state of the key command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMenuElement",
          "text": "UIMenuElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIMenuElementState",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/state",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/uikit/uikeycommand/state"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/title": {
      "abstract": [
        {
          "text": "The key command’s title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/uikit/uikeycommand/title"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyModifierFlags": {
      "abstract": [
        {
          "text": "Constants that indicate which modifier keys are pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIKeyModifierFlags"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyModifierFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyModifierFlags"
        }
      ],
      "role": "symbol",
      "title": "UIKeyModifierFlags",
      "type": "topic",
      "url": "/documentation/uikit/uikeymodifierflags"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-information-about-the-key-command",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/title",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/image",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/input",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/action",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/modifierFlags",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyModifierFlags",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/attributes",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/state"
      ],
      "title": "Getting information about the key command"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "discoverabilityTitle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "discoverabilityTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-information-about-the-key-command",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/title",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/image",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/input",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/action",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/modifierFlags",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyModifierFlags",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/attributes",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyCommand/state"
              ],
              "title": "Getting information about the key command"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "discoverabilityTitle"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand~1discoverabilityTitle/title",
          "value": "discoverabilityTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand~1discoverabilityTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "discoverabilityTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICommand~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICommand~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand/title",
          "value": "UIKeyCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand~1state/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand~1state/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand~1input/title",
          "value": "input"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand~1input/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "input"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand~1attributes/title",
          "value": "attributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand~1attributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand~1image/title",
          "value": "image"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand~1image/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "image"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand~1modifierFlags/title",
          "value": "modifierFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand~1modifierFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "modifierFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyModifierFlags/title",
          "value": "UIKeyModifierFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyModifierFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyModifierFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyModifierFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyModifierFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand~1action/title",
          "value": "action"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyCommand~1action/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "action"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uikeycommand/discoverabilitytitle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uikeycommand/discoverabilitytitle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
