{
  "abstract": [
    {
      "text": "Tells the delegate the service level indicator of the connected Bluetooth hands-free phone or headset has changed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:isServiceAvailable:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)IOBluetoothHandsFreeDeviceDelegate(im)handsFree:isServiceAvailable:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "handsFree"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)IOBluetoothHandsFreeDevice",
        "text": "IOBluetoothHandsFreeDevice"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "isServiceAvailable"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSNumber",
        "text": "NSNumber"
      },
      {
        "kind": "text",
        "text": "!)"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "handsFree:isServiceAvailable:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "handsFree(_:isServiceAvailable:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "handsFree"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "device"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDevice",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)IOBluetoothHandsFreeDevice",
              "text": "IOBluetoothHandsFreeDevice"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "isServiceAvailable"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": "!)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The connected Bluetooth hands-free phone or headset.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "device"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The new service level. For possible values, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorService",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "isServiceAvailable"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDevice": {
      "abstract": [
        {
          "text": "An object you use to manage phone calls on a connected Bluetooth hands-free phone or headset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDevice"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDevice"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeDevice",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreedevice"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods for receiving status change updates and information about a connected Bluetooth hands-free phone or headset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDeviceDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDeviceDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeDeviceDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreedevicedelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:batteryCharge:)": {
      "abstract": [
        {
          "text": "Tells the delegate the battery level indicator of the connected Bluetooth hands-free phone or headset has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handsFree"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothHandsFreeDevice",
          "text": "IOBluetoothHandsFreeDevice"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "batteryCharge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:batteryCharge:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handsFree:batteryCharge:"
        }
      ],
      "role": "symbol",
      "title": "handsFree(_:batteryCharge:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreedevicedelegate/handsfree(_:batterycharge:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:callHoldState:)": {
      "abstract": [
        {
          "text": "Tells the delegate the call held indicator of the connected Bluetooth hands-free phone or headset has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handsFree"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothHandsFreeDevice",
          "text": "IOBluetoothHandsFreeDevice"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "callHoldState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:callHoldState:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handsFree:callHoldState:"
        }
      ],
      "role": "symbol",
      "title": "handsFree(_:callHoldState:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreedevicedelegate/handsfree(_:callholdstate:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:callSetupMode:)": {
      "abstract": [
        {
          "text": "Tells the delegate the call setup indicator of the connected Bluetooth hands-free phone or headset has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handsFree"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothHandsFreeDevice",
          "text": "IOBluetoothHandsFreeDevice"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "callSetupMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:callSetupMode:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handsFree:callSetupMode:"
        }
      ],
      "role": "symbol",
      "title": "handsFree(_:callSetupMode:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreedevicedelegate/handsfree(_:callsetupmode:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:isCallActive:)": {
      "abstract": [
        {
          "text": "Tells the delegate the active call indicator of the connected Bluetooth hands-free phone or headset has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handsFree"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothHandsFreeDevice",
          "text": "IOBluetoothHandsFreeDevice"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "isCallActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:isCallActive:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handsFree:isCallActive:"
        }
      ],
      "role": "symbol",
      "title": "handsFree(_:isCallActive:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreedevicedelegate/handsfree(_:iscallactive:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:isRoaming:)": {
      "abstract": [
        {
          "text": "Tells the delegate the roaming indicator of the connected Bluetooth hands-free phone or headset has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handsFree"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothHandsFreeDevice",
          "text": "IOBluetoothHandsFreeDevice"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "isRoaming"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:isRoaming:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handsFree:isRoaming:"
        }
      ],
      "role": "symbol",
      "title": "handsFree(_:isRoaming:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreedevicedelegate/handsfree(_:isroaming:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:isServiceAvailable:)": {
      "abstract": [
        {
          "text": "Tells the delegate the service level indicator of the connected Bluetooth hands-free phone or headset has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handsFree"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothHandsFreeDevice",
          "text": "IOBluetoothHandsFreeDevice"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "isServiceAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:isServiceAvailable:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handsFree:isServiceAvailable:"
        }
      ],
      "role": "symbol",
      "title": "handsFree(_:isServiceAvailable:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreedevicedelegate/handsfree(_:isserviceavailable:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:signalStrength:)": {
      "abstract": [
        {
          "text": "Tells the delegate the call setup signal strength indicator of the connected Bluetooth hands-free phone or headset has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handsFree"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothHandsFreeDevice",
          "text": "IOBluetoothHandsFreeDevice"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "signalStrength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:signalStrength:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handsFree:signalStrength:"
        }
      ],
      "role": "symbol",
      "title": "handsFree(_:signalStrength:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreedevicedelegate/handsfree(_:signalstrength:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorService": {
      "abstract": [
        {
          "text": "The command string you use to show a carrier network connection indicator on a phone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeIndicatorService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeIndicatorService"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeIndicatorService",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreeindicatorservice"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Receiving-Status-Indicator-Changes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:callSetupMode:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:isCallActive:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:signalStrength:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:callHoldState:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:isRoaming:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:batteryCharge:)"
      ],
      "title": "Receiving Status Indicator Changes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "handsFree:isServiceAvailable:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handsFree:isServiceAvailable:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Receiving-Status-Indicator-Changes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:callSetupMode:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:isCallActive:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:signalStrength:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:callHoldState:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:isRoaming:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:batteryCharge:)"
              ],
              "title": "Receiving Status Indicator Changes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "handsFree:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDevice",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)IOBluetoothHandsFreeDevice",
                    "text": "IOBluetoothHandsFreeDevice"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "device"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "isServiceAvailable:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSNumber",
                    "text": "NSNumber"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "isServiceAvailable"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The connected Bluetooth hands-free phone or headset.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "device"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The new service level. For possible values, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorService",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "isServiceAvailable"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate~1handsFree(_:callHoldState:)/title",
          "value": "handsFree:callHoldState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate~1handsFree(_:callHoldState:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handsFree:callHoldState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate/title",
          "value": "IOBluetoothHandsFreeDeviceDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate~1handsFree(_:batteryCharge:)/title",
          "value": "handsFree:batteryCharge:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate~1handsFree(_:batteryCharge:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handsFree:batteryCharge:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate~1handsFree(_:signalStrength:)/title",
          "value": "handsFree:signalStrength:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate~1handsFree(_:signalStrength:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handsFree:signalStrength:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate~1handsFree(_:isServiceAvailable:)/title",
          "value": "handsFree:isServiceAvailable:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate~1handsFree(_:isServiceAvailable:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handsFree:isServiceAvailable:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDevice/title",
          "value": "IOBluetoothHandsFreeDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate~1handsFree(_:callSetupMode:)/title",
          "value": "handsFree:callSetupMode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate~1handsFree(_:callSetupMode:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handsFree:callSetupMode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorService/title",
          "value": "IOBluetoothHandsFreeIndicatorService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeIndicatorService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate~1handsFree(_:isRoaming:)/title",
          "value": "handsFree:isRoaming:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate~1handsFree(_:isRoaming:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handsFree:isRoaming:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate~1handsFree(_:isCallActive:)/title",
          "value": "handsFree:isCallActive:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate~1handsFree(_:isCallActive:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handsFree:isCallActive:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothhandsfreedevicedelegate/handsfree(_:isserviceavailable:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothhandsfreedevicedelegate/handsfree(_:isserviceavailable:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
