{
  "abstract": [
    {
      "text": "Creates a matching dictionary to find a USB device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iousbhost/documentation/IOUSBHost",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevice"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevice/createMatchingDictionaryWithVendorID:productID:bcdDevice:deviceClass:deviceSubclass:deviceProtocol:speed:productIDArray:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)IOUSBHostDevice(cm)createMatchingDictionaryWithVendorID:productID:bcdDevice:deviceClass:deviceSubclass:deviceProtocol:speed:productIDArray:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "createMatchingDictionaryWithVendorID:productID:bcdDevice:deviceClass:deviceSubclass:deviceProtocol:speed:productIDArray:"
      }
    ],
    "modules": [
      {
        "name": "IOUSBHost"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "createMatchingDictionaryWithVendorID:productID:bcdDevice:deviceClass:deviceSubclass:deviceProtocol:speed:productIDArray:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "createMatchingDictionaryWithVendorID:productID:bcdDevice:deviceClass:deviceSubclass:deviceProtocol:speed:productIDArray:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFMutableDictionaryRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
              "text": "CFMutableDictionaryRef"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "createMatchingDictionaryWithVendorID:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "vendorID"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "productID:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "productID"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bcdDevice:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "bcdDevice"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "deviceClass:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "deviceClass"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "deviceSubclass:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "deviceSubclass"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "deviceProtocol:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "deviceProtocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "speed:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "speed"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "productIDArray:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSArray",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSArray",
              "text": "NSArray"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "productIDArray"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The vendor ID for the device you’re searching for.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "vendorID"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The product ID for the device you’re searching for.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "productID"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The release number of the device you’re searching for.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "bcdDevice"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The class of the device you’re searching for.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "deviceClass"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The subclass of the device you’re searching for.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "deviceSubclass"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The protocol of the device you’re searching for.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "deviceProtocol"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The enumeration speed of the device you’re searching for. Add the speed to any of the keys in the table below.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "speed"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of product IDs to match against. Don’t use this parameter with the ",
                  "type": "text"
                },
                {
                  "code": "productID",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "productIDArray"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A dictionary to pass to IOKit matching methods, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/iokit/1514535-ioservicegetmatchingservice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The caller must release this object when done.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The table below shows the keys you can use to make a successful matching dictionary. A plus sign (+) separates the keys to emphasize the requirement that all of the specified keys combine.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The table presents the keys in order of specificity. The first key defines the most specific search, and the last key defines the broadest search.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Keys",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Notes",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425819-idvendor",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " + ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1426145-idproduct",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " + ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425514-bcddevice",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "None.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425819-idvendor",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " + ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1426145-idproduct",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "None.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425819-idvendor",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " + ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425757-bdevicesubclass",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " + ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425787-bdeviceprotocol",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Use these keys only if the device’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425902-bdeviceclass",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is set to 0xFF.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425819-idvendor",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " + ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425757-bdevicesubclass",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Use these keys only if the device’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425902-bdeviceclass",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is set to 0xFF.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425902-bdeviceclass",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " + ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425757-bdevicesubclass",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " + ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425787-bdeviceprotocol",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Use these keys only if the device’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425902-bdeviceclass",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is not set to 0xFF.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425902-bdeviceclass",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " + ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425757-bdevicesubclass",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Use these keys only if the device’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425902-bdeviceclass",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " is not set to 0xFF.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/iokit/1514535-ioservicegetmatchingservice": {
      "abstract": [
        {
          "text": "Look up a registered IOService object that matches a matching dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "IOServiceGetMatchingService"
        },
        {
          "kind": "text",
          "text": "(mach_port_t, CFDictionary!) -> io_service_t"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/iokit/1514535-ioservicegetmatchingservice",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOServiceGetMatchingService(_:_:)",
      "type": "topic",
      "url": "/documentation/iokit/1514535-ioservicegetmatchingservice"
    },
    "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOUSBDeviceDescriptor",
      "type": "topic",
      "url": "/documentation/iokit/iousbdevicedescriptor"
    },
    "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425514-bcddevice": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425514-bcddevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "bcdDevice",
      "type": "topic",
      "url": "/documentation/iokit/iousbdevicedescriptor/1425514-bcddevice"
    },
    "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425757-bdevicesubclass": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425757-bdevicesubclass",
      "kind": "symbol",
      "role": "symbol",
      "title": "bDeviceSubClass",
      "type": "topic",
      "url": "/documentation/iokit/iousbdevicedescriptor/1425757-bdevicesubclass"
    },
    "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425787-bdeviceprotocol": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425787-bdeviceprotocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "bDeviceProtocol",
      "type": "topic",
      "url": "/documentation/iokit/iousbdevicedescriptor/1425787-bdeviceprotocol"
    },
    "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425819-idvendor": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425819-idvendor",
      "kind": "symbol",
      "role": "symbol",
      "title": "idVendor",
      "type": "topic",
      "url": "/documentation/iokit/iousbdevicedescriptor/1425819-idvendor"
    },
    "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425902-bdeviceclass": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1425902-bdeviceclass",
      "kind": "symbol",
      "role": "symbol",
      "title": "bDeviceClass",
      "type": "topic",
      "url": "/documentation/iokit/iousbdevicedescriptor/1425902-bdeviceclass"
    },
    "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1426145-idproduct": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor/1426145-idproduct",
      "kind": "symbol",
      "role": "symbol",
      "title": "idProduct",
      "type": "topic",
      "url": "/documentation/iokit/iousbdevicedescriptor/1426145-idproduct"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost": {
      "abstract": [
        {
          "text": "Create host-mode user space drivers for USB devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost",
      "kind": "symbol",
      "role": "collection",
      "title": "IOUSBHost",
      "type": "topic",
      "url": "/documentation/iousbhost"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevice": {
      "abstract": [
        {
          "text": "The class that claims and configures devices, retrieves descriptors, and sends device requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostDevice"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostDevice"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostDevice",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostdevice"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevice/createMatchingDictionaryWithVendorID:productID:bcdDevice:deviceClass:deviceSubclass:deviceProtocol:speed:productIDArray:": {
      "abstract": [
        {
          "text": "Creates a matching dictionary to find a USB device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "createMatchingDictionaryWithVendorID:productID:bcdDevice:deviceClass:deviceSubclass:deviceProtocol:speed:productIDArray:"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevice/createMatchingDictionaryWithVendorID:productID:bcdDevice:deviceClass:deviceSubclass:deviceProtocol:speed:productIDArray:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createMatchingDictionaryWithVendorID:productID:bcdDevice:deviceClass:deviceSubclass:deviceProtocol:speed:productIDArray:"
        }
      ],
      "role": "symbol",
      "title": "createMatchingDictionaryWithVendorID:productID:bcdDevice:deviceClass:deviceSubclass:deviceProtocol:speed:productIDArray:",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostdevice/creatematchingdictionarywithvendorid:productid:bcddevice:deviceclass:devicesubclass:deviceprotocol:speed:productidarray:"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey": {
      "abstract": [
        {
          "text": "Properties for implementing the matching service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostMatchingPropertyKey"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostMatchingPropertyKey",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostmatchingpropertykey"
    },
    "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPropertyKey": {
      "abstract": [
        {
          "text": "Properties that the USB host device and interface classes share.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOUSBHostPropertyKey"
        }
      ],
      "identifier": "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPropertyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOUSBHostPropertyKey"
        }
      ],
      "role": "symbol",
      "title": "IOUSBHostPropertyKey",
      "type": "topic",
      "url": "/documentation/iousbhost/iousbhostpropertykey"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFMutableDictionaryRef": {
      "abstract": [
        {
          "text": "A reference to a mutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFMutableDictionary"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFMutableDictionaryRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFMutableDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfmutabledictionary"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSArray": {
      "abstract": [
        {
          "text": "An object representing a static ordered collection, for use instead of an  constant in cases that require reference semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSArray",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSArray",
      "type": "topic",
      "url": "/documentation/foundation/nsarray"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostDevice",
        "doc://com.apple.documentation/documentation/iokit/iousbdevicedescriptor"
      ],
      "title": "Related Documentation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Properties",
      "identifiers": [
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostMatchingPropertyKey",
        "doc://com.apple.iousbhost/documentation/IOUSBHost/IOUSBHostPropertyKey"
      ],
      "title": "Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevice/title",
          "value": "IOUSBHostDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1iokit~11514535-ioservicegetmatchingservice/title",
          "value": "IOServiceGetMatchingService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFMutableDictionaryRef/title",
          "value": "CFMutableDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey/title",
          "value": "IOUSBHostMatchingPropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostMatchingPropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostMatchingPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPropertyKey/title",
          "value": "IOUSBHostPropertyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPropertyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iousbhost~1documentation~1IOUSBHost~1IOUSBHostPropertyKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOUSBHostPropertyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSArray/abstract",
          "value": [
            {
              "text": "A static ordered collection of objects.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iousbhost/iousbhostdevice/creatematchingdictionarywithvendorid:productid:bcddevice:deviceclass:devicesubclass:deviceprotocol:speed:productidarray:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
