{
  "abstract": [
    {
      "text": "Constants that specify the preferred text styles you use with fonts.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSFont"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@T@NSFontTextStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TextStyle"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TextStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSFont.TextStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TextStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Pass these constants to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/preferredFont(forTextStyle:options:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/preferredFontDescriptor(forTextStyle:options:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to retrieve the corresponding font or font descriptor.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont": {
      "abstract": [
        {
          "text": "The representation of a font in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFont"
        }
      ],
      "role": "symbol",
      "title": "NSFont",
      "type": "topic",
      "url": "/documentation/appkit/nsfont"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle": {
      "abstract": [
        {
          "text": "Constants that specify the preferred text styles you use with fonts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextStyle"
        }
      ],
      "role": "symbol",
      "title": "NSFont.TextStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/body": {
      "abstract": [
        {
          "text": "The font you use for body text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "body"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/body",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleBody"
        }
      ],
      "role": "symbol",
      "title": "body",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/body"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/callout": {
      "abstract": [
        {
          "text": "The font you use for callouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/callout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleCallout"
        }
      ],
      "role": "symbol",
      "title": "callout",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/callout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/caption1": {
      "abstract": [
        {
          "text": "The font you use for standard captions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "caption1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/caption1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleCaption1"
        }
      ],
      "role": "symbol",
      "title": "caption1",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/caption1"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/caption2": {
      "abstract": [
        {
          "text": "The font you use for alternate captions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "caption2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/caption2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleCaption2"
        }
      ],
      "role": "symbol",
      "title": "caption2",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/caption2"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/footnote": {
      "abstract": [
        {
          "text": "The font you use in footnotes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "footnote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/footnote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleFootnote"
        }
      ],
      "role": "symbol",
      "title": "footnote",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/footnote"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/headline": {
      "abstract": [
        {
          "text": "The font you use for headings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/headline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleHeadline"
        }
      ],
      "role": "symbol",
      "title": "headline",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/headline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new instance with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/largeTitle": {
      "abstract": [
        {
          "text": "The font you use for large titles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "largeTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/largeTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleLargeTitle"
        }
      ],
      "role": "symbol",
      "title": "largeTitle",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/largetitle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/subheadline": {
      "abstract": [
        {
          "text": "The font you use for subheadings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subheadline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/subheadline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleSubheadline"
        }
      ],
      "role": "symbol",
      "title": "subheadline",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/subheadline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title1": {
      "abstract": [
        {
          "text": "The font you use for first-level hierarchical headings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleTitle1"
        }
      ],
      "role": "symbol",
      "title": "title1",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/title1"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title2": {
      "abstract": [
        {
          "text": "The font you use for second-level hierarchical headings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleTitle2"
        }
      ],
      "role": "symbol",
      "title": "title2",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/title2"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title3": {
      "abstract": [
        {
          "text": "The font you use for third-level hierarchical headings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleTitle3"
        }
      ],
      "role": "symbol",
      "title": "title3",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/title3"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyleOptionKey": {
      "abstract": [
        {
          "text": "The options that you apply when requesting the font or font descriptor of a preferred text style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextStyleOptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyleOptionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextStyleOptionKey"
        }
      ],
      "role": "symbol",
      "title": "NSFont.TextStyleOptionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyleoptionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight": {
      "abstract": [
        {
          "text": "System-defined font-weight values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Weight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Weight"
        }
      ],
      "role": "symbol",
      "title": "NSFont.Weight",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/weight"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/boldSystemFont(ofSize:)": {
      "abstract": [
        {
          "text": "Returns the standard system font in boldface type with the specified size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boldSystemFont"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/boldSystemFont(ofSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "boldSystemFontOfSize:"
        }
      ],
      "role": "symbol",
      "title": "boldSystemFont(ofSize:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/boldsystemfont(ofsize:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/monospacedDigitSystemFont(ofSize:weight:)": {
      "abstract": [
        {
          "text": "Returns a version of the standard system font that contains monospaced digit glyphs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monospacedDigitSystemFont"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontWeight",
          "text": "Weight"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/monospacedDigitSystemFont(ofSize:weight:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "monospacedDigitSystemFontOfSize:weight:"
        }
      ],
      "role": "symbol",
      "title": "monospacedDigitSystemFont(ofSize:weight:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/monospaceddigitsystemfont(ofsize:weight:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/monospacedSystemFont(ofSize:weight:)": {
      "abstract": [
        {
          "text": "Returns a monospace version of the system font with the specified size and weight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monospacedSystemFont"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontWeight",
          "text": "Weight"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/monospacedSystemFont(ofSize:weight:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "monospacedSystemFontOfSize:weight:"
        }
      ],
      "role": "symbol",
      "title": "monospacedSystemFont(ofSize:weight:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/monospacedsystemfont(ofsize:weight:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/preferredFont(forTextStyle:options:)": {
      "abstract": [
        {
          "text": "Returns the font associated with the text style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredFont"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forTextStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyleOptionKey",
          "text": "TextStyleOptionKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/preferredFont(forTextStyle:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredFontForTextStyle:options:"
        }
      ],
      "role": "symbol",
      "title": "preferredFont(forTextStyle:options:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/preferredfont(fortextstyle:options:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/smallSystemFontSize": {
      "abstract": [
        {
          "text": "Returns the size of the standard small system font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smallSystemFontSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/smallSystemFontSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "smallSystemFontSize"
        }
      ],
      "role": "symbol",
      "title": "smallSystemFontSize",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/smallsystemfontsize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/systemFont(ofSize:)": {
      "abstract": [
        {
          "text": "Returns the standard system font with the specified size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemFont"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/systemFont(ofSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemFontOfSize:"
        }
      ],
      "role": "symbol",
      "title": "systemFont(ofSize:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/systemfont(ofsize:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/systemFont(ofSize:weight:)": {
      "abstract": [
        {
          "text": "Returns the standard system font with the specified size and weight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemFont"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontWeight",
          "text": "Weight"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/systemFont(ofSize:weight:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemFontOfSize:weight:"
        }
      ],
      "role": "symbol",
      "title": "systemFont(ofSize:weight:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/systemfont(ofsize:weight:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/systemFontSize": {
      "abstract": [
        {
          "text": "Returns the size of the standard system font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemFontSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/systemFontSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemFontSize"
        }
      ],
      "role": "symbol",
      "title": "systemFontSize",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/systemfontsize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/preferredFontDescriptor(forTextStyle:options:)": {
      "abstract": [
        {
          "text": "Returns a font descriptor that contains the text style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredFontDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forTextStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyleOptionKey",
          "text": "TextStyleOptionKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/preferredFontDescriptor(forTextStyle:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredFontDescriptorForTextStyle:options:"
        }
      ],
      "role": "symbol",
      "title": "preferredFontDescriptor(forTextStyle:options:)",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/preferredfontdescriptor(fortextstyle:options:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-System-Fonts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFont/preferredFont(forTextStyle:options:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/systemFont(ofSize:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/systemFont(ofSize:weight:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/boldSystemFont(ofSize:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/monospacedSystemFont(ofSize:weight:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/monospacedDigitSystemFont(ofSize:weight:)",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/systemFontSize",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/smallSystemFontSize",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyleOptionKey"
      ],
      "title": "Creating System Fonts"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/body",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/callout",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/caption1",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/caption2",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/footnote",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/headline",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/subheadline",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/largeTitle",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title1",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title2",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title3"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFontTextStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/body",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/callout",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/caption1",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/caption2",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/footnote",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/headline",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/subheadline",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/largeTitle",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title1",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title2",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title3"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-System-Fonts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFont/preferredFont(forTextStyle:options:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/systemFont(ofSize:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/systemFont(ofSize:weight:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/boldSystemFont(ofSize:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/monospacedSystemFont(ofSize:weight:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/monospacedDigitSystemFont(ofSize:weight:)",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/systemFontSize",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/smallSystemFontSize",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/Weight",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyleOptionKey"
              ],
              "title": "Creating System Fonts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFontTextStyle"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1systemFontSize/title",
          "value": "systemFontSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1systemFontSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemFontSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1smallSystemFontSize/title",
          "value": "smallSystemFontSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1smallSystemFontSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "smallSystemFontSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1caption1/title",
          "value": "NSFontTextStyleCaption1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1caption1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleCaption1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1monospacedSystemFont(ofSize:weight:)/title",
          "value": "monospacedSystemFontOfSize:weight:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1monospacedSystemFont(ofSize:weight:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "monospacedSystemFontOfSize:weight:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1boldSystemFont(ofSize:)/title",
          "value": "boldSystemFontOfSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1boldSystemFont(ofSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "boldSystemFontOfSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1title1/title",
          "value": "NSFontTextStyleTitle1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1title1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleTitle1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/title",
          "value": "NSFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyleOptionKey/title",
          "value": "NSFontTextStyleOptionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyleOptionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleOptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyleOptionKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleOptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1headline/title",
          "value": "NSFontTextStyleHeadline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1headline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleHeadline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1largeTitle/title",
          "value": "NSFontTextStyleLargeTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1largeTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleLargeTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1body/title",
          "value": "NSFontTextStyleBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1body/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight/title",
          "value": "NSFontWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1Weight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1preferredFont(forTextStyle:options:)/title",
          "value": "preferredFontForTextStyle:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1preferredFont(forTextStyle:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "preferredFontForTextStyle:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1preferredFontDescriptor(forTextStyle:options:)/title",
          "value": "preferredFontDescriptorForTextStyle:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1preferredFontDescriptor(forTextStyle:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "preferredFontDescriptorForTextStyle:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1callout/title",
          "value": "NSFontTextStyleCallout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1callout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleCallout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1monospacedDigitSystemFont(ofSize:weight:)/title",
          "value": "monospacedDigitSystemFontOfSize:weight:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1monospacedDigitSystemFont(ofSize:weight:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "monospacedDigitSystemFontOfSize:weight:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1systemFont(ofSize:weight:)/title",
          "value": "systemFontOfSize:weight:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1systemFont(ofSize:weight:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "systemFontOfSize:weight:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1footnote/title",
          "value": "NSFontTextStyleFootnote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1footnote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleFootnote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1caption2/title",
          "value": "NSFontTextStyleCaption2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1caption2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleCaption2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1title3/title",
          "value": "NSFontTextStyleTitle3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1title3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleTitle3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1subheadline/title",
          "value": "NSFontTextStyleSubheadline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1subheadline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleSubheadline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle/title",
          "value": "NSFontTextStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1title2/title",
          "value": "NSFontTextStyleTitle2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1title2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleTitle2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1systemFont(ofSize:)/title",
          "value": "systemFontOfSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1systemFont(ofSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "systemFontOfSize:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfont/textstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfont/textstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
