{
  "abstract": [
    {
      "text": "No known attribute.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/unknown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INMessageAttribute@INMessageAttributeUnknown",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unknown"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INMessageAttributeUnknown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INMessageAttribute.unknown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unknown"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute": {
      "abstract": [
        {
          "text": "Constants that indicate an attribute of a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMessageAttribute"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageAttribute"
        }
      ],
      "role": "symbol",
      "title": "INMessageAttribute",
      "type": "topic",
      "url": "/documentation/intents/inmessageattribute"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/flagged": {
      "abstract": [
        {
          "text": "The message has been flagged.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flagged"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/flagged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageAttributeFlagged"
        }
      ],
      "role": "symbol",
      "title": "INMessageAttribute.flagged",
      "type": "topic",
      "url": "/documentation/intents/inmessageattribute/flagged"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/played": {
      "abstract": [
        {
          "text": "The message has been played.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "played"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/played",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageAttributePlayed"
        }
      ],
      "role": "symbol",
      "title": "INMessageAttribute.played",
      "type": "topic",
      "url": "/documentation/intents/inmessageattribute/played"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/read": {
      "abstract": [
        {
          "text": "The message is marked as read.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "read"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/read",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageAttributeRead"
        }
      ],
      "role": "symbol",
      "title": "INMessageAttribute.read",
      "type": "topic",
      "url": "/documentation/intents/inmessageattribute/read"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/unflagged": {
      "abstract": [
        {
          "text": "The message has not been flagged.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unflagged"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/unflagged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageAttributeUnflagged"
        }
      ],
      "role": "symbol",
      "title": "INMessageAttribute.unflagged",
      "type": "topic",
      "url": "/documentation/intents/inmessageattribute/unflagged"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/unknown": {
      "abstract": [
        {
          "text": "No known attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageAttributeUnknown"
        }
      ],
      "role": "symbol",
      "title": "INMessageAttribute.unknown",
      "type": "topic",
      "url": "/documentation/intents/inmessageattribute/unknown"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/unread": {
      "abstract": [
        {
          "text": "The message is marked as unread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unread"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/unread",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageAttributeUnread"
        }
      ],
      "role": "symbol",
      "title": "INMessageAttribute.unread",
      "type": "topic",
      "url": "/documentation/intents/inmessageattribute/unread"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/read",
        "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/unread",
        "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/flagged",
        "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/unflagged",
        "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/played"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INMessageAttributeUnknown"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageAttributeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/read",
                "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/unread",
                "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/flagged",
                "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/unflagged",
                "doc://com.apple.sirikit/documentation/Intents/INMessageAttribute/played"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INMessageAttributeUnknown"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageAttribute~1flagged/title",
          "value": "INMessageAttributeFlagged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageAttribute~1flagged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageAttributeFlagged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageAttribute~1played/title",
          "value": "INMessageAttributePlayed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageAttribute~1played/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageAttributePlayed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageAttribute~1unread/title",
          "value": "INMessageAttributeUnread"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageAttribute~1unread/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageAttributeUnread"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageAttribute~1read/title",
          "value": "INMessageAttributeRead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageAttribute~1read/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageAttributeRead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageAttribute~1unflagged/title",
          "value": "INMessageAttributeUnflagged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageAttribute~1unflagged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageAttributeUnflagged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageAttribute/title",
          "value": "INMessageAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageAttribute~1unknown/title",
          "value": "INMessageAttributeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageAttribute~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageAttributeUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inmessageattribute/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inmessageattribute/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
