{
  "abstract": [
    {
      "text": "A Boolean-like unit of measure.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/boolean"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AudioUnitParameterUnit@kAudioUnitParameterUnit_Boolean",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "boolean"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioUnitParameterUnit_Boolean"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AudioUnitParameterUnit.boolean"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "boolean"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A value of 0.0 means ",
              "type": "text"
            },
            {
              "code": "FALSE",
              "type": "codeVoice"
            },
            {
              "text": " and a nonzero value means ",
              "type": "text"
            },
            {
              "code": "TRUE",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit": {
      "abstract": [
        {
          "text": "The unit-of-measure for an audio unit parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioUnitParameterUnit"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioUnitParameterUnit"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/BPM": {
      "abstract": [
        {
          "text": "A whole-number unit of measure for musical tempo, representing beats per minute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BPM"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/BPM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_BPM"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.BPM",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/bpm"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/absoluteCents": {
      "abstract": [
        {
          "text": "An absolute unit of measure for the musical pitch of a note.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "absoluteCents"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/absoluteCents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_AbsoluteCents"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.absoluteCents",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/absolutecents"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/beats": {
      "abstract": [
        {
          "text": "A time unit of measure in musical beats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beats"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/beats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Beats"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.beats",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/beats"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/boolean": {
      "abstract": [
        {
          "text": "A Boolean-like unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boolean"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/boolean",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Boolean"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.boolean",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/boolean"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/cents": {
      "abstract": [
        {
          "text": "A logarithmic unit of measure for a musical interval between two notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cents"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/cents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Cents"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.cents",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/cents"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/customUnit": {
      "abstract": [
        {
          "text": "A custom unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customUnit"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/customUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_CustomUnit"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.customUnit",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/customunit"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/decibels": {
      "abstract": [
        {
          "text": "A logarithmic unit of measure representing the ratio between two audio levels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decibels"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/decibels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Decibels"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.decibels",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/decibels"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/degrees": {
      "abstract": [
        {
          "text": "An angular degree unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "degrees"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/degrees",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Degrees"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.degrees",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/degrees"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/equalPowerCrossfade": {
      "abstract": [
        {
          "text": "An audio power unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "equalPowerCrossfade"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/equalPowerCrossfade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_EqualPowerCrossfade"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.equalPowerCrossfade",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/equalpowercrossfade"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/generic": {
      "abstract": [
        {
          "text": "A generic unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "generic"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/generic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Generic"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.generic",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/generic"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/hertz": {
      "abstract": [
        {
          "text": "A hertz unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hertz"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/hertz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Hertz"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.hertz",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/hertz"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/indexed": {
      "abstract": [
        {
          "text": "An indexed unit of measure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexed"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/indexed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Indexed"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.indexed",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/indexed"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/linearGain": {
      "abstract": [
        {
          "text": "A linear unit of measure representing the difference between two audio levels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linearGain"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/linearGain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_LinearGain"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.linearGain",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/lineargain"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/meters": {
      "abstract": [
        {
          "text": "A distance unit of measure, corresponding to meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "meters"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/meters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_Meters"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.meters",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/meters"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midiController": {
      "abstract": [
        {
          "text": "A whole-number unit of measure corresponding to standard MIDI control numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "midiController"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midiController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_MIDIController"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.midiController",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/midicontroller"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midiNoteNumber": {
      "abstract": [
        {
          "text": "A whole-number unit of measure corresponding to audio frequency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "midiNoteNumber"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midiNoteNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioUnitParameterUnit_MIDINoteNumber"
        }
      ],
      "role": "symbol",
      "title": "AudioUnitParameterUnit.midiNoteNumber",
      "type": "topic",
      "url": "/documentation/audiotoolbox/audiounitparameterunit/midinotenumber"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/absoluteCents",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/BPM",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/beats",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/cents",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/customUnit",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/decibels",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/degrees",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/equalPowerCrossfade",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/generic",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/hertz",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/indexed",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/linearGain",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midiController",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midiNoteNumber",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/meters"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioUnitParameterUnit_Boolean"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Boolean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/absoluteCents",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/BPM",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/beats",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/cents",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/customUnit",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/decibels",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/degrees",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/equalPowerCrossfade",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/generic",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/hertz",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/indexed",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/linearGain",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midiController",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/midiNoteNumber",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AudioUnitParameterUnit/meters"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioUnitParameterUnit_Boolean"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1indexed/title",
          "value": "kAudioUnitParameterUnit_Indexed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1indexed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Indexed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1equalPowerCrossfade/title",
          "value": "kAudioUnitParameterUnit_EqualPowerCrossfade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1equalPowerCrossfade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_EqualPowerCrossfade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1meters/title",
          "value": "kAudioUnitParameterUnit_Meters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1meters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Meters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1linearGain/title",
          "value": "kAudioUnitParameterUnit_LinearGain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1linearGain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_LinearGain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1boolean/title",
          "value": "kAudioUnitParameterUnit_Boolean"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1boolean/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Boolean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit/title",
          "value": "AudioUnitParameterUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioUnitParameterUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1BPM/title",
          "value": "kAudioUnitParameterUnit_BPM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1BPM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_BPM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1degrees/title",
          "value": "kAudioUnitParameterUnit_Degrees"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1degrees/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Degrees"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1cents/title",
          "value": "kAudioUnitParameterUnit_Cents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1cents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Cents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1midiController/title",
          "value": "kAudioUnitParameterUnit_MIDIController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1midiController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_MIDIController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1midiNoteNumber/title",
          "value": "kAudioUnitParameterUnit_MIDINoteNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1midiNoteNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_MIDINoteNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1beats/title",
          "value": "kAudioUnitParameterUnit_Beats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1beats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Beats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1customUnit/title",
          "value": "kAudioUnitParameterUnit_CustomUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1customUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_CustomUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1generic/title",
          "value": "kAudioUnitParameterUnit_Generic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1generic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Generic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1hertz/title",
          "value": "kAudioUnitParameterUnit_Hertz"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1hertz/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Hertz"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1absoluteCents/title",
          "value": "kAudioUnitParameterUnit_AbsoluteCents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1absoluteCents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_AbsoluteCents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1decibels/title",
          "value": "kAudioUnitParameterUnit_Decibels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AudioUnitParameterUnit~1decibels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioUnitParameterUnit_Decibels"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/audiounitparameterunit/boolean"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/audiounitparameterunit/boolean"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
