{
  "abstract": [
    {
      "text": "The table view chooses an appropriate animation style for you.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITableView",
        "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/automatic"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UITableViewRowAnimation@UITableViewRowAnimationAutomatic",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "automatic"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITableViewRowAnimationAutomatic"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UITableView.RowAnimation.automatic"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "automatic"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView": {
      "abstract": [
        {
          "text": "A view that presents data using rows in a single column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableView"
        }
      ],
      "role": "symbol",
      "title": "UITableView",
      "type": "topic",
      "url": "/documentation/uikit/uitableview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation": {
      "abstract": [
        {
          "text": "The type of animation to use when inserting or deleting rows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RowAnimation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RowAnimation"
        }
      ],
      "role": "symbol",
      "title": "UITableView.RowAnimation",
      "type": "topic",
      "url": "/documentation/uikit/uitableview/rowanimation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/automatic": {
      "abstract": [
        {
          "text": "The table view chooses an appropriate animation style for you.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewRowAnimationAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UITableView.RowAnimation.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uitableview/rowanimation/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/bottom": {
      "abstract": [
        {
          "text": "The inserted row or rows slide in from the bottom; the deleted row or rows slide out toward the bottom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewRowAnimationBottom"
        }
      ],
      "role": "symbol",
      "title": "UITableView.RowAnimation.bottom",
      "type": "topic",
      "url": "/documentation/uikit/uitableview/rowanimation/bottom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/fade": {
      "abstract": [
        {
          "text": "The inserted or deleted row or rows fade into or out of the table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fade"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/fade",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewRowAnimationFade"
        }
      ],
      "role": "symbol",
      "title": "UITableView.RowAnimation.fade",
      "type": "topic",
      "url": "/documentation/uikit/uitableview/rowanimation/fade"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/left": {
      "abstract": [
        {
          "text": "The inserted row or rows slide in from the left; the deleted row or rows slide out to the left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewRowAnimationLeft"
        }
      ],
      "role": "symbol",
      "title": "UITableView.RowAnimation.left",
      "type": "topic",
      "url": "/documentation/uikit/uitableview/rowanimation/left"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/middle": {
      "abstract": [
        {
          "text": "The table view attempts to keep the old and new cells centered in the space they did or will occupy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "middle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/middle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewRowAnimationMiddle"
        }
      ],
      "role": "symbol",
      "title": "UITableView.RowAnimation.middle",
      "type": "topic",
      "url": "/documentation/uikit/uitableview/rowanimation/middle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/none": {
      "abstract": [
        {
          "text": "The inserted or deleted rows use the default animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewRowAnimationNone"
        }
      ],
      "role": "symbol",
      "title": "UITableView.RowAnimation.none",
      "type": "topic",
      "url": "/documentation/uikit/uitableview/rowanimation/none"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/right": {
      "abstract": [
        {
          "text": "The inserted row or rows slide in from the right; the deleted row or rows slide out to the right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewRowAnimationRight"
        }
      ],
      "role": "symbol",
      "title": "UITableView.RowAnimation.right",
      "type": "topic",
      "url": "/documentation/uikit/uitableview/rowanimation/right"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/top": {
      "abstract": [
        {
          "text": "The inserted row or rows slide in from the top; the deleted row or rows slide out toward the top.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewRowAnimationTop"
        }
      ],
      "role": "symbol",
      "title": "UITableView.RowAnimation.top",
      "type": "topic",
      "url": "/documentation/uikit/uitableview/rowanimation/top"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/fade",
        "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/right",
        "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/left",
        "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/top",
        "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/bottom",
        "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/none",
        "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/middle"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITableViewRowAnimationAutomatic"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewRowAnimationAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/fade",
                "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/right",
                "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/left",
                "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/top",
                "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/bottom",
                "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/none",
                "doc://com.apple.uikit/documentation/UIKit/UITableView/RowAnimation/middle"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UITableViewRowAnimationAutomatic"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation/title",
          "value": "UITableViewRowAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewRowAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewRowAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation~1automatic/title",
          "value": "UITableViewRowAnimationAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewRowAnimationAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation~1fade/title",
          "value": "UITableViewRowAnimationFade"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation~1fade/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewRowAnimationFade"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation~1none/title",
          "value": "UITableViewRowAnimationNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewRowAnimationNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/title",
          "value": "UITableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation~1left/title",
          "value": "UITableViewRowAnimationLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewRowAnimationLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation~1middle/title",
          "value": "UITableViewRowAnimationMiddle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation~1middle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewRowAnimationMiddle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation~1bottom/title",
          "value": "UITableViewRowAnimationBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewRowAnimationBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation~1right/title",
          "value": "UITableViewRowAnimationRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewRowAnimationRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation~1top/title",
          "value": "UITableViewRowAnimationTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1RowAnimation~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewRowAnimationTop"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitableview/rowanimation/automatic"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitableview/rowanimation/automatic"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
