{
  "abstract": [
    {
      "text": "An array of elements that refers to open auto-renewable subscription renewals or ones that failed in the past.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "App Store Server Notifications",
      "versions": [
        "2.0",
        "2.13"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appstoreservernotifications/documentation/AppStoreServerNotifications",
        "doc://com.apple.appstoreservernotifications/documentation/AppStoreServerNotifications/unified_receipt"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "data",
    "url": "doc://com.apple.appstoreservernotifications/documentation/AppStoreServerNotifications/unified_receipt/Pending_renewal_info-data.dictionary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "data:store_s2s:unified_receipt.Pending_renewal_info",
    "fragments": [
      {
        "kind": "text",
        "text": "object "
      },
      {
        "kind": "identifier",
        "text": "unified_receipt.Pending_renewal_info"
      }
    ],
    "modules": [
      {
        "name": "App Store Server Notifications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "unified_receipt.Pending_renewal_info"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "1.2",
        "name": "App Store Server Notifications"
      }
    ],
    "role": "symbol",
    "roleHeading": "Object",
    "symbolKind": "dictionary",
    "title": "unified_receipt.Pending_renewal_info"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "data"
          ],
          "platforms": [
            "Unsupported OS: App Store Server Notifications"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "unified_receipt.Pending_renewal_info"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "items": [
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The current renewal preference for the auto-renewable subscription. The value for this key corresponds to the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKMutablePayment/productIdentifier",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property of the product that the customer’s subscription renews.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "auto_renew_product_id",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [
            {
              "kind": "allowedValues",
              "values": [
                "1",
                "0"
              ]
            }
          ],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The current renewal status for the auto-renewable subscription. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/auto_renew_status",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "auto_renew_status",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [
            {
              "kind": "allowedValues",
              "values": [
                "1",
                "2",
                "3",
                "4",
                "5"
              ]
            }
          ],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The reason a subscription expired. This field is only present for a receipt that contains an expired, auto-renewable subscription. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/expiration_intent",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "expiration_intent",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The time at which the grace period for subscription renewals expires, in a date-time format similar to the ISO 8601.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "grace_period_expires_date",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The time at which the grace period for subscription renewals expires, in UNIX epoch time format, in milliseconds. This key is only present for apps that have Billing Grace Period enabled and when the user experiences a billing error at the time of renewal. Use this time format for processing dates.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "grace_period_expires_date_ms",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The time at which the grace period for subscription renewals expires, in the Pacific Time zone.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "grace_period_expires_date_pst",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [
            {
              "kind": "allowedValues",
              "values": [
                "1",
                "0"
              ]
            }
          ],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A flag that indicates Apple is attempting to renew an expired subscription automatically. This field is only present if an auto-renewable subscription is in the billing retry state. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/is_in_billing_retry_period",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "is_in_billing_retry_period",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The reference name of a subscription offer you configured in App Store Connect. This field is present when a customer redeemed a subscription offer code. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/offer_code_ref_name",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "offer_code_ref_name",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The transaction identifier of the original purchase.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "original_transaction_id",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [
            {
              "kind": "allowedValues",
              "values": [
                "1",
                "0"
              ]
            }
          ],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The price consent status for a subscription price increase. This field is present only if App Store notified the customer of the price increase. The default value is ",
                  "type": "text"
                },
                {
                  "code": "\"0\"",
                  "type": "codeVoice"
                },
                {
                  "text": " and changes to ",
                  "type": "text"
                },
                {
                  "code": "\"1\"",
                  "type": "codeVoice"
                },
                {
                  "text": " if the customer consents.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "price_consent_status",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The unique identifier of the product purchased. You provide this value when creating the product in App Store Connect, and it corresponds to the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPayment/productIdentifier",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property of the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPayment",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " object stored in the transaction’s ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPaymentTransaction/payment",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "product_id",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The identifier of the promotional offer for an auto-renewable subscription that the user redeemed. You provide this value in the Promotional Offer Identifier field when you create the promotional offer in App Store Connect. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/promotional_offer_id",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "promotional_offer_id",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        },
        {
          "attributes": [
            {
              "kind": "allowedValues",
              "values": [
                "1",
                "0"
              ]
            }
          ],
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "price_increase_status",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        }
      ],
      "kind": "properties",
      "title": "Properties"
    }
  ],
  "references": {
    "doc://com.apple.appstoreservernotifications/documentation/AppStoreServerNotifications": {
      "abstract": [
        {
          "text": "Monitor In-App Purchase events in real time and learn of unreported external purchase tokens, with server notifications from the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appstoreservernotifications/documentation/AppStoreServerNotifications",
      "kind": "symbol",
      "role": "collection",
      "title": "App Store Server Notifications",
      "type": "topic",
      "url": "/documentation/appstoreservernotifications"
    },
    "doc://com.apple.appstoreservernotifications/documentation/AppStoreServerNotifications/unified_receipt": {
      "abstract": [
        {
          "text": "An object that contains information about the most recent in-app purchase transactions for the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "unified_receipt"
        }
      ],
      "identifier": "doc://com.apple.appstoreservernotifications/documentation/AppStoreServerNotifications/unified_receipt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unified_receipt"
        }
      ],
      "role": "symbol",
      "title": "unified_receipt",
      "type": "topic",
      "url": "/documentation/appstoreservernotifications/unified_receipt"
    },
    "doc://com.apple.appstoreservernotifications/documentation/AppStoreServerNotifications/unified_receipt/Latest_receipt_info-data.dictionary": {
      "abstract": [
        {
          "text": "An object that contains information about the latest in-app subscription transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "unified_receipt.Latest_receipt_info"
        }
      ],
      "identifier": "doc://com.apple.appstoreservernotifications/documentation/AppStoreServerNotifications/unified_receipt/Latest_receipt_info-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unified_receipt.Latest_receipt_info"
        }
      ],
      "role": "symbol",
      "title": "unified_receipt.Latest_receipt_info",
      "type": "topic",
      "url": "/documentation/appstoreservernotifications/unified_receipt/latest_receipt_info-data.dictionary"
    },
    "doc://com.apple.appstoreservernotifications/documentation/AppStoreServerNotifications/unified_receipt/Pending_renewal_info-data.dictionary": {
      "abstract": [
        {
          "text": "An array of elements that refers to open auto-renewable subscription renewals or ones that failed in the past.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "unified_receipt.Pending_renewal_info"
        }
      ],
      "identifier": "doc://com.apple.appstoreservernotifications/documentation/AppStoreServerNotifications/unified_receipt/Pending_renewal_info-data.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unified_receipt.Pending_renewal_info"
        }
      ],
      "role": "symbol",
      "title": "unified_receipt.Pending_renewal_info",
      "type": "topic",
      "url": "/documentation/appstoreservernotifications/unified_receipt/pending_renewal_info-data.dictionary"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKMutablePayment/productIdentifier": {
      "abstract": [
        {
          "text": "A string that identifies a product that can be purchased from within your app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKMutablePayment/productIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "productIdentifier",
      "type": "topic",
      "url": "/documentation/StoreKit/SKMutablePayment/productIdentifier"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKPayment": {
      "abstract": [
        {
          "text": "A request to the App Store to process payment for additional functionality that your app offers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPayment"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPayment",
      "kind": "symbol",
      "role": "symbol",
      "title": "SKPayment",
      "type": "topic",
      "url": "/documentation/StoreKit/SKPayment"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKPayment/productIdentifier": {
      "abstract": [
        {
          "text": "A string used to identify a product that can be purchased from within your app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "productIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPayment/productIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "productIdentifier",
      "type": "topic",
      "url": "/documentation/StoreKit/SKPayment/productIdentifier"
    },
    "doc://com.apple.documentation/documentation/StoreKit/SKPaymentTransaction/payment": {
      "abstract": [
        {
          "text": "The payment for the transaction.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "payment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKPayment",
          "text": "SKPayment"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/StoreKit/SKPaymentTransaction/payment",
      "kind": "symbol",
      "role": "symbol",
      "title": "payment",
      "type": "topic",
      "url": "/documentation/StoreKit/SKPaymentTransaction/payment"
    },
    "doc://com.apple.documentation/documentation/appstorereceipts/auto_renew_status": {
      "abstract": [
        {
          "text": "The renewal status for the auto-renewable subscription.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "type "
        },
        {
          "kind": "identifier",
          "text": "auto_renew_status"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/auto_renew_status",
      "kind": "symbol",
      "role": "symbol",
      "title": "auto_renew_status",
      "type": "topic",
      "url": "/documentation/appstorereceipts/auto_renew_status"
    },
    "doc://com.apple.documentation/documentation/appstorereceipts/expiration_intent": {
      "abstract": [
        {
          "text": "The reason a subscription expires.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "type "
        },
        {
          "kind": "identifier",
          "text": "expiration_intent"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/expiration_intent",
      "kind": "symbol",
      "role": "symbol",
      "title": "expiration_intent",
      "type": "topic",
      "url": "/documentation/appstorereceipts/expiration_intent"
    },
    "doc://com.apple.documentation/documentation/appstorereceipts/is_in_billing_retry_period": {
      "abstract": [
        {
          "text": "An indicator of whether an auto-renewable subscription is in the billing retry period.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "type "
        },
        {
          "kind": "identifier",
          "text": "is_in_billing_retry_period"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/is_in_billing_retry_period",
      "kind": "symbol",
      "role": "symbol",
      "title": "is_in_billing_retry_period",
      "type": "topic",
      "url": "/documentation/appstorereceipts/is_in_billing_retry_period"
    },
    "doc://com.apple.documentation/documentation/appstorereceipts/offer_code_ref_name": {
      "abstract": [
        {
          "text": "The offer-reference name of the subscription offer code that the customer redeems.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "type "
        },
        {
          "kind": "identifier",
          "text": "offer_code_ref_name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/offer_code_ref_name",
      "kind": "symbol",
      "role": "symbol",
      "title": "offer_code_ref_name",
      "type": "topic",
      "url": "/documentation/appstorereceipts/offer_code_ref_name"
    },
    "doc://com.apple.documentation/documentation/appstorereceipts/promotional_offer_id": {
      "abstract": [
        {
          "text": "The identifier of the promotional offer for an auto-renewable subscription that the user redeems.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "type "
        },
        {
          "kind": "identifier",
          "text": "promotional_offer_id"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/appstorereceipts/promotional_offer_id",
      "kind": "symbol",
      "role": "symbol",
      "title": "promotional_offer_id",
      "type": "topic",
      "url": "/documentation/appstorereceipts/promotional_offer_id"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appstoreservernotifications/documentation/AppStoreServerNotifications/unified_receipt/Latest_receipt_info-data.dictionary"
      ],
      "title": "Objects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKPayment~1productIdentifier/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "productIdentifier"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKPaymentTransaction~1payment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SKPayment",
              "text": "SKPayment"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "payment"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKMutablePayment~1productIdentifier/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readwrite"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "productIdentifier"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1StoreKit~1SKPayment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKPayment"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appstoreservernotifications/unified_receipt/pending_renewal_info-data.dictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "data"
        }
      ]
    }
  ]
}
