{
  "abstract": [
    {
      "text": "Sets the color of the message to gray.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mailkit/documentation/MailKit",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/gray"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MEMessageActionMessageColor@MEMessageActionMessageColorGray",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "gray"
      }
    ],
    "modules": [
      {
        "name": "MailKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MEMessageActionMessageColorGray"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MEMessageAction.MessageColor.gray"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gray"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mailkit/documentation/MailKit": {
      "abstract": [
        {
          "text": "Secure, customize, and act on email messages that users send and receive.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MailKit",
      "type": "topic",
      "url": "/documentation/mailkit"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction": {
      "abstract": [
        {
          "text": "An action the system performs on a message, such as setting a color or archiving it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEMessageAction"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageAction"
        }
      ],
      "role": "symbol",
      "title": "MEMessageAction",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor": {
      "abstract": [
        {
          "text": "A color that the system uses to display a message in the message list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MessageColor"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MessageColor"
        }
      ],
      "role": "symbol",
      "title": "MEMessageAction.MessageColor",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/messagecolor"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/blue": {
      "abstract": [
        {
          "text": "Sets the color of the message to blue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blue"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/blue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageActionMessageColorBlue"
        }
      ],
      "role": "symbol",
      "title": "MEMessageAction.MessageColor.blue",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/messagecolor/blue"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/gray": {
      "abstract": [
        {
          "text": "Sets the color of the message to gray.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gray"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/gray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageActionMessageColorGray"
        }
      ],
      "role": "symbol",
      "title": "MEMessageAction.MessageColor.gray",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/messagecolor/gray"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/green": {
      "abstract": [
        {
          "text": "Sets the color of the message to green.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "green"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/green",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageActionMessageColorGreen"
        }
      ],
      "role": "symbol",
      "title": "MEMessageAction.MessageColor.green",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/messagecolor/green"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/none": {
      "abstract": [
        {
          "text": "Clears the color of the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageActionMessageColorNone"
        }
      ],
      "role": "symbol",
      "title": "MEMessageAction.MessageColor.none",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/messagecolor/none"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/orange": {
      "abstract": [
        {
          "text": "Sets the color of the message to orange.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orange"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/orange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageActionMessageColorOrange"
        }
      ],
      "role": "symbol",
      "title": "MEMessageAction.MessageColor.orange",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/messagecolor/orange"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/purple": {
      "abstract": [
        {
          "text": "Sets the color of the message to purple.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "purple"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/purple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageActionMessageColorPurple"
        }
      ],
      "role": "symbol",
      "title": "MEMessageAction.MessageColor.purple",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/messagecolor/purple"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/red": {
      "abstract": [
        {
          "text": "Sets the color of the message to red.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "red"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/red",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageActionMessageColorRed"
        }
      ],
      "role": "symbol",
      "title": "MEMessageAction.MessageColor.red",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/messagecolor/red"
    },
    "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/yellow": {
      "abstract": [
        {
          "text": "Sets the color of the message to yellow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yellow"
        }
      ],
      "identifier": "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/yellow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEMessageActionMessageColorYellow"
        }
      ],
      "role": "symbol",
      "title": "MEMessageAction.MessageColor.yellow",
      "type": "topic",
      "url": "/documentation/mailkit/memessageaction/messagecolor/yellow"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-a-Message-Color",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/green",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/yellow",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/orange",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/red",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/purple",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/blue",
        "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/none"
      ],
      "title": "Specifying a Message Color"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MEMessageActionMessageColorGray"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionMessageColorGray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mailkit/documentation/MailKit",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-a-Message-Color",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/green",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/yellow",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/orange",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/red",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/purple",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/blue",
                "doc://com.apple.mailkit/documentation/MailKit/MEMessageAction/MessageColor/none"
              ],
              "title": "Specifying a Message Color"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MEMessageActionMessageColorGray"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor~1purple/title",
          "value": "MEMessageActionMessageColorPurple"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor~1purple/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionMessageColorPurple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor~1gray/title",
          "value": "MEMessageActionMessageColorGray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor~1gray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionMessageColorGray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor~1orange/title",
          "value": "MEMessageActionMessageColorOrange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor~1orange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionMessageColorOrange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor/title",
          "value": "MEMessageActionMessageColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionMessageColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionMessageColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction/title",
          "value": "MEMessageAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor~1none/title",
          "value": "MEMessageActionMessageColorNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionMessageColorNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor~1red/title",
          "value": "MEMessageActionMessageColorRed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor~1red/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionMessageColorRed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor~1yellow/title",
          "value": "MEMessageActionMessageColorYellow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor~1yellow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionMessageColorYellow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor~1blue/title",
          "value": "MEMessageActionMessageColorBlue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor~1blue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionMessageColorBlue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor~1green/title",
          "value": "MEMessageActionMessageColorGreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mailkit~1documentation~1MailKit~1MEMessageAction~1MessageColor~1green/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEMessageActionMessageColorGreen"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mailkit/memessageaction/messagecolor/gray"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mailkit/memessageaction/messagecolor/gray"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
