{
  "abstract": [
    {
      "text": "An instantiation error that indicates an unknown error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pushtotalk/documentation/PushToTalk",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/unknown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PTInstantiationError@PTInstantiationErrorUnknown",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unknown"
      }
    ],
    "modules": [
      {
        "name": "Push to Talk"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PTInstantiationErrorUnknown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PTInstantiationError.Code.unknown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unknown"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk": {
      "abstract": [
        {
          "text": "Display the system user interface for your app’s Push to Talk services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk",
      "kind": "symbol",
      "role": "collection",
      "title": "Push to Talk",
      "type": "topic",
      "url": "/documentation/pushtotalk"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents an instantiation error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTInstantiationError"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationError"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for instantiation operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError.Code",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/instantiationAlreadyInProgress": {
      "abstract": [
        {
          "text": "An instantiation error that indicates there’s already an in-flight instantiation request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instantiationAlreadyInProgress"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/instantiationAlreadyInProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationErrorInstantiationAlreadyInProgress"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError.Code.instantiationAlreadyInProgress",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code/instantiationalreadyinprogress"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/invalidPlatform": {
      "abstract": [
        {
          "text": "An instantiation error that indicates the API isn’t available on the simulator or macOS devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidPlatform"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/invalidPlatform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationErrorInvalidPlatform"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError.Code.invalidPlatform",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code/invalidplatform"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingBackgroundMode": {
      "abstract": [
        {
          "text": "An instantiation error that indicates the app doesn’t have the background mode in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingBackgroundMode"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingBackgroundMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationErrorMissingBackgroundMode"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError.Code.missingBackgroundMode",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code/missingbackgroundmode"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingEntitlement": {
      "abstract": [
        {
          "text": "An instantiation error that indicates the app is missing the entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingEntitlement"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingEntitlement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationErrorMissingEntitlement"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError.Code.missingEntitlement",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code/missingentitlement"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingPushServerEnvironment": {
      "abstract": [
        {
          "text": "An instantiation error that indicates the app doesn’t have the push notification capability in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingPushServerEnvironment"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingPushServerEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationErrorMissingPushServerEnvironment"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError.Code.missingPushServerEnvironment",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code/missingpushserverenvironment"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/unknown": {
      "abstract": [
        {
          "text": "An instantiation error that indicates an unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTInstantiationErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "PTInstantiationError.Code.unknown",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/invalidPlatform",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingBackgroundMode",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingPushServerEnvironment",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingEntitlement",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/instantiationAlreadyInProgress"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PTInstantiationErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pushtotalk/documentation/PushToTalk",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/invalidPlatform",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingBackgroundMode",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingPushServerEnvironment",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/missingEntitlement",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTInstantiationError-swift.struct/Code/instantiationAlreadyInProgress"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PTInstantiationErrorUnknown"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code/title",
          "value": "PTInstantiationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1instantiationAlreadyInProgress/title",
          "value": "PTInstantiationErrorInstantiationAlreadyInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1instantiationAlreadyInProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationErrorInstantiationAlreadyInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1missingEntitlement/title",
          "value": "PTInstantiationErrorMissingEntitlement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1missingEntitlement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationErrorMissingEntitlement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1missingBackgroundMode/title",
          "value": "PTInstantiationErrorMissingBackgroundMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1missingBackgroundMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationErrorMissingBackgroundMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1missingPushServerEnvironment/title",
          "value": "PTInstantiationErrorMissingPushServerEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1missingPushServerEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationErrorMissingPushServerEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1unknown/title",
          "value": "PTInstantiationErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1invalidPlatform/title",
          "value": "PTInstantiationErrorInvalidPlatform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTInstantiationError-swift.struct~1Code~1invalidPlatform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTInstantiationErrorInvalidPlatform"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pushtotalk/ptinstantiationerror-swift.struct/code/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
