{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/1420190-anonymous"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Anonymous"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsConnectionAutomatic": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached using the current network configuration, but a connection must first be established.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsConnectionAutomatic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsConnectionAutomatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsConnectionAutomatic"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkFlagsConnectionAutomatic",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkflagsconnectionautomatic"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsConnectionRequired": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached using the current network configuration, but a connection must first be established.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsConnectionRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsConnectionRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsConnectionRequired"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkFlagsConnectionRequired",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkflagsconnectionrequired"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsInterventionRequired": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached using the current network configuration, but a connection must first be established.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsInterventionRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsInterventionRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsInterventionRequired"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkFlagsInterventionRequired",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkflagsinterventionrequired"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsIsDirect": {
      "abstract": [
        {
          "text": "Network traffic to the specified node name or address does not go through a gateway, but is routed directly to one of the interfaces in the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsIsDirect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsIsDirect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsIsDirect"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkFlagsIsDirect",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkflagsisdirect"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsIsLocalAddress": {
      "abstract": [
        {
          "text": "The specified node name or address is one associated with a network interface on the current system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsIsLocalAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsIsLocalAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsIsLocalAddress"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkFlagsIsLocalAddress",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkflagsislocaladdress"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsReachable": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached using the current network configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsReachable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsReachable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsReachable"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkFlagsReachable",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkflagsreachable"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsTransientConnection": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached via a transient connection, such as PPP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsTransientConnection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsTransientConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsTransientConnection"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkFlagsTransientConnection",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkflagstransientconnection"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SystemConfiguration Enumerations",
      "type": "topic",
      "url": "/documentation/systemconfiguration/systemconfiguration-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsConnectionAutomatic",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsConnectionRequired",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsInterventionRequired",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsIsDirect",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsIsLocalAddress",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsReachable",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsTransientConnection"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsConnectionAutomatic",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsConnectionRequired",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsInterventionRequired",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsIsDirect",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsIsLocalAddress",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsReachable",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsTransientConnection"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsConnectionRequired/title",
          "value": "kSCNetworkFlagsConnectionRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsConnectionRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkFlagsConnectionRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsReachable/title",
          "value": "kSCNetworkFlagsReachable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsReachable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkFlagsReachable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsIsLocalAddress/title",
          "value": "kSCNetworkFlagsIsLocalAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsIsLocalAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkFlagsIsLocalAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsConnectionAutomatic/title",
          "value": "kSCNetworkFlagsConnectionAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsConnectionAutomatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkFlagsConnectionAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsInterventionRequired/title",
          "value": "kSCNetworkFlagsInterventionRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsInterventionRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkFlagsInterventionRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsIsDirect/title",
          "value": "kSCNetworkFlagsIsDirect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsIsDirect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkFlagsIsDirect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsTransientConnection/title",
          "value": "kSCNetworkFlagsTransientConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsTransientConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkFlagsTransientConnection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/1420190-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/1420190-anonymous"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
