{
  "abstract": [
    {
      "text": "Ethernet bond aggregation status codes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/1546981-ethernet-bond-aggregation-status"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Ethernet Bond Aggregation Status"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-bond-status-constants": {
      "abstract": [
        {
          "text": "Ethernet bond status codes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-bond-status-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ethernet Bond Status Constants",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ethernet-bond-status-constants"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusLinkInvalid": {
      "abstract": [
        {
          "text": "The link state is not valid (such as down, half-duplex, or wrong speed).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCBondStatusLinkInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusLinkInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCBondStatusLinkInvalid"
        }
      ],
      "role": "symbol",
      "title": "kSCBondStatusLinkInvalid",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscbondstatuslinkinvalid"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusNoPartner": {
      "abstract": [
        {
          "text": "The port on the switch to which the device is connected doesn’t seem to have 802.3ad Link Aggregation enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCBondStatusNoPartner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusNoPartner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCBondStatusNoPartner"
        }
      ],
      "role": "symbol",
      "title": "kSCBondStatusNoPartner",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscbondstatusnopartner"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusNotInActiveGroup": {
      "abstract": [
        {
          "text": "Communication with a partner is occurring, but the link aggregation group is different from the one that is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCBondStatusNotInActiveGroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusNotInActiveGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCBondStatusNotInActiveGroup"
        }
      ],
      "role": "symbol",
      "title": "kSCBondStatusNotInActiveGroup",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscbondstatusnotinactivegroup"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusOK": {
      "abstract": [
        {
          "text": "The status is valid (for example, enabled, active, running, and so on).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCBondStatusOK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusOK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCBondStatusOK"
        }
      ],
      "role": "symbol",
      "title": "kSCBondStatusOK",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscbondstatusok"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusUnknown": {
      "abstract": [
        {
          "text": "Nonspecific failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCBondStatusUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCBondStatusUnknown"
        }
      ],
      "role": "symbol",
      "title": "kSCBondStatusUnknown",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscbondstatusunknown"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-interface-types": {
      "abstract": [
        {
          "text": "Keys that identify network interface types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-interface-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Interface Types",
      "type": "topic",
      "url": "/documentation/systemconfiguration/network-interface-types"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-protocol-types": {
      "abstract": [
        {
          "text": "Keys that identify network protocol types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-protocol-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Protocol Types",
      "type": "topic",
      "url": "/documentation/systemconfiguration/network-protocol-types"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCNetworkConfiguration",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconfiguration"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-bond-status-constants",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-interface-types",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-protocol-types"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusOK",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusLinkInvalid",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusNoPartner",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusNotInActiveGroup",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusUnknown"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusOK",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusLinkInvalid",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusNoPartner",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusNotInActiveGroup",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusUnknown"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-bond-status-constants",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-interface-types",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-protocol-types"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCBondStatusLinkInvalid/title",
          "value": "kSCBondStatusLinkInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCBondStatusLinkInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCBondStatusLinkInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCBondStatusUnknown/title",
          "value": "kSCBondStatusUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCBondStatusUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCBondStatusUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCBondStatusNotInActiveGroup/title",
          "value": "kSCBondStatusNotInActiveGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCBondStatusNotInActiveGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCBondStatusNotInActiveGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCBondStatusOK/title",
          "value": "kSCBondStatusOK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCBondStatusOK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCBondStatusOK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCBondStatusNoPartner/title",
          "value": "kSCBondStatusNoPartner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCBondStatusNoPartner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCBondStatusNoPartner"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/1546981-ethernet-bond-aggregation-status"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/1546981-ethernet-bond-aggregation-status"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
