{
  "abstract": [
    {
      "text": "The preferences session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferences-ft8",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCallBack"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/1808420-prefs"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "prefs"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/1808421-notificationtype": {
      "abstract": [
        {
          "text": "The type of notification, such as changes committed or changes applied. See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for information about possible values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/1808421-notificationtype",
      "kind": "article",
      "role": "article",
      "title": "notificationType",
      "type": "topic",
      "url": "/documentation/systemconfiguration/1808421-notificationtype"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCallBack": {
      "abstract": [
        {
          "text": "Type of the callback function used when the preferences have been updated or applied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesCallBack"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCallBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesCallBack"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesCallBack",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencescallback"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification": {
      "abstract": [
        {
          "text": "The type of notification (used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCallBack",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " callback).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesNotification"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesNotification"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesNotification",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencesnotification"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferences-ft8": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferences-ft8",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCPreferences",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferences-ft8"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Fields",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/1808421-notificationtype"
      ],
      "title": "Fields"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Fields",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/1808421-notificationtype"
              ],
              "title": "Fields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCallBack/title",
          "value": "SCPreferencesCallBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCallBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCallBack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesNotification/title",
          "value": "SCPreferencesNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesNotification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesNotification"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/1808420-prefs"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/1808420-prefs"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
