{
  "abstract": [
    {
      "text": "Keys that correspond to components in the persistent store.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Component Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNet6to4",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "6to4 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/6to4-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetDNS",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DNS Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/dns-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetEthernet",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ethernet Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ethernet-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys": {
      "abstract": [
        {
          "text": "General-purpose keys that apply to multiple dictionaries in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Generic Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/generic-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompHostnames",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Hostnames Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/hostnames-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompInterface",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Interface Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/interface-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetInterface",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Interface Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/interface-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetIPSec",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPSec Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ipsec-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetIPv4",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPv4 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ipv4-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetIPv6",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPv6 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ipv6-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompAnyRegex-swift.var": {
      "abstract": [
        {
          "text": "A regular expression pattern that matches any component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCCompAnyRegex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompAnyRegex-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCCompAnyRegex"
        }
      ],
      "role": "symbol",
      "title": "kSCCompAnyRegex",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ksccompanyregex-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompGlobal-swift.var": {
      "abstract": [
        {
          "text": "The Component key ",
          "type": "text"
        },
        {
          "code": "Global",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCCompGlobal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompGlobal-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCCompGlobal"
        }
      ],
      "role": "symbol",
      "title": "kSCCompGlobal",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ksccompglobal-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompHostNames-swift.var": {
      "abstract": [
        {
          "text": "The Component key ",
          "type": "text"
        },
        {
          "code": "HostNames",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCCompHostNames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompHostNames-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCCompHostNames"
        }
      ],
      "role": "symbol",
      "title": "kSCCompHostNames",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ksccomphostnames-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompInterface-swift.var": {
      "abstract": [
        {
          "text": "The Component key ",
          "type": "text"
        },
        {
          "code": "Interface",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCCompInterface"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompInterface-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCCompInterface"
        }
      ],
      "role": "symbol",
      "title": "kSCCompInterface",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ksccompinterface-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompNetwork-swift.var": {
      "abstract": [
        {
          "text": "The Component key ",
          "type": "text"
        },
        {
          "code": "Network",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCCompNetwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompNetwork-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCCompNetwork"
        }
      ],
      "role": "symbol",
      "title": "kSCCompNetwork",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ksccompnetwork-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompService-swift.var": {
      "abstract": [
        {
          "text": "The Component key ",
          "type": "text"
        },
        {
          "code": "Service",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCCompService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompService-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCCompService"
        }
      ],
      "role": "symbol",
      "title": "kSCCompService",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ksccompservice-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompSystem-swift.var": {
      "abstract": [
        {
          "text": "The Component key ",
          "type": "text"
        },
        {
          "code": "System",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCCompSystem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompSystem-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCCompSystem"
        }
      ],
      "role": "symbol",
      "title": "kSCCompSystem",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ksccompsystem-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompUsers-swift.var": {
      "abstract": [
        {
          "text": "The Component key Users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCCompUsers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompUsers-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCCompUsers"
        }
      ],
      "role": "symbol",
      "title": "kSCCompUsers",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ksccompusers-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetLink",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Link Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/link-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetModem",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Modem Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/modem-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompNetwork",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/network-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to network entity dictionaries in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/network-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to preferences in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Preference Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/preference-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCSchemaDefinitions",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scschemadefinitions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompNetwork-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompService-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompGlobal-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompHostNames-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompInterface-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompSystem-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompUsers-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompAnyRegex-swift.var"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompNetwork-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompService-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompGlobal-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompHostNames-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompInterface-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompSystem-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompUsers-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompAnyRegex-swift.var"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompSystem-swift.var/title",
          "value": "kSCCompSystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompSystem-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCCompSystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompGlobal-swift.var/title",
          "value": "kSCCompGlobal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompGlobal-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCCompGlobal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompInterface-swift.var/title",
          "value": "kSCCompInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompInterface-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCCompInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompUsers-swift.var/title",
          "value": "kSCCompUsers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompUsers-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCCompUsers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompAnyRegex-swift.var/title",
          "value": "kSCCompAnyRegex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompAnyRegex-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCCompAnyRegex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompNetwork-swift.var/title",
          "value": "kSCCompNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompNetwork-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCCompNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompHostNames-swift.var/title",
          "value": "kSCCompHostNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompHostNames-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCCompHostNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompService-swift.var/title",
          "value": "kSCCompService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompService-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCCompService"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/component-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/component-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
