{
  "abstract": [
    {
      "text": "Keys that correspond to values in the ",
      "type": "text"
    },
    {
      "code": "kSCEntNetDNS",
      "type": "codeVoice"
    },
    {
      "text": " dictionary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "DNS Entity Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNet6to4",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "6to4 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/6to4-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to components in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Component Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/component-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetEthernet",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ethernet Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ethernet-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys": {
      "abstract": [
        {
          "text": "General-purpose keys that apply to multiple dictionaries in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Generic Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/generic-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompHostnames",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Hostnames Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/hostnames-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompInterface",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Interface Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/interface-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetInterface",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Interface Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/interface-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetIPSec",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPSec Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ipsec-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetIPv4",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPv4 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ipv4-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetIPv6",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPv6 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ipv6-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSDomainName-swift.var": {
      "abstract": [
        {
          "text": "The DNS key ",
          "type": "text"
        },
        {
          "code": "DomainName",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSDomainName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSDomainName-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSDomainName"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetDNSDomainName",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetdnsdomainname-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSOptions-swift.var": {
      "abstract": [
        {
          "text": "The DNS key ",
          "type": "text"
        },
        {
          "code": "Options",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSOptions-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSOptions"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetDNSOptions",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetdnsoptions-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSearchDomains-swift.var": {
      "abstract": [
        {
          "text": "The DNS key ",
          "type": "text"
        },
        {
          "code": "SearchDomains",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFArray",
          "type": "codeVoice"
        },
        {
          "text": ", containing elements of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSSearchDomains"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSearchDomains-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSSearchDomains"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetDNSSearchDomains",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetdnssearchdomains-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSearchOrder-swift.var": {
      "abstract": [
        {
          "text": "The DNS key ",
          "type": "text"
        },
        {
          "code": "SearchOrder",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSSearchOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSearchOrder-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSSearchOrder"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetDNSSearchOrder",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetdnssearchorder-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSServerAddresses-swift.var": {
      "abstract": [
        {
          "text": "The DNS key ",
          "type": "text"
        },
        {
          "code": "ServerAddresses",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFArray",
          "type": "codeVoice"
        },
        {
          "text": ", containing elements of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSServerAddresses"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSServerAddresses-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSServerAddresses"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetDNSServerAddresses",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetdnsserveraddresses-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSServerPort-swift.var": {
      "abstract": [
        {
          "text": "The DNS key ",
          "type": "text"
        },
        {
          "code": "ServerPort",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSServerPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSServerPort-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSServerPort"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetDNSServerPort",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetdnsserverport-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSServerTimeout-swift.var": {
      "abstract": [
        {
          "text": "The DNS key ",
          "type": "text"
        },
        {
          "code": "ServerTimeout",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSServerTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSServerTimeout-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSServerTimeout"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetDNSServerTimeout",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetdnsservertimeout-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSortList-swift.var": {
      "abstract": [
        {
          "text": "The DNS key ",
          "type": "text"
        },
        {
          "code": "SortList",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFArray",
          "type": "codeVoice"
        },
        {
          "text": ", containing elements of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSSortList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSortList-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSSortList"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetDNSSortList",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetdnssortlist-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSupplementalMatchDomains-swift.var": {
      "abstract": [
        {
          "text": "The DNS key ",
          "type": "text"
        },
        {
          "code": "SupplementalMatchDomains",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFArray",
          "type": "codeVoice"
        },
        {
          "text": ", containing elements of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSSupplementalMatchDomains"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSupplementalMatchDomains-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSSupplementalMatchDomains"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetDNSSupplementalMatchDomains",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetdnssupplementalmatchdomains-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSupplementalMatchOrders-swift.var": {
      "abstract": [
        {
          "text": "The DNS key ",
          "type": "text"
        },
        {
          "code": "SupplementalMatchOrders",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFArray",
          "type": "codeVoice"
        },
        {
          "text": ", containing elements of type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSSupplementalMatchOrders"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSupplementalMatchOrders-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetDNSSupplementalMatchOrders"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetDNSSupplementalMatchOrders",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetdnssupplementalmatchorders-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetLink",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Link Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/link-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetModem",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Modem Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/modem-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompNetwork",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/network-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to network entity dictionaries in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/network-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to preferences in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Preference Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/preference-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCSchemaDefinitions",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scschemadefinitions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSDomainName-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSOptions-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSearchDomains-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSearchOrder-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSServerAddresses-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSServerPort-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSServerTimeout-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSortList-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSupplementalMatchDomains-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSupplementalMatchOrders-swift.var"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSDomainName-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSOptions-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSearchDomains-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSearchOrder-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSServerAddresses-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSServerPort-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSServerTimeout-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSortList-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSupplementalMatchDomains-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetDNSSupplementalMatchOrders-swift.var"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSSupplementalMatchDomains-swift.var/title",
          "value": "kSCPropNetDNSSupplementalMatchDomains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSSupplementalMatchDomains-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetDNSSupplementalMatchDomains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSOptions-swift.var/title",
          "value": "kSCPropNetDNSOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSOptions-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetDNSOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSDomainName-swift.var/title",
          "value": "kSCPropNetDNSDomainName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSDomainName-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetDNSDomainName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSServerAddresses-swift.var/title",
          "value": "kSCPropNetDNSServerAddresses"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSServerAddresses-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetDNSServerAddresses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSServerTimeout-swift.var/title",
          "value": "kSCPropNetDNSServerTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSServerTimeout-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetDNSServerTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSSearchDomains-swift.var/title",
          "value": "kSCPropNetDNSSearchDomains"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSSearchDomains-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetDNSSearchDomains"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSSupplementalMatchOrders-swift.var/title",
          "value": "kSCPropNetDNSSupplementalMatchOrders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSSupplementalMatchOrders-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetDNSSupplementalMatchOrders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSSortList-swift.var/title",
          "value": "kSCPropNetDNSSortList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSSortList-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetDNSSortList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSServerPort-swift.var/title",
          "value": "kSCPropNetDNSServerPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSServerPort-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetDNSServerPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSSearchOrder-swift.var/title",
          "value": "kSCPropNetDNSSearchOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetDNSSearchOrder-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetDNSSearchOrder"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/dns-entity-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/dns-entity-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
