{
  "abstract": [
    {
      "text": "Ethernet bond status codes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-bond-status-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Ethernet Bond Status Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/1546981-ethernet-bond-aggregation-status": {
      "abstract": [
        {
          "text": "Ethernet bond aggregation status codes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/1546981-ethernet-bond-aggregation-status",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ethernet Bond Aggregation Status",
      "type": "topic",
      "url": "/documentation/systemconfiguration/1546981-ethernet-bond-aggregation-status"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusDeviceAggregationStatus": {
      "abstract": [
        {
          "text": "Device is aggregating. See ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/1546981-ethernet-bond-aggregation-status",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " for a list of possible values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCBondStatusDeviceAggregationStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusDeviceAggregationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCBondStatusDeviceAggregationStatus"
        }
      ],
      "role": "symbol",
      "title": "kSCBondStatusDeviceAggregationStatus",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscbondstatusdeviceaggregationstatus"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusDeviceCollecting": {
      "abstract": [
        {
          "text": "Can be ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCBondStatusDeviceCollecting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusDeviceCollecting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCBondStatusDeviceCollecting"
        }
      ],
      "role": "symbol",
      "title": "kSCBondStatusDeviceCollecting",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscbondstatusdevicecollecting"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusDeviceDistributing": {
      "abstract": [
        {
          "text": "Can be ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCBondStatusDeviceDistributing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusDeviceDistributing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCBondStatusDeviceDistributing"
        }
      ],
      "role": "symbol",
      "title": "kSCBondStatusDeviceDistributing",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscbondstatusdevicedistributing"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-interface-types": {
      "abstract": [
        {
          "text": "Keys that identify network interface types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-interface-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Interface Types",
      "type": "topic",
      "url": "/documentation/systemconfiguration/network-interface-types"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-protocol-types": {
      "abstract": [
        {
          "text": "Keys that identify network protocol types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-protocol-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Protocol Types",
      "type": "topic",
      "url": "/documentation/systemconfiguration/network-protocol-types"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCNetworkConfiguration",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconfiguration"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/1546981-ethernet-bond-aggregation-status",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-interface-types",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-protocol-types"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusDeviceAggregationStatus",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusDeviceCollecting",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusDeviceDistributing"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusDeviceAggregationStatus",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusDeviceCollecting",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCBondStatusDeviceDistributing"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/1546981-ethernet-bond-aggregation-status",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-interface-types",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-protocol-types"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCBondStatusDeviceCollecting/title",
          "value": "kSCBondStatusDeviceCollecting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCBondStatusDeviceCollecting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCBondStatusDeviceCollecting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCBondStatusDeviceAggregationStatus/title",
          "value": "kSCBondStatusDeviceAggregationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCBondStatusDeviceAggregationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCBondStatusDeviceAggregationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCBondStatusDeviceDistributing/title",
          "value": "kSCBondStatusDeviceDistributing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCBondStatusDeviceDistributing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCBondStatusDeviceDistributing"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/ethernet-bond-status-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/ethernet-bond-status-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
