{
  "abstract": [
    {
      "text": "Keys that correspond to values in the ",
      "type": "text"
    },
    {
      "code": "kSCEntNetInterface",
      "type": "codeVoice"
    },
    {
      "text": " dictionary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Interface Entity Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNet6to4",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "6to4 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/6to4-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to components in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Component Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/component-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetDNS",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DNS Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/dns-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetEthernet",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ethernet Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ethernet-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys": {
      "abstract": [
        {
          "text": "General-purpose keys that apply to multiple dictionaries in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Generic Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/generic-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompHostnames",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Hostnames Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/hostnames-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompInterface",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Interface Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/interface-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetIPSec",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPSec Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ipsec-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetIPv4",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPv4 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ipv4-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetIPv6",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPv6 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ipv6-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceDeviceName-swift.var": {
      "abstract": [
        {
          "text": "The Interface key ",
          "type": "text"
        },
        {
          "code": "DeviceName",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceDeviceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceDeviceName-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceDeviceName"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetInterfaceDeviceName",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetinterfacedevicename-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceHardware-swift.var": {
      "abstract": [
        {
          "text": "The Interface key ",
          "type": "text"
        },
        {
          "code": "Hardware",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceHardware"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceHardware-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceHardware"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetInterfaceHardware",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetinterfacehardware-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceSubType-swift.var": {
      "abstract": [
        {
          "text": "The Interface key ",
          "type": "text"
        },
        {
          "code": "SubType",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceSubType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceSubType-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceSubType"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetInterfaceSubType",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetinterfacesubtype-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceSupportsModemOnHold-swift.var": {
      "abstract": [
        {
          "text": "The Interface key ",
          "type": "text"
        },
        {
          "code": "SupportsModemOnHold",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " and is equal to ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceSupportsModemOnHold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceSupportsModemOnHold-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceSupportsModemOnHold"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetInterfaceSupportsModemOnHold",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetinterfacesupportsmodemonhold-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceType-swift.var": {
      "abstract": [
        {
          "text": "The Interface key ",
          "type": "text"
        },
        {
          "code": "Type",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceType-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceType"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetInterfaceType",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetinterfacetype-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceSubTypeL2TP-swift.var": {
      "abstract": [
        {
          "text": "The constant value L2TP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceSubTypeL2TP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceSubTypeL2TP-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceSubTypeL2TP"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetInterfaceSubTypeL2TP",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetinterfacesubtypel2tp-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceSubTypePPPSerial-swift.var": {
      "abstract": [
        {
          "text": "The constant value PPPSerial.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceSubTypePPPSerial"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceSubTypePPPSerial-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceSubTypePPPSerial"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetInterfaceSubTypePPPSerial",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetinterfacesubtypepppserial-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceSubTypePPPoE-swift.var": {
      "abstract": [
        {
          "text": "The constant value PPPoE.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceSubTypePPPoE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceSubTypePPPoE-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceSubTypePPPoE"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetInterfaceSubTypePPPoE",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetinterfacesubtypepppoe-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceSubTypePPTP-swift.var": {
      "abstract": [
        {
          "text": "The constant value PPTP.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceSubTypePPTP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceSubTypePPTP-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceSubTypePPTP"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetInterfaceSubTypePPTP",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetinterfacesubtypepptp-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceType6to4-swift.var": {
      "abstract": [
        {
          "text": "The constant value 6to4.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceType6to4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceType6to4-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceType6to4"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetInterfaceType6to4",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetinterfacetype6to4-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceTypeEthernet-swift.var": {
      "abstract": [
        {
          "text": "The constant value Ethernet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceTypeEthernet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceTypeEthernet-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceTypeEthernet"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetInterfaceTypeEthernet",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetinterfacetypeethernet-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceTypeFireWire-swift.var": {
      "abstract": [
        {
          "text": "The constant value FireWire.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceTypeFireWire"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceTypeFireWire-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceTypeFireWire"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetInterfaceTypeFireWire",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetinterfacetypefirewire-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceTypeIPSec-swift.var": {
      "abstract": [
        {
          "text": "The constant value IPSec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceTypeIPSec"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceTypeIPSec-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceTypeIPSec"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetInterfaceTypeIPSec",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetinterfacetypeipsec-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceTypePPP-swift.var": {
      "abstract": [
        {
          "text": "The constant value PPP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceTypePPP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceTypePPP-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetInterfaceTypePPP"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetInterfaceTypePPP",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetinterfacetypeppp-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetLink",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Link Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/link-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetModem",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Modem Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/modem-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompNetwork",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/network-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to network entity dictionaries in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/network-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to preferences in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Preference Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/preference-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCSchemaDefinitions",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scschemadefinitions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceDeviceName-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceHardware-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceType-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceSubType-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceSupportsModemOnHold-swift.var"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Interface-Type-Values",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceTypeEthernet-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceTypeFireWire-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceTypePPP-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceType6to4-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceTypeIPSec-swift.var"
      ],
      "title": "Interface Type Values"
    },
    {
      "anchor": "Interface-Subtype-Values",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceSubTypePPPoE-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceSubTypePPPSerial-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceSubTypeL2TP-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceSubTypePPTP-swift.var"
      ],
      "title": "Interface Subtype Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceDeviceName-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceHardware-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceType-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceSubType-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceSupportsModemOnHold-swift.var"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Interface-Type-Values",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceTypeEthernet-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceTypeFireWire-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceTypePPP-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceType6to4-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceTypeIPSec-swift.var"
              ],
              "title": "Interface Type Values"
            },
            {
              "anchor": "Interface-Subtype-Values",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceSubTypePPPoE-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceSubTypePPPSerial-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceSubTypeL2TP-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetInterfaceSubTypePPTP-swift.var"
              ],
              "title": "Interface Subtype Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceTypePPP-swift.var/title",
          "value": "kSCValNetInterfaceTypePPP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceTypePPP-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetInterfaceTypePPP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceSupportsModemOnHold-swift.var/title",
          "value": "kSCPropNetInterfaceSupportsModemOnHold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceSupportsModemOnHold-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetInterfaceSupportsModemOnHold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceSubTypePPPSerial-swift.var/title",
          "value": "kSCValNetInterfaceSubTypePPPSerial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceSubTypePPPSerial-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetInterfaceSubTypePPPSerial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceTypeIPSec-swift.var/title",
          "value": "kSCValNetInterfaceTypeIPSec"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceTypeIPSec-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetInterfaceTypeIPSec"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceSubTypeL2TP-swift.var/title",
          "value": "kSCValNetInterfaceSubTypeL2TP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceSubTypeL2TP-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetInterfaceSubTypeL2TP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceSubTypePPPoE-swift.var/title",
          "value": "kSCValNetInterfaceSubTypePPPoE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceSubTypePPPoE-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetInterfaceSubTypePPPoE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceHardware-swift.var/title",
          "value": "kSCPropNetInterfaceHardware"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceHardware-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetInterfaceHardware"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceSubTypePPTP-swift.var/title",
          "value": "kSCValNetInterfaceSubTypePPTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceSubTypePPTP-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetInterfaceSubTypePPTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceDeviceName-swift.var/title",
          "value": "kSCPropNetInterfaceDeviceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceDeviceName-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetInterfaceDeviceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceType-swift.var/title",
          "value": "kSCPropNetInterfaceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceType-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetInterfaceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceTypeEthernet-swift.var/title",
          "value": "kSCValNetInterfaceTypeEthernet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceTypeEthernet-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetInterfaceTypeEthernet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceType6to4-swift.var/title",
          "value": "kSCValNetInterfaceType6to4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceType6to4-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetInterfaceType6to4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceSubType-swift.var/title",
          "value": "kSCPropNetInterfaceSubType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceSubType-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetInterfaceSubType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceTypeFireWire-swift.var/title",
          "value": "kSCValNetInterfaceTypeFireWire"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetInterfaceTypeFireWire-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetInterfaceTypeFireWire"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/interface-entity-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/interface-entity-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
