{
  "abstract": [
    {
      "text": "Keys that correspond to values in the ",
      "type": "text"
    },
    {
      "code": "kSCEntNetIPSec",
      "type": "codeVoice"
    },
    {
      "text": " dictionary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "IPSec Entity Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNet6to4",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "6to4 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/6to4-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to components in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Component Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/component-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetDNS",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DNS Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/dns-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetEthernet",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ethernet Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ethernet-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys": {
      "abstract": [
        {
          "text": "General-purpose keys that apply to multiple dictionaries in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Generic Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/generic-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompHostnames",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Hostnames Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/hostnames-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompInterface",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Interface Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/interface-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetInterface",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Interface Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/interface-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetIPv4",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPv4 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ipv4-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetIPv6",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPv6 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ipv6-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecAuthenticationMethod-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key ",
          "type": "text"
        },
        {
          "code": "AuthenticationMethod",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecAuthenticationMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecAuthenticationMethod-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecAuthenticationMethod"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecAuthenticationMethod",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecauthenticationmethod-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecConnectTime-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key ConnectTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecConnectTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecConnectTime-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecConnectTime"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecConnectTime",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecconnecttime-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecLocalCertificate-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key ",
          "type": "text"
        },
        {
          "code": "LocalCertificate",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFData",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecLocalCertificate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecLocalCertificate-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecLocalCertificate"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecLocalCertificate",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipseclocalcertificate-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecLocalIdentifier-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key ",
          "type": "text"
        },
        {
          "code": "LocalIdentifier",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecLocalIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecLocalIdentifier-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecLocalIdentifier"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecLocalIdentifier",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipseclocalidentifier-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecLocalIdentifierType-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key ",
          "type": "text"
        },
        {
          "code": "LocalIdentifierType",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecLocalIdentifierType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecLocalIdentifierType-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecLocalIdentifierType"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecLocalIdentifierType",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipseclocalidentifiertype-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecRemoteAddress-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key RemoteAddress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecRemoteAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecRemoteAddress-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecRemoteAddress"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecRemoteAddress",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecremoteaddress-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecSharedSecret-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key ",
          "type": "text"
        },
        {
          "code": "SharedSecret",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecSharedSecret"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecSharedSecret-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecSharedSecret"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecSharedSecret",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecsharedsecret-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecSharedSecretEncryption-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key ",
          "type": "text"
        },
        {
          "code": "SharedSecretEncryption",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecSharedSecretEncryption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecSharedSecretEncryption-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecSharedSecretEncryption"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecSharedSecretEncryption",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecsharedsecretencryption-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecStatus-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key Status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecStatus-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecStatus"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecStatus",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecstatus-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthEnabled-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key XAuthEnabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthEnabled-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthEnabled"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecXAuthEnabled",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecxauthenabled-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthName-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key XAuthName.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthName-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthName"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecXAuthName",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecxauthname-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPassword-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key XAuthPassword.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPassword-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthPassword"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecXAuthPassword",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecxauthpassword-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPasswordEncryption-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key XAuthPasswordEncryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthPasswordEncryption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPasswordEncryption-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthPasswordEncryption"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecXAuthPasswordEncryption",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecxauthpasswordencryption-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodCertificate-swift.var": {
      "abstract": [
        {
          "text": "The constant value Certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecAuthenticationMethodCertificate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodCertificate-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecAuthenticationMethodCertificate"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetIPSecAuthenticationMethodCertificate",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetipsecauthenticationmethodcertificate-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodHybrid-swift.var": {
      "abstract": [
        {
          "text": "The constant value Hybrid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecAuthenticationMethodHybrid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodHybrid-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecAuthenticationMethodHybrid"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetIPSecAuthenticationMethodHybrid",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetipsecauthenticationmethodhybrid-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodSharedSecret-swift.var": {
      "abstract": [
        {
          "text": "The constant value SharedSecret.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecAuthenticationMethodSharedSecret"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodSharedSecret-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecAuthenticationMethodSharedSecret"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetIPSecAuthenticationMethodSharedSecret",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetipsecauthenticationmethodsharedsecret-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecLocalIdentifierTypeKeyID-swift.var": {
      "abstract": [
        {
          "text": "The constant value KeyID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecLocalIdentifierTypeKeyID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecLocalIdentifierTypeKeyID-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecLocalIdentifierTypeKeyID"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetIPSecLocalIdentifierTypeKeyID",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetipseclocalidentifiertypekeyid-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecSharedSecretEncryptionKeychain-swift.var": {
      "abstract": [
        {
          "text": "The constant value Keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecSharedSecretEncryptionKeychain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecSharedSecretEncryptionKeychain-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecSharedSecretEncryptionKeychain"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetIPSecSharedSecretEncryptionKeychain",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetipsecsharedsecretencryptionkeychain-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecXAuthPasswordEncryptionKeychain-swift.var": {
      "abstract": [
        {
          "text": "The constant value Keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecXAuthPasswordEncryptionKeychain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecXAuthPasswordEncryptionKeychain-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecXAuthPasswordEncryptionKeychain"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetIPSecXAuthPasswordEncryptionKeychain",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetipsecxauthpasswordencryptionkeychain-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecXAuthPasswordEncryptionPrompt-swift.var": {
      "abstract": [
        {
          "text": "The constant value Prompt.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecXAuthPasswordEncryptionPrompt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecXAuthPasswordEncryptionPrompt-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecXAuthPasswordEncryptionPrompt"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetIPSecXAuthPasswordEncryptionPrompt",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetipsecxauthpasswordencryptionprompt-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetLink",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Link Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/link-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetModem",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Modem Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/modem-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompNetwork",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/network-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to network entity dictionaries in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/network-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to preferences in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Preference Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/preference-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCSchemaDefinitions",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scschemadefinitions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecLocalIdentifier-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecLocalIdentifierType-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecAuthenticationMethod-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecSharedSecret-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecSharedSecretEncryption-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecLocalCertificate-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecConnectTime-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecRemoteAddress-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecStatus-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthEnabled-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthName-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPassword-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPasswordEncryption-swift.var"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Authentication-Method-Values",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodSharedSecret-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodCertificate-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodHybrid-swift.var"
      ],
      "title": "Authentication Method Values"
    },
    {
      "anchor": "Local-Identifier-Type-Values",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecLocalIdentifierTypeKeyID-swift.var"
      ],
      "title": "Local Identifier Type Values"
    },
    {
      "anchor": "IPSec-Shared-Secret-Encryption-Values",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecSharedSecretEncryptionKeychain-swift.var"
      ],
      "title": "IPSec Shared Secret Encryption Values"
    },
    {
      "anchor": "XAuth-Password-Encryption-Values",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecXAuthPasswordEncryptionKeychain-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecXAuthPasswordEncryptionPrompt-swift.var"
      ],
      "title": "XAuth Password Encryption Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecLocalIdentifier-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecLocalIdentifierType-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecAuthenticationMethod-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecSharedSecret-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecSharedSecretEncryption-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecLocalCertificate-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecConnectTime-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecRemoteAddress-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecStatus-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthEnabled-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthName-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPassword-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPasswordEncryption-swift.var"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Authentication-Method-Values",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodSharedSecret-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodCertificate-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodHybrid-swift.var"
              ],
              "title": "Authentication Method Values"
            },
            {
              "anchor": "Local-Identifier-Type-Values",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecLocalIdentifierTypeKeyID-swift.var"
              ],
              "title": "Local Identifier Type Values"
            },
            {
              "anchor": "IPSec-Shared-Secret-Encryption-Values",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecSharedSecretEncryptionKeychain-swift.var"
              ],
              "title": "IPSec Shared Secret Encryption Values"
            },
            {
              "anchor": "XAuth-Password-Encryption-Values",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecXAuthPasswordEncryptionKeychain-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecXAuthPasswordEncryptionPrompt-swift.var"
              ],
              "title": "XAuth Password Encryption Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecSharedSecret-swift.var/title",
          "value": "kSCPropNetIPSecSharedSecret"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecSharedSecret-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecSharedSecret"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecAuthenticationMethodCertificate-swift.var/title",
          "value": "kSCValNetIPSecAuthenticationMethodCertificate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecAuthenticationMethodCertificate-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetIPSecAuthenticationMethodCertificate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthPassword-swift.var/title",
          "value": "kSCPropNetIPSecXAuthPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthPassword-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecXAuthPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecRemoteAddress-swift.var/title",
          "value": "kSCPropNetIPSecRemoteAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecRemoteAddress-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecRemoteAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecAuthenticationMethod-swift.var/title",
          "value": "kSCPropNetIPSecAuthenticationMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecAuthenticationMethod-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecAuthenticationMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecAuthenticationMethodSharedSecret-swift.var/title",
          "value": "kSCValNetIPSecAuthenticationMethodSharedSecret"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecAuthenticationMethodSharedSecret-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetIPSecAuthenticationMethodSharedSecret"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecLocalIdentifierTypeKeyID-swift.var/title",
          "value": "kSCValNetIPSecLocalIdentifierTypeKeyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecLocalIdentifierTypeKeyID-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetIPSecLocalIdentifierTypeKeyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthPasswordEncryption-swift.var/title",
          "value": "kSCPropNetIPSecXAuthPasswordEncryption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthPasswordEncryption-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecXAuthPasswordEncryption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecConnectTime-swift.var/title",
          "value": "kSCPropNetIPSecConnectTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecConnectTime-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecConnectTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecLocalIdentifierType-swift.var/title",
          "value": "kSCPropNetIPSecLocalIdentifierType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecLocalIdentifierType-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecLocalIdentifierType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecLocalIdentifier-swift.var/title",
          "value": "kSCPropNetIPSecLocalIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecLocalIdentifier-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecLocalIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecXAuthPasswordEncryptionKeychain-swift.var/title",
          "value": "kSCValNetIPSecXAuthPasswordEncryptionKeychain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecXAuthPasswordEncryptionKeychain-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetIPSecXAuthPasswordEncryptionKeychain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecStatus-swift.var/title",
          "value": "kSCPropNetIPSecStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecStatus-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecSharedSecretEncryption-swift.var/title",
          "value": "kSCPropNetIPSecSharedSecretEncryption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecSharedSecretEncryption-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecSharedSecretEncryption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthEnabled-swift.var/title",
          "value": "kSCPropNetIPSecXAuthEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthEnabled-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecXAuthEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecLocalCertificate-swift.var/title",
          "value": "kSCPropNetIPSecLocalCertificate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecLocalCertificate-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecLocalCertificate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecAuthenticationMethodHybrid-swift.var/title",
          "value": "kSCValNetIPSecAuthenticationMethodHybrid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecAuthenticationMethodHybrid-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetIPSecAuthenticationMethodHybrid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecXAuthPasswordEncryptionPrompt-swift.var/title",
          "value": "kSCValNetIPSecXAuthPasswordEncryptionPrompt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecXAuthPasswordEncryptionPrompt-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetIPSecXAuthPasswordEncryptionPrompt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthName-swift.var/title",
          "value": "kSCPropNetIPSecXAuthName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthName-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecXAuthName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecSharedSecretEncryptionKeychain-swift.var/title",
          "value": "kSCValNetIPSecSharedSecretEncryptionKeychain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecSharedSecretEncryptionKeychain-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetIPSecSharedSecretEncryptionKeychain"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/ipsec-entity-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/ipsec-entity-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
