{
  "abstract": [
    {
      "text": "The network entity key for the ",
      "type": "text"
    },
    {
      "code": "Interface",
      "type": "codeVoice"
    },
    {
      "text": " dictionary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetInterface-swift.var"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kSCEntNetInterface",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kSCEntNetInterface"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSCEntNetInterface"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kSCEntNetInterface"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSCEntNetInterface"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetAirPort-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "AirPort",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetAirPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetAirPort-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetAirPort"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetAirPort",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetairport-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetDHCP-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "DHCP",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetDHCP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetDHCP-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetDHCP"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetDHCP",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetdhcp-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetDNS-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "DNS",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetDNS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetDNS-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetDNS"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetDNS",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetdns-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetEthernet-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "Ethernet",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetEthernet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetEthernet-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetEthernet"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetEthernet",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetethernet-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetFireWire-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "FireWire",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetFireWire"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetFireWire-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetFireWire"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetFireWire",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetfirewire-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPSec-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "IPSec",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetIPSec"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPSec-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetIPSec"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetIPSec",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetipsec-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPv4-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "IPv4",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetIPv4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPv4-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetIPv4"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetIPv4",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetipv4-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPv6-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "IPv6",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetIPv6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPv6-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetIPv6"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetIPv6",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetipv6-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetInterface-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "Interface",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetInterface"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetInterface-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetInterface"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetInterface",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetinterface-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetL2TP-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "L2TP",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetL2TP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetL2TP-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetL2TP"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetL2TP",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetl2tp-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetLink-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "Link",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetLink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetLink-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetLink"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetLink",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetlink-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetModem-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "Modem",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetModem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetModem-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetModem"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetModem",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetmodem-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPP-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "PPP",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetPPP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPP-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetPPP"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetPPP",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetppp-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPPSerial-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "PPPSerial",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetPPPSerial"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPPSerial-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetPPPSerial"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetPPPSerial",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetpppserial-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPPoE-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "PPPoE",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetPPPoE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPPoE-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetPPPoE"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetPPPoE",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetpppoe-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPTP-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "PPTP",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetPPTP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPTP-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetPPTP"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetPPTP",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetpptp-swift.var"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetAirPort-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetDHCP-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetDNS-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetEthernet-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetFireWire-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPSec-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPv4-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPv6-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetL2TP-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetLink-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetModem-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPP-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPPoE-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPPSerial-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPTP-swift.var"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kSCEntNetInterface"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetAirPort-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetDHCP-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetDNS-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetEthernet-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetFireWire-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPSec-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPv4-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPv6-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetL2TP-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetLink-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetModem-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPP-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPPoE-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPPSerial-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPTP-swift.var"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kSCEntNetInterface"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetIPv6-swift.var/title",
          "value": "kSCEntNetIPv6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetIPv6-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetIPv6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetPPPoE-swift.var/title",
          "value": "kSCEntNetPPPoE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetPPPoE-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetPPPoE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetPPP-swift.var/title",
          "value": "kSCEntNetPPP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetPPP-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetPPP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetPPTP-swift.var/title",
          "value": "kSCEntNetPPTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetPPTP-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetPPTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetLink-swift.var/title",
          "value": "kSCEntNetLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetLink-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetL2TP-swift.var/title",
          "value": "kSCEntNetL2TP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetL2TP-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetL2TP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetPPPSerial-swift.var/title",
          "value": "kSCEntNetPPPSerial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetPPPSerial-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetPPPSerial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetDHCP-swift.var/title",
          "value": "kSCEntNetDHCP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetDHCP-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetDHCP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetModem-swift.var/title",
          "value": "kSCEntNetModem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetModem-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetModem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetIPv4-swift.var/title",
          "value": "kSCEntNetIPv4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetIPv4-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetIPv4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetDNS-swift.var/title",
          "value": "kSCEntNetDNS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetDNS-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetDNS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetAirPort-swift.var/title",
          "value": "kSCEntNetAirPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetAirPort-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetAirPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetFireWire-swift.var/title",
          "value": "kSCEntNetFireWire"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetFireWire-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetFireWire"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetInterface-swift.var/title",
          "value": "kSCEntNetInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetInterface-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetEthernet-swift.var/title",
          "value": "kSCEntNetEthernet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetEthernet-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetEthernet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetIPSec-swift.var/title",
          "value": "kSCEntNetIPSec"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetIPSec-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetIPSec"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/kscentnetinterface-swift.var"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/kscentnetinterface-swift.var"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
