{
  "abstract": [
    {
      "text": "The PPP interface.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypePPP"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kSCNetworkInterfaceTypePPP",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kSCNetworkInterfaceTypePPP"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSCNetworkInterfaceTypePPP"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kSCNetworkInterfaceTypePPP"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceTypePPP"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceType6to4": {
      "abstract": [
        {
          "text": "The 6to4 interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceType6to4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceType6to4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceType6to4"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkInterfaceType6to4",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkinterfacetype6to4"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeBluetooth": {
      "abstract": [
        {
          "text": "The Bluetooth interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeBluetooth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeBluetooth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeBluetooth"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkInterfaceTypeBluetooth",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkinterfacetypebluetooth"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeBond": {
      "abstract": [
        {
          "text": "The Ethernet bond interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeBond"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeBond",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeBond"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkInterfaceTypeBond",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkinterfacetypebond"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeEthernet": {
      "abstract": [
        {
          "text": "The Ethernet interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeEthernet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeEthernet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeEthernet"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkInterfaceTypeEthernet",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkinterfacetypeethernet"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeFireWire": {
      "abstract": [
        {
          "text": "The FireWire interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeFireWire"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeFireWire",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeFireWire"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkInterfaceTypeFireWire",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkinterfacetypefirewire"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeIEEE80211": {
      "abstract": [
        {
          "text": "The IEEE 802.11 interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeIEEE80211"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeIEEE80211",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeIEEE80211"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkInterfaceTypeIEEE80211",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkinterfacetypeieee80211"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeIPSec": {
      "abstract": [
        {
          "text": "The IPSec interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeIPSec"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeIPSec",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeIPSec"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkInterfaceTypeIPSec",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkinterfacetypeipsec"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeIPv4": {
      "abstract": [
        {
          "text": "The IPv4 interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeIPv4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeIPv4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeIPv4"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkInterfaceTypeIPv4",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkinterfacetypeipv4"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeIrDA": {
      "abstract": [
        {
          "text": "The IrDA interface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeIrDA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeIrDA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeIrDA"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkInterfaceTypeIrDA",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkinterfacetypeirda"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeL2TP": {
      "abstract": [
        {
          "text": "The L2TP interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeL2TP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeL2TP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeL2TP"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkInterfaceTypeL2TP",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkinterfacetypel2tp"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeModem": {
      "abstract": [
        {
          "text": "The modem interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeModem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeModem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeModem"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkInterfaceTypeModem",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkinterfacetypemodem"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypePPP": {
      "abstract": [
        {
          "text": "The PPP interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypePPP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypePPP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypePPP"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkInterfaceTypePPP",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkinterfacetypeppp"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypePPTP": {
      "abstract": [
        {
          "text": "The PPTP interface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypePPTP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypePPTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypePPTP"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkInterfaceTypePPTP",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkinterfacetypepptp"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeSerial": {
      "abstract": [
        {
          "text": "The serial interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeSerial"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeSerial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeSerial"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkInterfaceTypeSerial",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkinterfacetypeserial"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeVLAN": {
      "abstract": [
        {
          "text": "The VLAN interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeVLAN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeVLAN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeVLAN"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkInterfaceTypeVLAN",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkinterfacetypevlan"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeWWAN": {
      "abstract": [
        {
          "text": "The WWAN interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeWWAN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeWWAN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkInterfaceTypeWWAN"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkInterfaceTypeWWAN",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkinterfacetypewwan"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceType6to4",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeBluetooth",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeBond",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeEthernet",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeFireWire",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeIEEE80211",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeIPSec",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeIrDA",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeL2TP",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeModem",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypePPTP",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeSerial",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeVLAN",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeWWAN",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeIPv4"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kSCNetworkInterfaceTypePPP"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceTypePPP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceType6to4",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeBluetooth",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeBond",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeEthernet",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeFireWire",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeIEEE80211",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeIPSec",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeIrDA",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeL2TP",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeModem",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypePPTP",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeSerial",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeVLAN",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeWWAN",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkInterfaceTypeIPv4"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kSCNetworkInterfaceTypePPP"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeWWAN/title",
          "value": "kSCNetworkInterfaceTypeWWAN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeWWAN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceTypeWWAN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceType6to4/title",
          "value": "kSCNetworkInterfaceType6to4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceType6to4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceType6to4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeIPSec/title",
          "value": "kSCNetworkInterfaceTypeIPSec"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeIPSec/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceTypeIPSec"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeModem/title",
          "value": "kSCNetworkInterfaceTypeModem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeModem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceTypeModem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeSerial/title",
          "value": "kSCNetworkInterfaceTypeSerial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeSerial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceTypeSerial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeBluetooth/title",
          "value": "kSCNetworkInterfaceTypeBluetooth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeBluetooth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceTypeBluetooth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeIPv4/title",
          "value": "kSCNetworkInterfaceTypeIPv4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeIPv4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceTypeIPv4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeFireWire/title",
          "value": "kSCNetworkInterfaceTypeFireWire"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeFireWire/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceTypeFireWire"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypePPP/title",
          "value": "kSCNetworkInterfaceTypePPP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypePPP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceTypePPP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeVLAN/title",
          "value": "kSCNetworkInterfaceTypeVLAN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeVLAN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceTypeVLAN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypePPTP/title",
          "value": "kSCNetworkInterfaceTypePPTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypePPTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceTypePPTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeIrDA/title",
          "value": "kSCNetworkInterfaceTypeIrDA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeIrDA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceTypeIrDA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeIEEE80211/title",
          "value": "kSCNetworkInterfaceTypeIEEE80211"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeIEEE80211/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceTypeIEEE80211"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeBond/title",
          "value": "kSCNetworkInterfaceTypeBond"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeBond/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceTypeBond"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeL2TP/title",
          "value": "kSCNetworkInterfaceTypeL2TP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeL2TP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceTypeL2TP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeEthernet/title",
          "value": "kSCNetworkInterfaceTypeEthernet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkInterfaceTypeEthernet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkInterfaceTypeEthernet"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/kscnetworkinterfacetypeppp"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/kscnetworkinterfacetypeppp"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
