{
  "abstract": [
    {
      "text": "The specified node name or address can be reached using the current network configuration, but a connection must first be established.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsInterventionRequired"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kSCNetworkFlagsTransientConnection@kSCNetworkFlagsInterventionRequired",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kSCNetworkFlagsInterventionRequired"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSCNetworkFlagsInterventionRequired"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kSCNetworkFlagsInterventionRequired"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSCNetworkFlagsInterventionRequired"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In addition, some form of user intervention will be required to establish this connection, such as providing a password, an authentication token, etc.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Currently, this flag is returned when there is a dial-on-traffic configuration (",
              "type": "text"
            },
            {
              "code": "ConnectionAutomatic",
              "type": "codeVoice"
            },
            {
              "text": "), an attempt to connect has already been made, and when some error (for example, no dial tone, no answer, bad password, etc.) was encountered during the automatic connection attempt. In this case the PPP controller stops attempting to establish a connection until the user has intervened.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsConnectionAutomatic": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached using the current network configuration, but a connection must first be established.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsConnectionAutomatic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsConnectionAutomatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsConnectionAutomatic"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkFlagsConnectionAutomatic",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkflagsconnectionautomatic"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsConnectionRequired": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached using the current network configuration, but a connection must first be established.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsConnectionRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsConnectionRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsConnectionRequired"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkFlagsConnectionRequired",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkflagsconnectionrequired"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsInterventionRequired": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached using the current network configuration, but a connection must first be established.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsInterventionRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsInterventionRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsInterventionRequired"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkFlagsInterventionRequired",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkflagsinterventionrequired"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsIsDirect": {
      "abstract": [
        {
          "text": "Network traffic to the specified node name or address does not go through a gateway, but is routed directly to one of the interfaces in the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsIsDirect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsIsDirect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsIsDirect"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkFlagsIsDirect",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkflagsisdirect"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsIsLocalAddress": {
      "abstract": [
        {
          "text": "The specified node name or address is one associated with a network interface on the current system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsIsLocalAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsIsLocalAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsIsLocalAddress"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkFlagsIsLocalAddress",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkflagsislocaladdress"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsReachable": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached using the current network configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsReachable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsReachable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsReachable"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkFlagsReachable",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkflagsreachable"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsTransientConnection": {
      "abstract": [
        {
          "text": "The specified node name or address can be reached via a transient connection, such as PPP.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsTransientConnection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsTransientConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkFlagsTransientConnection"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkFlagsTransientConnection",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkflagstransientconnection"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsTransientConnection",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsReachable",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsConnectionRequired",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsConnectionAutomatic",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsIsLocalAddress",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsIsDirect"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kSCNetworkFlagsInterventionRequired"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkFlagsInterventionRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsTransientConnection",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsReachable",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsConnectionRequired",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsConnectionAutomatic",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsIsLocalAddress",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkFlagsIsDirect"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kSCNetworkFlagsInterventionRequired"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsConnectionRequired/title",
          "value": "kSCNetworkFlagsConnectionRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsConnectionRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkFlagsConnectionRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsInterventionRequired/title",
          "value": "kSCNetworkFlagsInterventionRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsInterventionRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkFlagsInterventionRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsTransientConnection/title",
          "value": "kSCNetworkFlagsTransientConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsTransientConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkFlagsTransientConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsIsLocalAddress/title",
          "value": "kSCNetworkFlagsIsLocalAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsIsLocalAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkFlagsIsLocalAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsConnectionAutomatic/title",
          "value": "kSCNetworkFlagsConnectionAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsConnectionAutomatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkFlagsConnectionAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsReachable/title",
          "value": "kSCNetworkFlagsReachable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsReachable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkFlagsReachable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsIsDirect/title",
          "value": "kSCNetworkFlagsIsDirect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkFlagsIsDirect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkFlagsIsDirect"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/kscnetworkflagsinterventionrequired"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/kscnetworkflagsinterventionrequired"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
