{
  "abstract": [
    {
      "text": "The Interface key ",
      "type": "text"
    },
    {
      "code": "SubType",
      "type": "codeVoice"
    },
    {
      "text": ", whose value is of type ",
      "type": "text"
    },
    {
      "code": "CFString",
      "type": "codeVoice"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceSubType-swift.var"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kSCPropNetInterfaceSubType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kSCPropNetInterfaceSubType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSCPropNetInterfaceSubType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kSCPropNetInterfaceSubType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSCPropNetInterfaceSubType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key can be passed the following constants when the ",
              "type": "text"
            },
            {
              "code": "Type",
              "type": "codeVoice"
            },
            {
              "text": " key has the value ",
              "type": "text"
            },
            {
              "code": "PPP",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "kSCValNetInterfaceSubTypePPPoE",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", which has the value ",
                      "type": "text"
                    },
                    {
                      "code": "PPPoE",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "kSCValNetInterfaceSubTypePPPSerial",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", which has the value ",
                      "type": "text"
                    },
                    {
                      "code": "PPPSerial",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "kSCValNetInterfaceSubTypePPTP",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", which has the value ",
                      "type": "text"
                    },
                    {
                      "code": "PPTP",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "kSCValNetInterfaceSubTypeL2TP",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", which has the value ",
                      "type": "text"
                    },
                    {
                      "code": "L2TP",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceDeviceName-swift.var": {
      "abstract": [
        {
          "text": "The Interface key ",
          "type": "text"
        },
        {
          "code": "DeviceName",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceDeviceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceDeviceName-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceDeviceName"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetInterfaceDeviceName",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetinterfacedevicename-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceHardware-swift.var": {
      "abstract": [
        {
          "text": "The Interface key ",
          "type": "text"
        },
        {
          "code": "Hardware",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceHardware"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceHardware-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceHardware"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetInterfaceHardware",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetinterfacehardware-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceSubType-swift.var": {
      "abstract": [
        {
          "text": "The Interface key ",
          "type": "text"
        },
        {
          "code": "SubType",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceSubType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceSubType-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceSubType"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetInterfaceSubType",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetinterfacesubtype-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceSupportsModemOnHold-swift.var": {
      "abstract": [
        {
          "text": "The Interface key ",
          "type": "text"
        },
        {
          "code": "SupportsModemOnHold",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " and is equal to ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceSupportsModemOnHold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceSupportsModemOnHold-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceSupportsModemOnHold"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetInterfaceSupportsModemOnHold",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetinterfacesupportsmodemonhold-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceType-swift.var": {
      "abstract": [
        {
          "text": "The Interface key ",
          "type": "text"
        },
        {
          "code": "Type",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceType-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetInterfaceType"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetInterfaceType",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetinterfacetype-swift.var"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceDeviceName-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceHardware-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceType-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceSupportsModemOnHold-swift.var"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kSCPropNetInterfaceSubType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetInterfaceSubType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceDeviceName-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceHardware-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceType-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetInterfaceSupportsModemOnHold-swift.var"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kSCPropNetInterfaceSubType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceDeviceName-swift.var/title",
          "value": "kSCPropNetInterfaceDeviceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceDeviceName-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetInterfaceDeviceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceHardware-swift.var/title",
          "value": "kSCPropNetInterfaceHardware"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceHardware-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetInterfaceHardware"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceSupportsModemOnHold-swift.var/title",
          "value": "kSCPropNetInterfaceSupportsModemOnHold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceSupportsModemOnHold-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetInterfaceSupportsModemOnHold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceType-swift.var/title",
          "value": "kSCPropNetInterfaceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceType-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetInterfaceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceSubType-swift.var/title",
          "value": "kSCPropNetInterfaceSubType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetInterfaceSubType-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetInterfaceSubType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/kscpropnetinterfacesubtype-swift.var"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/kscpropnetinterfacesubtype-swift.var"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
