{
  "abstract": [
    {
      "text": "The Proxies key ",
      "type": "text"
    },
    {
      "code": "HTTPEnable",
      "type": "codeVoice"
    },
    {
      "text": ", whose value is of type ",
      "type": "text"
    },
    {
      "code": "CFNumber",
      "type": "codeVoice"
    },
    {
      "text": " and is equal to ",
      "type": "text"
    },
    {
      "code": "0",
      "type": "codeVoice"
    },
    {
      "text": " or ",
      "type": "text"
    },
    {
      "code": "1",
      "type": "codeVoice"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPEnable-swift.var"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kSCPropNetProxiesHTTPEnable",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kSCPropNetProxiesHTTPEnable"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSCPropNetProxiesHTTPEnable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kSCPropNetProxiesHTTPEnable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesHTTPEnable"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesExceptionsList-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ",
          "type": "text"
        },
        {
          "code": "ExceptionsList",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFArray",
          "type": "codeVoice"
        },
        {
          "text": ", containing elements of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesExceptionsList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesExceptionsList-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesExceptionsList"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesExceptionsList",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxiesexceptionslist-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesExcludeSimpleHostnames-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ",
          "type": "text"
        },
        {
          "code": "ExcludeSimpleHostnames",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " and is equal to ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesExcludeSimpleHostnames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesExcludeSimpleHostnames-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesExcludeSimpleHostnames"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesExcludeSimpleHostnames",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxiesexcludesimplehostnames-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesFTPEnable-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ",
          "type": "text"
        },
        {
          "code": "FTPEnable",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " and is equal to ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesFTPEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesFTPEnable-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesFTPEnable"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesFTPEnable",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxiesftpenable-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesFTPPassive-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ",
          "type": "text"
        },
        {
          "code": "FTPPassive",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " and is equal to ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesFTPPassive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesFTPPassive-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesFTPPassive"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesFTPPassive",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxiesftppassive-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesFTPPort-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ",
          "type": "text"
        },
        {
          "code": "FTPPort",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesFTPPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesFTPPort-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesFTPPort"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesFTPPort",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxiesftpport-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesFTPProxy-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ",
          "type": "text"
        },
        {
          "code": "FTPProxy",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesFTPProxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesFTPProxy-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesFTPProxy"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesFTPProxy",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxiesftpproxy-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesGopherEnable-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ",
          "type": "text"
        },
        {
          "code": "GopherEnable",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " and is equal to ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesGopherEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesGopherEnable-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesGopherEnable"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesGopherEnable",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxiesgopherenable-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesGopherPort-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ",
          "type": "text"
        },
        {
          "code": "GopherPort",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesGopherPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesGopherPort-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesGopherPort"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesGopherPort",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxiesgopherport-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesGopherProxy-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ",
          "type": "text"
        },
        {
          "code": "GopherProxy",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesGopherProxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesGopherProxy-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesGopherProxy"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesGopherProxy",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxiesgopherproxy-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPEnable-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ",
          "type": "text"
        },
        {
          "code": "HTTPEnable",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " and is equal to ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesHTTPEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPEnable-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesHTTPEnable"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesHTTPEnable",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxieshttpenable-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPPort-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ",
          "type": "text"
        },
        {
          "code": "HTTPPort",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesHTTPPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPPort-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesHTTPPort"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesHTTPPort",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxieshttpport-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPProxy-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ",
          "type": "text"
        },
        {
          "code": "HTTPProxy",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesHTTPProxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPProxy-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesHTTPProxy"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesHTTPProxy",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxieshttpproxy-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPSEnable-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ",
          "type": "text"
        },
        {
          "code": "HTTPSEnable",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " and is equal to ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesHTTPSEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPSEnable-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesHTTPSEnable"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesHTTPSEnable",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxieshttpsenable-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPSPort-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ",
          "type": "text"
        },
        {
          "code": "HTTPSPort",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesHTTPSPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPSPort-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesHTTPSPort"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesHTTPSPort",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxieshttpsport-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPSProxy-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ",
          "type": "text"
        },
        {
          "code": "HTTPSProxy",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesHTTPSProxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPSProxy-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesHTTPSProxy"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesHTTPSProxy",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxieshttpsproxy-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesRTSPEnable-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ",
          "type": "text"
        },
        {
          "code": "RTSPEnable",
          "type": "codeVoice"
        },
        {
          "text": ", whose value is of type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": " and is equal to ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesRTSPEnable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesRTSPEnable-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesRTSPEnable"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesRTSPEnable",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxiesrtspenable-swift.var"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesExceptionsList-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesExcludeSimpleHostnames-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesFTPEnable-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesFTPPassive-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesFTPPort-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesFTPProxy-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesGopherEnable-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesGopherPort-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesGopherProxy-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPPort-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPProxy-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPSEnable-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPSPort-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPSProxy-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesRTSPEnable-swift.var"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kSCPropNetProxiesHTTPEnable"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesHTTPEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesExceptionsList-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesExcludeSimpleHostnames-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesFTPEnable-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesFTPPassive-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesFTPPort-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesFTPProxy-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesGopherEnable-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesGopherPort-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesGopherProxy-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPPort-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPProxy-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPSEnable-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPSPort-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesHTTPSProxy-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesRTSPEnable-swift.var"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kSCPropNetProxiesHTTPEnable"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesRTSPEnable-swift.var/title",
          "value": "kSCPropNetProxiesRTSPEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesRTSPEnable-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesRTSPEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesHTTPPort-swift.var/title",
          "value": "kSCPropNetProxiesHTTPPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesHTTPPort-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesHTTPPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesFTPPassive-swift.var/title",
          "value": "kSCPropNetProxiesFTPPassive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesFTPPassive-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesFTPPassive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesGopherProxy-swift.var/title",
          "value": "kSCPropNetProxiesGopherProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesGopherProxy-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesGopherProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesHTTPSEnable-swift.var/title",
          "value": "kSCPropNetProxiesHTTPSEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesHTTPSEnable-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesHTTPSEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesGopherEnable-swift.var/title",
          "value": "kSCPropNetProxiesGopherEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesGopherEnable-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesGopherEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesExceptionsList-swift.var/title",
          "value": "kSCPropNetProxiesExceptionsList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesExceptionsList-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesExceptionsList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesFTPPort-swift.var/title",
          "value": "kSCPropNetProxiesFTPPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesFTPPort-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesFTPPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesFTPEnable-swift.var/title",
          "value": "kSCPropNetProxiesFTPEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesFTPEnable-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesFTPEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesFTPProxy-swift.var/title",
          "value": "kSCPropNetProxiesFTPProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesFTPProxy-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesFTPProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesHTTPEnable-swift.var/title",
          "value": "kSCPropNetProxiesHTTPEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesHTTPEnable-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesHTTPEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesExcludeSimpleHostnames-swift.var/title",
          "value": "kSCPropNetProxiesExcludeSimpleHostnames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesExcludeSimpleHostnames-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesExcludeSimpleHostnames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesHTTPProxy-swift.var/title",
          "value": "kSCPropNetProxiesHTTPProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesHTTPProxy-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesHTTPProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesGopherPort-swift.var/title",
          "value": "kSCPropNetProxiesGopherPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesGopherPort-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesGopherPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesHTTPSProxy-swift.var/title",
          "value": "kSCPropNetProxiesHTTPSProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesHTTPSProxy-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesHTTPSProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesHTTPSPort-swift.var/title",
          "value": "kSCPropNetProxiesHTTPSPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesHTTPSPort-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesHTTPSPort"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/kscpropnetproxieshttpenable-swift.var"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/kscpropnetproxieshttpenable-swift.var"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
