{
  "abstract": [
    {
      "text": "A nonspecific failure occurred.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusFailed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kSCStatusOK@kSCStatusFailed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kSCStatusFailed"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSCStatusFailed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kSCStatusFailed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSCStatusFailed"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusAccessError": {
      "abstract": [
        {
          "text": "Permission is denied; you must be root to obtain a lock. As a result, the function could not create or access preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCStatusAccessError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusAccessError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCStatusAccessError"
        }
      ],
      "role": "symbol",
      "title": "kSCStatusAccessError",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscstatusaccesserror"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusFailed": {
      "abstract": [
        {
          "text": "A nonspecific failure occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCStatusFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCStatusFailed"
        }
      ],
      "role": "symbol",
      "title": "kSCStatusFailed",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscstatusfailed"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusInvalidArgument": {
      "abstract": [
        {
          "text": "An invalid argument was specified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCStatusInvalidArgument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusInvalidArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCStatusInvalidArgument"
        }
      ],
      "role": "symbol",
      "title": "kSCStatusInvalidArgument",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscstatusinvalidargument"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusKeyExists": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCStatusKeyExists"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusKeyExists",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCStatusKeyExists"
        }
      ],
      "role": "symbol",
      "title": "kSCStatusKeyExists",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscstatuskeyexists"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusLocked": {
      "abstract": [
        {
          "text": "A lock is already held.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCStatusLocked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusLocked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCStatusLocked"
        }
      ],
      "role": "symbol",
      "title": "kSCStatusLocked",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscstatuslocked"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNeedLock": {
      "abstract": [
        {
          "text": "A lock is required for this operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCStatusNeedLock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNeedLock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCStatusNeedLock"
        }
      ],
      "role": "symbol",
      "title": "kSCStatusNeedLock",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscstatusneedlock"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoConfigFile": {
      "abstract": [
        {
          "text": "The configuration file cannot be found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCStatusNoConfigFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoConfigFile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCStatusNoConfigFile"
        }
      ],
      "role": "symbol",
      "title": "kSCStatusNoConfigFile",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscstatusnoconfigfile"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoKey": {
      "abstract": [
        {
          "text": "No such key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCStatusNoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCStatusNoKey"
        }
      ],
      "role": "symbol",
      "title": "kSCStatusNoKey",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscstatusnokey"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoLink": {
      "abstract": [
        {
          "text": "No such link exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCStatusNoLink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCStatusNoLink"
        }
      ],
      "role": "symbol",
      "title": "kSCStatusNoLink",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscstatusnolink"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoPrefsSession": {
      "abstract": [
        {
          "text": "The preferences session is not active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCStatusNoPrefsSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoPrefsSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCStatusNoPrefsSession"
        }
      ],
      "role": "symbol",
      "title": "kSCStatusNoPrefsSession",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscstatusnoprefssession"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoStoreServer": {
      "abstract": [
        {
          "text": "The configuration daemon is not available or no longer available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCStatusNoStoreServer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoStoreServer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCStatusNoStoreServer"
        }
      ],
      "role": "symbol",
      "title": "kSCStatusNoStoreServer",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscstatusnostoreserver"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoStoreSession": {
      "abstract": [
        {
          "text": "The configuration daemon session is not active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCStatusNoStoreSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoStoreSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCStatusNoStoreSession"
        }
      ],
      "role": "symbol",
      "title": "kSCStatusNoStoreSession",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscstatusnostoresession"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNotifierActive": {
      "abstract": [
        {
          "text": "Notifier is currently active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCStatusNotifierActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNotifierActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCStatusNotifierActive"
        }
      ],
      "role": "symbol",
      "title": "kSCStatusNotifierActive",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscstatusnotifieractive"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusOK": {
      "abstract": [
        {
          "text": "The call was successful.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCStatusOK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusOK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCStatusOK"
        }
      ],
      "role": "symbol",
      "title": "kSCStatusOK",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscstatusok"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusPrefsBusy": {
      "abstract": [
        {
          "text": "A preferences update is currently in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCStatusPrefsBusy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusPrefsBusy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCStatusPrefsBusy"
        }
      ],
      "role": "symbol",
      "title": "kSCStatusPrefsBusy",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscstatusprefsbusy"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusStale": {
      "abstract": [
        {
          "text": "A write was attempted on a stale version of the object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCStatusStale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusStale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCStatusStale"
        }
      ],
      "role": "symbol",
      "title": "kSCStatusStale",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscstatusstale"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusOK",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusInvalidArgument",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusAccessError",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoKey",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusKeyExists",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusLocked",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNeedLock",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoStoreSession",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoStoreServer",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNotifierActive",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoPrefsSession",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusPrefsBusy",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoConfigFile",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoLink",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusStale"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kSCStatusFailed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCStatusFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusOK",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusInvalidArgument",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusAccessError",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoKey",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusKeyExists",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusLocked",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNeedLock",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoStoreSession",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoStoreServer",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNotifierActive",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoPrefsSession",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusPrefsBusy",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoConfigFile",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusNoLink",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCStatusStale"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kSCStatusFailed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusNoLink/title",
          "value": "kSCStatusNoLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusNoLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCStatusNoLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusNoConfigFile/title",
          "value": "kSCStatusNoConfigFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusNoConfigFile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCStatusNoConfigFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusNoStoreSession/title",
          "value": "kSCStatusNoStoreSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusNoStoreSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCStatusNoStoreSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusKeyExists/title",
          "value": "kSCStatusKeyExists"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusKeyExists/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCStatusKeyExists"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusNotifierActive/title",
          "value": "kSCStatusNotifierActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusNotifierActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCStatusNotifierActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusNeedLock/title",
          "value": "kSCStatusNeedLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusNeedLock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCStatusNeedLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusNoStoreServer/title",
          "value": "kSCStatusNoStoreServer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusNoStoreServer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCStatusNoStoreServer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusNoPrefsSession/title",
          "value": "kSCStatusNoPrefsSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusNoPrefsSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCStatusNoPrefsSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusPrefsBusy/title",
          "value": "kSCStatusPrefsBusy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusPrefsBusy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCStatusPrefsBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusNoKey/title",
          "value": "kSCStatusNoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusNoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCStatusNoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusLocked/title",
          "value": "kSCStatusLocked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusLocked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCStatusLocked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusOK/title",
          "value": "kSCStatusOK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusOK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCStatusOK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusInvalidArgument/title",
          "value": "kSCStatusInvalidArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusInvalidArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCStatusInvalidArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusAccessError/title",
          "value": "kSCStatusAccessError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusAccessError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCStatusAccessError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusFailed/title",
          "value": "kSCStatusFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCStatusFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusStale/title",
          "value": "kSCStatusStale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCStatusStale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCStatusStale"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/kscstatusfailed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/kscstatusfailed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
