{
  "abstract": [
    {
      "text": "The constant value Keychain.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecXAuthPasswordEncryptionKeychain-swift.var"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kSCValNetIPSecXAuthPasswordEncryptionKeychain",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kSCValNetIPSecXAuthPasswordEncryptionKeychain"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSCValNetIPSecXAuthPasswordEncryptionKeychain"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kSCValNetIPSecXAuthPasswordEncryptionKeychain"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSCValNetIPSecXAuthPasswordEncryptionKeychain"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This value applies to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPasswordEncryption-swift.var",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/cfdata": {
      "abstract": [
        {
          "text": "A reference to an immutable CFData object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFData"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdata",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFData",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdata"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfstring": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeyBSSID": {
      "abstract": [
        {
          "text": "The key for the network’s BSSID, which is represented as a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCNNetworkInfoKeyBSSID"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeyBSSID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCNNetworkInfoKeyBSSID",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kcnnetworkinfokeybssid"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeySSID": {
      "abstract": [
        {
          "text": "The key for the network’s SSID, which is represented as a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCNNetworkInfoKeySSID"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeySSID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCNNetworkInfoKeySSID",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kcnnetworkinfokeyssid"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeySSIDData": {
      "abstract": [
        {
          "text": "The key for the network’s SSID, which is represented as a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdata",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCNNetworkInfoKeySSIDData"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeySSIDData",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCNNetworkInfoKeySSIDData",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kcnnetworkinfokeyssiddata"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompAnyRegex-swift.var": {
      "abstract": [
        {
          "text": "A regular expression pattern that matches any component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCCompAnyRegex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompAnyRegex-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCCompAnyRegex"
        }
      ],
      "role": "symbol",
      "title": "kSCCompAnyRegex",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ksccompanyregex-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecConnectTime-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key ConnectTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecConnectTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecConnectTime-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecConnectTime"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecConnectTime",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecconnecttime-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecRemoteAddress-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key RemoteAddress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecRemoteAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecRemoteAddress-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecRemoteAddress"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecRemoteAddress",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecremoteaddress-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecStatus-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key Status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecStatus-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecStatus"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecStatus",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecstatus-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthEnabled-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key XAuthEnabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthEnabled-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthEnabled"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecXAuthEnabled",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecxauthenabled-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthName-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key XAuthName.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthName-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthName"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecXAuthName",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecxauthname-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPassword-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key XAuthPassword.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPassword-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthPassword"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecXAuthPassword",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecxauthpassword-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPasswordEncryption-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key XAuthPasswordEncryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthPasswordEncryption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPasswordEncryption-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthPasswordEncryption"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecXAuthPasswordEncryption",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecxauthpasswordencryption-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesProxyAutoConfigJavaScript-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ProxyAutoConfigJavaScript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesProxyAutoConfigJavaScript"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesProxyAutoConfigJavaScript-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesProxyAutoConfigJavaScript"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesProxyAutoConfigJavaScript",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxiesproxyautoconfigjavascript-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserGID-c.var": {
      "abstract": [
        {
          "text": "The deprecated key GID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSCPropUsersConsoleUserGID"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserGID-c.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSCPropUsersConsoleUserGID",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropusersconsoleusergid-c.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserName-c.var": {
      "abstract": [
        {
          "text": "The deprecated key Name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSCPropUsersConsoleUserName"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserName-c.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSCPropUsersConsoleUserName",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropusersconsoleusername-c.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserUID-c.var": {
      "abstract": [
        {
          "text": "The deprecated key UID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSCPropUsersConsoleUserUID"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserUID-c.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSCPropUsersConsoleUserUID",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropusersconsoleuseruid-c.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCResvInactive-swift.var": {
      "abstract": [
        {
          "text": "The reserved key __INACTIVE__.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCResvInactive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCResvInactive-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCResvInactive"
        }
      ],
      "role": "symbol",
      "title": "kSCResvInactive",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscresvinactive-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCResvLink-swift.var": {
      "abstract": [
        {
          "text": "The reserved key __LINK__.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCResvLink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCResvLink-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCResvLink"
        }
      ],
      "role": "symbol",
      "title": "kSCResvLink",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscresvlink-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodCertificate-swift.var": {
      "abstract": [
        {
          "text": "The constant value Certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecAuthenticationMethodCertificate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodCertificate-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecAuthenticationMethodCertificate"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetIPSecAuthenticationMethodCertificate",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetipsecauthenticationmethodcertificate-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodHybrid-swift.var": {
      "abstract": [
        {
          "text": "The constant value Hybrid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecAuthenticationMethodHybrid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodHybrid-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecAuthenticationMethodHybrid"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetIPSecAuthenticationMethodHybrid",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetipsecauthenticationmethodhybrid-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodSharedSecret-swift.var": {
      "abstract": [
        {
          "text": "The constant value SharedSecret.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecAuthenticationMethodSharedSecret"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodSharedSecret-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecAuthenticationMethodSharedSecret"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetIPSecAuthenticationMethodSharedSecret",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetipsecauthenticationmethodsharedsecret-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecLocalIdentifierTypeKeyID-swift.var": {
      "abstract": [
        {
          "text": "The constant value KeyID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecLocalIdentifierTypeKeyID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecLocalIdentifierTypeKeyID-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecLocalIdentifierTypeKeyID"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetIPSecLocalIdentifierTypeKeyID",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetipseclocalidentifiertypekeyid-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecXAuthPasswordEncryptionKeychain-swift.var": {
      "abstract": [
        {
          "text": "The constant value Keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecXAuthPasswordEncryptionKeychain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecXAuthPasswordEncryptionKeychain-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCValNetIPSecXAuthPasswordEncryptionKeychain"
        }
      ],
      "role": "symbol",
      "title": "kSCValNetIPSecXAuthPasswordEncryptionKeychain",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetipsecxauthpasswordencryptionkeychain-swift.var"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompAnyRegex-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecConnectTime-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecRemoteAddress-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecStatus-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthEnabled-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthName-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPassword-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPasswordEncryption-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesProxyAutoConfigJavaScript-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCResvInactive-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCResvLink-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodCertificate-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodHybrid-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecAuthenticationMethodSharedSecret-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetIPSecLocalIdentifierTypeKeyID-swift.var"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kSCValNetIPSecXAuthPasswordEncryptionKeychain"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetIPSecXAuthPasswordEncryptionKeychain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeyBSSID",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeySSID",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeySSIDData",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompAnyRegex-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecConnectTime-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecRemoteAddress-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecStatus-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthEnabled-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthName-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPassword-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPasswordEncryption-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesProxyAutoConfigJavaScript-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserGID-c.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserName-c.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserUID-c.var"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kSCValNetIPSecXAuthPasswordEncryptionKeychain"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesProxyAutoConfigJavaScript-swift.var/title",
          "value": "kSCPropNetProxiesProxyAutoConfigJavaScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesProxyAutoConfigJavaScript-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesProxyAutoConfigJavaScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecConnectTime-swift.var/title",
          "value": "kSCPropNetIPSecConnectTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecConnectTime-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecConnectTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecRemoteAddress-swift.var/title",
          "value": "kSCPropNetIPSecRemoteAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecRemoteAddress-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecRemoteAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfstring/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthPassword-swift.var/title",
          "value": "kSCPropNetIPSecXAuthPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthPassword-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecXAuthPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompAnyRegex-swift.var/title",
          "value": "kSCCompAnyRegex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompAnyRegex-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCCompAnyRegex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthName-swift.var/title",
          "value": "kSCPropNetIPSecXAuthName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthName-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecXAuthName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecAuthenticationMethodCertificate-swift.var/title",
          "value": "kSCValNetIPSecAuthenticationMethodCertificate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecAuthenticationMethodCertificate-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetIPSecAuthenticationMethodCertificate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecXAuthPasswordEncryptionKeychain-swift.var/title",
          "value": "kSCValNetIPSecXAuthPasswordEncryptionKeychain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecXAuthPasswordEncryptionKeychain-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetIPSecXAuthPasswordEncryptionKeychain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCResvInactive-swift.var/title",
          "value": "kSCResvInactive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCResvInactive-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCResvInactive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecStatus-swift.var/title",
          "value": "kSCPropNetIPSecStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecStatus-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecAuthenticationMethodHybrid-swift.var/title",
          "value": "kSCValNetIPSecAuthenticationMethodHybrid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecAuthenticationMethodHybrid-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetIPSecAuthenticationMethodHybrid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCResvLink-swift.var/title",
          "value": "kSCResvLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCResvLink-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCResvLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthEnabled-swift.var/title",
          "value": "kSCPropNetIPSecXAuthEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthEnabled-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecXAuthEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfdata/title",
          "value": "CFDataRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecLocalIdentifierTypeKeyID-swift.var/title",
          "value": "kSCValNetIPSecLocalIdentifierTypeKeyID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecLocalIdentifierTypeKeyID-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetIPSecLocalIdentifierTypeKeyID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthPasswordEncryption-swift.var/title",
          "value": "kSCPropNetIPSecXAuthPasswordEncryption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthPasswordEncryption-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecXAuthPasswordEncryption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecAuthenticationMethodSharedSecret-swift.var/title",
          "value": "kSCValNetIPSecAuthenticationMethodSharedSecret"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCValNetIPSecAuthenticationMethodSharedSecret-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCValNetIPSecAuthenticationMethodSharedSecret"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/kscvalnetipsecxauthpasswordencryptionkeychain-swift.var"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/kscvalnetipsecxauthpasswordencryptionkeychain-swift.var"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
