{
  "abstract": [
    {
      "text": "The deprecated value Keychain.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetAirPortAuthPasswordEncryptionKeychain-c.var"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kSCValNetAirPortAuthPasswordEncryptionKeychain",
    "fragments": [
      {
        "kind": "identifier",
        "text": "kSCValNetAirPortAuthPasswordEncryptionKeychain"
      }
    ],
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kSCValNetAirPortAuthPasswordEncryptionKeychain"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.9",
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kSCValNetAirPortAuthPasswordEncryptionKeychain"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFStringRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kSCValNetAirPortAuthPasswordEncryptionKeychain"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/cfdata": {
      "abstract": [
        {
          "text": "A reference to an immutable CFData object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFData"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdata",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFData",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdata"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfstring": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeyBSSID": {
      "abstract": [
        {
          "text": "The key for the network’s BSSID, which is represented as a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCNNetworkInfoKeyBSSID"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeyBSSID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCNNetworkInfoKeyBSSID",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kcnnetworkinfokeybssid"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeySSID": {
      "abstract": [
        {
          "text": "The key for the network’s SSID, which is represented as a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstring",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCNNetworkInfoKeySSID"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeySSID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCNNetworkInfoKeySSID",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kcnnetworkinfokeyssid"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeySSIDData": {
      "abstract": [
        {
          "text": "The key for the network’s SSID, which is represented as a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdata",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCNNetworkInfoKeySSIDData"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeySSIDData",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCNNetworkInfoKeySSIDData",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kcnnetworkinfokeyssiddata"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompAnyRegex-swift.var": {
      "abstract": [
        {
          "text": "A regular expression pattern that matches any component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCCompAnyRegex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompAnyRegex-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCCompAnyRegex"
        }
      ],
      "role": "symbol",
      "title": "kSCCompAnyRegex",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ksccompanyregex-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecConnectTime-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key ConnectTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecConnectTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecConnectTime-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecConnectTime"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecConnectTime",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecconnecttime-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecRemoteAddress-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key RemoteAddress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecRemoteAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecRemoteAddress-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecRemoteAddress"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecRemoteAddress",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecremoteaddress-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecStatus-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key Status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecStatus-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecStatus"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecStatus",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecstatus-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthEnabled-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key XAuthEnabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthEnabled-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthEnabled"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecXAuthEnabled",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecxauthenabled-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthName-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key XAuthName.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthName-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthName"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecXAuthName",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecxauthname-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPassword-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key XAuthPassword.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthPassword"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPassword-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthPassword"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecXAuthPassword",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecxauthpassword-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPasswordEncryption-swift.var": {
      "abstract": [
        {
          "text": "The IPSec key XAuthPasswordEncryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthPasswordEncryption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPasswordEncryption-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetIPSecXAuthPasswordEncryption"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetIPSecXAuthPasswordEncryption",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetipsecxauthpasswordencryption-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesProxyAutoConfigJavaScript-swift.var": {
      "abstract": [
        {
          "text": "The Proxies key ProxyAutoConfigJavaScript.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesProxyAutoConfigJavaScript"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesProxyAutoConfigJavaScript-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCPropNetProxiesProxyAutoConfigJavaScript"
        }
      ],
      "role": "symbol",
      "title": "kSCPropNetProxiesProxyAutoConfigJavaScript",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropnetproxiesproxyautoconfigjavascript-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserGID-c.var": {
      "abstract": [
        {
          "text": "The deprecated key GID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSCPropUsersConsoleUserGID"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserGID-c.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSCPropUsersConsoleUserGID",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropusersconsoleusergid-c.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserName-c.var": {
      "abstract": [
        {
          "text": "The deprecated key Name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSCPropUsersConsoleUserName"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserName-c.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSCPropUsersConsoleUserName",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropusersconsoleusername-c.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserUID-c.var": {
      "abstract": [
        {
          "text": "The deprecated key UID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSCPropUsersConsoleUserUID"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserUID-c.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSCPropUsersConsoleUserUID",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscpropusersconsoleuseruid-c.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetAirPortAuthPasswordEncryptionKeychain-c.var": {
      "abstract": [
        {
          "text": "The deprecated value Keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kSCValNetAirPortAuthPasswordEncryptionKeychain"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCValNetAirPortAuthPasswordEncryptionKeychain-c.var",
      "kind": "symbol",
      "role": "symbol",
      "title": "kSCValNetAirPortAuthPasswordEncryptionKeychain",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscvalnetairportauthpasswordencryptionkeychain-c.var"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeyBSSID",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeySSID",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kCNNetworkInfoKeySSIDData",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompAnyRegex-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecConnectTime-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecRemoteAddress-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecStatus-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthEnabled-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthName-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPassword-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetIPSecXAuthPasswordEncryption-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropNetProxiesProxyAutoConfigJavaScript-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserGID-c.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserName-c.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCPropUsersConsoleUserUID-c.var"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecRemoteAddress-swift.var/title",
          "value": "kSCPropNetIPSecRemoteAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecRemoteAddress-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecRemoteAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthPassword-swift.var/title",
          "value": "kSCPropNetIPSecXAuthPassword"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthPassword-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecXAuthPassword"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecConnectTime-swift.var/title",
          "value": "kSCPropNetIPSecConnectTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecConnectTime-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecConnectTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthName-swift.var/title",
          "value": "kSCPropNetIPSecXAuthName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthName-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecXAuthName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfstring/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesProxyAutoConfigJavaScript-swift.var/title",
          "value": "kSCPropNetProxiesProxyAutoConfigJavaScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetProxiesProxyAutoConfigJavaScript-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetProxiesProxyAutoConfigJavaScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthEnabled-swift.var/title",
          "value": "kSCPropNetIPSecXAuthEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthEnabled-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecXAuthEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfdata/title",
          "value": "CFDataRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompAnyRegex-swift.var/title",
          "value": "kSCCompAnyRegex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompAnyRegex-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCCompAnyRegex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecStatus-swift.var/title",
          "value": "kSCPropNetIPSecStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecStatus-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthPasswordEncryption-swift.var/title",
          "value": "kSCPropNetIPSecXAuthPasswordEncryption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCPropNetIPSecXAuthPasswordEncryption-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCPropNetIPSecXAuthPasswordEncryption"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/kscvalnetairportauthpasswordencryptionkeychain-c.var"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
