{
  "abstract": [
    {
      "text": "Keys that correspond to network entity dictionaries in the persistent store.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Network Entity Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNet6to4",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "6to4 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/6to4-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to components in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Component Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/component-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetDNS",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DNS Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/dns-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetEthernet",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ethernet Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ethernet-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys": {
      "abstract": [
        {
          "text": "General-purpose keys that apply to multiple dictionaries in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Generic Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/generic-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompHostnames",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Hostnames Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/hostnames-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompInterface",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Interface Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/interface-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetInterface",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Interface Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/interface-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetIPSec",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPSec Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ipsec-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetIPv4",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPv4 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ipv4-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetIPv6",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPv6 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ipv6-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNet6to4-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "6to4",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNet6to4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNet6to4-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNet6to4"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNet6to4",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnet6to4-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetAirPort-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "AirPort",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetAirPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetAirPort-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetAirPort"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetAirPort",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetairport-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetDHCP-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "DHCP",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetDHCP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetDHCP-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetDHCP"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetDHCP",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetdhcp-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetDNS-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "DNS",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetDNS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetDNS-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetDNS"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetDNS",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetdns-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetEthernet-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "Ethernet",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetEthernet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetEthernet-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetEthernet"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetEthernet",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetethernet-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetFireWire-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "FireWire",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetFireWire"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetFireWire-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetFireWire"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetFireWire",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetfirewire-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPSec-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "IPSec",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetIPSec"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPSec-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetIPSec"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetIPSec",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetipsec-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPv4-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "IPv4",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetIPv4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPv4-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetIPv4"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetIPv4",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetipv4-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPv6-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "IPv6",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetIPv6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPv6-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetIPv6"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetIPv6",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetipv6-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetInterface-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "Interface",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetInterface"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetInterface-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetInterface"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetInterface",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetinterface-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetL2TP-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "L2TP",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetL2TP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetL2TP-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetL2TP"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetL2TP",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetl2tp-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetLink-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "Link",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetLink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetLink-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetLink"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetLink",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetlink-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetModem-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "Modem",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetModem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetModem-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetModem"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetModem",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetmodem-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPP-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "PPP",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetPPP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPP-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetPPP"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetPPP",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetppp-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPPSerial-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "PPPSerial",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetPPPSerial"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPPSerial-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetPPPSerial"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetPPPSerial",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetpppserial-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPPoE-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "PPPoE",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetPPPoE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPPoE-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetPPPoE"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetPPPoE",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetpppoe-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPTP-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "PPTP",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetPPTP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPTP-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetPPTP"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetPPTP",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetpptp-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetProxies-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "Proxies",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetProxies"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetProxies-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetProxies"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetProxies",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetproxies-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetSMB-swift.var": {
      "abstract": [
        {
          "text": "The network entity key for the ",
          "type": "text"
        },
        {
          "code": "SMB",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCEntNetSMB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetSMB-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCEntNetSMB"
        }
      ],
      "role": "symbol",
      "title": "kSCEntNetSMB",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscentnetsmb-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetLink",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Link Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/link-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetModem",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Modem Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/modem-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompNetwork",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/network-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to preferences in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Preference Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/preference-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCSchemaDefinitions",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scschemadefinitions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetAirPort-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetDHCP-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetDNS-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetEthernet-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetFireWire-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetInterface-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPSec-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPv4-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPv6-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetL2TP-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetLink-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetModem-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPP-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPPoE-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPPSerial-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPTP-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetProxies-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetSMB-swift.var",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNet6to4-swift.var"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetAirPort-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetDHCP-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetDNS-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetEthernet-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetFireWire-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetInterface-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPSec-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPv4-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetIPv6-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetL2TP-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetLink-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetModem-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPP-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPPoE-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPPSerial-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetPPTP-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetProxies-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNetSMB-swift.var",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCEntNet6to4-swift.var"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetPPPoE-swift.var/title",
          "value": "kSCEntNetPPPoE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetPPPoE-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetPPPoE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetModem-swift.var/title",
          "value": "kSCEntNetModem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetModem-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetModem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetProxies-swift.var/title",
          "value": "kSCEntNetProxies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetProxies-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetProxies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetIPSec-swift.var/title",
          "value": "kSCEntNetIPSec"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetIPSec-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetIPSec"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetAirPort-swift.var/title",
          "value": "kSCEntNetAirPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetAirPort-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetAirPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetIPv6-swift.var/title",
          "value": "kSCEntNetIPv6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetIPv6-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetIPv6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetDHCP-swift.var/title",
          "value": "kSCEntNetDHCP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetDHCP-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetDHCP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetPPP-swift.var/title",
          "value": "kSCEntNetPPP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetPPP-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetPPP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetL2TP-swift.var/title",
          "value": "kSCEntNetL2TP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetL2TP-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetL2TP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetEthernet-swift.var/title",
          "value": "kSCEntNetEthernet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetEthernet-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetEthernet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetLink-swift.var/title",
          "value": "kSCEntNetLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetLink-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNet6to4-swift.var/title",
          "value": "kSCEntNet6to4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNet6to4-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNet6to4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetIPv4-swift.var/title",
          "value": "kSCEntNetIPv4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetIPv4-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetIPv4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetFireWire-swift.var/title",
          "value": "kSCEntNetFireWire"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetFireWire-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetFireWire"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetPPTP-swift.var/title",
          "value": "kSCEntNetPPTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetPPTP-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetPPTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetInterface-swift.var/title",
          "value": "kSCEntNetInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetInterface-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetDNS-swift.var/title",
          "value": "kSCEntNetDNS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetDNS-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetDNS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetSMB-swift.var/title",
          "value": "kSCEntNetSMB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetSMB-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetSMB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetPPPSerial-swift.var/title",
          "value": "kSCEntNetPPPSerial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCEntNetPPPSerial-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCEntNetPPPSerial"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/network-entity-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/network-entity-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
