{
  "abstract": [
    {
      "text": "Returns all Ethernet bond interfaces on the system.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceCopyAll(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SCBondInterfaceCopyAll",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCBondInterfaceCopyAll"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SCPreferencesRef",
        "text": "SCPreferences"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFArrayRef",
        "text": "CFArray"
      }
    ],
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCBondInterfaceCopyAll"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SCBondInterfaceCopyAll(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCBondInterfaceCopyAll"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "prefs"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SCPreferencesRef",
              "text": "SCPreferences"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArray"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The preferences session.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "prefs"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The list of Ethernet bond interfaces on the system. You must release the returned value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceCopyAll(_:)": {
      "abstract": [
        {
          "text": "Returns all Ethernet bond interfaces on the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCBondInterfaceCopyAll"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceCopyAll(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCBondInterfaceCopyAll"
        }
      ],
      "role": "symbol",
      "title": "SCBondInterfaceCopyAll(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scbondinterfacecopyall(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceCopyAvailableMemberInterfaces(_:)": {
      "abstract": [
        {
          "text": "Returns all network capable devices on the system that can be added to an Ethernet bond interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCBondInterfaceCopyAvailableMemberInterfaces"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceCopyAvailableMemberInterfaces(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCBondInterfaceCopyAvailableMemberInterfaces"
        }
      ],
      "role": "symbol",
      "title": "SCBondInterfaceCopyAvailableMemberInterfaces(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scbondinterfacecopyavailablememberinterfaces(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceCopyStatus(_:)": {
      "abstract": [
        {
          "text": "Returns the status of the specified Ethernet bond interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCBondInterfaceCopyStatus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCBondInterfaceRef",
          "text": "SCBondInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCBondStatusRef",
          "text": "SCBondStatus"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceCopyStatus(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCBondInterfaceCopyStatus"
        }
      ],
      "role": "symbol",
      "title": "SCBondInterfaceCopyStatus(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scbondinterfacecopystatus(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceCreate(_:)": {
      "abstract": [
        {
          "text": "Creates a new Ethernet bond interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCBondInterfaceCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCBondInterfaceRef",
          "text": "SCBondInterface"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceCreate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCBondInterfaceCreate"
        }
      ],
      "role": "symbol",
      "title": "SCBondInterfaceCreate(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scbondinterfacecreate(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceGetMemberInterfaces(_:)": {
      "abstract": [
        {
          "text": "Returns the member interfaces for the specified Ethernet bond interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCBondInterfaceGetMemberInterfaces"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCBondInterfaceRef",
          "text": "SCBondInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceGetMemberInterfaces(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCBondInterfaceGetMemberInterfaces"
        }
      ],
      "role": "symbol",
      "title": "SCBondInterfaceGetMemberInterfaces(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scbondinterfacegetmemberinterfaces(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceGetOptions(_:)": {
      "abstract": [
        {
          "text": "Returns the configuration settings associated with the specified Ethernet bond interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCBondInterfaceGetOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCBondInterfaceRef",
          "text": "SCBondInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceGetOptions(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCBondInterfaceGetOptions"
        }
      ],
      "role": "symbol",
      "title": "SCBondInterfaceGetOptions(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scbondinterfacegetoptions(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceRemove(_:)": {
      "abstract": [
        {
          "text": "Removes the Ethernet bond interface from the configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCBondInterfaceRemove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCBondInterfaceRef",
          "text": "SCBondInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceRemove(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCBondInterfaceRemove"
        }
      ],
      "role": "symbol",
      "title": "SCBondInterfaceRemove(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scbondinterfaceremove(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceSetLocalizedDisplayName(_:_:)": {
      "abstract": [
        {
          "text": "Sets the localized display name for the specified Ethernet bond interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCBondInterfaceSetLocalizedDisplayName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCBondInterfaceRef",
          "text": "SCBondInterface"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceSetLocalizedDisplayName(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCBondInterfaceSetLocalizedDisplayName"
        }
      ],
      "role": "symbol",
      "title": "SCBondInterfaceSetLocalizedDisplayName(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scbondinterfacesetlocalizeddisplayname(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceSetMemberInterfaces(_:_:)": {
      "abstract": [
        {
          "text": "Sets the member interfaces for the specified Ethernet bond interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCBondInterfaceSetMemberInterfaces"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCBondInterfaceRef",
          "text": "SCBondInterface"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceSetMemberInterfaces(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCBondInterfaceSetMemberInterfaces"
        }
      ],
      "role": "symbol",
      "title": "SCBondInterfaceSetMemberInterfaces(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scbondinterfacesetmemberinterfaces(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceSetOptions(_:_:)": {
      "abstract": [
        {
          "text": "Sets the configuration settings for the specified Ethernet bond interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCBondInterfaceSetOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCBondInterfaceRef",
          "text": "SCBondInterface"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceSetOptions(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCBondInterfaceSetOptions"
        }
      ],
      "role": "symbol",
      "title": "SCBondInterfaceSetOptions(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scbondinterfacesetoptions(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondStatusGetInterfaceStatus(_:_:)": {
      "abstract": [
        {
          "text": "Returns the status of the specified member interface of an Ethernet bond or the status of the bond as a whole.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCBondStatusGetInterfaceStatus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCBondStatusRef",
          "text": "SCBondStatus"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondStatusGetInterfaceStatus(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCBondStatusGetInterfaceStatus"
        }
      ],
      "role": "symbol",
      "title": "SCBondStatusGetInterfaceStatus(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scbondstatusgetinterfacestatus(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondStatusGetMemberInterfaces(_:)": {
      "abstract": [
        {
          "text": "Returns the member interfaces that are represented with the Ethernet bond interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCBondStatusGetMemberInterfaces"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCBondStatusRef",
          "text": "SCBondStatus"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondStatusGetMemberInterfaces(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCBondStatusGetMemberInterfaces"
        }
      ],
      "role": "symbol",
      "title": "SCBondStatusGetMemberInterfaces(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scbondstatusgetmemberinterfaces(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondStatusGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the type identifier of all ",
          "type": "text"
        },
        {
          "code": "SCBondStatusRef",
          "type": "codeVoice"
        },
        {
          "text": " instances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCBondStatusGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondStatusGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCBondStatusGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "SCBondStatusGetTypeID()",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scbondstatusgettypeid()"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences": {
      "abstract": [
        {
          "text": "The handle to an open preferences session for accessing system configuration preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferences"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferences"
        }
      ],
      "role": "symbol",
      "title": "SCPreferences",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferences"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFArrayRef": {
      "abstract": [
        {
          "text": "A reference to an immutable array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFArray",
      "type": "topic",
      "url": "/documentation/corefoundation/cfarray"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Ethernet-Bond-Interfaces",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceCopyAvailableMemberInterfaces(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceCopyStatus(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceCreate(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceGetMemberInterfaces(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceGetOptions(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceRemove(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceSetLocalizedDisplayName(_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceSetMemberInterfaces(_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceSetOptions(_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondStatusGetInterfaceStatus(_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondStatusGetMemberInterfaces(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondStatusGetTypeID()"
      ],
      "title": "Configuring Ethernet Bond Interfaces"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCBondInterfaceCopyAll"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCBondInterfaceCopyAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Ethernet-Bond-Interfaces",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceCopyAvailableMemberInterfaces(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceCopyStatus(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceCreate(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceGetMemberInterfaces(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceGetOptions(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceRemove(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceSetLocalizedDisplayName(_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceSetMemberInterfaces(_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondInterfaceSetOptions(_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondStatusGetInterfaceStatus(_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondStatusGetMemberInterfaces(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCBondStatusGetTypeID()"
              ],
              "title": "Configuring Ethernet Bond Interfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFArrayRef",
                    "text": "CFArrayRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCBondInterfaceCopyAll"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SCPreferencesRef",
                    "text": "SCPreferencesRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "prefs"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The preferences session.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "prefs"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The list of Ethernet bond interfaces on the system. You must release the returned value.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondStatusGetTypeID()/title",
          "value": "SCBondStatusGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondStatusGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCBondStatusGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceCopyStatus(_:)/title",
          "value": "SCBondInterfaceCopyStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceCopyStatus(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCBondInterfaceCopyStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondStatusGetMemberInterfaces(_:)/title",
          "value": "SCBondStatusGetMemberInterfaces"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondStatusGetMemberInterfaces(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCBondStatusGetMemberInterfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceCopyAvailableMemberInterfaces(_:)/title",
          "value": "SCBondInterfaceCopyAvailableMemberInterfaces"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceCopyAvailableMemberInterfaces(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCBondInterfaceCopyAvailableMemberInterfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceCopyAll(_:)/title",
          "value": "SCBondInterfaceCopyAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceCopyAll(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCBondInterfaceCopyAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceSetLocalizedDisplayName(_:_:)/title",
          "value": "SCBondInterfaceSetLocalizedDisplayName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceSetLocalizedDisplayName(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCBondInterfaceSetLocalizedDisplayName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceCreate(_:)/title",
          "value": "SCBondInterfaceCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceCreate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCBondInterfaceCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceGetMemberInterfaces(_:)/title",
          "value": "SCBondInterfaceGetMemberInterfaces"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceGetMemberInterfaces(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCBondInterfaceGetMemberInterfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFArrayRef/title",
          "value": "CFArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceSetMemberInterfaces(_:_:)/title",
          "value": "SCBondInterfaceSetMemberInterfaces"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceSetMemberInterfaces(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCBondInterfaceSetMemberInterfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceRemove(_:)/title",
          "value": "SCBondInterfaceRemove"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceRemove(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCBondInterfaceRemove"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceSetOptions(_:_:)/title",
          "value": "SCBondInterfaceSetOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceSetOptions(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCBondInterfaceSetOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceGetOptions(_:)/title",
          "value": "SCBondInterfaceGetOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondInterfaceGetOptions(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCBondInterfaceGetOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondStatusGetInterfaceStatus(_:_:)/title",
          "value": "SCBondStatusGetInterfaceStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCBondStatusGetInterfaceStatus(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCBondStatusGetInterfaceStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferences/title",
          "value": "SCPreferencesRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferences/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/scbondinterfacecopyall(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/scbondinterfacecopyall(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
