{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopyspecific"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "SCDynamicStoreCopySpecific"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The functions of the ",
              "type": "text"
            },
            {
              "code": "SCDynamicStoreCopySpecific",
              "type": "codeVoice"
            },
            {
              "text": " programming interface allow an application to determine specific configuration information about the current system (for example, the computer or sharing name or the currently logged-in user). Note that these functions follow Core Foundation function-name conventions. A function that has “Create” or “Copy” in its name returns a reference you must release with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease": {
      "abstract": [
        {
          "text": "Releases a Core Foundation object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRelease",
      "type": "topic",
      "url": "/documentation/corefoundation/1521153-cfrelease"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyComputerName(_:_:)": {
      "abstract": [
        {
          "text": "Returns the current computer name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCDynamicStoreCopyComputerName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCDynamicStoreRef",
          "text": "SCDynamicStore"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringEncoding",
          "text": "CFStringEncoding"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyComputerName(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCDynamicStoreCopyComputerName"
        }
      ],
      "role": "symbol",
      "title": "SCDynamicStoreCopyComputerName(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scdynamicstorecopycomputername(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyConsoleUser(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns information about the user currently logged into the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCDynamicStoreCopyConsoleUser"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCDynamicStoreRef",
          "text": "SCDynamicStore"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@uid_t",
          "text": "uid_t"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gid_t",
          "text": "gid_t"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyConsoleUser(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCDynamicStoreCopyConsoleUser"
        }
      ],
      "role": "symbol",
      "title": "SCDynamicStoreCopyConsoleUser(_:_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scdynamicstorecopyconsoleuser(_:_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyLocalHostName(_:)": {
      "abstract": [
        {
          "text": "Returns the current local host name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCDynamicStoreCopyLocalHostName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCDynamicStoreRef",
          "text": "SCDynamicStore"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyLocalHostName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCDynamicStoreCopyLocalHostName"
        }
      ],
      "role": "symbol",
      "title": "SCDynamicStoreCopyLocalHostName(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scdynamicstorecopylocalhostname(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyLocation(_:)": {
      "abstract": [
        {
          "text": "Returns the current location identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCDynamicStoreCopyLocation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCDynamicStoreRef",
          "text": "SCDynamicStore"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyLocation(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCDynamicStoreCopyLocation"
        }
      ],
      "role": "symbol",
      "title": "SCDynamicStoreCopyLocation(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scdynamicstorecopylocation(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyProxies(_:)": {
      "abstract": [
        {
          "text": "Returns the key-value pairs that represent the current internet proxy settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCDynamicStoreCopyProxies"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCDynamicStoreRef",
          "text": "SCDynamicStore"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyProxies(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCDynamicStoreCopyProxies"
        }
      ],
      "role": "symbol",
      "title": "SCDynamicStoreCopyProxies(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scdynamicstorecopyproxies(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dhcpclientpreferences": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dhcpclientpreferences",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DHCPClientPreferences",
      "type": "topic",
      "url": "/documentation/systemconfiguration/dhcpclientpreferences"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstore-gb2": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstore-gb2",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCDynamicStore",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scdynamicstore-gb2"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopydhcpinfo-apicollection": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopydhcpinfo-apicollection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCDynamicStoreCopyDHCPInfo",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scdynamicstorecopydhcpinfo-apicollection"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorekey": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorekey",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCDynamicStoreKey",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scdynamicstorekey"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetwork": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetwork",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCNetwork",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetwork"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCNetworkConfiguration",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconnection-g7e": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconnection-g7e",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCNetworkConnection",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnection-g7e"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkreachability-g7d": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkreachability-g7d",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCNetworkReachability",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkreachability-g7d"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferences-ft8": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferences-ft8",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCPreferences",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferences-ft8"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencespath": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencespath",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCPreferencesPath",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencespath"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencessetspecific": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencessetspecific",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCPreferencesSetSpecific",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencessetspecific"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCSchemaDefinitions",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scschemadefinitions"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/system-configuration": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/system-configuration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration/system-configuration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SystemConfiguration Constants",
      "type": "topic",
      "url": "/documentation/systemconfiguration/systemconfiguration-constants"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SystemConfiguration Data Types",
      "type": "topic",
      "url": "/documentation/systemconfiguration/systemconfiguration-data-types"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SystemConfiguration Enumerations",
      "type": "topic",
      "url": "/documentation/systemconfiguration/systemconfiguration-enumerations"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SystemConfiguration Functions",
      "type": "topic",
      "url": "/documentation/systemconfiguration/systemconfiguration-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstore-gb2",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorekey",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetwork",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconnection-g7e",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkreachability-g7d",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferences-ft8",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencespath",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencessetspecific",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/system-configuration",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-enumerations",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-constants",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-functions",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Group",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyComputerName(_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyConsoleUser(_:_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyLocalHostName(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyLocation(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyProxies(_:)"
      ],
      "title": "Group"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Group",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyComputerName(_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyConsoleUser(_:_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyLocalHostName(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyLocation(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreCopyProxies(_:)"
              ],
              "title": "Group"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dhcpclientpreferences",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstore-gb2",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopydhcpinfo-apicollection",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorekey",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetwork",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconnection-g7e",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkreachability-g7d",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferences-ft8",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencespath",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencessetspecific",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/system-configuration",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-enumerations",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreCopyLocalHostName(_:)/title",
          "value": "SCDynamicStoreCopyLocalHostName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreCopyLocalHostName(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCDynamicStoreCopyLocalHostName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreCopyComputerName(_:_:)/title",
          "value": "SCDynamicStoreCopyComputerName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreCopyComputerName(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCDynamicStoreCopyComputerName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreCopyProxies(_:)/title",
          "value": "SCDynamicStoreCopyProxies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreCopyProxies(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCDynamicStoreCopyProxies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreCopyConsoleUser(_:_:_:)/title",
          "value": "SCDynamicStoreCopyConsoleUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreCopyConsoleUser(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCDynamicStoreCopyConsoleUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreCopyLocation(_:)/title",
          "value": "SCDynamicStoreCopyLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreCopyLocation(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCDynamicStoreCopyLocation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/scdynamicstorecopyspecific"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/scdynamicstorecopyspecific"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
