{
  "abstract": [
    {
      "text": "Returns the type identifier of all ",
      "type": "text"
    },
    {
      "code": "SCDynamicStore",
      "type": "codeVoice"
    },
    {
      "text": " instances.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreGetTypeID()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SCDynamicStoreGetTypeID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCDynamicStoreGetTypeID"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFTypeID",
        "text": "CFTypeID"
      }
    ],
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCDynamicStoreGetTypeID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SCDynamicStoreGetTypeID()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCDynamicStoreGetTypeID"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTypeID",
              "text": "CFTypeID"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The type identifier of all ",
              "type": "text"
            },
            {
              "code": "SCDynamicStore",
              "type": "codeVoice"
            },
            {
              "text": " instances.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the type identifier of all ",
          "type": "text"
        },
        {
          "code": "SCDynamicStore",
          "type": "codeVoice"
        },
        {
          "text": " instances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCDynamicStoreGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCDynamicStoreGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "SCDynamicStoreGetTypeID()",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scdynamicstoregettypeid()"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFTypeID": {
      "abstract": [
        {
          "text": "A type for unique, constant integer values that identify particular Core Foundation opaque types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeID",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFTypeID",
      "type": "topic",
      "url": "/documentation/corefoundation/cftypeid"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCDynamicStoreGetTypeID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCDynamicStoreGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeID",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFTypeID",
                    "text": "CFTypeID"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCDynamicStoreGetTypeID"
                  },
                  {
                    "kind": "text",
                    "text": "();"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The type identifier of all ",
                    "type": "text"
                  },
                  {
                    "code": "SCDynamicStore",
                    "type": "codeVoice"
                  },
                  {
                    "text": " instances.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreGetTypeID()/title",
          "value": "SCDynamicStoreGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCDynamicStoreGetTypeID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/scdynamicstoregettypeid()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/scdynamicstoregettypeid()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
