{"metadata":{"modules":[{"name":"System Configuration"}],"symbolKind":"func","role":"symbol","platforms":[{"beta":false,"deprecated":false,"introducedAt":"10.1","name":"macOS","unavailable":false}],"roleHeading":"Function","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCDynamicStoreKeyCreateProxies","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CFAllocator","preciseIdentifier":"c:@T@CFAllocatorRef"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"CFString","preciseIdentifier":"c:@T@CFStringRef"}],"externalID":"c:@F@SCDynamicStoreKeyCreateProxies","title":"SCDynamicStoreKeyCreateProxies(_:)","navigatorTitle":[{"kind":"identifier","text":"SCDynamicStoreKeyCreateProxies"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateProxies(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/systemconfiguration/scdynamicstorekeycreateproxies(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/systemconfiguration/scdynamicstorekeycreateproxies(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.systemconfiguration/documentation/SystemConfiguration"]]},"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateNetworkGlobalEntity(_:_:_:)","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateNetworkInterface(_:_:)","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateNetworkInterfaceEntity(_:_:_:_:)","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateNetworkServiceEntity(_:_:_:_:)","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateComputerName(_:)","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateConsoleUser(_:)","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateHostNames(_:)","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateLocation(_:)"],"anchor":"Group","title":"Group"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCDynamicStoreKeyCreateProxies"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"allocator"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFAllocatorRef","text":"CFAllocator"},{"kind":"text","text":"?) -> "},{"identifier":"doc://com.externally.resolved.symbol/c:@T@CFStringRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef","text":"CFString"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"parameters":[{"name":"allocator","content":[{"inlineContent":[{"type":"text","text":"The allocator that should be used to allocate memory for this key. This parameter may be "},{"type":"codeVoice","code":"NULL"},{"type":"text","text":" in which case the current default allocator is used. If this value is not a valid "},{"identifier":"doc://com.apple.documentation/documentation/corefoundation/cfallocator","type":"reference","isActive":true},{"type":"text","text":", the behavior is undefined."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"A notification string for the current proxy settings."}],"type":"paragraph"}],"kind":"content"},{"content":[{"anchor":"Discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this key with the "},{"type":"reference","identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreSetNotificationKeys(_:_:_:)","isActive":true},{"type":"text","text":" function."}]}],"kind":"content"}],"abstract":[{"text":"Creates a key that can be used to receive notifications when the current network proxy settings are changed.","type":"text"}],"references":{"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateProxies(_:)":{"title":"SCDynamicStoreKeyCreateProxies(_:)","navigatorTitle":[{"kind":"identifier","text":"SCDynamicStoreKeyCreateProxies"}],"kind":"symbol","abstract":[{"type":"text","text":"Creates a key that can be used to receive notifications when the current network proxy settings are changed."}],"url":"/documentation/systemconfiguration/scdynamicstorekeycreateproxies(_:)","role":"symbol","type":"topic","identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateProxies(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"SCDynamicStoreKeyCreateProxies","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CFAllocator","preciseIdentifier":"c:@T@CFAllocatorRef","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString"}]},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateNetworkServiceEntity(_:_:_:_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCDynamicStoreKeyCreateNetworkServiceEntity"},{"kind":"text","text":"("},{"text":"CFAllocator","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFAllocatorRef"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@CFStringRef","text":"CFString","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@T@CFStringRef","text":"CFString","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"CFString","preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Creates a dynamic store key that can be used to access the per-service network configuration information.","type":"text"}],"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateNetworkServiceEntity(_:_:_:_:)","kind":"symbol","title":"SCDynamicStoreKeyCreateNetworkServiceEntity(_:_:_:_:)","navigatorTitle":[{"text":"SCDynamicStoreKeyCreateNetworkServiceEntity","kind":"identifier"}],"role":"symbol","url":"/documentation/systemconfiguration/scdynamicstorekeycreatenetworkserviceentity(_:_:_:_:)"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateNetworkInterface(_:_:)":{"navigatorTitle":[{"text":"SCDynamicStoreKeyCreateNetworkInterface","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Creates a dynamic store key that can be used to access the network interface configuration information in the dynamic store."}],"type":"topic","title":"SCDynamicStoreKeyCreateNetworkInterface(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"SCDynamicStoreKeyCreateNetworkInterface","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CFAllocator","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFAllocatorRef"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef","text":"CFString"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef","text":"CFString"}],"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateNetworkInterface(_:_:)","kind":"symbol","url":"/documentation/systemconfiguration/scdynamicstorekeycreatenetworkinterface(_:_:)"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateComputerName(_:)":{"navigatorTitle":[{"text":"SCDynamicStoreKeyCreateComputerName","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Creates a key that can be used to receive notifications when the current computer name changes.","type":"text"}],"type":"topic","title":"SCDynamicStoreKeyCreateComputerName(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCDynamicStoreKeyCreateComputerName"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CFAllocatorRef","kind":"typeIdentifier","text":"CFAllocator"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@T@CFStringRef","text":"CFString","kind":"typeIdentifier"}],"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateComputerName(_:)","kind":"symbol","url":"/documentation/systemconfiguration/scdynamicstorekeycreatecomputername(_:)"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateNetworkInterfaceEntity(_:_:_:_:)":{"role":"symbol","title":"SCDynamicStoreKeyCreateNetworkInterfaceEntity(_:_:_:_:)","type":"topic","url":"/documentation/systemconfiguration/scdynamicstorekeycreatenetworkinterfaceentity(_:_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCDynamicStoreKeyCreateNetworkInterfaceEntity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CFAllocator","preciseIdentifier":"c:@T@CFAllocatorRef","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@CFStringRef","text":"CFString","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@T@CFStringRef","text":"CFString","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"CFString","preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier"}],"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateNetworkInterfaceEntity(_:_:_:_:)","navigatorTitle":[{"text":"SCDynamicStoreKeyCreateNetworkInterfaceEntity","kind":"identifier"}],"abstract":[{"text":"Creates a dynamic store key that can be used to access the per-interface network configuration information in the dynamic store.","type":"text"}],"kind":"symbol"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration":{"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration","title":"System Configuration","type":"topic","abstract":[{"type":"text","text":"Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active."}],"role":"collection","kind":"symbol","url":"/documentation/systemconfiguration"},"doc://com.apple.documentation/documentation/corefoundation/cfallocator":{"fragments":[{"text":"class ","kind":"text"},{"text":"CFAllocator","kind":"identifier"}],"type":"topic","abstract":[{"text":"A reference to a CFAllocator object. ","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/corefoundation/cfallocator","kind":"symbol","title":"CFAllocator","role":"symbol","url":"/documentation/corefoundation/cfallocator"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreate":{"role":"symbol","title":"SCDynamicStoreKeyCreate","type":"topic","url":"/documentation/systemconfiguration/scdynamicstorekeycreate","fragments":[{"text":"SCDynamicStoreKeyCreate","kind":"identifier"}],"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreate","abstract":[{"text":"Creates a dynamic store key using the specified format.","type":"text"}],"kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef":{"abstract":[{"type":"text","text":"A reference to a CFAllocator object. "}],"kind":"symbol","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"CFAllocator"}],"role":"symbol","url":"/documentation/corefoundation/cfallocator","title":"CFAllocator","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateNetworkGlobalEntity(_:_:_:)":{"abstract":[{"type":"text","text":"Creates a dynamic store key that can be used to access a specific global (as opposed to a per-service or per-interface) network configuration entity."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCDynamicStoreKeyCreateNetworkGlobalEntity"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CFAllocatorRef","kind":"typeIdentifier","text":"CFAllocator"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"c:@T@CFStringRef","text":"CFString","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"CFString","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@CFStringRef","text":"CFString","kind":"typeIdentifier"}],"role":"symbol","url":"/documentation/systemconfiguration/scdynamicstorekeycreatenetworkglobalentity(_:_:_:)","title":"SCDynamicStoreKeyCreateNetworkGlobalEntity(_:_:_:)","navigatorTitle":[{"text":"SCDynamicStoreKeyCreateNetworkGlobalEntity","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateNetworkGlobalEntity(_:_:_:)"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreSetNotificationKeys(_:_:_:)":{"title":"SCDynamicStoreSetNotificationKeys(_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCDynamicStoreSetNotificationKeys","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@SCDynamicStoreRef","text":"SCDynamicStore","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@T@CFArrayRef","kind":"typeIdentifier","text":"CFArray"},{"kind":"text","text":"?, "},{"preciseIdentifier":"c:@T@CFArrayRef","kind":"typeIdentifier","text":"CFArray"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"SCDynamicStoreSetNotificationKeys"}],"kind":"symbol","abstract":[{"text":"Specifies a set of keys and key patterns that should be monitored for changes.","type":"text"}],"role":"symbol","url":"/documentation/systemconfiguration/scdynamicstoresetnotificationkeys(_:_:_:)","type":"topic","identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreSetNotificationKeys(_:_:_:)"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","type":"topic"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateLocation(_:)":{"role":"symbol","title":"SCDynamicStoreKeyCreateLocation(_:)","type":"topic","url":"/documentation/systemconfiguration/scdynamicstorekeycreatelocation(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCDynamicStoreKeyCreateLocation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CFAllocator","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFAllocatorRef"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString"}],"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateLocation(_:)","navigatorTitle":[{"kind":"identifier","text":"SCDynamicStoreKeyCreateLocation"}],"abstract":[{"text":"Creates a key that can be used to receive notifications when the location identifier changes.","type":"text"}],"kind":"symbol"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateHostNames(_:)":{"abstract":[{"text":"Creates a key that can be used to receive notifications when the ","type":"text"},{"code":"HostNames","type":"codeVoice"},{"text":" entity changes.","type":"text"}],"url":"/documentation/systemconfiguration/scdynamicstorekeycreatehostnames(_:)","kind":"symbol","title":"SCDynamicStoreKeyCreateHostNames(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCDynamicStoreKeyCreateHostNames"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@CFAllocatorRef","text":"CFAllocator","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"CFString","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef"}],"type":"topic","navigatorTitle":[{"text":"SCDynamicStoreKeyCreateHostNames","kind":"identifier"}],"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateHostNames(_:)"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateConsoleUser(_:)":{"navigatorTitle":[{"text":"SCDynamicStoreKeyCreateConsoleUser","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Creates a key that can be used to receive notifications when the current console user changes.","type":"text"}],"type":"topic","title":"SCDynamicStoreKeyCreateConsoleUser(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCDynamicStoreKeyCreateConsoleUser","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CFAllocatorRef","kind":"typeIdentifier","text":"CFAllocator"},{"text":"?) -> ","kind":"text"},{"text":"CFString","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef"}],"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateConsoleUser(_:)","kind":"symbol","url":"/documentation/systemconfiguration/scdynamicstorekeycreateconsoleuser(_:)"},"doc://com.externally.resolved.symbol/c:@T@CFStringRef":{"abstract":[{"text":"A reference to a CFString object.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@CFStringRef","kind":"symbol","title":"CFString","role":"symbol","type":"topic","url":"/documentation/corefoundation/cfstring","fragments":[{"text":"class ","kind":"text"},{"text":"CFString","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS","introducedAt":"10.1"}],"op":"replace","path":"/metadata/platforms"},{"value":"Function","op":"replace","path":"/metadata/roleHeading"},{"value":"SCDynamicStoreKeyCreateProxies","op":"replace","path":"/metadata/title"},{"value":"func","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"SCDynamicStoreKeyCreateProxies","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.systemconfiguration/documentation/SystemConfiguration"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Group","generated":true,"identifiers":["doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreate","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateNetworkGlobalEntity(_:_:_:)","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateNetworkInterface(_:_:)","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateNetworkInterfaceEntity(_:_:_:_:)","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateNetworkServiceEntity(_:_:_:_:)","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateComputerName(_:)","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateConsoleUser(_:)","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateHostNames(_:)","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCDynamicStoreKeyCreateLocation(_:)"],"anchor":"Group"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"CFStringRef","identifier":"doc://com.externally.resolved.symbol/c:@T@CFStringRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFStringRef"},{"text":" ","kind":"text"},{"text":"SCDynamicStoreKeyCreateProxies","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CFAllocatorRef","identifier":"doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@CFAllocatorRef"},{"kind":"text","text":" "},{"kind":"internalParam","text":"allocator"},{"kind":"text","text":");"}],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The allocator that should be used to allocate memory for this key. This parameter may be "},{"type":"codeVoice","code":"NULL"},{"type":"text","text":" in which case the current default allocator is used. If this value is not a valid "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/corefoundation/cfallocator","isActive":true},{"type":"text","text":", the behavior is undefined."}]}],"name":"allocator"}]},"op":"replace","path":"/primaryContentSections/1"},{"value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A notification string for the current proxy settings."}]}]},"op":"replace","path":"/primaryContentSections/2"},{"value":"SCDynamicStoreKeyCreateProxies","op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateProxies(_:)/title"},{"value":[{"text":"SCDynamicStoreKeyCreateProxies","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateProxies(_:)/fragments"},{"value":"SCDynamicStoreKeyCreateNetworkServiceEntity","op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateNetworkServiceEntity(_:_:_:_:)/title"},{"value":[{"text":"SCDynamicStoreKeyCreateNetworkServiceEntity","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateNetworkServiceEntity(_:_:_:_:)/fragments"},{"value":"SCDynamicStoreKeyCreateNetworkInterface","op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateNetworkInterface(_:_:)/title"},{"value":[{"text":"SCDynamicStoreKeyCreateNetworkInterface","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateNetworkInterface(_:_:)/fragments"},{"value":"SCDynamicStoreKeyCreateComputerName","op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateComputerName(_:)/title"},{"value":[{"kind":"identifier","text":"SCDynamicStoreKeyCreateComputerName"}],"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateComputerName(_:)/fragments"},{"value":"SCDynamicStoreKeyCreateNetworkInterfaceEntity","op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateNetworkInterfaceEntity(_:_:_:_:)/title"},{"value":[{"text":"SCDynamicStoreKeyCreateNetworkInterfaceEntity","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateNetworkInterfaceEntity(_:_:_:_:)/fragments"},{"value":"CFAllocatorRef","op":"replace","path":"/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfallocator/title"},{"value":"CFAllocatorRef","op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFAllocatorRef/title"},{"value":"SCDynamicStoreKeyCreateNetworkGlobalEntity","op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateNetworkGlobalEntity(_:_:_:)/title"},{"value":[{"kind":"identifier","text":"SCDynamicStoreKeyCreateNetworkGlobalEntity"}],"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateNetworkGlobalEntity(_:_:_:)/fragments"},{"value":"SCDynamicStoreSetNotificationKeys","op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreSetNotificationKeys(_:_:_:)/title"},{"value":[{"kind":"identifier","text":"SCDynamicStoreSetNotificationKeys"}],"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreSetNotificationKeys(_:_:_:)/fragments"},{"value":"SCDynamicStoreKeyCreateLocation","op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateLocation(_:)/title"},{"value":[{"text":"SCDynamicStoreKeyCreateLocation","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateLocation(_:)/fragments"},{"value":"SCDynamicStoreKeyCreateHostNames","op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateHostNames(_:)/title"},{"value":[{"kind":"identifier","text":"SCDynamicStoreKeyCreateHostNames"}],"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateHostNames(_:)/fragments"},{"value":"SCDynamicStoreKeyCreateConsoleUser","op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateConsoleUser(_:)/title"},{"value":[{"text":"SCDynamicStoreKeyCreateConsoleUser","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCDynamicStoreKeyCreateConsoleUser(_:)/fragments"},{"value":"CFStringRef","op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}