{
  "abstract": [
    {
      "text": "The PPP-specific status of the network connection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SCNetworkConnectionPPPStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCNetworkConnectionPPPStatus"
      }
    ],
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCNetworkConnectionPPPStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "SCNetworkConnectionPPPStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCNetworkConnectionPPPStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This status is returned as part of the extended information for a PPP service. Note that additional status might be returned in the future. Therefore, your application should be prepared to receive an unknown value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionCopyUserPreferences(_:_:_:)": {
      "abstract": [
        {
          "text": "Provides the default service ID and a dictionary of user options for the specified connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkConnectionCopyUserPreferences"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionCopyUserPreferences(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkConnectionCopyUserPreferences"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionCopyUserPreferences(_:_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectioncopyuserpreferences(_:_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus": {
      "abstract": [
        {
          "text": "The PPP-specific status of the network connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkConnectionPPPStatus"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkConnectionPPPStatus"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionPPPStatus",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionpppstatus"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/authenticating": {
      "abstract": [
        {
          "text": "PPP is authenticating to the server (PAP, CHAP, MS-CHAP, or EAP protocols).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticating"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/authenticating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionPPPAuthenticating"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionPPPStatus.authenticating",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionpppstatus/authenticating"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/connected": {
      "abstract": [
        {
          "text": "PPP is now fully connected for at least one networking layer. Additional networking protocol might still be negotiating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connected"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/connected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionPPPConnected"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionPPPStatus.connected",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionpppstatus/connected"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/connectingLink": {
      "abstract": [
        {
          "text": "PPP is connecting the lower connection layer (for example, the modem is dialing out).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectingLink"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/connectingLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionPPPConnectingLink"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionPPPStatus.connectingLink",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionpppstatus/connectinglink"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/dialOnTraffic": {
      "abstract": [
        {
          "text": "PPP is waiting for networking traffic to automatically establish the connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dialOnTraffic"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/dialOnTraffic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionPPPDialOnTraffic"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionPPPStatus.dialOnTraffic",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionpppstatus/dialontraffic"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/disconnected": {
      "abstract": [
        {
          "text": "PPP is disconnected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disconnected"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/disconnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionPPPDisconnected"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionPPPStatus.disconnected",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionpppstatus/disconnected"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/disconnectingLink": {
      "abstract": [
        {
          "text": "PPP is disconnecting the lower level (for example, the modem is hanging up).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disconnectingLink"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/disconnectingLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionPPPDisconnectingLink"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionPPPStatus.disconnectingLink",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionpppstatus/disconnectinglink"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/holdingLinkOff": {
      "abstract": [
        {
          "text": "PPP is disconnected and maintaining the link temporarily off.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "holdingLinkOff"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/holdingLinkOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionPPPHoldingLinkOff"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionPPPStatus.holdingLinkOff",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionpppstatus/holdinglinkoff"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionpppstatus/init(rawvalue:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/initializing": {
      "abstract": [
        {
          "text": "PPP is initializing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initializing"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/initializing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionPPPInitializing"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionPPPStatus.initializing",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionpppstatus/initializing"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/negotiatingLink": {
      "abstract": [
        {
          "text": "The PPP lower layer is connected and PPP is negotiating the link layer (LCP protocol).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "negotiatingLink"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/negotiatingLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionPPPNegotiatingLink"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionPPPStatus.negotiatingLink",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionpppstatus/negotiatinglink"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/negotiatingNetwork": {
      "abstract": [
        {
          "text": "PPP is now authenticated and negotiating the networking layer (IPCP or IPv6CP protocols).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "negotiatingNetwork"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/negotiatingNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionPPPNegotiatingNetwork"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionPPPStatus.negotiatingNetwork",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionpppstatus/negotiatingnetwork"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/suspended": {
      "abstract": [
        {
          "text": "PPP is suspended as a result of the suspend command (for example, when a V.92 Modem is On Hold).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suspended"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/suspended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionPPPSuspended"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionPPPStatus.suspended",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionpppstatus/suspended"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/terminating": {
      "abstract": [
        {
          "text": "PPP networking and link protocols are terminating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "terminating"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/terminating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionPPPTerminating"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionPPPStatus.terminating",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionpppstatus/terminating"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/waitingForCallBack": {
      "abstract": [
        {
          "text": "PPP is waiting for the server to call back.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waitingForCallBack"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/waitingForCallBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionPPPWaitingForCallBack"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionPPPStatus.waitingForCallBack",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionpppstatus/waitingforcallback"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/waitingForRedial": {
      "abstract": [
        {
          "text": "PPP has found a busy server and is waiting for redial.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waitingForRedial"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/waitingForRedial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionPPPWaitingForRedial"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionPPPStatus.waitingForRedial",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionpppstatus/waitingforredial"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionStatus": {
      "abstract": [
        {
          "text": "The current status of the network connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkConnectionStatus"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkConnectionStatus"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionStatus",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionstatus"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/selection-options-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionCopyUserPreferences(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " selection options dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/selection-options-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Selection Options Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/selection-options-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/statistics-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys associated with values in the statistics dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/statistics-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Statistics Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/statistics-dictionary-keys"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionStatus",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/statistics-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/selection-options-dictionary-keys"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/disconnected",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/initializing",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/connectingLink",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/dialOnTraffic",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/negotiatingLink",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/authenticating",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/waitingForCallBack",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/negotiatingNetwork",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/connected",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/terminating",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/disconnectingLink",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/holdingLinkOff",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/suspended",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/waitingForRedial"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNetworkConnectionPPPStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkConnectionPPPStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkConnectionPPPStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/disconnected",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/initializing",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/connectingLink",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/dialOnTraffic",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/negotiatingLink",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/authenticating",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/waitingForCallBack",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/negotiatingNetwork",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/connected",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/terminating",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/disconnectingLink",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/holdingLinkOff",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/suspended",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus/waitingForRedial"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionStatus",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/statistics-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/selection-options-dictionary-keys"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCNetworkConnectionPPPStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@int32_t",
                    "text": "int32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionCopyUserPreferences(_:_:_:)/title",
          "value": "SCNetworkConnectionCopyUserPreferences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionCopyUserPreferences(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkConnectionCopyUserPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1connectingLink/title",
          "value": "kSCNetworkConnectionPPPConnectingLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1connectingLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkConnectionPPPConnectingLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1holdingLinkOff/title",
          "value": "kSCNetworkConnectionPPPHoldingLinkOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1holdingLinkOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkConnectionPPPHoldingLinkOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1authenticating/title",
          "value": "kSCNetworkConnectionPPPAuthenticating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1authenticating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkConnectionPPPAuthenticating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1terminating/title",
          "value": "kSCNetworkConnectionPPPTerminating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1terminating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkConnectionPPPTerminating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1waitingForRedial/title",
          "value": "kSCNetworkConnectionPPPWaitingForRedial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1waitingForRedial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkConnectionPPPWaitingForRedial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1suspended/title",
          "value": "kSCNetworkConnectionPPPSuspended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1suspended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkConnectionPPPSuspended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionStatus/title",
          "value": "SCNetworkConnectionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkConnectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkConnectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1initializing/title",
          "value": "kSCNetworkConnectionPPPInitializing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1initializing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkConnectionPPPInitializing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1disconnected/title",
          "value": "kSCNetworkConnectionPPPDisconnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1disconnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkConnectionPPPDisconnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1dialOnTraffic/title",
          "value": "kSCNetworkConnectionPPPDialOnTraffic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1dialOnTraffic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkConnectionPPPDialOnTraffic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1negotiatingNetwork/title",
          "value": "kSCNetworkConnectionPPPNegotiatingNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1negotiatingNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkConnectionPPPNegotiatingNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus/title",
          "value": "SCNetworkConnectionPPPStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkConnectionPPPStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkConnectionPPPStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1connected/title",
          "value": "kSCNetworkConnectionPPPConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1connected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkConnectionPPPConnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1negotiatingLink/title",
          "value": "kSCNetworkConnectionPPPNegotiatingLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1negotiatingLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkConnectionPPPNegotiatingLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1waitingForCallBack/title",
          "value": "kSCNetworkConnectionPPPWaitingForCallBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1waitingForCallBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkConnectionPPPWaitingForCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1disconnectingLink/title",
          "value": "kSCNetworkConnectionPPPDisconnectingLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus~1disconnectingLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkConnectionPPPDisconnectingLink"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/scnetworkconnectionpppstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/scnetworkconnectionpppstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
