{
  "abstract": [
    {
      "text": "Returns a list of available media options for the specified interface configuration options and subtype.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyMediaSubTypeOptions(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SCNetworkInterfaceCopyMediaSubTypeOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCNetworkInterfaceCopyMediaSubTypeOptions"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFArrayRef",
        "text": "CFArray"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFArrayRef",
        "text": "CFArray"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCNetworkInterfaceCopyMediaSubTypeOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SCNetworkInterfaceCopyMediaSubTypeOptions(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceCopyMediaSubTypeOptions"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "available"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArray"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "subType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArray"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The available options as returned by the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyMediaOptions(_:_:_:_:_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "available"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The subtype.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "subType"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An array of available media options, or ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " if no options are available. Each of the available options is returned as an array of strings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyAll()": {
      "abstract": [
        {
          "text": "Returns all network-capable interfaces on the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceCopyAll"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyAll()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceCopyAll"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkInterfaceCopyAll()",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkinterfacecopyall()"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyMTU(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the current MTU setting and the range of allowable values for the specified network interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceCopyMTU"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyMTU(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceCopyMTU"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkInterfaceCopyMTU(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkinterfacecopymtu(_:_:_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyMediaOptions(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns information media options for the specified network interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceCopyMediaOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyMediaOptions(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceCopyMediaOptions"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkInterfaceCopyMediaOptions(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkinterfacecopymediaoptions(_:_:_:_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyMediaSubTypeOptions(_:_:)": {
      "abstract": [
        {
          "text": "Returns a list of available media options for the specified interface configuration options and subtype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceCopyMediaSubTypeOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyMediaSubTypeOptions(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceCopyMediaSubTypeOptions"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkInterfaceCopyMediaSubTypeOptions(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkinterfacecopymediasubtypeoptions(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyMediaSubTypes(_:)": {
      "abstract": [
        {
          "text": "Returns a list of available media subtypes for the specified interface configuration options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceCopyMediaSubTypes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyMediaSubTypes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceCopyMediaSubTypes"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkInterfaceCopyMediaSubTypes(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkinterfacecopymediasubtypes(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCreateWithInterface(_:_:)": {
      "abstract": [
        {
          "text": "Creates a new network interface layered on top of the specified interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceCreateWithInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCreateWithInterface(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceCreateWithInterface"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkInterfaceCreateWithInterface(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkinterfacecreatewithinterface(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceForceConfigurationRefresh(_:)": {
      "abstract": [
        {
          "text": "Sends a notification to interested network configuration agents to immediately retry their configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceForceConfigurationRefresh"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceForceConfigurationRefresh(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceForceConfigurationRefresh"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkInterfaceForceConfigurationRefresh(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkinterfaceforceconfigurationrefresh(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetBSDName(_:)": {
      "abstract": [
        {
          "text": "Returns the BSD interface or device name for the specified interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetBSDName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetBSDName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetBSDName"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkInterfaceGetBSDName(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkinterfacegetbsdname(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetConfiguration(_:)": {
      "abstract": [
        {
          "text": "Returns the configuration settings associated with the specified interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetConfiguration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetConfiguration(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetConfiguration"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkInterfaceGetConfiguration(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkinterfacegetconfiguration(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetExtendedConfiguration(_:_:)": {
      "abstract": [
        {
          "text": "Returns the extended configuration settings associated with the specified interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetExtendedConfiguration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetExtendedConfiguration(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetExtendedConfiguration"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkInterfaceGetExtendedConfiguration(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkinterfacegetextendedconfiguration(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetHardwareAddressString(_:)": {
      "abstract": [
        {
          "text": "Returns a displayable link layer address for the specified interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetHardwareAddressString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetHardwareAddressString(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetHardwareAddressString"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkInterfaceGetHardwareAddressString(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkinterfacegethardwareaddressstring(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetInterface(_:)": {
      "abstract": [
        {
          "text": "Returns the underlying interface, for layered network interfaces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetInterface(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetInterface"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkInterfaceGetInterface(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkinterfacegetinterface(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetInterfaceType(_:)": {
      "abstract": [
        {
          "text": "Returns the network interface type of the specified interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetInterfaceType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetInterfaceType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetInterfaceType"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkInterfaceGetInterfaceType(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkinterfacegetinterfacetype(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetLocalizedDisplayName(_:)": {
      "abstract": [
        {
          "text": "Returns the localized display name, such as “Ethernet” or “FireWire”, for the specified interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetLocalizedDisplayName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetLocalizedDisplayName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetLocalizedDisplayName"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkInterfaceGetLocalizedDisplayName(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkinterfacegetlocalizeddisplayname(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetSupportedInterfaceTypes(_:)": {
      "abstract": [
        {
          "text": "Identifies all of the network interface types, such as PPP, that can be layered on top of the specified interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetSupportedInterfaceTypes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetSupportedInterfaceTypes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetSupportedInterfaceTypes"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkInterfaceGetSupportedInterfaceTypes(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkinterfacegetsupportedinterfacetypes(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetSupportedProtocolTypes(_:)": {
      "abstract": [
        {
          "text": "Identifies all of the network protocol types, such as IPv4 and IPv6, that can be layered on top of the specified interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetSupportedProtocolTypes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetSupportedProtocolTypes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkInterfaceGetSupportedProtocolTypes"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkInterfaceGetSupportedProtocolTypes(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkinterfacegetsupportedprotocoltypes(_:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFArrayRef": {
      "abstract": [
        {
          "text": "A reference to an immutable array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFArray",
      "type": "topic",
      "url": "/documentation/corefoundation/cfarray"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Network-Interfaces",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyAll()",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyMTU(_:_:_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyMediaOptions(_:_:_:_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyMediaSubTypes(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCreateWithInterface(_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceForceConfigurationRefresh(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetBSDName(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetConfiguration(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetExtendedConfiguration(_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetHardwareAddressString(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetInterface(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetInterfaceType(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetLocalizedDisplayName(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetSupportedInterfaceTypes(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetSupportedProtocolTypes(_:)"
      ],
      "title": "Configuring Network Interfaces"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNetworkInterfaceCopyMediaSubTypeOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceCopyMediaSubTypeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Network-Interfaces",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyAll()",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyMTU(_:_:_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyMediaOptions(_:_:_:_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyMediaSubTypes(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCreateWithInterface(_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceForceConfigurationRefresh(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetBSDName(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetConfiguration(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetExtendedConfiguration(_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetHardwareAddressString(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetInterface(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetInterfaceType(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetLocalizedDisplayName(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetSupportedInterfaceTypes(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceGetSupportedProtocolTypes(_:)"
              ],
              "title": "Configuring Network Interfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFArrayRef",
                    "text": "CFArrayRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCNetworkInterfaceCopyMediaSubTypeOptions"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFArrayRef",
                    "text": "CFArrayRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "available"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "subType"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The available options as returned by the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterfaceCopyMediaOptions(_:_:_:_:_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " function.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "available"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The subtype.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "subType"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An array of available media options, or ",
                    "type": "text"
                  },
                  {
                    "code": "NULL",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if no options are available. Each of the available options is returned as an array of strings.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetBSDName(_:)/title",
          "value": "SCNetworkInterfaceGetBSDName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetBSDName(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceGetBSDName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceCopyMediaOptions(_:_:_:_:_:)/title",
          "value": "SCNetworkInterfaceCopyMediaOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceCopyMediaOptions(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceCopyMediaOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceCreateWithInterface(_:_:)/title",
          "value": "SCNetworkInterfaceCreateWithInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceCreateWithInterface(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceCreateWithInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetSupportedInterfaceTypes(_:)/title",
          "value": "SCNetworkInterfaceGetSupportedInterfaceTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetSupportedInterfaceTypes(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceGetSupportedInterfaceTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceCopyMediaSubTypes(_:)/title",
          "value": "SCNetworkInterfaceCopyMediaSubTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceCopyMediaSubTypes(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceCopyMediaSubTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetExtendedConfiguration(_:_:)/title",
          "value": "SCNetworkInterfaceGetExtendedConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetExtendedConfiguration(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceGetExtendedConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceCopyMTU(_:_:_:_:)/title",
          "value": "SCNetworkInterfaceCopyMTU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceCopyMTU(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceCopyMTU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetInterfaceType(_:)/title",
          "value": "SCNetworkInterfaceGetInterfaceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetInterfaceType(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceGetInterfaceType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceForceConfigurationRefresh(_:)/title",
          "value": "SCNetworkInterfaceForceConfigurationRefresh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceForceConfigurationRefresh(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceForceConfigurationRefresh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetSupportedProtocolTypes(_:)/title",
          "value": "SCNetworkInterfaceGetSupportedProtocolTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetSupportedProtocolTypes(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceGetSupportedProtocolTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFArrayRef/title",
          "value": "CFArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceCopyAll()/title",
          "value": "SCNetworkInterfaceCopyAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceCopyAll()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceCopyAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceCopyMediaSubTypeOptions(_:_:)/title",
          "value": "SCNetworkInterfaceCopyMediaSubTypeOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceCopyMediaSubTypeOptions(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceCopyMediaSubTypeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetLocalizedDisplayName(_:)/title",
          "value": "SCNetworkInterfaceGetLocalizedDisplayName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetLocalizedDisplayName(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceGetLocalizedDisplayName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetInterface(_:)/title",
          "value": "SCNetworkInterfaceGetInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetInterface(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceGetInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetConfiguration(_:)/title",
          "value": "SCNetworkInterfaceGetConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetConfiguration(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceGetConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetHardwareAddressString(_:)/title",
          "value": "SCNetworkInterfaceGetHardwareAddressString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterfaceGetHardwareAddressString(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceGetHardwareAddressString"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/scnetworkinterfacecopymediasubtypeoptions(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/scnetworkinterfacecopymediasubtypeoptions(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
