{
  "abstract": [
    {
      "text": "Returns all available sets for the specified preferences session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCopyAll(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SCNetworkSetCopyAll",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCNetworkSetCopyAll"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SCPreferencesRef",
        "text": "SCPreferences"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFArrayRef",
        "text": "CFArray"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCNetworkSetCopyAll"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SCNetworkSetCopyAll(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCNetworkSetCopyAll"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "prefs"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SCPreferencesRef",
              "text": "SCPreferences"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArray"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The preferences session.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "prefs"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The list of network sets associated with the preferences. You must release the returned value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetAddService(_:_:)": {
      "abstract": [
        {
          "text": "Adds the specified network service to the specified set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkSetAddService"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkSetRef",
          "text": "SCNetworkSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkServiceRef",
          "text": "SCNetworkService"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetAddService(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkSetAddService"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkSetAddService(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworksetaddservice(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetContainsInterface(_:_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the specified interface is represented by at least one network service in the specified set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkSetContainsInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkSetRef",
          "text": "SCNetworkSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetContainsInterface(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkSetContainsInterface"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkSetContainsInterface(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworksetcontainsinterface(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCopy(_:_:)": {
      "abstract": [
        {
          "text": "Returns the set with the specified identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkSetCopy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkSetRef",
          "text": "SCNetworkSet"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCopy(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkSetCopy"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkSetCopy(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworksetcopy(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCopyAll(_:)": {
      "abstract": [
        {
          "text": "Returns all available sets for the specified preferences session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkSetCopyAll"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCopyAll(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkSetCopyAll"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkSetCopyAll(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworksetcopyall(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCopyCurrent(_:)": {
      "abstract": [
        {
          "text": "Returns the current set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkSetCopyCurrent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkSetRef",
          "text": "SCNetworkSet"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCopyCurrent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkSetCopyCurrent"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkSetCopyCurrent(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworksetcopycurrent(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCopyServices(_:)": {
      "abstract": [
        {
          "text": "Returns all network services associated with the specified set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkSetCopyServices"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkSetRef",
          "text": "SCNetworkSet"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCopyServices(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkSetCopyServices"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkSetCopyServices(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworksetcopyservices(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCreate(_:)": {
      "abstract": [
        {
          "text": "Creates a new set in the configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkSetCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkSetRef",
          "text": "SCNetworkSet"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCreate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkSetCreate"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkSetCreate(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworksetcreate(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetGetName(_:)": {
      "abstract": [
        {
          "text": "Returns the user-specified name associated with the specified set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkSetGetName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkSetRef",
          "text": "SCNetworkSet"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetGetName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkSetGetName"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkSetGetName(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworksetgetname(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetGetServiceOrder(_:)": {
      "abstract": [
        {
          "text": "Returns the user-specified ordering of network services within the specified set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkSetGetServiceOrder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkSetRef",
          "text": "SCNetworkSet"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetGetServiceOrder(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkSetGetServiceOrder"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkSetGetServiceOrder(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworksetgetserviceorder(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetGetSetID(_:)": {
      "abstract": [
        {
          "text": "Returns the identifier for the specified set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkSetGetSetID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkSetRef",
          "text": "SCNetworkSet"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetGetSetID(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkSetGetSetID"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkSetGetSetID(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworksetgetsetid(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the type identifier of all ",
          "type": "text"
        },
        {
          "code": "SCNetworkSet",
          "type": "codeVoice"
        },
        {
          "text": " instances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkSetGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkSetGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkSetGetTypeID()",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworksetgettypeid()"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetRemove(_:)": {
      "abstract": [
        {
          "text": "Removes the specified set from the configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkSetRemove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkSetRef",
          "text": "SCNetworkSet"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetRemove(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkSetRemove"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkSetRemove(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworksetremove(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetRemoveService(_:_:)": {
      "abstract": [
        {
          "text": "Removes the specified network service from the specified set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkSetRemoveService"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkSetRef",
          "text": "SCNetworkSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkServiceRef",
          "text": "SCNetworkService"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetRemoveService(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkSetRemoveService"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkSetRemoveService(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworksetremoveservice(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetSetCurrent(_:)": {
      "abstract": [
        {
          "text": "Specifies the set that should be the current set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkSetSetCurrent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkSetRef",
          "text": "SCNetworkSet"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetSetCurrent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkSetSetCurrent"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkSetSetCurrent(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworksetsetcurrent(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetSetName(_:_:)": {
      "abstract": [
        {
          "text": "Stores the user-specified name for the specified set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkSetSetName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkSetRef",
          "text": "SCNetworkSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetSetName(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkSetSetName"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkSetSetName(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworksetsetname(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetSetServiceOrder(_:_:)": {
      "abstract": [
        {
          "text": "Stores the user-specified ordering of network services for the specified set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkSetSetServiceOrder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkSetRef",
          "text": "SCNetworkSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetSetServiceOrder(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkSetSetServiceOrder"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkSetSetServiceOrder(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworksetsetserviceorder(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences": {
      "abstract": [
        {
          "text": "The handle to an open preferences session for accessing system configuration preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferences"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferences"
        }
      ],
      "role": "symbol",
      "title": "SCPreferences",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferences"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFArrayRef": {
      "abstract": [
        {
          "text": "A reference to an immutable array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFArray",
      "type": "topic",
      "url": "/documentation/corefoundation/cfarray"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Network-Sets",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetAddService(_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetContainsInterface(_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCopy(_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCopyCurrent(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCopyServices(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCreate(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetGetName(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetGetServiceOrder(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetGetSetID(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetGetTypeID()",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetRemove(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetRemoveService(_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetSetCurrent(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetSetName(_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetSetServiceOrder(_:_:)"
      ],
      "title": "Configuring Network Sets"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNetworkSetCopyAll"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkSetCopyAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Network-Sets",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetAddService(_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetContainsInterface(_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCopy(_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCopyCurrent(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCopyServices(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetCreate(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetGetName(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetGetServiceOrder(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetGetSetID(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetGetTypeID()",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetRemove(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetRemoveService(_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetSetCurrent(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetSetName(_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkSetSetServiceOrder(_:_:)"
              ],
              "title": "Configuring Network Sets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFArrayRef",
                    "text": "CFArrayRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCNetworkSetCopyAll"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SCPreferencesRef",
                    "text": "SCPreferencesRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "prefs"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The preferences session.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "prefs"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The list of network sets associated with the preferences. You must release the returned value.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetAddService(_:_:)/title",
          "value": "SCNetworkSetAddService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetAddService(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkSetAddService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetGetTypeID()/title",
          "value": "SCNetworkSetGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkSetGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetCopyServices(_:)/title",
          "value": "SCNetworkSetCopyServices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetCopyServices(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkSetCopyServices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetSetCurrent(_:)/title",
          "value": "SCNetworkSetSetCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetSetCurrent(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkSetSetCurrent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetCreate(_:)/title",
          "value": "SCNetworkSetCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetCreate(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkSetCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetSetServiceOrder(_:_:)/title",
          "value": "SCNetworkSetSetServiceOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetSetServiceOrder(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkSetSetServiceOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetSetName(_:_:)/title",
          "value": "SCNetworkSetSetName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetSetName(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkSetSetName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetGetSetID(_:)/title",
          "value": "SCNetworkSetGetSetID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetGetSetID(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkSetGetSetID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferences/title",
          "value": "SCPreferencesRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferences/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetCopy(_:_:)/title",
          "value": "SCNetworkSetCopy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetCopy(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkSetCopy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFArrayRef/title",
          "value": "CFArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetCopyAll(_:)/title",
          "value": "SCNetworkSetCopyAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetCopyAll(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkSetCopyAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetRemove(_:)/title",
          "value": "SCNetworkSetRemove"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetRemove(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkSetRemove"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetContainsInterface(_:_:)/title",
          "value": "SCNetworkSetContainsInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetContainsInterface(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkSetContainsInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetCopyCurrent(_:)/title",
          "value": "SCNetworkSetCopyCurrent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetCopyCurrent(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkSetCopyCurrent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetGetName(_:)/title",
          "value": "SCNetworkSetGetName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetGetName(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkSetGetName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetRemoveService(_:_:)/title",
          "value": "SCNetworkSetRemoveService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetRemoveService(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkSetRemoveService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetGetServiceOrder(_:)/title",
          "value": "SCNetworkSetGetServiceOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkSetGetServiceOrder(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkSetGetServiceOrder"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/scnetworksetcopyall(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/scnetworksetcopyall(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
