{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferences-ft8"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "SCPreferences"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "SCPreferences",
              "type": "codeVoice"
            },
            {
              "text": " programming interface allows an application to load and store XML configuration data in a controlled manner and provide the necessary notifications to other applications that need to be aware of configuration changes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To access configuration preferences, you must first establish a preferences session using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCreate(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function. To identify a specific set of preferences to access, you pass a value in the prefsID parameter. A ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " value indicates that the default system preferences are to be accessed. A string that starts with a leading “/” character specifies the absolute path to the file containing the preferences to be accessed. A string that does not start with a leading “/” character specifies a file relative to the default system preferences directory.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you are finished with the preferences session, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to release it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease": {
      "abstract": [
        {
          "text": "Releases a Core Foundation object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/1521153-cfrelease",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRelease",
      "type": "topic",
      "url": "/documentation/corefoundation/1521153-cfrelease"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences": {
      "abstract": [
        {
          "text": "The handle to an open preferences session for accessing system configuration preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferences"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferences"
        }
      ],
      "role": "symbol",
      "title": "SCPreferences",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferences"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesAddValue(_:_:_:)": {
      "abstract": [
        {
          "text": "Associates the specified value with the specified preference key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesAddValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFPropertyListRef",
          "text": "CFPropertyList"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesAddValue(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesAddValue"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesAddValue(_:_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencesaddvalue(_:_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesApplyChanges(_:)": {
      "abstract": [
        {
          "text": "Requests that the currently stored configuration preferences be applied to the active configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesApplyChanges"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesApplyChanges(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesApplyChanges"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesApplyChanges(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencesapplychanges(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCallBack": {
      "abstract": [
        {
          "text": "Type of the callback function used when the preferences have been updated or applied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesCallBack"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCallBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesCallBack"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesCallBack",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencescallback"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCommitChanges(_:)": {
      "abstract": [
        {
          "text": "Commits changes made to the configuration preferences to persistent storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesCommitChanges"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCommitChanges(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesCommitChanges"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesCommitChanges(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencescommitchanges(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext": {
      "abstract": [
        {
          "text": "A structure containing user-specified data and callbacks for accessing system configuration preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesContext"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesContext"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesContext",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencescontext"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCopyKeyList(_:)": {
      "abstract": [
        {
          "text": "Returns the currently defined preference keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesCopyKeyList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCopyKeyList(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesCopyKeyList"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesCopyKeyList(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencescopykeylist(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCreate(_:_:_:)": {
      "abstract": [
        {
          "text": "Initiates access to the per-system set of configuration preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCreate(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesCreate"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesCreate(_:_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencescreate(_:_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCreateWithAuthorization(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Initiates access to the per-system set of configuration preferences with the specified authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesCreateWithAuthorization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AuthorizationRef",
          "text": "AuthorizationRef"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCreateWithAuthorization(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesCreateWithAuthorization"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesCreateWithAuthorization(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencescreatewithauthorization(_:_:_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesGetSignature(_:)": {
      "abstract": [
        {
          "text": "Returns a value that can be used to determine if the saved configuration preferences have changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesGetSignature"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesGetSignature(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesGetSignature"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesGetSignature(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencesgetsignature(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the type identifier of all ",
          "type": "text"
        },
        {
          "code": "SCPreferences",
          "type": "codeVoice"
        },
        {
          "text": " instances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesGetTypeID()",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencesgettypeid()"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesGetValue(_:_:)": {
      "abstract": [
        {
          "text": "Retrieves the value associated with the specified preference key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesGetValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFPropertyListRef",
          "text": "CFPropertyList"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesGetValue(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesGetValue"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesGetValue(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencesgetvalue(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesLock(_:_:)": {
      "abstract": [
        {
          "text": "Locks access to the configuration preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesLock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesLock(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesLock"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesLock(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferenceslock(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification": {
      "abstract": [
        {
          "text": "The type of notification (used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCallBack",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " callback).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesNotification"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesNotification"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesNotification",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencesnotification"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesRemoveValue(_:_:)": {
      "abstract": [
        {
          "text": "Removes the data associated with the specified preference key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesRemoveValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesRemoveValue(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesRemoveValue"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesRemoveValue(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencesremovevalue(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesScheduleWithRunLoop(_:_:_:)": {
      "abstract": [
        {
          "text": "Schedules commit and apply notifications for the specified preferences session using the specified run loop and mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesScheduleWithRunLoop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopRef",
          "text": "CFRunLoop"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesScheduleWithRunLoop(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesScheduleWithRunLoop"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesScheduleWithRunLoop(_:_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencesschedulewithrunloop(_:_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSetCallback(_:_:_:)": {
      "abstract": [
        {
          "text": "Assigns the specified callback to the specified preferences session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesSetCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesCallBack",
          "text": "SCPreferencesCallBack"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SCPreferencesContext",
          "text": "SCPreferencesContext"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSetCallback(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesSetCallback"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesSetCallback(_:_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencessetcallback(_:_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSetDispatchQueue(_:_:)": {
      "abstract": [
        {
          "text": "Schedules commit and apply notifications for the specified preferences session using the specified dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesSetDispatchQueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSetDispatchQueue(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesSetDispatchQueue"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesSetDispatchQueue(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencessetdispatchqueue(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSetValue(_:_:_:)": {
      "abstract": [
        {
          "text": "Updates the data associated with the specified preference key with the specified value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesSetValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFPropertyListRef",
          "text": "CFPropertyList"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSetValue(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesSetValue"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesSetValue(_:_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencessetvalue(_:_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSynchronize(_:)": {
      "abstract": [
        {
          "text": "Synchronizes accessed preferences with committed changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesSynchronize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSynchronize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesSynchronize"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesSynchronize(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencessynchronize(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesUnlock(_:)": {
      "abstract": [
        {
          "text": "Releases exclusive access to the configuration preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesUnlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesUnlock(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesUnlock"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesUnlock(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencesunlock(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesUnscheduleFromRunLoop(_:_:_:)": {
      "abstract": [
        {
          "text": "Unschedules commit and apply notifications for the specified preferences session from the specified run loop and mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesUnscheduleFromRunLoop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopRef",
          "text": "CFRunLoop"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesUnscheduleFromRunLoop(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesUnscheduleFromRunLoop"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesUnscheduleFromRunLoop(_:_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencesunschedulefromrunloop(_:_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dhcpclientpreferences": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dhcpclientpreferences",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DHCPClientPreferences",
      "type": "topic",
      "url": "/documentation/systemconfiguration/dhcpclientpreferences"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstore-gb2": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstore-gb2",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCDynamicStore",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scdynamicstore-gb2"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopydhcpinfo-apicollection": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopydhcpinfo-apicollection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCDynamicStoreCopyDHCPInfo",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scdynamicstorecopydhcpinfo-apicollection"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopyspecific": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopyspecific",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCDynamicStoreCopySpecific",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scdynamicstorecopyspecific"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorekey": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorekey",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCDynamicStoreKey",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scdynamicstorekey"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetwork": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetwork",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCNetwork",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetwork"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCNetworkConfiguration",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconnection-g7e": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconnection-g7e",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCNetworkConnection",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnection-g7e"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkreachability-g7d": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkreachability-g7d",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCNetworkReachability",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkreachability-g7d"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencespath": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencespath",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCPreferencesPath",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencespath"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencessetspecific": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencessetspecific",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCPreferencesSetSpecific",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencessetspecific"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCSchemaDefinitions",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scschemadefinitions"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/system-configuration": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/system-configuration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration/system-configuration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SystemConfiguration Constants",
      "type": "topic",
      "url": "/documentation/systemconfiguration/systemconfiguration-constants"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SystemConfiguration Data Types",
      "type": "topic",
      "url": "/documentation/systemconfiguration/systemconfiguration-data-types"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SystemConfiguration Enumerations",
      "type": "topic",
      "url": "/documentation/systemconfiguration/systemconfiguration-enumerations"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SystemConfiguration Functions",
      "type": "topic",
      "url": "/documentation/systemconfiguration/systemconfiguration-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstore-gb2",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopyspecific",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorekey",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetwork",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconnection-g7e",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkreachability-g7d",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencespath",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencessetspecific",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/system-configuration",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-enumerations",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-constants",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-functions",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Preferences-Session",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCreate(_:_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCreateWithAuthorization(_:_:_:_:)"
      ],
      "title": "Creating a Preferences Session"
    },
    {
      "anchor": "Getting-Information-About-a-Preferences-Session",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesGetTypeID()",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCopyKeyList(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesGetSignature(_:)"
      ],
      "title": "Getting Information About a Preferences Session"
    },
    {
      "anchor": "Adding-Getting-and-Removing-Values",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesAddValue(_:_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesGetValue(_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSetValue(_:_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesRemoveValue(_:_:)"
      ],
      "title": "Adding, Getting, and Removing Values"
    },
    {
      "anchor": "Applying-and-Committing-Changes",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesApplyChanges(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCommitChanges(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSynchronize(_:)"
      ],
      "title": "Applying and Committing Changes"
    },
    {
      "anchor": "Managing-Notifications-and-Callbacks",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSetCallback(_:_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesScheduleWithRunLoop(_:_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesUnscheduleFromRunLoop(_:_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSetDispatchQueue(_:_:)"
      ],
      "title": "Managing Notifications and Callbacks"
    },
    {
      "anchor": "Managing-Access-to-a-Preferences-Session",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesLock(_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesUnlock(_:)"
      ],
      "title": "Managing Access to a Preferences Session"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCallBack"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Preferences-Session",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCreate(_:_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCreateWithAuthorization(_:_:_:_:)"
              ],
              "title": "Creating a Preferences Session"
            },
            {
              "anchor": "Getting-Information-About-a-Preferences-Session",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesGetTypeID()",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCopyKeyList(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesGetSignature(_:)"
              ],
              "title": "Getting Information About a Preferences Session"
            },
            {
              "anchor": "Adding-Getting-and-Removing-Values",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesAddValue(_:_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesGetValue(_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSetValue(_:_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesRemoveValue(_:_:)"
              ],
              "title": "Adding, Getting, and Removing Values"
            },
            {
              "anchor": "Applying-and-Committing-Changes",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesApplyChanges(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCommitChanges(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSynchronize(_:)"
              ],
              "title": "Applying and Committing Changes"
            },
            {
              "anchor": "Managing-Notifications-and-Callbacks",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSetCallback(_:_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesScheduleWithRunLoop(_:_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesUnscheduleFromRunLoop(_:_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSetDispatchQueue(_:_:)"
              ],
              "title": "Managing Notifications and Callbacks"
            },
            {
              "anchor": "Managing-Access-to-a-Preferences-Session",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesLock(_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesUnlock(_:)"
              ],
              "title": "Managing Access to a Preferences Session"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCallBack"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dhcpclientpreferences",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstore-gb2",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopydhcpinfo-apicollection",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopyspecific",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorekey",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetwork",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconnection-g7e",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkreachability-g7d",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencespath",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencessetspecific",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/system-configuration",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-enumerations",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesGetValue(_:_:)/title",
          "value": "SCPreferencesGetValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesGetValue(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesGetValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCallBack/title",
          "value": "SCPreferencesCallBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCallBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCallBack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesLock(_:_:)/title",
          "value": "SCPreferencesLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesLock(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesSynchronize(_:)/title",
          "value": "SCPreferencesSynchronize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesSynchronize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesSynchronize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCommitChanges(_:)/title",
          "value": "SCPreferencesCommitChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCommitChanges(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesCommitChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesSetCallback(_:_:_:)/title",
          "value": "SCPreferencesSetCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesSetCallback(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesSetCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesGetSignature(_:)/title",
          "value": "SCPreferencesGetSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesGetSignature(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesGetSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCopyKeyList(_:)/title",
          "value": "SCPreferencesCopyKeyList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCopyKeyList(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesCopyKeyList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCreateWithAuthorization(_:_:_:_:)/title",
          "value": "SCPreferencesCreateWithAuthorization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCreateWithAuthorization(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesCreateWithAuthorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesUnscheduleFromRunLoop(_:_:_:)/title",
          "value": "SCPreferencesUnscheduleFromRunLoop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesUnscheduleFromRunLoop(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesUnscheduleFromRunLoop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesSetDispatchQueue(_:_:)/title",
          "value": "SCPreferencesSetDispatchQueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesSetDispatchQueue(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesSetDispatchQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesContext/title",
          "value": "SCPreferencesContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesRemoveValue(_:_:)/title",
          "value": "SCPreferencesRemoveValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesRemoveValue(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesRemoveValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesNotification/title",
          "value": "SCPreferencesNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesNotification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesSetValue(_:_:_:)/title",
          "value": "SCPreferencesSetValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesSetValue(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesSetValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesAddValue(_:_:_:)/title",
          "value": "SCPreferencesAddValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesAddValue(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesAddValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesGetTypeID()/title",
          "value": "SCPreferencesGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesUnlock(_:)/title",
          "value": "SCPreferencesUnlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesUnlock(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesUnlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesScheduleWithRunLoop(_:_:_:)/title",
          "value": "SCPreferencesScheduleWithRunLoop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesScheduleWithRunLoop(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesScheduleWithRunLoop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCreate(_:_:_:)/title",
          "value": "SCPreferencesCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCreate(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferences/title",
          "value": "SCPreferencesRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferences/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesApplyChanges(_:)/title",
          "value": "SCPreferencesApplyChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesApplyChanges(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesApplyChanges"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/scpreferences-ft8"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/scpreferences-ft8"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
