{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSynchronize(_:)"},"variants":[{"paths":["/documentation/systemconfiguration/scpreferencessynchronize(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/systemconfiguration/scpreferencessynchronize(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.systemconfiguration/documentation/SystemConfiguration"]]},"seeAlsoSections":[{"generated":true,"anchor":"Applying-and-Committing-Changes","title":"Applying and Committing Changes","identifiers":["doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesApplyChanges(_:)","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCommitChanges(_:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCPreferencesSynchronize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"prefs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SCPreferences","kind":"typeIdentifier","identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences","preciseIdentifier":"c:@T@SCPreferencesRef"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The preferences session."}]}],"name":"prefs"}],"kind":"parameters"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Any references to preference values returned by calls to "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesGetValue(_:_:)"},{"type":"text","text":" are no longer valid unless they were explicitly retained or copied. Any preference values that were updated (added, set, or removed), but not committed, are discarded."}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"role":"symbol","roleHeading":"Function","modules":[{"name":"System Configuration"}],"symbolKind":"func","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCPreferencesSynchronize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SCPreferences","kind":"typeIdentifier","preciseIdentifier":"c:@T@SCPreferencesRef"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"SCPreferencesSynchronize","kind":"identifier"}],"title":"SCPreferencesSynchronize(_:)","platforms":[{"name":"macOS","deprecated":false,"introducedAt":"10.4","beta":false,"unavailable":false}],"externalID":"c:@F@SCPreferencesSynchronize"},"abstract":[{"text":"Synchronizes accessed preferences with committed changes.","type":"text"}],"references":{"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCommitChanges(_:)":{"navigatorTitle":[{"kind":"identifier","text":"SCPreferencesCommitChanges"}],"type":"topic","role":"symbol","abstract":[{"text":"Commits changes made to the configuration preferences to persistent storage.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCommitChanges(_:)","title":"SCPreferencesCommitChanges(_:)","url":"/documentation/systemconfiguration/scpreferencescommitchanges(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SCPreferencesCommitChanges"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@SCPreferencesRef","kind":"typeIdentifier","text":"SCPreferences"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration":{"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration","title":"System Configuration","type":"topic","abstract":[{"type":"text","text":"Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active."}],"role":"collection","kind":"symbol","url":"/documentation/systemconfiguration"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesApplyChanges(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCPreferencesApplyChanges"},{"text":"(","kind":"text"},{"text":"SCPreferences","kind":"typeIdentifier","preciseIdentifier":"c:@T@SCPreferencesRef"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesApplyChanges(_:)","abstract":[{"type":"text","text":"Requests that the currently stored configuration preferences be applied to the active configuration."}],"role":"symbol","title":"SCPreferencesApplyChanges(_:)","url":"/documentation/systemconfiguration/scpreferencesapplychanges(_:)","navigatorTitle":[{"text":"SCPreferencesApplyChanges","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSynchronize(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SCPreferencesSynchronize"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@SCPreferencesRef","kind":"typeIdentifier","text":"SCPreferences"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSynchronize(_:)","abstract":[{"type":"text","text":"Synchronizes accessed preferences with committed changes."}],"role":"symbol","title":"SCPreferencesSynchronize(_:)","url":"/documentation/systemconfiguration/scpreferencessynchronize(_:)","navigatorTitle":[{"kind":"identifier","text":"SCPreferencesSynchronize"}],"kind":"symbol","type":"topic"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesGetValue(_:_:)":{"role":"symbol","title":"SCPreferencesGetValue(_:_:)","url":"/documentation/systemconfiguration/scpreferencesgetvalue(_:_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SCPreferencesGetValue"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@SCPreferencesRef","kind":"typeIdentifier","text":"SCPreferences"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@CFStringRef","kind":"typeIdentifier","text":"CFString"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@CFPropertyListRef","kind":"typeIdentifier","text":"CFPropertyList"},{"text":"?","kind":"text"}],"abstract":[{"text":"Retrieves the value associated with the specified preference key.","type":"text"}],"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesGetValue(_:_:)","navigatorTitle":[{"text":"SCPreferencesGetValue","kind":"identifier"}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","type":"topic"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCPreferences","kind":"identifier"}],"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences","abstract":[{"type":"text","text":"The handle to an open preferences session for accessing system configuration preferences."}],"role":"symbol","title":"SCPreferences","url":"/documentation/systemconfiguration/scpreferences","navigatorTitle":[{"kind":"identifier","text":"SCPreferences"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"macOS","deprecated":false,"introducedAt":"10.4","beta":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Function"},{"path":"/metadata/title","op":"replace","value":"SCPreferencesSynchronize"},{"path":"/metadata/symbolKind","op":"replace","value":"func"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"SCPreferencesSynchronize","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.systemconfiguration/documentation/SystemConfiguration"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"title":"Applying and Committing Changes","anchor":"Applying-and-Committing-Changes","identifiers":["doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesApplyChanges(_:)","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCommitChanges(_:)"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCPreferencesSynchronize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences","text":"SCPreferencesRef","preciseIdentifier":"c:@T@SCPreferencesRef"},{"kind":"text","text":" "},{"kind":"internalParam","text":"prefs"},{"kind":"text","text":");"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The preferences session."}]}],"name":"prefs"}],"kind":"parameters"}},{"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCommitChanges(_:)/title","value":"SCPreferencesCommitChanges"},{"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCommitChanges(_:)/fragments","value":[{"kind":"identifier","text":"SCPreferencesCommitChanges"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesApplyChanges(_:)/title","value":"SCPreferencesApplyChanges"},{"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesApplyChanges(_:)/fragments","value":[{"kind":"identifier","text":"SCPreferencesApplyChanges"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesSynchronize(_:)/title","value":"SCPreferencesSynchronize"},{"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesSynchronize(_:)/fragments","value":[{"kind":"identifier","text":"SCPreferencesSynchronize"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesGetValue(_:_:)/title","value":"SCPreferencesGetValue"},{"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesGetValue(_:_:)/fragments","value":[{"kind":"identifier","text":"SCPreferencesGetValue"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferences/title","value":"SCPreferencesRef"},{"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferences/fragments","value":[{"kind":"identifier","text":"SCPreferencesRef"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferences/navigatorTitle","value":[{"kind":"identifier","text":"SCPreferencesRef"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}