{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification/commit","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification/apply"],"anchor":"Constants","title":"Constants"},{"identifiers":["doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.systemconfiguration/documentation/SystemConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SCPreferencesNotification","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"]}]},{"kind":"mentions","mentions":["doc://com.apple.systemconfiguration/documentation/SystemConfiguration/1808421-notificationtype"]}],"abstract":[{"text":"The type of notification (used with the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCallBack","type":"reference"},{"text":" callback).","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP","doc://com.externally.resolved.symbol/s:s9OptionSetP","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP","doc://com.externally.resolved.symbol/s:s10SetAlgebraP"],"type":"conformsTo","title":"Conforms To"}],"kind":"symbol","metadata":{"symbolKind":"struct","platforms":[{"name":"iOS","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false},{"name":"macOS","beta":false,"deprecated":false,"unavailable":false},{"name":"tvOS","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","beta":false,"deprecated":false,"unavailable":false}],"roleHeading":"Structure","modules":[{"name":"System Configuration"}],"role":"symbol","externalID":"c:@E@SCPreferencesNotification","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCPreferencesNotification","kind":"identifier"}],"navigatorTitle":[{"text":"SCPreferencesNotification","kind":"identifier"}],"title":"SCPreferencesNotification"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/systemconfiguration/scpreferencesnotification"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/systemconfiguration/scpreferencesnotification"]}],"references":{"doc://com.apple.systemconfiguration/documentation/SystemConfiguration":{"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration","title":"System Configuration","type":"topic","abstract":[{"type":"text","text":"Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active."}],"role":"collection","kind":"symbol","url":"/documentation/systemconfiguration"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification/init(rawValue:)":{"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification/init(rawValue:)","abstract":[{"text":"Creates a preferences notification structure with the specified raw value.","type":"text"}],"kind":"symbol","url":"/documentation/systemconfiguration/scpreferencesnotification/init(rawvalue:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","abstract":[{"text":"","type":"text"}],"type":"topic","title":"BitwiseCopyable","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"BitwiseCopyable","kind":"identifier"},{"kind":"text","text":" : ~Escapable"}],"url":"/documentation/Swift/BitwiseCopyable","kind":"symbol"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification/apply":{"abstract":[{"type":"text","text":"Indicates when a request has been made to apply the currently saved preferences to the active system configuration."}],"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification/apply","navigatorTitle":[{"kind":"identifier","text":"kSCPreferencesNotificationApply"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apply"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SCPreferencesNotification","text":"SCPreferencesNotification"}],"url":"/documentation/systemconfiguration/scpreferencesnotification/apply","kind":"symbol","title":"apply","role":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/s:s9OptionSetP":{"identifier":"doc://com.externally.resolved.symbol/s:s9OptionSetP","role":"symbol","abstract":[{"text":"A type that presents a mathematical set interface to a bit set.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OptionSet"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SY","text":"RawRepresentable"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s10SetAlgebraP","text":"SetAlgebra"}],"type":"topic","kind":"symbol","title":"OptionSet","url":"/documentation/Swift/OptionSet"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCallBack":{"role":"symbol","title":"SCPreferencesCallBack","identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCallBack","kind":"symbol","abstract":[{"type":"text","text":"Type of the callback function used when the preferences have been updated or applied."}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SCPreferencesCallBack"}],"url":"/documentation/systemconfiguration/scpreferencescallback","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SCPreferencesCallBack"}]},"doc://com.externally.resolved.symbol/s:SQ":{"identifier":"doc://com.externally.resolved.symbol/s:SQ","abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"type":"topic","title":"Equatable","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Equatable"}],"url":"/documentation/Swift/Equatable","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s10SetAlgebraP":{"type":"topic","url":"/documentation/Swift/SetAlgebra","title":"SetAlgebra","abstract":[{"type":"text","text":"A type that provides mathematical set operations."}],"kind":"symbol","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s10SetAlgebraP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SetAlgebra"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Element","preciseIdentifier":"s:s10SetAlgebraP7ElementQa"},{"kind":"text","text":"> : "},{"kind":"typeIdentifier","text":"Equatable","preciseIdentifier":"s:SQ"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ExpressibleByArrayLiteral","preciseIdentifier":"s:s25ExpressibleByArrayLiteralP"}]},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification/commit":{"navigatorTitle":[{"kind":"identifier","text":"kSCPreferencesNotificationCommit"}],"type":"topic","title":"commit","role":"symbol","abstract":[{"text":"Indicates when new preferences have been saved.","type":"text"}],"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification/commit","kind":"symbol","url":"/documentation/systemconfiguration/scpreferencesnotification/commit","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"commit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SCPreferencesNotification","kind":"typeIdentifier","text":"SCPreferencesNotification"}]},"doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP":{"title":"ExpressibleByArrayLiteral","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A type that can be initialized using an array literal."}],"url":"/documentation/Swift/ExpressibleByArrayLiteral","identifier":"doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExpressibleByArrayLiteral"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","type":"topic"},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification":{"kind":"symbol","title":"SCPreferencesNotification","navigatorTitle":[{"kind":"identifier","text":"SCPreferencesNotification"}],"role":"symbol","url":"/documentation/systemconfiguration/scpreferencesnotification","type":"topic","identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification","abstract":[{"text":"The type of notification (used with the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCallBack","type":"reference"},{"text":" callback).","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCPreferencesNotification"}]},"doc://com.externally.resolved.symbol/s:SY":{"identifier":"doc://com.externally.resolved.symbol/s:SY","title":"RawRepresentable","type":"topic","abstract":[{"text":"A type that can be converted to and from an associated raw value.","type":"text"}],"role":"symbol","kind":"symbol","url":"/documentation/Swift/RawRepresentable","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RawRepresentable"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"RawValue","preciseIdentifier":"s:SY8RawValueQa"},{"kind":"text","text":">"}]},"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/1808421-notificationtype":{"identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/1808421-notificationtype","abstract":[{"type":"text","text":"The type of notification, such as changes committed or changes applied. See "},{"type":"reference","identifier":"doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification","isActive":true},{"type":"text","text":" for information about possible values."}],"kind":"article","url":"/documentation/systemconfiguration/1808421-notificationtype","type":"topic","role":"article","title":"notificationType"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"kind":"symbol","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","title":"Sendable","role":"symbol","url":"/documentation/Swift/Sendable","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Sendable"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"name":"iOS","beta":false,"unavailable":false},{"deprecated":false,"name":"iPadOS","beta":false,"unavailable":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false},{"deprecated":false,"name":"macOS","beta":false,"unavailable":false},{"deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","beta":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration"},{"path":"/metadata/title","op":"replace","value":"SCPreferencesNotification"},{"path":"/metadata/symbolKind","op":"replace","value":"enum"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"SCPreferencesNotification","kind":"identifier"}]},{"path":"/metadata/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SCPreferencesNotification"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.systemconfiguration/documentation/SystemConfiguration"]]}},{"path":"/topicSections","op":"replace","value":[{"identifiers":["doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification/commit","doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesNotification/apply"],"title":"Constants","anchor":"Constants"}]},{"path":"/relationshipsSections","op":"replace","value":null},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SCPreferencesNotification","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"uint32_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint32_t"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]}},{"path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesNotification~1apply/title","op":"replace","value":"kSCPreferencesNotificationApply"},{"path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesNotification~1apply/fragments","op":"replace","value":[{"kind":"identifier","text":"kSCPreferencesNotificationApply"}]},{"path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCallBack/title","op":"replace","value":"SCPreferencesCallBack"},{"path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCallBack/fragments","op":"replace","value":[{"text":"SCPreferencesCallBack","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCallBack/navigatorTitle","op":"replace","value":[{"text":"SCPreferencesCallBack","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesNotification~1commit/title","op":"replace","value":"kSCPreferencesNotificationCommit"},{"value":[{"text":"kSCPreferencesNotificationCommit","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesNotification~1commit/fragments","op":"replace"},{"value":"SCPreferencesNotification","path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesNotification/title","op":"replace"},{"value":[{"kind":"identifier","text":"SCPreferencesNotification"}],"path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesNotification/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SCPreferencesNotification"}],"path":"/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesNotification/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}