{
  "abstract": [
    {
      "text": "A structure containing user-specified data and callbacks for accessing system configuration preferences.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@SCPreferencesContext",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCPreferencesContext"
      }
    ],
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCPreferencesContext"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "SCPreferencesContext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCPreferencesContext"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences": {
      "abstract": [
        {
          "text": "The handle to an open preferences session for accessing system configuration preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferences"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferences"
        }
      ],
      "role": "symbol",
      "title": "SCPreferences",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferences"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCallBack": {
      "abstract": [
        {
          "text": "Type of the callback function used when the preferences have been updated or applied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesCallBack"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCallBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesCallBack"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesCallBack",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencescallback"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext": {
      "abstract": [
        {
          "text": "A structure containing user-specified data and callbacks for accessing system configuration preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesContext"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesContext"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesContext",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencescontext"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/copyDescription": {
      "abstract": [
        {
          "text": "The callback used to provide a description of the ",
          "type": "text"
        },
        {
          "code": "info",
          "type": "codeVoice"
        },
        {
          "text": " field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyDescription"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">)?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/copyDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "copyDescription"
        }
      ],
      "role": "symbol",
      "title": "copyDescription",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencescontext/copydescription"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/info": {
      "abstract": [
        {
          "text": "A C pointer to a user-specified block of data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "info"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/info",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "info"
        }
      ],
      "role": "symbol",
      "title": "info",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencescontext/info"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/init()": {
      "abstract": [
        {
          "text": "Creates a preferences context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencescontext/init()"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/init(version:info:retain:release:copyDescription:)": {
      "abstract": [
        {
          "text": "Creates a preferences context with the specified raw values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "info"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "retain"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "release"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "copyDescription"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">)?)"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/init(version:info:retain:release:copyDescription:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(version:info:retain:release:copyDescription:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencescontext/init(version:info:retain:release:copydescription:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/release": {
      "abstract": [
        {
          "text": "The calllback used to remove a retain previously added for the ",
          "type": "text"
        },
        {
          "code": "info",
          "type": "codeVoice"
        },
        {
          "text": " field. If this parameter is not a pointer to a function of the correct prototype, the behavior is undefined. The value may be ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "release"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/release",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "release"
        }
      ],
      "role": "symbol",
      "title": "release",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencescontext/release"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/retain": {
      "abstract": [
        {
          "text": "The callback used to add a retain for the ",
          "type": "text"
        },
        {
          "code": "info",
          "type": "codeVoice"
        },
        {
          "text": " field. If this parameter is not a pointer to a function of the correct prototype, the behavior is undefined. The value may be ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "retain"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/retain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "retain"
        }
      ],
      "role": "symbol",
      "title": "retain",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencescontext/retain"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/version": {
      "abstract": [
        {
          "text": "The version number of the structure type being passed in as a parameter to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSetCallback(_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". This structure is version ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencescontext/version"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSetCallback(_:_:_:)": {
      "abstract": [
        {
          "text": "Assigns the specified callback to the specified preferences session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCPreferencesSetCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesCallBack",
          "text": "SCPreferencesCallBack"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@SCPreferencesContext",
          "text": "SCPreferencesContext"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesSetCallback(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCPreferencesSetCallback"
        }
      ],
      "role": "symbol",
      "title": "SCPreferencesSetCallback(_:_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencessetcallback(_:_:_:)"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCallBack"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/init()",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/init(version:info:retain:release:copyDescription:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/copyDescription",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/info",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/release",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/retain",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/version"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCPreferencesContext"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/copyDescription",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/info",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/release",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/retain",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesContext/version"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferences",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCPreferencesCallBack"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCPreferencesContext"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferences/title",
          "value": "SCPreferencesRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferences/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesSetCallback(_:_:_:)/title",
          "value": "SCPreferencesSetCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesSetCallback(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesSetCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesContext~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesContext~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesContext~1copyDescription/title",
          "value": "copyDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesContext~1copyDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "copyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesContext~1info/title",
          "value": "info"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesContext~1info/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "info"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesContext~1release/title",
          "value": "release"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesContext~1release/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "release"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesContext~1retain/title",
          "value": "retain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesContext~1retain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "retain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCallBack/title",
          "value": "SCPreferencesCallBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCallBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesCallBack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesCallBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesContext/title",
          "value": "SCPreferencesContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCPreferencesContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCPreferencesContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/scpreferencescontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/scpreferencescontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
