{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scschemadefinitions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "role": "collectionGroup",
    "title": "SCSchemaDefinitions"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This document describes keys and values used to access elements in the System Configuration persistent store.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNet6to4",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "6to4 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/6to4-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/airport-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetAirPort",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/airport-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AirPort Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/airport-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to components in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Component Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/component-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/compsystem-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompSystem",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/compsystem-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CompSystem Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/compsystem-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/compusers-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompUsers-swift.var",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/compusers-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CompUsers Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/compusers-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/deprecated-keys": {
      "abstract": [
        {
          "text": "Keys that are no longer supported.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/deprecated-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/deprecated-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dhcpclientpreferences": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dhcpclientpreferences",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DHCPClientPreferences",
      "type": "topic",
      "url": "/documentation/systemconfiguration/dhcpclientpreferences"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetDNS",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "DNS Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/dns-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dynamic-store-domain-prefixes": {
      "abstract": [
        {
          "text": "Prefixes used to access information in the dynamic store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dynamic-store-domain-prefixes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dynamic Store Domain Prefixes",
      "type": "topic",
      "url": "/documentation/systemconfiguration/dynamic-store-domain-prefixes"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dynamic-store-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the dynamic store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dynamic-store-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dynamic Store Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/dynamic-store-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetEthernet",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Ethernet Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ethernet-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys": {
      "abstract": [
        {
          "text": "General-purpose keys that apply to multiple dictionaries in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Generic Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/generic-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompHostnames",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Hostnames Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/hostnames-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompInterface",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Interface Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/interface-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetInterface",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Interface Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/interface-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetIPSec",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPSec Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ipsec-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetIPv4",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPv4 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ipv4-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetIPv6",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IPv6 Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ipv6-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompUsers-swift.var": {
      "abstract": [
        {
          "text": "The Component key Users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCCompUsers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCCompUsers-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCCompUsers"
        }
      ],
      "role": "symbol",
      "title": "kSCCompUsers",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ksccompusers-swift.var"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/l2tp-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetL2TP",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/l2tp-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "L2TP Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/l2tp-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetLink",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Link Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/link-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetModem",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Modem Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/modem-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCCompNetwork",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/network-dictionary-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to network entity dictionaries in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Network Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/network-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ppp-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetPPP",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ppp-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "PPP Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/ppp-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to preferences in the persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Preference Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/preference-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/proxies-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetProxies",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/proxies-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Proxies Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/proxies-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/reserved-keys": {
      "abstract": [
        {
          "text": "Keys that have a reserved usage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/reserved-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Reserved Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/reserved-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstore-gb2": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstore-gb2",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCDynamicStore",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scdynamicstore-gb2"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopydhcpinfo-apicollection": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopydhcpinfo-apicollection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCDynamicStoreCopyDHCPInfo",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scdynamicstorecopydhcpinfo-apicollection"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopyspecific": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopyspecific",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCDynamicStoreCopySpecific",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scdynamicstorecopyspecific"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorekey": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorekey",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCDynamicStoreKey",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scdynamicstorekey"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetwork": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetwork",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCNetwork",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetwork"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCNetworkConfiguration",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconnection-g7e": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconnection-g7e",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCNetworkConnection",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnection-g7e"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkreachability-g7d": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkreachability-g7d",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCNetworkReachability",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkreachability-g7d"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferences-ft8": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferences-ft8",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCPreferences",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferences-ft8"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencespath": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencespath",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCPreferencesPath",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencespath"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencessetspecific": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencessetspecific",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCPreferencesSetSpecific",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scpreferencessetspecific"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/smb-entity-keys": {
      "abstract": [
        {
          "text": "Keys that correspond to values in the ",
          "type": "text"
        },
        {
          "code": "kSCEntNetSMB",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/smb-entity-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SMB Entity Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/smb-entity-keys"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/system-configuration": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/system-configuration",
      "kind": "article",
      "role": "collectionGroup",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration/system-configuration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SystemConfiguration Constants",
      "type": "topic",
      "url": "/documentation/systemconfiguration/systemconfiguration-constants"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SystemConfiguration Data Types",
      "type": "topic",
      "url": "/documentation/systemconfiguration/systemconfiguration-data-types"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SystemConfiguration Enumerations",
      "type": "topic",
      "url": "/documentation/systemconfiguration/systemconfiguration-enumerations"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SystemConfiguration Functions",
      "type": "topic",
      "url": "/documentation/systemconfiguration/systemconfiguration-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstore-gb2",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopyspecific",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorekey",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetwork",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconnection-g7e",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkreachability-g7d",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferences-ft8",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencespath",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencessetspecific",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/system-configuration",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-enumerations",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-constants",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-functions",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ppp-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/l2tp-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/proxies-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/smb-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/compusers-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/compsystem-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dynamic-store-domain-prefixes",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dynamic-store-entity-keys",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/reserved-keys"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/generic-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/preference-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/component-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/hostnames-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/network-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dns-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ethernet-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/interface-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipsec-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv4-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ipv6-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/6to4-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/link-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/modem-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/ppp-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/l2tp-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/proxies-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/smb-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/compusers-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/compsystem-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dynamic-store-domain-prefixes",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dynamic-store-entity-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/reserved-keys"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Deprecated-Constants",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/airport-dictionary-keys",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/deprecated-keys"
              ],
              "title": "Deprecated Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/dhcpclientpreferences",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstore-gb2",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopydhcpinfo-apicollection",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorecopyspecific",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scdynamicstorekey",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetwork",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconfiguration",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconnection-g7e",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkreachability-g7d",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferences-ft8",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencespath",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scpreferencessetspecific",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/system-configuration",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-enumerations",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/systemconfiguration-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompUsers-swift.var/title",
          "value": "kSCCompUsers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCCompUsers-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCCompUsers"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/scschemadefinitions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/scschemadefinitions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
