{
  "abstract": [
    {
      "text": "Updates the specified virtual LAN (VLAN) interface with the specified information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceSetPhysicalInterfaceAndTag(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@SCVLANInterfaceSetPhysicalInterfaceAndTag",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SCVLANInterfaceSetPhysicalInterfaceAndTag"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SCVLANInterfaceRef",
        "text": "SCVLANInterface"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
        "text": "SCNetworkInterface"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFNumberRef",
        "text": "CFNumber"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCVLANInterfaceSetPhysicalInterfaceAndTag"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "SCVLANInterfaceSetPhysicalInterfaceAndTag(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCVLANInterfaceSetPhysicalInterfaceAndTag"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "vlan"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterface",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SCVLANInterfaceRef",
              "text": "SCVLANInterface"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "physical"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterface",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
              "text": "SCNetworkInterface"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "tag"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFNumberRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFNumberRef",
              "text": "CFNumber"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The VLAN interface to update.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "vlan"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The physical interface to associate with the VLAN interface.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "physical"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The tag to associate with the VLAN interface. This value must be between 1 and 4094.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tag"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "code": "TRUE",
              "type": "codeVoice"
            },
            {
              "text": " if the configuration was stored; ",
              "type": "text"
            },
            {
              "code": "FALSE",
              "type": "codeVoice"
            },
            {
              "text": " if an error occurred.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterface": {
      "abstract": [
        {
          "text": "The reference to an object that represents a network interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkInterface"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkInterface"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkInterface",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkinterface"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterface": {
      "abstract": [
        {
          "text": "The reference to an object that represents a virtual LAN (VLAN) interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCVLANInterface"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCVLANInterface"
        }
      ],
      "role": "symbol",
      "title": "SCVLANInterface",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scvlaninterface"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceCopyAll(_:)": {
      "abstract": [
        {
          "text": "Returns all virtual LAN (VLAN) interfaces on the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceCopyAll"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceCopyAll(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceCopyAll"
        }
      ],
      "role": "symbol",
      "title": "SCVLANInterfaceCopyAll(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scvlaninterfacecopyall(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceCopyAvailablePhysicalInterfaces()": {
      "abstract": [
        {
          "text": "Returns the network capable devices on the system that can be associated with a virtual LAN (VLAN) interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceCopyAvailablePhysicalInterfaces"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceCopyAvailablePhysicalInterfaces()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceCopyAvailablePhysicalInterfaces"
        }
      ],
      "role": "symbol",
      "title": "SCVLANInterfaceCopyAvailablePhysicalInterfaces()",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scvlaninterfacecopyavailablephysicalinterfaces()"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceCreate(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a new virtual LAN (VLAN) interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCPreferencesRef",
          "text": "SCPreferences"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNumberRef",
          "text": "CFNumber"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCVLANInterfaceRef",
          "text": "SCVLANInterface"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceCreate(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceCreate"
        }
      ],
      "role": "symbol",
      "title": "SCVLANInterfaceCreate(_:_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scvlaninterfacecreate(_:_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceGetOptions(_:)": {
      "abstract": [
        {
          "text": "Returns the configuration settings associated with the virtual LAN (VLAN) interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceGetOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCVLANInterfaceRef",
          "text": "SCVLANInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceGetOptions(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceGetOptions"
        }
      ],
      "role": "symbol",
      "title": "SCVLANInterfaceGetOptions(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scvlaninterfacegetoptions(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceGetPhysicalInterface(_:)": {
      "abstract": [
        {
          "text": "Returns the physical interface for the specified virtual LAN (VLAN) interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceGetPhysicalInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCVLANInterfaceRef",
          "text": "SCVLANInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceGetPhysicalInterface(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceGetPhysicalInterface"
        }
      ],
      "role": "symbol",
      "title": "SCVLANInterfaceGetPhysicalInterface(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scvlaninterfacegetphysicalinterface(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceGetTag(_:)": {
      "abstract": [
        {
          "text": "Returns the tag for the specified virtual LAN (VLAN) interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceGetTag"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCVLANInterfaceRef",
          "text": "SCVLANInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNumberRef",
          "text": "CFNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceGetTag(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceGetTag"
        }
      ],
      "role": "symbol",
      "title": "SCVLANInterfaceGetTag(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scvlaninterfacegettag(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceRemove(_:)": {
      "abstract": [
        {
          "text": "Removes the virtual LAN (VLAN) interface from the configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceRemove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCVLANInterfaceRef",
          "text": "SCVLANInterface"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceRemove(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceRemove"
        }
      ],
      "role": "symbol",
      "title": "SCVLANInterfaceRemove(_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scvlaninterfaceremove(_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceSetLocalizedDisplayName(_:_:)": {
      "abstract": [
        {
          "text": "Sets the localized display name for the specified virtual LAN (VLAN) interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceSetLocalizedDisplayName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCVLANInterfaceRef",
          "text": "SCVLANInterface"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceSetLocalizedDisplayName(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceSetLocalizedDisplayName"
        }
      ],
      "role": "symbol",
      "title": "SCVLANInterfaceSetLocalizedDisplayName(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scvlaninterfacesetlocalizeddisplayname(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceSetOptions(_:_:)": {
      "abstract": [
        {
          "text": "Sets the specified configuration settings for the specified virtual LAN (VLAN) interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceSetOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCVLANInterfaceRef",
          "text": "SCVLANInterface"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceSetOptions(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceSetOptions"
        }
      ],
      "role": "symbol",
      "title": "SCVLANInterfaceSetOptions(_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scvlaninterfacesetoptions(_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceSetPhysicalInterfaceAndTag(_:_:_:)": {
      "abstract": [
        {
          "text": "Updates the specified virtual LAN (VLAN) interface with the specified information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceSetPhysicalInterfaceAndTag"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCVLANInterfaceRef",
          "text": "SCVLANInterface"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
          "text": "SCNetworkInterface"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFNumberRef",
          "text": "CFNumber"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceSetPhysicalInterfaceAndTag(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCVLANInterfaceSetPhysicalInterfaceAndTag"
        }
      ],
      "role": "symbol",
      "title": "SCVLANInterfaceSetPhysicalInterfaceAndTag(_:_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scvlaninterfacesetphysicalinterfaceandtag(_:_:_:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFNumberRef": {
      "abstract": [
        {
          "text": "A reference to a CFNumber object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFNumberRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFNumber",
      "type": "topic",
      "url": "/documentation/corefoundation/cfnumber"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-VLAN-Interfaces",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceCopyAll(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceCopyAvailablePhysicalInterfaces()",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceCreate(_:_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceGetOptions(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceGetPhysicalInterface(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceGetTag(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceRemove(_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceSetLocalizedDisplayName(_:_:)",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceSetOptions(_:_:)"
      ],
      "title": "Configuring VLAN Interfaces"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCVLANInterfaceSetPhysicalInterfaceAndTag"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCVLANInterfaceSetPhysicalInterfaceAndTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-VLAN-Interfaces",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceCopyAll(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceCopyAvailablePhysicalInterfaces()",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceCreate(_:_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceGetOptions(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceGetPhysicalInterface(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceGetTag(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceRemove(_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceSetLocalizedDisplayName(_:_:)",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterfaceSetOptions(_:_:)"
              ],
              "title": "Configuring VLAN Interfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@Boolean",
                    "text": "Boolean"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SCVLANInterfaceSetPhysicalInterfaceAndTag"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCVLANInterface",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SCVLANInterfaceRef",
                    "text": "SCVLANInterfaceRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "vlan"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkInterface",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SCNetworkInterfaceRef",
                    "text": "SCNetworkInterfaceRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "physical"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFNumberRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFNumberRef",
                    "text": "CFNumberRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "tag"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The VLAN interface to update.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "vlan"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The physical interface to associate with the VLAN interface.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "physical"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The tag to associate with the VLAN interface. This value must be between 1 and 4094.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "tag"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "code": "TRUE",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if the configuration was stored; ",
                    "type": "text"
                  },
                  {
                    "code": "FALSE",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if an error occurred.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceSetPhysicalInterfaceAndTag(_:_:_:)/title",
          "value": "SCVLANInterfaceSetPhysicalInterfaceAndTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceSetPhysicalInterfaceAndTag(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCVLANInterfaceSetPhysicalInterfaceAndTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceCopyAvailablePhysicalInterfaces()/title",
          "value": "SCVLANInterfaceCopyAvailablePhysicalInterfaces"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceCopyAvailablePhysicalInterfaces()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCVLANInterfaceCopyAvailablePhysicalInterfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceGetTag(_:)/title",
          "value": "SCVLANInterfaceGetTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceGetTag(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCVLANInterfaceGetTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceRemove(_:)/title",
          "value": "SCVLANInterfaceRemove"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceRemove(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCVLANInterfaceRemove"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterface/title",
          "value": "SCNetworkInterfaceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkInterface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkInterfaceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceCreate(_:_:_:)/title",
          "value": "SCVLANInterfaceCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceCreate(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCVLANInterfaceCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceSetLocalizedDisplayName(_:_:)/title",
          "value": "SCVLANInterfaceSetLocalizedDisplayName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceSetLocalizedDisplayName(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCVLANInterfaceSetLocalizedDisplayName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceSetOptions(_:_:)/title",
          "value": "SCVLANInterfaceSetOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceSetOptions(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCVLANInterfaceSetOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFNumberRef/title",
          "value": "CFNumberRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceCopyAll(_:)/title",
          "value": "SCVLANInterfaceCopyAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceCopyAll(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCVLANInterfaceCopyAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceGetOptions(_:)/title",
          "value": "SCVLANInterfaceGetOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceGetOptions(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCVLANInterfaceGetOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceGetPhysicalInterface(_:)/title",
          "value": "SCVLANInterfaceGetPhysicalInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterfaceGetPhysicalInterface(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCVLANInterfaceGetPhysicalInterface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterface/title",
          "value": "SCVLANInterfaceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCVLANInterfaceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCVLANInterface/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCVLANInterfaceRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/scvlaninterfacesetphysicalinterfaceandtag(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/scvlaninterfacesetphysicalinterfaceandtag(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
