{
  "abstract": [
    {
      "text": "Keys used with the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionCopyUserPreferences(_:_:_:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " selection options dictionary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconnection-g7e"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/selection-options-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "System Configuration"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Selection Options Dictionary Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration": {
      "abstract": [
        {
          "text": "Allow applications to access a device’s network configuration settings. Determine the reachability of the device, such as whether Wi-Fi or cell connectivity are active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration",
      "kind": "symbol",
      "role": "collection",
      "title": "System Configuration",
      "type": "topic",
      "url": "/documentation/systemconfiguration"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionCopyUserPreferences(_:_:_:)": {
      "abstract": [
        {
          "text": "Provides the default service ID and a dictionary of user options for the specified connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkConnectionCopyUserPreferences"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">?>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionCopyUserPreferences(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkConnectionCopyUserPreferences"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionCopyUserPreferences(_:_:_:)",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectioncopyuserpreferences(_:_:_:)"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus": {
      "abstract": [
        {
          "text": "The PPP-specific status of the network connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkConnectionPPPStatus"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkConnectionPPPStatus"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionPPPStatus",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionpppstatus"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionStatus": {
      "abstract": [
        {
          "text": "The current status of the network connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNetworkConnectionStatus"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNetworkConnectionStatus"
        }
      ],
      "role": "symbol",
      "title": "SCNetworkConnectionStatus",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnectionstatus"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkConnectionSelectionOptionOnDemandHostName": {
      "abstract": [
        {
          "text": "The key associated with a host name used to select the “best” network connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionSelectionOptionOnDemandHostName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkConnectionSelectionOptionOnDemandHostName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionSelectionOptionOnDemandHostName"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkConnectionSelectionOptionOnDemandHostName",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkconnectionselectionoptionondemandhostname"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkConnectionSelectionOptionOnDemandRetry": {
      "abstract": [
        {
          "text": "The key associated with a Boolean value used to indicate whether a DNS query has already been issued for the specified on-demand host name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionSelectionOptionOnDemandRetry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkConnectionSelectionOptionOnDemandRetry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kSCNetworkConnectionSelectionOptionOnDemandRetry"
        }
      ],
      "role": "symbol",
      "title": "kSCNetworkConnectionSelectionOptionOnDemandRetry",
      "type": "topic",
      "url": "/documentation/systemconfiguration/kscnetworkconnectionselectionoptionondemandretry"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconnection-g7e": {
      "abstract": [],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/scnetworkconnection-g7e",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SCNetworkConnection",
      "type": "topic",
      "url": "/documentation/systemconfiguration/scnetworkconnection-g7e"
    },
    "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/statistics-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys associated with values in the statistics dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/statistics-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Statistics Dictionary Keys",
      "type": "topic",
      "url": "/documentation/systemconfiguration/statistics-dictionary-keys"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionStatus",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/statistics-dictionary-keys"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkConnectionSelectionOptionOnDemandHostName",
        "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkConnectionSelectionOptionOnDemandRetry"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkConnectionSelectionOptionOnDemandHostName",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/kSCNetworkConnectionSelectionOptionOnDemandRetry"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionStatus",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/SCNetworkConnectionPPPStatus",
                "doc://com.apple.systemconfiguration/documentation/SystemConfiguration/statistics-dictionary-keys"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkConnectionSelectionOptionOnDemandRetry/title",
          "value": "kSCNetworkConnectionSelectionOptionOnDemandRetry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkConnectionSelectionOptionOnDemandRetry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkConnectionSelectionOptionOnDemandRetry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionStatus/title",
          "value": "SCNetworkConnectionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkConnectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkConnectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus/title",
          "value": "SCNetworkConnectionPPPStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkConnectionPPPStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionPPPStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkConnectionPPPStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkConnectionSelectionOptionOnDemandHostName/title",
          "value": "kSCNetworkConnectionSelectionOptionOnDemandHostName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1kSCNetworkConnectionSelectionOptionOnDemandHostName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kSCNetworkConnectionSelectionOptionOnDemandHostName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionCopyUserPreferences(_:_:_:)/title",
          "value": "SCNetworkConnectionCopyUserPreferences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.systemconfiguration~1documentation~1SystemConfiguration~1SCNetworkConnectionCopyUserPreferences(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNetworkConnectionCopyUserPreferences"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/systemconfiguration/selection-options-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/systemconfiguration/selection-options-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
