{
  "abstract": [
    {
      "text": "A value indicating that the item can be moved.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsReparenting"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSFileProviderItemCapabilities@NSFileProviderItemCapabilitiesAllowsReparenting",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "allowsReparenting"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSFileProviderItemCapabilities",
        "text": "NSFileProviderItemCapabilities"
      }
    ],
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFileProviderItemCapabilitiesAllowsReparenting"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "allowsReparenting"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "allowsReparenting"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSFileProviderItemCapabilities",
              "text": "NSFileProviderItemCapabilities"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities": {
      "abstract": [
        {
          "text": "An item’s capabilities, which define the actions that the user can perform in the document browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderItemCapabilities"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderItemCapabilities"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderItemCapabilities",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemcapabilities"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsAddingSubItems": {
      "abstract": [
        {
          "text": "A value indicating that the user can add subitems.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsAddingSubItems"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderItemCapabilities",
          "text": "NSFileProviderItemCapabilities"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsAddingSubItems",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderItemCapabilitiesAllowsAddingSubItems"
        }
      ],
      "role": "symbol",
      "title": "allowsAddingSubItems",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemcapabilities/allowsaddingsubitems"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsAll": {
      "abstract": [
        {
          "text": "A convenience value for enabling all capabilities.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsAll"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderItemCapabilities",
          "text": "NSFileProviderItemCapabilities"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsAll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderItemCapabilitiesAllowsAll"
        }
      ],
      "role": "symbol",
      "title": "allowsAll",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemcapabilities/allowsall"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsContentEnumerating": {
      "abstract": [
        {
          "text": "A value indicating that the item’s contents can be enumerated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsContentEnumerating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderItemCapabilities",
          "text": "NSFileProviderItemCapabilities"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsContentEnumerating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderItemCapabilitiesAllowsContentEnumerating"
        }
      ],
      "role": "symbol",
      "title": "allowsContentEnumerating",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemcapabilities/allowscontentenumerating"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsDeleting": {
      "abstract": [
        {
          "text": "A value indicating that the item can be deleted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsDeleting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderItemCapabilities",
          "text": "NSFileProviderItemCapabilities"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsDeleting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderItemCapabilitiesAllowsDeleting"
        }
      ],
      "role": "symbol",
      "title": "allowsDeleting",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemcapabilities/allowsdeleting"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsEvicting": {
      "abstract": [
        {
          "text": "A value indicating that the system can delete the local copy of the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsEvicting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderItemCapabilities",
          "text": "NSFileProviderItemCapabilities"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsEvicting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderItemCapabilitiesAllowsEvicting"
        }
      ],
      "role": "symbol",
      "title": "allowsEvicting",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemcapabilities/allowsevicting"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsExcludingFromSync": {
      "abstract": [
        {
          "text": "A value indicating that the user can exclude the item from sync operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsExcludingFromSync"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderItemCapabilities",
          "text": "NSFileProviderItemCapabilities"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsExcludingFromSync",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderItemCapabilitiesAllowsExcludingFromSync"
        }
      ],
      "role": "symbol",
      "title": "allowsExcludingFromSync",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemcapabilities/allowsexcludingfromsync"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsReading": {
      "abstract": [
        {
          "text": "A value indicating that the value can be read from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsReading"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderItemCapabilities",
          "text": "NSFileProviderItemCapabilities"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsReading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderItemCapabilitiesAllowsReading"
        }
      ],
      "role": "symbol",
      "title": "allowsReading",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemcapabilities/allowsreading"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsRenaming": {
      "abstract": [
        {
          "text": "A value indicating that the item can be renamed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsRenaming"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderItemCapabilities",
          "text": "NSFileProviderItemCapabilities"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsRenaming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderItemCapabilitiesAllowsRenaming"
        }
      ],
      "role": "symbol",
      "title": "allowsRenaming",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemcapabilities/allowsrenaming"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsReparenting": {
      "abstract": [
        {
          "text": "A value indicating that the item can be moved.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsReparenting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderItemCapabilities",
          "text": "NSFileProviderItemCapabilities"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsReparenting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderItemCapabilitiesAllowsReparenting"
        }
      ],
      "role": "symbol",
      "title": "allowsReparenting",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemcapabilities/allowsreparenting"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsTrashing": {
      "abstract": [
        {
          "text": "A value indicating that the item can be moved to the trash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsTrashing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderItemCapabilities",
          "text": "NSFileProviderItemCapabilities"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsTrashing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderItemCapabilitiesAllowsTrashing"
        }
      ],
      "role": "symbol",
      "title": "allowsTrashing",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemcapabilities/allowstrashing"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsWriting": {
      "abstract": [
        {
          "text": "A value indicating that the item can be written to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsWriting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFileProviderItemCapabilities",
          "text": "NSFileProviderItemCapabilities"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsWriting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderItemCapabilitiesAllowsWriting"
        }
      ],
      "role": "symbol",
      "title": "allowsWriting",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovideritemcapabilities/allowswriting"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsAddingSubItems",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsContentEnumerating",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsDeleting",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsEvicting",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsReading",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsRenaming",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsTrashing",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsWriting",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsExcludingFromSync",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsAll"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFileProviderItemCapabilitiesAllowsReparenting"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemCapabilitiesAllowsReparenting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.fileprovider/documentation/FileProvider",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsAddingSubItems",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsContentEnumerating",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsDeleting",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsEvicting",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsReading",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsRenaming",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsTrashing",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsWriting",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsExcludingFromSync",
                "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderItemCapabilities/allowsAll"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSFileProviderItemCapabilitiesAllowsReparenting"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsReparenting/title",
          "value": "NSFileProviderItemCapabilitiesAllowsReparenting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsReparenting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemCapabilitiesAllowsReparenting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsReading/title",
          "value": "NSFileProviderItemCapabilitiesAllowsReading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsReading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemCapabilitiesAllowsReading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities/title",
          "value": "NSFileProviderItemCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsAddingSubItems/title",
          "value": "NSFileProviderItemCapabilitiesAllowsAddingSubItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsAddingSubItems/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemCapabilitiesAllowsAddingSubItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsTrashing/title",
          "value": "NSFileProviderItemCapabilitiesAllowsTrashing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsTrashing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemCapabilitiesAllowsTrashing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsDeleting/title",
          "value": "NSFileProviderItemCapabilitiesAllowsDeleting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsDeleting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemCapabilitiesAllowsDeleting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsAll/title",
          "value": "NSFileProviderItemCapabilitiesAllowsAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsAll/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemCapabilitiesAllowsAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsWriting/title",
          "value": "NSFileProviderItemCapabilitiesAllowsWriting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsWriting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemCapabilitiesAllowsWriting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsExcludingFromSync/title",
          "value": "NSFileProviderItemCapabilitiesAllowsExcludingFromSync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsExcludingFromSync/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemCapabilitiesAllowsExcludingFromSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsRenaming/title",
          "value": "NSFileProviderItemCapabilitiesAllowsRenaming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsRenaming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemCapabilitiesAllowsRenaming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsEvicting/title",
          "value": "NSFileProviderItemCapabilitiesAllowsEvicting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsEvicting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemCapabilitiesAllowsEvicting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsContentEnumerating/title",
          "value": "NSFileProviderItemCapabilitiesAllowsContentEnumerating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderItemCapabilities~1allowsContentEnumerating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderItemCapabilitiesAllowsContentEnumerating"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovideritemcapabilities/allowsreparenting"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovideritemcapabilities/allowsreparenting"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
