{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.fileprovider/documentation/FileProvider",
        "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderVolumeUnsupportedReason"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderVolumeUnsupportedReason/NSFileProviderVolumeUnsupportedReasonNone"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSFileProviderVolumeUnsupportedReason@NSFileProviderVolumeUnsupportedReasonNone",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSFileProviderVolumeUnsupportedReasonNone"
      }
    ],
    "modules": [
      {
        "name": "File Provider"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFileProviderVolumeUnsupportedReasonNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "NSFileProviderVolumeUnsupportedReasonNone"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "NSFileProviderVolumeUnsupportedReasonNone"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider": {
      "abstract": [
        {
          "text": "An extension other apps use to access files and folders managed by your app and synced with a remote storage.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider",
      "kind": "symbol",
      "role": "collection",
      "title": "File Provider",
      "type": "topic",
      "url": "/documentation/fileprovider"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderVolumeUnsupportedReason": {
      "abstract": [
        {
          "text": "Constants that describe why an external volume might not be eligible for storing a domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileProviderVolumeUnsupportedReason"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderVolumeUnsupportedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFileProviderVolumeUnsupportedReason"
        }
      ],
      "role": "symbol",
      "title": "NSFileProviderVolumeUnsupportedReason",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidervolumeunsupportedreason"
    },
    "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderVolumeUnsupportedReason/NSFileProviderVolumeUnsupportedReasonNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFileProviderVolumeUnsupportedReasonNone"
        }
      ],
      "identifier": "doc://com.apple.fileprovider/documentation/FileProvider/NSFileProviderVolumeUnsupportedReason/NSFileProviderVolumeUnsupportedReasonNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFileProviderVolumeUnsupportedReasonNone",
      "type": "topic",
      "url": "/documentation/fileprovider/nsfileprovidervolumeunsupportedreason/nsfileprovidervolumeunsupportedreasonnone"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderVolumeUnsupportedReason/title",
          "value": "NSFileProviderVolumeUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderVolumeUnsupportedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderVolumeUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.fileprovider~1documentation~1FileProvider~1NSFileProviderVolumeUnsupportedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFileProviderVolumeUnsupportedReason"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fileprovider/nsfileprovidervolumeunsupportedreason/nsfileprovidervolumeunsupportedreasonnone"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
