{
  "abstract": [
    {
      "text": "Get a tag as a MIFARE tag object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum/miFare(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:7CoreNFC6NFCTagO6miFareyACSo05NFCMiE3Tag_pcACmF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "miFare"
      },
      {
        "kind": "text",
        "text": "(any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)NFCMiFareTag",
        "text": "NFCMiFareTag"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NFCTag.miFare(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "miFare"
            },
            {
              "kind": "text",
              "text": "(any "
            },
            {
              "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCMiFareTag",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NFCMiFareTag",
              "text": "NFCMiFareTag"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCMiFareTag": {
      "abstract": [
        {
          "text": "An interface for interacting with a MIFARE® tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCMiFareTag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCMiFareTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCMiFareTag"
        }
      ],
      "role": "symbol",
      "title": "NFCMiFareTag",
      "type": "topic",
      "url": "/documentation/corenfc/nfcmifaretag"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum": {
      "abstract": [
        {
          "text": "An object that represents an NFC tag object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCTag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCTag"
        }
      ],
      "role": "symbol",
      "title": "NFCTag",
      "type": "topic",
      "url": "/documentation/corenfc/nfctag-swift.enum"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum/feliCa(_:)": {
      "abstract": [
        {
          "text": "Gets a tag as a FeliCa tag object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "feliCa"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NFCFeliCaTag",
          "text": "NFCFeliCaTag"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum/feliCa(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "NFCTag.feliCa(_:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfctag-swift.enum/felica(_:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum/iso15693(_:)": {
      "abstract": [
        {
          "text": "Gets a tag as an ISO 15693 tag object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iso15693"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NFCISO15693Tag",
          "text": "NFCISO15693Tag"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum/iso15693(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "NFCTag.iso15693(_:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfctag-swift.enum/iso15693(_:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum/iso7816(_:)": {
      "abstract": [
        {
          "text": "Gets a tag as an ISO 7816 tag object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iso7816"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NFCISO7816Tag",
          "text": "NFCISO7816Tag"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum/iso7816(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "NFCTag.iso7816(_:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfctag-swift.enum/iso7816(_:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum/miFare(_:)": {
      "abstract": [
        {
          "text": "Get a tag as a MIFARE tag object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "miFare"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NFCMiFareTag",
          "text": "NFCMiFareTag"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum/miFare(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "NFCTag.miFare(_:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfctag-swift.enum/mifare(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-a-Specific-Tag-Type",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum/iso15693(_:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum/iso7816(_:)",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCTag-swift.enum/feliCa(_:)"
      ],
      "title": "Getting a Specific Tag Type"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCMiFareTag/title",
          "value": "NFCMiFareTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCMiFareTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCMiFareTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCMiFareTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCMiFareTag"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfctag-swift.enum/mifare(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
