{
  "abstract": [
    {
      "text": "A resonation that simulates the experience of hearing a sound in one kind of large room with specific dimensions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.phase/documentation/PHASE",
        "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeRoom2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PHASEReverbPreset@PHASEReverbPresetLargeRoom2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "largeRoom2"
      }
    ],
    "modules": [
      {
        "name": "PHASE"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PHASEReverbPresetLargeRoom2"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PHASEReverbPreset.largeRoom2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "largeRoom2"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.phase/documentation/PHASE": {
      "abstract": [
        {
          "text": "Create dynamic audio experiences in your game or app that react to events and cues in the environment.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE",
      "kind": "symbol",
      "role": "collection",
      "title": "PHASE",
      "type": "topic",
      "url": "/documentation/phase"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset": {
      "abstract": [
        {
          "text": "The manner in which PHASE diffuses resonating sound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHASEReverbPreset"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEReverbPreset"
        }
      ],
      "role": "symbol",
      "title": "PHASEReverbPreset",
      "type": "topic",
      "url": "/documentation/phase/phasereverbpreset"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/cathedral": {
      "abstract": [
        {
          "text": "A resonation that simulates the experience of hearing a sound in a cathedral.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cathedral"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/cathedral",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEReverbPresetCathedral"
        }
      ],
      "role": "symbol",
      "title": "PHASEReverbPreset.cathedral",
      "type": "topic",
      "url": "/documentation/phase/phasereverbpreset/cathedral"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeChamber": {
      "abstract": [
        {
          "text": "A resonation that simulates the experience of hearing a sound in a large chamber with specific dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "largeChamber"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeChamber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEReverbPresetLargeChamber"
        }
      ],
      "role": "symbol",
      "title": "PHASEReverbPreset.largeChamber",
      "type": "topic",
      "url": "/documentation/phase/phasereverbpreset/largechamber"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeHall": {
      "abstract": [
        {
          "text": "A resonation that simulates the experience of hearing a sound in a large hall with specific dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "largeHall"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeHall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEReverbPresetLargeHall"
        }
      ],
      "role": "symbol",
      "title": "PHASEReverbPreset.largeHall",
      "type": "topic",
      "url": "/documentation/phase/phasereverbpreset/largehall"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeHall2": {
      "abstract": [
        {
          "text": "A resonation that simulates the experience of hearing a sound in one kind of large hall with specific dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "largeHall2"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeHall2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEReverbPresetLargeHall2"
        }
      ],
      "role": "symbol",
      "title": "PHASEReverbPreset.largeHall2",
      "type": "topic",
      "url": "/documentation/phase/phasereverbpreset/largehall2"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeRoom": {
      "abstract": [
        {
          "text": "A resonation that simulates the experience of hearing a sound in a large room with specific dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "largeRoom"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeRoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEReverbPresetLargeRoom"
        }
      ],
      "role": "symbol",
      "title": "PHASEReverbPreset.largeRoom",
      "type": "topic",
      "url": "/documentation/phase/phasereverbpreset/largeroom"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeRoom2": {
      "abstract": [
        {
          "text": "A resonation that simulates the experience of hearing a sound in one kind of large room with specific dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "largeRoom2"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeRoom2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEReverbPresetLargeRoom2"
        }
      ],
      "role": "symbol",
      "title": "PHASEReverbPreset.largeRoom2",
      "type": "topic",
      "url": "/documentation/phase/phasereverbpreset/largeroom2"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumChamber": {
      "abstract": [
        {
          "text": "A resonation that simulates the experience of hearing a sound in a medium-size chamber with specific dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediumChamber"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumChamber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEReverbPresetMediumChamber"
        }
      ],
      "role": "symbol",
      "title": "PHASEReverbPreset.mediumChamber",
      "type": "topic",
      "url": "/documentation/phase/phasereverbpreset/mediumchamber"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumHall": {
      "abstract": [
        {
          "text": "A resonation that simulates the experience of hearing a sound in a medium-size hall with specific dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediumHall"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumHall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEReverbPresetMediumHall"
        }
      ],
      "role": "symbol",
      "title": "PHASEReverbPreset.mediumHall",
      "type": "topic",
      "url": "/documentation/phase/phasereverbpreset/mediumhall"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumHall2": {
      "abstract": [
        {
          "text": "A resonation that simulates the experience of hearing a sound in one kind of medium-size hall with specific dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediumHall2"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumHall2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEReverbPresetMediumHall2"
        }
      ],
      "role": "symbol",
      "title": "PHASEReverbPreset.mediumHall2",
      "type": "topic",
      "url": "/documentation/phase/phasereverbpreset/mediumhall2"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumHall3": {
      "abstract": [
        {
          "text": "A resonation that simulates the experience of hearing a sound in another kind of medium-size hall with specific dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediumHall3"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumHall3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEReverbPresetMediumHall3"
        }
      ],
      "role": "symbol",
      "title": "PHASEReverbPreset.mediumHall3",
      "type": "topic",
      "url": "/documentation/phase/phasereverbpreset/mediumhall3"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumRoom": {
      "abstract": [
        {
          "text": "A resonation that simulates the experience of hearing a sound in a medium-size room with specific dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediumRoom"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumRoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEReverbPresetMediumRoom"
        }
      ],
      "role": "symbol",
      "title": "PHASEReverbPreset.mediumRoom",
      "type": "topic",
      "url": "/documentation/phase/phasereverbpreset/mediumroom"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/none": {
      "abstract": [
        {
          "text": "An option that adds no reverberation to a sound.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEReverbPresetNone"
        }
      ],
      "role": "symbol",
      "title": "PHASEReverbPreset.none",
      "type": "topic",
      "url": "/documentation/phase/phasereverbpreset/none"
    },
    "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/smallRoom": {
      "abstract": [
        {
          "text": "A resonation that simulates the experience of hearing a sound in a small room with specific dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smallRoom"
        }
      ],
      "identifier": "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/smallRoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHASEReverbPresetSmallRoom"
        }
      ],
      "role": "symbol",
      "title": "PHASEReverbPreset.smallRoom",
      "type": "topic",
      "url": "/documentation/phase/phasereverbpreset/smallroom"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Presets",
      "generated": true,
      "identifiers": [
        "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/cathedral",
        "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeChamber",
        "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeHall",
        "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeHall2",
        "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeRoom",
        "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumChamber",
        "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumHall",
        "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumHall2",
        "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumHall3",
        "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumRoom",
        "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/none",
        "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/smallRoom"
      ],
      "title": "Presets"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PHASEReverbPresetLargeRoom2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPresetLargeRoom2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.phase/documentation/PHASE",
                "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Presets",
              "generated": true,
              "identifiers": [
                "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/cathedral",
                "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeChamber",
                "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeHall",
                "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeHall2",
                "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/largeRoom",
                "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumChamber",
                "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumHall",
                "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumHall2",
                "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumHall3",
                "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/mediumRoom",
                "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/none",
                "doc://com.apple.phase/documentation/PHASE/PHASEReverbPreset/smallRoom"
              ],
              "title": "Presets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PHASEReverbPresetLargeRoom2"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1none/title",
          "value": "PHASEReverbPresetNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPresetNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1mediumHall3/title",
          "value": "PHASEReverbPresetMediumHall3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1mediumHall3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPresetMediumHall3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1largeHall/title",
          "value": "PHASEReverbPresetLargeHall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1largeHall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPresetLargeHall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset/title",
          "value": "PHASEReverbPreset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1cathedral/title",
          "value": "PHASEReverbPresetCathedral"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1cathedral/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPresetCathedral"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1mediumChamber/title",
          "value": "PHASEReverbPresetMediumChamber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1mediumChamber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPresetMediumChamber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1largeChamber/title",
          "value": "PHASEReverbPresetLargeChamber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1largeChamber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPresetLargeChamber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1largeRoom2/title",
          "value": "PHASEReverbPresetLargeRoom2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1largeRoom2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPresetLargeRoom2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1mediumHall2/title",
          "value": "PHASEReverbPresetMediumHall2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1mediumHall2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPresetMediumHall2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1largeRoom/title",
          "value": "PHASEReverbPresetLargeRoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1largeRoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPresetLargeRoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1largeHall2/title",
          "value": "PHASEReverbPresetLargeHall2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1largeHall2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPresetLargeHall2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1smallRoom/title",
          "value": "PHASEReverbPresetSmallRoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1smallRoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPresetSmallRoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1mediumHall/title",
          "value": "PHASEReverbPresetMediumHall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1mediumHall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPresetMediumHall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1mediumRoom/title",
          "value": "PHASEReverbPresetMediumRoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.phase~1documentation~1PHASE~1PHASEReverbPreset~1mediumRoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHASEReverbPresetMediumRoom"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/phase/phasereverbpreset/largeroom2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/phase/phasereverbpreset/largeroom2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
