{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource/scrubber(_:viewForItemAt:)"},"sections":[],"abstract":[{"type":"text","text":"Asks the data source object for the view the corresponds to the specified item in the scrubber."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsscrubberdatasource/scrubber(_:viewforitemat:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsscrubberdatasource/scrubber(_:viewforitemat:)"]}],"metadata":{"modules":[{"name":"AppKit"}],"title":"scrubber(_:viewForItemAt:)","externalID":"c:objc(pl)NSScrubberDataSource(im)scrubber:viewForItemAtIndex:","roleHeading":"Instance Method","symbolKind":"method","platforms":[{"deprecated":false,"introducedAt":"10.12.2","beta":false,"name":"macOS","unavailable":false}],"role":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrubber","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSScrubber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSScrubber"},{"text":", ","kind":"text"},{"text":"viewForItemAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"NSScrubberItemView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSScrubberItemView"}],"navigatorTitle":[{"text":"scrubber:viewForItemAtIndex:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrubber","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"scrubber","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSScrubber","preciseIdentifier":"c:objc(cs)NSScrubber","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSScrubber"},{"text":", ","kind":"text"},{"text":"viewForItemAt","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"index","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Si"},{"text":") -> ","kind":"text"},{"text":"NSScrubberItemView","preciseIdentifier":"c:objc(cs)NSScrubberItemView","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSScrubberItemView"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"scrubber","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The scrubber requesting the view."}]}]},{"name":"index","content":[{"inlineContent":[{"type":"text","text":"The index that specifies the location of the item in the scrubber."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"A configured item view object."}],"type":"paragraph"}]}],"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource/scrubber(_:viewForItemAt:)":{"navigatorTitle":[{"text":"scrubber:viewForItemAtIndex:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource/scrubber(_:viewForItemAt:)","type":"topic","abstract":[{"type":"text","text":"Asks the data source object for the view the corresponds to the specified item in the scrubber."}],"title":"scrubber(_:viewForItemAt:)","role":"symbol","url":"/documentation/appkit/nsscrubberdatasource/scrubber(_:viewforitemat:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrubber"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSScrubber","text":"NSScrubber"},{"text":", ","kind":"text"},{"text":"viewForItemAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSScrubberItemView","preciseIdentifier":"c:objc(cs)NSScrubberItemView","kind":"typeIdentifier"}],"required":true},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource":{"title":"NSScrubberDataSource","type":"topic","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource","abstract":[{"text":"A set of methods that a scrubber data source object implements to provide items to the scrubber from an associated data collection in your app.","type":"text"}],"role":"symbol","url":"/documentation/appkit/nsscrubberdatasource","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NSScrubberDataSource","kind":"identifier"}],"navigatorTitle":[{"text":"NSScrubberDataSource","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSScrubberItemView":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSScrubberItemView"}],"title":"NSScrubberItemView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSScrubberItemView","abstract":[{"type":"text","text":"An item at a specific index position in the scrubber."}],"role":"symbol","url":"/documentation/appkit/nsscrubberitemview","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSScrubberItemView"}]},"doc://com.apple.appkit/documentation/AppKit/NSScrubber":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSScrubber","abstract":[{"type":"text","text":"A customizable item picker control for the Touch Bar."}],"role":"symbol","navigatorTitle":[{"text":"NSScrubber","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSScrubber","kind":"identifier"}],"title":"NSScrubber","kind":"symbol","url":"/documentation/appkit/nsscrubber","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"introducedAt":"10.12.2","deprecated":false,"beta":false,"name":"macOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"scrubber:viewForItemAtIndex:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"scrubber:viewForItemAtIndex:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSScrubberDataSource"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSScrubberItemView","identifier":"doc://com.apple.appkit/documentation/AppKit/NSScrubberItemView","text":"NSScrubberItemView"},{"text":" *) ","kind":"text"},{"text":"scrubber:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSScrubber","preciseIdentifier":"c:objc(cs)NSScrubber","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSScrubber"},{"text":" *) ","kind":"text"},{"text":"scrubber","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewForItemAtIndex:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"index"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The scrubber requesting the view.","type":"text"}],"type":"paragraph"}],"name":"scrubber"},{"content":[{"inlineContent":[{"type":"text","text":"The index that specifies the location of the item in the scrubber."}],"type":"paragraph"}],"name":"index"}],"kind":"parameters"},"op":"replace"},{"path":"/primaryContentSections/2","value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"text":"A configured item view object.","type":"text"}],"type":"paragraph"}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDataSource~1scrubber(_:viewForItemAt:)/title","value":"scrubber:viewForItemAtIndex:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDataSource~1scrubber(_:viewForItemAt:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrubber:viewForItemAtIndex:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDataSource/title","value":"NSScrubberDataSource","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDataSource/fragments","value":[{"text":"NSScrubberDataSource","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberDataSource/navigatorTitle","value":[{"text":"NSScrubberDataSource","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberItemView/title","value":"NSScrubberItemView","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberItemView/fragments","value":[{"kind":"identifier","text":"NSScrubberItemView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberItemView/navigatorTitle","value":[{"text":"NSScrubberItemView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubber/title","value":"NSScrubber","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubber/fragments","value":[{"text":"NSScrubber","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubber/navigatorTitle","value":[{"kind":"identifier","text":"NSScrubber"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}