{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTokenField",
        "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/default"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSTokenStyle@NSTokenStyleDefault",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "`default`"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTokenStyleDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSTokenField.TokenStyle.default"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "`default`"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenField": {
      "abstract": [
        {
          "text": "A text field that converts text into visually distinct tokens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTokenField"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTokenField"
        }
      ],
      "role": "symbol",
      "title": "NSTokenField",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfield"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum": {
      "abstract": [
        {
          "text": "The NSTokenStyle constants define how tokens are displayed and editable in the ",
          "type": "text"
        },
        {
          "code": "NSTokenFieldCell",
          "type": "codeVoice"
        },
        {
          "text": ". These values are used by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCell/tokenStyle",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and the delegate method ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:styleForRepresentedObject:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TokenStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TokenStyle"
        }
      ],
      "role": "symbol",
      "title": "NSTokenField.TokenStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfield/tokenstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/default": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTokenStyleDefault"
        }
      ],
      "role": "symbol",
      "title": "NSTokenField.TokenStyle.default",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfield/tokenstyle-swift.enum/default"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/none": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTokenStyleNone"
        }
      ],
      "role": "symbol",
      "title": "NSTokenField.TokenStyle.none",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfield/tokenstyle-swift.enum/none"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/plainSquared": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "plainSquared"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/plainSquared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTokenStylePlainSquared"
        }
      ],
      "role": "symbol",
      "title": "NSTokenField.TokenStyle.plainSquared",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfield/tokenstyle-swift.enum/plainsquared"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/rounded": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rounded"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/rounded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTokenStyleRounded"
        }
      ],
      "role": "symbol",
      "title": "NSTokenField.TokenStyle.rounded",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfield/tokenstyle-swift.enum/rounded"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/squared": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "squared"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/squared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTokenStyleSquared"
        }
      ],
      "role": "symbol",
      "title": "NSTokenField.TokenStyle.squared",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfield/tokenstyle-swift.enum/squared"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCell/tokenStyle": {
      "abstract": [
        {
          "text": "The token style of the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTokenField",
          "text": "NSTokenField"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTokenStyle",
          "text": "TokenStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCell/tokenStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenStyle"
        }
      ],
      "role": "symbol",
      "title": "tokenStyle",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfieldcell/tokenstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:styleForRepresentedObject:)": {
      "abstract": [
        {
          "text": "Allows the delegate to return the token style for editing the specified represented object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tokenFieldCell"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTokenFieldCell",
          "text": "NSTokenFieldCell"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "styleForRepresentedObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTokenField",
          "text": "NSTokenField"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTokenStyle",
          "text": "TokenStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTokenFieldCellDelegate/tokenFieldCell(_:styleForRepresentedObject:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tokenFieldCell:styleForRepresentedObject:"
        }
      ],
      "role": "symbol",
      "title": "tokenFieldCell(_:styleForRepresentedObject:)",
      "type": "topic",
      "url": "/documentation/appkit/nstokenfieldcelldelegate/tokenfieldcell(_:styleforrepresentedobject:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/none",
        "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/plainSquared",
        "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/rounded",
        "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/squared"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTokenStyleDefault"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenStyleDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/none",
                "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/plainSquared",
                "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/rounded",
                "doc://com.apple.appkit/documentation/AppKit/NSTokenField/TokenStyle-swift.enum/squared"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSTokenStyleDefault"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1TokenStyle-swift.enum~1none/title",
          "value": "NSTokenStyleNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1TokenStyle-swift.enum~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenStyleNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1TokenStyle-swift.enum~1default/title",
          "value": "NSTokenStyleDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1TokenStyle-swift.enum~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenStyleDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:styleForRepresentedObject:)/title",
          "value": "tokenFieldCell:styleForRepresentedObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCellDelegate~1tokenFieldCell(_:styleForRepresentedObject:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tokenFieldCell:styleForRepresentedObject:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1TokenStyle-swift.enum/title",
          "value": "NSTokenStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1TokenStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1TokenStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1TokenStyle-swift.enum~1plainSquared/title",
          "value": "NSTokenStylePlainSquared"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1TokenStyle-swift.enum~1plainSquared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenStylePlainSquared"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCell~1tokenStyle/title",
          "value": "tokenStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenFieldCell~1tokenStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tokenStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField/title",
          "value": "NSTokenField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1TokenStyle-swift.enum~1rounded/title",
          "value": "NSTokenStyleRounded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1TokenStyle-swift.enum~1rounded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenStyleRounded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1TokenStyle-swift.enum~1squared/title",
          "value": "NSTokenStyleSquared"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTokenField~1TokenStyle-swift.enum~1squared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTokenStyleSquared"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstokenfield/tokenstyle-swift.enum/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstokenfield/tokenstyle-swift.enum/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
