{
  "abstract": [
    {
      "text": "Initializes and returns a newly allocated matrix of the specified size using cells of the given class.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSMatrix"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSMatrix/init(frame:mode:cellClass:numberOfRows:numberOfColumns:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSMatrix(im)initWithFrame:mode:cellClass:numberOfRows:numberOfColumns:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "frame"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSRect",
        "text": "NSRect"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "mode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSMatrix",
        "text": "NSMatrix"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSMatrixMode",
        "text": "Mode"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "cellClass"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s8AnyClassa",
        "text": "AnyClass"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "numberOfRows"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "numberOfColumns"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithFrame:mode:cellClass:numberOfRows:numberOfColumns:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(frame:mode:cellClass:numberOfRows:numberOfColumns:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "frame"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "frameRect"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRect",
              "text": "NSRect"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "mode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMatrix",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSMatrix",
              "text": "NSMatrix"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMatrix/Mode-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSMatrixMode",
              "text": "Mode"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "cellClass"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "factoryId"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s8AnyClassa",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s8AnyClassa",
              "text": "AnyClass"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "numberOfRows"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "rowsHigh"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "numberOfColumns"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "colsWide"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The matrix’s frame.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "frameRect"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The tracking mode for the matrix; this can be one of the modes described in ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMatrix/Mode-swift.enum",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "mode"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The class to use for any cells that the matrix creates and uses. This can be obtained by sending a ",
                  "type": "text"
                },
                {
                  "code": "class",
                  "type": "codeVoice"
                },
                {
                  "text": " message to the desired subclass of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "factoryId"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of rows in the matrix.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rowsHigh"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of columns in the matrix.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "colsWide"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The initialized instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMatrix",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is the designated initializer for matrices that add cells by creating instances of an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " subclass.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell": {
      "abstract": [
        {
          "text": "A mechanism for displaying text or images in a view object without the overhead of a full ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " subclass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCell"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCell"
        }
      ],
      "role": "symbol",
      "title": "NSCell",
      "type": "topic",
      "url": "/documentation/appkit/nscell"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMatrix": {
      "abstract": [
        {
          "text": "A legacy interface for grouping radio buttons or other types of cells together.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMatrix"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMatrix"
        }
      ],
      "role": "symbol",
      "title": "NSMatrix",
      "type": "topic",
      "url": "/documentation/appkit/nsmatrix"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMatrix/Mode-swift.enum": {
      "abstract": [
        {
          "text": "These constants determine how ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects behave when an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMatrix",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object is tracking the mouse.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Mode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMatrix/Mode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Mode"
        }
      ],
      "role": "symbol",
      "title": "NSMatrix.Mode",
      "type": "topic",
      "url": "/documentation/appkit/nsmatrix/mode-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMatrix/init(frame:)": {
      "abstract": [
        {
          "text": "Initializes a newly allocated matrix with the specified frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMatrix/init(frame:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFrame:"
        }
      ],
      "role": "symbol",
      "title": "init(frame:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmatrix/init(frame:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMatrix/init(frame:mode:cellClass:numberOfRows:numberOfColumns:)": {
      "abstract": [
        {
          "text": "Initializes and returns a newly allocated matrix of the specified size using cells of the given class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMatrix",
          "text": "NSMatrix"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSMatrixMode",
          "text": "Mode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cellClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "numberOfRows"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "numberOfColumns"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMatrix/init(frame:mode:cellClass:numberOfRows:numberOfColumns:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFrame:mode:cellClass:numberOfRows:numberOfColumns:"
        }
      ],
      "role": "symbol",
      "title": "init(frame:mode:cellClass:numberOfRows:numberOfColumns:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmatrix/init(frame:mode:cellclass:numberofrows:numberofcolumns:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMatrix/init(frame:mode:prototype:numberOfRows:numberOfColumns:)": {
      "abstract": [
        {
          "text": "Initializes and returns a newly allocated matrix of the specified size using the given cell as a prototype.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMatrix",
          "text": "NSMatrix"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSMatrixMode",
          "text": "Mode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "prototype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCell",
          "text": "NSCell"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "numberOfRows"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "numberOfColumns"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMatrix/init(frame:mode:prototype:numberOfRows:numberOfColumns:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFrame:mode:prototype:numberOfRows:numberOfColumns:"
        }
      ],
      "role": "symbol",
      "title": "init(frame:mode:prototype:numberOfRows:numberOfColumns:)",
      "type": "topic",
      "url": "/documentation/appkit/nsmatrix/init(frame:mode:prototype:numberofrows:numberofcolumns:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSRect": {
      "abstract": [
        {
          "text": "A rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRect",
      "type": "topic",
      "url": "/documentation/foundation/nsrect"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    },
    "doc://com.externally.resolved.symbol/s:s8AnyClassa": {
      "abstract": [
        {
          "text": "The protocol to which all class types implicitly conform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": " = any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9AnyObjecta",
          "text": "AnyObject"
        },
        {
          "kind": "text",
          "text": ".Type"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8AnyClassa",
      "kind": "symbol",
      "role": "symbol",
      "title": "AnyClass",
      "type": "topic",
      "url": "/documentation/Swift/AnyClass"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Initializing-an-NSMatrix-Object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSMatrix/init(frame:)",
        "doc://com.apple.appkit/documentation/AppKit/NSMatrix/init(frame:mode:prototype:numberOfRows:numberOfColumns:)"
      ],
      "title": "Initializing an NSMatrix Object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithFrame:mode:cellClass:numberOfRows:numberOfColumns:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFrame:mode:cellClass:numberOfRows:numberOfColumns:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSMatrix"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Initializing-an-NSMatrix-Object",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMatrix/init(frame:)",
                "doc://com.apple.appkit/documentation/AppKit/NSMatrix/init(frame:mode:prototype:numberOfRows:numberOfColumns:)"
              ],
              "title": "Initializing an NSMatrix Object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithFrame:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSRect",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSRect",
                    "text": "NSRect"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "frameRect"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "mode:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMatrix/Mode-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSMatrixMode",
                    "text": "NSMatrixMode"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "mode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "cellClass:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@Class",
                    "text": "Class"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "factoryId"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "numberOfRows:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "rowsHigh"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "numberOfColumns:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "colsWide"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The matrix’s frame.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "frameRect"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The tracking mode for the matrix; this can be one of the modes described in ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMatrix/Mode-swift.enum",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "mode"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The class to use for any cells that the matrix creates and uses. This can be obtained by sending a ",
                        "type": "text"
                      },
                      {
                        "code": "class",
                        "type": "codeVoice"
                      },
                      {
                        "text": " message to the desired subclass of ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "factoryId"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The number of rows in the matrix.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "rowsHigh"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The number of columns in the matrix.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "colsWide"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The initialized instance of ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMatrix",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMatrix~1init(frame:)/title",
          "value": "initWithFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMatrix~1init(frame:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMatrix~1init(frame:mode:cellClass:numberOfRows:numberOfColumns:)/title",
          "value": "initWithFrame:mode:cellClass:numberOfRows:numberOfColumns:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMatrix~1init(frame:mode:cellClass:numberOfRows:numberOfColumns:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFrame:mode:cellClass:numberOfRows:numberOfColumns:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMatrix~1init(frame:mode:prototype:numberOfRows:numberOfColumns:)/title",
          "value": "initWithFrame:mode:prototype:numberOfRows:numberOfColumns:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMatrix~1init(frame:mode:prototype:numberOfRows:numberOfColumns:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFrame:mode:prototype:numberOfRows:numberOfColumns:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMatrix~1Mode-swift.enum/title",
          "value": "NSMatrixMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMatrix~1Mode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMatrixMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMatrix~1Mode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMatrixMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/title",
          "value": "NSCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMatrix/title",
          "value": "NSMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSMatrix/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMatrix"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsmatrix/init(frame:mode:cellclass:numberofrows:numberofcolumns:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsmatrix/init(frame:mode:cellclass:numberofrows:numberofcolumns:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
