{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus/notDetermined"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "ImageCaptureCore",
    "externalID": "c:@ICAuthorizationStatusNotDetermined",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "notDetermined"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ICAuthorizationStatus",
        "text": "ICAuthorizationStatus"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICAuthorizationStatusNotDetermined"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "notDetermined"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "notDetermined"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ICAuthorizationStatus",
              "text": "ICAuthorizationStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "ICAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icauthorizationstatus"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus/authorized": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICAuthorizationStatus",
          "text": "ICAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus/authorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICAuthorizationStatusAuthorized"
        }
      ],
      "role": "symbol",
      "title": "authorized",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icauthorizationstatus/authorized"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus/denied": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICAuthorizationStatus",
          "text": "ICAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus/denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICAuthorizationStatusDenied"
        }
      ],
      "role": "symbol",
      "title": "denied",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icauthorizationstatus/denied"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus/notDetermined": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notDetermined"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICAuthorizationStatus",
          "text": "ICAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus/notDetermined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICAuthorizationStatusNotDetermined"
        }
      ],
      "role": "symbol",
      "title": "notDetermined",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icauthorizationstatus/notdetermined"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus/restricted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restricted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICAuthorizationStatus",
          "text": "ICAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus/restricted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICAuthorizationStatusRestricted"
        }
      ],
      "role": "symbol",
      "title": "restricted",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icauthorizationstatus/restricted"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraItemThumbnailOption/imageSourceShouldCache": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSourceShouldCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICCameraItemThumbnailOption",
          "text": "ICCameraItemThumbnailOption"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraItemThumbnailOption/imageSourceShouldCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICImageSourceShouldCache"
        }
      ],
      "role": "symbol",
      "title": "imageSourceShouldCache",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameraitemthumbnailoption/imagesourceshouldcache"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraItemThumbnailOption/imageSourceThumbnailMaxPixelSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSourceThumbnailMaxPixelSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICCameraItemThumbnailOption",
          "text": "ICCameraItemThumbnailOption"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraItemThumbnailOption/imageSourceThumbnailMaxPixelSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICImageSourceThumbnailMaxPixelSize"
        }
      ],
      "role": "symbol",
      "title": "imageSourceThumbnailMaxPixelSize",
      "type": "topic",
      "url": "/documentation/imagecapturecore/iccameraitemthumbnailoption/imagesourcethumbnailmaxpixelsize"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceSupportsHEIF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraDeviceSupportsHEIF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceCapability",
          "text": "ICDeviceCapability"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceSupportsHEIF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICCameraDeviceSupportsHEIF"
        }
      ],
      "role": "symbol",
      "title": "cameraDeviceSupportsHEIF",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicecapability/cameradevicesupportsheif"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceStatus/localizedStatusNotificationKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedStatusNotificationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceStatus",
          "text": "ICDeviceStatus"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceStatus/localizedStatusNotificationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICLocalizedStatusNotificationKey"
        }
      ],
      "role": "symbol",
      "title": "localizedStatusNotificationKey",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicestatus/localizedstatusnotificationkey"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceStatus/statusCodeKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusCodeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceStatus",
          "text": "ICDeviceStatus"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceStatus/statusCodeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICStatusCodeKey"
        }
      ],
      "role": "symbol",
      "title": "statusCodeKey",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicestatus/statuscodekey"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceStatus/statusNotificationKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusNotificationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceStatus",
          "text": "ICDeviceStatus"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceStatus/statusNotificationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICStatusNotificationKey"
        }
      ],
      "role": "symbol",
      "title": "statusNotificationKey",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicestatus/statusnotificationkey"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeBluetooth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transportTypeBluetooth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceTransport",
          "text": "ICDeviceTransport"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeBluetooth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICTransportTypeBluetooth"
        }
      ],
      "role": "symbol",
      "title": "transportTypeBluetooth",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicetransport/transporttypebluetooth"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeExFAT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transportTypeExFAT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceTransport",
          "text": "ICDeviceTransport"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeExFAT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICTransportTypeExFAT"
        }
      ],
      "role": "symbol",
      "title": "transportTypeExFAT",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicetransport/transporttypeexfat"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeFireWire": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transportTypeFireWire"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceTransport",
          "text": "ICDeviceTransport"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeFireWire",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICTransportTypeFireWire"
        }
      ],
      "role": "symbol",
      "title": "transportTypeFireWire",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicetransport/transporttypefirewire"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeMassStorage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transportTypeMassStorage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceTransport",
          "text": "ICDeviceTransport"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeMassStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICTransportTypeMassStorage"
        }
      ],
      "role": "symbol",
      "title": "transportTypeMassStorage",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicetransport/transporttypemassstorage"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeProximity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transportTypeProximity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ICDeviceTransport",
          "text": "ICDeviceTransport"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeProximity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICTransportTypeProximity"
        }
      ],
      "role": "symbol",
      "title": "transportTypeProximity",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icdevicetransport/transporttypeproximity"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICErrorDomain": {
      "abstract": [
        {
          "text": "An error returned by the ImageCaptureCore framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "ICErrorDomain",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icerrordomain"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus/authorized",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus/denied",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus/restricted",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraItemThumbnailOption/imageSourceShouldCache",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraItemThumbnailOption/imageSourceThumbnailMaxPixelSize",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceSupportsHEIF",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICErrorDomain",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceStatus/localizedStatusNotificationKey",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceStatus/statusCodeKey",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceStatus/statusNotificationKey",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeBluetooth",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeExFAT",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeFireWire",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeMassStorage",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeProximity"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICAuthorizationStatusNotDetermined"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICAuthorizationStatusNotDetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus/authorized",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus/denied",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus/restricted",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraItemThumbnailOption/imageSourceShouldCache",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICCameraItemThumbnailOption/imageSourceThumbnailMaxPixelSize",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceCapability/cameraDeviceSupportsHEIF",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICErrorDomain",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceStatus/localizedStatusNotificationKey",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceStatus/statusCodeKey",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceStatus/statusNotificationKey",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeBluetooth",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeExFAT",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeFireWire",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeMassStorage",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICDeviceTransport/transportTypeProximity"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICAuthorizationStatus",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ICAuthorizationStatus",
                    "text": "ICAuthorizationStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ICAuthorizationStatusNotDetermined"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceTransport~1transportTypeBluetooth/title",
          "value": "ICTransportTypeBluetooth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceTransport~1transportTypeBluetooth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICTransportTypeBluetooth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceTransport~1transportTypeFireWire/title",
          "value": "ICTransportTypeFireWire"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceTransport~1transportTypeFireWire/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICTransportTypeFireWire"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceTransport~1transportTypeProximity/title",
          "value": "ICTransportTypeProximity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceTransport~1transportTypeProximity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICTransportTypeProximity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceTransport~1transportTypeMassStorage/title",
          "value": "ICTransportTypeMassStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceTransport~1transportTypeMassStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICTransportTypeMassStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICAuthorizationStatus~1restricted/title",
          "value": "ICAuthorizationStatusRestricted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICAuthorizationStatus~1restricted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICAuthorizationStatusRestricted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICAuthorizationStatus/title",
          "value": "ICAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceStatus~1statusCodeKey/title",
          "value": "ICStatusCodeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceStatus~1statusCodeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICStatusCodeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraItemThumbnailOption~1imageSourceThumbnailMaxPixelSize/title",
          "value": "ICImageSourceThumbnailMaxPixelSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraItemThumbnailOption~1imageSourceThumbnailMaxPixelSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICImageSourceThumbnailMaxPixelSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICAuthorizationStatus~1notDetermined/title",
          "value": "ICAuthorizationStatusNotDetermined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICAuthorizationStatus~1notDetermined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICAuthorizationStatusNotDetermined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICAuthorizationStatus~1authorized/title",
          "value": "ICAuthorizationStatusAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICAuthorizationStatus~1authorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICAuthorizationStatusAuthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1cameraDeviceSupportsHEIF/title",
          "value": "ICCameraDeviceSupportsHEIF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceCapability~1cameraDeviceSupportsHEIF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICCameraDeviceSupportsHEIF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICAuthorizationStatus~1denied/title",
          "value": "ICAuthorizationStatusDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICAuthorizationStatus~1denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICAuthorizationStatusDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICErrorDomain/title",
          "value": "ICErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraItemThumbnailOption~1imageSourceShouldCache/title",
          "value": "ICImageSourceShouldCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICCameraItemThumbnailOption~1imageSourceShouldCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICImageSourceShouldCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceStatus~1localizedStatusNotificationKey/title",
          "value": "ICLocalizedStatusNotificationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceStatus~1localizedStatusNotificationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICLocalizedStatusNotificationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceStatus~1statusNotificationKey/title",
          "value": "ICStatusNotificationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceStatus~1statusNotificationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICStatusNotificationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceTransport~1transportTypeExFAT/title",
          "value": "ICTransportTypeExFAT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICDeviceTransport~1transportTypeExFAT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICTransportTypeExFAT"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icauthorizationstatus/notdetermined"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icauthorizationstatus/notdetermined"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
