{
  "abstract": [
    {
      "text": "Exceptions thrown by the ",
      "type": "text"
    },
    {
      "code": "SFAuthorizationPluginView",
      "type": "codeVoice"
    },
    {
      "text": " class",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.securityinterface/documentation/SecurityInterface",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.securityinterface/documentation/SecurityInterface/exceptions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security Interface"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Exceptions"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface": {
      "abstract": [
        {
          "text": "Provide user interface elements for security features such as authorization, access to digital certificates, and access to items in keychains.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface",
      "kind": "symbol",
      "role": "collection",
      "title": "Security Interface",
      "type": "topic",
      "url": "/documentation/securityinterface"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView": {
      "abstract": [
        {
          "text": "Allows authorization plug-in developers to create a custom view their plug-in can display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFAuthorizationPluginView"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationPluginView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFAuthorizationPluginView"
        }
      ],
      "role": "symbol",
      "title": "SFAuthorizationPluginView",
      "type": "topic",
      "url": "/documentation/securityinterface/sfauthorizationpluginview"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonType": {
      "abstract": [
        {
          "text": "These constants define the button types used by authorization plug-ins.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFButtonType"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFButtonType"
        }
      ],
      "role": "symbol",
      "title": "SFButtonType",
      "type": "topic",
      "url": "/documentation/securityinterface/sfbuttontype"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFDisplayViewException": {
      "abstract": [
        {
          "text": "Raised when an error occurs in displaying the authorization dialog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFDisplayViewException"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFDisplayViewException",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFDisplayViewException"
        }
      ],
      "role": "symbol",
      "title": "SFDisplayViewException",
      "type": "topic",
      "url": "/documentation/securityinterface/sfdisplayviewexception"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFViewType": {
      "abstract": [
        {
          "text": "These constants define the view type requested by the authorization plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFViewType"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFViewType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFViewType"
        }
      ],
      "role": "symbol",
      "title": "SFViewType",
      "type": "topic",
      "url": "/documentation/securityinterface/sfviewtype"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonType",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFViewType"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFDisplayViewException"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFDisplayViewException"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonType",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFViewType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationPluginView/title",
          "value": "SFAuthorizationPluginView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationPluginView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorizationPluginView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationPluginView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorizationPluginView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFDisplayViewException/title",
          "value": "SFDisplayViewException"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFDisplayViewException/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFDisplayViewException"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonType/title",
          "value": "SFButtonType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFViewType/title",
          "value": "SFViewType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFViewType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFViewType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFViewType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFViewType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/securityinterface/exceptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/securityinterface/exceptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
