{
  "abstract": [
    {
      "text": "Data types found in the Security Interface framework.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.securityinterface/documentation/SecurityInterface"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Security Interface"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "SecurityInterface Data Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface": {
      "abstract": [
        {
          "text": "Provide user interface elements for security features such as authorization, access to digital certificates, and access to items in keychains.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface",
      "kind": "symbol",
      "role": "collection",
      "title": "Security Interface",
      "type": "topic",
      "url": "/documentation/securityinterface"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationViewState": {
      "abstract": [
        {
          "text": "Defines the current state of the authorization view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFAuthorizationViewState"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationViewState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFAuthorizationViewState"
        }
      ],
      "role": "symbol",
      "title": "SFAuthorizationViewState",
      "type": "topic",
      "url": "/documentation/securityinterface/sfauthorizationviewstate"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonType": {
      "abstract": [
        {
          "text": "These constants define the button types used by authorization plug-ins.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFButtonType"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFButtonType"
        }
      ],
      "role": "symbol",
      "title": "SFButtonType",
      "type": "topic",
      "url": "/documentation/securityinterface/sfbuttontype"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFViewType": {
      "abstract": [
        {
          "text": "These constants define the view type requested by the authorization plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFViewType"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFViewType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFViewType"
        }
      ],
      "role": "symbol",
      "title": "SFViewType",
      "type": "topic",
      "url": "/documentation/securityinterface/sfviewtype"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-constants": {
      "abstract": [
        {
          "text": "Constants in the SecurityInterface framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SecurityInterface Constants",
      "type": "topic",
      "url": "/documentation/securityinterface/securityinterface-constants"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SecurityInterface Enumerations",
      "type": "topic",
      "url": "/documentation/securityinterface/securityinterface-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationViewState",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonType",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFViewType",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-constants",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-enumerations"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationViewState"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationViewState"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFAuthorizationViewState",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonType",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFViewType",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-constants",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/securityinterface-enumerations"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonType/title",
          "value": "SFButtonType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationViewState/title",
          "value": "SFAuthorizationViewState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationViewState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorizationViewState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFAuthorizationViewState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFAuthorizationViewState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFViewType/title",
          "value": "SFViewType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFViewType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFViewType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFViewType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFViewType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/securityinterface/securityinterface-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/securityinterface/securityinterface-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
