{
  "abstract": [
    {
      "text": "Indicates the Cancel button was pressed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.securityinterface/documentation/SecurityInterface"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonTypeCancel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@SFButtonType@SFButtonTypeCancel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SFButtonTypeCancel"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@SFButtonType",
        "text": "SFButtonType"
      }
    ],
    "modules": [
      {
        "name": "Security Interface"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SFButtonTypeCancel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "SFButtonTypeCancel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SFButtonTypeCancel"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@SFButtonType",
              "text": "SFButtonType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface": {
      "abstract": [
        {
          "text": "Provide user interface elements for security features such as authorization, access to digital certificates, and access to items in keychains.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface",
      "kind": "symbol",
      "role": "collection",
      "title": "Security Interface",
      "type": "topic",
      "url": "/documentation/securityinterface"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonType": {
      "abstract": [
        {
          "text": "These constants define the button types used by authorization plug-ins.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFButtonType"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFButtonType"
        }
      ],
      "role": "symbol",
      "title": "SFButtonType",
      "type": "topic",
      "url": "/documentation/securityinterface/sfbuttontype"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonTypeBack": {
      "abstract": [
        {
          "text": "Indicates the Back button was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFButtonTypeBack"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SFButtonType",
          "text": "SFButtonType"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonTypeBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFButtonTypeBack"
        }
      ],
      "role": "symbol",
      "title": "SFButtonTypeBack",
      "type": "topic",
      "url": "/documentation/securityinterface/sfbuttontypeback"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonTypeCancel": {
      "abstract": [
        {
          "text": "Indicates the Cancel button was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFButtonTypeCancel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SFButtonType",
          "text": "SFButtonType"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonTypeCancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFButtonTypeCancel"
        }
      ],
      "role": "symbol",
      "title": "SFButtonTypeCancel",
      "type": "topic",
      "url": "/documentation/securityinterface/sfbuttontypecancel"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonTypeLogin": {
      "abstract": [
        {
          "text": "Indicates the Login button was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFButtonTypeLogin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SFButtonType",
          "text": "SFButtonType"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonTypeLogin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFButtonTypeLogin"
        }
      ],
      "role": "symbol",
      "title": "SFButtonTypeLogin",
      "type": "topic",
      "url": "/documentation/securityinterface/sfbuttontypelogin"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonTypeOK": {
      "abstract": [
        {
          "text": "Indicates the OK button was pressed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFButtonTypeOK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@SFButtonType",
          "text": "SFButtonType"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonTypeOK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFButtonTypeOK"
        }
      ],
      "role": "symbol",
      "title": "SFButtonTypeOK",
      "type": "topic",
      "url": "/documentation/securityinterface/sfbuttontypeok"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonTypeOK",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonTypeBack",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonTypeLogin"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SFButtonTypeCancel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFButtonTypeCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.securityinterface/documentation/SecurityInterface",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonTypeOK",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonTypeBack",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFButtonTypeLogin"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SFButtonTypeCancel"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonType/title",
          "value": "SFButtonType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonTypeOK/title",
          "value": "SFButtonTypeOK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonTypeOK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFButtonTypeOK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonTypeBack/title",
          "value": "SFButtonTypeBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonTypeBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFButtonTypeBack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonTypeCancel/title",
          "value": "SFButtonTypeCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonTypeCancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFButtonTypeCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonTypeLogin/title",
          "value": "SFButtonTypeLogin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFButtonTypeLogin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFButtonTypeLogin"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/securityinterface/sfbuttontypecancel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/securityinterface/sfbuttontypecancel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
