{
  "abstract": [
    {
      "text": "Stores an object in the record using the specified key.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/setObject:forKeyedSubscript:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CKRecordKeyValueSetting(im)setObject:forKeyedSubscript:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "setObject:forKeyedSubscript:"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setObject:forKeyedSubscript:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setObject:forKeyedSubscript:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "setObject:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Qoobjc(pl)CKRecordValue",
              "text": "id<CKRecordValue>"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "object"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "forKeyedSubscript:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordFieldKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CKRecordFieldKey",
              "text": "CKRecordFieldKey"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "key"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The object to store using the specified key. It must be one of the data types in ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord#Supported-Data-Types",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". You receive an error if you use a data type that CloudKit doesn’t support. If you specify ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": ", CloudKit removes any object that the record associates with the key.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "object"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The key to associate with ",
                  "type": "text"
                },
                {
                  "code": "object",
                  "type": "codeVoice"
                },
                {
                  "text": ". Use this key to retrieve the value later. A key must consist of one or more alphanumeric characters and must start with a letter. CloudKit permits the use of underscores, but not spaces. Avoid using a key that matches the name of any property of ",
                  "type": "text"
                },
                {
                  "code": "CKRecord",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "key"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord#Supported-Data-Types": {
      "abstract": [],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecord#Supported-Data-Types",
      "kind": "section",
      "title": "Supported Data Types",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecord#Supported-Data-Types"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordFieldKey": {
      "abstract": [
        {
          "text": "A data type that CloudKit requires for record field names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CKRecordFieldKey"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordFieldKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKRecordFieldKey",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordfieldkey"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting": {
      "abstract": [
        {
          "text": "A protocol for managing the key-value pairs of a CloudKit record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKRecordKeyValueSetting"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKRecordKeyValueSetting"
        }
      ],
      "role": "symbol",
      "title": "CKRecordKeyValueSetting",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordkeyvaluesetting"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/allKeys()": {
      "abstract": [
        {
          "text": "Returns an array of the record’s keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allKeys"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/allKeys()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allKeys"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "allKeys()",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordkeyvaluesetting/allkeys()"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/changedKeys()": {
      "abstract": [
        {
          "text": "Returns an array of keys with recent changes to their values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changedKeys"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/changedKeys()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changedKeys"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "changedKeys()",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordkeyvaluesetting/changedkeys()"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/object(forKey:)": {
      "abstract": [
        {
          "text": "Returns the object that the record stores for the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "object"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CKRecordObjCValue"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/object(forKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForKey:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "object(forKey:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordkeyvaluesetting/object(forkey:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/setObject(_:forKey:)": {
      "abstract": [
        {
          "text": "Stores an object in the record using the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setObject"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CKRecordObjCValue"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "forKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/setObject(_:forKey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setObject:forKey:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setObject(_:forKey:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordkeyvaluesetting/setobject(_:forkey:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/setObject:forKeyedSubscript:": {
      "abstract": [
        {
          "text": "Stores an object in the record using the specified key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setObject:forKeyedSubscript:"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/setObject:forKeyedSubscript:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setObject:forKeyedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "setObject:forKeyedSubscript:",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordkeyvaluesetting/setobject:forkeyedsubscript:"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/subscript(_:)": {
      "abstract": [
        {
          "text": "Returns the object that the record stores for the specified key.",
          "type": "text"
        }
      ],
      "defaultImplementations": 2,
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CKRecordObjCValue"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/subscript(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForKeyedSubscript:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckrecordkeyvaluesetting/subscript(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-a-Records-Fields",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/object(forKey:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/subscript(_:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/setObject(_:forKey:)",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/allKeys()",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKRecordKeyValueSetting/changedKeys()"
      ],
      "title": "Accessing a Record’s Fields"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1allKeys()/title",
          "value": "allKeys"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1allKeys()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "allKeys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1object(forKey:)/title",
          "value": "objectForKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1object(forKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectForKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting/title",
          "value": "CKRecordKeyValueSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordKeyValueSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKRecordKeyValueSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1changedKeys()/title",
          "value": "changedKeys"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1changedKeys()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "changedKeys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1setObject(_:forKey:)/title",
          "value": "setObject:forKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1setObject(_:forKey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setObject:forKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1subscript(_:)/title",
          "value": "objectForKeyedSubscript:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKRecordKeyValueSetting~1subscript(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectForKeyedSubscript:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckrecordkeyvaluesetting/setobject:forkeyedsubscript:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
