{
  "abstract": [
    {
      "text": "The type of the element.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xctest/documentation/XCTest",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/elementType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)XCUIElementAttributes(py)elementType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "elementType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)XCUIElement",
        "text": "XCUIElement"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@XCUIElementType",
        "text": "ElementType"
      }
    ],
    "modules": [
      {
        "name": "XCTest"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "elementType"
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "elementType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "elementType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)XCUIElement",
              "text": "XCUIElement"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/ElementType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@XCUIElementType",
              "text": "ElementType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xctest/documentation/XCTest": {
      "abstract": [
        {
          "text": "Create and run unit tests, performance tests, and UI tests for your Xcode project.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest",
      "kind": "symbol",
      "role": "collection",
      "title": "XCTest",
      "type": "topic",
      "url": "/documentation/xctest"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement": {
      "abstract": [
        {
          "text": "A UI element in an application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElement/ElementType": {
      "abstract": [
        {
          "text": "The types of UI element that you find, inspect, and interact with in a UI test.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/ElementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement.ElementType",
      "type": "topic",
      "url": "/documentation/xctest/xcuielement/elementtype"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes": {
      "abstract": [
        {
          "text": "Attributes exposed by UI elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElementAttributes"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElementAttributes"
        }
      ],
      "role": "symbol",
      "title": "XCUIElementAttributes",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/elementType": {
      "abstract": [
        {
          "text": "The type of the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elementType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIElementType",
          "text": "ElementType"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/elementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "elementType"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "elementType",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes/elementtype"
    },
    "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/identifier": {
      "abstract": [
        {
          "text": "The element’s accessibility identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/xctest/xcuielementattributes/identifier"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identity",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/identifier",
        "doc://com.apple.xctest/documentation/XCTest/XCUIElement/ElementType"
      ],
      "title": "Identity"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "elementType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "elementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xctest/documentation/XCTest",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Identity",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xctest/documentation/XCTest/XCUIElementAttributes/identifier",
                "doc://com.apple.xctest/documentation/XCTest/XCUIElement/ElementType"
              ],
              "title": "Identity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.xctest/documentation/XCTest/XCUIElement/ElementType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@XCUIElementType",
                    "text": "XCUIElementType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "elementType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/title",
          "value": "XCUIElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1ElementType/title",
          "value": "XCUIElementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1ElementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElement~1ElementType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1elementType/title",
          "value": "elementType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes~1elementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "elementType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes/title",
          "value": "XCUIElementAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xctest~1documentation~1XCTest~1XCUIElementAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElementAttributes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xctest/xcuielementattributes/elementtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xctest/xcuielementattributes/elementtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
