{
  "abstract": [
    {
      "text": "Requests the action to update its user interface from its stored parameters, which have changed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.automator/documentation/Automator",
        "doc://com.apple.automator/documentation/Automator/AMAction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.automator/documentation/Automator/AMAction/parametersUpdated()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AMAction(im)parametersUpdated",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "parametersUpdated"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "Automator"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "parametersUpdated"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "parametersUpdated()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "parametersUpdated"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.automator/documentation/Automator": {
      "abstract": [
        {
          "text": "Develop actions that the Automator app can load and run. View, edit, and run Automator workflows in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator",
      "kind": "symbol",
      "role": "collection",
      "title": "Automator",
      "type": "topic",
      "url": "/documentation/automator"
    },
    "doc://com.apple.automator/documentation/Automator/AMAction": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface and general characteristics of Automator actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMAction"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMAction"
        }
      ],
      "role": "symbol",
      "title": "AMAction",
      "type": "topic",
      "url": "/documentation/automator/amaction"
    },
    "doc://com.apple.automator/documentation/Automator/AMAction/parametersUpdated()": {
      "abstract": [
        {
          "text": "Requests the action to update its user interface from its stored parameters, which have changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parametersUpdated"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMAction/parametersUpdated()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parametersUpdated"
        }
      ],
      "role": "symbol",
      "title": "parametersUpdated()",
      "type": "topic",
      "url": "/documentation/automator/amaction/parametersupdated()"
    },
    "doc://com.apple.automator/documentation/Automator/AMAction/updateParameters()": {
      "abstract": [
        {
          "text": "Requests the action to update its stored set of parameters from the settings in the action’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateParameters"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMAction/updateParameters()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateParameters"
        }
      ],
      "role": "symbol",
      "title": "updateParameters()",
      "type": "topic",
      "url": "/documentation/automator/amaction/updateparameters()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Updating-Action-Parameters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMAction/updateParameters()"
      ],
      "title": "Updating Action Parameters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "parametersUpdated"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "parametersUpdated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.automator/documentation/Automator",
                "doc://com.apple.automator/documentation/Automator/AMAction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Updating-Action-Parameters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMAction/updateParameters()"
              ],
              "title": "Updating Action Parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "parametersUpdated"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction/title",
          "value": "AMAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1parametersUpdated()/title",
          "value": "parametersUpdated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1parametersUpdated()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "parametersUpdated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1updateParameters()/title",
          "value": "updateParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1updateParameters()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateParameters"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/automator/amaction/parametersupdated()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/automator/amaction/parametersupdated()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
