{
  "abstract": [
    {
      "text": "Requests the action to perform its task using the specified input.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.automator/documentation/Automator",
        "doc://com.apple.automator/documentation/Automator/AMAction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.automator/documentation/Automator/AMAction/run(withInput:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AMAction(im)runWithInput:error:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "run"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "withInput"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "?) "
      },
      {
        "kind": "keyword",
        "text": "throws"
      },
      {
        "kind": "text",
        "text": " -> "
      },
      {
        "kind": "keyword",
        "text": "Any"
      }
    ],
    "modules": [
      {
        "name": "Automator"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "runWithInput:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "run(withInput:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "run"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "withInput"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "input"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "?) "
            },
            {
              "kind": "keyword",
              "text": "throws"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "kind": "keyword",
              "text": "Any"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The input for the receiving action. Should contain one or more objects compatible with one of the types specified in the action’s ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.automator/documentation/Automator/AMAction/selectedInputType",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "input"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsarray",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that contains one or more objects of a data type compatible with a type specified in the receiving action’s ",
              "type": "text"
            },
            {
              "code": "AMProvides",
              "type": "codeVoice"
            },
            {
              "text": " property. If the action doesn’t modify the data passed in ",
              "type": "text"
            },
            {
              "code": "input",
              "type": "codeVoice"
            },
            {
              "text": ", it should return it unchanged. If the action doesn’t have any data to provide, it should return an empty ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsarray",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is intended to be overridden.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The input and output objects for actions are usually instances of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsarray",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If the action encounters problems, it should return by indirection an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that describes the error.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.automator/documentation/Automator": {
      "abstract": [
        {
          "text": "Develop actions that the Automator app can load and run. View, edit, and run Automator workflows in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator",
      "kind": "symbol",
      "role": "collection",
      "title": "Automator",
      "type": "topic",
      "url": "/documentation/automator"
    },
    "doc://com.apple.automator/documentation/Automator/AMAction": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface and general characteristics of Automator actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMAction"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMAction"
        }
      ],
      "role": "symbol",
      "title": "AMAction",
      "type": "topic",
      "url": "/documentation/automator/amaction"
    },
    "doc://com.apple.automator/documentation/Automator/AMAction/finishRunningWithError(_:)": {
      "abstract": [
        {
          "text": "Causes the action to stop running and return an error, which, in turn, causes the workflow to stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishRunningWithError"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMAction/finishRunningWithError(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishRunningWithError:"
        }
      ],
      "role": "symbol",
      "title": "finishRunningWithError(_:)",
      "type": "topic",
      "url": "/documentation/automator/amaction/finishrunningwitherror(_:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMAction/reset()": {
      "abstract": [
        {
          "text": "Resets the action to its initial state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reset"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMAction/reset()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reset"
        }
      ],
      "role": "symbol",
      "title": "reset()",
      "type": "topic",
      "url": "/documentation/automator/amaction/reset()"
    },
    "doc://com.apple.automator/documentation/Automator/AMAction/run(withInput:)": {
      "abstract": [
        {
          "text": "Requests the action to perform its task using the specified input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "run"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withInput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMAction/run(withInput:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runWithInput:error:"
        }
      ],
      "role": "symbol",
      "title": "run(withInput:)",
      "type": "topic",
      "url": "/documentation/automator/amaction/run(withinput:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMAction/runAsynchronously(withInput:)": {
      "abstract": [
        {
          "text": "Causes Automator to wait for notification that the action has completed execution, which allows the action to perform an asynchronous operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runAsynchronously"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withInput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMAction/runAsynchronously(withInput:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runAsynchronouslyWithInput:"
        }
      ],
      "role": "symbol",
      "title": "runAsynchronously(withInput:)",
      "type": "topic",
      "url": "/documentation/automator/amaction/runasynchronously(withinput:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMAction/selectedInputType": {
      "abstract": [
        {
          "text": "The type of input, in UTI format, of the input received by the action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedInputType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMAction/selectedInputType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedInputType"
        }
      ],
      "role": "symbol",
      "title": "selectedInputType",
      "type": "topic",
      "url": "/documentation/automator/amaction/selectedinputtype"
    },
    "doc://com.apple.automator/documentation/Automator/AMAction/stop()": {
      "abstract": [
        {
          "text": "Stops the action from running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stop"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMAction/stop()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stop"
        }
      ],
      "role": "symbol",
      "title": "stop()",
      "type": "topic",
      "url": "/documentation/automator/amaction/stop()"
    },
    "doc://com.apple.automator/documentation/Automator/AMAction/willFinishRunning()": {
      "abstract": [
        {
          "text": "Provides an opportunity for an action to perform cleanup operations, such as closing windows and deallocating memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willFinishRunning"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMAction/willFinishRunning()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "willFinishRunning"
        }
      ],
      "role": "symbol",
      "title": "willFinishRunning()",
      "type": "topic",
      "url": "/documentation/automator/amaction/willfinishrunning()"
    },
    "doc://com.apple.documentation/documentation/foundation/nsarray": {
      "abstract": [
        {
          "text": "An object representing a static ordered collection, for use instead of an  constant in cases that require reference semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSArray"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsarray",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSArray",
      "type": "topic",
      "url": "/documentation/foundation/nsarray"
    },
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/foundation/nserror/1411580-userinfo": {
      "abstract": [
        {
          "text": "The user info dictionary. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": [String : Any]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror/1411580-userinfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/foundation/nserror/1411580-userinfo"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/foundation/nsstring": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Controlling-the-Action",
      "generated": true,
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMAction/runAsynchronously(withInput:)",
        "doc://com.apple.automator/documentation/Automator/AMAction/finishRunningWithError(_:)",
        "doc://com.apple.automator/documentation/Automator/AMAction/willFinishRunning()",
        "doc://com.apple.automator/documentation/Automator/AMAction/stop()",
        "doc://com.apple.automator/documentation/Automator/AMAction/reset()"
      ],
      "title": "Controlling the Action"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "runWithInput:error:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runWithInput:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.automator/documentation/Automator",
                "doc://com.apple.automator/documentation/Automator/AMAction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Controlling-the-Action",
              "generated": true,
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMAction/runAsynchronously(withInput:)",
                "doc://com.apple.automator/documentation/Automator/AMAction/finishRunningWithError(_:)",
                "doc://com.apple.automator/documentation/Automator/AMAction/willFinishRunning()",
                "doc://com.apple.automator/documentation/Automator/AMAction/stop()",
                "doc://com.apple.automator/documentation/Automator/AMAction/reset()"
              ],
              "title": "Controlling the Action"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "runWithInput:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "input"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "error:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The input for the receiving action. Should contain one or more objects compatible with one of the types specified in the action’s ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.automator/documentation/Automator/AMAction/selectedInputType",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " property.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "input"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "If an error occurs, the action returns an ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " object in this parameter. For actions running AppleScript code, the following keys may be specified in the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/foundation/nserror/1411580-userinfo",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " property of ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ":",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "code": "OSAScriptErrorNumberKey",
                                "type": "codeVoice"
                              },
                              {
                                "text": " (a string constant) — The value for this key is an instance of ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " whose integer value indicates an error code.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      },
                      {
                        "content": [
                          {
                            "inlineContent": [
                              {
                                "code": "OSAScriptErrorMessageKey",
                                "type": "codeVoice"
                              },
                              {
                                "text": " (a string constant) — The value for this key is an instance of ",
                                "type": "text"
                              },
                              {
                                "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
                                "isActive": true,
                                "type": "reference"
                              },
                              {
                                "text": " describing the error.",
                                "type": "text"
                              }
                            ],
                            "type": "paragraph"
                          }
                        ]
                      }
                    ],
                    "type": "unorderedList"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/foundation/nsarray",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " object that contains one or more objects of a data type compatible with a type specified in the receiving action’s ",
                    "type": "text"
                  },
                  {
                    "code": "AMProvides",
                    "type": "codeVoice"
                  },
                  {
                    "text": " property. If the action doesn’t modify the data passed in ",
                    "type": "text"
                  },
                  {
                    "code": "input",
                    "type": "codeVoice"
                  },
                  {
                    "text": ", it should return it unchanged. If the action doesn’t have any data to provide, it should return an empty ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/foundation/nsarray",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " object.",
                    "type": "text"
                  },
                  {
                    "text": " On failure, this method returns ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1finishRunningWithError(_:)/title",
          "value": "finishRunningWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1finishRunningWithError(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishRunningWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction/title",
          "value": "AMAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1willFinishRunning()/title",
          "value": "willFinishRunning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1willFinishRunning()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "willFinishRunning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1run(withInput:)/title",
          "value": "runWithInput:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1run(withInput:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runWithInput:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsstring/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1selectedInputType/title",
          "value": "selectedInputType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1selectedInputType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedInputType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsarray/abstract",
          "value": [
            {
              "text": "A static ordered collection of objects.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1runAsynchronously(withInput:)/title",
          "value": "runAsynchronouslyWithInput:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1runAsynchronously(withInput:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runAsynchronouslyWithInput:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1reset()/title",
          "value": "reset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1reset()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1stop()/title",
          "value": "stop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAction~1stop()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stop"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/automator/amaction/run(withinput:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/automator/amaction/run(withinput:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
