{
  "abstract": [
    {
      "text": "A layout guide for placing content of a particular aspect ratio.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIWindow"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIWindow/safeAreaAspectFitLayoutGuide"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:objc(cs)UIWindow(py)safeAreaAspectFitLayoutGuide",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "safeAreaAspectFitLayoutGuide"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UILayoutGuide",
        "text": "UILayoutGuide"
      },
      {
        "kind": "text",
        "text": " & "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)UILayoutGuideAspectFitting",
        "text": "UILayoutGuideAspectFitting"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "safeAreaAspectFitLayoutGuide"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "safeAreaAspectFitLayoutGuide"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "safeAreaAspectFitLayoutGuide"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UILayoutGuide",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UILayoutGuide",
              "text": "UILayoutGuide"
            },
            {
              "kind": "text",
              "text": " & "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UILayoutGuideAspectFitting",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UILayoutGuideAspectFitting",
              "text": "UILayoutGuideAspectFitting"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This layout guide provides a centered region in the window where you can place media content of a particular aspect ratio (width over height) to avoid obscuring the content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Use this layout guide for full-screen content. Avoid adding constraints to the guide through deeply nested view hierarchies.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILayoutGuide": {
      "abstract": [
        {
          "text": "A rectangular area that can interact with Auto Layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UILayoutGuide"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILayoutGuide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILayoutGuide"
        }
      ],
      "role": "symbol",
      "title": "UILayoutGuide",
      "type": "topic",
      "url": "/documentation/uikit/uilayoutguide"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILayoutGuideAspectFitting": {
      "abstract": [
        {
          "text": "The interface for a layout guide that supports a particular aspect ratio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UILayoutGuideAspectFitting"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILayoutGuideAspectFitting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILayoutGuideAspectFitting"
        }
      ],
      "role": "symbol",
      "title": "UILayoutGuideAspectFitting",
      "type": "topic",
      "url": "/documentation/uikit/uilayoutguideaspectfitting"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindow": {
      "abstract": [
        {
          "text": "The backdrop for your app’s user interface and the object that dispatches events to your views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindow"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindow"
        }
      ],
      "role": "symbol",
      "title": "UIWindow",
      "type": "topic",
      "url": "/documentation/uikit/uiwindow"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindow/safeAreaAspectFitLayoutGuide": {
      "abstract": [
        {
          "text": "A layout guide for placing content of a particular aspect ratio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "safeAreaAspectFitLayoutGuide"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UILayoutGuide",
          "text": "UILayoutGuide"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UILayoutGuideAspectFitting",
          "text": "UILayoutGuideAspectFitting"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindow/safeAreaAspectFitLayoutGuide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "safeAreaAspectFitLayoutGuide"
        }
      ],
      "role": "symbol",
      "title": "safeAreaAspectFitLayoutGuide",
      "type": "topic",
      "url": "/documentation/uikit/uiwindow/safeareaaspectfitlayoutguide"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-layout-guides",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UILayoutGuideAspectFitting"
      ],
      "title": "Working with layout guides"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "safeAreaAspectFitLayoutGuide"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "safeAreaAspectFitLayoutGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIWindow"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-layout-guides",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UILayoutGuideAspectFitting"
              ],
              "title": "Working with layout guides"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)UILayoutGuideobjc(pl)UILayoutGuideAspectFitting",
                    "text": "UILayoutGuide<UILayoutGuideAspectFitting>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "safeAreaAspectFitLayoutGuide"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILayoutGuide/title",
          "value": "UILayoutGuide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILayoutGuide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILayoutGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILayoutGuide/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILayoutGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILayoutGuideAspectFitting/title",
          "value": "UILayoutGuideAspectFitting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILayoutGuideAspectFitting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILayoutGuideAspectFitting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILayoutGuideAspectFitting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILayoutGuideAspectFitting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindow/title",
          "value": "UIWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindow~1safeAreaAspectFitLayoutGuide/title",
          "value": "safeAreaAspectFitLayoutGuide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindow~1safeAreaAspectFitLayoutGuide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "safeAreaAspectFitLayoutGuide"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiwindow/safeareaaspectfitlayoutguide"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiwindow/safeareaaspectfitlayoutguide"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
