{
  "abstract": [
    {
      "text": "A preset that represents a reverb with the acoustic characteristics of a plate environment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/plate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVAudioUnitReverbPreset@AVAudioUnitReverbPresetPlate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "plate"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioUnitReverbPresetPlate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVAudioUnitReverbPreset.plate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "plate"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset": {
      "abstract": [
        {
          "text": "Constants that represent preset reverbs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitReverbPreset"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitReverbPreset"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitReverbPreset",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitreverbpreset"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/cathedral": {
      "abstract": [
        {
          "text": "A preset that represents a reverb with the acoustic characteristics of a cathedral environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cathedral"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/cathedral",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitReverbPresetCathedral"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitReverbPreset.cathedral",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitreverbpreset/cathedral"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeChamber": {
      "abstract": [
        {
          "text": "A preset that represents a reverb with the acoustic characteristics of a large-sized chamber environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "largeChamber"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeChamber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitReverbPresetLargeChamber"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitReverbPreset.largeChamber",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitreverbpreset/largechamber"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeHall": {
      "abstract": [
        {
          "text": "A preset that represents a reverb with the acoustic characteristics of a large-sized hall environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "largeHall"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeHall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitReverbPresetLargeHall"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitReverbPreset.largeHall",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitreverbpreset/largehall"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeHall2": {
      "abstract": [
        {
          "text": "A preset that represents a reverb with the acoustic characteristics of an alternative large-sized hall environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "largeHall2"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeHall2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitReverbPresetLargeHall2"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitReverbPreset.largeHall2",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitreverbpreset/largehall2"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeRoom": {
      "abstract": [
        {
          "text": "A preset that represents a reverb with the acoustic characteristics of a large-sized room environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "largeRoom"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeRoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitReverbPresetLargeRoom"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitReverbPreset.largeRoom",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitreverbpreset/largeroom"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeRoom2": {
      "abstract": [
        {
          "text": "A preset that represents a reverb with the acoustic characteristics of an alternative large-sized room environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "largeRoom2"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeRoom2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitReverbPresetLargeRoom2"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitReverbPreset.largeRoom2",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitreverbpreset/largeroom2"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumChamber": {
      "abstract": [
        {
          "text": "A preset that represents a reverb with the acoustic characteristics of a medium-sized chamber environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediumChamber"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumChamber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitReverbPresetMediumChamber"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitReverbPreset.mediumChamber",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitreverbpreset/mediumchamber"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumHall": {
      "abstract": [
        {
          "text": "A preset that represents a reverb with the acoustic characteristics of a medium-sized hall environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediumHall"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumHall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitReverbPresetMediumHall"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitReverbPreset.mediumHall",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitreverbpreset/mediumhall"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumHall2": {
      "abstract": [
        {
          "text": "A preset that represents a reverb with the acoustic characteristics of an alternative medium-sized hall environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediumHall2"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumHall2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitReverbPresetMediumHall2"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitReverbPreset.mediumHall2",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitreverbpreset/mediumhall2"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumHall3": {
      "abstract": [
        {
          "text": "A preset that represents a reverb with the acoustic characteristics of an alternative medium-sized hall environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediumHall3"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumHall3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitReverbPresetMediumHall3"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitReverbPreset.mediumHall3",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitreverbpreset/mediumhall3"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumRoom": {
      "abstract": [
        {
          "text": "A preset that represents a reverb with the acoustic characteristics of a medium-sized room environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediumRoom"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumRoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitReverbPresetMediumRoom"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitReverbPreset.mediumRoom",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitreverbpreset/mediumroom"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/plate": {
      "abstract": [
        {
          "text": "A preset that represents a reverb with the acoustic characteristics of a plate environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "plate"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/plate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitReverbPresetPlate"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitReverbPreset.plate",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitreverbpreset/plate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/smallRoom": {
      "abstract": [
        {
          "text": "A preset that represents a reverb with the acoustic characteristics of a small-sized room environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smallRoom"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/smallRoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitReverbPresetSmallRoom"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitReverbPreset.smallRoom",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitreverbpreset/smallroom"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Presets",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/smallRoom",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumRoom",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeRoom",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumHall",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeHall",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumChamber",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeChamber",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/cathedral",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeRoom2",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumHall2",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumHall3",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeHall2"
      ],
      "title": "Presets"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioUnitReverbPresetPlate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitReverbPresetPlate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Presets",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/smallRoom",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumRoom",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeRoom",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumHall",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeHall",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumChamber",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeChamber",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/cathedral",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeRoom2",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumHall2",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/mediumHall3",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitReverbPreset/largeHall2"
              ],
              "title": "Presets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVAudioUnitReverbPresetPlate"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1mediumRoom/title",
          "value": "AVAudioUnitReverbPresetMediumRoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1mediumRoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitReverbPresetMediumRoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1mediumHall3/title",
          "value": "AVAudioUnitReverbPresetMediumHall3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1mediumHall3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitReverbPresetMediumHall3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1smallRoom/title",
          "value": "AVAudioUnitReverbPresetSmallRoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1smallRoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitReverbPresetSmallRoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1mediumChamber/title",
          "value": "AVAudioUnitReverbPresetMediumChamber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1mediumChamber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitReverbPresetMediumChamber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1cathedral/title",
          "value": "AVAudioUnitReverbPresetCathedral"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1cathedral/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitReverbPresetCathedral"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1largeHall2/title",
          "value": "AVAudioUnitReverbPresetLargeHall2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1largeHall2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitReverbPresetLargeHall2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1largeRoom2/title",
          "value": "AVAudioUnitReverbPresetLargeRoom2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1largeRoom2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitReverbPresetLargeRoom2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1largeChamber/title",
          "value": "AVAudioUnitReverbPresetLargeChamber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1largeChamber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitReverbPresetLargeChamber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1mediumHall2/title",
          "value": "AVAudioUnitReverbPresetMediumHall2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1mediumHall2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitReverbPresetMediumHall2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1largeRoom/title",
          "value": "AVAudioUnitReverbPresetLargeRoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1largeRoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitReverbPresetLargeRoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1largeHall/title",
          "value": "AVAudioUnitReverbPresetLargeHall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1largeHall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitReverbPresetLargeHall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1mediumHall/title",
          "value": "AVAudioUnitReverbPresetMediumHall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1mediumHall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitReverbPresetMediumHall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset/title",
          "value": "AVAudioUnitReverbPreset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitReverbPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitReverbPreset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1plate/title",
          "value": "AVAudioUnitReverbPresetPlate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitReverbPreset~1plate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitReverbPresetPlate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiounitreverbpreset/plate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiounitreverbpreset/plate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
