{
  "abstract": [
    {
      "text": "Tells the delegate that a navigation response became a download.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKNavigationDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKNavigationDelegate/webView(_:navigationResponse:didBecome:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)WKNavigationDelegate(im)webView:navigationResponse:didBecomeDownload:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "webView"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)WKWebView",
        "text": "WKWebView"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "navigationResponse"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)WKNavigationResponse",
        "text": "WKNavigationResponse"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didBecome"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)WKDownload",
        "text": "WKDownload"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "webView:navigationResponse:didBecomeDownload:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "webView(_:navigationResponse:didBecome:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "webView"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "webView"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WKWebView",
              "text": "WKWebView"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "navigationResponse"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationResponse",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WKNavigationResponse",
              "text": "WKNavigationResponse"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didBecome"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "download"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDownload",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WKDownload",
              "text": "WKDownload"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The web view in which the navigation response took place.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "webView"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Descriptive information about the navigation response that turned into a download.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "navigationResponse"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An object that represents the download of a web resource.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "download"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement this method to begin tracking download progress.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKDownload": {
      "abstract": [
        {
          "text": "An object that represents the download of a web resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKDownload"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDownload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKDownload"
        }
      ],
      "role": "symbol",
      "title": "WKDownload",
      "type": "topic",
      "url": "/documentation/webkit/wkdownload"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKNavigationDelegate": {
      "abstract": [
        {
          "text": "Methods for accepting or rejecting navigation changes, and for tracking the progress of navigation requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKNavigationDelegate"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKNavigationDelegate"
        }
      ],
      "role": "symbol",
      "title": "WKNavigationDelegate",
      "type": "topic",
      "url": "/documentation/webkit/wknavigationdelegate"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKNavigationDelegate/webView(_:navigationAction:didBecome:)": {
      "abstract": [
        {
          "text": "Tells the delegate that a navigation action became a download.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebView",
          "text": "WKWebView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "navigationAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKNavigationAction",
          "text": "WKNavigationAction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didBecome"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKDownload",
          "text": "WKDownload"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationDelegate/webView(_:navigationAction:didBecome:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:navigationAction:didBecomeDownload:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:navigationAction:didBecome:)",
      "type": "topic",
      "url": "/documentation/webkit/wknavigationdelegate/webview(_:navigationaction:didbecome:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKNavigationDelegate/webView(_:navigationResponse:didBecome:)": {
      "abstract": [
        {
          "text": "Tells the delegate that a navigation response became a download.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKWebView",
          "text": "WKWebView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "navigationResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKNavigationResponse",
          "text": "WKNavigationResponse"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didBecome"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WKDownload",
          "text": "WKDownload"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationDelegate/webView(_:navigationResponse:didBecome:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:navigationResponse:didBecomeDownload:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:navigationResponse:didBecome:)",
      "type": "topic",
      "url": "/documentation/webkit/wknavigationdelegate/webview(_:navigationresponse:didbecome:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKNavigationResponse": {
      "abstract": [
        {
          "text": "An object that contains the response to a navigation request, and which you use to make navigation-related policy decisions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKNavigationResponse"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKNavigationResponse"
        }
      ],
      "role": "symbol",
      "title": "WKNavigationResponse",
      "type": "topic",
      "url": "/documentation/webkit/wknavigationresponse"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKWebView": {
      "abstract": [
        {
          "text": "An object that displays interactive web content, such as for an in-app browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWebView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWebView"
        }
      ],
      "role": "symbol",
      "title": "WKWebView",
      "type": "topic",
      "url": "/documentation/webkit/wkwebview"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-download-progress",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKNavigationDelegate/webView(_:navigationAction:didBecome:)"
      ],
      "title": "Handling download progress"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "webView:navigationResponse:didBecomeDownload:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:navigationResponse:didBecomeDownload:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit",
                "doc://com.apple.webkit/documentation/WebKit/WKNavigationDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-download-progress",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKNavigationDelegate/webView(_:navigationAction:didBecome:)"
              ],
              "title": "Handling download progress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "webView:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.webkit/documentation/WebKit/WKWebView",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)WKWebView",
                    "text": "WKWebView"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "webView"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "navigationResponse:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.webkit/documentation/WebKit/WKNavigationResponse",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)WKNavigationResponse",
                    "text": "WKNavigationResponse"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "navigationResponse"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didBecomeDownload:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.webkit/documentation/WebKit/WKDownload",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)WKDownload",
                    "text": "WKDownload"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "download"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The web view in which the navigation response took place.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "webView"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Descriptive information about the navigation response that turned into a download.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "navigationResponse"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An object that represents the download of a web resource.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "download"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationDelegate/title",
          "value": "WKNavigationDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKNavigationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKNavigationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationResponse/title",
          "value": "WKNavigationResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKNavigationResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKNavigationResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationDelegate~1webView(_:navigationAction:didBecome:)/title",
          "value": "webView:navigationAction:didBecomeDownload:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationDelegate~1webView(_:navigationAction:didBecome:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:navigationAction:didBecomeDownload:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationDelegate~1webView(_:navigationResponse:didBecome:)/title",
          "value": "webView:navigationResponse:didBecomeDownload:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKNavigationDelegate~1webView(_:navigationResponse:didBecome:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:navigationResponse:didBecomeDownload:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDownload/title",
          "value": "WKDownload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDownload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDownload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKDownload/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKDownload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/title",
          "value": "WKWebView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKWebView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWebView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wknavigationdelegate/webview(_:navigationresponse:didbecome:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wknavigationdelegate/webview(_:navigationresponse:didbecome:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
