{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult/init(deviceAddress:pageScanRepetitionMode:pageScanPeriodMode:pageScanMode:classOfDevice:clockOffset:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So25BluetoothHCIInquiryResultV13deviceAddress22pageScanRepetitionMode0fg6PeriodI00fgI013classOfDevice11clockOffsetABSo0amE0V_s5UInt8VA2Ls6UInt32Vs6UInt16Vtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "deviceAddress"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothDeviceAddress",
        "text": "BluetoothDeviceAddress"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "pageScanRepetitionMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@BluetoothPageScanRepetitionMode",
        "text": "BluetoothPageScanRepetitionMode"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "pageScanPeriodMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@BluetoothHCIPageScanPeriodMode",
        "text": "BluetoothHCIPageScanPeriodMode"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "pageScanMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@BluetoothHCIPageScanMode",
        "text": "BluetoothHCIPageScanMode"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "classOfDevice"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@BluetoothClassOfDevice",
        "text": "BluetoothClassOfDevice"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "clockOffset"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@BluetoothClockOffset",
        "text": "BluetoothClockOffset"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(deviceAddress:pageScanRepetitionMode:pageScanPeriodMode:pageScanMode:classOfDevice:clockOffset:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "deviceAddress"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceAddress",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothDeviceAddress",
              "text": "BluetoothDeviceAddress"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "pageScanRepetitionMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothPageScanRepetitionMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BluetoothPageScanRepetitionMode",
              "text": "BluetoothPageScanRepetitionMode"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "pageScanPeriodMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPageScanPeriodMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BluetoothHCIPageScanPeriodMode",
              "text": "BluetoothHCIPageScanPeriodMode"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "pageScanMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPageScanMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BluetoothHCIPageScanMode",
              "text": "BluetoothHCIPageScanMode"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "classOfDevice"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BluetoothClassOfDevice",
              "text": "BluetoothClassOfDevice"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "clockOffset"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BluetoothClockOffset",
              "text": "BluetoothClockOffset"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothClassOfDevice"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothClassOfDevice"
        }
      ],
      "role": "symbol",
      "title": "BluetoothClassOfDevice",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothclassofdevice"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothClockOffset"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothClockOffset"
        }
      ],
      "role": "symbol",
      "title": "BluetoothClockOffset",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothclockoffset"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceAddress"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceAddress"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceAddress",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdeviceaddress"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIInquiryResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIInquiryResult"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIInquiryResult",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhciinquiryresult"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult/init(deviceAddress:pageScanRepetitionMode:pageScanPeriodMode:pageScanMode:classOfDevice:clockOffset:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "deviceAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothDeviceAddress",
          "text": "BluetoothDeviceAddress"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "pageScanRepetitionMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothPageScanRepetitionMode",
          "text": "BluetoothPageScanRepetitionMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "pageScanPeriodMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothHCIPageScanPeriodMode",
          "text": "BluetoothHCIPageScanPeriodMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "pageScanMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothHCIPageScanMode",
          "text": "BluetoothHCIPageScanMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "classOfDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothClassOfDevice",
          "text": "BluetoothClassOfDevice"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clockOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothClockOffset",
          "text": "BluetoothClockOffset"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIInquiryResult/init(deviceAddress:pageScanRepetitionMode:pageScanPeriodMode:pageScanMode:classOfDevice:clockOffset:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(deviceAddress:pageScanRepetitionMode:pageScanPeriodMode:pageScanMode:classOfDevice:clockOffset:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhciinquiryresult/init(deviceaddress:pagescanrepetitionmode:pagescanperiodmode:pagescanmode:classofdevice:clockoffset:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPageScanMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIPageScanMode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPageScanMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIPageScanMode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIPageScanMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcipagescanmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPageScanPeriodMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIPageScanPeriodMode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPageScanPeriodMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIPageScanPeriodMode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIPageScanPeriodMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcipagescanperiodmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothPageScanRepetitionMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothPageScanRepetitionMode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothPageScanRepetitionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothPageScanRepetitionMode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothPageScanRepetitionMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothpagescanrepetitionmode"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPageScanMode/title",
          "value": "BluetoothHCIPageScanMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPageScanMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIPageScanMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPageScanMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIPageScanMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothPageScanRepetitionMode/title",
          "value": "BluetoothPageScanRepetitionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothPageScanRepetitionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothPageScanRepetitionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothPageScanRepetitionMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothPageScanRepetitionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/title",
          "value": "BluetoothClockOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClockOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClockOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPageScanPeriodMode/title",
          "value": "BluetoothHCIPageScanPeriodMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPageScanPeriodMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIPageScanPeriodMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPageScanPeriodMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIPageScanPeriodMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIInquiryResult/title",
          "value": "BluetoothHCIInquiryResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIInquiryResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIInquiryResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIInquiryResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIInquiryResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/title",
          "value": "BluetoothClassOfDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClassOfDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClassOfDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceAddress/title",
          "value": "BluetoothDeviceAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceAddress"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothhciinquiryresult/init(deviceaddress:pagescanrepetitionmode:pagescanperiodmode:pagescanmode:classofdevice:clockoffset:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
