{
  "abstract": [
    {
      "text": "Sends a text message.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.messages/documentation/Messages",
        "doc://com.apple.messages/documentation/Messages/MSConversation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.messages/documentation/Messages/MSConversation/sendText(_:completionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MSConversation(im)sendText:completionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sendText"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": (((any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")?)"
      }
    ],
    "modules": [
      {
        "name": "Messages"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "sendText:completionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "sendText(_:completionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sendText"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "text"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": (((any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")? = nil)"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sendText"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "text"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "throws"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The text to send.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "text"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A block that’s called as soon as the message starts sending. This block is passed the following parameter:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "An error object. If an error occurred, this object contains information about the error; otherwise, it’s set to ",
                            "type": "text"
                          },
                          {
                            "code": "nil",
                            "type": "codeVoice"
                          },
                          {
                            "text": ". An error occurs if the user hasn’t recently interacted with your app.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "text": "error",
                        "type": "text"
                      }
                    ]
                  }
                }
              ],
              "type": "termList"
            }
          ],
          "name": "completionHandler"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.messages/documentation/Messages/adding-sticker-packs-and-imessage-apps-to-the-system-stickers-app-messages-camera-and-facetime"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You can call this method from synchronous code using a completion handler, as shown on this page, or you can call it as an asynchronous method that has the following declaration:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "code": [
                "func sendText(_ text: String) async throws"
              ],
              "syntax": "swift",
              "type": "codeListing"
            },
            {
              "inlineContent": [
                {
                  "text": "For information about concurrency and asynchronous code in Swift, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "This method starts sending the text automatically, without any additional user interactions. You can call this method only in response to a user action while in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationContext/messages",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " context.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When calling this method, the following rules apply:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If the app isn’t visible, the send fails with a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/sendWhileNotVisible",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " error code.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If the app hasn’t registered a recent touch interaction from the user, the send fails with a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/sendWithoutRecentInteraction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " error code.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If the app is in the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationContext/media",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " context, the send fails with an ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/apiUnavailableInPresentationContext",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " error.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "This method operates asynchronously. Although the method returns immediately, the actual work is deferred and performed in the background. As soon as the message starts to send, the system calls the completion block on a background queue.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously": {
      "abstract": [
        {
          "text": "Learn how functions and methods that take a completion handler are converted to Swift asynchronous functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously",
      "kind": "article",
      "role": "article",
      "title": "Calling Objective-C APIs Asynchronously",
      "type": "topic",
      "url": "/documentation/Swift/calling-objective-c-apis-asynchronously"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.messages/documentation/Messages": {
      "abstract": [
        {
          "text": "Create app extensions that allow users to send text, stickers, media files, and interactive messages.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages",
      "kind": "symbol",
      "role": "collection",
      "title": "Messages",
      "type": "topic",
      "url": "/documentation/messages"
    },
    "doc://com.apple.messages/documentation/Messages/MSConversation": {
      "abstract": [
        {
          "text": "An object that represents a conversation in the Messages app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSConversation"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSConversation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSConversation"
        }
      ],
      "role": "symbol",
      "title": "MSConversation",
      "type": "topic",
      "url": "/documentation/messages/msconversation"
    },
    "doc://com.apple.messages/documentation/Messages/MSConversation/send(_:completionHandler:)-4kje0": {
      "abstract": [
        {
          "text": "Sends a sticker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "send"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MSSticker",
          "text": "MSSticker"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSConversation/send(_:completionHandler:)-4kje0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendSticker:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "send(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/messages/msconversation/send(_:completionhandler:)-4kje0"
    },
    "doc://com.apple.messages/documentation/Messages/MSConversation/send(_:completionHandler:)-9krz": {
      "abstract": [
        {
          "text": "Sends a message object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "send"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MSMessage",
          "text": "MSMessage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSConversation/send(_:completionHandler:)-9krz",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendMessage:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "send(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/messages/msconversation/send(_:completionhandler:)-9krz"
    },
    "doc://com.apple.messages/documentation/Messages/MSConversation/sendAttachment(_:withAlternateFilename:completionHandler:)": {
      "abstract": [
        {
          "text": "Sends the media file specified by the given URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withAlternateFilename"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSConversation/sendAttachment(_:withAlternateFilename:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendAttachment:withAlternateFilename:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "sendAttachment(_:withAlternateFilename:completionHandler:)",
      "type": "topic",
      "url": "/documentation/messages/msconversation/sendattachment(_:withalternatefilename:completionhandler:)"
    },
    "doc://com.apple.messages/documentation/Messages/MSConversation/sendText(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Sends a text message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendText"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSConversation/sendText(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sendText:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "sendText(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/messages/msconversation/sendtext(_:completionhandler:)"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/apiUnavailableInPresentationContext": {
      "abstract": [
        {
          "text": "The API is unavailable in the current context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "apiUnavailableInPresentationContext"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/apiUnavailableInPresentationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCodeAPIUnavailableInPresentationContext"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode.apiUnavailableInPresentationContext",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode/apiunavailableinpresentationcontext"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/sendWhileNotVisible": {
      "abstract": [
        {
          "text": "A message was sent while the app was not visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendWhileNotVisible"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/sendWhileNotVisible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCodeSendWhileNotVisible"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode.sendWhileNotVisible",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode/sendwhilenotvisible"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/sendWithoutRecentInteraction": {
      "abstract": [
        {
          "text": "A message was sent, but the app has not registered a recent touch interaction from the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendWithoutRecentInteraction"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessageErrorCode/sendWithoutRecentInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessageErrorCodeSendWithoutRecentInteraction"
        }
      ],
      "role": "symbol",
      "title": "MSMessageErrorCode.sendWithoutRecentInteraction",
      "type": "topic",
      "url": "/documentation/messages/msmessageerrorcode/sendwithoutrecentinteraction"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationContext/media": {
      "abstract": [
        {
          "text": "A constant that indicates the iMessage app appears inside the Stickers app throughout iOS including in Messages, FaceTime, the emoji keyboard, and Markup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "media"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationContext/media",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppPresentationContextMedia"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppPresentationContext.media",
      "type": "topic",
      "url": "/documentation/messages/msmessagesapppresentationcontext/media"
    },
    "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationContext/messages": {
      "abstract": [
        {
          "text": "A constant that indicates the iMessage app appears in Messages in the list of iMessage apps that appears when you press the plus button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messages"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/MSMessagesAppPresentationContext/messages",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSMessagesAppPresentationContextMessages"
        }
      ],
      "role": "symbol",
      "title": "MSMessagesAppPresentationContext.messages",
      "type": "topic",
      "url": "/documentation/messages/msmessagesapppresentationcontext/messages"
    },
    "doc://com.apple.messages/documentation/Messages/adding-sticker-packs-and-imessage-apps-to-the-system-stickers-app-messages-camera-and-facetime": {
      "abstract": [
        {
          "text": "Enable your Sticker pack or iMessage app in the media context.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.messages/documentation/Messages/adding-sticker-packs-and-imessage-apps-to-the-system-stickers-app-messages-camera-and-facetime",
      "kind": "article",
      "role": "article",
      "title": "Adding Sticker packs and iMessage apps to the system Stickers app, Messages camera, and FaceTime",
      "type": "topic",
      "url": "/documentation/messages/adding-sticker-packs-and-imessage-apps-to-the-system-stickers-app-messages-camera-and-facetime"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Directly-Sending-a-Message",
      "generated": true,
      "identifiers": [
        "doc://com.apple.messages/documentation/Messages/MSConversation/sendAttachment(_:withAlternateFilename:completionHandler:)",
        "doc://com.apple.messages/documentation/Messages/MSConversation/send(_:completionHandler:)-9krz",
        "doc://com.apple.messages/documentation/Messages/MSConversation/send(_:completionHandler:)-4kje0"
      ],
      "title": "Directly Sending a Message"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "sendText:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sendText:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.messages/documentation/Messages",
                "doc://com.apple.messages/documentation/Messages/MSConversation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Directly-Sending-a-Message",
              "generated": true,
              "identifiers": [
                "doc://com.apple.messages/documentation/Messages/MSConversation/sendAttachment(_:withAlternateFilename:completionHandler:)",
                "doc://com.apple.messages/documentation/Messages/MSConversation/send(_:completionHandler:)-9krz",
                "doc://com.apple.messages/documentation/Messages/MSConversation/send(_:completionHandler:)-4kje0"
              ],
              "title": "Directly Sending a Message"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "sendText:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "text"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "completionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The text to send.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "text"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A block that’s called as soon as the message starts sending. This block is passed the following parameter:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "An error object. If an error occurred, this object contains information about the error; otherwise, it’s set to ",
                                  "type": "text"
                                },
                                {
                                  "code": "nil",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": ". An error occurs if the user hasn’t recently interacted with your app.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "text": "error",
                              "type": "text"
                            }
                          ]
                        }
                      }
                    ],
                    "type": "termList"
                  }
                ],
                "name": "completionHandler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationContext~1media/title",
          "value": "MSMessagesAppPresentationContextMedia"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationContext~1media/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppPresentationContextMedia"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1sendWhileNotVisible/title",
          "value": "MSMessageErrorCodeSendWhileNotVisible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1sendWhileNotVisible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCodeSendWhileNotVisible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation~1send(_:completionHandler:)-9krz/title",
          "value": "sendMessage:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation~1send(_:completionHandler:)-9krz/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sendMessage:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationContext~1messages/title",
          "value": "MSMessagesAppPresentationContextMessages"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessagesAppPresentationContext~1messages/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessagesAppPresentationContextMessages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation~1sendAttachment(_:withAlternateFilename:completionHandler:)/title",
          "value": "sendAttachment:withAlternateFilename:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation~1sendAttachment(_:withAlternateFilename:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sendAttachment:withAlternateFilename:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1apiUnavailableInPresentationContext/title",
          "value": "MSMessageErrorCodeAPIUnavailableInPresentationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1apiUnavailableInPresentationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCodeAPIUnavailableInPresentationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1sendWithoutRecentInteraction/title",
          "value": "MSMessageErrorCodeSendWithoutRecentInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSMessageErrorCode~1sendWithoutRecentInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSMessageErrorCodeSendWithoutRecentInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation~1sendText(_:completionHandler:)/title",
          "value": "sendText:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation~1sendText(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sendText:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation~1send(_:completionHandler:)-4kje0/title",
          "value": "sendSticker:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation~1send(_:completionHandler:)-4kje0/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sendSticker:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation/title",
          "value": "MSConversation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSConversation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.messages~1documentation~1Messages~1MSConversation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSConversation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/messages/msconversation/sendtext(_:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/messages/msconversation/sendtext(_:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
