{
  "abstract": [
    {
      "text": "The application activities, if any, for the configuration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading/applicationActivitiesForActivityItemsConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIActivityItemsConfigurationReading(py)applicationActivitiesForActivityItemsConfiguration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "applicationActivitiesForActivityItemsConfiguration"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIActivity",
        "text": "UIActivity"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "applicationActivitiesForActivityItemsConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "applicationActivitiesForActivityItemsConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "applicationActivitiesForActivityItemsConfiguration"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIActivity",
              "text": "UIActivity"
            },
            {
              "kind": "text",
              "text": "]? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivity": {
      "abstract": [
        {
          "text": "An abstract class that you subclass to implement app-specific services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivity"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivity"
        }
      ],
      "role": "symbol",
      "title": "UIActivity",
      "type": "topic",
      "url": "/documentation/uikit/uiactivity"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationMetadataKey": {
      "abstract": [
        {
          "text": "A structure that defines keys for the metadata associated with an activity items configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationMetadataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationMetadataKey"
        }
      ],
      "role": "symbol",
      "title": "UIActivityItemsConfigurationMetadataKey",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfigurationmetadatakey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading": {
      "abstract": [
        {
          "text": "A set of methods adopted by an object so that the object can act as an activity items configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationReading"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationReading"
        }
      ],
      "role": "symbol",
      "title": "UIActivityItemsConfigurationReading",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfigurationreading"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading/activityItemsConfigurationMetadata(key:)": {
      "abstract": [
        {
          "text": "Returns the configuration for the specified metadata key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activityItemsConfigurationMetadata"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityItemsConfigurationMetadataKey",
          "text": "UIActivityItemsConfigurationMetadataKey"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading/activityItemsConfigurationMetadata(key:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activityItemsConfigurationMetadataForKey:"
        }
      ],
      "role": "symbol",
      "title": "activityItemsConfigurationMetadata(key:)",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfigurationreading/activityitemsconfigurationmetadata(key:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading/activityItemsConfigurationMetadataForItem(at:key:)": {
      "abstract": [
        {
          "text": "Returns the configuration for a particular item for the specified metadata key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activityItemsConfigurationMetadataForItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityItemsConfigurationMetadataKey",
          "text": "UIActivityItemsConfigurationMetadataKey"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading/activityItemsConfigurationMetadataForItem(at:key:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activityItemsConfigurationMetadataForItemAtIndex:key:"
        }
      ],
      "role": "symbol",
      "title": "activityItemsConfigurationMetadataForItem(at:key:)",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfigurationreading/activityitemsconfigurationmetadataforitem(at:key:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading/applicationActivitiesForActivityItemsConfiguration": {
      "abstract": [
        {
          "text": "The application activities, if any, for the configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationActivitiesForActivityItemsConfiguration"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading/applicationActivitiesForActivityItemsConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationActivitiesForActivityItemsConfiguration"
        }
      ],
      "role": "symbol",
      "title": "applicationActivitiesForActivityItemsConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfigurationreading/applicationactivitiesforactivityitemsconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading/itemProvidersForActivityItemsConfiguration": {
      "abstract": [
        {
          "text": "The item providers for the configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemProvidersForActivityItemsConfiguration"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSItemProvider",
          "text": "NSItemProvider"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading/itemProvidersForActivityItemsConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemProvidersForActivityItemsConfiguration"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "itemProvidersForActivityItemsConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfigurationreading/itemprovidersforactivityitemsconfiguration"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-Configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading/itemProvidersForActivityItemsConfiguration",
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading/activityItemsConfigurationMetadata(key:)",
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading/activityItemsConfigurationMetadataForItem(at:key:)",
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationMetadataKey"
      ],
      "title": "Managing the Configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "applicationActivitiesForActivityItemsConfiguration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationActivitiesForActivityItemsConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading/itemProvidersForActivityItemsConfiguration",
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading/activityItemsConfigurationMetadata(key:)",
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading/activityItemsConfigurationMetadataForItem(at:key:)",
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationMetadataKey"
              ],
              "title": "Managing the Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<UIActivity *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "applicationActivitiesForActivityItemsConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationReading~1itemProvidersForActivityItemsConfiguration/title",
          "value": "itemProvidersForActivityItemsConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationReading~1itemProvidersForActivityItemsConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "itemProvidersForActivityItemsConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationReading/title",
          "value": "UIActivityItemsConfigurationReading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationReading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationReading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationReading/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationReading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationReading~1activityItemsConfigurationMetadata(key:)/title",
          "value": "activityItemsConfigurationMetadataForKey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationReading~1activityItemsConfigurationMetadata(key:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "activityItemsConfigurationMetadataForKey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity/title",
          "value": "UIActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationReading~1activityItemsConfigurationMetadataForItem(at:key:)/title",
          "value": "activityItemsConfigurationMetadataForItemAtIndex:key:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationReading~1activityItemsConfigurationMetadataForItem(at:key:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "activityItemsConfigurationMetadataForItemAtIndex:key:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationMetadataKey/title",
          "value": "UIActivityItemsConfigurationMetadataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationMetadataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationMetadataKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationReading~1applicationActivitiesForActivityItemsConfiguration/title",
          "value": "applicationActivitiesForActivityItemsConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationReading~1applicationActivitiesForActivityItemsConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationActivitiesForActivityItemsConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiactivityitemsconfigurationreading/applicationactivitiesforactivityitemsconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiactivityitemsconfigurationreading/applicationactivitiesforactivityitemsconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
