{
  "abstract": [
    {
      "text": "The detected contours as a path object in normalized coordinates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNContoursObservation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNContoursObservation/normalizedPath"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VNContoursObservation(py)normalizedPath",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "normalizedPath"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CGPathRef",
        "text": "CGPath"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "normalizedPath"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "normalizedPath"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "normalizedPath"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CGPathRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGPathRef",
              "text": "CGPath"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNContour": {
      "abstract": [
        {
          "text": "A class that represents a detected contour in an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNContour"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNContour",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNContour"
        }
      ],
      "role": "symbol",
      "title": "VNContour",
      "type": "topic",
      "url": "/documentation/vision/vncontour"
    },
    "doc://com.apple.vision/documentation/Vision/VNContoursObservation": {
      "abstract": [
        {
          "text": "An object that represents the detected contours in an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNContoursObservation"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNContoursObservation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNContoursObservation"
        }
      ],
      "role": "symbol",
      "title": "VNContoursObservation",
      "type": "topic",
      "url": "/documentation/vision/vncontoursobservation"
    },
    "doc://com.apple.vision/documentation/Vision/VNContoursObservation/contour(at:)-52odo": {
      "abstract": [
        {
          "text": "Retrieves the contour object at the specified index path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contour"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNContour",
          "text": "VNContour"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNContoursObservation/contour(at:)-52odo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contourAtIndexPath:error:"
        }
      ],
      "role": "symbol",
      "title": "contour(at:)",
      "type": "topic",
      "url": "/documentation/vision/vncontoursobservation/contour(at:)-52odo"
    },
    "doc://com.apple.vision/documentation/Vision/VNContoursObservation/contour(at:)-9on0y": {
      "abstract": [
        {
          "text": "Retrieves the contour object at the specified index, irrespective of hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contour"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNContour",
          "text": "VNContour"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNContoursObservation/contour(at:)-9on0y",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contourAtIndex:error:"
        }
      ],
      "role": "symbol",
      "title": "contour(at:)",
      "type": "topic",
      "url": "/documentation/vision/vncontoursobservation/contour(at:)-9on0y"
    },
    "doc://com.apple.vision/documentation/Vision/VNContoursObservation/contourCount": {
      "abstract": [
        {
          "text": "The total number of detected contours.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contourCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNContoursObservation/contourCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contourCount"
        }
      ],
      "role": "symbol",
      "title": "contourCount",
      "type": "topic",
      "url": "/documentation/vision/vncontoursobservation/contourcount"
    },
    "doc://com.apple.vision/documentation/Vision/VNContoursObservation/normalizedPath": {
      "abstract": [
        {
          "text": "The detected contours as a path object in normalized coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normalizedPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGPathRef",
          "text": "CGPath"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNContoursObservation/normalizedPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "normalizedPath"
        }
      ],
      "role": "symbol",
      "title": "normalizedPath",
      "type": "topic",
      "url": "/documentation/vision/vncontoursobservation/normalizedpath"
    },
    "doc://com.apple.vision/documentation/Vision/VNContoursObservation/topLevelContourCount": {
      "abstract": [
        {
          "text": "The total number of detected top-level contours.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLevelContourCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNContoursObservation/topLevelContourCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "topLevelContourCount"
        }
      ],
      "role": "symbol",
      "title": "topLevelContourCount",
      "type": "topic",
      "url": "/documentation/vision/vncontoursobservation/toplevelcontourcount"
    },
    "doc://com.apple.vision/documentation/Vision/VNContoursObservation/topLevelContours": {
      "abstract": [
        {
          "text": "An array of contours that don’t have another contour enclosing them.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLevelContours"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VNContour",
          "text": "VNContour"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNContoursObservation/topLevelContours",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "topLevelContours"
        }
      ],
      "role": "symbol",
      "title": "topLevelContours",
      "type": "topic",
      "url": "/documentation/vision/vncontoursobservation/toplevelcontours"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGPathRef": {
      "abstract": [
        {
          "text": "An immutable graphics path: a mathematical description of shapes or lines to be drawn in a graphics context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CGPath"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGPathRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGPath",
      "type": "topic",
      "url": "/documentation/coregraphics/cgpath"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-the-Observation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNContoursObservation/contourCount",
        "doc://com.apple.vision/documentation/Vision/VNContoursObservation/topLevelContours",
        "doc://com.apple.vision/documentation/Vision/VNContoursObservation/topLevelContourCount",
        "doc://com.apple.vision/documentation/Vision/VNContoursObservation/contour(at:)-9on0y",
        "doc://com.apple.vision/documentation/Vision/VNContoursObservation/contour(at:)-52odo",
        "doc://com.apple.vision/documentation/Vision/VNContour"
      ],
      "title": "Inspecting the Observation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "normalizedPath"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "normalizedPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision",
                "doc://com.apple.vision/documentation/Vision/VNContoursObservation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-the-Observation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNContoursObservation/contourCount",
                "doc://com.apple.vision/documentation/Vision/VNContoursObservation/topLevelContours",
                "doc://com.apple.vision/documentation/Vision/VNContoursObservation/topLevelContourCount",
                "doc://com.apple.vision/documentation/Vision/VNContoursObservation/contour(at:)-9on0y",
                "doc://com.apple.vision/documentation/Vision/VNContoursObservation/contour(at:)-52odo",
                "doc://com.apple.vision/documentation/Vision/VNContour"
              ],
              "title": "Inspecting the Observation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CGPathRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGPathRef",
                    "text": "CGPathRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "normalizedPath"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContoursObservation~1normalizedPath/title",
          "value": "normalizedPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContoursObservation~1normalizedPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "normalizedPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContoursObservation~1contour(at:)-52odo/title",
          "value": "contourAtIndexPath:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContoursObservation~1contour(at:)-52odo/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contourAtIndexPath:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContoursObservation~1contour(at:)-9on0y/title",
          "value": "contourAtIndex:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContoursObservation~1contour(at:)-9on0y/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contourAtIndex:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContour/title",
          "value": "VNContour"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContour/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNContour"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContour/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNContour"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContoursObservation~1topLevelContours/title",
          "value": "topLevelContours"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContoursObservation~1topLevelContours/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "topLevelContours"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CGPathRef/title",
          "value": "CGPathRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContoursObservation/title",
          "value": "VNContoursObservation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContoursObservation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNContoursObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContoursObservation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNContoursObservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContoursObservation~1contourCount/title",
          "value": "contourCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContoursObservation~1contourCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contourCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContoursObservation~1topLevelContourCount/title",
          "value": "topLevelContourCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNContoursObservation~1topLevelContourCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "topLevelContourCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vncontoursobservation/normalizedpath"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vncontoursobservation/normalizedpath"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
