{
  "abstract": [
    {
      "text": "An error that indicates the system needs to finish a high-resolution frame request before accepting another request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARError",
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARError/Code/highResolutionFrameCaptureInProgress"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ARErrorCode@ARErrorCodeHighResolutionFrameCaptureInProgress",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "highResolutionFrameCaptureInProgress"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ARErrorCodeHighResolutionFrameCaptureInProgress"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ARError.Code.highResolutionFrameCaptureInProgress"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "highResolutionFrameCaptureInProgress"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system provides this error to the completion handler of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSession/captureHighResolutionFrame(completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for failed operations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError": {
      "abstract": [
        {
          "text": "An error reported by ARKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARError"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARError"
        }
      ],
      "role": "symbol",
      "title": "ARError",
      "type": "topic",
      "url": "/documentation/arkit/arerror"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code": {
      "abstract": [
        {
          "text": "Codes that identify errors in ARKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code/cameraUnauthorized": {
      "abstract": [
        {
          "text": "An error that indicates the app lacks user permission for the camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraUnauthorized"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code/cameraUnauthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARErrorCodeCameraUnauthorized"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code.cameraUnauthorized",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code/cameraunauthorized"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code/fileIOFailed": {
      "abstract": [
        {
          "text": "An error that indicates a file access fails to read or write.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileIOFailed"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code/fileIOFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARErrorCodeFileIOFailed"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code.fileIOFailed",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code/fileiofailed"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code/highResolutionFrameCaptureInProgress": {
      "abstract": [
        {
          "text": "An error that indicates the system needs to finish a high-resolution frame request before accepting another request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highResolutionFrameCaptureInProgress"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code/highResolutionFrameCaptureInProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARErrorCodeHighResolutionFrameCaptureInProgress"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code.highResolutionFrameCaptureInProgress",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code/highresolutionframecaptureinprogress"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code/insufficientFeatures": {
      "abstract": [
        {
          "text": "An error that indicates the framework requires more features to complete a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientFeatures"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code/insufficientFeatures",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARErrorCodeInsufficientFeatures"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code.insufficientFeatures",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code/insufficientfeatures"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidCollaborationData": {
      "abstract": [
        {
          "text": "An error that indicates the framework fails to parse collaboration data the app receives over the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidCollaborationData"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidCollaborationData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARErrorCodeInvalidCollaborationData"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code.invalidCollaborationData",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code/invalidcollaborationdata"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidConfiguration": {
      "abstract": [
        {
          "text": "An error that indicates the configuration contains ambiguous or erroneous data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidConfiguration"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARErrorCodeInvalidConfiguration"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code.invalidConfiguration",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code/invalidconfiguration"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidReferenceImage": {
      "abstract": [
        {
          "text": "An error that indicates the framework fails to process a reference image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidReferenceImage"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidReferenceImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARErrorCodeInvalidReferenceImage"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code.invalidReferenceImage",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code/invalidreferenceimage"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidReferenceObject": {
      "abstract": [
        {
          "text": "An error that indicates the framework fails to process a reference object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidReferenceObject"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidReferenceObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARErrorCodeInvalidReferenceObject"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code.invalidReferenceObject",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code/invalidreferenceobject"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidWorldMap": {
      "abstract": [
        {
          "text": "An error that indicates the framework fails to process a world map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidWorldMap"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidWorldMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARErrorCodeInvalidWorldMap"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code.invalidWorldMap",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code/invalidworldmap"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code/microphoneUnauthorized": {
      "abstract": [
        {
          "text": "An error that indicates the app lacks user permission for the microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "microphoneUnauthorized"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code/microphoneUnauthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARErrorCodeMicrophoneUnauthorized"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code.microphoneUnauthorized",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code/microphoneunauthorized"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code/objectMergeFailed": {
      "abstract": [
        {
          "text": "An error that indicates the framework fails to merge a detected object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectMergeFailed"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code/objectMergeFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARErrorCodeObjectMergeFailed"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code.objectMergeFailed",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code/objectmergefailed"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code/requestFailed": {
      "abstract": [
        {
          "text": "An error that indicates a request fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestFailed"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code/requestFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARErrorCodeRequestFailed"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code.requestFailed",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code/requestfailed"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code/sensorFailed": {
      "abstract": [
        {
          "text": "An error that indicates a sensor fails to provide required input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorFailed"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code/sensorFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARErrorCodeSensorFailed"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code.sensorFailed",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code/sensorfailed"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code/sensorUnavailable": {
      "abstract": [
        {
          "text": "An error that indicates the framework fails to access a required sensor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sensorUnavailable"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code/sensorUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARErrorCodeSensorUnavailable"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code.sensorUnavailable",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code/sensorunavailable"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code/unsupportedConfiguration": {
      "abstract": [
        {
          "text": "An error that indicates the device lacks support for the session’s configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedConfiguration"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code/unsupportedConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARErrorCodeUnsupportedConfiguration"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code.unsupportedConfiguration",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code/unsupportedconfiguration"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARError/Code/worldTrackingFailed": {
      "abstract": [
        {
          "text": "An error that indicates when world tracking experiences an unrecoverable problem.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "worldTrackingFailed"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARError/Code/worldTrackingFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARErrorCodeWorldTrackingFailed"
        }
      ],
      "role": "symbol",
      "title": "ARError.Code.worldTrackingFailed",
      "type": "topic",
      "url": "/documentation/arkit/arerror/code/worldtrackingfailed"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSession/captureHighResolutionFrame(completion:)": {
      "abstract": [
        {
          "text": "Requests a frame outside of the normal frequency that contains a high-resolution captured image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "captureHighResolutionFrame"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARFrame",
          "text": "ARFrame"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSession/captureHighResolutionFrame(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "captureHighResolutionFrameWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "captureHighResolutionFrame(completion:)",
      "type": "topic",
      "url": "/documentation/arkit/arsession/capturehighresolutionframe(completion:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code/requestFailed",
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code/cameraUnauthorized",
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code/fileIOFailed",
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code/insufficientFeatures",
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidCollaborationData",
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidConfiguration",
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidReferenceImage",
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidReferenceObject",
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidWorldMap",
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code/microphoneUnauthorized",
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code/objectMergeFailed",
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code/sensorFailed",
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code/sensorUnavailable",
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code/unsupportedConfiguration",
        "doc://com.apple.arkit/documentation/ARKit/ARError/Code/worldTrackingFailed"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ARErrorCodeHighResolutionFrameCaptureInProgress"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCodeHighResolutionFrameCaptureInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit",
                "doc://com.apple.arkit/documentation/ARKit/ARError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARError/Code/requestFailed",
                "doc://com.apple.arkit/documentation/ARKit/ARError/Code/cameraUnauthorized",
                "doc://com.apple.arkit/documentation/ARKit/ARError/Code/fileIOFailed",
                "doc://com.apple.arkit/documentation/ARKit/ARError/Code/insufficientFeatures",
                "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidCollaborationData",
                "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidConfiguration",
                "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidReferenceImage",
                "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidReferenceObject",
                "doc://com.apple.arkit/documentation/ARKit/ARError/Code/invalidWorldMap",
                "doc://com.apple.arkit/documentation/ARKit/ARError/Code/microphoneUnauthorized",
                "doc://com.apple.arkit/documentation/ARKit/ARError/Code/objectMergeFailed",
                "doc://com.apple.arkit/documentation/ARKit/ARError/Code/sensorFailed",
                "doc://com.apple.arkit/documentation/ARKit/ARError/Code/sensorUnavailable",
                "doc://com.apple.arkit/documentation/ARKit/ARError/Code/unsupportedConfiguration",
                "doc://com.apple.arkit/documentation/ARKit/ARError/Code/worldTrackingFailed"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ARErrorCodeHighResolutionFrameCaptureInProgress"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1highResolutionFrameCaptureInProgress/title",
          "value": "ARErrorCodeHighResolutionFrameCaptureInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1highResolutionFrameCaptureInProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCodeHighResolutionFrameCaptureInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code/title",
          "value": "ARErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1insufficientFeatures/title",
          "value": "ARErrorCodeInsufficientFeatures"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1insufficientFeatures/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCodeInsufficientFeatures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1invalidConfiguration/title",
          "value": "ARErrorCodeInvalidConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1invalidConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCodeInvalidConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1fileIOFailed/title",
          "value": "ARErrorCodeFileIOFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1fileIOFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCodeFileIOFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1worldTrackingFailed/title",
          "value": "ARErrorCodeWorldTrackingFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1worldTrackingFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCodeWorldTrackingFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1microphoneUnauthorized/title",
          "value": "ARErrorCodeMicrophoneUnauthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1microphoneUnauthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCodeMicrophoneUnauthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1sensorUnavailable/title",
          "value": "ARErrorCodeSensorUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1sensorUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCodeSensorUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1invalidReferenceObject/title",
          "value": "ARErrorCodeInvalidReferenceObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1invalidReferenceObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCodeInvalidReferenceObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1requestFailed/title",
          "value": "ARErrorCodeRequestFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1requestFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCodeRequestFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1unsupportedConfiguration/title",
          "value": "ARErrorCodeUnsupportedConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1unsupportedConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCodeUnsupportedConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1invalidWorldMap/title",
          "value": "ARErrorCodeInvalidWorldMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1invalidWorldMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCodeInvalidWorldMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1cameraUnauthorized/title",
          "value": "ARErrorCodeCameraUnauthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1cameraUnauthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCodeCameraUnauthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1objectMergeFailed/title",
          "value": "ARErrorCodeObjectMergeFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1objectMergeFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCodeObjectMergeFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession~1captureHighResolutionFrame(completion:)/title",
          "value": "captureHighResolutionFrameWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession~1captureHighResolutionFrame(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "captureHighResolutionFrameWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1invalidCollaborationData/title",
          "value": "ARErrorCodeInvalidCollaborationData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1invalidCollaborationData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCodeInvalidCollaborationData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1invalidReferenceImage/title",
          "value": "ARErrorCodeInvalidReferenceImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1invalidReferenceImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCodeInvalidReferenceImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1sensorFailed/title",
          "value": "ARErrorCodeSensorFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARError~1Code~1sensorFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARErrorCodeSensorFailed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arerror/code/highresolutionframecaptureinprogress"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arerror/code/highresolutionframecaptureinprogress"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
