{
  "abstract": [
    {
      "text": "An interval lasting one day.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use Product.SubscriptionPeriod.Unit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/day"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKProductPeriodUnit@SKProductPeriodUnitDay",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "day"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKProductPeriodUnitDay"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "11.2",
        "message": "Use Product.SubscriptionPeriod.Unit",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "11.2",
        "message": "Use Product.SubscriptionPeriod.Unit",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.1",
        "message": "Use Product.SubscriptionPeriod.Unit",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.13.2",
        "message": "Use Product.SubscriptionPeriod.Unit",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "11.2",
        "message": "Use Product.SubscriptionPeriod.Unit",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "Use Product.SubscriptionPeriod.Unit",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "6.2",
        "message": "Use Product.SubscriptionPeriod.Unit",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SKProduct.PeriodUnit.day"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "day"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct": {
      "abstract": [
        {
          "text": "Information about a registered product in App Store Connect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKProduct"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProduct"
        }
      ],
      "role": "symbol",
      "title": "SKProduct",
      "type": "topic",
      "url": "/documentation/storekit/skproduct"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit": {
      "abstract": [
        {
          "text": "Values representing the duration of an interval, from a day up to a year.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PeriodUnit"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PeriodUnit"
        }
      ],
      "role": "symbol",
      "title": "SKProduct.PeriodUnit",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/periodunit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/day": {
      "abstract": [
        {
          "text": "An interval lasting one day.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "day"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/day",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductPeriodUnitDay"
        }
      ],
      "role": "symbol",
      "title": "SKProduct.PeriodUnit.day",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/periodunit/day"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/month": {
      "abstract": [
        {
          "text": "An interval lasting one month.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "month"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/month",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductPeriodUnitMonth"
        }
      ],
      "role": "symbol",
      "title": "SKProduct.PeriodUnit.month",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/periodunit/month"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/week": {
      "abstract": [
        {
          "text": "An interval lasting one week.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "week"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/week",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductPeriodUnitWeek"
        }
      ],
      "role": "symbol",
      "title": "SKProduct.PeriodUnit.week",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/periodunit/week"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/year": {
      "abstract": [
        {
          "text": "An interval lasting one year.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "year"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/year",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKProductPeriodUnitYear"
        }
      ],
      "role": "symbol",
      "title": "SKProduct.PeriodUnit.year",
      "type": "topic",
      "url": "/documentation/storekit/skproduct/periodunit/year"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Period-Units",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/month",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/week",
        "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/year"
      ],
      "title": "Period Units"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "11.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "11.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.13.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "11.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "6.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKProductPeriodUnitDay"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductPeriodUnitDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekit/documentation/StoreKit",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Period-Units",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/month",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/week",
                "doc://com.apple.storekit/documentation/StoreKit/SKProduct/PeriodUnit/year"
              ],
              "title": "Period Units"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKProductPeriodUnitDay"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use Product.SubscriptionPeriod.Unit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit~1month/title",
          "value": "SKProductPeriodUnitMonth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit~1month/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductPeriodUnitMonth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit/title",
          "value": "SKProductPeriodUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductPeriodUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductPeriodUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit~1week/title",
          "value": "SKProductPeriodUnitWeek"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit~1week/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductPeriodUnitWeek"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct/title",
          "value": "SKProduct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProduct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProduct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit~1day/title",
          "value": "SKProductPeriodUnitDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit~1day/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductPeriodUnitDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit~1year/title",
          "value": "SKProductPeriodUnitYear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKProduct~1PeriodUnit~1year/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKProductPeriodUnitYear"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skproduct/periodunit/day"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skproduct/periodunit/day"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
