{
  "abstract": [
    {
      "text": "Sets the interval, in nanoseconds, at which to invoke the I/O handlers for the channel.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.dispatch/documentation/Dispatch",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setInterval(interval:flags:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Dispatch",
    "externalID": "s:So14OS_dispatch_ioC8DispatchE11setInterval8interval5flagsyAC0d4TimeF0O_AbCE0F5FlagsVtF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setInterval"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "interval"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:8Dispatch0A12TimeIntervalO",
        "text": "DispatchTimeInterval"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "flags"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)OS_dispatch_io",
        "text": "DispatchIO"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So14OS_dispatch_ioC8DispatchE13IntervalFlagsV",
        "text": "IntervalFlags"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Dispatch"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setInterval(interval:flags:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setInterval"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "interval"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:8Dispatch0A12TimeIntervalO",
              "text": "DispatchTimeInterval"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "flags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)OS_dispatch_io",
              "text": "DispatchIO"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/IntervalFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So14OS_dispatch_ioC8DispatchE13IntervalFlagsV",
              "text": "IntervalFlags"
            },
            {
              "kind": "text",
              "text": " = [])"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of nanoseconds that must elapse before the scheduling of any I/O handlers is desired.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "interval"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Flags indicating the desired delivery behavior at the interval time. For a list of flags, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/IntervalFlags",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "flags"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A channel interval is a way for you to receive periodic progress reports on the state of a read or write operation. You can use this feedback to update progress bars or other parts of your application.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you set an interval on a channel, the handlers for any read or write operations are enqueued at the given interval only if the amount of data that has been processed exceeds the current low-water mark for the channel. Passing the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/IntervalFlags/strictInterval",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " constant in the ",
              "type": "text"
            },
            {
              "code": "flags",
              "type": "codeVoice"
            },
            {
              "text": " parameter forces the enqueueing of the handlers even if the low-water mark is not exceeded.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The system may add a small amount of leeway to the specified interval in order to align the delivery of handlers with other system activity. The purpose of this behavior is to improve overall performance or power consumption for the system.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.dispatch/documentation/Dispatch": {
      "abstract": [
        {
          "text": "Execute code concurrently on multicore hardware by submitting work to dispatch queues managed by the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch",
      "kind": "symbol",
      "role": "collection",
      "title": "Dispatch",
      "type": "topic",
      "url": "/documentation/dispatch"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO": {
      "abstract": [
        {
          "text": "An object that manages operations on a file descriptor using either stream-based or random-access semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchIO"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchIO"
        }
      ],
      "role": "symbol",
      "title": "DispatchIO",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/IntervalFlags": {
      "abstract": [
        {
          "text": "The desired delivery behavior for interval events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IntervalFlags"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/IntervalFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IntervalFlags"
        }
      ],
      "role": "symbol",
      "title": "DispatchIO.IntervalFlags",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio/intervalflags"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/IntervalFlags/strictInterval": {
      "abstract": [
        {
          "text": "Enqueue handlers for a channel at strict intervals regardless of how much data has been read or written.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strictInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_io",
          "text": "DispatchIO"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So14OS_dispatch_ioC8DispatchE13IntervalFlagsV",
          "text": "IntervalFlags"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/IntervalFlags/strictInterval",
      "kind": "symbol",
      "role": "symbol",
      "title": "strictInterval",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio/intervalflags/strictinterval"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/fileDescriptor": {
      "abstract": [
        {
          "text": "Returns the file descriptor associated with the specified channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileDescriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/fileDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_io_get_descriptor"
        }
      ],
      "role": "symbol",
      "title": "fileDescriptor",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio/filedescriptor"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setInterval(interval:flags:)": {
      "abstract": [
        {
          "text": "Sets the interval, in nanoseconds, at which to invoke the I/O handlers for the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setInterval"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "interval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8Dispatch0A12TimeIntervalO",
          "text": "DispatchTimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_io",
          "text": "DispatchIO"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So14OS_dispatch_ioC8DispatchE13IntervalFlagsV",
          "text": "IntervalFlags"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setInterval(interval:flags:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setInterval(interval:flags:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio/setinterval(interval:flags:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(highWater:)": {
      "abstract": [
        {
          "text": "Sets the maximum number of bytes to process before enqueueing a handler block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setLimit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "highWater"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(highWater:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_io_set_high_water"
        }
      ],
      "role": "symbol",
      "title": "setLimit(highWater:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio/setlimit(highwater:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(lowWater:)": {
      "abstract": [
        {
          "text": "Sets the minimum number of bytes to process before enqueueing a handler block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setLimit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "lowWater"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(lowWater:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dispatch_io_set_low_water"
        }
      ],
      "role": "symbol",
      "title": "setLimit(lowWater:)",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchio/setlimit(lowwater:)"
    },
    "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval": {
      "abstract": [
        {
          "text": "A number of seconds, millisconds, microseconds, or nanoseconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DispatchTimeInterval"
        }
      ],
      "identifier": "doc://com.apple.dispatch/documentation/Dispatch/DispatchTimeInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DispatchTimeInterval"
        }
      ],
      "role": "symbol",
      "title": "DispatchTimeInterval",
      "type": "topic",
      "url": "/documentation/dispatch/dispatchtimeinterval"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-File-Descriptor",
      "generated": true,
      "identifiers": [
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/fileDescriptor",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(highWater:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/setLimit(lowWater:)",
        "doc://com.apple.dispatch/documentation/Dispatch/DispatchIO/IntervalFlags"
      ],
      "title": "Managing the File Descriptor"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1setLimit(highWater:)/title",
          "value": "dispatch_io_set_high_water"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1setLimit(highWater:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_set_high_water"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1fileDescriptor/title",
          "value": "dispatch_io_get_descriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1fileDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_get_descriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1setLimit(lowWater:)/title",
          "value": "dispatch_io_set_low_water"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.dispatch~1documentation~1Dispatch~1DispatchIO~1setLimit(lowWater:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dispatch_io_set_low_water"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/dispatch/dispatchio/setinterval(interval:flags:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
