{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.opendirectory/documentation/OpenDirectory",
        "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecord"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecord/secondsUntilAuthenticationsExpire"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ODRecord(py)secondsUntilAuthenticationsExpire",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "secondsUntilAuthenticationsExpire"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int64V",
        "text": "Int64"
      }
    ],
    "modules": [
      {
        "name": "Open Directory"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "secondsUntilAuthenticationsExpire"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "secondsUntilAuthenticationsExpire"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "secondsUntilAuthenticationsExpire"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int64V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int64V",
              "text": "Int64"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory": {
      "abstract": [
        {
          "text": "Authenticate users, and search for contact information in Open Directory and LDAP directories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory",
      "kind": "symbol",
      "role": "collection",
      "title": "Open Directory",
      "type": "topic",
      "url": "/documentation/opendirectory"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecord": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "code": "ODRecord",
          "type": "codeVoice"
        },
        {
          "text": " object serves as a Cocoa wrapper for an Open Directory record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ODRecord"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ODRecord"
        }
      ],
      "role": "symbol",
      "title": "ODRecord",
      "type": "topic",
      "url": "/documentation/opendirectory/odrecord"
    },
    "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecord/secondsUntilAuthenticationsExpire": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondsUntilAuthenticationsExpire"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecord/secondsUntilAuthenticationsExpire",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "secondsUntilAuthenticationsExpire"
        }
      ],
      "role": "symbol",
      "title": "secondsUntilAuthenticationsExpire",
      "type": "topic",
      "url": "/documentation/opendirectory/odrecord/secondsuntilauthenticationsexpire"
    },
    "doc://com.externally.resolved.symbol/s:s5Int64V": {
      "abstract": [
        {
          "text": "A 64-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int64V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int64",
      "type": "topic",
      "url": "/documentation/Swift/Int64"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "secondsUntilAuthenticationsExpire"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "secondsUntilAuthenticationsExpire"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.opendirectory/documentation/OpenDirectory",
                "doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecord"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@int64_t",
                    "text": "int64_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "secondsUntilAuthenticationsExpire"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecord/title",
          "value": "ODRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ODRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecord~1secondsUntilAuthenticationsExpire/title",
          "value": "secondsUntilAuthenticationsExpire"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecord~1secondsUntilAuthenticationsExpire/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "secondsUntilAuthenticationsExpire"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/opendirectory/odrecord/secondsuntilauthenticationsexpire"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/opendirectory/odrecord/secondsuntilauthenticationsexpire"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
