{
  "abstract": [
    {
      "text": "Constants that reflect the type of units to use in the string.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "MapKit",
    "externalID": "c:@E@MKDistanceFormatterUnits",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Units"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Units"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MKDistanceFormatter.Units"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Units"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter": {
      "abstract": [
        {
          "text": "A utility object that converts between a geographic distance and a string-based expression of that distance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKDistanceFormatter"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKDistanceFormatter"
        }
      ],
      "role": "symbol",
      "title": "MKDistanceFormatter",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/DistanceUnitStyle": {
      "abstract": [
        {
          "text": "Constants that indicate the format style to use for strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DistanceUnitStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/DistanceUnitStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DistanceUnitStyle"
        }
      ],
      "role": "symbol",
      "title": "MKDistanceFormatter.DistanceUnitStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter/distanceunitstyle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum": {
      "abstract": [
        {
          "text": "Constants that reflect the type of units to use in the string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Units"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Units"
        }
      ],
      "role": "symbol",
      "title": "MKDistanceFormatter.Units",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter/units-swift.enum"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/default": {
      "abstract": [
        {
          "text": "The format uses the locale information to determine which units to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKDistanceFormatterUnitsDefault"
        }
      ],
      "role": "symbol",
      "title": "MKDistanceFormatter.Units.default",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter/units-swift.enum/default"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperial": {
      "abstract": [
        {
          "text": "The format uses imperial units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imperial"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKDistanceFormatterUnitsImperial"
        }
      ],
      "role": "symbol",
      "title": "MKDistanceFormatter.Units.imperial",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter/units-swift.enum/imperial"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperialWithYards": {
      "abstract": [
        {
          "text": "The format uses imperial units that include measurements in yards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imperialWithYards"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperialWithYards",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKDistanceFormatterUnitsImperialWithYards"
        }
      ],
      "role": "symbol",
      "title": "MKDistanceFormatter.Units.imperialWithYards",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter/units-swift.enum/imperialwithyards"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter/units-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/metric": {
      "abstract": [
        {
          "text": "The format uses metric units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metric"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/metric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKDistanceFormatterUnitsMetric"
        }
      ],
      "role": "symbol",
      "title": "MKDistanceFormatter.Units.metric",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter/units-swift.enum/metric"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/locale": {
      "abstract": [
        {
          "text": "The locale to use when formatting strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/locale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locale"
        }
      ],
      "role": "symbol",
      "title": "locale",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter/locale"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/unitStyle": {
      "abstract": [
        {
          "text": "The preferred style for units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unitStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKDistanceFormatter",
          "text": "MKDistanceFormatter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKDistanceFormatterUnitStyle",
          "text": "DistanceUnitStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/unitStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unitStyle"
        }
      ],
      "role": "symbol",
      "title": "unitStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter/unitstyle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/units-swift.property": {
      "abstract": [
        {
          "text": "The measuring system — imperial or metric — to use for units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "units"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKDistanceFormatter",
          "text": "MKDistanceFormatter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKDistanceFormatterUnits",
          "text": "Units"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/units-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "units"
        }
      ],
      "role": "symbol",
      "title": "units",
      "type": "topic",
      "url": "/documentation/mapkit/mkdistanceformatter/units-swift.property"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-the-format",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/locale",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/units-swift.property",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/unitStyle",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/DistanceUnitStyle"
      ],
      "title": "Specifying the format"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/default",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/metric",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperial",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperialWithYards",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/default",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/metric",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperial",
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperialWithYards"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKDistanceFormatterUnits"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatterUnits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatterUnits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/default",
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/metric",
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperial",
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperialWithYards",
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/default",
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/metric",
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperial",
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/Units-swift.enum/imperialWithYards"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-the-format",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/locale",
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/units-swift.property",
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/unitStyle",
                "doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter/DistanceUnitStyle"
              ],
              "title": "Specifying the format"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKDistanceFormatterUnits"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1DistanceUnitStyle/title",
          "value": "MKDistanceFormatterUnitStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1DistanceUnitStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatterUnitStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1DistanceUnitStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatterUnitStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter/title",
          "value": "MKDistanceFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum~1imperialWithYards/title",
          "value": "MKDistanceFormatterUnitsImperialWithYards"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum~1imperialWithYards/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatterUnitsImperialWithYards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1units-swift.property/title",
          "value": "units"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1units-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "units"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum/title",
          "value": "MKDistanceFormatterUnits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatterUnits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatterUnits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum~1imperial/title",
          "value": "MKDistanceFormatterUnitsImperial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum~1imperial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatterUnitsImperial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1locale/title",
          "value": "locale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1locale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "locale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum~1default/title",
          "value": "MKDistanceFormatterUnitsDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatterUnitsDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1unitStyle/title",
          "value": "unitStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1unitStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "unitStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum~1metric/title",
          "value": "MKDistanceFormatterUnitsMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter~1Units-swift.enum~1metric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKDistanceFormatterUnitsMetric"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkdistanceformatter/units-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkdistanceformatter/units-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
