{
  "abstract": [
    {
      "text": "A string containing the width and height of the image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages/UILaunchImageSize"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.UILaunchImages.UILaunchImageSize",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UILaunchImageSize"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "UILaunchImageSize"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "UILaunchImageSize",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This string represents the size of the display for which the image is intended. You must specify the width and height with respect to the device in a portrait orientation. In other words, portrait and landscape images targeting the same device would have the same width and height.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The format of this string is {",
              "type": "text"
            },
            {
              "code": "width, height",
              "type": "codeVoice"
            },
            {
              "text": "} where width and height are the size of the image in points. For example, the string {320, 480} specifies an image that can be used on an iPhone 4 or iPhone 4S.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you do not specify this key, the image size is assumed to be {320, 480}.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages": {
      "abstract": [
        {
          "text": "A dictionary containing information about launch images.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages",
      "kind": "symbol",
      "name": "UILaunchImages",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchImages"
        }
      ],
      "role": "symbol",
      "title": "UILaunchImages",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchimages"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages/UILaunchImageMinimumOSVersion": {
      "abstract": [
        {
          "text": "A string representing the minimum iOS version number for which the image is intended.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages/UILaunchImageMinimumOSVersion",
      "kind": "symbol",
      "name": "UILaunchImageMinimumOSVersion",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchImageMinimumOSVersion"
        }
      ],
      "role": "symbol",
      "title": "UILaunchImageMinimumOSVersion",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchimages/uilaunchimageminimumosversion"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages/UILaunchImageName": {
      "abstract": [
        {
          "text": "A string containing the name of the image file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages/UILaunchImageName",
      "kind": "symbol",
      "name": "UILaunchImageName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchImageName"
        }
      ],
      "role": "symbol",
      "title": "UILaunchImageName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchimages/uilaunchimagename"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages/UILaunchImageOrientation": {
      "abstract": [
        {
          "text": "A string containing the orientation of the image",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages/UILaunchImageOrientation",
      "kind": "symbol",
      "name": "UILaunchImageOrientation",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchImageOrientation"
        }
      ],
      "role": "symbol",
      "title": "UILaunchImageOrientation",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchimages/uilaunchimageorientation"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages/UILaunchImageSize": {
      "abstract": [
        {
          "text": "A string containing the width and height of the image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages/UILaunchImageSize",
      "kind": "symbol",
      "name": "UILaunchImageSize",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILaunchImageSize"
        }
      ],
      "role": "symbol",
      "title": "UILaunchImageSize",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uilaunchimages/uilaunchimagesize"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Launch-Image-Configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages/UILaunchImageMinimumOSVersion",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages/UILaunchImageName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages/UILaunchImageOrientation"
      ],
      "title": "Launch Image Configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UILaunchImageSize"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchImageSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Launch-Image-Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages/UILaunchImageMinimumOSVersion",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages/UILaunchImageName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UILaunchImages/UILaunchImageOrientation"
              ],
              "title": "Launch Image Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchImages~1UILaunchImageOrientation/title",
          "value": "UILaunchImageOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchImages~1UILaunchImageOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchImageOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchImages~1UILaunchImageMinimumOSVersion/title",
          "value": "UILaunchImageMinimumOSVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchImages~1UILaunchImageMinimumOSVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchImageMinimumOSVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchImages~1UILaunchImageSize/title",
          "value": "UILaunchImageSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchImages~1UILaunchImageSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchImageSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchImages/title",
          "value": "UILaunchImages"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchImages/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchImages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchImages~1UILaunchImageName/title",
          "value": "UILaunchImageName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UILaunchImages~1UILaunchImageName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILaunchImageName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uilaunchimages/uilaunchimagesize"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uilaunchimages/uilaunchimagesize"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
