{
  "abstract": [
    {
      "text": "The entry was tagged with a hint indicating the system should try to preserve it for approximately 3 days.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.oslog/documentation/OSLog",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntry",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm3"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@OSLogEntryStoreCategory@OSLogEntryStoreCategoryLongTerm3",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "longTerm3"
      }
    ],
    "modules": [
      {
        "name": "OSLog"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OSLogEntryStoreCategoryLongTerm3"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "OSLogEntry.StoreCategory.longTerm3"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "longTerm3"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "It was persisted in the filesystem-backed date store, and rotation of these entries was based on both time and space considerations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.oslog/documentation/OSLog": {
      "abstract": [
        {
          "text": "A unified logging system for the reading of historical data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog",
      "kind": "symbol",
      "role": "collection",
      "title": "OSLog",
      "type": "topic",
      "url": "/documentation/oslog"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry": {
      "abstract": [
        {
          "text": "A single entry from the unified logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogEntry"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntry"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntry",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum": {
      "abstract": [
        {
          "text": "A classification of how the entry was to be stored and rotated at the point when it was created.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StoreCategory"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StoreCategory"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntry.StoreCategory",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry/storecategory-swift.enum"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm1": {
      "abstract": [
        {
          "text": "The entry was tagged with a hint indicating the system should try to preserve it for approximately 1 day.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "longTerm1"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryStoreCategoryLongTerm1"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntry.StoreCategory.longTerm1",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry/storecategory-swift.enum/longterm1"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm14": {
      "abstract": [
        {
          "text": "The entry was tagged with a hint indicating the system should try to preserve it for approximately 14 days.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "longTerm14"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm14",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryStoreCategoryLongTerm14"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntry.StoreCategory.longTerm14",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry/storecategory-swift.enum/longterm14"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm3": {
      "abstract": [
        {
          "text": "The entry was tagged with a hint indicating the system should try to preserve it for approximately 3 days.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "longTerm3"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryStoreCategoryLongTerm3"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntry.StoreCategory.longTerm3",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry/storecategory-swift.enum/longterm3"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm30": {
      "abstract": [
        {
          "text": "The entry was tagged with a hint indicating the system should try to preserve it for approximately 30 days.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "longTerm30"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm30",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryStoreCategoryLongTerm30"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntry.StoreCategory.longTerm30",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry/storecategory-swift.enum/longterm30"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm7": {
      "abstract": [
        {
          "text": "The entry was tagged with a hint indicating the system should try to preserve it for approximately 7 days.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "longTerm7"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryStoreCategoryLongTerm7"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntry.StoreCategory.longTerm7",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry/storecategory-swift.enum/longterm7"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTermAuto": {
      "abstract": [
        {
          "text": "The entry was tagged with a hint indicating the system should try to preserve it based on the amount of space available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "longTermAuto"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTermAuto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryStoreCategoryLongTermAuto"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntry.StoreCategory.longTermAuto",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry/storecategory-swift.enum/longtermauto"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/metadata": {
      "abstract": [
        {
          "text": "This entry was generated as information about the other entries or about the sequence of entries as a whole.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryStoreCategoryMetadata"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntry.StoreCategory.metadata",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry/storecategory-swift.enum/metadata"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/shortTerm": {
      "abstract": [
        {
          "text": "This entry was not intended to be long-lived, and was captured in the ring buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shortTerm"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/shortTerm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryStoreCategoryShortTerm"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntry.StoreCategory.shortTerm",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry/storecategory-swift.enum/shortterm"
    },
    "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/undefined": {
      "abstract": [
        {
          "text": "This entry’s purpose is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undefined"
        }
      ],
      "identifier": "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/undefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogEntryStoreCategoryUndefined"
        }
      ],
      "role": "symbol",
      "title": "OSLogEntry.StoreCategory.undefined",
      "type": "topic",
      "url": "/documentation/oslog/oslogentry/storecategory-swift.enum/undefined"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/undefined",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/metadata",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/shortTerm",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTermAuto",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm1",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm7",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm14",
        "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm30"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "OSLogEntryStoreCategoryLongTerm3"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryStoreCategoryLongTerm3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.oslog/documentation/OSLog",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/undefined",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/metadata",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/shortTerm",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTermAuto",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm1",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm7",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm14",
                "doc://com.apple.oslog/documentation/OSLog/OSLogEntry/StoreCategory-swift.enum/longTerm30"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "OSLogEntryStoreCategoryLongTerm3"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1shortTerm/title",
          "value": "OSLogEntryStoreCategoryShortTerm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1shortTerm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryStoreCategoryShortTerm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum/title",
          "value": "OSLogEntryStoreCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryStoreCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryStoreCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry/title",
          "value": "OSLogEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1longTerm3/title",
          "value": "OSLogEntryStoreCategoryLongTerm3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1longTerm3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryStoreCategoryLongTerm3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1metadata/title",
          "value": "OSLogEntryStoreCategoryMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryStoreCategoryMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1undefined/title",
          "value": "OSLogEntryStoreCategoryUndefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1undefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryStoreCategoryUndefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1longTerm30/title",
          "value": "OSLogEntryStoreCategoryLongTerm30"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1longTerm30/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryStoreCategoryLongTerm30"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1longTermAuto/title",
          "value": "OSLogEntryStoreCategoryLongTermAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1longTermAuto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryStoreCategoryLongTermAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1longTerm7/title",
          "value": "OSLogEntryStoreCategoryLongTerm7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1longTerm7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryStoreCategoryLongTerm7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1longTerm14/title",
          "value": "OSLogEntryStoreCategoryLongTerm14"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1longTerm14/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryStoreCategoryLongTerm14"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1longTerm1/title",
          "value": "OSLogEntryStoreCategoryLongTerm1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.oslog~1documentation~1OSLog~1OSLogEntry~1StoreCategory-swift.enum~1longTerm1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OSLogEntryStoreCategoryLongTerm1"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/oslog/oslogentry/storecategory-swift.enum/longterm3"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/oslog/oslogentry/storecategory-swift.enum/longterm3"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
