{
  "abstract": [
    {
      "text": "Options for animating views using block objects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UIViewAnimationOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AnimationOptions"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AnimationOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "UIView.AnimationOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AnimationOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Axis": {
      "abstract": [
        {
          "text": "Keys that specify a horizontal or vertical layout constraint between objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Axis"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Axis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Axis"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Axis",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/axis"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute": {
      "abstract": [
        {
          "text": "A semantic description of the view’s contents, used to determine whether the view should be flipped when switching between left-to-right and right-to-left layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISemanticContentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISemanticContentAttribute"
        }
      ],
      "role": "symbol",
      "title": "UISemanticContentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/uisemanticcontentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve": {
      "abstract": [
        {
          "text": "Specifies the supported animation curves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationCurve"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationCurve"
        }
      ],
      "role": "symbol",
      "title": "UIView.AnimationCurve",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationcurve"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions": {
      "abstract": [
        {
          "text": "Options for animating views using block objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationOptions"
        }
      ],
      "role": "symbol",
      "title": "UIView.AnimationOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/allowAnimatedContent": {
      "abstract": [
        {
          "text": "Animate the views by changing the property values dynamically and redrawing the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowAnimatedContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/allowAnimatedContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionAllowAnimatedContent"
        }
      ],
      "role": "symbol",
      "title": "allowAnimatedContent",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/allowanimatedcontent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/allowUserInteraction": {
      "abstract": [
        {
          "text": "Allow the user to interact with views while they are being animated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowUserInteraction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/allowUserInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionAllowUserInteraction"
        }
      ],
      "role": "symbol",
      "title": "allowUserInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/allowuserinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/autoreverse": {
      "abstract": [
        {
          "text": "Run the animation backwards and forwards (must be combined with the repeat option).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoreverse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/autoreverse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionAutoreverse"
        }
      ],
      "role": "symbol",
      "title": "autoreverse",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/autoreverse"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/beginFromCurrentState": {
      "abstract": [
        {
          "text": "Start the animation from the current setting associated with an already in-flight animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginFromCurrentState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/beginFromCurrentState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionBeginFromCurrentState"
        }
      ],
      "role": "symbol",
      "title": "beginFromCurrentState",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/beginfromcurrentstate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseIn": {
      "abstract": [
        {
          "text": "An ease-in curve causes the animation to begin slowly, and then speed up as it progresses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "curveEaseIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionCurveEaseIn"
        }
      ],
      "role": "symbol",
      "title": "curveEaseIn",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/curveeasein"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseInOut": {
      "abstract": [
        {
          "text": "Specify an ease-in ease-out curve, which causes the animation to begin slowly, accelerate through the middle of its duration, and then slow again before completing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "curveEaseInOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseInOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionCurveEaseInOut"
        }
      ],
      "role": "symbol",
      "title": "curveEaseInOut",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/curveeaseinout"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseOut": {
      "abstract": [
        {
          "text": "An ease-out curve causes the animation to begin quickly, and then slow as it completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "curveEaseOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionCurveEaseOut"
        }
      ],
      "role": "symbol",
      "title": "curveEaseOut",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/curveeaseout"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveLinear": {
      "abstract": [
        {
          "text": "A linear animation curve causes an animation to occur evenly over its duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "curveLinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionCurveLinear"
        }
      ],
      "role": "symbol",
      "title": "curveLinear",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/curvelinear"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates an animation options structure with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/layoutSubviews": {
      "abstract": [
        {
          "text": "Lay out subviews at commit time so that they are animated along with their parent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutSubviews"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/layoutSubviews",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionLayoutSubviews"
        }
      ],
      "role": "symbol",
      "title": "layoutSubviews",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/layoutsubviews"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedCurve": {
      "abstract": [
        {
          "text": "Force the animation to use the original curve value specified when the animation was submitted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overrideInheritedCurve"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionOverrideInheritedCurve"
        }
      ],
      "role": "symbol",
      "title": "overrideInheritedCurve",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/overrideinheritedcurve"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedDuration": {
      "abstract": [
        {
          "text": "Force the animation to use the original duration value specified when the animation was submitted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overrideInheritedDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionOverrideInheritedDuration"
        }
      ],
      "role": "symbol",
      "title": "overrideInheritedDuration",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/overrideinheritedduration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedOptions": {
      "abstract": [
        {
          "text": "The option to not inherit the animation type or any options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overrideInheritedOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionOverrideInheritedOptions"
        }
      ],
      "role": "symbol",
      "title": "overrideInheritedOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/overrideinheritedoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/preferredFramesPerSecond30": {
      "abstract": [
        {
          "text": "A frame rate of 30 frames per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredFramesPerSecond30"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/preferredFramesPerSecond30",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionPreferredFramesPerSecond30"
        }
      ],
      "role": "symbol",
      "title": "preferredFramesPerSecond30",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/preferredframespersecond30"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/preferredFramesPerSecond60": {
      "abstract": [
        {
          "text": "A frame rate of 60 frames per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredFramesPerSecond60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/preferredFramesPerSecond60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionPreferredFramesPerSecond60"
        }
      ],
      "role": "symbol",
      "title": "preferredFramesPerSecond60",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/preferredframespersecond60"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/repeat": {
      "abstract": [
        {
          "text": "Repeat the animation indefinitely.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`repeat`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/repeat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionRepeat"
        }
      ],
      "role": "symbol",
      "title": "repeat",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/repeat"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/showHideTransitionViews": {
      "abstract": [
        {
          "text": "Hide or show views during a view transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showHideTransitionViews"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/showHideTransitionViews",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionShowHideTransitionViews"
        }
      ],
      "role": "symbol",
      "title": "showHideTransitionViews",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/showhidetransitionviews"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionCrossDissolve": {
      "abstract": [
        {
          "text": "A transition that dissolves from one view to the next.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transitionCrossDissolve"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionCrossDissolve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionTransitionCrossDissolve"
        }
      ],
      "role": "symbol",
      "title": "transitionCrossDissolve",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/transitioncrossdissolve"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionCurlDown": {
      "abstract": [
        {
          "text": "A transition that curls a view down from the top.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transitionCurlDown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionCurlDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionTransitionCurlDown"
        }
      ],
      "role": "symbol",
      "title": "transitionCurlDown",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/transitioncurldown"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionCurlUp": {
      "abstract": [
        {
          "text": "A transition that curls a view up from the bottom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transitionCurlUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionCurlUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionTransitionCurlUp"
        }
      ],
      "role": "symbol",
      "title": "transitionCurlUp",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/transitioncurlup"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromBottom": {
      "abstract": [
        {
          "text": "A transition that flips a view around its horizontal axis from bottom to top (the bottom side of the view moves toward the front and the top side toward the back).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transitionFlipFromBottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromBottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionTransitionFlipFromBottom"
        }
      ],
      "role": "symbol",
      "title": "transitionFlipFromBottom",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/transitionflipfrombottom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromLeft": {
      "abstract": [
        {
          "text": "A transition that flips a view around its vertical axis from left to right (the left side of the view moves toward the front and right side toward the back).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transitionFlipFromLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionTransitionFlipFromLeft"
        }
      ],
      "role": "symbol",
      "title": "transitionFlipFromLeft",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/transitionflipfromleft"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromRight": {
      "abstract": [
        {
          "text": "A transition that flips a view around its vertical axis from right to left (the right side of the view moves toward the front and left side toward the back).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transitionFlipFromRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionTransitionFlipFromRight"
        }
      ],
      "role": "symbol",
      "title": "transitionFlipFromRight",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/transitionflipfromright"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromTop": {
      "abstract": [
        {
          "text": "A transition that flips a view around its horizontal axis from top to bottom (the top side of the view moves toward the front and the bottom side toward the back).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transitionFlipFromTop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationOptions",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromTop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionTransitionFlipFromTop"
        }
      ],
      "role": "symbol",
      "title": "transitionFlipFromTop",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions/transitionflipfromtop"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationTransition": {
      "abstract": [
        {
          "text": "Animation transition options for use in an animation block object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationTransition"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationTransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationTransition"
        }
      ],
      "role": "symbol",
      "title": "UIView.AnimationTransition",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationtransition"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct": {
      "abstract": [
        {
          "text": "Options for automatic view resizing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AutoresizingMask"
        }
      ],
      "role": "symbol",
      "title": "UIView.AutoresizingMask",
      "type": "topic",
      "url": "/documentation/uikit/uiview/autoresizingmask-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions": {
      "abstract": [
        {
          "text": "Options for configuring keyframe-based animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "role": "symbol",
      "title": "UIView.KeyframeAnimationOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/SystemAnimation": {
      "abstract": [
        {
          "text": "Option to remove the views from the hierarchy when animation is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SystemAnimation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/SystemAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SystemAnimation"
        }
      ],
      "role": "symbol",
      "title": "UIView.SystemAnimation",
      "type": "topic",
      "url": "/documentation/uikit/uiview/systemanimation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/TintAdjustmentMode-swift.enum": {
      "abstract": [
        {
          "text": "The tint adjustment mode for the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TintAdjustmentMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/TintAdjustmentMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TintAdjustmentMode"
        }
      ],
      "role": "symbol",
      "title": "UIView.TintAdjustmentMode",
      "type": "topic",
      "url": "/documentation/uikit/uiview/tintadjustmentmode-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingCompressedSize": {
      "abstract": [
        {
          "text": "The option to use the smallest possible size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutFittingCompressedSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingCompressedSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILayoutFittingCompressedSize"
        }
      ],
      "role": "symbol",
      "title": "layoutFittingCompressedSize",
      "type": "topic",
      "url": "/documentation/uikit/uiview/layoutfittingcompressedsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingExpandedSize": {
      "abstract": [
        {
          "text": "The option to use the largest possible size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutFittingExpandedSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingExpandedSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILayoutFittingExpandedSize"
        }
      ],
      "role": "symbol",
      "title": "layoutFittingExpandedSize",
      "type": "topic",
      "url": "/documentation/uikit/uiview/layoutfittingexpandedsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/noIntrinsicMetric": {
      "abstract": [
        {
          "text": "The absence of an intrinsic metric for a given numeric view property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noIntrinsicMetric"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/noIntrinsicMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewNoIntrinsicMetric"
        }
      ],
      "role": "symbol",
      "title": "noIntrinsicMetric",
      "type": "topic",
      "url": "/documentation/uikit/uiview/nointrinsicmetric"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewAnimationOptions/UIViewAnimationOptionPreferredFramesPerSecondDefault": {
      "abstract": [
        {
          "text": "The default number of frames per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionPreferredFramesPerSecondDefault"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimationOptions/UIViewAnimationOptionPreferredFramesPerSecondDefault",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIViewAnimationOptionPreferredFramesPerSecondDefault",
      "type": "topic",
      "url": "/documentation/uikit/uiviewanimationoptions/uiviewanimationoptionpreferredframesperseconddefault"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewAnimationOptions/UIViewAnimationOptionTransitionNone": {
      "abstract": [
        {
          "text": "No transition is specified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIViewAnimationOptionTransitionNone"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimationOptions/UIViewAnimationOptionTransitionNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIViewAnimationOptionTransitionNone",
      "type": "topic",
      "url": "/documentation/uikit/uiviewanimationoptions/uiviewanimationoptiontransitionnone"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationTransition",
        "doc://com.apple.uikit/documentation/UIKit/UIView/SystemAnimation",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Axis",
        "doc://com.apple.uikit/documentation/UIKit/UIView/TintAdjustmentMode-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingCompressedSize",
        "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingExpandedSize",
        "doc://com.apple.uikit/documentation/UIKit/UIView/noIntrinsicMetric",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/layoutSubviews",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/allowUserInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/beginFromCurrentState",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/repeat",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/autoreverse",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedDuration",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedCurve",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/allowAnimatedContent",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/showHideTransitionViews",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedOptions",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseInOut",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseIn",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseOut",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveLinear",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromLeft",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromRight",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionCurlUp",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionCurlDown",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionCrossDissolve",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromTop",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromBottom",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/preferredFramesPerSecond30",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/preferredFramesPerSecond60"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIViewAnimationOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/layoutSubviews",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/allowUserInteraction",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/beginFromCurrentState",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/repeat",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/autoreverse",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedDuration",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedCurve",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/allowAnimatedContent",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/showHideTransitionViews",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/overrideInheritedOptions",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseInOut",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseIn",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveEaseOut",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/curveLinear",
                "doc://com.apple.uikit/documentation/UIKit/UIViewAnimationOptions/UIViewAnimationOptionTransitionNone",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromLeft",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromRight",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionCurlUp",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionCurlDown",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionCrossDissolve",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromTop",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/transitionFlipFromBottom",
                "doc://com.apple.uikit/documentation/UIKit/UIViewAnimationOptions/UIViewAnimationOptionPreferredFramesPerSecondDefault",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/preferredFramesPerSecond30",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions/preferredFramesPerSecond60"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationTransition",
                "doc://com.apple.uikit/documentation/UIKit/UIView/SystemAnimation",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Axis",
                "doc://com.apple.uikit/documentation/UIKit/UIView/TintAdjustmentMode-swift.enum",
                "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingCompressedSize",
                "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingExpandedSize",
                "doc://com.apple.uikit/documentation/UIKit/UIView/noIntrinsicMetric",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct",
                "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIViewAnimationOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1preferredFramesPerSecond30/title",
          "value": "UIViewAnimationOptionPreferredFramesPerSecond30"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1preferredFramesPerSecond30/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionPreferredFramesPerSecond30"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1allowUserInteraction/title",
          "value": "UIViewAnimationOptionAllowUserInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1allowUserInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionAllowUserInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionFlipFromLeft/title",
          "value": "UIViewAnimationOptionTransitionFlipFromLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionFlipFromLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionTransitionFlipFromLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionFlipFromRight/title",
          "value": "UIViewAnimationOptionTransitionFlipFromRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionFlipFromRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionTransitionFlipFromRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1curveEaseOut/title",
          "value": "UIViewAnimationOptionCurveEaseOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1curveEaseOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionCurveEaseOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1autoreverse/title",
          "value": "UIViewAnimationOptionAutoreverse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1autoreverse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionAutoreverse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationTransition/title",
          "value": "UIViewAnimationTransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationTransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationTransition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions/title",
          "value": "UIViewAnimationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1curveLinear/title",
          "value": "UIViewAnimationOptionCurveLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1curveLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionCurveLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionCurlUp/title",
          "value": "UIViewAnimationOptionTransitionCurlUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionCurlUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionTransitionCurlUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct/title",
          "value": "UIViewAutoresizing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAutoresizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAutoresizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1layoutFittingCompressedSize/title",
          "value": "UILayoutFittingCompressedSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1layoutFittingCompressedSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILayoutFittingCompressedSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1overrideInheritedCurve/title",
          "value": "UIViewAnimationOptionOverrideInheritedCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1overrideInheritedCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionOverrideInheritedCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1beginFromCurrentState/title",
          "value": "UIViewAnimationOptionBeginFromCurrentState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1beginFromCurrentState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionBeginFromCurrentState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionCrossDissolve/title",
          "value": "UIViewAnimationOptionTransitionCrossDissolve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionCrossDissolve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionTransitionCrossDissolve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1noIntrinsicMetric/title",
          "value": "UIViewNoIntrinsicMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1noIntrinsicMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewNoIntrinsicMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1SystemAnimation/title",
          "value": "UISystemAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1SystemAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISystemAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1SystemAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISystemAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1overrideInheritedOptions/title",
          "value": "UIViewAnimationOptionOverrideInheritedOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1overrideInheritedOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionOverrideInheritedOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute/title",
          "value": "UISemanticContentAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1preferredFramesPerSecond60/title",
          "value": "UIViewAnimationOptionPreferredFramesPerSecond60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1preferredFramesPerSecond60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionPreferredFramesPerSecond60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationCurve/title",
          "value": "UIViewAnimationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1curveEaseInOut/title",
          "value": "UIViewAnimationOptionCurveEaseInOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1curveEaseInOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionCurveEaseInOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1TintAdjustmentMode-swift.enum/title",
          "value": "UIViewTintAdjustmentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1TintAdjustmentMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewTintAdjustmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1TintAdjustmentMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewTintAdjustmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1repeat/title",
          "value": "UIViewAnimationOptionRepeat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1repeat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionRepeat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1layoutSubviews/title",
          "value": "UIViewAnimationOptionLayoutSubviews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1layoutSubviews/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionLayoutSubviews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionFlipFromBottom/title",
          "value": "UIViewAnimationOptionTransitionFlipFromBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionFlipFromBottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionTransitionFlipFromBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionCurlDown/title",
          "value": "UIViewAnimationOptionTransitionCurlDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionCurlDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionTransitionCurlDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Axis/title",
          "value": "UILayoutConstraintAxis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Axis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILayoutConstraintAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Axis/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILayoutConstraintAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1curveEaseIn/title",
          "value": "UIViewAnimationOptionCurveEaseIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1curveEaseIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionCurveEaseIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1showHideTransitionViews/title",
          "value": "UIViewAnimationOptionShowHideTransitionViews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1showHideTransitionViews/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionShowHideTransitionViews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions/title",
          "value": "UIViewKeyframeAnimationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionFlipFromTop/title",
          "value": "UIViewAnimationOptionTransitionFlipFromTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1transitionFlipFromTop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionTransitionFlipFromTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1overrideInheritedDuration/title",
          "value": "UIViewAnimationOptionOverrideInheritedDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1overrideInheritedDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionOverrideInheritedDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1layoutFittingExpandedSize/title",
          "value": "UILayoutFittingExpandedSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1layoutFittingExpandedSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILayoutFittingExpandedSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1allowAnimatedContent/title",
          "value": "UIViewAnimationOptionAllowAnimatedContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions~1allowAnimatedContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptionAllowAnimatedContent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiview/animationoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiview/animationoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
