{
  "abstract": [
    {
      "text": "A layout anchor representing the horizontal center of the view’s frame.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIView/centerXAnchor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:objc(cs)UIView(py)centerXAnchor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "centerXAnchor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
        "text": "NSLayoutXAxisAnchor"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "centerXAnchor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "centerXAnchor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "centerXAnchor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutXAxisAnchor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
              "text": "NSLayoutXAxisAnchor"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this anchor to create constraints with the view’s horizontal center. You can combine this anchor only with other ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutXAxisAnchor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " anchors. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutAnchor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutAnchor": {
      "abstract": [
        {
          "text": "A factory class for creating layout constraint objects using a fluent API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutAnchor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAnchor"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutAnchor",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutanchor"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutXAxisAnchor": {
      "abstract": [
        {
          "text": "A factory class for creating horizontal layout constraint objects using a fluent API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutXAxisAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutXAxisAnchor",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutxaxisanchor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/bottomAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the bottom edge of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutYAxisAnchor",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/bottomAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bottomAnchor"
        }
      ],
      "role": "symbol",
      "title": "bottomAnchor",
      "type": "topic",
      "url": "/documentation/uikit/uiview/bottomanchor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/centerXAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the horizontal center of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerXAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/centerXAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "centerXAnchor"
        }
      ],
      "role": "symbol",
      "title": "centerXAnchor",
      "type": "topic",
      "url": "/documentation/uikit/uiview/centerxanchor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/centerYAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the vertical center of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerYAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutYAxisAnchor",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/centerYAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "centerYAnchor"
        }
      ],
      "role": "symbol",
      "title": "centerYAnchor",
      "type": "topic",
      "url": "/documentation/uikit/uiview/centeryanchor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/firstBaselineAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the baseline for the topmost line of text in the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstBaselineAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutYAxisAnchor",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/firstBaselineAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "firstBaselineAnchor"
        }
      ],
      "role": "symbol",
      "title": "firstBaselineAnchor",
      "type": "topic",
      "url": "/documentation/uikit/uiview/firstbaselineanchor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/heightAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the height of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heightAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutDimension",
          "text": "NSLayoutDimension"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/heightAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "heightAnchor"
        }
      ],
      "role": "symbol",
      "title": "heightAnchor",
      "type": "topic",
      "url": "/documentation/uikit/uiview/heightanchor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/lastBaselineAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the baseline for the bottommost line of text in the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lastBaselineAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutYAxisAnchor",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/lastBaselineAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lastBaselineAnchor"
        }
      ],
      "role": "symbol",
      "title": "lastBaselineAnchor",
      "type": "topic",
      "url": "/documentation/uikit/uiview/lastbaselineanchor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/leadingAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the leading edge of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leadingAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/leadingAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leadingAnchor"
        }
      ],
      "role": "symbol",
      "title": "leadingAnchor",
      "type": "topic",
      "url": "/documentation/uikit/uiview/leadinganchor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/leftAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the left edge of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/leftAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leftAnchor"
        }
      ],
      "role": "symbol",
      "title": "leftAnchor",
      "type": "topic",
      "url": "/documentation/uikit/uiview/leftanchor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/rightAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the right edge of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/rightAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rightAnchor"
        }
      ],
      "role": "symbol",
      "title": "rightAnchor",
      "type": "topic",
      "url": "/documentation/uikit/uiview/rightanchor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/topAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the top edge of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutYAxisAnchor",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/topAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "topAnchor"
        }
      ],
      "role": "symbol",
      "title": "topAnchor",
      "type": "topic",
      "url": "/documentation/uikit/uiview/topanchor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/trailingAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the trailing edge of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailingAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/trailingAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trailingAnchor"
        }
      ],
      "role": "symbol",
      "title": "trailingAnchor",
      "type": "topic",
      "url": "/documentation/uikit/uiview/trailinganchor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/widthAnchor": {
      "abstract": [
        {
          "text": "A layout anchor representing the width of the view’s frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widthAnchor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutDimension",
          "text": "NSLayoutDimension"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/widthAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widthAnchor"
        }
      ],
      "role": "symbol",
      "title": "widthAnchor",
      "type": "topic",
      "url": "/documentation/uikit/uiview/widthanchor"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-constraints-using-layout-anchors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/bottomAnchor",
        "doc://com.apple.uikit/documentation/UIKit/UIView/centerYAnchor",
        "doc://com.apple.uikit/documentation/UIKit/UIView/firstBaselineAnchor",
        "doc://com.apple.uikit/documentation/UIKit/UIView/heightAnchor",
        "doc://com.apple.uikit/documentation/UIKit/UIView/lastBaselineAnchor",
        "doc://com.apple.uikit/documentation/UIKit/UIView/leadingAnchor",
        "doc://com.apple.uikit/documentation/UIKit/UIView/leftAnchor",
        "doc://com.apple.uikit/documentation/UIKit/UIView/rightAnchor",
        "doc://com.apple.uikit/documentation/UIKit/UIView/topAnchor",
        "doc://com.apple.uikit/documentation/UIKit/UIView/trailingAnchor",
        "doc://com.apple.uikit/documentation/UIKit/UIView/widthAnchor"
      ],
      "title": "Creating constraints using layout anchors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "centerXAnchor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "centerXAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-constraints-using-layout-anchors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIView/bottomAnchor",
                "doc://com.apple.uikit/documentation/UIKit/UIView/centerYAnchor",
                "doc://com.apple.uikit/documentation/UIKit/UIView/firstBaselineAnchor",
                "doc://com.apple.uikit/documentation/UIKit/UIView/heightAnchor",
                "doc://com.apple.uikit/documentation/UIKit/UIView/lastBaselineAnchor",
                "doc://com.apple.uikit/documentation/UIKit/UIView/leadingAnchor",
                "doc://com.apple.uikit/documentation/UIKit/UIView/leftAnchor",
                "doc://com.apple.uikit/documentation/UIKit/UIView/rightAnchor",
                "doc://com.apple.uikit/documentation/UIKit/UIView/topAnchor",
                "doc://com.apple.uikit/documentation/UIKit/UIView/trailingAnchor",
                "doc://com.apple.uikit/documentation/UIKit/UIView/widthAnchor"
              ],
              "title": "Creating constraints using layout anchors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutXAxisAnchor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSLayoutXAxisAnchor",
                    "text": "NSLayoutXAxisAnchor"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "centerXAnchor"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1widthAnchor/title",
          "value": "widthAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1widthAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "widthAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1leadingAnchor/title",
          "value": "leadingAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1leadingAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leadingAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1trailingAnchor/title",
          "value": "trailingAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1trailingAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trailingAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1firstBaselineAnchor/title",
          "value": "firstBaselineAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1firstBaselineAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "firstBaselineAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutXAxisAnchor/title",
          "value": "NSLayoutXAxisAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutXAxisAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutXAxisAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutXAxisAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutXAxisAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1heightAnchor/title",
          "value": "heightAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1heightAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "heightAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1rightAnchor/title",
          "value": "rightAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1rightAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1centerYAnchor/title",
          "value": "centerYAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1centerYAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "centerYAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1lastBaselineAnchor/title",
          "value": "lastBaselineAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1lastBaselineAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lastBaselineAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1topAnchor/title",
          "value": "topAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1topAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "topAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1centerXAnchor/title",
          "value": "centerXAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1centerXAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "centerXAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutAnchor/title",
          "value": "NSLayoutAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1bottomAnchor/title",
          "value": "bottomAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1bottomAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bottomAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1leftAnchor/title",
          "value": "leftAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1leftAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftAnchor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiview/centerxanchor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiview/centerxanchor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
