{
  "abstract": [
    {
      "text": "Options to specify how a view adjusts its content when its size changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UIViewContentMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ContentMode"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ContentMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIView.ContentMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ContentMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum": {
      "abstract": [
        {
          "text": "Options to specify how a view adjusts its content when its size changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ContentMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ContentMode"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottom": {
      "abstract": [
        {
          "text": "The option to center the content aligned at the bottom in the view’s bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeBottom"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.bottom",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/bottom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottomLeft": {
      "abstract": [
        {
          "text": "The option to align the content in the bottom-left corner of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomLeft"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottomLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeBottomLeft"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.bottomLeft",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/bottomleft"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottomRight": {
      "abstract": [
        {
          "text": "The option to align the content in the bottom-right corner of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomRight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottomRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeBottomRight"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.bottomRight",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/bottomright"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/center": {
      "abstract": [
        {
          "text": "The option to center the content in the view’s bounds, keeping the proportions the same.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeCenter"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.center",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/center"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/left": {
      "abstract": [
        {
          "text": "The option to align the content on the left of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeLeft"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.left",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/left"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/redraw": {
      "abstract": [
        {
          "text": "The option to redisplay the view when the bounds change by invoking the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setNeedsDisplay()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "redraw"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/redraw",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeRedraw"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.redraw",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/redraw"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/right": {
      "abstract": [
        {
          "text": "The option to align the content on the right of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeRight"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.right",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/right"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleAspectFill": {
      "abstract": [
        {
          "text": "The option to scale the content to fill the size of the view. Some portion of the content may be clipped to fill the view’s bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleAspectFill"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleAspectFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeScaleAspectFill"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.scaleAspectFill",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/scaleaspectfill"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleAspectFit": {
      "abstract": [
        {
          "text": "The option to scale the content to fit the size of the view by maintaining the aspect ratio. Any remaining area of the view’s bounds is transparent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleAspectFit"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleAspectFit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeScaleAspectFit"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.scaleAspectFit",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/scaleaspectfit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleToFill": {
      "abstract": [
        {
          "text": "The option to scale the content to fit the size of itself by changing the aspect ratio of the content if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaleToFill"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleToFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeScaleToFill"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.scaleToFill",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/scaletofill"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/top": {
      "abstract": [
        {
          "text": "The option to center the content aligned at the top in the view’s bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeTop"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.top",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/top"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/topLeft": {
      "abstract": [
        {
          "text": "The option to align the content in the top-left corner of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLeft"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/topLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeTopLeft"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.topLeft",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/topleft"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/topRight": {
      "abstract": [
        {
          "text": "The option to align the content in the top-right corner of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topRight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/topRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewContentModeTopRight"
        }
      ],
      "role": "symbol",
      "title": "UIView.ContentMode.topRight",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.enum/topright"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/autoresizesSubviews": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the receiver automatically resizes its subviews when its bounds change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoresizesSubviews"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/autoresizesSubviews",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autoresizesSubviews"
        }
      ],
      "role": "symbol",
      "title": "autoresizesSubviews",
      "type": "topic",
      "url": "/documentation/uikit/uiview/autoresizessubviews"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/autoresizingMask-swift.property": {
      "abstract": [
        {
          "text": "An integer bit mask that determines how the receiver resizes itself when its superview’s bounds change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoresizingMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAutoresizing",
          "text": "AutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/autoresizingMask-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "autoresizingMask"
        }
      ],
      "role": "symbol",
      "title": "autoresizingMask",
      "type": "topic",
      "url": "/documentation/uikit/uiview/autoresizingmask-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/contentMode-swift.property": {
      "abstract": [
        {
          "text": "A flag used to determine how a view lays out its content when its bounds change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewContentMode",
          "text": "ContentMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/contentMode-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentMode"
        }
      ],
      "role": "symbol",
      "title": "contentMode",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentmode-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/setNeedsDisplay()": {
      "abstract": [
        {
          "text": "Marks the receiver’s entire bounds rectangle as needing to be redrawn.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setNeedsDisplay"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setNeedsDisplay()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setNeedsDisplay"
        }
      ],
      "role": "symbol",
      "title": "setNeedsDisplay()",
      "type": "topic",
      "url": "/documentation/uikit/uiview/setneedsdisplay()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/sizeThatFits(_:)": {
      "abstract": [
        {
          "text": "Asks the view to calculate and return the size that best fits the specified size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sizeThatFits"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/sizeThatFits(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sizeThatFits:"
        }
      ],
      "role": "symbol",
      "title": "sizeThatFits(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/sizethatfits(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/sizeToFit()": {
      "abstract": [
        {
          "text": "Resizes and moves the receiver view so it just encloses its subviews.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sizeToFit"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/sizeToFit()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sizeToFit"
        }
      ],
      "role": "symbol",
      "title": "sizeToFit()",
      "type": "topic",
      "url": "/documentation/uikit/uiview/sizetofit()"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-resizing-behavior",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/contentMode-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIView/sizeThatFits(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/sizeToFit()",
        "doc://com.apple.uikit/documentation/UIKit/UIView/autoresizesSubviews",
        "doc://com.apple.uikit/documentation/UIKit/UIView/autoresizingMask-swift.property"
      ],
      "title": "Configuring the resizing behavior"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleToFill",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleAspectFit",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleAspectFill",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/redraw",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/center",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/top",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottom",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/left",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/right",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/topLeft",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/topRight",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottomLeft",
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottomRight"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIViewContentMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleToFill",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleAspectFit",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/scaleAspectFill",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/redraw",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/center",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/top",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottom",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/left",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/right",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/topLeft",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/topRight",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottomLeft",
                "doc://com.apple.uikit/documentation/UIKit/UIView/ContentMode-swift.enum/bottomRight"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-resizing-behavior",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIView/contentMode-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UIView/sizeThatFits(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIView/sizeToFit()",
                "doc://com.apple.uikit/documentation/UIKit/UIView/autoresizesSubviews",
                "doc://com.apple.uikit/documentation/UIKit/UIView/autoresizingMask-swift.property"
              ],
              "title": "Configuring the resizing behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIViewContentMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1autoresizesSubviews/title",
          "value": "autoresizesSubviews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1autoresizesSubviews/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autoresizesSubviews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1topLeft/title",
          "value": "UIViewContentModeTopLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1topLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeTopLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1scaleAspectFill/title",
          "value": "UIViewContentModeScaleAspectFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1scaleAspectFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeScaleAspectFill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1scaleToFill/title",
          "value": "UIViewContentModeScaleToFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1scaleToFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeScaleToFill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1contentMode-swift.property/title",
          "value": "contentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1contentMode-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1top/title",
          "value": "UIViewContentModeTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1right/title",
          "value": "UIViewContentModeRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1bottom/title",
          "value": "UIViewContentModeBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1autoresizingMask-swift.property/title",
          "value": "autoresizingMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1autoresizingMask-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "autoresizingMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1center/title",
          "value": "UIViewContentModeCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1scaleAspectFit/title",
          "value": "UIViewContentModeScaleAspectFit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1scaleAspectFit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeScaleAspectFit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1topRight/title",
          "value": "UIViewContentModeTopRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1topRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeTopRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1redraw/title",
          "value": "UIViewContentModeRedraw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1redraw/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeRedraw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum/title",
          "value": "UIViewContentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1bottomLeft/title",
          "value": "UIViewContentModeBottomLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1bottomLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeBottomLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1sizeToFit()/title",
          "value": "sizeToFit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1sizeToFit()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sizeToFit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1bottomRight/title",
          "value": "UIViewContentModeBottomRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1bottomRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeBottomRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1left/title",
          "value": "UIViewContentModeLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1ContentMode-swift.enum~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewContentModeLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setNeedsDisplay()/title",
          "value": "setNeedsDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setNeedsDisplay()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setNeedsDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1sizeThatFits(_:)/title",
          "value": "sizeThatFits:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1sizeThatFits(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sizeThatFits:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiview/contentmode-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiview/contentmode-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
