{
  "abstract": [
    {
      "text": "Options for configuring keyframe-based animations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UIViewKeyframeAnimationOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "KeyframeAnimationOptions"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "KeyframeAnimationOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "UIView.KeyframeAnimationOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "KeyframeAnimationOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these options with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/animateKeyframes(withDuration:delay:options:animations:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Axis": {
      "abstract": [
        {
          "text": "Keys that specify a horizontal or vertical layout constraint between objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Axis"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Axis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Axis"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Axis",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/axis"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute": {
      "abstract": [
        {
          "text": "A semantic description of the view’s contents, used to determine whether the view should be flipped when switching between left-to-right and right-to-left layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISemanticContentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISemanticContentAttribute"
        }
      ],
      "role": "symbol",
      "title": "UISemanticContentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/uisemanticcontentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve": {
      "abstract": [
        {
          "text": "Specifies the supported animation curves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationCurve"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationCurve"
        }
      ],
      "role": "symbol",
      "title": "UIView.AnimationCurve",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationcurve"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions": {
      "abstract": [
        {
          "text": "Options for animating views using block objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationOptions"
        }
      ],
      "role": "symbol",
      "title": "UIView.AnimationOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationTransition": {
      "abstract": [
        {
          "text": "Animation transition options for use in an animation block object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationTransition"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationTransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationTransition"
        }
      ],
      "role": "symbol",
      "title": "UIView.AnimationTransition",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationtransition"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct": {
      "abstract": [
        {
          "text": "Options for automatic view resizing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AutoresizingMask"
        }
      ],
      "role": "symbol",
      "title": "UIView.AutoresizingMask",
      "type": "topic",
      "url": "/documentation/uikit/uiview/autoresizingmask-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions": {
      "abstract": [
        {
          "text": "Options for configuring keyframe-based animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "role": "symbol",
      "title": "UIView.KeyframeAnimationOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/allowUserInteraction": {
      "abstract": [
        {
          "text": "The option that allows a person to interact with views while they’re being animated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowUserInteraction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/allowUserInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionAllowUserInteraction"
        }
      ],
      "role": "symbol",
      "title": "allowUserInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/allowuserinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/autoreverse": {
      "abstract": [
        {
          "text": "The option to run an animation backwards and forwards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoreverse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/autoreverse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionAutoreverse"
        }
      ],
      "role": "symbol",
      "title": "autoreverse",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/autoreverse"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/beginFromCurrentState": {
      "abstract": [
        {
          "text": "The option to start an animation from the current setting associated with an already in-flight animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginFromCurrentState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/beginFromCurrentState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionBeginFromCurrentState"
        }
      ],
      "role": "symbol",
      "title": "beginFromCurrentState",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/beginfromcurrentstate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeCubic": {
      "abstract": [
        {
          "text": "The option to compute intermediate frames using a default Catmull-Rom spline that passes through the keyframe values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calculationModeCubic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeCubic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionCalculationModeCubic"
        }
      ],
      "role": "symbol",
      "title": "calculationModeCubic",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/calculationmodecubic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeCubicPaced": {
      "abstract": [
        {
          "text": "The option to compute intermediate frames using the cubic scheme while ignoring the timing properties of the animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calculationModeCubicPaced"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeCubicPaced",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionCalculationModeCubicPaced"
        }
      ],
      "role": "symbol",
      "title": "calculationModeCubicPaced",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/calculationmodecubicpaced"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeDiscrete": {
      "abstract": [
        {
          "text": "The option to not interpolate between keyframe values, but rather to jump directly to each new keyframe value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calculationModeDiscrete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeDiscrete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionCalculationModeDiscrete"
        }
      ],
      "role": "symbol",
      "title": "calculationModeDiscrete",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/calculationmodediscrete"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeLinear": {
      "abstract": [
        {
          "text": "The option to use a simple linear calculation when interpolating between keyframe values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calculationModeLinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionCalculationModeLinear"
        }
      ],
      "role": "symbol",
      "title": "calculationModeLinear",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/calculationmodelinear"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModePaced": {
      "abstract": [
        {
          "text": "The option to compute intermediate keyframe values using a simple pacing algorithm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calculationModePaced"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModePaced",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionCalculationModePaced"
        }
      ],
      "role": "symbol",
      "title": "calculationModePaced",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/calculationmodepaced"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates keyframe animation options with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/layoutSubviews": {
      "abstract": [
        {
          "text": "The option to lay out subviews at commit time so that they’re animated along with their parent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutSubviews"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/layoutSubviews",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionLayoutSubviews"
        }
      ],
      "role": "symbol",
      "title": "layoutSubviews",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/layoutsubviews"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/overrideInheritedDuration": {
      "abstract": [
        {
          "text": "The option to force an animation to use the original duration value specified when the animation was submitted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overrideInheritedDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/overrideInheritedDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionOverrideInheritedDuration"
        }
      ],
      "role": "symbol",
      "title": "overrideInheritedDuration",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/overrideinheritedduration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/overrideInheritedOptions": {
      "abstract": [
        {
          "text": "The option to not inherit the animation type or any options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overrideInheritedOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/overrideInheritedOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionOverrideInheritedOptions"
        }
      ],
      "role": "symbol",
      "title": "overrideInheritedOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/overrideinheritedoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/repeat": {
      "abstract": [
        {
          "text": "The option to repeat an animation indefinitely.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`repeat`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/repeat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewKeyframeAnimationOptionRepeat"
        }
      ],
      "role": "symbol",
      "title": "repeat",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions/repeat"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/SystemAnimation": {
      "abstract": [
        {
          "text": "Option to remove the views from the hierarchy when animation is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SystemAnimation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/SystemAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SystemAnimation"
        }
      ],
      "role": "symbol",
      "title": "UIView.SystemAnimation",
      "type": "topic",
      "url": "/documentation/uikit/uiview/systemanimation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/TintAdjustmentMode-swift.enum": {
      "abstract": [
        {
          "text": "The tint adjustment mode for the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TintAdjustmentMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/TintAdjustmentMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TintAdjustmentMode"
        }
      ],
      "role": "symbol",
      "title": "UIView.TintAdjustmentMode",
      "type": "topic",
      "url": "/documentation/uikit/uiview/tintadjustmentmode-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/animateKeyframes(withDuration:delay:options:animations:completion:)": {
      "abstract": [
        {
          "text": "Creates an animation block object that can be used to set up keyframe-based animations for the current view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animateKeyframes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "delay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewKeyframeAnimationOptions",
          "text": "KeyframeAnimationOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animations"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/animateKeyframes(withDuration:delay:options:animations:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "animateKeyframesWithDuration:delay:options:animations:completion:"
        }
      ],
      "role": "symbol",
      "title": "animateKeyframes(withDuration:delay:options:animations:completion:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animatekeyframes(withduration:delay:options:animations:completion:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingCompressedSize": {
      "abstract": [
        {
          "text": "The option to use the smallest possible size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutFittingCompressedSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingCompressedSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILayoutFittingCompressedSize"
        }
      ],
      "role": "symbol",
      "title": "layoutFittingCompressedSize",
      "type": "topic",
      "url": "/documentation/uikit/uiview/layoutfittingcompressedsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingExpandedSize": {
      "abstract": [
        {
          "text": "The option to use the largest possible size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutFittingExpandedSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingExpandedSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILayoutFittingExpandedSize"
        }
      ],
      "role": "symbol",
      "title": "layoutFittingExpandedSize",
      "type": "topic",
      "url": "/documentation/uikit/uiview/layoutfittingexpandedsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/noIntrinsicMetric": {
      "abstract": [
        {
          "text": "The absence of an intrinsic metric for a given numeric view property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noIntrinsicMetric"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/noIntrinsicMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewNoIntrinsicMetric"
        }
      ],
      "role": "symbol",
      "title": "noIntrinsicMetric",
      "type": "topic",
      "url": "/documentation/uikit/uiview/nointrinsicmetric"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationTransition",
        "doc://com.apple.uikit/documentation/UIKit/UIView/SystemAnimation",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Axis",
        "doc://com.apple.uikit/documentation/UIKit/UIView/TintAdjustmentMode-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingCompressedSize",
        "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingExpandedSize",
        "doc://com.apple.uikit/documentation/UIKit/UIView/noIntrinsicMetric",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/layoutSubviews",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/allowUserInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/beginFromCurrentState",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/repeat",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/autoreverse",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/overrideInheritedDuration",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/overrideInheritedOptions",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeLinear",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeDiscrete",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModePaced",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeCubic",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeCubicPaced"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIViewKeyframeAnimationOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/layoutSubviews",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/allowUserInteraction",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/beginFromCurrentState",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/repeat",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/autoreverse",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/overrideInheritedDuration",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/overrideInheritedOptions",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeLinear",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeDiscrete",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModePaced",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeCubic",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions/calculationModeCubicPaced"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationTransition",
                "doc://com.apple.uikit/documentation/UIKit/UIView/SystemAnimation",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Axis",
                "doc://com.apple.uikit/documentation/UIKit/UIView/TintAdjustmentMode-swift.enum",
                "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingCompressedSize",
                "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingExpandedSize",
                "doc://com.apple.uikit/documentation/UIKit/UIView/noIntrinsicMetric",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct",
                "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIViewKeyframeAnimationOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1overrideInheritedDuration/title",
          "value": "UIViewKeyframeAnimationOptionOverrideInheritedDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1overrideInheritedDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionOverrideInheritedDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModeCubic/title",
          "value": "UIViewKeyframeAnimationOptionCalculationModeCubic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModeCubic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionCalculationModeCubic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions/title",
          "value": "UIViewKeyframeAnimationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1layoutFittingCompressedSize/title",
          "value": "UILayoutFittingCompressedSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1layoutFittingCompressedSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILayoutFittingCompressedSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModeCubicPaced/title",
          "value": "UIViewKeyframeAnimationOptionCalculationModeCubicPaced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModeCubicPaced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionCalculationModeCubicPaced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1repeat/title",
          "value": "UIViewKeyframeAnimationOptionRepeat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1repeat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionRepeat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1layoutFittingExpandedSize/title",
          "value": "UILayoutFittingExpandedSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1layoutFittingExpandedSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILayoutFittingExpandedSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1beginFromCurrentState/title",
          "value": "UIViewKeyframeAnimationOptionBeginFromCurrentState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1beginFromCurrentState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionBeginFromCurrentState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1layoutSubviews/title",
          "value": "UIViewKeyframeAnimationOptionLayoutSubviews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1layoutSubviews/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionLayoutSubviews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1TintAdjustmentMode-swift.enum/title",
          "value": "UIViewTintAdjustmentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1TintAdjustmentMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewTintAdjustmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1TintAdjustmentMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewTintAdjustmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Axis/title",
          "value": "UILayoutConstraintAxis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Axis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILayoutConstraintAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Axis/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILayoutConstraintAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModeLinear/title",
          "value": "UIViewKeyframeAnimationOptionCalculationModeLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModeLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionCalculationModeLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1SystemAnimation/title",
          "value": "UISystemAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1SystemAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISystemAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1SystemAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISystemAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions/title",
          "value": "UIViewAnimationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModeDiscrete/title",
          "value": "UIViewKeyframeAnimationOptionCalculationModeDiscrete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModeDiscrete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionCalculationModeDiscrete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute/title",
          "value": "UISemanticContentAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModePaced/title",
          "value": "UIViewKeyframeAnimationOptionCalculationModePaced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1calculationModePaced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionCalculationModePaced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1noIntrinsicMetric/title",
          "value": "UIViewNoIntrinsicMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1noIntrinsicMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewNoIntrinsicMetric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationTransition/title",
          "value": "UIViewAnimationTransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationTransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationTransition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1animateKeyframes(withDuration:delay:options:animations:completion:)/title",
          "value": "animateKeyframesWithDuration:delay:options:animations:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1animateKeyframes(withDuration:delay:options:animations:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "animateKeyframesWithDuration:delay:options:animations:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationCurve/title",
          "value": "UIViewAnimationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1autoreverse/title",
          "value": "UIViewKeyframeAnimationOptionAutoreverse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1autoreverse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionAutoreverse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct/title",
          "value": "UIViewAutoresizing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAutoresizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAutoresizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1overrideInheritedOptions/title",
          "value": "UIViewKeyframeAnimationOptionOverrideInheritedOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1overrideInheritedOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionOverrideInheritedOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1allowUserInteraction/title",
          "value": "UIViewKeyframeAnimationOptionAllowUserInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions~1allowUserInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptionAllowUserInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiview/keyframeanimationoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiview/keyframeanimationoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
