{
  "abstract": [
    {
      "text": "Returns the layout direction implied by the specified semantic content attribute, relative to the specified layout direction.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIView/userInterfaceLayoutDirection(for:relativeTo:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIView(cm)userInterfaceLayoutDirectionForSemanticContentAttribute:relativeToLayoutDirection:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "userInterfaceLayoutDirection"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UISemanticContentAttribute",
        "text": "UISemanticContentAttribute"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "relativeTo"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIUserInterfaceLayoutDirection",
        "text": "UIUserInterfaceLayoutDirection"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIUserInterfaceLayoutDirection",
        "text": "UIUserInterfaceLayoutDirection"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "userInterfaceLayoutDirectionForSemanticContentAttribute:relativeToLayoutDirection:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "userInterfaceLayoutDirection(for:relativeTo:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "userInterfaceLayoutDirection"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "semanticContentAttribute"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UISemanticContentAttribute",
              "text": "UISemanticContentAttribute"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "relativeTo"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "layoutDirection"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLayoutDirection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIUserInterfaceLayoutDirection",
              "text": "UIUserInterfaceLayoutDirection"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLayoutDirection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIUserInterfaceLayoutDirection",
              "text": "UIUserInterfaceLayoutDirection"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The semantic content attribute for a view.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "semanticContentAttribute"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The user interface layout direction (",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLayoutDirection/leftToRight",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLayoutDirection/rightToLeft",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ").",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "layoutDirection"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The layout direction implied by the semantic content attribute and relative to the layout direction.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For example, when this method is passed a layout direction of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLayoutDirection/rightToLeft",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and a semantic content attribute of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/playback",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", it returns ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLayoutDirection/leftToRight",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Although layout and drawing code can use this method to determine how to arrange elements, it might be easier to query the container view’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/effectiveUserInterfaceLayoutDirection",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute": {
      "abstract": [
        {
          "text": "A semantic description of the view’s contents, used to determine whether the view should be flipped when switching between left-to-right and right-to-left layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISemanticContentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISemanticContentAttribute"
        }
      ],
      "role": "symbol",
      "title": "UISemanticContentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/uisemanticcontentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/playback": {
      "abstract": [
        {
          "text": "A view representing the playback controls, such as Play, Rewind, or Fast Forward buttons or playhead scrubbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playback"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/playback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISemanticContentAttributePlayback"
        }
      ],
      "role": "symbol",
      "title": "UISemanticContentAttribute.playback",
      "type": "topic",
      "url": "/documentation/uikit/uisemanticcontentattribute/playback"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLayoutDirection": {
      "abstract": [
        {
          "text": "Constants that specify the directional flow of the user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserInterfaceLayoutDirection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLayoutDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceLayoutDirection"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceLayoutDirection",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfacelayoutdirection"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLayoutDirection/leftToRight": {
      "abstract": [
        {
          "text": "The layout direction is left to right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftToRight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLayoutDirection/leftToRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceLayoutDirectionLeftToRight"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceLayoutDirection.leftToRight",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfacelayoutdirection/lefttoright"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLayoutDirection/rightToLeft": {
      "abstract": [
        {
          "text": "The layout direction right to left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightToLeft"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLayoutDirection/rightToLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceLayoutDirectionRightToLeft"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceLayoutDirection.rightToLeft",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfacelayoutdirection/righttoleft"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/effectiveUserInterfaceLayoutDirection": {
      "abstract": [
        {
          "text": "The user interface layout direction appropriate for arranging the immediate content of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "effectiveUserInterfaceLayoutDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIUserInterfaceLayoutDirection",
          "text": "UIUserInterfaceLayoutDirection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/effectiveUserInterfaceLayoutDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "effectiveUserInterfaceLayoutDirection"
        }
      ],
      "role": "symbol",
      "title": "effectiveUserInterfaceLayoutDirection",
      "type": "topic",
      "url": "/documentation/uikit/uiview/effectiveuserinterfacelayoutdirection"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/overrideUserInterfaceStyle": {
      "abstract": [
        {
          "text": "The user interface style adopted by the view and all of its subviews.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overrideUserInterfaceStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIUserInterfaceStyle",
          "text": "UIUserInterfaceStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/overrideUserInterfaceStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "overrideUserInterfaceStyle"
        }
      ],
      "role": "symbol",
      "title": "overrideUserInterfaceStyle",
      "type": "topic",
      "url": "/documentation/uikit/uiview/overrideuserinterfacestyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/semanticContentAttribute": {
      "abstract": [
        {
          "text": "A semantic description of the view’s contents, used to determine whether the view should be flipped when switching between left-to-right and right-to-left layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "semanticContentAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISemanticContentAttribute",
          "text": "UISemanticContentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/semanticContentAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "semanticContentAttribute"
        }
      ],
      "role": "symbol",
      "title": "semanticContentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/uiview/semanticcontentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/userInterfaceLayoutDirection(for:)": {
      "abstract": [
        {
          "text": "Returns the user interface direction for the given semantic content attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInterfaceLayoutDirection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISemanticContentAttribute",
          "text": "UISemanticContentAttribute"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIUserInterfaceLayoutDirection",
          "text": "UIUserInterfaceLayoutDirection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/userInterfaceLayoutDirection(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInterfaceLayoutDirectionForSemanticContentAttribute:"
        }
      ],
      "role": "symbol",
      "title": "userInterfaceLayoutDirection(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/userinterfacelayoutdirection(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/userInterfaceLayoutDirection(for:relativeTo:)": {
      "abstract": [
        {
          "text": "Returns the layout direction implied by the specified semantic content attribute, relative to the specified layout direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInterfaceLayoutDirection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISemanticContentAttribute",
          "text": "UISemanticContentAttribute"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "relativeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIUserInterfaceLayoutDirection",
          "text": "UIUserInterfaceLayoutDirection"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIUserInterfaceLayoutDirection",
          "text": "UIUserInterfaceLayoutDirection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/userInterfaceLayoutDirection(for:relativeTo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInterfaceLayoutDirectionForSemanticContentAttribute:relativeToLayoutDirection:"
        }
      ],
      "role": "symbol",
      "title": "userInterfaceLayoutDirection(for:relativeTo:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/userinterfacelayoutdirection(for:relativeto:)"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Adjusting-the-user-interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/overrideUserInterfaceStyle",
        "doc://com.apple.uikit/documentation/UIKit/UIView/semanticContentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/UIView/effectiveUserInterfaceLayoutDirection",
        "doc://com.apple.uikit/documentation/UIKit/UIView/userInterfaceLayoutDirection(for:)"
      ],
      "title": "Adjusting the user interface"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "userInterfaceLayoutDirectionForSemanticContentAttribute:relativeToLayoutDirection:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "userInterfaceLayoutDirectionForSemanticContentAttribute:relativeToLayoutDirection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Adjusting-the-user-interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIView/overrideUserInterfaceStyle",
                "doc://com.apple.uikit/documentation/UIKit/UIView/semanticContentAttribute",
                "doc://com.apple.uikit/documentation/UIKit/UIView/effectiveUserInterfaceLayoutDirection",
                "doc://com.apple.uikit/documentation/UIKit/UIView/userInterfaceLayoutDirection(for:)"
              ],
              "title": "Adjusting the user interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLayoutDirection",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@UIUserInterfaceLayoutDirection",
                    "text": "UIUserInterfaceLayoutDirection"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "userInterfaceLayoutDirectionForSemanticContentAttribute:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@UISemanticContentAttribute",
                    "text": "UISemanticContentAttribute"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "semanticContentAttribute"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "relativeToLayoutDirection:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLayoutDirection",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@UIUserInterfaceLayoutDirection",
                    "text": "UIUserInterfaceLayoutDirection"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "layoutDirection"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The semantic content attribute for a view.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "semanticContentAttribute"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The user interface layout direction (",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLayoutDirection/leftToRight",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " or ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLayoutDirection/rightToLeft",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ").",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "layoutDirection"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The layout direction implied by the semantic content attribute and relative to the layout direction.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1userInterfaceLayoutDirection(for:)/title",
          "value": "userInterfaceLayoutDirectionForSemanticContentAttribute:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1userInterfaceLayoutDirection(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "userInterfaceLayoutDirectionForSemanticContentAttribute:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceLayoutDirection~1rightToLeft/title",
          "value": "UIUserInterfaceLayoutDirectionRightToLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceLayoutDirection~1rightToLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceLayoutDirectionRightToLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute/title",
          "value": "UISemanticContentAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1playback/title",
          "value": "UISemanticContentAttributePlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1playback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttributePlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceLayoutDirection~1leftToRight/title",
          "value": "UIUserInterfaceLayoutDirectionLeftToRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceLayoutDirection~1leftToRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceLayoutDirectionLeftToRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1semanticContentAttribute/title",
          "value": "semanticContentAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1semanticContentAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "semanticContentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceLayoutDirection/title",
          "value": "UIUserInterfaceLayoutDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceLayoutDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceLayoutDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceLayoutDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceLayoutDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1overrideUserInterfaceStyle/title",
          "value": "overrideUserInterfaceStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1overrideUserInterfaceStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "overrideUserInterfaceStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1effectiveUserInterfaceLayoutDirection/title",
          "value": "effectiveUserInterfaceLayoutDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1effectiveUserInterfaceLayoutDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "effectiveUserInterfaceLayoutDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1userInterfaceLayoutDirection(for:relativeTo:)/title",
          "value": "userInterfaceLayoutDirectionForSemanticContentAttribute:relativeToLayoutDirection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1userInterfaceLayoutDirection(for:relativeTo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "userInterfaceLayoutDirectionForSemanticContentAttribute:relativeToLayoutDirection:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiview/userinterfacelayoutdirection(for:relativeto:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiview/userinterfacelayoutdirection(for:relativeto:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
