{
  "abstract": [
    {
      "text": "Retrieves the layout attributes of an item when it is being moved interactively by the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForInteractivelyMovingItem(at:withTargetPosition:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:objc(cs)UICollectionViewLayout(im)layoutAttributesForInteractivelyMovingItemAtIndexPath:withTargetPosition:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "layoutAttributesForInteractivelyMovingItem"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "at"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation9IndexPathV",
        "text": "IndexPath"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "withTargetPosition"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGPoint",
        "text": "CGPoint"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UICollectionViewLayoutAttributes",
        "text": "UICollectionViewLayoutAttributes"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "layoutAttributesForInteractivelyMovingItemAtIndexPath:withTargetPosition:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "layoutAttributesForInteractivelyMovingItem(at:withTargetPosition:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "layoutAttributesForInteractivelyMovingItem"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "at"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "indexPath"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation9IndexPathV",
              "text": "IndexPath"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "withTargetPosition"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "position"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGPoint",
              "text": "CGPoint"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UICollectionViewLayoutAttributes",
              "text": "UICollectionViewLayoutAttributes"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The index path of the item being moved.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "indexPath"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The current position of the item in the collection view’s coordinate system.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "position"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The layout attributes of the item while it is at the specified position.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When an item is moving because of user interactivity, the layout object uses this method to retrieve layout attributes to use for the item while it is at the specified position. The default implementation of this method returns a copy of the item’s existing attributes with two changes: the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes/center",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " point is set to the value in ",
              "type": "text"
            },
            {
              "code": "position",
              "type": "codeVoice"
            },
            {
              "text": " and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes/zIndex",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value is set to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nsintegermax",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " so that the item floats above other items in the collection view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Subclasses can override this method and modify additional layout attributes as needed. If you override this method, call ",
              "type": "text"
            },
            {
              "code": "super",
              "type": "codeVoice"
            },
            {
              "text": " first to retrieve the item’s existing attributes and then make your changes to the returned structure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/objectivec/nsintegermax": {
      "abstract": [
        {
          "text": "The maximum value for an `NSInteger`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "NSIntegerMax"
        },
        {
          "kind": "text",
          "text": ": Int"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsintegermax",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSIntegerMax",
      "type": "topic",
      "url": "/documentation/objectivec/nsintegermax"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout": {
      "abstract": [
        {
          "text": "An abstract base class for generating layout information for a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewLayout"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewLayout"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewLayout",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayout"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesClass": {
      "abstract": [
        {
          "text": "The class to use when creating layout attributes objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutAttributesClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutAttributesClass"
        }
      ],
      "role": "symbol",
      "title": "layoutAttributesClass",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayout/layoutattributesclass"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForDecorationView(ofKind:at:)": {
      "abstract": [
        {
          "text": "Retrieves the layout attributes for the specified decoration view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutAttributesForDecorationView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionViewLayoutAttributes",
          "text": "UICollectionViewLayoutAttributes"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForDecorationView(ofKind:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutAttributesForDecorationViewOfKind:atIndexPath:"
        }
      ],
      "role": "symbol",
      "title": "layoutAttributesForDecorationView(ofKind:at:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayout/layoutattributesfordecorationview(ofkind:at:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForElements(in:)": {
      "abstract": [
        {
          "text": "Retrieves the layout attributes for all of the cells and views in the specified rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutAttributesForElements"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionViewLayoutAttributes",
          "text": "UICollectionViewLayoutAttributes"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForElements(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutAttributesForElementsInRect:"
        }
      ],
      "role": "symbol",
      "title": "layoutAttributesForElements(in:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayout/layoutattributesforelements(in:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForInteractivelyMovingItem(at:withTargetPosition:)": {
      "abstract": [
        {
          "text": "Retrieves the layout attributes of an item when it is being moved interactively by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutAttributesForInteractivelyMovingItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withTargetPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionViewLayoutAttributes",
          "text": "UICollectionViewLayoutAttributes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForInteractivelyMovingItem(at:withTargetPosition:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutAttributesForInteractivelyMovingItemAtIndexPath:withTargetPosition:"
        }
      ],
      "role": "symbol",
      "title": "layoutAttributesForInteractivelyMovingItem(at:withTargetPosition:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayout/layoutattributesforinteractivelymovingitem(at:withtargetposition:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForItem(at:)": {
      "abstract": [
        {
          "text": "Retrieves layout information for an item at the specified index path with a corresponding cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutAttributesForItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionViewLayoutAttributes",
          "text": "UICollectionViewLayoutAttributes"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForItem(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutAttributesForItemAtIndexPath:"
        }
      ],
      "role": "symbol",
      "title": "layoutAttributesForItem(at:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayout/layoutattributesforitem(at:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForSupplementaryView(ofKind:at:)": {
      "abstract": [
        {
          "text": "Retrieves the layout attributes for the specified supplementary view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutAttributesForSupplementaryView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionViewLayoutAttributes",
          "text": "UICollectionViewLayoutAttributes"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForSupplementaryView(ofKind:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutAttributesForSupplementaryViewOfKind:atIndexPath:"
        }
      ],
      "role": "symbol",
      "title": "layoutAttributesForSupplementaryView(ofKind:at:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayout/layoutattributesforsupplementaryview(ofkind:at:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/prepare()": {
      "abstract": [
        {
          "text": "Tells the layout object to update the current layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepare"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/prepare()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepareLayout"
        }
      ],
      "role": "symbol",
      "title": "prepare()",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayout/prepare()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/targetContentOffset(forProposedContentOffset:)": {
      "abstract": [
        {
          "text": "Retrieves the content offset to use after an animated layout update or change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "targetContentOffset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forProposedContentOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/targetContentOffset(forProposedContentOffset:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "targetContentOffsetForProposedContentOffset:"
        }
      ],
      "role": "symbol",
      "title": "targetContentOffset(forProposedContentOffset:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayout/targetcontentoffset(forproposedcontentoffset:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/targetContentOffset(forProposedContentOffset:withScrollingVelocity:)": {
      "abstract": [
        {
          "text": "Retrieves the point at which to stop scrolling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "targetContentOffset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forProposedContentOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withScrollingVelocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/targetContentOffset(forProposedContentOffset:withScrollingVelocity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "targetContentOffsetForProposedContentOffset:withScrollingVelocity:"
        }
      ],
      "role": "symbol",
      "title": "targetContentOffset(forProposedContentOffset:withScrollingVelocity:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayout/targetcontentoffset(forproposedcontentoffset:withscrollingvelocity:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes": {
      "abstract": [
        {
          "text": "A layout object that manages the layout-related attributes for a given item in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewLayoutAttributes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewLayoutAttributes"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewLayoutAttributes",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayoutattributes"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes/center": {
      "abstract": [
        {
          "text": "The center point of the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "role": "symbol",
      "title": "center",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayoutattributes/center"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes/zIndex": {
      "abstract": [
        {
          "text": "Specifies the item’s position on the z axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes/zIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "zIndex"
        }
      ],
      "role": "symbol",
      "title": "zIndex",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayoutattributes/zindex"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGPoint": {
      "abstract": [
        {
          "text": "A structure that contains a point in a two-dimensional coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGPoint",
      "type": "topic",
      "url": "/documentation/corefoundation/cgpoint"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSIndexPath": {
      "abstract": [
        {
          "text": "An object containing a list of indexes that bridges to ; use  when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSIndexPath"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSIndexPath",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSIndexPath",
      "type": "topic",
      "url": "/documentation/foundation/nsindexpath"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV": {
      "abstract": [
        {
          "text": "A list of indexes that together represent the path to a specific location in a tree of nested arrays. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "IndexPath"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV",
      "kind": "symbol",
      "role": "symbol",
      "title": "IndexPath",
      "type": "topic",
      "url": "/documentation/foundation/indexpath"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-layout-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesClass",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/prepare()",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForElements(in:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForItem(at:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForSupplementaryView(ofKind:at:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForDecorationView(ofKind:at:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/targetContentOffset(forProposedContentOffset:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/targetContentOffset(forProposedContentOffset:withScrollingVelocity:)"
      ],
      "title": "Providing layout attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "layoutAttributesForInteractivelyMovingItemAtIndexPath:withTargetPosition:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "layoutAttributesForInteractivelyMovingItemAtIndexPath:withTargetPosition:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-layout-attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesClass",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/prepare()",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForElements(in:)",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForItem(at:)",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForSupplementaryView(ofKind:at:)",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForDecorationView(ofKind:at:)",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/targetContentOffset(forProposedContentOffset:)",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/targetContentOffset(forProposedContentOffset:withScrollingVelocity:)"
              ],
              "title": "Providing layout attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UICollectionViewLayoutAttributes",
                    "text": "UICollectionViewLayoutAttributes"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "layoutAttributesForInteractivelyMovingItemAtIndexPath:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSIndexPath",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSIndexPath",
                    "text": "NSIndexPath"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "indexPath"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "withTargetPosition:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGPoint",
                    "text": "CGPoint"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "position"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The index path of the item being moved.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "indexPath"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The current position of the item in the collection view’s coordinate system.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "position"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The layout attributes of the item while it is at the specified position.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1layoutAttributesForInteractivelyMovingItem(at:withTargetPosition:)/title",
          "value": "layoutAttributesForInteractivelyMovingItemAtIndexPath:withTargetPosition:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1layoutAttributesForInteractivelyMovingItem(at:withTargetPosition:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "layoutAttributesForInteractivelyMovingItemAtIndexPath:withTargetPosition:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1prepare()/title",
          "value": "prepareLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1prepare()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "prepareLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1layoutAttributesForItem(at:)/title",
          "value": "layoutAttributesForItemAtIndexPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1layoutAttributesForItem(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "layoutAttributesForItemAtIndexPath:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutAttributes/title",
          "value": "UICollectionViewLayoutAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1layoutAttributesForElements(in:)/title",
          "value": "layoutAttributesForElementsInRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1layoutAttributesForElements(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "layoutAttributesForElementsInRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutAttributes~1zIndex/title",
          "value": "zIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutAttributes~1zIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "zIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1layoutAttributesClass/title",
          "value": "layoutAttributesClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1layoutAttributesClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layoutAttributesClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1layoutAttributesForSupplementaryView(ofKind:at:)/title",
          "value": "layoutAttributesForSupplementaryViewOfKind:atIndexPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1layoutAttributesForSupplementaryView(ofKind:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "layoutAttributesForSupplementaryViewOfKind:atIndexPath:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutAttributes~1center/title",
          "value": "center"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutAttributes~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "center"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1targetContentOffset(forProposedContentOffset:withScrollingVelocity:)/title",
          "value": "targetContentOffsetForProposedContentOffset:withScrollingVelocity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1targetContentOffset(forProposedContentOffset:withScrollingVelocity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "targetContentOffsetForProposedContentOffset:withScrollingVelocity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1layoutAttributesForDecorationView(ofKind:at:)/title",
          "value": "layoutAttributesForDecorationViewOfKind:atIndexPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1layoutAttributesForDecorationView(ofKind:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "layoutAttributesForDecorationViewOfKind:atIndexPath:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSIndexPath/abstract",
          "value": [
            {
              "text": "A list of indexes that together represent the path to a specific location in a tree of nested arrays.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1targetContentOffset(forProposedContentOffset:)/title",
          "value": "targetContentOffsetForProposedContentOffset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1targetContentOffset(forProposedContentOffset:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "targetContentOffsetForProposedContentOffset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout/title",
          "value": "UICollectionViewLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewLayout"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicollectionviewlayout/layoutattributesforinteractivelymovingitem(at:withtargetposition:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicollectionviewlayout/layoutattributesforinteractivelymovingitem(at:withtargetposition:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
