{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker/delegate","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSSharingServicePickerDelegate","text":"NSSharingServicePickerDelegate"},{"kind":"text","text":")? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"Discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"The delegate object must conform to the "},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate","type":"reference"},{"type":"text","text":" delegate."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"NSSharingServicePickerDelegate","preciseIdentifier":"c:objc(pl)NSSharingServicePickerDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"roleHeading":"Instance Property","title":"delegate","platforms":[{"deprecated":false,"beta":false,"introducedAt":"10.8","unavailable":false,"name":"macOS"}],"symbolKind":"property","modules":[{"name":"AppKit"}],"role":"symbol","externalID":"c:objc(cs)NSSharingServicePicker(py)delegate"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker"]]},"variants":[{"paths":["/documentation/appkit/nssharingservicepicker/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nssharingservicepicker/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate"],"generated":true,"anchor":"Managing-the-sharing-service-picker","title":"Managing the sharing service picker"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The object for managing the sharing service picker.","type":"text"}],"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate":{"abstract":[{"type":"text","text":"An interface for managing content for the macOS share sheet."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"NSSharingServicePickerDelegate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"NSSharingServicePickerDelegate","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate","kind":"symbol","url":"/documentation/appkit/nssharingservicepickerdelegate","role":"symbol","title":"NSSharingServicePickerDelegate"},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSharingServicePicker","kind":"identifier"}],"title":"NSSharingServicePicker","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker","abstract":[{"type":"text","text":"A list of sharing services that the user can choose from."}],"role":"symbol","url":"/documentation/appkit/nssharingservicepicker","type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSSharingServicePicker","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker/delegate":{"url":"/documentation/appkit/nssharingservicepicker/delegate","kind":"symbol","abstract":[{"text":"The object for managing the sharing service picker.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"NSSharingServicePickerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSSharingServicePickerDelegate"},{"text":")?","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker/delegate","title":"delegate","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"beta":false,"deprecated":false,"introducedAt":"10.8","name":"macOS","unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"delegate"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"delegate","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSharingServicePicker"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Managing-the-sharing-service-picker","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSharingServicePickerDelegate"],"generated":true,"title":"Managing the sharing service picker"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qoobjc(pl)NSSharingServicePickerDelegate","kind":"typeIdentifier","text":"id<NSSharingServicePickerDelegate>"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":"NSSharingServicePickerDelegate","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate/title"},{"value":[{"kind":"identifier","text":"NSSharingServicePickerDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate/fragments"},{"value":[{"kind":"identifier","text":"NSSharingServicePickerDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePickerDelegate/navigatorTitle"},{"value":"NSSharingServicePicker","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePicker/title"},{"value":[{"text":"NSSharingServicePicker","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePicker/fragments"},{"value":[{"kind":"identifier","text":"NSSharingServicePicker"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePicker/navigatorTitle"},{"value":"delegate","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePicker~1delegate/title"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingServicePicker~1delegate/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}