{
  "abstract": [
    {
      "text": "The identifier string of the action that the user selected.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.usernotifications/documentation/UserNotifications",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationResponse"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationResponse/actionIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UNNotificationResponse(py)actionIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "actionIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "User Notifications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "actionIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "actionIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "actionIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.usernotifications/documentation/UserNotifications/handling-notifications-and-notification-related-actions",
        "doc://com.apple.usernotifications/documentation/UserNotifications/declaring-your-actionable-notification-types"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This parameter may contain one the identifier of one of your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects or it may contain a system-defined identifier. The system defined identifiers are ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationDefaultActionIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationDismissActionIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", which indicate that the user opened the app or dismissed the notification without any further actions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about defining custom actions, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/declaring-your-actionable-notification-types",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "UserNotifications-PageImage-card.png": {
      "alt": "[A notification interface displayed on the lock screen of an iOS device.]",
      "identifier": "UserNotifications-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/074de9a9213bf2905d67fae5eb46e4f8/UserNotifications-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5733742e1c084fc202b3c92df9083686/UserNotifications-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications": {
      "abstract": [
        {
          "text": "Push user-facing notifications to the user’s device from a server, or generate them locally from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications",
      "images": [
        {
          "identifier": "UserNotifications-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "User Notifications",
      "type": "topic",
      "url": "/documentation/usernotifications"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationAction": {
      "abstract": [
        {
          "text": "A task your app performs in response to a notification that the system delivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationAction"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationAction"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationAction",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationaction"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationDefaultActionIdentifier": {
      "abstract": [
        {
          "text": "An action that indicates the user opened the app from the notification interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationDefaultActionIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationDefaultActionIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationDefaultActionIdentifier"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationDefaultActionIdentifier",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationdefaultactionidentifier"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationDismissActionIdentifier": {
      "abstract": [
        {
          "text": "The action that indicates the user explicitly dismissed the notification interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationDismissActionIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationDismissActionIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationDismissActionIdentifier"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationDismissActionIdentifier",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationdismissactionidentifier"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationResponse": {
      "abstract": [
        {
          "text": "The user’s response to an actionable notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationResponse"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationResponse"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationResponse",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationresponse"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationResponse/actionIdentifier": {
      "abstract": [
        {
          "text": "The identifier string of the action that the user selected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationResponse/actionIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "actionIdentifier"
        }
      ],
      "role": "symbol",
      "title": "actionIdentifier",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationresponse/actionidentifier"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationResponse/notification": {
      "abstract": [
        {
          "text": "The notification to which the user responded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UNNotification",
          "text": "UNNotification"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationResponse/notification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notification"
        }
      ],
      "role": "symbol",
      "title": "notification",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationresponse/notification"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationResponse/targetScene": {
      "abstract": [
        {
          "text": "The scene where the system reflects the user’s response to a notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "targetScene"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScene",
          "text": "UIScene"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationResponse/targetScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "targetScene"
        }
      ],
      "role": "symbol",
      "title": "targetScene",
      "type": "topic",
      "url": "/documentation/usernotifications/unnotificationresponse/targetscene"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/declaring-your-actionable-notification-types": {
      "abstract": [
        {
          "text": "Differentiate your notifications and add action buttons to the notification interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/declaring-your-actionable-notification-types",
      "kind": "article",
      "role": "article",
      "title": "Declaring your actionable notification types",
      "type": "topic",
      "url": "/documentation/usernotifications/declaring-your-actionable-notification-types"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/handling-notifications-and-notification-related-actions": {
      "abstract": [
        {
          "text": "Respond to user interactions with the system’s notification interfaces, including handling your app’s custom actions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/handling-notifications-and-notification-related-actions",
      "kind": "article",
      "role": "article",
      "title": "Handling notifications and notification-related actions",
      "type": "topic",
      "url": "/documentation/usernotifications/handling-notifications-and-notification-related-actions"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Response-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationResponse/notification",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationResponse/targetScene",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationDefaultActionIdentifier",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationDismissActionIdentifier"
      ],
      "title": "Getting the Response Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "actionIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "actionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.usernotifications/documentation/UserNotifications",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationResponse"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Response-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationResponse/notification",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationResponse/targetScene",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationDefaultActionIdentifier",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNNotificationDismissActionIdentifier"
              ],
              "title": "Getting the Response Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "actionIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "atomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "actionIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationResponse~1targetScene/title",
          "value": "targetScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationResponse~1targetScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "targetScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationResponse~1actionIdentifier/title",
          "value": "actionIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationResponse~1actionIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "actionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationResponse/title",
          "value": "UNNotificationResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationAction/title",
          "value": "UNNotificationAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationResponse~1notification/title",
          "value": "notification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationResponse~1notification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationDismissActionIdentifier/title",
          "value": "UNNotificationDismissActionIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationDismissActionIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationDismissActionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationDefaultActionIdentifier/title",
          "value": "UNNotificationDefaultActionIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNNotificationDefaultActionIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationDefaultActionIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/usernotifications/unnotificationresponse/actionidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/usernotifications/unnotificationresponse/actionidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
