{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/javascriptcore-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "JavaScriptCore"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "JavaScriptCore Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore": {
      "abstract": [
        {
          "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
      "kind": "symbol",
      "role": "collection",
      "title": "JavaScriptCore",
      "type": "topic",
      "url": "/documentation/javascriptcore"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSExportAs": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "JSExportAs"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSExportAs",
      "kind": "symbol",
      "role": "symbol",
      "title": "JSExportAs",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsexportas"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JS_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "JS_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JS_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "JS_EXPORT",
      "type": "topic",
      "url": "/documentation/javascriptcore/js_export"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeBigInt64Array": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeBigInt64Array"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeBigInt64Array",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeBigInt64Array"
        }
      ],
      "role": "symbol",
      "title": "kJSTypedArrayTypeBigInt64Array",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypedarraytypebigint64array"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeBigUint64Array": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeBigUint64Array"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeBigUint64Array",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeBigUint64Array"
        }
      ],
      "role": "symbol",
      "title": "kJSTypedArrayTypeBigUint64Array",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypedarraytypebiguint64array"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeBigInt64Array",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeBigUint64Array"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeBigInt64Array",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeBigUint64Array"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSExportAs",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JS_EXPORT"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeBigUint64Array/title",
          "value": "kJSTypedArrayTypeBigUint64Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeBigUint64Array/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypedArrayTypeBigUint64Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeBigInt64Array/title",
          "value": "kJSTypedArrayTypeBigInt64Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeBigInt64Array/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypedArrayTypeBigInt64Array"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/javascriptcore/javascriptcore-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/javascriptcore/javascriptcore-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
