{
  "abstract": [
    {
      "text": "A group that associates JavaScript contexts with one another.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextGroupRef"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@JSContextGroupRef",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "JSContextGroupRef"
      }
    ],
    "modules": [
      {
        "name": "JavaScriptCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "JSContextGroupRef"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "JSContextGroupRef"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "JSContextGroupRef"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s13OpaquePointerV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s13OpaquePointerV",
              "text": "OpaquePointer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Contexts in the same group may share and exchange JavaScript objects.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore": {
      "abstract": [
        {
          "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
      "kind": "symbol",
      "role": "collection",
      "title": "JavaScriptCore",
      "type": "topic",
      "url": "/documentation/javascriptcore"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassRef": {
      "abstract": [
        {
          "text": "A JavaScript class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSClassRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSClassRef"
        }
      ],
      "role": "symbol",
      "title": "JSClassRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsclassref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextGetGroup(_:)": {
      "abstract": [
        {
          "text": "Gets the context group that a JavaScript execution context belongs to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSContextGetGroup"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextGroupRef",
          "text": "JSContextGroupRef"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextGetGroup(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSContextGetGroup"
        }
      ],
      "role": "symbol",
      "title": "JSContextGetGroup(_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jscontextgetgroup(_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextGroupRef": {
      "abstract": [
        {
          "text": "A group that associates JavaScript contexts with one another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSContextGroupRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextGroupRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSContextGroupRef"
        }
      ],
      "role": "symbol",
      "title": "JSContextGroupRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jscontextgroupref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef": {
      "abstract": [
        {
          "text": "A JavaScript execution context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSContextRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSContextRef"
        }
      ],
      "role": "symbol",
      "title": "JSContextRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jscontextref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSGlobalContextRef": {
      "abstract": [
        {
          "text": "A global JavaScript execution context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSGlobalContextRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSGlobalContextRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSGlobalContextRef"
        }
      ],
      "role": "symbol",
      "title": "JSGlobalContextRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsglobalcontextref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringRef": {
      "abstract": [
        {
          "text": "A UTF-16 character buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSStringRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSStringRef"
        }
      ],
      "role": "symbol",
      "title": "JSStringRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstringref"
    },
    "doc://com.externally.resolved.symbol/s:s13OpaquePointerV": {
      "abstract": [
        {
          "text": "A wrapper around an opaque C pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OpaquePointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s13OpaquePointerV",
      "kind": "symbol",
      "role": "symbol",
      "title": "OpaquePointer",
      "type": "topic",
      "url": "/documentation/Swift/OpaquePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "JavaScriptCore-Engine-Interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSGlobalContextRef",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringRef",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassRef"
      ],
      "title": "JavaScriptCore Engine Interface"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-the-Content-Group",
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextGetGroup(_:)"
      ],
      "title": "Accessing the Content Group"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "JSContextGroupRef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContextGroupRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContextGroupRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-the-Content-Group",
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextGetGroup(_:)"
              ],
              "title": "Accessing the Content Group"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "JavaScriptCore-Engine-Interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSGlobalContextRef",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringRef",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassRef"
              ],
              "title": "JavaScriptCore Engine Interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@OpaqueJSContextGroup",
                    "text": "OpaqueJSContextGroup"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "JSContextGroupRef"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextRef/title",
          "value": "JSContextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringRef/title",
          "value": "JSStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextGroupRef/title",
          "value": "JSContextGroupRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextGroupRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContextGroupRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextGroupRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContextGroupRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextGetGroup(_:)/title",
          "value": "JSContextGetGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextGetGroup(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContextGetGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSGlobalContextRef/title",
          "value": "JSGlobalContextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSGlobalContextRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSGlobalContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSGlobalContextRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSGlobalContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassRef/title",
          "value": "JSClassRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSClassRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSClassRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/javascriptcore/jscontextgroupref"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/javascriptcore/jscontextgroupref"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
