{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.javascriptcore/documentation/JavaScriptCore"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSObjectMakeDate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"ctx","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef","text":"JSContextRef","preciseIdentifier":"c:@T@JSContextRef","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"argumentCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"arguments"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer","identifier":"doc://com.externally.resolved.symbol/s:SP"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@T@JSValueRef","kind":"typeIdentifier","text":"JSValueRef","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef"},{"kind":"text","text":"?>!, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"exception","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@T@JSValueRef","text":"JSValueRef","kind":"typeIdentifier","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef"},{"text":"?>!) -> ","kind":"text"},{"preciseIdentifier":"c:@T@JSObjectRef","text":"JSObjectRef","kind":"typeIdentifier","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectRef"},{"text":"!","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The execution context to use."}]}],"name":"ctx"},{"content":[{"type":"paragraph","inlineContent":[{"text":"An integer count of the number of arguments in ","type":"text"},{"code":"arguments","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"argumentCount"},{"content":[{"inlineContent":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef","isActive":true},{"type":"text","text":" array of arguments to pass to the "},{"type":"codeVoice","code":"Date"},{"text":" constructor. Pass ","type":"text"},{"type":"codeVoice","code":"NULL"},{"text":" if ","type":"text"},{"type":"codeVoice","code":"argumentCount"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"0"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"arguments"},{"content":[{"inlineContent":[{"text":"A pointer to a ","type":"text"},{"type":"reference","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef","isActive":true},{"text":" to store an exception in, if any. Pass ","type":"text"},{"code":"NULL","type":"codeVoice"},{"text":" to discard any exception.","type":"text"}],"type":"paragraph"}],"name":"exception"}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"text":"A ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectRef"},{"text":" that is a date.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"JSObjectMakeDate"}],"title":"JSObjectMakeDate(_:_:_:_:)","modules":[{"name":"JavaScriptCore"}],"platforms":[{"beta":false,"introducedAt":"7.0","unavailable":false,"deprecated":false,"name":"iOS"},{"beta":false,"introducedAt":"7.0","unavailable":false,"deprecated":false,"name":"iPadOS"},{"beta":false,"introducedAt":"13.1","unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"beta":false,"introducedAt":"10.6","unavailable":false,"deprecated":false,"name":"macOS"},{"name":"tvOS","beta":false,"deprecated":false,"introducedAt":"9.0","unavailable":false},{"name":"visionOS","beta":false,"deprecated":false,"introducedAt":"1.0","unavailable":false}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSObjectMakeDate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JSContextRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSContextRef"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@JSValueRef","text":"JSValueRef"},{"kind":"text","text":"?>!, "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@JSValueRef","text":"JSValueRef"},{"kind":"text","text":"?>!) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@JSObjectRef","text":"JSObjectRef"},{"kind":"text","text":"!"}],"roleHeading":"Function","role":"symbol","externalID":"c:@F@JSObjectMakeDate","symbolKind":"func"},"variants":[{"paths":["/documentation/javascriptcore/jsobjectmakedate(_:_:_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/javascriptcore/jsobjectmakedate(_:_:_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Creates a JavaScript date object as though invoking the built-in date constructor."}],"seeAlsoSections":[{"title":"Working with Objects","generated":true,"identifiers":["doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsConstructor(_:_:_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsFunction(_:_:_:_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCopyPropertyNames(_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectDeleteProperty(_:_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPrivate(_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetProperty(_:_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyAtIndex(_:_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPrototype(_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectHasProperty(_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectIsConstructor(_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectIsFunction(_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMake(_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeArray(_:_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeConstructor(_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeError(_:_:_:_:)"],"anchor":"Working-with-Objects"}],"identifier":{"url":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeDate(_:_:_:_:)","interfaceLanguage":"swift"},"references":{"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectDeleteProperty(_:_:_:_:)":{"url":"/documentation/javascriptcore/jsobjectdeleteproperty(_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSObjectDeleteProperty"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"JSContextRef","preciseIdentifier":"c:@T@JSContextRef"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"JSObjectRef","preciseIdentifier":"c:@T@JSObjectRef"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"JSStringRef","preciseIdentifier":"c:@T@JSStringRef"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"JSValueRef","preciseIdentifier":"c:@T@JSValueRef"},{"kind":"text","text":"?>!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectDeleteProperty(_:_:_:_:)","kind":"symbol","abstract":[{"text":"Deletes a property from an object.","type":"text"}],"title":"JSObjectDeleteProperty(_:_:_:_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSObjectDeleteProperty"}]},"doc://com.externally.resolved.symbol/s:Si":{"fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"identifier":"doc://com.externally.resolved.symbol/s:Si","title":"Int","url":"/documentation/Swift/Int","role":"symbol","abstract":[{"type":"text","text":"A signed integer value type."}],"kind":"symbol","type":"topic"},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPrototype(_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"JSObjectGetPrototype"}],"abstract":[{"text":"Gets an object’s prototype.","type":"text"}],"identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPrototype(_:_:)","title":"JSObjectGetPrototype(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSObjectGetPrototype"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"JSContextRef","preciseIdentifier":"c:@T@JSContextRef"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"JSObjectRef","preciseIdentifier":"c:@T@JSObjectRef"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"JSValueRef","preciseIdentifier":"c:@T@JSValueRef"},{"kind":"text","text":"!"}],"url":"/documentation/javascriptcore/jsobjectgetprototype(_:_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetProperty(_:_:_:_:)":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSObjectGetProperty","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JSContextRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSContextRef"},{"text":"!, ","kind":"text"},{"text":"JSObjectRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSObjectRef"},{"text":"!, ","kind":"text"},{"text":"JSStringRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSStringRef"},{"text":"!, ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"JSValueRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSValueRef"},{"text":"?>!) -> ","kind":"text"},{"text":"JSValueRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSValueRef"},{"text":"!","kind":"text"}],"identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetProperty(_:_:_:_:)","abstract":[{"type":"text","text":"Gets a property from an object."}],"title":"JSObjectGetProperty(_:_:_:_:)","url":"/documentation/javascriptcore/jsobjectgetproperty(_:_:_:_:)","navigatorTitle":[{"text":"JSObjectGetProperty","kind":"identifier"}]},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef":{"identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef","url":"/documentation/javascriptcore/jscontextref","abstract":[{"text":"A JavaScript execution context.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JSContextRef"}],"type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSContextRef"}],"title":"JSContextRef"},"doc://com.externally.resolved.symbol/s:SP":{"role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnsafePointer","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Pointee","kind":"genericParameter"},{"text":"> ","kind":"text"},{"text":"where","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Pointee","kind":"typeIdentifier"},{"text":" : ~Copyable","kind":"text"}],"type":"topic","kind":"symbol","title":"UnsafePointer","identifier":"doc://com.externally.resolved.symbol/s:SP","url":"/documentation/Swift/UnsafePointer","abstract":[{"text":"A pointer for accessing data of a specific type.","type":"text"}]},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectIsFunction(_:_:)":{"navigatorTitle":[{"text":"JSObjectIsFunction","kind":"identifier"}],"title":"JSObjectIsFunction(_:_:)","url":"/documentation/javascriptcore/jsobjectisfunction(_:_:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSObjectIsFunction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JSContextRef","preciseIdentifier":"c:@T@JSContextRef","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"JSObjectRef","preciseIdentifier":"c:@T@JSObjectRef","kind":"typeIdentifier"},{"text":"!) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"Tests whether you can call an object as a function.","type":"text"}],"identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectIsFunction(_:_:)"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"type":"text","text":""}],"identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","role":"overview","kind":"technologies","type":"topic"},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectRef":{"navigatorTitle":[{"kind":"identifier","text":"JSObjectRef"}],"role":"symbol","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectRef","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"JSObjectRef","kind":"identifier"}],"title":"JSObjectRef","abstract":[{"type":"text","text":"A JavaScript object."}],"url":"/documentation/javascriptcore/jsobjectref","type":"topic"},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsFunction(_:_:_:_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"JSObjectCallAsFunction"}],"abstract":[{"text":"Calls an object as a function.","type":"text"}],"identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsFunction(_:_:_:_:_:_:)","title":"JSObjectCallAsFunction(_:_:_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSObjectCallAsFunction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"JSContextRef","preciseIdentifier":"c:@T@JSContextRef"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"JSObjectRef","preciseIdentifier":"c:@T@JSObjectRef"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"JSObjectRef","preciseIdentifier":"c:@T@JSObjectRef"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"JSValueRef","preciseIdentifier":"c:@T@JSValueRef"},{"kind":"text","text":"?>!, "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"JSValueRef","preciseIdentifier":"c:@T@JSValueRef"},{"kind":"text","text":"?>!) -> "},{"kind":"typeIdentifier","text":"JSValueRef","preciseIdentifier":"c:@T@JSValueRef"},{"kind":"text","text":"!"}],"url":"/documentation/javascriptcore/jsobjectcallasfunction(_:_:_:_:_:_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsConstructor(_:_:_:_:_:)":{"identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsConstructor(_:_:_:_:_:)","url":"/documentation/javascriptcore/jsobjectcallasconstructor(_:_:_:_:_:)","abstract":[{"text":"Calls an object as a constructor.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"JSObjectCallAsConstructor","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSObjectCallAsConstructor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JSContextRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSContextRef"},{"text":"!, ","kind":"text"},{"text":"JSObjectRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSObjectRef"},{"text":"!, ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"JSValueRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSValueRef"},{"text":"?>!, ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"JSValueRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSValueRef"},{"text":"?>!) -> ","kind":"text"},{"text":"JSObjectRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSObjectRef"},{"text":"!","kind":"text"}],"title":"JSObjectCallAsConstructor(_:_:_:_:_:)"},"doc://com.externally.resolved.symbol/s:Sp":{"title":"UnsafeMutablePointer","role":"symbol","url":"/documentation/Swift/UnsafeMutablePointer","type":"topic","abstract":[{"text":"A pointer for accessing and manipulating data of a specific type.","type":"text"}],"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Pointee"},{"kind":"text","text":"> "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Pointee"},{"kind":"text","text":" : ~Copyable"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sp"},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPrivate(_:)":{"navigatorTitle":[{"kind":"identifier","text":"JSObjectGetPrivate"}],"abstract":[{"text":"Gets an object’s private data.","type":"text"}],"identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPrivate(_:)","title":"JSObjectGetPrivate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSObjectGetPrivate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"JSObjectRef","preciseIdentifier":"c:@T@JSObjectRef"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"!"}],"url":"/documentation/javascriptcore/jsobjectgetprivate(_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCopyPropertyNames(_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"JSObjectCopyPropertyNames"}],"abstract":[{"text":"Gets the names of an object’s enumerable properties.","type":"text"}],"identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCopyPropertyNames(_:_:)","title":"JSObjectCopyPropertyNames(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSObjectCopyPropertyNames"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@JSContextRef","kind":"typeIdentifier","text":"JSContextRef"},{"kind":"text","text":"!, "},{"preciseIdentifier":"c:@T@JSObjectRef","kind":"typeIdentifier","text":"JSObjectRef"},{"kind":"text","text":"!) -> "},{"preciseIdentifier":"c:@T@JSPropertyNameArrayRef","kind":"typeIdentifier","text":"JSPropertyNameArrayRef"},{"kind":"text","text":"!"}],"url":"/documentation/javascriptcore/jsobjectcopypropertynames(_:_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef":{"navigatorTitle":[{"kind":"identifier","text":"JSValueRef"}],"title":"JSValueRef","url":"/documentation/javascriptcore/jsvalueref","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSValueRef"}],"abstract":[{"type":"text","text":"A JavaScript value."}],"identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef"},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeDate(_:_:_:_:)":{"kind":"symbol","title":"JSObjectMakeDate(_:_:_:_:)","navigatorTitle":[{"text":"JSObjectMakeDate","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeDate(_:_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSObjectMakeDate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JSContextRef","preciseIdentifier":"c:@T@JSContextRef","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"JSValueRef","preciseIdentifier":"c:@T@JSValueRef","kind":"typeIdentifier"},{"text":"?>!, ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"JSValueRef","preciseIdentifier":"c:@T@JSValueRef","kind":"typeIdentifier"},{"text":"?>!) -> ","kind":"text"},{"text":"JSObjectRef","preciseIdentifier":"c:@T@JSObjectRef","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"url":"/documentation/javascriptcore/jsobjectmakedate(_:_:_:_:)","abstract":[{"text":"Creates a JavaScript date object as though invoking the built-in date constructor.","type":"text"}],"role":"symbol"},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyAtIndex(_:_:_:_:)":{"url":"/documentation/javascriptcore/jsobjectgetpropertyatindex(_:_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSObjectGetPropertyAtIndex","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JSContextRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSContextRef"},{"text":"!, ","kind":"text"},{"text":"JSObjectRef","preciseIdentifier":"c:@T@JSObjectRef","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"JSValueRef","preciseIdentifier":"c:@T@JSValueRef","kind":"typeIdentifier"},{"text":"?>!) -> ","kind":"text"},{"text":"JSValueRef","preciseIdentifier":"c:@T@JSValueRef","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"role":"symbol","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyAtIndex(_:_:_:_:)","kind":"symbol","abstract":[{"text":"Gets a property from an object by numeric index.","type":"text"}],"title":"JSObjectGetPropertyAtIndex(_:_:_:_:)","type":"topic","navigatorTitle":[{"text":"JSObjectGetPropertyAtIndex","kind":"identifier"}]},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectIsConstructor(_:_:)":{"url":"/documentation/javascriptcore/jsobjectisconstructor(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSObjectIsConstructor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JSContextRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSContextRef"},{"text":"!, ","kind":"text"},{"text":"JSObjectRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSObjectRef"},{"text":"!) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectIsConstructor(_:_:)","kind":"symbol","abstract":[{"text":"Tests whether you can call an object as a constructor.","type":"text"}],"title":"JSObjectIsConstructor(_:_:)","type":"topic","navigatorTitle":[{"text":"JSObjectIsConstructor","kind":"identifier"}]},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeArray(_:_:_:_:)":{"navigatorTitle":[{"text":"JSObjectMakeArray","kind":"identifier"}],"abstract":[{"text":"Creates a JavaScript array object.","type":"text"}],"identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeArray(_:_:_:_:)","title":"JSObjectMakeArray(_:_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSObjectMakeArray","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JSContextRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSContextRef"},{"text":"!, ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"JSValueRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSValueRef"},{"text":"?>!, ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"JSValueRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSValueRef"},{"text":"?>!) -> ","kind":"text"},{"text":"JSObjectRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSObjectRef"},{"text":"!","kind":"text"}],"url":"/documentation/javascriptcore/jsobjectmakearray(_:_:_:_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://com.apple.javascriptcore/documentation/JavaScriptCore":{"abstract":[{"type":"text","text":"Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app."}],"identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore","title":"JavaScriptCore","url":"/documentation/javascriptcore","role":"collection","kind":"symbol","type":"topic"},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeError(_:_:_:_:)":{"role":"symbol","navigatorTitle":[{"text":"JSObjectMakeError","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Creates a JavaScript error object as though invoking the built-in error constructor.","type":"text"}],"type":"topic","title":"JSObjectMakeError(_:_:_:_:)","url":"/documentation/javascriptcore/jsobjectmakeerror(_:_:_:_:)","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeError(_:_:_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSObjectMakeError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JSContextRef","preciseIdentifier":"c:@T@JSContextRef","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"JSValueRef","preciseIdentifier":"c:@T@JSValueRef","kind":"typeIdentifier"},{"text":"?>!, ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"JSValueRef","preciseIdentifier":"c:@T@JSValueRef","kind":"typeIdentifier"},{"text":"?>!) -> ","kind":"text"},{"text":"JSObjectRef","preciseIdentifier":"c:@T@JSObjectRef","kind":"typeIdentifier"},{"text":"!","kind":"text"}]},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeConstructor(_:_:_:)":{"navigatorTitle":[{"kind":"identifier","text":"JSObjectMakeConstructor"}],"role":"symbol","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeConstructor(_:_:_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSObjectMakeConstructor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"JSContextRef","preciseIdentifier":"c:@T@JSContextRef"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"JSClassRef","preciseIdentifier":"c:@T@JSClassRef"},{"kind":"text","text":"!, "},{"kind":"typeIdentifier","text":"JSObjectCallAsConstructorCallback","preciseIdentifier":"c:@T@JSObjectCallAsConstructorCallback"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"JSObjectRef","preciseIdentifier":"c:@T@JSObjectRef"},{"kind":"text","text":"!"}],"title":"JSObjectMakeConstructor(_:_:_:)","abstract":[{"text":"Creates a JavaScript constructor.","type":"text"}],"url":"/documentation/javascriptcore/jsobjectmakeconstructor(_:_:_:)","type":"topic"},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectHasProperty(_:_:_:)":{"identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectHasProperty(_:_:_:)","url":"/documentation/javascriptcore/jsobjecthasproperty(_:_:_:)","abstract":[{"type":"text","text":"Tests whether an object has a specified property."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"JSObjectHasProperty","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JSObjectHasProperty"},{"text":"(","kind":"text"},{"text":"JSContextRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSContextRef"},{"text":"!, ","kind":"text"},{"text":"JSObjectRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSObjectRef"},{"text":"!, ","kind":"text"},{"text":"JSStringRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSStringRef"},{"text":"!) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"JSObjectHasProperty(_:_:_:)"},"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMake(_:_:_:)":{"kind":"symbol","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMake(_:_:_:)","navigatorTitle":[{"text":"JSObjectMake","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Creates a JavaScript object.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSObjectMake","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JSContextRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSContextRef"},{"text":"!, ","kind":"text"},{"text":"JSClassRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSClassRef"},{"text":"!, ","kind":"text"},{"text":"UnsafeMutableRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:Sv"},{"text":"!) -> ","kind":"text"},{"text":"JSObjectRef","kind":"typeIdentifier","preciseIdentifier":"c:@T@JSObjectRef"},{"text":"!","kind":"text"}],"url":"/documentation/javascriptcore/jsobjectmake(_:_:_:)","title":"JSObjectMake(_:_:_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"name":"iOS","introducedAt":"7.0","unavailable":false,"beta":false},{"deprecated":false,"name":"iPadOS","introducedAt":"7.0","unavailable":false,"beta":false},{"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"beta":false},{"deprecated":false,"name":"macOS","introducedAt":"10.6","unavailable":false,"beta":false},{"introducedAt":"9.0","beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","unavailable":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Function","op":"replace","path":"/metadata/roleHeading"},{"value":"JSObjectMakeDate","op":"replace","path":"/metadata/title"},{"value":"func","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"JSObjectMakeDate"}],"op":"replace","path":"/metadata/fragments"},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.javascriptcore/documentation/JavaScriptCore"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsConstructor(_:_:_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCallAsFunction(_:_:_:_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectCopyPropertyNames(_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectDeleteProperty(_:_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPrivate(_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetProperty(_:_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPropertyAtIndex(_:_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetPrototype(_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectHasProperty(_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectIsConstructor(_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectIsFunction(_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMake(_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeArray(_:_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeConstructor(_:_:_:)","doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeError(_:_:_:_:)"],"anchor":"Working-with-Objects","title":"Working with Objects"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"preciseIdentifier":"c:@T@JSObjectRef","kind":"typeIdentifier","text":"JSObjectRef","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectRef"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSObjectMakeDate"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@JSContextRef","kind":"typeIdentifier","text":"JSContextRef","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef"},{"kind":"text","text":" "},{"kind":"internalParam","text":"ctx"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@T@size_t","text":"size_t","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"argumentCount","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@T@JSValueRef","text":"JSValueRef","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"arguments","kind":"internalParam"},{"text":"[], ","kind":"text"},{"preciseIdentifier":"c:@T@JSValueRef","text":"JSValueRef","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"exception","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"/primaryContentSections/1","value":{"parameters":[{"name":"ctx","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The execution context to use."}]}]},{"name":"argumentCount","content":[{"inlineContent":[{"type":"text","text":"An integer count of the number of arguments in "},{"type":"codeVoice","code":"arguments"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"arguments","content":[{"inlineContent":[{"text":"A ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef"},{"text":" array of arguments to pass to the ","type":"text"},{"code":"Date","type":"codeVoice"},{"text":" constructor. Pass ","type":"text"},{"code":"NULL","type":"codeVoice"},{"text":" if ","type":"text"},{"code":"argumentCount","type":"codeVoice"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"0"},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"exception","content":[{"type":"paragraph","inlineContent":[{"text":"A pointer to a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef"},{"text":" to store an exception in, if any. Pass ","type":"text"},{"type":"codeVoice","code":"NULL"},{"text":" to discard any exception.","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"path":"/primaryContentSections/2","op":"replace","value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"text":"A ","type":"text"},{"identifier":"doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectRef","isActive":true,"type":"reference"},{"text":" that is a date.","type":"text"}],"type":"paragraph"}]}},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectDeleteProperty(_:_:_:_:)/title","value":"JSObjectDeleteProperty","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectDeleteProperty(_:_:_:_:)/fragments","value":[{"text":"JSObjectDeleteProperty","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPrototype(_:_:)/title","value":"JSObjectGetPrototype","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPrototype(_:_:)/fragments","value":[{"kind":"identifier","text":"JSObjectGetPrototype"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetProperty(_:_:_:_:)/title","value":"JSObjectGetProperty","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetProperty(_:_:_:_:)/fragments","value":[{"text":"JSObjectGetProperty","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextRef/title","value":"JSContextRef","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextRef/fragments","value":[{"text":"JSContextRef","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextRef/navigatorTitle","value":[{"kind":"identifier","text":"JSContextRef"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectIsFunction(_:_:)/title","value":"JSObjectIsFunction","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectIsFunction(_:_:)/fragments","value":[{"text":"JSObjectIsFunction","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectRef/title","value":"JSObjectRef","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectRef/fragments","value":[{"text":"JSObjectRef","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectRef/navigatorTitle","value":[{"text":"JSObjectRef","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCallAsFunction(_:_:_:_:_:_:)/title","value":"JSObjectCallAsFunction","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCallAsFunction(_:_:_:_:_:_:)/fragments","value":[{"kind":"identifier","text":"JSObjectCallAsFunction"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCallAsConstructor(_:_:_:_:_:)/title","value":"JSObjectCallAsConstructor","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCallAsConstructor(_:_:_:_:_:)/fragments","value":[{"kind":"identifier","text":"JSObjectCallAsConstructor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPrivate(_:)/title","value":"JSObjectGetPrivate","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPrivate(_:)/fragments","value":[{"kind":"identifier","text":"JSObjectGetPrivate"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCopyPropertyNames(_:_:)/title","value":"JSObjectCopyPropertyNames","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectCopyPropertyNames(_:_:)/fragments","value":[{"kind":"identifier","text":"JSObjectCopyPropertyNames"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueRef/title","value":"JSValueRef","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueRef/fragments","value":[{"kind":"identifier","text":"JSValueRef"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueRef/navigatorTitle","value":[{"text":"JSValueRef","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeDate(_:_:_:_:)/title","value":"JSObjectMakeDate","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeDate(_:_:_:_:)/fragments","value":[{"kind":"identifier","text":"JSObjectMakeDate"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPropertyAtIndex(_:_:_:_:)/title","value":"JSObjectGetPropertyAtIndex","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetPropertyAtIndex(_:_:_:_:)/fragments","value":[{"kind":"identifier","text":"JSObjectGetPropertyAtIndex"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectIsConstructor(_:_:)/title","value":"JSObjectIsConstructor","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectIsConstructor(_:_:)/fragments","value":[{"text":"JSObjectIsConstructor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeArray(_:_:_:_:)/title","value":"JSObjectMakeArray","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeArray(_:_:_:_:)/fragments","value":[{"kind":"identifier","text":"JSObjectMakeArray"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeError(_:_:_:_:)/title","value":"JSObjectMakeError","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeError(_:_:_:_:)/fragments","value":[{"text":"JSObjectMakeError","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeConstructor(_:_:_:)/title","value":"JSObjectMakeConstructor","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeConstructor(_:_:_:)/fragments","value":[{"text":"JSObjectMakeConstructor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectHasProperty(_:_:_:)/title","value":"JSObjectHasProperty","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectHasProperty(_:_:_:)/fragments","value":[{"text":"JSObjectHasProperty","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMake(_:_:_:)/title","value":"JSObjectMake","op":"replace"},{"path":"/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMake(_:_:_:)/fragments","value":[{"kind":"identifier","text":"JSObjectMake"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}