{
  "abstract": [
    {
      "text": "Creates a JavaScript array buffer object from an existing pointer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeArrayBufferWithBytesNoCopy(_:_:_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@JSObjectMakeArrayBufferWithBytesNoCopy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "JSObjectMakeArrayBufferWithBytesNoCopy"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSContextRef",
        "text": "JSContextRef"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sv",
        "text": "UnsafeMutableRawPointer"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSTypedArrayBytesDeallocator",
        "text": "JSTypedArrayBytesDeallocator"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sv",
        "text": "UnsafeMutableRawPointer"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSValueRef",
        "text": "JSValueRef"
      },
      {
        "kind": "text",
        "text": "?>!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSObjectRef",
        "text": "JSObjectRef"
      },
      {
        "kind": "text",
        "text": "!"
      }
    ],
    "modules": [
      {
        "name": "JavaScriptCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "JSObjectMakeArrayBufferWithBytesNoCopy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "JSObjectMakeArrayBufferWithBytesNoCopy(_:_:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "JSObjectMakeArrayBufferWithBytesNoCopy"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "ctx"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSContextRef",
              "text": "JSContextRef"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "bytes"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "byteLength"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "bytesDeallocator"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayBytesDeallocator",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSTypedArrayBytesDeallocator",
              "text": "JSTypedArrayBytesDeallocator"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "deallocatorContext"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sv",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sv",
              "text": "UnsafeMutableRawPointer"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "exception"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSValueRef",
              "text": "JSValueRef"
            },
            {
              "kind": "text",
              "text": "?>!) -> "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSObjectRef",
              "text": "JSObjectRef"
            },
            {
              "kind": "text",
              "text": "!"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The execution context to use.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "ctx"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to the byte buffer to use as the backing store of the typed array object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "bytes"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of bytes that ",
                  "type": "text"
                },
                {
                  "code": "bytes",
                  "type": "codeVoice"
                },
                {
                  "text": " points to.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "byteLength"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The allocator to use to deallocate the external buffer when deallocating the typed array object.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "bytesDeallocator"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to pass back to the deallocator.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "deallocatorContext"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to store an exception in, if any. Pass ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " to discard any exception.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "exception"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectRef",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array buffer with a backing store that is the same as the one that ",
              "type": "text"
            },
            {
              "code": "bytes",
              "type": "codeVoice"
            },
            {
              "text": " points to, or ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " if there is an error.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the system throws an exception during this function, it always calls the ",
              "type": "text"
            },
            {
              "code": "bytesDeallocator",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore": {
      "abstract": [
        {
          "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
      "kind": "symbol",
      "role": "collection",
      "title": "JavaScriptCore",
      "type": "topic",
      "url": "/documentation/javascriptcore"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef": {
      "abstract": [
        {
          "text": "A JavaScript execution context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSContextRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSContextRef"
        }
      ],
      "role": "symbol",
      "title": "JSContextRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jscontextref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetArrayBufferByteLength(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the number of bytes in a JavaScript data object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectGetArrayBufferByteLength"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectRef",
          "text": "JSObjectRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetArrayBufferByteLength(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectGetArrayBufferByteLength"
        }
      ],
      "role": "symbol",
      "title": "JSObjectGetArrayBufferByteLength(_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectgetarraybufferbytelength(_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetArrayBufferBytesPtr(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a pointer to the data buffer that serves as the backing store for a JavaScript typed array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectGetArrayBufferBytesPtr"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectRef",
          "text": "JSObjectRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetArrayBufferBytesPtr(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectGetArrayBufferBytesPtr"
        }
      ],
      "role": "symbol",
      "title": "JSObjectGetArrayBufferBytesPtr(_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectgetarraybufferbytesptr(_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeArrayBufferWithBytesNoCopy(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript array buffer object from an existing pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectMakeArrayBufferWithBytesNoCopy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSTypedArrayBytesDeallocator",
          "text": "JSTypedArrayBytesDeallocator"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectRef",
          "text": "JSObjectRef"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeArrayBufferWithBytesNoCopy(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectMakeArrayBufferWithBytesNoCopy"
        }
      ],
      "role": "symbol",
      "title": "JSObjectMakeArrayBufferWithBytesNoCopy(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectmakearraybufferwithbytesnocopy(_:_:_:_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectRef": {
      "abstract": [
        {
          "text": "A JavaScript object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectRef"
        }
      ],
      "role": "symbol",
      "title": "JSObjectRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayBytesDeallocator": {
      "abstract": [
        {
          "text": "A function that deallocates bytes that pass to a typed array constructor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSTypedArrayBytesDeallocator"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayBytesDeallocator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSTypedArrayBytesDeallocator"
        }
      ],
      "role": "symbol",
      "title": "JSTypedArrayBytesDeallocator",
      "type": "topic",
      "url": "/documentation/javascriptcore/jstypedarraybytesdeallocator"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef": {
      "abstract": [
        {
          "text": "A JavaScript value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueRef"
        }
      ],
      "role": "symbol",
      "title": "JSValueRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalueref"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:Sv": {
      "abstract": [
        {
          "text": "A raw pointer for accessing and manipulating untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutableRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sv",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutableRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutableRawPointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Array-Buffers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetArrayBufferByteLength(_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetArrayBufferBytesPtr(_:_:_:)"
      ],
      "title": "Working with Array Buffers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "JSObjectMakeArrayBufferWithBytesNoCopy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectMakeArrayBufferWithBytesNoCopy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Array-Buffers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetArrayBufferByteLength(_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectGetArrayBufferBytesPtr(_:_:_:)"
              ],
              "title": "Working with Array Buffers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@JSObjectRef",
                    "text": "JSObjectRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "JSObjectMakeArrayBufferWithBytesNoCopy"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@JSContextRef",
                    "text": "JSContextRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "ctx"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "bytes"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@size_t",
                    "text": "size_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "byteLength"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayBytesDeallocator",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@JSTypedArrayBytesDeallocator",
                    "text": "JSTypedArrayBytesDeallocator"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "bytesDeallocator"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "deallocatorContext"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@JSValueRef",
                    "text": "JSValueRef"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "exception"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The execution context to use.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "ctx"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to the byte buffer to use as the backing store of the typed array object.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "bytes"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The number of bytes that ",
                        "type": "text"
                      },
                      {
                        "code": "bytes",
                        "type": "codeVoice"
                      },
                      {
                        "text": " points to.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "byteLength"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The allocator to use to deallocate the external buffer when deallocating the typed array object.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "bytesDeallocator"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to pass back to the deallocator.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "deallocatorContext"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pointer to a ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to store an exception in, if any. Pass ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to discard any exception.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "exception"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectRef",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " array buffer with a backing store that is the same as the one that ",
                    "type": "text"
                  },
                  {
                    "code": "bytes",
                    "type": "codeVoice"
                  },
                  {
                    "text": " points to, or ",
                    "type": "text"
                  },
                  {
                    "code": "NULL",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if there is an error.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSTypedArrayBytesDeallocator/title",
          "value": "JSTypedArrayBytesDeallocator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSTypedArrayBytesDeallocator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSTypedArrayBytesDeallocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSTypedArrayBytesDeallocator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSTypedArrayBytesDeallocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeArrayBufferWithBytesNoCopy(_:_:_:_:_:_:)/title",
          "value": "JSObjectMakeArrayBufferWithBytesNoCopy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeArrayBufferWithBytesNoCopy(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectMakeArrayBufferWithBytesNoCopy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetArrayBufferBytesPtr(_:_:_:)/title",
          "value": "JSObjectGetArrayBufferBytesPtr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetArrayBufferBytesPtr(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectGetArrayBufferBytesPtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextRef/title",
          "value": "JSContextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectRef/title",
          "value": "JSObjectRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueRef/title",
          "value": "JSValueRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetArrayBufferByteLength(_:_:_:)/title",
          "value": "JSObjectGetArrayBufferByteLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectGetArrayBufferByteLength(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectGetArrayBufferByteLength"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/javascriptcore/jsobjectmakearraybufferwithbytesnocopy(_:_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/javascriptcore/jsobjectmakearraybufferwithbytesnocopy(_:_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
