{
  "abstract": [
    {
      "text": "The value for the property on the JavaScript object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorValueKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@JSPropertyDescriptorValueKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "JSPropertyDescriptorValueKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "JavaScriptCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "JSPropertyDescriptorValueKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "JSPropertyDescriptorValueKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "JSPropertyDescriptorValueKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore": {
      "abstract": [
        {
          "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
      "kind": "symbol",
      "role": "collection",
      "title": "JavaScriptCore",
      "type": "topic",
      "url": "/documentation/javascriptcore"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorConfigurableKey": {
      "abstract": [
        {
          "text": "The Boolean value for this key determines whether the property deleted from its JavaScript object or its descriptor changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorConfigurableKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorConfigurableKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorConfigurableKey"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyDescriptorConfigurableKey",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertydescriptorconfigurablekey"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorEnumerableKey": {
      "abstract": [
        {
          "text": "The Boolean value for this key determines whether the property appears when enumerating the JavaScript object’s properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorEnumerableKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorEnumerableKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorEnumerableKey"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyDescriptorEnumerableKey",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertydescriptorenumerablekey"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorGetKey": {
      "abstract": [
        {
          "text": "The JavaScript function to be invoked when reading the property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorGetKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorGetKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorGetKey"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyDescriptorGetKey",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertydescriptorgetkey"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorSetKey": {
      "abstract": [
        {
          "text": "The JavaScript function to be invoked when writing to the property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorSetKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorSetKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorSetKey"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyDescriptorSetKey",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertydescriptorsetkey"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorValueKey": {
      "abstract": [
        {
          "text": "The value for the property on the JavaScript object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorValueKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorValueKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorValueKey"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyDescriptorValueKey",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertydescriptorvaluekey"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorWritableKey": {
      "abstract": [
        {
          "text": "The Boolean value for this key determines whether the property permits assignment with the JavaScript ",
          "type": "text"
        },
        {
          "code": "=",
          "type": "codeVoice"
        },
        {
          "text": " operator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorWritableKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorWritableKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorWritableKey"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyDescriptorWritableKey",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertydescriptorwritablekey"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorWritableKey",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorEnumerableKey",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorConfigurableKey",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorGetKey",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorSetKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "JSPropertyDescriptorValueKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyDescriptorValueKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorWritableKey",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorEnumerableKey",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorConfigurableKey",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorGetKey",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorSetKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "JSPropertyDescriptorValueKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorEnumerableKey/title",
          "value": "JSPropertyDescriptorEnumerableKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorEnumerableKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyDescriptorEnumerableKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorGetKey/title",
          "value": "JSPropertyDescriptorGetKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorGetKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyDescriptorGetKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorConfigurableKey/title",
          "value": "JSPropertyDescriptorConfigurableKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorConfigurableKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyDescriptorConfigurableKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorValueKey/title",
          "value": "JSPropertyDescriptorValueKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorValueKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyDescriptorValueKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorWritableKey/title",
          "value": "JSPropertyDescriptorWritableKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorWritableKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyDescriptorWritableKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorSetKey/title",
          "value": "JSPropertyDescriptorSetKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorSetKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyDescriptorSetKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/javascriptcore/jspropertydescriptorvaluekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/javascriptcore/jspropertydescriptorvaluekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
