{
  "abstract": [
    {
      "text": "Gets a count of the number of items in a JavaScript property name array.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayGetCount(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@JSPropertyNameArrayGetCount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "JSPropertyNameArrayGetCount"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSPropertyNameArrayRef",
        "text": "JSPropertyNameArrayRef"
      },
      {
        "kind": "text",
        "text": "!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "JavaScriptCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "JSPropertyNameArrayGetCount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "JSPropertyNameArrayGetCount(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "JSPropertyNameArrayGetCount"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "array"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSPropertyNameArrayRef",
              "text": "JSPropertyNameArrayRef"
            },
            {
              "kind": "text",
              "text": "!) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The array to retrieve the count from.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "array"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An integer count of the number of names in ",
              "type": "text"
            },
            {
              "code": "array",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore": {
      "abstract": [
        {
          "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
      "kind": "symbol",
      "role": "collection",
      "title": "JavaScriptCore",
      "type": "topic",
      "url": "/documentation/javascriptcore"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyAttribute": {
      "abstract": [
        {
          "text": "A JavaScript property attribute.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyAttribute",
      "kind": "article",
      "role": "collectionGroup",
      "title": "JSPropertyAttribute",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertyattribute"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyAttributes": {
      "abstract": [
        {
          "text": "A set of JavaScript property attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyAttributes"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyAttributes"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyAttributes",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertyattributes"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameAccumulatorAddName(_:_:)": {
      "abstract": [
        {
          "text": "Adds a property name to a JavaScript property name accumulator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyNameAccumulatorAddName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSPropertyNameAccumulatorRef",
          "text": "JSPropertyNameAccumulatorRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameAccumulatorAddName(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyNameAccumulatorAddName"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyNameAccumulatorAddName(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertynameaccumulatoraddname(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameAccumulatorRef": {
      "abstract": [
        {
          "text": "An ordered set of the names of a JavaScript object’s properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyNameAccumulatorRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameAccumulatorRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyNameAccumulatorRef"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyNameAccumulatorRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertynameaccumulatorref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayGetCount(_:)": {
      "abstract": [
        {
          "text": "Gets a count of the number of items in a JavaScript property name array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayGetCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSPropertyNameArrayRef",
          "text": "JSPropertyNameArrayRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayGetCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayGetCount"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyNameArrayGetCount(_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertynamearraygetcount(_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayGetNameAtIndex(_:_:)": {
      "abstract": [
        {
          "text": "Gets a property name at a specified index in a JavaScript property name array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayGetNameAtIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSPropertyNameArrayRef",
          "text": "JSPropertyNameArrayRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayGetNameAtIndex(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayGetNameAtIndex"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyNameArrayGetNameAtIndex(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertynamearraygetnameatindex(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRef": {
      "abstract": [
        {
          "text": "An array of JavaScript property names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayRef"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyNameArrayRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertynamearrayref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRelease(_:)": {
      "abstract": [
        {
          "text": "Releases a JavaScript property name array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayRelease"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSPropertyNameArrayRef",
          "text": "JSPropertyNameArrayRef"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRelease(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayRelease"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyNameArrayRelease(_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertynamearrayrelease(_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRetain(_:)": {
      "abstract": [
        {
          "text": "Retains a JavaScript property name array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayRetain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSPropertyNameArrayRef",
          "text": "JSPropertyNameArrayRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSPropertyNameArrayRef",
          "text": "JSPropertyNameArrayRef"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRetain(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayRetain"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyNameArrayRetain(_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertynamearrayretain(_:)"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameAccumulatorAddName(_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayGetNameAtIndex(_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRelease(_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRetain(_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyAttributes",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyAttribute",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRef",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameAccumulatorRef"
      ],
      "title": "Working with Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "JSPropertyNameArrayGetCount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameArrayGetCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameAccumulatorAddName(_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayGetNameAtIndex(_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRelease(_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRetain(_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyAttributes",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRef",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameAccumulatorRef"
              ],
              "title": "Working with Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@size_t",
                    "text": "size_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "JSPropertyNameArrayGetCount"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@JSPropertyNameArrayRef",
                    "text": "JSPropertyNameArrayRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "array"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The array to retrieve the count from.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "array"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An integer count of the number of names in ",
                    "type": "text"
                  },
                  {
                    "code": "array",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayGetNameAtIndex(_:_:)/title",
          "value": "JSPropertyNameArrayGetNameAtIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayGetNameAtIndex(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameArrayGetNameAtIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyAttributes/title",
          "value": "JSPropertyAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayRef/title",
          "value": "JSPropertyNameArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameArrayRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameArrayRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayRetain(_:)/title",
          "value": "JSPropertyNameArrayRetain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayRetain(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameArrayRetain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameAccumulatorRef/title",
          "value": "JSPropertyNameAccumulatorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameAccumulatorRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameAccumulatorRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameAccumulatorRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameAccumulatorRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayRelease(_:)/title",
          "value": "JSPropertyNameArrayRelease"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayRelease(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameArrayRelease"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameAccumulatorAddName(_:_:)/title",
          "value": "JSPropertyNameAccumulatorAddName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameAccumulatorAddName(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameAccumulatorAddName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayGetCount(_:)/title",
          "value": "JSPropertyNameArrayGetCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayGetCount(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameArrayGetCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/javascriptcore/jspropertynamearraygetcount(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/javascriptcore/jspropertynamearraygetcount(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
