{
  "abstract": [
    {
      "text": "A JavaScript property attribute.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/c-javascriptcore-api",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectRef"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyAttribute"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "JavaScriptCore"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "JSPropertyAttribute"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore": {
      "abstract": [
        {
          "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
      "kind": "symbol",
      "role": "collection",
      "title": "JavaScriptCore",
      "type": "topic",
      "url": "/documentation/javascriptcore"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectRef": {
      "abstract": [
        {
          "text": "A JavaScript object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectRef"
        }
      ],
      "role": "symbol",
      "title": "JSObjectRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyAttributes": {
      "abstract": [
        {
          "text": "A set of JavaScript property attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyAttributes"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyAttributes"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyAttributes",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertyattributes"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameAccumulatorAddName(_:_:)": {
      "abstract": [
        {
          "text": "Adds a property name to a JavaScript property name accumulator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyNameAccumulatorAddName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSPropertyNameAccumulatorRef",
          "text": "JSPropertyNameAccumulatorRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameAccumulatorAddName(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyNameAccumulatorAddName"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyNameAccumulatorAddName(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertynameaccumulatoraddname(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameAccumulatorRef": {
      "abstract": [
        {
          "text": "An ordered set of the names of a JavaScript object’s properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyNameAccumulatorRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameAccumulatorRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyNameAccumulatorRef"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyNameAccumulatorRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertynameaccumulatorref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayGetCount(_:)": {
      "abstract": [
        {
          "text": "Gets a count of the number of items in a JavaScript property name array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayGetCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSPropertyNameArrayRef",
          "text": "JSPropertyNameArrayRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayGetCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayGetCount"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyNameArrayGetCount(_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertynamearraygetcount(_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayGetNameAtIndex(_:_:)": {
      "abstract": [
        {
          "text": "Gets a property name at a specified index in a JavaScript property name array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayGetNameAtIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSPropertyNameArrayRef",
          "text": "JSPropertyNameArrayRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayGetNameAtIndex(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayGetNameAtIndex"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyNameArrayGetNameAtIndex(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertynamearraygetnameatindex(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRef": {
      "abstract": [
        {
          "text": "An array of JavaScript property names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayRef"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyNameArrayRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertynamearrayref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRelease(_:)": {
      "abstract": [
        {
          "text": "Releases a JavaScript property name array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayRelease"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSPropertyNameArrayRef",
          "text": "JSPropertyNameArrayRef"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRelease(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayRelease"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyNameArrayRelease(_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertynamearrayrelease(_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRetain(_:)": {
      "abstract": [
        {
          "text": "Retains a JavaScript property name array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayRetain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSPropertyNameArrayRef",
          "text": "JSPropertyNameArrayRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSPropertyNameArrayRef",
          "text": "JSPropertyNameArrayRef"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRetain(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyNameArrayRetain"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyNameArrayRetain(_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertynamearrayretain(_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/c-javascriptcore-api": {
      "abstract": [
        {
          "text": "Browse the alternative C-based APIs for JavaScriptCore.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/c-javascriptcore-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "C JavaScriptCore API",
      "type": "topic",
      "url": "/documentation/javascriptcore/c-javascriptcore-api"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSPropertyAttributeDontDelete": {
      "abstract": [
        {
          "text": "An attribute that specifies that the delete operation fails on a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSPropertyAttributeDontDelete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSPropertyAttributeDontDelete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSPropertyAttributeDontDelete"
        }
      ],
      "role": "symbol",
      "title": "kJSPropertyAttributeDontDelete",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjspropertyattributedontdelete"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSPropertyAttributeDontEnum": {
      "abstract": [
        {
          "text": "An attribute that specifies that property enumerators and JavaScript for-in loops don’t enumerate a property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSPropertyAttributeDontEnum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSPropertyAttributeDontEnum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSPropertyAttributeDontEnum"
        }
      ],
      "role": "symbol",
      "title": "kJSPropertyAttributeDontEnum",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjspropertyattributedontenum"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSPropertyAttributeNone": {
      "abstract": [
        {
          "text": "An attribute that specifies that a property has no special attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSPropertyAttributeNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSPropertyAttributeNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSPropertyAttributeNone"
        }
      ],
      "role": "symbol",
      "title": "kJSPropertyAttributeNone",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjspropertyattributenone"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSPropertyAttributeReadOnly": {
      "abstract": [
        {
          "text": "An attribute that specifies that a property is read-only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSPropertyAttributeReadOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSPropertyAttributeReadOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSPropertyAttributeReadOnly"
        }
      ],
      "role": "symbol",
      "title": "kJSPropertyAttributeReadOnly",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjspropertyattributereadonly"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameAccumulatorAddName(_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayGetCount(_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayGetNameAtIndex(_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRelease(_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRetain(_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyAttributes",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameArrayRef",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyNameAccumulatorRef"
      ],
      "title": "Working with Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSPropertyAttributeNone",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSPropertyAttributeReadOnly",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSPropertyAttributeDontEnum",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSPropertyAttributeDontDelete"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSPropertyAttributeDontDelete/title",
          "value": "kJSPropertyAttributeDontDelete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSPropertyAttributeDontDelete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSPropertyAttributeDontDelete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayGetCount(_:)/title",
          "value": "JSPropertyNameArrayGetCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayGetCount(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameArrayGetCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameAccumulatorAddName(_:_:)/title",
          "value": "JSPropertyNameAccumulatorAddName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameAccumulatorAddName(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameAccumulatorAddName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameAccumulatorRef/title",
          "value": "JSPropertyNameAccumulatorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameAccumulatorRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameAccumulatorRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameAccumulatorRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameAccumulatorRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayGetNameAtIndex(_:_:)/title",
          "value": "JSPropertyNameArrayGetNameAtIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayGetNameAtIndex(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameArrayGetNameAtIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayRef/title",
          "value": "JSPropertyNameArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameArrayRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameArrayRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSPropertyAttributeNone/title",
          "value": "kJSPropertyAttributeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSPropertyAttributeNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSPropertyAttributeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayRelease(_:)/title",
          "value": "JSPropertyNameArrayRelease"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayRelease(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameArrayRelease"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayRetain(_:)/title",
          "value": "JSPropertyNameArrayRetain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyNameArrayRetain(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyNameArrayRetain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSPropertyAttributeReadOnly/title",
          "value": "kJSPropertyAttributeReadOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSPropertyAttributeReadOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSPropertyAttributeReadOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSPropertyAttributeDontEnum/title",
          "value": "kJSPropertyAttributeDontEnum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSPropertyAttributeDontEnum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSPropertyAttributeDontEnum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectRef/title",
          "value": "JSObjectRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyAttributes/title",
          "value": "JSPropertyAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyAttributes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/javascriptcore/jspropertyattribute"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
