{
  "abstract": [
    {
      "text": "A UTF-16 character buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringRef"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@JSStringRef",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "JSStringRef"
      }
    ],
    "modules": [
      {
        "name": "JavaScriptCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "JSStringRef"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "JSStringRef"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "JSStringRef"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s13OpaquePointerV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s13OpaquePointerV",
              "text": "OpaquePointer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This is the fundamental string representation in JavaScript.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore": {
      "abstract": [
        {
          "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
      "kind": "symbol",
      "role": "collection",
      "title": "JavaScriptCore",
      "type": "topic",
      "url": "/documentation/javascriptcore"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSChar": {
      "abstract": [
        {
          "text": "A Unicode character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSChar"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSChar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSChar"
        }
      ],
      "role": "symbol",
      "title": "JSChar",
      "type": "topic",
      "url": "/documentation/javascriptcore/jschar"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassRef": {
      "abstract": [
        {
          "text": "A JavaScript class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSClassRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSClassRef"
        }
      ],
      "role": "symbol",
      "title": "JSClassRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsclassref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextGroupRef": {
      "abstract": [
        {
          "text": "A group that associates JavaScript contexts with one another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSContextGroupRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextGroupRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSContextGroupRef"
        }
      ],
      "role": "symbol",
      "title": "JSContextGroupRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jscontextgroupref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef": {
      "abstract": [
        {
          "text": "A JavaScript execution context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSContextRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSContextRef"
        }
      ],
      "role": "symbol",
      "title": "JSContextRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jscontextref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSGlobalContextRef": {
      "abstract": [
        {
          "text": "A global JavaScript execution context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSGlobalContextRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSGlobalContextRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSGlobalContextRef"
        }
      ],
      "role": "symbol",
      "title": "JSGlobalContextRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsglobalcontextref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringCopyCFString(_:_:)": {
      "abstract": [
        {
          "text": "Creates a Core Foundation string from a JavaScript string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSStringCopyCFString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringCopyCFString(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSStringCopyCFString"
        }
      ],
      "role": "symbol",
      "title": "JSStringCopyCFString(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstringcopycfstring(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringCreateWithCFString(_:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript string from a Core Foundation string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSStringCreateWithCFString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringCreateWithCFString(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSStringCreateWithCFString"
        }
      ],
      "role": "symbol",
      "title": "JSStringCreateWithCFString(_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstringcreatewithcfstring(_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringCreateWithCharacters(_:_:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript string from a buffer of Unicode characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSStringCreateWithCharacters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSChar",
          "text": "JSChar"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringCreateWithCharacters(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSStringCreateWithCharacters"
        }
      ],
      "role": "symbol",
      "title": "JSStringCreateWithCharacters(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstringcreatewithcharacters(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringCreateWithUTF8CString(_:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript string from a null-terminated UTF-8 string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSStringCreateWithUTF8CString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringCreateWithUTF8CString(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSStringCreateWithUTF8CString"
        }
      ],
      "role": "symbol",
      "title": "JSStringCreateWithUTF8CString(_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstringcreatewithutf8cstring(_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringGetCharactersPtr(_:)": {
      "abstract": [
        {
          "text": "Returns a pointer to the Unicode character buffer that serves as the backing store for a JavaScript string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSStringGetCharactersPtr"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSChar",
          "text": "JSChar"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringGetCharactersPtr(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSStringGetCharactersPtr"
        }
      ],
      "role": "symbol",
      "title": "JSStringGetCharactersPtr(_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstringgetcharactersptr(_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringGetLength(_:)": {
      "abstract": [
        {
          "text": "Returns the number of Unicode characters in a JavaScript string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSStringGetLength"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringGetLength(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSStringGetLength"
        }
      ],
      "role": "symbol",
      "title": "JSStringGetLength(_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstringgetlength(_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringGetMaximumUTF8CStringSize(_:)": {
      "abstract": [
        {
          "text": "Returns the maximum number of bytes a JavaScript string uses when you convert it into a null-terminated UTF-8 string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSStringGetMaximumUTF8CStringSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringGetMaximumUTF8CStringSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSStringGetMaximumUTF8CStringSize"
        }
      ],
      "role": "symbol",
      "title": "JSStringGetMaximumUTF8CStringSize(_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstringgetmaximumutf8cstringsize(_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringGetUTF8CString(_:_:_:)": {
      "abstract": [
        {
          "text": "Converts a JavaScript string into a null-terminated UTF-8 string, and copies the result into an external byte buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSStringGetUTF8CString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringGetUTF8CString(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSStringGetUTF8CString"
        }
      ],
      "role": "symbol",
      "title": "JSStringGetUTF8CString(_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstringgetutf8cstring(_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringIsEqual(_:_:)": {
      "abstract": [
        {
          "text": "Tests whether two JavaScript strings match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSStringIsEqual"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringIsEqual(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSStringIsEqual"
        }
      ],
      "role": "symbol",
      "title": "JSStringIsEqual(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstringisequal(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringIsEqualToUTF8CString(_:_:)": {
      "abstract": [
        {
          "text": "Tests whether a JavaScript string matches a null-terminated UTF-8 string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSStringIsEqualToUTF8CString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringIsEqualToUTF8CString(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSStringIsEqualToUTF8CString"
        }
      ],
      "role": "symbol",
      "title": "JSStringIsEqualToUTF8CString(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstringisequaltoutf8cstring(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringRef": {
      "abstract": [
        {
          "text": "A UTF-16 character buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSStringRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSStringRef"
        }
      ],
      "role": "symbol",
      "title": "JSStringRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstringref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringRelease(_:)": {
      "abstract": [
        {
          "text": "Releases a JavaScript string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSStringRelease"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringRelease(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSStringRelease"
        }
      ],
      "role": "symbol",
      "title": "JSStringRelease(_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstringrelease(_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringRetain(_:)": {
      "abstract": [
        {
          "text": "Retains a JavaScript string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSStringRetain"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSStringRef",
          "text": "JSStringRef"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringRetain(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSStringRetain"
        }
      ],
      "role": "symbol",
      "title": "JSStringRetain(_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsstringretain(_:)"
    },
    "doc://com.externally.resolved.symbol/s:s13OpaquePointerV": {
      "abstract": [
        {
          "text": "A wrapper around an opaque C pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OpaquePointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s13OpaquePointerV",
      "kind": "symbol",
      "role": "symbol",
      "title": "OpaquePointer",
      "type": "topic",
      "url": "/documentation/Swift/OpaquePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "JavaScriptCore-Engine-Interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextGroupRef",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSGlobalContextRef",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassRef"
      ],
      "title": "JavaScriptCore Engine Interface"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-JavaScript-String",
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringCreateWithCharacters(_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSChar",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringCreateWithUTF8CString(_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringRetain(_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringRelease(_:)"
      ],
      "title": "Creating a JavaScript String"
    },
    {
      "anchor": "Accessing-JavaScript-String-Information",
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringGetLength(_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringGetCharactersPtr(_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringGetMaximumUTF8CStringSize(_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringGetUTF8CString(_:_:_:)"
      ],
      "title": "Accessing JavaScript String Information"
    },
    {
      "anchor": "Comparing-JavaScript-Strings",
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringIsEqual(_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringIsEqualToUTF8CString(_:_:)"
      ],
      "title": "Comparing JavaScript Strings"
    },
    {
      "anchor": "Converting-to-and-from-Core-Foundation-Strings",
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringCreateWithCFString(_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringCopyCFString(_:_:)"
      ],
      "title": "Converting to and from Core Foundation Strings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "JSStringRef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-JavaScript-String",
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringCreateWithCharacters(_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSChar",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringCreateWithUTF8CString(_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringRetain(_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringRelease(_:)"
              ],
              "title": "Creating a JavaScript String"
            },
            {
              "anchor": "Accessing-JavaScript-String-Information",
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringGetLength(_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringGetCharactersPtr(_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringGetMaximumUTF8CStringSize(_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringGetUTF8CString(_:_:_:)"
              ],
              "title": "Accessing JavaScript String Information"
            },
            {
              "anchor": "Comparing-JavaScript-Strings",
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringIsEqual(_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringIsEqualToUTF8CString(_:_:)"
              ],
              "title": "Comparing JavaScript Strings"
            },
            {
              "anchor": "Converting-to-and-from-Core-Foundation-Strings",
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringCreateWithCFString(_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSStringCopyCFString(_:_:)"
              ],
              "title": "Converting to and from Core Foundation Strings"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "JavaScriptCore-Engine-Interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextGroupRef",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSGlobalContextRef",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSClassRef"
              ],
              "title": "JavaScriptCore Engine Interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@OpaqueJSString",
                    "text": "OpaqueJSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "JSStringRef"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringCopyCFString(_:_:)/title",
          "value": "JSStringCopyCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringCopyCFString(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringCopyCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringCreateWithCharacters(_:_:)/title",
          "value": "JSStringCreateWithCharacters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringCreateWithCharacters(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringCreateWithCharacters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassRef/title",
          "value": "JSClassRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSClassRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSClassRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSClassRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringGetLength(_:)/title",
          "value": "JSStringGetLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringGetLength(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringGetLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextRef/title",
          "value": "JSContextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSChar/title",
          "value": "JSChar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSChar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSChar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSChar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSChar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringGetUTF8CString(_:_:_:)/title",
          "value": "JSStringGetUTF8CString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringGetUTF8CString(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringGetUTF8CString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringIsEqualToUTF8CString(_:_:)/title",
          "value": "JSStringIsEqualToUTF8CString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringIsEqualToUTF8CString(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringIsEqualToUTF8CString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringGetMaximumUTF8CStringSize(_:)/title",
          "value": "JSStringGetMaximumUTF8CStringSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringGetMaximumUTF8CStringSize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringGetMaximumUTF8CStringSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringCreateWithUTF8CString(_:)/title",
          "value": "JSStringCreateWithUTF8CString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringCreateWithUTF8CString(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringCreateWithUTF8CString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSGlobalContextRef/title",
          "value": "JSGlobalContextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSGlobalContextRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSGlobalContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSGlobalContextRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSGlobalContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringRetain(_:)/title",
          "value": "JSStringRetain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringRetain(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringRetain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextGroupRef/title",
          "value": "JSContextGroupRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextGroupRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContextGroupRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextGroupRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContextGroupRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringCreateWithCFString(_:)/title",
          "value": "JSStringCreateWithCFString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringCreateWithCFString(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringCreateWithCFString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringIsEqual(_:_:)/title",
          "value": "JSStringIsEqual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringIsEqual(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringIsEqual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringGetCharactersPtr(_:)/title",
          "value": "JSStringGetCharactersPtr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringGetCharactersPtr(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringGetCharactersPtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringRelease(_:)/title",
          "value": "JSStringRelease"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringRelease(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringRelease"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringRef/title",
          "value": "JSStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSStringRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSStringRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/javascriptcore/jsstringref"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/javascriptcore/jsstringref"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
