{
  "abstract": [
    {
      "text": "The type of a JavaScript typed array object.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@JSTypedArrayType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "JSTypedArrayType"
      }
    ],
    "modules": [
      {
        "name": "JavaScriptCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "JSTypedArrayType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "JSTypedArrayType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "JSTypedArrayType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore": {
      "abstract": [
        {
          "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
      "kind": "symbol",
      "role": "collection",
      "title": "JavaScriptCore",
      "type": "topic",
      "url": "/documentation/javascriptcore"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeTypedArray(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript typed array object with the specified number of elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectMakeTypedArray"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectRef",
          "text": "JSObjectRef"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeTypedArray(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectMakeTypedArray"
        }
      ],
      "role": "symbol",
      "title": "JSObjectMakeTypedArray(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectmaketypedarray(_:_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeTypedArrayWithArrayBuffer(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript typed array object from an existing JavaScript array buffer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectMakeTypedArrayWithArrayBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectRef",
          "text": "JSObjectRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectRef",
          "text": "JSObjectRef"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeTypedArrayWithArrayBuffer(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectMakeTypedArrayWithArrayBuffer"
        }
      ],
      "role": "symbol",
      "title": "JSObjectMakeTypedArrayWithArrayBuffer(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectmaketypedarraywitharraybuffer(_:_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeTypedArrayWithArrayBufferAndOffset(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript typed array object from an existing JavaScript array buffer object with the specified offset and length.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectMakeTypedArrayWithArrayBufferAndOffset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectRef",
          "text": "JSObjectRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectRef",
          "text": "JSObjectRef"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeTypedArrayWithArrayBufferAndOffset(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectMakeTypedArrayWithArrayBufferAndOffset"
        }
      ],
      "role": "symbol",
      "title": "JSObjectMakeTypedArrayWithArrayBufferAndOffset(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectmaketypedarraywitharraybufferandoffset(_:_:_:_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeTypedArrayWithBytesNoCopy(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a JavaScript typed array object from an existing pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSObjectMakeTypedArrayWithBytesNoCopy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSTypedArrayBytesDeallocator",
          "text": "JSTypedArrayBytesDeallocator"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSObjectRef",
          "text": "JSObjectRef"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeTypedArrayWithBytesNoCopy(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSObjectMakeTypedArrayWithBytesNoCopy"
        }
      ],
      "role": "symbol",
      "title": "JSObjectMakeTypedArrayWithBytesNoCopy(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsobjectmaketypedarraywithbytesnocopy(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayBytesDeallocator": {
      "abstract": [
        {
          "text": "A function that deallocates bytes that pass to a typed array constructor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSTypedArrayBytesDeallocator"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayBytesDeallocator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSTypedArrayBytesDeallocator"
        }
      ],
      "role": "symbol",
      "title": "JSTypedArrayBytesDeallocator",
      "type": "topic",
      "url": "/documentation/javascriptcore/jstypedarraybytesdeallocator"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayType": {
      "abstract": [
        {
          "text": "The type of a JavaScript typed array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSTypedArrayType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSTypedArrayType"
        }
      ],
      "role": "symbol",
      "title": "JSTypedArrayType",
      "type": "topic",
      "url": "/documentation/javascriptcore/jstypedarraytype"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayType/init(_:)": {
      "abstract": [
        {
          "text": "Creates a typed array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayType/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jstypedarraytype/init(_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayType/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a typed array with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jstypedarraytype/init(rawvalue:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayType/rawValue": {
      "abstract": [
        {
          "text": "The raw value that represents the typed array’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayType/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/javascriptcore/jstypedarraytype/rawvalue"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeArrayBuffer": {
      "abstract": [
        {
          "text": "An array buffer type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeArrayBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeArrayBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeArrayBuffer"
        }
      ],
      "role": "symbol",
      "title": "kJSTypedArrayTypeArrayBuffer",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypedarraytypearraybuffer"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeBigInt64Array": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeBigInt64Array"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeBigInt64Array",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeBigInt64Array"
        }
      ],
      "role": "symbol",
      "title": "kJSTypedArrayTypeBigInt64Array",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypedarraytypebigint64array"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeBigUint64Array": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeBigUint64Array"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeBigUint64Array",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeBigUint64Array"
        }
      ],
      "role": "symbol",
      "title": "kJSTypedArrayTypeBigUint64Array",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypedarraytypebiguint64array"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeFloat32Array": {
      "abstract": [
        {
          "text": "A 32-bit floating point array type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeFloat32Array"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeFloat32Array",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeFloat32Array"
        }
      ],
      "role": "symbol",
      "title": "kJSTypedArrayTypeFloat32Array",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypedarraytypefloat32array"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeFloat64Array": {
      "abstract": [
        {
          "text": "A 64-bit floating point array type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeFloat64Array"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeFloat64Array",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeFloat64Array"
        }
      ],
      "role": "symbol",
      "title": "kJSTypedArrayTypeFloat64Array",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypedarraytypefloat64array"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeInt16Array": {
      "abstract": [
        {
          "text": "A 16-bit integer array type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeInt16Array"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeInt16Array",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeInt16Array"
        }
      ],
      "role": "symbol",
      "title": "kJSTypedArrayTypeInt16Array",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypedarraytypeint16array"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeInt32Array": {
      "abstract": [
        {
          "text": "A 32-bit integer array type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeInt32Array"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeInt32Array",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeInt32Array"
        }
      ],
      "role": "symbol",
      "title": "kJSTypedArrayTypeInt32Array",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypedarraytypeint32array"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeInt8Array": {
      "abstract": [
        {
          "text": "An 8-bit integer array type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeInt8Array"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeInt8Array",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeInt8Array"
        }
      ],
      "role": "symbol",
      "title": "kJSTypedArrayTypeInt8Array",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypedarraytypeint8array"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeNone": {
      "abstract": [
        {
          "text": "Not a typed array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeNone"
        }
      ],
      "role": "symbol",
      "title": "kJSTypedArrayTypeNone",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypedarraytypenone"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeUint16Array": {
      "abstract": [
        {
          "text": "A 16-bit unsigned integer array type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeUint16Array"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeUint16Array",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeUint16Array"
        }
      ],
      "role": "symbol",
      "title": "kJSTypedArrayTypeUint16Array",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypedarraytypeuint16array"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeUint32Array": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer array type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeUint32Array"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeUint32Array",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeUint32Array"
        }
      ],
      "role": "symbol",
      "title": "kJSTypedArrayTypeUint32Array",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypedarraytypeuint32array"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeUint8Array": {
      "abstract": [
        {
          "text": "An 8-bit unsigned integer array type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeUint8Array"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeUint8Array",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeUint8Array"
        }
      ],
      "role": "symbol",
      "title": "kJSTypedArrayTypeUint8Array",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypedarraytypeuint8array"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeUint8ClampedArray": {
      "abstract": [
        {
          "text": "An 8-bit unsigned integer clamped array type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeUint8ClampedArray"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeUint8ClampedArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypedArrayTypeUint8ClampedArray"
        }
      ],
      "role": "symbol",
      "title": "kJSTypedArrayTypeUint8ClampedArray",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypedarraytypeuint8clampedarray"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Typed-Array",
      "generated": true,
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeTypedArray(_:_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeTypedArrayWithBytesNoCopy(_:_:_:_:_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeTypedArrayWithArrayBuffer(_:_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeTypedArrayWithArrayBufferAndOffset(_:_:_:_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayBytesDeallocator"
      ],
      "title": "Creating a Typed Array"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeNone",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeArrayBuffer",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeInt8Array",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeInt16Array",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeInt32Array",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeBigInt64Array",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeUint8Array",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeUint8ClampedArray",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeUint16Array",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeUint32Array",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeBigUint64Array",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeFloat32Array",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeFloat64Array"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayType/init(_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayType/init(rawValue:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayType/rawValue"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "JSTypedArrayType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSTypedArrayType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSTypedArrayType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeNone",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeArrayBuffer",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeInt8Array",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeInt16Array",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeInt32Array",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeBigInt64Array",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeUint8Array",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeUint8ClampedArray",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeUint16Array",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeUint32Array",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeBigUint64Array",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeFloat32Array",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypedArrayTypeFloat64Array"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Typed-Array",
              "generated": true,
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeTypedArray(_:_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeTypedArrayWithBytesNoCopy(_:_:_:_:_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeTypedArrayWithArrayBuffer(_:_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSObjectMakeTypedArrayWithArrayBufferAndOffset(_:_:_:_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSTypedArrayBytesDeallocator"
              ],
              "title": "Creating a Typed Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "JSTypedArrayType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeUint32Array/title",
          "value": "kJSTypedArrayTypeUint32Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeUint32Array/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypedArrayTypeUint32Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeInt32Array/title",
          "value": "kJSTypedArrayTypeInt32Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeInt32Array/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypedArrayTypeInt32Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeTypedArrayWithArrayBuffer(_:_:_:_:)/title",
          "value": "JSObjectMakeTypedArrayWithArrayBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeTypedArrayWithArrayBuffer(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectMakeTypedArrayWithArrayBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeTypedArrayWithArrayBufferAndOffset(_:_:_:_:_:_:)/title",
          "value": "JSObjectMakeTypedArrayWithArrayBufferAndOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeTypedArrayWithArrayBufferAndOffset(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectMakeTypedArrayWithArrayBufferAndOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeArrayBuffer/title",
          "value": "kJSTypedArrayTypeArrayBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeArrayBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypedArrayTypeArrayBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeFloat32Array/title",
          "value": "kJSTypedArrayTypeFloat32Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeFloat32Array/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypedArrayTypeFloat32Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeTypedArrayWithBytesNoCopy(_:_:_:_:_:_:_:)/title",
          "value": "JSObjectMakeTypedArrayWithBytesNoCopy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeTypedArrayWithBytesNoCopy(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectMakeTypedArrayWithBytesNoCopy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeBigInt64Array/title",
          "value": "kJSTypedArrayTypeBigInt64Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeBigInt64Array/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypedArrayTypeBigInt64Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeTypedArray(_:_:_:_:)/title",
          "value": "JSObjectMakeTypedArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSObjectMakeTypedArray(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSObjectMakeTypedArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeUint8Array/title",
          "value": "kJSTypedArrayTypeUint8Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeUint8Array/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypedArrayTypeUint8Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSTypedArrayBytesDeallocator/title",
          "value": "JSTypedArrayBytesDeallocator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSTypedArrayBytesDeallocator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSTypedArrayBytesDeallocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSTypedArrayBytesDeallocator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSTypedArrayBytesDeallocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeInt8Array/title",
          "value": "kJSTypedArrayTypeInt8Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeInt8Array/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypedArrayTypeInt8Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeFloat64Array/title",
          "value": "kJSTypedArrayTypeFloat64Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeFloat64Array/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypedArrayTypeFloat64Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeInt16Array/title",
          "value": "kJSTypedArrayTypeInt16Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeInt16Array/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypedArrayTypeInt16Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeUint16Array/title",
          "value": "kJSTypedArrayTypeUint16Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeUint16Array/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypedArrayTypeUint16Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSTypedArrayType/title",
          "value": "JSTypedArrayType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSTypedArrayType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSTypedArrayType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSTypedArrayType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSTypedArrayType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeBigUint64Array/title",
          "value": "kJSTypedArrayTypeBigUint64Array"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeBigUint64Array/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypedArrayTypeBigUint64Array"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeUint8ClampedArray/title",
          "value": "kJSTypedArrayTypeUint8ClampedArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeUint8ClampedArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypedArrayTypeUint8ClampedArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeNone/title",
          "value": "kJSTypedArrayTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypedArrayTypeNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypedArrayTypeNone"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/javascriptcore/jstypedarraytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/javascriptcore/jstypedarraytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
