{
  "abstract": [
    {
      "text": "Tests whether a JavaScript value’s type is the symbol type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsSymbol(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@JSValueIsSymbol",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "JSValueIsSymbol"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSContextRef",
        "text": "JSContextRef"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@JSValueRef",
        "text": "JSValueRef"
      },
      {
        "kind": "text",
        "text": "!) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "JavaScriptCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "JSValueIsSymbol"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "JSValueIsSymbol(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "JSValueIsSymbol"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "ctx"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSContextRef",
              "text": "JSContextRef"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "value"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@JSValueRef",
              "text": "JSValueRef"
            },
            {
              "kind": "text",
              "text": "!) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The execution context to use.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "ctx"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to test.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "value"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if the type of ",
              "type": "text"
            },
            {
              "code": "value",
              "type": "codeVoice"
            },
            {
              "text": " is the symbol type; otherwise, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore": {
      "abstract": [
        {
          "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
      "kind": "symbol",
      "role": "collection",
      "title": "JavaScriptCore",
      "type": "topic",
      "url": "/documentation/javascriptcore"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef": {
      "abstract": [
        {
          "text": "A JavaScript execution context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSContextRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSContextRef"
        }
      ],
      "role": "symbol",
      "title": "JSContextRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jscontextref"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSType": {
      "abstract": [
        {
          "text": "Constants that identify the type of a JavaScript value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSType"
        }
      ],
      "role": "symbol",
      "title": "JSType",
      "type": "topic",
      "url": "/documentation/javascriptcore/jstype"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueGetType(_:_:)": {
      "abstract": [
        {
          "text": "Returns a JavaScript value’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueGetType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSType",
          "text": "JSType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueGetType(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueGetType"
        }
      ],
      "role": "symbol",
      "title": "JSValueGetType(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvaluegettype(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueGetTypedArrayType(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a JavaScript value’s typed array type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueGetTypedArrayType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "?>!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSTypedArrayType",
          "text": "JSTypedArrayType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueGetTypedArrayType(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueGetTypedArrayType"
        }
      ],
      "role": "symbol",
      "title": "JSValueGetTypedArrayType(_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvaluegettypedarraytype(_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsArray(_:_:)": {
      "abstract": [
        {
          "text": "Tests whether a JavaScript value is an array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueIsArray"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsArray(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueIsArray"
        }
      ],
      "role": "symbol",
      "title": "JSValueIsArray(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalueisarray(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsBoolean(_:_:)": {
      "abstract": [
        {
          "text": "Tests whether a JavaScript value is Boolean.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueIsBoolean"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsBoolean(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueIsBoolean"
        }
      ],
      "role": "symbol",
      "title": "JSValueIsBoolean(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalueisboolean(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsDate(_:_:)": {
      "abstract": [
        {
          "text": "Tests whether a JavaScript value is a date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueIsDate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsDate(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueIsDate"
        }
      ],
      "role": "symbol",
      "title": "JSValueIsDate(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalueisdate(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsNull(_:_:)": {
      "abstract": [
        {
          "text": "Tests whether a JavaScript value’s type is the null type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueIsNull"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsNull(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueIsNull"
        }
      ],
      "role": "symbol",
      "title": "JSValueIsNull(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalueisnull(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsNumber(_:_:)": {
      "abstract": [
        {
          "text": "Tests whether a JavaScript value’s type is the number type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueIsNumber"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsNumber(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueIsNumber"
        }
      ],
      "role": "symbol",
      "title": "JSValueIsNumber(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalueisnumber(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsObject(_:_:)": {
      "abstract": [
        {
          "text": "Tests whether a JavaScript value’s type is the object type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueIsObject"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsObject(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueIsObject"
        }
      ],
      "role": "symbol",
      "title": "JSValueIsObject(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalueisobject(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsObjectOfClass(_:_:_:)": {
      "abstract": [
        {
          "text": "Tests whether a JavaScript value is an object with a specified class in its class chain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueIsObjectOfClass"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSClassRef",
          "text": "JSClassRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsObjectOfClass(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueIsObjectOfClass"
        }
      ],
      "role": "symbol",
      "title": "JSValueIsObjectOfClass(_:_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalueisobjectofclass(_:_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsString(_:_:)": {
      "abstract": [
        {
          "text": "Tests whether a JavaScript value’s type is the string type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueIsString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsString(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueIsString"
        }
      ],
      "role": "symbol",
      "title": "JSValueIsString(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalueisstring(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsSymbol(_:_:)": {
      "abstract": [
        {
          "text": "Tests whether a JavaScript value’s type is the symbol type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueIsSymbol"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsSymbol(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueIsSymbol"
        }
      ],
      "role": "symbol",
      "title": "JSValueIsSymbol(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalueissymbol(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsUndefined(_:_:)": {
      "abstract": [
        {
          "text": "Tests whether a JavaScript value’s type is the undefined type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueIsUndefined"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSContextRef",
          "text": "JSContextRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@JSValueRef",
          "text": "JSValueRef"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsUndefined(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueIsUndefined"
        }
      ],
      "role": "symbol",
      "title": "JSValueIsUndefined(_:_:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalueisundefined(_:_:)"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef": {
      "abstract": [
        {
          "text": "A JavaScript value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValueRef"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValueRef"
        }
      ],
      "role": "symbol",
      "title": "JSValueRef",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalueref"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Testing-the-Values-Type",
      "generated": true,
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueGetType(_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsUndefined(_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsNull(_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsBoolean(_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsNumber(_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsString(_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsObject(_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsObjectOfClass(_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsArray(_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsDate(_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueGetTypedArrayType(_:_:_:)",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSType"
      ],
      "title": "Testing the Value’s Type"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "JSValueIsSymbol"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueIsSymbol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Testing-the-Values-Type",
              "generated": true,
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueGetType(_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsUndefined(_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsNull(_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsBoolean(_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsNumber(_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsString(_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsObject(_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsObjectOfClass(_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsArray(_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueIsDate(_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueGetTypedArrayType(_:_:_:)",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSType"
              ],
              "title": "Testing the Value’s Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:b",
                    "text": "bool"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "JSValueIsSymbol"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSContextRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@JSContextRef",
                    "text": "JSContextRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "ctx"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@JSValueRef",
                    "text": "JSValueRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "value"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The execution context to use.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "ctx"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValueRef",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " to test.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "value"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/true",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " if the type of ",
                    "type": "text"
                  },
                  {
                    "code": "value",
                    "type": "codeVoice"
                  },
                  {
                    "text": " is the symbol type; otherwise, ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.documentation/documentation/swift/false",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsUndefined(_:_:)/title",
          "value": "JSValueIsUndefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsUndefined(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueIsUndefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextRef/title",
          "value": "JSContextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSContextRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSContextRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSType/title",
          "value": "JSType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsNumber(_:_:)/title",
          "value": "JSValueIsNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsNumber(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueIsNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsArray(_:_:)/title",
          "value": "JSValueIsArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsArray(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueIsArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueRef/title",
          "value": "JSValueRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsObjectOfClass(_:_:_:)/title",
          "value": "JSValueIsObjectOfClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsObjectOfClass(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueIsObjectOfClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsBoolean(_:_:)/title",
          "value": "JSValueIsBoolean"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsBoolean(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueIsBoolean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueGetTypedArrayType(_:_:_:)/title",
          "value": "JSValueGetTypedArrayType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueGetTypedArrayType(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueGetTypedArrayType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueGetType(_:_:)/title",
          "value": "JSValueGetType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueGetType(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueGetType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsSymbol(_:_:)/title",
          "value": "JSValueIsSymbol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsSymbol(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueIsSymbol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsString(_:_:)/title",
          "value": "JSValueIsString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsString(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueIsString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsDate(_:_:)/title",
          "value": "JSValueIsDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsDate(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueIsDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsObject(_:_:)/title",
          "value": "JSValueIsObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsObject(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueIsObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsNull(_:_:)/title",
          "value": "JSValueIsNull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValueIsNull(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValueIsNull"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/javascriptcore/jsvalueissymbol(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/javascriptcore/jsvalueissymbol(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
