{
  "abstract": [
    {
      "text": "A primitive string value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeString"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@JSType@kJSTypeString",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kJSTypeString"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@JSType",
        "text": "JSType"
      }
    ],
    "modules": [
      {
        "name": "JavaScriptCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kJSTypeString"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kJSTypeString"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kJSTypeString"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@JSType",
              "text": "JSType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore": {
      "abstract": [
        {
          "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
      "kind": "symbol",
      "role": "collection",
      "title": "JavaScriptCore",
      "type": "topic",
      "url": "/documentation/javascriptcore"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSType": {
      "abstract": [
        {
          "text": "Constants that identify the type of a JavaScript value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSType"
        }
      ],
      "role": "symbol",
      "title": "JSType",
      "type": "topic",
      "url": "/documentation/javascriptcore/jstype"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeBoolean": {
      "abstract": [
        {
          "text": "A primitive Boolean value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypeBoolean"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSType",
          "text": "JSType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeBoolean",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypeBoolean"
        }
      ],
      "role": "symbol",
      "title": "kJSTypeBoolean",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypeboolean"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeNull": {
      "abstract": [
        {
          "text": "The unique null value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypeNull"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSType",
          "text": "JSType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeNull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypeNull"
        }
      ],
      "role": "symbol",
      "title": "kJSTypeNull",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypenull"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeNumber": {
      "abstract": [
        {
          "text": "A primitive number value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypeNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSType",
          "text": "JSType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypeNumber"
        }
      ],
      "role": "symbol",
      "title": "kJSTypeNumber",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypenumber"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeObject": {
      "abstract": [
        {
          "text": "An object value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypeObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSType",
          "text": "JSType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypeObject"
        }
      ],
      "role": "symbol",
      "title": "kJSTypeObject",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypeobject"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeString": {
      "abstract": [
        {
          "text": "A primitive string value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypeString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSType",
          "text": "JSType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypeString"
        }
      ],
      "role": "symbol",
      "title": "kJSTypeString",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypestring"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeSymbol": {
      "abstract": [
        {
          "text": "A primitive symbol value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypeSymbol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSType",
          "text": "JSType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeSymbol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypeSymbol"
        }
      ],
      "role": "symbol",
      "title": "kJSTypeSymbol",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypesymbol"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeUndefined": {
      "abstract": [
        {
          "text": "The unique undefined value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kJSTypeUndefined"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@JSType",
          "text": "JSType"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeUndefined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kJSTypeUndefined"
        }
      ],
      "role": "symbol",
      "title": "kJSTypeUndefined",
      "type": "topic",
      "url": "/documentation/javascriptcore/kjstypeundefined"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeUndefined",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeNull",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeBoolean",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeNumber",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeObject",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeSymbol"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kJSTypeString"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypeString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeUndefined",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeNull",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeBoolean",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeNumber",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeObject",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/kJSTypeSymbol"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kJSTypeString"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypeObject/title",
          "value": "kJSTypeObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypeObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypeObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypeUndefined/title",
          "value": "kJSTypeUndefined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypeUndefined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypeUndefined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSType/title",
          "value": "JSType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypeBoolean/title",
          "value": "kJSTypeBoolean"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypeBoolean/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypeBoolean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypeNull/title",
          "value": "kJSTypeNull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypeNull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypeNull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypeString/title",
          "value": "kJSTypeString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypeString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypeString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypeSymbol/title",
          "value": "kJSTypeSymbol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypeSymbol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypeSymbol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypeNumber/title",
          "value": "kJSTypeNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1kJSTypeNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kJSTypeNumber"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/javascriptcore/kjstypestring"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/javascriptcore/kjstypestring"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
