{
  "abstract": [
    {
      "text": "Keys for the native dictionary representation of a JavaScript property descriptor, used with the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/defineProperty(_:descriptor:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " method.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/property-descriptor-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "JavaScriptCore"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Property Descriptor Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore": {
      "abstract": [
        {
          "text": "Evaluate JavaScript programs from within an app, and support JavaScript scripting of your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore",
      "kind": "symbol",
      "role": "collection",
      "title": "JavaScriptCore",
      "type": "topic",
      "url": "/documentation/javascriptcore"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorConfigurableKey": {
      "abstract": [
        {
          "text": "The Boolean value for this key determines whether the property deleted from its JavaScript object or its descriptor changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorConfigurableKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorConfigurableKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorConfigurableKey"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyDescriptorConfigurableKey",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertydescriptorconfigurablekey"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorEnumerableKey": {
      "abstract": [
        {
          "text": "The Boolean value for this key determines whether the property appears when enumerating the JavaScript object’s properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorEnumerableKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorEnumerableKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorEnumerableKey"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyDescriptorEnumerableKey",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertydescriptorenumerablekey"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorGetKey": {
      "abstract": [
        {
          "text": "The JavaScript function to be invoked when reading the property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorGetKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorGetKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorGetKey"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyDescriptorGetKey",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertydescriptorgetkey"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorSetKey": {
      "abstract": [
        {
          "text": "The JavaScript function to be invoked when writing to the property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorSetKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorSetKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorSetKey"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyDescriptorSetKey",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertydescriptorsetkey"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorValueKey": {
      "abstract": [
        {
          "text": "The value for the property on the JavaScript object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorValueKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorValueKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorValueKey"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyDescriptorValueKey",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertydescriptorvaluekey"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorWritableKey": {
      "abstract": [
        {
          "text": "The Boolean value for this key determines whether the property permits assignment with the JavaScript ",
          "type": "text"
        },
        {
          "code": "=",
          "type": "codeVoice"
        },
        {
          "text": " operator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorWritableKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorWritableKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSPropertyDescriptorWritableKey"
        }
      ],
      "role": "symbol",
      "title": "JSPropertyDescriptorWritableKey",
      "type": "topic",
      "url": "/documentation/javascriptcore/jspropertydescriptorwritablekey"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue": {
      "abstract": [
        {
          "text": "A JavaScript value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JSValue"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JSValue"
        }
      ],
      "role": "symbol",
      "title": "JSValue",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue"
    },
    "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/defineProperty(_:descriptor:)": {
      "abstract": [
        {
          "text": "Defines a property on the JavaScript object value or modifies a property’s definition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defineProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSValue/defineProperty(_:descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defineProperty:descriptor:"
        }
      ],
      "role": "symbol",
      "title": "defineProperty(_:descriptor:)",
      "type": "topic",
      "url": "/documentation/javascriptcore/jsvalue/defineproperty(_:descriptor:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorWritableKey",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorEnumerableKey",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorConfigurableKey",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorValueKey",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorGetKey",
        "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorSetKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorWritableKey",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorEnumerableKey",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorConfigurableKey",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorValueKey",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorGetKey",
                "doc://com.apple.javascriptcore/documentation/JavaScriptCore/JSPropertyDescriptorSetKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorWritableKey/title",
          "value": "JSPropertyDescriptorWritableKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorWritableKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyDescriptorWritableKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue/title",
          "value": "JSValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JSValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1defineProperty(_:descriptor:)/title",
          "value": "defineProperty:descriptor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSValue~1defineProperty(_:descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "defineProperty:descriptor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorEnumerableKey/title",
          "value": "JSPropertyDescriptorEnumerableKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorEnumerableKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyDescriptorEnumerableKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorValueKey/title",
          "value": "JSPropertyDescriptorValueKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorValueKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyDescriptorValueKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorSetKey/title",
          "value": "JSPropertyDescriptorSetKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorSetKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyDescriptorSetKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorConfigurableKey/title",
          "value": "JSPropertyDescriptorConfigurableKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorConfigurableKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyDescriptorConfigurableKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorGetKey/title",
          "value": "JSPropertyDescriptorGetKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.javascriptcore~1documentation~1JavaScriptCore~1JSPropertyDescriptorGetKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JSPropertyDescriptorGetKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/javascriptcore/property-descriptor-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/javascriptcore/property-descriptor-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
