{
  "abstract": [
    {
      "text": "The library or function failed to compile.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct",
        "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/compileFailure"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLLibraryError@MTLLibraryErrorCompileFailure",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "compileFailure"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLLibraryErrorCompileFailure"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLLibraryError.Code.compileFailure"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "compileFailure"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct": {
      "abstract": [
        {
          "text": "Metal errors related to libraries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLLibraryError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLibraryError"
        }
      ],
      "role": "symbol",
      "title": "MTLLibraryError",
      "type": "topic",
      "url": "/documentation/metal/mtllibraryerror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for Metal library errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MTLLibraryError.Code",
      "type": "topic",
      "url": "/documentation/metal/mtllibraryerror-swift.struct/code"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/compileFailure": {
      "abstract": [
        {
          "text": "The library or function failed to compile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compileFailure"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/compileFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLibraryErrorCompileFailure"
        }
      ],
      "role": "symbol",
      "title": "MTLLibraryError.Code.compileFailure",
      "type": "topic",
      "url": "/documentation/metal/mtllibraryerror-swift.struct/code/compilefailure"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/compileWarning": {
      "abstract": [
        {
          "text": "The library or function compiled successfully but generated warnings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compileWarning"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/compileWarning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLibraryErrorCompileWarning"
        }
      ],
      "role": "symbol",
      "title": "MTLLibraryError.Code.compileWarning",
      "type": "topic",
      "url": "/documentation/metal/mtllibraryerror-swift.struct/code/compilewarning"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/fileNotFound": {
      "abstract": [
        {
          "text": "Metal couldn’t find the Metal source file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileNotFound"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/fileNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLibraryErrorFileNotFound"
        }
      ],
      "role": "symbol",
      "title": "MTLLibraryError.Code.fileNotFound",
      "type": "topic",
      "url": "/documentation/metal/mtllibraryerror-swift.struct/code/filenotfound"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/functionNotFound": {
      "abstract": [
        {
          "text": "Metal couldn’t find the specified Metal function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "functionNotFound"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/functionNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLibraryErrorFunctionNotFound"
        }
      ],
      "role": "symbol",
      "title": "MTLLibraryError.Code.functionNotFound",
      "type": "topic",
      "url": "/documentation/metal/mtllibraryerror-swift.struct/code/functionnotfound"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/internal": {
      "abstract": [
        {
          "text": "The action caused an internal error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`internal`"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/internal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLibraryErrorInternal"
        }
      ],
      "role": "symbol",
      "title": "MTLLibraryError.Code.internal",
      "type": "topic",
      "url": "/documentation/metal/mtllibraryerror-swift.struct/code/internal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/unsupported": {
      "abstract": [
        {
          "text": "Metal couldn’t support the requested action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/unsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLibraryErrorUnsupported"
        }
      ],
      "role": "symbol",
      "title": "MTLLibraryError.Code.unsupported",
      "type": "topic",
      "url": "/documentation/metal/mtllibraryerror-swift.struct/code/unsupported"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/unsupported",
        "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/internal",
        "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/compileWarning",
        "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/fileNotFound",
        "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/functionNotFound",
        "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/unsupported",
        "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/internal",
        "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/compileWarning",
        "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/fileNotFound",
        "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/functionNotFound"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLLibraryErrorCompileFailure"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLibraryErrorCompileFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/unsupported",
                "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/internal",
                "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/compileWarning",
                "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/fileNotFound",
                "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/functionNotFound",
                "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/unsupported",
                "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/internal",
                "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/compileWarning",
                "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/fileNotFound",
                "doc://com.apple.metal/documentation/Metal/MTLLibraryError-swift.struct/Code/functionNotFound"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLLibraryErrorCompileFailure"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibraryError-swift.struct~1Code~1compileFailure/title",
          "value": "MTLLibraryErrorCompileFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibraryError-swift.struct~1Code~1compileFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLibraryErrorCompileFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibraryError-swift.struct~1Code~1compileWarning/title",
          "value": "MTLLibraryErrorCompileWarning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibraryError-swift.struct~1Code~1compileWarning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLibraryErrorCompileWarning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibraryError-swift.struct~1Code/title",
          "value": "MTLLibraryError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibraryError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLibraryError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibraryError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLibraryError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibraryError-swift.struct~1Code~1unsupported/title",
          "value": "MTLLibraryErrorUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibraryError-swift.struct~1Code~1unsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLibraryErrorUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibraryError-swift.struct~1Code~1internal/title",
          "value": "MTLLibraryErrorInternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibraryError-swift.struct~1Code~1internal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLibraryErrorInternal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibraryError-swift.struct~1Code~1fileNotFound/title",
          "value": "MTLLibraryErrorFileNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibraryError-swift.struct~1Code~1fileNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLibraryErrorFileNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibraryError-swift.struct~1Code~1functionNotFound/title",
          "value": "MTLLibraryErrorFunctionNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLibraryError-swift.struct~1Code~1functionNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLibraryErrorFunctionNotFound"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtllibraryerror-swift.struct/code/compilefailure"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtllibraryerror-swift.struct/code/compilefailure"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
