{
  "abstract": [
    {
      "text": "A touch for a given event has left a window on the screen.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITouch",
        "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/regionExited"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UITouchPhase@UITouchPhaseRegionExited",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "regionExited"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITouchPhaseRegionExited"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UITouch.Phase.regionExited"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "regionExited"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/regionEntered",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/regionMoved",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/regionExited",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " phases don’t always align with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/state-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIHoverGestureRecognizer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". States of the hover gesture recognizer only apply within the context of the gesture’s view, whereas the touch states apply within the window.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/state-swift.property": {
      "abstract": [
        {
          "text": "The current state of the gesture recognizer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIGestureRecognizer",
          "text": "UIGestureRecognizer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIGestureRecognizerState",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/state-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/uikit/uigesturerecognizer/state-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIHoverGestureRecognizer": {
      "abstract": [
        {
          "text": "A continuous gesture recognizer that interprets pointer movement over a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIHoverGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIHoverGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIHoverGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "UIHoverGestureRecognizer",
      "type": "topic",
      "url": "/documentation/uikit/uihovergesturerecognizer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITouch": {
      "abstract": [
        {
          "text": "An object representing the location, size, movement, and force of a touch occurring on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITouch"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITouch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITouch"
        }
      ],
      "role": "symbol",
      "title": "UITouch",
      "type": "topic",
      "url": "/documentation/uikit/uitouch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum": {
      "abstract": [
        {
          "text": "The phase of a touch event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Phase"
        }
      ],
      "role": "symbol",
      "title": "UITouch.Phase",
      "type": "topic",
      "url": "/documentation/uikit/uitouch/phase-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/began": {
      "abstract": [
        {
          "text": "A touch for a given event has pressed down on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "began"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/began",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITouchPhaseBegan"
        }
      ],
      "role": "symbol",
      "title": "UITouch.Phase.began",
      "type": "topic",
      "url": "/documentation/uikit/uitouch/phase-swift.enum/began"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/cancelled": {
      "abstract": [
        {
          "text": "The system canceled tracking for a touch, for example, when the user moves the device against their face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITouchPhaseCancelled"
        }
      ],
      "role": "symbol",
      "title": "UITouch.Phase.cancelled",
      "type": "topic",
      "url": "/documentation/uikit/uitouch/phase-swift.enum/cancelled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/ended": {
      "abstract": [
        {
          "text": "A touch for a given event has lifted from the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ended"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/ended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITouchPhaseEnded"
        }
      ],
      "role": "symbol",
      "title": "UITouch.Phase.ended",
      "type": "topic",
      "url": "/documentation/uikit/uitouch/phase-swift.enum/ended"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/moved": {
      "abstract": [
        {
          "text": "A touch for a given event has moved over the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moved"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/moved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITouchPhaseMoved"
        }
      ],
      "role": "symbol",
      "title": "UITouch.Phase.moved",
      "type": "topic",
      "url": "/documentation/uikit/uitouch/phase-swift.enum/moved"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/regionEntered": {
      "abstract": [
        {
          "text": "A touch for a given event has entered a window on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionEntered"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/regionEntered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITouchPhaseRegionEntered"
        }
      ],
      "role": "symbol",
      "title": "UITouch.Phase.regionEntered",
      "type": "topic",
      "url": "/documentation/uikit/uitouch/phase-swift.enum/regionentered"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/regionExited": {
      "abstract": [
        {
          "text": "A touch for a given event has left a window on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionExited"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/regionExited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITouchPhaseRegionExited"
        }
      ],
      "role": "symbol",
      "title": "UITouch.Phase.regionExited",
      "type": "topic",
      "url": "/documentation/uikit/uitouch/phase-swift.enum/regionexited"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/regionMoved": {
      "abstract": [
        {
          "text": "A touch for the given event is within a window on the screen, but has not yet pressed down.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionMoved"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/regionMoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITouchPhaseRegionMoved"
        }
      ],
      "role": "symbol",
      "title": "UITouch.Phase.regionMoved",
      "type": "topic",
      "url": "/documentation/uikit/uitouch/phase-swift.enum/regionmoved"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/stationary": {
      "abstract": [
        {
          "text": "A touch for a given event is pressed down on the screen, but hasn’t moved since the previous event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stationary"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/stationary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITouchPhaseStationary"
        }
      ],
      "role": "symbol",
      "title": "UITouch.Phase.stationary",
      "type": "topic",
      "url": "/documentation/uikit/uitouch/phase-swift.enum/stationary"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/began",
        "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/moved",
        "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/stationary",
        "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/ended",
        "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/cancelled",
        "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/regionEntered",
        "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/regionMoved"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.4",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITouchPhaseRegionExited"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITouchPhaseRegionExited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/began",
                "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/moved",
                "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/stationary",
                "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/ended",
                "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/cancelled",
                "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/regionEntered",
                "doc://com.apple.uikit/documentation/UIKit/UITouch/Phase-swift.enum/regionMoved"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UITouchPhaseRegionExited"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum~1ended/title",
          "value": "UITouchPhaseEnded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum~1ended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITouchPhaseEnded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum~1moved/title",
          "value": "UITouchPhaseMoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum~1moved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITouchPhaseMoved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum/title",
          "value": "UITouchPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITouchPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITouchPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum~1regionEntered/title",
          "value": "UITouchPhaseRegionEntered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum~1regionEntered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITouchPhaseRegionEntered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/title",
          "value": "UITouch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITouch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITouch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum~1cancelled/title",
          "value": "UITouchPhaseCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITouchPhaseCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1state-swift.property/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1state-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum~1stationary/title",
          "value": "UITouchPhaseStationary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum~1stationary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITouchPhaseStationary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum~1began/title",
          "value": "UITouchPhaseBegan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum~1began/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITouchPhaseBegan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum~1regionExited/title",
          "value": "UITouchPhaseRegionExited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum~1regionExited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITouchPhaseRegionExited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIHoverGestureRecognizer/title",
          "value": "UIHoverGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIHoverGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIHoverGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIHoverGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIHoverGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum~1regionMoved/title",
          "value": "UITouchPhaseRegionMoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITouch~1Phase-swift.enum~1regionMoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITouchPhaseRegionMoved"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitouch/phase-swift.enum/regionexited"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitouch/phase-swift.enum/regionexited"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
