{
  "abstract": [
    {
      "text": "Called when a widget’s editing session ends.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.notificationcenter/documentation/NotificationCenter",
        "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding/widgetDidEndEditing()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NCWidgetProviding(im)widgetDidEndEditing",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "widgetDidEndEditing"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "Notification Center"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "widgetDidEndEditing"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.10",
        "message": "Use WidgetKit instead. Today View extensions have been deprecated.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "widgetDidEndEditing()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "widgetDidEndEditing"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is called when a user chooses the widget’s end editing button or when editing is deactivated because editing begins in a different widget. This method can be called when ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding/widgetAllowsEditing",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/WidgetKit": {
      "abstract": [
        {
          "text": "Extend the reach of your app by creating widgets, watch complications, Live Activities, and controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WidgetKit",
      "type": "topic",
      "url": "/documentation/WidgetKit"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter": {
      "abstract": [
        {
          "text": "Create and manage widgets for the Today view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter",
      "kind": "symbol",
      "role": "collection",
      "title": "Notification Center",
      "type": "topic",
      "url": "/documentation/notificationcenter"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding": {
      "abstract": [
        {
          "text": "The interface for customizing the appearance and behavior of a Today widget.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NCWidgetProviding"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NCWidgetProviding"
        }
      ],
      "role": "symbol",
      "title": "NCWidgetProviding",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetproviding"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding/widgetAllowsEditing": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the widget can be edited by users.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetAllowsEditing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding/widgetAllowsEditing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widgetAllowsEditing"
        }
      ],
      "role": "symbol",
      "title": "widgetAllowsEditing",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetproviding/widgetallowsediting"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding/widgetDidBeginEditing()": {
      "abstract": [
        {
          "text": "Called when a user chooses the widget’s begin editing button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetDidBeginEditing"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding/widgetDidBeginEditing()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widgetDidBeginEditing"
        }
      ],
      "role": "symbol",
      "title": "widgetDidBeginEditing()",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetproviding/widgetdidbeginediting()"
    },
    "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding/widgetDidEndEditing()": {
      "abstract": [
        {
          "text": "Called when a widget’s editing session ends.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widgetDidEndEditing"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding/widgetDidEndEditing()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widgetDidEndEditing"
        }
      ],
      "role": "symbol",
      "title": "widgetDidEndEditing()",
      "type": "topic",
      "url": "/documentation/notificationcenter/ncwidgetproviding/widgetdidendediting()"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-Editing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding/widgetAllowsEditing",
        "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding/widgetDidBeginEditing()"
      ],
      "title": "Supporting Editing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "widgetDidEndEditing"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "widgetDidEndEditing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.notificationcenter/documentation/NotificationCenter",
                "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Supporting-Editing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding/widgetAllowsEditing",
                "doc://com.apple.notificationcenter/documentation/NotificationCenter/NCWidgetProviding/widgetDidBeginEditing()"
              ],
              "title": "Supporting Editing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "widgetDidEndEditing"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/WidgetKit",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetProviding~1widgetDidEndEditing()/title",
          "value": "widgetDidEndEditing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetProviding~1widgetDidEndEditing()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "widgetDidEndEditing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetProviding~1widgetDidBeginEditing()/title",
          "value": "widgetDidBeginEditing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetProviding~1widgetDidBeginEditing()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "widgetDidBeginEditing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetProviding~1widgetAllowsEditing/title",
          "value": "widgetAllowsEditing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetProviding~1widgetAllowsEditing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "widgetAllowsEditing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetProviding/title",
          "value": "NCWidgetProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.notificationcenter~1documentation~1NotificationCenter~1NCWidgetProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NCWidgetProviding"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/notificationcenter/ncwidgetproviding/widgetdidendediting()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/notificationcenter/ncwidgetproviding/widgetdidendediting()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
