{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"title":"accessibilityValue()","externalID":"c:objc(pl)NSAccessibilityRadioButton(im)accessibilityValue","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"AppKit"}],"platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS"}],"required":true,"navigatorTitle":[{"text":"accessibilityValue","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityValue","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton"]]},"abstract":[{"text":"Returns the radio button’s value.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton/accessibilityValue()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsaccessibilityradiobutton/accessibilityvalue()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsaccessibilityradiobutton/accessibilityvalue()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityValue","kind":"identifier"},{"text":"() -> ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNumber","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"text":"","type":"text"},{"code":"@YES","type":"codeVoice"},{"text":" if selected; otherwise, ","type":"text"},{"code":"@NO","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","anchor":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"This method is the getter for the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","type":"reference"},{"text":" protocol’s ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityValue","type":"reference"},{"text":" property.","type":"text"}],"type":"paragraph"},{"style":"note","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This class must also post an "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/valueChanged"},{"type":"text","text":" notification whenever its value changes."}],"type":"paragraph"}],"type":"aside","name":"Note"}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton/accessibilityValue()":{"url":"/documentation/appkit/nsaccessibilityradiobutton/accessibilityvalue()","abstract":[{"text":"Returns the radio button’s value.","type":"text"}],"role":"symbol","required":true,"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accessibilityValue"}],"title":"accessibilityValue()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityValue"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton/accessibilityValue()"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton":{"navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityRadioButton"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSAccessibilityRadioButton"}],"type":"topic","title":"NSAccessibilityRadioButton","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A role-based protocol that declares the minimum interface necessary for an accessibility element to act as a radio button."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton","url":"/documentation/appkit/nsaccessibilityradiobutton"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityValue":{"role":"symbol","type":"topic","kind":"symbol","title":"accessibilityValue","abstract":[{"text":"The accessibility element’s value.","type":"text"}],"url":"/documentation/appkit/nsaccessibility-c.protocol/accessibilityvalue","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityValue","fragments":[{"text":"accessibilityValue","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"post"},{"kind":"text","text":"("},{"kind":"externalParam","text":"element"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"notification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@NSAccessibility","text":"NSAccessibility"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSAccessibilityNotificationName","text":"Notification"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Sends a notification to any observing assistive apps."}],"url":"/documentation/appkit/nsaccessibility-swift.struct/post(element:notification:)","navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityPostNotification"}],"title":"post(element:notification:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/c:objc(cs)NSNumber":{"url":"/documentation/foundation/nsnumber","kind":"symbol","title":"NSNumber","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNumber","type":"topic","abstract":[{"text":"An object wrapper for primitive scalar numeric values.","type":"text"}],"fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSNumber"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/valueChanged":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/Notification/valueChanged","title":"valueChanged","abstract":[{"type":"text","text":"This notification is posted after an accessibility element’s value changes. Post this notification using the "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibility-swift.struct/post(element:notification:)","isActive":true},{"type":"text","text":" function instead of an "},{"type":"codeVoice","code":"NSNotificationCenter"},{"type":"text","text":" instance."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAccessibility","preciseIdentifier":"c:@S@NSAccessibility"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Notification","preciseIdentifier":"c:@T@NSAccessibilityNotificationName"}],"url":"/documentation/appkit/nsaccessibility-swift.struct/notification/valuechanged","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityValueChangedNotification"}]},"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSAccessibilityProtocol","kind":"identifier"}],"url":"/documentation/appkit/nsaccessibilityprotocol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSAccessibilityProtocol","role":"symbol","title":"NSAccessibilityProtocol","kind":"symbol","abstract":[{"text":"The complete list of properties and methods for accessible elements.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSAccessibilityProtocol"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"name":"macOS","beta":false,"deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"accessibilityValue"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessibilityValue"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSAccessibilityRadioButton"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSAccessibility-c.protocol/accessibilityValue"],"anchor":"Related-Documentation","title":"Related Documentation"}],"op":"add","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"accessibilityValue"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","op":"replace","value":{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"@YES","type":"codeVoice"},{"type":"text","text":" if selected; otherwise, "},{"code":"@NO","type":"codeVoice"},{"type":"text","text":"."}]}],"kind":"content"}},{"value":"accessibilityValue","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRadioButton~1accessibilityValue()/title"},{"value":[{"text":"- ","kind":"text"},{"text":"accessibilityValue","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRadioButton~1accessibilityValue()/fragments"},{"value":"NSAccessibilityRadioButton","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRadioButton/title"},{"value":[{"kind":"identifier","text":"NSAccessibilityRadioButton"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRadioButton/fragments"},{"value":[{"kind":"identifier","text":"NSAccessibilityRadioButton"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityRadioButton/navigatorTitle"},{"value":"NSAccessibilityPostNotification","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1post(element:notification:)/title"},{"value":[{"kind":"identifier","text":"NSAccessibilityPostNotification"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1post(element:notification:)/fragments"},{"value":"NSAccessibilityValueChangedNotification","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1valueChanged/title"},{"value":[{"kind":"identifier","text":"NSAccessibilityValueChangedNotification"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibility-swift.struct~1Notification~1valueChanged/fragments"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/title","value":"NSAccessibility"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/fragments","value":[{"kind":"identifier","text":"NSAccessibility"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityProtocol/navigatorTitle","value":[{"text":"NSAccessibility","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}