{
  "abstract": [
    {
      "text": "Display content with a collection view that maximizes the tvOS experience.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvuikit/documentation/TVUIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvuikit/documentation/TVUIKit/creating-immersive-experiences-using-a-full-screen-layout"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "TVUIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "14.2",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Creating immersive experiences using a full-screen layout"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC 2019 session ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/videos/play/wwdc19/211/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "6d260bba65c6/CreatingImmersiveExperiencesUsingAFullScreenLayout.zip": {
      "checksum": "6d260bba65c6289d17afef5064dd5b2e03538ed56aa0c9fc228e4370a6878b5742135e142ec8080e979847bb06c68b9d9c15e46934d0b3e1b209c2232d419c49",
      "identifier": "6d260bba65c6/CreatingImmersiveExperiencesUsingAFullScreenLayout.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/6d260bba65c6/CreatingImmersiveExperiencesUsingAFullScreenLayout.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit": {
      "abstract": [
        {
          "text": "Show common user interface elements from Apple TV in your native app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVUIKit",
      "type": "topic",
      "url": "/documentation/tvuikit"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewDelegateFullScreenLayout": {
      "abstract": [
        {
          "text": "Methods that send notifications of events during cell transitions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCollectionViewDelegateFullScreenLayout"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewDelegateFullScreenLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCollectionViewDelegateFullScreenLayout"
        }
      ],
      "role": "symbol",
      "title": "TVCollectionViewDelegateFullScreenLayout",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewdelegatefullscreenlayout"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenCell": {
      "abstract": [
        {
          "text": "A full-screen cell to use in full-screen display format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenCell"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenCell"
        }
      ],
      "role": "symbol",
      "title": "TVCollectionViewFullScreenCell",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreencell"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout": {
      "abstract": [
        {
          "text": "A collection view layout that organizes items into a browsable, full-screen display format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenLayout"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenLayout"
        }
      ],
      "role": "symbol",
      "title": "TVCollectionViewFullScreenLayout",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayout"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes": {
      "abstract": [
        {
          "text": "Attributes to manage the appearance of the collection view’s layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenLayoutAttributes"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenLayoutAttributes"
        }
      ],
      "role": "symbol",
      "title": "TVCollectionViewFullScreenLayoutAttributes",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayoutattributes"
    },
    "https://developer.apple.com/videos/play/wwdc19/211/": {
      "identifier": "https://developer.apple.com/videos/play/wwdc19/211/",
      "title": "211: Mastering the Living Room with tvOS",
      "titleInlineContent": [
        {
          "text": "211: Mastering the Living Room with tvOS",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc19/211/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "6d260bba65c6/CreatingImmersiveExperiencesUsingAFullScreenLayout.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Collections-of-content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewDelegateFullScreenLayout",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenCell",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes"
      ],
      "title": "Collections of content"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes/title",
          "value": "TVCollectionViewFullScreenLayoutAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout/title",
          "value": "TVCollectionViewFullScreenLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenCell/title",
          "value": "TVCollectionViewFullScreenCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewDelegateFullScreenLayout/title",
          "value": "TVCollectionViewDelegateFullScreenLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewDelegateFullScreenLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewDelegateFullScreenLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewDelegateFullScreenLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewDelegateFullScreenLayout"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvuikit/creating-immersive-experiences-using-a-full-screen-layout"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
