{
  "abstract": [
    {
      "text": "The directions that the caption button view can tilt in response to user interactions on the remote.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvuikit/documentation/TVUIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@TVCaptionButtonViewMotionDirection",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TVCaptionButtonViewMotionDirection"
      }
    ],
    "modules": [
      {
        "name": "TVUIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVCaptionButtonViewMotionDirection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "TVCaptionButtonViewMotionDirection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TVCaptionButtonViewMotionDirection"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit": {
      "abstract": [
        {
          "text": "Show common user interface elements from Apple TV in your native app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVUIKit",
      "type": "topic",
      "url": "/documentation/tvuikit"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonView/motionDirection": {
      "abstract": [
        {
          "text": "The direction that the caption button view tilts in response to user interaction on the remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "motionDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@TVCaptionButtonViewMotionDirection",
          "text": "TVCaptionButtonViewMotionDirection"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonView/motionDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "motionDirection"
        }
      ],
      "role": "symbol",
      "title": "motionDirection",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcaptionbuttonview/motiondirection"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection": {
      "abstract": [
        {
          "text": "The directions that the caption button view can tilt in response to user interactions on the remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCaptionButtonViewMotionDirection"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCaptionButtonViewMotionDirection"
        }
      ],
      "role": "symbol",
      "title": "TVCaptionButtonViewMotionDirection",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcaptionbuttonviewmotiondirection"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/all": {
      "abstract": [
        {
          "text": "The caption button view can tilt in all directions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCaptionButtonViewMotionDirectionAll"
        }
      ],
      "role": "symbol",
      "title": "TVCaptionButtonViewMotionDirection.all",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcaptionbuttonviewmotiondirection/all"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/horizontal": {
      "abstract": [
        {
          "text": "The caption button view can tilt in the horzontal direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontal"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/horizontal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCaptionButtonViewMotionDirectionHorizontal"
        }
      ],
      "role": "symbol",
      "title": "TVCaptionButtonViewMotionDirection.horizontal",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcaptionbuttonviewmotiondirection/horizontal"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcaptionbuttonviewmotiondirection/init(rawvalue:)"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/none": {
      "abstract": [
        {
          "text": "The caption button view can’t tilt.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCaptionButtonViewMotionDirectionNone"
        }
      ],
      "role": "symbol",
      "title": "TVCaptionButtonViewMotionDirection.none",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcaptionbuttonviewmotiondirection/none"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/vertical": {
      "abstract": [
        {
          "text": "The caption button view can tilt in the vertical direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertical"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/vertical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCaptionButtonViewMotionDirectionVertical"
        }
      ],
      "role": "symbol",
      "title": "TVCaptionButtonViewMotionDirection.vertical",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcaptionbuttonviewmotiondirection/vertical"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-the-Motion-Direction",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonView/motionDirection"
      ],
      "title": "Setting the Motion Direction"
    }
  ],
  "topicSections": [
    {
      "anchor": "Tilt-Directions",
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/all",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/horizontal",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/none",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/vertical"
      ],
      "title": "Tilt Directions"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVCaptionButtonViewMotionDirection"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonViewMotionDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonViewMotionDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvuikit/documentation/TVUIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Tilt-Directions",
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/all",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/horizontal",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/none",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonViewMotionDirection/vertical"
              ],
              "title": "Tilt Directions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-the-Motion-Direction",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonView/motionDirection"
              ],
              "title": "Setting the Motion Direction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TVCaptionButtonViewMotionDirection"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection~1horizontal/title",
          "value": "TVCaptionButtonViewMotionDirectionHorizontal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection~1horizontal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonViewMotionDirectionHorizontal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection/title",
          "value": "TVCaptionButtonViewMotionDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonViewMotionDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonViewMotionDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection~1all/title",
          "value": "TVCaptionButtonViewMotionDirectionAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonViewMotionDirectionAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection~1vertical/title",
          "value": "TVCaptionButtonViewMotionDirectionVertical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection~1vertical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonViewMotionDirectionVertical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonView~1motionDirection/title",
          "value": "motionDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonView~1motionDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "motionDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection~1none/title",
          "value": "TVCaptionButtonViewMotionDirectionNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonViewMotionDirection~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonViewMotionDirectionNone"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvuikit/tvcaptionbuttonviewmotiondirection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvuikit/tvcaptionbuttonviewmotiondirection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
