{
  "abstract": [
    {
      "text": "Attributes to manage the appearance of the collection view’s layout.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvuikit/documentation/TVUIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TVCollectionViewFullScreenLayoutAttributes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TVCollectionViewFullScreenLayoutAttributes"
      }
    ],
    "modules": [
      {
        "name": "TVUIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVCollectionViewFullScreenLayoutAttributes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "TVCollectionViewFullScreenLayoutAttributes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayoutAttributes"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit": {
      "abstract": [
        {
          "text": "Show common user interface elements from Apple TV in your native app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVUIKit",
      "type": "topic",
      "url": "/documentation/tvuikit"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewDelegateFullScreenLayout": {
      "abstract": [
        {
          "text": "Methods that send notifications of events during cell transitions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCollectionViewDelegateFullScreenLayout"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewDelegateFullScreenLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCollectionViewDelegateFullScreenLayout"
        }
      ],
      "role": "symbol",
      "title": "TVCollectionViewDelegateFullScreenLayout",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewdelegatefullscreenlayout"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenCell": {
      "abstract": [
        {
          "text": "A full-screen cell to use in full-screen display format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenCell"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenCell"
        }
      ],
      "role": "symbol",
      "title": "TVCollectionViewFullScreenCell",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreencell"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout": {
      "abstract": [
        {
          "text": "A collection view layout that organizes items into a browsable, full-screen display format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenLayout"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenLayout"
        }
      ],
      "role": "symbol",
      "title": "TVCollectionViewFullScreenLayout",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayout"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes": {
      "abstract": [
        {
          "text": "Attributes to manage the appearance of the collection view’s layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenLayoutAttributes"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenLayoutAttributes"
        }
      ],
      "role": "symbol",
      "title": "TVCollectionViewFullScreenLayoutAttributes",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayoutattributes"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/contentBleed": {
      "abstract": [
        {
          "text": "The amount of content that bleeds into the masked portions of the cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentBleed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIEdgeInsets",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/contentBleed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentBleed"
        }
      ],
      "role": "symbol",
      "title": "contentBleed",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayoutattributes/contentbleed"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/cornerRadius": {
      "abstract": [
        {
          "text": "The radius to use when drawing rounded corners for the cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cornerRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/cornerRadius",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cornerRadius"
        }
      ],
      "role": "symbol",
      "title": "cornerRadius",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayoutattributes/cornerradius"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/maskAmount": {
      "abstract": [
        {
          "text": "The amount of masking to apply to the cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maskAmount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/maskAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maskAmount"
        }
      ],
      "role": "symbol",
      "title": "maskAmount",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayoutattributes/maskamount"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/normalizedPosition": {
      "abstract": [
        {
          "text": "A value that indicates the distance of the current cell from the collection view’s center cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normalizedPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/normalizedPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "normalizedPosition"
        }
      ],
      "role": "symbol",
      "title": "normalizedPosition",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayoutattributes/normalizedposition"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/parallaxOffset": {
      "abstract": [
        {
          "text": "The number of points by which to shift the background from the center when moving focus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parallaxOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/parallaxOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parallaxOffset"
        }
      ],
      "role": "symbol",
      "title": "parallaxOffset",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayoutattributes/parallaxoffset"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/creating-immersive-experiences-using-a-full-screen-layout": {
      "abstract": [
        {
          "text": "Display content with a collection view that maximizes the tvOS experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/creating-immersive-experiences-using-a-full-screen-layout",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating immersive experiences using a full-screen layout",
      "type": "topic",
      "url": "/documentation/tvuikit/creating-immersive-experiences-using-a-full-screen-layout"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)UICollectionViewLayoutAttributes": {
      "abstract": [
        {
          "text": "A layout object that manages the layout-related attributes for a given item in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewLayoutAttributes"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UICollectionViewLayoutAttributes",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICollectionViewLayoutAttributes",
      "type": "topic",
      "url": "/documentation/UIKit/UICollectionViewLayoutAttributes"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIDynamicItem": {
      "abstract": [
        {
          "text": "A set of methods that can make a custom object eligible to participate in UIKit Dynamics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDynamicItem"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIDynamicItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIDynamicItem",
      "type": "topic",
      "url": "/documentation/UIKit/UIDynamicItem"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)UICollectionViewLayoutAttributes"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIDynamicItem"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Collections-of-content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/creating-immersive-experiences-using-a-full-screen-layout",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewDelegateFullScreenLayout",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenCell"
      ],
      "title": "Collections of content"
    }
  ],
  "topicSections": [
    {
      "anchor": "Modifying-Cell-Appearance",
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/contentBleed",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/cornerRadius",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/maskAmount"
      ],
      "title": "Modifying Cell Appearance"
    },
    {
      "anchor": "Modifying-the-Parallax-Effect",
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/parallaxOffset"
      ],
      "title": "Modifying the Parallax Effect"
    },
    {
      "anchor": "Managing-Cell-Position",
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/normalizedPosition"
      ],
      "title": "Managing Cell Position"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVCollectionViewFullScreenLayoutAttributes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvuikit/documentation/TVUIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Modifying-Cell-Appearance",
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/contentBleed",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/cornerRadius",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/maskAmount"
              ],
              "title": "Modifying Cell Appearance"
            },
            {
              "anchor": "Modifying-the-Parallax-Effect",
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/parallaxOffset"
              ],
              "title": "Modifying the Parallax Effect"
            },
            {
              "anchor": "Managing-Cell-Position",
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes/normalizedPosition"
              ],
              "title": "Managing Cell Position"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)UICollectionViewLayoutAttributes"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Collections-of-content",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewDelegateFullScreenLayout",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenCell"
              ],
              "title": "Collections of content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TVCollectionViewFullScreenLayoutAttributes"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UICollectionViewLayoutAttributes",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UICollectionViewLayoutAttributes",
                    "text": "UICollectionViewLayoutAttributes"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UICollectionViewLayoutAttributes/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UICollectionViewLayoutAttributes"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes~1contentBleed/title",
          "value": "contentBleed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes~1contentBleed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentBleed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewDelegateFullScreenLayout/title",
          "value": "TVCollectionViewDelegateFullScreenLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewDelegateFullScreenLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewDelegateFullScreenLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewDelegateFullScreenLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewDelegateFullScreenLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes~1parallaxOffset/title",
          "value": "parallaxOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes~1parallaxOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parallaxOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout/title",
          "value": "TVCollectionViewFullScreenLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes~1cornerRadius/title",
          "value": "cornerRadius"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes~1cornerRadius/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cornerRadius"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIDynamicItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIDynamicItem"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenCell/title",
          "value": "TVCollectionViewFullScreenCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes~1normalizedPosition/title",
          "value": "normalizedPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes~1normalizedPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "normalizedPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes/title",
          "value": "TVCollectionViewFullScreenLayoutAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes~1maskAmount/title",
          "value": "maskAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes~1maskAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maskAmount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvuikit/tvcollectionviewfullscreenlayoutattributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvuikit/tvcollectionviewfullscreenlayoutattributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
