{
  "abstract": [
    {
      "text": "A collection view layout that organizes items into a browsable, full-screen display format.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvuikit/documentation/TVUIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TVCollectionViewFullScreenLayout",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TVCollectionViewFullScreenLayout"
      }
    ],
    "modules": [
      {
        "name": "TVUIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVCollectionViewFullScreenLayout"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "TVCollectionViewFullScreenLayout"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayout"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this class to create a full-screen browsing experience. Full-screen layouts are an immersive way to present and navigate through content.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3332103",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit": {
      "abstract": [
        {
          "text": "Show common user interface elements from Apple TV in your native app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVUIKit",
      "type": "topic",
      "url": "/documentation/tvuikit"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewDelegateFullScreenLayout": {
      "abstract": [
        {
          "text": "Methods that send notifications of events during cell transitions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCollectionViewDelegateFullScreenLayout"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewDelegateFullScreenLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCollectionViewDelegateFullScreenLayout"
        }
      ],
      "role": "symbol",
      "title": "TVCollectionViewDelegateFullScreenLayout",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewdelegatefullscreenlayout"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenCell": {
      "abstract": [
        {
          "text": "A full-screen cell to use in full-screen display format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenCell"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenCell"
        }
      ],
      "role": "symbol",
      "title": "TVCollectionViewFullScreenCell",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreencell"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout": {
      "abstract": [
        {
          "text": "A collection view layout that organizes items into a browsable, full-screen display format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenLayout"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenLayout"
        }
      ],
      "role": "symbol",
      "title": "TVCollectionViewFullScreenLayout",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayout"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/centerIndexPath": {
      "abstract": [
        {
          "text": "The index path of the currently centered item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerIndexPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/centerIndexPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "centerIndexPath"
        }
      ],
      "role": "symbol",
      "title": "centerIndexPath",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayout/centerindexpath"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/cornerRadius": {
      "abstract": [
        {
          "text": "The radius to use when drawing rounded corners for the cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cornerRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/cornerRadius",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cornerRadius"
        }
      ],
      "role": "symbol",
      "title": "cornerRadius",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayout/cornerradius"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/interitemSpacing": {
      "abstract": [
        {
          "text": "The spacing between each cell in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interitemSpacing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/interitemSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interitemSpacing"
        }
      ],
      "role": "symbol",
      "title": "interitemSpacing",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayout/interitemspacing"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/isTransitioningToCenterIndexPath": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the cell is changing index paths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isTransitioningToCenterIndexPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/isTransitioningToCenterIndexPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transitioningToCenterIndexPath"
        }
      ],
      "role": "symbol",
      "title": "isTransitioningToCenterIndexPath",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayout/istransitioningtocenterindexpath"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/maskAmount": {
      "abstract": [
        {
          "text": "The amount by which to mask the cells in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maskAmount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/maskAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maskAmount"
        }
      ],
      "role": "symbol",
      "title": "maskAmount",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayout/maskamount"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/maskInset": {
      "abstract": [
        {
          "text": "The edge insets of the cell mask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maskInset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIEdgeInsets",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/maskInset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maskInset"
        }
      ],
      "role": "symbol",
      "title": "maskInset",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayout/maskinset"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/parallaxFactor": {
      "abstract": [
        {
          "text": "A value that specifies how slowly the background should move relative to the foreground.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parallaxFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/parallaxFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parallaxFactor"
        }
      ],
      "role": "symbol",
      "title": "parallaxFactor",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayout/parallaxfactor"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes": {
      "abstract": [
        {
          "text": "Attributes to manage the appearance of the collection view’s layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenLayoutAttributes"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCollectionViewFullScreenLayoutAttributes"
        }
      ],
      "role": "symbol",
      "title": "TVCollectionViewFullScreenLayoutAttributes",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcollectionviewfullscreenlayoutattributes"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/creating-immersive-experiences-using-a-full-screen-layout": {
      "abstract": [
        {
          "text": "Display content with a collection view that maximizes the tvOS experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/creating-immersive-experiences-using-a-full-screen-layout",
      "kind": "article",
      "role": "sampleCode",
      "title": "Creating immersive experiences using a full-screen layout",
      "type": "topic",
      "url": "/documentation/tvuikit/creating-immersive-experiences-using-a-full-screen-layout"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)UICollectionViewLayout": {
      "abstract": [
        {
          "text": "An abstract base class for generating layout information for a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewLayout"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UICollectionViewLayout",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICollectionViewLayout",
      "type": "topic",
      "url": "/documentation/UIKit/UICollectionViewLayout"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "media-3332103": {
      "alt": "A diagram showing the TVCollectionViewFullScreenLayout. One cell is centered, and two cells are peeking from the left and right sides.",
      "identifier": "media-3332103",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/dc256aae53b2cb0d0bc0e88c31ab8fa5/media-3332103@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/51fe536c1da37db04d03d2df780d4763/media-3332103~dark@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)UICollectionViewLayout"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Collections-of-content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/creating-immersive-experiences-using-a-full-screen-layout",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewDelegateFullScreenLayout",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenCell",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes"
      ],
      "title": "Collections of content"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-a-collection-views-appearance",
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/interitemSpacing"
      ],
      "title": "Managing a collection view’s appearance"
    },
    {
      "anchor": "Accessing-collection-view-items",
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/centerIndexPath"
      ],
      "title": "Accessing collection view items"
    },
    {
      "anchor": "Configuring-cell-masks",
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/maskAmount",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/maskInset"
      ],
      "title": "Configuring cell masks"
    },
    {
      "anchor": "Managing-cell-appearance",
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/cornerRadius"
      ],
      "title": "Managing cell appearance"
    },
    {
      "anchor": "Managing-transitions",
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/parallaxFactor",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/isTransitioningToCenterIndexPath"
      ],
      "title": "Managing transitions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVCollectionViewFullScreenLayout"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvuikit/documentation/TVUIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-a-collection-views-appearance",
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/interitemSpacing"
              ],
              "title": "Managing a collection view’s appearance"
            },
            {
              "anchor": "Accessing-collection-view-items",
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/centerIndexPath"
              ],
              "title": "Accessing collection view items"
            },
            {
              "anchor": "Configuring-cell-masks",
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/maskAmount",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/maskInset"
              ],
              "title": "Configuring cell masks"
            },
            {
              "anchor": "Managing-cell-appearance",
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/cornerRadius"
              ],
              "title": "Managing cell appearance"
            },
            {
              "anchor": "Managing-transitions",
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/parallaxFactor",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayout/isTransitioningToCenterIndexPath"
              ],
              "title": "Managing transitions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)UICollectionViewLayout"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Collections-of-content",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewDelegateFullScreenLayout",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenCell",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCollectionViewFullScreenLayoutAttributes"
              ],
              "title": "Collections of content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TVCollectionViewFullScreenLayout"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UICollectionViewLayout",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UICollectionViewLayout",
                    "text": "UICollectionViewLayout"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout~1isTransitioningToCenterIndexPath/title",
          "value": "transitioningToCenterIndexPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout~1isTransitioningToCenterIndexPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transitioningToCenterIndexPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewDelegateFullScreenLayout/title",
          "value": "TVCollectionViewDelegateFullScreenLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewDelegateFullScreenLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewDelegateFullScreenLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewDelegateFullScreenLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewDelegateFullScreenLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout~1cornerRadius/title",
          "value": "cornerRadius"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout~1cornerRadius/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cornerRadius"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout~1parallaxFactor/title",
          "value": "parallaxFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout~1parallaxFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parallaxFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout~1centerIndexPath/title",
          "value": "centerIndexPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout~1centerIndexPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "centerIndexPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes/title",
          "value": "TVCollectionViewFullScreenLayoutAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayoutAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout/title",
          "value": "TVCollectionViewFullScreenLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UICollectionViewLayout/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UICollectionViewLayout"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout~1maskInset/title",
          "value": "maskInset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout~1maskInset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maskInset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout~1interitemSpacing/title",
          "value": "interitemSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout~1interitemSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interitemSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenCell/title",
          "value": "TVCollectionViewFullScreenCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCollectionViewFullScreenCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout~1maskAmount/title",
          "value": "maskAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCollectionViewFullScreenLayout~1maskAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maskAmount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvuikit/tvcollectionviewfullscreenlayout"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvuikit/tvcollectionviewfullscreenlayout"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
