{
  "abstract": [
    {
      "text": "The protocol for responding to lockup view state changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvuikit/documentation/TVUIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupViewComponent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)TVLockupViewComponent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TVLockupViewComponent"
      }
    ],
    "modules": [
      {
        "name": "TVUIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVLockupViewComponent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "TVLockupViewComponent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TVLockupViewComponent"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit": {
      "abstract": [
        {
          "text": "Show common user interface elements from Apple TV in your native app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVUIKit",
      "type": "topic",
      "url": "/documentation/tvuikit"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonView": {
      "abstract": [
        {
          "text": "A button-like view that responds to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCaptionButtonView"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCaptionButtonView"
        }
      ],
      "role": "symbol",
      "title": "TVCaptionButtonView",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcaptionbuttonview"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVCardView": {
      "abstract": [
        {
          "text": "A view that responds to focus interaction with a motion effect it applies to all of its subviews.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVCardView"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVCardView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVCardView"
        }
      ],
      "role": "symbol",
      "title": "TVCardView",
      "type": "topic",
      "url": "/documentation/tvuikit/tvcardview"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupHeaderFooterView": {
      "abstract": [
        {
          "text": "A view that contains header and footer information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVLockupHeaderFooterView"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupHeaderFooterView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVLockupHeaderFooterView"
        }
      ],
      "role": "symbol",
      "title": "TVLockupHeaderFooterView",
      "type": "topic",
      "url": "/documentation/tvuikit/tvlockupheaderfooterview"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView": {
      "abstract": [
        {
          "text": "A focusable view that presents main content, like a movie poster, and an optional header and footer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVLockupView"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVLockupView"
        }
      ],
      "role": "symbol",
      "title": "TVLockupView",
      "type": "topic",
      "url": "/documentation/tvuikit/tvlockupview"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupViewComponent": {
      "abstract": [
        {
          "text": "The protocol for responding to lockup view state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVLockupViewComponent"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupViewComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVLockupViewComponent"
        }
      ],
      "role": "symbol",
      "title": "TVLockupViewComponent",
      "type": "topic",
      "url": "/documentation/tvuikit/tvlockupviewcomponent"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupViewComponent/updateAppearance(forLockupViewState:)": {
      "abstract": [
        {
          "text": "Provides an opportunity to change the appearance of a view when a state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateAppearance"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forLockupViewState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupViewComponent/updateAppearance(forLockupViewState:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateAppearanceForLockupViewState:"
        }
      ],
      "role": "symbol",
      "title": "updateAppearance(forLockupViewState:)",
      "type": "topic",
      "url": "/documentation/tvuikit/tvlockupviewcomponent/updateappearance(forlockupviewstate:)"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramView": {
      "abstract": [
        {
          "text": "A specialized lockup view that contains a circular image of a person or the person’s initials, along with a footer view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVMonogramView"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVMonogramView"
        }
      ],
      "role": "symbol",
      "title": "TVMonogramView",
      "type": "topic",
      "url": "/documentation/tvuikit/tvmonogramview"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVPosterView": {
      "abstract": [
        {
          "text": "An optimized view for displaying an image, a header, and a footer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVPosterView"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVPosterView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVPosterView"
        }
      ],
      "role": "symbol",
      "title": "TVPosterView",
      "type": "topic",
      "url": "/documentation/tvuikit/tvposterview"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupHeaderFooterView"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Lockup-views",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupHeaderFooterView",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCardView",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVPosterView",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonView",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramView"
      ],
      "title": "Lockup views"
    }
  ],
  "topicSections": [
    {
      "anchor": "Updating-the-Lockup-View-Appearance",
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupViewComponent/updateAppearance(forLockupViewState:)"
      ],
      "title": "Updating the Lockup View Appearance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVLockupViewComponent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVLockupViewComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVLockupViewComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvuikit/documentation/TVUIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Updating-the-Lockup-View-Appearance",
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupViewComponent/updateAppearance(forLockupViewState:)"
              ],
              "title": "Updating the Lockup View Appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupHeaderFooterView"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Lockup-views",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupView",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVLockupHeaderFooterView",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCardView",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVPosterView",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVCaptionButtonView",
                "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramView"
              ],
              "title": "Lockup views"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TVLockupViewComponent"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVPosterView/title",
          "value": "TVPosterView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVPosterView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPosterView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVPosterView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVPosterView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMonogramView/title",
          "value": "TVMonogramView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMonogramView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMonogramView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMonogramView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMonogramView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupHeaderFooterView/title",
          "value": "TVLockupHeaderFooterView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupHeaderFooterView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVLockupHeaderFooterView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupHeaderFooterView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVLockupHeaderFooterView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupViewComponent/title",
          "value": "TVLockupViewComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupViewComponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVLockupViewComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupViewComponent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVLockupViewComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupView/title",
          "value": "TVLockupView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVLockupView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVLockupView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCardView/title",
          "value": "TVCardView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCardView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCardView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCardView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCardView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonView/title",
          "value": "TVCaptionButtonView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVCaptionButtonView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVCaptionButtonView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupViewComponent~1updateAppearance(forLockupViewState:)/title",
          "value": "updateAppearanceForLockupViewState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVLockupViewComponent~1updateAppearance(forLockupViewState:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateAppearanceForLockupViewState:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvuikit/tvlockupviewcomponent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvuikit/tvlockupviewcomponent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
