{
  "abstract": [
    {
      "text": "The default value for views.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/unspecified"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UISemanticContentAttribute@UISemanticContentAttributeUnspecified",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unspecified"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UISemanticContentAttributeUnspecified"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UISemanticContentAttribute.unspecified"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unspecified"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The view is flipped when switching between left-to-right and right-to-left layouts.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute": {
      "abstract": [
        {
          "text": "A semantic description of the view’s contents, used to determine whether the view should be flipped when switching between left-to-right and right-to-left layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISemanticContentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISemanticContentAttribute"
        }
      ],
      "role": "symbol",
      "title": "UISemanticContentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/uisemanticcontentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceLeftToRight": {
      "abstract": [
        {
          "text": "A view that’s always displayed using a left-to-right layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forceLeftToRight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceLeftToRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISemanticContentAttributeForceLeftToRight"
        }
      ],
      "role": "symbol",
      "title": "UISemanticContentAttribute.forceLeftToRight",
      "type": "topic",
      "url": "/documentation/uikit/uisemanticcontentattribute/forcelefttoright"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceRightToLeft": {
      "abstract": [
        {
          "text": "A view that’s always displayed using a right-to-left layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forceRightToLeft"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceRightToLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISemanticContentAttributeForceRightToLeft"
        }
      ],
      "role": "symbol",
      "title": "UISemanticContentAttribute.forceRightToLeft",
      "type": "topic",
      "url": "/documentation/uikit/uisemanticcontentattribute/forcerighttoleft"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/playback": {
      "abstract": [
        {
          "text": "A view representing the playback controls, such as Play, Rewind, or Fast Forward buttons or playhead scrubbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playback"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/playback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISemanticContentAttributePlayback"
        }
      ],
      "role": "symbol",
      "title": "UISemanticContentAttribute.playback",
      "type": "topic",
      "url": "/documentation/uikit/uisemanticcontentattribute/playback"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/spatial": {
      "abstract": [
        {
          "text": "A view representing a directional control, such as a segment control for text alignment, or a D-pad control for a game.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatial"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/spatial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISemanticContentAttributeSpatial"
        }
      ],
      "role": "symbol",
      "title": "UISemanticContentAttribute.spatial",
      "type": "topic",
      "url": "/documentation/uikit/uisemanticcontentattribute/spatial"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/unspecified": {
      "abstract": [
        {
          "text": "The default value for views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISemanticContentAttributeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "UISemanticContentAttribute.unspecified",
      "type": "topic",
      "url": "/documentation/uikit/uisemanticcontentattribute/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/playback",
        "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/spatial",
        "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceLeftToRight",
        "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceRightToLeft"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UISemanticContentAttributeUnspecified"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttributeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/playback",
                "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/spatial",
                "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceLeftToRight",
                "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceRightToLeft"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UISemanticContentAttributeUnspecified"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute/title",
          "value": "UISemanticContentAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1unspecified/title",
          "value": "UISemanticContentAttributeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttributeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1spatial/title",
          "value": "UISemanticContentAttributeSpatial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1spatial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttributeSpatial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1playback/title",
          "value": "UISemanticContentAttributePlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1playback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttributePlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1forceLeftToRight/title",
          "value": "UISemanticContentAttributeForceLeftToRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1forceLeftToRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttributeForceLeftToRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1forceRightToLeft/title",
          "value": "UISemanticContentAttributeForceRightToLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1forceRightToLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttributeForceRightToLeft"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisemanticcontentattribute/unspecified"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uisemanticcontentattribute/unspecified"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
