{
  "abstract": [
    {
      "text": "Returns a fetch request configured with a given entity name.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/fetchRequestWithEntityName:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSFetchRequest(cm)fetchRequestWithEntityName:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "fetchRequestWithEntityName:"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "fetchRequestWithEntityName:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "fetchRequestWithEntityName:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "fetchRequestWithEntityName:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "entityName"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the entity to fetch.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "entityName"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A fetch request configured to fetch the entity named ",
              "type": "text"
            },
            {
              "code": "entityName",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method provides a convenient way to configure the entity for a fetch request without having to retrieve an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityDescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. When the fetch is executed, the request uses the managed object context to find the entity with the given name. The model associated with the context’s persistent store coordinator must contain an entity named ",
              "type": "text"
            },
            {
              "code": "entityName",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityDescription": {
      "abstract": [
        {
          "text": "A description of a Core Data entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEntityDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEntityDescription"
        }
      ],
      "role": "symbol",
      "title": "NSEntityDescription",
      "type": "topic",
      "url": "/documentation/coredata/nsentitydescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest": {
      "abstract": [
        {
          "text": "A description of search criteria used to retrieve data from a persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFetchRequest"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFetchRequest"
        }
      ],
      "role": "symbol",
      "title": "NSFetchRequest",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchrequest"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/entity": {
      "abstract": [
        {
          "text": "The entity specified for the fetch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "entity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEntityDescription",
          "text": "NSEntityDescription"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/entity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "entity"
        }
      ],
      "role": "symbol",
      "title": "entity",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchrequest/entity"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/entityName": {
      "abstract": [
        {
          "text": "The name of the entity the request is configured to fetch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "entityName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/entityName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "entityName"
        }
      ],
      "role": "symbol",
      "title": "entityName",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchrequest/entityname"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/fetchRequestWithEntityName:": {
      "abstract": [
        {
          "text": "Returns a fetch request configured with a given entity name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "fetchRequestWithEntityName:"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/fetchRequestWithEntityName:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchRequestWithEntityName:"
        }
      ],
      "role": "symbol",
      "title": "fetchRequestWithEntityName:",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchrequest/fetchrequestwithentityname:"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/includesSubentities": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the fetch request includes subentities in the results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "includesSubentities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/includesSubentities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "includesSubentities"
        }
      ],
      "role": "symbol",
      "title": "includesSubentities",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchrequest/includessubentities"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/init()": {
      "abstract": [
        {
          "text": "Creates a new fetch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchrequest/init()"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/init(entityName:)": {
      "abstract": [
        {
          "text": "Initializes a fetch request configured with a given entity name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "entityName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/init(entityName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEntityName:"
        }
      ],
      "role": "symbol",
      "title": "init(entityName:)",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchrequest/init(entityname:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchRequestResultType": {
      "abstract": [
        {
          "text": "Constants that specify the possible result types a fetch request can return.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFetchRequestResultType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequestResultType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFetchRequestResultType"
        }
      ],
      "role": "symbol",
      "title": "NSFetchRequestResultType",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchrequestresulttype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreData/index.html#//apple_ref/doc/uid/TP40001075": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreData/index.html#//apple_ref/doc/uid/TP40001075",
      "title": "Core Data Programming Guide",
      "titleInlineContent": [
        {
          "text": "Core Data Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreData/index.html#//apple_ref/doc/uid/TP40001075"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Predicates/AdditionalChapters/Introduction.html#//apple_ref/doc/uid/TP40001789": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Predicates/AdditionalChapters/Introduction.html#//apple_ref/doc/uid/TP40001789",
      "title": "Predicate Programming Guide",
      "titleInlineContent": [
        {
          "text": "Predicate Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Predicates/AdditionalChapters/Introduction.html#//apple_ref/doc/uid/TP40001789"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Predicates/AdditionalChapters/Introduction.html#//apple_ref/doc/uid/TP40001789",
        "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreData/index.html#//apple_ref/doc/uid/TP40001075"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Managing-the-Fetch-Requests-Entity",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/init()",
        "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/init(entityName:)",
        "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/entityName",
        "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/entity",
        "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/includesSubentities",
        "doc://com.apple.coredata/documentation/CoreData/NSFetchRequestResultType"
      ],
      "title": "Managing the Fetch Request’s Entity"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1entityName/title",
          "value": "entityName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1entityName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "entityName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1init(entityName:)/title",
          "value": "initWithEntityName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1init(entityName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEntityName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1includesSubentities/title",
          "value": "includesSubentities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1includesSubentities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "includesSubentities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequestResultType/title",
          "value": "NSFetchRequestResultType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequestResultType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchRequestResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequestResultType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchRequestResultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityDescription/title",
          "value": "NSEntityDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1entity/title",
          "value": "entity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1entity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "entity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest/title",
          "value": "NSFetchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsfetchrequest/fetchrequestwithentityname:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
