{"abstract":[{"type":"text","text":"Notification is active."}],"metadata":{"role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"}],"modules":[{"name":"Exposure Notification"}],"navigatorTitle":[{"text":"ENStatusActive","kind":"identifier"}],"title":"ENStatus.active","roleHeading":"Case","externalID":"c:@E@ENStatus@ENStatusActive","platforms":[{"introducedAt":"12.5","beta":false,"name":"iOS","unavailable":false,"deprecated":false},{"introducedAt":"12.5","beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"introducedAt":"12.5","beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false}]},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.exposurenotification/documentation/ExposureNotification","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"}],"platforms":["iOS","iPadOS"]}]}],"seeAlsoSections":[{"anchor":"States","identifiers":["doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/bluetoothOff","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/disabled","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/restricted","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/unknown","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/paused","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/unauthorized"],"generated":true,"title":"States"}],"sections":[],"variants":[{"paths":["/documentation/exposurenotification/enstatus/active"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/exposurenotification/enstatus/active"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/active"},"references":{"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/bluetoothOff":{"abstract":[{"text":"Bluetooth is turned off.","type":"text"}],"kind":"symbol","role":"symbol","title":"ENStatus.bluetoothOff","url":"/documentation/exposurenotification/enstatus/bluetoothoff","navigatorTitle":[{"kind":"identifier","text":"ENStatusBluetoothOff"}],"type":"topic","identifier":"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/bluetoothOff","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bluetoothOff"}]},"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/restricted":{"abstract":[{"text":"Notification is not active due to system restrictions, such as parental controls.","type":"text"}],"kind":"symbol","role":"symbol","title":"ENStatus.restricted","url":"/documentation/exposurenotification/enstatus/restricted","navigatorTitle":[{"kind":"identifier","text":"ENStatusRestricted"}],"type":"topic","identifier":"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/restricted","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"restricted"}]},"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/active":{"navigatorTitle":[{"text":"ENStatusActive","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"Notification is active.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/active","title":"ENStatus.active","url":"/documentation/exposurenotification/enstatus/active","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"}]},"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus":{"abstract":[{"text":"A set of cases that represents the overall status of exposure notification on the system.","type":"text"}],"kind":"symbol","role":"symbol","title":"ENStatus","url":"/documentation/exposurenotification/enstatus","navigatorTitle":[{"kind":"identifier","text":"ENStatus"}],"type":"topic","identifier":"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ENStatus"}]},"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/unauthorized":{"abstract":[{"text":"The user hasn’t authorized Exposure Notification.","type":"text"}],"kind":"symbol","role":"symbol","title":"ENStatus.unauthorized","url":"/documentation/exposurenotification/enstatus/unauthorized","navigatorTitle":[{"kind":"identifier","text":"ENStatusUnauthorized"}],"type":"topic","identifier":"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/unauthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unauthorized"}]},"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/unknown":{"abstract":[{"text":"Notification is unknown.","type":"text"}],"kind":"symbol","role":"symbol","title":"ENStatus.unknown","url":"/documentation/exposurenotification/enstatus/unknown","navigatorTitle":[{"kind":"identifier","text":"ENStatusUnknown"}],"type":"topic","identifier":"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}]},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","role":"overview","url":"/documentation/technologies","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/paused":{"abstract":[{"text":"The user paused Exposure Notification.","type":"text"}],"kind":"symbol","role":"symbol","title":"ENStatus.paused","url":"/documentation/exposurenotification/enstatus/paused","navigatorTitle":[{"kind":"identifier","text":"ENStatusPaused"}],"type":"topic","identifier":"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/paused","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"paused"}]},"doc://com.apple.exposurenotification/documentation/ExposureNotification":{"abstract":[{"type":"text","text":"Implement a COVID-19 exposure notification system that protects user privacy."}],"type":"topic","title":"Exposure Notification","role":"collection","url":"/documentation/exposurenotification","kind":"symbol","identifier":"doc://com.apple.exposurenotification/documentation/ExposureNotification"},"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/disabled":{"abstract":[{"text":"Notification is disabled.","type":"text"}],"kind":"symbol","role":"symbol","title":"ENStatus.disabled","url":"/documentation/exposurenotification/enstatus/disabled","navigatorTitle":[{"kind":"identifier","text":"ENStatusDisabled"}],"type":"topic","identifier":"doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/disabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disabled"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"beta":false,"introducedAt":"12.5","name":"iOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"12.5","name":"iPadOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"12.5","name":"Mac Catalyst","deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"/metadata/title","value":"ENStatusActive"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"ENStatusActive","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.exposurenotification/documentation/ExposureNotification","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/bluetoothOff","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/disabled","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/restricted","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/unknown","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/paused","doc://com.apple.exposurenotification/documentation/ExposureNotification/ENStatus/unauthorized"],"title":"States","generated":true,"anchor":"States"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ENStatusActive"}],"platforms":["iOS","iPadOS"]}],"kind":"declarations"}},{"op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus~1bluetoothOff/title","value":"ENStatusBluetoothOff"},{"op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus~1bluetoothOff/fragments","value":[{"kind":"identifier","text":"ENStatusBluetoothOff"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus~1restricted/title","value":"ENStatusRestricted"},{"op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus~1restricted/fragments","value":[{"kind":"identifier","text":"ENStatusRestricted"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus~1active/title","value":"ENStatusActive"},{"op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus~1active/fragments","value":[{"text":"ENStatusActive","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus/title","value":"ENStatus"},{"op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus/fragments","value":[{"text":"ENStatus","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus/navigatorTitle","value":[{"kind":"identifier","text":"ENStatus"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus~1unauthorized/title","value":"ENStatusUnauthorized"},{"path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus~1unauthorized/fragments","value":[{"kind":"identifier","text":"ENStatusUnauthorized"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus~1unknown/title","value":"ENStatusUnknown","op":"replace"},{"path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus~1unknown/fragments","value":[{"kind":"identifier","text":"ENStatusUnknown"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus~1paused/title","value":"ENStatusPaused","op":"replace"},{"path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus~1paused/fragments","value":[{"kind":"identifier","text":"ENStatusPaused"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus~1disabled/title","value":"ENStatusDisabled","op":"replace"},{"path":"/references/doc:~1~1com.apple.exposurenotification~1documentation~1ExposureNotification~1ENStatus~1disabled/fragments","value":[{"text":"ENStatusDisabled","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}