{
  "abstract": [
    {
      "text": "The temperature was taken on the eardrum.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/earDrum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKBodyTemperatureSensorLocation@HKBodyTemperatureSensorLocationEarDrum",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "earDrum"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKBodyTemperatureSensorLocationEarDrum"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKBodyTemperatureSensorLocation.earDrum"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "earDrum"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation": {
      "abstract": [
        {
          "text": "Constants that indicate where on the body a temperature reading was taken.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKBodyTemperatureSensorLocation"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBodyTemperatureSensorLocation"
        }
      ],
      "role": "symbol",
      "title": "HKBodyTemperatureSensorLocation",
      "type": "topic",
      "url": "/documentation/healthkit/hkbodytemperaturesensorlocation"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/armpit": {
      "abstract": [
        {
          "text": "The temperature was taken in the armpit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "armpit"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/armpit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBodyTemperatureSensorLocationArmpit"
        }
      ],
      "role": "symbol",
      "title": "HKBodyTemperatureSensorLocation.armpit",
      "type": "topic",
      "url": "/documentation/healthkit/hkbodytemperaturesensorlocation/armpit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/body": {
      "abstract": [
        {
          "text": "The temperature was taken on the body.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "body"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/body",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBodyTemperatureSensorLocationBody"
        }
      ],
      "role": "symbol",
      "title": "HKBodyTemperatureSensorLocation.body",
      "type": "topic",
      "url": "/documentation/healthkit/hkbodytemperaturesensorlocation/body"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/ear": {
      "abstract": [
        {
          "text": "The temperature was taken in the ear.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ear"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/ear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBodyTemperatureSensorLocationEar"
        }
      ],
      "role": "symbol",
      "title": "HKBodyTemperatureSensorLocation.ear",
      "type": "topic",
      "url": "/documentation/healthkit/hkbodytemperaturesensorlocation/ear"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/earDrum": {
      "abstract": [
        {
          "text": "The temperature was taken on the eardrum.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "earDrum"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/earDrum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBodyTemperatureSensorLocationEarDrum"
        }
      ],
      "role": "symbol",
      "title": "HKBodyTemperatureSensorLocation.earDrum",
      "type": "topic",
      "url": "/documentation/healthkit/hkbodytemperaturesensorlocation/eardrum"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/finger": {
      "abstract": [
        {
          "text": "The temperature was taken at the finger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finger"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/finger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBodyTemperatureSensorLocationFinger"
        }
      ],
      "role": "symbol",
      "title": "HKBodyTemperatureSensorLocation.finger",
      "type": "topic",
      "url": "/documentation/healthkit/hkbodytemperaturesensorlocation/finger"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/forehead": {
      "abstract": [
        {
          "text": "The temperature was taken on the forehead.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forehead"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/forehead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBodyTemperatureSensorLocationForehead"
        }
      ],
      "role": "symbol",
      "title": "HKBodyTemperatureSensorLocation.forehead",
      "type": "topic",
      "url": "/documentation/healthkit/hkbodytemperaturesensorlocation/forehead"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/gastroIntestinal": {
      "abstract": [
        {
          "text": "The temperature was taken inside the gastrointestinal tract.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gastroIntestinal"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/gastroIntestinal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBodyTemperatureSensorLocationGastroIntestinal"
        }
      ],
      "role": "symbol",
      "title": "HKBodyTemperatureSensorLocation.gastroIntestinal",
      "type": "topic",
      "url": "/documentation/healthkit/hkbodytemperaturesensorlocation/gastrointestinal"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/mouth": {
      "abstract": [
        {
          "text": "The temperature was taken in the mouth.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mouth"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/mouth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBodyTemperatureSensorLocationMouth"
        }
      ],
      "role": "symbol",
      "title": "HKBodyTemperatureSensorLocation.mouth",
      "type": "topic",
      "url": "/documentation/healthkit/hkbodytemperaturesensorlocation/mouth"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/other": {
      "abstract": [
        {
          "text": "The temperature was taken at a location that is not otherwise in this list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBodyTemperatureSensorLocationOther"
        }
      ],
      "role": "symbol",
      "title": "HKBodyTemperatureSensorLocation.other",
      "type": "topic",
      "url": "/documentation/healthkit/hkbodytemperaturesensorlocation/other"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/rectum": {
      "abstract": [
        {
          "text": "The temperature was taken in the rectum.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rectum"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/rectum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBodyTemperatureSensorLocationRectum"
        }
      ],
      "role": "symbol",
      "title": "HKBodyTemperatureSensorLocation.rectum",
      "type": "topic",
      "url": "/documentation/healthkit/hkbodytemperaturesensorlocation/rectum"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/temporalArtery": {
      "abstract": [
        {
          "text": "The temperature was taken at the temporal artery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "temporalArtery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/temporalArtery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBodyTemperatureSensorLocationTemporalArtery"
        }
      ],
      "role": "symbol",
      "title": "HKBodyTemperatureSensorLocation.temporalArtery",
      "type": "topic",
      "url": "/documentation/healthkit/hkbodytemperaturesensorlocation/temporalartery"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/toe": {
      "abstract": [
        {
          "text": "The temperature was taken at the toe.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toe"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/toe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKBodyTemperatureSensorLocationToe"
        }
      ],
      "role": "symbol",
      "title": "HKBodyTemperatureSensorLocation.toe",
      "type": "topic",
      "url": "/documentation/healthkit/hkbodytemperaturesensorlocation/toe"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Locations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/other",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/armpit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/body",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/ear",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/finger",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/gastroIntestinal",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/mouth",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/rectum",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/toe",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/temporalArtery",
        "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/forehead"
      ],
      "title": "Locations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKBodyTemperatureSensorLocationEarDrum"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBodyTemperatureSensorLocationEarDrum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Locations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/other",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/armpit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/body",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/ear",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/finger",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/gastroIntestinal",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/mouth",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/rectum",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/toe",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/temporalArtery",
                "doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/forehead"
              ],
              "title": "Locations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKBodyTemperatureSensorLocationEarDrum"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1earDrum/title",
          "value": "HKBodyTemperatureSensorLocationEarDrum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1earDrum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBodyTemperatureSensorLocationEarDrum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1other/title",
          "value": "HKBodyTemperatureSensorLocationOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBodyTemperatureSensorLocationOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation/title",
          "value": "HKBodyTemperatureSensorLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBodyTemperatureSensorLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBodyTemperatureSensorLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1ear/title",
          "value": "HKBodyTemperatureSensorLocationEar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1ear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBodyTemperatureSensorLocationEar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1finger/title",
          "value": "HKBodyTemperatureSensorLocationFinger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1finger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBodyTemperatureSensorLocationFinger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1forehead/title",
          "value": "HKBodyTemperatureSensorLocationForehead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1forehead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBodyTemperatureSensorLocationForehead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1toe/title",
          "value": "HKBodyTemperatureSensorLocationToe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1toe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBodyTemperatureSensorLocationToe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1armpit/title",
          "value": "HKBodyTemperatureSensorLocationArmpit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1armpit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBodyTemperatureSensorLocationArmpit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1temporalArtery/title",
          "value": "HKBodyTemperatureSensorLocationTemporalArtery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1temporalArtery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBodyTemperatureSensorLocationTemporalArtery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1rectum/title",
          "value": "HKBodyTemperatureSensorLocationRectum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1rectum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBodyTemperatureSensorLocationRectum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1gastroIntestinal/title",
          "value": "HKBodyTemperatureSensorLocationGastroIntestinal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1gastroIntestinal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBodyTemperatureSensorLocationGastroIntestinal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1body/title",
          "value": "HKBodyTemperatureSensorLocationBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1body/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBodyTemperatureSensorLocationBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1mouth/title",
          "value": "HKBodyTemperatureSensorLocationMouth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1mouth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKBodyTemperatureSensorLocationMouth"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkbodytemperaturesensorlocation/eardrum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkbodytemperaturesensorlocation/eardrum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
