{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation"]]},"variants":[{"paths":["/documentation/healthkit/hkbodytemperaturesensorlocation/forehead"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/healthkit/hkbodytemperaturesensorlocation/forehead"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"forehead"}],"navigatorTitle":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationForehead"}],"modules":[{"name":"HealthKit"}],"externalID":"c:@E@HKBodyTemperatureSensorLocation@HKBodyTemperatureSensorLocationForehead","role":"symbol","title":"HKBodyTemperatureSensorLocation.forehead","platforms":[{"deprecated":false,"name":"iOS","beta":false,"introducedAt":"8.0","unavailable":false},{"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"8.0","unavailable":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.0","unavailable":false},{"deprecated":false,"unavailable":false,"introducedAt":"13.0","name":"macOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"1.0","name":"visionOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"2.0","name":"watchOS","beta":false}]},"abstract":[{"type":"text","text":"The temperature was taken on the forehead."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/forehead"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"forehead"}]}]}],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/other","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/armpit","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/body","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/ear","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/finger","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/gastroIntestinal","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/mouth","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/rectum","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/toe","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/earDrum","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/temporalArtery"],"generated":true,"title":"Locations","anchor":"Locations"}],"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/forehead":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"forehead","kind":"identifier"}],"title":"HKBodyTemperatureSensorLocation.forehead","abstract":[{"text":"The temperature was taken on the forehead.","type":"text"}],"navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationForehead","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/forehead","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/forehead"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/mouth":{"type":"topic","abstract":[{"text":"The temperature was taken in the mouth.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"mouth","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationMouth","kind":"identifier"}],"title":"HKBodyTemperatureSensorLocation.mouth","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/mouth","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/mouth"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/rectum":{"abstract":[{"type":"text","text":"The temperature was taken in the rectum."}],"url":"/documentation/healthkit/hkbodytemperaturesensorlocation/rectum","role":"symbol","title":"HKBodyTemperatureSensorLocation.rectum","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rectum","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationRectum","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/rectum"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/body":{"type":"topic","title":"HKBodyTemperatureSensorLocation.body","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationBody","kind":"identifier"}],"url":"/documentation/healthkit/hkbodytemperaturesensorlocation/body","kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/body","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"body","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The temperature was taken on the body.","type":"text"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/armpit":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"armpit"}],"title":"HKBodyTemperatureSensorLocation.armpit","abstract":[{"text":"The temperature was taken in the armpit.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationArmpit"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/armpit","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/armpit"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/finger":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/finger","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/finger","kind":"symbol","abstract":[{"text":"The temperature was taken at the finger.","type":"text"}],"title":"HKBodyTemperatureSensorLocation.finger","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"finger","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationFinger","kind":"identifier"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/temporalArtery":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"temporalArtery","kind":"identifier"}],"title":"HKBodyTemperatureSensorLocation.temporalArtery","abstract":[{"text":"The temperature was taken at the temporal artery.","type":"text"}],"navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationTemporalArtery","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/temporalArtery","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/temporalartery"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation":{"type":"topic","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocation","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation","kind":"symbol","abstract":[{"type":"text","text":"Constants that indicate where on the body a temperature reading was taken."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKBodyTemperatureSensorLocation","kind":"identifier"}],"url":"/documentation/healthkit/hkbodytemperaturesensorlocation","title":"HKBodyTemperatureSensorLocation","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/earDrum":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"earDrum"}],"title":"HKBodyTemperatureSensorLocation.earDrum","abstract":[{"text":"The temperature was taken on the eardrum.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationEarDrum"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/earDrum","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/eardrum"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/other":{"title":"HKBodyTemperatureSensorLocation.other","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The temperature was taken at a location that is not otherwise in this list."}],"url":"/documentation/healthkit/hkbodytemperaturesensorlocation/other","role":"symbol","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationOther","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/other","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"other","kind":"identifier"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/gastroIntestinal":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gastroIntestinal","kind":"identifier"}],"title":"HKBodyTemperatureSensorLocation.gastroIntestinal","abstract":[{"text":"The temperature was taken inside the gastrointestinal tract.","type":"text"}],"navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationGastroIntestinal","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/gastroIntestinal","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/gastrointestinal"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/ear":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ear"}],"title":"HKBodyTemperatureSensorLocation.ear","abstract":[{"text":"The temperature was taken in the ear.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationEar"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/ear","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/ear"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/toe":{"abstract":[{"type":"text","text":"The temperature was taken at the toe."}],"url":"/documentation/healthkit/hkbodytemperaturesensorlocation/toe","role":"symbol","title":"HKBodyTemperatureSensorLocation.toe","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toe","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationToe","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/toe"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","beta":false,"introducedAt":"8.0","deprecated":false,"unavailable":false},{"name":"iPadOS","beta":false,"introducedAt":"8.0","deprecated":false,"unavailable":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"13.0","deprecated":false,"unavailable":false},{"name":"macOS","beta":false,"introducedAt":"13.0","deprecated":false,"unavailable":false},{"name":"visionOS","beta":false,"introducedAt":"1.0","deprecated":false,"unavailable":false},{"name":"watchOS","beta":false,"introducedAt":"2.0","deprecated":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"/metadata/title","op":"replace","value":"HKBodyTemperatureSensorLocationForehead"},{"path":"/metadata/symbolKind","op":"replace","value":"case"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationForehead"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Locations","anchor":"Locations","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/other","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/armpit","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/body","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/ear","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/finger","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/gastroIntestinal","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/mouth","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/rectum","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/toe","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/earDrum","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/temporalArtery"],"generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"tokens":[{"text":"HKBodyTemperatureSensorLocationForehead","kind":"identifier"}]}]}},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1forehead/title","op":"replace","value":"HKBodyTemperatureSensorLocationForehead"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1forehead/fragments","op":"replace","value":[{"text":"HKBodyTemperatureSensorLocationForehead","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1mouth/title","op":"replace","value":"HKBodyTemperatureSensorLocationMouth"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1mouth/fragments","op":"replace","value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationMouth"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1rectum/title","op":"replace","value":"HKBodyTemperatureSensorLocationRectum"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1rectum/fragments","op":"replace","value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationRectum"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1body/title","op":"replace","value":"HKBodyTemperatureSensorLocationBody"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1body/fragments","op":"replace","value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationBody"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1armpit/title","op":"replace","value":"HKBodyTemperatureSensorLocationArmpit"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1armpit/fragments","op":"replace","value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationArmpit"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1finger/title","op":"replace","value":"HKBodyTemperatureSensorLocationFinger"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1finger/fragments","op":"replace","value":[{"text":"HKBodyTemperatureSensorLocationFinger","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1temporalArtery/title","op":"replace","value":"HKBodyTemperatureSensorLocationTemporalArtery"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1temporalArtery/fragments","op":"replace","value":[{"text":"HKBodyTemperatureSensorLocationTemporalArtery","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation/title","op":"replace","value":"HKBodyTemperatureSensorLocation"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation/fragments","op":"replace","value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocation"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocation"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1earDrum/title","op":"replace","value":"HKBodyTemperatureSensorLocationEarDrum"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1earDrum/fragments","op":"replace","value":[{"text":"HKBodyTemperatureSensorLocationEarDrum","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1other/title","op":"replace","value":"HKBodyTemperatureSensorLocationOther"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1other/fragments","op":"replace","value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationOther"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1gastroIntestinal/title","op":"replace","value":"HKBodyTemperatureSensorLocationGastroIntestinal"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1gastroIntestinal/fragments","op":"replace","value":[{"text":"HKBodyTemperatureSensorLocationGastroIntestinal","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1ear/title","op":"replace","value":"HKBodyTemperatureSensorLocationEar"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1ear/fragments","op":"replace","value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationEar"}]},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1toe/title","op":"replace","value":"HKBodyTemperatureSensorLocationToe"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1toe/fragments","op":"replace","value":[{"text":"HKBodyTemperatureSensorLocationToe","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}