{"abstract":[{"type":"text","text":"The temperature was taken at a location that is not otherwise in this list."}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/other"},"metadata":{"platforms":[{"introducedAt":"8.0","deprecated":false,"name":"iOS","unavailable":false,"beta":false},{"introducedAt":"8.0","deprecated":false,"name":"iPadOS","unavailable":false,"beta":false},{"introducedAt":"13.0","deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"introducedAt":"13.0","deprecated":false,"name":"macOS","unavailable":false,"beta":false},{"introducedAt":"1.0","deprecated":false,"name":"visionOS","unavailable":false,"beta":false},{"introducedAt":"2.0","deprecated":false,"name":"watchOS","unavailable":false,"beta":false}],"symbolKind":"case","title":"HKBodyTemperatureSensorLocation.other","modules":[{"name":"HealthKit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"roleHeading":"Case","externalID":"c:@E@HKBodyTemperatureSensorLocation@HKBodyTemperatureSensorLocationOther","navigatorTitle":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationOther"}]},"seeAlsoSections":[{"generated":true,"title":"Locations","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/armpit","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/body","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/ear","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/finger","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/gastroIntestinal","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/mouth","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/rectum","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/toe","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/earDrum","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/temporalArtery","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/forehead"],"anchor":"Locations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/healthkit/hkbodytemperaturesensorlocation/other"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/healthkit/hkbodytemperaturesensorlocation/other"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation"]]},"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation":{"type":"topic","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocation","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation","kind":"symbol","abstract":[{"type":"text","text":"Constants that indicate where on the body a temperature reading was taken."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKBodyTemperatureSensorLocation","kind":"identifier"}],"url":"/documentation/healthkit/hkbodytemperaturesensorlocation","title":"HKBodyTemperatureSensorLocation","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/gastroIntestinal":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gastroIntestinal","kind":"identifier"}],"title":"HKBodyTemperatureSensorLocation.gastroIntestinal","abstract":[{"text":"The temperature was taken inside the gastrointestinal tract.","type":"text"}],"navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationGastroIntestinal","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/gastroIntestinal","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/gastrointestinal"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/earDrum":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"earDrum"}],"title":"HKBodyTemperatureSensorLocation.earDrum","abstract":[{"text":"The temperature was taken on the eardrum.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationEarDrum"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/earDrum","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/eardrum"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/finger":{"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/finger","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/finger","kind":"symbol","abstract":[{"text":"The temperature was taken at the finger.","type":"text"}],"title":"HKBodyTemperatureSensorLocation.finger","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"finger","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationFinger","kind":"identifier"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/ear":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ear"}],"title":"HKBodyTemperatureSensorLocation.ear","abstract":[{"text":"The temperature was taken in the ear.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationEar"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/ear","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/ear"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/body":{"type":"topic","title":"HKBodyTemperatureSensorLocation.body","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationBody","kind":"identifier"}],"url":"/documentation/healthkit/hkbodytemperaturesensorlocation/body","kind":"symbol","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/body","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"body","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The temperature was taken on the body.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/forehead":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"forehead","kind":"identifier"}],"title":"HKBodyTemperatureSensorLocation.forehead","abstract":[{"text":"The temperature was taken on the forehead.","type":"text"}],"navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationForehead","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/forehead","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/forehead"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/other":{"title":"HKBodyTemperatureSensorLocation.other","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The temperature was taken at a location that is not otherwise in this list."}],"url":"/documentation/healthkit/hkbodytemperaturesensorlocation/other","role":"symbol","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationOther","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/other","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"other","kind":"identifier"}]},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/rectum":{"abstract":[{"type":"text","text":"The temperature was taken in the rectum."}],"url":"/documentation/healthkit/hkbodytemperaturesensorlocation/rectum","role":"symbol","title":"HKBodyTemperatureSensorLocation.rectum","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rectum","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationRectum","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/rectum"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/armpit":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"armpit"}],"title":"HKBodyTemperatureSensorLocation.armpit","abstract":[{"text":"The temperature was taken in the armpit.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationArmpit"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/armpit","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/armpit"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/toe":{"abstract":[{"type":"text","text":"The temperature was taken at the toe."}],"url":"/documentation/healthkit/hkbodytemperaturesensorlocation/toe","role":"symbol","title":"HKBodyTemperatureSensorLocation.toe","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toe","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationToe","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/toe"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/mouth":{"type":"topic","abstract":[{"text":"The temperature was taken in the mouth.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"mouth","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationMouth","kind":"identifier"}],"title":"HKBodyTemperatureSensorLocation.mouth","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/mouth","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/mouth"},"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/temporalArtery":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"temporalArtery","kind":"identifier"}],"title":"HKBodyTemperatureSensorLocation.temporalArtery","abstract":[{"text":"The temperature was taken at the temporal artery.","type":"text"}],"navigatorTitle":[{"text":"HKBodyTemperatureSensorLocationTemporalArtery","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/temporalArtery","type":"topic","kind":"symbol","role":"symbol","url":"/documentation/healthkit/hkbodytemperaturesensorlocation/temporalartery"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"introducedAt":"8.0","deprecated":false,"name":"iOS","unavailable":false,"beta":false},{"introducedAt":"8.0","deprecated":false,"name":"iPadOS","unavailable":false,"beta":false},{"introducedAt":"13.0","deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"introducedAt":"13.0","deprecated":false,"name":"macOS","unavailable":false,"beta":false},{"introducedAt":"1.0","deprecated":false,"name":"visionOS","unavailable":false,"beta":false},{"introducedAt":"2.0","deprecated":false,"name":"watchOS","unavailable":false,"beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"/metadata/title","op":"replace","value":"HKBodyTemperatureSensorLocationOther"},{"path":"/metadata/symbolKind","op":"replace","value":"case"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"HKBodyTemperatureSensorLocationOther","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Locations","anchor":"Locations","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/armpit","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/body","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/ear","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/finger","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/gastroIntestinal","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/mouth","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/rectum","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/toe","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/earDrum","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/temporalArtery","doc://com.apple.healthkit/documentation/HealthKit/HKBodyTemperatureSensorLocation/forehead"],"generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"HKBodyTemperatureSensorLocationOther","kind":"identifier"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"]}],"kind":"declarations"}},{"value":"HKBodyTemperatureSensorLocation","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation/title"},{"value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocation"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation/fragments"},{"value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocation"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation/navigatorTitle"},{"value":"HKBodyTemperatureSensorLocationGastroIntestinal","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1gastroIntestinal/title"},{"value":[{"text":"HKBodyTemperatureSensorLocationGastroIntestinal","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1gastroIntestinal/fragments"},{"value":"HKBodyTemperatureSensorLocationEarDrum","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1earDrum/title"},{"value":[{"text":"HKBodyTemperatureSensorLocationEarDrum","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1earDrum/fragments"},{"value":"HKBodyTemperatureSensorLocationFinger","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1finger/title"},{"value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationFinger"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1finger/fragments"},{"value":"HKBodyTemperatureSensorLocationEar","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1ear/title"},{"value":[{"text":"HKBodyTemperatureSensorLocationEar","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1ear/fragments"},{"value":"HKBodyTemperatureSensorLocationBody","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1body/title"},{"value":[{"text":"HKBodyTemperatureSensorLocationBody","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1body/fragments"},{"value":"HKBodyTemperatureSensorLocationForehead","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1forehead/title"},{"value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationForehead"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1forehead/fragments"},{"value":"HKBodyTemperatureSensorLocationOther","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1other/title"},{"value":[{"text":"HKBodyTemperatureSensorLocationOther","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1other/fragments"},{"value":"HKBodyTemperatureSensorLocationRectum","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1rectum/title"},{"value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationRectum"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1rectum/fragments"},{"value":"HKBodyTemperatureSensorLocationArmpit","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1armpit/title"},{"value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationArmpit"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1armpit/fragments"},{"value":"HKBodyTemperatureSensorLocationToe","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1toe/title"},{"value":[{"kind":"identifier","text":"HKBodyTemperatureSensorLocationToe"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1toe/fragments"},{"value":"HKBodyTemperatureSensorLocationMouth","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1mouth/title"},{"value":[{"text":"HKBodyTemperatureSensorLocationMouth","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1mouth/fragments"},{"value":"HKBodyTemperatureSensorLocationTemporalArtery","op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1temporalArtery/title"},{"value":[{"text":"HKBodyTemperatureSensorLocationTemporalArtery","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKBodyTemperatureSensorLocation~1temporalArtery/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}