{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay",
        "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppConfiguration/appImpression"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "StoreKit",
    "externalID": "s:So25SKOverlayAppConfigurationC023_AdAttributionKit_StoreF0E13appImpression0deF00bI0VSgvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "appImpression"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:16AdAttributionKit13AppImpressionV",
        "text": "AppImpression"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "AdAttributionKit",
        "relatedModules": [
          "StoreKit"
        ]
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "appImpression"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "appImpression"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:16AdAttributionKit13AppImpressionV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:16AdAttributionKit13AppImpressionV",
              "text": "AppImpression"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay": {
      "abstract": [
        {
          "text": "A class that displays an overlay you can use to recommend another app or an App Clip’s corresponding full app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKOverlay"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKOverlay"
        }
      ],
      "role": "symbol",
      "title": "SKOverlay",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppConfiguration": {
      "abstract": [
        {
          "text": "An object that represents the attributes of an overlay you use to recommend another app on the App Store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AppConfiguration"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AppConfiguration"
        }
      ],
      "role": "symbol",
      "title": "SKOverlay.AppConfiguration",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/appconfiguration"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppConfiguration/appImpression": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appImpression"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:16AdAttributionKit13AppImpressionV",
          "text": "AppImpression"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKOverlay/AppConfiguration/appImpression",
      "kind": "symbol",
      "role": "symbol",
      "title": "appImpression",
      "type": "topic",
      "url": "/documentation/storekit/skoverlay/appconfiguration/appimpression"
    },
    "doc://com.externally.resolved.symbol/s:16AdAttributionKit13AppImpressionV": {
      "abstract": [
        {
          "text": "A structure that represents an attributable impression the developer generates in response to a person’s interaction with an ad in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AppImpression"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:16AdAttributionKit13AppImpressionV",
      "kind": "symbol",
      "role": "symbol",
      "title": "AppImpression",
      "type": "topic",
      "url": "/documentation/AdAttributionKit/AppImpression"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay/title",
          "value": "SKOverlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppConfiguration/title",
          "value": "SKOverlayAppConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayAppConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKOverlay~1AppConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKOverlayAppConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skoverlay/appconfiguration/appimpression"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
