{
  "abstract": [
    {
      "text": "An electronic money card.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/eMoney"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKPaymentMethodType@PKPaymentMethodTypeEMoney",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "eMoney"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKPaymentMethodTypeEMoney"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PKPaymentMethodType.eMoney"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "eMoney"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType": {
      "abstract": [
        {
          "text": "The type of cards available in Apple Pay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentMethodType"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentMethodType"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentMethodType",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentmethodtype"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/credit": {
      "abstract": [
        {
          "text": "A credit card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "credit"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/credit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentMethodTypeCredit"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentMethodType.credit",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentmethodtype/credit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/debit": {
      "abstract": [
        {
          "text": "A debit card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debit"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/debit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentMethodTypeDebit"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentMethodType.debit",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentmethodtype/debit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/eMoney": {
      "abstract": [
        {
          "text": "An electronic money card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eMoney"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/eMoney",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentMethodTypeEMoney"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentMethodType.eMoney",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentmethodtype/emoney"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/prepaid": {
      "abstract": [
        {
          "text": "A prepaid card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepaid"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/prepaid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentMethodTypePrepaid"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentMethodType.prepaid",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentmethodtype/prepaid"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/store": {
      "abstract": [
        {
          "text": "A store card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "store"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/store",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentMethodTypeStore"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentMethodType.store",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentmethodtype/store"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/unknown": {
      "abstract": [
        {
          "text": "The card’s type is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentMethodTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentMethodType.unknown",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentmethodtype/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Payment-Method-Type-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/unknown",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/debit",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/credit",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/prepaid",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/store"
      ],
      "title": "Payment Method Type Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKPaymentMethodTypeEMoney"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentMethodTypeEMoney"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Payment-Method-Type-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/unknown",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/debit",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/credit",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/prepaid",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentMethodType/store"
              ],
              "title": "Payment Method Type Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PKPaymentMethodTypeEMoney"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentMethodType~1unknown/title",
          "value": "PKPaymentMethodTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentMethodType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentMethodTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentMethodType~1store/title",
          "value": "PKPaymentMethodTypeStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentMethodType~1store/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentMethodTypeStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentMethodType/title",
          "value": "PKPaymentMethodType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentMethodType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentMethodType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentMethodType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentMethodType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentMethodType~1prepaid/title",
          "value": "PKPaymentMethodTypePrepaid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentMethodType~1prepaid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentMethodTypePrepaid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentMethodType~1credit/title",
          "value": "PKPaymentMethodTypeCredit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentMethodType~1credit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentMethodTypeCredit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentMethodType~1debit/title",
          "value": "PKPaymentMethodTypeDebit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentMethodType~1debit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentMethodTypeDebit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentMethodType~1eMoney/title",
          "value": "PKPaymentMethodTypeEMoney"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentMethodType~1eMoney/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentMethodTypeEMoney"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpaymentmethodtype/emoney"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpaymentmethodtype/emoney"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
