{
  "abstract": [
    {
      "text": "The content of the PDF appears with thumbnails of all pages on the right side of the current page’s content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quicklook/documentation/QuickLook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPDFPagesWithThumbnailsOnRightStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@QLPreviewPDFStyle@kQLPreviewPDFPagesWithThumbnailsOnRightStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kQLPreviewPDFPagesWithThumbnailsOnRightStyle"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@QLPreviewPDFStyle",
        "text": "QLPreviewPDFStyle"
      }
    ],
    "modules": [
      {
        "name": "Quick Look"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kQLPreviewPDFPagesWithThumbnailsOnRightStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kQLPreviewPDFPagesWithThumbnailsOnRightStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kQLPreviewPDFPagesWithThumbnailsOnRightStyle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewPDFStyle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@QLPreviewPDFStyle",
              "text": "QLPreviewPDFStyle"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quicklook/documentation/QuickLook": {
      "abstract": [
        {
          "text": "Create previews of files to use inside your app, or perform simple edits on previews.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook",
      "kind": "symbol",
      "role": "collection",
      "title": "Quick Look",
      "type": "topic",
      "url": "/documentation/quicklook"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewPDFStyle": {
      "abstract": [
        {
          "text": "A value you use to configure the appearance of previews for PDF files.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewPDFStyle"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewPDFStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewPDFStyle"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewPDFStyle",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewpdfstyle"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPDFPagesWithThumbnailsOnLeftStyle": {
      "abstract": [
        {
          "text": "The content of the PDF appears with thumbnails of all pages on the left side of the current page’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLPreviewPDFPagesWithThumbnailsOnLeftStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@QLPreviewPDFStyle",
          "text": "QLPreviewPDFStyle"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPDFPagesWithThumbnailsOnLeftStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLPreviewPDFPagesWithThumbnailsOnLeftStyle"
        }
      ],
      "role": "symbol",
      "title": "kQLPreviewPDFPagesWithThumbnailsOnLeftStyle",
      "type": "topic",
      "url": "/documentation/quicklook/kqlpreviewpdfpageswiththumbnailsonleftstyle"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPDFPagesWithThumbnailsOnRightStyle": {
      "abstract": [
        {
          "text": "The content of the PDF appears with thumbnails of all pages on the right side of the current page’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLPreviewPDFPagesWithThumbnailsOnRightStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@QLPreviewPDFStyle",
          "text": "QLPreviewPDFStyle"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPDFPagesWithThumbnailsOnRightStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLPreviewPDFPagesWithThumbnailsOnRightStyle"
        }
      ],
      "role": "symbol",
      "title": "kQLPreviewPDFPagesWithThumbnailsOnRightStyle",
      "type": "topic",
      "url": "/documentation/quicklook/kqlpreviewpdfpageswiththumbnailsonrightstyle"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPDFStandardStyle": {
      "abstract": [
        {
          "text": "The PDF appears in the operating system’s standard style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLPreviewPDFStandardStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@QLPreviewPDFStyle",
          "text": "QLPreviewPDFStyle"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPDFStandardStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLPreviewPDFStandardStyle"
        }
      ],
      "role": "symbol",
      "title": "kQLPreviewPDFStandardStyle",
      "type": "topic",
      "url": "/documentation/quicklook/kqlpreviewpdfstandardstyle"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Styles-for-PDF-Previews",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPDFStandardStyle",
        "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPDFPagesWithThumbnailsOnLeftStyle"
      ],
      "title": "Styles for PDF Previews"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kQLPreviewPDFPagesWithThumbnailsOnRightStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewPDFPagesWithThumbnailsOnRightStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quicklook/documentation/QuickLook",
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewPDFStyle"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Styles-for-PDF-Previews",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPDFStandardStyle",
                "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPDFPagesWithThumbnailsOnLeftStyle"
              ],
              "title": "Styles for PDF Previews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kQLPreviewPDFPagesWithThumbnailsOnRightStyle"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPDFStandardStyle/title",
          "value": "kQLPreviewPDFStandardStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPDFStandardStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewPDFStandardStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPDFPagesWithThumbnailsOnRightStyle/title",
          "value": "kQLPreviewPDFPagesWithThumbnailsOnRightStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPDFPagesWithThumbnailsOnRightStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewPDFPagesWithThumbnailsOnRightStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewPDFStyle/title",
          "value": "QLPreviewPDFStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewPDFStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPDFStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewPDFStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewPDFStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPDFPagesWithThumbnailsOnLeftStyle/title",
          "value": "kQLPreviewPDFPagesWithThumbnailsOnLeftStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPDFPagesWithThumbnailsOnLeftStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewPDFPagesWithThumbnailsOnLeftStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quicklook/kqlpreviewpdfpageswiththumbnailsonrightstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quicklook/kqlpreviewpdfpageswiththumbnailsonrightstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
