{
  "abstract": [
    {
      "text": "The height in points of the preview.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use the preferredContentSize property of your QLPreviewingController in a Preview Extension.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quicklook/documentation/QuickLook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyHeightKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kQLPreviewPropertyHeightKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kQLPreviewPropertyHeightKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": "!"
      }
    ],
    "modules": [
      {
        "name": "Quick Look"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kQLPreviewPropertyHeightKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.0",
        "message": "Use the preferredContentSize property of your QLPreviewingController in a Preview Extension.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kQLPreviewPropertyHeightKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kQLPreviewPropertyHeightKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": "!"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Note that this property is a hint; Quick Look may set the height automatically for some types of previews. You must encapsulate the value in a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd",
      "kind": "article",
      "role": "article",
      "title": "CFNumber",
      "type": "topic",
      "url": "/documentation/corefoundation/cfnumber-rjd"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quicklook/documentation/QuickLook": {
      "abstract": [
        {
          "text": "Create previews of files to use inside your app, or perform simple edits on previews.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook",
      "kind": "symbol",
      "role": "collection",
      "title": "Quick Look",
      "type": "topic",
      "url": "/documentation/quicklook"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewContentIDScheme": {
      "abstract": [
        {
          "text": "The content ID URL scheme.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLPreviewContentIDScheme"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewContentIDScheme",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLPreviewContentIDScheme"
        }
      ],
      "role": "symbol",
      "title": "kQLPreviewContentIDScheme",
      "type": "topic",
      "url": "/documentation/quicklook/kqlpreviewcontentidscheme"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewOptionCursorKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLPreviewOptionCursorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewOptionCursorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLPreviewOptionCursorKey"
        }
      ],
      "role": "symbol",
      "title": "kQLPreviewOptionCursorKey",
      "type": "topic",
      "url": "/documentation/quicklook/kqlpreviewoptioncursorkey"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyAttachmentDataKey": {
      "abstract": [
        {
          "text": "Attachment data for a preview.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyAttachmentDataKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyAttachmentDataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyAttachmentDataKey"
        }
      ],
      "role": "symbol",
      "title": "kQLPreviewPropertyAttachmentDataKey",
      "type": "topic",
      "url": "/documentation/quicklook/kqlpreviewpropertyattachmentdatakey"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyAttachmentsKey": {
      "abstract": [
        {
          "text": "A list of attachments or sub-resources.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyAttachmentsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyAttachmentsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyAttachmentsKey"
        }
      ],
      "role": "symbol",
      "title": "kQLPreviewPropertyAttachmentsKey",
      "type": "topic",
      "url": "/documentation/quicklook/kqlpreviewpropertyattachmentskey"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyBaseBundlePathKey": {
      "abstract": [
        {
          "text": "A path that’s outside of the default security scope for creating a preview.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyBaseBundlePathKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyBaseBundlePathKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyBaseBundlePathKey"
        }
      ],
      "role": "symbol",
      "title": "kQLPreviewPropertyBaseBundlePathKey",
      "type": "topic",
      "url": "/documentation/quicklook/kqlpreviewpropertybasebundlepathkey"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyCursorKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyCursorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyCursorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyCursorKey"
        }
      ],
      "role": "symbol",
      "title": "kQLPreviewPropertyCursorKey",
      "type": "topic",
      "url": "/documentation/quicklook/kqlpreviewpropertycursorkey"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyDisplayNameKey": {
      "abstract": [
        {
          "text": "A custom display name for the preview panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyDisplayNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyDisplayNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyDisplayNameKey"
        }
      ],
      "role": "symbol",
      "title": "kQLPreviewPropertyDisplayNameKey",
      "type": "topic",
      "url": "/documentation/quicklook/kqlpreviewpropertydisplaynamekey"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyHeightKey": {
      "abstract": [
        {
          "text": "The height in points of the preview.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyHeightKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyHeightKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyHeightKey"
        }
      ],
      "role": "symbol",
      "title": "kQLPreviewPropertyHeightKey",
      "type": "topic",
      "url": "/documentation/quicklook/kqlpreviewpropertyheightkey"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyMIMETypeKey": {
      "abstract": [
        {
          "text": "The web content or attachment mime type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyMIMETypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyMIMETypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyMIMETypeKey"
        }
      ],
      "role": "symbol",
      "title": "kQLPreviewPropertyMIMETypeKey",
      "type": "topic",
      "url": "/documentation/quicklook/kqlpreviewpropertymimetypekey"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyPDFStyleKey": {
      "abstract": [
        {
          "text": "The preferred way to display PDF content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyPDFStyleKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyPDFStyleKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyPDFStyleKey"
        }
      ],
      "role": "symbol",
      "title": "kQLPreviewPropertyPDFStyleKey",
      "type": "topic",
      "url": "/documentation/quicklook/kqlpreviewpropertypdfstylekey"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyStringEncodingKey": {
      "abstract": [
        {
          "text": "The string encoding of the preview data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyStringEncodingKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyStringEncodingKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyStringEncodingKey"
        }
      ],
      "role": "symbol",
      "title": "kQLPreviewPropertyStringEncodingKey",
      "type": "topic",
      "url": "/documentation/quicklook/kqlpreviewpropertystringencodingkey"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyTextEncodingNameKey": {
      "abstract": [
        {
          "text": "The encoding of the web content or attachment text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyTextEncodingNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyTextEncodingNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyTextEncodingNameKey"
        }
      ],
      "role": "symbol",
      "title": "kQLPreviewPropertyTextEncodingNameKey",
      "type": "topic",
      "url": "/documentation/quicklook/kqlpreviewpropertytextencodingnamekey"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyWidthKey": {
      "abstract": [
        {
          "text": "The width in points of the preview.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyWidthKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyWidthKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLPreviewPropertyWidthKey"
        }
      ],
      "role": "symbol",
      "title": "kQLPreviewPropertyWidthKey",
      "type": "topic",
      "url": "/documentation/quicklook/kqlpreviewpropertywidthkey"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLThumbnailPropertyBadgeImageKey": {
      "abstract": [
        {
          "text": "An image to use for generating the badge for a file’s icon.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLThumbnailPropertyBadgeImageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLThumbnailPropertyBadgeImageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLThumbnailPropertyBadgeImageKey"
        }
      ],
      "role": "symbol",
      "title": "kQLThumbnailPropertyBadgeImageKey",
      "type": "topic",
      "url": "/documentation/quicklook/kqlthumbnailpropertybadgeimagekey"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLThumbnailPropertyBaseBundlePathKey": {
      "abstract": [
        {
          "text": "A path that’s outside of the default security scope for creating a thumbnail.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLThumbnailPropertyBaseBundlePathKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLThumbnailPropertyBaseBundlePathKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLThumbnailPropertyBaseBundlePathKey"
        }
      ],
      "role": "symbol",
      "title": "kQLThumbnailPropertyBaseBundlePathKey",
      "type": "topic",
      "url": "/documentation/quicklook/kqlthumbnailpropertybasebundlepathkey"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/kQLThumbnailPropertyExtensionKey": {
      "abstract": [
        {
          "text": "The extension to use as a badge when creating an icon.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kQLThumbnailPropertyExtensionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/kQLThumbnailPropertyExtensionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kQLThumbnailPropertyExtensionKey"
        }
      ],
      "role": "symbol",
      "title": "kQLThumbnailPropertyExtensionKey",
      "type": "topic",
      "url": "/documentation/quicklook/kqlthumbnailpropertyextensionkey"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewContentIDScheme",
        "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyCursorKey",
        "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewOptionCursorKey",
        "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyAttachmentDataKey",
        "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyAttachmentsKey",
        "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyBaseBundlePathKey",
        "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyDisplayNameKey",
        "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyMIMETypeKey",
        "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyPDFStyleKey",
        "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyStringEncodingKey",
        "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyTextEncodingNameKey",
        "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyWidthKey",
        "doc://com.apple.quicklook/documentation/QuickLook/kQLThumbnailPropertyBadgeImageKey",
        "doc://com.apple.quicklook/documentation/QuickLook/kQLThumbnailPropertyBaseBundlePathKey",
        "doc://com.apple.quicklook/documentation/QuickLook/kQLThumbnailPropertyExtensionKey"
      ],
      "title": "Deprecated constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kQLPreviewPropertyHeightKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewPropertyHeightKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quicklook/documentation/QuickLook"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewContentIDScheme",
                "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyCursorKey",
                "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewOptionCursorKey",
                "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyAttachmentDataKey",
                "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyAttachmentsKey",
                "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyBaseBundlePathKey",
                "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyDisplayNameKey",
                "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyMIMETypeKey",
                "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyPDFStyleKey",
                "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyStringEncodingKey",
                "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyTextEncodingNameKey",
                "doc://com.apple.quicklook/documentation/QuickLook/kQLPreviewPropertyWidthKey",
                "doc://com.apple.quicklook/documentation/QuickLook/kQLThumbnailPropertyBadgeImageKey",
                "doc://com.apple.quicklook/documentation/QuickLook/kQLThumbnailPropertyBaseBundlePathKey",
                "doc://com.apple.quicklook/documentation/QuickLook/kQLThumbnailPropertyExtensionKey"
              ],
              "title": "Deprecated constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kQLPreviewPropertyHeightKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use the preferredContentSize property of your QLPreviewingController in a Preview Extension.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewOptionCursorKey/title",
          "value": "kQLPreviewOptionCursorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewOptionCursorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewOptionCursorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLThumbnailPropertyBaseBundlePathKey/title",
          "value": "kQLThumbnailPropertyBaseBundlePathKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLThumbnailPropertyBaseBundlePathKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLThumbnailPropertyBaseBundlePathKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyWidthKey/title",
          "value": "kQLPreviewPropertyWidthKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyWidthKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewPropertyWidthKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyDisplayNameKey/title",
          "value": "kQLPreviewPropertyDisplayNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyDisplayNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewPropertyDisplayNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyHeightKey/title",
          "value": "kQLPreviewPropertyHeightKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyHeightKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewPropertyHeightKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLThumbnailPropertyExtensionKey/title",
          "value": "kQLThumbnailPropertyExtensionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLThumbnailPropertyExtensionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLThumbnailPropertyExtensionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyStringEncodingKey/title",
          "value": "kQLPreviewPropertyStringEncodingKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyStringEncodingKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewPropertyStringEncodingKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyMIMETypeKey/title",
          "value": "kQLPreviewPropertyMIMETypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyMIMETypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewPropertyMIMETypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyBaseBundlePathKey/title",
          "value": "kQLPreviewPropertyBaseBundlePathKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyBaseBundlePathKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewPropertyBaseBundlePathKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyTextEncodingNameKey/title",
          "value": "kQLPreviewPropertyTextEncodingNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyTextEncodingNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewPropertyTextEncodingNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyPDFStyleKey/title",
          "value": "kQLPreviewPropertyPDFStyleKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyPDFStyleKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewPropertyPDFStyleKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyAttachmentsKey/title",
          "value": "kQLPreviewPropertyAttachmentsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyAttachmentsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewPropertyAttachmentsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyCursorKey/title",
          "value": "kQLPreviewPropertyCursorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyCursorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewPropertyCursorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewContentIDScheme/title",
          "value": "kQLPreviewContentIDScheme"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewContentIDScheme/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewContentIDScheme"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLThumbnailPropertyBadgeImageKey/title",
          "value": "kQLThumbnailPropertyBadgeImageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLThumbnailPropertyBadgeImageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLThumbnailPropertyBadgeImageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyAttachmentDataKey/title",
          "value": "kQLPreviewPropertyAttachmentDataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1kQLPreviewPropertyAttachmentDataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kQLPreviewPropertyAttachmentDataKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quicklook/kqlpreviewpropertyheightkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quicklook/kqlpreviewpropertyheightkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
