{
  "abstract": [
    {
      "text": "An opaque reference that provides callbacks that the platform uses to interface with a Quick Look plug-in.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quicklook/documentation/QuickLook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@QLGeneratorInterfaceStruct",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "QLGeneratorInterfaceStruct"
      }
    ],
    "modules": [
      {
        "name": "Quick Look"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "QLGeneratorInterfaceStruct"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "QLGeneratorInterfaceStruct"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "QLGeneratorInterfaceStruct"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quicklook/documentation/QuickLook": {
      "abstract": [
        {
          "text": "Create previews of files to use inside your app, or perform simple edits on previews.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook",
      "kind": "symbol",
      "role": "collection",
      "title": "Quick Look",
      "type": "topic",
      "url": "/documentation/quicklook"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct": {
      "abstract": [
        {
          "text": "An opaque reference that provides callbacks that the platform uses to interface with a Quick Look plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLGeneratorInterfaceStruct"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLGeneratorInterfaceStruct"
        }
      ],
      "role": "symbol",
      "title": "QLGeneratorInterfaceStruct",
      "type": "topic",
      "url": "/documentation/quicklook/qlgeneratorinterfacestruct"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/AddRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AddRef"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ULONG",
          "text": "ULONG"
        },
        {
          "kind": "text",
          "text": ")!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/AddRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AddRef"
        }
      ],
      "role": "symbol",
      "title": "AddRef",
      "type": "topic",
      "url": "/documentation/quicklook/qlgeneratorinterfacestruct/addref"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/CancelPreviewGeneration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CancelPreviewGeneration"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@QLPreviewRequestRef",
          "text": "QLPreviewRequest"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/CancelPreviewGeneration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CancelPreviewGeneration"
        }
      ],
      "role": "symbol",
      "title": "CancelPreviewGeneration",
      "type": "topic",
      "url": "/documentation/quicklook/qlgeneratorinterfacestruct/cancelpreviewgeneration"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/CancelThumbnailGeneration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CancelThumbnailGeneration"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@QLThumbnailRequestRef",
          "text": "QLThumbnailRequest"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/CancelThumbnailGeneration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CancelThumbnailGeneration"
        }
      ],
      "role": "symbol",
      "title": "CancelThumbnailGeneration",
      "type": "topic",
      "url": "/documentation/quicklook/qlgeneratorinterfacestruct/cancelthumbnailgeneration"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/GeneratePreviewForURL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GeneratePreviewForURL"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@QLPreviewRequestRef",
          "text": "QLPreviewRequest"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        },
        {
          "kind": "text",
          "text": ")!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/GeneratePreviewForURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GeneratePreviewForURL"
        }
      ],
      "role": "symbol",
      "title": "GeneratePreviewForURL",
      "type": "topic",
      "url": "/documentation/quicklook/qlgeneratorinterfacestruct/generatepreviewforurl"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/GenerateThumbnailForURL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GenerateThumbnailForURL"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@QLThumbnailRequestRef",
          "text": "QLThumbnailRequest"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        },
        {
          "kind": "text",
          "text": ")!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/GenerateThumbnailForURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GenerateThumbnailForURL"
        }
      ],
      "role": "symbol",
      "title": "GenerateThumbnailForURL",
      "type": "topic",
      "url": "/documentation/quicklook/qlgeneratorinterfacestruct/generatethumbnailforurl"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/QueryInterface": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QueryInterface"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@REFIID",
          "text": "REFIID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@LPVOID",
          "text": "LPVOID"
        },
        {
          "kind": "text",
          "text": "?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@HRESULT",
          "text": "HRESULT"
        },
        {
          "kind": "text",
          "text": ")!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/QueryInterface",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QueryInterface"
        }
      ],
      "role": "symbol",
      "title": "QueryInterface",
      "type": "topic",
      "url": "/documentation/quicklook/qlgeneratorinterfacestruct/queryinterface"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/Release": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Release"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ULONG",
          "text": "ULONG"
        },
        {
          "kind": "text",
          "text": ")!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/Release",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Release"
        }
      ],
      "role": "symbol",
      "title": "Release",
      "type": "topic",
      "url": "/documentation/quicklook/qlgeneratorinterfacestruct/release"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/init()": {
      "abstract": [
        {
          "text": "Creates the interface structure that the platform uses to interface with a Quick Look plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/quicklook/qlgeneratorinterfacestruct/init()"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-a-Quick-Look-Plug-In",
      "identifiers": [
        "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/init()",
        "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/QueryInterface",
        "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/AddRef",
        "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/Release",
        "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/GenerateThumbnailForURL",
        "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/CancelThumbnailGeneration",
        "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/GeneratePreviewForURL",
        "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/CancelPreviewGeneration"
      ],
      "title": "Creating a Quick Look Plug-In"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "QLGeneratorInterfaceStruct"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLGeneratorInterfaceStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLGeneratorInterfaceStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quicklook/documentation/QuickLook"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Quick-Look-Plug-In",
              "identifiers": [
                "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/QueryInterface",
                "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/AddRef",
                "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/Release",
                "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/GenerateThumbnailForURL",
                "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/CancelThumbnailGeneration",
                "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/GeneratePreviewForURL",
                "doc://com.apple.quicklook/documentation/QuickLook/QLGeneratorInterfaceStruct/CancelPreviewGeneration"
              ],
              "title": "Creating a Quick Look Plug-In"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "QLGeneratorInterfaceStruct"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLGeneratorInterfaceStruct~1GeneratePreviewForURL/title",
          "value": "GeneratePreviewForURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLGeneratorInterfaceStruct~1GeneratePreviewForURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GeneratePreviewForURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLGeneratorInterfaceStruct~1AddRef/title",
          "value": "AddRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLGeneratorInterfaceStruct~1AddRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AddRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLGeneratorInterfaceStruct~1CancelPreviewGeneration/title",
          "value": "CancelPreviewGeneration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLGeneratorInterfaceStruct~1CancelPreviewGeneration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CancelPreviewGeneration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLGeneratorInterfaceStruct~1CancelThumbnailGeneration/title",
          "value": "CancelThumbnailGeneration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLGeneratorInterfaceStruct~1CancelThumbnailGeneration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CancelThumbnailGeneration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLGeneratorInterfaceStruct~1GenerateThumbnailForURL/title",
          "value": "GenerateThumbnailForURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLGeneratorInterfaceStruct~1GenerateThumbnailForURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GenerateThumbnailForURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLGeneratorInterfaceStruct~1Release/title",
          "value": "Release"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLGeneratorInterfaceStruct~1Release/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Release"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLGeneratorInterfaceStruct/title",
          "value": "QLGeneratorInterfaceStruct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLGeneratorInterfaceStruct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLGeneratorInterfaceStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLGeneratorInterfaceStruct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLGeneratorInterfaceStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLGeneratorInterfaceStruct~1QueryInterface/title",
          "value": "QueryInterface"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLGeneratorInterfaceStruct~1QueryInterface/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QueryInterface"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quicklook/qlgeneratorinterfacestruct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quicklook/qlgeneratorinterfacestruct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
