{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quicklook/documentation/QuickLook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReplyAttachment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)QLPreviewReplyAttachment",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "QLPreviewReplyAttachment"
      }
    ],
    "modules": [
      {
        "name": "Quick Look"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "QLPreviewReplyAttachment"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "QLPreviewReplyAttachment"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "QLPreviewReplyAttachment"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quicklook/documentation/QuickLook": {
      "abstract": [
        {
          "text": "Create previews of files to use inside your app, or perform simple edits on previews.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook",
      "kind": "symbol",
      "role": "collection",
      "title": "Quick Look",
      "type": "topic",
      "url": "/documentation/quicklook"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLFilePreviewRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLFilePreviewRequest"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLFilePreviewRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLFilePreviewRequest"
        }
      ],
      "role": "symbol",
      "title": "QLFilePreviewRequest",
      "type": "topic",
      "url": "/documentation/quicklook/qlfilepreviewrequest"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItem": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewItem"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewItem"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewItem",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewitem"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewProvider": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewProvider"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewProvider"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewProvider",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewprovider"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReply": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewReply"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewReply"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewReply",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewreply"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReplyAttachment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewReplyAttachment"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReplyAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewReplyAttachment"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewReplyAttachment",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewreplyattachment"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReplyAttachment/contentType": {
      "abstract": [
        {
          "text": "The content type of the attachment for an html preview",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22UniformTypeIdentifiers6UTTypeV",
          "text": "UTType"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReplyAttachment/contentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentType"
        }
      ],
      "role": "symbol",
      "title": "contentType",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewreplyattachment/contenttype"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReplyAttachment/data": {
      "abstract": [
        {
          "text": "The data content of an html preview",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReplyAttachment/data",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "data"
        }
      ],
      "role": "symbol",
      "title": "data",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewreplyattachment/data"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReplyAttachment/init(data:contentType:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:22UniformTypeIdentifiers6UTTypeV",
          "text": "UTType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReplyAttachment/init(data:contentType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithData:contentType:"
        }
      ],
      "role": "symbol",
      "title": "init(data:contentType:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewreplyattachment/init(data:contenttype:)"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewingController": {
      "abstract": [
        {
          "text": "For view based previews, the view controller that implements the QLPreviewingController protocol must at least implement one of the two following methods:",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "-[QLPreviewingController preparePreviewOfSearchableItemWithIdentifier:queryString:completionHandler:], to generate previews for Spotlight searchable items.",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "-[QLPreviewingController preparePreviewOfFileAtURL:completionHandler:], to generate previews for file URLs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewingController"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewingController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewingController"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewingController",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewingcontroller"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "QuickLookUI-symbols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklook/documentation/QuickLook/QLFilePreviewRequest",
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewProvider",
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReply",
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItem",
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewingController"
      ],
      "title": "QuickLookUI symbols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReplyAttachment/init(data:contentType:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReplyAttachment/contentType",
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReplyAttachment/data"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "QLPreviewReplyAttachment"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewReplyAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewReplyAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quicklook/documentation/QuickLook"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReplyAttachment/contentType",
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReplyAttachment/data"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReplyAttachment/init(data:contentType:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "QuickLookUI-symbols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quicklook/documentation/QuickLook/QLFilePreviewRequest",
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewProvider",
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewReply",
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItem",
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewingController"
              ],
              "title": "QuickLookUI symbols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "QLPreviewReplyAttachment"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewReplyAttachment~1data/title",
          "value": "data"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewReplyAttachment~1data/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewingController/title",
          "value": "QLPreviewingController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewingController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewingController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewingController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewingController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItem/title",
          "value": "QLPreviewItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewProvider/title",
          "value": "QLPreviewProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLFilePreviewRequest/title",
          "value": "QLFilePreviewRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLFilePreviewRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLFilePreviewRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLFilePreviewRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLFilePreviewRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewReplyAttachment~1init(data:contentType:)/title",
          "value": "initWithData:contentType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewReplyAttachment~1init(data:contentType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithData:contentType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewReply/title",
          "value": "QLPreviewReply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewReply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewReply/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewReplyAttachment/title",
          "value": "QLPreviewReplyAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewReplyAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewReplyAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewReplyAttachment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewReplyAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewReplyAttachment~1contentType/title",
          "value": "contentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewReplyAttachment~1contentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quicklook/qlpreviewreplyattachment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quicklook/qlpreviewreplyattachment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
