{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quicklook/documentation/QuickLook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@QLPreviewItemEditingMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "QLPreviewItemEditingMode"
      }
    ],
    "modules": [
      {
        "name": "Quick Look"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "QLPreviewItemEditingMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "QLPreviewItemEditingMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "QLPreviewItemEditingMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quicklook/documentation/QuickLook": {
      "abstract": [
        {
          "text": "Create previews of files to use inside your app, or perform simple edits on previews.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook",
      "kind": "symbol",
      "role": "collection",
      "title": "Quick Look",
      "type": "topic",
      "url": "/documentation/quicklook"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:didSaveEditedCopyOf:at:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the preview item’s edited content was successfully saved to a copy at the given URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLPreviewController",
          "text": "QLPreviewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSaveEditedCopyOf"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)QLPreviewItem",
          "text": "QLPreviewItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:didSaveEditedCopyOf:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewController:didSaveEditedCopyOfPreviewItem:atURL:"
        }
      ],
      "role": "symbol",
      "title": "previewController(_:didSaveEditedCopyOf:at:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewcontrollerdelegate/previewcontroller(_:didsaveeditedcopyof:at:)"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:didUpdateContentsOf:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the content of a preview was updated successfully.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLPreviewController",
          "text": "QLPreviewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdateContentsOf"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)QLPreviewItem",
          "text": "QLPreviewItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:didUpdateContentsOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewController:didUpdateContentsOfPreviewItem:"
        }
      ],
      "role": "symbol",
      "title": "previewController(_:didUpdateContentsOf:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewcontrollerdelegate/previewcontroller(_:didupdatecontentsof:)"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:editingModeFor:)": {
      "abstract": [
        {
          "text": "Returns a value that indicates how the preview controller handles edits to the content of the previewed file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)QLPreviewController",
          "text": "QLPreviewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "editingModeFor"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)QLPreviewItem",
          "text": "QLPreviewItem"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@QLPreviewItemEditingMode",
          "text": "QLPreviewItemEditingMode"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:editingModeFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewController:editingModeForPreviewItem:"
        }
      ],
      "role": "symbol",
      "title": "previewController(_:editingModeFor:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewcontrollerdelegate/previewcontroller(_:editingmodefor:)"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLPreviewItemEditingMode"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewItemEditingMode"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewItemEditingMode",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewitemeditingmode"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/createCopy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createCopy"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/createCopy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewItemEditingModeCreateCopy"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewItemEditingMode.createCopy",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewitemeditingmode/createcopy"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/disabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disabled"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/disabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewItemEditingModeDisabled"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewItemEditingMode.disabled",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewitemeditingmode/disabled"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewitemeditingmode/init(rawvalue:)"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/updateContents": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateContents"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/updateContents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLPreviewItemEditingModeUpdateContents"
        }
      ],
      "role": "symbol",
      "title": "QLPreviewItemEditingMode.updateContents",
      "type": "topic",
      "url": "/documentation/quicklook/qlpreviewitemeditingmode/updatecontents"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Editing-the-content-of-a-preview",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:editingModeFor:)",
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:didUpdateContentsOf:)",
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:didSaveEditedCopyOf:at:)"
      ],
      "title": "Editing the content of a preview"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/createCopy",
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/disabled",
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/updateContents"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "QLPreviewItemEditingMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemEditingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemEditingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quicklook/documentation/QuickLook"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/createCopy",
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/disabled",
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewItemEditingMode/updateContents"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Editing-the-content-of-a-preview",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:editingModeFor:)",
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:didUpdateContentsOf:)",
                "doc://com.apple.quicklook/documentation/QuickLook/QLPreviewControllerDelegate/previewController(_:didSaveEditedCopyOf:at:)"
              ],
              "title": "Editing the content of a preview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "QLPreviewItemEditingMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:didUpdateContentsOf:)/title",
          "value": "previewController:didUpdateContentsOfPreviewItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:didUpdateContentsOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "previewController:didUpdateContentsOfPreviewItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode~1disabled/title",
          "value": "QLPreviewItemEditingModeDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode~1disabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemEditingModeDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:editingModeFor:)/title",
          "value": "previewController:editingModeForPreviewItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:editingModeFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "previewController:editingModeForPreviewItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode~1updateContents/title",
          "value": "QLPreviewItemEditingModeUpdateContents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode~1updateContents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemEditingModeUpdateContents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:didSaveEditedCopyOf:at:)/title",
          "value": "previewController:didSaveEditedCopyOfPreviewItem:atURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewControllerDelegate~1previewController(_:didSaveEditedCopyOf:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "previewController:didSaveEditedCopyOfPreviewItem:atURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode~1createCopy/title",
          "value": "QLPreviewItemEditingModeCreateCopy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode~1createCopy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemEditingModeCreateCopy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode/title",
          "value": "QLPreviewItemEditingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemEditingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLPreviewItemEditingMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLPreviewItemEditingMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quicklook/qlpreviewitemeditingmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quicklook/qlpreviewitemeditingmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
