{
  "abstract": [
    {
      "text": "Cancels the computation of the thumbnail.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use [QLThumbnailGenerator cancelRequest:] in QuickLookThumbnailing.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quicklook/documentation/QuickLook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCancel(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@QLThumbnailCancel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "QLThumbnailCancel"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@QLThumbnailRef",
        "text": "QLThumbnail"
      },
      {
        "kind": "text",
        "text": "!)"
      }
    ],
    "modules": [
      {
        "name": "Quick Look"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "QLThumbnailCancel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.6",
        "message": "Use [QLThumbnailGenerator cancelRequest:] in QuickLookThumbnailing.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "QLThumbnailCancel(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "QLThumbnailCancel"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "thumbnail"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnail",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@QLThumbnailRef",
              "text": "QLThumbnail"
            },
            {
              "kind": "text",
              "text": "!)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The thumbnail to cancel.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "thumbnail"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailDispatchAsync(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to request the thumbnail, calling this function invokes the completion callback of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailDispatchAsync(_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If you use synchronous mode, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCopyImage(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " returns ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " immediately.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quicklook/documentation/QuickLook": {
      "abstract": [
        {
          "text": "Create previews of files to use inside your app, or perform simple edits on previews.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook",
      "kind": "symbol",
      "role": "collection",
      "title": "Quick Look",
      "type": "topic",
      "url": "/documentation/quicklook"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnail": {
      "abstract": [
        {
          "text": "An opaque reference that represents a thumbnail object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnail"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnail"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnail",
      "type": "topic",
      "url": "/documentation/quicklook/qlthumbnail"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCancel(_:)": {
      "abstract": [
        {
          "text": "Cancels the computation of the thumbnail.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailCancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@QLThumbnailRef",
          "text": "QLThumbnail"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCancel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailCancel"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailCancel(_:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlthumbnailcancel(_:)"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCopyDocumentURL(_:)": {
      "abstract": [
        {
          "text": "Returns the URL of the document that you’re requesting a thumbnail for.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailCopyDocumentURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@QLThumbnailRef",
          "text": "QLThumbnail"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCopyDocumentURL(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailCopyDocumentURL"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailCopyDocumentURL(_:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlthumbnailcopydocumenturl(_:)"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCopyImage(_:)": {
      "abstract": [
        {
          "text": "Returns a thumbnail image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailCopyImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@QLThumbnailRef",
          "text": "QLThumbnail"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCopyImage(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailCopyImage"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailCopyImage(_:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlthumbnailcopyimage(_:)"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCopyOptions(_:)": {
      "abstract": [
        {
          "text": "Returns the options for the requested thumbnail.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailCopyOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@QLThumbnailRef",
          "text": "QLThumbnail"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCopyOptions(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailCopyOptions"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailCopyOptions(_:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlthumbnailcopyoptions(_:)"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCreate(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a thumbnail that’s generated in the background.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@QLThumbnailRef",
          "text": "QLThumbnail"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCreate(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailCreate"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailCreate(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlthumbnailcreate(_:_:_:_:)"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailDispatchAsync(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a thumbnail in the background on the provided background queue.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailDispatchAsync"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@QLThumbnailRef",
          "text": "QLThumbnail"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "!, (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")!)"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailDispatchAsync(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailDispatchAsync"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailDispatchAsync(_:_:_:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlthumbnaildispatchasync(_:_:_:)"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailGetContentRect(_:)": {
      "abstract": [
        {
          "text": "Returns the rectangle of the provided thumbnail image that represents the content of the document.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailGetContentRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@QLThumbnailRef",
          "text": "QLThumbnail"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailGetContentRect(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailGetContentRect"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailGetContentRect(_:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlthumbnailgetcontentrect(_:)"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailGetMaximumSize(_:)": {
      "abstract": [
        {
          "text": "Returns the maximum allowed size for the provided thumbnail image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailGetMaximumSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@QLThumbnailRef",
          "text": "QLThumbnail"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailGetMaximumSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailGetMaximumSize"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailGetMaximumSize(_:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlthumbnailgetmaximumsize(_:)"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the type identifier for the thumbnail’s opaque type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailGetTypeID()",
      "type": "topic",
      "url": "/documentation/quicklook/qlthumbnailgettypeid()"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailImageCreate(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a thumbnail image for the specified file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailImageCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailImageCreate(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailImageCreate"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailImageCreate(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlthumbnailimagecreate(_:_:_:_:)"
    },
    "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailIsCancelled(_:)": {
      "abstract": [
        {
          "text": "Returns whether the creation of the thumbnail was canceled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "QLThumbnailIsCancelled"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@QLThumbnailRef",
          "text": "QLThumbnail"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailIsCancelled(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "QLThumbnailIsCancelled"
        }
      ],
      "role": "symbol",
      "title": "QLThumbnailIsCancelled(_:)",
      "type": "topic",
      "url": "/documentation/quicklook/qlthumbnailiscancelled(_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-thumbnails",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailImageCreate(_:_:_:_:)",
        "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCreate(_:_:_:_:)",
        "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailDispatchAsync(_:_:_:)",
        "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCopyDocumentURL(_:)",
        "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCopyImage(_:)",
        "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCopyOptions(_:)",
        "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailGetContentRect(_:)",
        "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailGetMaximumSize(_:)",
        "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailGetTypeID()",
        "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailIsCancelled(_:)"
      ],
      "title": "Creating thumbnails"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "QLThumbnailCancel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quicklook/documentation/QuickLook"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-thumbnails",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailImageCreate(_:_:_:_:)",
                "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCreate(_:_:_:_:)",
                "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailDispatchAsync(_:_:_:)",
                "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCopyDocumentURL(_:)",
                "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCopyImage(_:)",
                "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailCopyOptions(_:)",
                "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailGetContentRect(_:)",
                "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailGetMaximumSize(_:)",
                "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailGetTypeID()",
                "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnailIsCancelled(_:)"
              ],
              "title": "Creating thumbnails"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "QLThumbnailCancel"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.quicklook/documentation/QuickLook/QLThumbnail",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@QLThumbnailRef",
                    "text": "QLThumbnailRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "thumbnail"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The thumbnail to cancel.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "thumbnail"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use [QLThumbnailGenerator cancelRequest:] in QuickLookThumbnailing.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailDispatchAsync(_:_:_:)/title",
          "value": "QLThumbnailDispatchAsync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailDispatchAsync(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailDispatchAsync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailCancel(_:)/title",
          "value": "QLThumbnailCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailCancel(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnail/title",
          "value": "QLThumbnailRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnail/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailCopyImage(_:)/title",
          "value": "QLThumbnailCopyImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailCopyImage(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailCopyImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailCopyOptions(_:)/title",
          "value": "QLThumbnailCopyOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailCopyOptions(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailCopyOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailCopyDocumentURL(_:)/title",
          "value": "QLThumbnailCopyDocumentURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailCopyDocumentURL(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailCopyDocumentURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailImageCreate(_:_:_:_:)/title",
          "value": "QLThumbnailImageCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailImageCreate(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailImageCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailGetContentRect(_:)/title",
          "value": "QLThumbnailGetContentRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailGetContentRect(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGetContentRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailGetMaximumSize(_:)/title",
          "value": "QLThumbnailGetMaximumSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailGetMaximumSize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGetMaximumSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailCreate(_:_:_:_:)/title",
          "value": "QLThumbnailCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailCreate(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailGetTypeID()/title",
          "value": "QLThumbnailGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailIsCancelled(_:)/title",
          "value": "QLThumbnailIsCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quicklook~1documentation~1QuickLook~1QLThumbnailIsCancelled(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "QLThumbnailIsCancelled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quicklook/qlthumbnailcancel(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quicklook/qlthumbnailcancel(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
