{
  "abstract": [
    {
      "text": "A binary outcome for the task, like true or false.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.classkit/documentation/ClassKit",
        "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability",
        "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/binary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CLSProgressReportingCapabilityKind@CLSProgressReportingCapabilityKindBinary",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "binary"
      }
    ],
    "modules": [
      {
        "name": "ClassKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLSProgressReportingCapabilityKindBinary"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CLSProgressReportingCapability.Kind.binary"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "binary"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Add this capability to indicate that a context reports a binary condition at the end of a task, like pass or fail, using a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.classkit/documentation/ClassKit": {
      "abstract": [
        {
          "text": "Enable teachers to assign activities from your app’s content and to view student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClassKit",
      "type": "topic",
      "url": "/documentation/classkit"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryItem": {
      "abstract": [
        {
          "text": "Activity information that is true or false, pass or fail, yes or no.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSBinaryItem"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSBinaryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSBinaryItem"
        }
      ],
      "role": "symbol",
      "title": "CLSBinaryItem",
      "type": "topic",
      "url": "/documentation/classkit/clsbinaryitem"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability": {
      "abstract": [
        {
          "text": "A progress reporting capability supported by a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSProgressReportingCapability"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSProgressReportingCapability"
        }
      ],
      "role": "symbol",
      "title": "CLSProgressReportingCapability",
      "type": "topic",
      "url": "/documentation/classkit/clsprogressreportingcapability"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum": {
      "abstract": [
        {
          "text": "The available kinds of progress reporting that a context can perform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Kind"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Kind"
        }
      ],
      "role": "symbol",
      "title": "CLSProgressReportingCapability.Kind",
      "type": "topic",
      "url": "/documentation/classkit/clsprogressreportingcapability/kind-swift.enum"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/binary": {
      "abstract": [
        {
          "text": "A binary outcome for the task, like true or false.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "binary"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/binary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSProgressReportingCapabilityKindBinary"
        }
      ],
      "role": "symbol",
      "title": "CLSProgressReportingCapability.Kind.binary",
      "type": "topic",
      "url": "/documentation/classkit/clsprogressreportingcapability/kind-swift.enum/binary"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/duration": {
      "abstract": [
        {
          "text": "Time spent performing the task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/duration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSProgressReportingCapabilityKindDuration"
        }
      ],
      "role": "symbol",
      "title": "CLSProgressReportingCapability.Kind.duration",
      "type": "topic",
      "url": "/documentation/classkit/clsprogressreportingcapability/kind-swift.enum/duration"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/percent": {
      "abstract": [
        {
          "text": "The percentage of the total task that has been completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "percent"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/percent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSProgressReportingCapabilityKindPercent"
        }
      ],
      "role": "symbol",
      "title": "CLSProgressReportingCapability.Kind.percent",
      "type": "topic",
      "url": "/documentation/classkit/clsprogressreportingcapability/kind-swift.enum/percent"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/quantity": {
      "abstract": [
        {
          "text": "A discrete value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quantity"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/quantity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSProgressReportingCapabilityKindQuantity"
        }
      ],
      "role": "symbol",
      "title": "CLSProgressReportingCapability.Kind.quantity",
      "type": "topic",
      "url": "/documentation/classkit/clsprogressreportingcapability/kind-swift.enum/quantity"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/score": {
      "abstract": [
        {
          "text": "A score.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "score"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/score",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSProgressReportingCapabilityKindScore"
        }
      ],
      "role": "symbol",
      "title": "CLSProgressReportingCapability.Kind.score",
      "type": "topic",
      "url": "/documentation/classkit/clsprogressreportingcapability/kind-swift.enum/score"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reporting-Capabilities",
      "generated": true,
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/duration",
        "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/percent",
        "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/quantity",
        "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/score"
      ],
      "title": "Reporting Capabilities"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLSProgressReportingCapabilityKindBinary"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSProgressReportingCapabilityKindBinary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.classkit/documentation/ClassKit",
                "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reporting-Capabilities",
              "generated": true,
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/duration",
                "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/percent",
                "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/quantity",
                "doc://com.apple.classkit/documentation/ClassKit/CLSProgressReportingCapability/Kind-swift.enum/score"
              ],
              "title": "Reporting Capabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CLSProgressReportingCapabilityKindBinary"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability~1Kind-swift.enum~1score/title",
          "value": "CLSProgressReportingCapabilityKindScore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability~1Kind-swift.enum~1score/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSProgressReportingCapabilityKindScore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryItem/title",
          "value": "CLSBinaryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSBinaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSBinaryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSBinaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability/title",
          "value": "CLSProgressReportingCapability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSProgressReportingCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSProgressReportingCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability~1Kind-swift.enum~1duration/title",
          "value": "CLSProgressReportingCapabilityKindDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability~1Kind-swift.enum~1duration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSProgressReportingCapabilityKindDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability~1Kind-swift.enum/title",
          "value": "CLSProgressReportingCapabilityKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability~1Kind-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSProgressReportingCapabilityKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability~1Kind-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSProgressReportingCapabilityKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability~1Kind-swift.enum~1quantity/title",
          "value": "CLSProgressReportingCapabilityKindQuantity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability~1Kind-swift.enum~1quantity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSProgressReportingCapabilityKindQuantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability~1Kind-swift.enum~1binary/title",
          "value": "CLSProgressReportingCapabilityKindBinary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability~1Kind-swift.enum~1binary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSProgressReportingCapabilityKindBinary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability~1Kind-swift.enum~1percent/title",
          "value": "CLSProgressReportingCapabilityKindPercent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSProgressReportingCapability~1Kind-swift.enum~1percent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSProgressReportingCapabilityKindPercent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/classkit/clsprogressreportingcapability/kind-swift.enum/binary"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/classkit/clsprogressreportingcapability/kind-swift.enum/binary"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
