{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WKWaterResistanceRating"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKWaterResistanceRating/wr100"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKWaterResistanceRating@WKWaterResistanceRatingWR100",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "wr100"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKWaterResistanceRatingWR100"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WKWaterResistanceRating.wr100"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "wr100"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKWaterResistanceRating": {
      "abstract": [
        {
          "text": "Values indicating the water-resistance rating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKWaterResistanceRating"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKWaterResistanceRating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWaterResistanceRating"
        }
      ],
      "role": "symbol",
      "title": "WKWaterResistanceRating",
      "type": "topic",
      "url": "/documentation/watchkit/wkwaterresistancerating"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKWaterResistanceRating/ipx7": {
      "abstract": [
        {
          "text": "A water-resistance rating of IPX7.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ipx7"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKWaterResistanceRating/ipx7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWaterResistanceRatingIPX7"
        }
      ],
      "role": "symbol",
      "title": "WKWaterResistanceRating.ipx7",
      "type": "topic",
      "url": "/documentation/watchkit/wkwaterresistancerating/ipx7"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKWaterResistanceRating/wr100": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wr100"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKWaterResistanceRating/wr100",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWaterResistanceRatingWR100"
        }
      ],
      "role": "symbol",
      "title": "WKWaterResistanceRating.wr100",
      "type": "topic",
      "url": "/documentation/watchkit/wkwaterresistancerating/wr100"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKWaterResistanceRating/wr50": {
      "abstract": [
        {
          "text": "A water-resistance rating of 50 meters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wr50"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKWaterResistanceRating/wr50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKWaterResistanceRatingWR50"
        }
      ],
      "role": "symbol",
      "title": "WKWaterResistanceRating.wr50",
      "type": "topic",
      "url": "/documentation/watchkit/wkwaterresistancerating/wr50"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKWaterResistanceRating/ipx7",
        "doc://com.apple.watchkit/documentation/WatchKit/WKWaterResistanceRating/wr50"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKWaterResistanceRatingWR100"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWaterResistanceRatingWR100"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit",
                "doc://com.apple.watchkit/documentation/WatchKit/WKWaterResistanceRating"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKWaterResistanceRating/ipx7",
                "doc://com.apple.watchkit/documentation/WatchKit/WKWaterResistanceRating/wr50"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WKWaterResistanceRatingWR100"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKWaterResistanceRating~1wr100/title",
          "value": "WKWaterResistanceRatingWR100"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKWaterResistanceRating~1wr100/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWaterResistanceRatingWR100"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKWaterResistanceRating/title",
          "value": "WKWaterResistanceRating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKWaterResistanceRating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWaterResistanceRating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKWaterResistanceRating/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWaterResistanceRating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKWaterResistanceRating~1ipx7/title",
          "value": "WKWaterResistanceRatingIPX7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKWaterResistanceRating~1ipx7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWaterResistanceRatingIPX7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKWaterResistanceRating~1wr50/title",
          "value": "WKWaterResistanceRatingWR50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKWaterResistanceRating~1wr50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKWaterResistanceRatingWR50"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkwaterresistancerating/wr100"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkwaterresistancerating/wr100"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
