{
  "abstract": [
    {
      "text": "The type for multidimensional array features and feature values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML",
        "doc://com.apple.coreml/documentation/CoreML/MLFeatureType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/multiArray"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLFeatureType@MLFeatureTypeMultiArray",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "multiArray"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLFeatureTypeMultiArray"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MLFeatureType.multiArray"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "multiArray"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureType": {
      "abstract": [
        {
          "text": "The possible types for feature values, input features, and output features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLFeatureType"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLFeatureType"
        }
      ],
      "role": "symbol",
      "title": "MLFeatureType",
      "type": "topic",
      "url": "/documentation/coreml/mlfeaturetype"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/dictionary": {
      "abstract": [
        {
          "text": "The type for dictionary features and feature values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dictionary"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLFeatureTypeDictionary"
        }
      ],
      "role": "symbol",
      "title": "MLFeatureType.dictionary",
      "type": "topic",
      "url": "/documentation/coreml/mlfeaturetype/dictionary"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/double": {
      "abstract": [
        {
          "text": "The type for double features and feature values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "double"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLFeatureTypeDouble"
        }
      ],
      "role": "symbol",
      "title": "MLFeatureType.double",
      "type": "topic",
      "url": "/documentation/coreml/mlfeaturetype/double"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/image": {
      "abstract": [
        {
          "text": "The type for image features and feature values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLFeatureTypeImage"
        }
      ],
      "role": "symbol",
      "title": "MLFeatureType.image",
      "type": "topic",
      "url": "/documentation/coreml/mlfeaturetype/image"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/int64": {
      "abstract": [
        {
          "text": "The type for integer features and feature values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "int64"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/int64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLFeatureTypeInt64"
        }
      ],
      "role": "symbol",
      "title": "MLFeatureType.int64",
      "type": "topic",
      "url": "/documentation/coreml/mlfeaturetype/int64"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/invalid": {
      "abstract": [
        {
          "text": "The type for invalid feature values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalid"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/invalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLFeatureTypeInvalid"
        }
      ],
      "role": "symbol",
      "title": "MLFeatureType.invalid",
      "type": "topic",
      "url": "/documentation/coreml/mlfeaturetype/invalid"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/multiArray": {
      "abstract": [
        {
          "text": "The type for multidimensional array features and feature values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiArray"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/multiArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLFeatureTypeMultiArray"
        }
      ],
      "role": "symbol",
      "title": "MLFeatureType.multiArray",
      "type": "topic",
      "url": "/documentation/coreml/mlfeaturetype/multiarray"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/sequence": {
      "abstract": [
        {
          "text": "The type for sequence features and feature values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sequence"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/sequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLFeatureTypeSequence"
        }
      ],
      "role": "symbol",
      "title": "MLFeatureType.sequence",
      "type": "topic",
      "url": "/documentation/coreml/mlfeaturetype/sequence"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/string": {
      "abstract": [
        {
          "text": "The type for string features and feature values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/string",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLFeatureTypeString"
        }
      ],
      "role": "symbol",
      "title": "MLFeatureType.string",
      "type": "topic",
      "url": "/documentation/coreml/mlfeaturetype/string"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/int64",
        "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/double",
        "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/image",
        "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/string",
        "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/dictionary",
        "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/sequence",
        "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/invalid"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLFeatureTypeMultiArray"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureTypeMultiArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreml/documentation/CoreML",
                "doc://com.apple.coreml/documentation/CoreML/MLFeatureType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/int64",
                "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/double",
                "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/image",
                "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/string",
                "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/dictionary",
                "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/sequence",
                "doc://com.apple.coreml/documentation/CoreML/MLFeatureType/invalid"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MLFeatureTypeMultiArray"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType~1string/title",
          "value": "MLFeatureTypeString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType~1string/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureTypeString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType/title",
          "value": "MLFeatureType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType~1int64/title",
          "value": "MLFeatureTypeInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType~1int64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureTypeInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType~1sequence/title",
          "value": "MLFeatureTypeSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType~1sequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureTypeSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType~1invalid/title",
          "value": "MLFeatureTypeInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType~1invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureTypeInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType~1dictionary/title",
          "value": "MLFeatureTypeDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType~1dictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureTypeDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType~1multiArray/title",
          "value": "MLFeatureTypeMultiArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType~1multiArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureTypeMultiArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType~1image/title",
          "value": "MLFeatureTypeImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType~1image/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureTypeImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType~1double/title",
          "value": "MLFeatureTypeDouble"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLFeatureType~1double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLFeatureTypeDouble"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlfeaturetype/multiarray"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreml/mlfeaturetype/multiarray"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
