{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIInteraction/didMove(to:)"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"UIKit"}],"symbolKind":"method","platforms":[{"introducedAt":"11.0","beta":false,"deprecated":false,"unavailable":false,"name":"iOS"},{"introducedAt":"11.0","beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS"},{"introducedAt":"13.1","beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst"},{"introducedAt":"13.0","beta":false,"deprecated":false,"unavailable":false,"name":"tvOS"},{"introducedAt":"1.0","beta":false,"deprecated":false,"unavailable":false,"name":"visionOS"}],"role":"symbol","externalID":"c:objc(pl)UIInteraction(im)didMoveToView:","required":true,"navigatorTitle":[{"text":"didMoveToView:","kind":"identifier"}],"title":"didMove(to:)"},"seeAlsoSections":[{"anchor":"Tracking-the-Movements","title":"Tracking the Movements","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIInteraction/willMove(to:)"],"generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIInteraction"]]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Tells the interaction that a view added or removed it from the view’s interactions array."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"view","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView"},{"text":"?)","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The view that owns and contains the interaction in its interaction array. If the view is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", the interaction’s owner removed the interaction from its interactions array.","type":"text"}]}],"name":"view"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiinteraction/didmove(to:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiinteraction/didmove(to:)"]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIInteraction/didMove(to:)":{"url":"/documentation/uikit/uiinteraction/didmove(to:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIInteraction/didMove(to:)","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"didMoveToView:"}],"kind":"symbol","type":"topic","title":"didMove(to:)","abstract":[{"type":"text","text":"Tells the interaction that a view added or removed it from the view’s interactions array."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"?)"}]},"doc://com.apple.uikit/documentation/UIKit/UIInteraction":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIInteraction"}],"role":"symbol","title":"UIInteraction","url":"/documentation/uikit/uiinteraction","identifier":"doc://com.apple.uikit/documentation/UIKit/UIInteraction","navigatorTitle":[{"kind":"identifier","text":"UIInteraction"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The protocol that an interaction implements to access the view that owns it."}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIView":{"title":"UIView","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","abstract":[{"text":"An object that manages the content for a rectangular area on the screen.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"UIView","kind":"identifier"}],"url":"/documentation/uikit/uiview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIView","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIInteraction/willMove(to:)":{"url":"/documentation/uikit/uiinteraction/willmove(to:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIInteraction/willMove(to:)","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"willMoveToView:"}],"kind":"symbol","type":"topic","title":"willMove(to:)","abstract":[{"type":"text","text":"Tells the interaction that a view will add or remove it from the view’s interactions array."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willMove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"?)"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"name":"iOS","deprecated":false,"beta":false,"introducedAt":"11.0"},{"unavailable":false,"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"11.0"},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"13.1"},{"unavailable":false,"name":"tvOS","deprecated":false,"beta":false,"introducedAt":"13.0"},{"unavailable":false,"name":"visionOS","deprecated":false,"beta":false,"introducedAt":"1.0"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"didMoveToView:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToView:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIInteraction"]]}},{"path":"/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Tracking the Movements","generated":true,"anchor":"Tracking-the-Movements","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIInteraction/willMove(to:)"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"didMoveToView:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIView","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"view"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"view","content":[{"inlineContent":[{"text":"The view that owns and contains the interaction in its interaction array. If the view is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":", the interaction’s owner removed the interaction from its interactions array.","type":"text"}],"type":"paragraph"}]}]},"path":"/primaryContentSections/1"},{"value":"didMoveToView:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction~1didMove(to:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToView:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction~1didMove(to:)/fragments"},{"value":"UIInteraction","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/title"},{"value":[{"kind":"identifier","text":"UIInteraction"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/fragments"},{"value":[{"text":"UIInteraction","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/navigatorTitle"},{"value":"UIView","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title"},{"value":[{"text":"UIView","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments"},{"value":[{"kind":"identifier","text":"UIView"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle"},{"value":"willMoveToView:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction~1willMove(to:)/title"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction~1willMove(to:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willMoveToView:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}