{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIInteraction"]]},"abstract":[{"text":"The view that owns the interaction.","type":"text"}],"metadata":{"title":"view","platforms":[{"beta":false,"introducedAt":"11.0","name":"iOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"11.0","name":"iPadOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"13.0","name":"tvOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"1.0","name":"visionOS","deprecated":false,"unavailable":false}],"modules":[{"name":"UIKit"}],"symbolKind":"property","roleHeading":"Instance Property","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"view"}],"externalID":"c:objc(pl)UIInteraction(py)view"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIInteraction/view","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiinteraction/view"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiinteraction/view"]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIInteraction":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIInteraction"}],"role":"symbol","title":"UIInteraction","url":"/documentation/uikit/uiinteraction","identifier":"doc://com.apple.uikit/documentation/UIKit/UIInteraction","navigatorTitle":[{"kind":"identifier","text":"UIInteraction"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The protocol that an interaction implements to access the view that owns it."}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIInteraction/view":{"type":"topic","title":"view","url":"/documentation/uikit/uiinteraction/view","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"?"}],"required":true,"kind":"symbol","abstract":[{"text":"The view that owns the interaction.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"view"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIInteraction/view"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIView":{"title":"UIView","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","abstract":[{"text":"An object that manages the content for a rectangular area on the screen.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"UIView","kind":"identifier"}],"url":"/documentation/uikit/uiview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":false,"introducedAt":"11.0","name":"iOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"11.0","name":"iPadOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"13.1","name":"Mac Catalyst","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"13.0","name":"tvOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"1.0","name":"visionOS","beta":false}],"op":"replace","path":"/metadata/platforms"},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"view"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"view","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIInteraction"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"view"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/title","op":"replace","value":"UIInteraction"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/fragments","op":"replace","value":[{"text":"UIInteraction","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/navigatorTitle","op":"replace","value":[{"text":"UIInteraction","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction~1view/title","op":"replace","value":"view"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction~1view/fragments","op":"replace","value":[{"text":"view","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title","op":"replace","value":"UIView"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments","op":"replace","value":[{"text":"UIView","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIView"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}