{
  "abstract": [
    {
      "text": "Configure your server to generate reader tokens to prepare a device for mobile document reading.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ProximityReader/documentation/ProximityReader"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ProximityReader/documentation/ProximityReader/generating-reader-tokens-for-the-verifier-api"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "ProximityReader"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Generating reader tokens for the Verifier API"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Verifier API supports displaying your brand’s name and logo in the reader UI during a document request.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To show your brand’s name and logo, your app needs to pass a reader token as an argument to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.ProximityReader/documentation/ProximityReader/MobileDocumentReader/prepare(using:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Reader tokens are JSON Web Tokens (JWT) generated by your server containing your brand ID, key ID, and a reader instance identifier. You can obtain a brand ID and key ID by enrolling with ",
              "type": "text"
            },
            {
              "identifier": "https://register.apple.com/services/login?returnTo=/signin/id-verifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The person who enrolls your organization with ",
              "type": "text"
            },
            {
              "identifier": "https://register.apple.com/services/login?returnTo=/signin/id-verifier",
              "isActive": true,
              "overridingTitle": "Apple Business Register",
              "overridingTitleInlineContent": [
                {
                  "text": "Apple Business Register",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " will need to enter your company’s business name, and upload your brand’s logo and a public signing key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Generate-a-reader-token-on-your-server",
          "level": 2,
          "text": "Generate a reader token on your server",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You need to link a reader token to the device that you’ll use to read documents, as well as your brand information from Apple Business Register. To generate a reader token:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Fetch the device’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.ProximityReader/documentation/ProximityReader/MobileDocumentReader/Configuration-swift.struct/readerInstanceIdentifier",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Send the reader instance identifier to your server.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "On your server, create a JWT containing the device’s reader instance identifier, along with your brand and key IDs from ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://register.apple.com/services/login?returnTo=/signin/id-verifier",
                      "isActive": true,
                      "overridingTitle": "Apple Business Register",
                      "overridingTitleInlineContent": [
                        {
                          "text": "Apple Business Register",
                          "type": "text"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Sign the JWT with your server’s private signing key and return the token to your app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "After creating the reader token, confirm the validity of the token authorization by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.ProximityReader/documentation/ProximityReader/MobileDocumentReader/prepare(using:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If the method returns successfully, the framework returns a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.ProximityReader/documentation/ProximityReader/MobileDocumentReaderSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and the device is ready to read mobile documents. After using a reader token to prepare a reader device, your app can cache and reuse it for up to 48 hours.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A JWT has two sections, a header and a payload. The header describes the token and the cryptographic operations applied to the payload. The payload contains a set of cryptographically signed claims.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Construct a token with these fields in the header:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The algorithm you use to sign the token. Use the ES-256 algorithm to sign your token.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "alg",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A key identifier that represents your server’s signing key. You can obtain this value from Apple Business Register.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "kid",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A type parameter that you set to ",
                        "type": "text"
                      },
                      {
                        "code": "JWT",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "typ",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "In the payload section of the token, include the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The audience of the token. Set this value to ",
                        "type": "text"
                      },
                      {
                        "code": "apple-identityservices-v1",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "aud",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The issuer of the token. This is the Brand ID that you obtain from Apple Business Register.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "iss",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The subject of the token. This is the reader instance identifier obtained from your app.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "sub",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The Issued At registered claim key. The value of this claim indicates the token creation time, in terms of the number of seconds since UNIX Epoch, in UTC.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "iat",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The Expiration Time registered claim key. The value of this claim indicates when the token expires, in terms of the number of seconds since UNIX Epoch, in UTC. This must be set to a value after and no later than 5 minutes after the value of ",
                        "type": "text"
                      },
                      {
                        "code": "iat",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "exp",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "When decoded, a token for use with the Verifier API has the following format:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "{",
            "    \"alg\": \"ES256\",",
            "    \"kid\": \"ABCDEFGHIJ\",",
            "    \"typ\": \"JWT\"",
            "}",
            "{",
            "    \"aud\": \"apple-identityservices-v1\",",
            "    \"iss\": \"KLMNOPQRST\",",
            "    \"sub\": \"UVWXYZ1234\",",
            "    \"iat\": 1685980800,",
            "    \"exp\": 1685981100",
            "}"
          ],
          "syntax": "json",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To learn more about JWT, see the ",
              "type": "text"
            },
            {
              "identifier": "https://tools.ietf.org/html/rfc7519",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You can find a collection of libraries for generating signed tokens at ",
              "type": "text"
            },
            {
              "identifier": "https://jwt.io",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.ProximityReader/documentation/ProximityReader": {
      "abstract": [
        {
          "text": "Read contactless physical and digital wallet cards using your iPhone.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ProximityReader/documentation/ProximityReader",
      "kind": "symbol",
      "role": "collection",
      "title": "ProximityReader",
      "type": "topic",
      "url": "/documentation/proximityreader"
    },
    "doc://com.apple.ProximityReader/documentation/ProximityReader/MobileDocumentReader": {
      "abstract": [
        {
          "text": "An object for configuring mobile document reading on the current device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MobileDocumentReader"
        }
      ],
      "identifier": "doc://com.apple.ProximityReader/documentation/ProximityReader/MobileDocumentReader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MobileDocumentReader"
        }
      ],
      "role": "symbol",
      "title": "MobileDocumentReader",
      "type": "topic",
      "url": "/documentation/proximityreader/mobiledocumentreader"
    },
    "doc://com.apple.ProximityReader/documentation/ProximityReader/MobileDocumentReader/Configuration-swift.struct/readerInstanceIdentifier": {
      "abstract": [
        {
          "text": "The unique identifier for the mobile document reader instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readerInstanceIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.ProximityReader/documentation/ProximityReader/MobileDocumentReader/Configuration-swift.struct/readerInstanceIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "readerInstanceIdentifier",
      "type": "topic",
      "url": "/documentation/proximityreader/mobiledocumentreader/configuration-swift.struct/readerinstanceidentifier"
    },
    "doc://com.apple.ProximityReader/documentation/ProximityReader/MobileDocumentReader/prepare(using:)": {
      "abstract": [
        {
          "text": "Configures the device to read mobile documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepare"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15ProximityReader014MobileDocumentB0C",
          "text": "MobileDocumentReader"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15ProximityReader014MobileDocumentB0C5TokenV",
          "text": "Token"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15ProximityReader014MobileDocumentB7SessionC",
          "text": "MobileDocumentReaderSession"
        }
      ],
      "identifier": "doc://com.apple.ProximityReader/documentation/ProximityReader/MobileDocumentReader/prepare(using:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "prepare(using:)",
      "type": "topic",
      "url": "/documentation/proximityreader/mobiledocumentreader/prepare(using:)"
    },
    "doc://com.apple.ProximityReader/documentation/ProximityReader/MobileDocumentReaderSession": {
      "abstract": [
        {
          "text": "The object you use to start reading a mobile document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MobileDocumentReaderSession"
        }
      ],
      "identifier": "doc://com.apple.ProximityReader/documentation/ProximityReader/MobileDocumentReaderSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MobileDocumentReaderSession"
        }
      ],
      "role": "symbol",
      "title": "MobileDocumentReaderSession",
      "type": "topic",
      "url": "/documentation/proximityreader/mobiledocumentreadersession"
    },
    "doc://com.apple.ProximityReader/documentation/ProximityReader/adopting-the-verifier-api-in-your-iphone-app": {
      "abstract": [
        {
          "text": "Configure and test ID Verifier support in your app for reading mobile documents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ProximityReader/documentation/ProximityReader/adopting-the-verifier-api-in-your-iphone-app",
      "kind": "article",
      "role": "article",
      "title": "Adopting the Verifier API in your iPhone app",
      "type": "topic",
      "url": "/documentation/proximityreader/adopting-the-verifier-api-in-your-iphone-app"
    },
    "doc://com.apple.ProximityReader/documentation/ProximityReader/checking-ids-with-the-verifier-api": {
      "abstract": [
        {
          "text": "Read and verify mobile driver’s license information without any additional hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ProximityReader/documentation/ProximityReader/checking-ids-with-the-verifier-api",
      "kind": "article",
      "role": "sampleCode",
      "title": "Checking IDs with the Verifier API",
      "type": "topic",
      "url": "/documentation/proximityreader/checking-ids-with-the-verifier-api"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://jwt.io": {
      "identifier": "https://jwt.io",
      "title": "JWT.io",
      "titleInlineContent": [
        {
          "text": "JWT.io",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://jwt.io"
    },
    "https://register.apple.com/services/login?returnTo=/signin/id-verifier": {
      "identifier": "https://register.apple.com/services/login?returnTo=/signin/id-verifier",
      "title": "Apple Business Register",
      "titleInlineContent": [
        {
          "text": "Apple Business Register",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://register.apple.com/services/login?returnTo=/signin/id-verifier"
    },
    "https://tools.ietf.org/html/rfc7519": {
      "identifier": "https://tools.ietf.org/html/rfc7519",
      "title": "JSON Web Token (JWT) specification",
      "titleInlineContent": [
        {
          "text": "JSON Web Token (JWT) specification",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://tools.ietf.org/html/rfc7519"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Mobile-document-reader",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ProximityReader/documentation/ProximityReader/adopting-the-verifier-api-in-your-iphone-app",
        "doc://com.apple.ProximityReader/documentation/ProximityReader/checking-ids-with-the-verifier-api",
        "doc://com.apple.ProximityReader/documentation/ProximityReader/MobileDocumentReader",
        "doc://com.apple.ProximityReader/documentation/ProximityReader/MobileDocumentReaderSession"
      ],
      "title": "Mobile document reader"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Mobile-document-reader",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ProximityReader/documentation/ProximityReader/adopting-the-verifier-api-in-your-iphone-app"
              ],
              "title": "Mobile document reader"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/proximityreader/generating-reader-tokens-for-the-verifier-api"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/proximityreader/generating-reader-tokens-for-the-verifier-api"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
