{
  "abstract": [
    {
      "text": "The app’s role with respect to the document type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/CFBundleTypeRole"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.CFBundleDocumentTypes.CFBundleTypeRole",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CFBundleTypeRole"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "CFBundleTypeRole"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Role",
        "name": "CFBundleTypeRole",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    },
    {
      "kind": "possibleValues",
      "title": "Possible Values",
      "values": [
        {
          "content": [],
          "name": "Editor"
        },
        {
          "content": [],
          "name": "Viewer"
        },
        {
          "content": [],
          "name": "Shell"
        },
        {
          "content": [],
          "name": "QLGenerator"
        },
        {
          "content": [],
          "name": "None"
        }
      ]
    },
    {
      "attributes": [
        {
          "kind": "default",
          "value": "None"
        }
      ],
      "kind": "attributes",
      "title": "Attributes"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes": {
      "abstract": [
        {
          "text": "The document types supported by the bundle.",
          "type": "text"
        }
      ],
      "ideTitle": "Document types",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes",
      "kind": "symbol",
      "name": "CFBundleDocumentTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleDocumentTypes"
        }
      ],
      "role": "symbol",
      "title": "CFBundleDocumentTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundledocumenttypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/CFBundleTypeIconFile": {
      "abstract": [
        {
          "text": "The icon to associate with the document type.",
          "type": "text"
        }
      ],
      "ideTitle": "Icon File Name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/CFBundleTypeIconFile",
      "kind": "symbol",
      "name": "CFBundleTypeIconFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleTypeIconFile"
        }
      ],
      "role": "symbol",
      "title": "CFBundleTypeIconFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundledocumenttypes/cfbundletypeiconfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/CFBundleTypeName": {
      "abstract": [
        {
          "text": "The abstract name for the document type.",
          "type": "text"
        }
      ],
      "ideTitle": "Document Type Name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/CFBundleTypeName",
      "kind": "symbol",
      "name": "CFBundleTypeName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleTypeName"
        }
      ],
      "role": "symbol",
      "title": "CFBundleTypeName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundledocumenttypes/cfbundletypename"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/CFBundleTypeRole": {
      "abstract": [
        {
          "text": "The app’s role with respect to the document type.",
          "type": "text"
        }
      ],
      "ideTitle": "Role",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/CFBundleTypeRole",
      "kind": "symbol",
      "name": "CFBundleTypeRole",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CFBundleTypeRole"
        }
      ],
      "role": "symbol",
      "title": "CFBundleTypeRole",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundledocumenttypes/cfbundletyperole"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/LSHandlerRank": {
      "abstract": [
        {
          "text": "The ranking of this app among apps that declare themselves as editors or viewers of the given file type.",
          "type": "text"
        }
      ],
      "ideTitle": "Handler rank",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/LSHandlerRank",
      "kind": "symbol",
      "name": "LSHandlerRank",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSHandlerRank"
        }
      ],
      "role": "symbol",
      "title": "LSHandlerRank",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundledocumenttypes/lshandlerrank"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/LSItemContentTypes": {
      "abstract": [
        {
          "text": "The document file types the app supports.",
          "type": "text"
        }
      ],
      "ideTitle": "Document Content Type UTIs",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/LSItemContentTypes",
      "kind": "symbol",
      "name": "LSItemContentTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSItemContentTypes"
        }
      ],
      "role": "symbol",
      "title": "LSItemContentTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundledocumenttypes/lsitemcontenttypes"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/LSTypeIsPackage": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the document is distributed as a bundle.",
          "type": "text"
        }
      ],
      "ideTitle": "Document is a package or bundle",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/LSTypeIsPackage",
      "kind": "symbol",
      "name": "LSTypeIsPackage",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LSTypeIsPackage"
        }
      ],
      "role": "symbol",
      "title": "LSTypeIsPackage",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundledocumenttypes/lstypeispackage"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/NSDocumentClass": {
      "abstract": [
        {
          "text": "The subclass used to create instances of this document.",
          "type": "text"
        }
      ],
      "ideTitle": "Cocoa NSDocument Class",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/NSDocumentClass",
      "kind": "symbol",
      "name": "NSDocumentClass",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDocumentClass"
        }
      ],
      "role": "symbol",
      "title": "NSDocumentClass",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundledocumenttypes/nsdocumentclass"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/NSExportableTypes": {
      "abstract": [
        {
          "text": "The file types that this document can be exported to.",
          "type": "text"
        }
      ],
      "ideTitle": "Exportable Type UTIs",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/NSExportableTypes",
      "kind": "symbol",
      "name": "NSExportableTypes",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExportableTypes"
        }
      ],
      "role": "symbol",
      "title": "NSExportableTypes",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/cfbundledocumenttypes/nsexportabletypes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Property-List-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/CFBundleTypeIconFile",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/CFBundleTypeName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/LSHandlerRank",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/LSItemContentTypes",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/LSTypeIsPackage",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/NSDocumentClass",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/NSExportableTypes"
      ],
      "title": "Property List Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CFBundleTypeRole"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleTypeRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Property-List-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/CFBundleTypeIconFile",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/CFBundleTypeName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/LSHandlerRank",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/LSItemContentTypes",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/LSTypeIsPackage",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/NSDocumentClass",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/NSExportableTypes"
              ],
              "title": "Property List Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes~1LSTypeIsPackage/title",
          "value": "LSTypeIsPackage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes~1LSTypeIsPackage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSTypeIsPackage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes~1CFBundleTypeIconFile/title",
          "value": "CFBundleTypeIconFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes~1CFBundleTypeIconFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleTypeIconFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes~1LSItemContentTypes/title",
          "value": "LSItemContentTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes~1LSItemContentTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSItemContentTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes/title",
          "value": "CFBundleDocumentTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleDocumentTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes~1CFBundleTypeRole/title",
          "value": "CFBundleTypeRole"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes~1CFBundleTypeRole/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleTypeRole"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes~1LSHandlerRank/title",
          "value": "LSHandlerRank"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes~1LSHandlerRank/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LSHandlerRank"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes~1CFBundleTypeName/title",
          "value": "CFBundleTypeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes~1CFBundleTypeName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CFBundleTypeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes~1NSDocumentClass/title",
          "value": "NSDocumentClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes~1NSDocumentClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocumentClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes~1NSExportableTypes/title",
          "value": "NSExportableTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1CFBundleDocumentTypes~1NSExportableTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExportableTypes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/cfbundledocumenttypes/cfbundletyperole"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/cfbundledocumenttypes/cfbundletyperole"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
