{
  "abstract": [
    {
      "text": "The printer supports printing larger than the ISO A3 size.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIPrinter",
        "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/largeFormat"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIPrinterJobTypes@UIPrinterJobTypeLargeFormat",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "largeFormat"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIPrinter",
        "text": "UIPrinter"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIPrinterJobTypes",
        "text": "JobTypes"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIPrinterJobTypeLargeFormat"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "largeFormat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "largeFormat"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinter",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIPrinter",
              "text": "UIPrinter"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIPrinterJobTypes",
              "text": "JobTypes"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinter": {
      "abstract": [
        {
          "text": "A printer on the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrinter"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrinter"
        }
      ],
      "role": "symbol",
      "title": "UIPrinter",
      "type": "topic",
      "url": "/documentation/uikit/uiprinter"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes": {
      "abstract": [
        {
          "text": "Constants that indicate the types of jobs that the printer supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JobTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JobTypes"
        }
      ],
      "role": "symbol",
      "title": "UIPrinter.JobTypes",
      "type": "topic",
      "url": "/documentation/uikit/uiprinter/jobtypes"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/document": {
      "abstract": [
        {
          "text": "The printer supports standard document printing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "document"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinter",
          "text": "UIPrinter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPrinterJobTypes",
          "text": "JobTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/document",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrinterJobTypeDocument"
        }
      ],
      "role": "symbol",
      "title": "document",
      "type": "topic",
      "url": "/documentation/uikit/uiprinter/jobtypes/document"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/envelope": {
      "abstract": [
        {
          "text": "The printer supports printing on envelopes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "envelope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinter",
          "text": "UIPrinter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPrinterJobTypes",
          "text": "JobTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/envelope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrinterJobTypeEnvelope"
        }
      ],
      "role": "symbol",
      "title": "envelope",
      "type": "topic",
      "url": "/documentation/uikit/uiprinter/jobtypes/envelope"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/label": {
      "abstract": [
        {
          "text": "The printer supports printing on cut labels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinter",
          "text": "UIPrinter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPrinterJobTypes",
          "text": "JobTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/label",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrinterJobTypeLabel"
        }
      ],
      "role": "symbol",
      "title": "label",
      "type": "topic",
      "url": "/documentation/uikit/uiprinter/jobtypes/label"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/largeFormat": {
      "abstract": [
        {
          "text": "The printer supports printing larger than the ISO A3 size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "largeFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinter",
          "text": "UIPrinter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPrinterJobTypes",
          "text": "JobTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/largeFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrinterJobTypeLargeFormat"
        }
      ],
      "role": "symbol",
      "title": "largeFormat",
      "type": "topic",
      "url": "/documentation/uikit/uiprinter/jobtypes/largeformat"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/photo": {
      "abstract": [
        {
          "text": "The printer supports printing with photographic print quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinter",
          "text": "UIPrinter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPrinterJobTypes",
          "text": "JobTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/photo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrinterJobTypePhoto"
        }
      ],
      "role": "symbol",
      "title": "photo",
      "type": "topic",
      "url": "/documentation/uikit/uiprinter/jobtypes/photo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/postcard": {
      "abstract": [
        {
          "text": "The printer supports printing on postcards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postcard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinter",
          "text": "UIPrinter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPrinterJobTypes",
          "text": "JobTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/postcard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrinterJobTypePostcard"
        }
      ],
      "role": "symbol",
      "title": "postcard",
      "type": "topic",
      "url": "/documentation/uikit/uiprinter/jobtypes/postcard"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/receipt": {
      "abstract": [
        {
          "text": "The printer supports printing receipts on a continuous roll of paper.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "receipt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinter",
          "text": "UIPrinter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPrinterJobTypes",
          "text": "JobTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/receipt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrinterJobTypeReceipt"
        }
      ],
      "role": "symbol",
      "title": "receipt",
      "type": "topic",
      "url": "/documentation/uikit/uiprinter/jobtypes/receipt"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/roll": {
      "abstract": [
        {
          "text": "The printer supports printing documents or photos on a continuous roll of paper.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "roll"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinter",
          "text": "UIPrinter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPrinterJobTypes",
          "text": "JobTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/roll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrinterJobTypeRoll"
        }
      ],
      "role": "symbol",
      "title": "roll",
      "type": "topic",
      "url": "/documentation/uikit/uiprinter/jobtypes/roll"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/unknown": {
      "abstract": [
        {
          "text": "The printer support is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinter",
          "text": "UIPrinter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPrinterJobTypes",
          "text": "JobTypes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrinterJobTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/uikit/uiprinter/jobtypes/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/unknown",
        "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/document",
        "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/envelope",
        "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/label",
        "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/photo",
        "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/receipt",
        "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/roll",
        "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/postcard"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIPrinterJobTypeLargeFormat"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterJobTypeLargeFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/unknown",
                "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/document",
                "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/envelope",
                "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/label",
                "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/photo",
                "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/receipt",
                "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/roll",
                "doc://com.apple.uikit/documentation/UIKit/UIPrinter/JobTypes/postcard"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIPrinterJobTypeLargeFormat"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter/title",
          "value": "UIPrinter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1largeFormat/title",
          "value": "UIPrinterJobTypeLargeFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1largeFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterJobTypeLargeFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1label/title",
          "value": "UIPrinterJobTypeLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1label/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterJobTypeLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes/title",
          "value": "UIPrinterJobTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterJobTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterJobTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1unknown/title",
          "value": "UIPrinterJobTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterJobTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1receipt/title",
          "value": "UIPrinterJobTypeReceipt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1receipt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterJobTypeReceipt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1envelope/title",
          "value": "UIPrinterJobTypeEnvelope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1envelope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterJobTypeEnvelope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1photo/title",
          "value": "UIPrinterJobTypePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1photo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterJobTypePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1roll/title",
          "value": "UIPrinterJobTypeRoll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1roll/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterJobTypeRoll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1postcard/title",
          "value": "UIPrinterJobTypePostcard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1postcard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterJobTypePostcard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1document/title",
          "value": "UIPrinterJobTypeDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1JobTypes~1document/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterJobTypeDocument"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiprinter/jobtypes/largeformat"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiprinter/jobtypes/largeformat"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
