{
  "abstract": [
    {
      "text": "The width and height of the movie frame.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use AVPlayerViewController in AVKit",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/naturalSize"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MPMoviePlayerController(py)naturalSize",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "naturalSize"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGSize",
        "text": "CGSize"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "naturalSize"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "3.2",
        "message": "Use AVPlayerViewController in AVKit",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "3.2",
        "message": "Use AVPlayerViewController in AVKit",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use AVPlayerViewController in AVKit",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "naturalSize"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "naturalSize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGSize",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGSize",
              "text": "CGSize"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property reports the clean aperture of the video in square pixels. Thus, the reported dimensions take into account anamorphic content and aperture modes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "It is possible for the natural size of a movie to change during playback. This typically happens when the bit-rate of streaming content changes or when playback toggles between audio-only and a combination of audio and video.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController": {
      "abstract": [
        {
          "text": "A type of movie player that manages the playback of a movie from a file or a network stream.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPMoviePlayerController"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPMoviePlayerController"
        }
      ],
      "role": "symbol",
      "title": "MPMoviePlayerController",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayercontroller"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/allowsAirPlay": {
      "abstract": [
        {
          "text": "Specifies whether the movie player allows AirPlay movie playback.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsAirPlay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/allowsAirPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsAirPlay"
        }
      ],
      "role": "symbol",
      "title": "allowsAirPlay",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayercontroller/allowsairplay"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/contentURL": {
      "abstract": [
        {
          "text": "The URL that points to the movie file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/contentURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentURL"
        }
      ],
      "role": "symbol",
      "title": "contentURL",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayercontroller/contenturl"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/controlStyle": {
      "abstract": [
        {
          "text": "The style of the playback controls.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMovieControlStyle",
          "text": "MPMovieControlStyle"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/controlStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "controlStyle"
        }
      ],
      "role": "symbol",
      "title": "controlStyle",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayercontroller/controlstyle"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/isAirPlayVideoActive": {
      "abstract": [
        {
          "text": "Indicates whether the movie player is currently playing video via AirPlay.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAirPlayVideoActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/isAirPlayVideoActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "airPlayVideoActive"
        }
      ],
      "role": "symbol",
      "title": "isAirPlayVideoActive",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayercontroller/isairplayvideoactive"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/isFullscreen": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the movie player is in full-screen mode.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFullscreen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/isFullscreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fullscreen"
        }
      ],
      "role": "symbol",
      "title": "isFullscreen",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayercontroller/isfullscreen"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/movieMediaTypes": {
      "abstract": [
        {
          "text": "The types of media available in the movie.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "movieMediaTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMovieMediaTypeMask",
          "text": "MPMovieMediaTypeMask"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/movieMediaTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "movieMediaTypes"
        }
      ],
      "role": "symbol",
      "title": "movieMediaTypes",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayercontroller/moviemediatypes"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/movieSourceType": {
      "abstract": [
        {
          "text": "The playback type of the movie.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "movieSourceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMovieSourceType",
          "text": "MPMovieSourceType"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/movieSourceType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "movieSourceType"
        }
      ],
      "role": "symbol",
      "title": "movieSourceType",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayercontroller/moviesourcetype"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/naturalSize": {
      "abstract": [
        {
          "text": "The width and height of the movie frame.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "naturalSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/naturalSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "naturalSize"
        }
      ],
      "role": "symbol",
      "title": "naturalSize",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayercontroller/naturalsize"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/scalingMode": {
      "abstract": [
        {
          "text": "The scaling mode to use when displaying the movie.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scalingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MPMovieScalingMode",
          "text": "MPMovieScalingMode"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/scalingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scalingMode"
        }
      ],
      "role": "symbol",
      "title": "scalingMode",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayercontroller/scalingmode"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/setFullscreen(_:animated:)": {
      "abstract": [
        {
          "text": "Causes the movie player to enter or exit full-screen mode.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setFullscreen"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/setFullscreen(_:animated:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setFullscreen:animated:"
        }
      ],
      "role": "symbol",
      "title": "setFullscreen(_:animated:)",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayercontroller/setfullscreen(_:animated:)"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/useApplicationAudioSession": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the movie player should use the app’s audio session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "useApplicationAudioSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/useApplicationAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "useApplicationAudioSession"
        }
      ],
      "role": "symbol",
      "title": "useApplicationAudioSession",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpmovieplayercontroller/useapplicationaudiosession"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGSize": {
      "abstract": [
        {
          "text": "A structure that contains width and height values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGSize",
      "type": "topic",
      "url": "/documentation/corefoundation/cgsize"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-movie-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/contentURL",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/movieSourceType",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/movieMediaTypes",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/allowsAirPlay",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/isAirPlayVideoActive",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/isFullscreen",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/setFullscreen(_:animated:)",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/scalingMode",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/controlStyle",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/useApplicationAudioSession"
      ],
      "title": "Accessing movie properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "3.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "3.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "naturalSize"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "naturalSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-movie-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/contentURL",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/movieSourceType",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/movieMediaTypes",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/allowsAirPlay",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/isAirPlayVideoActive",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/isFullscreen",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/setFullscreen(_:animated:)",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/scalingMode",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/controlStyle",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPMoviePlayerController/useApplicationAudioSession"
              ],
              "title": "Accessing movie properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGSize",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGSize",
                    "text": "CGSize"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "naturalSize"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use AVPlayerViewController in AVKit",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1movieMediaTypes/title",
          "value": "movieMediaTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1movieMediaTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "movieMediaTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController/title",
          "value": "MPMoviePlayerController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPMoviePlayerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1contentURL/title",
          "value": "contentURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1contentURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1isAirPlayVideoActive/title",
          "value": "airPlayVideoActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1isAirPlayVideoActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "airPlayVideoActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1isFullscreen/title",
          "value": "fullscreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1isFullscreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fullscreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1naturalSize/title",
          "value": "naturalSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1naturalSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "naturalSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1controlStyle/title",
          "value": "controlStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1controlStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "controlStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1setFullscreen(_:animated:)/title",
          "value": "setFullscreen:animated:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1setFullscreen(_:animated:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setFullscreen:animated:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1allowsAirPlay/title",
          "value": "allowsAirPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1allowsAirPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsAirPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1useApplicationAudioSession/title",
          "value": "useApplicationAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1useApplicationAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "useApplicationAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1scalingMode/title",
          "value": "scalingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1scalingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scalingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1movieSourceType/title",
          "value": "movieSourceType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPMoviePlayerController~1movieSourceType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "movieSourceType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpmovieplayercontroller/naturalsize"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpmovieplayercontroller/naturalsize"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
