{
  "abstract": [
    {
      "text": "A constant that specifies advanced audio coding, which is the basic MPEG-4 technology.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/aac_Main"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MPEG4ObjectID@kMPEG4Object_AAC_Main",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "aac_Main"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMPEG4Object_AAC_Main"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.3",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MPEG4ObjectID.aac_Main"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "aac_Main"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID": {
      "abstract": [
        {
          "text": "Constants that define the type of MPEG-4 audio data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPEG4ObjectID"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPEG4ObjectID"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_LC": {
      "abstract": [
        {
          "text": "A constant that specifies lossless coding, which provides compression with no loss of quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AAC_LC"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_LC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_AAC_LC"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.AAC_LC",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/aac_lc"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_LTP": {
      "abstract": [
        {
          "text": "A constant that specifies long-term prediction, which reduces redundancy in a coded signal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AAC_LTP"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_LTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_AAC_LTP"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.AAC_LTP",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/aac_ltp"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_SBR": {
      "abstract": [
        {
          "text": "A constant that specifies spectral band replication, which reconstructs high-frequency content from lower frequencies and side information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AAC_SBR"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_SBR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_AAC_SBR"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.AAC_SBR",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/aac_sbr"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_SSR": {
      "abstract": [
        {
          "text": "A constant that specifies scalable sampling rate, which provides different sampling frequencies for different targets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AAC_SSR"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_SSR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_AAC_SSR"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.AAC_SSR",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/aac_ssr"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/CELP": {
      "abstract": [
        {
          "text": "A constant that specifies code-excited linear prediction, which is a narrow-band/wide-band speech codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CELP"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/CELP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_CELP"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.CELP",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/celp"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/HVXC": {
      "abstract": [
        {
          "text": "A constant that specifies harmonic vector excitation coding, which is a very-low bit-rate parametric speech codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HVXC"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/HVXC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_HVXC"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.HVXC",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/hvxc"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/aac_Main": {
      "abstract": [
        {
          "text": "A constant that specifies advanced audio coding, which is the basic MPEG-4 technology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aac_Main"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/aac_Main",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_AAC_Main"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.aac_Main",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/aac_main"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/aac_Scalable": {
      "abstract": [
        {
          "text": "A constant that specifies scalable lossless coding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aac_Scalable"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/aac_Scalable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_AAC_Scalable"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.aac_Scalable",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/aac_scalable"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/twinVQ": {
      "abstract": [
        {
          "text": "A constant that specifies transform-domain weighted interleaved vector quantization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "twinVQ"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/twinVQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMPEG4Object_TwinVQ"
        }
      ],
      "role": "symbol",
      "title": "MPEG4ObjectID.twinVQ",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/mpeg4objectid/twinvq"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_LC",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_LTP",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_SBR",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_SSR",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/aac_Scalable",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/CELP",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/HVXC",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/twinVQ"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMPEG4Object_AAC_Main"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_AAC_Main"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_LC",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_LTP",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_SBR",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/AAC_SSR",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/aac_Scalable",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/CELP",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/HVXC",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/MPEG4ObjectID/twinVQ"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kMPEG4Object_AAC_Main"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1AAC_SBR/title",
          "value": "kMPEG4Object_AAC_SBR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1AAC_SBR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_AAC_SBR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1AAC_SSR/title",
          "value": "kMPEG4Object_AAC_SSR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1AAC_SSR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_AAC_SSR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1twinVQ/title",
          "value": "kMPEG4Object_TwinVQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1twinVQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_TwinVQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1aac_Scalable/title",
          "value": "kMPEG4Object_AAC_Scalable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1aac_Scalable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_AAC_Scalable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1AAC_LC/title",
          "value": "kMPEG4Object_AAC_LC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1AAC_LC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_AAC_LC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1AAC_LTP/title",
          "value": "kMPEG4Object_AAC_LTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1AAC_LTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_AAC_LTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1CELP/title",
          "value": "kMPEG4Object_CELP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1CELP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_CELP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1HVXC/title",
          "value": "kMPEG4Object_HVXC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1HVXC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_HVXC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID/title",
          "value": "MPEG4ObjectID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPEG4ObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPEG4ObjectID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1aac_Main/title",
          "value": "kMPEG4Object_AAC_Main"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1MPEG4ObjectID~1aac_Main/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMPEG4Object_AAC_Main"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/mpeg4objectid/aac_main"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/mpeg4objectid/aac_main"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
