{
  "abstract": [
    {
      "text": "Provides an opportunity to use the data source before it’s released.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource/extensionWillDiscardDataSource()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)PHProjectTypeDescriptionDataSource(im)extensionWillDiscardDataSource",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "extensionWillDiscardDataSource"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "extensionWillDiscardDataSource"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "extensionWillDiscardDataSource()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "extensionWillDiscardDataSource"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After this call, the extension context no longer strongly references the data source. Fetch any last data you need here before the data source goes out of scope.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource": {
      "abstract": [
        {
          "text": "A protocol that you use to provide the project with type description data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectTypeDescriptionDataSource"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectTypeDescriptionDataSource"
        }
      ],
      "role": "symbol",
      "title": "PHProjectTypeDescriptionDataSource",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttypedescriptiondatasource"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource/extensionWillDiscardDataSource()": {
      "abstract": [
        {
          "text": "Provides an opportunity to use the data source before it’s released.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionWillDiscardDataSource"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource/extensionWillDiscardDataSource()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extensionWillDiscardDataSource"
        }
      ],
      "role": "symbol",
      "title": "extensionWillDiscardDataSource()",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttypedescriptiondatasource/extensionwilldiscarddatasource()"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "extensionWillDiscardDataSource"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "extensionWillDiscardDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/PhotosUI",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "extensionWillDiscardDataSource"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource/title",
          "value": "PHProjectTypeDescriptionDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTypeDescriptionDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTypeDescriptionDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource~1extensionWillDiscardDataSource()/title",
          "value": "extensionWillDiscardDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource~1extensionWillDiscardDataSource()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "extensionWillDiscardDataSource"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phprojecttypedescriptiondatasource/extensionwilldiscarddatasource()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photosui/phprojecttypedescriptiondatasource/extensionwilldiscarddatasource()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
