{
  "abstract": [
    {
      "text": "Provides the updated project type description for previously invalidated project types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/PhotosUI",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource/typeDescription(for:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)PHProjectTypeDescriptionDataSource(im)typeDescriptionForProjectType:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "typeDescription"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@PHProjectType",
        "text": "PHProjectType"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)PHProjectTypeDescription",
        "text": "PHProjectTypeDescription"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "PhotosUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "typeDescriptionForProjectType:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "typeDescription(for:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "typeDescription"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "projectType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@PHProjectType",
              "text": "PHProjectType"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescription",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PHProjectTypeDescription",
              "text": "PHProjectTypeDescription"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The previously invalidated project type whose type description is being requested.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "projectType"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the given project type.  The returned description’s project type must match the given project type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/PhotosUI": {
      "abstract": [
        {
          "text": "Present a person’s photo library using a picker interface, display Live Photos, or extend the Photos app with custom functionality.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI",
      "kind": "symbol",
      "role": "collection",
      "title": "PhotosUI",
      "type": "topic",
      "url": "/documentation/photosui"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType": {
      "abstract": [
        {
          "text": "The type descriptor of a project extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectType"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectType"
        }
      ],
      "role": "symbol",
      "title": "PHProjectType",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttype"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescription": {
      "abstract": [
        {
          "text": "An extensible enumerator for ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " that’s presented to users in the project picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectTypeDescription"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectTypeDescription"
        }
      ],
      "role": "symbol",
      "title": "PHProjectTypeDescription",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttypedescription"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescription/canProvideSubtypes": {
      "abstract": [
        {
          "text": "A Boolean variable indicating whether subtypes can be fetched from the data source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canProvideSubtypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescription/canProvideSubtypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canProvideSubtypes"
        }
      ],
      "role": "symbol",
      "title": "canProvideSubtypes",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttypedescription/canprovidesubtypes"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource": {
      "abstract": [
        {
          "text": "A protocol that you use to provide the project with type description data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHProjectTypeDescriptionDataSource"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHProjectTypeDescriptionDataSource"
        }
      ],
      "role": "symbol",
      "title": "PHProjectTypeDescriptionDataSource",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttypedescriptiondatasource"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource/footerText(forSubtypesOf:)": {
      "abstract": [
        {
          "text": "Provides the footer text for the subtypes of the given project type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "footerText"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forSubtypesOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHProjectType",
          "text": "PHProjectType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource/footerText(forSubtypesOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "footerTextForSubtypesOfProjectType:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "footerText(forSubtypesOf:)",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttypedescriptiondatasource/footertext(forsubtypesof:)"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource/subtypes(for:)": {
      "abstract": [
        {
          "text": "Provides the root-level project type descriptions and descriptions of any promised subtypes with ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescription/canProvideSubtypes",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " set to ",
          "type": "text"
        },
        {
          "code": "true",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtypes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHProjectType",
          "text": "PHProjectType"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHProjectTypeDescription",
          "text": "PHProjectTypeDescription"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource/subtypes(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subtypesForProjectType:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "subtypes(for:)",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttypedescriptiondatasource/subtypes(for:)"
    },
    "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource/typeDescription(for:)": {
      "abstract": [
        {
          "text": "Provides the updated project type description for previously invalidated project types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeDescription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHProjectType",
          "text": "PHProjectType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHProjectTypeDescription",
          "text": "PHProjectTypeDescription"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource/typeDescription(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typeDescriptionForProjectType:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "typeDescription(for:)",
      "type": "topic",
      "url": "/documentation/photosui/phprojecttypedescriptiondatasource/typedescription(for:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-Required-Fields",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource/subtypes(for:)",
        "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource/footerText(forSubtypesOf:)"
      ],
      "title": "Providing Required Fields"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "typeDescriptionForProjectType:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "typeDescriptionForProjectType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/PhotosUI",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-Required-Fields",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource/subtypes(for:)",
                "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescriptionDataSource/footerText(forSubtypesOf:)"
              ],
              "title": "Providing Required Fields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescription",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PHProjectTypeDescription",
                    "text": "PHProjectTypeDescription"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "typeDescriptionForProjectType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@PHProjectType",
                    "text": "PHProjectType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "projectType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The previously invalidated project type whose type description is being requested.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "projectType"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.photokit/documentation/PhotosUI/PHProjectTypeDescription",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " for the given project type.  The returned description’s project type must match the given project type.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectType/title",
          "value": "PHProjectType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource~1subtypes(for:)/title",
          "value": "subtypesForProjectType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource~1subtypes(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subtypesForProjectType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource/title",
          "value": "PHProjectTypeDescriptionDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTypeDescriptionDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTypeDescriptionDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescription~1canProvideSubtypes/title",
          "value": "canProvideSubtypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescription~1canProvideSubtypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canProvideSubtypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescription/title",
          "value": "PHProjectTypeDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTypeDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHProjectTypeDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource~1typeDescription(for:)/title",
          "value": "typeDescriptionForProjectType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource~1typeDescription(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "typeDescriptionForProjectType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource~1footerText(forSubtypesOf:)/title",
          "value": "footerTextForSubtypesOfProjectType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1PhotosUI~1PHProjectTypeDescriptionDataSource~1footerText(forSubtypesOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "footerTextForSubtypesOfProjectType:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photosui/phprojecttypedescriptiondatasource/typedescription(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photosui/phprojecttypedescriptiondatasource/typedescription(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
