{
  "abstract": [
    {
      "text": "Moves the path object’s current drawing point to the specified point.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/moveTo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSBezierPathElement@NSBezierPathElementMoveTo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "moveTo"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSBezierPathElementMoveTo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSBezierPath.ElementType.moveTo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "moveTo"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath": {
      "abstract": [
        {
          "text": "An object that can create paths using PostScript-style commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBezierPath"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPath"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType": {
      "abstract": [
        {
          "text": "Constants that specify basic path element commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ElementType"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.ElementType",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/closePath": {
      "abstract": [
        {
          "text": "Marks the end of the current subpath at the specified point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closePath"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/closePath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPathElementClosePath"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.ElementType.closePath",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype/closepath"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/cubicCurveTo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cubicCurveTo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/cubicCurveTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPathElementCubicCurveTo"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.ElementType.cubicCurveTo",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype/cubiccurveto"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/curveTo": {
      "abstract": [
        {
          "text": "Creates a curved line segment from the current point to the specified endpoint using two control points to define the curve.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "curveTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBezierPath",
          "text": "NSBezierPath"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBezierPathElement",
          "text": "ElementType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/curveTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPathElementCurveTo"
        }
      ],
      "role": "symbol",
      "title": "curveTo",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype/curveto"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/lineTo": {
      "abstract": [
        {
          "text": "Creates a straight line from the current drawing point to the specified point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineTo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/lineTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPathElementLineTo"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.ElementType.lineTo",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype/lineto"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/moveTo": {
      "abstract": [
        {
          "text": "Moves the path object’s current drawing point to the specified point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveTo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/moveTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPathElementMoveTo"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.ElementType.moveTo",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype/moveto"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/quadraticCurveTo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quadraticCurveTo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/quadraticCurveTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezierPathElementQuadraticCurveTo"
        }
      ],
      "role": "symbol",
      "title": "NSBezierPath.ElementType.quadraticCurveTo",
      "type": "topic",
      "url": "/documentation/appkit/nsbezierpath/elementtype/quadraticcurveto"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/lineTo",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/closePath",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/curveTo",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/cubicCurveTo",
        "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/quadraticCurveTo"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSBezierPathElementMoveTo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElementMoveTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/lineTo",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/closePath",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/curveTo",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/cubicCurveTo",
                "doc://com.apple.appkit/documentation/AppKit/NSBezierPath/ElementType/quadraticCurveTo"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSBezierPathElementMoveTo"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1curveTo/title",
          "value": "NSBezierPathElementCurveTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1curveTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElementCurveTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1closePath/title",
          "value": "NSBezierPathElementClosePath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1closePath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElementClosePath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1moveTo/title",
          "value": "NSBezierPathElementMoveTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1moveTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElementMoveTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1quadraticCurveTo/title",
          "value": "NSBezierPathElementQuadraticCurveTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1quadraticCurveTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElementQuadraticCurveTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1cubicCurveTo/title",
          "value": "NSBezierPathElementCubicCurveTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1cubicCurveTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElementCubicCurveTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType/title",
          "value": "NSBezierPathElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/title",
          "value": "NSBezierPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1lineTo/title",
          "value": "NSBezierPathElementLineTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBezierPath~1ElementType~1lineTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezierPathElementLineTo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbezierpath/elementtype/moveto"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsbezierpath/elementtype/moveto"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
