{
  "abstract": [
    {
      "text": "The stroke width to use for the path.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineWidth"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MKOverlayPathRenderer(py)lineWidth",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "lineWidth"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
        "text": "CGFloat"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "lineWidth"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "lineWidth"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "lineWidth"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default value of this property is ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer": {
      "abstract": [
        {
          "text": "The visual representation of a path-based overlay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKOverlayPathRenderer"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKOverlayPathRenderer"
        }
      ],
      "role": "symbol",
      "title": "MKOverlayPathRenderer",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlaypathrenderer"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/fillColor": {
      "abstract": [
        {
          "text": "The fill color to use for the path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fillColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/fillColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fillColor"
        }
      ],
      "role": "symbol",
      "title": "fillColor",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlaypathrenderer/fillcolor"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineCap": {
      "abstract": [
        {
          "text": "The line cap style to apply to the open ends of the path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineCap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CGLineCap",
          "text": "CGLineCap"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineCap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineCap"
        }
      ],
      "role": "symbol",
      "title": "lineCap",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlaypathrenderer/linecap"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineDashPattern": {
      "abstract": [
        {
          "text": "An array of numbers specifying the dash pattern to use for the path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineDashPattern"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineDashPattern",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineDashPattern"
        }
      ],
      "role": "symbol",
      "title": "lineDashPattern",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlaypathrenderer/linedashpattern"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineDashPhase": {
      "abstract": [
        {
          "text": "The offset (in points) at which to start drawing the dash pattern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineDashPhase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineDashPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineDashPhase"
        }
      ],
      "role": "symbol",
      "title": "lineDashPhase",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlaypathrenderer/linedashphase"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineJoin": {
      "abstract": [
        {
          "text": "The line join style to apply to the corners of the path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineJoin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CGLineJoin",
          "text": "CGLineJoin"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineJoin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineJoin"
        }
      ],
      "role": "symbol",
      "title": "lineJoin",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlaypathrenderer/linejoin"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineWidth": {
      "abstract": [
        {
          "text": "The stroke width to use for the path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineWidth"
        }
      ],
      "role": "symbol",
      "title": "lineWidth",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlaypathrenderer/linewidth"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/miterLimit": {
      "abstract": [
        {
          "text": "The limiting value that helps avoid spikes at junctions between connected line segments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "miterLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/miterLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "miterLimit"
        }
      ],
      "role": "symbol",
      "title": "miterLimit",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlaypathrenderer/miterlimit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/strokeColor": {
      "abstract": [
        {
          "text": "The stroke color to use for the path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "strokeColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/strokeColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "strokeColor"
        }
      ],
      "role": "symbol",
      "title": "strokeColor",
      "type": "topic",
      "url": "/documentation/mapkit/mkoverlaypathrenderer/strokecolor"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGFloat": {
      "abstract": [
        {
          "text": "The basic type for all floating-point values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-drawing-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/fillColor",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/strokeColor",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineJoin",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineCap",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/miterLimit",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineDashPhase",
        "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineDashPattern"
      ],
      "title": "Accessing the drawing attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "lineWidth"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit",
                "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-the-drawing-attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/fillColor",
                "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/strokeColor",
                "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineJoin",
                "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineCap",
                "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/miterLimit",
                "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineDashPhase",
                "doc://com.apple.mapkit/documentation/MapKit/MKOverlayPathRenderer/lineDashPattern"
              ],
              "title": "Accessing the drawing attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGFloat",
                    "text": "CGFloat"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "lineWidth"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer~1fillColor/title",
          "value": "fillColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer~1fillColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fillColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer/title",
          "value": "MKOverlayPathRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayPathRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKOverlayPathRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer~1strokeColor/title",
          "value": "strokeColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer~1strokeColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "strokeColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer~1lineJoin/title",
          "value": "lineJoin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer~1lineJoin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineJoin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer~1lineWidth/title",
          "value": "lineWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer~1lineWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer~1lineCap/title",
          "value": "lineCap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer~1lineCap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineCap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer~1lineDashPhase/title",
          "value": "lineDashPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer~1lineDashPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineDashPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer~1miterLimit/title",
          "value": "miterLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer~1miterLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "miterLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer~1lineDashPattern/title",
          "value": "lineDashPattern"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKOverlayPathRenderer~1lineDashPattern/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineDashPattern"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkoverlaypathrenderer/linewidth"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkoverlaypathrenderer/linewidth"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
