{
  "abstract": [
    {
      "text": "A button on a physical remote control.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@XCUIRemoteButton",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "XCUIRemoteButton"
      }
    ],
    "modules": [
      {
        "name": "XCUIAutomation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "XCUIRemoteButton"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.3",
        "name": "Xcode",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "XCUIRemoteButton"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "XCUIRemoteButton"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Button"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation": {
      "abstract": [
        {
          "text": "Replicate sequences of interactions and make sure that your app’s user interface behaves as intended.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation",
      "kind": "symbol",
      "role": "collection",
      "title": "XCUIAutomation",
      "type": "topic",
      "url": "/documentation/xcuiautomation"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemote/press(_:)": {
      "abstract": [
        {
          "text": "Sends a momentary press of a button on a physical remote control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "press"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIRemote",
          "text": "XCUIRemote"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIRemoteButton",
          "text": "Button"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemote/press(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pressButton:"
        }
      ],
      "role": "symbol",
      "title": "press(_:)",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremote/press(_:)"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemote/press(_:forDuration:)": {
      "abstract": [
        {
          "text": "Sends a press and hold of a button on a physical remote control, holding for the specified duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "press"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIRemote",
          "text": "XCUIRemote"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@XCUIRemoteButton",
          "text": "Button"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemote/press(_:forDuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pressButton:forDuration:"
        }
      ],
      "role": "symbol",
      "title": "press(_:forDuration:)",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremote/press(_:forduration:)"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton": {
      "abstract": [
        {
          "text": "A button on a physical remote control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIRemoteButton"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButton"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/equatable-implementations"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/RawRepresentable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/RawRepresentable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RawRepresentable Implementations",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/rawrepresentable-implementations"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/down": {
      "abstract": [
        {
          "text": "A constant that represents the down button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "down"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/down",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonDown"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.down",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/down"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/fourColors": {
      "abstract": [
        {
          "text": "A constant that represents the color functions button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fourColors"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/fourColors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonFourColors"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.fourColors",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/fourcolors"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/guide": {
      "abstract": [
        {
          "text": "A constant that represents the guide button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "guide"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/guide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonGuide"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.guide",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/guide"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/home": {
      "abstract": [
        {
          "text": "A constant that represents the home button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/home",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonHome"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.home",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/home"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/init(rawvalue:)"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/left": {
      "abstract": [
        {
          "text": "A constant that represents the left button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonLeft"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.left",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/left"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/menu": {
      "abstract": [
        {
          "text": "A constant that represents the menu button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menu"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/menu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonMenu"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.menu",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/menu"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/oneTwoThree": {
      "abstract": [
        {
          "text": "A constant that represents the channel-tuning button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneTwoThree"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/oneTwoThree",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonOneTwoThree"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.oneTwoThree",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/onetwothree"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/pageDown": {
      "abstract": [
        {
          "text": "A constant that represents the page down button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageDown"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/pageDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonPageDown"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.pageDown",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/pagedown"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/pageUp": {
      "abstract": [
        {
          "text": "A constant that represents the page up button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageUp"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/pageUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonPageUp"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.pageUp",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/pageup"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/playPause": {
      "abstract": [
        {
          "text": "A constant that represents the play-and-pause button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playPause"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/playPause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonPlayPause"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.playPause",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/playpause"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/right": {
      "abstract": [
        {
          "text": "A constant that represents the right button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonRight"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.right",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/right"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/select": {
      "abstract": [
        {
          "text": "A constant that represents the select button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "select"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/select",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonSelect"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.select",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/select"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/tvProvider": {
      "abstract": [
        {
          "text": "A constant that represents the TV provider button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tvProvider"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/tvProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonTVProvider"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.tvProvider",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/tvprovider"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/up": {
      "abstract": [
        {
          "text": "A constant that represents the up button on a remote.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "up"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/up",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIRemoteButtonUp"
        }
      ],
      "role": "symbol",
      "title": "XCUIRemoteButton.up",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuiremotebutton/up"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Pressing-remote-buttons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemote/press(_:)",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemote/press(_:forDuration:)"
      ],
      "title": "Pressing remote buttons"
    }
  ],
  "topicSections": [
    {
      "anchor": "Remote-buttons",
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/up",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/down",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/left",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/right",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/select",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/menu",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/playPause",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/home",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/pageUp",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/pageDown",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/guide",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/fourColors",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/oneTwoThree",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/tvProvider"
      ],
      "title": "Remote buttons"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/Equatable-Implementations",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/RawRepresentable-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.3",
              "name": "Xcode",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "XCUIRemoteButton"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Remote-buttons",
              "identifiers": [
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/up",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/down",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/left",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/right",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/select",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/menu",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/playPause",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/home",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/pageUp",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/pageDown",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/guide",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/fourColors",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/oneTwoThree",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemoteButton/tvProvider"
              ],
              "title": "Remote buttons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Pressing-remote-buttons",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemote/press(_:)",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIRemote/press(_:forDuration:)"
              ],
              "title": "Pressing remote buttons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "XCUIRemoteButton"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1left/title",
          "value": "XCUIRemoteButtonLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1playPause/title",
          "value": "XCUIRemoteButtonPlayPause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1playPause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonPlayPause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1down/title",
          "value": "XCUIRemoteButtonDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1down/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1tvProvider/title",
          "value": "XCUIRemoteButtonTVProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1tvProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonTVProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1select/title",
          "value": "XCUIRemoteButtonSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1select/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemote~1press(_:forDuration:)/title",
          "value": "pressButton:forDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemote~1press(_:forDuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pressButton:forDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1oneTwoThree/title",
          "value": "XCUIRemoteButtonOneTwoThree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1oneTwoThree/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonOneTwoThree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1home/title",
          "value": "XCUIRemoteButtonHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1home/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1pageUp/title",
          "value": "XCUIRemoteButtonPageUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1pageUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonPageUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1fourColors/title",
          "value": "XCUIRemoteButtonFourColors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1fourColors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonFourColors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton/title",
          "value": "XCUIRemoteButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemote~1press(_:)/title",
          "value": "pressButton:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemote~1press(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pressButton:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1pageDown/title",
          "value": "XCUIRemoteButtonPageDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1pageDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonPageDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1guide/title",
          "value": "XCUIRemoteButtonGuide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1guide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1menu/title",
          "value": "XCUIRemoteButtonMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1menu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1up/title",
          "value": "XCUIRemoteButtonUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1up/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1right/title",
          "value": "XCUIRemoteButtonRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIRemoteButton~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIRemoteButtonRight"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcuiautomation/xcuiremotebutton"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xcuiautomation/xcuiremotebutton"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
