{
  "abstract": [
    {
      "text": "Reasons the app can’t add the media item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INAddMediaMediaItemUnsupportedReason",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INAddMediaMediaItemUnsupportedReason"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INAddMediaMediaItemUnsupportedReason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INAddMediaMediaItemUnsupportedReason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INAddMediaMediaItemUnsupportedReason"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemResolutionResult/unsupported(forReason:)": {
      "abstract": [
        {
          "text": "Creates a result that requires the user to confirm the request because your app is unable to support the current request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INAddMediaMediaItemUnsupportedReason",
          "text": "INAddMediaMediaItemUnsupportedReason"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemResolutionResult/unsupported(forReason:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unsupportedForReason:"
        }
      ],
      "role": "symbol",
      "title": "unsupported(forReason:)",
      "type": "topic",
      "url": "/documentation/intents/inaddmediamediaitemresolutionresult/unsupported(forreason:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason": {
      "abstract": [
        {
          "text": "Reasons the app can’t add the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAddMediaMediaItemUnsupportedReason"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaMediaItemUnsupportedReason"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaMediaItemUnsupportedReason",
      "type": "topic",
      "url": "/documentation/intents/inaddmediamediaitemunsupportedreason"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/cellularDataSettings": {
      "abstract": [
        {
          "text": "The cellular data settings don’t allow the user to add the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cellularDataSettings"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/cellularDataSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaMediaItemUnsupportedReasonCellularDataSettings"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaMediaItemUnsupportedReason.cellularDataSettings",
      "type": "topic",
      "url": "/documentation/intents/inaddmediamediaitemunsupportedreason/cellulardatasettings"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/explicitContentSettings": {
      "abstract": [
        {
          "text": "The content settings don’t allow the user to add the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "explicitContentSettings"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/explicitContentSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaMediaItemUnsupportedReasonExplicitContentSettings"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaMediaItemUnsupportedReason.explicitContentSettings",
      "type": "topic",
      "url": "/documentation/intents/inaddmediamediaitemunsupportedreason/explicitcontentsettings"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/inaddmediamediaitemunsupportedreason/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/loginRequired": {
      "abstract": [
        {
          "text": "The user must log in to the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loginRequired"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/loginRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaMediaItemUnsupportedReasonLoginRequired"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaMediaItemUnsupportedReason.loginRequired",
      "type": "topic",
      "url": "/documentation/intents/inaddmediamediaitemunsupportedreason/loginrequired"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/regionRestriction": {
      "abstract": [
        {
          "text": "The media is unavailable to add in the user’s geographic location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionRestriction"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/regionRestriction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaMediaItemUnsupportedReasonRegionRestriction"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaMediaItemUnsupportedReason.regionRestriction",
      "type": "topic",
      "url": "/documentation/intents/inaddmediamediaitemunsupportedreason/regionrestriction"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/restrictedContent": {
      "abstract": [
        {
          "text": "The media item is restricted content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restrictedContent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/restrictedContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaMediaItemUnsupportedReasonRestrictedContent"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaMediaItemUnsupportedReason.restrictedContent",
      "type": "topic",
      "url": "/documentation/intents/inaddmediamediaitemunsupportedreason/restrictedcontent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/serviceUnavailable": {
      "abstract": [
        {
          "text": "The media service isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceUnavailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/serviceUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaMediaItemUnsupportedReasonServiceUnavailable"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaMediaItemUnsupportedReason.serviceUnavailable",
      "type": "topic",
      "url": "/documentation/intents/inaddmediamediaitemunsupportedreason/serviceunavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/subscriptionRequired": {
      "abstract": [
        {
          "text": "The user must have a subscription to the app’s service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriptionRequired"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/subscriptionRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaMediaItemUnsupportedReasonSubscriptionRequired"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaMediaItemUnsupportedReason.subscriptionRequired",
      "type": "topic",
      "url": "/documentation/intents/inaddmediamediaitemunsupportedreason/subscriptionrequired"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/unsupportedMediaType": {
      "abstract": [
        {
          "text": "The media is an unsupported type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedMediaType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/unsupportedMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddMediaMediaItemUnsupportedReasonUnsupportedMediaType"
        }
      ],
      "role": "symbol",
      "title": "INAddMediaMediaItemUnsupportedReason.unsupportedMediaType",
      "type": "topic",
      "url": "/documentation/intents/inaddmediamediaitemunsupportedreason/unsupportedmediatype"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reporting-a-Problem",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemResolutionResult/unsupported(forReason:)"
      ],
      "title": "Reporting a Problem"
    }
  ],
  "topicSections": [
    {
      "anchor": "Limitations",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/loginRequired",
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/subscriptionRequired",
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/unsupportedMediaType",
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/explicitContentSettings",
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/cellularDataSettings",
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/restrictedContent",
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/regionRestriction",
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/serviceUnavailable"
      ],
      "title": "Limitations"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INAddMediaMediaItemUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaMediaItemUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaMediaItemUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Limitations",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/loginRequired",
                "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/subscriptionRequired",
                "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/unsupportedMediaType",
                "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/explicitContentSettings",
                "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/cellularDataSettings",
                "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/restrictedContent",
                "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/regionRestriction",
                "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemUnsupportedReason/serviceUnavailable"
              ],
              "title": "Limitations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reporting-a-Problem",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INAddMediaMediaItemResolutionResult/unsupported(forReason:)"
              ],
              "title": "Reporting a Problem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INAddMediaMediaItemUnsupportedReason"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason/title",
          "value": "INAddMediaMediaItemUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaMediaItemUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaMediaItemUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason~1loginRequired/title",
          "value": "INAddMediaMediaItemUnsupportedReasonLoginRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason~1loginRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaMediaItemUnsupportedReasonLoginRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason~1cellularDataSettings/title",
          "value": "INAddMediaMediaItemUnsupportedReasonCellularDataSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason~1cellularDataSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaMediaItemUnsupportedReasonCellularDataSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason~1unsupportedMediaType/title",
          "value": "INAddMediaMediaItemUnsupportedReasonUnsupportedMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason~1unsupportedMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaMediaItemUnsupportedReasonUnsupportedMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason~1serviceUnavailable/title",
          "value": "INAddMediaMediaItemUnsupportedReasonServiceUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason~1serviceUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaMediaItemUnsupportedReasonServiceUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason~1restrictedContent/title",
          "value": "INAddMediaMediaItemUnsupportedReasonRestrictedContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason~1restrictedContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaMediaItemUnsupportedReasonRestrictedContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason~1subscriptionRequired/title",
          "value": "INAddMediaMediaItemUnsupportedReasonSubscriptionRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason~1subscriptionRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaMediaItemUnsupportedReasonSubscriptionRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason~1regionRestriction/title",
          "value": "INAddMediaMediaItemUnsupportedReasonRegionRestriction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason~1regionRestriction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaMediaItemUnsupportedReasonRegionRestriction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemResolutionResult~1unsupported(forReason:)/title",
          "value": "unsupportedForReason:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemResolutionResult~1unsupported(forReason:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "unsupportedForReason:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason~1explicitContentSettings/title",
          "value": "INAddMediaMediaItemUnsupportedReasonExplicitContentSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddMediaMediaItemUnsupportedReason~1explicitContentSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddMediaMediaItemUnsupportedReasonExplicitContentSettings"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inaddmediamediaitemunsupportedreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inaddmediamediaitemunsupportedreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
