{
  "abstract": [
    {
      "text": "A resolution result that adds tasks to a target task list.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INAddTasksTargetTaskListResolutionResult"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INAddTasksTargetTaskListResolutionResult",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INAddTasksTargetTaskListResolutionResult"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INAddTasksTargetTaskListResolutionResult"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "INAddTasksTargetTaskListResolutionResult"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INAddTasksTargetTaskListResolutionResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You return an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddTasksTargetTaskListResolutionResult",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object when resolving parameters containing an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddTasksTargetTaskListConfirmationReason",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value. Use the creation method that best reflects your ability to successfully resolve the parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For additional resolution operators, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddTasksTargetTaskListConfirmationReason": {
      "abstract": [
        {
          "text": "Constants that indicate the reason for confirming a task list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAddTasksTargetTaskListConfirmationReason"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddTasksTargetTaskListConfirmationReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddTasksTargetTaskListConfirmationReason"
        }
      ],
      "role": "symbol",
      "title": "INAddTasksTargetTaskListConfirmationReason",
      "type": "topic",
      "url": "/documentation/intents/inaddtaskstargettasklistconfirmationreason"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddTasksTargetTaskListResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result that adds tasks to a target task list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAddTasksTargetTaskListResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddTasksTargetTaskListResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddTasksTargetTaskListResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INAddTasksTargetTaskListResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inaddtaskstargettasklistresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddTasksTargetTaskListResolutionResult/confirmationRequired(with:forReason:)": {
      "abstract": [
        {
          "text": "Creates an object whose resolution requires the user to confirm the reason for creating a new task list before proceeding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirmationRequired"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTaskList",
          "text": "INTaskList"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "forReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INAddTasksTargetTaskListConfirmationReason",
          "text": "INAddTasksTargetTaskListConfirmationReason"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddTasksTargetTaskListResolutionResult/confirmationRequired(with:forReason:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "confirmationRequiredWithTaskListToConfirm:forReason:"
        }
      ],
      "role": "symbol",
      "title": "confirmationRequired(with:forReason:)",
      "type": "topic",
      "url": "/documentation/intents/inaddtaskstargettasklistresolutionresult/confirmationrequired(with:forreason:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddTasksTargetTaskListResolutionResult/init(taskListResolutionResult:)": {
      "abstract": [
        {
          "text": "Creates an object whose resolution involves successfully matching the specified task list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "taskListResolutionResult"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTaskListResolutionResult",
          "text": "INTaskListResolutionResult"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddTasksTargetTaskListResolutionResult/init(taskListResolutionResult:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTaskListResolutionResult:"
        }
      ],
      "role": "symbol",
      "title": "init(taskListResolutionResult:)",
      "type": "topic",
      "url": "/documentation/intents/inaddtaskstargettasklistresolutionresult/init(tasklistresolutionresult:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAddTasksTemporalEventTriggerResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a temporal event trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAddTasksTemporalEventTriggerResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAddTasksTemporalEventTriggerResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAddTasksTemporalEventTriggerResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INAddTasksTemporalEventTriggerResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inaddtaskstemporaleventtriggerresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDateSearchTypeResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the types of dates supported by a search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INDateSearchTypeResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDateSearchTypeResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDateSearchTypeResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INDateSearchTypeResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/indatesearchtyperesolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a parameter of an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INIntentResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inintentresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INLocationSearchTypeResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for location-based searches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INLocationSearchTypeResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INLocationSearchTypeResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INLocationSearchTypeResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INLocationSearchTypeResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inlocationsearchtyperesolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INNoteContentResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the content of notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INNoteContentResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INNoteContentResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INNoteContentResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INNoteContentResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/innotecontentresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INNoteResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INNoteResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INNoteResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INNoteResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INNoteResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/innoteresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INNotebookItemTypeResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the type of items to look for during a search of notes and tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INNotebookItemTypeResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INNotebookItemTypeResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INNotebookItemTypeResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INNotebookItemTypeResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/innotebookitemtyperesolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetTaskAttributeTemporalEventTriggerResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a temporal event trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetTaskAttributeTemporalEventTriggerResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetTaskAttributeTemporalEventTriggerResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetTaskAttributeTemporalEventTriggerResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INSetTaskAttributeTemporalEventTriggerResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/insettaskattributetemporaleventtriggerresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSnoozeTasksTaskResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for snoozing a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSnoozeTasksTaskResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSnoozeTasksTaskResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSnoozeTasksTaskResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INSnoozeTasksTaskResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/insnoozetaskstaskresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSpatialEventTriggerResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the location-based trigger associated with a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSpatialEventTriggerResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSpatialEventTriggerResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSpatialEventTriggerResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INSpatialEventTriggerResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inspatialeventtriggerresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTaskListResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a list of tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INTaskListResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTaskListResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INTaskListResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INTaskListResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/intasklistresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTaskPriorityResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the priority associated with a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INTaskPriorityResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTaskPriorityResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INTaskPriorityResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INTaskPriorityResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/intaskpriorityresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTaskResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a single task within a task list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INTaskResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTaskResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INTaskResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INTaskResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/intaskresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTaskStatusResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the status of a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INTaskStatusResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTaskStatusResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INTaskStatusResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INTaskStatusResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/intaskstatusresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTemporalEventTriggerResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the time-based trigger associated with a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INTemporalEventTriggerResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTemporalEventTriggerResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INTemporalEventTriggerResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INTemporalEventTriggerResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/intemporaleventtriggerresolutionresult"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INTaskListResolutionResult"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Resolution-Results",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INAddTasksTemporalEventTriggerResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INDateSearchTypeResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INLocationSearchTypeResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INNoteResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INNoteContentResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INNotebookItemTypeResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INSetTaskAttributeTemporalEventTriggerResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INSnoozeTasksTaskResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INSpatialEventTriggerResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INTaskListResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INTaskResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INTaskStatusResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INTemporalEventTriggerResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INTaskPriorityResolutionResult"
      ],
      "title": "Resolution Results"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Resolution-Result",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INAddTasksTargetTaskListResolutionResult/init(taskListResolutionResult:)",
        "doc://com.apple.sirikit/documentation/Intents/INAddTasksTargetTaskListResolutionResult/confirmationRequired(with:forReason:)",
        "doc://com.apple.sirikit/documentation/Intents/INAddTasksTargetTaskListConfirmationReason"
      ],
      "title": "Creating a Resolution Result"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INAddTasksTargetTaskListResolutionResult"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddTasksTargetTaskListResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddTasksTargetTaskListResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Resolution-Result",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INAddTasksTargetTaskListResolutionResult/init(taskListResolutionResult:)",
                "doc://com.apple.sirikit/documentation/Intents/INAddTasksTargetTaskListResolutionResult/confirmationRequired(with:forReason:)",
                "doc://com.apple.sirikit/documentation/Intents/INAddTasksTargetTaskListConfirmationReason"
              ],
              "title": "Creating a Resolution Result"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INTaskListResolutionResult"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Resolution-Results",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INAddTasksTemporalEventTriggerResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INDateSearchTypeResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INLocationSearchTypeResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INNoteResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INNoteContentResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INNotebookItemTypeResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INSetTaskAttributeTemporalEventTriggerResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INSnoozeTasksTaskResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INSpatialEventTriggerResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INTaskListResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INTaskResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INTaskStatusResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INTemporalEventTriggerResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INTaskPriorityResolutionResult"
              ],
              "title": "Resolution Results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INAddTasksTargetTaskListResolutionResult"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INTaskListResolutionResult",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INTaskListResolutionResult",
                    "text": "INTaskListResolutionResult"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetTaskAttributeTemporalEventTriggerResolutionResult/title",
          "value": "INSetTaskAttributeTemporalEventTriggerResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetTaskAttributeTemporalEventTriggerResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetTaskAttributeTemporalEventTriggerResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetTaskAttributeTemporalEventTriggerResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetTaskAttributeTemporalEventTriggerResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateSearchTypeResolutionResult/title",
          "value": "INDateSearchTypeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateSearchTypeResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDateSearchTypeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateSearchTypeResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INDateSearchTypeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpatialEventTriggerResolutionResult/title",
          "value": "INSpatialEventTriggerResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpatialEventTriggerResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSpatialEventTriggerResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpatialEventTriggerResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSpatialEventTriggerResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLocationSearchTypeResolutionResult/title",
          "value": "INLocationSearchTypeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLocationSearchTypeResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INLocationSearchTypeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLocationSearchTypeResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INLocationSearchTypeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNoteResolutionResult/title",
          "value": "INNoteResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNoteResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INNoteResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNoteResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INNoteResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddTasksTargetTaskListResolutionResult~1init(taskListResolutionResult:)/title",
          "value": "initWithTaskListResolutionResult:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddTasksTargetTaskListResolutionResult~1init(taskListResolutionResult:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTaskListResolutionResult:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddTasksTargetTaskListResolutionResult~1confirmationRequired(with:forReason:)/title",
          "value": "confirmationRequiredWithTaskListToConfirm:forReason:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddTasksTargetTaskListResolutionResult~1confirmationRequired(with:forReason:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "confirmationRequiredWithTaskListToConfirm:forReason:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskListResolutionResult/title",
          "value": "INTaskListResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskListResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTaskListResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskListResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTaskListResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNoteContentResolutionResult/title",
          "value": "INNoteContentResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNoteContentResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INNoteContentResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNoteContentResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INNoteContentResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddTasksTemporalEventTriggerResolutionResult/title",
          "value": "INAddTasksTemporalEventTriggerResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddTasksTemporalEventTriggerResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddTasksTemporalEventTriggerResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddTasksTemporalEventTriggerResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddTasksTemporalEventTriggerResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddTasksTargetTaskListConfirmationReason/title",
          "value": "INAddTasksTargetTaskListConfirmationReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddTasksTargetTaskListConfirmationReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddTasksTargetTaskListConfirmationReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddTasksTargetTaskListConfirmationReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddTasksTargetTaskListConfirmationReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTemporalEventTriggerResolutionResult/title",
          "value": "INTemporalEventTriggerResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTemporalEventTriggerResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTemporalEventTriggerResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTemporalEventTriggerResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTemporalEventTriggerResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNotebookItemTypeResolutionResult/title",
          "value": "INNotebookItemTypeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNotebookItemTypeResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INNotebookItemTypeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNotebookItemTypeResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INNotebookItemTypeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskStatusResolutionResult/title",
          "value": "INTaskStatusResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskStatusResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTaskStatusResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskStatusResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTaskStatusResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddTasksTargetTaskListResolutionResult/title",
          "value": "INAddTasksTargetTaskListResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddTasksTargetTaskListResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddTasksTargetTaskListResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAddTasksTargetTaskListResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAddTasksTargetTaskListResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskResolutionResult/title",
          "value": "INTaskResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTaskResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTaskResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSnoozeTasksTaskResolutionResult/title",
          "value": "INSnoozeTasksTaskResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSnoozeTasksTaskResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSnoozeTasksTaskResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSnoozeTasksTaskResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSnoozeTasksTaskResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/title",
          "value": "INIntentResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskPriorityResolutionResult/title",
          "value": "INTaskPriorityResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskPriorityResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTaskPriorityResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTaskPriorityResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTaskPriorityResolutionResult"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inaddtaskstargettasklistresolutionresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inaddtaskstargettasklistresolutionresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
