{
  "abstract": [
    {
      "text": "Constants indicating an account-specific amount to apply to a payment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INAmountType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INAmountType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INAmountType"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INAmountType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INAmountType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INAmountType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAmountType": {
      "abstract": [
        {
          "text": "Constants indicating an account-specific amount to apply to a payment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAmountType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAmountType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAmountType"
        }
      ],
      "role": "symbol",
      "title": "INAmountType",
      "type": "topic",
      "url": "/documentation/intents/inamounttype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAmountType/amountDue": {
      "abstract": [
        {
          "text": "The amount due for the bill.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "amountDue"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAmountType/amountDue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAmountTypeAmountDue"
        }
      ],
      "role": "symbol",
      "title": "INAmountType.amountDue",
      "type": "topic",
      "url": "/documentation/intents/inamounttype/amountdue"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAmountType/currentBalance": {
      "abstract": [
        {
          "text": "The current account balance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentBalance"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAmountType/currentBalance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAmountTypeCurrentBalance"
        }
      ],
      "role": "symbol",
      "title": "INAmountType.currentBalance",
      "type": "topic",
      "url": "/documentation/intents/inamounttype/currentbalance"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAmountType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAmountType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/inamounttype/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAmountType/maximumTransferAmount": {
      "abstract": [
        {
          "text": "The maximum amount the user can transfer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumTransferAmount"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAmountType/maximumTransferAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAmountTypeMaximumTransferAmount"
        }
      ],
      "role": "symbol",
      "title": "INAmountType.maximumTransferAmount",
      "type": "topic",
      "url": "/documentation/intents/inamounttype/maximumtransferamount"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAmountType/minimumDue": {
      "abstract": [
        {
          "text": "The minimum amount the user must apply to the bill.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumDue"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAmountType/minimumDue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAmountTypeMinimumDue"
        }
      ],
      "role": "symbol",
      "title": "INAmountType.minimumDue",
      "type": "topic",
      "url": "/documentation/intents/inamounttype/minimumdue"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAmountType/minimumTransferAmount": {
      "abstract": [
        {
          "text": "The minimum amount the user can transfer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumTransferAmount"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAmountType/minimumTransferAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAmountTypeMinimumTransferAmount"
        }
      ],
      "role": "symbol",
      "title": "INAmountType.minimumTransferAmount",
      "type": "topic",
      "url": "/documentation/intents/inamounttype/minimumtransferamount"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAmountType/statementBalance": {
      "abstract": [
        {
          "text": "The statement balance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statementBalance"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAmountType/statementBalance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAmountTypeStatementBalance"
        }
      ],
      "role": "symbol",
      "title": "INAmountType.statementBalance",
      "type": "topic",
      "url": "/documentation/intents/inamounttype/statementbalance"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAmountType/unknown": {
      "abstract": [
        {
          "text": "An unknown amount.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAmountType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAmountTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "INAmountType.unknown",
      "type": "topic",
      "url": "/documentation/intents/inamounttype/unknown"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentAmount/amount": {
      "abstract": [
        {
          "text": "The precise amount of money to pay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "amount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
          "text": "INCurrencyAmount"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentAmount/amount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "amount"
        }
      ],
      "role": "symbol",
      "title": "amount",
      "type": "topic",
      "url": "/documentation/intents/inpaymentamount/amount"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentAmount/amountType": {
      "abstract": [
        {
          "text": "The account-specific amount to pay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "amountType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INAmountType",
          "text": "INAmountType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentAmount/amountType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "amountType"
        }
      ],
      "role": "symbol",
      "title": "amountType",
      "type": "topic",
      "url": "/documentation/intents/inpaymentamount/amounttype"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Payment-Amount",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPaymentAmount/amount",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentAmount/amountType"
      ],
      "title": "Getting the Payment Amount"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INAmountType/unknown",
        "doc://com.apple.sirikit/documentation/Intents/INAmountType/minimumDue",
        "doc://com.apple.sirikit/documentation/Intents/INAmountType/amountDue",
        "doc://com.apple.sirikit/documentation/Intents/INAmountType/currentBalance",
        "doc://com.apple.sirikit/documentation/Intents/INAmountType/maximumTransferAmount",
        "doc://com.apple.sirikit/documentation/Intents/INAmountType/minimumTransferAmount",
        "doc://com.apple.sirikit/documentation/Intents/INAmountType/statementBalance"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INAmountType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INAmountType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAmountType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAmountType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INAmountType/unknown",
                "doc://com.apple.sirikit/documentation/Intents/INAmountType/minimumDue",
                "doc://com.apple.sirikit/documentation/Intents/INAmountType/amountDue",
                "doc://com.apple.sirikit/documentation/Intents/INAmountType/currentBalance",
                "doc://com.apple.sirikit/documentation/Intents/INAmountType/maximumTransferAmount",
                "doc://com.apple.sirikit/documentation/Intents/INAmountType/minimumTransferAmount",
                "doc://com.apple.sirikit/documentation/Intents/INAmountType/statementBalance"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Payment-Amount",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPaymentAmount/amount",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentAmount/amountType"
              ],
              "title": "Getting the Payment Amount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INAmountType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAmountType~1maximumTransferAmount/title",
          "value": "INAmountTypeMaximumTransferAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAmountType~1maximumTransferAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAmountTypeMaximumTransferAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAmountType~1minimumTransferAmount/title",
          "value": "INAmountTypeMinimumTransferAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAmountType~1minimumTransferAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAmountTypeMinimumTransferAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentAmount~1amountType/title",
          "value": "amountType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentAmount~1amountType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "amountType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAmountType~1unknown/title",
          "value": "INAmountTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAmountType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAmountTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAmountType~1amountDue/title",
          "value": "INAmountTypeAmountDue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAmountType~1amountDue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAmountTypeAmountDue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAmountType~1currentBalance/title",
          "value": "INAmountTypeCurrentBalance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAmountType~1currentBalance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAmountTypeCurrentBalance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentAmount~1amount/title",
          "value": "amount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentAmount~1amount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "amount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAmountType~1statementBalance/title",
          "value": "INAmountTypeStatementBalance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAmountType~1statementBalance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAmountTypeStatementBalance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAmountType~1minimumDue/title",
          "value": "INAmountTypeMinimumDue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAmountType~1minimumDue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAmountTypeMinimumDue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAmountType/title",
          "value": "INAmountType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAmountType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAmountType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAmountType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAmountType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inamounttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inamounttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
