{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponse"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INAnswerCallIntentResponse",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INAnswerCallIntentResponse"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INAnswerCallIntentResponse"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "INAnswerCallIntentResponse"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INAnswerCallIntentResponse"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAnswerCallIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAnswerCallIntent"
        }
      ],
      "role": "symbol",
      "title": "INAnswerCallIntent",
      "type": "topic",
      "url": "/documentation/intents/inanswercallintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentHandling": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAnswerCallIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAnswerCallIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INAnswerCallIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/inanswercallintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAnswerCallIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAnswerCallIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INAnswerCallIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/inanswercallintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponse/callRecords": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callRecords"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCallRecord",
          "text": "INCallRecord"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponse/callRecords",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "callRecords"
        }
      ],
      "role": "symbol",
      "title": "callRecords",
      "type": "topic",
      "url": "/documentation/intents/inanswercallintentresponse/callrecords"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponse/code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INAnswerCallIntentResponseCode",
          "text": "INAnswerCallIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponse/code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "code"
        }
      ],
      "role": "symbol",
      "title": "code",
      "type": "topic",
      "url": "/documentation/intents/inanswercallintentresponse/code"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponse/init(code:userActivity:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INAnswerCallIntentResponseCode",
          "text": "INAnswerCallIntentResponseCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserActivity",
          "text": "NSUserActivity"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponse/init(code:userActivity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCode:userActivity:"
        }
      ],
      "role": "symbol",
      "title": "init(code:userActivity:)",
      "type": "topic",
      "url": "/documentation/intents/inanswercallintentresponse/init(code:useractivity:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponseCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAnswerCallIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAnswerCallIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INAnswerCallIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/inanswercallintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentResponse": {
      "abstract": [
        {
          "text": "Your response to an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/inintentresponse"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentResponse"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Answering-a-Call",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntent",
        "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponseCode"
      ],
      "title": "Answering a Call"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponse/init(code:userActivity:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponse/callRecords",
        "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponse/code"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.2",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INAnswerCallIntentResponse"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAnswerCallIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAnswerCallIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponse/callRecords",
                "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponse/code"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponse/init(code:userActivity:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INIntentResponse"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Answering-a-Call",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntent",
                "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INAnswerCallIntentResponseCode"
              ],
              "title": "Answering a Call"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INAnswerCallIntentResponse"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResponse",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INIntentResponse",
                    "text": "INIntentResponse"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/title",
          "value": "INIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntentResponseCode/title",
          "value": "INAnswerCallIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAnswerCallIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAnswerCallIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntentHandling/title",
          "value": "INAnswerCallIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAnswerCallIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAnswerCallIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntentResponse~1code/title",
          "value": "code"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntentResponse~1code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntentResponse/title",
          "value": "INAnswerCallIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAnswerCallIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAnswerCallIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntentResponse~1init(code:userActivity:)/title",
          "value": "initWithCode:userActivity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntentResponse~1init(code:userActivity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCode:userActivity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntentResponse~1callRecords/title",
          "value": "callRecords"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntentResponse~1callRecords/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "callRecords"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntent/title",
          "value": "INAnswerCallIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAnswerCallIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAnswerCallIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAnswerCallIntent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inanswercallintentresponse"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inanswercallintentresponse"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
