{
  "abstract": [
    {
      "text": "The detailed information associated with a bill.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INBillDetails"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INBillDetails",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INBillDetails"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INBillDetails"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.3",
        "message": "INBillDetails is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.3",
        "message": "INBillDetails is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INBillDetails is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INBillDetails is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "3.2",
        "message": "INBillDetails is deprecated. There is no replacement.",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "INBillDetails"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INBillDetails"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillDetails",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object contains the details surrounding the payment of a bill. You create instances of this class when handling bill payment-related intents. For example, you create instances of this class when searching for the user’s bill payments. The details include the recipient of the funds, the amount that’s due, and the date of payment.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When creating instances of this class, specify as many details as possible. During searches or when paying a bill, Siri may display some of the bill details to the user. Omitting an important piece of information, such as the payee, might cause the user to cancel a bill payment.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillDetails": {
      "abstract": [
        {
          "text": "The detailed information associated with a bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INBillDetails"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillDetails",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillDetails"
        }
      ],
      "role": "symbol",
      "title": "INBillDetails",
      "type": "topic",
      "url": "/documentation/intents/inbilldetails"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillDetails/amountDue": {
      "abstract": [
        {
          "text": "The amount due for the bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "amountDue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
          "text": "INCurrencyAmount"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillDetails/amountDue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "amountDue"
        }
      ],
      "role": "symbol",
      "title": "amountDue",
      "type": "topic",
      "url": "/documentation/intents/inbilldetails/amountdue"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillDetails/billPayee": {
      "abstract": [
        {
          "text": "The entity receiving the payment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "billPayee"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBillPayee",
          "text": "INBillPayee"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillDetails/billPayee",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "billPayee"
        }
      ],
      "role": "symbol",
      "title": "billPayee",
      "type": "topic",
      "url": "/documentation/intents/inbilldetails/billpayee"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillDetails/billType": {
      "abstract": [
        {
          "text": "The type of the bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "billType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INBillType",
          "text": "INBillType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillDetails/billType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "billType"
        }
      ],
      "role": "symbol",
      "title": "billType",
      "type": "topic",
      "url": "/documentation/intents/inbilldetails/billtype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillDetails/dueDate": {
      "abstract": [
        {
          "text": "The due date of the payment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dueDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14DateComponentsV",
          "text": "DateComponents"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillDetails/dueDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dueDate"
        }
      ],
      "role": "symbol",
      "title": "dueDate",
      "type": "topic",
      "url": "/documentation/intents/inbilldetails/duedate"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillDetails/init(billType:paymentStatus:billPayee:amountDue:minimumDue:lateFee:dueDate:paymentDate:)": {
      "abstract": [
        {
          "text": "Initializes a bill details object with information about the bill to pay.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "billType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INBillType",
          "text": "INBillType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "paymentStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPaymentStatus",
          "text": "INPaymentStatus"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "billPayee"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBillPayee",
          "text": "INBillPayee"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "amountDue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
          "text": "INCurrencyAmount"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "minimumDue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
          "text": "INCurrencyAmount"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "lateFee"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
          "text": "INCurrencyAmount"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "dueDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14DateComponentsV",
          "text": "DateComponents"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "paymentDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14DateComponentsV",
          "text": "DateComponents"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillDetails/init(billType:paymentStatus:billPayee:amountDue:minimumDue:lateFee:dueDate:paymentDate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithBillType:paymentStatus:billPayee:amountDue:minimumDue:lateFee:dueDate:paymentDate:"
        }
      ],
      "role": "symbol",
      "title": "init(billType:paymentStatus:billPayee:amountDue:minimumDue:lateFee:dueDate:paymentDate:)",
      "type": "topic",
      "url": "/documentation/intents/inbilldetails/init(billtype:paymentstatus:billpayee:amountdue:minimumdue:latefee:duedate:paymentdate:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillDetails/lateFee": {
      "abstract": [
        {
          "text": "The late fee to apply if the payment is late.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lateFee"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
          "text": "INCurrencyAmount"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillDetails/lateFee",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lateFee"
        }
      ],
      "role": "symbol",
      "title": "lateFee",
      "type": "topic",
      "url": "/documentation/intents/inbilldetails/latefee"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillDetails/minimumDue": {
      "abstract": [
        {
          "text": "The minimum amount to pay toward the bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumDue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
          "text": "INCurrencyAmount"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillDetails/minimumDue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumDue"
        }
      ],
      "role": "symbol",
      "title": "minimumDue",
      "type": "topic",
      "url": "/documentation/intents/inbilldetails/minimumdue"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillDetails/paymentDate": {
      "abstract": [
        {
          "text": "The scheduled payment date for the bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14DateComponentsV",
          "text": "DateComponents"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillDetails/paymentDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentDate"
        }
      ],
      "role": "symbol",
      "title": "paymentDate",
      "type": "topic",
      "url": "/documentation/intents/inbilldetails/paymentdate"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillDetails/paymentStatus": {
      "abstract": [
        {
          "text": "The current status of the payment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPaymentStatus",
          "text": "INPaymentStatus"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillDetails/paymentStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentStatus"
        }
      ],
      "role": "symbol",
      "title": "paymentStatus",
      "type": "topic",
      "url": "/documentation/intents/inbilldetails/paymentstatus"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillPayee": {
      "abstract": [
        {
          "text": "The entity that receives the proceeds from a bill payment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INBillPayee"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillPayee",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillPayee"
        }
      ],
      "role": "symbol",
      "title": "INBillPayee",
      "type": "topic",
      "url": "/documentation/intents/inbillpayee"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillPayeeResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the recipient of a bill payment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INBillPayeeResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillPayeeResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillPayeeResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INBillPayeeResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inbillpayeeresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType": {
      "abstract": [
        {
          "text": "Constants indicating the type of bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INBillType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillType"
        }
      ],
      "role": "symbol",
      "title": "INBillType",
      "type": "topic",
      "url": "/documentation/intents/inbilltype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillTypeResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the types of bills a user might pay.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INBillTypeResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillTypeResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INBillTypeResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inbilltyperesolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVisualCodeTypeResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the type of visual code used to exchange information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVisualCodeTypeResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVisualCodeTypeResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVisualCodeTypeResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INVisualCodeTypeResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/invisualcodetyperesolutionresult"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Bill-Data-Objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INBillPayee",
        "doc://com.apple.sirikit/documentation/Intents/INBillTypeResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INBillPayeeResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INVisualCodeTypeResolutionResult"
      ],
      "title": "Bill Data Objects"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-the-Bill-Details",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INBillDetails/init(billType:paymentStatus:billPayee:amountDue:minimumDue:lateFee:dueDate:paymentDate:)"
      ],
      "title": "Initializing the Bill Details"
    },
    {
      "anchor": "Accessing-the-Bill-Information",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INBillDetails/billPayee",
        "doc://com.apple.sirikit/documentation/Intents/INBillDetails/paymentDate",
        "doc://com.apple.sirikit/documentation/Intents/INBillDetails/paymentStatus",
        "doc://com.apple.sirikit/documentation/Intents/INBillDetails/billType"
      ],
      "title": "Accessing the Bill Information"
    },
    {
      "anchor": "Getting-the-Bill-Amount",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INBillDetails/minimumDue",
        "doc://com.apple.sirikit/documentation/Intents/INBillDetails/amountDue",
        "doc://com.apple.sirikit/documentation/Intents/INBillDetails/dueDate",
        "doc://com.apple.sirikit/documentation/Intents/INBillDetails/lateFee"
      ],
      "title": "Getting the Bill Amount"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INBillType"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INBillDetails"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillDetails"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillDetails"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializing-the-Bill-Details",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INBillDetails/init(billType:paymentStatus:billPayee:amountDue:minimumDue:lateFee:dueDate:paymentDate:)"
              ],
              "title": "Initializing the Bill Details"
            },
            {
              "anchor": "Accessing-the-Bill-Information",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INBillDetails/billPayee",
                "doc://com.apple.sirikit/documentation/Intents/INBillDetails/paymentDate",
                "doc://com.apple.sirikit/documentation/Intents/INBillDetails/paymentStatus",
                "doc://com.apple.sirikit/documentation/Intents/INBillDetails/billType"
              ],
              "title": "Accessing the Bill Information"
            },
            {
              "anchor": "Getting-the-Bill-Amount",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INBillDetails/minimumDue",
                "doc://com.apple.sirikit/documentation/Intents/INBillDetails/amountDue",
                "doc://com.apple.sirikit/documentation/Intents/INBillDetails/dueDate",
                "doc://com.apple.sirikit/documentation/Intents/INBillDetails/lateFee"
              ],
              "title": "Getting the Bill Amount"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INBillType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Bill-Data-Objects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INBillPayee",
                "doc://com.apple.sirikit/documentation/Intents/INBillTypeResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INBillPayeeResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INVisualCodeTypeResolutionResult"
              ],
              "title": "Bill Data Objects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INBillDetails"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType/title",
          "value": "INBillType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails/title",
          "value": "INBillDetails"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillDetails"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillDetails"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillPayeeResolutionResult/title",
          "value": "INBillPayeeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillPayeeResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillPayeeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillPayeeResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillPayeeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1paymentDate/title",
          "value": "paymentDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1paymentDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paymentDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1dueDate/title",
          "value": "dueDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1dueDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dueDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1billPayee/title",
          "value": "billPayee"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1billPayee/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "billPayee"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillPayee/title",
          "value": "INBillPayee"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillPayee/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillPayee"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillPayee/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillPayee"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillTypeResolutionResult/title",
          "value": "INBillTypeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillTypeResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillTypeResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1billType/title",
          "value": "billType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1billType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "billType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1amountDue/title",
          "value": "amountDue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1amountDue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "amountDue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1paymentStatus/title",
          "value": "paymentStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1paymentStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paymentStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1lateFee/title",
          "value": "lateFee"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1lateFee/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lateFee"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1minimumDue/title",
          "value": "minimumDue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1minimumDue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumDue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1init(billType:paymentStatus:billPayee:amountDue:minimumDue:lateFee:dueDate:paymentDate:)/title",
          "value": "initWithBillType:paymentStatus:billPayee:amountDue:minimumDue:lateFee:dueDate:paymentDate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillDetails~1init(billType:paymentStatus:billPayee:amountDue:minimumDue:lateFee:dueDate:paymentDate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithBillType:paymentStatus:billPayee:amountDue:minimumDue:lateFee:dueDate:paymentDate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVisualCodeTypeResolutionResult/title",
          "value": "INVisualCodeTypeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVisualCodeTypeResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVisualCodeTypeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVisualCodeTypeResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVisualCodeTypeResolutionResult"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inbilldetails"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inbilldetails"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
