{
  "abstract": [
    {
      "text": "Constants indicating the type of bill.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INBillType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INBillType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INBillType"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INBillType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.3",
        "message": "INBillType is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.3",
        "message": "INBillType is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INBillType is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INBillType is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "3.2",
        "message": "INBillType is deprecated. There is no replacement.",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INBillType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INBillType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType": {
      "abstract": [
        {
          "text": "Constants indicating the type of bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INBillType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillType"
        }
      ],
      "role": "symbol",
      "title": "INBillType",
      "type": "topic",
      "url": "/documentation/intents/inbilltype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/autoInsurance": {
      "abstract": [
        {
          "text": "An auto insurance bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "autoInsurance"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/autoInsurance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeAutoInsurance"
        }
      ],
      "role": "symbol",
      "title": "INBillType.autoInsurance",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/autoinsurance"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/cable": {
      "abstract": [
        {
          "text": "A cable television bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/cable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeCable"
        }
      ],
      "role": "symbol",
      "title": "INBillType.cable",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/cable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/carLease": {
      "abstract": [
        {
          "text": "A car lease payment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "carLease"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/carLease",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeCarLease"
        }
      ],
      "role": "symbol",
      "title": "INBillType.carLease",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/carlease"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/carLoan": {
      "abstract": [
        {
          "text": "A car loan payment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "carLoan"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/carLoan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeCarLoan"
        }
      ],
      "role": "symbol",
      "title": "INBillType.carLoan",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/carloan"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/creditCard": {
      "abstract": [
        {
          "text": "A credit card bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creditCard"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/creditCard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeCreditCard"
        }
      ],
      "role": "symbol",
      "title": "INBillType.creditCard",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/creditcard"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/electricity": {
      "abstract": [
        {
          "text": "An electricity bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "electricity"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/electricity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeElectricity"
        }
      ],
      "role": "symbol",
      "title": "INBillType.electricity",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/electricity"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/garbageAndRecycling": {
      "abstract": [
        {
          "text": "A garbage and recycling bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "garbageAndRecycling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/garbageAndRecycling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeGarbageAndRecycling"
        }
      ],
      "role": "symbol",
      "title": "INBillType.garbageAndRecycling",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/garbageandrecycling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/gas": {
      "abstract": [
        {
          "text": "A gasoline bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gas"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/gas",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeGas"
        }
      ],
      "role": "symbol",
      "title": "INBillType.gas",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/gas"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/healthInsurance": {
      "abstract": [
        {
          "text": "A health insurance bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "healthInsurance"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/healthInsurance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeHealthInsurance"
        }
      ],
      "role": "symbol",
      "title": "INBillType.healthInsurance",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/healthinsurance"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/homeInsurance": {
      "abstract": [
        {
          "text": "A home insurance bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "homeInsurance"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/homeInsurance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeHomeInsurance"
        }
      ],
      "role": "symbol",
      "title": "INBillType.homeInsurance",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/homeinsurance"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/internet": {
      "abstract": [
        {
          "text": "An internet service bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internet"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/internet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeInternet"
        }
      ],
      "role": "symbol",
      "title": "INBillType.internet",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/internet"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/lifeInsurance": {
      "abstract": [
        {
          "text": "A life insurance payment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lifeInsurance"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/lifeInsurance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeLifeInsurance"
        }
      ],
      "role": "symbol",
      "title": "INBillType.lifeInsurance",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/lifeinsurance"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/mortgage": {
      "abstract": [
        {
          "text": "A mortgage payment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mortgage"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/mortgage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeMortgage"
        }
      ],
      "role": "symbol",
      "title": "INBillType.mortgage",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/mortgage"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/musicStreaming": {
      "abstract": [
        {
          "text": "A music streaming bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "musicStreaming"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/musicStreaming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeMusicStreaming"
        }
      ],
      "role": "symbol",
      "title": "INBillType.musicStreaming",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/musicstreaming"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/phone": {
      "abstract": [
        {
          "text": "A telephone bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phone"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/phone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypePhone"
        }
      ],
      "role": "symbol",
      "title": "INBillType.phone",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/phone"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/rent": {
      "abstract": [
        {
          "text": "A rental payment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/rent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeRent"
        }
      ],
      "role": "symbol",
      "title": "INBillType.rent",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/rent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/sewer": {
      "abstract": [
        {
          "text": "A sewer service payment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sewer"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/sewer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeSewer"
        }
      ],
      "role": "symbol",
      "title": "INBillType.sewer",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/sewer"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/studentLoan": {
      "abstract": [
        {
          "text": "A student loan payment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "studentLoan"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/studentLoan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeStudentLoan"
        }
      ],
      "role": "symbol",
      "title": "INBillType.studentLoan",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/studentloan"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/trafficTicket": {
      "abstract": [
        {
          "text": "A traffic ticket bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trafficTicket"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/trafficTicket",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeTrafficTicket"
        }
      ],
      "role": "symbol",
      "title": "INBillType.trafficTicket",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/trafficticket"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/tuition": {
      "abstract": [
        {
          "text": "A school tuition bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tuition"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/tuition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeTuition"
        }
      ],
      "role": "symbol",
      "title": "INBillType.tuition",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/tuition"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/unknown": {
      "abstract": [
        {
          "text": "An unknown type of bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "INBillType.unknown",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/unknown"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/utilities": {
      "abstract": [
        {
          "text": "A utility bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "utilities"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/utilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeUtilities"
        }
      ],
      "role": "symbol",
      "title": "INBillType.utilities",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/utilities"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBillType/water": {
      "abstract": [
        {
          "text": "A water bill.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "water"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBillType/water",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBillTypeWater"
        }
      ],
      "role": "symbol",
      "title": "INBillType.water",
      "type": "topic",
      "url": "/documentation/intents/inbilltype/water"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INBillType/autoInsurance",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/cable",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/carLease",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/carLoan",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/creditCard",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/electricity",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/garbageAndRecycling",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/gas",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/healthInsurance",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/homeInsurance",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/internet",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/lifeInsurance",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/mortgage",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/musicStreaming",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/phone",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/rent",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/sewer",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/studentLoan",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/trafficTicket",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/tuition",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/unknown",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/utilities",
        "doc://com.apple.sirikit/documentation/Intents/INBillType/water"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INBillType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INBillType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INBillType/autoInsurance",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/cable",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/carLease",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/carLoan",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/creditCard",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/electricity",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/garbageAndRecycling",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/gas",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/healthInsurance",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/homeInsurance",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/internet",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/lifeInsurance",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/mortgage",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/musicStreaming",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/phone",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/rent",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/sewer",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/studentLoan",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/trafficTicket",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/tuition",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/unknown",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/utilities",
                "doc://com.apple.sirikit/documentation/Intents/INBillType/water"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INBillType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1tuition/title",
          "value": "INBillTypeTuition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1tuition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeTuition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1healthInsurance/title",
          "value": "INBillTypeHealthInsurance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1healthInsurance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeHealthInsurance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType/title",
          "value": "INBillType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1electricity/title",
          "value": "INBillTypeElectricity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1electricity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeElectricity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1utilities/title",
          "value": "INBillTypeUtilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1utilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeUtilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1carLoan/title",
          "value": "INBillTypeCarLoan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1carLoan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeCarLoan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1lifeInsurance/title",
          "value": "INBillTypeLifeInsurance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1lifeInsurance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeLifeInsurance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1autoInsurance/title",
          "value": "INBillTypeAutoInsurance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1autoInsurance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeAutoInsurance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1gas/title",
          "value": "INBillTypeGas"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1gas/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeGas"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1homeInsurance/title",
          "value": "INBillTypeHomeInsurance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1homeInsurance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeHomeInsurance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1water/title",
          "value": "INBillTypeWater"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1water/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeWater"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1phone/title",
          "value": "INBillTypePhone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1phone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypePhone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1musicStreaming/title",
          "value": "INBillTypeMusicStreaming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1musicStreaming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeMusicStreaming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1trafficTicket/title",
          "value": "INBillTypeTrafficTicket"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1trafficTicket/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeTrafficTicket"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1sewer/title",
          "value": "INBillTypeSewer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1sewer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeSewer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1rent/title",
          "value": "INBillTypeRent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1rent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeRent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1mortgage/title",
          "value": "INBillTypeMortgage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1mortgage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeMortgage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1studentLoan/title",
          "value": "INBillTypeStudentLoan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1studentLoan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeStudentLoan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1garbageAndRecycling/title",
          "value": "INBillTypeGarbageAndRecycling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1garbageAndRecycling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeGarbageAndRecycling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1carLease/title",
          "value": "INBillTypeCarLease"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1carLease/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeCarLease"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1creditCard/title",
          "value": "INBillTypeCreditCard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1creditCard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeCreditCard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1internet/title",
          "value": "INBillTypeInternet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1internet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeInternet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1cable/title",
          "value": "INBillTypeCable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1cable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeCable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1unknown/title",
          "value": "INBillTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBillType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBillTypeUnknown"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inbilltype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inbilltype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
