{
  "abstract": [
    {
      "text": "The handler interface booking a reservation that the user selected.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INBookRestaurantReservationIntentHandling",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INBookRestaurantReservationIntentHandling"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INBookRestaurantReservationIntentHandling"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "INBookRestaurantReservationIntentHandling"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntentHandling"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the methods of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol to resolve, confirm, and handle requests to book a reservation based on the provided information. The system delivers an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to your handler with the reservation details, including the restaurant, date, party size, and any special offers selected by the user. Use that intent object to complete the reservation in your system and to communicate the reservation details to the restaurant itself.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Maps does not require you to resolve or confirm the contents of a get available restaurant reservation bookings intent before handling it. User interactions drive the selection of data in Maps, ensuring that the data Maps places into an intent object is already valid.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntent": {
      "abstract": [
        {
          "text": "A request to create a reservation at the specified restaurant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INBookRestaurantReservationIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBookRestaurantReservationIntent"
        }
      ],
      "role": "symbol",
      "title": "INBookRestaurantReservationIntent",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface booking a reservation that the user selected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INBookRestaurantReservationIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBookRestaurantReservationIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INBookRestaurantReservationIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/confirm(bookRestaurantReservation:completion:)": {
      "abstract": [
        {
          "text": "Confirms whether you can complete the reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirm"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bookRestaurantReservation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBookRestaurantReservationIntent",
          "text": "INBookRestaurantReservationIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBookRestaurantReservationIntentResponse",
          "text": "INBookRestaurantReservationIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/confirm(bookRestaurantReservation:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "confirmBookRestaurantReservation:completion:"
        }
      ],
      "role": "symbol",
      "title": "confirm(bookRestaurantReservation:completion:)",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintenthandling/confirm(bookrestaurantreservation:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/handle(bookRestaurantReservation:completion:)": {
      "abstract": [
        {
          "text": "Handles completing the user’s reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bookRestaurantReservation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBookRestaurantReservationIntent",
          "text": "INBookRestaurantReservationIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBookRestaurantReservationIntentResponse",
          "text": "INBookRestaurantReservationIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/handle(bookRestaurantReservation:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleBookRestaurantReservation:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handle(bookRestaurantReservation:completion:)",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintenthandling/handle(bookrestaurantreservation:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolveBookingDateComponents(for:completion:)": {
      "abstract": [
        {
          "text": "Resolves the date of the reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveBookingDateComponents"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBookRestaurantReservationIntent",
          "text": "INBookRestaurantReservationIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INDateComponentsResolutionResult",
          "text": "INDateComponentsResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolveBookingDateComponents(for:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveBookingDateComponentsForBookRestaurantReservation:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveBookingDateComponents(for:completion:)",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintenthandling/resolvebookingdatecomponents(for:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolveGuest(for:completion:)": {
      "abstract": [
        {
          "text": "Resolves the identity of the guest associated with the reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveGuest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBookRestaurantReservationIntent",
          "text": "INBookRestaurantReservationIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INRestaurantGuestResolutionResult",
          "text": "INRestaurantGuestResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolveGuest(for:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveGuestForBookRestaurantReservation:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveGuest(for:completion:)",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintenthandling/resolveguest(for:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolveGuestProvidedSpecialRequestText(for:completion:)": {
      "abstract": [
        {
          "text": "Resolves any special requests made in connection with the reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveGuestProvidedSpecialRequestText"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBookRestaurantReservationIntent",
          "text": "INBookRestaurantReservationIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INStringResolutionResult",
          "text": "INStringResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolveGuestProvidedSpecialRequestText(for:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveGuestProvidedSpecialRequestTextForBookRestaurantReservation:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveGuestProvidedSpecialRequestText(for:completion:)",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintenthandling/resolveguestprovidedspecialrequesttext(for:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolvePartySize(for:completion:)": {
      "abstract": [
        {
          "text": "Resolves the number of people in the user’s party.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolvePartySize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBookRestaurantReservationIntent",
          "text": "INBookRestaurantReservationIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INIntegerResolutionResult",
          "text": "INIntegerResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolvePartySize(for:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolvePartySizeForBookRestaurantReservation:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolvePartySize(for:completion:)",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintenthandling/resolvepartysize(for:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolveRestaurant(for:completion:)": {
      "abstract": [
        {
          "text": "Resolves the restaurant associated with the reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveRestaurant"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBookRestaurantReservationIntent",
          "text": "INBookRestaurantReservationIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INRestaurantResolutionResult",
          "text": "INRestaurantResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolveRestaurant(for:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveRestaurantForBookRestaurantReservation:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveRestaurant(for:completion:)",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintenthandling/resolverestaurant(for:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a book restaurant reservation intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INBookRestaurantReservationIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBookRestaurantReservationIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INBookRestaurantReservationIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintentresponse"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Book-Restaurant-Reservation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntent",
        "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentResponse"
      ],
      "title": "Book Restaurant Reservation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Resolving-the-Intent-Parameters",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolveRestaurant(for:completion:)",
        "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolveBookingDateComponents(for:completion:)",
        "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolvePartySize(for:completion:)",
        "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolveGuest(for:completion:)",
        "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolveGuestProvidedSpecialRequestText(for:completion:)"
      ],
      "title": "Resolving the Intent Parameters"
    },
    {
      "anchor": "Confirming-the-Response",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/confirm(bookRestaurantReservation:completion:)"
      ],
      "title": "Confirming the Response"
    },
    {
      "anchor": "Handling-the-Intent",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/handle(bookRestaurantReservation:completion:)"
      ],
      "title": "Handling the Intent"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INBookRestaurantReservationIntentHandling"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Resolving-the-Intent-Parameters",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolveRestaurant(for:completion:)",
                "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolveBookingDateComponents(for:completion:)",
                "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolvePartySize(for:completion:)",
                "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolveGuest(for:completion:)",
                "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/resolveGuestProvidedSpecialRequestText(for:completion:)"
              ],
              "title": "Resolving the Intent Parameters"
            },
            {
              "anchor": "Confirming-the-Response",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/confirm(bookRestaurantReservation:completion:)"
              ],
              "title": "Confirming the Response"
            },
            {
              "anchor": "Handling-the-Intent",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentHandling/handle(bookRestaurantReservation:completion:)"
              ],
              "title": "Handling the Intent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Book-Restaurant-Reservation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntent",
                "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentResponse"
              ],
              "title": "Book Restaurant Reservation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INBookRestaurantReservationIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntent/title",
          "value": "INBookRestaurantReservationIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentHandling~1resolveBookingDateComponents(for:completion:)/title",
          "value": "resolveBookingDateComponentsForBookRestaurantReservation:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentHandling~1resolveBookingDateComponents(for:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveBookingDateComponentsForBookRestaurantReservation:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentHandling~1resolveRestaurant(for:completion:)/title",
          "value": "resolveRestaurantForBookRestaurantReservation:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentHandling~1resolveRestaurant(for:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveRestaurantForBookRestaurantReservation:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentHandling~1resolveGuestProvidedSpecialRequestText(for:completion:)/title",
          "value": "resolveGuestProvidedSpecialRequestTextForBookRestaurantReservation:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentHandling~1resolveGuestProvidedSpecialRequestText(for:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveGuestProvidedSpecialRequestTextForBookRestaurantReservation:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentHandling~1resolvePartySize(for:completion:)/title",
          "value": "resolvePartySizeForBookRestaurantReservation:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentHandling~1resolvePartySize(for:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolvePartySizeForBookRestaurantReservation:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentHandling~1resolveGuest(for:completion:)/title",
          "value": "resolveGuestForBookRestaurantReservation:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentHandling~1resolveGuest(for:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveGuestForBookRestaurantReservation:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentResponse/title",
          "value": "INBookRestaurantReservationIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentHandling~1handle(bookRestaurantReservation:completion:)/title",
          "value": "handleBookRestaurantReservation:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentHandling~1handle(bookRestaurantReservation:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleBookRestaurantReservation:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentHandling/title",
          "value": "INBookRestaurantReservationIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentHandling~1confirm(bookRestaurantReservation:completion:)/title",
          "value": "confirmBookRestaurantReservation:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentHandling~1confirm(bookRestaurantReservation:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "confirmBookRestaurantReservation:completion:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inbookrestaurantreservationintenthandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inbookrestaurantreservationintenthandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
