{
  "abstract": [
    {
      "text": "The details about a call handled by your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INCallRecord"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INCallRecord",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INCallRecord"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INCallRecord"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "INCallRecord"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INCallRecord"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "code": "INCallRecord",
              "type": "codeVoice"
            },
            {
              "text": " object stores details about calls made by the user through your app. You use call record objects to communicate basic information about calls to SiriKit. A call record identifies the type of call, the duration of the call, the date and time of the call, and the person on the other end of the call. You create call record objects when reporting search results back to SiriKit and when identifying voicemails to play.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallCapability": {
      "abstract": [
        {
          "text": "Constants indicating the capabilities of the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCallCapability"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallCapability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallCapability"
        }
      ],
      "role": "symbol",
      "title": "INCallCapability",
      "type": "topic",
      "url": "/documentation/intents/incallcapability"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType": {
      "abstract": [
        {
          "text": "Constants describing the destination of a call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCallDestinationType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallDestinationType"
        }
      ],
      "role": "symbol",
      "title": "INCallDestinationType",
      "type": "topic",
      "url": "/documentation/intents/incalldestinationtype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallGroup": {
      "abstract": [
        {
          "text": "The details of a group call handled by your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCallGroup"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallGroup"
        }
      ],
      "role": "symbol",
      "title": "INCallGroup",
      "type": "topic",
      "url": "/documentation/intents/incallgroup"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord": {
      "abstract": [
        {
          "text": "The details about a call handled by your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCallRecord"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallRecord"
        }
      ],
      "role": "symbol",
      "title": "INCallRecord",
      "type": "topic",
      "url": "/documentation/intents/incallrecord"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/callCapability": {
      "abstract": [
        {
          "text": "The audio and video capabilities of the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callCapability"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCallCapability",
          "text": "INCallCapability"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/callCapability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "callCapability"
        }
      ],
      "role": "symbol",
      "title": "callCapability",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/callcapability"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/callDuration-2d9u1": {
      "abstract": [
        {
          "text": "The duration (measured in seconds) of the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "callDuration"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/callDuration-2d9u1",
      "kind": "symbol",
      "role": "symbol",
      "title": "callDuration",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/callduration-2d9u1"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/callDuration-47iud": {
      "abstract": [
        {
          "text": "The duration (measured in seconds) of the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/callDuration-47iud",
      "kind": "symbol",
      "role": "symbol",
      "title": "callDuration",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/callduration-47iud"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/callRecordType": {
      "abstract": [
        {
          "text": "The type of call that resulted from the attempt.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callRecordType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCallRecordType",
          "text": "INCallRecordType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/callRecordType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "callRecordType"
        }
      ],
      "role": "symbol",
      "title": "callRecordType",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/callrecordtype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/caller": {
      "abstract": [
        {
          "text": "The person who participated in the call with the current user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "caller"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPerson",
          "text": "INPerson"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/caller",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "caller"
        }
      ],
      "role": "symbol",
      "title": "caller",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/caller"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/dateCreated": {
      "abstract": [
        {
          "text": "The date and time at which the call was initiated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dateCreated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/dateCreated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dateCreated"
        }
      ],
      "role": "symbol",
      "title": "dateCreated",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/datecreated"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/identifier": {
      "abstract": [
        {
          "text": "A unique string that you can use to locate the call in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/identifier"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/init(identifier:dateCreated:caller:callRecordType:callCapability:callDuration:unseen:numberOfCalls:)": {
      "abstract": [
        {
          "text": "Creates a call record with the details about the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dateCreated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "caller"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPerson",
          "text": "INPerson"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "callRecordType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCallRecordType",
          "text": "INCallRecordType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "callCapability"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCallCapability",
          "text": "INCallCapability"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "callDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "unseen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "numberOfCalls"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/init(identifier:dateCreated:caller:callRecordType:callCapability:callDuration:unseen:numberOfCalls:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(identifier:dateCreated:caller:callRecordType:callCapability:callDuration:unseen:numberOfCalls:)",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/init(identifier:datecreated:caller:callrecordtype:callcapability:callduration:unseen:numberofcalls:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:": {
      "abstract": [
        {
          "text": "Creates a call record with the details about the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:"
        }
      ],
      "role": "symbol",
      "title": "initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/initwithidentifier:datecreated:callrecordtype:callcapability:callduration:unseen:"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:numberOfCalls:": {
      "abstract": [
        {
          "text": "Creates a call record with the details about the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:numberOfCalls:"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:numberOfCalls:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:numberOfCalls:"
        }
      ],
      "role": "symbol",
      "title": "initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:numberOfCalls:",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/initwithidentifier:datecreated:callrecordtype:callcapability:callduration:unseen:numberofcalls:"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:participants:numberOfCalls:isCallerIdBlocked:": {
      "abstract": [
        {
          "text": "Creates a call record with the details about the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:participants:numberOfCalls:isCallerIdBlocked:"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:participants:numberOfCalls:isCallerIdBlocked:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:participants:numberOfCalls:isCallerIdBlocked:"
        }
      ],
      "role": "symbol",
      "title": "initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:participants:numberOfCalls:isCallerIdBlocked:",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/initwithidentifier:datecreated:callrecordtype:callcapability:callduration:unseen:participants:numberofcalls:iscalleridblocked:"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/initWithIdentifier:dateCreated:caller:callRecordType:callCapability:callDuration:unseen:": {
      "abstract": [
        {
          "text": "Initializes a call record with the details about the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithIdentifier:dateCreated:caller:callRecordType:callCapability:callDuration:unseen:"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/initWithIdentifier:dateCreated:caller:callRecordType:callCapability:callDuration:unseen:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithIdentifier:dateCreated:caller:callRecordType:callCapability:callDuration:unseen:"
        }
      ],
      "role": "symbol",
      "title": "initWithIdentifier:dateCreated:caller:callRecordType:callCapability:callDuration:unseen:",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/initwithidentifier:datecreated:caller:callrecordtype:callcapability:callduration:unseen:"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/initWithIdentifier:dateCreated:caller:callRecordType:callCapability:callDuration:unseen:numberOfCalls:": {
      "abstract": [
        {
          "text": "Initializes a call record with the details about the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithIdentifier:dateCreated:caller:callRecordType:callCapability:callDuration:unseen:numberOfCalls:"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/initWithIdentifier:dateCreated:caller:callRecordType:callCapability:callDuration:unseen:numberOfCalls:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithIdentifier:dateCreated:caller:callRecordType:callCapability:callDuration:unseen:numberOfCalls:"
        }
      ],
      "role": "symbol",
      "title": "initWithIdentifier:dateCreated:caller:callRecordType:callCapability:callDuration:unseen:numberOfCalls:",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/initwithidentifier:datecreated:caller:callrecordtype:callcapability:callduration:unseen:numberofcalls:"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/isCallerIdBlocked": {
      "abstract": [
        {
          "text": "A Boolean value indicating if user’s callerID is showing during a call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "isCallerIdBlocked"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/isCallerIdBlocked",
      "kind": "symbol",
      "role": "symbol",
      "title": "isCallerIdBlocked",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/iscalleridblocked"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/numberOfCalls-7vv6o": {
      "abstract": [
        {
          "text": "The number of calls in the call record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "numberOfCalls"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/numberOfCalls-7vv6o",
      "kind": "symbol",
      "role": "symbol",
      "title": "numberOfCalls",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/numberofcalls-7vv6o"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/numberOfCalls-r8kl": {
      "abstract": [
        {
          "text": "The number of calls in the call record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfCalls"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/numberOfCalls-r8kl",
      "kind": "symbol",
      "role": "symbol",
      "title": "numberOfCalls",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/numberofcalls-r8kl"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/participants": {
      "abstract": [
        {
          "text": "The recipient of the user’s call request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "participants"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPerson",
          "text": "INPerson"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/participants",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "participants"
        }
      ],
      "role": "symbol",
      "title": "participants",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/participants"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/unseen-2m7sz": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the user has seen the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unseen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/unseen-2m7sz",
      "kind": "symbol",
      "role": "symbol",
      "title": "unseen",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/unseen-2m7sz"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecord/unseen-8qab3": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the user has seen the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "unseen"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecord/unseen-8qab3",
      "kind": "symbol",
      "role": "symbol",
      "title": "unseen",
      "type": "topic",
      "url": "/documentation/intents/incallrecord/unseen-8qab3"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecordFilter": {
      "abstract": [
        {
          "text": "Filters a user specifies to redial a call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCallRecordFilter"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecordFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallRecordFilter"
        }
      ],
      "role": "symbol",
      "title": "INCallRecordFilter",
      "type": "topic",
      "url": "/documentation/intents/incallrecordfilter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecordType": {
      "abstract": [
        {
          "text": "Constants describing the type of the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCallRecordType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecordType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallRecordType"
        }
      ],
      "role": "symbol",
      "title": "INCallRecordType",
      "type": "topic",
      "url": "/documentation/intents/incallrecordtype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecordTypeOptions": {
      "abstract": [
        {
          "text": "Constants describing the types of calls to include during a search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCallRecordTypeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecordTypeOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallRecordTypeOptions"
        }
      ],
      "role": "symbol",
      "title": "INCallRecordTypeOptions",
      "type": "topic",
      "url": "/documentation/intents/incallrecordtypeoptions"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Describing-a-Call",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCallGroup",
        "doc://com.apple.sirikit/documentation/Intents/INCallRecordFilter",
        "doc://com.apple.sirikit/documentation/Intents/INCallRecordType",
        "doc://com.apple.sirikit/documentation/Intents/INCallRecordTypeOptions",
        "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType"
      ],
      "title": "Describing a Call"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-a-Call-Record",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCallRecord/init(identifier:dateCreated:caller:callRecordType:callCapability:callDuration:unseen:numberOfCalls:)"
      ],
      "title": "Initializing a Call Record"
    },
    {
      "anchor": "Identifying-the-Call",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCallRecord/identifier"
      ],
      "title": "Identifying the Call"
    },
    {
      "anchor": "Identifying-the-Caller",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCallRecord/caller"
      ],
      "title": "Identifying the Caller"
    },
    {
      "anchor": "Getting-the-Call-Details",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCallRecord/callRecordType",
        "doc://com.apple.sirikit/documentation/Intents/INCallRecord/callCapability",
        "doc://com.apple.sirikit/documentation/Intents/INCallCapability",
        "doc://com.apple.sirikit/documentation/Intents/INCallRecord/dateCreated",
        "doc://com.apple.sirikit/documentation/Intents/INCallRecord/callDuration-47iud",
        "doc://com.apple.sirikit/documentation/Intents/INCallRecord/unseen-2m7sz",
        "doc://com.apple.sirikit/documentation/Intents/INCallRecord/numberOfCalls-r8kl",
        "doc://com.apple.sirikit/documentation/Intents/INCallRecord/participants"
      ],
      "title": "Getting the Call Details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INCallRecord"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializing-a-Call-Record",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INCallRecord/initWithIdentifier:dateCreated:caller:callRecordType:callCapability:callDuration:unseen:numberOfCalls:",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecord/initWithIdentifier:dateCreated:caller:callRecordType:callCapability:callDuration:unseen:",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecord/initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecord/initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:numberOfCalls:",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecord/initWithIdentifier:dateCreated:callRecordType:callCapability:callDuration:unseen:participants:numberOfCalls:isCallerIdBlocked:"
              ],
              "title": "Initializing a Call Record"
            },
            {
              "anchor": "Identifying-the-Call",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INCallRecord/identifier"
              ],
              "title": "Identifying the Call"
            },
            {
              "anchor": "Identifying-the-Caller",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INCallRecord/caller"
              ],
              "title": "Identifying the Caller"
            },
            {
              "anchor": "Getting-the-Call-Details",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INCallRecord/callRecordType",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecord/callCapability",
                "doc://com.apple.sirikit/documentation/Intents/INCallCapability",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecord/dateCreated",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecord/callDuration-2d9u1",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecord/unseen-8qab3",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecord/numberOfCalls-7vv6o",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecord/participants",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecord/isCallerIdBlocked"
              ],
              "title": "Getting the Call Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Describing-a-Call",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INCallGroup",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecordFilter",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecordType",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecordTypeOptions",
                "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType"
              ],
              "title": "Describing a Call"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INCallRecord"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallCapability/title",
          "value": "INCallCapability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallCapability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallCapability/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecord~1dateCreated/title",
          "value": "dateCreated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecord~1dateCreated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dateCreated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecord~1caller/title",
          "value": "caller"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecord~1caller/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "caller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordTypeOptions/title",
          "value": "INCallRecordTypeOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordTypeOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordTypeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordTypeOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordTypeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordFilter/title",
          "value": "INCallRecordFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecord~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecord~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallGroup/title",
          "value": "INCallGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecord/title",
          "value": "INCallRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType/title",
          "value": "INCallRecordType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecord~1callCapability/title",
          "value": "callCapability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecord~1callCapability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "callCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecord~1participants/title",
          "value": "participants"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecord~1participants/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "participants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType/title",
          "value": "INCallDestinationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallDestinationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallDestinationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecord~1callRecordType/title",
          "value": "callRecordType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecord~1callRecordType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "callRecordType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/incallrecord"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/incallrecord"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
