{
  "abstract": [
    {
      "text": "An interface for adopting all of the protocols in the CarPlay domain.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please conform to INSetAudioSourceInCarIntentHandling, INSetClimateSettingsInCarIntentHandling, INSetDefrosterSettingsInCarIntentHandling, INSetSeatSettingsInCarIntentHandling, INSetProfileInCarIntentHandling and INSaveProfileInCarIntentHandling instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INCarPlayDomainHandling",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INCarPlayDomainHandling"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INCarPlayDomainHandling"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "10.0",
        "message": "Please conform to INSetAudioSourceInCarIntentHandling, INSetClimateSettingsInCarIntentHandling, INSetDefrosterSettingsInCarIntentHandling, INSetSeatSettingsInCarIntentHandling, INSetProfileInCarIntentHandling and INSaveProfileInCarIntentHandling instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "10.0",
        "message": "Please conform to INSetAudioSourceInCarIntentHandling, INSetClimateSettingsInCarIntentHandling, INSetDefrosterSettingsInCarIntentHandling, INSetSeatSettingsInCarIntentHandling, INSetProfileInCarIntentHandling and INSaveProfileInCarIntentHandling instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Please conform to INSetAudioSourceInCarIntentHandling, INSetClimateSettingsInCarIntentHandling, INSetDefrosterSettingsInCarIntentHandling, INSetSeatSettingsInCarIntentHandling, INSetProfileInCarIntentHandling and INSaveProfileInCarIntentHandling instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please conform to INSetAudioSourceInCarIntentHandling, INSetClimateSettingsInCarIntentHandling, INSetDefrosterSettingsInCarIntentHandling, INSetSeatSettingsInCarIntentHandling, INSetProfileInCarIntentHandling and INSaveProfileInCarIntentHandling instead",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "INCarPlayDomainHandling"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INCarPlayDomainHandling"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSaveProfileInCarIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INSaveProfileInCarIntentHandling",
              "text": "INSaveProfileInCarIntentHandling"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetAudioSourceInCarIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INSetAudioSourceInCarIntentHandling",
              "text": "INSetAudioSourceInCarIntentHandling"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INSetClimateSettingsInCarIntentHandling",
              "text": "INSetClimateSettingsInCarIntentHandling"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INSetDefrosterSettingsInCarIntentHandling",
              "text": "INSetDefrosterSettingsInCarIntentHandling"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetProfileInCarIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INSetProfileInCarIntentHandling",
              "text": "INSetProfileInCarIntentHandling"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INSetSeatSettingsInCarIntentHandling",
              "text": "INSetSeatSettingsInCarIntentHandling"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol is a convenience protocol that adopts all of the protocols used to handle CarPlay-related intents. When your app adopts all of the protocols associated with CarPlay, you can adopt this one protocol instead of adopting the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetAudioSourceInCarIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetProfileInCarIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSaveProfileInCarIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocols separately.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "An object that adopts this protocol must be able to respond to the following intents:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetAudioSourceInCarIntent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", a request to change the audio source.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", a request to change the climate control settings.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", a request to change the defroster settings.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", a request to change the seat temperature settings.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetProfileInCarIntent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", a request to configure the car with the specified profile information.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSaveProfileInCarIntent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", a request to save the current settings to a designated profile.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Your handler object must be prepared to resolve any parameters associated with these intents and to confirm and handle the requests. When confirming and handling a request, you provide the response object that matches the specified intent.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallsDomainHandling": {
      "abstract": [
        {
          "text": "Provides a convenient way to adopt all of the protocols in the VoIP calling domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCallsDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallsDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallsDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INCallsDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/incallsdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarCommandsDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all the handling protocols in the car commands domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarCommandsDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarCommandsDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarCommandsDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INCarCommandsDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/incarcommandsdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the CarPlay domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarPlayDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarPlayDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INCarPlayDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/incarplaydomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessagesDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the messages domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMessagesDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessagesDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessagesDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INMessagesDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inmessagesdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INNotebookDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the lists and notes domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INNotebookDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INNotebookDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INNotebookDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INNotebookDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/innotebookdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentsDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the payments domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPaymentsDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentsDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentsDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INPaymentsDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inpaymentsdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotosDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the photos domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPhotosDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotosDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotosDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INPhotosDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inphotosdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRadioDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the radio domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRadioDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRadioDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRadioDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INRadioDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inradiodomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRidesharingDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the ride-booking domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRidesharingDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRidesharingDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRidesharingDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INRidesharingDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inridesharingdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSaveProfileInCarIntent": {
      "abstract": [
        {
          "text": "A request to save the user’s vehicle environment settings in a CarPlay-enabled vehicle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSaveProfileInCarIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSaveProfileInCarIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSaveProfileInCarIntent"
        }
      ],
      "role": "symbol",
      "title": "INSaveProfileInCarIntent",
      "type": "topic",
      "url": "/documentation/intents/insaveprofileincarintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSaveProfileInCarIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for saving vehicle environment settings to a user-specified profile.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSaveProfileInCarIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSaveProfileInCarIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSaveProfileInCarIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSaveProfileInCarIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insaveprofileincarintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetAudioSourceInCarIntent": {
      "abstract": [
        {
          "text": "A request to change the source of audio playback in a CarPlay-enabled vehicle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetAudioSourceInCarIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetAudioSourceInCarIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetAudioSourceInCarIntent"
        }
      ],
      "role": "symbol",
      "title": "INSetAudioSourceInCarIntent",
      "type": "topic",
      "url": "/documentation/intents/insetaudiosourceincarintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetAudioSourceInCarIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for changing a vehicle’s audio source.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetAudioSourceInCarIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetAudioSourceInCarIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetAudioSourceInCarIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSetAudioSourceInCarIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insetaudiosourceincarintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent": {
      "abstract": [
        {
          "text": "A request to change the climate settings in a CarPlay-enabled vehicle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetClimateSettingsInCarIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetClimateSettingsInCarIntent"
        }
      ],
      "role": "symbol",
      "title": "INSetClimateSettingsInCarIntent",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for changing a vehicle’s climate control settings.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetClimateSettingsInCarIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetClimateSettingsInCarIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSetClimateSettingsInCarIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent": {
      "abstract": [
        {
          "text": "A request to change the defroster settings in a CarPlay-enabled vehicle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetDefrosterSettingsInCarIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetDefrosterSettingsInCarIntent"
        }
      ],
      "role": "symbol",
      "title": "INSetDefrosterSettingsInCarIntent",
      "type": "topic",
      "url": "/documentation/intents/insetdefrostersettingsincarintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for changing a vehicle’s defroster settings.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetDefrosterSettingsInCarIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetDefrosterSettingsInCarIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSetDefrosterSettingsInCarIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insetdefrostersettingsincarintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetProfileInCarIntent": {
      "abstract": [
        {
          "text": "A request to change the user’s vehicle environment settings to the ones from the specified profile.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetProfileInCarIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetProfileInCarIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetProfileInCarIntent"
        }
      ],
      "role": "symbol",
      "title": "INSetProfileInCarIntent",
      "type": "topic",
      "url": "/documentation/intents/insetprofileincarintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetProfileInCarIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for restoring vehicle environment settings from a user-specified profile.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetProfileInCarIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetProfileInCarIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetProfileInCarIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSetProfileInCarIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insetprofileincarintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent": {
      "abstract": [
        {
          "text": "A request to change the seat-related settings in a CarPlay-enabled vehicle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntent"
        }
      ],
      "role": "symbol",
      "title": "INSetSeatSettingsInCarIntent",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for changing a vehicle’s seat-related settings.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSetSeatSettingsInCarIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVisualCodeDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the visual codes domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVisualCodeDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVisualCodeDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVisualCodeDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INVisualCodeDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/invisualcodedomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutsDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the workouts domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INWorkoutsDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutsDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutsDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INWorkoutsDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inworkoutsdomainhandling"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSaveProfileInCarIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INSetAudioSourceInCarIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INSetProfileInCarIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Domain-Handling-Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMessagesDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INNotebookDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutsDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentsDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INCallsDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INVisualCodeDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INPhotosDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INRidesharingDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INCarCommandsDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INRadioDomainHandling"
      ],
      "title": "Domain-Handling Protocols"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INCarPlayDomainHandling"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarPlayDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarPlayDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSaveProfileInCarIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INSetAudioSourceInCarIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INSetProfileInCarIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Domain-Handling-Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMessagesDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INNotebookDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutsDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentsDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INCallsDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INVisualCodeDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INPhotosDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INRidesharingDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INCarCommandsDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INRadioDomainHandling"
              ],
              "title": "Domain-Handling Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INCarPlayDomainHandling"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetAudioSourceInCarIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INSetAudioSourceInCarIntentHandling",
                    "text": "INSetAudioSourceInCarIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INSetClimateSettingsInCarIntentHandling",
                    "text": "INSetClimateSettingsInCarIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INSetDefrosterSettingsInCarIntentHandling",
                    "text": "INSetDefrosterSettingsInCarIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INSetSeatSettingsInCarIntentHandling",
                    "text": "INSetSeatSettingsInCarIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetProfileInCarIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INSetProfileInCarIntentHandling",
                    "text": "INSetProfileInCarIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INSaveProfileInCarIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INSaveProfileInCarIntentHandling",
                    "text": "INSaveProfileInCarIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please conform to INSetAudioSourceInCarIntentHandling, INSetClimateSettingsInCarIntentHandling, INSetDefrosterSettingsInCarIntentHandling, INSetSeatSettingsInCarIntentHandling, INSetProfileInCarIntentHandling and INSaveProfileInCarIntentHandling instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutsDomainHandling/title",
          "value": "INWorkoutsDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutsDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutsDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntent/title",
          "value": "INSetClimateSettingsInCarIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetClimateSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetClimateSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNotebookDomainHandling/title",
          "value": "INNotebookDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNotebookDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INNotebookDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNotebookDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INNotebookDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSaveProfileInCarIntentHandling/title",
          "value": "INSaveProfileInCarIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSaveProfileInCarIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSaveProfileInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSaveProfileInCarIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSaveProfileInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRadioDomainHandling/title",
          "value": "INRadioDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRadioDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRadioDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRadioDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRadioDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetAudioSourceInCarIntentHandling/title",
          "value": "INSetAudioSourceInCarIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetAudioSourceInCarIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetAudioSourceInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetAudioSourceInCarIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetAudioSourceInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarCommandsDomainHandling/title",
          "value": "INCarCommandsDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarCommandsDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarCommandsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarCommandsDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarCommandsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSaveProfileInCarIntent/title",
          "value": "INSaveProfileInCarIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSaveProfileInCarIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSaveProfileInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSaveProfileInCarIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSaveProfileInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessagesDomainHandling/title",
          "value": "INMessagesDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessagesDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessagesDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessagesDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessagesDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling/title",
          "value": "INSetClimateSettingsInCarIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetClimateSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetClimateSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetProfileInCarIntent/title",
          "value": "INSetProfileInCarIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetProfileInCarIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetProfileInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetProfileInCarIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetProfileInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent/title",
          "value": "INSetSeatSettingsInCarIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRidesharingDomainHandling/title",
          "value": "INRidesharingDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRidesharingDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRidesharingDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRidesharingDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRidesharingDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVisualCodeDomainHandling/title",
          "value": "INVisualCodeDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVisualCodeDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVisualCodeDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVisualCodeDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVisualCodeDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling/title",
          "value": "INSetSeatSettingsInCarIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentsDomainHandling/title",
          "value": "INPaymentsDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentsDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentsDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotosDomainHandling/title",
          "value": "INPhotosDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotosDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotosDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotosDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotosDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarPlayDomainHandling/title",
          "value": "INCarPlayDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarPlayDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarPlayDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarPlayDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarPlayDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent/title",
          "value": "INSetDefrosterSettingsInCarIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetDefrosterSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetDefrosterSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentHandling/title",
          "value": "INSetDefrosterSettingsInCarIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetDefrosterSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetDefrosterSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallsDomainHandling/title",
          "value": "INCallsDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallsDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallsDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetAudioSourceInCarIntent/title",
          "value": "INSetAudioSourceInCarIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetAudioSourceInCarIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetAudioSourceInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetAudioSourceInCarIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetAudioSourceInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetProfileInCarIntentHandling/title",
          "value": "INSetProfileInCarIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetProfileInCarIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetProfileInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetProfileInCarIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetProfileInCarIntentHandling"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/incarplaydomainhandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/incarplaydomainhandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
