{
  "abstract": [
    {
      "text": "A resolution result for the air circulation mode to use in a car.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INCarAirCirculationModeResolutionResult",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INCarAirCirculationModeResolutionResult"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INCarAirCirculationModeResolutionResult"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INCarAirCirculationModeResolutionResult is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INCarAirCirculationModeResolutionResult is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INCarAirCirculationModeResolutionResult is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INCarAirCirculationModeResolutionResult is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "INCarAirCirculationModeResolutionResult"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INCarAirCirculationModeResolutionResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object is what you return when resolving parameters containing a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationMode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value. Use the creation method that best reflects your ability to successfully resolve the parameter. For additional resolution options, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationMode": {
      "abstract": [
        {
          "text": "Constants indicating the circulation mode for the climate system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarAirCirculationMode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarAirCirculationMode"
        }
      ],
      "role": "symbol",
      "title": "INCarAirCirculationMode",
      "type": "topic",
      "url": "/documentation/intents/incaraircirculationmode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the air circulation mode to use in a car.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarAirCirculationModeResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarAirCirculationModeResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INCarAirCirculationModeResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/incaraircirculationmoderesolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult/confirmationRequired(with:)": {
      "abstract": [
        {
          "text": "Creates an object whose resolution requires that the user must confirm the value before proceeding.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirmationRequired"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCarAirCirculationMode",
          "text": "INCarAirCirculationMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult/confirmationRequired(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "confirmationRequiredWithCarAirCirculationModeToConfirm:"
        }
      ],
      "role": "symbol",
      "title": "confirmationRequired(with:)",
      "type": "topic",
      "url": "/documentation/intents/incaraircirculationmoderesolutionresult/confirmationrequired(with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult/confirmationRequiredWithValueToConfirm:": {
      "abstract": [
        {
          "text": "Creates an object whose resolution requires that the user must confirm the value before proceeding.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "confirmationRequiredWithValueToConfirm:"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult/confirmationRequiredWithValueToConfirm:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "confirmationRequiredWithValueToConfirm:"
        }
      ],
      "role": "symbol",
      "title": "confirmationRequiredWithValueToConfirm:",
      "type": "topic",
      "url": "/documentation/intents/incaraircirculationmoderesolutionresult/confirmationrequiredwithvaluetoconfirm:"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult/success(with:)": {
      "abstract": [
        {
          "text": "Creates an object whose resolution involves the successful matching of the specified parameter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCarAirCirculationMode",
          "text": "INCarAirCirculationMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult/success(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "successWithResolvedCarAirCirculationMode:"
        }
      ],
      "role": "symbol",
      "title": "success(with:)",
      "type": "topic",
      "url": "/documentation/intents/incaraircirculationmoderesolutionresult/success(with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult/successWithResolvedValue:": {
      "abstract": [
        {
          "text": "Creates an object whose resolution involves the successful matching of the specified parameter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "successWithResolvedValue:"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult/successWithResolvedValue:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "successWithResolvedValue:"
        }
      ],
      "role": "symbol",
      "title": "successWithResolvedValue:",
      "type": "topic",
      "url": "/documentation/intents/incaraircirculationmoderesolutionresult/successwithresolvedvalue:"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarAudioSourceResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the audio source to use in a car.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarAudioSourceResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarAudioSourceResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarAudioSourceResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INCarAudioSourceResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/incaraudiosourceresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarDefrosterResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for which defroster to use in a car.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarDefrosterResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarDefrosterResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarDefrosterResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INCarDefrosterResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/incardefrosterresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarSeatResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a specific seat of the car.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarSeatResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarSeatResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarSeatResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INCarSeatResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/incarseatresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a parameter of an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INIntentResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inintentresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRadioTypeResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the type of radio to use in a car.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRadioTypeResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRadioTypeResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRadioTypeResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INRadioTypeResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inradiotyperesolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRelativeReferenceResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a choice between the next or previous option.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRelativeReferenceResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelativeReferenceResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRelativeReferenceResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INRelativeReferenceResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inrelativereferenceresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRelativeSettingResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for whether you can select the minimum, current, or maximum value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRelativeSettingResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRelativeSettingResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRelativeSettingResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INRelativeSettingResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inrelativesettingresolutionresult"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "CarPlay-Resolution-Results",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCarSeatResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INCarDefrosterResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INCarAudioSourceResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INRadioTypeResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INRelativeReferenceResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INRelativeSettingResolutionResult"
      ],
      "title": "CarPlay Resolution Results"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Resolution-Result-Object",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult/success(with:)",
        "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult/confirmationRequired(with:)"
      ],
      "title": "Creating a Resolution Result Object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INCarAirCirculationModeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAirCirculationModeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAirCirculationModeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Resolution-Result-Object",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult/success(with:)",
                "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult/confirmationRequired(with:)",
                "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult/successWithResolvedValue:",
                "doc://com.apple.sirikit/documentation/Intents/INCarAirCirculationModeResolutionResult/confirmationRequiredWithValueToConfirm:"
              ],
              "title": "Creating a Resolution Result Object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "CarPlay-Resolution-Results",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INCarSeatResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INCarDefrosterResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INCarAudioSourceResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INRadioTypeResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INRelativeReferenceResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INRelativeSettingResolutionResult"
              ],
              "title": "CarPlay Resolution Results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INCarAirCirculationModeResolutionResult"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INIntentResolutionResult",
                    "text": "INIntentResolutionResult"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarDefrosterResolutionResult/title",
          "value": "INCarDefrosterResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarDefrosterResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarDefrosterResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarDefrosterResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarDefrosterResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/title",
          "value": "INIntentResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelativeSettingResolutionResult/title",
          "value": "INRelativeSettingResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelativeSettingResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRelativeSettingResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelativeSettingResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRelativeSettingResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAirCirculationModeResolutionResult/title",
          "value": "INCarAirCirculationModeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAirCirculationModeResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAirCirculationModeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAirCirculationModeResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAirCirculationModeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAirCirculationModeResolutionResult~1confirmationRequired(with:)/title",
          "value": "confirmationRequiredWithCarAirCirculationModeToConfirm:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAirCirculationModeResolutionResult~1confirmationRequired(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "confirmationRequiredWithCarAirCirculationModeToConfirm:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeatResolutionResult/title",
          "value": "INCarSeatResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeatResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeatResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarSeatResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarSeatResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelativeReferenceResolutionResult/title",
          "value": "INRelativeReferenceResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelativeReferenceResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRelativeReferenceResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRelativeReferenceResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRelativeReferenceResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSourceResolutionResult/title",
          "value": "INCarAudioSourceResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSourceResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAudioSourceResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAudioSourceResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAudioSourceResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRadioTypeResolutionResult/title",
          "value": "INRadioTypeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRadioTypeResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRadioTypeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRadioTypeResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRadioTypeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAirCirculationMode/title",
          "value": "INCarAirCirculationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAirCirculationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAirCirculationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAirCirculationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarAirCirculationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAirCirculationModeResolutionResult~1success(with:)/title",
          "value": "successWithResolvedCarAirCirculationMode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarAirCirculationModeResolutionResult~1success(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "successWithResolvedCarAirCirculationMode:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/incaraircirculationmoderesolutionresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/incaraircirculationmoderesolutionresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
