{
  "abstract": [
    {
      "text": "Provides a convenient way to adopt all of the protocols in the VoIP calling domain.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please conform to INStartAudioCallIntentHandling, INStartVideoCallIntentHandling and INSearchCallHistoryIntentHandling instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INCallsDomainHandling"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INCallsDomainHandling",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INCallsDomainHandling"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INCallsDomainHandling"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "11.0",
        "message": "Please conform to INStartAudioCallIntentHandling, INStartVideoCallIntentHandling and INSearchCallHistoryIntentHandling instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "11.0",
        "message": "Please conform to INStartAudioCallIntentHandling, INStartVideoCallIntentHandling and INSearchCallHistoryIntentHandling instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Please conform to INStartAudioCallIntentHandling, INStartVideoCallIntentHandling and INSearchCallHistoryIntentHandling instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please conform to INStartAudioCallIntentHandling, INStartVideoCallIntentHandling and INSearchCallHistoryIntentHandling instead",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "6.0",
        "introducedAt": "3.2",
        "message": "Please conform to INStartAudioCallIntentHandling and INSearchCallHistoryIntentHandling instead",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "INCallsDomainHandling"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INCallsDomainHandling"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INSearchCallHistoryIntentHandling",
              "text": "INSearchCallHistoryIntentHandling"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INStartAudioCallIntentHandling",
              "text": "INStartAudioCallIntentHandling"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INCallsDomainHandling"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INSearchCallHistoryIntentHandling",
              "text": "INSearchCallHistoryIntentHandling"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INStartAudioCallIntentHandling",
              "text": "INStartAudioCallIntentHandling"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INStartVideoCallIntentHandling",
              "text": "INStartVideoCallIntentHandling"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallsDomainHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol is a convenience protocol that adopts all of the protocols used to handle call-related intents. When your app adopts all of the protocols associated with call handling, you can adopt this one protocol instead of adopting the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocols separately.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "An object that adopts this protocol must be able to respond to the following intents:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", a request to search for an entry in the app’s call logs.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", a request to start an audio-only call.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ",  a request to start a video call.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Your handler object must be prepared to resolve any parameters associated with these intents and to confirm and handle the requests. When confirming and handling a request, you provide the response object that matches the specified intent.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallsDomainHandling": {
      "abstract": [
        {
          "text": "Provides a convenient way to adopt all of the protocols in the VoIP calling domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCallsDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallsDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallsDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INCallsDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/incallsdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarCommandsDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all the handling protocols in the car commands domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarCommandsDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarCommandsDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarCommandsDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INCarCommandsDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/incarcommandsdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the CarPlay domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarPlayDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarPlayDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INCarPlayDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/incarplaydomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessagesDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the messages domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMessagesDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessagesDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessagesDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INMessagesDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inmessagesdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INNotebookDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the lists and notes domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INNotebookDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INNotebookDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INNotebookDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INNotebookDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/innotebookdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentsDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the payments domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPaymentsDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentsDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentsDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INPaymentsDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inpaymentsdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotosDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the photos domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPhotosDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotosDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotosDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INPhotosDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inphotosdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRadioDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the radio domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRadioDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRadioDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRadioDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INRadioDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inradiodomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRidesharingDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the ride-booking domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRidesharingDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRidesharingDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRidesharingDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INRidesharingDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inridesharingdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent": {
      "abstract": [
        {
          "text": "A request to list the calls matching the specified criteria.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchCallHistoryIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchCallHistoryIntent"
        }
      ],
      "role": "symbol",
      "title": "INSearchCallHistoryIntent",
      "type": "topic",
      "url": "/documentation/intents/insearchcallhistoryintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for searching the user’s call history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchCallHistoryIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchCallHistoryIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSearchCallHistoryIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insearchcallhistoryintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntent": {
      "abstract": [
        {
          "text": "A request to start an audio-only call with one or more users.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartAudioCallIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartAudioCallIntent"
        }
      ],
      "role": "symbol",
      "title": "INStartAudioCallIntent",
      "type": "topic",
      "url": "/documentation/intents/instartaudiocallintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for initiating an audio call from your app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartAudioCallIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartAudioCallIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INStartAudioCallIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/instartaudiocallintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntent": {
      "abstract": [
        {
          "text": "A request to start a video call with one or more users.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartVideoCallIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartVideoCallIntent"
        }
      ],
      "role": "symbol",
      "title": "INStartVideoCallIntent",
      "type": "topic",
      "url": "/documentation/intents/instartvideocallintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for initiating a video call from your app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartVideoCallIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartVideoCallIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INStartVideoCallIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/instartvideocallintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVisualCodeDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the visual codes domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVisualCodeDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVisualCodeDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVisualCodeDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INVisualCodeDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/invisualcodedomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutsDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the workouts domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INWorkoutsDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutsDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutsDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INWorkoutsDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inworkoutsdomainhandling"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentHandling",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Domain-Handling-Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMessagesDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INNotebookDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutsDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentsDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INVisualCodeDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INPhotosDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INRidesharingDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INCarCommandsDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INRadioDomainHandling"
      ],
      "title": "Domain-Handling Protocols"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "6.0",
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INCallsDomainHandling"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentHandling"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Domain-Handling-Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMessagesDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INNotebookDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutsDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentsDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INVisualCodeDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INPhotosDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INRidesharingDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INCarCommandsDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INRadioDomainHandling"
              ],
              "title": "Domain-Handling Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INCallsDomainHandling"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INStartAudioCallIntentHandling",
                    "text": "INStartAudioCallIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INStartVideoCallIntentHandling",
                    "text": "INStartVideoCallIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INSearchCallHistoryIntentHandling",
                    "text": "INSearchCallHistoryIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INCallsDomainHandling"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INStartAudioCallIntentHandling",
                    "text": "INStartAudioCallIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INSearchCallHistoryIntentHandling",
                    "text": "INSearchCallHistoryIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please conform to INStartAudioCallIntentHandling, INStartVideoCallIntentHandling and INSearchCallHistoryIntentHandling instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentsDomainHandling/title",
          "value": "INPaymentsDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentsDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentsDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVisualCodeDomainHandling/title",
          "value": "INVisualCodeDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVisualCodeDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVisualCodeDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVisualCodeDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVisualCodeDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessagesDomainHandling/title",
          "value": "INMessagesDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessagesDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessagesDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessagesDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessagesDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntentHandling/title",
          "value": "INSearchCallHistoryIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchCallHistoryIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchCallHistoryIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntent/title",
          "value": "INStartAudioCallIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallsDomainHandling/title",
          "value": "INCallsDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallsDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallsDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRidesharingDomainHandling/title",
          "value": "INRidesharingDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRidesharingDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRidesharingDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRidesharingDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRidesharingDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentHandling/title",
          "value": "INStartVideoCallIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentHandling/title",
          "value": "INStartAudioCallIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarCommandsDomainHandling/title",
          "value": "INCarCommandsDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarCommandsDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarCommandsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarCommandsDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarCommandsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntent/title",
          "value": "INStartVideoCallIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutsDomainHandling/title",
          "value": "INWorkoutsDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutsDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutsDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRadioDomainHandling/title",
          "value": "INRadioDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRadioDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRadioDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRadioDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRadioDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNotebookDomainHandling/title",
          "value": "INNotebookDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNotebookDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INNotebookDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNotebookDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INNotebookDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent/title",
          "value": "INSearchCallHistoryIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchCallHistoryIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchCallHistoryIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotosDomainHandling/title",
          "value": "INPhotosDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotosDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotosDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotosDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotosDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarPlayDomainHandling/title",
          "value": "INCarPlayDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarPlayDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarPlayDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarPlayDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarPlayDomainHandling"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/incallsdomainhandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/incallsdomainhandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
