{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INEditMessageIntentResponseCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INEditMessageIntentResponseCode"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INEditMessageIntentResponseCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INEditMessageIntentResponseCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponseCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.sirikit/documentation/SiriKit/improving-interactions-between-siri-and-your-messaging-app"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INEditMessageIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEditMessageIntent"
        }
      ],
      "role": "symbol",
      "title": "INEditMessageIntent",
      "type": "topic",
      "url": "/documentation/intents/ineditmessageintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentHandling": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INEditMessageIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEditMessageIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INEditMessageIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/ineditmessageintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INEditMessageIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEditMessageIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INEditMessageIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/ineditmessageintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INEditMessageIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEditMessageIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INEditMessageIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/ineditmessageintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEditMessageIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INEditMessageIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/ineditmessageintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureMessageNotFound": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureMessageNotFound"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureMessageNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEditMessageIntentResponseCodeFailureMessageNotFound"
        }
      ],
      "role": "symbol",
      "title": "INEditMessageIntentResponseCode.failureMessageNotFound",
      "type": "topic",
      "url": "/documentation/intents/ineditmessageintentresponsecode/failuremessagenotfound"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureMessageServiceNotAvailable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureMessageServiceNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureMessageServiceNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEditMessageIntentResponseCodeFailureMessageServiceNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "INEditMessageIntentResponseCode.failureMessageServiceNotAvailable",
      "type": "topic",
      "url": "/documentation/intents/ineditmessageintentresponsecode/failuremessageservicenotavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureMessageTypeUnsupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureMessageTypeUnsupported"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureMessageTypeUnsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEditMessageIntentResponseCodeFailureMessageTypeUnsupported"
        }
      ],
      "role": "symbol",
      "title": "INEditMessageIntentResponseCode.failureMessageTypeUnsupported",
      "type": "topic",
      "url": "/documentation/intents/ineditmessageintentresponsecode/failuremessagetypeunsupported"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failurePastEditTimeLimit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failurePastEditTimeLimit"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failurePastEditTimeLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEditMessageIntentResponseCodeFailurePastEditTimeLimit"
        }
      ],
      "role": "symbol",
      "title": "INEditMessageIntentResponseCode.failurePastEditTimeLimit",
      "type": "topic",
      "url": "/documentation/intents/ineditmessageintentresponsecode/failurepastedittimelimit"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEditMessageIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INEditMessageIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/ineditmessageintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureRequiringInAppAuthentication": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringInAppAuthentication"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureRequiringInAppAuthentication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEditMessageIntentResponseCodeFailureRequiringInAppAuthentication"
        }
      ],
      "role": "symbol",
      "title": "INEditMessageIntentResponseCode.failureRequiringInAppAuthentication",
      "type": "topic",
      "url": "/documentation/intents/ineditmessageintentresponsecode/failurerequiringinappauthentication"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureUnsupportedOnService": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureUnsupportedOnService"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureUnsupportedOnService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEditMessageIntentResponseCodeFailureUnsupportedOnService"
        }
      ],
      "role": "symbol",
      "title": "INEditMessageIntentResponseCode.failureUnsupportedOnService",
      "type": "topic",
      "url": "/documentation/intents/ineditmessageintentresponsecode/failureunsupportedonservice"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/inProgress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProgress"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/inProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEditMessageIntentResponseCodeInProgress"
        }
      ],
      "role": "symbol",
      "title": "INEditMessageIntentResponseCode.inProgress",
      "type": "topic",
      "url": "/documentation/intents/ineditmessageintentresponsecode/inprogress"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/ineditmessageintentresponsecode/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/ready": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEditMessageIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INEditMessageIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/ineditmessageintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/success": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEditMessageIntentResponseCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "INEditMessageIntentResponseCode.success",
      "type": "topic",
      "url": "/documentation/intents/ineditmessageintentresponsecode/success"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/unspecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEditMessageIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INEditMessageIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/ineditmessageintentresponsecode/unspecified"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/improving-interactions-between-siri-and-your-messaging-app": {
      "abstract": [
        {
          "text": "Donate app-specific content, use Siri’s contact suggestions, and adopt the latest platform features to create a more consistent messaging experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/improving-interactions-between-siri-and-your-messaging-app",
      "kind": "article",
      "role": "article",
      "title": "Improving interactions between Siri and your messaging app",
      "type": "topic",
      "url": "/documentation/sirikit/improving-interactions-between-siri-and-your-messaging-app"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Editing-a-Message",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntent",
        "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponse",
        "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentHandling"
      ],
      "title": "Editing a Message"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureMessageNotFound",
        "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureMessageServiceNotAvailable",
        "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureMessageTypeUnsupported",
        "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failurePastEditTimeLimit",
        "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureRequiringAppLaunch",
        "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureRequiringInAppAuthentication",
        "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureUnsupportedOnService",
        "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/inProgress",
        "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/success",
        "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/unspecified"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INEditMessageIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureMessageNotFound",
                "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureMessageServiceNotAvailable",
                "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureMessageTypeUnsupported",
                "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failurePastEditTimeLimit",
                "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureRequiringAppLaunch",
                "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureRequiringInAppAuthentication",
                "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/failureUnsupportedOnService",
                "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/inProgress",
                "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/success",
                "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponseCode/unspecified"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Editing-a-Message",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntent",
                "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentResponse",
                "doc://com.apple.sirikit/documentation/Intents/INEditMessageIntentHandling"
              ],
              "title": "Editing a Message"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INEditMessageIntentResponseCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1unspecified/title",
          "value": "INEditMessageIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1failureMessageNotFound/title",
          "value": "INEditMessageIntentResponseCodeFailureMessageNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1failureMessageNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponseCodeFailureMessageNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponse/title",
          "value": "INEditMessageIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1failurePastEditTimeLimit/title",
          "value": "INEditMessageIntentResponseCodeFailurePastEditTimeLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1failurePastEditTimeLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponseCodeFailurePastEditTimeLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1ready/title",
          "value": "INEditMessageIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode/title",
          "value": "INEditMessageIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntent/title",
          "value": "INEditMessageIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1failureUnsupportedOnService/title",
          "value": "INEditMessageIntentResponseCodeFailureUnsupportedOnService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1failureUnsupportedOnService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponseCodeFailureUnsupportedOnService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1inProgress/title",
          "value": "INEditMessageIntentResponseCodeInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1inProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponseCodeInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INEditMessageIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1success/title",
          "value": "INEditMessageIntentResponseCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponseCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1failureRequiringInAppAuthentication/title",
          "value": "INEditMessageIntentResponseCodeFailureRequiringInAppAuthentication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1failureRequiringInAppAuthentication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponseCodeFailureRequiringInAppAuthentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1failure/title",
          "value": "INEditMessageIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponseCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1failureMessageServiceNotAvailable/title",
          "value": "INEditMessageIntentResponseCodeFailureMessageServiceNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1failureMessageServiceNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponseCodeFailureMessageServiceNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1failureMessageTypeUnsupported/title",
          "value": "INEditMessageIntentResponseCodeFailureMessageTypeUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentResponseCode~1failureMessageTypeUnsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentResponseCodeFailureMessageTypeUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentHandling/title",
          "value": "INEditMessageIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEditMessageIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INEditMessageIntentHandling"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/ineditmessageintentresponsecode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/ineditmessageintentresponsecode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
