{
  "abstract": [
    {
      "text": "A resolution result for an energy parameter associated with an intent.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INEnergyResolutionResult",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INEnergyResolutionResult"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INEnergyResolutionResult"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "INEnergyResolutionResult"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INEnergyResolutionResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object is what you return when resolving energy related parameters of an intent object. Use the creation method that best reflects your ability to successfully resolve the parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For additional resolution options, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for an energy parameter associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INEnergyResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INEnergyResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INEnergyResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inenergyresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult/confirmationRequired(with:)": {
      "abstract": [
        {
          "text": "Creates an object whose resolution requires that the user must confirm the value before proceeding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirmationRequired"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitEnergy",
          "text": "UnitEnergy"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult/confirmationRequired(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "confirmationRequiredWithEnergyToConfirm:"
        }
      ],
      "role": "symbol",
      "title": "confirmationRequired(with:)",
      "type": "topic",
      "url": "/documentation/intents/inenergyresolutionresult/confirmationrequired(with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult/disambiguation(with:)": {
      "abstract": [
        {
          "text": "Creates an object whose resolution requires the user to select from among the specified objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disambiguation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitEnergy",
          "text": "UnitEnergy"
        },
        {
          "kind": "text",
          "text": ">]) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult/disambiguation(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disambiguationWithEnergyToDisambiguate:"
        }
      ],
      "role": "symbol",
      "title": "disambiguation(with:)",
      "type": "topic",
      "url": "/documentation/intents/inenergyresolutionresult/disambiguation(with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult/success(with:)": {
      "abstract": [
        {
          "text": "Creates an object whose resolution involves the successful matching of the specified parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitEnergy",
          "text": "UnitEnergy"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult/success(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "successWithResolvedEnergy:"
        }
      ],
      "role": "symbol",
      "title": "success(with:)",
      "type": "topic",
      "url": "/documentation/intents/inenergyresolutionresult/success(with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a parameter of an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INIntentResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inintentresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INLengthResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a length associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INLengthResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INLengthResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INLengthResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INLengthResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inlengthresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMassResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a mass associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMassResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMassResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMassResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INMassResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inmassresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSpeedResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a speed associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSpeedResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSpeedResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSpeedResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INSpeedResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inspeedresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTemperatureResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the units to use with a temperature value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INTemperatureResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTemperatureResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INTemperatureResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INTemperatureResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/intemperatureresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVolumeResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a volume associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVolumeResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVolumeResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVolumeResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INVolumeResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/involumeresolutionresult"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Measurements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INLengthResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INMassResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INSpeedResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INTemperatureResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INVolumeResolutionResult"
      ],
      "title": "Measurements"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Resolution-Result-Object",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult/success(with:)",
        "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult/confirmationRequired(with:)",
        "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult/disambiguation(with:)"
      ],
      "title": "Creating a Resolution Result Object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INEnergyResolutionResult"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEnergyResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INEnergyResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Resolution-Result-Object",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult/success(with:)",
                "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult/confirmationRequired(with:)",
                "doc://com.apple.sirikit/documentation/Intents/INEnergyResolutionResult/disambiguation(with:)"
              ],
              "title": "Creating a Resolution Result Object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Measurements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INLengthResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INMassResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INSpeedResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INTemperatureResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INVolumeResolutionResult"
              ],
              "title": "Measurements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INEnergyResolutionResult"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INIntentResolutionResult",
                    "text": "INIntentResolutionResult"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTemperatureResolutionResult/title",
          "value": "INTemperatureResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTemperatureResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTemperatureResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTemperatureResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTemperatureResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEnergyResolutionResult~1confirmationRequired(with:)/title",
          "value": "confirmationRequiredWithEnergyToConfirm:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEnergyResolutionResult~1confirmationRequired(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "confirmationRequiredWithEnergyToConfirm:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEnergyResolutionResult~1disambiguation(with:)/title",
          "value": "disambiguationWithEnergyToDisambiguate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEnergyResolutionResult~1disambiguation(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "disambiguationWithEnergyToDisambiguate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEnergyResolutionResult/title",
          "value": "INEnergyResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEnergyResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INEnergyResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEnergyResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INEnergyResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMassResolutionResult/title",
          "value": "INMassResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMassResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMassResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMassResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMassResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVolumeResolutionResult/title",
          "value": "INVolumeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVolumeResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVolumeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVolumeResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVolumeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLengthResolutionResult/title",
          "value": "INLengthResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLengthResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INLengthResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INLengthResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INLengthResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeedResolutionResult/title",
          "value": "INSpeedResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeedResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSpeedResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeedResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSpeedResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEnergyResolutionResult~1success(with:)/title",
          "value": "successWithResolvedEnergy:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INEnergyResolutionResult~1success(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "successWithResolvedEnergy:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/title",
          "value": "INIntentResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResolutionResult"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inenergyresolutionresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inenergyresolutionresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
