{
  "abstract": [
    {
      "text": "An object that maintains the user’s current focus status and your app’s ability to access it.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INFocusStatusCenter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INFocusStatusCenter"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INFocusStatusCenter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "INFocusStatusCenter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INFocusStatusCenter"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INFocusStatus": {
      "abstract": [
        {
          "text": "The user’s preference for receiving notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INFocusStatus"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INFocusStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INFocusStatus"
        }
      ],
      "role": "symbol",
      "title": "INFocusStatus",
      "type": "topic",
      "url": "/documentation/intents/infocusstatus"
    },
    "doc://com.apple.sirikit/documentation/Intents/INFocusStatusAuthorizationStatus": {
      "abstract": [
        {
          "text": "A constant that indicates whether your app has authorization to access the user’s focus status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INFocusStatusAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INFocusStatusAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INFocusStatusAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "INFocusStatusAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/intents/infocusstatusauthorizationstatus"
    },
    "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter": {
      "abstract": [
        {
          "text": "An object that maintains the user’s current focus status and your app’s ability to access it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INFocusStatusCenter"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INFocusStatusCenter"
        }
      ],
      "role": "symbol",
      "title": "INFocusStatusCenter",
      "type": "topic",
      "url": "/documentation/intents/infocusstatuscenter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter/authorizationStatus": {
      "abstract": [
        {
          "text": "Returns your app’s current ability to access the user’s focus status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INFocusStatusAuthorizationStatus",
          "text": "INFocusStatusAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter/authorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "authorizationStatus",
      "type": "topic",
      "url": "/documentation/intents/infocusstatuscenter/authorizationstatus"
    },
    "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter/default": {
      "abstract": [
        {
          "text": "The systemwide object that holds the user’s focus status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INFocusStatusCenter",
          "text": "INFocusStatusCenter"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultCenter"
        }
      ],
      "role": "symbol",
      "title": "default",
      "type": "topic",
      "url": "/documentation/intents/infocusstatuscenter/default"
    },
    "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter/focusStatus": {
      "abstract": [
        {
          "text": "The user’s ability to receive notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INFocusStatus",
          "text": "INFocusStatus"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter/focusStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focusStatus"
        }
      ],
      "role": "symbol",
      "title": "focusStatus",
      "type": "topic",
      "url": "/documentation/intents/infocusstatuscenter/focusstatus"
    },
    "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter/requestAuthorization(completionHandler:)": {
      "abstract": [
        {
          "text": "Asks the system for access to the user’s focus status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAuthorization"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INFocusStatusAuthorizationStatus",
          "text": "INFocusStatusAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter/requestAuthorization(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAuthorizationWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestAuthorization(completionHandler:)",
      "type": "topic",
      "url": "/documentation/intents/infocusstatuscenter/requestauthorization(completionhandler:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntent": {
      "abstract": [
        {
          "text": "An object that indicates the user’s focus status is changing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INShareFocusStatusIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShareFocusStatusIntent"
        }
      ],
      "role": "symbol",
      "title": "INShareFocusStatusIntent",
      "type": "topic",
      "url": "/documentation/intents/insharefocusstatusintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentHandling": {
      "abstract": [
        {
          "text": "A set of methods an object implements to process intents that share the user’s focus status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INShareFocusStatusIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShareFocusStatusIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INShareFocusStatusIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insharefocusstatusintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to an intent that shares the user’s focus status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INShareFocusStatusIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShareFocusStatusIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INShareFocusStatusIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/insharefocusstatusintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode": {
      "abstract": [
        {
          "text": "A constant that indicates your app’s ability to handle an intent to share the user’s focus status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INShareFocusStatusIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShareFocusStatusIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INShareFocusStatusIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/insharefocusstatusintentresponsecode"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sharing-the-Users-Focus-Status",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntent",
        "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponse",
        "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode",
        "doc://com.apple.sirikit/documentation/Intents/INFocusStatus",
        "doc://com.apple.sirikit/documentation/Intents/INFocusStatusAuthorizationStatus"
      ],
      "title": "Sharing the User’s Focus Status"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-the-Default-Status-Center",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter/default"
      ],
      "title": "Accessing the Default Status Center"
    },
    {
      "anchor": "Requesting-Authorization",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter/requestAuthorization(completionHandler:)",
        "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter/authorizationStatus"
      ],
      "title": "Requesting Authorization"
    },
    {
      "anchor": "Retrieving-the-Users-Focus-Status",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter/focusStatus"
      ],
      "title": "Retrieving the User’s Focus Status"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INFocusStatusCenter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INFocusStatusCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INFocusStatusCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-the-Default-Status-Center",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter/default"
              ],
              "title": "Accessing the Default Status Center"
            },
            {
              "anchor": "Requesting-Authorization",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter/requestAuthorization(completionHandler:)",
                "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter/authorizationStatus"
              ],
              "title": "Requesting Authorization"
            },
            {
              "anchor": "Retrieving-the-Users-Focus-Status",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INFocusStatusCenter/focusStatus"
              ],
              "title": "Retrieving the User’s Focus Status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sharing-the-Users-Focus-Status",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntent",
                "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponse",
                "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode",
                "doc://com.apple.sirikit/documentation/Intents/INFocusStatus",
                "doc://com.apple.sirikit/documentation/Intents/INFocusStatusAuthorizationStatus"
              ],
              "title": "Sharing the User’s Focus Status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INFocusStatusCenter"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFocusStatus/title",
          "value": "INFocusStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFocusStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INFocusStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFocusStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INFocusStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFocusStatusCenter~1requestAuthorization(completionHandler:)/title",
          "value": "requestAuthorizationWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFocusStatusCenter~1requestAuthorization(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestAuthorizationWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFocusStatusCenter~1default/title",
          "value": "defaultCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFocusStatusCenter~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentResponse/title",
          "value": "INShareFocusStatusIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShareFocusStatusIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INShareFocusStatusIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFocusStatusCenter/title",
          "value": "INFocusStatusCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFocusStatusCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INFocusStatusCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFocusStatusCenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INFocusStatusCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntent/title",
          "value": "INShareFocusStatusIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShareFocusStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INShareFocusStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentHandling/title",
          "value": "INShareFocusStatusIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShareFocusStatusIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INShareFocusStatusIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentResponseCode/title",
          "value": "INShareFocusStatusIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShareFocusStatusIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INShareFocusStatusIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFocusStatusAuthorizationStatus/title",
          "value": "INFocusStatusAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFocusStatusAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INFocusStatusAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFocusStatusAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INFocusStatusAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFocusStatusCenter~1focusStatus/title",
          "value": "focusStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFocusStatusCenter~1focusStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focusStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFocusStatusCenter~1authorizationStatus/title",
          "value": "authorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INFocusStatusCenter~1authorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "authorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/infocusstatuscenter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/infocusstatuscenter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
