{
  "abstract": [
    {
      "text": "A request for the current status of a previously booked ride.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INGetRideStatusIntent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INGetRideStatusIntent"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INGetRideStatusIntent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "INGetRideStatusIntent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntent"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When there’s a request for the status of a booked ride, SiriKit sends an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to your handler object. Upon receiving this intent, fetch the ride status and return it in your response object. The intent object has no additional parameters.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To handle this intent, the handler object in your Intents extension must adopt the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol. Your handler should confirm the request and create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object with the status of the ride.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Additional-Intent-Attributes",
          "level": 3,
          "text": "Additional Intent Attributes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The following table lists additional attributes of this intent object:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Attribute",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Description",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Supported by",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Siri Intents, Maps",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Always requires unlocked device",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "No",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "Apps can optionally ask the user to unlock the device before handling this intent. To require unlocking of the device, include the name of this class in the ",
              "type": "text"
            },
            {
              "code": "IntentsRestrictedWhileLocked",
              "type": "codeVoice"
            },
            {
              "text": " key of your Intents extension’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntent": {
      "abstract": [
        {
          "text": "A request for the current status of a previously booked ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntent"
        }
      ],
      "role": "symbol",
      "title": "INGetRideStatusIntent",
      "type": "topic",
      "url": "/documentation/intents/ingetridestatusintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntent/init()": {
      "abstract": [
        {
          "text": "Initializes the get ride status intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntent/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/intents/ingetridestatusintent/init()"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for fetching the status of the user’s current ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INGetRideStatusIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/ingetridestatusintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a get ride status intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INGetRideStatusIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/ingetridestatusintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseObserver": {
      "abstract": [
        {
          "text": "An interface for providing updated status for an active ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentResponseObserver"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentResponseObserver"
        }
      ],
      "role": "symbol",
      "title": "INGetRideStatusIntentResponseObserver",
      "type": "topic",
      "url": "/documentation/intents/ingetridestatusintentresponseobserver"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntent": {
      "abstract": [
        {
          "text": "A request to fulfill in your app or Intents extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntent"
        }
      ],
      "role": "symbol",
      "title": "INIntent",
      "type": "topic",
      "url": "/documentation/intents/inintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentSetImageKeyPath": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentSetImageKeyPath"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentSetImageKeyPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentSetImageKeyPath"
        }
      ],
      "role": "symbol",
      "title": "INIntentSetImageKeyPath",
      "type": "topic",
      "url": "/documentation/intents/inintentsetimagekeypath"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntent"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.sirikit/documentation/Intents/INIntentSetImageKeyPath",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Get-the-Ride-Status",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponse",
        "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseObserver"
      ],
      "title": "Get the Ride Status"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-an-Intent-Object",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntent/init()"
      ],
      "title": "Initializing an Intent Object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INGetRideStatusIntent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializing-an-Intent-Object",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntent/init()"
              ],
              "title": "Initializing an Intent Object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INIntent"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Get-the-Ride-Status",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponse",
                "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentResponseObserver"
              ],
              "title": "Get the Ride Status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INGetRideStatusIntent"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INIntent",
                    "text": "INIntent"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseObserver/title",
          "value": "INGetRideStatusIntentResponseObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentResponseObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponseObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentResponseObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntent/title",
          "value": "INIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntent/title",
          "value": "INGetRideStatusIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponse/title",
          "value": "INGetRideStatusIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentHandling/title",
          "value": "INGetRideStatusIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntent~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntent~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/ingetridestatusintent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/ingetridestatusintent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
