{
  "abstract": [
    {
      "text": "Your app’s response to a get user current restaurant reservation bookings intent.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponse"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INGetUserCurrentRestaurantReservationBookingsIntentResponse",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponse"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponse"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "INGetUserCurrentRestaurantReservationBookingsIntentResponse"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponse"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object contains the current reservations associated with the user and matching the search criteria in the corresponding ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. You create instances of this class when confirming or handling an intent object of that type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentHandling/confirm(getUserCurrentRestaurantReservationBookings:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentHandling/handle(getUserCurrentRestaurantReservationBookings:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods of your handler object. For more information about implementing your handler object, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntent": {
      "abstract": [
        {
          "text": "A request for the list of the user’s current reservations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetUserCurrentRestaurantReservationBookingsIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetUserCurrentRestaurantReservationBookingsIntent"
        }
      ],
      "role": "symbol",
      "title": "INGetUserCurrentRestaurantReservationBookingsIntent",
      "type": "topic",
      "url": "/documentation/intents/ingetusercurrentrestaurantreservationbookingsintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for fetching and delivering the user’s current reservations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetUserCurrentRestaurantReservationBookingsIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetUserCurrentRestaurantReservationBookingsIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INGetUserCurrentRestaurantReservationBookingsIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/ingetusercurrentrestaurantreservationbookingsintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentHandling/confirm(getUserCurrentRestaurantReservationBookings:completion:)": {
      "abstract": [
        {
          "text": "Confirms whether you can get the user’s current reservations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirm"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "getUserCurrentRestaurantReservationBookings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INGetUserCurrentRestaurantReservationBookingsIntent",
          "text": "INGetUserCurrentRestaurantReservationBookingsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INGetUserCurrentRestaurantReservationBookingsIntentResponse",
          "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentHandling/confirm(getUserCurrentRestaurantReservationBookings:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "confirmGetUserCurrentRestaurantReservationBookings:completion:"
        }
      ],
      "role": "symbol",
      "title": "confirm(getUserCurrentRestaurantReservationBookings:completion:)",
      "type": "topic",
      "url": "/documentation/intents/ingetusercurrentrestaurantreservationbookingsintenthandling/confirm(getusercurrentrestaurantreservationbookings:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentHandling/handle(getUserCurrentRestaurantReservationBookings:completion:)": {
      "abstract": [
        {
          "text": "Handles fetching the user’s current reservations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "getUserCurrentRestaurantReservationBookings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INGetUserCurrentRestaurantReservationBookingsIntent",
          "text": "INGetUserCurrentRestaurantReservationBookingsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INGetUserCurrentRestaurantReservationBookingsIntentResponse",
          "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentHandling/handle(getUserCurrentRestaurantReservationBookings:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleGetUserCurrentRestaurantReservationBookings:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handle(getUserCurrentRestaurantReservationBookings:completion:)",
      "type": "topic",
      "url": "/documentation/intents/ingetusercurrentrestaurantreservationbookingsintenthandling/handle(getusercurrentrestaurantreservationbookings:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a get user current restaurant reservation bookings intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INGetUserCurrentRestaurantReservationBookingsIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/ingetusercurrentrestaurantreservationbookingsintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponse/code": {
      "abstract": [
        {
          "text": "The code indicating whether you successfully handled the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INGetUserCurrentRestaurantReservationBookingsIntentResponseCode",
          "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponse/code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "code"
        }
      ],
      "role": "symbol",
      "title": "code",
      "type": "topic",
      "url": "/documentation/intents/ingetusercurrentrestaurantreservationbookingsintentresponse/code"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponse/init(userCurrentBookings:code:userActivity:)": {
      "abstract": [
        {
          "text": "Initializes the response object with the specified code and user activity object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "userCurrentBookings"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INRestaurantReservationUserBooking",
          "text": "INRestaurantReservationUserBooking"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INGetUserCurrentRestaurantReservationBookingsIntentResponseCode",
          "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponseCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserActivity",
          "text": "NSUserActivity"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponse/init(userCurrentBookings:code:userActivity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithUserCurrentBookings:code:userActivity:"
        }
      ],
      "role": "symbol",
      "title": "init(userCurrentBookings:code:userActivity:)",
      "type": "topic",
      "url": "/documentation/intents/ingetusercurrentrestaurantreservationbookingsintentresponse/init(usercurrentbookings:code:useractivity:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponse/userCurrentBookings": {
      "abstract": [
        {
          "text": "An array of the user’s current reservations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userCurrentBookings"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INRestaurantReservationUserBooking",
          "text": "INRestaurantReservationUserBooking"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponse/userCurrentBookings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userCurrentBookings"
        }
      ],
      "role": "symbol",
      "title": "userCurrentBookings",
      "type": "topic",
      "url": "/documentation/intents/ingetusercurrentrestaurantreservationbookingsintentresponse/usercurrentbookings"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponseCode": {
      "abstract": [
        {
          "text": "Constants indicating the state of the response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INGetUserCurrentRestaurantReservationBookingsIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/ingetusercurrentrestaurantreservationbookingsintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentResponse": {
      "abstract": [
        {
          "text": "Your response to an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/inintentresponse"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentResponse"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Get-User-Current-Restaurant-Reservation-Bookings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntent"
      ],
      "title": "Get User Current Restaurant Reservation Bookings"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-the-Response-Object",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponse/init(userCurrentBookings:code:userActivity:)"
      ],
      "title": "Initializing the Response Object"
    },
    {
      "anchor": "Getting-the-Response-Code",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponse/code",
        "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponseCode"
      ],
      "title": "Getting the Response Code"
    },
    {
      "anchor": "Specifying-the-Users-Current-Reservations",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponse/userCurrentBookings"
      ],
      "title": "Specifying the User’s Current Reservations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INGetUserCurrentRestaurantReservationBookingsIntentResponse"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializing-the-Response-Object",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponse/init(userCurrentBookings:code:userActivity:)"
              ],
              "title": "Initializing the Response Object"
            },
            {
              "anchor": "Getting-the-Response-Code",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponse/code",
                "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponseCode"
              ],
              "title": "Getting the Response Code"
            },
            {
              "anchor": "Specifying-the-Users-Current-Reservations",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentResponse/userCurrentBookings"
              ],
              "title": "Specifying the User’s Current Reservations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INIntentResponse"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Get-User-Current-Restaurant-Reservation-Bookings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntent"
              ],
              "title": "Get User Current Restaurant Reservation Bookings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponse"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResponse",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INIntentResponse",
                    "text": "INIntentResponse"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentResponse~1init(userCurrentBookings:code:userActivity:)/title",
          "value": "initWithUserCurrentBookings:code:userActivity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentResponse~1init(userCurrentBookings:code:userActivity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithUserCurrentBookings:code:userActivity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/title",
          "value": "INIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentHandling~1handle(getUserCurrentRestaurantReservationBookings:completion:)/title",
          "value": "handleGetUserCurrentRestaurantReservationBookings:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentHandling~1handle(getUserCurrentRestaurantReservationBookings:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleGetUserCurrentRestaurantReservationBookings:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentResponseCode/title",
          "value": "INGetUserCurrentRestaurantReservationBookingsIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentResponse~1userCurrentBookings/title",
          "value": "userCurrentBookings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentResponse~1userCurrentBookings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userCurrentBookings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntent/title",
          "value": "INGetUserCurrentRestaurantReservationBookingsIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetUserCurrentRestaurantReservationBookingsIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetUserCurrentRestaurantReservationBookingsIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentResponse~1code/title",
          "value": "code"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentResponse~1code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentResponse/title",
          "value": "INGetUserCurrentRestaurantReservationBookingsIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetUserCurrentRestaurantReservationBookingsIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentHandling~1confirm(getUserCurrentRestaurantReservationBookings:completion:)/title",
          "value": "confirmGetUserCurrentRestaurantReservationBookings:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentHandling~1confirm(getUserCurrentRestaurantReservationBookings:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "confirmGetUserCurrentRestaurantReservationBookings:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentHandling/title",
          "value": "INGetUserCurrentRestaurantReservationBookingsIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetUserCurrentRestaurantReservationBookingsIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetUserCurrentRestaurantReservationBookingsIntentHandling"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/ingetusercurrentrestaurantreservationbookingsintentresponse"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/ingetusercurrentrestaurantreservationbookingsintentresponse"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
