{
  "abstract": [
    {
      "text": "Your app’s response to a get available restaurant reservation booking defaults intent.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INGetAvailableRestaurantReservationBookingDefaultsIntentResponse",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponse"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponse"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponse"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponse"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object contains the default values to use when booking a reservation at a restaurant. You create instances of this class when confirming or handling an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The system uses the information to improve the overall user experience. Restaurants may have requirements for the minimum or maximum size of a party. Similarly, your service might be able to provide a default date that reflects the first time when reservations are available. The system uses this information both to gather an initial set of valid reservation options and to show the user what requirements the restaurant may impose. Although providing default values is not required, it is highly recommended.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling/confirm(getAvailableRestaurantReservationBookingDefaults:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling/handle(getAvailableRestaurantReservationBookingDefaults:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods of handler object. For more information about implementing your handler object, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntent": {
      "abstract": [
        {
          "text": "A request for the default values to use when fetching potential reservation options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntent"
        }
      ],
      "role": "symbol",
      "title": "INGetAvailableRestaurantReservationBookingDefaultsIntent",
      "type": "topic",
      "url": "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for providing default values to the system when pre-fetching an initial set of possible reservation times.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INGetAvailableRestaurantReservationBookingDefaultsIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling/confirm(getAvailableRestaurantReservationBookingDefaults:completion:)": {
      "abstract": [
        {
          "text": "Confirms whether you can return default values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirm"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "getAvailableRestaurantReservationBookingDefaults"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INGetAvailableRestaurantReservationBookingDefaultsIntent",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INGetAvailableRestaurantReservationBookingDefaultsIntentResponse",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling/confirm(getAvailableRestaurantReservationBookingDefaults:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "confirmGetAvailableRestaurantReservationBookingDefaults:completion:"
        }
      ],
      "role": "symbol",
      "title": "confirm(getAvailableRestaurantReservationBookingDefaults:completion:)",
      "type": "topic",
      "url": "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintenthandling/confirm(getavailablerestaurantreservationbookingdefaults:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling/handle(getAvailableRestaurantReservationBookingDefaults:completion:)": {
      "abstract": [
        {
          "text": "Handles returning the default values to use when pre-fetching reservations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "getAvailableRestaurantReservationBookingDefaults"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INGetAvailableRestaurantReservationBookingDefaultsIntent",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INGetAvailableRestaurantReservationBookingDefaultsIntentResponse",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling/handle(getAvailableRestaurantReservationBookingDefaults:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleGetAvailableRestaurantReservationBookingDefaults:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handle(getAvailableRestaurantReservationBookingDefaults:completion:)",
      "type": "topic",
      "url": "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintenthandling/handle(getavailablerestaurantreservationbookingdefaults:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a get available restaurant reservation booking defaults intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/code": {
      "abstract": [
        {
          "text": "The code indicating whether you successfully handled the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INGetAvailableRestaurantReservationBookingDefaultsIntentResponseCode",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "code"
        }
      ],
      "role": "symbol",
      "title": "code",
      "type": "topic",
      "url": "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintentresponse/code"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/defaultBookingDate": {
      "abstract": [
        {
          "text": "The default booking date to use when placing the initial reservations request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultBookingDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/defaultBookingDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultBookingDate"
        }
      ],
      "role": "symbol",
      "title": "defaultBookingDate",
      "type": "topic",
      "url": "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintentresponse/defaultbookingdate"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/defaultPartySize": {
      "abstract": [
        {
          "text": "The party size to use when placing the initial reservations request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultPartySize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/defaultPartySize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultPartySize"
        }
      ],
      "role": "symbol",
      "title": "defaultPartySize",
      "type": "topic",
      "url": "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintentresponse/defaultpartysize"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/init(defaultPartySize:defaultBooking:code:userActivity:)": {
      "abstract": [
        {
          "text": "Initializes the response object with the specified information and user activity object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "defaultPartySize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "defaultBooking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INGetAvailableRestaurantReservationBookingDefaultsIntentResponseCode",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponseCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserActivity",
          "text": "NSUserActivity"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/init(defaultPartySize:defaultBooking:code:userActivity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDefaultPartySize:defaultBookingDate:code:userActivity:"
        }
      ],
      "role": "symbol",
      "title": "init(defaultPartySize:defaultBooking:code:userActivity:)",
      "type": "topic",
      "url": "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintentresponse/init(defaultpartysize:defaultbooking:code:useractivity:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/maximumPartySize": {
      "abstract": [
        {
          "text": "The maximum party size allowed by the restaurant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumPartySize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/maximumPartySize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumPartySize"
        }
      ],
      "role": "symbol",
      "title": "maximumPartySize",
      "type": "topic",
      "url": "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintentresponse/maximumpartysize"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/minimumPartySize": {
      "abstract": [
        {
          "text": "The minimum party size allowed by the restaurant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumPartySize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/minimumPartySize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumPartySize"
        }
      ],
      "role": "symbol",
      "title": "minimumPartySize",
      "type": "topic",
      "url": "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintentresponse/minimumpartysize"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/providerImage": {
      "abstract": [
        {
          "text": "An image representing your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providerImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INImage",
          "text": "INImage"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/providerImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "providerImage"
        }
      ],
      "role": "symbol",
      "title": "providerImage",
      "type": "topic",
      "url": "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintentresponse/providerimage"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponseCode": {
      "abstract": [
        {
          "text": "Constants indicating the state of the response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentResponse": {
      "abstract": [
        {
          "text": "Your response to an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/inintentresponse"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentResponse"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Get-Available-Restaurant-Reservation-Booking-Defaults",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntent"
      ],
      "title": "Get Available Restaurant Reservation Booking Defaults"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-the-Response-Object",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/init(defaultPartySize:defaultBooking:code:userActivity:)"
      ],
      "title": "Initializing the Response Object"
    },
    {
      "anchor": "Getting-the-Response-Code",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/code",
        "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponseCode"
      ],
      "title": "Getting the Response Code"
    },
    {
      "anchor": "Specifying-the-Default-Values",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/defaultBookingDate",
        "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/defaultPartySize",
        "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/maximumPartySize",
        "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/minimumPartySize",
        "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/providerImage"
      ],
      "title": "Specifying the Default Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponse"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializing-the-Response-Object",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/init(defaultPartySize:defaultBooking:code:userActivity:)"
              ],
              "title": "Initializing the Response Object"
            },
            {
              "anchor": "Getting-the-Response-Code",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/code",
                "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponseCode"
              ],
              "title": "Getting the Response Code"
            },
            {
              "anchor": "Specifying-the-Default-Values",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/defaultBookingDate",
                "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/defaultPartySize",
                "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/maximumPartySize",
                "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/minimumPartySize",
                "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/providerImage"
              ],
              "title": "Specifying the Default Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INIntentResponse"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Get-Available-Restaurant-Reservation-Booking-Defaults",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntent"
              ],
              "title": "Get Available Restaurant Reservation Booking Defaults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponse"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResponse",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INIntentResponse",
                    "text": "INIntentResponse"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntent/title",
          "value": "INGetAvailableRestaurantReservationBookingDefaultsIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetAvailableRestaurantReservationBookingDefaultsIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetAvailableRestaurantReservationBookingDefaultsIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/title",
          "value": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponse~1providerImage/title",
          "value": "providerImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponse~1providerImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "providerImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/title",
          "value": "INIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentHandling~1confirm(getAvailableRestaurantReservationBookingDefaults:completion:)/title",
          "value": "confirmGetAvailableRestaurantReservationBookingDefaults:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentHandling~1confirm(getAvailableRestaurantReservationBookingDefaults:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "confirmGetAvailableRestaurantReservationBookingDefaults:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponse~1minimumPartySize/title",
          "value": "minimumPartySize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponse~1minimumPartySize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumPartySize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponse~1defaultPartySize/title",
          "value": "defaultPartySize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponse~1defaultPartySize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultPartySize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentHandling/title",
          "value": "INGetAvailableRestaurantReservationBookingDefaultsIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponse~1maximumPartySize/title",
          "value": "maximumPartySize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponse~1maximumPartySize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumPartySize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponse~1code/title",
          "value": "code"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponse~1code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentHandling~1handle(getAvailableRestaurantReservationBookingDefaults:completion:)/title",
          "value": "handleGetAvailableRestaurantReservationBookingDefaults:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentHandling~1handle(getAvailableRestaurantReservationBookingDefaults:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleGetAvailableRestaurantReservationBookingDefaults:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponseCode/title",
          "value": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponse~1init(defaultPartySize:defaultBooking:code:userActivity:)/title",
          "value": "initWithDefaultPartySize:defaultBookingDate:code:userActivity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponse~1init(defaultPartySize:defaultBooking:code:userActivity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDefaultPartySize:defaultBookingDate:code:userActivity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponse~1defaultBookingDate/title",
          "value": "defaultBookingDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentResponse~1defaultBookingDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultBookingDate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintentresponse"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintentresponse"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
