{
  "abstract": [
    {
      "text": "Errors returned by SiriKit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INIntentError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC17INIntentErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INIntentError"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INIntentError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "INIntentError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INIntentError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/sirikit/inintenterror/2882876-erroruserinfo": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "errorUserInfo"
        },
        {
          "kind": "text",
          "text": ": [String : Any]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/sirikit/inintenterror/2882876-erroruserinfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorUserInfo",
      "type": "topic",
      "url": "/documentation/sirikit/inintenterror/2882876-erroruserinfo"
    },
    "doc://com.apple.documentation/documentation/sirikit/inintenterror/2882880-errorcode": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "errorCode"
        },
        {
          "kind": "text",
          "text": ": Int"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/sirikit/inintenterror/2882880-errorcode",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorCode",
      "type": "topic",
      "url": "/documentation/sirikit/inintenterror/2882880-errorcode"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError": {
      "abstract": [
        {
          "text": "Errors returned by SiriKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentError"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentError"
        }
      ],
      "role": "symbol",
      "title": "INIntentError",
      "type": "topic",
      "url": "/documentation/intents/inintenterror"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code": {
      "abstract": [
        {
          "text": "Constants for error codes returned by the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "INIntentError.Code",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/code"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/decodingGeneric": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decodingGeneric"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/decodingGeneric",
      "kind": "symbol",
      "role": "symbol",
      "title": "decodingGeneric",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/decodinggeneric"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/deletingAllInteractions": {
      "abstract": [
        {
          "text": "The system was unable to delete all donated ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.sirikit/documentation/Intents/INInteraction",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletingAllInteractions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/deletingAllInteractions",
      "kind": "symbol",
      "role": "symbol",
      "title": "deletingAllInteractions",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/deletingallinteractions"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/deletingInteractionWithGroupIdentifier": {
      "abstract": [
        {
          "text": "The system was unable to delete the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.sirikit/documentation/Intents/INInteraction",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects using their group identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletingInteractionWithGroupIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/deletingInteractionWithGroupIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "deletingInteractionWithGroupIdentifier",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/deletinginteractionwithgroupidentifier"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/deletingInteractionWithIdentifiers": {
      "abstract": [
        {
          "text": "The system was unable to delete the specified set of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.sirikit/documentation/Intents/INInteraction",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletingInteractionWithIdentifiers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/deletingInteractionWithIdentifiers",
      "kind": "symbol",
      "role": "symbol",
      "title": "deletingInteractionWithIdentifiers",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/deletinginteractionwithidentifiers"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/donatingInteraction": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.sirikit/documentation/Intents/INInteraction",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object could not be donated to the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "donatingInteraction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/donatingInteraction",
      "kind": "symbol",
      "role": "symbol",
      "title": "donatingInteraction",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/donatinginteraction"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/encodingFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encodingFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/encodingFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "encodingFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/encodingfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/encodingGeneric": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encodingGeneric"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/encodingGeneric",
      "kind": "symbol",
      "role": "symbol",
      "title": "encodingGeneric",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/encodinggeneric"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/errorDomain": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/errordomain"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/extensionBringUpFailed": {
      "abstract": [
        {
          "text": "There was an error while trying to communicate with the extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionBringUpFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/extensionBringUpFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "extensionBringUpFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/extensionbringupfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/extensionLaunchingTimeout": {
      "abstract": [
        {
          "text": "The extension failed to launch in a timely manner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extensionLaunchingTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/extensionLaunchingTimeout",
      "kind": "symbol",
      "role": "symbol",
      "title": "extensionLaunchingTimeout",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/extensionlaunchingtimeout"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageGeneric": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageGeneric"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageGeneric",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageGeneric",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imagegeneric"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageLoadingFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageLoadingFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageLoadingFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageLoadingFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imageloadingfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageNoServiceAvailable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageNoServiceAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageNoServiceAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageNoServiceAvailable",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imagenoserviceavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyInvalid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageProxyInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageProxyInvalid",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imageproxyinvalid"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyLoop": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageProxyLoop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyLoop",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageProxyLoop",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imageproxyloop"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyTimeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageProxyTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyTimeout",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageProxyTimeout",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imageproxytimeout"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageRetrievalFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageRetrievalFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageRetrievalFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageRetrievalFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imageretrievalfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageScalingFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageScalingFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageScalingFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageScalingFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imagescalingfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageServiceFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageServiceFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageServiceFailure",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageServiceFailure",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imageservicefailure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageStorageFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageStorageFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageStorageFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageStorageFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/imagestoragefailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/intentSupportedByMultipleExtension": {
      "abstract": [
        {
          "text": "An intent was supported by more than one Intents extension in the same app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intentSupportedByMultipleExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/intentSupportedByMultipleExtension",
      "kind": "symbol",
      "role": "symbol",
      "title": "intentSupportedByMultipleExtension",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/intentsupportedbymultipleextension"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/interactionOperationNotSupported": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.sirikit/documentation/Intents/INInteraction",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object could not be donated or deleted because those capabilities are not supported on the current device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interactionOperationNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/interactionOperationNotSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "interactionOperationNotSupported",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/interactionoperationnotsupported"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/invalidIntentName": {
      "abstract": [
        {
          "text": "The extension declared support for a nonexistent intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidIntentName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/invalidIntentName",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidIntentName",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/invalidintentname"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/invalidUserVocabularyFileLocation": {
      "abstract": [
        {
          "text": "An invalid location was specified for the user vocabulary file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidUserVocabularyFileLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/invalidUserVocabularyFileLocation",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidUserVocabularyFileLocation",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/invaliduservocabularyfilelocation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/missingInformation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingInformation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/missingInformation",
      "kind": "symbol",
      "role": "symbol",
      "title": "missingInformation",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/missinginformation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/noAppAvailable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noAppAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/noAppAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "noAppAvailable",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/noappavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/noAppIntent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noAppIntent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/noAppIntent",
      "kind": "symbol",
      "role": "symbol",
      "title": "noAppIntent",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/noappintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/noHandlerProvidedForIntent": {
      "abstract": [
        {
          "text": "No object was provided to handle the specified intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noHandlerProvidedForIntent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/noHandlerProvidedForIntent",
      "kind": "symbol",
      "role": "symbol",
      "title": "noHandlerProvidedForIntent",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/nohandlerprovidedforintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/permissionDenied": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "permissionDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/permissionDenied",
      "kind": "symbol",
      "role": "symbol",
      "title": "permissionDenied",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/permissiondenied"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/requestTimedOut": {
      "abstract": [
        {
          "text": "The underlying request timed out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestTimedOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/requestTimedOut",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestTimedOut",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/requesttimedout"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/restrictedIntentsNotSupportedByExtension": {
      "abstract": [
        {
          "text": "An intent was listed in the ",
          "type": "text"
        },
        {
          "code": "IntentsRestrictedWhileLocked",
          "type": "codeVoice"
        },
        {
          "text": " key of the app’s ",
          "type": "text"
        },
        {
          "code": "Info.plist",
          "type": "codeVoice"
        },
        {
          "text": ", but not in the ",
          "type": "text"
        },
        {
          "code": "IntentsSupported",
          "type": "codeVoice"
        },
        {
          "text": " key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restrictedIntentsNotSupportedByExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/restrictedIntentsNotSupportedByExtension",
      "kind": "symbol",
      "role": "symbol",
      "title": "restrictedIntentsNotSupportedByExtension",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/restrictedintentsnotsupportedbyextension"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/unableToCreateAppIntentRepresentation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unableToCreateAppIntentRepresentation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/unableToCreateAppIntentRepresentation",
      "kind": "symbol",
      "role": "symbol",
      "title": "unableToCreateAppIntentRepresentation",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/unabletocreateappintentrepresentation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/voiceShortcutCreationFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voiceShortcutCreationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/voiceShortcutCreationFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "voiceShortcutCreationFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/voiceshortcutcreationfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/voiceShortcutDeleteFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voiceShortcutDeleteFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/voiceShortcutDeleteFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "voiceShortcutDeleteFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/voiceshortcutdeletefailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentError/voiceShortcutGetFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voiceShortcutGetFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC17INIntentErrorCodeLeV",
          "text": "INIntentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INIntentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentError/voiceShortcutGetFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "voiceShortcutGetFailed",
      "type": "topic",
      "url": "/documentation/intents/inintenterror/voiceshortcutgetfailed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for the Intents framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "INIntentErrorDomain",
      "type": "topic",
      "url": "/documentation/intents/inintenterrordomain"
    },
    "doc://com.apple.sirikit/documentation/Intents/INInteraction": {
      "abstract": [
        {
          "text": "An interaction between the user and your app involving an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INInteraction"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INInteraction"
        }
      ],
      "role": "symbol",
      "title": "INInteraction",
      "type": "topic",
      "url": "/documentation/intents/ininteraction"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/Code",
        "doc://com.apple.sirikit/documentation/Intents/INIntentErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Encoding-Errors",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/decodingGeneric",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/encodingFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/encodingGeneric"
      ],
      "title": "Encoding Errors"
    },
    {
      "anchor": "Image-Errors",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageGeneric",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageLoadingFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageNoServiceAvailable",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageServiceFailure",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyInvalid",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyLoop",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageProxyTimeout",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageRetrievalFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageStorageFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/imageScalingFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/permissionDenied"
      ],
      "title": "Image Errors"
    },
    {
      "anchor": "Voice-Shortcut-Errors",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/voiceShortcutCreationFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/voiceShortcutDeleteFailed",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/voiceShortcutGetFailed"
      ],
      "title": "Voice Shortcut Errors"
    },
    {
      "anchor": "Interaction-Errors",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/interactionOperationNotSupported",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/donatingInteraction",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/deletingAllInteractions",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/deletingInteractionWithIdentifiers",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/deletingInteractionWithGroupIdentifier"
      ],
      "title": "Interaction Errors"
    },
    {
      "anchor": "Extension-Errors",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/intentSupportedByMultipleExtension",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/restrictedIntentsNotSupportedByExtension",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/noHandlerProvidedForIntent",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/invalidIntentName",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/noAppAvailable",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/extensionLaunchingTimeout",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/extensionBringUpFailed"
      ],
      "title": "Extension Errors"
    },
    {
      "anchor": "Other-Errors",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/invalidUserVocabularyFileLocation",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/requestTimedOut",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/missingInformation"
      ],
      "title": "Other Errors"
    },
    {
      "anchor": "General-Error",
      "identifiers": [
        "doc://com.apple.documentation/documentation/sirikit/inintenterror/2882880-errorcode",
        "doc://com.apple.documentation/documentation/sirikit/inintenterror/2882876-erroruserinfo"
      ],
      "title": "General Error"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/errorDomain",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/noAppIntent",
        "doc://com.apple.sirikit/documentation/Intents/INIntentError/unableToCreateAppIntentRepresentation"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/title",
          "value": "INInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentErrorDomain/title",
          "value": "INIntentErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code/title",
          "value": "INIntentErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inintenterror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
