{
  "abstract": [
    {
      "text": "The type of content the media item describes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INMediaItemType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INMediaItemType"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INMediaItemType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INMediaItemType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INMediaItemType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItem/artist": {
      "abstract": [
        {
          "text": "The artist associated with the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "artist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItem/artist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "artist"
        }
      ],
      "role": "symbol",
      "title": "artist",
      "type": "topic",
      "url": "/documentation/intents/inmediaitem/artist"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItem/artwork": {
      "abstract": [
        {
          "text": "Artwork for the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "artwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INImage",
          "text": "INImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItem/artwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "artwork"
        }
      ],
      "role": "symbol",
      "title": "artwork",
      "type": "topic",
      "url": "/documentation/intents/inmediaitem/artwork"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItem/identifier": {
      "abstract": [
        {
          "text": "The value your app uses to identify the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItem/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/intents/inmediaitem/identifier"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItem/title": {
      "abstract": [
        {
          "text": "The media item title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItem/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/intents/inmediaitem/title"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItem/type": {
      "abstract": [
        {
          "text": "The media item type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INMediaItemType",
          "text": "INMediaItemType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItem/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/intents/inmediaitem/type"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType": {
      "abstract": [
        {
          "text": "The type of content the media item describes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMediaItemType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemType"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/album": {
      "abstract": [
        {
          "text": "A media type that indicates an album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "album"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/album",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeAlbum"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.album",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/album"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/algorithmicRadioStation": {
      "abstract": [
        {
          "text": "A media type that indicates related content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "algorithmicRadioStation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/algorithmicRadioStation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeAlgorithmicRadioStation"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.algorithmicRadioStation",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/algorithmicradiostation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/artist": {
      "abstract": [
        {
          "text": "A media type that indicates an artist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "artist"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/artist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeArtist"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.artist",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/artist"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/audioBook": {
      "abstract": [
        {
          "text": "A media type that indicates an audio book.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioBook"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/audioBook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeAudioBook"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.audioBook",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/audiobook"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/genre": {
      "abstract": [
        {
          "text": "A media type that indicates a genre.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genre"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/genre",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeGenre"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.genre",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/genre"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/movie": {
      "abstract": [
        {
          "text": "A media type that indicates a movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "movie"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/movie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeMovie"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.movie",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/movie"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/music": {
      "abstract": [
        {
          "text": "A media type that indicates music.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "music"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/music",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeMusic"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.music",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/music"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/musicStation": {
      "abstract": [
        {
          "text": "A media type that indicates a music station.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "musicStation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/musicStation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeMusicStation"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.musicStation",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/musicstation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/musicVideo": {
      "abstract": [
        {
          "text": "A media type that indicates a music video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "musicVideo"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/musicVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeMusicVideo"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.musicVideo",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/musicvideo"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/news": {
      "abstract": [
        {
          "text": "A media type that indicates news.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "news"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/news",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeNews"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.news",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/news"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/playlist": {
      "abstract": [
        {
          "text": "A media type that indicates a playlist of music.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playlist"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/playlist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypePlaylist"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.playlist",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/playlist"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/podcastEpisode": {
      "abstract": [
        {
          "text": "A media type that indicates a podcast episode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "podcastEpisode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/podcastEpisode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypePodcastEpisode"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.podcastEpisode",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/podcastepisode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/podcastPlaylist": {
      "abstract": [
        {
          "text": "A media type that indicates a playlist of podcast episodes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "podcastPlaylist"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/podcastPlaylist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypePodcastPlaylist"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.podcastPlaylist",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/podcastplaylist"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/podcastShow": {
      "abstract": [
        {
          "text": "A media type that indicates a podcast show.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "podcastShow"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/podcastShow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypePodcastShow"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.podcastShow",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/podcastshow"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/podcastStation": {
      "abstract": [
        {
          "text": "A media type that indicates a podcast station.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "podcastStation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/podcastStation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypePodcastStation"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.podcastStation",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/podcaststation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/radioStation": {
      "abstract": [
        {
          "text": "A media type that indicates a radio station.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "radioStation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/radioStation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeRadioStation"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.radioStation",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/radiostation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/song": {
      "abstract": [
        {
          "text": "A media type that indicates a song.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "song"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/song",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeSong"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.song",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/song"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/station": {
      "abstract": [
        {
          "text": "A media type that indicates a station.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "station"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/station",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeStation"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.station",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/station"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/tvShow": {
      "abstract": [
        {
          "text": "A media type that indicates a TV show or series.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tvShow"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/tvShow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeTVShow"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.tvShow",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/tvshow"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/tvShowEpisode": {
      "abstract": [
        {
          "text": "A media type that indicates an episode of a TV show or series.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tvShowEpisode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/tvShowEpisode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeTVShowEpisode"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.tvShowEpisode",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/tvshowepisode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/unknown": {
      "abstract": [
        {
          "text": "A media type that indicates an unknown type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaItemTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "INMediaItemType.unknown",
      "type": "topic",
      "url": "/documentation/intents/inmediaitemtype/unknown"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Describing-the-Media-Item",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMediaItem/artwork",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItem/identifier",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItem/title",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItem/artist",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItem/type"
      ],
      "title": "Describing the Media Item"
    }
  ],
  "topicSections": [
    {
      "anchor": "Stations",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/station",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/radioStation",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/algorithmicRadioStation"
      ],
      "title": "Stations"
    },
    {
      "anchor": "Music",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/album",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/artist",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/musicStation",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/musicVideo",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/playlist",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/song",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/music"
      ],
      "title": "Music"
    },
    {
      "anchor": "Movie-and-TV",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/movie",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/tvShow",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/tvShowEpisode"
      ],
      "title": "Movie and TV"
    },
    {
      "anchor": "Podcast",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/podcastEpisode",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/podcastPlaylist",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/podcastShow",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/podcastStation"
      ],
      "title": "Podcast"
    },
    {
      "anchor": "Audio-Book",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/audioBook"
      ],
      "title": "Audio Book"
    },
    {
      "anchor": "News",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/news"
      ],
      "title": "News"
    },
    {
      "anchor": "General",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/unknown",
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/genre"
      ],
      "title": "General"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INMediaItemType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Stations",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/station",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/radioStation",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/algorithmicRadioStation"
              ],
              "title": "Stations"
            },
            {
              "anchor": "Music",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/album",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/artist",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/musicStation",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/musicVideo",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/playlist",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/song",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/music"
              ],
              "title": "Music"
            },
            {
              "anchor": "Movie-and-TV",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/movie",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/tvShow",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/tvShowEpisode"
              ],
              "title": "Movie and TV"
            },
            {
              "anchor": "Podcast",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/podcastEpisode",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/podcastPlaylist",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/podcastShow",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/podcastStation"
              ],
              "title": "Podcast"
            },
            {
              "anchor": "Audio-Book",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/audioBook"
              ],
              "title": "Audio Book"
            },
            {
              "anchor": "News",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/news"
              ],
              "title": "News"
            },
            {
              "anchor": "General",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/unknown",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItemType/genre"
              ],
              "title": "General"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Describing-the-Media-Item",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMediaItem/artwork",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItem/identifier",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItem/title",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItem/artist",
                "doc://com.apple.sirikit/documentation/Intents/INMediaItem/type"
              ],
              "title": "Describing the Media Item"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INMediaItemType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1artist/title",
          "value": "INMediaItemTypeArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1artist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1music/title",
          "value": "INMediaItemTypeMusic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1music/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeMusic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItem~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItem~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1podcastStation/title",
          "value": "INMediaItemTypePodcastStation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1podcastStation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypePodcastStation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItem~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItem~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1radioStation/title",
          "value": "INMediaItemTypeRadioStation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1radioStation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeRadioStation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1algorithmicRadioStation/title",
          "value": "INMediaItemTypeAlgorithmicRadioStation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1algorithmicRadioStation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeAlgorithmicRadioStation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1song/title",
          "value": "INMediaItemTypeSong"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1song/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeSong"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1playlist/title",
          "value": "INMediaItemTypePlaylist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1playlist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypePlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1station/title",
          "value": "INMediaItemTypeStation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1station/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeStation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1audioBook/title",
          "value": "INMediaItemTypeAudioBook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1audioBook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeAudioBook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1podcastEpisode/title",
          "value": "INMediaItemTypePodcastEpisode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1podcastEpisode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypePodcastEpisode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType/title",
          "value": "INMediaItemType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1tvShowEpisode/title",
          "value": "INMediaItemTypeTVShowEpisode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1tvShowEpisode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeTVShowEpisode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1podcastPlaylist/title",
          "value": "INMediaItemTypePodcastPlaylist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1podcastPlaylist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypePodcastPlaylist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1podcastShow/title",
          "value": "INMediaItemTypePodcastShow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1podcastShow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypePodcastShow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1news/title",
          "value": "INMediaItemTypeNews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1news/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeNews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1musicStation/title",
          "value": "INMediaItemTypeMusicStation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1musicStation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeMusicStation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1genre/title",
          "value": "INMediaItemTypeGenre"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1genre/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeGenre"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1tvShow/title",
          "value": "INMediaItemTypeTVShow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1tvShow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeTVShow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItem~1artwork/title",
          "value": "artwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItem~1artwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "artwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1album/title",
          "value": "INMediaItemTypeAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1album/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1unknown/title",
          "value": "INMediaItemTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1movie/title",
          "value": "INMediaItemTypeMovie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1movie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeMovie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItem~1artist/title",
          "value": "artist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItem~1artist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "artist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItem~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItem~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1musicVideo/title",
          "value": "INMediaItemTypeMusicVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaItemType~1musicVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaItemTypeMusicVideo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inmediaitemtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inmediaitemtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
