{
  "abstract": [
    {
      "text": "Constants that describe the kinds of content a message can contain.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INMessageType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INMessageType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INMessageType"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INMessageType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INMessageType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INMessageType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessage/dateSent": {
      "abstract": [
        {
          "text": "The date and time the app sent the message to each recipient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dateSent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessage/dateSent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dateSent"
        }
      ],
      "role": "symbol",
      "title": "dateSent",
      "type": "topic",
      "url": "/documentation/intents/inmessage/datesent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessage/groupName": {
      "abstract": [
        {
          "text": "The name of the grouped conversation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groupName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSpeakableString",
          "text": "INSpeakableString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessage/groupName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "groupName"
        }
      ],
      "role": "symbol",
      "title": "groupName",
      "type": "topic",
      "url": "/documentation/intents/inmessage/groupname"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessage/messageType": {
      "abstract": [
        {
          "text": "The type of content the message contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messageType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INMessageType",
          "text": "INMessageType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessage/messageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "messageType"
        }
      ],
      "role": "symbol",
      "title": "messageType",
      "type": "topic",
      "url": "/documentation/intents/inmessage/messagetype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessage/serviceName": {
      "abstract": [
        {
          "text": "The name of the service that delivers the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessage/serviceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serviceName"
        }
      ],
      "role": "symbol",
      "title": "serviceName",
      "type": "topic",
      "url": "/documentation/intents/inmessage/servicename"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType": {
      "abstract": [
        {
          "text": "Constants that describe the kinds of content a message can contain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMessageType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageType"
        }
      ],
      "role": "symbol",
      "title": "INMessageType",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/activitySnippet": {
      "abstract": [
        {
          "text": "The message contains an activity snippet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activitySnippet"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/activitySnippet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeActivitySnippet"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.activitySnippet",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/activitysnippet"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/animoji": {
      "abstract": [
        {
          "text": "The message content is an animoji.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "animoji"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/animoji",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeAnimoji"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.animoji",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/animoji"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/audio": {
      "abstract": [
        {
          "text": "The message contains audio content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audio"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/audio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeAudio"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.audio",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/audio"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/digitalTouch": {
      "abstract": [
        {
          "text": "The message contains digital touch content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "digitalTouch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/digitalTouch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeDigitalTouch"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.digitalTouch",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/digitaltouch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/file": {
      "abstract": [
        {
          "text": "The message contains a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "file"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/file",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeFile"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.file",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/file"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/handwriting": {
      "abstract": [
        {
          "text": "The message contains handwritten content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handwriting"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/handwriting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeHandwriting"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.handwriting",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/handwriting"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/link": {
      "abstract": [
        {
          "text": "The message contains link content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "link"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/link",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeLink"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.link",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/link"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAddressCard": {
      "abstract": [
        {
          "text": "Media content containing an address card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaAddressCard"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAddressCard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeMediaAddressCard"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.mediaAddressCard",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/mediaaddresscard"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAnimatedImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaAnimatedImage"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAnimatedImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeMediaAnimatedImage"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.mediaAnimatedImage",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/mediaanimatedimage"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAudio": {
      "abstract": [
        {
          "text": "Media content containing audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaAudio"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeMediaAudio"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.mediaAudio",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/mediaaudio"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaCalendar": {
      "abstract": [
        {
          "text": "Media content containing calendar data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaCalendar"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaCalendar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeMediaCalendar"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.mediaCalendar",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/mediacalendar"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaImage": {
      "abstract": [
        {
          "text": "Media content containing an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaImage"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeMediaImage"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.mediaImage",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/mediaimage"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaLocation": {
      "abstract": [
        {
          "text": "Media content containing location data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaLocation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeMediaLocation"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.mediaLocation",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/medialocation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaPass": {
      "abstract": [
        {
          "text": "Media content containing PassKit data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaPass"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaPass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeMediaPass"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.mediaPass",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/mediapass"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaVideo": {
      "abstract": [
        {
          "text": "Media content containing video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaVideo"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeMediaVideo"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.mediaVideo",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/mediavideo"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/paymentNote": {
      "abstract": [
        {
          "text": "Content indicating the message contains notes about a payment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentNote"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/paymentNote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypePaymentNote"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.paymentNote",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/paymentnote"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/paymentRequest": {
      "abstract": [
        {
          "text": "Content indicating the message contains payment request information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentRequest"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/paymentRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypePaymentRequest"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.paymentRequest",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/paymentrequest"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/paymentSent": {
      "abstract": [
        {
          "text": "Content indicating the message contains sent payment information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentSent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/paymentSent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypePaymentSent"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.paymentSent",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/paymentsent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/reaction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reaction"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/reaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeReaction"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.reaction",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/reaction"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/sticker": {
      "abstract": [
        {
          "text": "The message contains sticker content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sticker"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/sticker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeSticker"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.sticker",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/sticker"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackDisliked": {
      "abstract": [
        {
          "text": "Content indicating that the user disliked something.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tapbackDisliked"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackDisliked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeTapbackDisliked"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.tapbackDisliked",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/tapbackdisliked"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackEmphasized": {
      "abstract": [
        {
          "text": "Content indicating that the user emphasized something.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tapbackEmphasized"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackEmphasized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeTapbackEmphasized"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.tapbackEmphasized",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/tapbackemphasized"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLaughed": {
      "abstract": [
        {
          "text": "Content indicating that the user laughed at something.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tapbackLaughed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLaughed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeTapbackLaughed"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.tapbackLaughed",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/tapbacklaughed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLiked": {
      "abstract": [
        {
          "text": "Content indicating that the user liked something.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tapbackLiked"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLiked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeTapbackLiked"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.tapbackLiked",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/tapbackliked"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLoved": {
      "abstract": [
        {
          "text": "Content indicating that the user loved something.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tapbackLoved"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeTapbackLoved"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.tapbackLoved",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/tapbackloved"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackQuestioned": {
      "abstract": [
        {
          "text": "Content indicating that the user questioned something.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tapbackQuestioned"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackQuestioned",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeTapbackQuestioned"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.tapbackQuestioned",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/tapbackquestioned"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/text": {
      "abstract": [
        {
          "text": "The message content is text-based.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/text",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeText"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.text",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/text"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/thirdPartyAttachment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thirdPartyAttachment"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/thirdPartyAttachment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeThirdPartyAttachment"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.thirdPartyAttachment",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/thirdpartyattachment"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessageType/unspecified": {
      "abstract": [
        {
          "text": "The message content isn’t specified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessageType/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessageTypeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INMessageType.unspecified",
      "type": "topic",
      "url": "/documentation/intents/inmessagetype/unspecified"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Supplementary-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMessage/dateSent",
        "doc://com.apple.sirikit/documentation/Intents/INMessage/groupName",
        "doc://com.apple.sirikit/documentation/Intents/INMessage/messageType",
        "doc://com.apple.sirikit/documentation/Intents/INMessage/serviceName"
      ],
      "title": "Getting the Supplementary Attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "General-Types",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/unspecified",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/text",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/animoji",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/audio",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/digitalTouch",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/handwriting",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/sticker",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/link",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/file",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/activitySnippet"
      ],
      "title": "General Types"
    },
    {
      "anchor": "Media-Types",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaCalendar",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaLocation",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAddressCard",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaImage",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaVideo",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaPass",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAudio"
      ],
      "title": "Media Types"
    },
    {
      "anchor": "Payment-Types",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/paymentNote",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/paymentRequest",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/paymentSent"
      ],
      "title": "Payment Types"
    },
    {
      "anchor": "Tapback-Types",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLiked",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackDisliked",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackEmphasized",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLoved",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackQuestioned",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLaughed"
      ],
      "title": "Tapback Types"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAnimatedImage",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/reaction",
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/thirdPartyAttachment"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMessageType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INMessageType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "General-Types",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/unspecified",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/text",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/animoji",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/audio",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/digitalTouch",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/handwriting",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/sticker",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/link",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/file",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/activitySnippet"
              ],
              "title": "General Types"
            },
            {
              "anchor": "Media-Types",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaCalendar",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaLocation",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAddressCard",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaImage",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaVideo",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaPass",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAudio"
              ],
              "title": "Media Types"
            },
            {
              "anchor": "Payment-Types",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/paymentNote",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/paymentRequest",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/paymentSent"
              ],
              "title": "Payment Types"
            },
            {
              "anchor": "Tapback-Types",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLiked",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackDisliked",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackEmphasized",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLoved",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackQuestioned",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/tapbackLaughed"
              ],
              "title": "Tapback Types"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/mediaAnimatedImage",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/reaction",
                "doc://com.apple.sirikit/documentation/Intents/INMessageType/thirdPartyAttachment"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Supplementary-Attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMessage/dateSent",
                "doc://com.apple.sirikit/documentation/Intents/INMessage/groupName",
                "doc://com.apple.sirikit/documentation/Intents/INMessage/messageType",
                "doc://com.apple.sirikit/documentation/Intents/INMessage/serviceName"
              ],
              "title": "Getting the Supplementary Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INMessageType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaImage/title",
          "value": "INMessageTypeMediaImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeMediaImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1digitalTouch/title",
          "value": "INMessageTypeDigitalTouch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1digitalTouch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeDigitalTouch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaCalendar/title",
          "value": "INMessageTypeMediaCalendar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaCalendar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeMediaCalendar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1paymentSent/title",
          "value": "INMessageTypePaymentSent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1paymentSent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypePaymentSent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackLaughed/title",
          "value": "INMessageTypeTapbackLaughed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackLaughed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeTapbackLaughed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaAddressCard/title",
          "value": "INMessageTypeMediaAddressCard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaAddressCard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeMediaAddressCard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType/title",
          "value": "INMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1file/title",
          "value": "INMessageTypeFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1file/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1handwriting/title",
          "value": "INMessageTypeHandwriting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1handwriting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeHandwriting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessage~1groupName/title",
          "value": "groupName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessage~1groupName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "groupName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaLocation/title",
          "value": "INMessageTypeMediaLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeMediaLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1text/title",
          "value": "INMessageTypeText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1text/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackEmphasized/title",
          "value": "INMessageTypeTapbackEmphasized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackEmphasized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeTapbackEmphasized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaVideo/title",
          "value": "INMessageTypeMediaVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeMediaVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackDisliked/title",
          "value": "INMessageTypeTapbackDisliked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackDisliked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeTapbackDisliked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaAudio/title",
          "value": "INMessageTypeMediaAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeMediaAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1reaction/title",
          "value": "INMessageTypeReaction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1reaction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeReaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1activitySnippet/title",
          "value": "INMessageTypeActivitySnippet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1activitySnippet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeActivitySnippet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaAnimatedImage/title",
          "value": "INMessageTypeMediaAnimatedImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaAnimatedImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeMediaAnimatedImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1unspecified/title",
          "value": "INMessageTypeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackLoved/title",
          "value": "INMessageTypeTapbackLoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackLoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeTapbackLoved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackLiked/title",
          "value": "INMessageTypeTapbackLiked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackLiked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeTapbackLiked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessage~1serviceName/title",
          "value": "serviceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessage~1serviceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serviceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1animoji/title",
          "value": "INMessageTypeAnimoji"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1animoji/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeAnimoji"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1audio/title",
          "value": "INMessageTypeAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1audio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1thirdPartyAttachment/title",
          "value": "INMessageTypeThirdPartyAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1thirdPartyAttachment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeThirdPartyAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackQuestioned/title",
          "value": "INMessageTypeTapbackQuestioned"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1tapbackQuestioned/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeTapbackQuestioned"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1paymentRequest/title",
          "value": "INMessageTypePaymentRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1paymentRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypePaymentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1sticker/title",
          "value": "INMessageTypeSticker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1sticker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeSticker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessage~1messageType/title",
          "value": "messageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessage~1messageType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "messageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1paymentNote/title",
          "value": "INMessageTypePaymentNote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1paymentNote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypePaymentNote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1link/title",
          "value": "INMessageTypeLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1link/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessage~1dateSent/title",
          "value": "dateSent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessage~1dateSent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dateSent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaPass/title",
          "value": "INMessageTypeMediaPass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessageType~1mediaPass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessageTypeMediaPass"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inmessagetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inmessagetype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
