{
  "abstract": [
    {
      "text": "Constants indicating the sort order for the found media items.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INMediaSortOrder",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INMediaSortOrder"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INMediaSortOrder"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INMediaSortOrder"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INMediaSortOrder"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaReference": {
      "abstract": [
        {
          "text": "Constants that describe a reference for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMediaReference"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaReference"
        }
      ],
      "role": "symbol",
      "title": "INMediaReference",
      "type": "topic",
      "url": "/documentation/intents/inmediareference"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/activityNames": {
      "abstract": [
        {
          "text": "The activity names to search for.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activityNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/activityNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activityNames"
        }
      ],
      "role": "symbol",
      "title": "activityNames",
      "type": "topic",
      "url": "/documentation/intents/inmediasearch/activitynames"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/genreNames": {
      "abstract": [
        {
          "text": "The media genres to search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genreNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/genreNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "genreNames"
        }
      ],
      "role": "symbol",
      "title": "genreNames",
      "type": "topic",
      "url": "/documentation/intents/inmediasearch/genrenames"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/mediaIdentifier": {
      "abstract": [
        {
          "text": "The unique media identifier to search for.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/mediaIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaIdentifier"
        }
      ],
      "role": "symbol",
      "title": "mediaIdentifier",
      "type": "topic",
      "url": "/documentation/intents/inmediasearch/mediaidentifier"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/mediaName": {
      "abstract": [
        {
          "text": "The name of the media to search for.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/mediaName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaName"
        }
      ],
      "role": "symbol",
      "title": "mediaName",
      "type": "topic",
      "url": "/documentation/intents/inmediasearch/medianame"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/mediaType": {
      "abstract": [
        {
          "text": "The type of media to search for.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INMediaItemType",
          "text": "INMediaItemType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/mediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaType"
        }
      ],
      "role": "symbol",
      "title": "mediaType",
      "type": "topic",
      "url": "/documentation/intents/inmediasearch/mediatype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/moodNames": {
      "abstract": [
        {
          "text": "The moods to search for.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moodNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/moodNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "moodNames"
        }
      ],
      "role": "symbol",
      "title": "moodNames",
      "type": "topic",
      "url": "/documentation/intents/inmediasearch/moodnames"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/reference": {
      "abstract": [
        {
          "text": "A reference for the media item to search for.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INMediaReference",
          "text": "INMediaReference"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/reference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reference"
        }
      ],
      "role": "symbol",
      "title": "reference",
      "type": "topic",
      "url": "/documentation/intents/inmediasearch/reference"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/releaseDate": {
      "abstract": [
        {
          "text": "The release date to search for.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "releaseDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INDateComponentsRange",
          "text": "INDateComponentsRange"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/releaseDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "releaseDate"
        }
      ],
      "role": "symbol",
      "title": "releaseDate",
      "type": "topic",
      "url": "/documentation/intents/inmediasearch/releasedate"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/sortOrder": {
      "abstract": [
        {
          "text": "The sort order for the found media items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sortOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INMediaSortOrder",
          "text": "INMediaSortOrder"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/sortOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sortOrder"
        }
      ],
      "role": "symbol",
      "title": "sortOrder",
      "type": "topic",
      "url": "/documentation/intents/inmediasearch/sortorder"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder": {
      "abstract": [
        {
          "text": "Constants indicating the sort order for the found media items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMediaSortOrder"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaSortOrder"
        }
      ],
      "role": "symbol",
      "title": "INMediaSortOrder",
      "type": "topic",
      "url": "/documentation/intents/inmediasortorder"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/best": {
      "abstract": [
        {
          "text": "The app sorts the media items from best to worst.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "best"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/best",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaSortOrderBest"
        }
      ],
      "role": "symbol",
      "title": "INMediaSortOrder.best",
      "type": "topic",
      "url": "/documentation/intents/inmediasortorder/best"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/inmediasortorder/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/newest": {
      "abstract": [
        {
          "text": "The app sorts the media items from newest to oldest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newest"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/newest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaSortOrderNewest"
        }
      ],
      "role": "symbol",
      "title": "INMediaSortOrder.newest",
      "type": "topic",
      "url": "/documentation/intents/inmediasortorder/newest"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/oldest": {
      "abstract": [
        {
          "text": "The app sorts the media items from oldest to newest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oldest"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/oldest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaSortOrderOldest"
        }
      ],
      "role": "symbol",
      "title": "INMediaSortOrder.oldest",
      "type": "topic",
      "url": "/documentation/intents/inmediasortorder/oldest"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/popular": {
      "abstract": [
        {
          "text": "The app sorts the media items from the most to least popular.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popular"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/popular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaSortOrderPopular"
        }
      ],
      "role": "symbol",
      "title": "INMediaSortOrder.popular",
      "type": "topic",
      "url": "/documentation/intents/inmediasortorder/popular"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/recommended": {
      "abstract": [
        {
          "text": "The app sorts the media items with those it recommends first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recommended"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/recommended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaSortOrderRecommended"
        }
      ],
      "role": "symbol",
      "title": "INMediaSortOrder.recommended",
      "type": "topic",
      "url": "/documentation/intents/inmediasortorder/recommended"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/trending": {
      "abstract": [
        {
          "text": "The app sorts the media items with those trending the most first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trending"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/trending",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaSortOrderTrending"
        }
      ],
      "role": "symbol",
      "title": "INMediaSortOrder.trending",
      "type": "topic",
      "url": "/documentation/intents/inmediasortorder/trending"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/unknown": {
      "abstract": [
        {
          "text": "The sort order is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaSortOrderUnknown"
        }
      ],
      "role": "symbol",
      "title": "INMediaSortOrder.unknown",
      "type": "topic",
      "url": "/documentation/intents/inmediasortorder/unknown"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/unpopular": {
      "abstract": [
        {
          "text": "The app sorts the media items from the least to most popular.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unpopular"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/unpopular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaSortOrderUnpopular"
        }
      ],
      "role": "symbol",
      "title": "INMediaSortOrder.unpopular",
      "type": "topic",
      "url": "/documentation/intents/inmediasortorder/unpopular"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/worst": {
      "abstract": [
        {
          "text": "The app sorts the media items from worst to best.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "worst"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/worst",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMediaSortOrderWorst"
        }
      ],
      "role": "symbol",
      "title": "INMediaSortOrder.worst",
      "type": "topic",
      "url": "/documentation/intents/inmediasortorder/worst"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Retrieving-Search-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/genreNames",
        "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/mediaIdentifier",
        "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/mediaName",
        "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/mediaType",
        "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/moodNames",
        "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/reference",
        "doc://com.apple.sirikit/documentation/Intents/INMediaReference",
        "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/releaseDate",
        "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/sortOrder",
        "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/activityNames"
      ],
      "title": "Retrieving Search Information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/unknown",
        "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/newest",
        "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/oldest",
        "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/best",
        "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/worst",
        "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/popular",
        "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/unpopular",
        "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/trending",
        "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/recommended"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INMediaSortOrder"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSortOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSortOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/unknown",
                "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/newest",
                "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/oldest",
                "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/best",
                "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/worst",
                "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/popular",
                "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/unpopular",
                "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/trending",
                "doc://com.apple.sirikit/documentation/Intents/INMediaSortOrder/recommended"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Retrieving-Search-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/genreNames",
                "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/mediaIdentifier",
                "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/mediaName",
                "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/mediaType",
                "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/moodNames",
                "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/reference",
                "doc://com.apple.sirikit/documentation/Intents/INMediaReference",
                "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/releaseDate",
                "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/sortOrder",
                "doc://com.apple.sirikit/documentation/Intents/INMediaSearch/activityNames"
              ],
              "title": "Retrieving Search Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INMediaSortOrder"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1recommended/title",
          "value": "INMediaSortOrderRecommended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1recommended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSortOrderRecommended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1popular/title",
          "value": "INMediaSortOrderPopular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1popular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSortOrderPopular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1newest/title",
          "value": "INMediaSortOrderNewest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1newest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSortOrderNewest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1worst/title",
          "value": "INMediaSortOrderWorst"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1worst/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSortOrderWorst"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1releaseDate/title",
          "value": "releaseDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1releaseDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "releaseDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1unknown/title",
          "value": "INMediaSortOrderUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSortOrderUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1moodNames/title",
          "value": "moodNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1moodNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "moodNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1activityNames/title",
          "value": "activityNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1activityNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activityNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1reference/title",
          "value": "reference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1reference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaReference/title",
          "value": "INMediaReference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaReference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1trending/title",
          "value": "INMediaSortOrderTrending"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1trending/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSortOrderTrending"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1best/title",
          "value": "INMediaSortOrderBest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1best/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSortOrderBest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1mediaType/title",
          "value": "mediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1mediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1unpopular/title",
          "value": "INMediaSortOrderUnpopular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1unpopular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSortOrderUnpopular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1sortOrder/title",
          "value": "sortOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1sortOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sortOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1mediaIdentifier/title",
          "value": "mediaIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1mediaIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1oldest/title",
          "value": "INMediaSortOrderOldest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder~1oldest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSortOrderOldest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder/title",
          "value": "INMediaSortOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSortOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSortOrder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMediaSortOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1genreNames/title",
          "value": "genreNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1genreNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "genreNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1mediaName/title",
          "value": "mediaName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMediaSearch~1mediaName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inmediasortorder"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inmediasortorder"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
