{
  "abstract": [
    {
      "text": "Detailed information about a financial transaction made between two users.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INPaymentRecord",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INPaymentRecord"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INPaymentRecord"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "INPaymentRecord"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INPaymentRecord"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object contains the details of a financial transaction that your app is facilitating. You create instances of this class when handling payment-related intents. The payment record contains the users involved in the transaction, the amount of money to transfer, and the current state of the transaction. Siri conveys this detailed information to the user at appropriate times.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When creating payment records, specify as many details as possible. Siri always asks the user to confirm payments before asking your Intents extension to process them. During confirmation, Siri displays the information from this object in the confirmation interface. Omitting important pieces of information, such as the recipient or currency amount, might cause the user to cancel the transaction.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAccountType": {
      "abstract": [
        {
          "text": "Constants indicating the type of account involved in a financial transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAccountType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAccountType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAccountType"
        }
      ],
      "role": "symbol",
      "title": "INAccountType",
      "type": "topic",
      "url": "/documentation/intents/inaccounttype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCurrencyAmount": {
      "abstract": [
        {
          "text": "An amount of money to transfer during a financial transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCurrencyAmount"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCurrencyAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCurrencyAmount"
        }
      ],
      "role": "symbol",
      "title": "INCurrencyAmount",
      "type": "topic",
      "url": "/documentation/intents/incurrencyamount"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentAccount": {
      "abstract": [
        {
          "text": "A user account that provides the funds when making a payment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPaymentAccount"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentAccount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentAccount"
        }
      ],
      "role": "symbol",
      "title": "INPaymentAccount",
      "type": "topic",
      "url": "/documentation/intents/inpaymentaccount"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentAmount": {
      "abstract": [
        {
          "text": "The amount of money to apply to a bill payment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPaymentAmount"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentAmount"
        }
      ],
      "role": "symbol",
      "title": "INPaymentAmount",
      "type": "topic",
      "url": "/documentation/intents/inpaymentamount"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentMethod": {
      "abstract": [
        {
          "text": "Information about a form of payment supported by your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPaymentMethod"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentMethod"
        }
      ],
      "role": "symbol",
      "title": "INPaymentMethod",
      "type": "topic",
      "url": "/documentation/intents/inpaymentmethod"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord": {
      "abstract": [
        {
          "text": "Detailed information about a financial transaction made between two users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPaymentRecord"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentRecord"
        }
      ],
      "role": "symbol",
      "title": "INPaymentRecord",
      "type": "topic",
      "url": "/documentation/intents/inpaymentrecord"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/currencyAmount": {
      "abstract": [
        {
          "text": "The type of currency to transfer and the amount to transfer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currencyAmount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
          "text": "INCurrencyAmount"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/currencyAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currencyAmount"
        }
      ],
      "role": "symbol",
      "title": "currencyAmount",
      "type": "topic",
      "url": "/documentation/intents/inpaymentrecord/currencyamount"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/feeAmount": {
      "abstract": [
        {
          "text": "The total amount of any fees added to the payment record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "feeAmount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
          "text": "INCurrencyAmount"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/feeAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "feeAmount"
        }
      ],
      "role": "symbol",
      "title": "feeAmount",
      "type": "topic",
      "url": "/documentation/intents/inpaymentrecord/feeamount"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/init(payee:payer:currencyAmount:paymentMethod:note:status:)": {
      "abstract": [
        {
          "text": "Initializes a payment record with the specified payment details.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "payee"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPerson",
          "text": "INPerson"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "payer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPerson",
          "text": "INPerson"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "currencyAmount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
          "text": "INCurrencyAmount"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "paymentMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPaymentMethod",
          "text": "INPaymentMethod"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "note"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPaymentStatus",
          "text": "INPaymentStatus"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/init(payee:payer:currencyAmount:paymentMethod:note:status:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPayee:payer:currencyAmount:paymentMethod:note:status:"
        }
      ],
      "role": "symbol",
      "title": "init(payee:payer:currencyAmount:paymentMethod:note:status:)",
      "type": "topic",
      "url": "/documentation/intents/inpaymentrecord/init(payee:payer:currencyamount:paymentmethod:note:status:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/init(payee:payer:currencyAmount:paymentMethod:note:status:feeAmount:)": {
      "abstract": [
        {
          "text": "Initializes a payment record with the specified payment details.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "payee"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPerson",
          "text": "INPerson"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "payer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPerson",
          "text": "INPerson"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "currencyAmount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
          "text": "INCurrencyAmount"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "paymentMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPaymentMethod",
          "text": "INPaymentMethod"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "note"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPaymentStatus",
          "text": "INPaymentStatus"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "feeAmount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCurrencyAmount",
          "text": "INCurrencyAmount"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/init(payee:payer:currencyAmount:paymentMethod:note:status:feeAmount:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPayee:payer:currencyAmount:paymentMethod:note:status:feeAmount:"
        }
      ],
      "role": "symbol",
      "title": "init(payee:payer:currencyAmount:paymentMethod:note:status:feeAmount:)",
      "type": "topic",
      "url": "/documentation/intents/inpaymentrecord/init(payee:payer:currencyamount:paymentmethod:note:status:feeamount:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/note": {
      "abstract": [
        {
          "text": "A description of the payment to send.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "note"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/note",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "note"
        }
      ],
      "role": "symbol",
      "title": "note",
      "type": "topic",
      "url": "/documentation/intents/inpaymentrecord/note"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/payee": {
      "abstract": [
        {
          "text": "The person receiving the funds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "payee"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPerson",
          "text": "INPerson"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/payee",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "payee"
        }
      ],
      "role": "symbol",
      "title": "payee",
      "type": "topic",
      "url": "/documentation/intents/inpaymentrecord/payee"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/payer": {
      "abstract": [
        {
          "text": "The person providing the funds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "payer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPerson",
          "text": "INPerson"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/payer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "payer"
        }
      ],
      "role": "symbol",
      "title": "payer",
      "type": "topic",
      "url": "/documentation/intents/inpaymentrecord/payer"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/paymentMethod": {
      "abstract": [
        {
          "text": "The payment method used to supply the funds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentMethod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPaymentMethod",
          "text": "INPaymentMethod"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/paymentMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "paymentMethod"
        }
      ],
      "role": "symbol",
      "title": "paymentMethod",
      "type": "topic",
      "url": "/documentation/intents/inpaymentrecord/paymentmethod"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/status": {
      "abstract": [
        {
          "text": "The current status of the financial transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPaymentStatus",
          "text": "INPaymentStatus"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/status",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "status"
        }
      ],
      "role": "symbol",
      "title": "status",
      "type": "topic",
      "url": "/documentation/intents/inpaymentrecord/status"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentStatus": {
      "abstract": [
        {
          "text": "Constants indicating the state of the financial transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPaymentStatus"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentStatus"
        }
      ],
      "role": "symbol",
      "title": "INPaymentStatus",
      "type": "topic",
      "url": "/documentation/intents/inpaymentstatus"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPerson": {
      "abstract": [
        {
          "text": "Information about a person participating in a SiriKit interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPerson"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPerson",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPerson"
        }
      ],
      "role": "symbol",
      "title": "INPerson",
      "type": "topic",
      "url": "/documentation/intents/inperson"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INAccountType",
        "doc://com.apple.sirikit/documentation/Intents/INCurrencyAmount",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentAccount",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentAmount",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentMethod",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentStatus",
        "doc://com.apple.sirikit/documentation/Intents/INPerson"
      ],
      "title": "Data Objects"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Payment-Record-Object",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/init(payee:payer:currencyAmount:paymentMethod:note:status:feeAmount:)",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/init(payee:payer:currencyAmount:paymentMethod:note:status:)"
      ],
      "title": "Creating a Payment Record Object"
    },
    {
      "anchor": "Getting-the-Payment-Status",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/status"
      ],
      "title": "Getting the Payment Status"
    },
    {
      "anchor": "Getting-Payment-Record-Details",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/payee",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/payer",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/currencyAmount",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/feeAmount",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/paymentMethod",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/note"
      ],
      "title": "Getting Payment Record Details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INPaymentRecord"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Payment-Record-Object",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/init(payee:payer:currencyAmount:paymentMethod:note:status:feeAmount:)",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/init(payee:payer:currencyAmount:paymentMethod:note:status:)"
              ],
              "title": "Creating a Payment Record Object"
            },
            {
              "anchor": "Getting-the-Payment-Status",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/status"
              ],
              "title": "Getting the Payment Status"
            },
            {
              "anchor": "Getting-Payment-Record-Details",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/payee",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/payer",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/currencyAmount",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/feeAmount",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/paymentMethod",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentRecord/note"
              ],
              "title": "Getting Payment Record Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Objects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INAccountType",
                "doc://com.apple.sirikit/documentation/Intents/INCurrencyAmount",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentAccount",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentAmount",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentMethod",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentStatus",
                "doc://com.apple.sirikit/documentation/Intents/INPerson"
              ],
              "title": "Data Objects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INPaymentRecord"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCurrencyAmount/title",
          "value": "INCurrencyAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCurrencyAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCurrencyAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCurrencyAmount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCurrencyAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1status/title",
          "value": "status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1status/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPerson/title",
          "value": "INPerson"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPerson/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPerson/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethod/title",
          "value": "INPaymentMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethod/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentStatus/title",
          "value": "INPaymentStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAccountType/title",
          "value": "INAccountType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAccountType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAccountType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAccountType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAccountType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1currencyAmount/title",
          "value": "currencyAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1currencyAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currencyAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentAccount/title",
          "value": "INPaymentAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentAccount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentAccount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1paymentMethod/title",
          "value": "paymentMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1paymentMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "paymentMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1feeAmount/title",
          "value": "feeAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1feeAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "feeAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentAmount/title",
          "value": "INPaymentAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentAmount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1init(payee:payer:currencyAmount:paymentMethod:note:status:feeAmount:)/title",
          "value": "initWithPayee:payer:currencyAmount:paymentMethod:note:status:feeAmount:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1init(payee:payer:currencyAmount:paymentMethod:note:status:feeAmount:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPayee:payer:currencyAmount:paymentMethod:note:status:feeAmount:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1payer/title",
          "value": "payer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1payer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "payer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1init(payee:payer:currencyAmount:paymentMethod:note:status:)/title",
          "value": "initWithPayee:payer:currencyAmount:paymentMethod:note:status:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1init(payee:payer:currencyAmount:paymentMethod:note:status:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPayee:payer:currencyAmount:paymentMethod:note:status:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1payee/title",
          "value": "payee"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1payee/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "payee"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord/title",
          "value": "INPaymentRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1note/title",
          "value": "note"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentRecord~1note/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "note"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inpaymentrecord"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inpaymentrecord"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
