{
  "abstract": [
    {
      "text": "Constants describing how the person handle relates to the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@INPersonHandleLabel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INPersonHandleLabel"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INPersonHandleLabel"
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "INPersonHandleLabel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INPersonHandleLabel"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPerson": {
      "abstract": [
        {
          "text": "Information about a person participating in a SiriKit interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPerson"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPerson",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPerson"
        }
      ],
      "role": "symbol",
      "title": "INPerson",
      "type": "topic",
      "url": "/documentation/intents/inperson"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonHandle": {
      "abstract": [
        {
          "text": "The identifying information for a user of your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPersonHandle"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonHandle"
        }
      ],
      "role": "symbol",
      "title": "INPersonHandle",
      "type": "topic",
      "url": "/documentation/intents/inpersonhandle"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel": {
      "abstract": [
        {
          "text": "Constants describing how the person handle relates to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPersonHandleLabel"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonHandleLabel"
        }
      ],
      "role": "symbol",
      "title": "INPersonHandleLabel",
      "type": "topic",
      "url": "/documentation/intents/inpersonhandlelabel"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/home": {
      "abstract": [
        {
          "text": "A constant indicating that the handle is associated with the user’s home.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "home"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonHandleLabel",
          "text": "INPersonHandleLabel"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/home",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonHandleLabelHome"
        }
      ],
      "role": "symbol",
      "title": "home",
      "type": "topic",
      "url": "/documentation/intents/inpersonhandlelabel/home"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/homeFax": {
      "abstract": [
        {
          "text": "A constant indicating that the handle represents a home fax number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "homeFax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonHandleLabel",
          "text": "INPersonHandleLabel"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/homeFax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonHandleLabelHomeFax"
        }
      ],
      "role": "symbol",
      "title": "homeFax",
      "type": "topic",
      "url": "/documentation/intents/inpersonhandlelabel/homefax"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/iPhone": {
      "abstract": [
        {
          "text": "A constant indicating that the handle is associated with the user’s iPhone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iPhone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonHandleLabel",
          "text": "INPersonHandleLabel"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/iPhone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonHandleLabeliPhone"
        }
      ],
      "role": "symbol",
      "title": "iPhone",
      "type": "topic",
      "url": "/documentation/intents/inpersonhandlelabel/iphone"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/init(_:)": {
      "abstract": [
        {
          "text": "Creates a person handle label with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/intents/inpersonhandlelabel/init(_:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a person handle label with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/inpersonhandlelabel/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/main": {
      "abstract": [
        {
          "text": "A constant indicating that the handle is the primary way to contact the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "main"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonHandleLabel",
          "text": "INPersonHandleLabel"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/main",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonHandleLabelMain"
        }
      ],
      "role": "symbol",
      "title": "main",
      "type": "topic",
      "url": "/documentation/intents/inpersonhandlelabel/main"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/mobile": {
      "abstract": [
        {
          "text": "A constant indicating that the handle is associated with a mobile device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mobile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonHandleLabel",
          "text": "INPersonHandleLabel"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/mobile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonHandleLabelMobile"
        }
      ],
      "role": "symbol",
      "title": "mobile",
      "type": "topic",
      "url": "/documentation/intents/inpersonhandlelabel/mobile"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/other": {
      "abstract": [
        {
          "text": "A constant indicating that the handle is associated with a location or device not specified by any other constant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "other"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonHandleLabel",
          "text": "INPersonHandleLabel"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/other",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonHandleLabelOther"
        }
      ],
      "role": "symbol",
      "title": "other",
      "type": "topic",
      "url": "/documentation/intents/inpersonhandlelabel/other"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/pager": {
      "abstract": [
        {
          "text": "A constant indicating that the handle is associated with the user’s pager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonHandleLabel",
          "text": "INPersonHandleLabel"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/pager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonHandleLabelPager"
        }
      ],
      "role": "symbol",
      "title": "pager",
      "type": "topic",
      "url": "/documentation/intents/inpersonhandlelabel/pager"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/school": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "school"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonHandleLabel",
          "text": "INPersonHandleLabel"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/school",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonHandleLabelSchool"
        }
      ],
      "role": "symbol",
      "title": "school",
      "type": "topic",
      "url": "/documentation/intents/inpersonhandlelabel/school"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/work": {
      "abstract": [
        {
          "text": "A constant indicating that the handle is associated with the user’s work.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "work"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonHandleLabel",
          "text": "INPersonHandleLabel"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/work",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonHandleLabelWork"
        }
      ],
      "role": "symbol",
      "title": "work",
      "type": "topic",
      "url": "/documentation/intents/inpersonhandlelabel/work"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/workFax": {
      "abstract": [
        {
          "text": "A constant indicating that the handle represents a work fax number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workFax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonHandleLabel",
          "text": "INPersonHandleLabel"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/workFax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonHandleLabelWorkFax"
        }
      ],
      "role": "symbol",
      "title": "workFax",
      "type": "topic",
      "url": "/documentation/intents/inpersonhandlelabel/workfax"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Contacts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPerson",
        "doc://com.apple.sirikit/documentation/Intents/INPersonHandle"
      ],
      "title": "Contacts"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/init(_:)",
        "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/home",
        "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/homeFax",
        "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/iPhone",
        "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/main",
        "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/mobile",
        "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/other",
        "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/pager",
        "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/work",
        "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/workFax",
        "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/school"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INPersonHandleLabel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonHandleLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonHandleLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/home",
                "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/homeFax",
                "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/iPhone",
                "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/main",
                "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/mobile",
                "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/other",
                "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/pager",
                "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/work",
                "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/workFax",
                "doc://com.apple.sirikit/documentation/Intents/INPersonHandleLabel/school"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Contacts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPerson",
                "doc://com.apple.sirikit/documentation/Intents/INPersonHandle"
              ],
              "title": "Contacts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "INPersonHandleLabel"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel/title",
          "value": "INPersonHandleLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonHandleLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonHandleLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1main/title",
          "value": "INPersonHandleLabelMain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1main/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonHandleLabelMain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandle/title",
          "value": "INPersonHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPerson/title",
          "value": "INPerson"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPerson/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPerson/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1homeFax/title",
          "value": "INPersonHandleLabelHomeFax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1homeFax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonHandleLabelHomeFax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1work/title",
          "value": "INPersonHandleLabelWork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1work/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonHandleLabelWork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1pager/title",
          "value": "INPersonHandleLabelPager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1pager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonHandleLabelPager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1school/title",
          "value": "INPersonHandleLabelSchool"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1school/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonHandleLabelSchool"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1home/title",
          "value": "INPersonHandleLabelHome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1home/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonHandleLabelHome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1mobile/title",
          "value": "INPersonHandleLabelMobile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1mobile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonHandleLabelMobile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1other/title",
          "value": "INPersonHandleLabelOther"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1other/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonHandleLabelOther"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1iPhone/title",
          "value": "INPersonHandleLabeliPhone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1iPhone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonHandleLabeliPhone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1workFax/title",
          "value": "INPersonHandleLabelWorkFax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonHandleLabel~1workFax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonHandleLabelWorkFax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inpersonhandlelabel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inpersonhandlelabel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
