{
  "abstract": [
    {
      "text": "Constants indicating the relationship between the person using the device and another person.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@INPersonRelationship",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INPersonRelationship"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INPersonRelationship"
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "INPersonRelationship"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INPersonRelationship"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPerson/relationship": {
      "abstract": [
        {
          "text": "The relationship between this person and the person using the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relationship"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPerson/relationship",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "relationship"
        }
      ],
      "role": "symbol",
      "title": "relationship",
      "type": "topic",
      "url": "/documentation/intents/inperson/relationship"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship": {
      "abstract": [
        {
          "text": "Constants indicating the relationship between the person using the device and another person.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationship"
        }
      ],
      "role": "symbol",
      "title": "INPersonRelationship",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/assistant": {
      "abstract": [
        {
          "text": "The person is an assistant to the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assistant"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/assistant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipAssistant"
        }
      ],
      "role": "symbol",
      "title": "assistant",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/assistant"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/brother": {
      "abstract": [
        {
          "text": "The person is the brother of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "brother"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/brother",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipBrother"
        }
      ],
      "role": "symbol",
      "title": "brother",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/brother"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/child": {
      "abstract": [
        {
          "text": "The person is a child of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "child"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/child",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipChild"
        }
      ],
      "role": "symbol",
      "title": "child",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/child"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/daughter": {
      "abstract": [
        {
          "text": "The person is the daughter of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "daughter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/daughter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipDaughter"
        }
      ],
      "role": "symbol",
      "title": "daughter",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/daughter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/father": {
      "abstract": [
        {
          "text": "The person is the father of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "father"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/father",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipFather"
        }
      ],
      "role": "symbol",
      "title": "father",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/father"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/friend": {
      "abstract": [
        {
          "text": "The person is a friend of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "friend"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/friend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipFriend"
        }
      ],
      "role": "symbol",
      "title": "friend",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/friend"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/init(_:)": {
      "abstract": [
        {
          "text": "Creates a person relationship type with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/init(_:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a person relationship type with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/manager": {
      "abstract": [
        {
          "text": "The person is the manager of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/manager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipManager"
        }
      ],
      "role": "symbol",
      "title": "manager",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/manager"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/mother": {
      "abstract": [
        {
          "text": "The person is the mother of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mother"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/mother",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipMother"
        }
      ],
      "role": "symbol",
      "title": "mother",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/mother"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/parent": {
      "abstract": [
        {
          "text": "The person is a parent of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/parent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipParent"
        }
      ],
      "role": "symbol",
      "title": "parent",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/parent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/partner": {
      "abstract": [
        {
          "text": "The person is the partner of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "partner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/partner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipPartner"
        }
      ],
      "role": "symbol",
      "title": "partner",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/partner"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/sister": {
      "abstract": [
        {
          "text": "The person is the sister of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sister"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/sister",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipSister"
        }
      ],
      "role": "symbol",
      "title": "sister",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/sister"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/son": {
      "abstract": [
        {
          "text": "The person is the son of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "son"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/son",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipSon"
        }
      ],
      "role": "symbol",
      "title": "son",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/son"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/spouse": {
      "abstract": [
        {
          "text": "The person is the spouse of the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spouse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@INPersonRelationship",
          "text": "INPersonRelationship"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/spouse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonRelationshipSpouse"
        }
      ],
      "role": "symbol",
      "title": "spouse",
      "type": "topic",
      "url": "/documentation/intents/inpersonrelationship/spouse"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-relationship-details",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPerson/relationship"
      ],
      "title": "Accessing relationship details"
    }
  ],
  "topicSections": [
    {
      "anchor": "Relationship-Type",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/assistant",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/brother",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/child",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/father",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/friend",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/manager",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/mother",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/parent",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/partner",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/sister",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/spouse",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/daughter",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/son"
      ],
      "title": "Relationship Type"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/init(_:)",
        "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INPersonRelationship"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationship"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationship"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Relationship-Type",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/assistant",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/brother",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/child",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/father",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/friend",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/manager",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/mother",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/parent",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/partner",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/sister",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/spouse",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/daughter",
                "doc://com.apple.sirikit/documentation/Intents/INPersonRelationship/son"
              ],
              "title": "Relationship Type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-relationship-details",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPerson/relationship"
              ],
              "title": "Accessing relationship details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "INPersonRelationship"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1friend/title",
          "value": "INPersonRelationshipFriend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1friend/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipFriend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1parent/title",
          "value": "INPersonRelationshipParent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1parent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipParent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPerson~1relationship/title",
          "value": "relationship"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPerson~1relationship/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "relationship"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1child/title",
          "value": "INPersonRelationshipChild"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1child/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipChild"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1spouse/title",
          "value": "INPersonRelationshipSpouse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1spouse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipSpouse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1partner/title",
          "value": "INPersonRelationshipPartner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1partner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipPartner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship/title",
          "value": "INPersonRelationship"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationship"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationship"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1son/title",
          "value": "INPersonRelationshipSon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1son/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipSon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1manager/title",
          "value": "INPersonRelationshipManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1manager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1sister/title",
          "value": "INPersonRelationshipSister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1sister/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipSister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1brother/title",
          "value": "INPersonRelationshipBrother"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1brother/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipBrother"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1daughter/title",
          "value": "INPersonRelationshipDaughter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1daughter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipDaughter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1father/title",
          "value": "INPersonRelationshipFather"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1father/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipFather"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1mother/title",
          "value": "INPersonRelationshipMother"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1mother/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipMother"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1assistant/title",
          "value": "INPersonRelationshipAssistant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonRelationship~1assistant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonRelationshipAssistant"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inpersonrelationship"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inpersonrelationship"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
