{
  "abstract": [
    {
      "text": "Constants indicating attributes of a photo.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INPhotoAttributeOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INPhotoAttributeOptions"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INPhotoAttributeOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INPhotoAttributeOptions is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INPhotoAttributeOptions is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INPhotoAttributeOptions is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INPhotoAttributeOptions is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "3.2",
        "message": "INPhotoAttributeOptions is deprecated. There is no replacement.",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "INPhotoAttributeOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions": {
      "abstract": [
        {
          "text": "Constants indicating attributes of a photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "role": "symbol",
      "title": "INPhotoAttributeOptions",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/GIF": {
      "abstract": [
        {
          "text": "A Graphics Interchange Format image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GIF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/GIF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionGIF"
        }
      ],
      "role": "symbol",
      "title": "GIF",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/gif"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/bouncePhoto": {
      "abstract": [
        {
          "text": "A live photo edited with the bounce effect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bouncePhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/bouncePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionBouncePhoto"
        }
      ],
      "role": "symbol",
      "title": "bouncePhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/bouncephoto"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/burstPhoto": {
      "abstract": [
        {
          "text": "A burst-mode photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "burstPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/burstPhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionBurstPhoto"
        }
      ],
      "role": "symbol",
      "title": "burstPhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/burstphoto"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/chromeFilter": {
      "abstract": [
        {
          "text": "A chrome filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chromeFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/chromeFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionChromeFilter"
        }
      ],
      "role": "symbol",
      "title": "chromeFilter",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/chromefilter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/fadeFilter": {
      "abstract": [
        {
          "text": "A fade filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fadeFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/fadeFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionFadeFilter"
        }
      ],
      "role": "symbol",
      "title": "fadeFilter",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/fadefilter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/favorite": {
      "abstract": [
        {
          "text": "A favorite item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "favorite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/favorite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionFavorite"
        }
      ],
      "role": "symbol",
      "title": "favorite",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/favorite"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/flash": {
      "abstract": [
        {
          "text": "A photo taken with a flash.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/flash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionFlash"
        }
      ],
      "role": "symbol",
      "title": "flash",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/flash"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/frontFacingCamera": {
      "abstract": [
        {
          "text": "Taken using a front-facing camera.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frontFacingCamera"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/frontFacingCamera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionFrontFacingCamera"
        }
      ],
      "role": "symbol",
      "title": "frontFacingCamera",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/frontfacingcamera"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/hdrPhoto": {
      "abstract": [
        {
          "text": "An HDR photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hdrPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/hdrPhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionHDRPhoto"
        }
      ],
      "role": "symbol",
      "title": "hdrPhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/hdrphoto"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new instance with the specified raw value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/instantFilter": {
      "abstract": [
        {
          "text": "An instant filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instantFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/instantFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionInstantFilter"
        }
      ],
      "role": "symbol",
      "title": "instantFilter",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/instantfilter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/landscapeOrientation": {
      "abstract": [
        {
          "text": "A landscape aspect ratio.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "landscapeOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/landscapeOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionLandscapeOrientation"
        }
      ],
      "role": "symbol",
      "title": "landscapeOrientation",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/landscapeorientation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/livePhoto": {
      "abstract": [
        {
          "text": "A live photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "livePhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/livePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionLivePhoto"
        }
      ],
      "role": "symbol",
      "title": "livePhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/livephoto"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/longExposurePhoto": {
      "abstract": [
        {
          "text": "A live photo edited with the long exxposure effect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "longExposurePhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/longExposurePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionLongExposurePhoto"
        }
      ],
      "role": "symbol",
      "title": "longExposurePhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/longexposurephoto"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/loopPhoto": {
      "abstract": [
        {
          "text": "A live photo edited with the loop effect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loopPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/loopPhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionLoopPhoto"
        }
      ],
      "role": "symbol",
      "title": "loopPhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/loopphoto"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/monoFilter": {
      "abstract": [
        {
          "text": "A mono filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monoFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/monoFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionMonoFilter"
        }
      ],
      "role": "symbol",
      "title": "monoFilter",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/monofilter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/noirFilter": {
      "abstract": [
        {
          "text": "A noir filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noirFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/noirFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionNoirFilter"
        }
      ],
      "role": "symbol",
      "title": "noirFilter",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/noirfilter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/panoramaPhoto": {
      "abstract": [
        {
          "text": "A panorama photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "panoramaPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/panoramaPhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionPanoramaPhoto"
        }
      ],
      "role": "symbol",
      "title": "panoramaPhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/panoramaphoto"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/photo": {
      "abstract": [
        {
          "text": "A still image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/photo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionPhoto"
        }
      ],
      "role": "symbol",
      "title": "photo",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/photo"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/portraitOrientation": {
      "abstract": [
        {
          "text": "A portrait aspect ratio.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portraitOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/portraitOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionPortraitOrientation"
        }
      ],
      "role": "symbol",
      "title": "portraitOrientation",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/portraitorientation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/portraitPhoto": {
      "abstract": [
        {
          "text": "A portrait photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portraitPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/portraitPhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionPortraitPhoto"
        }
      ],
      "role": "symbol",
      "title": "portraitPhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/portraitphoto"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/processFilter": {
      "abstract": [
        {
          "text": "A process filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "processFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/processFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionProcessFilter"
        }
      ],
      "role": "symbol",
      "title": "processFilter",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/processfilter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/screenshot": {
      "abstract": [
        {
          "text": "A screenshot.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenshot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/screenshot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionScreenshot"
        }
      ],
      "role": "symbol",
      "title": "screenshot",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/screenshot"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/selfie": {
      "abstract": [
        {
          "text": "A selfie.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selfie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/selfie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionSelfie"
        }
      ],
      "role": "symbol",
      "title": "selfie",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/selfie"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/slowMotionVideo": {
      "abstract": [
        {
          "text": "A slow-motion video.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slowMotionVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/slowMotionVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionSlowMotionVideo"
        }
      ],
      "role": "symbol",
      "title": "slowMotionVideo",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/slowmotionvideo"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/squarePhoto": {
      "abstract": [
        {
          "text": "A square photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "squarePhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/squarePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionSquarePhoto"
        }
      ],
      "role": "symbol",
      "title": "squarePhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/squarephoto"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/timeLapseVideo": {
      "abstract": [
        {
          "text": "A time-lapse video.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeLapseVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/timeLapseVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionTimeLapseVideo"
        }
      ],
      "role": "symbol",
      "title": "timeLapseVideo",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/timelapsevideo"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/tonalFilter": {
      "abstract": [
        {
          "text": "A tonal filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tonalFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/tonalFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionTonalFilter"
        }
      ],
      "role": "symbol",
      "title": "tonalFilter",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/tonalfilter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/transferFilter": {
      "abstract": [
        {
          "text": "A transfer filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transferFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/transferFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionTransferFilter"
        }
      ],
      "role": "symbol",
      "title": "transferFilter",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/transferfilter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/video": {
      "abstract": [
        {
          "text": "A video.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "video"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionVideo"
        }
      ],
      "role": "symbol",
      "title": "video",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/video"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Photo",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/photo",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/bouncePhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/burstPhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/hdrPhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/livePhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/longExposurePhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/loopPhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/squarePhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/panoramaPhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/portraitPhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/GIF",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/flash",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/selfie"
      ],
      "title": "Photo"
    },
    {
      "anchor": "Video",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/video",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/timeLapseVideo",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/slowMotionVideo"
      ],
      "title": "Video"
    },
    {
      "anchor": "Filter",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/noirFilter",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/chromeFilter",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/instantFilter",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/tonalFilter",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/transferFilter",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/monoFilter",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/fadeFilter",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/processFilter"
      ],
      "title": "Filter"
    },
    {
      "anchor": "Orientation",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/landscapeOrientation",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/portraitOrientation"
      ],
      "title": "Orientation"
    },
    {
      "anchor": "Other",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/favorite",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/frontFacingCamera",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/screenshot"
      ],
      "title": "Other"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INPhotoAttributeOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Photo",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/photo",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/bouncePhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/burstPhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/hdrPhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/livePhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/longExposurePhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/loopPhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/squarePhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/panoramaPhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/portraitPhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/GIF",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/flash",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/selfie"
              ],
              "title": "Photo"
            },
            {
              "anchor": "Video",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/video",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/timeLapseVideo",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/slowMotionVideo"
              ],
              "title": "Video"
            },
            {
              "anchor": "Filter",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/noirFilter",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/chromeFilter",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/instantFilter",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/tonalFilter",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/transferFilter",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/monoFilter",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/fadeFilter",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/processFilter"
              ],
              "title": "Filter"
            },
            {
              "anchor": "Orientation",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/landscapeOrientation",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/portraitOrientation"
              ],
              "title": "Orientation"
            },
            {
              "anchor": "Other",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/favorite",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/frontFacingCamera",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/screenshot"
              ],
              "title": "Other"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INPhotoAttributeOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1longExposurePhoto/title",
          "value": "INPhotoAttributeOptionLongExposurePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1longExposurePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionLongExposurePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1burstPhoto/title",
          "value": "INPhotoAttributeOptionBurstPhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1burstPhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionBurstPhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1slowMotionVideo/title",
          "value": "INPhotoAttributeOptionSlowMotionVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1slowMotionVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionSlowMotionVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1portraitPhoto/title",
          "value": "INPhotoAttributeOptionPortraitPhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1portraitPhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionPortraitPhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions/title",
          "value": "INPhotoAttributeOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1timeLapseVideo/title",
          "value": "INPhotoAttributeOptionTimeLapseVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1timeLapseVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionTimeLapseVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1landscapeOrientation/title",
          "value": "INPhotoAttributeOptionLandscapeOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1landscapeOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionLandscapeOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1portraitOrientation/title",
          "value": "INPhotoAttributeOptionPortraitOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1portraitOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionPortraitOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1panoramaPhoto/title",
          "value": "INPhotoAttributeOptionPanoramaPhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1panoramaPhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionPanoramaPhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1loopPhoto/title",
          "value": "INPhotoAttributeOptionLoopPhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1loopPhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionLoopPhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1selfie/title",
          "value": "INPhotoAttributeOptionSelfie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1selfie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionSelfie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1livePhoto/title",
          "value": "INPhotoAttributeOptionLivePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1livePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionLivePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1chromeFilter/title",
          "value": "INPhotoAttributeOptionChromeFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1chromeFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionChromeFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1screenshot/title",
          "value": "INPhotoAttributeOptionScreenshot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1screenshot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionScreenshot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1monoFilter/title",
          "value": "INPhotoAttributeOptionMonoFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1monoFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionMonoFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1bouncePhoto/title",
          "value": "INPhotoAttributeOptionBouncePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1bouncePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionBouncePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1frontFacingCamera/title",
          "value": "INPhotoAttributeOptionFrontFacingCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1frontFacingCamera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionFrontFacingCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1noirFilter/title",
          "value": "INPhotoAttributeOptionNoirFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1noirFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionNoirFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1GIF/title",
          "value": "INPhotoAttributeOptionGIF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1GIF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionGIF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1photo/title",
          "value": "INPhotoAttributeOptionPhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1photo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionPhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1favorite/title",
          "value": "INPhotoAttributeOptionFavorite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1favorite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionFavorite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1video/title",
          "value": "INPhotoAttributeOptionVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1instantFilter/title",
          "value": "INPhotoAttributeOptionInstantFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1instantFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionInstantFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1hdrPhoto/title",
          "value": "INPhotoAttributeOptionHDRPhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1hdrPhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionHDRPhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1tonalFilter/title",
          "value": "INPhotoAttributeOptionTonalFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1tonalFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionTonalFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1fadeFilter/title",
          "value": "INPhotoAttributeOptionFadeFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1fadeFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionFadeFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1transferFilter/title",
          "value": "INPhotoAttributeOptionTransferFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1transferFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionTransferFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1squarePhoto/title",
          "value": "INPhotoAttributeOptionSquarePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1squarePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionSquarePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1processFilter/title",
          "value": "INPhotoAttributeOptionProcessFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1processFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionProcessFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1flash/title",
          "value": "INPhotoAttributeOptionFlash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1flash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionFlash"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inphotoattributeoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inphotoattributeoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
