{
  "abstract": [
    {
      "text": "The possible repeat modes at the time the user plays the media item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INPlaybackRepeatMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INPlaybackRepeatMode"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INPlaybackRepeatMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INPlaybackRepeatMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INPlaybackRepeatMode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/mediaSearch": {
      "abstract": [
        {
          "text": "An object that contains the search parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaSearch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INMediaSearch",
          "text": "INMediaSearch"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/mediaSearch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaSearch"
        }
      ],
      "role": "symbol",
      "title": "mediaSearch",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/mediasearch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playShuffled-2btex": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the media plays in a shuffled order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playShuffled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playShuffled-2btex",
      "kind": "symbol",
      "role": "symbol",
      "title": "playShuffled",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/playshuffled-2btex"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playShuffled-93hn1": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the media plays in a shuffled order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "playShuffled"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playShuffled-93hn1",
      "kind": "symbol",
      "role": "symbol",
      "title": "playShuffled",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/playshuffled-93hn1"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackQueueLocation": {
      "abstract": [
        {
          "text": "The queue location for a media item during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackQueueLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPlaybackQueueLocation",
          "text": "INPlaybackQueueLocation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackQueueLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playbackQueueLocation"
        }
      ],
      "role": "symbol",
      "title": "playbackQueueLocation",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/playbackqueuelocation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackRepeatMode": {
      "abstract": [
        {
          "text": "The repeat mode setting at the time the user plays the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackRepeatMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPlaybackRepeatMode",
          "text": "INPlaybackRepeatMode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackRepeatMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playbackRepeatMode"
        }
      ],
      "role": "symbol",
      "title": "playbackRepeatMode",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/playbackrepeatmode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackSpeed-17r2t": {
      "abstract": [
        {
          "text": "The playback speed for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackSpeed-17r2t",
      "kind": "symbol",
      "role": "symbol",
      "title": "playbackSpeed",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/playbackspeed-17r2t"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackSpeed-6ngbq": {
      "abstract": [
        {
          "text": "The playback speed for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "playbackSpeed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackSpeed-6ngbq",
      "kind": "symbol",
      "role": "symbol",
      "title": "playbackSpeed",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/playbackspeed-6ngbq"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/resumePlayback-1xw6r": {
      "abstract": [
        {
          "text": "The resume playback setting at the time the user plays the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resumePlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/resumePlayback-1xw6r",
      "kind": "symbol",
      "role": "symbol",
      "title": "resumePlayback",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/resumeplayback-1xw6r"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/resumePlayback-9zfyp": {
      "abstract": [
        {
          "text": "The resume playback setting at the time the user plays the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "resumePlayback"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/resumePlayback-9zfyp",
      "kind": "symbol",
      "role": "symbol",
      "title": "resumePlayback",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintent/resumeplayback-9zfyp"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation": {
      "abstract": [
        {
          "text": "Constants that describe the playback queue location for a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlaybackQueueLocation"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlaybackQueueLocation"
        }
      ],
      "role": "symbol",
      "title": "INPlaybackQueueLocation",
      "type": "topic",
      "url": "/documentation/intents/inplaybackqueuelocation"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode": {
      "abstract": [
        {
          "text": "The possible repeat modes at the time the user plays the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlaybackRepeatMode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlaybackRepeatMode"
        }
      ],
      "role": "symbol",
      "title": "INPlaybackRepeatMode",
      "type": "topic",
      "url": "/documentation/intents/inplaybackrepeatmode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/all": {
      "abstract": [
        {
          "text": "A mode that repeats all media items within a media container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlaybackRepeatModeAll"
        }
      ],
      "role": "symbol",
      "title": "INPlaybackRepeatMode.all",
      "type": "topic",
      "url": "/documentation/intents/inplaybackrepeatmode/all"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/inplaybackrepeatmode/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/none": {
      "abstract": [
        {
          "text": "A mode that doesn’t repeat media items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlaybackRepeatModeNone"
        }
      ],
      "role": "symbol",
      "title": "INPlaybackRepeatMode.none",
      "type": "topic",
      "url": "/documentation/intents/inplaybackrepeatmode/none"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/one": {
      "abstract": [
        {
          "text": "A mode that repeats the current media item within a media container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "one"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/one",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlaybackRepeatModeOne"
        }
      ],
      "role": "symbol",
      "title": "INPlaybackRepeatMode.one",
      "type": "topic",
      "url": "/documentation/intents/inplaybackrepeatmode/one"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/unknown": {
      "abstract": [
        {
          "text": "Unknown repeat mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlaybackRepeatModeUnknown"
        }
      ],
      "role": "symbol",
      "title": "INPlaybackRepeatMode.unknown",
      "type": "topic",
      "url": "/documentation/intents/inplaybackrepeatmode/unknown"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Playback-Settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playShuffled-2btex",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/resumePlayback-1xw6r",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackRepeatMode",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackSpeed-17r2t",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackQueueLocation",
        "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/mediaSearch"
      ],
      "title": "Accessing Playback Settings"
    }
  ],
  "topicSections": [
    {
      "anchor": "Repeat-Modes",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/unknown",
        "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/none",
        "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/all",
        "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/one"
      ],
      "title": "Repeat Modes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INPlaybackRepeatMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackRepeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackRepeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Repeat-Modes",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/unknown",
                "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/none",
                "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/all",
                "doc://com.apple.sirikit/documentation/Intents/INPlaybackRepeatMode/one"
              ],
              "title": "Repeat Modes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Playback-Settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playShuffled-93hn1",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/resumePlayback-9zfyp",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackRepeatMode",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackSpeed-6ngbq",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/playbackQueueLocation",
                "doc://com.apple.sirikit/documentation/Intents/INPlaybackQueueLocation",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntent/mediaSearch"
              ],
              "title": "Accessing Playback Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INPlaybackRepeatMode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatMode~1unknown/title",
          "value": "INPlaybackRepeatModeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatMode~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackRepeatModeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatMode~1all/title",
          "value": "INPlaybackRepeatModeAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatMode~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackRepeatModeAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent~1playbackQueueLocation/title",
          "value": "playbackQueueLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent~1playbackQueueLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playbackQueueLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatMode~1one/title",
          "value": "INPlaybackRepeatModeOne"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatMode~1one/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackRepeatModeOne"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation/title",
          "value": "INPlaybackQueueLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackQueueLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackQueueLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackQueueLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatMode~1none/title",
          "value": "INPlaybackRepeatModeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatMode~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackRepeatModeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent~1mediaSearch/title",
          "value": "mediaSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent~1mediaSearch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatMode/title",
          "value": "INPlaybackRepeatMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackRepeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlaybackRepeatMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlaybackRepeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent~1playbackRepeatMode/title",
          "value": "playbackRepeatMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntent~1playbackRepeatMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playbackRepeatMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inplaybackrepeatmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inplaybackrepeatmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
