{
  "abstract": [
    {
      "text": "Codes returned by an app or Intents app extension when handling or confirming a play media intent.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INPlayMediaIntentResponseCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INPlayMediaIntentResponseCode"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INPlayMediaIntentResponseCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INPlayMediaIntentResponseCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponse/code": {
      "abstract": [
        {
          "text": "A response code that indicates whether the app can play the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPlayMediaIntentResponseCode",
          "text": "INPlayMediaIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponse/code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "code"
        }
      ],
      "role": "symbol",
      "title": "code",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponse/code"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode": {
      "abstract": [
        {
          "text": "Codes returned by an app or Intents app extension when handling or confirming a play media intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/continueInApp": {
      "abstract": [
        {
          "text": "The system should launch the app in the foreground to play the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continueInApp"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/continueInApp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCodeContinueInApp"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode.continueInApp",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/continueinapp"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "A failure occurred while confirming or handling the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureMaxStreamLimitReached": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureMaxStreamLimitReached"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureMaxStreamLimitReached",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCodeFailureMaxStreamLimitReached"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode.failureMaxStreamLimitReached",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/failuremaxstreamlimitreached"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureNoUnplayedContent": {
      "abstract": [
        {
          "text": "The media container has no unplayed content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureNoUnplayedContent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureNoUnplayedContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCodeFailureNoUnplayedContent"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode.failureNoUnplayedContent",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/failurenounplayedcontent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "The user must launch the app before media playback can begin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureRestrictedContent": {
      "abstract": [
        {
          "text": "The app cannot play the media because of content restrictions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRestrictedContent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureRestrictedContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCodeFailureRestrictedContent"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode.failureRestrictedContent",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/failurerestrictedcontent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureUnknownMediaType": {
      "abstract": [
        {
          "text": "The app cannot play the media because the type is unknown or not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureUnknownMediaType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureUnknownMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCodeFailureUnknownMediaType"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode.failureUnknownMediaType",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/failureunknownmediatype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/handleInApp": {
      "abstract": [
        {
          "text": "The system should launch the app in the background to play the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handleInApp"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/handleInApp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCodeHandleInApp"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode.handleInApp",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/handleinapp"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/inProgress": {
      "abstract": [
        {
          "text": "The app is preparing to play the media content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProgress"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/inProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCodeInProgress"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode.inProgress",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/inprogress"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "The intents handler is ready to handle the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/success": {
      "abstract": [
        {
          "text": "The app is playing the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode.success",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/success"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "An unspecified response code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPlayMediaIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INPlayMediaIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/inplaymediaintentresponsecode/unspecified"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-the-Response-Code",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponse/code"
      ],
      "title": "Providing the Response Code"
    }
  ],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "Response codes returned by an Intents app extension when confirming or handling a play media intent.",
          "type": "text"
        }
      ],
      "anchor": "Intents-App-Extensions",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/continueInApp",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/handleInApp"
      ],
      "title": "Intents App Extensions"
    },
    {
      "abstract": [
        {
          "text": "Response codes returned by an app when handling a play media intent.",
          "type": "text"
        }
      ],
      "anchor": "App",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/inProgress",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/success"
      ],
      "title": "App"
    },
    {
      "abstract": [
        {
          "text": "Response codes returned by either an app or an Intents app extension.",
          "type": "text"
        }
      ],
      "anchor": "General",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/unspecified"
      ],
      "title": "General"
    },
    {
      "abstract": [
        {
          "text": "Failure response codes returned by an app or an Intents app extension.",
          "type": "text"
        }
      ],
      "anchor": "Failures",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureNoUnplayedContent",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureRequiringAppLaunch",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureRestrictedContent",
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureUnknownMediaType"
      ],
      "title": "Failures"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureMaxStreamLimitReached"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INPlayMediaIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "Response codes returned by an Intents app extension when confirming or handling a play media intent.",
                  "type": "text"
                }
              ],
              "anchor": "Intents-App-Extensions",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/continueInApp",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/handleInApp"
              ],
              "title": "Intents App Extensions"
            },
            {
              "abstract": [
                {
                  "text": "Response codes returned by an app when handling a play media intent.",
                  "type": "text"
                }
              ],
              "anchor": "App",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/inProgress",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/success"
              ],
              "title": "App"
            },
            {
              "abstract": [
                {
                  "text": "Response codes returned by either an app or an Intents app extension.",
                  "type": "text"
                }
              ],
              "anchor": "General",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/unspecified"
              ],
              "title": "General"
            },
            {
              "abstract": [
                {
                  "text": "Failure response codes returned by an app or an Intents app extension.",
                  "type": "text"
                }
              ],
              "anchor": "Failures",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureNoUnplayedContent",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureRequiringAppLaunch",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureRestrictedContent",
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureUnknownMediaType"
              ],
              "title": "Failures"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponseCode/failureMaxStreamLimitReached"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-the-Response-Code",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPlayMediaIntentResponse/code"
              ],
              "title": "Providing the Response Code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INPlayMediaIntentResponseCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failure/title",
          "value": "INPlayMediaIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1continueInApp/title",
          "value": "INPlayMediaIntentResponseCodeContinueInApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1continueInApp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeContinueInApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureMaxStreamLimitReached/title",
          "value": "INPlayMediaIntentResponseCodeFailureMaxStreamLimitReached"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureMaxStreamLimitReached/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeFailureMaxStreamLimitReached"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1ready/title",
          "value": "INPlayMediaIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponse~1code/title",
          "value": "code"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponse~1code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureRestrictedContent/title",
          "value": "INPlayMediaIntentResponseCodeFailureRestrictedContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureRestrictedContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeFailureRestrictedContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INPlayMediaIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureNoUnplayedContent/title",
          "value": "INPlayMediaIntentResponseCodeFailureNoUnplayedContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureNoUnplayedContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeFailureNoUnplayedContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1success/title",
          "value": "INPlayMediaIntentResponseCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1handleInApp/title",
          "value": "INPlayMediaIntentResponseCodeHandleInApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1handleInApp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeHandleInApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1inProgress/title",
          "value": "INPlayMediaIntentResponseCodeInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1inProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureUnknownMediaType/title",
          "value": "INPlayMediaIntentResponseCodeFailureUnknownMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1failureUnknownMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeFailureUnknownMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode/title",
          "value": "INPlayMediaIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1unspecified/title",
          "value": "INPlayMediaIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPlayMediaIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPlayMediaIntentResponseCodeUnspecified"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inplaymediaintentresponsecode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inplaymediaintentresponsecode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
