{
  "abstract": [
    {
      "text": "A reservation created by a user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INRestaurantReservationUserBooking",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INRestaurantReservationUserBooking"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INRestaurantReservationUserBooking"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "INRestaurantReservationUserBooking"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INRestaurantReservationUserBooking"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object contains information about a reservation placed by a user. When the user actually books a reservation at a restaurant, you create an instance of this class to represent the reservation details. This object contains the specific details of the reservation, including any user-specified information such as selected offers or special requests.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You create instances of this class when providing responses to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects. After initializing an instance of this class with basic information, fill in any additional properties with details relevant to the reservation before returning it with your response.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information about additional properties of this class that you can configure for a booking, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationBooking",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntent": {
      "abstract": [
        {
          "text": "A request to create a reservation at the specified restaurant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INBookRestaurantReservationIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBookRestaurantReservationIntent"
        }
      ],
      "role": "symbol",
      "title": "INBookRestaurantReservationIntent",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntent": {
      "abstract": [
        {
          "text": "A request for the list of the user’s current reservations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetUserCurrentRestaurantReservationBookingsIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetUserCurrentRestaurantReservationBookingsIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetUserCurrentRestaurantReservationBookingsIntent"
        }
      ],
      "role": "symbol",
      "title": "INGetUserCurrentRestaurantReservationBookingsIntent",
      "type": "topic",
      "url": "/documentation/intents/ingetusercurrentrestaurantreservationbookingsintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRestaurant": {
      "abstract": [
        {
          "text": "A restaurant for which your app can make and manage reservations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRestaurant"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRestaurant"
        }
      ],
      "role": "symbol",
      "title": "INRestaurant",
      "type": "topic",
      "url": "/documentation/intents/inrestaurant"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRestaurantGuest": {
      "abstract": [
        {
          "text": "The person assigned to a reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRestaurantGuest"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantGuest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRestaurantGuest"
        }
      ],
      "role": "symbol",
      "title": "INRestaurantGuest",
      "type": "topic",
      "url": "/documentation/intents/inrestaurantguest"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRestaurantGuestDisplayPreferences": {
      "abstract": [
        {
          "text": "Options about how to display guest information from system interfaces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRestaurantGuestDisplayPreferences"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantGuestDisplayPreferences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRestaurantGuestDisplayPreferences"
        }
      ],
      "role": "symbol",
      "title": "INRestaurantGuestDisplayPreferences",
      "type": "topic",
      "url": "/documentation/intents/inrestaurantguestdisplaypreferences"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRestaurantOffer": {
      "abstract": [
        {
          "text": "Information about special offers made by a restaurant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRestaurantOffer"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantOffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRestaurantOffer"
        }
      ],
      "role": "symbol",
      "title": "INRestaurantOffer",
      "type": "topic",
      "url": "/documentation/intents/inrestaurantoffer"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationBooking": {
      "abstract": [
        {
          "text": "A potential reservation that a user can book.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRestaurantReservationBooking"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationBooking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRestaurantReservationBooking"
        }
      ],
      "role": "symbol",
      "title": "INRestaurantReservationBooking",
      "type": "topic",
      "url": "/documentation/intents/inrestaurantreservationbooking"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking": {
      "abstract": [
        {
          "text": "A reservation created by a user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRestaurantReservationUserBooking"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRestaurantReservationUserBooking"
        }
      ],
      "role": "symbol",
      "title": "INRestaurantReservationUserBooking",
      "type": "topic",
      "url": "/documentation/intents/inrestaurantreservationuserbooking"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/advisementText": {
      "abstract": [
        {
          "text": "A user-readable string containing policies and information related to the reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "advisementText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/advisementText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "advisementText"
        }
      ],
      "role": "symbol",
      "title": "advisementText",
      "type": "topic",
      "url": "/documentation/intents/inrestaurantreservationuserbooking/advisementtext"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/dateStatusModified": {
      "abstract": [
        {
          "text": "The date on which the status of the reservation changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dateStatusModified"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/dateStatusModified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dateStatusModified"
        }
      ],
      "role": "symbol",
      "title": "dateStatusModified",
      "type": "topic",
      "url": "/documentation/intents/inrestaurantreservationuserbooking/datestatusmodified"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/guest": {
      "abstract": [
        {
          "text": "The guest associated with the reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "guest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INRestaurantGuest",
          "text": "INRestaurantGuest"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/guest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "guest"
        }
      ],
      "role": "symbol",
      "title": "guest",
      "type": "topic",
      "url": "/documentation/intents/inrestaurantreservationuserbooking/guest"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/guestProvidedSpecialRequestText": {
      "abstract": [
        {
          "text": "Any special requests made by the user with the reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "guestProvidedSpecialRequestText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/guestProvidedSpecialRequestText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "guestProvidedSpecialRequestText"
        }
      ],
      "role": "symbol",
      "title": "guestProvidedSpecialRequestText",
      "type": "topic",
      "url": "/documentation/intents/inrestaurantreservationuserbooking/guestprovidedspecialrequesttext"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/init(restaurant:booking:partySize:bookingIdentifier:guest:status:dateStatusModified:)": {
      "abstract": [
        {
          "text": "Initializes the reservation object with the specified information and status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "restaurant"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INRestaurant",
          "text": "INRestaurant"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "booking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "partySize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "bookingIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "guest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INRestaurantGuest",
          "text": "INRestaurantGuest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INRestaurantReservationUserBookingStatus",
          "text": "INRestaurantReservationUserBookingStatus"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dateStatusModified"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/init(restaurant:booking:partySize:bookingIdentifier:guest:status:dateStatusModified:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithRestaurant:bookingDate:partySize:bookingIdentifier:guest:status:dateStatusModified:"
        }
      ],
      "role": "symbol",
      "title": "init(restaurant:booking:partySize:bookingIdentifier:guest:status:dateStatusModified:)",
      "type": "topic",
      "url": "/documentation/intents/inrestaurantreservationuserbooking/init(restaurant:booking:partysize:bookingidentifier:guest:status:datestatusmodified:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/selectedOffer": {
      "abstract": [
        {
          "text": "The offer selected by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedOffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INRestaurantOffer",
          "text": "INRestaurantOffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/selectedOffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedOffer"
        }
      ],
      "role": "symbol",
      "title": "selectedOffer",
      "type": "topic",
      "url": "/documentation/intents/inrestaurantreservationuserbooking/selectedoffer"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/status": {
      "abstract": [
        {
          "text": "The current status of the reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INRestaurantReservationUserBookingStatus",
          "text": "INRestaurantReservationUserBookingStatus"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/status",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "status"
        }
      ],
      "role": "symbol",
      "title": "status",
      "type": "topic",
      "url": "/documentation/intents/inrestaurantreservationuserbooking/status"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBookingStatus": {
      "abstract": [
        {
          "text": "Constants indicating the status of a user reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRestaurantReservationUserBookingStatus"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBookingStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRestaurantReservationUserBookingStatus"
        }
      ],
      "role": "symbol",
      "title": "INRestaurantReservationUserBookingStatus",
      "type": "topic",
      "url": "/documentation/intents/inrestaurantreservationuserbookingstatus"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTermsAndConditions": {
      "abstract": [
        {
          "text": "The terms and conditions of service when making restaurant reservations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INTermsAndConditions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTermsAndConditions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INTermsAndConditions"
        }
      ],
      "role": "symbol",
      "title": "INTermsAndConditions",
      "type": "topic",
      "url": "/documentation/intents/intermsandconditions"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationBooking"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INRestaurant",
        "doc://com.apple.sirikit/documentation/Intents/INRestaurantGuest",
        "doc://com.apple.sirikit/documentation/Intents/INRestaurantGuestDisplayPreferences",
        "doc://com.apple.sirikit/documentation/Intents/INRestaurantOffer",
        "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationBooking",
        "doc://com.apple.sirikit/documentation/Intents/INTermsAndConditions",
        "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBookingStatus"
      ],
      "title": "Data Objects"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-a-Reservation",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/init(restaurant:booking:partySize:bookingIdentifier:guest:status:dateStatusModified:)"
      ],
      "title": "Initializing a Reservation"
    },
    {
      "anchor": "Accessing-the-Reservation-Information",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/guest",
        "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/status",
        "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/dateStatusModified",
        "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/guestProvidedSpecialRequestText"
      ],
      "title": "Accessing the Reservation Information"
    },
    {
      "anchor": "Accessing-Special-Offers",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/selectedOffer",
        "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/advisementText"
      ],
      "title": "Accessing Special Offers"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBookingStatus"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INRestaurantReservationUserBooking"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurantReservationUserBooking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurantReservationUserBooking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializing-a-Reservation",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/init(restaurant:booking:partySize:bookingIdentifier:guest:status:dateStatusModified:)"
              ],
              "title": "Initializing a Reservation"
            },
            {
              "anchor": "Accessing-the-Reservation-Information",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/guest",
                "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/status",
                "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/dateStatusModified",
                "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/guestProvidedSpecialRequestText"
              ],
              "title": "Accessing the Reservation Information"
            },
            {
              "anchor": "Accessing-Special-Offers",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/selectedOffer",
                "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBooking/advisementText"
              ],
              "title": "Accessing Special Offers"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBookingStatus"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationBooking"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Objects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INRestaurant",
                "doc://com.apple.sirikit/documentation/Intents/INRestaurantGuest",
                "doc://com.apple.sirikit/documentation/Intents/INRestaurantGuestDisplayPreferences",
                "doc://com.apple.sirikit/documentation/Intents/INRestaurantOffer",
                "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationBooking",
                "doc://com.apple.sirikit/documentation/Intents/INTermsAndConditions",
                "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationUserBookingStatus"
              ],
              "title": "Data Objects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INRestaurantReservationUserBooking"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantReservationBooking",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INRestaurantReservationBooking",
                    "text": "INRestaurantReservationBooking"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBooking~1dateStatusModified/title",
          "value": "dateStatusModified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBooking~1dateStatusModified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dateStatusModified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBooking~1status/title",
          "value": "status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBooking~1status/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBookingStatus/title",
          "value": "INRestaurantReservationUserBookingStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBookingStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurantReservationUserBookingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBookingStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurantReservationUserBookingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurant/title",
          "value": "INRestaurant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurant/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBooking~1selectedOffer/title",
          "value": "selectedOffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBooking~1selectedOffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedOffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntent/title",
          "value": "INBookRestaurantReservationIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBooking~1guest/title",
          "value": "guest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBooking~1guest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "guest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBooking~1guestProvidedSpecialRequestText/title",
          "value": "guestProvidedSpecialRequestText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBooking~1guestProvidedSpecialRequestText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "guestProvidedSpecialRequestText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantGuest/title",
          "value": "INRestaurantGuest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantGuest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurantGuest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantGuest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurantGuest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBooking/title",
          "value": "INRestaurantReservationUserBooking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBooking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurantReservationUserBooking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBooking/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurantReservationUserBooking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBooking~1advisementText/title",
          "value": "advisementText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBooking~1advisementText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "advisementText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTermsAndConditions/title",
          "value": "INTermsAndConditions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTermsAndConditions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTermsAndConditions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTermsAndConditions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTermsAndConditions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBooking~1init(restaurant:booking:partySize:bookingIdentifier:guest:status:dateStatusModified:)/title",
          "value": "initWithRestaurant:bookingDate:partySize:bookingIdentifier:guest:status:dateStatusModified:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationUserBooking~1init(restaurant:booking:partySize:bookingIdentifier:guest:status:dateStatusModified:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithRestaurant:bookingDate:partySize:bookingIdentifier:guest:status:dateStatusModified:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantOffer/title",
          "value": "INRestaurantOffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantOffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurantOffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantOffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurantOffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantGuestDisplayPreferences/title",
          "value": "INRestaurantGuestDisplayPreferences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantGuestDisplayPreferences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurantGuestDisplayPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantGuestDisplayPreferences/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurantGuestDisplayPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationBooking/title",
          "value": "INRestaurantReservationBooking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationBooking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurantReservationBooking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantReservationBooking/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurantReservationBooking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntent/title",
          "value": "INGetUserCurrentRestaurantReservationBookingsIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetUserCurrentRestaurantReservationBookingsIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetUserCurrentRestaurantReservationBookingsIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetUserCurrentRestaurantReservationBookingsIntent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inrestaurantreservationuserbooking"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inrestaurantreservationuserbooking"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
