{
  "abstract": [
    {
      "text": "An interface for adopting all of the protocols in the ride-booking domain.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Please conform to INListRideOptionsIntentHandling, INRequestRideIntentHandling, INGetRideStatusIntentHandling, INCancelRideIntentHandling and INSendRideFeedbackIntentHandling instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INRidesharingDomainHandling"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INRidesharingDomainHandling",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INRidesharingDomainHandling"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INRidesharingDomainHandling"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "11.0",
        "message": "Please conform to INListRideOptionsIntentHandling, INRequestRideIntentHandling, INGetRideStatusIntentHandling, INCancelRideIntentHandling and INSendRideFeedbackIntentHandling instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "11.0",
        "message": "Please conform to INListRideOptionsIntentHandling, INRequestRideIntentHandling, INGetRideStatusIntentHandling, INCancelRideIntentHandling and INSendRideFeedbackIntentHandling instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Please conform to INListRideOptionsIntentHandling, INRequestRideIntentHandling, INGetRideStatusIntentHandling, INCancelRideIntentHandling and INSendRideFeedbackIntentHandling instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Please conform to INListRideOptionsIntentHandling, INRequestRideIntentHandling, INGetRideStatusIntentHandling, INCancelRideIntentHandling and INSendRideFeedbackIntentHandling instead",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "6.0",
        "introducedAt": "3.2",
        "message": "Please conform to INListRideOptionsIntentHandling, INRequestRideIntentHandling and INGetRideStatusIntentHandling instead",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "INRidesharingDomainHandling"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INRidesharingDomainHandling"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INCancelRideIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INCancelRideIntentHandling",
              "text": "INCancelRideIntentHandling"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INGetRideStatusIntentHandling",
              "text": "INGetRideStatusIntentHandling"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INListRideOptionsIntentHandling",
              "text": "INListRideOptionsIntentHandling"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INRequestRideIntentHandling",
              "text": "INRequestRideIntentHandling"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INSendRideFeedbackIntentHandling",
              "text": "INSendRideFeedbackIntentHandling"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INRidesharingDomainHandling"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INGetRideStatusIntentHandling",
              "text": "INGetRideStatusIntentHandling"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INListRideOptionsIntentHandling",
              "text": "INListRideOptionsIntentHandling"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentHandling",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)INRequestRideIntentHandling",
              "text": "INRequestRideIntentHandling"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRidesharingDomainHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol is a convenience protocol that adopts all of the protocols used to handle ride sharing-related intents. When your app adopts all of the protocols associated with ride sharing, you can adopt this one protocol instead of adopting the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INCancelRideIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocols separately.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "An object that adopts this protocol must be able to respond to the following intents:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", a request to view the available vehicles and prices.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", a request to book a ride.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", a request to get the status of a previously booked ride.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCancelRideIntent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", a request to cancel the currently active ride.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntent",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", a request to record feedback for the just-completed ride.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Your handler object must be prepared to resolve any parameters associated with these intents and to confirm and handle the requests. When confirming and handling a request, you provide the response object that matches the specified intent.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallsDomainHandling": {
      "abstract": [
        {
          "text": "Provides a convenient way to adopt all of the protocols in the VoIP calling domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCallsDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallsDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallsDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INCallsDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/incallsdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCancelRideIntent": {
      "abstract": [
        {
          "text": "An intent requesting the cancellation of a previously booked ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCancelRideIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCancelRideIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCancelRideIntent"
        }
      ],
      "role": "symbol",
      "title": "INCancelRideIntent",
      "type": "topic",
      "url": "/documentation/intents/incancelrideintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCancelRideIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for canceling a previously booked ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCancelRideIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCancelRideIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCancelRideIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INCancelRideIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/incancelrideintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarCommandsDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all the handling protocols in the car commands domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarCommandsDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarCommandsDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarCommandsDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INCarCommandsDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/incarcommandsdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the CarPlay domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarPlayDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarPlayDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INCarPlayDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/incarplaydomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntent": {
      "abstract": [
        {
          "text": "A request for the current status of a previously booked ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntent"
        }
      ],
      "role": "symbol",
      "title": "INGetRideStatusIntent",
      "type": "topic",
      "url": "/documentation/intents/ingetridestatusintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for fetching the status of the user’s current ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetRideStatusIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INGetRideStatusIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/ingetridestatusintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntent": {
      "abstract": [
        {
          "text": "An intent for getting the types of rides available from a ride-booking service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INListRideOptionsIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListRideOptionsIntent"
        }
      ],
      "role": "symbol",
      "title": "INListRideOptionsIntent",
      "type": "topic",
      "url": "/documentation/intents/inlistrideoptionsintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for fetching the list of rides currently available from your ride-booking service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INListRideOptionsIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INListRideOptionsIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INListRideOptionsIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/inlistrideoptionsintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INMessagesDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the messages domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INMessagesDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INMessagesDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INMessagesDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INMessagesDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inmessagesdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INNotebookDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the lists and notes domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INNotebookDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INNotebookDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INNotebookDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INNotebookDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/innotebookdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentsDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the payments domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPaymentsDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentsDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentsDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INPaymentsDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inpaymentsdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotosDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the photos domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPhotosDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotosDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotosDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INPhotosDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inphotosdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRadioDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the radio domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRadioDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRadioDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRadioDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INRadioDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inradiodomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntent": {
      "abstract": [
        {
          "text": "A request to book the specified ride from your service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRequestRideIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestRideIntent"
        }
      ],
      "role": "symbol",
      "title": "INRequestRideIntent",
      "type": "topic",
      "url": "/documentation/intents/inrequestrideintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for booking a ride for the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRequestRideIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestRideIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INRequestRideIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/inrequestrideintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRidesharingDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the ride-booking domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRidesharingDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRidesharingDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRidesharingDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INRidesharingDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inridesharingdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntent": {
      "abstract": [
        {
          "text": "An intent indicating that the user provided feedback for a completed ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSendRideFeedbackIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendRideFeedbackIntent"
        }
      ],
      "role": "symbol",
      "title": "INSendRideFeedbackIntent",
      "type": "topic",
      "url": "/documentation/intents/insendridefeedbackintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for sending ride feedback to your service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSendRideFeedbackIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendRideFeedbackIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSendRideFeedbackIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insendridefeedbackintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVisualCodeDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the visual codes domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVisualCodeDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVisualCodeDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVisualCodeDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INVisualCodeDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/invisualcodedomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INWorkoutsDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the workouts domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INWorkoutsDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INWorkoutsDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INWorkoutsDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INWorkoutsDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inworkoutsdomainhandling"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCancelRideIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Domain-Handling-Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INMessagesDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INNotebookDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INWorkoutsDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentsDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INCallsDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INVisualCodeDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INPhotosDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INCarCommandsDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling",
        "doc://com.apple.sirikit/documentation/Intents/INRadioDomainHandling"
      ],
      "title": "Domain-Handling Protocols"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "6.0",
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INRidesharingDomainHandling"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRidesharingDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRidesharingDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INCancelRideIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Domain-Handling-Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INMessagesDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INNotebookDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INWorkoutsDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentsDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INCallsDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INVisualCodeDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INPhotosDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INCarCommandsDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling",
                "doc://com.apple.sirikit/documentation/Intents/INRadioDomainHandling"
              ],
              "title": "Domain-Handling Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INRidesharingDomainHandling"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INListRideOptionsIntentHandling",
                    "text": "INListRideOptionsIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INRequestRideIntentHandling",
                    "text": "INRequestRideIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INGetRideStatusIntentHandling",
                    "text": "INGetRideStatusIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INRidesharingDomainHandling"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INListRideOptionsIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INListRideOptionsIntentHandling",
                    "text": "INListRideOptionsIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestRideIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INRequestRideIntentHandling",
                    "text": "INRequestRideIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetRideStatusIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INGetRideStatusIntentHandling",
                    "text": "INGetRideStatusIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INCancelRideIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INCancelRideIntentHandling",
                    "text": "INCancelRideIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)INSendRideFeedbackIntentHandling",
                    "text": "INSendRideFeedbackIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Please conform to INListRideOptionsIntentHandling, INRequestRideIntentHandling, INGetRideStatusIntentHandling, INCancelRideIntentHandling and INSendRideFeedbackIntentHandling instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallsDomainHandling/title",
          "value": "INCallsDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallsDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallsDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentHandling/title",
          "value": "INGetRideStatusIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessagesDomainHandling/title",
          "value": "INMessagesDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessagesDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessagesDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INMessagesDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INMessagesDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVisualCodeDomainHandling/title",
          "value": "INVisualCodeDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVisualCodeDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVisualCodeDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVisualCodeDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVisualCodeDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNotebookDomainHandling/title",
          "value": "INNotebookDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNotebookDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INNotebookDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNotebookDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INNotebookDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntent/title",
          "value": "INGetRideStatusIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetRideStatusIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetRideStatusIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutsDomainHandling/title",
          "value": "INWorkoutsDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutsDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INWorkoutsDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INWorkoutsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentsDomainHandling/title",
          "value": "INPaymentsDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentsDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentsDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntent/title",
          "value": "INSendRideFeedbackIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntent/title",
          "value": "INListRideOptionsIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarCommandsDomainHandling/title",
          "value": "INCarCommandsDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarCommandsDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarCommandsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarCommandsDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarCommandsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRadioDomainHandling/title",
          "value": "INRadioDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRadioDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRadioDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRadioDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRadioDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCancelRideIntent/title",
          "value": "INCancelRideIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCancelRideIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCancelRideIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCancelRideIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCancelRideIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentHandling/title",
          "value": "INRequestRideIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCancelRideIntentHandling/title",
          "value": "INCancelRideIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCancelRideIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCancelRideIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCancelRideIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCancelRideIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRidesharingDomainHandling/title",
          "value": "INRidesharingDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRidesharingDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRidesharingDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRidesharingDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRidesharingDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotosDomainHandling/title",
          "value": "INPhotosDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotosDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotosDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotosDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotosDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentHandling/title",
          "value": "INListRideOptionsIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INListRideOptionsIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INListRideOptionsIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarPlayDomainHandling/title",
          "value": "INCarPlayDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarPlayDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarPlayDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarPlayDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarPlayDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntent/title",
          "value": "INRequestRideIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestRideIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestRideIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentHandling/title",
          "value": "INSendRideFeedbackIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntentHandling"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inridesharingdomainhandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inridesharingdomainhandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
