{
  "abstract": [
    {
      "text": "Identifying information about a driver of a ride service.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INRideDriver"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INRideDriver",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INRideDriver"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INRideDriver"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "INRideDriver"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INRideDriver"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideDriver",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object encapsulates information about a driver associated with your ride service. This object stores basic information about the driver, including the driver’s name, picture, and phone number. You create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideDriver",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object and assign it to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideStatus/driver",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideStatus",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object when the user books a ride or when you update the status of an existing ride. SiriKit displays the driver information to the user at appropriate times.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This class is a subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INPerson",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and contains properties that are relevant only for ride-booking services. For additional driver properties, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INPerson",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPerson": {
      "abstract": [
        {
          "text": "Information about a person participating in a SiriKit interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPerson"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPerson",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPerson"
        }
      ],
      "role": "symbol",
      "title": "INPerson",
      "type": "topic",
      "url": "/documentation/intents/inperson"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRideCompletionStatus": {
      "abstract": [
        {
          "text": "Additional details about whether a ride completed successfully or someone canceled the ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRideCompletionStatus"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideCompletionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRideCompletionStatus"
        }
      ],
      "role": "symbol",
      "title": "INRideCompletionStatus",
      "type": "topic",
      "url": "/documentation/intents/inridecompletionstatus"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRideDriver": {
      "abstract": [
        {
          "text": "Identifying information about a driver of a ride service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRideDriver"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideDriver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRideDriver"
        }
      ],
      "role": "symbol",
      "title": "INRideDriver",
      "type": "topic",
      "url": "/documentation/intents/inridedriver"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRideDriver/init(handle:displayName:image:rating:phoneNumber:)": {
      "abstract": [
        {
          "text": "Initializes and returns a ride driver object using a display name and other driver information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "displayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INImage",
          "text": "INImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "rating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "phoneNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideDriver/init(handle:displayName:image:rating:phoneNumber:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithHandle:displayName:image:rating:phoneNumber:"
        }
      ],
      "role": "symbol",
      "title": "init(handle:displayName:image:rating:phoneNumber:)",
      "type": "topic",
      "url": "/documentation/intents/inridedriver/init(handle:displayname:image:rating:phonenumber:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRideDriver/init(handle:nameComponents:image:rating:phoneNumber:)": {
      "abstract": [
        {
          "text": "Initializes and returns a ride driver object using a set of name components and other driver information",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "nameComponents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation20PersonNameComponentsV",
          "text": "PersonNameComponents"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INImage",
          "text": "INImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "rating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "phoneNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideDriver/init(handle:nameComponents:image:rating:phoneNumber:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithHandle:nameComponents:image:rating:phoneNumber:"
        }
      ],
      "role": "symbol",
      "title": "init(handle:nameComponents:image:rating:phoneNumber:)",
      "type": "topic",
      "url": "/documentation/intents/inridedriver/init(handle:namecomponents:image:rating:phonenumber:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRideDriver/init(personHandle:nameComponents:displayName:image:rating:phoneNumber:)": {
      "abstract": [
        {
          "text": "Initializes and returns a ride driver object using a set of name components and other driver information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "personHandle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPersonHandle",
          "text": "INPersonHandle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "nameComponents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation20PersonNameComponentsV",
          "text": "PersonNameComponents"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "displayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INImage",
          "text": "INImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "rating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "phoneNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideDriver/init(personHandle:nameComponents:displayName:image:rating:phoneNumber:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPersonHandle:nameComponents:displayName:image:rating:phoneNumber:"
        }
      ],
      "role": "symbol",
      "title": "init(personHandle:nameComponents:displayName:image:rating:phoneNumber:)",
      "type": "topic",
      "url": "/documentation/intents/inridedriver/init(personhandle:namecomponents:displayname:image:rating:phonenumber:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRideDriver/init(phoneNumber:nameComponents:displayName:image:rating:)": {
      "abstract": [
        {
          "text": "Initializes and returns a ride driver object using a set of name components and other driver information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "phoneNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "nameComponents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation20PersonNameComponentsV",
          "text": "PersonNameComponents"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "displayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INImage",
          "text": "INImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "rating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideDriver/init(phoneNumber:nameComponents:displayName:image:rating:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPhoneNumber:nameComponents:displayName:image:rating:"
        }
      ],
      "role": "symbol",
      "title": "init(phoneNumber:nameComponents:displayName:image:rating:)",
      "type": "topic",
      "url": "/documentation/intents/inridedriver/init(phonenumber:namecomponents:displayname:image:rating:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRideDriver/phoneNumber": {
      "abstract": [
        {
          "text": "The driver’s phone number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phoneNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideDriver/phoneNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "phoneNumber"
        }
      ],
      "role": "symbol",
      "title": "phoneNumber",
      "type": "topic",
      "url": "/documentation/intents/inridedriver/phonenumber"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRideDriver/rating": {
      "abstract": [
        {
          "text": "The driver’s current rating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideDriver/rating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rating"
        }
      ],
      "role": "symbol",
      "title": "rating",
      "type": "topic",
      "url": "/documentation/intents/inridedriver/rating"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRideFareLineItem": {
      "abstract": [
        {
          "text": "A specific type of ride-related charge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRideFareLineItem"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideFareLineItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRideFareLineItem"
        }
      ],
      "role": "symbol",
      "title": "INRideFareLineItem",
      "type": "topic",
      "url": "/documentation/intents/inridefarelineitem"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRideOption": {
      "abstract": [
        {
          "text": "Details about a type of ride offered by your ride-booking service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRideOption"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRideOption"
        }
      ],
      "role": "symbol",
      "title": "INRideOption",
      "type": "topic",
      "url": "/documentation/intents/inrideoption"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRidePartySizeOption": {
      "abstract": [
        {
          "text": "The price of a ride involving the specified number of people.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRidePartySizeOption"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRidePartySizeOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRidePartySizeOption"
        }
      ],
      "role": "symbol",
      "title": "INRidePartySizeOption",
      "type": "topic",
      "url": "/documentation/intents/inridepartysizeoption"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRideStatus": {
      "abstract": [
        {
          "text": "The status of a ride booked through a ride-booking service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRideStatus"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRideStatus"
        }
      ],
      "role": "symbol",
      "title": "INRideStatus",
      "type": "topic",
      "url": "/documentation/intents/inridestatus"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRideStatus/driver": {
      "abstract": [
        {
          "text": "The driver providing the ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "driver"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INRideDriver",
          "text": "INRideDriver"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideStatus/driver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "driver"
        }
      ],
      "role": "symbol",
      "title": "driver",
      "type": "topic",
      "url": "/documentation/intents/inridestatus/driver"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRideVehicle": {
      "abstract": [
        {
          "text": "A specific vehicle used by a ride-booking service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRideVehicle"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideVehicle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRideVehicle"
        }
      ],
      "role": "symbol",
      "title": "INRideVehicle",
      "type": "topic",
      "url": "/documentation/intents/inridevehicle"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSpeakable": {
      "abstract": [
        {
          "text": "Pronunciation hints for strings used in a spoken interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSpeakable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSpeakable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSpeakable"
        }
      ],
      "role": "symbol",
      "title": "INSpeakable",
      "type": "topic",
      "url": "/documentation/intents/inspeakable"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPerson"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.sirikit/documentation/Intents/INSpeakable",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INRideOption",
        "doc://com.apple.sirikit/documentation/Intents/INRideStatus",
        "doc://com.apple.sirikit/documentation/Intents/INRideVehicle",
        "doc://com.apple.sirikit/documentation/Intents/INRideFareLineItem",
        "doc://com.apple.sirikit/documentation/Intents/INRidePartySizeOption",
        "doc://com.apple.sirikit/documentation/Intents/INRideCompletionStatus"
      ],
      "title": "Data Objects"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-a-Ride-Driver-Object",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INRideDriver/init(phoneNumber:nameComponents:displayName:image:rating:)",
        "doc://com.apple.sirikit/documentation/Intents/INRideDriver/init(handle:displayName:image:rating:phoneNumber:)",
        "doc://com.apple.sirikit/documentation/Intents/INRideDriver/init(handle:nameComponents:image:rating:phoneNumber:)",
        "doc://com.apple.sirikit/documentation/Intents/INRideDriver/init(personHandle:nameComponents:displayName:image:rating:phoneNumber:)"
      ],
      "title": "Initializing a Ride Driver Object"
    },
    {
      "anchor": "Getting-the-Driver-Information",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INRideDriver/rating",
        "doc://com.apple.sirikit/documentation/Intents/INRideDriver/phoneNumber"
      ],
      "title": "Getting the Driver Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INRideDriver"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRideDriver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRideDriver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializing-a-Ride-Driver-Object",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INRideDriver/init(phoneNumber:nameComponents:displayName:image:rating:)",
                "doc://com.apple.sirikit/documentation/Intents/INRideDriver/init(handle:displayName:image:rating:phoneNumber:)",
                "doc://com.apple.sirikit/documentation/Intents/INRideDriver/init(handle:nameComponents:image:rating:phoneNumber:)",
                "doc://com.apple.sirikit/documentation/Intents/INRideDriver/init(personHandle:nameComponents:displayName:image:rating:phoneNumber:)"
              ],
              "title": "Initializing a Ride Driver Object"
            },
            {
              "anchor": "Getting-the-Driver-Information",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INRideDriver/rating",
                "doc://com.apple.sirikit/documentation/Intents/INRideDriver/phoneNumber"
              ],
              "title": "Getting the Driver Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPerson"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Objects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INRideOption",
                "doc://com.apple.sirikit/documentation/Intents/INRideStatus",
                "doc://com.apple.sirikit/documentation/Intents/INRideVehicle",
                "doc://com.apple.sirikit/documentation/Intents/INRideFareLineItem",
                "doc://com.apple.sirikit/documentation/Intents/INRidePartySizeOption",
                "doc://com.apple.sirikit/documentation/Intents/INRideCompletionStatus"
              ],
              "title": "Data Objects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INRideDriver"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INPerson",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INPerson",
                    "text": "INPerson"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeakable/title",
          "value": "INSpeakable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeakable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSpeakable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSpeakable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSpeakable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideDriver~1init(handle:nameComponents:image:rating:phoneNumber:)/title",
          "value": "initWithHandle:nameComponents:image:rating:phoneNumber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideDriver~1init(handle:nameComponents:image:rating:phoneNumber:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithHandle:nameComponents:image:rating:phoneNumber:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideVehicle/title",
          "value": "INRideVehicle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideVehicle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRideVehicle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideVehicle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRideVehicle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideCompletionStatus/title",
          "value": "INRideCompletionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideCompletionStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRideCompletionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideCompletionStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRideCompletionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRidePartySizeOption/title",
          "value": "INRidePartySizeOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRidePartySizeOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRidePartySizeOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRidePartySizeOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRidePartySizeOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideStatus/title",
          "value": "INRideStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRideStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRideStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideOption/title",
          "value": "INRideOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRideOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRideOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideDriver~1init(personHandle:nameComponents:displayName:image:rating:phoneNumber:)/title",
          "value": "initWithPersonHandle:nameComponents:displayName:image:rating:phoneNumber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideDriver~1init(personHandle:nameComponents:displayName:image:rating:phoneNumber:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPersonHandle:nameComponents:displayName:image:rating:phoneNumber:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideDriver~1phoneNumber/title",
          "value": "phoneNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideDriver~1phoneNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "phoneNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideFareLineItem/title",
          "value": "INRideFareLineItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideFareLineItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRideFareLineItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideFareLineItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRideFareLineItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPerson/title",
          "value": "INPerson"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPerson/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPerson/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideStatus~1driver/title",
          "value": "driver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideStatus~1driver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "driver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideDriver~1init(phoneNumber:nameComponents:displayName:image:rating:)/title",
          "value": "initWithPhoneNumber:nameComponents:displayName:image:rating:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideDriver~1init(phoneNumber:nameComponents:displayName:image:rating:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPhoneNumber:nameComponents:displayName:image:rating:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideDriver/title",
          "value": "INRideDriver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideDriver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRideDriver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideDriver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRideDriver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideDriver~1rating/title",
          "value": "rating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideDriver~1rating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideDriver~1init(handle:displayName:image:rating:phoneNumber:)/title",
          "value": "initWithHandle:displayName:image:rating:phoneNumber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideDriver~1init(handle:displayName:image:rating:phoneNumber:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithHandle:displayName:image:rating:phoneNumber:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inridedriver"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inridedriver"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
