{
  "abstract": [
    {
      "text": "Constants indicating the state of the response.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INSendPaymentIntentResponseCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INSendPaymentIntentResponseCode"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INSendPaymentIntentResponseCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INSendPaymentIntentResponseCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponse/code": {
      "abstract": [
        {
          "text": "The code indicating whether you successfully handled the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INSendPaymentIntentResponseCode",
          "text": "INSendPaymentIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponse/code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "code"
        }
      ],
      "role": "symbol",
      "title": "code",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentintentresponse/code"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode": {
      "abstract": [
        {
          "text": "Constants indicating the state of the response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSendPaymentIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "You were unable to send the funds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureCredentialsUnverified": {
      "abstract": [
        {
          "text": "You were unable to deliver the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureCredentialsUnverified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureCredentialsUnverified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentIntentResponseCodeFailureCredentialsUnverified"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentIntentResponseCode.failureCredentialsUnverified",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentintentresponsecode/failurecredentialsunverified"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureInsufficientFunds": {
      "abstract": [
        {
          "text": "You were unable to deliver the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureInsufficientFunds"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureInsufficientFunds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentIntentResponseCodeFailureInsufficientFunds"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentIntentResponseCode.failureInsufficientFunds",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentintentresponsecode/failureinsufficientfunds"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureNoBankAccount": {
      "abstract": [
        {
          "text": "You were unable to deliver the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureNoBankAccount"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureNoBankAccount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentIntentResponseCodeFailureNoBankAccount"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentIntentResponseCode.failureNoBankAccount",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentintentresponsecode/failurenobankaccount"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureNotEligible": {
      "abstract": [
        {
          "text": "The request failed because a user was not eligible to perform the transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureNotEligible"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureNotEligible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentIntentResponseCodeFailureNotEligible"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentIntentResponseCode.failureNotEligible",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentintentresponsecode/failurenoteligible"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failurePaymentsAmountAboveMaximum": {
      "abstract": [
        {
          "text": "You were unable to deliver the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failurePaymentsAmountAboveMaximum"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failurePaymentsAmountAboveMaximum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentIntentResponseCodeFailurePaymentsAmountAboveMaximum"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentIntentResponseCode.failurePaymentsAmountAboveMaximum",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentintentresponsecode/failurepaymentsamountabovemaximum"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failurePaymentsAmountBelowMinimum": {
      "abstract": [
        {
          "text": "You were unable to deliver the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failurePaymentsAmountBelowMinimum"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failurePaymentsAmountBelowMinimum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentIntentResponseCodeFailurePaymentsAmountBelowMinimum"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentIntentResponseCode.failurePaymentsAmountBelowMinimum",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentintentresponsecode/failurepaymentsamountbelowminimum"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failurePaymentsCurrencyUnsupported": {
      "abstract": [
        {
          "text": "You were unable to deliver the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failurePaymentsCurrencyUnsupported"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failurePaymentsCurrencyUnsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentIntentResponseCodeFailurePaymentsCurrencyUnsupported"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentIntentResponseCode.failurePaymentsCurrencyUnsupported",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentintentresponsecode/failurepaymentscurrencyunsupported"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "The user must launch your app to send the funds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureTermsAndConditionsAcceptanceRequired": {
      "abstract": [
        {
          "text": "The request failed because the user must accept the app’s terms and conditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureTermsAndConditionsAcceptanceRequired"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureTermsAndConditionsAcceptanceRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentIntentResponseCodeFailureTermsAndConditionsAcceptanceRequired"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentIntentResponseCode.failureTermsAndConditionsAcceptanceRequired",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentintentresponsecode/failuretermsandconditionsacceptancerequired"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/inProgress": {
      "abstract": [
        {
          "text": "You are in the process of handling the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProgress"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/inProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentIntentResponseCodeInProgress"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentIntentResponseCode.inProgress",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentintentresponsecode/inprogress"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentintentresponsecode/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "You are ready to handle the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/success": {
      "abstract": [
        {
          "text": "You successfully handled the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentIntentResponseCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentIntentResponseCode.success",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentintentresponsecode/success"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "The response didn’t specify a response code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentintentresponsecode/unspecified"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Response-Code",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponse/code"
      ],
      "title": "Getting the Response Code"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/unspecified",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/inProgress",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/success",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureRequiringAppLaunch",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureCredentialsUnverified",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failurePaymentsAmountBelowMinimum",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failurePaymentsAmountAboveMaximum",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failurePaymentsCurrencyUnsupported",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureInsufficientFunds",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureNoBankAccount",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureNotEligible",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureTermsAndConditionsAcceptanceRequired"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INSendPaymentIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/unspecified",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/inProgress",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/success",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureRequiringAppLaunch",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureCredentialsUnverified",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failurePaymentsAmountBelowMinimum",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failurePaymentsAmountAboveMaximum",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failurePaymentsCurrencyUnsupported",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureInsufficientFunds",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureNoBankAccount",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureNotEligible",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponseCode/failureTermsAndConditionsAcceptanceRequired"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Response-Code",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentIntentResponse/code"
              ],
              "title": "Getting the Response Code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INSendPaymentIntentResponseCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1ready/title",
          "value": "INSendPaymentIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failureInsufficientFunds/title",
          "value": "INSendPaymentIntentResponseCodeFailureInsufficientFunds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failureInsufficientFunds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCodeFailureInsufficientFunds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failureCredentialsUnverified/title",
          "value": "INSendPaymentIntentResponseCodeFailureCredentialsUnverified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failureCredentialsUnverified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCodeFailureCredentialsUnverified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failureNotEligible/title",
          "value": "INSendPaymentIntentResponseCodeFailureNotEligible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failureNotEligible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCodeFailureNotEligible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failurePaymentsAmountBelowMinimum/title",
          "value": "INSendPaymentIntentResponseCodeFailurePaymentsAmountBelowMinimum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failurePaymentsAmountBelowMinimum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCodeFailurePaymentsAmountBelowMinimum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponse~1code/title",
          "value": "code"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponse~1code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failureNoBankAccount/title",
          "value": "INSendPaymentIntentResponseCodeFailureNoBankAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failureNoBankAccount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCodeFailureNoBankAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1unspecified/title",
          "value": "INSendPaymentIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INSendPaymentIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1success/title",
          "value": "INSendPaymentIntentResponseCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1inProgress/title",
          "value": "INSendPaymentIntentResponseCodeInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1inProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCodeInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failurePaymentsAmountAboveMaximum/title",
          "value": "INSendPaymentIntentResponseCodeFailurePaymentsAmountAboveMaximum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failurePaymentsAmountAboveMaximum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCodeFailurePaymentsAmountAboveMaximum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failure/title",
          "value": "INSendPaymentIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failurePaymentsCurrencyUnsupported/title",
          "value": "INSendPaymentIntentResponseCodeFailurePaymentsCurrencyUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failurePaymentsCurrencyUnsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCodeFailurePaymentsCurrencyUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failureTermsAndConditionsAcceptanceRequired/title",
          "value": "INSendPaymentIntentResponseCodeFailureTermsAndConditionsAcceptanceRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode~1failureTermsAndConditionsAcceptanceRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCodeFailureTermsAndConditionsAcceptanceRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode/title",
          "value": "INSendPaymentIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentIntentResponseCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insendpaymentintentresponsecode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insendpaymentintentresponsecode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
