{
  "abstract": [
    {
      "text": "Constants indicating the reason why a recipient is not supported.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INSendMessageRecipientUnsupportedReason",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INSendMessageRecipientUnsupportedReason"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INSendMessageRecipientUnsupportedReason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INSendMessageRecipientUnsupportedReason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReason"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientResolutionResult/init(personResolutionResult:)": {
      "abstract": [
        {
          "text": "Creates a resolution result object with the specified person resolution result object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "personResolutionResult"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPersonResolutionResult",
          "text": "INPersonResolutionResult"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientResolutionResult/init(personResolutionResult:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPersonResolutionResult:"
        }
      ],
      "role": "symbol",
      "title": "init(personResolutionResult:)",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientresolutionresult/init(personresolutionresult:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientResolutionResult/unsupported(forReason:)": {
      "abstract": [
        {
          "text": "Creates an object whose resolution indicates that your app can’t use the specified person as a message recipient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INSendMessageRecipientUnsupportedReason",
          "text": "INSendMessageRecipientUnsupportedReason"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientResolutionResult/unsupported(forReason:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unsupportedForReason:"
        }
      ],
      "role": "symbol",
      "title": "unsupported(forReason:)",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientresolutionresult/unsupported(forreason:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason": {
      "abstract": [
        {
          "text": "Constants indicating the reason why a recipient is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReason"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReason"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageRecipientUnsupportedReason",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientunsupportedreason"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientunsupportedreason/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/messagingServiceNotEnabledForRecipient": {
      "abstract": [
        {
          "text": "A recipient for whom messaging is not enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messagingServiceNotEnabledForRecipient"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/messagingServiceNotEnabledForRecipient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReasonMessagingServiceNotEnabledForRecipient"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageRecipientUnsupportedReason.messagingServiceNotEnabledForRecipient",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientunsupportedreason/messagingservicenotenabledforrecipient"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noAccount": {
      "abstract": [
        {
          "text": "A recipient without an account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noAccount"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noAccount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReasonNoAccount"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageRecipientUnsupportedReason.noAccount",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientunsupportedreason/noaccount"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noHandleForLabel": {
      "abstract": [
        {
          "text": "A recipient for whom there is no handle for the provided label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noHandleForLabel"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noHandleForLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReasonNoHandleForLabel"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageRecipientUnsupportedReason.noHandleForLabel",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientunsupportedreason/nohandleforlabel"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noValidHandle": {
      "abstract": [
        {
          "text": "A recipient for whom there is no valid handle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noValidHandle"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noValidHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReasonNoValidHandle"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageRecipientUnsupportedReason.noValidHandle",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientunsupportedreason/novalidhandle"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/offline": {
      "abstract": [
        {
          "text": "An offline recipient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offline"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/offline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReasonOffline"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageRecipientUnsupportedReason.offline",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientunsupportedreason/offline"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/requestedHandleInvalid": {
      "abstract": [
        {
          "text": "A recipient for whom the requested handle is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestedHandleInvalid"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/requestedHandleInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReasonRequestedHandleInvalid"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageRecipientUnsupportedReason.requestedHandleInvalid",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientunsupportedreason/requestedhandleinvalid"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/requiringInAppAuthentication": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiringInAppAuthentication"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/requiringInAppAuthentication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageRecipientUnsupportedReasonRequiringInAppAuthentication"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageRecipientUnsupportedReason.requiringInAppAuthentication",
      "type": "topic",
      "url": "/documentation/intents/insendmessagerecipientunsupportedreason/requiringinappauthentication"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Resolution-Result-Object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientResolutionResult/unsupported(forReason:)",
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientResolutionResult/init(personResolutionResult:)"
      ],
      "title": "Creating a Resolution Result Object"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noAccount",
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/offline",
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/messagingServiceNotEnabledForRecipient",
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noHandleForLabel",
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noValidHandle",
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/requestedHandleInvalid",
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/requiringInAppAuthentication"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INSendMessageRecipientUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noAccount",
                "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/offline",
                "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/messagingServiceNotEnabledForRecipient",
                "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noHandleForLabel",
                "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/noValidHandle",
                "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/requestedHandleInvalid",
                "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientUnsupportedReason/requiringInAppAuthentication"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Resolution-Result-Object",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientResolutionResult/unsupported(forReason:)",
                "doc://com.apple.sirikit/documentation/Intents/INSendMessageRecipientResolutionResult/init(personResolutionResult:)"
              ],
              "title": "Creating a Resolution Result Object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INSendMessageRecipientUnsupportedReason"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason/title",
          "value": "INSendMessageRecipientUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1noAccount/title",
          "value": "INSendMessageRecipientUnsupportedReasonNoAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1noAccount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReasonNoAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1noValidHandle/title",
          "value": "INSendMessageRecipientUnsupportedReasonNoValidHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1noValidHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReasonNoValidHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientResolutionResult~1init(personResolutionResult:)/title",
          "value": "initWithPersonResolutionResult:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientResolutionResult~1init(personResolutionResult:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPersonResolutionResult:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientResolutionResult~1unsupported(forReason:)/title",
          "value": "unsupportedForReason:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientResolutionResult~1unsupported(forReason:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "unsupportedForReason:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1messagingServiceNotEnabledForRecipient/title",
          "value": "INSendMessageRecipientUnsupportedReasonMessagingServiceNotEnabledForRecipient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1messagingServiceNotEnabledForRecipient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReasonMessagingServiceNotEnabledForRecipient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1requestedHandleInvalid/title",
          "value": "INSendMessageRecipientUnsupportedReasonRequestedHandleInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1requestedHandleInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReasonRequestedHandleInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1offline/title",
          "value": "INSendMessageRecipientUnsupportedReasonOffline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1offline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReasonOffline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1noHandleForLabel/title",
          "value": "INSendMessageRecipientUnsupportedReasonNoHandleForLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1noHandleForLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReasonNoHandleForLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1requiringInAppAuthentication/title",
          "value": "INSendMessageRecipientUnsupportedReasonRequiringInAppAuthentication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageRecipientUnsupportedReason~1requiringInAppAuthentication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageRecipientUnsupportedReasonRequiringInAppAuthentication"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insendmessagerecipientunsupportedreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insendmessagerecipientunsupportedreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
