{
  "abstract": [
    {
      "text": "The handler interface for changing a vehicle’s seat-related settings.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INSetSeatSettingsInCarIntentHandling",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INSetSeatSettingsInCarIntentHandling"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INSetSeatSettingsInCarIntentHandling"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INSetSeatSettingsInCarIntentHandling is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INSetSeatSettingsInCarIntentHandling is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INSetSeatSettingsInCarIntentHandling is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INSetSeatSettingsInCarIntentHandling is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "INSetSeatSettingsInCarIntentHandling"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntentHandling"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Automotive venders can support the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol in an Intents extension that they ship with their automotive apps. Use the methods of this protocol to resolve, confirm, and handle requests to change the vehicle’s seat-related settings. Your extension should be able to communicate with the vehicle and make the necessary changes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Siri delivers an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to your handler when the user asks to change any seat settings. The provided intent object contains information that you use to determine which settings changed and what the new settings should be.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the CarPlay domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarPlayDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarPlayDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INCarPlayDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/incarplaydomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent": {
      "abstract": [
        {
          "text": "A request to change the seat-related settings in a CarPlay-enabled vehicle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntent"
        }
      ],
      "role": "symbol",
      "title": "INSetSeatSettingsInCarIntent",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for changing a vehicle’s seat-related settings.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSetSeatSettingsInCarIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/confirm(intent:completion:)": {
      "abstract": [
        {
          "text": "Confirms whether you can change the seat settings.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirm"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetSeatSettingsInCarIntent",
          "text": "INSetSeatSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetSeatSettingsInCarIntentResponse",
          "text": "INSetSeatSettingsInCarIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/confirm(intent:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "confirmSetSeatSettingsInCar:completion:"
        }
      ],
      "role": "symbol",
      "title": "confirm(intent:completion:)",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintenthandling/confirm(intent:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/handle(intent:completion:)": {
      "abstract": [
        {
          "text": "Handles changing the seat settings.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetSeatSettingsInCarIntent",
          "text": "INSetSeatSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetSeatSettingsInCarIntentResponse",
          "text": "INSetSeatSettingsInCarIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/handle(intent:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleSetSeatSettingsInCar:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handle(intent:completion:)",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintenthandling/handle(intent:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveCarName(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the car name.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveCarName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetSeatSettingsInCarIntent",
          "text": "INSetSeatSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSpeakableStringResolutionResult",
          "text": "INSpeakableStringResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveCarName(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveCarNameForSetSeatSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveCarName(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintenthandling/resolvecarname(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveEnableCooling(for:with:)": {
      "abstract": [
        {
          "text": "Resolves whether you can enable the seat cooling system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveEnableCooling"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetSeatSettingsInCarIntent",
          "text": "INSetSeatSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBooleanResolutionResult",
          "text": "INBooleanResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveEnableCooling(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveEnableCoolingForSetSeatSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveEnableCooling(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintenthandling/resolveenablecooling(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveEnableHeating(for:with:)": {
      "abstract": [
        {
          "text": "Resolves whether you can enable the seat heating system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveEnableHeating"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetSeatSettingsInCarIntent",
          "text": "INSetSeatSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBooleanResolutionResult",
          "text": "INBooleanResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveEnableHeating(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveEnableHeatingForSetSeatSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveEnableHeating(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintenthandling/resolveenableheating(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveEnableMassage(for:with:)": {
      "abstract": [
        {
          "text": "Resolves whether you can enable the seat massage system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveEnableMassage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetSeatSettingsInCarIntent",
          "text": "INSetSeatSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBooleanResolutionResult",
          "text": "INBooleanResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveEnableMassage(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveEnableMassageForSetSeatSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveEnableMassage(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintenthandling/resolveenablemassage(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveLevel(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the intensity level of the requested system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveLevel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetSeatSettingsInCarIntent",
          "text": "INSetSeatSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INIntegerResolutionResult",
          "text": "INIntegerResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveLevel(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveLevelForSetSeatSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveLevel(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintenthandling/resolvelevel(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveRelativeLevelSetting(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the requested relative qualifier for the intensity level.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveRelativeLevelSetting"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetSeatSettingsInCarIntent",
          "text": "INSetSeatSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INRelativeSettingResolutionResult",
          "text": "INRelativeSettingResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveRelativeLevelSetting(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveRelativeLevelSettingForSetSeatSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveRelativeLevelSetting(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintenthandling/resolverelativelevelsetting(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveSeat(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the requested seat position.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveSeat"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetSeatSettingsInCarIntent",
          "text": "INSetSeatSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCarSeatResolutionResult",
          "text": "INCarSeatResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveSeat(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveSeatForSetSeatSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveSeat(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintenthandling/resolveseat(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a set seat settings in car intent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INSetSeatSettingsInCarIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintentresponse"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "CarPlay-Seat-Settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent",
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentResponse"
      ],
      "title": "CarPlay Seat Settings"
    }
  ],
  "topicSections": [
    {
      "anchor": "Resolving-the-Intent-Parameters",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveEnableCooling(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveEnableHeating(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveEnableMassage(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveSeat(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveLevel(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveRelativeLevelSetting(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveCarName(for:with:)"
      ],
      "title": "Resolving the Intent Parameters"
    },
    {
      "anchor": "Confirming-the-Response",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/confirm(intent:completion:)"
      ],
      "title": "Confirming the Response"
    },
    {
      "anchor": "Handling-the-Intent",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/handle(intent:completion:)"
      ],
      "title": "Handling the Intent"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INSetSeatSettingsInCarIntentHandling"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Resolving-the-Intent-Parameters",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveEnableCooling(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveEnableHeating(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveEnableMassage(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveSeat(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveLevel(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveRelativeLevelSetting(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/resolveCarName(for:with:)"
              ],
              "title": "Resolving the Intent Parameters"
            },
            {
              "anchor": "Confirming-the-Response",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/confirm(intent:completion:)"
              ],
              "title": "Confirming the Response"
            },
            {
              "anchor": "Handling-the-Intent",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling/handle(intent:completion:)"
              ],
              "title": "Handling the Intent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "CarPlay-Seat-Settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentResponse"
              ],
              "title": "CarPlay Seat Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INSetSeatSettingsInCarIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling/title",
          "value": "INSetSeatSettingsInCarIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentResponse/title",
          "value": "INSetSeatSettingsInCarIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1confirm(intent:completion:)/title",
          "value": "confirmSetSeatSettingsInCar:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1confirm(intent:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "confirmSetSeatSettingsInCar:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1resolveCarName(for:with:)/title",
          "value": "resolveCarNameForSetSeatSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1resolveCarName(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveCarNameForSetSeatSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1handle(intent:completion:)/title",
          "value": "handleSetSeatSettingsInCar:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1handle(intent:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleSetSeatSettingsInCar:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1resolveEnableCooling(for:with:)/title",
          "value": "resolveEnableCoolingForSetSeatSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1resolveEnableCooling(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveEnableCoolingForSetSeatSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent/title",
          "value": "INSetSeatSettingsInCarIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarPlayDomainHandling/title",
          "value": "INCarPlayDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarPlayDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarPlayDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarPlayDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarPlayDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1resolveSeat(for:with:)/title",
          "value": "resolveSeatForSetSeatSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1resolveSeat(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveSeatForSetSeatSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1resolveRelativeLevelSetting(for:with:)/title",
          "value": "resolveRelativeLevelSettingForSetSeatSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1resolveRelativeLevelSetting(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveRelativeLevelSettingForSetSeatSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1resolveLevel(for:with:)/title",
          "value": "resolveLevelForSetSeatSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1resolveLevel(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveLevelForSetSeatSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1resolveEnableHeating(for:with:)/title",
          "value": "resolveEnableHeatingForSetSeatSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1resolveEnableHeating(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveEnableHeatingForSetSeatSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1resolveEnableMassage(for:with:)/title",
          "value": "resolveEnableMassageForSetSeatSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling~1resolveEnableMassage(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveEnableMassageForSetSeatSettingsInCar:withCompletion:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insetseatsettingsincarintenthandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insetseatsettingsincarintenthandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
