{
  "abstract": [
    {
      "text": "An ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntent",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@INSearchForMessagesIntentIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INSearchForMessagesIntentIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INSearchForMessagesIntentIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "INSearchForMessagesIntentIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntentIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntent": {
      "abstract": [
        {
          "text": "A request to list the messages that match the specified criteria.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchForMessagesIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMessagesIntent"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMessagesIntent",
      "type": "topic",
      "url": "/documentation/intents/insearchformessagesintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentIdentifier": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntent",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchForMessagesIntentIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMessagesIntentIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMessagesIntentIdentifier"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMessagesIntentIdentifier",
      "type": "topic",
      "url": "/documentation/intents/insearchformessagesintentidentifier"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageIntent": {
      "abstract": [
        {
          "text": "A request to send a message to the designated recipients.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSendMessageIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageIntent"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageIntent",
      "type": "topic",
      "url": "/documentation/intents/insendmessageintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendMessageIntentIdentifier": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageIntent",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSendMessageIntentIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendMessageIntentIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendMessageIntentIdentifier"
        }
      ],
      "role": "symbol",
      "title": "INSendMessageIntentIdentifier",
      "type": "topic",
      "url": "/documentation/intents/insendmessageintentidentifier"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetMessageAttributeIntent": {
      "abstract": [
        {
          "text": "A request to modify the attributes of a message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetMessageAttributeIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetMessageAttributeIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetMessageAttributeIntent"
        }
      ],
      "role": "symbol",
      "title": "INSetMessageAttributeIntent",
      "type": "topic",
      "url": "/documentation/intents/insetmessageattributeintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetMessageAttributeIntentIdentifier": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetMessageAttributeIntent",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetMessageAttributeIntentIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetMessageAttributeIntentIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetMessageAttributeIntentIdentifier"
        }
      ],
      "role": "symbol",
      "title": "INSetMessageAttributeIntentIdentifier",
      "type": "topic",
      "url": "/documentation/intents/insetmessageattributeintentidentifier"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Messaging",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSendMessageIntentIdentifier",
        "doc://com.apple.sirikit/documentation/Intents/INSetMessageAttributeIntentIdentifier"
      ],
      "title": "Messaging"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INSearchForMessagesIntentIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntentIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Messaging",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSendMessageIntentIdentifier",
                "doc://com.apple.sirikit/documentation/Intents/INSetMessageAttributeIntentIdentifier"
              ],
              "title": "Messaging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INSearchForMessagesIntentIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntent/title",
          "value": "INSearchForMessagesIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentIdentifier/title",
          "value": "INSearchForMessagesIntentIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMessagesIntentIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMessagesIntentIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetMessageAttributeIntent/title",
          "value": "INSetMessageAttributeIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetMessageAttributeIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetMessageAttributeIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetMessageAttributeIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetMessageAttributeIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetMessageAttributeIntentIdentifier/title",
          "value": "INSetMessageAttributeIntentIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetMessageAttributeIntentIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetMessageAttributeIntentIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageIntent/title",
          "value": "INSendMessageIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageIntentIdentifier/title",
          "value": "INSendMessageIntentIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendMessageIntentIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendMessageIntentIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insearchformessagesintentidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insearchformessagesintentidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
