{
  "abstract": [
    {
      "text": "A request to change the seat-related settings in a CarPlay-enabled vehicle.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INSetSeatSettingsInCarIntent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INSetSeatSettingsInCarIntent"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INSetSeatSettingsInCarIntent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INSetSeatSettingsInCarIntent is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INSetSeatSettingsInCarIntent is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INSetSeatSettingsInCarIntent is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INSetSeatSettingsInCarIntent is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "INSetSeatSettingsInCarIntent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntent"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Automotive venders can add support for this intent to an Intents extension that they ship with their automotive apps. When the user asks Siri to change a seat-related setting, Siri creates an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object and delivers it to the app’s Intents extension. You use the intent to identify which setting the user wants to change.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This class contains properties for multiple types of seat-related settings, but a given instance of this class contains changes for only one setting at a time. When resolving and confirming the parameters of this intent, use the specified properties to modify your vehicle’s seat settings. Assume no changes for other settings. If your vehicle doesn’t support a particular setting, offer a reasonable fallback setting and ask the user for confirmation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The object that handles this intent must adopt the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol. Use this intent object to identify which setting changed and to create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentResponse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object indicating the results of changing the seat settings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Additional-Intent-Attributes",
          "level": 3,
          "text": "Additional Intent Attributes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The following table lists additional attributes of this intent object:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Attribute",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Description",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Supported by",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Siri Intents (in conjunction with CarPlay)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Always requires unlocked device",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Yes",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "anchor": "Example-Phrases",
          "level": 3,
          "text": "Example Phrases",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Users can ask Siri to change the seat settings in a vehicle in a variety of ways. The table below provides a few sample phrases in different languages. You can use these phrases during testing to trigger your intents. This list isn’t exhaustive and Siri may recognize many other phrases.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Locale",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Example 1",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Example 2",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "en",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Turn on the passenger seat heater",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Set the driver’s seat cooler to level 2",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "zh_CN",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "打开乘客加热座椅",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "把座位温度调到2级",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "zh_HK",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "打開乘客加熱座椅",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "將通風座椅溫度調到level 2",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "zh_TW",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "打開乘客加熱座椅",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "把座位溫度調到2級",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "yue_CN",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "打开乘客加热座椅",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "将通风座椅温度调到level 2",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "ar",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "شغل تدفئة المقاعد للركاب",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "ضبط تهوية المقاعد إلى المستوى ٢",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "da",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "forsæde varme til niveau tre",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "bagsædevarme til niveau 2",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "de",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Schalte Beifahrersitzheizung ein",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Schalte Fahrersitzheizung ein auf 2",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "es",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Prende el calentador de asientos del copiloto",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Activa el calentador de asientos",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "fi",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Laita matkustajan istuimen lämmitin päälle",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Aseta kuljettajan istuimen viilennys tasoon 2",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "fr",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "chauffage du siège avant sur position 3",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Mets le chauffage du siège du passager avant sur 2",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "he",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "קירור המושב הקדמי למצב 3",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "תכווני את חימום המושב הקדמי למצב 3",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "it",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Accendi il riscaldamento del sedile passeggero",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Imposta il raffreddamento del sedile guidatore a livello due",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "ja",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "前の助手席の座席ヒーターをオン",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "運転席のシートクーラーの強さを2に設定",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "ko",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "탑승자 시트 히터 켜줘",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "운전자 시트 쿨러 레벨 2로 설정해줘",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "ms",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Hidupkan penghangat kerusi penumpang",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Setkan pendingin kerusi pemandu kepada posisi 2",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "nb",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Skru på varme i passasjersetet",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Sett setekjøler i førersetet til 2",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "nl",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Zet de stoelverwarming van de passagier aan",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Stel de stoelverkoeling op niveau 2 in",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "pt",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Ligue o aquecedor de assento do carona",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Coloque o resfriador de assento do motorista no nível 2",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "ru",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Включи подогрев сиденья пассажира",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Установи охлаждение сиденья водителя на уровень 2",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "sv",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Sätt på sätesvärmaren för passageraren",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Sätt chaufförens säteskylare till nivå 2",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "th",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "เปิดเบาะอุ่นที่นั่งผู้โดยสาร",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "ปรับความเย็นที่นั่งคนขับเป็นระดับ 2",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "tr",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Yolcu koltuğunun ısıtıcısını aç",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Sürücü koltuğu soğutucusunu 1’e getir",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "When managing CarPlay features, users don’t need to include the name of the app in the phrases that they speak. Siri knows automatically when CarPlay is active and routes CarPlay-related intents to the app of the corresponding automotive vendor.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntent": {
      "abstract": [
        {
          "text": "A request to fulfill in your app or Intents extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntent"
        }
      ],
      "role": "symbol",
      "title": "INIntent",
      "type": "topic",
      "url": "/documentation/intents/inintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentSetImageKeyPath": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentSetImageKeyPath"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentSetImageKeyPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentSetImageKeyPath"
        }
      ],
      "role": "symbol",
      "title": "INIntentSetImageKeyPath",
      "type": "topic",
      "url": "/documentation/intents/inintentsetimagekeypath"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent": {
      "abstract": [
        {
          "text": "A request to change the seat-related settings in a CarPlay-enabled vehicle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntent"
        }
      ],
      "role": "symbol",
      "title": "INSetSeatSettingsInCarIntent",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/carName": {
      "abstract": [
        {
          "text": "The name of the car you applied the settings to.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "carName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSpeakableString",
          "text": "INSpeakableString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/carName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "carName"
        }
      ],
      "role": "symbol",
      "title": "carName",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/carname"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableCooling-6bcu7": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to enable the seat cooling system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "enableCooling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableCooling-6bcu7",
      "kind": "symbol",
      "role": "symbol",
      "title": "enableCooling",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/enablecooling-6bcu7"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableCooling-8qqx3": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to enable the seat cooling system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableCooling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableCooling-8qqx3",
      "kind": "symbol",
      "role": "symbol",
      "title": "enableCooling",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/enablecooling-8qqx3"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableHeating-5qj7i": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to enable the seat heating system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "enableHeating"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableHeating-5qj7i",
      "kind": "symbol",
      "role": "symbol",
      "title": "enableHeating",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/enableheating-5qj7i"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableHeating-8auz2": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to enable the seat heating system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableHeating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableHeating-8auz2",
      "kind": "symbol",
      "role": "symbol",
      "title": "enableHeating",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/enableheating-8auz2"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableMassage-46ndx": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to enable the seat massage system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enableMassage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableMassage-46ndx",
      "kind": "symbol",
      "role": "symbol",
      "title": "enableMassage",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/enablemassage-46ndx"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableMassage-5jf2s": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to enable the seat massage system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "enableMassage"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableMassage-5jf2s",
      "kind": "symbol",
      "role": "symbol",
      "title": "enableMassage",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/enablemassage-5jf2s"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/init(enableHeating:enableCooling:enableMassage:seat:level:relativeLevel:carName:)": {
      "abstract": [
        {
          "text": "Initializes the intent object with the specified climate settings information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "enableHeating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "enableCooling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "enableMassage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "seat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCarSeat",
          "text": "INCarSeat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "level"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "relativeLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INRelativeSetting",
          "text": "INRelativeSetting"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "carName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSpeakableString",
          "text": "INSpeakableString"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/init(enableHeating:enableCooling:enableMassage:seat:level:relativeLevel:carName:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(enableHeating:enableCooling:enableMassage:seat:level:relativeLevel:carName:)",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/init(enableheating:enablecooling:enablemassage:seat:level:relativelevel:carname:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/initWithEnableHeating:enableCooling:enableMassage:seat:level:relativeLevelSetting:": {
      "abstract": [
        {
          "text": "Initializes the intent object with the specified climate settings information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithEnableHeating:enableCooling:enableMassage:seat:level:relativeLevelSetting:"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/initWithEnableHeating:enableCooling:enableMassage:seat:level:relativeLevelSetting:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEnableHeating:enableCooling:enableMassage:seat:level:relativeLevelSetting:"
        }
      ],
      "role": "symbol",
      "title": "initWithEnableHeating:enableCooling:enableMassage:seat:level:relativeLevelSetting:",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/initwithenableheating:enablecooling:enablemassage:seat:level:relativelevelsetting:"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/initWithEnableHeating:enableCooling:enableMassage:seat:level:relativeLevelSetting:carName:": {
      "abstract": [
        {
          "text": "Initializes the intent object with the specified climate settings information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithEnableHeating:enableCooling:enableMassage:seat:level:relativeLevelSetting:carName:"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/initWithEnableHeating:enableCooling:enableMassage:seat:level:relativeLevelSetting:carName:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEnableHeating:enableCooling:enableMassage:seat:level:relativeLevelSetting:carName:"
        }
      ],
      "role": "symbol",
      "title": "initWithEnableHeating:enableCooling:enableMassage:seat:level:relativeLevelSetting:carName:",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/initwithenableheating:enablecooling:enablemassage:seat:level:relativelevelsetting:carname:"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/level-5i2i": {
      "abstract": [
        {
          "text": "An integer value indicating the desired level for the seat setting.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "level"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/level-5i2i",
      "kind": "symbol",
      "role": "symbol",
      "title": "level",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/level-5i2i"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/level-94975": {
      "abstract": [
        {
          "text": "An integer value indicating the desired level for the seat setting.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "level"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/level-94975",
      "kind": "symbol",
      "role": "symbol",
      "title": "level",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/level-94975"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/relativeLevelSetting": {
      "abstract": [
        {
          "text": "A relative change to the level value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relativeLevelSetting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INRelativeSetting",
          "text": "INRelativeSetting"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/relativeLevelSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "relativeLevelSetting"
        }
      ],
      "role": "symbol",
      "title": "relativeLevelSetting",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/relativelevelsetting"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/seat": {
      "abstract": [
        {
          "text": "The seat position whose settings you want to modify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "seat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCarSeat",
          "text": "INCarSeat"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/seat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "seat"
        }
      ],
      "role": "symbol",
      "title": "seat",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintent/seat"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for changing a vehicle’s seat-related settings.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSetSeatSettingsInCarIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a set seat settings in car intent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetSeatSettingsInCarIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INSetSeatSettingsInCarIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/insetseatsettingsincarintentresponse"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntent"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.sirikit/documentation/Intents/INIntentSetImageKeyPath",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "CarPlay-Seat-Settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentResponse"
      ],
      "title": "CarPlay Seat Settings"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-the-Intent-Object",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/init(enableHeating:enableCooling:enableMassage:seat:level:relativeLevel:carName:)"
      ],
      "title": "Initializing the Intent Object"
    },
    {
      "anchor": "Getting-the-Seat-Position",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/seat"
      ],
      "title": "Getting the Seat Position"
    },
    {
      "anchor": "Getting-the-New-Settings",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableCooling-8qqx3",
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableHeating-8auz2",
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableMassage-46ndx",
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/level-94975",
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/relativeLevelSetting"
      ],
      "title": "Getting the New Settings"
    },
    {
      "anchor": "Getting-the-Car-Name",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/carName"
      ],
      "title": "Getting the Car Name"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INSetSeatSettingsInCarIntent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializing-the-Intent-Object",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/initWithEnableHeating:enableCooling:enableMassage:seat:level:relativeLevelSetting:carName:",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/initWithEnableHeating:enableCooling:enableMassage:seat:level:relativeLevelSetting:"
              ],
              "title": "Initializing the Intent Object"
            },
            {
              "anchor": "Getting-the-Seat-Position",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/seat"
              ],
              "title": "Getting the Seat Position"
            },
            {
              "anchor": "Getting-the-New-Settings",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableCooling-6bcu7",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableHeating-5qj7i",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/enableMassage-5jf2s",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/level-5i2i",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/relativeLevelSetting"
              ],
              "title": "Getting the New Settings"
            },
            {
              "anchor": "Getting-the-Car-Name",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntent/carName"
              ],
              "title": "Getting the Car Name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INIntent"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "CarPlay-Seat-Settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INSetSeatSettingsInCarIntentResponse"
              ],
              "title": "CarPlay Seat Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INSetSeatSettingsInCarIntent"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INIntent",
                    "text": "INIntent"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling/title",
          "value": "INSetSeatSettingsInCarIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntent/title",
          "value": "INIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent~1seat/title",
          "value": "seat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent~1seat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "seat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentResponse/title",
          "value": "INSetSeatSettingsInCarIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent~1carName/title",
          "value": "carName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent~1carName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "carName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent~1relativeLevelSetting/title",
          "value": "relativeLevelSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent~1relativeLevelSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "relativeLevelSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent/title",
          "value": "INSetSeatSettingsInCarIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetSeatSettingsInCarIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetSeatSettingsInCarIntent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insetseatsettingsincarintent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insetseatsettingsincarintent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
