{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent","interfaceLanguage":"swift"},"metadata":{"symbolKind":"class","title":"INSetDefrosterSettingsInCarIntent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INSetDefrosterSettingsInCarIntent"}],"role":"symbol","externalID":"c:objc(cs)INSetDefrosterSettingsInCarIntent","modules":[{"name":"Intents"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"INSetDefrosterSettingsInCarIntent"}],"platforms":[{"deprecated":false,"unavailable":false,"deprecatedAt":"15.0","message":"INSetDefrosterSettingsInCarIntent is deprecated. There is no replacement.","beta":false,"name":"iOS","introducedAt":"10.0"},{"beta":false,"message":"INSetDefrosterSettingsInCarIntent is deprecated. There is no replacement.","name":"iPadOS","deprecatedAt":"15.0","unavailable":false,"introducedAt":"10.0","deprecated":false},{"beta":false,"message":"INSetDefrosterSettingsInCarIntent is deprecated. There is no replacement.","name":"Mac Catalyst","deprecatedAt":"15.0","unavailable":false,"introducedAt":"13.1","deprecated":false},{"beta":false,"message":"INSetDefrosterSettingsInCarIntent is deprecated. There is no replacement.","name":"visionOS","deprecatedAt":"1.0","unavailable":false,"introducedAt":"1.0","deprecated":false}]},"topicSections":[{"title":"Initializing the Intent Object","anchor":"Initializing-the-Intent-Object","identifiers":["doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/init(enable:defroster:carName:)"]},{"title":"Getting Details About the Defroster Settings to Set","anchor":"Getting-Details-About-the-Defroster-Settings-to-Set","identifiers":["doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/enable-9xte9","doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/defroster"]},{"title":"Getting the Car Name","anchor":"Getting-the-Car-Name","identifiers":["doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/carName"]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc://com.apple.sirikit/documentation/Intents/INIntent"],"type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.apple.sirikit/documentation/Intents/INIntentSetImageKeyPath","doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"],"title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.sirikit/documentation/Intents"]]},"seeAlsoSections":[{"anchor":"CarPlay-Defroster-Settings","identifiers":["doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling","doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentResponse"],"title":"CarPlay Defroster Settings","generated":true}],"variants":[{"paths":["/documentation/intents/insetdefrostersettingsincarintent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/intents/insetdefrostersettingsincarintent"],"traits":[{"interfaceLanguage":"occ"}]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This intent is no longer available. You may define a custom intent instead. For more information, see "},{"type":"reference","identifier":"https://developer.apple.com/support/deprecated-sirikit-intent-domains","isActive":true},{"type":"text","text":"."}]}],"kind":"symbol","sections":[],"abstract":[{"text":"A request to change the defroster settings in a CarPlay-enabled vehicle.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"INSetDefrosterSettingsInCarIntent","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"inlineContent":[{"text":"Automotive venders can add support for this intent to an Intents extension that they ship with their automotive apps. When the user asks Siri to change the defroster settings for a vehicle, SiriKit creates an ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent","type":"reference"},{"text":" object and delivers it to the app’s Intents extension. You use the intent to identify which defroster the user wants to enable or disable and to communicate the changes directly to your vehicle’s systems.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The object that handles this intent must adopt the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling"},{"type":"text","text":" protocol. Use this intent object to resolve the defroster details and to create an "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentResponse"},{"type":"text","text":" object indicating whether you were able to make the change successfully."}],"type":"paragraph"},{"level":3,"anchor":"Additional-Intent-Attributes","type":"heading","text":"Additional Intent Attributes"},{"inlineContent":[{"type":"text","text":"The following table lists additional attributes of this intent object:"}],"type":"paragraph"},{"header":"row","type":"table","rows":[[[{"inlineContent":[{"text":"Attribute","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Description"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"Supported by"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Siri Intents (in conjunction with CarPlay)","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"Always requires unlocked device"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Yes","type":"text"}],"type":"paragraph"}]]]},{"level":3,"anchor":"Example-Phrases","type":"heading","text":"Example Phrases"},{"inlineContent":[{"text":"Users can ask Siri to enable or disable the defrosters in a vehicle in a variety of ways. The table below provides a few sample phrases in different languages. You can use these phrases during testing to trigger your intents. This list isn’t exhaustive and Siri may recognize many other phrases.","type":"text"}],"type":"paragraph"},{"header":"row","type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Locale"}]}],[{"type":"paragraph","inlineContent":[{"text":"Example 1","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"Example 2","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"text":"en","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"Turn on the rear defroster","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"Turn off the front defroster","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"text":"zh_CN","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"打开前窗除雾","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"打开后窗除雾","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"text":"zh_HK","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"打開前面車窗除霧"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"打開後車窗嘅除霧"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"zh_TW"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"打開前窗除霧"}]}],[{"type":"paragraph","inlineContent":[{"text":"打開後窗除霧","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"text":"yue_CN","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"打开前面车窗除雾"}]}],[{"type":"paragraph","inlineContent":[{"text":"打开后车窗嘅除雾","type":"text"}]}]],[[{"inlineContent":[{"type":"text","text":"ar"}],"type":"paragraph"}],[{"inlineContent":[{"text":"شغل مزيل الصقيع الخلفي","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"شغل مزيل الصقيع الأمامي","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"da","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"afrimer på fuld styrke"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Sluk for afrimeren"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"de"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Heckscheibenheizung einschalten"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Schalte Heckscheibenheizung ein","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"es","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Enciende el desempañador"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Apaga el desempañador trasero","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"fi"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Laita takaikkunan huurteenpoisto päälle"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Laita takaikkunan huurteenpoisto pois päältä"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"fr","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Allume le dégivrage arrière"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Mets en marche le dégivrage arrière"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"he","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"שים את מפיג האדים בעוצמה הגבוהה ביותר","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"שימי את המוריד אדים על הכי חזק"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"it"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Accendi lo sbrinatore posteriore","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Spegni lo sbrinatore del parabrezza","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"ja","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"後部デフロスターをオンにして"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"フロントデフロスターをオフにして"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"ko","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"뒷 유리 서리 제거해","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"앞 유리 서리 제거해","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"type":"text","text":"ms"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Hidupkan penyahfros belakang","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Matikan penyahfros depan"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"text":"nb","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"Skru på defrosteren bak","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"Skru av defrosteren foran","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"nl"}]}],[{"type":"paragraph","inlineContent":[{"text":"Zet de ontdooier achteraan aan","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Zet de ontwasemer van voor uit"}]}]],[[{"type":"paragraph","inlineContent":[{"text":"pt","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"Ligue o desembaçador traseiro"}]}],[{"type":"paragraph","inlineContent":[{"text":"Desligar o desembaçador frontal","type":"text"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"ru"}]}],[{"type":"paragraph","inlineContent":[{"text":"Включи задний обогреватель стёкол","type":"text"}]}],[{"type":"paragraph","inlineContent":[{"text":"Выключи передний подогрев стёкол","type":"text"}]}]],[[{"inlineContent":[{"type":"text","text":"sv"}],"type":"paragraph"}],[{"inlineContent":[{"text":"avfrostaren på full styrka","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"avfrostaren på max"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"th","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"เปิดตัวไล่ฝ้าด้านหลัง","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"text":"ปิดที่ไล่ฝ้าด้านหน้า","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"text":"tr","type":"text"}],"type":"paragraph"}],[{"inlineContent":[{"type":"text","text":"Arka buz çözücüyü başlat"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Ön buz çözücüyü kapat","type":"text"}],"type":"paragraph"}]]]},{"inlineContent":[{"type":"text","text":"When managing CarPlay features, users don’t need to include the name of the app in the phrases that they speak. Siri knows automatically when CarPlay is active and routes CarPlay-related intents to the app of the corresponding automotive vendor."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:SQ","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Equatable"}],"role":"symbol","url":"/documentation/Swift/Equatable","title":"Equatable"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"role":"symbol","abstract":[{"type":"text","text":"The group of methods that are fundamental to all Objective-C objects."}],"kind":"symbol","url":"/documentation/objectivec/nsobjectprotocol","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSObjectProtocol"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","type":"topic","title":"NSObjectProtocol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding":{"abstract":[{"text":"A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.","type":"text"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding","type":"topic","title":"NSSecureCoding","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSSecureCoding","kind":"identifier"}],"url":"/documentation/foundation/nssecurecoding"},"doc://com.externally.resolved.symbol/s:SH":{"type":"topic","url":"/documentation/Swift/Hashable","kind":"symbol","title":"Hashable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"Equatable","preciseIdentifier":"s:SQ"}],"role":"symbol","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"identifier":"doc://com.externally.resolved.symbol/s:SH"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","kind":"technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","title":"Technologies","url":"/documentation/technologies"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"url":"/documentation/Swift/CVarArg","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"title":"CVarArg","identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"kind":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"role":"symbol","url":"/documentation/Swift/CustomStringConvertible","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","type":"topic","abstract":[{"type":"text","text":"A type with a customized textual representation."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"title":"CustomStringConvertible"},"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/enable-9xte9":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enable","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"enable","type":"topic","url":"/documentation/intents/insetdefrostersettingsincarintent/enable-9xte9","identifier":"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/enable-9xte9","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A Boolean indicating whether to enable or disable the defroster."}],"deprecated":true},"doc://com.apple.sirikit/documentation/Intents/INIntent":{"abstract":[{"text":"A request to fulfill in your app or Intents extension.","type":"text"}],"url":"/documentation/intents/inintent","type":"topic","kind":"symbol","title":"INIntent","identifier":"doc://com.apple.sirikit/documentation/Intents/INIntent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"INIntent","kind":"identifier"}],"navigatorTitle":[{"text":"INIntent","kind":"identifier"}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A protocol that enables an object to be encoded and decoded for archiving and distribution."}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","type":"topic","title":"NSCoding","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCoding"}],"url":"/documentation/foundation/nscoding"},"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/defroster":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defroster"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"INCarDefroster","preciseIdentifier":"c:@E@INCarDefroster"}],"title":"defroster","type":"topic","url":"/documentation/intents/insetdefrostersettingsincarintent/defroster","identifier":"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/defroster","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The defroster to enable or disable."}],"navigatorTitle":[{"kind":"identifier","text":"defroster"}],"deprecated":true},"doc://com.apple.sirikit/documentation/Intents/INIntentSetImageKeyPath":{"navigatorTitle":[{"kind":"identifier","text":"INIntentSetImageKeyPath"}],"url":"/documentation/intents/inintentsetimagekeypath","role":"symbol","kind":"symbol","abstract":[],"type":"topic","title":"INIntentSetImageKeyPath","identifier":"doc://com.apple.sirikit/documentation/Intents/INIntentSetImageKeyPath","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"INIntentSetImageKeyPath"}]},"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/initWithEnable:defroster:":{"role":"symbol","abstract":[{"text":"Initializes the intent object with the specified defroster information.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithEnable:defroster:"}],"url":"/documentation/intents/insetdefrostersettingsincarintent/initwithenable:defroster:","identifier":"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/initWithEnable:defroster:","type":"topic","title":"initWithEnable:defroster:","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEnable:defroster:"}],"deprecated":true},"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/carName":{"role":"symbol","title":"carName","identifier":"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/carName","url":"/documentation/intents/insetdefrostersettingsincarintent/carname","abstract":[{"type":"text","text":"The name of the car you applied the settings to."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"carName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)INSpeakableString","text":"INSpeakableString"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"carName"}],"kind":"symbol","type":"topic","deprecated":true},"https://developer.apple.com/support/deprecated-sirikit-intent-domains":{"titleInlineContent":[{"text":"Deprecated SiriKit Intent Domains","type":"text"}],"url":"https://developer.apple.com/support/deprecated-sirikit-intent-domains","identifier":"https://developer.apple.com/support/deprecated-sirikit-intent-domains","type":"link","title":"Deprecated SiriKit Intent Domains"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"type":"topic","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"fragments":[{"text":"protocol ","kind":"text"},{"kind":"identifier","text":"NSCopying"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","role":"symbol","url":"/documentation/foundation/nscopying","title":"NSCopying"},"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent":{"abstract":[{"text":"A request to change the defroster settings in a CarPlay-enabled vehicle.","type":"text"}],"type":"topic","identifier":"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"INSetDefrosterSettingsInCarIntent"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INSetDefrosterSettingsInCarIntent"}],"role":"symbol","deprecated":true,"url":"/documentation/intents/insetdefrostersettingsincarintent","title":"INSetDefrosterSettingsInCarIntent"},"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/init(enable:defroster:carName:)":{"url":"/documentation/intents/insetdefrostersettingsincarintent/init(enable:defroster:carname:)","title":"init(enable:defroster:carName:)","role":"symbol","fragments":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"enable"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"defroster","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"INCarDefroster","preciseIdentifier":"c:@E@INCarDefroster","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"carName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"INSpeakableString","preciseIdentifier":"c:objc(cs)INSpeakableString"},{"kind":"text","text":"?)"}],"kind":"symbol","deprecated":true,"identifier":"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/init(enable:defroster:carName:)","abstract":[{"type":"text","text":"Initializes the intent object with the specified defroster information."}],"type":"topic"},"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/enable-8tf0i":{"fragments":[{"text":"enable","kind":"identifier"}],"title":"enable","type":"topic","url":"/documentation/intents/insetdefrostersettingsincarintent/enable-8tf0i","identifier":"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/enable-8tf0i","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A Boolean indicating whether to enable or disable the defroster."}],"deprecated":true},"doc://com.apple.sirikit/documentation/Intents":{"role":"collection","identifier":"doc://com.apple.sirikit/documentation/Intents","url":"/documentation/intents","type":"topic","title":"Intents","abstract":[{"type":"text","text":"Empower people to customize interactions for your app on their device."}],"kind":"symbol"},"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/initWithEnable:defroster:carName:":{"role":"symbol","abstract":[{"text":"Initializes the intent object with the specified defroster information.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithEnable:defroster:carName:"}],"url":"/documentation/intents/insetdefrostersettingsincarintent/initwithenable:defroster:carname:","identifier":"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/initWithEnable:defroster:carName:","type":"topic","title":"initWithEnable:defroster:carName:","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEnable:defroster:carName:"}],"deprecated":true},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","url":"/documentation/Swift/CustomDebugStringConvertible","title":"CustomDebugStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDebugStringConvertible"}],"abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentResponse":{"role":"symbol","abstract":[{"text":"Your app’s response to a set defroster settings in car intent.","type":"text"}],"type":"topic","deprecated":true,"identifier":"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentResponse","url":"/documentation/intents/insetdefrostersettingsincarintentresponse","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"INSetDefrosterSettingsInCarIntentResponse","kind":"identifier"}],"navigatorTitle":[{"text":"INSetDefrosterSettingsInCarIntentResponse","kind":"identifier"}],"title":"INSetDefrosterSettingsInCarIntentResponse"},"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling":{"role":"symbol","abstract":[{"text":"The handler interface for changing a vehicle’s defroster settings.","type":"text"}],"type":"topic","deprecated":true,"identifier":"doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling","url":"/documentation/intents/insetdefrostersettingsincarintenthandling","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"INSetDefrosterSettingsInCarIntentHandling"}],"navigatorTitle":[{"text":"INSetDefrosterSettingsInCarIntentHandling","kind":"identifier"}],"title":"INSetDefrosterSettingsInCarIntentHandling"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"introducedAt":"10.0","beta":false,"name":"iOS","deprecatedAt":"15.0","deprecated":false,"unavailable":false},{"unavailable":false,"deprecatedAt":"15.0","deprecated":false,"introducedAt":"10.0","name":"iPadOS","beta":false},{"unavailable":false,"deprecatedAt":"15.0","deprecated":false,"introducedAt":"13.1","name":"Mac Catalyst","beta":false},{"unavailable":false,"deprecatedAt":"1.0","deprecated":false,"introducedAt":"1.0","name":"visionOS","beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Class"},{"op":"replace","path":"/metadata/title","value":"INSetDefrosterSettingsInCarIntent"},{"op":"replace","value":"class","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"INSetDefrosterSettingsInCarIntent","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"INSetDefrosterSettingsInCarIntent"}],"path":"/metadata/navigatorTitle"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.sirikit/documentation/Intents"]]},"path":"/hierarchy"},{"op":"replace","value":[{"title":"Initializing the Intent Object","anchor":"Initializing-the-Intent-Object","identifiers":["doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/initWithEnable:defroster:carName:","doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/initWithEnable:defroster:"]},{"title":"Getting Details About the Defroster Settings to Set","anchor":"Getting-Details-About-the-Defroster-Settings-to-Set","identifiers":["doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/enable-8tf0i","doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/defroster"]},{"title":"Getting the Car Name","anchor":"Getting-the-Car-Name","identifiers":["doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntent/carName"]}],"path":"/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc://com.apple.sirikit/documentation/Intents/INIntent"],"kind":"relationships"}],"path":"/relationshipsSections"},{"value":[{"anchor":"CarPlay-Defroster-Settings","generated":true,"title":"CarPlay Defroster Settings","identifiers":["doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentHandling","doc://com.apple.sirikit/documentation/Intents/INSetDefrosterSettingsInCarIntentResponse"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"INSetDefrosterSettingsInCarIntent"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)INIntent","kind":"typeIdentifier","text":"INIntent","identifier":"doc://com.apple.sirikit/documentation/Intents/INIntent"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/deprecationSummary","op":"replace","value":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This intent is no longer available. You may define a custom intent instead. For more information, see "},{"type":"reference","isActive":true,"identifier":"https://developer.apple.com/support/deprecated-sirikit-intent-domains"},{"type":"text","text":"."}]}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","op":"replace","value":"NSObject"},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntent/title","op":"replace","value":"INIntent"},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntent/fragments","op":"replace","value":[{"text":"INIntent","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntent/navigatorTitle","op":"replace","value":[{"text":"INIntent","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent~1defroster/title","op":"replace","value":"defroster"},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent~1defroster/fragments","op":"replace","value":[{"text":"defroster","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent~1carName/title","op":"replace","value":"carName"},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent~1carName/fragments","op":"replace","value":[{"text":"carName","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent/title","op":"replace","value":"INSetDefrosterSettingsInCarIntent"},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent/fragments","op":"replace","value":[{"text":"INSetDefrosterSettingsInCarIntent","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntent/navigatorTitle","op":"replace","value":[{"text":"INSetDefrosterSettingsInCarIntent","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentResponse/title","op":"replace","value":"INSetDefrosterSettingsInCarIntentResponse"},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentResponse/fragments","op":"replace","value":[{"kind":"identifier","text":"INSetDefrosterSettingsInCarIntentResponse"}]},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentResponse/navigatorTitle","op":"replace","value":[{"text":"INSetDefrosterSettingsInCarIntentResponse","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentHandling/title","op":"replace","value":"INSetDefrosterSettingsInCarIntentHandling"},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentHandling/fragments","op":"replace","value":[{"kind":"identifier","text":"INSetDefrosterSettingsInCarIntentHandling"}]},{"path":"/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetDefrosterSettingsInCarIntentHandling/navigatorTitle","op":"replace","value":[{"text":"INSetDefrosterSettingsInCarIntentHandling","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}