{
  "abstract": [
    {
      "text": "The handler interface for sending ride feedback to your service.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INSendRideFeedbackIntentHandling",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INSendRideFeedbackIntentHandling"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INSendRideFeedbackIntentHandling"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "INSendRideFeedbackIntentHandling"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntentHandling"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the methods of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol to confirm and handle requests to send feedback about a ride to your service. Adopt this protocol in an object of your Intents extension that is capable of conveying the feedback to your service.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To initiate the delivery of an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the user must have previously completed a ride in Maps or Siri and asked the user to provide feedback. Specifically, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideCompletionStatus",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that you created must indicate that it requires feedback before beginning a new ride. (Maps also gives the user a chance to provide feedback proactively). After the user provides feedback, Siri delivers the feedback intent to your Intents extension.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRideCompletionStatus": {
      "abstract": [
        {
          "text": "Additional details about whether a ride completed successfully or someone canceled the ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRideCompletionStatus"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRideCompletionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRideCompletionStatus"
        }
      ],
      "role": "symbol",
      "title": "INRideCompletionStatus",
      "type": "topic",
      "url": "/documentation/intents/inridecompletionstatus"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRidesharingDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the ride-booking domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRidesharingDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRidesharingDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRidesharingDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INRidesharingDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inridesharingdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntent": {
      "abstract": [
        {
          "text": "An intent indicating that the user provided feedback for a completed ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSendRideFeedbackIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendRideFeedbackIntent"
        }
      ],
      "role": "symbol",
      "title": "INSendRideFeedbackIntent",
      "type": "topic",
      "url": "/documentation/intents/insendridefeedbackintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for sending ride feedback to your service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSendRideFeedbackIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendRideFeedbackIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSendRideFeedbackIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insendridefeedbackintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling/confirm(sendRideFeedback:completion:)": {
      "abstract": [
        {
          "text": "Confirms that you can apply the feedback to the specified ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirm"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "sendRideFeedback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSendRideFeedbackIntent",
          "text": "INSendRideFeedbackIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSendRideFeedbackIntentResponse",
          "text": "INSendRideFeedbackIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling/confirm(sendRideFeedback:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "confirmSendRideFeedback:completion:"
        }
      ],
      "role": "symbol",
      "title": "confirm(sendRideFeedback:completion:)",
      "type": "topic",
      "url": "/documentation/intents/insendridefeedbackintenthandling/confirm(sendridefeedback:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling/handle(sendRideFeedback:completion:)": {
      "abstract": [
        {
          "text": "Handles the recording of feedback for the specified ride.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "sendRideFeedback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSendRideFeedbackIntent",
          "text": "INSendRideFeedbackIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSendRideFeedbackIntentResponse",
          "text": "INSendRideFeedbackIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling/handle(sendRideFeedback:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleSendRideFeedback:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handle(sendRideFeedback:completion:)",
      "type": "topic",
      "url": "/documentation/intents/insendridefeedbackintenthandling/handle(sendridefeedback:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a send ride feedback intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSendRideFeedbackIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendRideFeedbackIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INSendRideFeedbackIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/insendridefeedbackintentresponse"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INRidesharingDomainHandling"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Send-Ride-Feedback",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntent",
        "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponse"
      ],
      "title": "Send Ride Feedback"
    }
  ],
  "topicSections": [
    {
      "anchor": "Confirming-the-Intent",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling/confirm(sendRideFeedback:completion:)"
      ],
      "title": "Confirming the Intent"
    },
    {
      "anchor": "Handling-the-Intent",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling/handle(sendRideFeedback:completion:)"
      ],
      "title": "Handling the Intent"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INSendRideFeedbackIntentHandling"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Confirming-the-Intent",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling/confirm(sendRideFeedback:completion:)"
              ],
              "title": "Confirming the Intent"
            },
            {
              "anchor": "Handling-the-Intent",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentHandling/handle(sendRideFeedback:completion:)"
              ],
              "title": "Handling the Intent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INRidesharingDomainHandling"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Send-Ride-Feedback",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntent",
                "doc://com.apple.sirikit/documentation/Intents/INSendRideFeedbackIntentResponse"
              ],
              "title": "Send Ride Feedback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INSendRideFeedbackIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntent/title",
          "value": "INSendRideFeedbackIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentHandling~1confirm(sendRideFeedback:completion:)/title",
          "value": "confirmSendRideFeedback:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentHandling~1confirm(sendRideFeedback:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "confirmSendRideFeedback:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentHandling/title",
          "value": "INSendRideFeedbackIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRidesharingDomainHandling/title",
          "value": "INRidesharingDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRidesharingDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRidesharingDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRidesharingDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRidesharingDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentHandling~1handle(sendRideFeedback:completion:)/title",
          "value": "handleSendRideFeedback:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentHandling~1handle(sendRideFeedback:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleSendRideFeedback:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideCompletionStatus/title",
          "value": "INRideCompletionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideCompletionStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRideCompletionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRideCompletionStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRideCompletionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentResponse/title",
          "value": "INSendRideFeedbackIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendRideFeedbackIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendRideFeedbackIntentResponse"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insendridefeedbackintenthandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insendridefeedbackintenthandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
