{
  "abstract": [
    {
      "text": "Constants indicating the state of the response.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INSearchForAccountsIntentResponseCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INSearchForAccountsIntentResponseCode"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INSearchForAccountsIntentResponseCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INSearchForAccountsIntentResponseCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INSearchForAccountsIntentResponseCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponse/code": {
      "abstract": [
        {
          "text": "The code indicating whether you successfully handled the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INSearchForAccountsIntentResponseCode",
          "text": "INSearchForAccountsIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponse/code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "code"
        }
      ],
      "role": "symbol",
      "title": "code",
      "type": "topic",
      "url": "/documentation/intents/insearchforaccountsintentresponse/code"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode": {
      "abstract": [
        {
          "text": "Constants indicating the state of the response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchForAccountsIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForAccountsIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INSearchForAccountsIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/insearchforaccountsintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "You were unable to retrieve the search results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForAccountsIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INSearchForAccountsIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/insearchforaccountsintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureAccountNotFound": {
      "abstract": [
        {
          "text": "The search yielded no results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureAccountNotFound"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureAccountNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForAccountsIntentResponseCodeFailureAccountNotFound"
        }
      ],
      "role": "symbol",
      "title": "INSearchForAccountsIntentResponseCode.failureAccountNotFound",
      "type": "topic",
      "url": "/documentation/intents/insearchforaccountsintentresponsecode/failureaccountnotfound"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureCredentialsUnverified": {
      "abstract": [
        {
          "text": "You were unable to perform the search because you could not verify the user’s credentials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureCredentialsUnverified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureCredentialsUnverified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForAccountsIntentResponseCodeFailureCredentialsUnverified"
        }
      ],
      "role": "symbol",
      "title": "INSearchForAccountsIntentResponseCode.failureCredentialsUnverified",
      "type": "topic",
      "url": "/documentation/intents/insearchforaccountsintentresponsecode/failurecredentialsunverified"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureNotEligible": {
      "abstract": [
        {
          "text": "The request failed because a user was not eligible to perform the transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureNotEligible"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureNotEligible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForAccountsIntentResponseCodeFailureNotEligible"
        }
      ],
      "role": "symbol",
      "title": "INSearchForAccountsIntentResponseCode.failureNotEligible",
      "type": "topic",
      "url": "/documentation/intents/insearchforaccountsintentresponsecode/failurenoteligible"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "The user must launch your app to perform the search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForAccountsIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INSearchForAccountsIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/insearchforaccountsintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureTermsAndConditionsAcceptanceRequired": {
      "abstract": [
        {
          "text": "The search failed as the user must accept the terms and conditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureTermsAndConditionsAcceptanceRequired"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureTermsAndConditionsAcceptanceRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForAccountsIntentResponseCodeFailureTermsAndConditionsAcceptanceRequired"
        }
      ],
      "role": "symbol",
      "title": "INSearchForAccountsIntentResponseCode.failureTermsAndConditionsAcceptanceRequired",
      "type": "topic",
      "url": "/documentation/intents/insearchforaccountsintentresponsecode/failuretermsandconditionsacceptancerequired"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/inProgress": {
      "abstract": [
        {
          "text": "The search is still in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProgress"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/inProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForAccountsIntentResponseCodeInProgress"
        }
      ],
      "role": "symbol",
      "title": "INSearchForAccountsIntentResponseCode.inProgress",
      "type": "topic",
      "url": "/documentation/intents/insearchforaccountsintentresponsecode/inprogress"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/insearchforaccountsintentresponsecode/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "You are ready to handle the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForAccountsIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INSearchForAccountsIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/insearchforaccountsintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/success": {
      "abstract": [
        {
          "text": "You successfully retrieved the search results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForAccountsIntentResponseCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "INSearchForAccountsIntentResponseCode.success",
      "type": "topic",
      "url": "/documentation/intents/insearchforaccountsintentresponsecode/success"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "The response didn’t specify a response code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForAccountsIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INSearchForAccountsIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/insearchforaccountsintentresponsecode/unspecified"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Response-Code",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponse/code"
      ],
      "title": "Getting the Response Code"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/unspecified",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/inProgress",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/success",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureNotEligible",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureRequiringAppLaunch",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureCredentialsUnverified",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureAccountNotFound",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureTermsAndConditionsAcceptanceRequired"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INSearchForAccountsIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForAccountsIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForAccountsIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/unspecified",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/inProgress",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/success",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureNotEligible",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureRequiringAppLaunch",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureCredentialsUnverified",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureAccountNotFound",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponseCode/failureTermsAndConditionsAcceptanceRequired"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Response-Code",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSearchForAccountsIntentResponse/code"
              ],
              "title": "Getting the Response Code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INSearchForAccountsIntentResponseCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1failureAccountNotFound/title",
          "value": "INSearchForAccountsIntentResponseCodeFailureAccountNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1failureAccountNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForAccountsIntentResponseCodeFailureAccountNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1failure/title",
          "value": "INSearchForAccountsIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForAccountsIntentResponseCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INSearchForAccountsIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForAccountsIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponse~1code/title",
          "value": "code"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponse~1code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1inProgress/title",
          "value": "INSearchForAccountsIntentResponseCodeInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1inProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForAccountsIntentResponseCodeInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1failureTermsAndConditionsAcceptanceRequired/title",
          "value": "INSearchForAccountsIntentResponseCodeFailureTermsAndConditionsAcceptanceRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1failureTermsAndConditionsAcceptanceRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForAccountsIntentResponseCodeFailureTermsAndConditionsAcceptanceRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode/title",
          "value": "INSearchForAccountsIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForAccountsIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForAccountsIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1unspecified/title",
          "value": "INSearchForAccountsIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForAccountsIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1ready/title",
          "value": "INSearchForAccountsIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForAccountsIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1failureCredentialsUnverified/title",
          "value": "INSearchForAccountsIntentResponseCodeFailureCredentialsUnverified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1failureCredentialsUnverified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForAccountsIntentResponseCodeFailureCredentialsUnverified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1failureNotEligible/title",
          "value": "INSearchForAccountsIntentResponseCodeFailureNotEligible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1failureNotEligible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForAccountsIntentResponseCodeFailureNotEligible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1success/title",
          "value": "INSearchForAccountsIntentResponseCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForAccountsIntentResponseCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForAccountsIntentResponseCodeSuccess"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insearchforaccountsintentresponsecode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insearchforaccountsintentresponsecode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
