{
  "abstract": [
    {
      "text": "The handler interface for changing a vehicle’s climate control settings.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INSetClimateSettingsInCarIntentHandling",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INSetClimateSettingsInCarIntentHandling"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INSetClimateSettingsInCarIntentHandling"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INSetClimateSettingsInCarIntentHandling is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INSetClimateSettingsInCarIntentHandling is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INSetClimateSettingsInCarIntentHandling is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INSetClimateSettingsInCarIntentHandling is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "INSetClimateSettingsInCarIntentHandling"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INSetClimateSettingsInCarIntentHandling"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Automotive vendors can support the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol in an Intents extension that they ship with their automotive apps. Use the methods of this protocol to resolve, confirm, and handle requests to change the vehicle’s current climate control settings. Your extension should be able to communicate with the vehicle and make the necessary changes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Siri delivers an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to your handler when the user asks to change any climate settings. The provided intent object contains information that you use to determine which settings changed and what the new settings should be.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the CarPlay domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCarPlayDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCarPlayDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INCarPlayDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/incarplaydomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent": {
      "abstract": [
        {
          "text": "A request to change the climate settings in a CarPlay-enabled vehicle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetClimateSettingsInCarIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetClimateSettingsInCarIntent"
        }
      ],
      "role": "symbol",
      "title": "INSetClimateSettingsInCarIntent",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for changing a vehicle’s climate control settings.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetClimateSettingsInCarIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetClimateSettingsInCarIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSetClimateSettingsInCarIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/confirm(intent:completion:)": {
      "abstract": [
        {
          "text": "Confirms whether you can change the climate settings.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirm"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetClimateSettingsInCarIntent",
          "text": "INSetClimateSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetClimateSettingsInCarIntentResponse",
          "text": "INSetClimateSettingsInCarIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/confirm(intent:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "confirmSetClimateSettingsInCar:completion:"
        }
      ],
      "role": "symbol",
      "title": "confirm(intent:completion:)",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintenthandling/confirm(intent:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/handle(intent:completion:)": {
      "abstract": [
        {
          "text": "Handles changing the climate control settings.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetClimateSettingsInCarIntent",
          "text": "INSetClimateSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetClimateSettingsInCarIntentResponse",
          "text": "INSetClimateSettingsInCarIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/handle(intent:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleSetClimateSettingsInCar:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handle(intent:completion:)",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintenthandling/handle(intent:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveAirCirculationMode(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the requested air circulation mode.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveAirCirculationMode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetClimateSettingsInCarIntent",
          "text": "INSetClimateSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCarAirCirculationModeResolutionResult",
          "text": "INCarAirCirculationModeResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveAirCirculationMode(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveAirCirculationModeForSetClimateSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveAirCirculationMode(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintenthandling/resolveaircirculationmode(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveCarName(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the car name.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveCarName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetClimateSettingsInCarIntent",
          "text": "INSetClimateSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSpeakableStringResolutionResult",
          "text": "INSpeakableStringResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveCarName(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveCarNameForSetClimateSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveCarName(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintenthandling/resolvecarname(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveClimateZone(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the requested climate zone.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveClimateZone"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetClimateSettingsInCarIntent",
          "text": "INSetClimateSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCarSeatResolutionResult",
          "text": "INCarSeatResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveClimateZone(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveClimateZoneForSetClimateSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveClimateZone(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintenthandling/resolveclimatezone(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveEnableAirConditioner(for:with:)": {
      "abstract": [
        {
          "text": "Resolves whether you can enable the air conditioner.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveEnableAirConditioner"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetClimateSettingsInCarIntent",
          "text": "INSetClimateSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBooleanResolutionResult",
          "text": "INBooleanResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveEnableAirConditioner(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveEnableAirConditionerForSetClimateSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveEnableAirConditioner(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintenthandling/resolveenableairconditioner(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveEnableAutoMode(for:with:)": {
      "abstract": [
        {
          "text": "Resolves whether you can enable automatic mode for the car’s climate control.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveEnableAutoMode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetClimateSettingsInCarIntent",
          "text": "INSetClimateSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBooleanResolutionResult",
          "text": "INBooleanResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveEnableAutoMode(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveEnableAutoModeForSetClimateSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveEnableAutoMode(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintenthandling/resolveenableautomode(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveEnableClimateControl(for:with:)": {
      "abstract": [
        {
          "text": "Resolves whether you can enable the climate control system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveEnableClimateControl"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetClimateSettingsInCarIntent",
          "text": "INSetClimateSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBooleanResolutionResult",
          "text": "INBooleanResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveEnableClimateControl(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveEnableClimateControlForSetClimateSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveEnableClimateControl(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintenthandling/resolveenableclimatecontrol(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveEnableFan(for:with:)": {
      "abstract": [
        {
          "text": "Resolves whether you can enable the car’s fan.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveEnableFan"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetClimateSettingsInCarIntent",
          "text": "INSetClimateSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INBooleanResolutionResult",
          "text": "INBooleanResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveEnableFan(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveEnableFanForSetClimateSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveEnableFan(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintenthandling/resolveenablefan(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveFanSpeedIndex(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the requested fan speed index.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveFanSpeedIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetClimateSettingsInCarIntent",
          "text": "INSetClimateSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INIntegerResolutionResult",
          "text": "INIntegerResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveFanSpeedIndex(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveFanSpeedIndexForSetClimateSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveFanSpeedIndex(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintenthandling/resolvefanspeedindex(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveFanSpeedPercentage(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the requested fan speed percentage.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveFanSpeedPercentage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetClimateSettingsInCarIntent",
          "text": "INSetClimateSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INDoubleResolutionResult",
          "text": "INDoubleResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveFanSpeedPercentage(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveFanSpeedPercentageForSetClimateSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveFanSpeedPercentage(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintenthandling/resolvefanspeedpercentage(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveRelativeFanSpeedSetting(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the requested relative qualifier for the fan speed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveRelativeFanSpeedSetting"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetClimateSettingsInCarIntent",
          "text": "INSetClimateSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INRelativeSettingResolutionResult",
          "text": "INRelativeSettingResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveRelativeFanSpeedSetting(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveRelativeFanSpeedSettingForSetClimateSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveRelativeFanSpeedSetting(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintenthandling/resolverelativefanspeedsetting(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveRelativeTemperatureSetting(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the requested relative qualifier for the temperature change.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveRelativeTemperatureSetting"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetClimateSettingsInCarIntent",
          "text": "INSetClimateSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INRelativeSettingResolutionResult",
          "text": "INRelativeSettingResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveRelativeTemperatureSetting(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveRelativeTemperatureSettingForSetClimateSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveRelativeTemperatureSetting(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintenthandling/resolverelativetemperaturesetting(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveTemperature(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the requested temperature value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveTemperature"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSetClimateSettingsInCarIntent",
          "text": "INSetClimateSettingsInCarIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTemperatureResolutionResult",
          "text": "INTemperatureResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveTemperature(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveTemperatureForSetClimateSettingsInCar:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveTemperature(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintenthandling/resolvetemperature(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a set climate settings in car intent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSetClimateSettingsInCarIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSetClimateSettingsInCarIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INSetClimateSettingsInCarIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/insetclimatesettingsincarintentresponse"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "CarPlay-Climate-Settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent",
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentResponse"
      ],
      "title": "CarPlay Climate Settings"
    }
  ],
  "topicSections": [
    {
      "anchor": "Resolving-the-Intent-Parameters",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveEnableFan(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveEnableAirConditioner(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveEnableClimateControl(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveEnableAutoMode(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveAirCirculationMode(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveFanSpeedIndex(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveFanSpeedPercentage(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveRelativeFanSpeedSetting(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveTemperature(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveRelativeTemperatureSetting(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveClimateZone(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveCarName(for:with:)"
      ],
      "title": "Resolving the Intent Parameters"
    },
    {
      "anchor": "Confirming-the-Response",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/confirm(intent:completion:)"
      ],
      "title": "Confirming the Response"
    },
    {
      "anchor": "Handling-the-Intent",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/handle(intent:completion:)"
      ],
      "title": "Handling the Intent"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INSetClimateSettingsInCarIntentHandling"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetClimateSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetClimateSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Resolving-the-Intent-Parameters",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveEnableFan(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveEnableAirConditioner(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveEnableClimateControl(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveEnableAutoMode(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveAirCirculationMode(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveFanSpeedIndex(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveFanSpeedPercentage(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveRelativeFanSpeedSetting(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveTemperature(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveRelativeTemperatureSetting(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveClimateZone(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/resolveCarName(for:with:)"
              ],
              "title": "Resolving the Intent Parameters"
            },
            {
              "anchor": "Confirming-the-Response",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/confirm(intent:completion:)"
              ],
              "title": "Confirming the Response"
            },
            {
              "anchor": "Handling-the-Intent",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentHandling/handle(intent:completion:)"
              ],
              "title": "Handling the Intent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INCarPlayDomainHandling"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "CarPlay-Climate-Settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntent",
                "doc://com.apple.sirikit/documentation/Intents/INSetClimateSettingsInCarIntentResponse"
              ],
              "title": "CarPlay Climate Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INSetClimateSettingsInCarIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveEnableAutoMode(for:with:)/title",
          "value": "resolveEnableAutoModeForSetClimateSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveEnableAutoMode(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveEnableAutoModeForSetClimateSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveEnableFan(for:with:)/title",
          "value": "resolveEnableFanForSetClimateSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveEnableFan(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveEnableFanForSetClimateSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveClimateZone(for:with:)/title",
          "value": "resolveClimateZoneForSetClimateSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveClimateZone(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveClimateZoneForSetClimateSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveEnableClimateControl(for:with:)/title",
          "value": "resolveEnableClimateControlForSetClimateSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveEnableClimateControl(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveEnableClimateControlForSetClimateSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveTemperature(for:with:)/title",
          "value": "resolveTemperatureForSetClimateSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveTemperature(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveTemperatureForSetClimateSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentResponse/title",
          "value": "INSetClimateSettingsInCarIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetClimateSettingsInCarIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetClimateSettingsInCarIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntent/title",
          "value": "INSetClimateSettingsInCarIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetClimateSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetClimateSettingsInCarIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1confirm(intent:completion:)/title",
          "value": "confirmSetClimateSettingsInCar:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1confirm(intent:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "confirmSetClimateSettingsInCar:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarPlayDomainHandling/title",
          "value": "INCarPlayDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarPlayDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarPlayDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCarPlayDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCarPlayDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveAirCirculationMode(for:with:)/title",
          "value": "resolveAirCirculationModeForSetClimateSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveAirCirculationMode(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveAirCirculationModeForSetClimateSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveFanSpeedPercentage(for:with:)/title",
          "value": "resolveFanSpeedPercentageForSetClimateSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveFanSpeedPercentage(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveFanSpeedPercentageForSetClimateSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveRelativeFanSpeedSetting(for:with:)/title",
          "value": "resolveRelativeFanSpeedSettingForSetClimateSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveRelativeFanSpeedSetting(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveRelativeFanSpeedSettingForSetClimateSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveFanSpeedIndex(for:with:)/title",
          "value": "resolveFanSpeedIndexForSetClimateSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveFanSpeedIndex(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveFanSpeedIndexForSetClimateSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveRelativeTemperatureSetting(for:with:)/title",
          "value": "resolveRelativeTemperatureSettingForSetClimateSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveRelativeTemperatureSetting(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveRelativeTemperatureSettingForSetClimateSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling/title",
          "value": "INSetClimateSettingsInCarIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetClimateSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSetClimateSettingsInCarIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1handle(intent:completion:)/title",
          "value": "handleSetClimateSettingsInCar:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1handle(intent:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleSetClimateSettingsInCar:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveCarName(for:with:)/title",
          "value": "resolveCarNameForSetClimateSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveCarName(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveCarNameForSetClimateSettingsInCar:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveEnableAirConditioner(for:with:)/title",
          "value": "resolveEnableAirConditionerForSetClimateSettingsInCar:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSetClimateSettingsInCarIntentHandling~1resolveEnableAirConditioner(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveEnableAirConditionerForSetClimateSettingsInCar:withCompletion:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insetclimatesettingsincarintenthandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insetclimatesettingsincarintenthandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
