{
  "abstract": [
    {
      "text": "A resolution result for the recipient of a payment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INSendPaymentPayeeResolutionResult",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INSendPaymentPayeeResolutionResult"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INSendPaymentPayeeResolutionResult"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "INSendPaymentPayeeResolutionResult"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INSendPaymentPayeeResolutionResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object is what you return when resolving parameters containing an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INPerson",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. Use the creation method that best reflects your ability to resolve the parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For additional resolution options, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonResolutionResult",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INAccountTypeResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for account types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INAccountTypeResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INAccountTypeResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INAccountTypeResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INAccountTypeResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inaccounttyperesolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBalanceTypeResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for balance types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INBalanceTypeResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBalanceTypeResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBalanceTypeResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INBalanceTypeResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inbalancetyperesolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCurrencyAmountResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a currency amount associated with an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCurrencyAmountResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCurrencyAmountResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCurrencyAmountResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INCurrencyAmountResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/incurrencyamountresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a parameter of an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INIntentResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inintentresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentAccountResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the user account that provides the funds to pay a bill.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPaymentAccountResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentAccountResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentAccountResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INPaymentAccountResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inpaymentaccountresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentAmountResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the amount to pay for a bill.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPaymentAmountResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentAmountResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentAmountResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INPaymentAmountResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inpaymentamountresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodResolutionResult": {
      "abstract": [
        {
          "text": "Describes the result of resolving a payment method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPaymentMethodResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentMethodResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INPaymentMethodResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inpaymentmethodresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentStatusResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the payment status of a bill during a search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPaymentStatusResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentStatusResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentStatusResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INPaymentStatusResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inpaymentstatusresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPerson": {
      "abstract": [
        {
          "text": "Information about a person participating in a SiriKit interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPerson"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPerson",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPerson"
        }
      ],
      "role": "symbol",
      "title": "INPerson",
      "type": "topic",
      "url": "/documentation/intents/inperson"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPersonResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for a user as a parameter of an intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPersonResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPersonResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INPersonResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inpersonresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the currency amount associated with a payment request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRequestPaymentCurrencyAmountResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestPaymentCurrencyAmountResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INRequestPaymentCurrencyAmountResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inrequestpaymentcurrencyamountresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentPayerResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the person making the payment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRequestPaymentPayerResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentPayerResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRequestPaymentPayerResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INRequestPaymentPayerResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inrequestpaymentpayerresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentCurrencyAmountResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the currency amount to send to another user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSendPaymentCurrencyAmountResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentCurrencyAmountResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentCurrencyAmountResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentCurrencyAmountResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentcurrencyamountresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the recipient of a payment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSendPaymentPayeeResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentPayeeResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentPayeeResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentpayeeresolutionresult"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult/init(personResolutionResult:)": {
      "abstract": [
        {
          "text": "Creates a resolution result object with the specified person resolution result object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "personResolutionResult"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPersonResolutionResult",
          "text": "INPersonResolutionResult"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult/init(personResolutionResult:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPersonResolutionResult:"
        }
      ],
      "role": "symbol",
      "title": "init(personResolutionResult:)",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentpayeeresolutionresult/init(personresolutionresult:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult/unsupported(forReason:)": {
      "abstract": [
        {
          "text": "Creates an object whose resolution indicates that the specified value is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INSendPaymentPayeeUnsupportedReason",
          "text": "INSendPaymentPayeeUnsupportedReason"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult/unsupported(forReason:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unsupportedForReason:"
        }
      ],
      "role": "symbol",
      "title": "unsupported(forReason:)",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentpayeeresolutionresult/unsupported(forreason:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason": {
      "abstract": [
        {
          "text": "Constants indicating the reason for being unable to resolve the payee.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSendPaymentPayeeUnsupportedReason"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentPayeeUnsupportedReason"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentPayeeUnsupportedReason",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentpayeeunsupportedreason"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPersonResolutionResult"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Resolution-Results",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INAccountTypeResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INBalanceTypeResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INCurrencyAmountResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentAccountResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentAmountResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INPaymentStatusResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentPayerResolutionResult",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentCurrencyAmountResolutionResult"
      ],
      "title": "Resolution Results"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Resolution-Result-Object",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult/unsupported(forReason:)",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult/init(personResolutionResult:)"
      ],
      "title": "Creating a Resolution Result Object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INSendPaymentPayeeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentPayeeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentPayeeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Resolution-Result-Object",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult/unsupported(forReason:)",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult/init(personResolutionResult:)"
              ],
              "title": "Creating a Resolution Result Object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPersonResolutionResult"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Resolution-Results",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INAccountTypeResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INBalanceTypeResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INCurrencyAmountResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentAccountResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentAmountResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentMethodResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INPaymentStatusResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentCurrencyAmountResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INRequestPaymentPayerResolutionResult",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentCurrencyAmountResolutionResult"
              ],
              "title": "Resolution Results"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INSendPaymentPayeeResolutionResult"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INPersonResolutionResult",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INPersonResolutionResult",
                    "text": "INPersonResolutionResult"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentStatusResolutionResult/title",
          "value": "INPaymentStatusResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentStatusResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentStatusResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentStatusResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentStatusResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPerson/title",
          "value": "INPerson"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPerson/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPerson/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonResolutionResult/title",
          "value": "INPersonResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPersonResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPersonResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeResolutionResult/title",
          "value": "INSendPaymentPayeeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentPayeeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentPayeeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCurrencyAmountResolutionResult/title",
          "value": "INCurrencyAmountResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCurrencyAmountResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCurrencyAmountResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCurrencyAmountResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCurrencyAmountResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/title",
          "value": "INIntentResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestPaymentCurrencyAmountResolutionResult/title",
          "value": "INRequestPaymentCurrencyAmountResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestPaymentCurrencyAmountResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestPaymentCurrencyAmountResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestPaymentCurrencyAmountResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestPaymentCurrencyAmountResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeResolutionResult~1init(personResolutionResult:)/title",
          "value": "initWithPersonResolutionResult:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeResolutionResult~1init(personResolutionResult:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPersonResolutionResult:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAccountTypeResolutionResult/title",
          "value": "INAccountTypeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAccountTypeResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INAccountTypeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INAccountTypeResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INAccountTypeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestPaymentPayerResolutionResult/title",
          "value": "INRequestPaymentPayerResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestPaymentPayerResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestPaymentPayerResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRequestPaymentPayerResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRequestPaymentPayerResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentAmountResolutionResult/title",
          "value": "INPaymentAmountResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentAmountResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentAmountResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentAmountResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentAmountResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentCurrencyAmountResolutionResult/title",
          "value": "INSendPaymentCurrencyAmountResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentCurrencyAmountResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentCurrencyAmountResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentCurrencyAmountResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentCurrencyAmountResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeUnsupportedReason/title",
          "value": "INSendPaymentPayeeUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeUnsupportedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentPayeeUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeUnsupportedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentPayeeUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentAccountResolutionResult/title",
          "value": "INPaymentAccountResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentAccountResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentAccountResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentAccountResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentAccountResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBalanceTypeResolutionResult/title",
          "value": "INBalanceTypeResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBalanceTypeResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBalanceTypeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBalanceTypeResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBalanceTypeResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodResolutionResult/title",
          "value": "INPaymentMethodResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentMethodResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentMethodResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentMethodResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeResolutionResult~1unsupported(forReason:)/title",
          "value": "unsupportedForReason:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeResolutionResult~1unsupported(forReason:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "unsupportedForReason:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insendpaymentpayeeresolutionresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insendpaymentpayeeresolutionresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
