{
  "abstract": [
    {
      "text": "Reasons the app can’t provide results for the search.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INSearchForMediaMediaItemUnsupportedReason",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INSearchForMediaMediaItemUnsupportedReason"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INSearchForMediaMediaItemUnsupportedReason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INSearchForMediaMediaItemUnsupportedReason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReason"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemResolutionResult/unsupported(forReason:)": {
      "abstract": [
        {
          "text": "Creates a result that requires the user to confirm the request because your app is unable to support the current request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INSearchForMediaMediaItemUnsupportedReason",
          "text": "INSearchForMediaMediaItemUnsupportedReason"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemResolutionResult/unsupported(forReason:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unsupportedForReason:"
        }
      ],
      "role": "symbol",
      "title": "unsupported(forReason:)",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemresolutionresult/unsupported(forreason:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason": {
      "abstract": [
        {
          "text": "Reasons the app can’t provide results for the search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReason"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReason"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/cellularDataSettings": {
      "abstract": [
        {
          "text": "The cellular data settings don’t allow the user to search for the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cellularDataSettings"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/cellularDataSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReasonCellularDataSettings"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason.cellularDataSettings",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason/cellulardatasettings"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/explicitContentSettings": {
      "abstract": [
        {
          "text": "The content settings don’t allow the user to search for the media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "explicitContentSettings"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/explicitContentSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReasonExplicitContentSettings"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason.explicitContentSettings",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason/explicitcontentsettings"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/loginRequired": {
      "abstract": [
        {
          "text": "The user must log in to the app in order to search for media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loginRequired"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/loginRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReasonLoginRequired"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason.loginRequired",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason/loginrequired"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/regionRestriction": {
      "abstract": [
        {
          "text": "There are media items that match this request, but they aren’t available in the user’s geographic location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regionRestriction"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/regionRestriction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReasonRegionRestriction"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason.regionRestriction",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason/regionrestriction"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/restrictedContent": {
      "abstract": [
        {
          "text": "The media item is restricted content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restrictedContent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/restrictedContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReasonRestrictedContent"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason.restrictedContent",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason/restrictedcontent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/serviceUnavailable": {
      "abstract": [
        {
          "text": "The app couldn’t perform the search because the media service is unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceUnavailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/serviceUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReasonServiceUnavailable"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason.serviceUnavailable",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason/serviceunavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/subscriptionRequired": {
      "abstract": [
        {
          "text": "The user must have a subscription to the app’s service in order to search for media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriptionRequired"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/subscriptionRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReasonSubscriptionRequired"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason.subscriptionRequired",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason/subscriptionrequired"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/unsupportedMediaType": {
      "abstract": [
        {
          "text": "The media’s type is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedMediaType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/unsupportedMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForMediaMediaItemUnsupportedReasonUnsupportedMediaType"
        }
      ],
      "role": "symbol",
      "title": "INSearchForMediaMediaItemUnsupportedReason.unsupportedMediaType",
      "type": "topic",
      "url": "/documentation/intents/insearchformediamediaitemunsupportedreason/unsupportedmediatype"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reporting-a-Problem",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemResolutionResult/unsupported(forReason:)"
      ],
      "title": "Reporting a Problem"
    }
  ],
  "topicSections": [
    {
      "anchor": "Limitations",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/loginRequired",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/subscriptionRequired",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/unsupportedMediaType",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/explicitContentSettings",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/cellularDataSettings",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/restrictedContent",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/regionRestriction",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/serviceUnavailable"
      ],
      "title": "Limitations"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INSearchForMediaMediaItemUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Limitations",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/loginRequired",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/subscriptionRequired",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/unsupportedMediaType",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/explicitContentSettings",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/cellularDataSettings",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/restrictedContent",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/regionRestriction",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemUnsupportedReason/serviceUnavailable"
              ],
              "title": "Limitations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reporting-a-Problem",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSearchForMediaMediaItemResolutionResult/unsupported(forReason:)"
              ],
              "title": "Reporting a Problem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INSearchForMediaMediaItemUnsupportedReason"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1cellularDataSettings/title",
          "value": "INSearchForMediaMediaItemUnsupportedReasonCellularDataSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1cellularDataSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReasonCellularDataSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1subscriptionRequired/title",
          "value": "INSearchForMediaMediaItemUnsupportedReasonSubscriptionRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1subscriptionRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReasonSubscriptionRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1restrictedContent/title",
          "value": "INSearchForMediaMediaItemUnsupportedReasonRestrictedContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1restrictedContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReasonRestrictedContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1loginRequired/title",
          "value": "INSearchForMediaMediaItemUnsupportedReasonLoginRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1loginRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReasonLoginRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1serviceUnavailable/title",
          "value": "INSearchForMediaMediaItemUnsupportedReasonServiceUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1serviceUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReasonServiceUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemResolutionResult~1unsupported(forReason:)/title",
          "value": "unsupportedForReason:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemResolutionResult~1unsupported(forReason:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "unsupportedForReason:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1regionRestriction/title",
          "value": "INSearchForMediaMediaItemUnsupportedReasonRegionRestriction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1regionRestriction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReasonRegionRestriction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason/title",
          "value": "INSearchForMediaMediaItemUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1unsupportedMediaType/title",
          "value": "INSearchForMediaMediaItemUnsupportedReasonUnsupportedMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1unsupportedMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReasonUnsupportedMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1explicitContentSettings/title",
          "value": "INSearchForMediaMediaItemUnsupportedReasonExplicitContentSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForMediaMediaItemUnsupportedReason~1explicitContentSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForMediaMediaItemUnsupportedReasonExplicitContentSettings"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insearchformediamediaitemunsupportedreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insearchformediamediaitemunsupportedreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
