{
  "abstract": [
    {
      "text": "Constants indicating the reason for being unable to resolve the payee.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INSendPaymentPayeeUnsupportedReason",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INSendPaymentPayeeUnsupportedReason"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INSendPaymentPayeeUnsupportedReason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INSendPaymentPayeeUnsupportedReason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INSendPaymentPayeeUnsupportedReason"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult/init(personResolutionResult:)": {
      "abstract": [
        {
          "text": "Creates a resolution result object with the specified person resolution result object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "personResolutionResult"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPersonResolutionResult",
          "text": "INPersonResolutionResult"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult/init(personResolutionResult:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPersonResolutionResult:"
        }
      ],
      "role": "symbol",
      "title": "init(personResolutionResult:)",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentpayeeresolutionresult/init(personresolutionresult:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult/unsupported(forReason:)": {
      "abstract": [
        {
          "text": "Creates an object whose resolution indicates that the specified value is not supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INSendPaymentPayeeUnsupportedReason",
          "text": "INSendPaymentPayeeUnsupportedReason"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult/unsupported(forReason:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unsupportedForReason:"
        }
      ],
      "role": "symbol",
      "title": "unsupported(forReason:)",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentpayeeresolutionresult/unsupported(forreason:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason": {
      "abstract": [
        {
          "text": "Constants indicating the reason for being unable to resolve the payee.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSendPaymentPayeeUnsupportedReason"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentPayeeUnsupportedReason"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentPayeeUnsupportedReason",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentpayeeunsupportedreason"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/credentialsUnverified": {
      "abstract": [
        {
          "text": "The payee’s credentials are unverifiable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "credentialsUnverified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/credentialsUnverified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentPayeeUnsupportedReasonCredentialsUnverified"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentPayeeUnsupportedReason.credentialsUnverified",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentpayeeunsupportedreason/credentialsunverified"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentpayeeunsupportedreason/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/insufficientFunds": {
      "abstract": [
        {
          "text": "The current user’s account has insufficient funds to make the payment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientFunds"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/insufficientFunds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentPayeeUnsupportedReasonInsufficientFunds"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentPayeeUnsupportedReason.insufficientFunds",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentpayeeunsupportedreason/insufficientfunds"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/noAccount": {
      "abstract": [
        {
          "text": "The payee does not have an account in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noAccount"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/noAccount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentPayeeUnsupportedReasonNoAccount"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentPayeeUnsupportedReason.noAccount",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentpayeeunsupportedreason/noaccount"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/noValidHandle": {
      "abstract": [
        {
          "text": "The unique handle that you use to identify the payee is invalid or missing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noValidHandle"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/noValidHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSendPaymentPayeeUnsupportedReasonNoValidHandle"
        }
      ],
      "role": "symbol",
      "title": "INSendPaymentPayeeUnsupportedReason.noValidHandle",
      "type": "topic",
      "url": "/documentation/intents/insendpaymentpayeeunsupportedreason/novalidhandle"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Resolution-Result-Object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult/unsupported(forReason:)",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult/init(personResolutionResult:)"
      ],
      "title": "Creating a Resolution Result Object"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/credentialsUnverified",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/insufficientFunds",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/noAccount",
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/noValidHandle"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INSendPaymentPayeeUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentPayeeUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentPayeeUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/credentialsUnverified",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/insufficientFunds",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/noAccount",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeUnsupportedReason/noValidHandle"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Resolution-Result-Object",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult/unsupported(forReason:)",
                "doc://com.apple.sirikit/documentation/Intents/INSendPaymentPayeeResolutionResult/init(personResolutionResult:)"
              ],
              "title": "Creating a Resolution Result Object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INSendPaymentPayeeUnsupportedReason"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeResolutionResult~1unsupported(forReason:)/title",
          "value": "unsupportedForReason:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeResolutionResult~1unsupported(forReason:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "unsupportedForReason:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeUnsupportedReason~1credentialsUnverified/title",
          "value": "INSendPaymentPayeeUnsupportedReasonCredentialsUnverified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeUnsupportedReason~1credentialsUnverified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentPayeeUnsupportedReasonCredentialsUnverified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeUnsupportedReason~1insufficientFunds/title",
          "value": "INSendPaymentPayeeUnsupportedReasonInsufficientFunds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeUnsupportedReason~1insufficientFunds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentPayeeUnsupportedReasonInsufficientFunds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeUnsupportedReason/title",
          "value": "INSendPaymentPayeeUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeUnsupportedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentPayeeUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeUnsupportedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentPayeeUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeUnsupportedReason~1noValidHandle/title",
          "value": "INSendPaymentPayeeUnsupportedReasonNoValidHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeUnsupportedReason~1noValidHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentPayeeUnsupportedReasonNoValidHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeResolutionResult~1init(personResolutionResult:)/title",
          "value": "initWithPersonResolutionResult:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeResolutionResult~1init(personResolutionResult:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPersonResolutionResult:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeUnsupportedReason~1noAccount/title",
          "value": "INSendPaymentPayeeUnsupportedReasonNoAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSendPaymentPayeeUnsupportedReason~1noAccount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSendPaymentPayeeUnsupportedReasonNoAccount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insendpaymentpayeeunsupportedreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insendpaymentpayeeunsupportedreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
