{
  "abstract": [
    {
      "text": "The handler interface for searching for notes, tasks, and reminders.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INSearchForNotebookItemsIntentHandling",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INSearchForNotebookItemsIntentHandling"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INSearchForNotebookItemsIntentHandling"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "INSearchForNotebookItemsIntentHandling"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INSearchForNotebookItemsIntentHandling"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the methods of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol to resolve, confirm, and handle requests to search for notes, tasks, and reminders in your app’s content. Adopt this protocol in an object of your Intents extension that’s capable of performing the search and returning the search results to SiriKit.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Siri delivers an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to your handler when the user asks to search for items in your app. The provided intent object contains the search parameters provided by the user. Use the methods of this protocol to resolve the parameters and return the search results.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INNotebookDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the lists and notes domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INNotebookDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INNotebookDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INNotebookDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INNotebookDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/innotebookdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntent": {
      "abstract": [
        {
          "text": "A request to search for notes, tasks, and reminders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchForNotebookItemsIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForNotebookItemsIntent"
        }
      ],
      "role": "symbol",
      "title": "INSearchForNotebookItemsIntent",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for searching for notes, tasks, and reminders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchForNotebookItemsIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForNotebookItemsIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INSearchForNotebookItemsIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/confirm(intent:completion:)": {
      "abstract": [
        {
          "text": "Confirms whether you can perform the search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirm"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSearchForNotebookItemsIntent",
          "text": "INSearchForNotebookItemsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSearchForNotebookItemsIntentResponse",
          "text": "INSearchForNotebookItemsIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/confirm(intent:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "confirmSearchForNotebookItems:completion:"
        }
      ],
      "role": "symbol",
      "title": "confirm(intent:completion:)",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintenthandling/confirm(intent:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/handle(intent:completion:)": {
      "abstract": [
        {
          "text": "Performs the search and deliver the results to SiriKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSearchForNotebookItemsIntent",
          "text": "INSearchForNotebookItemsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSearchForNotebookItemsIntentResponse",
          "text": "INSearchForNotebookItemsIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/handle(intent:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleSearchForNotebookItems:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handle(intent:completion:)",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintenthandling/handle(intent:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveContent(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the string to use when searching the content of notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSearchForNotebookItemsIntent",
          "text": "INSearchForNotebookItemsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INStringResolutionResult",
          "text": "INStringResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveContent(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveContentForSearchForNotebookItems:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveContent(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintenthandling/resolvecontent(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveDateSearchType(for:with:)": {
      "abstract": [
        {
          "text": "Resolves how to use a date value during the search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveDateSearchType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSearchForNotebookItemsIntent",
          "text": "INSearchForNotebookItemsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INDateSearchTypeResolutionResult",
          "text": "INDateSearchTypeResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveDateSearchType(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveDateSearchTypeForSearchForNotebookItems:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveDateSearchType(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintenthandling/resolvedatesearchtype(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveDateTime(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the date to use during a date-based search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveDateTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSearchForNotebookItemsIntent",
          "text": "INSearchForNotebookItemsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INDateComponentsRangeResolutionResult",
          "text": "INDateComponentsRangeResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveDateTime(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveDateTimeForSearchForNotebookItems:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveDateTime(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintenthandling/resolvedatetime(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveItemType(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the type of items to search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveItemType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSearchForNotebookItemsIntent",
          "text": "INSearchForNotebookItemsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INNotebookItemTypeResolutionResult",
          "text": "INNotebookItemTypeResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveItemType(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveItemTypeForSearchForNotebookItems:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveItemType(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintenthandling/resolveitemtype(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveLocation(for:with:)": {
      "abstract": [
        {
          "text": "Resolves how to use a location value during the search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveLocation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSearchForNotebookItemsIntent",
          "text": "INSearchForNotebookItemsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPlacemarkResolutionResult",
          "text": "INPlacemarkResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveLocation(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveLocationForSearchForNotebookItems:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveLocation(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintenthandling/resolvelocation(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveLocationSearchType(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the location to use during a location-based search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveLocationSearchType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSearchForNotebookItemsIntent",
          "text": "INSearchForNotebookItemsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INLocationSearchTypeResolutionResult",
          "text": "INLocationSearchTypeResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveLocationSearchType(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveLocationSearchTypeForSearchForNotebookItems:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveLocationSearchType(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintenthandling/resolvelocationsearchtype(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveStatus(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the status value to use during the search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveStatus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSearchForNotebookItemsIntent",
          "text": "INSearchForNotebookItemsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTaskStatusResolutionResult",
          "text": "INTaskStatusResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveStatus(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveStatusForSearchForNotebookItems:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveStatus(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintenthandling/resolvestatus(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveTaskPriority(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the priority to use during a priority-based search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveTaskPriority"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSearchForNotebookItemsIntent",
          "text": "INSearchForNotebookItemsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTaskPriorityResolutionResult",
          "text": "INTaskPriorityResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveTaskPriority(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveTaskPriorityForSearchForNotebookItems:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveTaskPriority(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintenthandling/resolvetaskpriority(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveTemporalEventTriggerTypes(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the trigger type to use during a temporal-based search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveTemporalEventTriggerTypes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSearchForNotebookItemsIntent",
          "text": "INSearchForNotebookItemsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTemporalEventTriggerTypeOptionsResolutionResult",
          "text": "INTemporalEventTriggerTypeOptionsResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveTemporalEventTriggerTypes(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveTemporalEventTriggerTypesForSearchForNotebookItems:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveTemporalEventTriggerTypes(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintenthandling/resolvetemporaleventtriggertypes(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveTitle(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the string to use when searching the title of notes, tasks, or reminders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveTitle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSearchForNotebookItemsIntent",
          "text": "INSearchForNotebookItemsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INSpeakableStringResolutionResult",
          "text": "INSpeakableStringResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveTitle(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveTitleForSearchForNotebookItems:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveTitle(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintenthandling/resolvetitle(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a request to search for notes, tasks, or reminders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchForNotebookItemsIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForNotebookItemsIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INSearchForNotebookItemsIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/insearchfornotebookitemsintentresponse"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INNotebookDomainHandling"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Notebook-Search",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntent",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentResponse"
      ],
      "title": "Notebook Search"
    }
  ],
  "topicSections": [
    {
      "anchor": "Resolving-the-Intent-Parameters",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveItemType(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveTitle(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveContent(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveStatus(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveDateSearchType(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveDateTime(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveLocation(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveLocationSearchType(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveTaskPriority(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveTemporalEventTriggerTypes(for:with:)"
      ],
      "title": "Resolving the Intent Parameters"
    },
    {
      "anchor": "Confirming-the-Response",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/confirm(intent:completion:)"
      ],
      "title": "Confirming the Response"
    },
    {
      "anchor": "Handling-the-Intent",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/handle(intent:completion:)"
      ],
      "title": "Handling the Intent"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INSearchForNotebookItemsIntentHandling"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForNotebookItemsIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForNotebookItemsIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Resolving-the-Intent-Parameters",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveItemType(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveTitle(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveContent(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveStatus(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveDateSearchType(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveDateTime(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveLocation(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveLocationSearchType(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveTaskPriority(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/resolveTemporalEventTriggerTypes(for:with:)"
              ],
              "title": "Resolving the Intent Parameters"
            },
            {
              "anchor": "Confirming-the-Response",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/confirm(intent:completion:)"
              ],
              "title": "Confirming the Response"
            },
            {
              "anchor": "Handling-the-Intent",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentHandling/handle(intent:completion:)"
              ],
              "title": "Handling the Intent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INNotebookDomainHandling"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Notebook-Search",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntent",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForNotebookItemsIntentResponse"
              ],
              "title": "Notebook Search"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INSearchForNotebookItemsIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveContent(for:with:)/title",
          "value": "resolveContentForSearchForNotebookItems:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveContent(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveContentForSearchForNotebookItems:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveTaskPriority(for:with:)/title",
          "value": "resolveTaskPriorityForSearchForNotebookItems:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveTaskPriority(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveTaskPriorityForSearchForNotebookItems:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentResponse/title",
          "value": "INSearchForNotebookItemsIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForNotebookItemsIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForNotebookItemsIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNotebookDomainHandling/title",
          "value": "INNotebookDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNotebookDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INNotebookDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INNotebookDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INNotebookDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1confirm(intent:completion:)/title",
          "value": "confirmSearchForNotebookItems:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1confirm(intent:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "confirmSearchForNotebookItems:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling/title",
          "value": "INSearchForNotebookItemsIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForNotebookItemsIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForNotebookItemsIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveLocationSearchType(for:with:)/title",
          "value": "resolveLocationSearchTypeForSearchForNotebookItems:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveLocationSearchType(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveLocationSearchTypeForSearchForNotebookItems:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveTemporalEventTriggerTypes(for:with:)/title",
          "value": "resolveTemporalEventTriggerTypesForSearchForNotebookItems:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveTemporalEventTriggerTypes(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveTemporalEventTriggerTypesForSearchForNotebookItems:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveDateSearchType(for:with:)/title",
          "value": "resolveDateSearchTypeForSearchForNotebookItems:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveDateSearchType(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveDateSearchTypeForSearchForNotebookItems:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveItemType(for:with:)/title",
          "value": "resolveItemTypeForSearchForNotebookItems:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveItemType(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveItemTypeForSearchForNotebookItems:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1handle(intent:completion:)/title",
          "value": "handleSearchForNotebookItems:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1handle(intent:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleSearchForNotebookItems:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntent/title",
          "value": "INSearchForNotebookItemsIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForNotebookItemsIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForNotebookItemsIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveTitle(for:with:)/title",
          "value": "resolveTitleForSearchForNotebookItems:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveTitle(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveTitleForSearchForNotebookItems:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveDateTime(for:with:)/title",
          "value": "resolveDateTimeForSearchForNotebookItems:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveDateTime(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveDateTimeForSearchForNotebookItems:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveLocation(for:with:)/title",
          "value": "resolveLocationForSearchForNotebookItems:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveLocation(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveLocationForSearchForNotebookItems:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveStatus(for:with:)/title",
          "value": "resolveStatusForSearchForNotebookItems:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForNotebookItemsIntentHandling~1resolveStatus(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveStatusForSearchForNotebookItems:withCompletion:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insearchfornotebookitemsintenthandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insearchfornotebookitemsintenthandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
