{
  "abstract": [
    {
      "text": "An object representing an action available in your app that the system may suggest to a user or a user may add to Siri.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INShortcutReference"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INShortcut",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INShortcutReference"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INShortcutReference"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "INShortcutReference"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INShortcutReference"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.sirikit/documentation/SiriKit/offering-actions-in-the-shortcuts-app",
        "doc://com.apple.sirikit/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentDonationMetadata": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentDonationMetadata"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentDonationMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentDonationMetadata"
        }
      ],
      "role": "symbol",
      "title": "INIntentDonationMetadata",
      "type": "topic",
      "url": "/documentation/intents/inintentdonationmetadata"
    },
    "doc://com.apple.sirikit/documentation/Intents/INInteraction": {
      "abstract": [
        {
          "text": "An interaction between the user and your app involving an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INInteraction"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INInteraction"
        }
      ],
      "role": "symbol",
      "title": "INInteraction",
      "type": "topic",
      "url": "/documentation/intents/ininteraction"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcut-swift.enum": {
      "abstract": [
        {
          "text": "An action available in your app that the system may suggest to a user or a user may add to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INShortcut"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcut-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcut"
        }
      ],
      "role": "symbol",
      "title": "INShortcut",
      "type": "topic",
      "url": "/documentation/intents/inshortcut-swift.enum"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions": {
      "abstract": [
        {
          "text": "Defined contexts in which an intent or activity might be relevant to a user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INShortcutAvailabilityOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcutAvailabilityOptions"
        }
      ],
      "role": "symbol",
      "title": "INShortcutAvailabilityOptions",
      "type": "topic",
      "url": "/documentation/intents/inshortcutavailabilityoptions"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutReference": {
      "abstract": [
        {
          "text": "An object representing an action available in your app that the system may suggest to a user or a user may add to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INShortcutReference"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutReference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShortcutReference"
        }
      ],
      "role": "symbol",
      "title": "INShortcutReference",
      "type": "topic",
      "url": "/documentation/intents/inshortcutreference"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutReference/init(intent:)": {
      "abstract": [
        {
          "text": "Creates a shortcut with the specified intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INIntent",
          "text": "INIntent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutReference/init(intent:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithIntent:"
        }
      ],
      "role": "symbol",
      "title": "init(intent:)",
      "type": "topic",
      "url": "/documentation/intents/inshortcutreference/init(intent:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutReference/init(userActivity:)": {
      "abstract": [
        {
          "text": "Creates a shortcut with the specified user activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "userActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserActivity",
          "text": "NSUserActivity"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutReference/init(userActivity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithUserActivity:"
        }
      ],
      "role": "symbol",
      "title": "init(userActivity:)",
      "type": "topic",
      "url": "/documentation/intents/inshortcutreference/init(useractivity:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutReference/intent": {
      "abstract": [
        {
          "text": "The intent that performs the action when invoking the shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INIntent",
          "text": "INIntent"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutReference/intent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "intent"
        }
      ],
      "role": "symbol",
      "title": "intent",
      "type": "topic",
      "url": "/documentation/intents/inshortcutreference/intent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShortcutReference/userActivity": {
      "abstract": [
        {
          "text": "The user activity that defines the action to perform when invoking the shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserActivity",
          "text": "NSUserActivity"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShortcutReference/userActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userActivity"
        }
      ],
      "role": "symbol",
      "title": "userActivity",
      "type": "topic",
      "url": "/documentation/intents/inshortcutreference/useractivity"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut": {
      "abstract": [
        {
          "text": "A shortcut the user added to Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVoiceShortcut"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVoiceShortcut"
        }
      ],
      "role": "symbol",
      "title": "INVoiceShortcut",
      "type": "topic",
      "url": "/documentation/intents/invoiceshortcut"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter": {
      "abstract": [
        {
          "text": "Retrieve the user’s shortcuts and make shortcut suggestions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVoiceShortcutCenter"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVoiceShortcutCenter"
        }
      ],
      "role": "symbol",
      "title": "INVoiceShortcutCenter",
      "type": "topic",
      "url": "/documentation/intents/invoiceshortcutcenter"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/adding-shortcuts-for-wind-down": {
      "abstract": [
        {
          "text": "Reveal your app’s shortcuts inside the Health app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/adding-shortcuts-for-wind-down",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adding Shortcuts for Wind Down",
      "type": "topic",
      "url": "/documentation/sirikit/adding-shortcuts-for-wind-down"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app": {
      "abstract": [
        {
          "text": "Add custom intents and parameters to help users interact more quickly and effectively with Siri and the Shortcuts app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app",
      "kind": "article",
      "role": "article",
      "title": "Adding User Interactivity with Siri Shortcuts and the Shortcuts App",
      "type": "topic",
      "url": "/documentation/sirikit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face": {
      "abstract": [
        {
          "text": "Inform Siri when your app’s shortcuts may be useful to the user.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/defining-relevant-shortcuts-for-the-siri-watch-face",
      "kind": "article",
      "role": "article",
      "title": "Defining Relevant Shortcuts for the Siri Watch Face",
      "type": "topic",
      "url": "/documentation/sirikit/defining-relevant-shortcuts-for-the-siri-watch-face"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/deleting-donated-shortcuts": {
      "abstract": [
        {
          "text": "Remove your donations from Siri.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/deleting-donated-shortcuts",
      "kind": "article",
      "role": "article",
      "title": "Deleting Donated Shortcuts",
      "type": "topic",
      "url": "/documentation/sirikit/deleting-donated-shortcuts"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/donating-shortcuts": {
      "abstract": [
        {
          "text": "Tell Siri about shortcuts to actions that the user performed in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/donating-shortcuts",
      "kind": "article",
      "role": "article",
      "title": "Donating Shortcuts",
      "type": "topic",
      "url": "/documentation/sirikit/donating-shortcuts"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/offering-actions-in-the-shortcuts-app": {
      "abstract": [
        {
          "text": "Suggest shortcuts users may want to add to Siri or combine with other actions in their own shortcuts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/offering-actions-in-the-shortcuts-app",
      "kind": "article",
      "role": "article",
      "title": "Offering Actions in the Shortcuts App",
      "type": "topic",
      "url": "/documentation/sirikit/offering-actions-in-the-shortcuts-app"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/siri-event-suggestions": {
      "abstract": [
        {
          "text": "Provide users with current, actionable information connected to a reservation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/siri-event-suggestions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Siri Event Suggestions",
      "type": "topic",
      "url": "/documentation/sirikit/siri-event-suggestions"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-accelerating-app-interactions-with-shortcuts": {
      "abstract": [
        {
          "text": "Make it easy for people to use Siri with your app by providing shortcuts to your app’s actions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-accelerating-app-interactions-with-shortcuts",
      "kind": "article",
      "role": "sampleCode",
      "title": "Soup Chef: Accelerating App Interactions with Shortcuts",
      "type": "topic",
      "url": "/documentation/sirikit/soup-chef-accelerating-app-interactions-with-shortcuts"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-with-app-intents-migrating-custom-intents": {
      "abstract": [
        {
          "text": "Integrating App Intents to provide your appʼs actions to Siri and Shortcuts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-with-app-intents-migrating-custom-intents",
      "kind": "article",
      "role": "sampleCode",
      "title": "Soup Chef with App Intents: Migrating custom intents",
      "type": "topic",
      "url": "/documentation/sirikit/soup-chef-with-app-intents-migrating-custom-intents"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/watch-and-widget-support": {
      "abstract": [
        {
          "text": "Display relevant shortcuts on the Siri watch face and suggest widgets in Smart Stacks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/watch-and-widget-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Watch and Widget Support",
      "type": "topic",
      "url": "/documentation/sirikit/watch-and-widget-support"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Shortcuts-and-Donations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/offering-actions-in-the-shortcuts-app",
        "doc://com.apple.sirikit/documentation/SiriKit/adding-user-interactivity-with-siri-shortcuts-and-the-shortcuts-app",
        "doc://com.apple.sirikit/documentation/SiriKit/donating-shortcuts",
        "doc://com.apple.sirikit/documentation/SiriKit/deleting-donated-shortcuts",
        "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-accelerating-app-interactions-with-shortcuts",
        "doc://com.apple.sirikit/documentation/SiriKit/soup-chef-with-app-intents-migrating-custom-intents",
        "doc://com.apple.sirikit/documentation/SiriKit/adding-shortcuts-for-wind-down",
        "doc://com.apple.sirikit/documentation/Intents/INInteraction",
        "doc://com.apple.sirikit/documentation/Intents/INShortcut-swift.enum",
        "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter",
        "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut",
        "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions",
        "doc://com.apple.sirikit/documentation/Intents/INIntentDonationMetadata",
        "doc://com.apple.sirikit/documentation/SiriKit/watch-and-widget-support",
        "doc://com.apple.sirikit/documentation/SiriKit/siri-event-suggestions"
      ],
      "title": "Shortcuts and Donations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Shortcut",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INShortcutReference/init(intent:)",
        "doc://com.apple.sirikit/documentation/Intents/INShortcutReference/init(userActivity:)"
      ],
      "title": "Creating a Shortcut"
    },
    {
      "anchor": "Getting-the-Intent",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INShortcutReference/intent"
      ],
      "title": "Getting the Intent"
    },
    {
      "anchor": "Getting-the-User-Activity",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INShortcutReference/userActivity"
      ],
      "title": "Getting the User Activity"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INShortcut"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Shortcut",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INShortcutReference/init(intent:)",
                "doc://com.apple.sirikit/documentation/Intents/INShortcutReference/init(userActivity:)"
              ],
              "title": "Creating a Shortcut"
            },
            {
              "anchor": "Getting-the-Intent",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INShortcutReference/intent"
              ],
              "title": "Getting the Intent"
            },
            {
              "anchor": "Getting-the-User-Activity",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INShortcutReference/userActivity"
              ],
              "title": "Getting the User Activity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Shortcuts-and-Donations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INInteraction",
                "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcutCenter",
                "doc://com.apple.sirikit/documentation/Intents/INVoiceShortcut",
                "doc://com.apple.sirikit/documentation/Intents/INShortcutAvailabilityOptions",
                "doc://com.apple.sirikit/documentation/Intents/INIntentDonationMetadata"
              ],
              "title": "Shortcuts and Donations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INShortcut"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference~1userActivity/title",
          "value": "userActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference~1userActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcut/title",
          "value": "INVoiceShortcut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVoiceShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcut/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVoiceShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions/title",
          "value": "INShortcutAvailabilityOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcutAvailabilityOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutAvailabilityOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcutAvailabilityOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcutCenter/title",
          "value": "INVoiceShortcutCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcutCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVoiceShortcutCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVoiceShortcutCenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVoiceShortcutCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference/title",
          "value": "INShortcut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentDonationMetadata/title",
          "value": "INIntentDonationMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentDonationMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentDonationMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentDonationMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentDonationMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference~1init(userActivity:)/title",
          "value": "initWithUserActivity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference~1init(userActivity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithUserActivity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference~1intent/title",
          "value": "intent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference~1intent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "intent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference~1init(intent:)/title",
          "value": "initWithIntent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShortcutReference~1init(intent:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithIntent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/title",
          "value": "INInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INInteraction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inshortcutreference"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inshortcutreference"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
