{
  "abstract": [
    {
      "text": "Constants indicating the status of the response.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "INStartAudioCallIntent is deprecated. Please adopt INStartCallIntent instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INStartAudioCallIntentResponseCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INStartAudioCallIntentResponseCode"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INStartAudioCallIntentResponseCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "10.0",
        "message": "INStartAudioCallIntent is deprecated. Please adopt INStartCallIntent instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "10.0",
        "message": "INStartAudioCallIntent is deprecated. Please adopt INStartCallIntent instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "INStartAudioCallIntent is deprecated. Please adopt INStartCallIntent instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INStartAudioCallIntent is deprecated. Please adopt INStartCallIntent instead",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "6.0",
        "introducedAt": "3.2",
        "message": "INStartAudioCallIntent is deprecated. Please adopt INStartCallIntent instead",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INStartAudioCallIntentResponseCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntentResponseCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponse/code": {
      "abstract": [
        {
          "text": "The code indicating whether you successfully handled the intent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INStartAudioCallIntentResponseCode",
          "text": "INStartAudioCallIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponse/code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "code"
        }
      ],
      "role": "symbol",
      "title": "code",
      "type": "topic",
      "url": "/documentation/intents/instartaudiocallintentresponse/code"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode": {
      "abstract": [
        {
          "text": "Constants indicating the status of the response.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartAudioCallIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartAudioCallIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INStartAudioCallIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/instartaudiocallintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/continueInApp": {
      "abstract": [
        {
          "text": "Your extension is ready to transfer control so your app can place the call.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continueInApp"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/continueInApp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartAudioCallIntentResponseCodeContinueInApp"
        }
      ],
      "role": "symbol",
      "title": "INStartAudioCallIntentResponseCode.continueInApp",
      "type": "topic",
      "url": "/documentation/intents/instartaudiocallintentresponsecode/continueinapp"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "You were unable to initiate the call.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartAudioCallIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INStartAudioCallIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/instartaudiocallintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureAppConfigurationRequired": {
      "abstract": [
        {
          "text": "The user must perform additional configuration steps before initiating a call is possible.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureAppConfigurationRequired"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureAppConfigurationRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartAudioCallIntentResponseCodeFailureAppConfigurationRequired"
        }
      ],
      "role": "symbol",
      "title": "INStartAudioCallIntentResponseCode.failureAppConfigurationRequired",
      "type": "topic",
      "url": "/documentation/intents/instartaudiocallintentresponsecode/failureappconfigurationrequired"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureCallingServiceNotAvailable": {
      "abstract": [
        {
          "text": "Your app’s calling service isn’t currently available.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureCallingServiceNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureCallingServiceNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartAudioCallIntentResponseCodeFailureCallingServiceNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "INStartAudioCallIntentResponseCode.failureCallingServiceNotAvailable",
      "type": "topic",
      "url": "/documentation/intents/instartaudiocallintentresponsecode/failurecallingservicenotavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureContactNotSupportedByApp": {
      "abstract": [
        {
          "text": "You can’t use the specified contact to place the call.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureContactNotSupportedByApp"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureContactNotSupportedByApp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartAudioCallIntentResponseCodeFailureContactNotSupportedByApp"
        }
      ],
      "role": "symbol",
      "title": "INStartAudioCallIntentResponseCode.failureContactNotSupportedByApp",
      "type": "topic",
      "url": "/documentation/intents/instartaudiocallintentresponsecode/failurecontactnotsupportedbyapp"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureNoValidNumber": {
      "abstract": [
        {
          "text": "The specified number doesn’t support audio calls.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureNoValidNumber"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureNoValidNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartAudioCallIntentResponseCodeFailureNoValidNumber"
        }
      ],
      "role": "symbol",
      "title": "INStartAudioCallIntentResponseCode.failureNoValidNumber",
      "type": "topic",
      "url": "/documentation/intents/instartaudiocallintentresponsecode/failurenovalidnumber"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "The user must launch your app to initiate the call.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartAudioCallIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INStartAudioCallIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/instartaudiocallintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/instartaudiocallintentresponsecode/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "You’re ready to handle the intent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartAudioCallIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INStartAudioCallIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/instartaudiocallintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "Your app can’t provide a specific status.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartAudioCallIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INStartAudioCallIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/instartaudiocallintentresponsecode/unspecified"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Response-Code",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponse/code"
      ],
      "title": "Getting the Response Code"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/unspecified",
        "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/continueInApp",
        "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureRequiringAppLaunch",
        "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureAppConfigurationRequired",
        "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureCallingServiceNotAvailable",
        "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureContactNotSupportedByApp",
        "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureNoValidNumber"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "6.0",
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INStartAudioCallIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/unspecified",
                "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/continueInApp",
                "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureRequiringAppLaunch",
                "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureAppConfigurationRequired",
                "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureCallingServiceNotAvailable",
                "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureContactNotSupportedByApp",
                "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponseCode/failureNoValidNumber"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Response-Code",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartAudioCallIntentResponse/code"
              ],
              "title": "Getting the Response Code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INStartAudioCallIntentResponseCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "INStartAudioCallIntent is deprecated. Please adopt INStartCallIntent instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1failureCallingServiceNotAvailable/title",
          "value": "INStartAudioCallIntentResponseCodeFailureCallingServiceNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1failureCallingServiceNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntentResponseCodeFailureCallingServiceNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode/title",
          "value": "INStartAudioCallIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1unspecified/title",
          "value": "INStartAudioCallIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1failure/title",
          "value": "INStartAudioCallIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntentResponseCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INStartAudioCallIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1ready/title",
          "value": "INStartAudioCallIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1failureAppConfigurationRequired/title",
          "value": "INStartAudioCallIntentResponseCodeFailureAppConfigurationRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1failureAppConfigurationRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntentResponseCodeFailureAppConfigurationRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponse~1code/title",
          "value": "code"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponse~1code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1continueInApp/title",
          "value": "INStartAudioCallIntentResponseCodeContinueInApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1continueInApp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntentResponseCodeContinueInApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1failureNoValidNumber/title",
          "value": "INStartAudioCallIntentResponseCodeFailureNoValidNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1failureNoValidNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntentResponseCodeFailureNoValidNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1failureContactNotSupportedByApp/title",
          "value": "INStartAudioCallIntentResponseCodeFailureContactNotSupportedByApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartAudioCallIntentResponseCode~1failureContactNotSupportedByApp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartAudioCallIntentResponseCodeFailureContactNotSupportedByApp"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/instartaudiocallintentresponsecode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/instartaudiocallintentresponsecode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
