{
  "abstract": [
    {
      "text": "Constants indicating the status of the response.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "INStartVideoCallIntent is deprecated. Please adopt INStartCallIntent instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INStartVideoCallIntentResponseCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INStartVideoCallIntentResponseCode"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INStartVideoCallIntentResponseCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "10.0",
        "message": "INStartVideoCallIntent is deprecated. Please adopt INStartCallIntent instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "10.0",
        "message": "INStartVideoCallIntent is deprecated. Please adopt INStartCallIntent instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "INStartVideoCallIntent is deprecated. Please adopt INStartCallIntent instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INStartVideoCallIntent is deprecated. Please adopt INStartCallIntent instead",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INStartVideoCallIntentResponseCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntentResponseCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponse/code": {
      "abstract": [
        {
          "text": "The code indicating whether you successfully handled the intent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INStartVideoCallIntentResponseCode",
          "text": "INStartVideoCallIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponse/code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "code"
        }
      ],
      "role": "symbol",
      "title": "code",
      "type": "topic",
      "url": "/documentation/intents/instartvideocallintentresponse/code"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode": {
      "abstract": [
        {
          "text": "Constants indicating the status of the response.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartVideoCallIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartVideoCallIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INStartVideoCallIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/instartvideocallintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/continueInApp": {
      "abstract": [
        {
          "text": "Your extension is ready to transfer control to the app so that your app can place the call.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continueInApp"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/continueInApp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartVideoCallIntentResponseCodeContinueInApp"
        }
      ],
      "role": "symbol",
      "title": "INStartVideoCallIntentResponseCode.continueInApp",
      "type": "topic",
      "url": "/documentation/intents/instartvideocallintentresponsecode/continueinapp"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "You were unable to initiate the call.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartVideoCallIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INStartVideoCallIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/instartvideocallintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureAppConfigurationRequired": {
      "abstract": [
        {
          "text": "The user must perform additional configuration steps before initiating a call is possible.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureAppConfigurationRequired"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureAppConfigurationRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartVideoCallIntentResponseCodeFailureAppConfigurationRequired"
        }
      ],
      "role": "symbol",
      "title": "INStartVideoCallIntentResponseCode.failureAppConfigurationRequired",
      "type": "topic",
      "url": "/documentation/intents/instartvideocallintentresponsecode/failureappconfigurationrequired"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureCallingServiceNotAvailable": {
      "abstract": [
        {
          "text": "Your app’s calling service isn’t currently available.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureCallingServiceNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureCallingServiceNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartVideoCallIntentResponseCodeFailureCallingServiceNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "INStartVideoCallIntentResponseCode.failureCallingServiceNotAvailable",
      "type": "topic",
      "url": "/documentation/intents/instartvideocallintentresponsecode/failurecallingservicenotavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureContactNotSupportedByApp": {
      "abstract": [
        {
          "text": "Your app can’t use the specified contact to place the call.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureContactNotSupportedByApp"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureContactNotSupportedByApp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartVideoCallIntentResponseCodeFailureContactNotSupportedByApp"
        }
      ],
      "role": "symbol",
      "title": "INStartVideoCallIntentResponseCode.failureContactNotSupportedByApp",
      "type": "topic",
      "url": "/documentation/intents/instartvideocallintentresponsecode/failurecontactnotsupportedbyapp"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureInvalidNumber": {
      "abstract": [
        {
          "text": "The specified number doesn’t support video calls.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureInvalidNumber"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureInvalidNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartVideoCallIntentResponseCodeFailureInvalidNumber"
        }
      ],
      "role": "symbol",
      "title": "INStartVideoCallIntentResponseCode.failureInvalidNumber",
      "type": "topic",
      "url": "/documentation/intents/instartvideocallintentresponsecode/failureinvalidnumber"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "The user must launch your app to initiate the call.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartVideoCallIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INStartVideoCallIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/instartvideocallintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/instartvideocallintentresponsecode/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "You’re ready to handle the intent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartVideoCallIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INStartVideoCallIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/instartvideocallintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "Your app can’t provide a more specific response.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartVideoCallIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INStartVideoCallIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/instartvideocallintentresponsecode/unspecified"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Response-Code",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponse/code"
      ],
      "title": "Getting the Response Code"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/unspecified",
        "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/continueInApp",
        "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureRequiringAppLaunch",
        "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureAppConfigurationRequired",
        "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureCallingServiceNotAvailable",
        "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureContactNotSupportedByApp",
        "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureInvalidNumber"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INStartVideoCallIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/unspecified",
                "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/continueInApp",
                "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureRequiringAppLaunch",
                "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureAppConfigurationRequired",
                "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureCallingServiceNotAvailable",
                "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureContactNotSupportedByApp",
                "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponseCode/failureInvalidNumber"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Response-Code",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartVideoCallIntentResponse/code"
              ],
              "title": "Getting the Response Code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INStartVideoCallIntentResponseCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "INStartVideoCallIntent is deprecated. Please adopt INStartCallIntent instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1unspecified/title",
          "value": "INStartVideoCallIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1failure/title",
          "value": "INStartVideoCallIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntentResponseCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1failureInvalidNumber/title",
          "value": "INStartVideoCallIntentResponseCodeFailureInvalidNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1failureInvalidNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntentResponseCodeFailureInvalidNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponse~1code/title",
          "value": "code"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponse~1code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1failureAppConfigurationRequired/title",
          "value": "INStartVideoCallIntentResponseCodeFailureAppConfigurationRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1failureAppConfigurationRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntentResponseCodeFailureAppConfigurationRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1failureCallingServiceNotAvailable/title",
          "value": "INStartVideoCallIntentResponseCodeFailureCallingServiceNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1failureCallingServiceNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntentResponseCodeFailureCallingServiceNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1ready/title",
          "value": "INStartVideoCallIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1continueInApp/title",
          "value": "INStartVideoCallIntentResponseCodeContinueInApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1continueInApp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntentResponseCodeContinueInApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INStartVideoCallIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode/title",
          "value": "INStartVideoCallIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1failureContactNotSupportedByApp/title",
          "value": "INStartVideoCallIntentResponseCodeFailureContactNotSupportedByApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartVideoCallIntentResponseCode~1failureContactNotSupportedByApp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartVideoCallIntentResponseCodeFailureContactNotSupportedByApp"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/instartvideocallintentresponsecode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/instartvideocallintentresponsecode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
