{
  "abstract": [
    {
      "text": "An interface that handles requests to start audio and video calls.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INStartCallIntentHandling",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INStartCallIntentHandling"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INStartCallIntentHandling"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "INStartCallIntentHandling"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INStartCallIntentHandling"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.sirikit/documentation/SiriKit/dispatching-intents-to-handlers"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the methods of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol to resolve, confirm, and handle requests to start an audio or video call with the designated users. Adopt this protocol in an object of your Intents extension that’s capable of validating the call information. Your Intents extension shouldn’t try to initiate the call directly. Instead, a successful response involves asking Siri to launch your app to begin the call.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Siri delivers an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to your handler when the user asks to initiate a call using your app. The provided intent object contains information about who the user wants to call. Use the methods of this protocol to resolve the list of callable contacts and to validate that your app can place the call successfully.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallCallRecordToCallBackUnsupportedReason": {
      "abstract": [
        {
          "text": "A reason why your app can’t use a record to call a person back.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartCallCallRecordToCallBackUnsupportedReason"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallCallRecordToCallBackUnsupportedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallCallRecordToCallBackUnsupportedReason"
        }
      ],
      "role": "symbol",
      "title": "INStartCallCallRecordToCallBackUnsupportedReason",
      "type": "topic",
      "url": "/documentation/intents/instartcallcallrecordtocallbackunsupportedreason"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntent": {
      "abstract": [
        {
          "text": "A request to start an audio or video call with one or more users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartCallIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallIntent"
        }
      ],
      "role": "symbol",
      "title": "INStartCallIntent",
      "type": "topic",
      "url": "/documentation/intents/instartcallintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling": {
      "abstract": [
        {
          "text": "An interface that handles requests to start audio and video calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartCallIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INStartCallIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/instartcallintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/confirm(intent:completion:)": {
      "abstract": [
        {
          "text": "Confirms whether your app is able to initiate the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirm"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INStartCallIntent",
          "text": "INStartCallIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INStartCallIntentResponse",
          "text": "INStartCallIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/confirm(intent:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "confirmStartCall:completion:"
        }
      ],
      "role": "symbol",
      "title": "confirm(intent:completion:)",
      "type": "topic",
      "url": "/documentation/intents/instartcallintenthandling/confirm(intent:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/handle(intent:completion:)": {
      "abstract": [
        {
          "text": "Handles handing off the call to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INStartCallIntent",
          "text": "INStartCallIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INStartCallIntentResponse",
          "text": "INStartCallIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/handle(intent:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleStartCall:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handle(intent:completion:)",
      "type": "topic",
      "url": "/documentation/intents/instartcallintenthandling/handle(intent:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/resolveCallCapability(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the type of call to start.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveCallCapability"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INStartCallIntent",
          "text": "INStartCallIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INStartCallCallCapabilityResolutionResult",
          "text": "INStartCallCallCapabilityResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/resolveCallCapability(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveCallCapabilityForStartCall:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveCallCapability(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/instartcallintenthandling/resolvecallcapability(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/resolveCallRecordToCallBack(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the redial of a missed call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveCallRecordToCallBack"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INStartCallIntent",
          "text": "INStartCallIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCallRecordResolutionResult",
          "text": "INCallRecordResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/resolveCallRecordToCallBack(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveCallRecordToCallBackForStartCall:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveCallRecordToCallBack(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/instartcallintenthandling/resolvecallrecordtocallback(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/resolveContacts(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the recipients of the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveContacts"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INStartCallIntent",
          "text": "INStartCallIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INStartCallContactResolutionResult",
          "text": "INStartCallContactResolutionResult"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/resolveContacts(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveContactsForStartCall:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveContacts(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/instartcallintenthandling/resolvecontacts(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/resolveDestinationType(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the destination of the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveDestinationType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INStartCallIntent",
          "text": "INStartCallIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INCallDestinationTypeResolutionResult",
          "text": "INCallDestinationTypeResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/resolveDestinationType(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveDestinationTypeForStartCall:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveDestinationType(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/instartcallintenthandling/resolvedestinationtype(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a start call intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartCallIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INStartCallIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/instartcallintentresponse"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/dispatching-intents-to-handlers": {
      "abstract": [
        {
          "text": "Provide SiriKit with an intent handler capable of handling a specific intent.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/dispatching-intents-to-handlers",
      "kind": "article",
      "role": "article",
      "title": "Dispatching intents to handlers",
      "type": "topic",
      "url": "/documentation/sirikit/dispatching-intents-to-handlers"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Starting-a-Call",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntent",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponse",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallCallRecordToCallBackUnsupportedReason"
      ],
      "title": "Starting a Call"
    }
  ],
  "topicSections": [
    {
      "anchor": "Resolving-the-Intent-Parameters",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/resolveCallCapability(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/resolveContacts(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/resolveDestinationType(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/resolveCallRecordToCallBack(for:with:)"
      ],
      "title": "Resolving the Intent Parameters"
    },
    {
      "anchor": "Confirming-the-Response",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/confirm(intent:completion:)"
      ],
      "title": "Confirming the Response"
    },
    {
      "anchor": "Handling-the-Intent",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/handle(intent:completion:)"
      ],
      "title": "Handling the Intent"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INStartCallIntentHandling"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Resolving-the-Intent-Parameters",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/resolveCallCapability(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/resolveContacts(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/resolveDestinationType(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/resolveCallRecordToCallBack(for:with:)"
              ],
              "title": "Resolving the Intent Parameters"
            },
            {
              "anchor": "Confirming-the-Response",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/confirm(intent:completion:)"
              ],
              "title": "Confirming the Response"
            },
            {
              "anchor": "Handling-the-Intent",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentHandling/handle(intent:completion:)"
              ],
              "title": "Handling the Intent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Starting-a-Call",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntent",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallIntentResponse",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallCallRecordToCallBackUnsupportedReason"
              ],
              "title": "Starting a Call"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INStartCallIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntent/title",
          "value": "INStartCallIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling/title",
          "value": "INStartCallIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling~1handle(intent:completion:)/title",
          "value": "handleStartCall:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling~1handle(intent:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleStartCall:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling~1resolveCallCapability(for:with:)/title",
          "value": "resolveCallCapabilityForStartCall:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling~1resolveCallCapability(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveCallCapabilityForStartCall:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling~1resolveCallRecordToCallBack(for:with:)/title",
          "value": "resolveCallRecordToCallBackForStartCall:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling~1resolveCallRecordToCallBack(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveCallRecordToCallBackForStartCall:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling~1confirm(intent:completion:)/title",
          "value": "confirmStartCall:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling~1confirm(intent:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "confirmStartCall:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponse/title",
          "value": "INStartCallIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallCallRecordToCallBackUnsupportedReason/title",
          "value": "INStartCallCallRecordToCallBackUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallCallRecordToCallBackUnsupportedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallCallRecordToCallBackUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallCallRecordToCallBackUnsupportedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallCallRecordToCallBackUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling~1resolveDestinationType(for:with:)/title",
          "value": "resolveDestinationTypeForStartCall:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling~1resolveDestinationType(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveDestinationTypeForStartCall:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling~1resolveContacts(for:with:)/title",
          "value": "resolveContactsForStartCall:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallIntentHandling~1resolveContacts(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveContactsForStartCall:withCompletion:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/instartcallintenthandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/instartcallintenthandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
