{
  "abstract": [
    {
      "text": "Constants indicating the reason the app can’t support starting a call with the contact.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INStartCallContactUnsupportedReason",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INStartCallContactUnsupportedReason"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INStartCallContactUnsupportedReason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INStartCallContactUnsupportedReason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReason"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactResolutionResult/init(personResolutionResult:)": {
      "abstract": [
        {
          "text": "Creates an object whose resolution involves the succesful start of a call with the specified contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "personResolutionResult"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPersonResolutionResult",
          "text": "INPersonResolutionResult"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactResolutionResult/init(personResolutionResult:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPersonResolutionResult:"
        }
      ],
      "role": "symbol",
      "title": "init(personResolutionResult:)",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactresolutionresult/init(personresolutionresult:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactResolutionResult/unsupported(forReason:)": {
      "abstract": [
        {
          "text": "Creates an object specifying that resolution of the parameter wasn’t supported, for the specified reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupported"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INStartCallContactUnsupportedReason",
          "text": "INStartCallContactUnsupportedReason"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactResolutionResult/unsupported(forReason:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unsupportedForReason:"
        }
      ],
      "role": "symbol",
      "title": "unsupported(forReason:)",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactresolutionresult/unsupported(forreason:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason": {
      "abstract": [
        {
          "text": "Constants indicating the reason the app can’t support starting a call with the contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReason"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReason"
        }
      ],
      "role": "symbol",
      "title": "INStartCallContactUnsupportedReason",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/invalidHandle": {
      "abstract": [
        {
          "text": "The handle is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidHandle"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/invalidHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReasonInvalidHandle"
        }
      ],
      "role": "symbol",
      "title": "INStartCallContactUnsupportedReason.invalidHandle",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason/invalidhandle"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/multipleContactsUnsupported": {
      "abstract": [
        {
          "text": "The app doesn’t support calls with multiple contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multipleContactsUnsupported"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/multipleContactsUnsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReasonMultipleContactsUnsupported"
        }
      ],
      "role": "symbol",
      "title": "INStartCallContactUnsupportedReason.multipleContactsUnsupported",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason/multiplecontactsunsupported"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noCallHistoryForRedial": {
      "abstract": [
        {
          "text": "No redial attempt doesn’t have an associated call history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noCallHistoryForRedial"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noCallHistoryForRedial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReasonNoCallHistoryForRedial"
        }
      ],
      "role": "symbol",
      "title": "INStartCallContactUnsupportedReason.noCallHistoryForRedial",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason/nocallhistoryforredial"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noContactFound": {
      "abstract": [
        {
          "text": "The contact wasn’t found in the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noContactFound"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noContactFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReasonNoContactFound"
        }
      ],
      "role": "symbol",
      "title": "INStartCallContactUnsupportedReason.noContactFound",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason/nocontactfound"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noHandleForLabel": {
      "abstract": [
        {
          "text": "The handle for the label wasn’t found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noHandleForLabel"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noHandleForLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReasonNoHandleForLabel"
        }
      ],
      "role": "symbol",
      "title": "INStartCallContactUnsupportedReason.noHandleForLabel",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason/nohandleforlabel"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noUsableHandleForRedial": {
      "abstract": [
        {
          "text": "The redial attempt doesn’t have a usable handle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noUsableHandleForRedial"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noUsableHandleForRedial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReasonNoUsableHandleForRedial"
        }
      ],
      "role": "symbol",
      "title": "INStartCallContactUnsupportedReason.noUsableHandleForRedial",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason/nousablehandleforredial"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/requiringInAppAuthentication": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiringInAppAuthentication"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/requiringInAppAuthentication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReasonRequiringInAppAuthentication"
        }
      ],
      "role": "symbol",
      "title": "INStartCallContactUnsupportedReason.requiringInAppAuthentication",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason/requiringinappauthentication"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/unsupportedMmiUssd": {
      "abstract": [
        {
          "text": "An unsupported MMI codewas used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedMmiUssd"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/unsupportedMmiUssd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReasonUnsupportedMmiUssd"
        }
      ],
      "role": "symbol",
      "title": "INStartCallContactUnsupportedReason.unsupportedMmiUssd",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason/unsupportedmmiussd"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Resolution-Result-Object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactResolutionResult/init(personResolutionResult:)",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactResolutionResult/unsupported(forReason:)"
      ],
      "title": "Creating a Resolution Result Object"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noContactFound",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/multipleContactsUnsupported",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noHandleForLabel",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/invalidHandle",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/unsupportedMmiUssd",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noCallHistoryForRedial",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noUsableHandleForRedial"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/requiringInAppAuthentication"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INStartCallContactUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noContactFound",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/multipleContactsUnsupported",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noHandleForLabel",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/invalidHandle",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/unsupportedMmiUssd",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noCallHistoryForRedial",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noUsableHandleForRedial"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/requiringInAppAuthentication"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Resolution-Result-Object",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartCallContactResolutionResult/init(personResolutionResult:)",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallContactResolutionResult/unsupported(forReason:)"
              ],
              "title": "Creating a Resolution Result Object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INStartCallContactUnsupportedReason"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactResolutionResult~1unsupported(forReason:)/title",
          "value": "unsupportedForReason:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactResolutionResult~1unsupported(forReason:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "unsupportedForReason:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactResolutionResult~1init(personResolutionResult:)/title",
          "value": "initWithPersonResolutionResult:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactResolutionResult~1init(personResolutionResult:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPersonResolutionResult:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1multipleContactsUnsupported/title",
          "value": "INStartCallContactUnsupportedReasonMultipleContactsUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1multipleContactsUnsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReasonMultipleContactsUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1unsupportedMmiUssd/title",
          "value": "INStartCallContactUnsupportedReasonUnsupportedMmiUssd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1unsupportedMmiUssd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReasonUnsupportedMmiUssd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1noContactFound/title",
          "value": "INStartCallContactUnsupportedReasonNoContactFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1noContactFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReasonNoContactFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1noHandleForLabel/title",
          "value": "INStartCallContactUnsupportedReasonNoHandleForLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1noHandleForLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReasonNoHandleForLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1noCallHistoryForRedial/title",
          "value": "INStartCallContactUnsupportedReasonNoCallHistoryForRedial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1noCallHistoryForRedial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReasonNoCallHistoryForRedial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1requiringInAppAuthentication/title",
          "value": "INStartCallContactUnsupportedReasonRequiringInAppAuthentication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1requiringInAppAuthentication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReasonRequiringInAppAuthentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason/title",
          "value": "INStartCallContactUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1noUsableHandleForRedial/title",
          "value": "INStartCallContactUnsupportedReasonNoUsableHandleForRedial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1noUsableHandleForRedial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReasonNoUsableHandleForRedial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1invalidHandle/title",
          "value": "INStartCallContactUnsupportedReasonInvalidHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1invalidHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReasonInvalidHandle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/instartcallcontactunsupportedreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/instartcallcontactunsupportedreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
