{
  "abstract": [
    {
      "text": "Your app’s response to a start workout intent.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponse"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INStartWorkoutIntentResponse",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INStartWorkoutIntentResponse"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INStartWorkoutIntentResponse"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "INStartWorkoutIntentResponse"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponse"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to specify whether your app is able to start a workout. The response object contains only the response code that indicates whether to launch your app or whether there was a problem.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentHandling/confirm(intent:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentHandling/handle(intent:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods of your start workout handler object. For more information about implementing your handler object, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentResponse": {
      "abstract": [
        {
          "text": "Your response to an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/inintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntent": {
      "abstract": [
        {
          "text": "A request to start a workout for the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntent"
        }
      ],
      "role": "symbol",
      "title": "INStartWorkoutIntent",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentHandling": {
      "abstract": [
        {
          "text": "An interface that handles requests to start a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INStartWorkoutIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentHandling/confirm(intent:completion:)": {
      "abstract": [
        {
          "text": "Validates that your app is able to start the workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirm"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INStartWorkoutIntent",
          "text": "INStartWorkoutIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INStartWorkoutIntentResponse",
          "text": "INStartWorkoutIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentHandling/confirm(intent:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "confirmStartWorkout:completion:"
        }
      ],
      "role": "symbol",
      "title": "confirm(intent:completion:)",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintenthandling/confirm(intent:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentHandling/handle(intent:completion:)": {
      "abstract": [
        {
          "text": "Handles starting the workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INStartWorkoutIntent",
          "text": "INStartWorkoutIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INStartWorkoutIntentResponse",
          "text": "INStartWorkoutIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentHandling/handle(intent:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleStartWorkout:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handle(intent:completion:)",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintenthandling/handle(intent:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a start workout intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INStartWorkoutIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponse/code": {
      "abstract": [
        {
          "text": "The code that indicates whether you successfully handled the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INStartWorkoutIntentResponseCode",
          "text": "INStartWorkoutIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponse/code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "code"
        }
      ],
      "role": "symbol",
      "title": "code",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintentresponse/code"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponse/init(code:userActivity:)": {
      "abstract": [
        {
          "text": "Initializes the response object with the specified code and user activity object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INStartWorkoutIntentResponseCode",
          "text": "INStartWorkoutIntentResponseCode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserActivity",
          "text": "NSUserActivity"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponse/init(code:userActivity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCode:userActivity:"
        }
      ],
      "role": "symbol",
      "title": "init(code:userActivity:)",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintentresponse/init(code:useractivity:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode": {
      "abstract": [
        {
          "text": "Constants that indicate the response state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartWorkoutIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INStartWorkoutIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/instartworkoutintentresponsecode"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INIntentResponse"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Start-a-Workout",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentHandling",
        "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntent"
      ],
      "title": "Start a Workout"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-the-Response-Object",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponse/init(code:userActivity:)"
      ],
      "title": "Initializing the Response Object"
    },
    {
      "anchor": "Getting-the-Response-Code",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponse/code",
        "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode"
      ],
      "title": "Getting the Response Code"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INStartWorkoutIntentResponse"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializing-the-Response-Object",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponse/init(code:userActivity:)"
              ],
              "title": "Initializing the Response Object"
            },
            {
              "anchor": "Getting-the-Response-Code",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponse/code",
                "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentResponseCode"
              ],
              "title": "Getting the Response Code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INIntentResponse"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Start-a-Workout",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntentHandling",
                "doc://com.apple.sirikit/documentation/Intents/INStartWorkoutIntent"
              ],
              "title": "Start a Workout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INStartWorkoutIntentResponse"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentResponse",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INIntentResponse",
                    "text": "INIntentResponse"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentHandling~1confirm(intent:completion:)/title",
          "value": "confirmStartWorkout:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentHandling~1confirm(intent:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "confirmStartWorkout:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/title",
          "value": "INIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponse/title",
          "value": "INStartWorkoutIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentHandling/title",
          "value": "INStartWorkoutIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponse~1init(code:userActivity:)/title",
          "value": "initWithCode:userActivity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponse~1init(code:userActivity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCode:userActivity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode/title",
          "value": "INStartWorkoutIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntent/title",
          "value": "INStartWorkoutIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartWorkoutIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentHandling~1handle(intent:completion:)/title",
          "value": "handleStartWorkout:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentHandling~1handle(intent:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleStartWorkout:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponse~1code/title",
          "value": "code"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartWorkoutIntentResponse~1code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "code"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/instartworkoutintentresponse"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/instartworkoutintentresponse"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
