{
  "abstract": [
    {
      "text": "The handler interface for transferring money between accounts.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INTransferMoneyIntentHandling",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INTransferMoneyIntentHandling"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INTransferMoneyIntentHandling"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "message": "INTransferMoneyIntentHandling is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "message": "INTransferMoneyIntentHandling is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INTransferMoneyIntentHandling is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INTransferMoneyIntentHandling is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "4.0",
        "message": "INTransferMoneyIntentHandling is deprecated. There is no replacement.",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "INTransferMoneyIntentHandling"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INTransferMoneyIntentHandling"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the methods of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol to resolve, confirm, and handle requests to transfer money between accounts. Adopt this protocol in an object of your Intents extension that’s capable of handling the transfer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Siri delivers an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to your handler when the user asks to transfer money using your app. The provided intent object contains information about the amount to transfer and the accounts involved. Use the methods of this protocol to resolve the account information and initiate the transaction.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPaymentsDomainHandling": {
      "abstract": [
        {
          "text": "An interface for adopting all of the protocols in the payments domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPaymentsDomainHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPaymentsDomainHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPaymentsDomainHandling"
        }
      ],
      "role": "symbol",
      "title": "INPaymentsDomainHandling",
      "type": "topic",
      "url": "/documentation/intents/inpaymentsdomainhandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntent": {
      "abstract": [
        {
          "text": "A request to transfer money between two accounts.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INTransferMoneyIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INTransferMoneyIntent"
        }
      ],
      "role": "symbol",
      "title": "INTransferMoneyIntent",
      "type": "topic",
      "url": "/documentation/intents/intransfermoneyintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for transferring money between accounts.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INTransferMoneyIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INTransferMoneyIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INTransferMoneyIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/intransfermoneyintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/confirm(intent:completion:)": {
      "abstract": [
        {
          "text": "Confirms the transaction details and validates the transaciton.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confirm"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTransferMoneyIntent",
          "text": "INTransferMoneyIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTransferMoneyIntentResponse",
          "text": "INTransferMoneyIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/confirm(intent:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "confirmTransferMoney:completion:"
        }
      ],
      "role": "symbol",
      "title": "confirm(intent:completion:)",
      "type": "topic",
      "url": "/documentation/intents/intransfermoneyintenthandling/confirm(intent:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/handle(intent:completion:)": {
      "abstract": [
        {
          "text": "Handles the scheduling of the transfer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTransferMoneyIntent",
          "text": "INTransferMoneyIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTransferMoneyIntentResponse",
          "text": "INTransferMoneyIntentResponse"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/handle(intent:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleTransferMoney:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "handle(intent:completion:)",
      "type": "topic",
      "url": "/documentation/intents/intransfermoneyintenthandling/handle(intent:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveFromAccount(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the user account that’s the source of the funds.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveFromAccount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTransferMoneyIntent",
          "text": "INTransferMoneyIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPaymentAccountResolutionResult",
          "text": "INPaymentAccountResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveFromAccount(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveFromAccountForTransferMoney:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveFromAccount(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/intransfermoneyintenthandling/resolvefromaccount(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveToAccount(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the user account that’s the destination of the funds.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveToAccount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTransferMoneyIntent",
          "text": "INTransferMoneyIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPaymentAccountResolutionResult",
          "text": "INPaymentAccountResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveToAccount(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveToAccountForTransferMoney:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveToAccount(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/intransfermoneyintenthandling/resolvetoaccount(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveTransactionAmount(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the amount that the user wants to transfer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveTransactionAmount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTransferMoneyIntent",
          "text": "INTransferMoneyIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPaymentAmountResolutionResult",
          "text": "INPaymentAmountResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveTransactionAmount(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveTransactionAmountForTransferMoney:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveTransactionAmount(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/intransfermoneyintenthandling/resolvetransactionamount(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveTransactionNote(for:with:)": {
      "abstract": [
        {
          "text": "Resolves any custom notes associated with the transaction.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveTransactionNote"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTransferMoneyIntent",
          "text": "INTransferMoneyIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INStringResolutionResult",
          "text": "INStringResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveTransactionNote(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveTransactionNoteForTransferMoney:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveTransactionNote(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/intransfermoneyintenthandling/resolvetransactionnote(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveTransactionScheduledDate(for:with:)": {
      "abstract": [
        {
          "text": "Resolves the date on which the transfer is to occur.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveTransactionScheduledDate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INTransferMoneyIntent",
          "text": "INTransferMoneyIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INDateComponentsRangeResolutionResult",
          "text": "INDateComponentsRangeResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveTransactionScheduledDate(for:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveTransactionScheduledDateForTransferMoney:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveTransactionScheduledDate(for:with:)",
      "type": "topic",
      "url": "/documentation/intents/intransfermoneyintenthandling/resolvetransactionscheduleddate(for:with:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentResponse": {
      "abstract": [
        {
          "text": "Your app’s response to a request to transfer money.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INTransferMoneyIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INTransferMoneyIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INTransferMoneyIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/intransfermoneyintentresponse"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPaymentsDomainHandling"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Money-Transfers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntent",
        "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentResponse"
      ],
      "title": "Money Transfers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Resolving-the-Intent-Parameters",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveFromAccount(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveToAccount(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveTransactionAmount(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveTransactionScheduledDate(for:with:)",
        "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveTransactionNote(for:with:)"
      ],
      "title": "Resolving the Intent Parameters"
    },
    {
      "anchor": "Confirming-the-Response",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/confirm(intent:completion:)"
      ],
      "title": "Confirming the Response"
    },
    {
      "anchor": "Handling-the-Intent",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/handle(intent:completion:)"
      ],
      "title": "Handling the Intent"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INTransferMoneyIntentHandling"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTransferMoneyIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTransferMoneyIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Resolving-the-Intent-Parameters",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveFromAccount(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveToAccount(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveTransactionAmount(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveTransactionScheduledDate(for:with:)",
                "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/resolveTransactionNote(for:with:)"
              ],
              "title": "Resolving the Intent Parameters"
            },
            {
              "anchor": "Confirming-the-Response",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/confirm(intent:completion:)"
              ],
              "title": "Confirming the Response"
            },
            {
              "anchor": "Handling-the-Intent",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentHandling/handle(intent:completion:)"
              ],
              "title": "Handling the Intent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPaymentsDomainHandling"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Money-Transfers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntent",
                "doc://com.apple.sirikit/documentation/Intents/INTransferMoneyIntentResponse"
              ],
              "title": "Money Transfers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INTransferMoneyIntentHandling"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentResponse/title",
          "value": "INTransferMoneyIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTransferMoneyIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTransferMoneyIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentHandling/title",
          "value": "INTransferMoneyIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTransferMoneyIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTransferMoneyIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentHandling~1resolveTransactionAmount(for:with:)/title",
          "value": "resolveTransactionAmountForTransferMoney:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentHandling~1resolveTransactionAmount(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveTransactionAmountForTransferMoney:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentHandling~1resolveTransactionScheduledDate(for:with:)/title",
          "value": "resolveTransactionScheduledDateForTransferMoney:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentHandling~1resolveTransactionScheduledDate(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveTransactionScheduledDateForTransferMoney:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentHandling~1resolveFromAccount(for:with:)/title",
          "value": "resolveFromAccountForTransferMoney:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentHandling~1resolveFromAccount(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveFromAccountForTransferMoney:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentHandling~1resolveToAccount(for:with:)/title",
          "value": "resolveToAccountForTransferMoney:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentHandling~1resolveToAccount(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveToAccountForTransferMoney:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentHandling~1handle(intent:completion:)/title",
          "value": "handleTransferMoney:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentHandling~1handle(intent:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleTransferMoney:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentHandling~1resolveTransactionNote(for:with:)/title",
          "value": "resolveTransactionNoteForTransferMoney:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentHandling~1resolveTransactionNote(for:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveTransactionNoteForTransferMoney:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntent/title",
          "value": "INTransferMoneyIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INTransferMoneyIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INTransferMoneyIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentHandling~1confirm(intent:completion:)/title",
          "value": "confirmTransferMoney:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INTransferMoneyIntentHandling~1confirm(intent:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "confirmTransferMoney:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentsDomainHandling/title",
          "value": "INPaymentsDomainHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentsDomainHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentsDomainHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPaymentsDomainHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPaymentsDomainHandling"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/intransfermoneyintenthandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/intransfermoneyintenthandling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
