{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INUnsendMessagesIntentResponseCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INUnsendMessagesIntentResponseCode"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INUnsendMessagesIntentResponseCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INUnsendMessagesIntentResponseCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponseCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.sirikit/documentation/SiriKit/improving-interactions-between-siri-and-your-messaging-app"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntent"
        }
      ],
      "role": "symbol",
      "title": "INUnsendMessagesIntent",
      "type": "topic",
      "url": "/documentation/intents/inunsendmessagesintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentHandling": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INUnsendMessagesIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/inunsendmessagesintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentResponse"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentResponse"
        }
      ],
      "role": "symbol",
      "title": "INUnsendMessagesIntentResponse",
      "type": "topic",
      "url": "/documentation/intents/inunsendmessagesintentresponse"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INUnsendMessagesIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/inunsendmessagesintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INUnsendMessagesIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/inunsendmessagesintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureMessageNotFound": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureMessageNotFound"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureMessageNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentResponseCodeFailureMessageNotFound"
        }
      ],
      "role": "symbol",
      "title": "INUnsendMessagesIntentResponseCode.failureMessageNotFound",
      "type": "topic",
      "url": "/documentation/intents/inunsendmessagesintentresponsecode/failuremessagenotfound"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureMessageServiceNotAvailable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureMessageServiceNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureMessageServiceNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentResponseCodeFailureMessageServiceNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "INUnsendMessagesIntentResponseCode.failureMessageServiceNotAvailable",
      "type": "topic",
      "url": "/documentation/intents/inunsendmessagesintentresponsecode/failuremessageservicenotavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureMessageTypeUnsupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureMessageTypeUnsupported"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureMessageTypeUnsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentResponseCodeFailureMessageTypeUnsupported"
        }
      ],
      "role": "symbol",
      "title": "INUnsendMessagesIntentResponseCode.failureMessageTypeUnsupported",
      "type": "topic",
      "url": "/documentation/intents/inunsendmessagesintentresponsecode/failuremessagetypeunsupported"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failurePastUnsendTimeLimit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failurePastUnsendTimeLimit"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failurePastUnsendTimeLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentResponseCodeFailurePastUnsendTimeLimit"
        }
      ],
      "role": "symbol",
      "title": "INUnsendMessagesIntentResponseCode.failurePastUnsendTimeLimit",
      "type": "topic",
      "url": "/documentation/intents/inunsendmessagesintentresponsecode/failurepastunsendtimelimit"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INUnsendMessagesIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/inunsendmessagesintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureRequiringInAppAuthentication": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringInAppAuthentication"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureRequiringInAppAuthentication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentResponseCodeFailureRequiringInAppAuthentication"
        }
      ],
      "role": "symbol",
      "title": "INUnsendMessagesIntentResponseCode.failureRequiringInAppAuthentication",
      "type": "topic",
      "url": "/documentation/intents/inunsendmessagesintentresponsecode/failurerequiringinappauthentication"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureUnsupportedOnService": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureUnsupportedOnService"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureUnsupportedOnService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentResponseCodeFailureUnsupportedOnService"
        }
      ],
      "role": "symbol",
      "title": "INUnsendMessagesIntentResponseCode.failureUnsupportedOnService",
      "type": "topic",
      "url": "/documentation/intents/inunsendmessagesintentresponsecode/failureunsupportedonservice"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/inProgress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProgress"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/inProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentResponseCodeInProgress"
        }
      ],
      "role": "symbol",
      "title": "INUnsendMessagesIntentResponseCode.inProgress",
      "type": "topic",
      "url": "/documentation/intents/inunsendmessagesintentresponsecode/inprogress"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/inunsendmessagesintentresponsecode/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/ready": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INUnsendMessagesIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/inunsendmessagesintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/success": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentResponseCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "INUnsendMessagesIntentResponseCode.success",
      "type": "topic",
      "url": "/documentation/intents/inunsendmessagesintentresponsecode/success"
    },
    "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/unspecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUnsendMessagesIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INUnsendMessagesIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/inunsendmessagesintentresponsecode/unspecified"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/improving-interactions-between-siri-and-your-messaging-app": {
      "abstract": [
        {
          "text": "Donate app-specific content, use Siri’s contact suggestions, and adopt the latest platform features to create a more consistent messaging experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/improving-interactions-between-siri-and-your-messaging-app",
      "kind": "article",
      "role": "article",
      "title": "Improving interactions between Siri and your messaging app",
      "type": "topic",
      "url": "/documentation/sirikit/improving-interactions-between-siri-and-your-messaging-app"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Unsending-a-Message",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntent",
        "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponse",
        "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentHandling"
      ],
      "title": "Unsending a Message"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureMessageNotFound",
        "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureMessageServiceNotAvailable",
        "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureMessageTypeUnsupported",
        "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failurePastUnsendTimeLimit",
        "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureRequiringAppLaunch",
        "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureRequiringInAppAuthentication",
        "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureUnsupportedOnService",
        "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/inProgress",
        "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/success",
        "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/unspecified"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INUnsendMessagesIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureMessageNotFound",
                "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureMessageServiceNotAvailable",
                "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureMessageTypeUnsupported",
                "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failurePastUnsendTimeLimit",
                "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureRequiringAppLaunch",
                "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureRequiringInAppAuthentication",
                "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/failureUnsupportedOnService",
                "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/inProgress",
                "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/success",
                "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponseCode/unspecified"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Unsending-a-Message",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntent",
                "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentResponse",
                "doc://com.apple.sirikit/documentation/Intents/INUnsendMessagesIntentHandling"
              ],
              "title": "Unsending a Message"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INUnsendMessagesIntentResponseCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1unspecified/title",
          "value": "INUnsendMessagesIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1failureUnsupportedOnService/title",
          "value": "INUnsendMessagesIntentResponseCodeFailureUnsupportedOnService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1failureUnsupportedOnService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponseCodeFailureUnsupportedOnService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INUnsendMessagesIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode/title",
          "value": "INUnsendMessagesIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentHandling/title",
          "value": "INUnsendMessagesIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1success/title",
          "value": "INUnsendMessagesIntentResponseCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponseCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1ready/title",
          "value": "INUnsendMessagesIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1failureRequiringInAppAuthentication/title",
          "value": "INUnsendMessagesIntentResponseCodeFailureRequiringInAppAuthentication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1failureRequiringInAppAuthentication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponseCodeFailureRequiringInAppAuthentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1failureMessageServiceNotAvailable/title",
          "value": "INUnsendMessagesIntentResponseCodeFailureMessageServiceNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1failureMessageServiceNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponseCodeFailureMessageServiceNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponse/title",
          "value": "INUnsendMessagesIntentResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1failure/title",
          "value": "INUnsendMessagesIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponseCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntent/title",
          "value": "INUnsendMessagesIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1failurePastUnsendTimeLimit/title",
          "value": "INUnsendMessagesIntentResponseCodeFailurePastUnsendTimeLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1failurePastUnsendTimeLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponseCodeFailurePastUnsendTimeLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1failureMessageTypeUnsupported/title",
          "value": "INUnsendMessagesIntentResponseCodeFailureMessageTypeUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1failureMessageTypeUnsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponseCodeFailureMessageTypeUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1failureMessageNotFound/title",
          "value": "INUnsendMessagesIntentResponseCodeFailureMessageNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1failureMessageNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponseCodeFailureMessageNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1inProgress/title",
          "value": "INUnsendMessagesIntentResponseCodeInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INUnsendMessagesIntentResponseCode~1inProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUnsendMessagesIntentResponseCodeInProgress"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inunsendmessagesintentresponsecode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inunsendmessagesintentresponsecode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
