{
  "abstract": [
    {
      "text": "Possible usages for a custom vocabulary term.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INVocabularyStringType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INVocabularyStringType"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INVocabularyStringType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "INVocabularyStringType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INVocabularyStringType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabulary/removeAllVocabularyStrings()": {
      "abstract": [
        {
          "text": "Removes all user-specific vocabulary strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllVocabularyStrings"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabulary/removeAllVocabularyStrings()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllVocabularyStrings"
        }
      ],
      "role": "symbol",
      "title": "removeAllVocabularyStrings()",
      "type": "topic",
      "url": "/documentation/intents/invocabulary/removeallvocabularystrings()"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabulary/setVocabulary(_:of:)": {
      "abstract": [
        {
          "text": "Registers the specified vocabulary strings with the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setVocabulary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOrderedSet",
          "text": "NSOrderedSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INVocabularyStringType",
          "text": "INVocabularyStringType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabulary/setVocabulary(_:of:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setVocabulary:ofType:"
        }
      ],
      "role": "symbol",
      "title": "setVocabulary(_:of:)",
      "type": "topic",
      "url": "/documentation/intents/invocabulary/setvocabulary(_:of:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabulary/setVocabularyStrings(_:of:)": {
      "abstract": [
        {
          "text": "Registers the specified vocabulary strings with the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setVocabularyStrings"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOrderedSet",
          "text": "NSOrderedSet"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INVocabularyStringType",
          "text": "INVocabularyStringType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabulary/setVocabularyStrings(_:of:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setVocabularyStrings:ofType:"
        }
      ],
      "role": "symbol",
      "title": "setVocabularyStrings(_:of:)",
      "type": "topic",
      "url": "/documentation/intents/invocabulary/setvocabularystrings(_:of:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType": {
      "abstract": [
        {
          "text": "Possible usages for a custom vocabulary term.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INVocabularyStringType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringType"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/carName": {
      "abstract": [
        {
          "text": "A name that identifies the user’s car.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "carName"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/carName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringTypeCarName"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType.carName",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype/carname"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/carProfileName": {
      "abstract": [
        {
          "text": "The name of a vehicle configuration profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "carProfileName"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/carProfileName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringTypeCarProfileName"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType.carProfileName",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype/carprofilename"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/contactGroupName": {
      "abstract": [
        {
          "text": "The name of a group of contacts, as a person would say it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contactGroupName"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/contactGroupName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringTypeContactGroupName"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType.contactGroupName",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype/contactgroupname"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/contactName": {
      "abstract": [
        {
          "text": "The name of an app-specific contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contactName"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/contactName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringTypeContactName"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType.contactName",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype/contactname"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype/init(rawvalue:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaAudiobookAuthorName": {
      "abstract": [
        {
          "text": "The name of an audiobook’s author.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaAudiobookAuthorName"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaAudiobookAuthorName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringTypeMediaAudiobookAuthorName"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType.mediaAudiobookAuthorName",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype/mediaaudiobookauthorname"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaAudiobookTitle": {
      "abstract": [
        {
          "text": "The name or title of an audiobook.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaAudiobookTitle"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaAudiobookTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringTypeMediaAudiobookTitle"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType.mediaAudiobookTitle",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype/mediaaudiobooktitle"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaMusicArtistName": {
      "abstract": [
        {
          "text": "The name of a musical artist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaMusicArtistName"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaMusicArtistName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringTypeMediaMusicArtistName"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType.mediaMusicArtistName",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype/mediamusicartistname"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaPlaylistTitle": {
      "abstract": [
        {
          "text": "The name or title of a playlist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaPlaylistTitle"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaPlaylistTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringTypeMediaPlaylistTitle"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType.mediaPlaylistTitle",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype/mediaplaylisttitle"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaShowTitle": {
      "abstract": [
        {
          "text": "The name or title of a podcast or radio show.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaShowTitle"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaShowTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringTypeMediaShowTitle"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType.mediaShowTitle",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype/mediashowtitle"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/notebookItemGroupName": {
      "abstract": [
        {
          "text": "The title of a group (or folder) containing the user’s notes or task lists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notebookItemGroupName"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/notebookItemGroupName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringTypeNotebookItemGroupName"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType.notebookItemGroupName",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype/notebookitemgroupname"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/notebookItemTitle": {
      "abstract": [
        {
          "text": "The title of a note, task, or task list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notebookItemTitle"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/notebookItemTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringTypeNotebookItemTitle"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType.notebookItemTitle",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype/notebookitemtitle"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/paymentsAccountNickname": {
      "abstract": [
        {
          "text": "The user-given nickname for a bank account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentsAccountNickname"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/paymentsAccountNickname",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringTypePaymentsAccountNickname"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType.paymentsAccountNickname",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype/paymentsaccountnickname"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/paymentsOrganizationName": {
      "abstract": [
        {
          "text": "The name of the bank or company that holds the user’s account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paymentsOrganizationName"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/paymentsOrganizationName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringTypePaymentsOrganizationName"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType.paymentsOrganizationName",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype/paymentsorganizationname"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/photoAlbumName": {
      "abstract": [
        {
          "text": "The user-given name assigned to a collection of photographs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoAlbumName"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/photoAlbumName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringTypePhotoAlbumName"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType.photoAlbumName",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype/photoalbumname"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/photoTag": {
      "abstract": [
        {
          "text": "A user-defined keyword associated with an image or images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoTag"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/photoTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringTypePhotoTag"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType.photoTag",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype/phototag"
    },
    "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/workoutActivityName": {
      "abstract": [
        {
          "text": "The user-given name assigned to a workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workoutActivityName"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/workoutActivityName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INVocabularyStringTypeWorkoutActivityName"
        }
      ],
      "role": "symbol",
      "title": "INVocabularyStringType.workoutActivityName",
      "type": "topic",
      "url": "/documentation/intents/invocabularystringtype/workoutactivityname"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Updating-the-User-Specific-Vocabulary",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INVocabulary/setVocabulary(_:of:)",
        "doc://com.apple.sirikit/documentation/Intents/INVocabulary/setVocabularyStrings(_:of:)",
        "doc://com.apple.sirikit/documentation/Intents/INVocabulary/removeAllVocabularyStrings()"
      ],
      "title": "Updating the User-Specific Vocabulary"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/contactName",
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/contactGroupName",
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/photoTag",
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/photoAlbumName",
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/workoutActivityName",
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/carProfileName",
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/carName",
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/paymentsOrganizationName",
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/paymentsAccountNickname",
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/notebookItemTitle",
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/notebookItemGroupName",
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaPlaylistTitle",
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaMusicArtistName",
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaAudiobookTitle",
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaAudiobookAuthorName",
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaShowTitle"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INVocabularyStringType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/contactName",
                "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/contactGroupName",
                "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/photoTag",
                "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/photoAlbumName",
                "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/workoutActivityName",
                "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/carProfileName",
                "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/carName",
                "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/paymentsOrganizationName",
                "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/paymentsAccountNickname",
                "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/notebookItemTitle",
                "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/notebookItemGroupName",
                "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaPlaylistTitle",
                "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaMusicArtistName",
                "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaAudiobookTitle",
                "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaAudiobookAuthorName",
                "doc://com.apple.sirikit/documentation/Intents/INVocabularyStringType/mediaShowTitle"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Updating-the-User-Specific-Vocabulary",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INVocabulary/setVocabulary(_:of:)",
                "doc://com.apple.sirikit/documentation/Intents/INVocabulary/setVocabularyStrings(_:of:)",
                "doc://com.apple.sirikit/documentation/Intents/INVocabulary/removeAllVocabularyStrings()"
              ],
              "title": "Updating the User-Specific Vocabulary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INVocabularyStringType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1notebookItemTitle/title",
          "value": "INVocabularyStringTypeNotebookItemTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1notebookItemTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringTypeNotebookItemTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1photoAlbumName/title",
          "value": "INVocabularyStringTypePhotoAlbumName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1photoAlbumName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringTypePhotoAlbumName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1carProfileName/title",
          "value": "INVocabularyStringTypeCarProfileName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1carProfileName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringTypeCarProfileName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1paymentsOrganizationName/title",
          "value": "INVocabularyStringTypePaymentsOrganizationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1paymentsOrganizationName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringTypePaymentsOrganizationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1mediaAudiobookTitle/title",
          "value": "INVocabularyStringTypeMediaAudiobookTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1mediaAudiobookTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringTypeMediaAudiobookTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1carName/title",
          "value": "INVocabularyStringTypeCarName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1carName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringTypeCarName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1mediaMusicArtistName/title",
          "value": "INVocabularyStringTypeMediaMusicArtistName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1mediaMusicArtistName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringTypeMediaMusicArtistName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1photoTag/title",
          "value": "INVocabularyStringTypePhotoTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1photoTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringTypePhotoTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary~1removeAllVocabularyStrings()/title",
          "value": "removeAllVocabularyStrings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary~1removeAllVocabularyStrings()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAllVocabularyStrings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1mediaShowTitle/title",
          "value": "INVocabularyStringTypeMediaShowTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1mediaShowTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringTypeMediaShowTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1notebookItemGroupName/title",
          "value": "INVocabularyStringTypeNotebookItemGroupName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1notebookItemGroupName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringTypeNotebookItemGroupName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1contactGroupName/title",
          "value": "INVocabularyStringTypeContactGroupName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1contactGroupName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringTypeContactGroupName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary~1setVocabulary(_:of:)/title",
          "value": "setVocabulary:ofType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary~1setVocabulary(_:of:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setVocabulary:ofType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1paymentsAccountNickname/title",
          "value": "INVocabularyStringTypePaymentsAccountNickname"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1paymentsAccountNickname/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringTypePaymentsAccountNickname"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary~1setVocabularyStrings(_:of:)/title",
          "value": "setVocabularyStrings:ofType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabulary~1setVocabularyStrings(_:of:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setVocabularyStrings:ofType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1workoutActivityName/title",
          "value": "INVocabularyStringTypeWorkoutActivityName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1workoutActivityName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringTypeWorkoutActivityName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1contactName/title",
          "value": "INVocabularyStringTypeContactName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1contactName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringTypeContactName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType/title",
          "value": "INVocabularyStringType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1mediaAudiobookAuthorName/title",
          "value": "INVocabularyStringTypeMediaAudiobookAuthorName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1mediaAudiobookAuthorName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringTypeMediaAudiobookAuthorName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1mediaPlaylistTitle/title",
          "value": "INVocabularyStringTypeMediaPlaylistTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INVocabularyStringType~1mediaPlaylistTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INVocabularyStringTypeMediaPlaylistTitle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/invocabularystringtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/invocabularystringtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
