{
  "abstract": [
    {
      "text": "The relative inter-glyph spacing value as a number object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey/width"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSFontWidthTrait",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "width"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
        "text": "NSFontDescriptor"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSFontDescriptorTraitKey",
        "text": "TraitKey"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFontWidthTrait"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "width"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "width"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
              "text": "NSFontDescriptor"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSFontDescriptorTraitKey",
              "text": "TraitKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this key is an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. The valid value range is from ",
              "type": "text"
            },
            {
              "code": "-1.0",
              "type": "codeVoice"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "1.0",
              "type": "codeVoice"
            },
            {
              "text": ". The value of ",
              "type": "text"
            },
            {
              "code": "0.0",
              "type": "codeVoice"
            },
            {
              "text": " corresponds to the regular glyph spacing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor": {
      "abstract": [
        {
          "text": "A dictionary of attributes that describe a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontDescriptor"
        }
      ],
      "role": "symbol",
      "title": "NSFontDescriptor",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey": {
      "abstract": [
        {
          "text": "Constants that can be used as keys to retrieve information about a font descriptor from its trait dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TraitKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TraitKey"
        }
      ],
      "role": "symbol",
      "title": "NSFontDescriptor.TraitKey",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/traitkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey/slant": {
      "abstract": [
        {
          "text": "The relative slant angle value as a number object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slant"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorTraitKey",
          "text": "TraitKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey/slant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontSlantTrait"
        }
      ],
      "role": "symbol",
      "title": "slant",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/traitkey/slant"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey/symbolic": {
      "abstract": [
        {
          "text": "The symbolic traits value as a number object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symbolic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorTraitKey",
          "text": "TraitKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey/symbolic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontSymbolicTrait"
        }
      ],
      "role": "symbol",
      "title": "symbolic",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/traitkey/symbolic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey/weight": {
      "abstract": [
        {
          "text": "The normalized weight value as a number object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "weight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorTraitKey",
          "text": "TraitKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey/weight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontWeightTrait"
        }
      ],
      "role": "symbol",
      "title": "weight",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/traitkey/weight"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey/width": {
      "abstract": [
        {
          "text": "The relative inter-glyph spacing value as a number object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFontDescriptor",
          "text": "NSFontDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontDescriptorTraitKey",
          "text": "TraitKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey/width",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontWidthTrait"
        }
      ],
      "role": "symbol",
      "title": "width",
      "type": "topic",
      "url": "/documentation/appkit/nsfontdescriptor/traitkey/width"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Trait-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey/symbolic",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey/weight",
        "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey/slant"
      ],
      "title": "Trait Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFontWidthTrait"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontWidthTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Trait-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey/symbolic",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey/weight",
                "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey/slant"
              ],
              "title": "Trait Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFontDescriptor/TraitKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSFontDescriptorTraitKey",
                    "text": "NSFontDescriptorTraitKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFontWidthTrait"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1TraitKey~1weight/title",
          "value": "NSFontWeightTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1TraitKey~1weight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontWeightTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1TraitKey/title",
          "value": "NSFontDescriptorTraitKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1TraitKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorTraitKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1TraitKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptorTraitKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1TraitKey~1symbolic/title",
          "value": "NSFontSymbolicTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1TraitKey~1symbolic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontSymbolicTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1TraitKey~1slant/title",
          "value": "NSFontSlantTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1TraitKey~1slant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontSlantTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1TraitKey~1width/title",
          "value": "NSFontWidthTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor~1TraitKey~1width/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontWidthTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/title",
          "value": "NSFontDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFontDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfontdescriptor/traitkey/width"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfontdescriptor/traitkey/width"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
