{
  "abstract": [
    {
      "text": "Returns the Virtio console port at the specified index.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization",
        "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioConsolePortArray"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioConsolePortArray/subscript(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)VZVirtioConsolePortArray(im)objectAtIndexedSubscript:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "subscript"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)VZVirtioConsolePort",
        "text": "VZVirtioConsolePort"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "objectAtIndexedSubscript:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Subscript",
    "symbolKind": "subscript",
    "title": "subscript(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "subscript"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "internalParam",
              "text": "portIndex"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioConsolePort",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)VZVirtioConsolePort",
              "text": "VZVirtioConsolePort"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The index of the port to return, if present.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "portIndex"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioConsolePort",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " port, or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if the index is outside the bounds of the array.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioConsolePort": {
      "abstract": [
        {
          "text": "A class that represents a Virtio console port in a VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioConsolePort"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioConsolePort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioConsolePort"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioConsolePort",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtioconsoleport"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioConsolePortArray": {
      "abstract": [
        {
          "text": "A class that represents a collection of Virtio console ports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZVirtioConsolePortArray"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioConsolePortArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZVirtioConsolePortArray"
        }
      ],
      "role": "symbol",
      "title": "VZVirtioConsolePortArray",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtioconsoleportarray"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioConsolePortArray/subscript(_:)": {
      "abstract": [
        {
          "text": "Returns the Virtio console port at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "subscript"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)VZVirtioConsolePort",
          "text": "VZVirtioConsolePort"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioConsolePortArray/subscript(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectAtIndexedSubscript:"
        }
      ],
      "role": "symbol",
      "title": "subscript(_:)",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtioconsoleportarray/subscript(_:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "objectAtIndexedSubscript:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectAtIndexedSubscript:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.virtualization/documentation/Virtualization",
                "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioConsolePortArray"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioConsolePort",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)VZVirtioConsolePort",
                    "text": "VZVirtioConsolePort"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "objectAtIndexedSubscript:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "portIndex"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The index of the port to return, if present.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "portIndex"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtioConsolePort",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " port, or ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if the index is outside the bounds of the array.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioConsolePort/title",
          "value": "VZVirtioConsolePort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioConsolePort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioConsolePort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioConsolePort/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioConsolePort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioConsolePortArray~1subscript(_:)/title",
          "value": "objectAtIndexedSubscript:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioConsolePortArray~1subscript(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "objectAtIndexedSubscript:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioConsolePortArray/title",
          "value": "VZVirtioConsolePortArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioConsolePortArray/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioConsolePortArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtioConsolePortArray/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZVirtioConsolePortArray"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzvirtioconsoleportarray/subscript(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/vzvirtioconsoleportarray/subscript(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
