{
  "abstract": [
    {
      "text": "The experience controller for this view controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/experienceController"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVKit",
    "externalID": "s:So22AVPlayerViewControllerC5AVKitE010experienceC0AC012AVExperienceC0Cvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "experienceController"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:5AVKit22AVExperienceControllerC",
        "text": "AVExperienceController"
      }
    ],
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "experienceController"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@preconcurrency"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "experienceController"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avkit/documentation/AVKit/AVExperienceController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5AVKit22AVExperienceControllerC",
              "text": "AVExperienceController"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use an experience controller to transition a player to different experiences and observe experience transitions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The use of the experience controller is mutually exclusive with a view controller’s existing API for managing the experience. After accessing the ",
              "type": "text"
            },
            {
              "code": "experienceController",
              "type": "codeVoice"
            },
            {
              "text": " property, those methods will log an error and have no effect. Attempting to access this property may fail if these mutually-exclusive properties and methods have been used.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVExperienceController": {
      "abstract": [
        {
          "text": "An object that controls video experiences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVExperienceController"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVExperienceController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVExperienceController"
        }
      ],
      "role": "symbol",
      "title": "AVExperienceController",
      "type": "topic",
      "url": "/documentation/avkit/avexperiencecontroller"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController": {
      "abstract": [
        {
          "text": "A view controller that displays content from a player and presents a native user interface to control playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerViewController"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerViewController"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerViewController",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewcontroller"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/contextualActions": {
      "abstract": [
        {
          "text": "An array of action controls to present contextually during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contextualActions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAction",
          "text": "UIAction"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/contextualActions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contextualActions"
        }
      ],
      "role": "symbol",
      "title": "contextualActions",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewcontroller/contextualactions"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/contextualActionsInfoView": {
      "abstract": [
        {
          "text": "A view the system shows adjacent to the contextual actions that’s suitable for showing related information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contextualActionsInfoView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/contextualActionsInfoView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contextualActionsInfoView"
        }
      ],
      "role": "symbol",
      "title": "contextualActionsInfoView",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewcontroller/contextualactionsinfoview"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/contextualActionsPreviewImage": {
      "abstract": [
        {
          "text": "An image to show alongside the contextual actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contextualActionsPreviewImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/contextualActionsPreviewImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contextualActionsPreviewImage"
        }
      ],
      "role": "symbol",
      "title": "contextualActionsPreviewImage",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewcontroller/contextualactionspreviewimage"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/customInfoViewControllers": {
      "abstract": [
        {
          "text": "An array of view controllers to display as content tabs in the player user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customInfoViewControllers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/customInfoViewControllers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customInfoViewControllers"
        }
      ],
      "role": "symbol",
      "title": "customInfoViewControllers",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewcontroller/custominfoviewcontrollers"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/experienceController": {
      "abstract": [
        {
          "text": "The experience controller for this view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "experienceController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5AVKit22AVExperienceControllerC",
          "text": "AVExperienceController"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/experienceController",
      "kind": "symbol",
      "role": "symbol",
      "title": "experienceController",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewcontroller/experiencecontroller"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/groupExperienceCoordinator": {
      "abstract": [
        {
          "text": "The group experience coordinator for this view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groupExperienceCoordinator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@AVKit@objc(cs)AVGroupExperienceCoordinator",
          "text": "AVGroupExperienceCoordinator"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/groupExperienceCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "groupExperienceCoordinator"
        }
      ],
      "role": "symbol",
      "title": "groupExperienceCoordinator",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewcontroller/groupexperiencecoordinator"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/infoViewActions": {
      "abstract": [
        {
          "text": "An array of actions to present in the Info content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "infoViewActions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAction",
          "text": "UIAction"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/infoViewActions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "infoViewActions"
        }
      ],
      "role": "symbol",
      "title": "infoViewActions",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewcontroller/infoviewactions"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/requiresMonoscopicViewingMode": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to permit playback of 2D video content only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiresMonoscopicViewingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/requiresMonoscopicViewingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requiresMonoscopicViewingMode"
        }
      ],
      "role": "symbol",
      "title": "requiresMonoscopicViewingMode",
      "type": "topic",
      "url": "/documentation/avkit/avplayerviewcontroller/requiresmonoscopicviewingmode"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-visionOS-Player-UI",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/infoViewActions",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/customInfoViewControllers",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/contextualActions",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/contextualActionsInfoView",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/contextualActionsPreviewImage",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/requiresMonoscopicViewingMode",
        "doc://com.apple.avkit/documentation/AVKit/AVPlayerViewController/groupExperienceCoordinator"
      ],
      "title": "Configuring the visionOS Player UI"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController~1customInfoViewControllers/title",
          "value": "customInfoViewControllers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController~1customInfoViewControllers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "customInfoViewControllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController~1contextualActionsInfoView/title",
          "value": "contextualActionsInfoView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController~1contextualActionsInfoView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contextualActionsInfoView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController~1requiresMonoscopicViewingMode/title",
          "value": "requiresMonoscopicViewingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController~1requiresMonoscopicViewingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requiresMonoscopicViewingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController~1contextualActionsPreviewImage/title",
          "value": "contextualActionsPreviewImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController~1contextualActionsPreviewImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contextualActionsPreviewImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController~1groupExperienceCoordinator/title",
          "value": "groupExperienceCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController~1groupExperienceCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "groupExperienceCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController~1infoViewActions/title",
          "value": "infoViewActions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController~1infoViewActions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "infoViewActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController~1contextualActions/title",
          "value": "contextualActions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController~1contextualActions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contextualActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/title",
          "value": "AVPlayerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVPlayerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/avplayerviewcontroller/experiencecontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
