{
  "abstract": [
    {
      "text": "An error code that indicates an attempt to perform an operation that isn’t allowed while Siri is recording.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/siriIsRecording"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVAudioSessionErrorCode@AVAudioSessionErrorCodeSiriIsRecording",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "siriIsRecording"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioSessionErrorCodeSiriIsRecording"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVAudioSession.ErrorCode.siriIsRecording"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "siriIsRecording"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode": {
      "abstract": [
        {
          "text": "Codes that describe error conditions that may occur when performing audio session operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ErrorCode"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.ErrorCode",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/avaudiosession/errorcode"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/badParam": {
      "abstract": [
        {
          "text": "An error code that indicates an attempt to set a property to an illegal value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badParam"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/badParam",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionErrorCodeBadParam"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.ErrorCode.badParam",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/avaudiosession/errorcode/badparam"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/cannotInterruptOthers": {
      "abstract": [
        {
          "text": "An error code that indictates an attempt to make a nonmixable audio session active while the app was in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cannotInterruptOthers"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/cannotInterruptOthers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionErrorCodeCannotInterruptOthers"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.ErrorCode.cannotInterruptOthers",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/avaudiosession/errorcode/cannotinterruptothers"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/cannotStartPlaying": {
      "abstract": [
        {
          "text": "An error code that indicates an attempt to start audio playback when it wasn’t allowed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cannotStartPlaying"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/cannotStartPlaying",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionErrorCodeCannotStartPlaying"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.ErrorCode.cannotStartPlaying",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/avaudiosession/errorcode/cannotstartplaying"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/cannotStartRecording": {
      "abstract": [
        {
          "text": "An error code that indicates an attempt to start audio recording, but the operation failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cannotStartRecording"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/cannotStartRecording",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionErrorCodeCannotStartRecording"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.ErrorCode.cannotStartRecording",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/avaudiosession/errorcode/cannotstartrecording"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/expiredSession": {
      "abstract": [
        {
          "text": "An error code that indicates that an operation failed because the system deallocated the associated session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expiredSession"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/expiredSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionErrorCodeExpiredSession"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.ErrorCode.expiredSession",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/avaudiosession/errorcode/expiredsession"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/incompatibleCategory": {
      "abstract": [
        {
          "text": "An error code that indicates an attempt to perform an operation that the current audio session category doesn’t support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incompatibleCategory"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/incompatibleCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionErrorCodeIncompatibleCategory"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.ErrorCode.incompatibleCategory",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/avaudiosession/errorcode/incompatiblecategory"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/insufficientPriority": {
      "abstract": [
        {
          "text": "An error code that indicates the app isn’t allowed to set the audio category because it’s in use by another app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientPriority"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/insufficientPriority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionErrorCodeInsufficientPriority"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.ErrorCode.insufficientPriority",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/avaudiosession/errorcode/insufficientpriority"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/isBusy": {
      "abstract": [
        {
          "text": "An error code that indicates an attempt to deactivate the audio session while it’s still playing or recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isBusy"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/isBusy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionErrorCodeIsBusy"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.ErrorCode.isBusy",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/avaudiosession/errorcode/isbusy"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/mediaServicesFailed": {
      "abstract": [
        {
          "text": "An error code that indictates an attempt to use the audio session during or after a Media Services failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaServicesFailed"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/mediaServicesFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionErrorCodeMediaServicesFailed"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.ErrorCode.mediaServicesFailed",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/avaudiosession/errorcode/mediaservicesfailed"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/missingEntitlement": {
      "abstract": [
        {
          "text": "An error code that indicates an attempt to perform an operation for which the app doesn’t have the required entitlements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingEntitlement"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/missingEntitlement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionErrorCodeMissingEntitlement"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.ErrorCode.missingEntitlement",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/avaudiosession/errorcode/missingentitlement"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/none": {
      "abstract": [
        {
          "text": "An error code that indicates the operation succeeded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionErrorCodeNone"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.ErrorCode.none",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/avaudiosession/errorcode/none"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/resourceNotAvailable": {
      "abstract": [
        {
          "text": "An error code that indicates that an operation failed because the device doesn’t have sufficient hardware resources to complete the action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceNotAvailable"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/resourceNotAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionErrorCodeResourceNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.ErrorCode.resourceNotAvailable",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/avaudiosession/errorcode/resourcenotavailable"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/sessionNotActive": {
      "abstract": [
        {
          "text": "An error code that indicates the operation failed because the session isn’t active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionNotActive"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/sessionNotActive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionErrorCodeSessionNotActive"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.ErrorCode.sessionNotActive",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/avaudiosession/errorcode/sessionnotactive"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/siriIsRecording": {
      "abstract": [
        {
          "text": "An error code that indicates an attempt to perform an operation that isn’t allowed while Siri is recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "siriIsRecording"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/siriIsRecording",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionErrorCodeSiriIsRecording"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.ErrorCode.siriIsRecording",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/avaudiosession/errorcode/siriisrecording"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/unspecified": {
      "abstract": [
        {
          "text": "An error code that indicates an unspecified error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionErrorCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.ErrorCode.unspecified",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/avaudiosession/errorcode/unspecified"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/none",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/badParam",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/cannotInterruptOthers",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/cannotStartPlaying",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/cannotStartRecording",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/expiredSession",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/incompatibleCategory",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/isBusy",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/mediaServicesFailed",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/missingEntitlement",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/resourceNotAvailable",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/sessionNotActive",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/unspecified",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/insufficientPriority"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioSessionErrorCodeSiriIsRecording"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCodeSiriIsRecording"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/none",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/badParam",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/cannotInterruptOthers",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/cannotStartPlaying",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/cannotStartRecording",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/expiredSession",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/incompatibleCategory",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/isBusy",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/mediaServicesFailed",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/missingEntitlement",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/resourceNotAvailable",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/sessionNotActive",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/unspecified",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AVAudioSession/ErrorCode/insufficientPriority"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVAudioSessionErrorCodeSiriIsRecording"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1cannotStartPlaying/title",
          "value": "AVAudioSessionErrorCodeCannotStartPlaying"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1cannotStartPlaying/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCodeCannotStartPlaying"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1resourceNotAvailable/title",
          "value": "AVAudioSessionErrorCodeResourceNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1resourceNotAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCodeResourceNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1expiredSession/title",
          "value": "AVAudioSessionErrorCodeExpiredSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1expiredSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCodeExpiredSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1mediaServicesFailed/title",
          "value": "AVAudioSessionErrorCodeMediaServicesFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1mediaServicesFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCodeMediaServicesFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1missingEntitlement/title",
          "value": "AVAudioSessionErrorCodeMissingEntitlement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1missingEntitlement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCodeMissingEntitlement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode/title",
          "value": "AVAudioSessionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1none/title",
          "value": "AVAudioSessionErrorCodeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCodeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1cannotInterruptOthers/title",
          "value": "AVAudioSessionErrorCodeCannotInterruptOthers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1cannotInterruptOthers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCodeCannotInterruptOthers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1siriIsRecording/title",
          "value": "AVAudioSessionErrorCodeSiriIsRecording"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1siriIsRecording/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCodeSiriIsRecording"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1cannotStartRecording/title",
          "value": "AVAudioSessionErrorCodeCannotStartRecording"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1cannotStartRecording/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCodeCannotStartRecording"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1badParam/title",
          "value": "AVAudioSessionErrorCodeBadParam"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1badParam/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCodeBadParam"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1sessionNotActive/title",
          "value": "AVAudioSessionErrorCodeSessionNotActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1sessionNotActive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCodeSessionNotActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1unspecified/title",
          "value": "AVAudioSessionErrorCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1isBusy/title",
          "value": "AVAudioSessionErrorCodeIsBusy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1isBusy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCodeIsBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1incompatibleCategory/title",
          "value": "AVAudioSessionErrorCodeIncompatibleCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1incompatibleCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCodeIncompatibleCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1insufficientPriority/title",
          "value": "AVAudioSessionErrorCodeInsufficientPriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AVAudioSession~1ErrorCode~1insufficientPriority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionErrorCodeInsufficientPriority"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/avaudiosession/errorcode/siriisrecording"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/avaudiosession/errorcode/siriisrecording"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
