{
  "abstract": [
    {
      "text": "Initializes a newly created calendar chooser.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkitui/documentation/EventKitUI",
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser/init(selectionStyle:displayStyle:eventStore:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)EKCalendarChooser(im)initWithSelectionStyle:displayStyle:eventStore:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "selectionStyle"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@EKCalendarChooserSelectionStyle",
        "text": "EKCalendarChooserSelectionStyle"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "displayStyle"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@EKCalendarChooserDisplayStyle",
        "text": "EKCalendarChooserDisplayStyle"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "eventStore"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)EKEventStore",
        "text": "EKEventStore"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "EventKit UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithSelectionStyle:displayStyle:eventStore:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(selectionStyle:displayStyle:eventStore:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "selectionStyle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserSelectionStyle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@EKCalendarChooserSelectionStyle",
              "text": "EKCalendarChooserSelectionStyle"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "displayStyle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDisplayStyle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@EKCalendarChooserDisplayStyle",
              "text": "EKCalendarChooserDisplayStyle"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "eventStore"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)EKEventStore",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)EKEventStore",
              "text": "EKEventStore"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Determines whether to allow selection of multiple calendars. Possible values are described in ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserSelectionStyle",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "selectionStyle"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Determines which calendars to display. Possible values are described in ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDisplayStyle",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "displayStyle"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The event store to which the calendars belong.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "eventStore"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Return-Value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The initialized calendar chooser.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI": {
      "abstract": [
        {
          "text": "Display an interface for viewing, selecting, and editing calendar events and reminders.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit UI",
      "type": "topic",
      "url": "/documentation/eventkitui"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser": {
      "abstract": [
        {
          "text": "A view controller for determining whether a user may select one or more calendars.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKCalendarChooser"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarChooser"
        }
      ],
      "role": "symbol",
      "title": "EKCalendarChooser",
      "type": "topic",
      "url": "/documentation/eventkitui/ekcalendarchooser"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser/init(selectionStyle:displayStyle:entityType:eventStore:)": {
      "abstract": [
        {
          "text": "Initializes a newly created calendar chooser for a specific entity type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "selectionStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKCalendarChooserSelectionStyle",
          "text": "EKCalendarChooserSelectionStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "displayStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKCalendarChooserDisplayStyle",
          "text": "EKCalendarChooserDisplayStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "entityType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKEntityType",
          "text": "EKEntityType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "eventStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKEventStore",
          "text": "EKEventStore"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser/init(selectionStyle:displayStyle:entityType:eventStore:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSelectionStyle:displayStyle:entityType:eventStore:"
        }
      ],
      "role": "symbol",
      "title": "init(selectionStyle:displayStyle:entityType:eventStore:)",
      "type": "topic",
      "url": "/documentation/eventkitui/ekcalendarchooser/init(selectionstyle:displaystyle:entitytype:eventstore:)"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser/init(selectionStyle:displayStyle:eventStore:)": {
      "abstract": [
        {
          "text": "Initializes a newly created calendar chooser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "selectionStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKCalendarChooserSelectionStyle",
          "text": "EKCalendarChooserSelectionStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "displayStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKCalendarChooserDisplayStyle",
          "text": "EKCalendarChooserDisplayStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "eventStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)EKEventStore",
          "text": "EKEventStore"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser/init(selectionStyle:displayStyle:eventStore:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSelectionStyle:displayStyle:eventStore:"
        }
      ],
      "role": "symbol",
      "title": "init(selectionStyle:displayStyle:eventStore:)",
      "type": "topic",
      "url": "/documentation/eventkitui/ekcalendarchooser/init(selectionstyle:displaystyle:eventstore:)"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDisplayStyle": {
      "abstract": [
        {
          "text": "Indicates whether to display all calendars or writable calendars only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKCalendarChooserDisplayStyle"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDisplayStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarChooserDisplayStyle"
        }
      ],
      "role": "symbol",
      "title": "EKCalendarChooserDisplayStyle",
      "type": "topic",
      "url": "/documentation/eventkitui/ekcalendarchooserdisplaystyle"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserSelectionStyle": {
      "abstract": [
        {
          "text": "Indicates whether users may select a single calendar, or multiple calendars.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKCalendarChooserSelectionStyle"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserSelectionStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarChooserSelectionStyle"
        }
      ],
      "role": "symbol",
      "title": "EKCalendarChooserSelectionStyle",
      "type": "topic",
      "url": "/documentation/eventkitui/ekcalendarchooserselectionstyle"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)EKEventStore": {
      "abstract": [
        {
          "text": "An object that accesses a person’s calendar events and reminders and supports the scheduling of new events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEventStore"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)EKEventStore",
      "kind": "symbol",
      "role": "symbol",
      "title": "EKEventStore",
      "type": "topic",
      "url": "/documentation/EventKit/EKEventStore"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Initializing-Calendar-Choosers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser/init(selectionStyle:displayStyle:entityType:eventStore:)"
      ],
      "title": "Initializing Calendar Choosers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithSelectionStyle:displayStyle:eventStore:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSelectionStyle:displayStyle:eventStore:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkitui/documentation/EventKitUI",
                "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Initializing-Calendar-Choosers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooser/init(selectionStyle:displayStyle:entityType:eventStore:)"
              ],
              "title": "Initializing Calendar Choosers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithSelectionStyle:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserSelectionStyle",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@EKCalendarChooserSelectionStyle",
                    "text": "EKCalendarChooserSelectionStyle"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "selectionStyle"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "displayStyle:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDisplayStyle",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@EKCalendarChooserDisplayStyle",
                    "text": "EKCalendarChooserDisplayStyle"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "displayStyle"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "eventStore:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)EKEventStore",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)EKEventStore",
                    "text": "EKEventStore"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "eventStore"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Determines whether to allow selection of multiple calendars. Possible values are described in ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserSelectionStyle",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "selectionStyle"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Determines which calendars to display. Possible values are described in ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKCalendarChooserDisplayStyle",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "displayStyle"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The event store to which the calendars belong.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "eventStore"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooser/title",
          "value": "EKCalendarChooser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarChooser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooser/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarChooser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooserSelectionStyle/title",
          "value": "EKCalendarChooserSelectionStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooserSelectionStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarChooserSelectionStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooserSelectionStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarChooserSelectionStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooser~1init(selectionStyle:displayStyle:eventStore:)/title",
          "value": "initWithSelectionStyle:displayStyle:eventStore:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooser~1init(selectionStyle:displayStyle:eventStore:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSelectionStyle:displayStyle:eventStore:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)EKEventStore/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EKEventStore"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooser~1init(selectionStyle:displayStyle:entityType:eventStore:)/title",
          "value": "initWithSelectionStyle:displayStyle:entityType:eventStore:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooser~1init(selectionStyle:displayStyle:entityType:eventStore:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSelectionStyle:displayStyle:entityType:eventStore:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooserDisplayStyle/title",
          "value": "EKCalendarChooserDisplayStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooserDisplayStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarChooserDisplayStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKCalendarChooserDisplayStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarChooserDisplayStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkitui/ekcalendarchooser/init(selectionstyle:displaystyle:eventstore:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkitui/ekcalendarchooser/init(selectionstyle:displaystyle:eventstore:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
