{
  "abstract": [
    {
      "text": "The edge against which the button places the image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imagePlacement"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIButtonConfiguration(py)imagePlacement",
    "fragments": [
      {
        "kind": "identifier",
        "text": "imagePlacement"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "imagePlacement"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "imagePlacement"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readwrite"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSDirectionalRectEdge",
              "text": "NSDirectionalRectEdge"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "imagePlacement"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this property to place the image along the top, leading, trailing, or bottom edge of the button.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge": {
      "abstract": [
        {
          "text": "Constants that specify an edge or a set of edges, taking the user interface layout direction into account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDirectionalRectEdge"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDirectionalRectEdge"
        }
      ],
      "role": "symbol",
      "title": "NSDirectionalRectEdge",
      "type": "topic",
      "url": "/documentation/uikit/nsdirectionalrectedge"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration": {
      "abstract": [
        {
          "text": "A configuration that specifies the appearance and behavior of a button and its contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIButtonConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButtonConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/image": {
      "abstract": [
        {
          "text": "The foreground image the button displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/image",
      "kind": "symbol",
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/image"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imageColorTransformer": {
      "abstract": [
        {
          "text": "A block that transforms the image color when the button state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "imageColorTransformer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imageColorTransformer",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageColorTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/imagecolortransformer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imagePadding": {
      "abstract": [
        {
          "text": "The distance between the button’s image and text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "imagePadding"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imagePadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "imagePadding",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/imagepadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imagePlacement": {
      "abstract": [
        {
          "text": "The edge against which the button places the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "imagePlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imagePlacement",
      "kind": "symbol",
      "role": "symbol",
      "title": "imagePlacement",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/imageplacement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/preferredSymbolConfigurationForImage": {
      "abstract": [
        {
          "text": "A requested configuration object for the button symbol image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "preferredSymbolConfigurationForImage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/preferredSymbolConfigurationForImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredSymbolConfigurationForImage",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/preferredsymbolconfigurationforimage"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-images",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/image",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imagePadding",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imageColorTransformer",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/preferredSymbolConfigurationForImage"
      ],
      "title": "Configuring images"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge/title",
          "value": "NSDirectionalRectEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalRectEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalRectEdge"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibuttonconfiguration/imageplacement"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
