{
  "abstract": [
    {
      "text": "The text of the title label the button displays.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/title"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIButtonConfiguration(py)title",
    "fragments": [
      {
        "kind": "identifier",
        "text": "title"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "title"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "title"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readwrite"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "title"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property matches the string value of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/attributedTitle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. To change the button title when the button state changes, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/configurationUpdateHandler-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/updateConfiguration()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/configurationUpdateHandler-swift.property": {
      "abstract": [
        {
          "text": "A closure that executes when the button state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationUpdateHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIButtonConfigurationUpdateHandler",
          "text": "ConfigurationUpdateHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/configurationUpdateHandler-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configurationUpdateHandler"
        }
      ],
      "role": "symbol",
      "title": "configurationUpdateHandler",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configurationupdatehandler-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/updateConfiguration()": {
      "abstract": [
        {
          "text": "Updates the button configuration in response to a button state change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateConfiguration"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/updateConfiguration()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateConfiguration"
        }
      ],
      "role": "symbol",
      "title": "updateConfiguration()",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/updateconfiguration()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration": {
      "abstract": [
        {
          "text": "A configuration that specifies the appearance and behavior of a button and its contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIButtonConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButtonConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/attributedSubtitle": {
      "abstract": [
        {
          "text": "The text and style attributes for the button’s subtitle label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "attributedSubtitle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/attributedSubtitle",
      "kind": "symbol",
      "role": "symbol",
      "title": "attributedSubtitle",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/attributedsubtitle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/attributedTitle": {
      "abstract": [
        {
          "text": "The text and style attributes for the button’s title label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "attributedTitle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/attributedTitle",
      "kind": "symbol",
      "role": "symbol",
      "title": "attributedTitle",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/attributedtitle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitle": {
      "abstract": [
        {
          "text": "The text the subtitle label of the button displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "subtitle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitle",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtitle",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/subtitle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitleLineBreakMode": {
      "abstract": [
        {
          "text": "The line break mode the button uses to lay out the button’s subtitle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "subtitleLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitleLineBreakMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtitleLineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/subtitlelinebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitleTextAttributesTransformer": {
      "abstract": [
        {
          "text": "A transformer to update the attributed subtitle when the button state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "subtitleTextAttributesTransformer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitleTextAttributesTransformer",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtitleTextAttributesTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/subtitletextattributestransformer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/title": {
      "abstract": [
        {
          "text": "The text of the title label the button displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/title",
      "kind": "symbol",
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/title"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleAlignment": {
      "abstract": [
        {
          "text": "The text alignment the button uses to lay out the title and subtitle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "titleAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "titleAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/titlealignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleLineBreakMode": {
      "abstract": [
        {
          "text": "The line break mode the button uses to lay out the button’s title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "titleLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleLineBreakMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "titleLineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/titlelinebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titlePadding": {
      "abstract": [
        {
          "text": "The distance between the title and subtitle labels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "titlePadding"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titlePadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "titlePadding",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/titlepadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleTextAttributesTransformer": {
      "abstract": [
        {
          "text": "A transformer to update the attributed title when the button state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "titleTextAttributesTransformer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleTextAttributesTransformer",
      "kind": "symbol",
      "role": "symbol",
      "title": "titleTextAttributesTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/titletextattributestransformer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationTitleAlignment": {
      "abstract": [
        {
          "text": "Specifies how to align a button’s title and subtitle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIButtonConfigurationTitleAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationTitleAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButtonConfigurationTitleAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfigurationtitlealignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIConfigurationTextAttributesTransformer-c.typealias": {
      "abstract": [
        {
          "text": "Defines a text transformation that can affect the visual appearance of a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIConfigurationTextAttributesTransformer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationTextAttributesTransformer-c.typealias",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIConfigurationTextAttributesTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uiconfigurationtextattributestransformer-c.typealias"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-titles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitle",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/attributedTitle",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/attributedSubtitle",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleTextAttributesTransformer",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitleTextAttributesTransformer",
        "doc://com.apple.uikit/documentation/UIKit/UIConfigurationTextAttributesTransformer-c.typealias",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titlePadding",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleAlignment",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationTitleAlignment",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleLineBreakMode",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitleLineBreakMode"
      ],
      "title": "Configuring titles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1configurationUpdateHandler-swift.property/title",
          "value": "configurationUpdateHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1configurationUpdateHandler-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "configurationUpdateHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1updateConfiguration()/title",
          "value": "updateConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1updateConfiguration()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibuttonconfiguration/title"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
