{
  "abstract": [
    {
      "text": "The background color to apply to the accessory.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessoryInsert"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICellAccessoryInsert/backgroundColor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UICellAccessoryInsert(py)backgroundColor",
    "fragments": [
      {
        "kind": "identifier",
        "text": "backgroundColor"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "backgroundColor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "backgroundColor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "strong"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIColor",
              "text": "UIColor"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "backgroundColor"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default value of this property is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", which uses the system default.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessoryInsert": {
      "abstract": [
        {
          "text": "The insert system accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UICellAccessoryInsert"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessoryInsert",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICellAccessoryInsert",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessoryinsert"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessoryInsert/actionHandler": {
      "abstract": [
        {
          "text": "A handler that the system calls when a user interacts with the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "actionHandler"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessoryInsert/actionHandler",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionHandler",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessoryinsert/actionhandler"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessoryInsert/backgroundColor": {
      "abstract": [
        {
          "text": "The background color to apply to the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "backgroundColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessoryInsert/backgroundColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "backgroundColor",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessoryinsert/backgroundcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIColor"
        }
      ],
      "role": "symbol",
      "title": "UIColor",
      "type": "topic",
      "url": "/documentation/uikit/uicolor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-configuration-options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessoryInsert/actionHandler"
      ],
      "title": "Accessing configuration options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/title",
          "value": "UIColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicellaccessoryinsert/backgroundcolor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
