{
  "abstract": [
    {
      "text": "A status that occurs when the app prompts the user to review the passes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus/shouldReviewPasses"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKPassLibraryAddPassesStatus@PKPassLibraryShouldReviewPasses",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "shouldReviewPasses"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKPassLibraryShouldReviewPasses"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PKPassLibraryAddPassesStatus.shouldReviewPasses"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "shouldReviewPasses"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus": {
      "abstract": [
        {
          "text": "Statuses that PassKit uses when it adds passes to the pass library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassLibraryAddPassesStatus"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryAddPassesStatus"
        }
      ],
      "role": "symbol",
      "title": "PKPassLibraryAddPassesStatus",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibraryaddpassesstatus"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus/didAddPasses": {
      "abstract": [
        {
          "text": "A status that occurs when the user successfully adds one or more passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didAddPasses"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus/didAddPasses",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryDidAddPasses"
        }
      ],
      "role": "symbol",
      "title": "PKPassLibraryAddPassesStatus.didAddPasses",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibraryaddpassesstatus/didaddpasses"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus/didCancelAddPasses": {
      "abstract": [
        {
          "text": "A status that occurs when the user cancels the addition of passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didCancelAddPasses"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus/didCancelAddPasses",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryDidCancelAddPasses"
        }
      ],
      "role": "symbol",
      "title": "PKPassLibraryAddPassesStatus.didCancelAddPasses",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibraryaddpassesstatus/didcanceladdpasses"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus/shouldReviewPasses": {
      "abstract": [
        {
          "text": "A status that occurs when the app prompts the user to review the passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldReviewPasses"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus/shouldReviewPasses",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassLibraryShouldReviewPasses"
        }
      ],
      "role": "symbol",
      "title": "PKPassLibraryAddPassesStatus.shouldReviewPasses",
      "type": "topic",
      "url": "/documentation/passkit/pkpasslibraryaddpassesstatus/shouldreviewpasses"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus/didAddPasses",
        "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus/didCancelAddPasses"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKPassLibraryShouldReviewPasses"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryShouldReviewPasses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus/didAddPasses",
                "doc://com.apple.passkit/documentation/PassKit/PKPassLibraryAddPassesStatus/didCancelAddPasses"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PKPassLibraryShouldReviewPasses"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryAddPassesStatus~1shouldReviewPasses/title",
          "value": "PKPassLibraryShouldReviewPasses"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryAddPassesStatus~1shouldReviewPasses/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryShouldReviewPasses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryAddPassesStatus/title",
          "value": "PKPassLibraryAddPassesStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryAddPassesStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryAddPassesStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryAddPassesStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryAddPassesStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryAddPassesStatus~1didAddPasses/title",
          "value": "PKPassLibraryDidAddPasses"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryAddPassesStatus~1didAddPasses/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryDidAddPasses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryAddPassesStatus~1didCancelAddPasses/title",
          "value": "PKPassLibraryDidCancelAddPasses"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassLibraryAddPassesStatus~1didCancelAddPasses/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassLibraryDidCancelAddPasses"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpasslibraryaddpassesstatus/shouldreviewpasses"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpasslibraryaddpassesstatus/shouldreviewpasses"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
