{
  "abstract": [
    {
      "text": "A mode in which the search controller shows the scope bar when typing begins in the search field, and hides it after search cancellation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/onTextEntry"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UISearchControllerScopeBarActivation@UISearchControllerScopeBarActivationOnTextEntry",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "onTextEntry"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UISearchControllerScopeBarActivationOnTextEntry"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UISearchController.ScopeBarActivation.onTextEntry"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "onTextEntry"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController": {
      "abstract": [
        {
          "text": "A view controller that manages the display of search results based on interactions with a search bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchController"
        }
      ],
      "role": "symbol",
      "title": "UISearchController",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the modes for showing and hiding the scope bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScopeBarActivation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScopeBarActivation"
        }
      ],
      "role": "symbol",
      "title": "UISearchController.ScopeBarActivation",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/scopebaractivation-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/automatic": {
      "abstract": [
        {
          "text": "A mode in which the system automatically determines when to show and hide the scope bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchControllerScopeBarActivationAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UISearchController.ScopeBarActivation.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/scopebaractivation-swift.enum/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/manual": {
      "abstract": [
        {
          "text": "A mode that gives you manual control over when to show and hide the scope bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manual"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/manual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchControllerScopeBarActivationManual"
        }
      ],
      "role": "symbol",
      "title": "UISearchController.ScopeBarActivation.manual",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/scopebaractivation-swift.enum/manual"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/onSearchActivation": {
      "abstract": [
        {
          "text": "A mode in which the search controller shows the scope bar when search becomes active, and hides it after search cancellation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onSearchActivation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/onSearchActivation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchControllerScopeBarActivationOnSearchActivation"
        }
      ],
      "role": "symbol",
      "title": "UISearchController.ScopeBarActivation.onSearchActivation",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/scopebaractivation-swift.enum/onsearchactivation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/onTextEntry": {
      "abstract": [
        {
          "text": "A mode in which the search controller shows the scope bar when typing begins in the search field, and hides it after search cancellation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onTextEntry"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/onTextEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchControllerScopeBarActivationOnTextEntry"
        }
      ],
      "role": "symbol",
      "title": "UISearchController.ScopeBarActivation.onTextEntry",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/scopebaractivation-swift.enum/ontextentry"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/manual",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/onSearchActivation"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UISearchControllerScopeBarActivationOnTextEntry"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchControllerScopeBarActivationOnTextEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/manual",
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/onSearchActivation"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UISearchControllerScopeBarActivationOnTextEntry"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum/title",
          "value": "UISearchControllerScopeBarActivation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchControllerScopeBarActivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchControllerScopeBarActivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum~1automatic/title",
          "value": "UISearchControllerScopeBarActivationAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchControllerScopeBarActivationAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController/title",
          "value": "UISearchController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum~1manual/title",
          "value": "UISearchControllerScopeBarActivationManual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum~1manual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchControllerScopeBarActivationManual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum~1onSearchActivation/title",
          "value": "UISearchControllerScopeBarActivationOnSearchActivation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum~1onSearchActivation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchControllerScopeBarActivationOnSearchActivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum~1onTextEntry/title",
          "value": "UISearchControllerScopeBarActivationOnTextEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum~1onTextEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchControllerScopeBarActivationOnTextEntry"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisearchcontroller/scopebaractivation-swift.enum/ontextentry"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uisearchcontroller/scopebaractivation-swift.enum/ontextentry"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
