{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BADownloaderExtension-zuvm"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BADownloaderExtension-zuvm/downloadsForRequest:manifestURL:extensionInfo:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)BADownloaderExtension(im)downloadsForRequest:manifestURL:extensionInfo:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "downloadsForRequest:manifestURL:extensionInfo:"
      }
    ],
    "modules": [
      {
        "name": "Background Assets"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "downloadsForRequest:manifestURL:extensionInfo:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "2.4",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "downloadsForRequest:manifestURL:extensionInfo:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSSet",
              "text": "NSSet<BADownload *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "downloadsForRequest:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@BAContentRequest",
              "text": "BAContentRequest"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "contentRequest"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "manifestURL:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSURL",
              "text": "NSURL"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "manifestURL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "extensionInfo:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAAppExtensionInfo",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)BAAppExtensionInfo",
              "text": "BAAppExtensionInfo"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "extensionInfo"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets": {
      "abstract": [
        {
          "text": "Schedule background downloads of large assets after app installation, when the app updates, and periodically while the app remains on-device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets",
      "kind": "symbol",
      "role": "collection",
      "title": "Background Assets",
      "type": "topic",
      "url": "/documentation/backgroundassets"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAAppExtensionInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BAAppExtensionInfo"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAAppExtensionInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAAppExtensionInfo"
        }
      ],
      "role": "symbol",
      "title": "BAAppExtensionInfo",
      "type": "topic",
      "url": "/documentation/backgroundassets/baappextensioninfo"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BAContentRequest"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BAContentRequest"
        }
      ],
      "role": "symbol",
      "title": "BAContentRequest",
      "type": "topic",
      "url": "/documentation/backgroundassets/bacontentrequest"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BADownloaderExtension-zuvm": {
      "abstract": [
        {
          "text": "An interface for reacting to app life-cycle events and processing concluded asset downloads while your app isn’t running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BADownloaderExtension"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BADownloaderExtension-zuvm",
      "kind": "symbol",
      "role": "symbol",
      "title": "BADownloaderExtension",
      "type": "topic",
      "url": "/documentation/backgroundassets/badownloaderextension-zuvm"
    },
    "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BADownloaderExtension-zuvm/downloadsForRequest:manifestURL:extensionInfo:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "downloadsForRequest:manifestURL:extensionInfo:"
        }
      ],
      "identifier": "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BADownloaderExtension-zuvm/downloadsForRequest:manifestURL:extensionInfo:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "downloadsForRequest:manifestURL:extensionInfo:"
        }
      ],
      "role": "symbol",
      "title": "downloadsForRequest:manifestURL:extensionInfo:",
      "type": "topic",
      "url": "/documentation/backgroundassets/badownloaderextension-zuvm/downloadsforrequest:manifesturl:extensioninfo:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSURL": {
      "abstract": [
        {
          "text": "An object representing the location of a resource that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSURL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSURL",
      "type": "topic",
      "url": "/documentation/foundation/nsurl"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Checking-for-asset-updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAContentRequest",
        "doc://com.apple.backgroundassets/documentation/BackgroundAssets/BAAppExtensionInfo"
      ],
      "title": "Checking for asset updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAContentRequest/title",
          "value": "BAContentRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAContentRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAContentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAContentRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BAContentRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAAppExtensionInfo/title",
          "value": "BAAppExtensionInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAAppExtensionInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BAAppExtensionInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.backgroundassets~1documentation~1BackgroundAssets~1BAAppExtensionInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BAAppExtensionInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSURL/abstract",
          "value": [
            {
              "text": "An object that represents the location of a resource, such as an item on a remote server or the path to a local file. ",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/backgroundassets/badownloaderextension-zuvm/downloadsforrequest:manifesturl:extensioninfo:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
