{
  "abstract": [
    {
      "text": "States of cellular calls; one of dialing, incoming, connected, or disconnected.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretelephony/documentation/CoreTelephony",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCall"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretelephony/documentation/CoreTelephony/cellular-call-states"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Telephony"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Cellular Call States"
  },
  "references": {
    "doc://com.apple.coretelephony/documentation/CoreTelephony": {
      "abstract": [
        {
          "text": "Access information about a user’s cellular service provider, such as its unique identifier and whether the carrier allows VoIP.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Telephony",
      "type": "topic",
      "url": "/documentation/coretelephony"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCall": {
      "abstract": [
        {
          "text": "An object used to identify a cellular call and determine its state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCall"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCall"
        }
      ],
      "role": "symbol",
      "title": "CTCall",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcall"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallStateConnected": {
      "abstract": [
        {
          "text": "The call state when fully establishing the call for all parties involved.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCallStateConnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallStateConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCallStateConnected"
        }
      ],
      "role": "symbol",
      "title": "CTCallStateConnected",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcallstateconnected"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallStateDialing": {
      "abstract": [
        {
          "text": "The call state, before establishing the connection, when the user initiates the call.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCallStateDialing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallStateDialing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCallStateDialing"
        }
      ],
      "role": "symbol",
      "title": "CTCallStateDialing",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcallstatedialing"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallStateDisconnected": {
      "abstract": [
        {
          "text": "The call state upon call termination.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCallStateDisconnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallStateDisconnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCallStateDisconnected"
        }
      ],
      "role": "symbol",
      "title": "CTCallStateDisconnected",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcallstatedisconnected"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallStateIncoming": {
      "abstract": [
        {
          "text": "The call state, before establishing the connection, when a call is incoming but not yet answered by the user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCallStateIncoming"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallStateIncoming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCallStateIncoming"
        }
      ],
      "role": "symbol",
      "title": "CTCallStateIncoming",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcallstateincoming"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallStateDialing",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallStateIncoming",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallStateConnected",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallStateDisconnected"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallStateDialing",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallStateIncoming",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallStateConnected",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCallStateDisconnected"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallStateDialing/title",
          "value": "CTCallStateDialing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallStateDialing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCallStateDialing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCall/title",
          "value": "CTCall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCall/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallStateIncoming/title",
          "value": "CTCallStateIncoming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallStateIncoming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCallStateIncoming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallStateDisconnected/title",
          "value": "CTCallStateDisconnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallStateDisconnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCallStateDisconnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallStateConnected/title",
          "value": "CTCallStateConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCallStateConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCallStateConnected"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretelephony/cellular-call-states"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretelephony/cellular-call-states"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
