{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretelephony/documentation/CoreTelephony"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretelephony/documentation/CoreTelephony/coretelephony-macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Telephony"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Telephony Macros"
  },
  "references": {
    "doc://com.apple.coretelephony/documentation/CoreTelephony": {
      "abstract": [
        {
          "text": "Access information about a user’s cellular service provider, such as its unique identifier and whether the carrier allows VoIP.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Telephony",
      "type": "topic",
      "url": "/documentation/coretelephony"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CORETELEPHONY_CLASS_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CORETELEPHONY_CLASS_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CORETELEPHONY_CLASS_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CORETELEPHONY_CLASS_AVAILABLE",
      "type": "topic",
      "url": "/documentation/coretelephony/coretelephony_class_available"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CORETELEPHONY_CLASS_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CORETELEPHONY_CLASS_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CORETELEPHONY_CLASS_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "CORETELEPHONY_CLASS_DEPRECATED",
      "type": "topic",
      "url": "/documentation/coretelephony/coretelephony_class_deprecated"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CORETELEPHONY_CPP_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CORETELEPHONY_CPP_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CORETELEPHONY_CPP_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "CORETELEPHONY_CPP_EXTERN",
      "type": "topic",
      "url": "/documentation/coretelephony/coretelephony_cpp_extern"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CORETELEPHONY_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CORETELEPHONY_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CORETELEPHONY_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "CORETELEPHONY_EXTERN",
      "type": "topic",
      "url": "/documentation/coretelephony/coretelephony_extern"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CORETELEPHONY_EXTERN_CLASS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CORETELEPHONY_EXTERN_CLASS"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CORETELEPHONY_EXTERN_CLASS",
      "kind": "symbol",
      "role": "symbol",
      "title": "CORETELEPHONY_EXTERN_CLASS",
      "type": "topic",
      "url": "/documentation/coretelephony/coretelephony_extern_class"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CORETELEPHONY_CLASS_AVAILABLE",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CORETELEPHONY_CLASS_DEPRECATED",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CORETELEPHONY_CPP_EXTERN",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CORETELEPHONY_EXTERN",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CORETELEPHONY_EXTERN_CLASS"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretelephony/coretelephony-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretelephony/coretelephony-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
