{
  "abstract": [
    {
      "text": "An object you use to download and install a carrier eSIM.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretelephony/documentation/CoreTelephony"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CTCellularPlanProvisioning",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTCellularPlanProvisioning"
      }
    ],
    "modules": [
      {
        "name": "Core Telephony"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTCellularPlanProvisioning"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CTCellularPlanProvisioning"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioning"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This class is only available to carrier apps with suitable entitlements.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretelephony/documentation/CoreTelephony": {
      "abstract": [
        {
          "text": "Access information about a user’s cellular service provider, such as its unique identifier and whether the carrier allows VoIP.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Telephony",
      "type": "topic",
      "url": "/documentation/coretelephony"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning": {
      "abstract": [
        {
          "text": "An object you use to download and install a carrier eSIM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioning"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioning"
        }
      ],
      "role": "symbol",
      "title": "CTCellularPlanProvisioning",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioning"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/addPlan(with:completionHandler:)": {
      "abstract": [
        {
          "text": "Starts the provisioning process for a specified eSIM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addPlan"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CTCellularPlanProvisioningRequest",
          "text": "CTCellularPlanProvisioningRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCellularPlanProvisioningAddPlanResult",
          "text": "CTCellularPlanProvisioningAddPlanResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/addPlan(with:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPlanWith:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "addPlan(with:completionHandler:)",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioning/addplan(with:completionhandler:)"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/supportsCellularPlan()": {
      "abstract": [
        {
          "text": "Indicates whether the device supports eSIM and the activation policy allows eSIM installation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsCellularPlan"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/supportsCellularPlan()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsCellularPlan"
        }
      ],
      "role": "symbol",
      "title": "supportsCellularPlan()",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioning/supportscellularplan()"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/supportsEmbeddedSIM": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device has hardware eSIM support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsEmbeddedSIM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/supportsEmbeddedSIM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsEmbeddedSIM"
        }
      ],
      "role": "symbol",
      "title": "supportsEmbeddedSIM",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioning/supportsembeddedsim"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult": {
      "abstract": [
        {
          "text": "The result from attempting to provision an eSIM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioningAddPlanResult"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioningAddPlanResult"
        }
      ],
      "role": "symbol",
      "title": "CTCellularPlanProvisioningAddPlanResult",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioningaddplanresult"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningRequest": {
      "abstract": [
        {
          "text": "A request specifying an eSIM to download and install.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioningRequest"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCellularPlanProvisioningRequest"
        }
      ],
      "role": "symbol",
      "title": "CTCellularPlanProvisioningRequest",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcellularplanprovisioningrequest"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "eSIM",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningRequest"
      ],
      "title": "eSIM"
    }
  ],
  "topicSections": [
    {
      "anchor": "Provisioning-an-eSIM",
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/supportsCellularPlan()",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/supportsEmbeddedSIM",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/addPlan(with:completionHandler:)",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult"
      ],
      "title": "Provisioning an eSIM"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTCellularPlanProvisioning"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretelephony/documentation/CoreTelephony"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Provisioning-an-eSIM",
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/supportsCellularPlan()",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/supportsEmbeddedSIM",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioning/addPlan(with:completionHandler:)",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningAddPlanResult"
              ],
              "title": "Provisioning an eSIM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "eSIM",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCellularPlanProvisioningRequest"
              ],
              "title": "eSIM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTCellularPlanProvisioning"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning~1supportsCellularPlan()/title",
          "value": "supportsCellularPlan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning~1supportsCellularPlan()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportsCellularPlan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningAddPlanResult/title",
          "value": "CTCellularPlanProvisioningAddPlanResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningAddPlanResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioningAddPlanResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningAddPlanResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioningAddPlanResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning~1addPlan(with:completionHandler:)/title",
          "value": "addPlanWith:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning~1addPlan(with:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addPlanWith:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningRequest/title",
          "value": "CTCellularPlanProvisioningRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioningRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioningRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioningRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning/title",
          "value": "CTCellularPlanProvisioning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCellularPlanProvisioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning~1supportsEmbeddedSIM/title",
          "value": "supportsEmbeddedSIM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCellularPlanProvisioning~1supportsEmbeddedSIM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsEmbeddedSIM"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretelephony/ctcellularplanprovisioning"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretelephony/ctcellularplanprovisioning"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
