{
  "abstract": [
    {
      "text": "The High-Speed Downlink Packet Access (HSDPA) radio access technology.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretelephony/documentation/CoreTelephony"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyHSDPA"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@CTRadioAccessTechnologyHSDPA",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTRadioAccessTechnologyHSDPA"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Core Telephony"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTRadioAccessTechnologyHSDPA"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "CTRadioAccessTechnologyHSDPA"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTRadioAccessTechnologyHSDPA"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretelephony/documentation/CoreTelephony": {
      "abstract": [
        {
          "text": "Access information about a user’s cellular service provider, such as its unique identifier and whether the carrier allows VoIP.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Telephony",
      "type": "topic",
      "url": "/documentation/coretelephony"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyCDMA1x": {
      "abstract": [
        {
          "text": "The Code Division Multiple Access (CDMA) 1x radio access technology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyCDMA1x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyCDMA1x",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyCDMA1x"
        }
      ],
      "role": "symbol",
      "title": "CTRadioAccessTechnologyCDMA1x",
      "type": "topic",
      "url": "/documentation/coretelephony/ctradioaccesstechnologycdma1x"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyCDMAEVDORev0": {
      "abstract": [
        {
          "text": "The Code Division Multiple Access (CDMA) Evolution-Data Optimized (EV-DO) Rev. 0 radio access technology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyCDMAEVDORev0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyCDMAEVDORev0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyCDMAEVDORev0"
        }
      ],
      "role": "symbol",
      "title": "CTRadioAccessTechnologyCDMAEVDORev0",
      "type": "topic",
      "url": "/documentation/coretelephony/ctradioaccesstechnologycdmaevdorev0"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyCDMAEVDORevA": {
      "abstract": [
        {
          "text": "The Code Division Multiple Access (CDMA) Evolution-Data Optimized (EV-DO) Rev. A radio access technology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyCDMAEVDORevA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyCDMAEVDORevA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyCDMAEVDORevA"
        }
      ],
      "role": "symbol",
      "title": "CTRadioAccessTechnologyCDMAEVDORevA",
      "type": "topic",
      "url": "/documentation/coretelephony/ctradioaccesstechnologycdmaevdoreva"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyCDMAEVDORevB": {
      "abstract": [
        {
          "text": "The Code Division Multiple Access (CDMA) Evolution-Data Optimized (EV-DO) Rev. B radio access technology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyCDMAEVDORevB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyCDMAEVDORevB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyCDMAEVDORevB"
        }
      ],
      "role": "symbol",
      "title": "CTRadioAccessTechnologyCDMAEVDORevB",
      "type": "topic",
      "url": "/documentation/coretelephony/ctradioaccesstechnologycdmaevdorevb"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyEdge": {
      "abstract": [
        {
          "text": "The Enhanced Data rates for GSM Evolution (EDGE) radio access technology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyEdge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyEdge"
        }
      ],
      "role": "symbol",
      "title": "CTRadioAccessTechnologyEdge",
      "type": "topic",
      "url": "/documentation/coretelephony/ctradioaccesstechnologyedge"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyGPRS": {
      "abstract": [
        {
          "text": "The General Packet Radio Service (GPRS) radio access technology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyGPRS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyGPRS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyGPRS"
        }
      ],
      "role": "symbol",
      "title": "CTRadioAccessTechnologyGPRS",
      "type": "topic",
      "url": "/documentation/coretelephony/ctradioaccesstechnologygprs"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyHSDPA": {
      "abstract": [
        {
          "text": "The High-Speed Downlink Packet Access (HSDPA) radio access technology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyHSDPA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyHSDPA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyHSDPA"
        }
      ],
      "role": "symbol",
      "title": "CTRadioAccessTechnologyHSDPA",
      "type": "topic",
      "url": "/documentation/coretelephony/ctradioaccesstechnologyhsdpa"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyHSUPA": {
      "abstract": [
        {
          "text": "The High-Speed Uplink Packet Acess (HSUPA) radio access technology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyHSUPA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyHSUPA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyHSUPA"
        }
      ],
      "role": "symbol",
      "title": "CTRadioAccessTechnologyHSUPA",
      "type": "topic",
      "url": "/documentation/coretelephony/ctradioaccesstechnologyhsupa"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyLTE": {
      "abstract": [
        {
          "text": "The Long-Term Evolution (LTE) radio access technology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyLTE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyLTE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyLTE"
        }
      ],
      "role": "symbol",
      "title": "CTRadioAccessTechnologyLTE",
      "type": "topic",
      "url": "/documentation/coretelephony/ctradioaccesstechnologylte"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyNR": {
      "abstract": [
        {
          "text": "The 5G New Radio (NR) radio access technology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyNR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyNR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyNR"
        }
      ],
      "role": "symbol",
      "title": "CTRadioAccessTechnologyNR",
      "type": "topic",
      "url": "/documentation/coretelephony/ctradioaccesstechnologynr"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyNRNSA": {
      "abstract": [
        {
          "text": "The 5G New Radio Non-Standalone (NRNSA) radio access technology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyNRNSA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyNRNSA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyNRNSA"
        }
      ],
      "role": "symbol",
      "title": "CTRadioAccessTechnologyNRNSA",
      "type": "topic",
      "url": "/documentation/coretelephony/ctradioaccesstechnologynrnsa"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyWCDMA": {
      "abstract": [
        {
          "text": "The Wideband Code Division Multiple Access (WCDMA) radio access technology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyWCDMA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyWCDMA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyWCDMA"
        }
      ],
      "role": "symbol",
      "title": "CTRadioAccessTechnologyWCDMA",
      "type": "topic",
      "url": "/documentation/coretelephony/ctradioaccesstechnologywcdma"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyeHRPD": {
      "abstract": [
        {
          "text": "The Enhanced High Rate Packet Data (eHRPD) radio access technology.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyeHRPD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyeHRPD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyeHRPD"
        }
      ],
      "role": "symbol",
      "title": "CTRadioAccessTechnologyeHRPD",
      "type": "topic",
      "url": "/documentation/coretelephony/ctradioaccesstechnologyehrpd"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyGPRS",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyEdge",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyWCDMA",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyHSUPA",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyCDMA1x",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyCDMAEVDORev0",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyCDMAEVDORevA",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyCDMAEVDORevB",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyeHRPD",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyLTE",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyNRNSA",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyNR"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTRadioAccessTechnologyHSDPA"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRadioAccessTechnologyHSDPA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretelephony/documentation/CoreTelephony"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyGPRS",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyEdge",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyWCDMA",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyHSUPA",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyCDMA1x",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyCDMAEVDORev0",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyCDMAEVDORevA",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyCDMAEVDORevB",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyeHRPD",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyLTE",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyNRNSA",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyNR"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTRadioAccessTechnologyHSDPA"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyLTE/title",
          "value": "CTRadioAccessTechnologyLTE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyLTE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRadioAccessTechnologyLTE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyGPRS/title",
          "value": "CTRadioAccessTechnologyGPRS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyGPRS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRadioAccessTechnologyGPRS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyeHRPD/title",
          "value": "CTRadioAccessTechnologyeHRPD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyeHRPD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRadioAccessTechnologyeHRPD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyCDMAEVDORevB/title",
          "value": "CTRadioAccessTechnologyCDMAEVDORevB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyCDMAEVDORevB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRadioAccessTechnologyCDMAEVDORevB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyCDMA1x/title",
          "value": "CTRadioAccessTechnologyCDMA1x"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyCDMA1x/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRadioAccessTechnologyCDMA1x"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyHSUPA/title",
          "value": "CTRadioAccessTechnologyHSUPA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyHSUPA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRadioAccessTechnologyHSUPA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyCDMAEVDORevA/title",
          "value": "CTRadioAccessTechnologyCDMAEVDORevA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyCDMAEVDORevA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRadioAccessTechnologyCDMAEVDORevA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyHSDPA/title",
          "value": "CTRadioAccessTechnologyHSDPA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyHSDPA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRadioAccessTechnologyHSDPA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyNR/title",
          "value": "CTRadioAccessTechnologyNR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyNR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRadioAccessTechnologyNR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyCDMAEVDORev0/title",
          "value": "CTRadioAccessTechnologyCDMAEVDORev0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyCDMAEVDORev0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRadioAccessTechnologyCDMAEVDORev0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyNRNSA/title",
          "value": "CTRadioAccessTechnologyNRNSA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyNRNSA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRadioAccessTechnologyNRNSA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyWCDMA/title",
          "value": "CTRadioAccessTechnologyWCDMA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyWCDMA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRadioAccessTechnologyWCDMA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyEdge/title",
          "value": "CTRadioAccessTechnologyEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTRadioAccessTechnologyEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRadioAccessTechnologyEdge"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretelephony/ctradioaccesstechnologyhsdpa"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretelephony/ctradioaccesstechnologyhsdpa"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
