{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretelephony/documentation/CoreTelephony"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTServiceRadioAccessTechnologyDidChangeNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@CTServiceRadioAccessTechnologyDidChangeNotification",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CTServiceRadioAccessTechnologyDidChangeNotification"
      }
    ],
    "modules": [
      {
        "name": "Core Telephony"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTServiceRadioAccessTechnologyDidChangeNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "CTServiceRadioAccessTechnologyDidChangeNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTServiceRadioAccessTechnologyDidChangeNotification"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretelephony/documentation/CoreTelephony": {
      "abstract": [
        {
          "text": "Access information about a user’s cellular service provider, such as its unique identifier and whether the carrier allows VoIP.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Telephony",
      "type": "topic",
      "url": "/documentation/coretelephony"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyDidChangeNotification": {
      "abstract": [
        {
          "text": "The name of the notification indicating that the radio access technology changed for one of the services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "CTRadioAccessTechnologyDidChangeNotification",
      "type": "topic",
      "url": "/documentation/coretelephony/ctradioaccesstechnologydidchangenotification"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTServiceRadioAccessTechnologyDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CTServiceRadioAccessTechnologyDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTServiceRadioAccessTechnologyDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "CTServiceRadioAccessTechnologyDidChangeNotification",
      "type": "topic",
      "url": "/documentation/coretelephony/ctserviceradioaccesstechnologydidchangenotification"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/currentRadioAccessTechnology": {
      "abstract": [
        {
          "text": "The current radio access technology registered with the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentRadioAccessTechnology"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/currentRadioAccessTechnology",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentRadioAccessTechnology"
        }
      ],
      "role": "symbol",
      "title": "currentRadioAccessTechnology",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo/currentradioaccesstechnology"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProviders": {
      "abstract": [
        {
          "text": "A dictionary that contains carrier information about each service.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceSubscriberCellularProviders"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CTCarrier",
          "text": "CTCarrier"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProviders",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serviceSubscriberCellularProviders"
        }
      ],
      "role": "symbol",
      "title": "serviceSubscriberCellularProviders",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo/servicesubscribercellularproviders"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProvidersDidUpdateNotifier": {
      "abstract": [
        {
          "text": "A block dispatched when there are updates to the user’s cellular provider information for any service.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceSubscriberCellularProvidersDidUpdateNotifier"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProvidersDidUpdateNotifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serviceSubscriberCellularProvidersDidUpdateNotifier"
        }
      ],
      "role": "symbol",
      "title": "serviceSubscriberCellularProvidersDidUpdateNotifier",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo/servicesubscribercellularprovidersdidupdatenotifier"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProvider": {
      "abstract": [
        {
          "text": "Information about the user’s cellular service provider.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriberCellularProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CTCarrier",
          "text": "CTCarrier"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscriberCellularProvider"
        }
      ],
      "role": "symbol",
      "title": "subscriberCellularProvider",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo/subscribercellularprovider"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProviderDidUpdateNotifier": {
      "abstract": [
        {
          "text": "A block dispatched when the user’s cellular service provider information changes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriberCellularProviderDidUpdateNotifier"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CTCarrier",
          "text": "CTCarrier"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProviderDidUpdateNotifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscriberCellularProviderDidUpdateNotifier"
        }
      ],
      "role": "symbol",
      "title": "subscriberCellularProviderDidUpdateNotifier",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo/subscribercellularproviderdidupdatenotifier"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1616908-ctradioaccesstechnologydidchange": {
      "abstract": [
        {
          "text": "The name of the notification indicating that the radio access technology changed for one of the services.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyDidChange"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1616908-ctradioaccesstechnologydidchange",
      "kind": "symbol",
      "role": "symbol",
      "title": "CTRadioAccessTechnologyDidChange",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1616908-ctradioaccesstechnologydidchange"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/currentRadioAccessTechnology",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProvider",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProviderDidUpdateNotifier",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProviders",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProvidersDidUpdateNotifier",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1616908-ctradioaccesstechnologydidchange",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyDidChangeNotification"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceSubscriberCellularProviders/title",
          "value": "serviceSubscriberCellularProviders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceSubscriberCellularProviders/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serviceSubscriberCellularProviders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1currentRadioAccessTechnology/title",
          "value": "currentRadioAccessTechnology"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1currentRadioAccessTechnology/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentRadioAccessTechnology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1subscriberCellularProvider/title",
          "value": "subscriberCellularProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1subscriberCellularProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subscriberCellularProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceSubscriberCellularProvidersDidUpdateNotifier/title",
          "value": "serviceSubscriberCellularProvidersDidUpdateNotifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceSubscriberCellularProvidersDidUpdateNotifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serviceSubscriberCellularProvidersDidUpdateNotifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1subscriberCellularProviderDidUpdateNotifier/title",
          "value": "subscriberCellularProviderDidUpdateNotifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1subscriberCellularProviderDidUpdateNotifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subscriberCellularProviderDidUpdateNotifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretelephony/ctserviceradioaccesstechnologydidchangenotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
