{
  "abstract": [
    {
      "text": "A protocol to handle changes to subscriber information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretelephony/documentation/CoreTelephony"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CTSubscriberDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTSubscriberDelegate"
      }
    ],
    "modules": [
      {
        "name": "Core Telephony"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTSubscriberDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.1",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "CTSubscriberDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTSubscriberDelegate"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretelephony/documentation/CoreTelephony": {
      "abstract": [
        {
          "text": "Access information about a user’s cellular service provider, such as its unique identifier and whether the carrier allows VoIP.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Telephony",
      "type": "topic",
      "url": "/documentation/coretelephony"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriber": {
      "abstract": [
        {
          "text": "A cellular network subscriber.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTSubscriber"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTSubscriber"
        }
      ],
      "role": "symbol",
      "title": "CTSubscriber",
      "type": "topic",
      "url": "/documentation/coretelephony/ctsubscriber"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberDelegate": {
      "abstract": [
        {
          "text": "A protocol to handle changes to subscriber information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTSubscriberDelegate"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTSubscriberDelegate"
        }
      ],
      "role": "symbol",
      "title": "CTSubscriberDelegate",
      "type": "topic",
      "url": "/documentation/coretelephony/ctsubscriberdelegate"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberDelegate/subscriberTokenRefreshed(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate the subscriber’s token refreshed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriberTokenRefreshed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CTSubscriber",
          "text": "CTSubscriber"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberDelegate/subscriberTokenRefreshed(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscriberTokenRefreshed:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "subscriberTokenRefreshed(_:)",
      "type": "topic",
      "url": "/documentation/coretelephony/ctsubscriberdelegate/subscribertokenrefreshed(_:)"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberInfo": {
      "abstract": [
        {
          "text": "An object that provides an array of cellular network subscribers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTSubscriberInfo"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTSubscriberInfo"
        }
      ],
      "role": "symbol",
      "title": "CTSubscriberInfo",
      "type": "topic",
      "url": "/documentation/coretelephony/ctsubscriberinfo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Subscriber-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriber",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberInfo"
      ],
      "title": "Subscriber Information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Handling-Token-Updates",
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberDelegate/subscriberTokenRefreshed(_:)"
      ],
      "title": "Handling Token Updates"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.1",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTSubscriberDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTSubscriberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTSubscriberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretelephony/documentation/CoreTelephony"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Handling-Token-Updates",
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberDelegate/subscriberTokenRefreshed(_:)"
              ],
              "title": "Handling Token Updates"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Subscriber-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriber",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTSubscriberInfo"
              ],
              "title": "Subscriber Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTSubscriberDelegate"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriberDelegate~1subscriberTokenRefreshed(_:)/title",
          "value": "subscriberTokenRefreshed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriberDelegate~1subscriberTokenRefreshed(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "subscriberTokenRefreshed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriberDelegate/title",
          "value": "CTSubscriberDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriberDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTSubscriberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriberDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTSubscriberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriberInfo/title",
          "value": "CTSubscriberInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriberInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTSubscriberInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriberInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTSubscriberInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriber/title",
          "value": "CTSubscriber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTSubscriber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTSubscriber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTSubscriber"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretelephony/ctsubscriberdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretelephony/ctsubscriberdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
