{
  "abstract": [
    {
      "text": "An object that provides notifications of changes to the user’s cellular service provider.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretelephony/documentation/CoreTelephony"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CTTelephonyNetworkInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTTelephonyNetworkInfo"
      }
    ],
    "modules": [
      {
        "name": "Core Telephony"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTTelephonyNetworkInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CTTelephonyNetworkInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTTelephonyNetworkInfo"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your app should be able to handle changes to the user’s cellular service provider. For example, the user could swap the device’s SIM card with one from another provider while your app is running.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This class also gives you access to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCarrier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, which contains information about the user’s home cellular service provider.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretelephony/documentation/CoreTelephony": {
      "abstract": [
        {
          "text": "Access information about a user’s cellular service provider, such as its unique identifier and whether the carrier allows VoIP.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Telephony",
      "type": "topic",
      "url": "/documentation/coretelephony"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCarrier": {
      "abstract": [
        {
          "text": "Information about the user’s cellular service provider, such as its unique identifier and whether it allows VoIP calls on its network.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCarrier"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCarrier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCarrier"
        }
      ],
      "role": "symbol",
      "title": "CTCarrier",
      "type": "topic",
      "url": "/documentation/coretelephony/ctcarrier"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyDidChangeNotification": {
      "abstract": [
        {
          "text": "The name of the notification indicating that the radio access technology changed for one of the services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "CTRadioAccessTechnologyDidChangeNotification",
      "type": "topic",
      "url": "/documentation/coretelephony/ctradioaccesstechnologydidchangenotification"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTServiceRadioAccessTechnologyDidChangeNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CTServiceRadioAccessTechnologyDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTServiceRadioAccessTechnologyDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "CTServiceRadioAccessTechnologyDidChangeNotification",
      "type": "topic",
      "url": "/documentation/coretelephony/ctserviceradioaccesstechnologydidchangenotification"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo": {
      "abstract": [
        {
          "text": "An object that provides notifications of changes to the user’s cellular service provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTTelephonyNetworkInfo"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTTelephonyNetworkInfo"
        }
      ],
      "role": "symbol",
      "title": "CTTelephonyNetworkInfo",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/currentRadioAccessTechnology": {
      "abstract": [
        {
          "text": "The current radio access technology registered with the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentRadioAccessTechnology"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/currentRadioAccessTechnology",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentRadioAccessTechnology"
        }
      ],
      "role": "symbol",
      "title": "currentRadioAccessTechnology",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo/currentradioaccesstechnology"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/dataServiceIdentifier": {
      "abstract": [
        {
          "text": "The identifier of the service that’s currently providing data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataServiceIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/dataServiceIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataServiceIdentifier"
        }
      ],
      "role": "symbol",
      "title": "dataServiceIdentifier",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo/dataserviceidentifier"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/delegate": {
      "abstract": [
        {
          "text": "An object that the system notifies when the data service identifier changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CTTelephonyNetworkInfoDelegate",
          "text": "CTTelephonyNetworkInfoDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo/delegate"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology": {
      "abstract": [
        {
          "text": "A dictionary containing the current radio access technology registered to each service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceCurrentRadioAccessTechnology"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serviceCurrentRadioAccessTechnology"
        }
      ],
      "role": "symbol",
      "title": "serviceCurrentRadioAccessTechnology",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo/servicecurrentradioaccesstechnology"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProviders": {
      "abstract": [
        {
          "text": "A dictionary that contains carrier information about each service.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceSubscriberCellularProviders"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CTCarrier",
          "text": "CTCarrier"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProviders",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serviceSubscriberCellularProviders"
        }
      ],
      "role": "symbol",
      "title": "serviceSubscriberCellularProviders",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo/servicesubscribercellularproviders"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProvidersDidUpdateNotifier": {
      "abstract": [
        {
          "text": "A block dispatched when there are updates to the user’s cellular provider information for any service.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceSubscriberCellularProvidersDidUpdateNotifier"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProvidersDidUpdateNotifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serviceSubscriberCellularProvidersDidUpdateNotifier"
        }
      ],
      "role": "symbol",
      "title": "serviceSubscriberCellularProvidersDidUpdateNotifier",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo/servicesubscribercellularprovidersdidupdatenotifier"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProvider": {
      "abstract": [
        {
          "text": "Information about the user’s cellular service provider.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriberCellularProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CTCarrier",
          "text": "CTCarrier"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscriberCellularProvider"
        }
      ],
      "role": "symbol",
      "title": "subscriberCellularProvider",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo/subscribercellularprovider"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProviderDidUpdateNotifier": {
      "abstract": [
        {
          "text": "A block dispatched when the user’s cellular service provider information changes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriberCellularProviderDidUpdateNotifier"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CTCarrier",
          "text": "CTCarrier"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProviderDidUpdateNotifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscriberCellularProviderDidUpdateNotifier"
        }
      ],
      "role": "symbol",
      "title": "subscriberCellularProviderDidUpdateNotifier",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfo/subscribercellularproviderdidupdatenotifier"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfoDelegate": {
      "abstract": [
        {
          "text": "The methods that the system invokes when data service changes occur.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTTelephonyNetworkInfoDelegate"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfoDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTTelephonyNetworkInfoDelegate"
        }
      ],
      "role": "symbol",
      "title": "CTTelephonyNetworkInfoDelegate",
      "type": "topic",
      "url": "/documentation/coretelephony/cttelephonynetworkinfodelegate"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/radio-access-technology-constants": {
      "abstract": [
        {
          "text": "Constants that describe the current radio access technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/radio-access-technology-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Radio Access Technology Constants",
      "type": "topic",
      "url": "/documentation/coretelephony/radio-access-technology-constants"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1616908-ctradioaccesstechnologydidchange": {
      "abstract": [
        {
          "text": "The name of the notification indicating that the radio access technology changed for one of the services.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "CTRadioAccessTechnologyDidChange"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1616908-ctradioaccesstechnologydidchange",
      "kind": "symbol",
      "role": "symbol",
      "title": "CTRadioAccessTechnologyDidChange",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1616908-ctradioaccesstechnologydidchange"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Service-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCarrier"
      ],
      "title": "Service Information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-Information-About-the-Cellular-Service-Provider",
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/dataServiceIdentifier",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/delegate",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfoDelegate",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/radio-access-technology-constants"
      ],
      "title": "Getting Information About the Cellular Service Provider"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/currentRadioAccessTechnology",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProvider",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProviderDidUpdateNotifier",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProviders",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProvidersDidUpdateNotifier",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1616908-ctradioaccesstechnologydidchange"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTTelephonyNetworkInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTelephonyNetworkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTelephonyNetworkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretelephony/documentation/CoreTelephony"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-Information-About-the-Cellular-Service-Provider",
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/dataServiceIdentifier",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/delegate",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfoDelegate",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceCurrentRadioAccessTechnology",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/radio-access-technology-constants"
              ],
              "title": "Getting Information About the Cellular Service Provider"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/currentRadioAccessTechnology",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProvider",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/subscriberCellularProviderDidUpdateNotifier",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProviders",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTTelephonyNetworkInfo/serviceSubscriberCellularProvidersDidUpdateNotifier",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTServiceRadioAccessTechnologyDidChangeNotification",
                "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1616908-ctradioaccesstechnologydidchange",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTRadioAccessTechnologyDidChangeNotification"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Service-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/CTCarrier"
              ],
              "title": "Service Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTTelephonyNetworkInfo"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/title",
          "value": "CTTelephonyNetworkInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTelephonyNetworkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTelephonyNetworkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceSubscriberCellularProvidersDidUpdateNotifier/title",
          "value": "serviceSubscriberCellularProvidersDidUpdateNotifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceSubscriberCellularProvidersDidUpdateNotifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serviceSubscriberCellularProvidersDidUpdateNotifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1subscriberCellularProvider/title",
          "value": "subscriberCellularProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1subscriberCellularProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subscriberCellularProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCarrier/title",
          "value": "CTCarrier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCarrier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCarrier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTCarrier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCarrier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1dataServiceIdentifier/title",
          "value": "dataServiceIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1dataServiceIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dataServiceIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceSubscriberCellularProviders/title",
          "value": "serviceSubscriberCellularProviders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceSubscriberCellularProviders/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serviceSubscriberCellularProviders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfoDelegate/title",
          "value": "CTTelephonyNetworkInfoDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfoDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTelephonyNetworkInfoDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfoDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTelephonyNetworkInfoDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1subscriberCellularProviderDidUpdateNotifier/title",
          "value": "subscriberCellularProviderDidUpdateNotifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1subscriberCellularProviderDidUpdateNotifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subscriberCellularProviderDidUpdateNotifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceCurrentRadioAccessTechnology/title",
          "value": "serviceCurrentRadioAccessTechnology"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1serviceCurrentRadioAccessTechnology/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serviceCurrentRadioAccessTechnology"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1currentRadioAccessTechnology/title",
          "value": "currentRadioAccessTechnology"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTTelephonyNetworkInfo~1currentRadioAccessTechnology/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentRadioAccessTechnology"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretelephony/cttelephonynetworkinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretelephony/cttelephonynetworkinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
