{
  "abstract": [
    {
      "text": "Error domains used by Core Telephony errors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretelephony/documentation/CoreTelephony",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/CTError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretelephony/documentation/CoreTelephony/error-domain-codes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Telephony"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Error Domains"
  },
  "references": {
    "doc://com.apple.coretelephony/documentation/CoreTelephony": {
      "abstract": [
        {
          "text": "Access information about a user’s cellular service provider, such as its unique identifier and whether the carrier allows VoIP.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Telephony",
      "type": "topic",
      "url": "/documentation/coretelephony"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/CTError": {
      "abstract": [
        {
          "text": "A type representing a Core Telephony error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTError"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/CTError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTError"
        }
      ],
      "role": "symbol",
      "title": "CTError",
      "type": "topic",
      "url": "/documentation/coretelephony/cterror"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/kCTErrorDomainMach": {
      "abstract": [
        {
          "text": "The domain value for errors reported by Mach.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTErrorDomainMach"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/kCTErrorDomainMach",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTErrorDomainMach"
        }
      ],
      "role": "symbol",
      "title": "kCTErrorDomainMach",
      "type": "topic",
      "url": "/documentation/coretelephony/kcterrordomainmach"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/kCTErrorDomainNoError": {
      "abstract": [
        {
          "text": "The domain value indicating there is no error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTErrorDomainNoError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/kCTErrorDomainNoError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTErrorDomainNoError"
        }
      ],
      "role": "symbol",
      "title": "kCTErrorDomainNoError",
      "type": "topic",
      "url": "/documentation/coretelephony/kcterrordomainnoerror"
    },
    "doc://com.apple.coretelephony/documentation/CoreTelephony/kCTErrorDomainPOSIX": {
      "abstract": [
        {
          "text": "The domain value for errors from POSIX.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTErrorDomainPOSIX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretelephony/documentation/CoreTelephony/kCTErrorDomainPOSIX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTErrorDomainPOSIX"
        }
      ],
      "role": "symbol",
      "title": "kCTErrorDomainPOSIX",
      "type": "topic",
      "url": "/documentation/coretelephony/kcterrordomainposix"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Error-Domains",
      "identifiers": [
        "doc://com.apple.coretelephony/documentation/CoreTelephony/kCTErrorDomainMach",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/kCTErrorDomainNoError",
        "doc://com.apple.coretelephony/documentation/CoreTelephony/kCTErrorDomainPOSIX"
      ],
      "title": "Error Domains"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Domains",
              "identifiers": [
                "doc://com.apple.coretelephony/documentation/CoreTelephony/kCTErrorDomainMach",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/kCTErrorDomainNoError",
                "doc://com.apple.coretelephony/documentation/CoreTelephony/kCTErrorDomainPOSIX"
              ],
              "title": "Error Domains"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTError/title",
          "value": "CTError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1CTError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1kCTErrorDomainNoError/title",
          "value": "kCTErrorDomainNoError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1kCTErrorDomainNoError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTErrorDomainNoError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1kCTErrorDomainPOSIX/title",
          "value": "kCTErrorDomainPOSIX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1kCTErrorDomainPOSIX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTErrorDomainPOSIX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1kCTErrorDomainMach/title",
          "value": "kCTErrorDomainMach"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretelephony~1documentation~1CoreTelephony~1kCTErrorDomainMach/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTErrorDomainMach"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretelephony/error-domain-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretelephony/error-domain-codes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
