{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UICalendarViewDelegate/calendarView(_:didChangeVisibleDateComponentsFrom:)"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UICalendarViewDelegate"]]},"variants":[{"paths":["/documentation/uikit/uicalendarviewdelegate/calendarview(_:didchangevisibledatecomponentsfrom:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uicalendarviewdelegate/calendarview(_:didchangevisibledatecomponentsfrom:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","title":"calendarView(_:didChangeVisibleDateComponentsFrom:)","modules":[{"name":"UIKit"}],"externalID":"c:objc(pl)UICalendarViewDelegate(im)calendarView:didChangeVisibleDateComponentsFrom:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calendarView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UICalendarView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICalendarView"},{"text":", ","kind":"text"},{"text":"didChangeVisibleDateComponentsFrom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DateComponents","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation14DateComponentsV"},{"text":")","kind":"text"}],"platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","beta":false,"introducedAt":"16.2"},{"deprecated":false,"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"16.2"},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"16.2"},{"deprecated":false,"unavailable":false,"name":"visionOS","beta":false,"introducedAt":"1.0"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"calendarView:didChangeVisibleDateComponentsFrom:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calendarView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"calendarView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UICalendarView","text":"UICalendarView","preciseIdentifier":"c:objc(cs)UICalendarView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeVisibleDateComponentsFrom"},{"kind":"text","text":" "},{"kind":"internalParam","text":"previousDateComponents"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:10Foundation14DateComponentsV","text":"DateComponents","preciseIdentifier":"s:10Foundation14DateComponentsV"},{"kind":"text","text":")"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICalendarViewDelegate/calendarView(_:didChangeVisibleDateComponentsFrom:)":{"abstract":[],"title":"calendarView(_:didChangeVisibleDateComponentsFrom:)","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UICalendarViewDelegate/calendarView(_:didChangeVisibleDateComponentsFrom:)","url":"/documentation/uikit/uicalendarviewdelegate/calendarview(_:didchangevisibledatecomponentsfrom:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calendarView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UICalendarView","kind":"typeIdentifier","text":"UICalendarView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeVisibleDateComponentsFrom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation14DateComponentsV","kind":"typeIdentifier","text":"DateComponents"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"calendarView:didChangeVisibleDateComponentsFrom:"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICalendarViewDelegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"UICalendarViewDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that a calendar view uses to display decorations for dates."}],"navigatorTitle":[{"text":"UICalendarViewDelegate","kind":"identifier"}],"role":"symbol","url":"/documentation/uikit/uicalendarviewdelegate","title":"UICalendarViewDelegate","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UICalendarViewDelegate"},"doc://com.externally.resolved.symbol/s:10Foundation14DateComponentsV":{"fragments":[{"text":"struct ","kind":"text"},{"text":"DateComponents","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation14DateComponentsV","type":"topic","title":"DateComponents","role":"symbol","url":"/documentation/foundation/datecomponents","kind":"symbol","abstract":[{"text":"A date or time specified in terms of units (such as year, month, day, hour, and minute) to be evaluated in a calendar system and time zone. ","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UICalendarView":{"type":"topic","abstract":[{"type":"text","text":"A view that displays a calendar with date-specific decorations, and provides for user selection of a single date or multiple dates."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UICalendarView"}],"url":"/documentation/uikit/uicalendarview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UICalendarView"}],"title":"UICalendarView","identifier":"doc://com.apple.uikit/documentation/UIKit/UICalendarView","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false,"introducedAt":"16.2"},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"16.2"},{"unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"16.2"},{"unavailable":false,"name":"visionOS","beta":false,"deprecated":false,"introducedAt":"1.0"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"calendarView:didChangeVisibleDateComponentsFrom:","path":"/metadata/title"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"calendarView:didChangeVisibleDateComponentsFrom:","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UICalendarViewDelegate"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"add","path":"/seeAlsoSections","value":null},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"calendarView:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICalendarView","text":"UICalendarView","preciseIdentifier":"c:objc(cs)UICalendarView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"calendarView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didChangeVisibleDateComponentsFrom:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSDateComponents","preciseIdentifier":"c:objc(cs)NSDateComponents"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"previousDateComponents"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarViewDelegate~1calendarView(_:didChangeVisibleDateComponentsFrom:)/title","op":"replace","value":"calendarView:didChangeVisibleDateComponentsFrom:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarViewDelegate~1calendarView(_:didChangeVisibleDateComponentsFrom:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calendarView:didChangeVisibleDateComponentsFrom:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarViewDelegate/title","op":"replace","value":"UICalendarViewDelegate"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarViewDelegate/fragments","op":"replace","value":[{"text":"UICalendarViewDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarViewDelegate/navigatorTitle","op":"replace","value":[{"text":"UICalendarViewDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView/title","op":"replace","value":"UICalendarView"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView/fragments","op":"replace","value":[{"kind":"identifier","text":"UICalendarView"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UICalendarView"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}