{
  "abstract": [
    {
      "text": "A transform that sets the maximum value to the specified parameter value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/maxValue"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MIDITransformType@kMIDITransform_MaxValue",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "maxValue"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMIDITransform_MaxValue"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MIDITransformType.maxValue"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "maxValue"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType": {
      "abstract": [
        {
          "text": "Values that specify the type of MIDI transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDITransformType"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDITransformType"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/add": {
      "abstract": [
        {
          "text": "A transform that adds a parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/add",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDITransform_Add"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType.add",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype/add"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/filterOut": {
      "abstract": [
        {
          "text": "A transformation that filters out an event type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filterOut"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/filterOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDITransform_FilterOut"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType.filterOut",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype/filterout"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/mapControl": {
      "abstract": [
        {
          "text": "A transformation that changes a specified control number to a supplied parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapControl"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/mapControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDITransform_MapControl"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType.mapControl",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype/mapcontrol"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/mapValue": {
      "abstract": [
        {
          "text": "A transform that maps one value to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapValue"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/mapValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDITransform_MapValue"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType.mapValue",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype/mapvalue"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/maxValue": {
      "abstract": [
        {
          "text": "A transform that sets the maximum value to the specified parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxValue"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/maxValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDITransform_MaxValue"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType.maxValue",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype/maxvalue"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/minValue": {
      "abstract": [
        {
          "text": "A transform that sets the minimum value to the specified parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minValue"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/minValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDITransform_MinValue"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType.minValue",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype/minvalue"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/none": {
      "abstract": [
        {
          "text": "No transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDITransform_None"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType.none",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype/none"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/scale": {
      "abstract": [
        {
          "text": "A transform that multiplies by the specified parameter value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scale"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/scale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDITransform_Scale"
        }
      ],
      "role": "symbol",
      "title": "MIDITransformType.scale",
      "type": "topic",
      "url": "/documentation/coremidi/miditransformtype/scale"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Transform-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/none",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/filterOut",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/mapControl",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/add",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/scale",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/minValue",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/mapValue"
      ],
      "title": "Transform Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMIDITransform_MaxValue"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDITransform_MaxValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Transform-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/none",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/filterOut",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/mapControl",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/add",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/scale",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/minValue",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDITransformType/mapValue"
              ],
              "title": "Transform Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kMIDITransform_MaxValue"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1scale/title",
          "value": "kMIDITransform_Scale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1scale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDITransform_Scale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1maxValue/title",
          "value": "kMIDITransform_MaxValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1maxValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDITransform_MaxValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1add/title",
          "value": "kMIDITransform_Add"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1add/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDITransform_Add"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1none/title",
          "value": "kMIDITransform_None"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDITransform_None"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1minValue/title",
          "value": "kMIDITransform_MinValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1minValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDITransform_MinValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1mapControl/title",
          "value": "kMIDITransform_MapControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1mapControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDITransform_MapControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType/title",
          "value": "MIDITransformType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDITransformType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDITransformType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1filterOut/title",
          "value": "kMIDITransform_FilterOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1filterOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDITransform_FilterOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1mapValue/title",
          "value": "kMIDITransform_MapValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDITransformType~1mapValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDITransform_MapValue"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/miditransformtype/maxvalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/miditransformtype/maxvalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
