{
  "abstract": [
    {
      "text": "Notifies the delegate when the workflow encounters an error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.automator/documentation/Automator",
        "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didError:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)AMWorkflowControllerDelegate(im)workflowController:didError:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "workflowController"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AMWorkflowController",
        "text": "AMWorkflowController"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didError"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Automator"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "workflowController:didError:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "workflowController(_:didError:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "workflowController"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "controller"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AMWorkflowController",
              "text": "AMWorkflowController"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didError"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The controller object sending the message.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "controller"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If a workflow error occurs, upon return contains an instance of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " that describes the problem.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.automator/documentation/Automator": {
      "abstract": [
        {
          "text": "Develop actions that the Automator app can load and run. View, edit, and run Automator workflows in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator",
      "kind": "symbol",
      "role": "collection",
      "title": "Automator",
      "type": "topic",
      "url": "/documentation/automator"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflowController": {
      "abstract": [
        {
          "text": "An object that lets you manage an Automator workflow in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMWorkflowController"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowController"
        }
      ],
      "role": "symbol",
      "title": "AMWorkflowController",
      "type": "topic",
      "url": "/documentation/automator/amworkflowcontroller"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods that a delegate of a workflow controller implements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMWorkflowControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "AMWorkflowControllerDelegate",
      "type": "topic",
      "url": "/documentation/automator/amworkflowcontrollerdelegate"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didError:)": {
      "abstract": [
        {
          "text": "Notifies the delegate when the workflow encounters an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AMWorkflowController",
          "text": "AMWorkflowController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate/workflowController(_:didError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "workflowController:didError:"
        }
      ],
      "role": "symbol",
      "title": "workflowController(_:didError:)",
      "type": "topic",
      "url": "/documentation/automator/amworkflowcontrollerdelegate/workflowcontroller(_:diderror:)"
    },
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "workflowController:didError:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "workflowController:didError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.automator/documentation/Automator",
                "doc://com.apple.automator/documentation/Automator/AMWorkflowControllerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "workflowController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AMWorkflowController",
                    "text": "AMWorkflowController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "controller"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didError:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The controller object sending the message.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "controller"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "If a workflow error occurs, upon return contains an instance of ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " that describes the problem.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowController(_:didError:)/title",
          "value": "workflowController:didError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate~1workflowController(_:didError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "workflowController:didError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate/title",
          "value": "AMWorkflowControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowController/title",
          "value": "AMWorkflowController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/automator/amworkflowcontrollerdelegate/workflowcontroller(_:diderror:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/automator/amworkflowcontrollerdelegate/workflowcontroller(_:diderror:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
