{
  "abstract": [
    {
      "text": "The GPU family 1, version 4 feature set for iOS.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v4"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLFeatureSet@MTLFeatureSet_iOS_GPUFamily1_v4",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "iOS_GPUFamily1_v4"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLFeatureSet_iOS_GPUFamily1_v4"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLFeatureSet.iOS_GPUFamily1_v4"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "iOS_GPUFamily1_v4"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This feature set corresponds with Apple A7 devices running iOS 11.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet": {
      "abstract": [
        {
          "text": "The device feature sets that define specific platform, hardware, and software configurations.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLFeatureSet"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v1": {
      "abstract": [
        {
          "text": "The GPU family 1, version 1 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily1_v1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily1_v1"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily1_v1",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily1_v1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v2": {
      "abstract": [
        {
          "text": "The GPU family 1, version 2 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily1_v2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily1_v2"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily1_v2",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily1_v2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v3": {
      "abstract": [
        {
          "text": "The GPU family 1, version 3 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily1_v3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily1_v3"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily1_v3",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily1_v3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v4": {
      "abstract": [
        {
          "text": "The GPU family 1, version 4 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily1_v4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily1_v4"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily1_v4",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily1_v4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v5": {
      "abstract": [
        {
          "text": "The GPU family 1, version 5 feature set for iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS_GPUFamily1_v5"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLFeatureSet_iOS_GPUFamily1_v5"
        }
      ],
      "role": "symbol",
      "title": "MTLFeatureSet.iOS_GPUFamily1_v5",
      "type": "topic",
      "url": "/documentation/metal/mtlfeatureset/ios_gpufamily1_v5"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "iOS-GPU-Family-1",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v5",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v3",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v2",
        "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v1"
      ],
      "title": "iOS GPU Family 1"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLFeatureSet_iOS_GPUFamily1_v4"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily1_v4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "iOS-GPU-Family-1",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v5",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v3",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v2",
                "doc://com.apple.metal/documentation/Metal/MTLFeatureSet/iOS_GPUFamily1_v1"
              ],
              "title": "iOS GPU Family 1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLFeatureSet_iOS_GPUFamily1_v4"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet/title",
          "value": "MTLFeatureSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v5/title",
          "value": "MTLFeatureSet_iOS_GPUFamily1_v5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily1_v5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v3/title",
          "value": "MTLFeatureSet_iOS_GPUFamily1_v3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily1_v3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v2/title",
          "value": "MTLFeatureSet_iOS_GPUFamily1_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily1_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v1/title",
          "value": "MTLFeatureSet_iOS_GPUFamily1_v1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily1_v1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v4/title",
          "value": "MTLFeatureSet_iOS_GPUFamily1_v4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLFeatureSet~1iOS_GPUFamily1_v4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLFeatureSet_iOS_GPUFamily1_v4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlfeatureset/ios_gpufamily1_v4"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlfeatureset/ios_gpufamily1_v4"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
