{
  "abstract": [
    {
      "text": "A constant that represents a list formation, so drag images display vertically, non-overlapping with the left edges aligned.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/list"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSDraggingFormation@NSDraggingFormationList",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "list"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSDraggingFormationList"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSDraggingFormation.list"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "list"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation": {
      "abstract": [
        {
          "text": "Constants that control the visual format of multiple dragging items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDraggingFormation"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingFormation"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingFormation",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingformation"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/default": {
      "abstract": [
        {
          "text": "A constant that represents the system determined formation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingFormationDefault"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingFormation.default",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingformation/default"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/list": {
      "abstract": [
        {
          "text": "A constant that represents a list formation, so drag images display vertically, non-overlapping with the left edges aligned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "list"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/list",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingFormationList"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingFormation.list",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingformation/list"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/none": {
      "abstract": [
        {
          "text": "A constant that represents no custom formation, so drag images maintain their set positions relative to each other.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingFormationNone"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingFormation.none",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingformation/none"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/pile": {
      "abstract": [
        {
          "text": "A constant that represents a pile formation, so drag images display on top of each other with random rotations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pile"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/pile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingFormationPile"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingFormation.pile",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingformation/pile"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/stack": {
      "abstract": [
        {
          "text": "A constant that represents a stack formation, so drag images display overlapping diagonally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stack"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/stack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDraggingFormationStack"
        }
      ],
      "role": "symbol",
      "title": "NSDraggingFormation.stack",
      "type": "topic",
      "url": "/documentation/appkit/nsdraggingformation/stack"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/default",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/none",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/pile",
        "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/stack"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSDraggingFormationList"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingFormationList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/default",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/none",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/pile",
                "doc://com.apple.appkit/documentation/AppKit/NSDraggingFormation/stack"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSDraggingFormationList"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingFormation~1default/title",
          "value": "NSDraggingFormationDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingFormation~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingFormationDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingFormation~1pile/title",
          "value": "NSDraggingFormationPile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingFormation~1pile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingFormationPile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingFormation~1list/title",
          "value": "NSDraggingFormationList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingFormation~1list/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingFormationList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingFormation~1none/title",
          "value": "NSDraggingFormationNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingFormation~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingFormationNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingFormation~1stack/title",
          "value": "NSDraggingFormationStack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingFormation~1stack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingFormationStack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingFormation/title",
          "value": "NSDraggingFormation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingFormation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingFormation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDraggingFormation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDraggingFormation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdraggingformation/list"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsdraggingformation/list"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
