{
  "abstract": [
    {
      "text": "Constants that specify the modes for showing and hiding the scope bar.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UISearchControllerScopeBarActivation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ScopeBarActivation"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ScopeBarActivation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UISearchController.ScopeBarActivation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ScopeBarActivation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You use these constants with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/scopeBarActivation-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController": {
      "abstract": [
        {
          "text": "A view controller that manages the display of search results based on interactions with a search bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchController"
        }
      ],
      "role": "symbol",
      "title": "UISearchController",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify the modes for showing and hiding the scope bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ScopeBarActivation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ScopeBarActivation"
        }
      ],
      "role": "symbol",
      "title": "UISearchController.ScopeBarActivation",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/scopebaractivation-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/automatic": {
      "abstract": [
        {
          "text": "A mode in which the system automatically determines when to show and hide the scope bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchControllerScopeBarActivationAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UISearchController.ScopeBarActivation.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/scopebaractivation-swift.enum/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/scopebaractivation-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/manual": {
      "abstract": [
        {
          "text": "A mode that gives you manual control over when to show and hide the scope bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manual"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/manual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchControllerScopeBarActivationManual"
        }
      ],
      "role": "symbol",
      "title": "UISearchController.ScopeBarActivation.manual",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/scopebaractivation-swift.enum/manual"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/onSearchActivation": {
      "abstract": [
        {
          "text": "A mode in which the search controller shows the scope bar when search becomes active, and hides it after search cancellation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onSearchActivation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/onSearchActivation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchControllerScopeBarActivationOnSearchActivation"
        }
      ],
      "role": "symbol",
      "title": "UISearchController.ScopeBarActivation.onSearchActivation",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/scopebaractivation-swift.enum/onsearchactivation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/onTextEntry": {
      "abstract": [
        {
          "text": "A mode in which the search controller shows the scope bar when typing begins in the search field, and hides it after search cancellation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onTextEntry"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/onTextEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchControllerScopeBarActivationOnTextEntry"
        }
      ],
      "role": "symbol",
      "title": "UISearchController.ScopeBarActivation.onTextEntry",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/scopebaractivation-swift.enum/ontextentry"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/automaticallyShowsCancelButton": {
      "abstract": [
        {
          "text": "A Boolean indicating whether the search controller manages the visibility of the search bar’s cancel button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticallyShowsCancelButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/automaticallyShowsCancelButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticallyShowsCancelButton"
        }
      ],
      "role": "symbol",
      "title": "automaticallyShowsCancelButton",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/automaticallyshowscancelbutton"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/automaticallyShowsScopeBar": {
      "abstract": [
        {
          "text": "A Boolean indicating whether the search controller manages the visibility of the search bar’s scope bar.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticallyShowsScopeBar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/automaticallyShowsScopeBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticallyShowsScopeBar"
        }
      ],
      "role": "symbol",
      "title": "automaticallyShowsScopeBar",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/automaticallyshowsscopebar"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/automaticallyShowsSearchResultsController": {
      "abstract": [
        {
          "text": "A Boolean indicating whether the search controller manages the visibility of its results controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticallyShowsSearchResultsController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/automaticallyShowsSearchResultsController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticallyShowsSearchResultsController"
        }
      ],
      "role": "symbol",
      "title": "automaticallyShowsSearchResultsController",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/automaticallyshowssearchresultscontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/hidesNavigationBarDuringPresentation": {
      "abstract": [
        {
          "text": "A Boolean indicating whether to hide the navigation bar when searching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hidesNavigationBarDuringPresentation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/hidesNavigationBarDuringPresentation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hidesNavigationBarDuringPresentation"
        }
      ],
      "role": "symbol",
      "title": "hidesNavigationBarDuringPresentation",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/hidesnavigationbarduringpresentation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/ignoresSearchSuggestionsForSearchBarPlacementStacked": {
      "abstract": [
        {
          "text": "A Boolean value you use to specify whether the search controller prevents search suggestions from displaying for a stacked search bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ignoresSearchSuggestionsForSearchBarPlacementStacked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/ignoresSearchSuggestionsForSearchBarPlacementStacked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ignoresSearchSuggestionsForSearchBarPlacementStacked"
        }
      ],
      "role": "symbol",
      "title": "ignoresSearchSuggestionsForSearchBarPlacementStacked",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/ignoressearchsuggestionsforsearchbarplacementstacked"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/obscuresBackgroundDuringPresentation": {
      "abstract": [
        {
          "text": "A Boolean indicating whether to obscure the underlying content during a search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "obscuresBackgroundDuringPresentation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/obscuresBackgroundDuringPresentation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "obscuresBackgroundDuringPresentation"
        }
      ],
      "role": "symbol",
      "title": "obscuresBackgroundDuringPresentation",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/obscuresbackgroundduringpresentation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/scopeBarActivation-swift.property": {
      "abstract": [
        {
          "text": "A mode that determines when the search controller shows and hides the scope bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scopeBarActivation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchController",
          "text": "UISearchController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISearchControllerScopeBarActivation",
          "text": "ScopeBarActivation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/scopeBarActivation-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scopeBarActivation"
        }
      ],
      "role": "symbol",
      "title": "scopeBarActivation",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/scopebaractivation-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/searchBarPlacement": {
      "abstract": [
        {
          "text": "The placement of the search bar in the navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchBarPlacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UINavigationItem",
          "text": "UINavigationItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UINavigationItemSearchBarPlacement",
          "text": "SearchBarPlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/searchBarPlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchBarPlacement"
        }
      ],
      "role": "symbol",
      "title": "searchBarPlacement",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/searchbarplacement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/showsSearchResultsController": {
      "abstract": [
        {
          "text": "A Boolean indicating whether the search results controller is visible when the search controller is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsSearchResultsController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/showsSearchResultsController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsSearchResultsController"
        }
      ],
      "role": "symbol",
      "title": "showsSearchResultsController",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/showssearchresultscontroller"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-search-interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/obscuresBackgroundDuringPresentation",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/hidesNavigationBarDuringPresentation",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/automaticallyShowsCancelButton",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/automaticallyShowsSearchResultsController",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/showsSearchResultsController",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/searchBarPlacement",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/ignoresSearchSuggestionsForSearchBarPlacementStacked",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/automaticallyShowsScopeBar",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/scopeBarActivation-swift.property"
      ],
      "title": "Configuring the search interface"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/manual",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/onTextEntry",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/onSearchActivation"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UISearchControllerScopeBarActivation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchControllerScopeBarActivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchControllerScopeBarActivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/manual",
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/onTextEntry",
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/ScopeBarActivation-swift.enum/onSearchActivation"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-search-interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/obscuresBackgroundDuringPresentation",
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/hidesNavigationBarDuringPresentation",
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/automaticallyShowsCancelButton",
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/automaticallyShowsSearchResultsController",
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/showsSearchResultsController",
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/searchBarPlacement",
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/ignoresSearchSuggestionsForSearchBarPlacementStacked",
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/automaticallyShowsScopeBar",
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/scopeBarActivation-swift.property"
              ],
              "title": "Configuring the search interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UISearchControllerScopeBarActivation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1automaticallyShowsCancelButton/title",
          "value": "automaticallyShowsCancelButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1automaticallyShowsCancelButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticallyShowsCancelButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum~1onSearchActivation/title",
          "value": "UISearchControllerScopeBarActivationOnSearchActivation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum~1onSearchActivation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchControllerScopeBarActivationOnSearchActivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1hidesNavigationBarDuringPresentation/title",
          "value": "hidesNavigationBarDuringPresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1hidesNavigationBarDuringPresentation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hidesNavigationBarDuringPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1showsSearchResultsController/title",
          "value": "showsSearchResultsController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1showsSearchResultsController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsSearchResultsController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1scopeBarActivation-swift.property/title",
          "value": "scopeBarActivation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1scopeBarActivation-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scopeBarActivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1automaticallyShowsScopeBar/title",
          "value": "automaticallyShowsScopeBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1automaticallyShowsScopeBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticallyShowsScopeBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ignoresSearchSuggestionsForSearchBarPlacementStacked/title",
          "value": "ignoresSearchSuggestionsForSearchBarPlacementStacked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ignoresSearchSuggestionsForSearchBarPlacementStacked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ignoresSearchSuggestionsForSearchBarPlacementStacked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum/title",
          "value": "UISearchControllerScopeBarActivation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchControllerScopeBarActivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchControllerScopeBarActivation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum~1automatic/title",
          "value": "UISearchControllerScopeBarActivationAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchControllerScopeBarActivationAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1obscuresBackgroundDuringPresentation/title",
          "value": "obscuresBackgroundDuringPresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1obscuresBackgroundDuringPresentation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "obscuresBackgroundDuringPresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1automaticallyShowsSearchResultsController/title",
          "value": "automaticallyShowsSearchResultsController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1automaticallyShowsSearchResultsController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticallyShowsSearchResultsController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum~1onTextEntry/title",
          "value": "UISearchControllerScopeBarActivationOnTextEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum~1onTextEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchControllerScopeBarActivationOnTextEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController/title",
          "value": "UISearchController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum~1manual/title",
          "value": "UISearchControllerScopeBarActivationManual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ScopeBarActivation-swift.enum~1manual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchControllerScopeBarActivationManual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1searchBarPlacement/title",
          "value": "searchBarPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1searchBarPlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchBarPlacement"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisearchcontroller/scopebaractivation-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uisearchcontroller/scopebaractivation-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
