{
  "abstract": [
    {
      "text": "Display visualizations of the skeletal animation parameters for relevant geometries.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showSkeletons"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SCNDebugOptions@SCNDebugOptionShowSkeletons",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "showSkeletons"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SCNDebugOptions",
        "text": "SCNDebugOptions"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCNDebugOptionShowSkeletons"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "showSkeletons"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "showSkeletons"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SCNDebugOptions",
              "text": "SCNDebugOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions": {
      "abstract": [
        {
          "text": "Options for drawing overlays with SceneKit content that can aid in debugging, used with the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/debugOptions",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptions"
        }
      ],
      "role": "symbol",
      "title": "SCNDebugOptions",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/renderAsWireframe": {
      "abstract": [
        {
          "text": "Display only wireframe placeholders for geometries in the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renderAsWireframe"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/renderAsWireframe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionRenderAsWireframe"
        }
      ],
      "role": "symbol",
      "title": "renderAsWireframe",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/renderaswireframe"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showBoundingBoxes": {
      "abstract": [
        {
          "text": "Display the bounding boxes for any nodes with content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showBoundingBoxes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showBoundingBoxes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionShowBoundingBoxes"
        }
      ],
      "role": "symbol",
      "title": "showBoundingBoxes",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/showboundingboxes"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showConstraints": {
      "abstract": [
        {
          "text": "Display visualizations of the constraint objects acting on nodes in the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showConstraints"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showConstraints",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionShowConstraints"
        }
      ],
      "role": "symbol",
      "title": "showConstraints",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/showconstraints"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showCreases": {
      "abstract": [
        {
          "text": "Display nonsmoothed crease regions for geometries affected by surface subdivision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showCreases"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showCreases",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionShowCreases"
        }
      ],
      "role": "symbol",
      "title": "showCreases",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/showcreases"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showSkeletons": {
      "abstract": [
        {
          "text": "Display visualizations of the skeletal animation parameters for relevant geometries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showSkeletons"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showSkeletons",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionShowSkeletons"
        }
      ],
      "role": "symbol",
      "title": "showSkeletons",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/showskeletons"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showWireframe": {
      "abstract": [
        {
          "text": "Display geometries in the scene with wireframe rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showWireframe"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showWireframe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNDebugOptionShowWireframe"
        }
      ],
      "role": "symbol",
      "title": "showWireframe",
      "type": "topic",
      "url": "/documentation/scenekit/scndebugoptions/showwireframe"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/debugOptions": {
      "abstract": [
        {
          "text": "Options for drawing overlay content in a scene that can aid debugging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debugOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNDebugOptions",
          "text": "SCNDebugOptions"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/debugOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "debugOptions"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "debugOptions",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer/debugoptions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Debugging-Geometry-and-Animation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showBoundingBoxes",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showWireframe",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/renderAsWireframe",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showCreases",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showConstraints"
      ],
      "title": "Debugging Geometry and Animation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNDebugOptionShowSkeletons"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionShowSkeletons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Debugging-Geometry-and-Animation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showBoundingBoxes",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showWireframe",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/renderAsWireframe",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showCreases",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNDebugOptions/showConstraints"
              ],
              "title": "Debugging Geometry and Animation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SCNDebugOptionShowSkeletons"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showCreases/title",
          "value": "SCNDebugOptionShowCreases"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showCreases/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionShowCreases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1debugOptions/title",
          "value": "debugOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1debugOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "debugOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showWireframe/title",
          "value": "SCNDebugOptionShowWireframe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showWireframe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionShowWireframe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showSkeletons/title",
          "value": "SCNDebugOptionShowSkeletons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showSkeletons/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionShowSkeletons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showConstraints/title",
          "value": "SCNDebugOptionShowConstraints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showConstraints/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionShowConstraints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showBoundingBoxes/title",
          "value": "SCNDebugOptionShowBoundingBoxes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1showBoundingBoxes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionShowBoundingBoxes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions/title",
          "value": "SCNDebugOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1renderAsWireframe/title",
          "value": "SCNDebugOptionRenderAsWireframe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNDebugOptions~1renderAsWireframe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNDebugOptionRenderAsWireframe"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scndebugoptions/showskeletons"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scndebugoptions/showskeletons"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
