{
  "abstract": [
    {
      "text": "A Boolean value that determines whether the material responds identically to both ambient and diffuse lighting. Animatable.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/locksAmbientWithDiffuse"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SCNMaterial(py)locksAmbientWithDiffuse",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "locksAmbientWithDiffuse"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "locksAmbientWithDiffuse"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "locksAmbientWithDiffuse"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "locksAmbientWithDiffuse"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When modeling real-world lighting, a surface is typically considered to have a single “base” color or texture that is visible under both ambient and diffuse light. When this property’s value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", SceneKit does not have this limitation: you may use a material’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/diffuse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to provide a color or texture that is visible under direct lighting, and its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/ambient",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to provide a different color or texture for areas not directly illuminated.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When this property’s value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or when using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/LightingModel-swift.struct/physicallyBased",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " shading mode, SceneKit uses the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/diffuse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property for ambient lighting, ignoring the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/ambient",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property and ensuring that the material responds identically to both ambient and diffuse light.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The default value for this property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for new apps on all platforms. (In OS X v10.9 and earlier, the default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can animate changes to this property’s value. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Animating this property fades between the results of rendering with each state.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial": {
      "abstract": [
        {
          "text": "A set of shading attributes that define the appearance of a geometry’s surface when rendered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMaterial"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMaterial"
        }
      ],
      "role": "symbol",
      "title": "SCNMaterial",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterial"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/LightingModel-swift.struct/physicallyBased": {
      "abstract": [
        {
          "text": "Shading based on a realistic abstraction of physical lights and materials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "physicallyBased"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNMaterial",
          "text": "SCNMaterial"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNLightingModel",
          "text": "LightingModel"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/LightingModel-swift.struct/physicallyBased",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNLightingModelPhysicallyBased"
        }
      ],
      "role": "symbol",
      "title": "physicallyBased",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterial/lightingmodel-swift.struct/physicallybased"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/ambient": {
      "abstract": [
        {
          "text": "An object that manages the material’s response to ambient lighting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ambient"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNMaterialProperty",
          "text": "SCNMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/ambient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ambient"
        }
      ],
      "role": "symbol",
      "title": "ambient",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterial/ambient"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/diffuse": {
      "abstract": [
        {
          "text": "An object that manages the material’s diffuse response to lighting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "diffuse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNMaterialProperty",
          "text": "SCNMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/diffuse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "diffuse"
        }
      ],
      "role": "symbol",
      "title": "diffuse",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterial/diffuse"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/fresnelExponent": {
      "abstract": [
        {
          "text": "A factor affecting the material’s reflectivity. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fresnelExponent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/fresnelExponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fresnelExponent"
        }
      ],
      "role": "symbol",
      "title": "fresnelExponent",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterial/fresnelexponent"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/locksAmbientWithDiffuse": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the material responds identically to both ambient and diffuse lighting. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locksAmbientWithDiffuse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/locksAmbientWithDiffuse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locksAmbientWithDiffuse"
        }
      ],
      "role": "symbol",
      "title": "locksAmbientWithDiffuse",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterial/locksambientwithdiffuse"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/multiply": {
      "abstract": [
        {
          "text": "An object that provides color values that are multiplied with pixels in a material after all other shading is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiply"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNMaterialProperty",
          "text": "SCNMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/multiply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "multiply"
        }
      ],
      "role": "symbol",
      "title": "multiply",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterial/multiply"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/reflective": {
      "abstract": [
        {
          "text": "An object that defines the reflected color for each point on a surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reflective"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNMaterialProperty",
          "text": "SCNMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/reflective",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reflective"
        }
      ],
      "role": "symbol",
      "title": "reflective",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterial/reflective"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/shininess": {
      "abstract": [
        {
          "text": "The sharpness of specular highlights. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shininess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/shininess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shininess"
        }
      ],
      "role": "symbol",
      "title": "shininess",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterial/shininess"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/specular": {
      "abstract": [
        {
          "text": "An object that manages the material’s specular response to lighting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "specular"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNMaterialProperty",
          "text": "SCNMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/specular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "specular"
        }
      ],
      "role": "symbol",
      "title": "specular",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterial/specular"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/transparent": {
      "abstract": [
        {
          "text": "An object that determines the opacity of each point in a material.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transparent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNMaterialProperty",
          "text": "SCNMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/transparent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transparent"
        }
      ],
      "role": "symbol",
      "title": "transparent",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterial/transparent"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content": {
      "abstract": [
        {
          "text": "Learn about implicit animations, explicit animations, and actions, and when to choose each in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/animating-scenekit-content",
      "kind": "article",
      "role": "article",
      "title": "Animating SceneKit Content",
      "type": "topic",
      "url": "/documentation/scenekit/animating-scenekit-content"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Visual-Properties-for-Basic-Shading",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/diffuse",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/ambient",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/specular",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/reflective",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/multiply",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/transparent",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/shininess",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/fresnelExponent"
      ],
      "title": "Visual Properties for Basic Shading"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "locksAmbientWithDiffuse"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "locksAmbientWithDiffuse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Visual-Properties-for-Basic-Shading",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/diffuse",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/ambient",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/specular",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/reflective",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/multiply",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/transparent",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/shininess",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterial/fresnelExponent"
              ],
              "title": "Visual Properties for Basic Shading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "locksAmbientWithDiffuse"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1locksAmbientWithDiffuse/title",
          "value": "locksAmbientWithDiffuse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1locksAmbientWithDiffuse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "locksAmbientWithDiffuse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1reflective/title",
          "value": "reflective"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1reflective/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reflective"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1specular/title",
          "value": "specular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1specular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "specular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1fresnelExponent/title",
          "value": "fresnelExponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1fresnelExponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fresnelExponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1transparent/title",
          "value": "transparent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1transparent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transparent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1LightingModel-swift.struct~1physicallyBased/title",
          "value": "SCNLightingModelPhysicallyBased"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1LightingModel-swift.struct~1physicallyBased/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNLightingModelPhysicallyBased"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1ambient/title",
          "value": "ambient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1ambient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ambient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial/title",
          "value": "SCNMaterial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1diffuse/title",
          "value": "diffuse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1diffuse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "diffuse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1shininess/title",
          "value": "shininess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1shininess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shininess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1multiply/title",
          "value": "multiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterial~1multiply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "multiply"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnmaterial/locksambientwithdiffuse"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnmaterial/locksambientwithdiffuse"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
