{
  "abstract": [
    {
      "text": "An empty flag set that you use as a placeholder when you don’t want any of the other flags.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/AuthorizationFlags"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/AuthorizationFlags/kAuthorizationFlagDefaults"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AuthorizationFlags@kAuthorizationFlagDefaults",
    "fragments": [
      {
        "kind": "identifier",
        "text": "kAuthorizationFlagDefaults"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAuthorizationFlagDefaults"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "macOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "kAuthorizationFlagDefaults"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "kAuthorizationFlagDefaults"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationFlags": {
      "abstract": [
        {
          "text": "The flags used to specify authorization options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AuthorizationFlags"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AuthorizationFlags"
        }
      ],
      "role": "symbol",
      "title": "AuthorizationFlags",
      "type": "topic",
      "url": "/documentation/security/authorizationflags"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationFlags/kAuthorizationFlagDefaults": {
      "abstract": [
        {
          "text": "An empty flag set that you use as a placeholder when you don’t want any of the other flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kAuthorizationFlagDefaults"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationFlags/kAuthorizationFlagDefaults",
      "kind": "symbol",
      "role": "symbol",
      "title": "kAuthorizationFlagDefaults",
      "type": "topic",
      "url": "/documentation/security/authorizationflags/kauthorizationflagdefaults"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags/title",
          "value": "AuthorizationFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1AuthorizationFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AuthorizationFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/authorizationflags/kauthorizationflagdefaults"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
