{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/assignablePNC"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MIDICVStatus@kMIDICVStatusAssignablePNC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "assignablePNC"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMIDICVStatusAssignablePNC"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MIDICVStatus.assignablePNC"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "assignablePNC"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus": {
      "abstract": [
        {
          "text": "MIDI status types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICVStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICVStatus"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/assignableControl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assignableControl"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/assignableControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICVStatusAssignableControl"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus.assignableControl",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus/assignablecontrol"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/assignablePNC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assignablePNC"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/assignablePNC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICVStatusAssignablePNC"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus.assignablePNC",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus/assignablepnc"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/perNoteMgmt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perNoteMgmt"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/perNoteMgmt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICVStatusPerNoteMgmt"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus.perNoteMgmt",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus/pernotemgmt"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/perNotePitchBend": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perNotePitchBend"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/perNotePitchBend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICVStatusPerNotePitchBend"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus.perNotePitchBend",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus/pernotepitchbend"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/registeredControl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registeredControl"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/registeredControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICVStatusRegisteredControl"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus.registeredControl",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus/registeredcontrol"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/registeredPNC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registeredPNC"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/registeredPNC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICVStatusRegisteredPNC"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus.registeredPNC",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus/registeredpnc"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/relAssignableControl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relAssignableControl"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/relAssignableControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICVStatusRelAssignableControl"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus.relAssignableControl",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus/relassignablecontrol"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/relRegisteredControl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relRegisteredControl"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/relRegisteredControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICVStatusRelRegisteredControl"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus.relRegisteredControl",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus/relregisteredcontrol"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "MIDI-20",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/registeredPNC",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/registeredControl",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/assignableControl",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/relRegisteredControl",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/relAssignableControl",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/perNotePitchBend",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/perNoteMgmt"
      ],
      "title": "MIDI 2.0"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMIDICVStatusAssignablePNC"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICVStatusAssignablePNC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "MIDI-20",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/registeredPNC",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/registeredControl",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/assignableControl",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/relRegisteredControl",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/relAssignableControl",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/perNotePitchBend",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/perNoteMgmt"
              ],
              "title": "MIDI 2.0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kMIDICVStatusAssignablePNC"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1perNoteMgmt/title",
          "value": "kMIDICVStatusPerNoteMgmt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1perNoteMgmt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICVStatusPerNoteMgmt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1assignableControl/title",
          "value": "kMIDICVStatusAssignableControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1assignableControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICVStatusAssignableControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1relRegisteredControl/title",
          "value": "kMIDICVStatusRelRegisteredControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1relRegisteredControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICVStatusRelRegisteredControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1registeredPNC/title",
          "value": "kMIDICVStatusRegisteredPNC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1registeredPNC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICVStatusRegisteredPNC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1relAssignableControl/title",
          "value": "kMIDICVStatusRelAssignableControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1relAssignableControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICVStatusRelAssignableControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus/title",
          "value": "MIDICVStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICVStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICVStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1assignablePNC/title",
          "value": "kMIDICVStatusAssignablePNC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1assignablePNC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICVStatusAssignablePNC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1registeredControl/title",
          "value": "kMIDICVStatusRegisteredControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1registeredControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICVStatusRegisteredControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1perNotePitchBend/title",
          "value": "kMIDICVStatusPerNotePitchBend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1perNotePitchBend/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICVStatusPerNotePitchBend"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midicvstatus/assignablepnc"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midicvstatus/assignablepnc"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
