{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/noteOn"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MIDICVStatus@kMIDICVStatusNoteOn",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "noteOn"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMIDICVStatusNoteOn"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MIDICVStatus.noteOn"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "noteOn"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus": {
      "abstract": [
        {
          "text": "MIDI status types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICVStatus"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICVStatus"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/channelPressure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelPressure"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/channelPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICVStatusChannelPressure"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus.channelPressure",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus/channelpressure"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/controlChange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlChange"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/controlChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICVStatusControlChange"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus.controlChange",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus/controlchange"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/noteOff": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noteOff"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/noteOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICVStatusNoteOff"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus.noteOff",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus/noteoff"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/noteOn": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noteOn"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/noteOn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICVStatusNoteOn"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus.noteOn",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus/noteon"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/pitchBend": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pitchBend"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/pitchBend",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICVStatusPitchBend"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus.pitchBend",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus/pitchbend"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/polyPressure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "polyPressure"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/polyPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICVStatusPolyPressure"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus.polyPressure",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus/polypressure"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/programChange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "programChange"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/programChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICVStatusProgramChange"
        }
      ],
      "role": "symbol",
      "title": "MIDICVStatus.programChange",
      "type": "topic",
      "url": "/documentation/coremidi/midicvstatus/programchange"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "MIDI-10",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/noteOff",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/polyPressure",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/controlChange",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/programChange",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/channelPressure",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/pitchBend"
      ],
      "title": "MIDI 1.0"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMIDICVStatusNoteOn"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICVStatusNoteOn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "MIDI-10",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/noteOff",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/polyPressure",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/controlChange",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/programChange",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/channelPressure",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICVStatus/pitchBend"
              ],
              "title": "MIDI 1.0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kMIDICVStatusNoteOn"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1noteOn/title",
          "value": "kMIDICVStatusNoteOn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1noteOn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICVStatusNoteOn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus/title",
          "value": "MIDICVStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICVStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICVStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1polyPressure/title",
          "value": "kMIDICVStatusPolyPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1polyPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICVStatusPolyPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1programChange/title",
          "value": "kMIDICVStatusProgramChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1programChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICVStatusProgramChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1controlChange/title",
          "value": "kMIDICVStatusControlChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1controlChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICVStatusControlChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1noteOff/title",
          "value": "kMIDICVStatusNoteOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1noteOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICVStatusNoteOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1pitchBend/title",
          "value": "kMIDICVStatusPitchBend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1pitchBend/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICVStatusPitchBend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1channelPressure/title",
          "value": "kMIDICVStatusChannelPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICVStatus~1channelPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICVStatusChannelPressure"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midicvstatus/noteon"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midicvstatus/noteon"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
