{
  "abstract": [
    {
      "text": "The participant finishes in first place.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/first"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GKTurnBasedMatchOutcome@GKTurnBasedMatchOutcomeFirst",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "first"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKTurnBasedMatchOutcomeFirst"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "GKTurnBasedMatch.Outcome.first"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "first"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch": {
      "abstract": [
        {
          "text": "An object that encapsulates the match data for games where players take turns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatch"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatch"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatch",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome": {
      "abstract": [
        {
          "text": "The state of a participant when they forfeit a match or when a match ends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Outcome"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Outcome"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatch.Outcome",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/outcome"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/customRange": {
      "abstract": [
        {
          "text": "The participant reaches a game-specific outcome.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customRange"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/customRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatchOutcomeCustomRange"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatch.Outcome.customRange",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/outcome/customrange"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/first": {
      "abstract": [
        {
          "text": "The participant finishes in first place.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "first"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/first",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatchOutcomeFirst"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatch.Outcome.first",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/outcome/first"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/fourth": {
      "abstract": [
        {
          "text": "The participant finishes in fourth place.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fourth"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/fourth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatchOutcomeFourth"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatch.Outcome.fourth",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/outcome/fourth"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/lost": {
      "abstract": [
        {
          "text": "The participant loses the match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lost"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/lost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatchOutcomeLost"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatch.Outcome.lost",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/outcome/lost"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/none": {
      "abstract": [
        {
          "text": "The participant doesn’t reach an outcome.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatchOutcomeNone"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatch.Outcome.none",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/outcome/none"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/quit": {
      "abstract": [
        {
          "text": "The participant forfeits the match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quit"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/quit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatchOutcomeQuit"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatch.Outcome.quit",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/outcome/quit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/second": {
      "abstract": [
        {
          "text": "The participant finishes in second place.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "second"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/second",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatchOutcomeSecond"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatch.Outcome.second",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/outcome/second"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/third": {
      "abstract": [
        {
          "text": "The participant finishes in third place.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "third"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/third",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatchOutcomeThird"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatch.Outcome.third",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/outcome/third"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/tied": {
      "abstract": [
        {
          "text": "The participant ties the match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tied"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/tied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatchOutcomeTied"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatch.Outcome.tied",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/outcome/tied"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/timeExpired": {
      "abstract": [
        {
          "text": "The match ends because the time limit expires.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeExpired"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/timeExpired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatchOutcomeTimeExpired"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatch.Outcome.timeExpired",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/outcome/timeexpired"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/won": {
      "abstract": [
        {
          "text": "The participant wins the match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "won"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/won",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKTurnBasedMatchOutcomeWon"
        }
      ],
      "role": "symbol",
      "title": "GKTurnBasedMatch.Outcome.won",
      "type": "topic",
      "url": "/documentation/gamekit/gkturnbasedmatch/outcome/won"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Outcomes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/none",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/quit",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/won",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/lost",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/tied",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/timeExpired",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/second",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/third",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/fourth",
        "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/customRange"
      ],
      "title": "Outcomes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKTurnBasedMatchOutcomeFirst"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchOutcomeFirst"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Outcomes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/none",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/quit",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/won",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/lost",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/tied",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/timeExpired",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/second",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/third",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/fourth",
                "doc://com.apple.gamekit/documentation/GameKit/GKTurnBasedMatch/Outcome/customRange"
              ],
              "title": "Outcomes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "GKTurnBasedMatchOutcomeFirst"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1first/title",
          "value": "GKTurnBasedMatchOutcomeFirst"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1first/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchOutcomeFirst"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1second/title",
          "value": "GKTurnBasedMatchOutcomeSecond"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1second/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchOutcomeSecond"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome/title",
          "value": "GKTurnBasedMatchOutcome"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchOutcome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchOutcome"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1lost/title",
          "value": "GKTurnBasedMatchOutcomeLost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1lost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchOutcomeLost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1quit/title",
          "value": "GKTurnBasedMatchOutcomeQuit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1quit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchOutcomeQuit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1won/title",
          "value": "GKTurnBasedMatchOutcomeWon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1won/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchOutcomeWon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1third/title",
          "value": "GKTurnBasedMatchOutcomeThird"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1third/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchOutcomeThird"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1fourth/title",
          "value": "GKTurnBasedMatchOutcomeFourth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1fourth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchOutcomeFourth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch/title",
          "value": "GKTurnBasedMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1none/title",
          "value": "GKTurnBasedMatchOutcomeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchOutcomeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1customRange/title",
          "value": "GKTurnBasedMatchOutcomeCustomRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1customRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchOutcomeCustomRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1tied/title",
          "value": "GKTurnBasedMatchOutcomeTied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1tied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchOutcomeTied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1timeExpired/title",
          "value": "GKTurnBasedMatchOutcomeTimeExpired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKTurnBasedMatch~1Outcome~1timeExpired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKTurnBasedMatchOutcomeTimeExpired"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkturnbasedmatch/outcome/first"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkturnbasedmatch/outcome/first"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
