{
  "abstract": [
    {
      "text": "None of the currently resolved endpoints can be used at this time, either due to problems with the path or the client rejecting the endpoints.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/Network/nw_connection_state_t",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "type from the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/Network",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " framework instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/failed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NWUDPSessionState@NWUDPSessionStateFailed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "failed"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NWUDPSessionStateFailed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.0",
        "message": "Use `nw_connection_state_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWUDPSession.h>",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.0",
        "message": "Use `nw_connection_state_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWUDPSession.h>",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.1",
        "message": "Use `nw_connection_state_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWUDPSession.h>",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.11",
        "message": "Use `nw_connection_state_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWUDPSession.h>",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "17.0",
        "message": "Use `nw_connection_state_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWUDPSession.h>",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "Use `nw_connection_state_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWUDPSession.h>",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NWUDPSessionState.failed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "failed"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Network": {
      "abstract": [
        {
          "text": "Create network connections to send and receive data using transport and security protocols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Network",
      "kind": "symbol",
      "role": "collection",
      "title": "Network",
      "type": "topic",
      "url": "/documentation/Network"
    },
    "doc://com.apple.documentation/documentation/Network/nw_connection_state_t": {
      "abstract": [
        {
          "text": "States indicating whether a connection can be used to send and receive data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nw_connection_state_t"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Network/nw_connection_state_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "nw_connection_state_t",
      "type": "topic",
      "url": "/documentation/Network/nw_connection_state_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWUDPSessionState"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWUDPSessionState"
        }
      ],
      "role": "symbol",
      "title": "NWUDPSessionState",
      "type": "topic",
      "url": "/documentation/networkextension/nwudpsessionstate"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/cancelled": {
      "abstract": [
        {
          "text": "The session has been cancelled by the client calling ",
          "type": "text"
        },
        {
          "code": "cancel",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWUDPSessionStateCancelled"
        }
      ],
      "role": "symbol",
      "title": "NWUDPSessionState.cancelled",
      "type": "topic",
      "url": "/documentation/networkextension/nwudpsessionstate/cancelled"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/failed": {
      "abstract": [
        {
          "text": "None of the currently resolved endpoints can be used at this time, either due to problems with the path or the client rejecting the endpoints.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failed"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/failed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWUDPSessionStateFailed"
        }
      ],
      "role": "symbol",
      "title": "NWUDPSessionState.failed",
      "type": "topic",
      "url": "/documentation/networkextension/nwudpsessionstate/failed"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/invalid": {
      "abstract": [
        {
          "text": "The session is in an invalid or uninitialized state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalid"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/invalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWUDPSessionStateInvalid"
        }
      ],
      "role": "symbol",
      "title": "NWUDPSessionState.invalid",
      "type": "topic",
      "url": "/documentation/networkextension/nwudpsessionstate/invalid"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/preparing": {
      "abstract": [
        {
          "text": "The remote endpoint is being resolved.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preparing"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/preparing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWUDPSessionStatePreparing"
        }
      ],
      "role": "symbol",
      "title": "NWUDPSessionState.preparing",
      "type": "topic",
      "url": "/documentation/networkextension/nwudpsessionstate/preparing"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/ready": {
      "abstract": [
        {
          "text": "The session is ready for reading and writing data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWUDPSessionStateReady"
        }
      ],
      "role": "symbol",
      "title": "NWUDPSessionState.ready",
      "type": "topic",
      "url": "/documentation/networkextension/nwudpsessionstate/ready"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/waiting": {
      "abstract": [
        {
          "text": "The session is waiting for better conditions before attempting to make the session ready.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waiting"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/waiting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWUDPSessionStateWaiting"
        }
      ],
      "role": "symbol",
      "title": "NWUDPSessionState.waiting",
      "type": "topic",
      "url": "/documentation/networkextension/nwudpsessionstate/waiting"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Session-States",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/invalid",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/waiting",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/preparing",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/ready",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/cancelled"
      ],
      "title": "Session States"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NWUDPSessionStateFailed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWUDPSessionStateFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Session-States",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/invalid",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/waiting",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/preparing",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/ready",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NWUDPSessionState/cancelled"
              ],
              "title": "Session States"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NWUDPSessionStateFailed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Network/nw_connection_state_t",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "type from the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Network",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " framework instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSessionState~1failed/title",
          "value": "NWUDPSessionStateFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSessionState~1failed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWUDPSessionStateFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSessionState~1invalid/title",
          "value": "NWUDPSessionStateInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSessionState~1invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWUDPSessionStateInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSessionState~1cancelled/title",
          "value": "NWUDPSessionStateCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSessionState~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWUDPSessionStateCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSessionState/title",
          "value": "NWUDPSessionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSessionState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWUDPSessionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSessionState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NWUDPSessionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Network~1nw_connection_state_t/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " { ... } "
            },
            {
              "kind": "identifier",
              "text": "nw_connection_state_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSessionState~1preparing/title",
          "value": "NWUDPSessionStatePreparing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSessionState~1preparing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWUDPSessionStatePreparing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSessionState~1waiting/title",
          "value": "NWUDPSessionStateWaiting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSessionState~1waiting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWUDPSessionStateWaiting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSessionState~1ready/title",
          "value": "NWUDPSessionStateReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWUDPSessionState~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWUDPSessionStateReady"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nwudpsessionstate/failed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nwudpsessionstate/failed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
