{
  "abstract": [
    {
      "text": "The device is plugged into power and the battery is less than 100% charged.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIDevice",
        "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum/charging"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIDeviceBatteryState@UIDeviceBatteryStateCharging",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "charging"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIDeviceBatteryStateCharging"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIDevice.BatteryState.charging"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "charging"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDevice": {
      "abstract": [
        {
          "text": "A representation of the current device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDevice"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDevice"
        }
      ],
      "role": "symbol",
      "title": "UIDevice",
      "type": "topic",
      "url": "/documentation/uikit/uidevice"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the battery power state of the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BatteryState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BatteryState"
        }
      ],
      "role": "symbol",
      "title": "UIDevice.BatteryState",
      "type": "topic",
      "url": "/documentation/uikit/uidevice/batterystate-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum/charging": {
      "abstract": [
        {
          "text": "The device is plugged into power and the battery is less than 100% charged.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "charging"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum/charging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDeviceBatteryStateCharging"
        }
      ],
      "role": "symbol",
      "title": "UIDevice.BatteryState.charging",
      "type": "topic",
      "url": "/documentation/uikit/uidevice/batterystate-swift.enum/charging"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum/full": {
      "abstract": [
        {
          "text": "The device is plugged into power and the battery is 100% charged.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "full"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum/full",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDeviceBatteryStateFull"
        }
      ],
      "role": "symbol",
      "title": "UIDevice.BatteryState.full",
      "type": "topic",
      "url": "/documentation/uikit/uidevice/batterystate-swift.enum/full"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum/unknown": {
      "abstract": [
        {
          "text": "The battery state for the device can’t be determined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDeviceBatteryStateUnknown"
        }
      ],
      "role": "symbol",
      "title": "UIDevice.BatteryState.unknown",
      "type": "topic",
      "url": "/documentation/uikit/uidevice/batterystate-swift.enum/unknown"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum/unplugged": {
      "abstract": [
        {
          "text": "The device isn’t plugged into power; the battery is discharging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unplugged"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum/unplugged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDeviceBatteryStateUnplugged"
        }
      ],
      "role": "symbol",
      "title": "UIDevice.BatteryState.unplugged",
      "type": "topic",
      "url": "/documentation/uikit/uidevice/batterystate-swift.enum/unplugged"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum/unknown",
        "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum/unplugged",
        "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum/full"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIDeviceBatteryStateCharging"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceBatteryStateCharging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum/unknown",
                "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum/unplugged",
                "doc://com.apple.uikit/documentation/UIKit/UIDevice/BatteryState-swift.enum/full"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIDeviceBatteryStateCharging"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1BatteryState-swift.enum~1full/title",
          "value": "UIDeviceBatteryStateFull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1BatteryState-swift.enum~1full/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceBatteryStateFull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1BatteryState-swift.enum~1unplugged/title",
          "value": "UIDeviceBatteryStateUnplugged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1BatteryState-swift.enum~1unplugged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceBatteryStateUnplugged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1BatteryState-swift.enum~1unknown/title",
          "value": "UIDeviceBatteryStateUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1BatteryState-swift.enum~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceBatteryStateUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1BatteryState-swift.enum/title",
          "value": "UIDeviceBatteryState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1BatteryState-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceBatteryState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1BatteryState-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceBatteryState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice/title",
          "value": "UIDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1BatteryState-swift.enum~1charging/title",
          "value": "UIDeviceBatteryStateCharging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1BatteryState-swift.enum~1charging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceBatteryStateCharging"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uidevice/batterystate-swift.enum/charging"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uidevice/batterystate-swift.enum/charging"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
