{
  "abstract": [
    {
      "text": "Include an entitlement to indicate your extension is a MediaExtension format reader.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/format-reader-entitlement"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Format reader entitlement"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "MediaExtension",
              "type": "codeVoice"
            },
            {
              "text": " format readers must include an special entitlement key with a Boolean value set to true. To add the entitlement key in Xcode, follow these steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Select the build target for your format reader extension",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Go to the Signing & Capabilities tab",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click + to add a new capability",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Choose Media Extension Format Reader from the list",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The entitlement key is ",
              "type": "text"
            },
            {
              "code": "com.apple.developer.mediaextension.formatreader",
              "type": "codeVoice"
            },
            {
              "text": " and it must have a Boolean value set to true. A developer provisioning profile will be needed to use this entitlement.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo": {
      "abstract": [
        {
          "text": "An object that contains file properties from the media asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEFileInfo"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFileInfo"
        }
      ],
      "role": "symbol",
      "title": "MEFileInfo",
      "type": "topic",
      "url": "/documentation/mediaextension/mefileinfo"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader": {
      "abstract": [
        {
          "text": "A protocol that defines the requirements for a format reader, which represents a single media asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEFormatReader"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFormatReader"
        }
      ],
      "role": "symbol",
      "title": "MEFormatReader",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreader"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderExtension": {
      "abstract": [
        {
          "text": "A protocol that defines a factory to create a new format reader with a byte source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEFormatReaderExtension"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFormatReaderExtension"
        }
      ],
      "role": "symbol",
      "title": "MEFormatReaderExtension",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderInstantiationOptions": {
      "abstract": [
        {
          "text": "An object that contains options to pass to a format reader extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEFormatReaderInstantiationOptions"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderInstantiationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFormatReaderInstantiationOptions"
        }
      ],
      "role": "symbol",
      "title": "MEFormatReaderInstantiationOptions",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderinstantiationoptions"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/format-reader-property-list-dictionaries": {
      "abstract": [
        {
          "text": "Include property list dictionaries to describe a format reader and register the formats it supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/format-reader-property-list-dictionaries",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format reader property list dictionaries",
      "type": "topic",
      "url": "/documentation/mediaextension/format-reader-property-list-dictionaries"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Format-readers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderInstantiationOptions",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo",
        "doc://com.apple.mediaextension/documentation/MediaExtension/format-reader-property-list-dictionaries"
      ],
      "title": "Format readers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Format-readers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderExtension",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderInstantiationOptions",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFileInfo",
                "doc://com.apple.mediaextension/documentation/MediaExtension/format-reader-property-list-dictionaries"
              ],
              "title": "Format readers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderInstantiationOptions/title",
          "value": "MEFormatReaderInstantiationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderInstantiationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReaderInstantiationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderInstantiationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReaderInstantiationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReader/title",
          "value": "MEFormatReader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderExtension/title",
          "value": "MEFormatReaderExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReaderExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReaderExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo/title",
          "value": "MEFileInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFileInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFileInfo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/format-reader-entitlement"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaextension/format-reader-entitlement"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
