{
  "abstract": [
    {
      "text": "The unique identifier for the format reader.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderClassImplementationIDKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@kMEFormatReaderClassImplementationIDKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kMEFormatReaderClassImplementationIDKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMEFormatReaderClassImplementationIDKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kMEFormatReaderClassImplementationIDKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kMEFormatReaderClassImplementationIDKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Format the string similar to the bundle identifier of the format reader. Start with the reverse domain identifier of your developer account, followed by ",
              "type": "text"
            },
            {
              "code": ".formatreader.",
              "type": "codeVoice"
            },
            {
              "text": " and the name of the media format. If you plan to create multiple variants of the same media format, include an additional component to make each format reader identifier unique; for example ",
              "type": "text"
            },
            {
              "code": "com.mycompany.formatreader.mymediaformat.formatvariant",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderClassImplementationIDKey": {
      "abstract": [
        {
          "text": "The unique identifier for the format reader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMEFormatReaderClassImplementationIDKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderClassImplementationIDKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMEFormatReaderClassImplementationIDKey"
        }
      ],
      "role": "symbol",
      "title": "kMEFormatReaderClassImplementationIDKey",
      "type": "topic",
      "url": "/documentation/mediaextension/kmeformatreaderclassimplementationidkey"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderExtensionPointName": {
      "abstract": [
        {
          "text": "A key to the extension point name for format readers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMEFormatReaderExtensionPointName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderExtensionPointName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMEFormatReaderExtensionPointName"
        }
      ],
      "role": "symbol",
      "title": "kMEFormatReaderExtensionPointName",
      "type": "topic",
      "url": "/documentation/mediaextension/kmeformatreaderextensionpointname"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderFileNameExtensionArrayKey": {
      "abstract": [
        {
          "text": "A key to the array of file extensions that the format reader plug-in supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMEFormatReaderFileNameExtensionArrayKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderFileNameExtensionArrayKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMEFormatReaderFileNameExtensionArrayKey"
        }
      ],
      "role": "symbol",
      "title": "kMEFormatReaderFileNameExtensionArrayKey",
      "type": "topic",
      "url": "/documentation/mediaextension/kmeformatreaderfilenameextensionarraykey"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderObjectNameKey": {
      "abstract": [
        {
          "text": "A user-readable string describing the format reader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMEFormatReaderObjectNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderObjectNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMEFormatReaderObjectNameKey"
        }
      ],
      "role": "symbol",
      "title": "kMEFormatReaderObjectNameKey",
      "type": "topic",
      "url": "/documentation/mediaextension/kmeformatreaderobjectnamekey"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderUTTypeArrayKey": {
      "abstract": [
        {
          "text": "A key to the array of Uniform Type Identifiers that the format reader supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMEFormatReaderUTTypeArrayKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderUTTypeArrayKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMEFormatReaderUTTypeArrayKey"
        }
      ],
      "role": "symbol",
      "title": "kMEFormatReaderUTTypeArrayKey",
      "type": "topic",
      "url": "/documentation/mediaextension/kmeformatreaderuttypearraykey"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Property-list-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderExtensionPointName",
        "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderFileNameExtensionArrayKey",
        "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderUTTypeArrayKey",
        "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderObjectNameKey"
      ],
      "title": "Property list keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMEFormatReaderClassImplementationIDKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMEFormatReaderClassImplementationIDKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaextension/documentation/MediaExtension"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Property-list-keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderExtensionPointName",
                "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderFileNameExtensionArrayKey",
                "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderUTTypeArrayKey",
                "doc://com.apple.mediaextension/documentation/MediaExtension/kMEFormatReaderObjectNameKey"
              ],
              "title": "Property list keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kMEFormatReaderClassImplementationIDKey"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEFormatReaderFileNameExtensionArrayKey/title",
          "value": "kMEFormatReaderFileNameExtensionArrayKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEFormatReaderFileNameExtensionArrayKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMEFormatReaderFileNameExtensionArrayKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEFormatReaderObjectNameKey/title",
          "value": "kMEFormatReaderObjectNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEFormatReaderObjectNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMEFormatReaderObjectNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEFormatReaderUTTypeArrayKey/title",
          "value": "kMEFormatReaderUTTypeArrayKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEFormatReaderUTTypeArrayKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMEFormatReaderUTTypeArrayKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEFormatReaderExtensionPointName/title",
          "value": "kMEFormatReaderExtensionPointName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEFormatReaderExtensionPointName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMEFormatReaderExtensionPointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEFormatReaderClassImplementationIDKey/title",
          "value": "kMEFormatReaderClassImplementationIDKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEFormatReaderClassImplementationIDKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMEFormatReaderClassImplementationIDKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/kmeformatreaderclassimplementationidkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaextension/kmeformatreaderclassimplementationidkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
