{
  "abstract": [
    {
      "text": "The unique identifier for the video decoder.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderClassImplementationIDKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@kMEVideoDecoderClassImplementationIDKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kMEVideoDecoderClassImplementationIDKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMEVideoDecoderClassImplementationIDKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kMEVideoDecoderClassImplementationIDKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kMEVideoDecoderClassImplementationIDKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Format the string similar to the bundle identifier of the video decoder. Start with the reverse domain identifier of your developer account, followed by ",
              "type": "text"
            },
            {
              "code": ".videodecoder.",
              "type": "codeVoice"
            },
            {
              "text": " and the name of the codec. If you plan to create multiple variants of the same video decoder, include an additional component to make each video decoder identifier unique; for example ",
              "type": "text"
            },
            {
              "code": "com.mycompany.videodecoder.mycodec.codecvariant",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/kMERAWProcessorExtensionPointName": {
      "abstract": [
        {
          "text": "The extension point name for RAW processors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMERAWProcessorExtensionPointName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMERAWProcessorExtensionPointName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMERAWProcessorExtensionPointName"
        }
      ],
      "role": "symbol",
      "title": "kMERAWProcessorExtensionPointName",
      "type": "topic",
      "url": "/documentation/mediaextension/kmerawprocessorextensionpointname"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderClassImplementationIDKey": {
      "abstract": [
        {
          "text": "The unique identifier for the video decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderClassImplementationIDKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderClassImplementationIDKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderClassImplementationIDKey"
        }
      ],
      "role": "symbol",
      "title": "kMEVideoDecoderClassImplementationIDKey",
      "type": "topic",
      "url": "/documentation/mediaextension/kmevideodecoderclassimplementationidkey"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecInfoKey": {
      "abstract": [
        {
          "text": "An array of one or more dictionaries describing the codecs that the decoder supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderCodecInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderCodecInfoKey"
        }
      ],
      "role": "symbol",
      "title": "kMEVideoDecoderCodecInfoKey",
      "type": "topic",
      "url": "/documentation/mediaextension/kmevideodecodercodecinfokey"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecNameKey": {
      "abstract": [
        {
          "text": "A user-readable string describing the name of the codec format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderCodecNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderCodecNameKey"
        }
      ],
      "role": "symbol",
      "title": "kMEVideoDecoderCodecNameKey",
      "type": "topic",
      "url": "/documentation/mediaextension/kmevideodecodercodecnamekey"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecTypeKey": {
      "abstract": [
        {
          "text": "A string describing the four-character code of the codec that the decoder supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderCodecTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderCodecTypeKey"
        }
      ],
      "role": "symbol",
      "title": "kMEVideoDecoderCodecTypeKey",
      "type": "topic",
      "url": "/documentation/mediaextension/kmevideodecodercodectypekey"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderObjectNameKey": {
      "abstract": [
        {
          "text": "A user-readable string describing the decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderObjectNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderObjectNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderObjectNameKey"
        }
      ],
      "role": "symbol",
      "title": "kMEVideoDecoderObjectNameKey",
      "type": "topic",
      "url": "/documentation/mediaextension/kmevideodecoderobjectnamekey"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Property-list-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/kMERAWProcessorExtensionPointName",
        "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderObjectNameKey",
        "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecInfoKey",
        "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecTypeKey",
        "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecNameKey"
      ],
      "title": "Property list keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMEVideoDecoderClassImplementationIDKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMEVideoDecoderClassImplementationIDKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaextension/documentation/MediaExtension"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Property-list-keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/kMERAWProcessorExtensionPointName",
                "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderObjectNameKey",
                "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecInfoKey",
                "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecTypeKey",
                "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecNameKey"
              ],
              "title": "Property list keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kMEVideoDecoderClassImplementationIDKey"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderCodecTypeKey/title",
          "value": "kMEVideoDecoderCodecTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderCodecTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMEVideoDecoderCodecTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderClassImplementationIDKey/title",
          "value": "kMEVideoDecoderClassImplementationIDKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderClassImplementationIDKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMEVideoDecoderClassImplementationIDKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderCodecInfoKey/title",
          "value": "kMEVideoDecoderCodecInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderCodecInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMEVideoDecoderCodecInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderObjectNameKey/title",
          "value": "kMEVideoDecoderObjectNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderObjectNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMEVideoDecoderObjectNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderCodecNameKey/title",
          "value": "kMEVideoDecoderCodecNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderCodecNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMEVideoDecoderCodecNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMERAWProcessorExtensionPointName/title",
          "value": "kMERAWProcessorExtensionPointName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMERAWProcessorExtensionPointName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMERAWProcessorExtensionPointName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/kmevideodecoderclassimplementationidkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaextension/kmevideodecoderclassimplementationidkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
