{
  "abstract": [
    {
      "text": "An object that guides the video decoder operation on a per-frame basis.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MEDecodeFrameOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MEDecodeFrameOptions"
      }
    ],
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MEDecodeFrameOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MEDecodeFrameOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MEDecodeFrameOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameOptions": {
      "abstract": [
        {
          "text": "An object that guides the video decoder operation on a per-frame basis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEDecodeFrameOptions"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEDecodeFrameOptions"
        }
      ],
      "role": "symbol",
      "title": "MEDecodeFrameOptions",
      "type": "topic",
      "url": "/documentation/mediaextension/medecodeframeoptions"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameOptions/doNotOutputFrame": {
      "abstract": [
        {
          "text": "A Boolean value that hints to the decoder whether or not it should emit an image buffer for the frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doNotOutputFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameOptions/doNotOutputFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doNotOutputFrame"
        }
      ],
      "role": "symbol",
      "title": "doNotOutputFrame",
      "type": "topic",
      "url": "/documentation/mediaextension/medecodeframeoptions/donotoutputframe"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameOptions/realTimePlayback": {
      "abstract": [
        {
          "text": "A Boolean value that hints to the decoder to use a low-power mode that can’t decode faster than 1x real-time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "realTimePlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameOptions/realTimePlayback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "realTimePlayback"
        }
      ],
      "role": "symbol",
      "title": "realTimePlayback",
      "type": "topic",
      "url": "/documentation/mediaextension/medecodeframeoptions/realtimeplayback"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder": {
      "abstract": [
        {
          "text": "A protocol that defines the requirements for a video decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEVideoDecoder"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEVideoDecoder"
        }
      ],
      "role": "symbol",
      "title": "MEVideoDecoder",
      "type": "topic",
      "url": "/documentation/mediaextension/mevideodecoder"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoderExtension": {
      "abstract": [
        {
          "text": "A protocol that defines a factory to create new video decoders for a codec type that the extension implements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEVideoDecoderExtension"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoderExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEVideoDecoderExtension"
        }
      ],
      "role": "symbol",
      "title": "MEVideoDecoderExtension",
      "type": "topic",
      "url": "/documentation/mediaextension/mevideodecoderextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoderPixelBufferManager": {
      "abstract": [
        {
          "text": "Describes pixel buffer requirements and creates new pixel buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEVideoDecoderPixelBufferManager"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoderPixelBufferManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEVideoDecoderPixelBufferManager"
        }
      ],
      "role": "symbol",
      "title": "MEVideoDecoderPixelBufferManager",
      "type": "topic",
      "url": "/documentation/mediaextension/mevideodecoderpixelbuffermanager"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/video-decoder-entitlement": {
      "abstract": [
        {
          "text": "Include an entitlement to indicate your extension is a MediaExtension video decoder.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/video-decoder-entitlement",
      "kind": "article",
      "role": "article",
      "title": "Video decoder entitlement",
      "type": "topic",
      "url": "/documentation/mediaextension/video-decoder-entitlement"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/video-decoder-property-list-dictionary": {
      "abstract": [
        {
          "text": "Include a property list dictionary to describe a video decoder.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/video-decoder-property-list-dictionary",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Video decoder property list dictionary",
      "type": "topic",
      "url": "/documentation/mediaextension/video-decoder-property-list-dictionary"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Video-decoders",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoderExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoderPixelBufferManager",
        "doc://com.apple.mediaextension/documentation/MediaExtension/video-decoder-property-list-dictionary",
        "doc://com.apple.mediaextension/documentation/MediaExtension/video-decoder-entitlement"
      ],
      "title": "Video decoders"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-frame-decoding-options",
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameOptions/doNotOutputFrame",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameOptions/realTimePlayback"
      ],
      "title": "Inspecting frame decoding options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MEDecodeFrameOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEDecodeFrameOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEDecodeFrameOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaextension/documentation/MediaExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-frame-decoding-options",
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameOptions/doNotOutputFrame",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEDecodeFrameOptions/realTimePlayback"
              ],
              "title": "Inspecting frame decoding options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Video-decoders",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoder",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoderExtension",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEVideoDecoderPixelBufferManager",
                "doc://com.apple.mediaextension/documentation/MediaExtension/video-decoder-property-list-dictionary",
                "doc://com.apple.mediaextension/documentation/MediaExtension/video-decoder-entitlement"
              ],
              "title": "Video decoders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MEDecodeFrameOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEDecodeFrameOptions~1doNotOutputFrame/title",
          "value": "doNotOutputFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEDecodeFrameOptions~1doNotOutputFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "doNotOutputFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoderExtension/title",
          "value": "MEVideoDecoderExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoderExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEVideoDecoderExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoderExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEVideoDecoderExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEDecodeFrameOptions/title",
          "value": "MEDecodeFrameOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEDecodeFrameOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEDecodeFrameOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEDecodeFrameOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEDecodeFrameOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoderPixelBufferManager/title",
          "value": "MEVideoDecoderPixelBufferManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoderPixelBufferManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEVideoDecoderPixelBufferManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoderPixelBufferManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEVideoDecoderPixelBufferManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder/title",
          "value": "MEVideoDecoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEVideoDecoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEVideoDecoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEVideoDecoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEDecodeFrameOptions~1realTimePlayback/title",
          "value": "realTimePlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEDecodeFrameOptions~1realTimePlayback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "realTimePlayback"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/medecodeframeoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaextension/medecodeframeoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
