{
  "abstract": [
    {
      "text": "Informational status flags that the format reader returns after parsing additional fragments.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MEFormatReaderParseAdditionalFragmentsStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MEFormatReaderParseAdditionalFragmentsStatus"
      }
    ],
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MEFormatReaderParseAdditionalFragmentsStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MEFormatReaderParseAdditionalFragmentsStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MEFormatReaderParseAdditionalFragmentsStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader/loadFileInfo(completionHandler:)": {
      "abstract": [
        {
          "text": "Loads the file info object with the properties of the media asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadFileInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MEFileInfo",
          "text": "MEFileInfo"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader/loadFileInfo(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadFileInfoWithCompletionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "loadFileInfo(completionHandler:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreader/loadfileinfo(completionhandler:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader/loadMetadata(completionHandler:)": {
      "abstract": [
        {
          "text": "Loads the array of metadata items from the media asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadMetadata"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataItem",
          "text": "AVMetadataItem"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader/loadMetadata(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadMetadataWithCompletionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "loadMetadata(completionHandler:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreader/loadmetadata(completionhandler:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader/loadTrackReaders(completionHandler:)": {
      "abstract": [
        {
          "text": "Loads the array of track readers that represent the tracks in the media asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadTrackReaders"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ([any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)METrackReader",
          "text": "METrackReader"
        },
        {
          "kind": "text",
          "text": "]?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader/loadTrackReaders(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadTrackReadersWithCompletionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "loadTrackReaders(completionHandler:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreader/loadtrackreaders(completionhandler:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader/parseAdditionalFragments(completionHandler:)": {
      "abstract": [
        {
          "text": "Incorporates additional fragments that the file received after the last time the format reader parsed it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parseAdditionalFragments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MEFormatReaderParseAdditionalFragmentsStatus",
          "text": "MEFormatReaderParseAdditionalFragmentsStatus"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader/parseAdditionalFragments(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parseAdditionalFragmentsWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "parseAdditionalFragments(completionHandler:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreader/parseadditionalfragments(completionhandler:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus": {
      "abstract": [
        {
          "text": "Informational status flags that the format reader returns after parsing additional fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEFormatReaderParseAdditionalFragmentsStatus"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFormatReaderParseAdditionalFragmentsStatus"
        }
      ],
      "role": "symbol",
      "title": "MEFormatReaderParseAdditionalFragmentsStatus",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/equatable-implementations"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/OptionSet-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/OptionSet-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OptionSet Implementations",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/optionset-implementations"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/SetAlgebra-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/SetAlgebra-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SetAlgebra Implementations",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/setalgebra-implementations"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/fragmentAdded": {
      "abstract": [
        {
          "text": "Indicates that the format reader received one or more fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fragmentAdded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MEFormatReaderParseAdditionalFragmentsStatus",
          "text": "MEFormatReaderParseAdditionalFragmentsStatus"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/fragmentAdded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFormatReaderParseAdditionalFragmentsStatusFragmentAdded"
        }
      ],
      "role": "symbol",
      "title": "fragmentAdded",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/fragmentadded"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/fragmentsComplete": {
      "abstract": [
        {
          "text": "Indicates that the format reader can’t receive any more fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fragmentsComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MEFormatReaderParseAdditionalFragmentsStatus",
          "text": "MEFormatReaderParseAdditionalFragmentsStatus"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/fragmentsComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFormatReaderParseAdditionalFragmentsStatusFragmentsComplete"
        }
      ],
      "role": "symbol",
      "title": "fragmentsComplete",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/fragmentscomplete"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/init(rawValue:)": {
      "abstract": [
        {
          "text": "Create a new information status flag for parsing additional fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/init(rawvalue:)"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/sizeIncreased": {
      "abstract": [
        {
          "text": "Indicates that the format reader file size increased.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sizeIncreased"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MEFormatReaderParseAdditionalFragmentsStatus",
          "text": "MEFormatReaderParseAdditionalFragmentsStatus"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/sizeIncreased",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEFormatReaderParseAdditionalFragmentsStatusSizeIncreased"
        }
      ],
      "role": "symbol",
      "title": "sizeIncreased",
      "type": "topic",
      "url": "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus/sizeincreased"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reading-and-parsing-media-assets",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader/loadFileInfo(completionHandler:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader/loadMetadata(completionHandler:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader/loadTrackReaders(completionHandler:)",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader/parseAdditionalFragments(completionHandler:)"
      ],
      "title": "Reading and parsing media assets"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-informational-status-flags",
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/init(rawValue:)"
      ],
      "title": "Creating informational status flags"
    },
    {
      "anchor": "Evaluating-a-fragment-parsing-operation",
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/sizeIncreased",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/fragmentAdded",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/fragmentsComplete"
      ],
      "title": "Evaluating a fragment parsing operation"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/Equatable-Implementations",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/OptionSet-Implementations",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/SetAlgebra-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MEFormatReaderParseAdditionalFragmentsStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReaderParseAdditionalFragmentsStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReaderParseAdditionalFragmentsStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaextension/documentation/MediaExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Evaluating-a-fragment-parsing-operation",
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/sizeIncreased",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/fragmentAdded",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReaderParseAdditionalFragmentsStatus/fragmentsComplete"
              ],
              "title": "Evaluating a fragment parsing operation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reading-and-parsing-media-assets",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader/loadFileInfo(completionHandler:)",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader/loadMetadata(completionHandler:)",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader/loadTrackReaders(completionHandler:)",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEFormatReader/parseAdditionalFragments(completionHandler:)"
              ],
              "title": "Reading and parsing media assets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MEFormatReaderParseAdditionalFragmentsStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderParseAdditionalFragmentsStatus~1sizeIncreased/title",
          "value": "MEFormatReaderParseAdditionalFragmentsStatusSizeIncreased"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderParseAdditionalFragmentsStatus~1sizeIncreased/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReaderParseAdditionalFragmentsStatusSizeIncreased"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReader~1loadTrackReaders(completionHandler:)/title",
          "value": "loadTrackReadersWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReader~1loadTrackReaders(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadTrackReadersWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderParseAdditionalFragmentsStatus/title",
          "value": "MEFormatReaderParseAdditionalFragmentsStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderParseAdditionalFragmentsStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReaderParseAdditionalFragmentsStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderParseAdditionalFragmentsStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReaderParseAdditionalFragmentsStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReader~1loadMetadata(completionHandler:)/title",
          "value": "loadMetadataWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReader~1loadMetadata(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadMetadataWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReader~1parseAdditionalFragments(completionHandler:)/title",
          "value": "parseAdditionalFragmentsWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReader~1parseAdditionalFragments(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "parseAdditionalFragmentsWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderParseAdditionalFragmentsStatus~1fragmentsComplete/title",
          "value": "MEFormatReaderParseAdditionalFragmentsStatusFragmentsComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderParseAdditionalFragmentsStatus~1fragmentsComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReaderParseAdditionalFragmentsStatusFragmentsComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReader~1loadFileInfo(completionHandler:)/title",
          "value": "loadFileInfoWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReader~1loadFileInfo(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadFileInfoWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderParseAdditionalFragmentsStatus~1fragmentAdded/title",
          "value": "MEFormatReaderParseAdditionalFragmentsStatusFragmentAdded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEFormatReaderParseAdditionalFragmentsStatus~1fragmentAdded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEFormatReaderParseAdditionalFragmentsStatusFragmentAdded"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaextension/meformatreaderparseadditionalfragmentsstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
