{
  "abstract": [
    {
      "text": "An object that provides information about the HEVC dependency attributes of a sample.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MEHEVCDependencyInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MEHEVCDependencyInfo"
      }
    ],
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MEHEVCDependencyInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "MEHEVCDependencyInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MEHEVCDependencyInfo"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEEstimatedSampleLocation": {
      "abstract": [
        {
          "text": "An object that provides information about the estimated sample location with the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEEstimatedSampleLocation"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEEstimatedSampleLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEEstimatedSampleLocation"
        }
      ],
      "role": "symbol",
      "title": "MEEstimatedSampleLocation",
      "type": "topic",
      "url": "/documentation/mediaextension/meestimatedsamplelocation"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo": {
      "abstract": [
        {
          "text": "An object that provides information about the HEVC dependency attributes of a sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MEHEVCDependencyInfo"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MEHEVCDependencyInfo"
        }
      ],
      "role": "symbol",
      "title": "MEHEVCDependencyInfo",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/constraintIndicatorFlags": {
      "abstract": [
        {
          "text": "The HEVC constraint indicator flags (6 bytes), if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constraintIndicatorFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/constraintIndicatorFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "constraintIndicatorFlags"
        }
      ],
      "role": "symbol",
      "title": "constraintIndicatorFlags",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/constraintindicatorflags"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/hasStepwiseTemporalSubLayerAccess": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if the sample has an HEVC stepwise temporal sublayer access (STSA) picture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasStepwiseTemporalSubLayerAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/hasStepwiseTemporalSubLayerAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stepwiseTemporalSubLayerAccess"
        }
      ],
      "role": "symbol",
      "title": "hasStepwiseTemporalSubLayerAccess",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/hasstepwisetemporalsublayeraccess"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/hasTemporalSubLayerAccess": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if the sample has an HEVC temporal sublayer access (TSA) picture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasTemporalSubLayerAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/hasTemporalSubLayerAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "temporalSubLayerAccess"
        }
      ],
      "role": "symbol",
      "title": "hasTemporalSubLayerAccess",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/hastemporalsublayeraccess"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/levelIndex": {
      "abstract": [
        {
          "text": "The HEVC level index, if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "levelIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/levelIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "levelIndex"
        }
      ],
      "role": "symbol",
      "title": "levelIndex",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/levelindex"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileCompatibilityFlags": {
      "abstract": [
        {
          "text": "The HEVC profile compatibility flags (4 bytes), if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "profileCompatibilityFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileCompatibilityFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "profileCompatibilityFlags"
        }
      ],
      "role": "symbol",
      "title": "profileCompatibilityFlags",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/profilecompatibilityflags"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileIndex": {
      "abstract": [
        {
          "text": "The HEVC profile index, if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "profileIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "profileIndex"
        }
      ],
      "role": "symbol",
      "title": "profileIndex",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/profileindex"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileSpace": {
      "abstract": [
        {
          "text": "The HEVC profile space, if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "profileSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "profileSpace"
        }
      ],
      "role": "symbol",
      "title": "profileSpace",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/profilespace"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/syncSampleNALUnitType": {
      "abstract": [
        {
          "text": "The NAL unit type for HEVC sync sample groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "syncSampleNALUnitType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/syncSampleNALUnitType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "syncSampleNALUnitType"
        }
      ],
      "role": "symbol",
      "title": "syncSampleNALUnitType",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/syncsamplenalunittype"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/temporalLevel": {
      "abstract": [
        {
          "text": "The HEVC temporal level, if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "temporalLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/temporalLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "temporalLevel"
        }
      ],
      "role": "symbol",
      "title": "temporalLevel",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/temporallevel"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/tierFlag": {
      "abstract": [
        {
          "text": "The HEVC tier level flag, if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tierFlag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/tierFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tierFlag"
        }
      ],
      "role": "symbol",
      "title": "tierFlag",
      "type": "topic",
      "url": "/documentation/mediaextension/mehevcdependencyinfo/tierflag"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor": {
      "abstract": [
        {
          "text": "A protocol that defines the information to provide about samples within a track of a media asset, and enables stepping through samples in the track in decode or presentation order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MESampleCursor"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MESampleCursor"
        }
      ],
      "role": "symbol",
      "title": "MESampleCursor",
      "type": "topic",
      "url": "/documentation/mediaextension/mesamplecursor"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursorChunk": {
      "abstract": [
        {
          "text": "An object that provides information about the chunk of media at the location of a sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MESampleCursorChunk"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursorChunk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MESampleCursorChunk"
        }
      ],
      "role": "symbol",
      "title": "MESampleCursorChunk",
      "type": "topic",
      "url": "/documentation/mediaextension/mesamplecursorchunk"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleLocation": {
      "abstract": [
        {
          "text": "An object that provides information about the sample location with the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MESampleLocation"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MESampleLocation"
        }
      ],
      "role": "symbol",
      "title": "MESampleLocation",
      "type": "topic",
      "url": "/documentation/mediaextension/mesamplelocation"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sample-cursors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleLocation",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursorChunk",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEEstimatedSampleLocation"
      ],
      "title": "Sample cursors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-the-HEVC-dependency-attributes-of-a-sample",
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/hasTemporalSubLayerAccess",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/hasStepwiseTemporalSubLayerAccess",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/syncSampleNALUnitType",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/temporalLevel",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileSpace",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/tierFlag",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileIndex",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileCompatibilityFlags",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/constraintIndicatorFlags",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/levelIndex"
      ],
      "title": "Inspecting the HEVC dependency attributes of a sample"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MEHEVCDependencyInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEHEVCDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEHEVCDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaextension/documentation/MediaExtension"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-the-HEVC-dependency-attributes-of-a-sample",
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/hasTemporalSubLayerAccess",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/hasStepwiseTemporalSubLayerAccess",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/syncSampleNALUnitType",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/temporalLevel",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileSpace",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/tierFlag",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileIndex",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/profileCompatibilityFlags",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/constraintIndicatorFlags",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEHEVCDependencyInfo/levelIndex"
              ],
              "title": "Inspecting the HEVC dependency attributes of a sample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sample-cursors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursor",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleLocation",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MESampleCursorChunk",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MEEstimatedSampleLocation"
              ],
              "title": "Sample cursors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MEHEVCDependencyInfo"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1tierFlag/title",
          "value": "tierFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1tierFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tierFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleLocation/title",
          "value": "MESampleLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MESampleLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MESampleLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEEstimatedSampleLocation/title",
          "value": "MEEstimatedSampleLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEEstimatedSampleLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEEstimatedSampleLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEEstimatedSampleLocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEEstimatedSampleLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1levelIndex/title",
          "value": "levelIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1levelIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "levelIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursorChunk/title",
          "value": "MESampleCursorChunk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursorChunk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MESampleCursorChunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursorChunk/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MESampleCursorChunk"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor/title",
          "value": "MESampleCursor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MESampleCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MESampleCursor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MESampleCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1hasStepwiseTemporalSubLayerAccess/title",
          "value": "stepwiseTemporalSubLayerAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1hasStepwiseTemporalSubLayerAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stepwiseTemporalSubLayerAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1syncSampleNALUnitType/title",
          "value": "syncSampleNALUnitType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1syncSampleNALUnitType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "syncSampleNALUnitType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1hasTemporalSubLayerAccess/title",
          "value": "temporalSubLayerAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1hasTemporalSubLayerAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "temporalSubLayerAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1constraintIndicatorFlags/title",
          "value": "constraintIndicatorFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1constraintIndicatorFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "constraintIndicatorFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1profileSpace/title",
          "value": "profileSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1profileSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "profileSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1profileIndex/title",
          "value": "profileIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1profileIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "profileIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1temporalLevel/title",
          "value": "temporalLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1temporalLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "temporalLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1profileCompatibilityFlags/title",
          "value": "profileCompatibilityFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo~1profileCompatibilityFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "profileCompatibilityFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo/title",
          "value": "MEHEVCDependencyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MEHEVCDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MEHEVCDependencyInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MEHEVCDependencyInfo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/mehevcdependencyinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaextension/mehevcdependencyinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
