{
  "abstract": [
    {
      "text": "Include a property list dictionary to describe a RAW processor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaextension/documentation/MediaExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaextension/documentation/MediaExtension/raw-processor-property-list-dictionary"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "MediaExtension"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "RAW processor property list dictionary"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A MediaExtension RAW processor needs to include an ",
              "type": "text"
            },
            {
              "code": "EXAppExtensionAttributes",
              "type": "codeVoice"
            },
            {
              "text": " dictionary in its ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file that contains the following keys and values:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderClassImplementationIDKey",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ": The identifier for the RAW processor. Format similarly to the bundle identifier. The key is the same as for video decoders.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "EXExtensionPointIdentifier",
                      "type": "codeVoice"
                    },
                    {
                      "text": ": The extension point name for RAW processors. Set to the value for ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMERAWProcessorExtensionPointName",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "EXPrincipalClass",
                      "type": "codeVoice"
                    },
                    {
                      "text": ": The name of the RAW processor factory class that conforms to the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessorExtension",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " protocol.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderObjectNameKey",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ": A user-readable string that describes RAW processor. This string is used for uniquely identifying RAW processors and possibly for debug logging but is typically not visible to users. The key is the same as for video decoders.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecInfoKey",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ": An array of one or more dictionaries describing the formats that the RAW processor supports. The key is the same as for video decoders. Each dictionary must include the following keys:",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                },
                {
                  "items": [
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecTypeKey",
                              "isActive": true,
                              "type": "reference"
                            },
                            {
                              "text": ": A string describing the four-character code of the codec associated with the video decoder. Each string should be exactly four characters long and use ASCII character set encoding. The key is the same as for video decoders.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    },
                    {
                      "content": [
                        {
                          "inlineContent": [
                            {
                              "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecNameKey",
                              "isActive": true,
                              "type": "reference"
                            },
                            {
                              "text": ": A user-readable string describing the name of the codec format. This string might be displayed as format information for the video track in a player application. The key is the same as for video decoders.",
                              "type": "text"
                            }
                          ],
                          "type": "paragraph"
                        }
                      ]
                    }
                  ],
                  "type": "unorderedList"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension": {
      "abstract": [
        {
          "text": "This framework provides a means for developers to create format readers, video decoders, and RAW processors for media that the system doesn’t natively support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "MediaExtension",
      "type": "topic",
      "url": "/documentation/mediaextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingParameter": {
      "abstract": [
        {
          "text": "An object for the RAW processor to describe each processing parameter the processor exposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MERAWProcessingParameter"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MERAWProcessingParameter"
        }
      ],
      "role": "symbol",
      "title": "MERAWProcessingParameter",
      "type": "topic",
      "url": "/documentation/mediaextension/merawprocessingparameter"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessor": {
      "abstract": [
        {
          "text": "A protocol that defines the requirements for a RAW processor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MERAWProcessor"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MERAWProcessor"
        }
      ],
      "role": "symbol",
      "title": "MERAWProcessor",
      "type": "topic",
      "url": "/documentation/mediaextension/merawprocessor"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessorExtension": {
      "abstract": [
        {
          "text": "A protocol that defines a factory to create RAW processors for a codec type that the extension implements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MERAWProcessorExtension"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessorExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MERAWProcessorExtension"
        }
      ],
      "role": "symbol",
      "title": "MERAWProcessorExtension",
      "type": "topic",
      "url": "/documentation/mediaextension/merawprocessorextension"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessorNotification": {
      "abstract": [
        {
          "text": "Notifications that indicate a RAW processor state change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MERAWProcessorNotification"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessorNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MERAWProcessorNotification"
        }
      ],
      "role": "symbol",
      "title": "MERAWProcessorNotification",
      "type": "topic",
      "url": "/documentation/mediaextension/merawprocessornotification"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessorPixelBufferManager": {
      "abstract": [
        {
          "text": "Describes pixel buffer requirements and creates new pixel buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MERAWProcessorPixelBufferManager"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessorPixelBufferManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MERAWProcessorPixelBufferManager"
        }
      ],
      "role": "symbol",
      "title": "MERAWProcessorPixelBufferManager",
      "type": "topic",
      "url": "/documentation/mediaextension/merawprocessorpixelbuffermanager"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/kMERAWProcessorExtensionPointName": {
      "abstract": [
        {
          "text": "The extension point name for RAW processors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMERAWProcessorExtensionPointName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMERAWProcessorExtensionPointName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMERAWProcessorExtensionPointName"
        }
      ],
      "role": "symbol",
      "title": "kMERAWProcessorExtensionPointName",
      "type": "topic",
      "url": "/documentation/mediaextension/kmerawprocessorextensionpointname"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderClassImplementationIDKey": {
      "abstract": [
        {
          "text": "The unique identifier for the video decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderClassImplementationIDKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderClassImplementationIDKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderClassImplementationIDKey"
        }
      ],
      "role": "symbol",
      "title": "kMEVideoDecoderClassImplementationIDKey",
      "type": "topic",
      "url": "/documentation/mediaextension/kmevideodecoderclassimplementationidkey"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecInfoKey": {
      "abstract": [
        {
          "text": "An array of one or more dictionaries describing the codecs that the decoder supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderCodecInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderCodecInfoKey"
        }
      ],
      "role": "symbol",
      "title": "kMEVideoDecoderCodecInfoKey",
      "type": "topic",
      "url": "/documentation/mediaextension/kmevideodecodercodecinfokey"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecNameKey": {
      "abstract": [
        {
          "text": "A user-readable string describing the name of the codec format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderCodecNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderCodecNameKey"
        }
      ],
      "role": "symbol",
      "title": "kMEVideoDecoderCodecNameKey",
      "type": "topic",
      "url": "/documentation/mediaextension/kmevideodecodercodecnamekey"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecTypeKey": {
      "abstract": [
        {
          "text": "A string describing the four-character code of the codec that the decoder supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderCodecTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderCodecTypeKey"
        }
      ],
      "role": "symbol",
      "title": "kMEVideoDecoderCodecTypeKey",
      "type": "topic",
      "url": "/documentation/mediaextension/kmevideodecodercodectypekey"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderObjectNameKey": {
      "abstract": [
        {
          "text": "A user-readable string describing the decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderObjectNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderObjectNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMEVideoDecoderObjectNameKey"
        }
      ],
      "role": "symbol",
      "title": "kMEVideoDecoderObjectNameKey",
      "type": "topic",
      "url": "/documentation/mediaextension/kmevideodecoderobjectnamekey"
    },
    "doc://com.apple.mediaextension/documentation/MediaExtension/raw-processor-entitlement": {
      "abstract": [
        {
          "text": "Include an entitlement to indicate your extension is a MediaExtension RAW processor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaextension/documentation/MediaExtension/raw-processor-entitlement",
      "kind": "article",
      "role": "article",
      "title": "RAW processor entitlement",
      "type": "topic",
      "url": "/documentation/mediaextension/raw-processor-entitlement"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "RAW-processors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessor",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessorExtension",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessorPixelBufferManager",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingParameter",
        "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessorNotification",
        "doc://com.apple.mediaextension/documentation/MediaExtension/raw-processor-entitlement"
      ],
      "title": "RAW processors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Property-list-keys",
      "identifiers": [
        "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderClassImplementationIDKey",
        "doc://com.apple.mediaextension/documentation/MediaExtension/kMERAWProcessorExtensionPointName",
        "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderObjectNameKey",
        "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecInfoKey",
        "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecTypeKey",
        "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecNameKey"
      ],
      "title": "Property list keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Property-list-keys",
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderClassImplementationIDKey",
                "doc://com.apple.mediaextension/documentation/MediaExtension/kMERAWProcessorExtensionPointName",
                "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderObjectNameKey",
                "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecInfoKey",
                "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecTypeKey",
                "doc://com.apple.mediaextension/documentation/MediaExtension/kMEVideoDecoderCodecNameKey"
              ],
              "title": "Property list keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "RAW-processors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessor",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessorExtension",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessorPixelBufferManager",
                "doc://com.apple.mediaextension/documentation/MediaExtension/MERAWProcessingParameter",
                "doc://com.apple.mediaextension/documentation/MediaExtension/raw-processor-entitlement"
              ],
              "title": "RAW processors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MERAWProcessorPixelBufferManager/title",
          "value": "MERAWProcessorPixelBufferManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MERAWProcessorPixelBufferManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MERAWProcessorPixelBufferManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MERAWProcessorPixelBufferManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MERAWProcessorPixelBufferManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderClassImplementationIDKey/title",
          "value": "kMEVideoDecoderClassImplementationIDKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderClassImplementationIDKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMEVideoDecoderClassImplementationIDKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderCodecInfoKey/title",
          "value": "kMEVideoDecoderCodecInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderCodecInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMEVideoDecoderCodecInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MERAWProcessorExtension/title",
          "value": "MERAWProcessorExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MERAWProcessorExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MERAWProcessorExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MERAWProcessorExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MERAWProcessorExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MERAWProcessor/title",
          "value": "MERAWProcessor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MERAWProcessor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MERAWProcessor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MERAWProcessor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MERAWProcessor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MERAWProcessingParameter/title",
          "value": "MERAWProcessingParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MERAWProcessingParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MERAWProcessingParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1MERAWProcessingParameter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MERAWProcessingParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMERAWProcessorExtensionPointName/title",
          "value": "kMERAWProcessorExtensionPointName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMERAWProcessorExtensionPointName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMERAWProcessorExtensionPointName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderCodecNameKey/title",
          "value": "kMEVideoDecoderCodecNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderCodecNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMEVideoDecoderCodecNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderCodecTypeKey/title",
          "value": "kMEVideoDecoderCodecTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderCodecTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMEVideoDecoderCodecTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderObjectNameKey/title",
          "value": "kMEVideoDecoderObjectNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaextension~1documentation~1MediaExtension~1kMEVideoDecoderObjectNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMEVideoDecoderObjectNameKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaextension/raw-processor-property-list-dictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaextension/raw-processor-property-list-dictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
