{
  "abstract": [
    {
      "text": "An ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWEndpoint",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " object containing information about the local endpoint of the flow.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyUDPFlow"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyUDPFlow/localEndpoint"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NEAppProxyUDPFlow(py)localEndpoint",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "localEndpoint"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NWEndpoint",
        "text": "NWEndpoint"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "localEndpoint"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "localEndpoint"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "localEndpoint"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWEndpoint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NWEndpoint",
              "text": "NWEndpoint"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property may be nil if the corresponding UDP socket was not bound to a port by the application and the App Proxy Provider did not set a local endpoint in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlow/open(withLocalEndpoint:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlow/open(withLocalEndpoint:completionHandler:)": {
      "abstract": [
        {
          "text": "Opens the flow, indicating to the system that the caller is ready to start receiving and sending data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "open"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withLocalEndpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NWHostEndpoint",
          "text": "NWHostEndpoint"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyFlow/open(withLocalEndpoint:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openWithLocalEndpoint:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "open(withLocalEndpoint:completionHandler:)",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyflow/open(withlocalendpoint:completionhandler:)"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyUDPFlow": {
      "abstract": [
        {
          "text": "An object for reading and writing data to and from a UDP conversation being proxied by the provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEAppProxyUDPFlow"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyUDPFlow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppProxyUDPFlow"
        }
      ],
      "role": "symbol",
      "title": "NEAppProxyUDPFlow",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyudpflow"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyUDPFlow/localEndpoint": {
      "abstract": [
        {
          "text": "An ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWEndpoint",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " object containing information about the local endpoint of the flow.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localEndpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NWEndpoint",
          "text": "NWEndpoint"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyUDPFlow/localEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localEndpoint"
        }
      ],
      "role": "symbol",
      "title": "localEndpoint",
      "type": "topic",
      "url": "/documentation/networkextension/neappproxyudpflow/localendpoint"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWBonjourServiceEndpoint": {
      "abstract": [
        {
          "text": "A network endpoint specified as a Bonjour service name, type, and domain.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWBonjourServiceEndpoint"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWBonjourServiceEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWBonjourServiceEndpoint"
        }
      ],
      "role": "symbol",
      "title": "NWBonjourServiceEndpoint",
      "type": "topic",
      "url": "/documentation/networkextension/nwbonjourserviceendpoint"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWEndpoint": {
      "abstract": [
        {
          "text": "An abstract base class, shared by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWHostEndpoint",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWBonjourServiceEndpoint",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", that represents the source or destination of a network connection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWEndpoint"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWEndpoint"
        }
      ],
      "role": "symbol",
      "title": "NWEndpoint",
      "type": "topic",
      "url": "/documentation/networkextension/nwendpoint"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NWHostEndpoint": {
      "abstract": [
        {
          "text": "A network endpoint specified by DNS name (or IP address) and port.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWHostEndpoint"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWHostEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NWHostEndpoint"
        }
      ],
      "role": "symbol",
      "title": "NWHostEndpoint",
      "type": "topic",
      "url": "/documentation/networkextension/nwhostendpoint"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "localEndpoint"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppProxyUDPFlow"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NWEndpoint",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NWEndpoint",
                    "text": "NWEndpoint"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "localEndpoint"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWHostEndpoint/title",
          "value": "NWHostEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWHostEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWHostEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWHostEndpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NWHostEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyUDPFlow/title",
          "value": "NEAppProxyUDPFlow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyUDPFlow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyUDPFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyUDPFlow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppProxyUDPFlow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWEndpoint/title",
          "value": "NWEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWEndpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NWEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyUDPFlow~1localEndpoint/title",
          "value": "localEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyUDPFlow~1localEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWBonjourServiceEndpoint/title",
          "value": "NWBonjourServiceEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWBonjourServiceEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NWBonjourServiceEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NWBonjourServiceEndpoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NWBonjourServiceEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlow~1open(withLocalEndpoint:completionHandler:)/title",
          "value": "openWithLocalEndpoint:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppProxyFlow~1open(withLocalEndpoint:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openWithLocalEndpoint:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/neappproxyudpflow/localendpoint"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/neappproxyudpflow/localendpoint"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
