{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/appkit/nsscrubberlayout/shouldinvalidatelayoutforhighlightchange"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsscrubberlayout/shouldinvalidatelayoutforhighlightchange"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"shouldInvalidateLayoutForHighlightChange"}],"platforms":[{"beta":false,"name":"macOS","deprecated":false,"introducedAt":"10.12.2","unavailable":false}],"role":"symbol","modules":[{"name":"AppKit"}],"title":"shouldInvalidateLayoutForHighlightChange","externalID":"c:objc(cs)NSScrubberLayout(py)shouldInvalidateLayoutForHighlightChange","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldInvalidateLayoutForHighlightChange"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"roleHeading":"Instance Property"},"kind":"symbol","sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/prepare()","doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/scrubberContentSize","doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesForItem(at:)","doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesForItems(in:)","doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForSelectionChange","doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForChange(fromVisibleRect:toVisibleRect:)","doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/automaticallyMirrorsInRightToLeftLayout"],"title":"Subclassing a scrubber layout","anchor":"Subclassing-a-scrubber-layout","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shouldInvalidateLayoutForHighlightChange"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["macOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"Discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"If "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true"},{"type":"text","text":", the scrubber invalidates its layout when an item is highlighted. Subclasses should return "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true"},{"type":"text","text":" if the highlight state affects the item layout."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The base implementation of this method returns "},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForHighlightChange"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout"]]},"abstract":[{"type":"text","text":"Determines whether the scrubber should refresh its layout when an item is highlighted."}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/automaticallyMirrorsInRightToLeftLayout":{"role":"symbol","title":"automaticallyMirrorsInRightToLeftLayout","abstract":[{"text":"Determines whether the scrubber mirrors its layout for right-to-left layouts.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"automaticallyMirrorsInRightToLeftLayout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/automaticallyMirrorsInRightToLeftLayout","kind":"symbol","type":"topic","url":"/documentation/appkit/nsscrubberlayout/automaticallymirrorsinrighttoleftlayout","navigatorTitle":[{"text":"automaticallyMirrorsInRightToLeftLayout","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesForItems(in:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesForItems(in:)","url":"/documentation/appkit/nsscrubberlayout/layoutattributesforitems(in:)","navigatorTitle":[{"text":"layoutAttributesForItemsInRect:","kind":"identifier"}],"abstract":[{"text":"The set of layout attributes for all items within the provided rectangle.","type":"text"}],"role":"symbol","title":"layoutAttributesForItems(in:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"layoutAttributesForItems","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"text":"NSRect","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect"},{"text":") -> ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"NSScrubberLayoutAttributes","preciseIdentifier":"c:objc(cs)NSScrubberLayoutAttributes","kind":"typeIdentifier"},{"text":">","kind":"text"}],"type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/scrubberContentSize":{"role":"symbol","title":"scrubberContentSize","abstract":[{"text":"The size required to contain all elements within the scrubber.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"scrubberContentSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSSize","preciseIdentifier":"c:@T@NSSize","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/scrubberContentSize","kind":"symbol","type":"topic","url":"/documentation/appkit/nsscrubberlayout/scrubbercontentsize","navigatorTitle":[{"text":"scrubberContentSize","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForChange(fromVisibleRect:toVisibleRect:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForChange(fromVisibleRect:toVisibleRect:)","title":"shouldInvalidateLayoutForChange(fromVisibleRect:toVisibleRect:)","navigatorTitle":[{"text":"shouldInvalidateLayoutForChangeFromVisibleRect:toVisibleRect:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldInvalidateLayoutForChange","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromVisibleRect"},{"kind":"text","text":": "},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"toVisibleRect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Determines whether the scrubber should refresh its layout in response to a change of its visible region."}],"url":"/documentation/appkit/nsscrubberlayout/shouldinvalidatelayoutforchange(fromvisiblerect:tovisiblerect:)"},"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSScrubberLayout","kind":"identifier"}],"title":"NSScrubberLayout","url":"/documentation/appkit/nsscrubberlayout","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout","type":"topic","abstract":[{"text":"An abstract class that describes the layout of items within a scrubber control.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"NSScrubberLayout","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForSelectionChange":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForSelectionChange","navigatorTitle":[{"text":"shouldInvalidateLayoutForSelectionChange","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nsscrubberlayout/shouldinvalidatelayoutforselectionchange","abstract":[{"text":"Determines whether the scrubber should refresh its layout when the selection changes.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shouldInvalidateLayoutForSelectionChange","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"shouldInvalidateLayoutForSelectionChange","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesForItem(at:)":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesForItem(at:)","navigatorTitle":[{"text":"layoutAttributesForItemAtIndex:","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nsscrubberlayout/layoutattributesforitem(at:)","abstract":[{"text":"The layout attributes for the item with the specified index.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layoutAttributesForItem"},{"kind":"text","text":"("},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"NSScrubberLayoutAttributes","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSScrubberLayoutAttributes"},{"text":"?","kind":"text"}],"title":"layoutAttributesForItem(at:)","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForHighlightChange":{"role":"symbol","title":"shouldInvalidateLayoutForHighlightChange","abstract":[{"text":"Determines whether the scrubber should refresh its layout when an item is highlighted.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shouldInvalidateLayoutForHighlightChange","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForHighlightChange","kind":"symbol","type":"topic","url":"/documentation/appkit/nsscrubberlayout/shouldinvalidatelayoutforhighlightchange","navigatorTitle":[{"text":"shouldInvalidateLayoutForHighlightChange","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/prepare()":{"url":"/documentation/appkit/nsscrubberlayout/prepare()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/prepare()","title":"prepare()","kind":"symbol","abstract":[{"type":"text","text":"Gives you an opportunity to perform layout calculations when the scrubber’s layout is invalidated."}],"navigatorTitle":[{"text":"prepareLayout","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"prepare","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"introducedAt":"10.12.2","name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"shouldInvalidateLayoutForHighlightChange","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"shouldInvalidateLayoutForHighlightChange"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Subclassing a scrubber layout","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/prepare()","doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/scrubberContentSize","doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesForItem(at:)","doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/layoutAttributesForItems(in:)","doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForSelectionChange","doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/shouldInvalidateLayoutForChange(fromVisibleRect:toVisibleRect:)","doc://com.apple.appkit/documentation/AppKit/NSScrubberLayout/automaticallyMirrorsInRightToLeftLayout"],"anchor":"Subclassing-a-scrubber-layout","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldInvalidateLayoutForHighlightChange"},{"kind":"text","text":";"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"automaticallyMirrorsInRightToLeftLayout","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1automaticallyMirrorsInRightToLeftLayout/title"},{"value":[{"text":"automaticallyMirrorsInRightToLeftLayout","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1automaticallyMirrorsInRightToLeftLayout/fragments"},{"value":"layoutAttributesForItemsInRect:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1layoutAttributesForItems(in:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"layoutAttributesForItemsInRect:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1layoutAttributesForItems(in:)/fragments"},{"value":"scrubberContentSize","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1scrubberContentSize/title"},{"value":[{"text":"scrubberContentSize","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1scrubberContentSize/fragments"},{"value":"shouldInvalidateLayoutForChangeFromVisibleRect:toVisibleRect:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1shouldInvalidateLayoutForChange(fromVisibleRect:toVisibleRect:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shouldInvalidateLayoutForChangeFromVisibleRect:toVisibleRect:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1shouldInvalidateLayoutForChange(fromVisibleRect:toVisibleRect:)/fragments"},{"value":"NSScrubberLayout","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout/title"},{"value":[{"text":"NSScrubberLayout","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout/fragments"},{"value":[{"text":"NSScrubberLayout","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout/navigatorTitle"},{"value":"shouldInvalidateLayoutForSelectionChange","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1shouldInvalidateLayoutForSelectionChange/title"},{"op":"replace","value":[{"kind":"identifier","text":"shouldInvalidateLayoutForSelectionChange"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1shouldInvalidateLayoutForSelectionChange/fragments"},{"op":"replace","value":"layoutAttributesForItemAtIndex:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1layoutAttributesForItem(at:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutAttributesForItemAtIndex:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1layoutAttributesForItem(at:)/fragments"},{"op":"replace","value":"shouldInvalidateLayoutForHighlightChange","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1shouldInvalidateLayoutForHighlightChange/title"},{"op":"replace","value":[{"kind":"identifier","text":"shouldInvalidateLayoutForHighlightChange"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1shouldInvalidateLayoutForHighlightChange/fragments"},{"op":"replace","value":"prepareLayout","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1prepare()/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"prepareLayout","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScrubberLayout~1prepare()/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}