{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremidi/documentation/CoreMIDI",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeRequestID"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeRequestID/badRequestID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreMIDI",
    "externalID": "c:@kMIDICIPropertyExchangeBadRequestID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "badRequestID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MIDICIPropertyExchangeRequestID",
        "text": "MIDICIPropertyExchangeRequestID"
      }
    ],
    "modules": [
      {
        "name": "Core MIDI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kMIDICIPropertyExchangeBadRequestID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "badRequestID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "badRequestID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeRequestID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MIDICIPropertyExchangeRequestID",
              "text": "MIDICIPropertyExchangeRequestID"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremidi/documentation/CoreMIDI": {
      "abstract": [
        {
          "text": "Communicate with MIDI devices such as hardware keyboards and synthesizers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI",
      "kind": "symbol",
      "role": "collection",
      "title": "Core MIDI",
      "type": "topic",
      "url": "/documentation/coremidi"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/CM_CONSTEXPR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CM_CONSTEXPR"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/CM_CONSTEXPR",
      "kind": "symbol",
      "role": "symbol",
      "title": "CM_CONSTEXPR",
      "type": "topic",
      "url": "/documentation/coremidi/cm_constexpr"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDICI1_0"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_0",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDICI1_0",
      "type": "topic",
      "url": "/documentation/coremidi/midici1_0"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_0_AVAILABILITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDICI1_0_AVAILABILITY"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_0_AVAILABILITY",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDICI1_0_AVAILABILITY",
      "type": "topic",
      "url": "/documentation/coremidi/midici1_0_availability"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_0_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDICI1_0_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_0_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDICI1_0_DEPRECATED",
      "type": "topic",
      "url": "/documentation/coremidi/midici1_0_deprecated"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDICI1_1"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_1",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDICI1_1",
      "type": "topic",
      "url": "/documentation/coremidi/midici1_1"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_1_AVAILABILITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDICI1_1_AVAILABILITY"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_1_AVAILABILITY",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDICI1_1_AVAILABILITY",
      "type": "topic",
      "url": "/documentation/coremidi/midici1_1_availability"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_1_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDICI1_1_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_1_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDICI1_1_DEPRECATED",
      "type": "topic",
      "url": "/documentation/coremidi/midici1_1_deprecated"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDICI1_2"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_2",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDICI1_2",
      "type": "topic",
      "url": "/documentation/coremidi/midici1_2"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeRequestID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MIDICIPropertyExchangeRequestID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeRequestID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDICIPropertyExchangeRequestID"
        }
      ],
      "role": "symbol",
      "title": "MIDICIPropertyExchangeRequestID",
      "type": "topic",
      "url": "/documentation/coremidi/midicipropertyexchangerequestid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeRequestID/badRequestID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badRequestID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDICIPropertyExchangeRequestID",
          "text": "MIDICIPropertyExchangeRequestID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeRequestID/badRequestID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kMIDICIPropertyExchangeBadRequestID"
        }
      ],
      "role": "symbol",
      "title": "badRequestID",
      "type": "topic",
      "url": "/documentation/coremidi/midicipropertyexchangerequestid/badrequestid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINETWORKSESSION_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDINETWORKSESSION_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINETWORKSESSION_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDINETWORKSESSION_AVAILABLE",
      "type": "topic",
      "url": "/documentation/coremidi/midinetworksession_available"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpointManager/DictionaryKey/endpointObject": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endpointObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MIDIUMPEndpointManager",
          "text": "MIDIUMPEndpointManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUMPEndpointManagerDictionaryKey",
          "text": "DictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpointManager/DictionaryKey/endpointObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUMPEndpointObjectKey"
        }
      ],
      "role": "symbol",
      "title": "endpointObject",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpendpointmanager/dictionarykey/endpointobject"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpointManager/DictionaryKey/functionBlockObject": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "functionBlockObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MIDIUMPEndpointManager",
          "text": "MIDIUMPEndpointManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MIDIUMPEndpointManagerDictionaryKey",
          "text": "DictionaryKey"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpointManager/DictionaryKey/functionBlockObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MIDIUMPFunctionBlockObjectKey"
        }
      ],
      "role": "symbol",
      "title": "functionBlockObject",
      "type": "topic",
      "url": "/documentation/coremidi/midiumpendpointmanager/dictionarykey/functionblockobject"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI_API_UNAVAILABLE_NON_MACOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDI_API_UNAVAILABLE_NON_MACOS"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI_API_UNAVAILABLE_NON_MACOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDI_API_UNAVAILABLE_NON_MACOS",
      "type": "topic",
      "url": "/documentation/coremidi/midi_api_unavailable_non_macos"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI_AVAILABLE_UMP1_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MIDI_AVAILABLE_UMP1_1"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI_AVAILABLE_UMP1_1",
      "kind": "symbol",
      "role": "symbol",
      "title": "MIDI_AVAILABLE_UMP1_1",
      "type": "topic",
      "url": "/documentation/coremidi/midi_available_ump1_1"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverInterface2ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kMIDIDriverInterface2ID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverInterface2ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kMIDIDriverInterface2ID",
      "type": "topic",
      "url": "/documentation/coremidi/kmididriverinterface2id"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverInterface3ID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kMIDIDriverInterface3ID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverInterface3ID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kMIDIDriverInterface3ID",
      "type": "topic",
      "url": "/documentation/coremidi/kmididriverinterface3id"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverInterfaceID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kMIDIDriverInterfaceID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverInterfaceID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kMIDIDriverInterfaceID",
      "type": "topic",
      "url": "/documentation/coremidi/kmididriverinterfaceid"
    },
    "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverTypeID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kMIDIDriverTypeID"
        }
      ],
      "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverTypeID",
      "kind": "symbol",
      "role": "symbol",
      "title": "kMIDIDriverTypeID",
      "type": "topic",
      "url": "/documentation/coremidi/kmididrivertypeid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Macros",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpointManager/DictionaryKey/endpointObject",
        "doc://com.apple.coremidi/documentation/CoreMIDI/MIDIUMPEndpointManager/DictionaryKey/functionBlockObject"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kMIDICIPropertyExchangeBadRequestID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICIPropertyExchangeBadRequestID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremidi/documentation/CoreMIDI"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremidi/documentation/CoreMIDI/CM_CONSTEXPR",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverInterface2ID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverInterface3ID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverInterfaceID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/kMIDIDriverTypeID",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI_API_UNAVAILABLE_NON_MACOS",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDI_AVAILABLE_UMP1_1",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_0_AVAILABILITY",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_0_DEPRECATED",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_0",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_1_AVAILABILITY",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_1_DEPRECATED",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_1",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICI1_2",
                "doc://com.apple.coremidi/documentation/CoreMIDI/MIDINETWORKSESSION_AVAILABLE"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "static"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.coremidi/documentation/CoreMIDI/MIDICIPropertyExchangeRequestID",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MIDICIPropertyExchangeRequestID",
                    "text": "MIDICIPropertyExchangeRequestID"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kMIDICIPropertyExchangeBadRequestID"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPEndpointManager~1DictionaryKey~1functionBlockObject/title",
          "value": "MIDIUMPFunctionBlockObjectKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPEndpointManager~1DictionaryKey~1functionBlockObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPFunctionBlockObjectKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIPropertyExchangeRequestID~1badRequestID/title",
          "value": "kMIDICIPropertyExchangeBadRequestID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIPropertyExchangeRequestID~1badRequestID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kMIDICIPropertyExchangeBadRequestID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPEndpointManager~1DictionaryKey~1endpointObject/title",
          "value": "MIDIUMPEndpointObjectKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDIUMPEndpointManager~1DictionaryKey~1endpointObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDIUMPEndpointObjectKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIPropertyExchangeRequestID/title",
          "value": "MIDICIPropertyExchangeRequestID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIPropertyExchangeRequestID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIPropertyExchangeRequestID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremidi~1documentation~1CoreMIDI~1MIDICIPropertyExchangeRequestID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MIDICIPropertyExchangeRequestID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremidi/midicipropertyexchangerequestid/badrequestid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremidi/midicipropertyexchangerequestid/badrequestid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
