{
  "abstract": [
    {
      "text": "An identifier that represents the description of the media.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierDescription"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@AVMetadataCommonIdentifierDescription",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "commonIdentifierDescription"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVMetadataIdentifier",
        "text": "AVMetadataIdentifier"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMetadataCommonIdentifierDescription"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "commonIdentifierDescription"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "commonIdentifierDescription"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVMetadataIdentifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier": {
      "abstract": [
        {
          "text": "A structure that defines identifiers for metadata formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataIdentifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierAccessibilityDescription": {
      "abstract": [
        {
          "text": "An identifier that represents the accessibility description for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonIdentifierAccessibilityDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierAccessibilityDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonIdentifierAccessibilityDescription"
        }
      ],
      "role": "symbol",
      "title": "commonIdentifierAccessibilityDescription",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/commonidentifieraccessibilitydescription"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierAlbumName": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonIdentifierAlbumName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierAlbumName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonIdentifierAlbumName"
        }
      ],
      "role": "symbol",
      "title": "commonIdentifierAlbumName",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/commonidentifieralbumname"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierArtist": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the artist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonIdentifierArtist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierArtist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonIdentifierArtist"
        }
      ],
      "role": "symbol",
      "title": "commonIdentifierArtist",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/commonidentifierartist"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierArtwork": {
      "abstract": [
        {
          "text": "An identifier that represents an image relating to the album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonIdentifierArtwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierArtwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonIdentifierArtwork"
        }
      ],
      "role": "symbol",
      "title": "commonIdentifierArtwork",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/commonidentifierartwork"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierAssetIdentifier": {
      "abstract": [
        {
          "text": "An identifier that represents the asset ID for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonIdentifierAssetIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierAssetIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonIdentifierAssetIdentifier"
        }
      ],
      "role": "symbol",
      "title": "commonIdentifierAssetIdentifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/commonidentifierassetidentifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierAuthor": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the author.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonIdentifierAuthor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierAuthor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonIdentifierAuthor"
        }
      ],
      "role": "symbol",
      "title": "commonIdentifierAuthor",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/commonidentifierauthor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierContributor": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the contributor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonIdentifierContributor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierContributor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonIdentifierContributor"
        }
      ],
      "role": "symbol",
      "title": "commonIdentifierContributor",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/commonidentifiercontributor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierCopyrights": {
      "abstract": [
        {
          "text": "An identifier that represents the copyright statement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonIdentifierCopyrights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierCopyrights",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonIdentifierCopyrights"
        }
      ],
      "role": "symbol",
      "title": "commonIdentifierCopyrights",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/commonidentifiercopyrights"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierCreationDate": {
      "abstract": [
        {
          "text": "An identifier that represents the date of the original recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonIdentifierCreationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierCreationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonIdentifierCreationDate"
        }
      ],
      "role": "symbol",
      "title": "commonIdentifierCreationDate",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/commonidentifiercreationdate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierCreator": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the creator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonIdentifierCreator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierCreator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonIdentifierCreator"
        }
      ],
      "role": "symbol",
      "title": "commonIdentifierCreator",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/commonidentifiercreator"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierDescription": {
      "abstract": [
        {
          "text": "An identifier that represents the description of the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonIdentifierDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonIdentifierDescription"
        }
      ],
      "role": "symbol",
      "title": "commonIdentifierDescription",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/commonidentifierdescription"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierFormat": {
      "abstract": [
        {
          "text": "An identifier that represents the file format of the media content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonIdentifierFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonIdentifierFormat"
        }
      ],
      "role": "symbol",
      "title": "commonIdentifierFormat",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/commonidentifierformat"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierLanguage": {
      "abstract": [
        {
          "text": "An identifier that represents the language of the text or lyrics spoken or sung in the audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonIdentifierLanguage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierLanguage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonIdentifierLanguage"
        }
      ],
      "role": "symbol",
      "title": "commonIdentifierLanguage",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/commonidentifierlanguage"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierLastModifiedDate": {
      "abstract": [
        {
          "text": "An identifier that represents the last modification date of the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonIdentifierLastModifiedDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierLastModifiedDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonIdentifierLastModifiedDate"
        }
      ],
      "role": "symbol",
      "title": "commonIdentifierLastModifiedDate",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/commonidentifierlastmodifieddate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierLocation": {
      "abstract": [
        {
          "text": "An identifier that represents the location information for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonIdentifierLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonIdentifierLocation"
        }
      ],
      "role": "symbol",
      "title": "commonIdentifierLocation",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/commonidentifierlocation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierMake": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the camera maker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonIdentifierMake"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierMake",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataCommonIdentifierMake"
        }
      ],
      "role": "symbol",
      "title": "commonIdentifierMake",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/commonidentifiermake"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Common-Metadata-Identifiers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierAccessibilityDescription",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierAlbumName",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierArtist",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierArtwork",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierAssetIdentifier",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierAuthor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierContributor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierCopyrights",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierCreationDate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierCreator",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierFormat",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierLanguage",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierLastModifiedDate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierLocation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierMake"
      ],
      "title": "Common Metadata Identifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMetadataCommonIdentifierDescription"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonIdentifierDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Common-Metadata-Identifiers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierAccessibilityDescription",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierAlbumName",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierArtist",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierArtwork",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierAssetIdentifier",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierAuthor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierContributor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierCopyrights",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierCreationDate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierCreator",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierFormat",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierLanguage",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierLastModifiedDate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierLocation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/commonIdentifierMake"
              ],
              "title": "Common Metadata Identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVMetadataIdentifier",
                    "text": "AVMetadataIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVMetadataCommonIdentifierDescription"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierCopyrights/title",
          "value": "AVMetadataCommonIdentifierCopyrights"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierCopyrights/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonIdentifierCopyrights"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierArtwork/title",
          "value": "AVMetadataCommonIdentifierArtwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierArtwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonIdentifierArtwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierArtist/title",
          "value": "AVMetadataCommonIdentifierArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierArtist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonIdentifierArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierAssetIdentifier/title",
          "value": "AVMetadataCommonIdentifierAssetIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierAssetIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonIdentifierAssetIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierAccessibilityDescription/title",
          "value": "AVMetadataCommonIdentifierAccessibilityDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierAccessibilityDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonIdentifierAccessibilityDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierCreator/title",
          "value": "AVMetadataCommonIdentifierCreator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierCreator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonIdentifierCreator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/title",
          "value": "AVMetadataIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierContributor/title",
          "value": "AVMetadataCommonIdentifierContributor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierContributor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonIdentifierContributor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierFormat/title",
          "value": "AVMetadataCommonIdentifierFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonIdentifierFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierMake/title",
          "value": "AVMetadataCommonIdentifierMake"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierMake/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonIdentifierMake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierLastModifiedDate/title",
          "value": "AVMetadataCommonIdentifierLastModifiedDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierLastModifiedDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonIdentifierLastModifiedDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierLocation/title",
          "value": "AVMetadataCommonIdentifierLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonIdentifierLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierDescription/title",
          "value": "AVMetadataCommonIdentifierDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonIdentifierDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierLanguage/title",
          "value": "AVMetadataCommonIdentifierLanguage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierLanguage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonIdentifierLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierAuthor/title",
          "value": "AVMetadataCommonIdentifierAuthor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierAuthor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonIdentifierAuthor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierAlbumName/title",
          "value": "AVMetadataCommonIdentifierAlbumName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierAlbumName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonIdentifierAlbumName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierCreationDate/title",
          "value": "AVMetadataCommonIdentifierCreationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1commonIdentifierCreationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataCommonIdentifierCreationDate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetadataidentifier/commonidentifierdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmetadataidentifier/commonidentifierdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
