{
  "abstract": [
    {
      "text": "An identifier that represents the software or hardware and settings used for encoding.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataEncodedWith"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@AVMetadataIdentifierID3MetadataEncodedWith",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "id3MetadataEncodedWith"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVMetadataIdentifier",
        "text": "AVMetadataIdentifier"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMetadataIdentifierID3MetadataEncodedWith"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "id3MetadataEncodedWith"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "id3MetadataEncodedWith"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVMetadataIdentifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier": {
      "abstract": [
        {
          "text": "A structure that defines identifiers for metadata formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataIdentifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAlbumSortOrder": {
      "abstract": [
        {
          "text": "An identifier that represents how to sort the album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataAlbumSortOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAlbumSortOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierID3MetadataAlbumSortOrder"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataAlbumSortOrder",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/id3metadataalbumsortorder"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAlbumTitle": {
      "abstract": [
        {
          "text": "An identifier that represents the title of the recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataAlbumTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAlbumTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierID3MetadataAlbumTitle"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataAlbumTitle",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/id3metadataalbumtitle"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAttachedPicture": {
      "abstract": [
        {
          "text": "An identifier that represents an image relating to the audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataAttachedPicture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAttachedPicture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierID3MetadataAttachedPicture"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataAttachedPicture",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/id3metadataattachedpicture"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAudioEncryption": {
      "abstract": [
        {
          "text": "An identifier that represents the encryption details of the audio stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataAudioEncryption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAudioEncryption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierID3MetadataAudioEncryption"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataAudioEncryption",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/id3metadataaudioencryption"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAudioSeekPointIndex": {
      "abstract": [
        {
          "text": "An identifier that represents the list of seek points within the audio file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataAudioSeekPointIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAudioSeekPointIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierID3MetadataAudioSeekPointIndex"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataAudioSeekPointIndex",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/id3metadataaudioseekpointindex"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataBand": {
      "abstract": [
        {
          "text": "An identifier that represents additional information about the performers in the recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataBand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataBand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierID3MetadataBand"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataBand",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/id3metadataband"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataBeatsPerMinute": {
      "abstract": [
        {
          "text": "An identifier that represents the beats per minute of the audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataBeatsPerMinute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataBeatsPerMinute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierID3MetadataBeatsPerMinute"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataBeatsPerMinute",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/id3metadatabeatsperminute"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataComments": {
      "abstract": [
        {
          "text": "An identifier that represents additional text information for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataComments"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataComments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierID3MetadataComments"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataComments",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/id3metadatacomments"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataCommercial": {
      "abstract": [
        {
          "text": "An identifier that represents the commercial details for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataCommercial"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataCommercial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierID3MetadataCommercial"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataCommercial",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/id3metadatacommercial"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataCommercialInformation": {
      "abstract": [
        {
          "text": "An identifier that represents the webpage containing purchasing information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataCommercialInformation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataCommercialInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierID3MetadataCommercialInformation"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataCommercialInformation",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/id3metadatacommercialinformation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataComposer": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the composer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataComposer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataComposer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierID3MetadataComposer"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataComposer",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/id3metadatacomposer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataConductor": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the conductor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataConductor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataConductor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierID3MetadataConductor"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataConductor",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/id3metadataconductor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataContentGroupDescription": {
      "abstract": [
        {
          "text": "An identifier that indicates the sound belongs to a larger category of sounds or music.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataContentGroupDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataContentGroupDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierID3MetadataContentGroupDescription"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataContentGroupDescription",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/id3metadatacontentgroupdescription"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataContentType": {
      "abstract": [
        {
          "text": "An identifier that represents the media content type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataContentType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataContentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierID3MetadataContentType"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataContentType",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/id3metadatacontenttype"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataCopyright": {
      "abstract": [
        {
          "text": "An identifier that represents the copyright statement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataCopyright"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataCopyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierID3MetadataCopyright"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataCopyright",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/id3metadatacopyright"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataEncodedWith": {
      "abstract": [
        {
          "text": "An identifier that represents the software or hardware and settings used for encoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id3MetadataEncodedWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataEncodedWith",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierID3MetadataEncodedWith"
        }
      ],
      "role": "symbol",
      "title": "id3MetadataEncodedWith",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/id3metadataencodedwith"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "ID3-Metadata-Identifiers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAlbumSortOrder",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAlbumTitle",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAttachedPicture",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAudioEncryption",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAudioSeekPointIndex",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataBand",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataBeatsPerMinute",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataComments",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataCommercial",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataCommercialInformation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataComposer",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataConductor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataContentGroupDescription",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataContentType",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataCopyright"
      ],
      "title": "ID3 Metadata Identifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMetadataIdentifierID3MetadataEncodedWith"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierID3MetadataEncodedWith"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "ID3-Metadata-Identifiers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAlbumSortOrder",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAlbumTitle",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAttachedPicture",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAudioEncryption",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataAudioSeekPointIndex",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataBand",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataBeatsPerMinute",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataComments",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataCommercial",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataCommercialInformation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataComposer",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataConductor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataContentGroupDescription",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataContentType",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/id3MetadataCopyright"
              ],
              "title": "ID3 Metadata Identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVMetadataIdentifier",
                    "text": "AVMetadataIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVMetadataIdentifierID3MetadataEncodedWith"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataEncodedWith/title",
          "value": "AVMetadataIdentifierID3MetadataEncodedWith"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataEncodedWith/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierID3MetadataEncodedWith"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataAlbumSortOrder/title",
          "value": "AVMetadataIdentifierID3MetadataAlbumSortOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataAlbumSortOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierID3MetadataAlbumSortOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataBand/title",
          "value": "AVMetadataIdentifierID3MetadataBand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataBand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierID3MetadataBand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataContentType/title",
          "value": "AVMetadataIdentifierID3MetadataContentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataContentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierID3MetadataContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataCommercialInformation/title",
          "value": "AVMetadataIdentifierID3MetadataCommercialInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataCommercialInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierID3MetadataCommercialInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataBeatsPerMinute/title",
          "value": "AVMetadataIdentifierID3MetadataBeatsPerMinute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataBeatsPerMinute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierID3MetadataBeatsPerMinute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataCommercial/title",
          "value": "AVMetadataIdentifierID3MetadataCommercial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataCommercial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierID3MetadataCommercial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataAudioEncryption/title",
          "value": "AVMetadataIdentifierID3MetadataAudioEncryption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataAudioEncryption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierID3MetadataAudioEncryption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataContentGroupDescription/title",
          "value": "AVMetadataIdentifierID3MetadataContentGroupDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataContentGroupDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierID3MetadataContentGroupDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataAttachedPicture/title",
          "value": "AVMetadataIdentifierID3MetadataAttachedPicture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataAttachedPicture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierID3MetadataAttachedPicture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataComposer/title",
          "value": "AVMetadataIdentifierID3MetadataComposer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataComposer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierID3MetadataComposer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataComments/title",
          "value": "AVMetadataIdentifierID3MetadataComments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataComments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierID3MetadataComments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataCopyright/title",
          "value": "AVMetadataIdentifierID3MetadataCopyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataCopyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierID3MetadataCopyright"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/title",
          "value": "AVMetadataIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataAudioSeekPointIndex/title",
          "value": "AVMetadataIdentifierID3MetadataAudioSeekPointIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataAudioSeekPointIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierID3MetadataAudioSeekPointIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataAlbumTitle/title",
          "value": "AVMetadataIdentifierID3MetadataAlbumTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataAlbumTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierID3MetadataAlbumTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataConductor/title",
          "value": "AVMetadataIdentifierID3MetadataConductor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1id3MetadataConductor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierID3MetadataConductor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetadataidentifier/id3metadataencodedwith"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmetadataidentifier/id3metadataencodedwith"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
