{
  "abstract": [
    {
      "text": "An identifier that represents the copyright statement.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataCopyright"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@AVMetadataIdentifier3GPUserDataCopyright",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "identifier3GPUserDataCopyright"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVMetadataIdentifier",
        "text": "AVMetadataIdentifier"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMetadataIdentifier3GPUserDataCopyright"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "identifier3GPUserDataCopyright"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "identifier3GPUserDataCopyright"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVMetadataIdentifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier": {
      "abstract": [
        {
          "text": "A structure that defines identifiers for metadata formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataIdentifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataAlbumAndTrack": {
      "abstract": [
        {
          "text": "An identifier that represents the text for the album and track titles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier3GPUserDataAlbumAndTrack"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataAlbumAndTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier3GPUserDataAlbumAndTrack"
        }
      ],
      "role": "symbol",
      "title": "identifier3GPUserDataAlbumAndTrack",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/identifier3gpuserdataalbumandtrack"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataAuthor": {
      "abstract": [
        {
          "text": "An identifier that represents the author of the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier3GPUserDataAuthor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataAuthor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier3GPUserDataAuthor"
        }
      ],
      "role": "symbol",
      "title": "identifier3GPUserDataAuthor",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/identifier3gpuserdataauthor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataCollection": {
      "abstract": [
        {
          "text": "An identifier that represents the collection name for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier3GPUserDataCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier3GPUserDataCollection"
        }
      ],
      "role": "symbol",
      "title": "identifier3GPUserDataCollection",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/identifier3gpuserdatacollection"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataCopyright": {
      "abstract": [
        {
          "text": "An identifier that represents the copyright statement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier3GPUserDataCopyright"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataCopyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier3GPUserDataCopyright"
        }
      ],
      "role": "symbol",
      "title": "identifier3GPUserDataCopyright",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/identifier3gpuserdatacopyright"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataDescription": {
      "abstract": [
        {
          "text": "An identifier that represents the description for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier3GPUserDataDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier3GPUserDataDescription"
        }
      ],
      "role": "symbol",
      "title": "identifier3GPUserDataDescription",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/identifier3gpuserdatadescription"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataGenre": {
      "abstract": [
        {
          "text": "An identifier that represents the genre of the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier3GPUserDataGenre"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataGenre",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier3GPUserDataGenre"
        }
      ],
      "role": "symbol",
      "title": "identifier3GPUserDataGenre",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/identifier3gpuserdatagenre"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataKeywordList": {
      "abstract": [
        {
          "text": "An identifier that represents the list of keywords for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier3GPUserDataKeywordList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataKeywordList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier3GPUserDataKeywordList"
        }
      ],
      "role": "symbol",
      "title": "identifier3GPUserDataKeywordList",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/identifier3gpuserdatakeywordlist"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataLocation": {
      "abstract": [
        {
          "text": "An identifier that represents the location information for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier3GPUserDataLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier3GPUserDataLocation"
        }
      ],
      "role": "symbol",
      "title": "identifier3GPUserDataLocation",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/identifier3gpuserdatalocation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataMediaClassification": {
      "abstract": [
        {
          "text": "An identifier that represents the classification of the media content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier3GPUserDataMediaClassification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataMediaClassification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier3GPUserDataMediaClassification"
        }
      ],
      "role": "symbol",
      "title": "identifier3GPUserDataMediaClassification",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/identifier3gpuserdatamediaclassification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataMediaRating": {
      "abstract": [
        {
          "text": "An identifier that represents the rating of the media content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier3GPUserDataMediaRating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataMediaRating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier3GPUserDataMediaRating"
        }
      ],
      "role": "symbol",
      "title": "identifier3GPUserDataMediaRating",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/identifier3gpuserdatamediarating"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataPerformer": {
      "abstract": [
        {
          "text": "An identifier that represents information about the performer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier3GPUserDataPerformer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataPerformer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier3GPUserDataPerformer"
        }
      ],
      "role": "symbol",
      "title": "identifier3GPUserDataPerformer",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/identifier3gpuserdataperformer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataRecordingYear": {
      "abstract": [
        {
          "text": "An identifier that represents the recording year for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier3GPUserDataRecordingYear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataRecordingYear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier3GPUserDataRecordingYear"
        }
      ],
      "role": "symbol",
      "title": "identifier3GPUserDataRecordingYear",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/identifier3gpuserdatarecordingyear"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataThumbnail": {
      "abstract": [
        {
          "text": "An identifier that represents the media thumbnail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier3GPUserDataThumbnail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataThumbnail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier3GPUserDataThumbnail"
        }
      ],
      "role": "symbol",
      "title": "identifier3GPUserDataThumbnail",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/identifier3gpuserdatathumbnail"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataTitle": {
      "abstract": [
        {
          "text": "An identifier that represents the title for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier3GPUserDataTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier3GPUserDataTitle"
        }
      ],
      "role": "symbol",
      "title": "identifier3GPUserDataTitle",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/identifier3gpuserdatatitle"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataUserRating": {
      "abstract": [
        {
          "text": "An identifier that represents the user rating.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier3GPUserDataUserRating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataUserRating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier3GPUserDataUserRating"
        }
      ],
      "role": "symbol",
      "title": "identifier3GPUserDataUserRating",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/identifier3gpuserdatauserrating"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "3GP-User-Metadata-Identifiers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataAlbumAndTrack",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataAuthor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataCollection",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataDescription",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataGenre",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataKeywordList",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataLocation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataMediaClassification",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataMediaRating",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataPerformer",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataRecordingYear",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataThumbnail",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataTitle",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataUserRating"
      ],
      "title": "3GP User Metadata Identifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMetadataIdentifier3GPUserDataCopyright"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier3GPUserDataCopyright"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "3GP-User-Metadata-Identifiers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataAlbumAndTrack",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataAuthor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataCollection",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataDescription",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataGenre",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataKeywordList",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataLocation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataMediaClassification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataMediaRating",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataPerformer",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataRecordingYear",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataThumbnail",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataTitle",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/identifier3GPUserDataUserRating"
              ],
              "title": "3GP User Metadata Identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVMetadataIdentifier",
                    "text": "AVMetadataIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVMetadataIdentifier3GPUserDataCopyright"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataMediaClassification/title",
          "value": "AVMetadataIdentifier3GPUserDataMediaClassification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataMediaClassification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier3GPUserDataMediaClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataRecordingYear/title",
          "value": "AVMetadataIdentifier3GPUserDataRecordingYear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataRecordingYear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier3GPUserDataRecordingYear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataLocation/title",
          "value": "AVMetadataIdentifier3GPUserDataLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier3GPUserDataLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataUserRating/title",
          "value": "AVMetadataIdentifier3GPUserDataUserRating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataUserRating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier3GPUserDataUserRating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataCopyright/title",
          "value": "AVMetadataIdentifier3GPUserDataCopyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataCopyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier3GPUserDataCopyright"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataMediaRating/title",
          "value": "AVMetadataIdentifier3GPUserDataMediaRating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataMediaRating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier3GPUserDataMediaRating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataPerformer/title",
          "value": "AVMetadataIdentifier3GPUserDataPerformer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataPerformer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier3GPUserDataPerformer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataThumbnail/title",
          "value": "AVMetadataIdentifier3GPUserDataThumbnail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataThumbnail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier3GPUserDataThumbnail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataAuthor/title",
          "value": "AVMetadataIdentifier3GPUserDataAuthor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataAuthor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier3GPUserDataAuthor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataGenre/title",
          "value": "AVMetadataIdentifier3GPUserDataGenre"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataGenre/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier3GPUserDataGenre"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataAlbumAndTrack/title",
          "value": "AVMetadataIdentifier3GPUserDataAlbumAndTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataAlbumAndTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier3GPUserDataAlbumAndTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataKeywordList/title",
          "value": "AVMetadataIdentifier3GPUserDataKeywordList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataKeywordList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier3GPUserDataKeywordList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataCollection/title",
          "value": "AVMetadataIdentifier3GPUserDataCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier3GPUserDataCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataDescription/title",
          "value": "AVMetadataIdentifier3GPUserDataDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier3GPUserDataDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/title",
          "value": "AVMetadataIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataTitle/title",
          "value": "AVMetadataIdentifier3GPUserDataTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1identifier3GPUserDataTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier3GPUserDataTitle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetadataidentifier/identifier3gpuserdatacopyright"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmetadataidentifier/identifier3gpuserdatacopyright"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
