{
  "abstract": [
    {
      "text": "An identifier that represents the extra materials for an album.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataOnlineExtras"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@AVMetadataIdentifieriTunesMetadataOnlineExtras",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "iTunesMetadataOnlineExtras"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVMetadataIdentifier",
        "text": "AVMetadataIdentifier"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMetadataIdentifieriTunesMetadataOnlineExtras"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "iTunesMetadataOnlineExtras"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "iTunesMetadataOnlineExtras"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVMetadataIdentifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier": {
      "abstract": [
        {
          "text": "A structure that defines identifiers for metadata formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataIdentifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAccountKind": {
      "abstract": [
        {
          "text": "An identifier that represents the kind of iTunes account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iTunesMetadataAccountKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAccountKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifieriTunesMetadataAccountKind"
        }
      ],
      "role": "symbol",
      "title": "iTunesMetadataAccountKind",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/itunesmetadataaccountkind"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAcknowledgement": {
      "abstract": [
        {
          "text": "An identifier that represents the acknowledgement information in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iTunesMetadataAcknowledgement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAcknowledgement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifieriTunesMetadataAcknowledgement"
        }
      ],
      "role": "symbol",
      "title": "iTunesMetadataAcknowledgement",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/itunesmetadataacknowledgement"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAlbum": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the album in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iTunesMetadataAlbum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAlbum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifieriTunesMetadataAlbum"
        }
      ],
      "role": "symbol",
      "title": "iTunesMetadataAlbum",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/itunesmetadataalbum"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAlbumArtist": {
      "abstract": [
        {
          "text": "An identifier that represents the artist for the album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iTunesMetadataAlbumArtist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAlbumArtist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifieriTunesMetadataAlbumArtist"
        }
      ],
      "role": "symbol",
      "title": "iTunesMetadataAlbumArtist",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/itunesmetadataalbumartist"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAppleID": {
      "abstract": [
        {
          "text": "An identifier that represents an Apple ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iTunesMetadataAppleID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAppleID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifieriTunesMetadataAppleID"
        }
      ],
      "role": "symbol",
      "title": "iTunesMetadataAppleID",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/itunesmetadataappleid"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataArranger": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the arranger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iTunesMetadataArranger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataArranger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifieriTunesMetadataArranger"
        }
      ],
      "role": "symbol",
      "title": "iTunesMetadataArranger",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/itunesmetadataarranger"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataArtDirector": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the art director.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iTunesMetadataArtDirector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataArtDirector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifieriTunesMetadataArtDirector"
        }
      ],
      "role": "symbol",
      "title": "iTunesMetadataArtDirector",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/itunesmetadataartdirector"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataArtist": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the artist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iTunesMetadataArtist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataArtist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifieriTunesMetadataArtist"
        }
      ],
      "role": "symbol",
      "title": "iTunesMetadataArtist",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/itunesmetadataartist"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataArtistID": {
      "abstract": [
        {
          "text": "An identifier that represents the ID for an artist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iTunesMetadataArtistID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataArtistID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifieriTunesMetadataArtistID"
        }
      ],
      "role": "symbol",
      "title": "iTunesMetadataArtistID",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/itunesmetadataartistid"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAuthor": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the author.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iTunesMetadataAuthor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAuthor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifieriTunesMetadataAuthor"
        }
      ],
      "role": "symbol",
      "title": "iTunesMetadataAuthor",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/itunesmetadataauthor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataBeatsPerMin": {
      "abstract": [
        {
          "text": "An identifier that represents the beats per minute of a track in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iTunesMetadataBeatsPerMin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataBeatsPerMin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifieriTunesMetadataBeatsPerMin"
        }
      ],
      "role": "symbol",
      "title": "iTunesMetadataBeatsPerMin",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/itunesmetadatabeatspermin"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataComposer": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the composer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iTunesMetadataComposer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataComposer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifieriTunesMetadataComposer"
        }
      ],
      "role": "symbol",
      "title": "iTunesMetadataComposer",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/itunesmetadatacomposer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataConductor": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the conductor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iTunesMetadataConductor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataConductor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifieriTunesMetadataConductor"
        }
      ],
      "role": "symbol",
      "title": "iTunesMetadataConductor",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/itunesmetadataconductor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataContentRating": {
      "abstract": [
        {
          "text": "An identifier that represents the content rating in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iTunesMetadataContentRating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataContentRating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifieriTunesMetadataContentRating"
        }
      ],
      "role": "symbol",
      "title": "iTunesMetadataContentRating",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/itunesmetadatacontentrating"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataCopyright": {
      "abstract": [
        {
          "text": "An identifier that represents the copyright statement in iTunes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iTunesMetadataCopyright"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataCopyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifieriTunesMetadataCopyright"
        }
      ],
      "role": "symbol",
      "title": "iTunesMetadataCopyright",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/itunesmetadatacopyright"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataOnlineExtras": {
      "abstract": [
        {
          "text": "An identifier that represents the extra materials for an album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iTunesMetadataOnlineExtras"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataOnlineExtras",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifieriTunesMetadataOnlineExtras"
        }
      ],
      "role": "symbol",
      "title": "iTunesMetadataOnlineExtras",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/itunesmetadataonlineextras"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "iTunes-Metadata-Identifiers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAccountKind",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAcknowledgement",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAlbum",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAlbumArtist",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAppleID",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataArranger",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataArtDirector",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataArtist",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataArtistID",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAuthor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataBeatsPerMin",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataComposer",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataConductor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataContentRating",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataCopyright"
      ],
      "title": "iTunes Metadata Identifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMetadataIdentifieriTunesMetadataOnlineExtras"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifieriTunesMetadataOnlineExtras"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "iTunes-Metadata-Identifiers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAccountKind",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAcknowledgement",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAlbum",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAlbumArtist",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAppleID",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataArranger",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataArtDirector",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataArtist",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataArtistID",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataAuthor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataBeatsPerMin",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataComposer",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataConductor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataContentRating",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/iTunesMetadataCopyright"
              ],
              "title": "iTunes Metadata Identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVMetadataIdentifier",
                    "text": "AVMetadataIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVMetadataIdentifieriTunesMetadataOnlineExtras"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataArranger/title",
          "value": "AVMetadataIdentifieriTunesMetadataArranger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataArranger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifieriTunesMetadataArranger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataBeatsPerMin/title",
          "value": "AVMetadataIdentifieriTunesMetadataBeatsPerMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataBeatsPerMin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifieriTunesMetadataBeatsPerMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataArtDirector/title",
          "value": "AVMetadataIdentifieriTunesMetadataArtDirector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataArtDirector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifieriTunesMetadataArtDirector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataAccountKind/title",
          "value": "AVMetadataIdentifieriTunesMetadataAccountKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataAccountKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifieriTunesMetadataAccountKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataArtistID/title",
          "value": "AVMetadataIdentifieriTunesMetadataArtistID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataArtistID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifieriTunesMetadataArtistID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataCopyright/title",
          "value": "AVMetadataIdentifieriTunesMetadataCopyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataCopyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifieriTunesMetadataCopyright"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataOnlineExtras/title",
          "value": "AVMetadataIdentifieriTunesMetadataOnlineExtras"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataOnlineExtras/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifieriTunesMetadataOnlineExtras"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/title",
          "value": "AVMetadataIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataAcknowledgement/title",
          "value": "AVMetadataIdentifieriTunesMetadataAcknowledgement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataAcknowledgement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifieriTunesMetadataAcknowledgement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataConductor/title",
          "value": "AVMetadataIdentifieriTunesMetadataConductor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataConductor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifieriTunesMetadataConductor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataComposer/title",
          "value": "AVMetadataIdentifieriTunesMetadataComposer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataComposer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifieriTunesMetadataComposer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataArtist/title",
          "value": "AVMetadataIdentifieriTunesMetadataArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataArtist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifieriTunesMetadataArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataAppleID/title",
          "value": "AVMetadataIdentifieriTunesMetadataAppleID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataAppleID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifieriTunesMetadataAppleID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataAuthor/title",
          "value": "AVMetadataIdentifieriTunesMetadataAuthor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataAuthor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifieriTunesMetadataAuthor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataAlbum/title",
          "value": "AVMetadataIdentifieriTunesMetadataAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataAlbum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifieriTunesMetadataAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataAlbumArtist/title",
          "value": "AVMetadataIdentifieriTunesMetadataAlbumArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataAlbumArtist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifieriTunesMetadataAlbumArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataContentRating/title",
          "value": "AVMetadataIdentifieriTunesMetadataContentRating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1iTunesMetadataContentRating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifieriTunesMetadataContentRating"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetadataidentifier/itunesmetadataonlineextras"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmetadataidentifier/itunesmetadataonlineextras"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
