{
  "abstract": [
    {
      "text": "An identifier that represents the name of the camera model.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataModel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@AVMetadataIdentifierQuickTimeUserDataModel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "quickTimeUserDataModel"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVMetadataIdentifier",
        "text": "AVMetadataIdentifier"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMetadataIdentifierQuickTimeUserDataModel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "quickTimeUserDataModel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "quickTimeUserDataModel"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVMetadataIdentifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier": {
      "abstract": [
        {
          "text": "A structure that defines identifiers for metadata formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataIdentifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataAccessibilityDescription": {
      "abstract": [
        {
          "text": "An identifier that represents the accessibility description for the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataAccessibilityDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataAccessibilityDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeUserDataAccessibilityDescription"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataAccessibilityDescription",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdataaccessibilitydescription"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataAlbum": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the album or collection in QuickTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataAlbum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataAlbum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeUserDataAlbum"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataAlbum",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdataalbum"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataArranger": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the arranger of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataArranger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataArranger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeUserDataArranger"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataArranger",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdataarranger"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataArtist": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the artist of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataArtist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataArtist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeUserDataArtist"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataArtist",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdataartist"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataAuthor": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the author of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataAuthor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataAuthor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeUserDataAuthor"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataAuthor",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdataauthor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataChapter": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the chapter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataChapter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataChapter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeUserDataChapter"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataChapter",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdatachapter"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataComment": {
      "abstract": [
        {
          "text": "An identifier that represents a comment regarding the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataComment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataComment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeUserDataComment"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataComment",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdatacomment"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataComposer": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the composer of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataComposer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataComposer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeUserDataComposer"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataComposer",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdatacomposer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataCopyright": {
      "abstract": [
        {
          "text": "An identifier that represents the copyright statement in QuickTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataCopyright"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataCopyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeUserDataCopyright"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataCopyright",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdatacopyright"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataCreationDate": {
      "abstract": [
        {
          "text": "An identifier that represents the creation date of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataCreationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataCreationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeUserDataCreationDate"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataCreationDate",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdatacreationdate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataCredits": {
      "abstract": [
        {
          "text": "An identifier that represents the credits of movie source content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataCredits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataCredits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeUserDataCredits"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataCredits",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdatacredits"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataDescription": {
      "abstract": [
        {
          "text": "An identifier that represents the description of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeUserDataDescription"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataDescription",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdatadescription"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataDirector": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the director of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataDirector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataDirector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeUserDataDirector"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataDirector",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdatadirector"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataDisclaimer": {
      "abstract": [
        {
          "text": "An identifier that represents the disclaimer regarding the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataDisclaimer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataDisclaimer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeUserDataDisclaimer"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataDisclaimer",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdatadisclaimer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataEncodedBy": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the person or organization responsible for encoding the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataEncodedBy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataEncodedBy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeUserDataEncodedBy"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataEncodedBy",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdataencodedby"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataModel": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the camera model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeUserDataModel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeUserDataModel"
        }
      ],
      "role": "symbol",
      "title": "quickTimeUserDataModel",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdatamodel"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "QuickTime-User-Metadata-Identifiers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataAccessibilityDescription",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataAlbum",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataArranger",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataArtist",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataAuthor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataChapter",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataComment",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataComposer",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataCopyright",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataCreationDate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataCredits",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataDescription",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataDirector",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataDisclaimer",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataEncodedBy"
      ],
      "title": "QuickTime User Metadata Identifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMetadataIdentifierQuickTimeUserDataModel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeUserDataModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "QuickTime-User-Metadata-Identifiers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataAccessibilityDescription",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataAlbum",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataArranger",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataArtist",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataAuthor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataChapter",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataComment",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataComposer",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataCopyright",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataCreationDate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataCredits",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataDescription",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataDirector",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataDisclaimer",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeUserDataEncodedBy"
              ],
              "title": "QuickTime User Metadata Identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVMetadataIdentifier",
                    "text": "AVMetadataIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVMetadataIdentifierQuickTimeUserDataModel"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataAlbum/title",
          "value": "AVMetadataIdentifierQuickTimeUserDataAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataAlbum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeUserDataAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataArtist/title",
          "value": "AVMetadataIdentifierQuickTimeUserDataArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataArtist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeUserDataArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataModel/title",
          "value": "AVMetadataIdentifierQuickTimeUserDataModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeUserDataModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataAuthor/title",
          "value": "AVMetadataIdentifierQuickTimeUserDataAuthor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataAuthor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeUserDataAuthor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataArranger/title",
          "value": "AVMetadataIdentifierQuickTimeUserDataArranger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataArranger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeUserDataArranger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataDisclaimer/title",
          "value": "AVMetadataIdentifierQuickTimeUserDataDisclaimer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataDisclaimer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeUserDataDisclaimer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataCopyright/title",
          "value": "AVMetadataIdentifierQuickTimeUserDataCopyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataCopyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeUserDataCopyright"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataEncodedBy/title",
          "value": "AVMetadataIdentifierQuickTimeUserDataEncodedBy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataEncodedBy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeUserDataEncodedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataCredits/title",
          "value": "AVMetadataIdentifierQuickTimeUserDataCredits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataCredits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeUserDataCredits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/title",
          "value": "AVMetadataIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataAccessibilityDescription/title",
          "value": "AVMetadataIdentifierQuickTimeUserDataAccessibilityDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataAccessibilityDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeUserDataAccessibilityDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataComposer/title",
          "value": "AVMetadataIdentifierQuickTimeUserDataComposer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataComposer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeUserDataComposer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataChapter/title",
          "value": "AVMetadataIdentifierQuickTimeUserDataChapter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataChapter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeUserDataChapter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataCreationDate/title",
          "value": "AVMetadataIdentifierQuickTimeUserDataCreationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataCreationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeUserDataCreationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataComment/title",
          "value": "AVMetadataIdentifierQuickTimeUserDataComment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataComment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeUserDataComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataDescription/title",
          "value": "AVMetadataIdentifierQuickTimeUserDataDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeUserDataDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataDirector/title",
          "value": "AVMetadataIdentifierQuickTimeUserDataDirector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeUserDataDirector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeUserDataDirector"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdatamodel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmetadataidentifier/quicktimeuserdatamodel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
