{
  "abstract": [
    {
      "text": "An identifier that represents the name of the artist of the movie file content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataArtist"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFoundation",
    "externalID": "c:@AVMetadataIdentifierQuickTimeMetadataArtist",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "quickTimeMetadataArtist"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AVMetadataIdentifier",
        "text": "AVMetadataIdentifier"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMetadataIdentifierQuickTimeMetadataArtist"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "quickTimeMetadataArtist"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "quickTimeMetadataArtist"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AVMetadataIdentifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier": {
      "abstract": [
        {
          "text": "A structure that defines identifiers for metadata formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataIdentifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataAccessibilityDescription": {
      "abstract": [
        {
          "text": "An identifier that represents the accessibility description for the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataAccessibilityDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataAccessibilityDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeMetadataAccessibilityDescription"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataAccessibilityDescription",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimemetadataaccessibilitydescription"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataAlbum": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the album or collection in QuickTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataAlbum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataAlbum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeMetadataAlbum"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataAlbum",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimemetadataalbum"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataArranger": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the arranger of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataArranger"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataArranger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeMetadataArranger"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataArranger",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimemetadataarranger"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataArtist": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the artist of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataArtist"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataArtist",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeMetadataArtist"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataArtist",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimemetadataartist"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataArtwork": {
      "abstract": [
        {
          "text": "An identifier that represents an image relating to the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataArtwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataArtwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeMetadataArtwork"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataArtwork",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimemetadataartwork"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataAuthor": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the author of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataAuthor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataAuthor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeMetadataAuthor"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataAuthor",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimemetadataauthor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataAutoLivePhoto": {
      "abstract": [
        {
          "text": "An identifier that represents whether the live photo movie used auto mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataAutoLivePhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataAutoLivePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeMetadataAutoLivePhoto"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataAutoLivePhoto",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimemetadataautolivephoto"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCameraFrameReadoutTime": {
      "abstract": [
        {
          "text": "An identifier that represents the camera frame readout time in QuickTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataCameraFrameReadoutTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCameraFrameReadoutTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeMetadataCameraFrameReadoutTime"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataCameraFrameReadoutTime",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimemetadatacameraframereadouttime"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCameraIdentifier": {
      "abstract": [
        {
          "text": "An identifier that represents the camera identifier in QuickTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataCameraIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCameraIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeMetadataCameraIdentifier"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataCameraIdentifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimemetadatacameraidentifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCollectionUser": {
      "abstract": [
        {
          "text": "An identifier that represents a name that indicates a user-defined collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataCollectionUser"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCollectionUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeMetadataCollectionUser"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataCollectionUser",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimemetadatacollectionuser"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataComment": {
      "abstract": [
        {
          "text": "An identifier that represents a comment regarding the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataComment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataComment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeMetadataComment"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataComment",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimemetadatacomment"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataComposer": {
      "abstract": [
        {
          "text": "An identifier that represents the name of the composer of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataComposer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataComposer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeMetadataComposer"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataComposer",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimemetadatacomposer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataContentIdentifier": {
      "abstract": [
        {
          "text": "An identifier that represents the content identifier in QuickTime.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataContentIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataContentIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeMetadataContentIdentifier"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataContentIdentifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimemetadatacontentidentifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCopyright": {
      "abstract": [
        {
          "text": "An identifier that represents the copyright statement for the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataCopyright"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCopyright",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeMetadataCopyright"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataCopyright",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimemetadatacopyright"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCreationDate": {
      "abstract": [
        {
          "text": "An identifier that represents the creation date of the movie file content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataCreationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCreationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeMetadataCreationDate"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataCreationDate",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimemetadatacreationdate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCredits": {
      "abstract": [
        {
          "text": "An identifier that represents the credits of the movie source content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickTimeMetadataCredits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataIdentifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCredits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifierQuickTimeMetadataCredits"
        }
      ],
      "role": "symbol",
      "title": "quickTimeMetadataCredits",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier/quicktimemetadatacredits"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "QuickTime-Metadata-Identifiers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataAccessibilityDescription",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataAlbum",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataArranger",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataArtwork",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataAuthor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataAutoLivePhoto",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCameraFrameReadoutTime",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCameraIdentifier",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCollectionUser",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataComment",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataComposer",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataContentIdentifier",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCopyright",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCreationDate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCredits"
      ],
      "title": "QuickTime Metadata Identifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMetadataIdentifierQuickTimeMetadataArtist"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeMetadataArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "QuickTime-Metadata-Identifiers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataAccessibilityDescription",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataAlbum",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataArranger",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataArtwork",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataAuthor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataAutoLivePhoto",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCameraFrameReadoutTime",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCameraIdentifier",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCollectionUser",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataComment",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataComposer",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataContentIdentifier",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCopyright",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCreationDate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier/quickTimeMetadataCredits"
              ],
              "title": "QuickTime Metadata Identifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AVMetadataIdentifier",
                    "text": "AVMetadataIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVMetadataIdentifierQuickTimeMetadataArtist"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataCreationDate/title",
          "value": "AVMetadataIdentifierQuickTimeMetadataCreationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataCreationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeMetadataCreationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataContentIdentifier/title",
          "value": "AVMetadataIdentifierQuickTimeMetadataContentIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataContentIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeMetadataContentIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataCameraIdentifier/title",
          "value": "AVMetadataIdentifierQuickTimeMetadataCameraIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataCameraIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeMetadataCameraIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataCredits/title",
          "value": "AVMetadataIdentifierQuickTimeMetadataCredits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataCredits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeMetadataCredits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataArtwork/title",
          "value": "AVMetadataIdentifierQuickTimeMetadataArtwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataArtwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeMetadataArtwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataComment/title",
          "value": "AVMetadataIdentifierQuickTimeMetadataComment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataComment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeMetadataComment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataArranger/title",
          "value": "AVMetadataIdentifierQuickTimeMetadataArranger"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataArranger/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeMetadataArranger"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/title",
          "value": "AVMetadataIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataCameraFrameReadoutTime/title",
          "value": "AVMetadataIdentifierQuickTimeMetadataCameraFrameReadoutTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataCameraFrameReadoutTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeMetadataCameraFrameReadoutTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataAlbum/title",
          "value": "AVMetadataIdentifierQuickTimeMetadataAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataAlbum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeMetadataAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataCopyright/title",
          "value": "AVMetadataIdentifierQuickTimeMetadataCopyright"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataCopyright/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeMetadataCopyright"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataAutoLivePhoto/title",
          "value": "AVMetadataIdentifierQuickTimeMetadataAutoLivePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataAutoLivePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeMetadataAutoLivePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataCollectionUser/title",
          "value": "AVMetadataIdentifierQuickTimeMetadataCollectionUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataCollectionUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeMetadataCollectionUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataArtist/title",
          "value": "AVMetadataIdentifierQuickTimeMetadataArtist"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataArtist/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeMetadataArtist"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataAccessibilityDescription/title",
          "value": "AVMetadataIdentifierQuickTimeMetadataAccessibilityDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataAccessibilityDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeMetadataAccessibilityDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataAuthor/title",
          "value": "AVMetadataIdentifierQuickTimeMetadataAuthor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataAuthor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeMetadataAuthor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataComposer/title",
          "value": "AVMetadataIdentifierQuickTimeMetadataComposer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier~1quickTimeMetadataComposer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifierQuickTimeMetadataComposer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetadataidentifier/quicktimemetadataartist"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmetadataidentifier/quicktimemetadataartist"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
