{
  "abstract": [
    {
      "text": "Searches the renderer’s scene for objects corresponding to a point in the rendered image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/hitTest(_:options:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)SCNSceneRenderer(im)hitTest:options:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "hitTest"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGPoint",
        "text": "CGPoint"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "options"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@SCNHitTestOption",
        "text": "SCNHitTestOption"
      },
      {
        "kind": "text",
        "text": " : "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "]?) -> ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SCNHitTestResult",
        "text": "SCNHitTestResult"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "hitTest:options:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "hitTest(_:options:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "hitTest"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "point"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGPoint",
              "text": "CGPoint"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOption",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@SCNHitTestOption",
              "text": "SCNHitTestOption"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "]? = nil) -> ["
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SCNHitTestResult",
              "text": "SCNHitTestResult"
            },
            {
              "kind": "text",
              "text": "]"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A point in the screen-space (view, layer, or GPU viewport) coordinate system of the scene renderer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "point"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A dictionary of options affecting the search. See Hit Testing Options Keys for acceptable values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestResult",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects representing search results.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A 2D point in the rendered screen coordinate space can refer to any point along a line segment in the 3D scene coordinate space. Hit-testing is the process of finding elements of a scene located along this line segment. For example, you can use this method to find the geometry corresponding to a click event in a SceneKit view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOption": {
      "abstract": [
        {
          "text": "Options affecting the behavior of SceneKit hit-testing methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNHitTestOption"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNHitTestOption"
        }
      ],
      "role": "symbol",
      "title": "SCNHitTestOption",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestoption"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestResult": {
      "abstract": [
        {
          "text": "Information about the result of a scene-space or view-space search for scene elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNHitTestResult"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNHitTestResult"
        }
      ],
      "role": "symbol",
      "title": "SCNHitTestResult",
      "type": "topic",
      "url": "/documentation/scenekit/scnhittestresult"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNLayer": {
      "abstract": [
        {
          "text": "A Core Animation layer that renders a SceneKit scene as its content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNLayer"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNLayer"
        }
      ],
      "role": "symbol",
      "title": "SCNLayer",
      "type": "topic",
      "url": "/documentation/scenekit/scnlayer"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderer": {
      "abstract": [
        {
          "text": "A renderer for displaying a SceneKit scene in an existing Metal workflow or OpenGL context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNRenderer"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNRenderer"
        }
      ],
      "role": "symbol",
      "title": "SCNRenderer",
      "type": "topic",
      "url": "/documentation/scenekit/scnrenderer"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer": {
      "abstract": [
        {
          "text": "Methods and properties common to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNLayer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNRenderer",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " classes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSceneRenderer"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSceneRenderer"
        }
      ],
      "role": "symbol",
      "title": "SCNSceneRenderer",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/hitTest(_:options:)": {
      "abstract": [
        {
          "text": "Searches the renderer’s scene for objects corresponding to a point in the rendered image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hitTest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@SCNHitTestOption",
          "text": "SCNHitTestOption"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNHitTestResult",
          "text": "SCNHitTestResult"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/hitTest(_:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hitTest:options:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "hitTest(_:options:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer/hittest(_:options:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/isNode(_:insideFrustumOf:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether a node might be visible from a specified point of view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isNode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNNode",
          "text": "SCNNode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "insideFrustumOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNNode",
          "text": "SCNNode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/isNode(_:insideFrustumOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isNodeInsideFrustum:withPointOfView:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isNode(_:insideFrustumOf:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer/isnode(_:insidefrustumof:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/nodesInsideFrustum(of:)": {
      "abstract": [
        {
          "text": "Returns all nodes that might be visible from a specified point of view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nodesInsideFrustum"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNNode",
          "text": "SCNNode"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNNode",
          "text": "SCNNode"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/nodesInsideFrustum(of:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nodesInsideFrustumWithPointOfView:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "nodesInsideFrustum(of:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer/nodesinsidefrustum(of:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/projectPoint(_:)": {
      "abstract": [
        {
          "text": "Projects a point from the 3D world coordinate system of the scene to the 2D pixel coordinate system of the renderer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "projectPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/projectPoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "projectPoint:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "projectPoint(_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer/projectpoint(_:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/unprojectPoint(_:)": {
      "abstract": [
        {
          "text": "Unprojects a point from the 2D pixel coordinate system of the renderer to the 3D world coordinate system of the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unprojectPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/unprojectPoint(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unprojectPoint:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "unprojectPoint(_:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnscenerenderer/unprojectpoint(_:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNView": {
      "abstract": [
        {
          "text": "A view for displaying 3D SceneKit content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNView"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNView"
        }
      ],
      "role": "symbol",
      "title": "SCNView",
      "type": "topic",
      "url": "/documentation/scenekit/scnview"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGPoint": {
      "abstract": [
        {
          "text": "A structure that contains a point in a two-dimensional coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGPoint",
      "type": "topic",
      "url": "/documentation/corefoundation/cgpoint"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-With-Projected-Scene-Contents",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOption",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/isNode(_:insideFrustumOf:)",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/nodesInsideFrustum(of:)",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/projectPoint(_:)",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/unprojectPoint(_:)"
      ],
      "title": "Working With Projected Scene Contents"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "hitTest:options:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "hitTest:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-With-Projected-Scene-Contents",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestOption",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/isNode(_:insideFrustumOf:)",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/nodesInsideFrustum(of:)",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/projectPoint(_:)",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNSceneRenderer/unprojectPoint(_:)"
              ],
              "title": "Working With Projected Scene Contents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<SCNHitTestResult *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "hitTest:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGPoint",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGPoint",
                    "text": "CGPoint"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "point"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "options:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSDictionary",
                    "text": "NSDictionary<NSString *,id>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "options"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A point in the screen-space (view, layer, or GPU viewport) coordinate system of the scene renderer.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "point"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A dictionary of options affecting the search. See Hit Testing Options Keys for acceptable values.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "options"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An array of ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNHitTestResult",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " objects representing search results.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1projectPoint(_:)/title",
          "value": "projectPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1projectPoint(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "projectPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNHitTestOption/title",
          "value": "SCNHitTestOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNHitTestOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNHitTestOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNHitTestOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNHitTestOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1nodesInsideFrustum(of:)/title",
          "value": "nodesInsideFrustumWithPointOfView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1nodesInsideFrustum(of:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "nodesInsideFrustumWithPointOfView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderer/title",
          "value": "SCNRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNHitTestResult/title",
          "value": "SCNHitTestResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNHitTestResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNHitTestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNHitTestResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNHitTestResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView/title",
          "value": "SCNView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer/title",
          "value": "SCNSceneRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSceneRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1isNode(_:insideFrustumOf:)/title",
          "value": "isNodeInsideFrustum:withPointOfView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1isNode(_:insideFrustumOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isNodeInsideFrustum:withPointOfView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1unprojectPoint(_:)/title",
          "value": "unprojectPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1unprojectPoint(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unprojectPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1hitTest(_:options:)/title",
          "value": "hitTest:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSceneRenderer~1hitTest(_:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "hitTest:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLayer/title",
          "value": "SCNLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNLayer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnscenerenderer/hittest(_:options:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnscenerenderer/hittest(_:options:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
