{
  "abstract": [
    {
      "text": "A date that represents the start of the event.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.datadetection/documentation/DataDetection",
        "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/startDate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)DDMatchCalendarEvent(py)startDate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "startDate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4DateV",
        "text": "Date"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "DataDetection"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "startDate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "startDate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "startDate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DateV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4DateV",
              "text": "Date"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.datadetection/documentation/DataDetection": {
      "abstract": [
        {
          "text": "Access and utilize common types of data that the data detection system matches.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection",
      "kind": "symbol",
      "role": "collection",
      "title": "DataDetection",
      "type": "topic",
      "url": "/documentation/datadetection"
    },
    "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent": {
      "abstract": [
        {
          "text": "An object that represents a calendar date or date range that the data detection system matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDMatchCalendarEvent"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDMatchCalendarEvent"
        }
      ],
      "role": "symbol",
      "title": "DDMatchCalendarEvent",
      "type": "topic",
      "url": "/documentation/datadetection/ddmatchcalendarevent"
    },
    "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/endDate": {
      "abstract": [
        {
          "text": "A date that represents the end of the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/endDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endDate"
        }
      ],
      "role": "symbol",
      "title": "endDate",
      "type": "topic",
      "url": "/documentation/datadetection/ddmatchcalendarevent/enddate"
    },
    "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/endTimeZone": {
      "abstract": [
        {
          "text": "The time zone for the event’s end date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endTimeZone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8TimeZoneV",
          "text": "TimeZone"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/endTimeZone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endTimeZone"
        }
      ],
      "role": "symbol",
      "title": "endTimeZone",
      "type": "topic",
      "url": "/documentation/datadetection/ddmatchcalendarevent/endtimezone"
    },
    "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/isAllDay": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the event is an all-day event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAllDay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/isAllDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allDay"
        }
      ],
      "role": "symbol",
      "title": "isAllDay",
      "type": "topic",
      "url": "/documentation/datadetection/ddmatchcalendarevent/isallday"
    },
    "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/startDate": {
      "abstract": [
        {
          "text": "A date that represents the start of the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/startDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startDate"
        }
      ],
      "role": "symbol",
      "title": "startDate",
      "type": "topic",
      "url": "/documentation/datadetection/ddmatchcalendarevent/startdate"
    },
    "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/startTimeZone": {
      "abstract": [
        {
          "text": "The time zone for the event’s start date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startTimeZone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8TimeZoneV",
          "text": "TimeZone"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/startTimeZone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startTimeZone"
        }
      ],
      "role": "symbol",
      "title": "startTimeZone",
      "type": "topic",
      "url": "/documentation/datadetection/ddmatchcalendarevent/starttimezone"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4DateV": {
      "abstract": [
        {
          "text": "A specific point in time, independent of any calendar or time zone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DateV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Date",
      "type": "topic",
      "url": "/documentation/foundation/date"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-event-details",
      "generated": true,
      "identifiers": [
        "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/isAllDay",
        "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/endDate",
        "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/endTimeZone",
        "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/startTimeZone"
      ],
      "title": "Getting event details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "startDate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.datadetection/documentation/DataDetection",
                "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-event-details",
              "generated": true,
              "identifiers": [
                "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/isAllDay",
                "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/endDate",
                "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/endTimeZone",
                "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent/startTimeZone"
              ],
              "title": "Getting event details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSDate",
                    "text": "NSDate"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "startDate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchCalendarEvent/title",
          "value": "DDMatchCalendarEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchCalendarEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchCalendarEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchCalendarEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchCalendarEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchCalendarEvent~1startDate/title",
          "value": "startDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchCalendarEvent~1startDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchCalendarEvent~1isAllDay/title",
          "value": "allDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchCalendarEvent~1isAllDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchCalendarEvent~1endDate/title",
          "value": "endDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchCalendarEvent~1endDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "endDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchCalendarEvent~1endTimeZone/title",
          "value": "endTimeZone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchCalendarEvent~1endTimeZone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "endTimeZone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchCalendarEvent~1startTimeZone/title",
          "value": "startTimeZone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchCalendarEvent~1startTimeZone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startTimeZone"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/datadetection/ddmatchcalendarevent/startdate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/datadetection/ddmatchcalendarevent/startdate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
