{
  "abstract": [
    {
      "text": "An error that indicates the web process that contains the content is no longer running.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKError",
        "doc://com.apple.webkit/documentation/WebKit/WKError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKError/Code/webContentProcessTerminated"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKErrorCode@WKErrorWebContentProcessTerminated",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "webContentProcessTerminated"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKErrorWebContentProcessTerminated"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WKError.Code.webContentProcessTerminated"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "webContentProcessTerminated"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError": {
      "abstract": [
        {
          "text": "Possible error values that WebKit APIs can return.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKError"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKError"
        }
      ],
      "role": "symbol",
      "title": "WKError",
      "type": "topic",
      "url": "/documentation/webkit/wkerror"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code": {
      "abstract": [
        {
          "text": "Possible error values that WebKit APIs can return.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code/attributedStringContentFailedToLoad": {
      "abstract": [
        {
          "text": "An error that indicates the failure to navigate to web content from an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedStringContentFailedToLoad"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code/attributedStringContentFailedToLoad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKErrorAttributedStringContentFailedToLoad"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code.attributedStringContentFailedToLoad",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code/attributedstringcontentfailedtoload"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code/attributedStringContentLoadTimedOut": {
      "abstract": [
        {
          "text": "An error that indicates a timeout occurred while trying to load web content from an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedStringContentLoadTimedOut"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code/attributedStringContentLoadTimedOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKErrorAttributedStringContentLoadTimedOut"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code.attributedStringContentLoadTimedOut",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code/attributedstringcontentloadtimedout"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code/contentRuleListStoreCompileFailed": {
      "abstract": [
        {
          "text": "An error that indicates the compilation of a rule list failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentRuleListStoreCompileFailed"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code/contentRuleListStoreCompileFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKErrorContentRuleListStoreCompileFailed"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code.contentRuleListStoreCompileFailed",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code/contentruleliststorecompilefailed"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code/contentRuleListStoreLookUpFailed": {
      "abstract": [
        {
          "text": "An error that indicates a content rule list data store didn’t find a rule list with the specified identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentRuleListStoreLookUpFailed"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code/contentRuleListStoreLookUpFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKErrorContentRuleListStoreLookUpFailed"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code.contentRuleListStoreLookUpFailed",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code/contentruleliststorelookupfailed"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code/contentRuleListStoreRemoveFailed": {
      "abstract": [
        {
          "text": "An error that indicates a failure to remove a content rule list from the rule list data store object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentRuleListStoreRemoveFailed"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code/contentRuleListStoreRemoveFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKErrorContentRuleListStoreRemoveFailed"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code.contentRuleListStoreRemoveFailed",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code/contentruleliststoreremovefailed"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code/contentRuleListStoreVersionMismatch": {
      "abstract": [
        {
          "text": "An error that indicates the rule list version is outdated and cannot be read.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentRuleListStoreVersionMismatch"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code/contentRuleListStoreVersionMismatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKErrorContentRuleListStoreVersionMismatch"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code.contentRuleListStoreVersionMismatch",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code/contentruleliststoreversionmismatch"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code/credentialNotFound": {
      "abstract": [
        {
          "text": "An error that indicates the system could not find a passkey during an export.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "credentialNotFound"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code/credentialNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKErrorCredentialNotFound"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code.credentialNotFound",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code/credentialnotfound"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code/duplicateCredential": {
      "abstract": [
        {
          "text": "An error that indicates the system found a duplicate passkey during an import.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duplicateCredential"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code/duplicateCredential",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKErrorDuplicateCredential"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code.duplicateCredential",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code/duplicatecredential"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code/javaScriptAppBoundDomain": {
      "abstract": [
        {
          "text": "An error that indicates JavaScript execution failed due to an app-bound domain restriction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "javaScriptAppBoundDomain"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code/javaScriptAppBoundDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKErrorJavaScriptAppBoundDomain"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code.javaScriptAppBoundDomain",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code/javascriptappbounddomain"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code/javaScriptExceptionOccurred": {
      "abstract": [
        {
          "text": "An error that indicates a JavaScript exception occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "javaScriptExceptionOccurred"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code/javaScriptExceptionOccurred",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKErrorJavaScriptExceptionOccurred"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code.javaScriptExceptionOccurred",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code/javascriptexceptionoccurred"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code/javaScriptInvalidFrameTarget": {
      "abstract": [
        {
          "text": "An error that indicates your content referenced an invalid web frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "javaScriptInvalidFrameTarget"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code/javaScriptInvalidFrameTarget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKErrorJavaScriptInvalidFrameTarget"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code.javaScriptInvalidFrameTarget",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code/javascriptinvalidframetarget"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code/javaScriptResultTypeIsUnsupported": {
      "abstract": [
        {
          "text": "An error that indicates the result of JavaScript execution could not be returned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "javaScriptResultTypeIsUnsupported"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code/javaScriptResultTypeIsUnsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKErrorJavaScriptResultTypeIsUnsupported"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code.javaScriptResultTypeIsUnsupported",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code/javascriptresulttypeisunsupported"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code/navigationAppBoundDomain": {
      "abstract": [
        {
          "text": "An error that indicates navigation failed due to an app-bound domain restriction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "navigationAppBoundDomain"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code/navigationAppBoundDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKErrorNavigationAppBoundDomain"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code.navigationAppBoundDomain",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code/navigationappbounddomain"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code/unknown": {
      "abstract": [
        {
          "text": "An error that indicates an unknown issue occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code.unknown",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code/unknown"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code/webContentProcessTerminated": {
      "abstract": [
        {
          "text": "An error that indicates the web process that contains the content is no longer running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webContentProcessTerminated"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code/webContentProcessTerminated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKErrorWebContentProcessTerminated"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code.webContentProcessTerminated",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code/webcontentprocessterminated"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKError/Code/webViewInvalidated": {
      "abstract": [
        {
          "text": "An error that indicates the web view was invalidated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webViewInvalidated"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKError/Code/webViewInvalidated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKErrorWebViewInvalidated"
        }
      ],
      "role": "symbol",
      "title": "WKError.Code.webViewInvalidated",
      "type": "topic",
      "url": "/documentation/webkit/wkerror/code/webviewinvalidated"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKError/Code/unknown",
        "doc://com.apple.webkit/documentation/WebKit/WKError/Code/webViewInvalidated",
        "doc://com.apple.webkit/documentation/WebKit/WKError/Code/javaScriptExceptionOccurred",
        "doc://com.apple.webkit/documentation/WebKit/WKError/Code/javaScriptResultTypeIsUnsupported",
        "doc://com.apple.webkit/documentation/WebKit/WKError/Code/contentRuleListStoreCompileFailed",
        "doc://com.apple.webkit/documentation/WebKit/WKError/Code/contentRuleListStoreLookUpFailed",
        "doc://com.apple.webkit/documentation/WebKit/WKError/Code/contentRuleListStoreRemoveFailed",
        "doc://com.apple.webkit/documentation/WebKit/WKError/Code/contentRuleListStoreVersionMismatch",
        "doc://com.apple.webkit/documentation/WebKit/WKError/Code/attributedStringContentFailedToLoad",
        "doc://com.apple.webkit/documentation/WebKit/WKError/Code/attributedStringContentLoadTimedOut",
        "doc://com.apple.webkit/documentation/WebKit/WKError/Code/javaScriptInvalidFrameTarget",
        "doc://com.apple.webkit/documentation/WebKit/WKError/Code/navigationAppBoundDomain",
        "doc://com.apple.webkit/documentation/WebKit/WKError/Code/javaScriptAppBoundDomain",
        "doc://com.apple.webkit/documentation/WebKit/WKError/Code/credentialNotFound",
        "doc://com.apple.webkit/documentation/WebKit/WKError/Code/duplicateCredential"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKErrorWebContentProcessTerminated"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorWebContentProcessTerminated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit",
                "doc://com.apple.webkit/documentation/WebKit/WKError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKError/Code/unknown",
                "doc://com.apple.webkit/documentation/WebKit/WKError/Code/webViewInvalidated",
                "doc://com.apple.webkit/documentation/WebKit/WKError/Code/javaScriptExceptionOccurred",
                "doc://com.apple.webkit/documentation/WebKit/WKError/Code/javaScriptResultTypeIsUnsupported",
                "doc://com.apple.webkit/documentation/WebKit/WKError/Code/contentRuleListStoreCompileFailed",
                "doc://com.apple.webkit/documentation/WebKit/WKError/Code/contentRuleListStoreLookUpFailed",
                "doc://com.apple.webkit/documentation/WebKit/WKError/Code/contentRuleListStoreRemoveFailed",
                "doc://com.apple.webkit/documentation/WebKit/WKError/Code/contentRuleListStoreVersionMismatch",
                "doc://com.apple.webkit/documentation/WebKit/WKError/Code/attributedStringContentFailedToLoad",
                "doc://com.apple.webkit/documentation/WebKit/WKError/Code/attributedStringContentLoadTimedOut",
                "doc://com.apple.webkit/documentation/WebKit/WKError/Code/javaScriptInvalidFrameTarget",
                "doc://com.apple.webkit/documentation/WebKit/WKError/Code/navigationAppBoundDomain",
                "doc://com.apple.webkit/documentation/WebKit/WKError/Code/javaScriptAppBoundDomain",
                "doc://com.apple.webkit/documentation/WebKit/WKError/Code/credentialNotFound",
                "doc://com.apple.webkit/documentation/WebKit/WKError/Code/duplicateCredential"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WKErrorWebContentProcessTerminated"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1javaScriptInvalidFrameTarget/title",
          "value": "WKErrorJavaScriptInvalidFrameTarget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1javaScriptInvalidFrameTarget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorJavaScriptInvalidFrameTarget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1contentRuleListStoreLookUpFailed/title",
          "value": "WKErrorContentRuleListStoreLookUpFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1contentRuleListStoreLookUpFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorContentRuleListStoreLookUpFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1attributedStringContentFailedToLoad/title",
          "value": "WKErrorAttributedStringContentFailedToLoad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1attributedStringContentFailedToLoad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorAttributedStringContentFailedToLoad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1unknown/title",
          "value": "WKErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1contentRuleListStoreRemoveFailed/title",
          "value": "WKErrorContentRuleListStoreRemoveFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1contentRuleListStoreRemoveFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorContentRuleListStoreRemoveFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1credentialNotFound/title",
          "value": "WKErrorCredentialNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1credentialNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorCredentialNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1javaScriptAppBoundDomain/title",
          "value": "WKErrorJavaScriptAppBoundDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1javaScriptAppBoundDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorJavaScriptAppBoundDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1contentRuleListStoreCompileFailed/title",
          "value": "WKErrorContentRuleListStoreCompileFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1contentRuleListStoreCompileFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorContentRuleListStoreCompileFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1javaScriptExceptionOccurred/title",
          "value": "WKErrorJavaScriptExceptionOccurred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1javaScriptExceptionOccurred/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorJavaScriptExceptionOccurred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1javaScriptResultTypeIsUnsupported/title",
          "value": "WKErrorJavaScriptResultTypeIsUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1javaScriptResultTypeIsUnsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorJavaScriptResultTypeIsUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1contentRuleListStoreVersionMismatch/title",
          "value": "WKErrorContentRuleListStoreVersionMismatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1contentRuleListStoreVersionMismatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorContentRuleListStoreVersionMismatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1duplicateCredential/title",
          "value": "WKErrorDuplicateCredential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1duplicateCredential/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorDuplicateCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1attributedStringContentLoadTimedOut/title",
          "value": "WKErrorAttributedStringContentLoadTimedOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1attributedStringContentLoadTimedOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorAttributedStringContentLoadTimedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1webContentProcessTerminated/title",
          "value": "WKErrorWebContentProcessTerminated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1webContentProcessTerminated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorWebContentProcessTerminated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1navigationAppBoundDomain/title",
          "value": "WKErrorNavigationAppBoundDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1navigationAppBoundDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorNavigationAppBoundDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1webViewInvalidated/title",
          "value": "WKErrorWebViewInvalidated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code~1webViewInvalidated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorWebViewInvalidated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code/title",
          "value": "WKErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkerror/code/webcontentprocessterminated"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkerror/code/webcontentprocessterminated"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
