{
  "abstract": [
    {
      "text": "The system can’t open the file because it’s in an unrecognized format.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/fileFormatNotRecognized"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC7AVErrorLeV23fileFormatNotRecognizedSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "fileFormatNotRecognized"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC7AVErrorLeV",
        "text": "AVError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AVError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "fileFormatNotRecognized"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "fileFormatNotRecognized"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC7AVErrorLeV",
              "text": "AVError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AVError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that defines the errors that framework operations can generate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVError"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVError"
        }
      ],
      "role": "symbol",
      "title": "AVError",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code": {
      "abstract": [
        {
          "text": "An enumeration that defines the errors that framework operations can generate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "AVError.Code",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/code"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/airPlayControllerRequiresInternet": {
      "abstract": [
        {
          "text": "The AirPlay controller requires an internet connection to function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "airPlayControllerRequiresInternet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7AVErrorLeV",
          "text": "AVError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/airPlayControllerRequiresInternet",
      "kind": "symbol",
      "role": "symbol",
      "title": "airPlayControllerRequiresInternet",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/airplaycontrollerrequiresinternet"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/airPlayReceiverRequiresInternet": {
      "abstract": [
        {
          "text": "The AirPlay receiver requires an internet connection to function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "airPlayReceiverRequiresInternet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7AVErrorLeV",
          "text": "AVError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/airPlayReceiverRequiresInternet",
      "kind": "symbol",
      "role": "symbol",
      "title": "airPlayReceiverRequiresInternet",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/airplayreceiverrequiresinternet"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/airPlayReceiverTemporarilyUnavailable": {
      "abstract": [
        {
          "text": "An AirPlay receiver is temporarily unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "airPlayReceiverTemporarilyUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7AVErrorLeV",
          "text": "AVError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/airPlayReceiverTemporarilyUnavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "airPlayReceiverTemporarilyUnavailable",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/airplayreceivertemporarilyunavailable"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/applicationIsNotAuthorized": {
      "abstract": [
        {
          "text": "The app isn’t authorized to play media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationIsNotAuthorized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7AVErrorLeV",
          "text": "AVError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/applicationIsNotAuthorized",
      "kind": "symbol",
      "role": "symbol",
      "title": "applicationIsNotAuthorized",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/applicationisnotauthorized"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/applicationIsNotAuthorizedToUseDevice": {
      "abstract": [
        {
          "text": "The user denied this app permission to capture media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationIsNotAuthorizedToUseDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7AVErrorLeV",
          "text": "AVError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/applicationIsNotAuthorizedToUseDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "applicationIsNotAuthorizedToUseDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/applicationisnotauthorizedtousedevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/compositionTrackSegmentsNotContiguous": {
      "abstract": [
        {
          "text": "The composition can’t add the source media because it contains gaps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compositionTrackSegmentsNotContiguous"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7AVErrorLeV",
          "text": "AVError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/compositionTrackSegmentsNotContiguous",
      "kind": "symbol",
      "role": "symbol",
      "title": "compositionTrackSegmentsNotContiguous",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/compositiontracksegmentsnotcontiguous"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/contentIsNotAuthorized": {
      "abstract": [
        {
          "text": "The user isn’t authorized to play the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentIsNotAuthorized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7AVErrorLeV",
          "text": "AVError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/contentIsNotAuthorized",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentIsNotAuthorized",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/contentisnotauthorized"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/contentIsProtected": {
      "abstract": [
        {
          "text": "The app isn’t authorized to open the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentIsProtected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7AVErrorLeV",
          "text": "AVError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/contentIsProtected",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentIsProtected",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/contentisprotected"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/contentIsUnavailable": {
      "abstract": [
        {
          "text": "The captured content is unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentIsUnavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7AVErrorLeV",
          "text": "AVError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/contentIsUnavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentIsUnavailable",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/contentisunavailable"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/contentKeyRequestCancelled": {
      "abstract": [
        {
          "text": "The app canceled a request to retrieve a content key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentKeyRequestCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7AVErrorLeV",
          "text": "AVError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/contentKeyRequestCancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentKeyRequestCancelled",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/contentkeyrequestcancelled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/contentNotUpdated": {
      "abstract": [
        {
          "text": "The system couldn’t update the captured content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentNotUpdated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7AVErrorLeV",
          "text": "AVError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/contentNotUpdated",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentNotUpdated",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/contentnotupdated"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/createContentKeyRequestFailed": {
      "abstract": [
        {
          "text": "The app couldn’t create a content key request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createContentKeyRequestFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7AVErrorLeV",
          "text": "AVError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/createContentKeyRequestFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "createContentKeyRequestFailed",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/createcontentkeyrequestfailed"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/decodeFailed": {
      "abstract": [
        {
          "text": "The system failed to decode the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decodeFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7AVErrorLeV",
          "text": "AVError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/decodeFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "decodeFailed",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/decodefailed"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/decoderNotFound": {
      "abstract": [
        {
          "text": "The system can’t find a suitable decoder for the media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decoderNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7AVErrorLeV",
          "text": "AVError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/decoderNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "decoderNotFound",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/decodernotfound"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/fileFormatNotRecognized": {
      "abstract": [
        {
          "text": "The system can’t open the file because it’s in an unrecognized format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileFormatNotRecognized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC7AVErrorLeV",
          "text": "AVError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/fileFormatNotRecognized",
      "kind": "symbol",
      "role": "symbol",
      "title": "fileFormatNotRecognized",
      "type": "topic",
      "url": "/documentation/avfoundation/averror-swift.struct/fileformatnotrecognized"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/Code",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/airPlayControllerRequiresInternet",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/airPlayReceiverRequiresInternet",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/airPlayReceiverTemporarilyUnavailable",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/applicationIsNotAuthorized",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/applicationIsNotAuthorizedToUseDevice",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/compositionTrackSegmentsNotContiguous",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/contentIsNotAuthorized",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/contentIsProtected",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/contentIsUnavailable",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/contentKeyRequestCancelled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/contentNotUpdated",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/createContentKeyRequestFailed",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/decodeFailed",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVError-swift.struct/decoderNotFound"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/title",
          "value": "AVError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/averror-swift.struct/fileformatnotrecognized"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
