{
  "abstract": [
    {
      "text": "Continue the deselection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectNow"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSPreferencePaneUnselectReply@NSUnselectNow",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unselectNow"
      }
    ],
    "modules": [
      {
        "name": "Preference Panes"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSUnselectNow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.1",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSPreferencePaneUnselectReply.unselectNow"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unselectNow"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes": {
      "abstract": [
        {
          "text": "Integrate your app’s custom preferences into the System Preferences app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes",
      "kind": "symbol",
      "role": "collection",
      "title": "Preference Panes",
      "type": "topic",
      "url": "/documentation/preferencepanes"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/reply(toShouldUnselect:)": {
      "abstract": [
        {
          "text": "Notifies the main application of the preference pane’s ability to be deselected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reply"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toShouldUnselect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/reply(toShouldUnselect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replyToShouldUnselect:"
        }
      ],
      "role": "symbol",
      "title": "reply(toShouldUnselect:)",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepane/reply(toshouldunselect:)"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply": {
      "abstract": [
        {
          "text": "Constants that indicate the preference pane’s availability to be deselected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPreferencePaneUnselectReply"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPreferencePaneUnselectReply"
        }
      ],
      "role": "symbol",
      "title": "NSPreferencePaneUnselectReply",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepaneunselectreply"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectCancel": {
      "abstract": [
        {
          "text": "Cancel the deselection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unselectCancel"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectCancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnselectCancel"
        }
      ],
      "role": "symbol",
      "title": "NSPreferencePaneUnselectReply.unselectCancel",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepaneunselectreply/unselectcancel"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectLater": {
      "abstract": [
        {
          "text": "Delay the deselection until the preference pane invokes ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePane/reply(toShouldUnselect:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unselectLater"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectLater",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnselectLater"
        }
      ],
      "role": "symbol",
      "title": "NSPreferencePaneUnselectReply.unselectLater",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepaneunselectreply/unselectlater"
    },
    "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectNow": {
      "abstract": [
        {
          "text": "Continue the deselection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unselectNow"
        }
      ],
      "identifier": "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectNow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnselectNow"
        }
      ],
      "role": "symbol",
      "title": "NSPreferencePaneUnselectReply.unselectNow",
      "type": "topic",
      "url": "/documentation/preferencepanes/nspreferencepaneunselectreply/unselectnow"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Replies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectCancel",
        "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectLater"
      ],
      "title": "Replies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.1",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSUnselectNow"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnselectNow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.preferencepanes/documentation/PreferencePanes",
                "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Replies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectCancel",
                "doc://com.apple.preferencepanes/documentation/PreferencePanes/NSPreferencePaneUnselectReply/unselectLater"
              ],
              "title": "Replies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSUnselectNow"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply~1unselectLater/title",
          "value": "NSUnselectLater"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply~1unselectLater/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnselectLater"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply~1unselectNow/title",
          "value": "NSUnselectNow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply~1unselectNow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnselectNow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply/title",
          "value": "NSPreferencePaneUnselectReply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPreferencePaneUnselectReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPreferencePaneUnselectReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1reply(toShouldUnselect:)/title",
          "value": "replyToShouldUnselect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePane~1reply(toShouldUnselect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replyToShouldUnselect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply~1unselectCancel/title",
          "value": "NSUnselectCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.preferencepanes~1documentation~1PreferencePanes~1NSPreferencePaneUnselectReply~1unselectCancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnselectCancel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/preferencepanes/nspreferencepaneunselectreply/unselectnow"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/preferencepanes/nspreferencepaneunselectreply/unselectnow"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
