{
  "abstract": [
    {
      "text": "Prevents the system from showing the message normally, filtered as an Orders (eCommerce) message.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.identitylookup/documentation/IdentityLookup",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalOrders"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ILMessageFilterSubAction@ILMessageFilterSubActionTransactionalOrders",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "transactionalOrders"
      }
    ],
    "modules": [
      {
        "name": "SMS and Call Reporting"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ILMessageFilterSubActionTransactionalOrders"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ILMessageFilterSubAction.transactionalOrders"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "transactionalOrders"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup": {
      "abstract": [
        {
          "text": "Create app extensions to manage and report unwanted SMS messages and spam calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup",
      "kind": "symbol",
      "role": "collection",
      "title": "SMS and Call Reporting",
      "type": "topic",
      "url": "/documentation/identitylookup"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction": {
      "abstract": [
        {
          "text": "Responds to a received message with a filter subaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ILMessageFilterSubAction"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterSubAction"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterSubAction",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltersubaction"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/none": {
      "abstract": [
        {
          "text": "Allows the system to show the message unfiltered due to insufficient information to determine an action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterSubActionNone"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterSubAction.none",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltersubaction/none"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalCarrier": {
      "abstract": [
        {
          "text": "Prevents the system from showing the message normally, filtered as a Carrier message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transactionalCarrier"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalCarrier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterSubActionTransactionalCarrier"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterSubAction.transactionalCarrier",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltersubaction/transactionalcarrier"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalFinance": {
      "abstract": [
        {
          "text": "Prevents the system from showing the message normally, filtered as a Finance message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transactionalFinance"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalFinance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterSubActionTransactionalFinance"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterSubAction.transactionalFinance",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltersubaction/transactionalfinance"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalHealth": {
      "abstract": [
        {
          "text": "Prevents the system from showing the message normally, filtered as a Health message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transactionalHealth"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalHealth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterSubActionTransactionalHealth"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterSubAction.transactionalHealth",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltersubaction/transactionalhealth"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalOrders": {
      "abstract": [
        {
          "text": "Prevents the system from showing the message normally, filtered as an Orders (eCommerce) message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transactionalOrders"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalOrders",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterSubActionTransactionalOrders"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterSubAction.transactionalOrders",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltersubaction/transactionalorders"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalOthers": {
      "abstract": [
        {
          "text": "Prevents the system from showing the message normally, filtered as an Others message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transactionalOthers"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalOthers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterSubActionTransactionalOthers"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterSubAction.transactionalOthers",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltersubaction/transactionalothers"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalPublicServices": {
      "abstract": [
        {
          "text": "Prevents the system from showing the message normally, filtered as a Government message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transactionalPublicServices"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalPublicServices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterSubActionTransactionalPublicServices"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterSubAction.transactionalPublicServices",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltersubaction/transactionalpublicservices"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalReminders": {
      "abstract": [
        {
          "text": "Prevents the system from showing the message normally, filtered as a Reminder message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transactionalReminders"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalReminders",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterSubActionTransactionalReminders"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterSubAction.transactionalReminders",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltersubaction/transactionalreminders"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalRewards": {
      "abstract": [
        {
          "text": "Prevents the system from showing the message normally, filtered as a Rewards message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transactionalRewards"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalRewards",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterSubActionTransactionalRewards"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterSubAction.transactionalRewards",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltersubaction/transactionalrewards"
    },
    "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalWeather": {
      "abstract": [
        {
          "text": "Prevents the system from showing the message normally, filtered as a Weather message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transactionalWeather"
        }
      ],
      "identifier": "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalWeather",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ILMessageFilterSubActionTransactionalWeather"
        }
      ],
      "role": "symbol",
      "title": "ILMessageFilterSubAction.transactionalWeather",
      "type": "topic",
      "url": "/documentation/identitylookup/ilmessagefiltersubaction/transactionalweather"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Transactional-Subactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/none",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalOthers",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalFinance",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalReminders",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalHealth",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalWeather",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalCarrier",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalRewards",
        "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalPublicServices"
      ],
      "title": "Transactional Subactions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ILMessageFilterSubActionTransactionalOrders"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterSubActionTransactionalOrders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.identitylookup/documentation/IdentityLookup",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Transactional-Subactions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/none",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalOthers",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalFinance",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalReminders",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalHealth",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalWeather",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalCarrier",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalRewards",
                "doc://com.apple.identitylookup/documentation/IdentityLookup/ILMessageFilterSubAction/transactionalPublicServices"
              ],
              "title": "Transactional Subactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ILMessageFilterSubActionTransactionalOrders"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction/title",
          "value": "ILMessageFilterSubAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterSubAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterSubAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalWeather/title",
          "value": "ILMessageFilterSubActionTransactionalWeather"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalWeather/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterSubActionTransactionalWeather"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalReminders/title",
          "value": "ILMessageFilterSubActionTransactionalReminders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalReminders/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterSubActionTransactionalReminders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalRewards/title",
          "value": "ILMessageFilterSubActionTransactionalRewards"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalRewards/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterSubActionTransactionalRewards"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalOthers/title",
          "value": "ILMessageFilterSubActionTransactionalOthers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalOthers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterSubActionTransactionalOthers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalPublicServices/title",
          "value": "ILMessageFilterSubActionTransactionalPublicServices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalPublicServices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterSubActionTransactionalPublicServices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalFinance/title",
          "value": "ILMessageFilterSubActionTransactionalFinance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalFinance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterSubActionTransactionalFinance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalOrders/title",
          "value": "ILMessageFilterSubActionTransactionalOrders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalOrders/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterSubActionTransactionalOrders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1none/title",
          "value": "ILMessageFilterSubActionNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterSubActionNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalCarrier/title",
          "value": "ILMessageFilterSubActionTransactionalCarrier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalCarrier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterSubActionTransactionalCarrier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalHealth/title",
          "value": "ILMessageFilterSubActionTransactionalHealth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.identitylookup~1documentation~1IdentityLookup~1ILMessageFilterSubAction~1transactionalHealth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ILMessageFilterSubActionTransactionalHealth"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/identitylookup/ilmessagefiltersubaction/transactionalorders"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/identitylookup/ilmessagefiltersubaction/transactionalorders"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
