{
  "abstract": [
    {
      "text": "The parent index for each joint.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition/parentIndices-82iw2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ARSkeletonDefinition(py)parentIndices",
    "fragments": [
      {
        "kind": "identifier",
        "text": "parentIndices"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "parentIndices"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "parentIndices"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<NSNumber *>"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "parentIndices"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property may be used to identify the hierarchical dependency between joints. If a line is drawn for every joint and its parent joint, the result is a visualization of the underlying skeleton. The joint with no parent is denoted as the root joint. The root joint’s parent index is -1.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition": {
      "abstract": [
        {
          "text": "The hierarchy of joints and their names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSkeletonDefinition"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSkeletonDefinition"
        }
      ],
      "role": "symbol",
      "title": "ARSkeletonDefinition",
      "type": "topic",
      "url": "/documentation/arkit/arskeletondefinition"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition/indexForJointName:": {
      "abstract": [
        {
          "text": "Returns the index for a given joint identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "indexForJointName:"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition/indexForJointName:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexForJointName:"
        }
      ],
      "role": "symbol",
      "title": "indexForJointName:",
      "type": "topic",
      "url": "/documentation/arkit/arskeletondefinition/indexforjointname:"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition/jointCount": {
      "abstract": [
        {
          "text": "The skeleton’s total number of joints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jointCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition/jointCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "jointCount"
        }
      ],
      "role": "symbol",
      "title": "jointCount",
      "type": "topic",
      "url": "/documentation/arkit/arskeletondefinition/jointcount"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition/jointNames": {
      "abstract": [
        {
          "text": "A collection of unique joint names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jointNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition/jointNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "jointNames"
        }
      ],
      "role": "symbol",
      "title": "jointNames",
      "type": "topic",
      "url": "/documentation/arkit/arskeletondefinition/jointnames"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition/parentIndices-82iw2": {
      "abstract": [
        {
          "text": "The parent index for each joint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "parentIndices"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition/parentIndices-82iw2",
      "kind": "symbol",
      "role": "symbol",
      "title": "parentIndices",
      "type": "topic",
      "url": "/documentation/arkit/arskeletondefinition/parentindices-82iw2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Joint-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition/jointNames",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition/jointCount",
        "doc://com.apple.arkit/documentation/ARKit/ARSkeletonDefinition/indexForJointName:"
      ],
      "title": "Getting Joint Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeletonDefinition~1jointNames/title",
          "value": "jointNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeletonDefinition~1jointNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "jointNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeletonDefinition~1jointCount/title",
          "value": "jointCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeletonDefinition~1jointCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "jointCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeletonDefinition/title",
          "value": "ARSkeletonDefinition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeletonDefinition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonDefinition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSkeletonDefinition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSkeletonDefinition"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arskeletondefinition/parentindices-82iw2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
