{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alignmentRect","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"inlineContent":[{"text":"Alignment rectangles specify baselines that you can use to position the content of an image more accurately. These baselines are merely hints that your own code can use to determine positioning. The ","type":"text"},{"code":"NSImage","type":"codeVoice"},{"text":" class does not use this rectangle during drawing; however, instances of ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell","isActive":true,"type":"reference"},{"text":" typically use this information when laying out images within their boundaries.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"For example, if you have a 20 x 20 pixel icon that includes a glow effect, you might set the alignment rectangle to ","type":"text"},{"code":"{{2, 2}, {16, 16}}","type":"codeVoice"},{"text":" to indicate the position of the underlying icon without the glow effect. This property defaults to a rectangle with an origin of ","type":"text"},{"code":"{0, 0}","type":"codeVoice"},{"text":" and a size that matches the size of the image.","type":"text"}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSImage/alignmentRect"},"kind":"symbol","abstract":[{"text":"A rectangle that you can use to position the image during layout.","type":"text"}],"metadata":{"platforms":[{"unavailable":false,"name":"macOS","beta":false,"deprecated":false,"introducedAt":"10.5"}],"symbolKind":"property","modules":[{"name":"AppKit"}],"title":"alignmentRect","externalID":"c:objc(cs)NSImage(py)alignmentRect","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"alignmentRect"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier","text":"NSRect"}],"navigatorTitle":[{"kind":"identifier","text":"alignmentRect"}],"roleHeading":"Instance Property"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsimage/alignmentrect"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsimage/alignmentrect"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSImage"]]},"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSImage/alignmentRect":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alignmentRect"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier","text":"NSRect"}],"abstract":[{"text":"A rectangle that you can use to position the image during layout.","type":"text"}],"title":"alignmentRect","navigatorTitle":[{"kind":"identifier","text":"alignmentRect"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/alignmentRect","url":"/documentation/appkit/nsimage/alignmentrect"},"doc://com.apple.appkit/documentation/AppKit/NSCell":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell","abstract":[{"type":"text","text":"A mechanism for displaying text or images in a view object without the overhead of a full "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView"},{"type":"text","text":" subclass."}],"role":"symbol","navigatorTitle":[{"text":"NSCell","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCell","kind":"identifier"}],"title":"NSCell","kind":"symbol","url":"/documentation/appkit/nscell","type":"topic"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSImage":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage","url":"/documentation/appkit/nsimage","navigatorTitle":[{"text":"NSImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSImage","kind":"identifier"}],"type":"topic","title":"NSImage","role":"symbol","abstract":[{"text":"A high-level interface for manipulating image data.","type":"text"}]},"doc://com.externally.resolved.symbol/c:@T@NSRect":{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","role":"symbol","type":"topic","url":"/documentation/foundation/nsrect","abstract":[{"text":"A rectangle.","type":"text"}],"fragments":[{"text":"typealias ","kind":"text"},{"text":"NSRect","kind":"identifier"}],"title":"NSRect","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSView":{"abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"url":"/documentation/appkit/nsview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","title":"NSView","navigatorTitle":[{"kind":"identifier","text":"NSView"}],"type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"name":"macOS","introducedAt":"10.5","deprecated":false,"beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Property"},{"path":"/metadata/title","op":"replace","value":"alignmentRect"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"alignmentRect","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSImage"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"alignmentRect","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1alignmentRect/title","value":"alignmentRect"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1alignmentRect/fragments","value":[{"text":"alignmentRect","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/title","value":"NSCell"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/fragments","value":[{"kind":"identifier","text":"NSCell"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/navigatorTitle","value":[{"text":"NSCell","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/title","value":"NSImage","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/fragments","value":[{"kind":"identifier","text":"NSImage"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/navigatorTitle","value":[{"kind":"identifier","text":"NSImage"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title","value":"NSView","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments","value":[{"kind":"identifier","text":"NSView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle","value":[{"text":"NSView","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}