{"variants":[{"paths":["/documentation/appkit/nsimage/cachemode-swift.enum"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsimage/cachemode-swift.enum"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSImage"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","topicSections":[{"title":"Cache Options","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/default","doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/always","doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/bySize","doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/never"],"anchor":"Cache-Options"},{"title":"Initializers","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/init(rawValue:)"],"anchor":"Initializers"}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"],"kind":"relationships"}],"sections":[],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheMode"}],"role":"symbol","roleHeading":"Enumeration","modules":[{"name":"AppKit"}],"platforms":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"title":"NSImage.CacheMode","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"CacheMode"}],"extendedModule":"AppKit","externalID":"c:@E@NSImageCacheMode"},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Constants that specify the caching policy on a per-image basis."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheMode"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"inlineContent":[{"text":"Set the caching policy using the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/cacheMode-swift.property","type":"reference"},{"text":" property.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The following table specifies the default caching policy for the various types of image representation."}],"type":"paragraph"},{"header":"row","type":"table","rows":[[[{"inlineContent":[{"type":"text","text":"Image Rep Class"}],"type":"paragraph"}],[{"inlineContent":[{"text":"Default caching policy","type":"text"}],"type":"paragraph"}]],[[{"inlineContent":[{"code":"NSBitmapImageRep","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"type":"codeVoice","code":"NSImageCacheBySize"},{"type":"text","text":". Cache if bitmap is 32-bits in 16-bit world or greater than 72 dpi."}],"type":"paragraph"}]],[[{"inlineContent":[{"code":"NSPICTImageRep","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"type":"codeVoice","code":"NSImageCacheBySize"},{"type":"text","text":". Same reasoning as "},{"type":"codeVoice","code":"NSBitmapImageRep"},{"type":"text","text":" in the event the PICT contains a bitmap."}],"type":"paragraph"}]],[[{"inlineContent":[{"code":"NSPDFImageRep","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"type":"codeVoice","code":"NSImageCacheAlways"}],"type":"paragraph"}]],[[{"inlineContent":[{"code":"NSCIImageRep","type":"codeVoice"}],"type":"paragraph"}],[{"inlineContent":[{"code":"NSImageCacheBySize","type":"codeVoice"},{"text":". Cache if the bitmap depth does not match the screen depth or the resolution is greater than 72 dpi.","type":"text"}],"type":"paragraph"}]],[[{"type":"paragraph","inlineContent":[{"code":"NSEPSImageRep","type":"codeVoice"}]}],[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"NSImageCacheAlways"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"NSCustomImageRep"}]}],[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"NSImageCacheAlways"}]}]]]}],"kind":"content"}],"seeAlsoSections":[{"title":"Managing Caching Options","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSImage/cacheMode-swift.property","doc://com.apple.appkit/documentation/AppKit/NSImage/recache()"],"anchor":"Managing-Caching-Options"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/always":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"always"}],"url":"/documentation/appkit/nsimage/cachemode-swift.enum/always","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/always","role":"symbol","abstract":[{"text":"Always generate a cache when drawing.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSImageCacheAlways"}],"type":"topic","title":"NSImage.CacheMode.always"},"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/never":{"url":"/documentation/appkit/nsimage/cachemode-swift.enum/never","title":"NSImage.CacheMode.never","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/never","abstract":[{"text":"Never cache; always draw direct.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"never"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSImageCacheNever"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/init(rawValue:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"url":"/documentation/appkit/nsimage/cachemode-swift.enum/init(rawvalue:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/init(rawValue:)","role":"symbol","abstract":[],"type":"topic","title":"init(rawValue:)"},"doc://com.externally.resolved.symbol/s:SY":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawRepresentable","kind":"identifier"},{"text":"<","kind":"text"},{"text":"RawValue","kind":"typeIdentifier","preciseIdentifier":"s:SY8RawValueQa"},{"text":">","kind":"text"}],"url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable","abstract":[{"text":"A type that can be converted to and from an associated raw value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:SY","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/bySize":{"url":"/documentation/appkit/nsimage/cachemode-swift.enum/bysize","title":"NSImage.CacheMode.bySize","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/bySize","abstract":[{"text":"Cache if the cache size is smaller than the original data.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bySize"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSImageCacheBySize"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSImage/cacheMode-swift.property":{"abstract":[{"text":"The image’s caching mode.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSImage","text":"NSImage"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSImageCacheMode","text":"CacheMode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cacheMode"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/cacheMode-swift.property","url":"/documentation/appkit/nsimage/cachemode-swift.property","title":"cacheMode"},"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum":{"abstract":[{"text":"Constants that specify the caching policy on a per-image basis.","type":"text"}],"type":"topic","title":"NSImage.CacheMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheMode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CacheMode"}],"url":"/documentation/appkit/nsimage/cachemode-swift.enum","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum"},"doc://com.apple.appkit/documentation/AppKit/NSImage":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage","url":"/documentation/appkit/nsimage","navigatorTitle":[{"text":"NSImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSImage","kind":"identifier"}],"type":"topic","title":"NSImage","role":"symbol","abstract":[{"text":"A high-level interface for manipulating image data.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/default":{"abstract":[{"text":"Caching is unspecified.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`default`","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"NSImageCacheDefault","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/default","url":"/documentation/appkit/nsimage/cachemode-swift.enum/default","title":"NSImage.CacheMode.default"},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"abstract":[{"type":"text","text":"Describes an unsigned integer."}],"url":"/documentation/objectivec/nsuinteger","kind":"symbol","role":"symbol","title":"NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","type":"topic"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","role":"symbol","type":"topic","url":"/documentation/Swift/Sendable","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"title":"Sendable","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:SH":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"title":"Hashable"},"doc://com.apple.appkit/documentation/AppKit/NSImage/recache()":{"abstract":[{"text":"Invalidates and frees offscreen caches of all image representations.","type":"text"}],"type":"topic","title":"recache()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recache"},{"kind":"text","text":"()"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"recache"}],"url":"/documentation/appkit/nsimage/recache()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/recache()"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"type":"topic","title":"Equatable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","role":"symbol","url":"/documentation/Swift/Equatable"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","title":"BitwiseCopyable","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","type":"topic","abstract":[{"text":"","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"name":"macOS","beta":false,"deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration"},{"path":"/metadata/title","op":"replace","value":"NSImageCacheMode"},{"path":"/metadata/symbolKind","op":"replace","value":"enum"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"NSImageCacheMode"}]},{"path":"/metadata/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSImageCacheMode"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit"]]}},{"path":"/topicSections","op":"replace","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/default","doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/always","doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/bySize","doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/never"],"anchor":"Cache-Options","title":"Cache Options"}]},{"path":"/relationshipsSections","op":"replace","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Managing Caching Options","generated":true,"anchor":"Managing-Caching-Options","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSImage/cacheMode-swift.property","doc://com.apple.appkit/documentation/AppKit/NSImage/recache()"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSImageCacheMode"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum~1always/title","op":"replace","value":"NSImageCacheAlways"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum~1always/fragments","op":"replace","value":[{"text":"NSImageCacheAlways","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum~1never/title","op":"replace","value":"NSImageCacheNever"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum~1never/fragments","op":"replace","value":[{"kind":"identifier","text":"NSImageCacheNever"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum~1bySize/title","op":"replace","value":"NSImageCacheBySize"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum~1bySize/fragments","op":"replace","value":[{"text":"NSImageCacheBySize","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1cacheMode-swift.property/title","op":"replace","value":"cacheMode"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1cacheMode-swift.property/fragments","op":"replace","value":[{"text":"cacheMode","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum/title","op":"replace","value":"NSImageCacheMode"},{"op":"replace","value":[{"text":"NSImageCacheMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSImageCacheMode"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum/navigatorTitle"},{"op":"replace","value":"NSImage","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/title"},{"op":"replace","value":[{"text":"NSImage","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/fragments"},{"op":"replace","value":[{"text":"NSImage","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/navigatorTitle"},{"op":"replace","value":"NSImageCacheDefault","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum~1default/title"},{"op":"replace","value":[{"text":"NSImageCacheDefault","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum~1default/fragments"},{"op":"replace","value":"recache","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1recache()/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"recache","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1recache()/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}