{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSImage/cacheMode-swift.property","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSImage"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsimage/cachemode-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsimage/cachemode-swift.property"]}],"metadata":{"externalID":"c:objc(cs)NSImage(py)cacheMode","navigatorTitle":[{"text":"cacheMode","kind":"identifier"}],"role":"symbol","modules":[{"name":"AppKit"}],"platforms":[{"deprecated":false,"unavailable":false,"name":"macOS","beta":false}],"title":"cacheMode","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cacheMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSImage"},{"text":".","kind":"text"},{"text":"CacheMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSImageCacheMode"}],"roleHeading":"Instance Property"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage","preciseIdentifier":"c:objc(cs)NSImage","text":"NSImage"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum","preciseIdentifier":"c:@E@NSImageCacheMode","text":"CacheMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["macOS"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"Discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"The caching mode determines when the image representations use offscreen caches. Offscreen caches speed up rendering time but do so by using extra memory. In the default caching mode ("},{"code":"NSImageCacheDefault","type":"codeVoice"},{"type":"text","text":"), each image representation chooses the caching technique that produces the fastest drawing times. For example, in the default mode, the "},{"code":"NSPDFImageRep","type":"codeVoice"},{"type":"text","text":" and "},{"code":"NSEPSImageRep","type":"codeVoice"},{"type":"text","text":" classes use the "},{"code":"NSImageCacheAlways","type":"codeVoice"},{"text":" mode but the ","type":"text"},{"code":"NSBitmapImageRep","type":"codeVoice"},{"text":" class uses the ","type":"text"},{"code":"NSImageCacheBySize","type":"codeVoice"},{"text":" mode.  For a list of possible values, see ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum","type":"reference"},{"text":". This value is set to ","type":"text"},{"code":"NSImageCacheDefault","type":"codeVoice"},{"text":" by default.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"For more information on image caching behavior, see the "},{"type":"reference","identifier":"https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Images/Images.html#//apple_ref/doc/uid/TP40003290-CH208","isActive":true},{"type":"text","text":" chapter of "},{"type":"reference","identifier":"https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40003290","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"title":"Managing Caching Options","anchor":"Managing-Caching-Options","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSImage/recache()","doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum"]}],"abstract":[{"text":"The image’s caching mode.","type":"text"}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSImage":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage","url":"/documentation/appkit/nsimage","navigatorTitle":[{"text":"NSImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSImage","kind":"identifier"}],"type":"topic","title":"NSImage","role":"symbol","abstract":[{"text":"A high-level interface for manipulating image data.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSImage/cacheMode-swift.property":{"abstract":[{"text":"The image’s caching mode.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSImage","text":"NSImage"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSImageCacheMode","text":"CacheMode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cacheMode"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/cacheMode-swift.property","url":"/documentation/appkit/nsimage/cachemode-swift.property","title":"cacheMode"},"https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40003290":{"identifier":"https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40003290","type":"link","url":"https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40003290","titleInlineContent":[{"text":"Cocoa Drawing Guide","type":"text"}],"title":"Cocoa Drawing Guide"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum":{"abstract":[{"text":"Constants that specify the caching policy on a per-image basis.","type":"text"}],"type":"topic","title":"NSImage.CacheMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheMode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CacheMode"}],"url":"/documentation/appkit/nsimage/cachemode-swift.enum","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum"},"doc://com.apple.appkit/documentation/AppKit/NSImage/recache()":{"abstract":[{"text":"Invalidates and frees offscreen caches of all image representations.","type":"text"}],"type":"topic","title":"recache()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recache"},{"kind":"text","text":"()"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"recache"}],"url":"/documentation/appkit/nsimage/recache()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/recache()"},"https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Images/Images.html#//apple_ref/doc/uid/TP40003290-CH208":{"identifier":"https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Images/Images.html#//apple_ref/doc/uid/TP40003290-CH208","type":"link","url":"https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Images/Images.html#//apple_ref/doc/uid/TP40003290-CH208","titleInlineContent":[{"text":"Images","type":"text"}],"title":"Images"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"name":"macOS","beta":false,"deprecated":false}]},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"cacheMode","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"cacheMode"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSImage"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"anchor":"Managing-Caching-Options","title":"Managing Caching Options","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSImage/recache()","doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSImageCacheMode","text":"NSImageCacheMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheMode"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/title","value":"NSImage"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/fragments","value":[{"kind":"identifier","text":"NSImage"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/navigatorTitle","value":[{"kind":"identifier","text":"NSImage"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1cacheMode-swift.property/title","value":"cacheMode"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1cacheMode-swift.property/fragments","value":[{"kind":"identifier","text":"cacheMode"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum/title","value":"NSImageCacheMode"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum/fragments","value":[{"text":"NSImageCacheMode","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum/navigatorTitle","value":[{"kind":"identifier","text":"NSImageCacheMode"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1recache()/title","value":"recache"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1recache()/fragments","value":[{"text":"- ","kind":"text"},{"text":"recache","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}