{
  "abstract": [
    {
      "text": "An exit full-screen mode template image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSImage"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSImage/exitFullScreenTemplateName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSImageNameExitFullScreenTemplate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "exitFullScreenTemplateName"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSImageNameExitFullScreenTemplate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "exitFullScreenTemplateName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "exitFullScreenTemplateName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage": {
      "abstract": [
        {
          "text": "A high-level interface for manipulating image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "role": "symbol",
      "title": "NSImage",
      "type": "topic",
      "url": "/documentation/appkit/nsimage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/Name-swift.typealias": {
      "abstract": [
        {
          "text": "Named images, defined by the system or you, for use in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/Name-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "role": "symbol",
      "title": "NSImage.Name",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/name-swift.typealias"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/actionTemplateName": {
      "abstract": [
        {
          "text": "An action menu template image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/actionTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameActionTemplate"
        }
      ],
      "role": "symbol",
      "title": "actionTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/actiontemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/addTemplateName": {
      "abstract": [
        {
          "text": "An add item template image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/addTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameAddTemplate"
        }
      ],
      "role": "symbol",
      "title": "addTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/addtemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/advancedName": {
      "abstract": [
        {
          "text": "Advanced preferences toolbar icon for the preferences window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "advancedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/advancedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameAdvanced"
        }
      ],
      "role": "symbol",
      "title": "advancedName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/advancedname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/applicationIconName": {
      "abstract": [
        {
          "text": "The app’s icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationIconName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/applicationIconName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameApplicationIcon"
        }
      ],
      "role": "symbol",
      "title": "applicationIconName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/applicationiconname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/bluetoothTemplateName": {
      "abstract": [
        {
          "text": "A Bluetooth template image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bluetoothTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/bluetoothTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameBluetoothTemplate"
        }
      ],
      "role": "symbol",
      "title": "bluetoothTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/bluetoothtemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/bonjourName": {
      "abstract": [
        {
          "text": "A Bonjour icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bonjourName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/bonjourName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameBonjour"
        }
      ],
      "role": "symbol",
      "title": "bonjourName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/bonjourname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/bookmarksTemplateName": {
      "abstract": [
        {
          "text": "Bookmarks image suitable for a template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bookmarksTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/bookmarksTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameBookmarksTemplate"
        }
      ],
      "role": "symbol",
      "title": "bookmarksTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/bookmarkstemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/cautionName": {
      "abstract": [
        {
          "text": "A caution image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cautionName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/cautionName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameCaution"
        }
      ],
      "role": "symbol",
      "title": "cautionName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/cautionname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/colorPanelName": {
      "abstract": [
        {
          "text": "A color panel toolbar icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorPanelName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/colorPanelName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameColorPanel"
        }
      ],
      "role": "symbol",
      "title": "colorPanelName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/colorpanelname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/columnViewTemplateName": {
      "abstract": [
        {
          "text": "A column view mode template image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "columnViewTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/columnViewTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameColumnViewTemplate"
        }
      ],
      "role": "symbol",
      "title": "columnViewTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/columnviewtemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/computerName": {
      "abstract": [
        {
          "text": "A computer icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "computerName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/computerName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameComputer"
        }
      ],
      "role": "symbol",
      "title": "computerName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/computername"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/enterFullScreenTemplateName": {
      "abstract": [
        {
          "text": "An enter full-screen mode template image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enterFullScreenTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/enterFullScreenTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameEnterFullScreenTemplate"
        }
      ],
      "role": "symbol",
      "title": "enterFullScreenTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/enterfullscreentemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/everyoneName": {
      "abstract": [
        {
          "text": "Permissions for all users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "everyoneName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/everyoneName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameEveryone"
        }
      ],
      "role": "symbol",
      "title": "everyoneName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/everyonename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/exitFullScreenTemplateName": {
      "abstract": [
        {
          "text": "An exit full-screen mode template image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exitFullScreenTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/exitFullScreenTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameExitFullScreenTemplate"
        }
      ],
      "role": "symbol",
      "title": "exitFullScreenTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/exitfullscreentemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/flowViewTemplateName": {
      "abstract": [
        {
          "text": "A cover flow view mode template image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flowViewTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/flowViewTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameFlowViewTemplate"
        }
      ],
      "role": "symbol",
      "title": "flowViewTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/flowviewtemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/folderName": {
      "abstract": [
        {
          "text": "A folder image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "folderName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/folderName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameFolder"
        }
      ],
      "role": "symbol",
      "title": "folderName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/foldername"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageNameDotMac": {
      "abstract": [
        {
          "text": "A Dot Mac icon.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSImageNameDotMac"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageNameDotMac",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSImageNameDotMac",
      "type": "topic",
      "url": "/documentation/appkit/nsimagenamedotmac"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "System-Images",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSImage/actionTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/addTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/advancedName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/applicationIconName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/bluetoothTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/bonjourName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/bookmarksTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/cautionName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/colorPanelName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/columnViewTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/computerName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/enterFullScreenTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/everyoneName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/flowViewTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/folderName"
      ],
      "title": "System Images"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSImageNameExitFullScreenTemplate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameExitFullScreenTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "System-Images",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSImage/actionTemplateName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/addTemplateName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/advancedName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/applicationIconName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/bluetoothTemplateName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/bonjourName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/bookmarksTemplateName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/cautionName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/colorPanelName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/columnViewTemplateName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/computerName",
                "doc://com.apple.appkit/documentation/AppKit/NSImageNameDotMac",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/enterFullScreenTemplateName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/everyoneName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/flowViewTemplateName"
              ],
              "title": "System Images"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/Name-swift.typealias",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSImageName",
                    "text": "NSImageName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSImageNameExitFullScreenTemplate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1exitFullScreenTemplateName/title",
          "value": "NSImageNameExitFullScreenTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1exitFullScreenTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameExitFullScreenTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1computerName/title",
          "value": "NSImageNameComputer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1computerName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameComputer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1advancedName/title",
          "value": "NSImageNameAdvanced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1advancedName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameAdvanced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/title",
          "value": "NSImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1bookmarksTemplateName/title",
          "value": "NSImageNameBookmarksTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1bookmarksTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameBookmarksTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1folderName/title",
          "value": "NSImageNameFolder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1folderName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameFolder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1flowViewTemplateName/title",
          "value": "NSImageNameFlowViewTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1flowViewTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameFlowViewTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1applicationIconName/title",
          "value": "NSImageNameApplicationIcon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1applicationIconName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameApplicationIcon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1colorPanelName/title",
          "value": "NSImageNameColorPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1colorPanelName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameColorPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1Name-swift.typealias/title",
          "value": "NSImageName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1Name-swift.typealias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1Name-swift.typealias/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1columnViewTemplateName/title",
          "value": "NSImageNameColumnViewTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1columnViewTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameColumnViewTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1bluetoothTemplateName/title",
          "value": "NSImageNameBluetoothTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1bluetoothTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameBluetoothTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1everyoneName/title",
          "value": "NSImageNameEveryone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1everyoneName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameEveryone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1enterFullScreenTemplateName/title",
          "value": "NSImageNameEnterFullScreenTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1enterFullScreenTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameEnterFullScreenTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1addTemplateName/title",
          "value": "NSImageNameAddTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1addTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameAddTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1actionTemplateName/title",
          "value": "NSImageNameActionTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1actionTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameActionTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1bonjourName/title",
          "value": "NSImageNameBonjour"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1bonjourName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameBonjour"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1cautionName/title",
          "value": "NSImageNameCaution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1cautionName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameCaution"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsimage/exitfullscreentemplatename"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsimage/exitfullscreentemplatename"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
