{
  "abstract": [
    {
      "text": "Returns an array of strings identifying the pasteboard types supported directly by the registered image representation objects.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use +imageTypes instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSImage"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSImage/imagePasteboardTypes()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:objc(cs)NSImage(cm)imagePasteboardTypes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "imagePasteboardTypes"
      },
      {
        "kind": "text",
        "text": "() -> ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSPasteboard",
        "text": "NSPasteboard"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSPasteboardType",
        "text": "PasteboardType"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "imagePasteboardTypes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.10",
        "introducedAt": "10.0",
        "message": "Use +imageTypes instead",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "imagePasteboardTypes()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "imagePasteboardTypes"
            },
            {
              "kind": "text",
              "text": "() -> ["
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSPasteboard",
              "text": "NSPasteboard"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSPasteboardType",
              "text": "PasteboardType"
            },
            {
              "kind": "text",
              "text": "]"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An array of ",
              "type": "text"
            },
            {
              "code": "NSString",
              "type": "codeVoice"
            },
            {
              "text": " objects, each of which identifies a single supported pasteboard type. By default, this list contains the  ",
              "type": "text"
            },
            {
              "code": "NSPDFPboardType",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "NSPICTPboardType",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "NSPostScriptPboardType",
              "type": "codeVoice"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "code": "NSTIFFPboardType",
              "type": "codeVoice"
            },
            {
              "text": " types.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This list includes all pasteboard types supported by registered subclasses of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRep",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " plus those that can be converted to a supported type by a user-installed filter service.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Do not override this method. Instead, override the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRep/imageUnfilteredPasteboardTypes()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to notify ",
              "type": "text"
            },
            {
              "code": "NSImage",
              "type": "codeVoice"
            },
            {
              "text": " of the pasteboard types your class supports.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage": {
      "abstract": [
        {
          "text": "A high-level interface for manipulating image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "role": "symbol",
      "title": "NSImage",
      "type": "topic",
      "url": "/documentation/appkit/nsimage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/imageFileTypes()": {
      "abstract": [
        {
          "text": "Returns an array of strings identifying the image types supported by the registered image representation objects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageFileTypes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/imageFileTypes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageFileTypes"
        }
      ],
      "role": "symbol",
      "title": "imageFileTypes()",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/imagefiletypes()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/imagePasteboardTypes()": {
      "abstract": [
        {
          "text": "Returns an array of strings identifying the pasteboard types supported directly by the registered image representation objects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imagePasteboardTypes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/imagePasteboardTypes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imagePasteboardTypes"
        }
      ],
      "role": "symbol",
      "title": "imagePasteboardTypes()",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/imagepasteboardtypes()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/imageUnfilteredFileTypes()": {
      "abstract": [
        {
          "text": "Returns an array of strings identifying the file types supported directly by the registered image representation objects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageUnfilteredFileTypes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/imageUnfilteredFileTypes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageUnfilteredFileTypes"
        }
      ],
      "role": "symbol",
      "title": "imageUnfilteredFileTypes()",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/imageunfilteredfiletypes()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/imageUnfilteredPasteboardTypes()": {
      "abstract": [
        {
          "text": "Returns an array of strings identifying the pasteboard types supported directly by the registered image representation objects.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageUnfilteredPasteboardTypes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/imageUnfilteredPasteboardTypes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageUnfilteredPasteboardTypes"
        }
      ],
      "role": "symbol",
      "title": "imageUnfilteredPasteboardTypes()",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/imageunfilteredpasteboardtypes()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageRep": {
      "abstract": [
        {
          "text": "A semiabstract superclass that provides subclasses that you use to draw an image from a particular type of source data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImageRep"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageRep"
        }
      ],
      "role": "symbol",
      "title": "NSImageRep",
      "type": "topic",
      "url": "/documentation/appkit/nsimagerep"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageRep/imageUnfilteredPasteboardTypes()": {
      "abstract": [
        {
          "text": "Returns the list of pasteboard types supported directly by the image representation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageUnfilteredPasteboardTypes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageRep/imageUnfilteredPasteboardTypes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageUnfilteredPasteboardTypes"
        }
      ],
      "role": "symbol",
      "title": "imageUnfilteredPasteboardTypes()",
      "type": "topic",
      "url": "/documentation/appkit/nsimagerep/imageunfilteredpasteboardtypes()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard": {
      "abstract": [
        {
          "text": "An object that transfers data to and from the pasteboard server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPasteboard"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboard"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboard",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType": {
      "abstract": [
        {
          "text": "The supported pasteboard types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PasteboardType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PasteboardType"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboard.PasteboardType",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboardtype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Class-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSImage/imageFileTypes()",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/imageUnfilteredFileTypes()",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/imageUnfilteredPasteboardTypes()"
      ],
      "title": "Class Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.10",
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "imagePasteboardTypes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "imagePasteboardTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSImage"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Class-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSImage/imageFileTypes()",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/imageUnfilteredFileTypes()",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/imageUnfilteredPasteboardTypes()"
              ],
              "title": "Class Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSString *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "imagePasteboardTypes"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An array of ",
                    "type": "text"
                  },
                  {
                    "code": "NSString",
                    "type": "codeVoice"
                  },
                  {
                    "text": " objects, each of which identifies a single supported pasteboard type. By default, this list contains the  ",
                    "type": "text"
                  },
                  {
                    "code": "NSPDFPboardType",
                    "type": "codeVoice"
                  },
                  {
                    "text": ", ",
                    "type": "text"
                  },
                  {
                    "code": "NSPICTPboardType",
                    "type": "codeVoice"
                  },
                  {
                    "text": ", ",
                    "type": "text"
                  },
                  {
                    "code": "NSPostScriptPboardType",
                    "type": "codeVoice"
                  },
                  {
                    "text": ", and ",
                    "type": "text"
                  },
                  {
                    "code": "NSTIFFPboardType",
                    "type": "codeVoice"
                  },
                  {
                    "text": " types.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use +imageTypes instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/title",
          "value": "NSPasteboardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep/title",
          "value": "NSImageRep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imageUnfilteredPasteboardTypes()/title",
          "value": "imageUnfilteredPasteboardTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imageUnfilteredPasteboardTypes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "imageUnfilteredPasteboardTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/title",
          "value": "NSImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imagePasteboardTypes()/title",
          "value": "imagePasteboardTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imagePasteboardTypes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "imagePasteboardTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imageFileTypes()/title",
          "value": "imageFileTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imageFileTypes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "imageFileTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep~1imageUnfilteredPasteboardTypes()/title",
          "value": "imageUnfilteredPasteboardTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageRep~1imageUnfilteredPasteboardTypes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "imageUnfilteredPasteboardTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imageUnfilteredFileTypes()/title",
          "value": "imageUnfilteredFileTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imageUnfilteredFileTypes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "imageUnfilteredFileTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/title",
          "value": "NSPasteboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboard"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsimage/imagepasteboardtypes()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsimage/imagepasteboardtypes()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
