{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(imageLiteralResourceName:)"},"variants":[{"paths":["/documentation/appkit/nsimage/init(imageliteralresourcename:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.documentation/documentation/UIKit/configuring-and-displaying-symbol-images-in-your-ui","doc://com.apple.appkit/documentation/AppKit/NSImage/init(named:)","doc://com.apple.appkit/documentation/AppKit/NSImage/init(systemSymbolName:accessibilityDescription:)","doc://com.apple.appkit/documentation/AppKit/NSImage/init(systemSymbolName:variableValue:accessibilityDescription:)","doc://com.apple.appkit/documentation/AppKit/NSImage/init(symbolName:variableValue:)","doc://com.apple.appkit/documentation/AppKit/NSImage/init(symbolName:bundle:variableValue:)","doc://com.apple.appkit/documentation/AppKit/NSImage/init(resource:)","doc://com.apple.appkit/documentation/AppKit/NSImage/setName(_:)","doc://com.apple.appkit/documentation/AppKit/NSImage/name()","doc://com.apple.appkit/documentation/AppKit/NSImage/Name-swift.typealias"],"generated":true,"title":"Creating Images by Name","anchor":"Creating-Images-by-Name"}],"metadata":{"modules":[{"name":"AppKit"}],"platforms":[{"name":"macOS","introducedAt":"10.9","unavailable":false,"deprecated":false,"beta":false}],"fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"imageLiteralResourceName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","title":"init(imageLiteralResourceName:)","extendedModule":"AppKit","role":"symbol","externalID":"s:So7NSImageC6AppKitE24imageLiteralResourceNameABSS_tcfc","symbolKind":"init"},"abstract":[{"type":"text","text":"Creates an image initialized with the specified resource name."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSImage"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@nonobjc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"imageLiteralResourceName","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","identifier":"doc://com.externally.resolved.symbol/s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["macOS"]}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSImage/init(named:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(named:)","role":"symbol","type":"topic","url":"/documentation/appkit/nsimage/init(named:)","navigatorTitle":[{"text":"imageNamed:","kind":"identifier"}],"abstract":[{"text":"Returns the image object associated with the specified name.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"named","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSImage","text":"NSImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSImageName","text":"Name","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(named:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSImage/setName(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/setName(_:)","role":"symbol","type":"topic","url":"/documentation/appkit/nsimage/setname(_:)","navigatorTitle":[{"text":"setName:","kind":"identifier"}],"abstract":[{"text":"Registers the image object under the specified name.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setName","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSImage","text":"NSImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSImageName","text":"Name","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"setName(_:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSImage/name()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSImage"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSImageName"},{"text":"?","kind":"text"}],"title":"name()","url":"/documentation/appkit/nsimage/name()","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/name()","type":"topic","abstract":[{"text":"Returns the name associated with the image, if any.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"name","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSImage/init(systemSymbolName:variableValue:accessibilityDescription:)":{"url":"/documentation/appkit/nsimage/init(systemsymbolname:variablevalue:accessibilitydescription:)","title":"init(systemSymbolName:variableValue:accessibilityDescription:)","kind":"symbol","abstract":[{"type":"text","text":"Creates a symbol image with the system symbol name and variable value you specify."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(systemSymbolName:variableValue:accessibilityDescription:)","type":"topic","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"systemSymbolName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"variableValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessibilityDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"imageWithSystemSymbolName:variableValue:accessibilityDescription:"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSImage/init(systemSymbolName:accessibilityDescription:)":{"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"systemSymbolName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessibilityDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(systemSymbolName:accessibilityDescription:)","url":"/documentation/appkit/nsimage/init(systemsymbolname:accessibilitydescription:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(systemSymbolName:accessibilityDescription:)","type":"topic","abstract":[{"text":"Creates a symbol image with the system symbol name and accessibility description you specify.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageWithSystemSymbolName:accessibilityDescription:"}]},"doc://com.externally.resolved.symbol/s:SS":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SS","url":"/documentation/Swift/String","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String","kind":"identifier"}],"type":"topic","title":"String","role":"symbol","abstract":[{"text":"A Unicode string value that is a collection of characters.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSImage/init(symbolName:bundle:variableValue:)":{"abstract":[],"fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"symbolName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bundle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"variableValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nsimage/init(symbolname:bundle:variablevalue:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(symbolName:bundle:variableValue:)","role":"symbol","navigatorTitle":[{"text":"imageWithSymbolName:bundle:variableValue:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"init(symbolName:bundle:variableValue:)"},"doc://com.apple.appkit/documentation/AppKit/NSImage/Name-swift.typealias":{"kind":"symbol","url":"/documentation/appkit/nsimage/name-swift.typealias","title":"NSImage.Name","navigatorTitle":[{"text":"Name","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Name","kind":"identifier"}],"type":"topic","abstract":[{"text":"Named images, defined by the system or you, for use in your app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/Name-swift.typealias","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSImage":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage","url":"/documentation/appkit/nsimage","navigatorTitle":[{"text":"NSImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSImage","kind":"identifier"}],"type":"topic","title":"NSImage","role":"symbol","abstract":[{"text":"A high-level interface for manipulating image data.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSImage/init(resource:)":{"url":"/documentation/appkit/nsimage/init(resource:)","kind":"symbol","role":"symbol","type":"topic","title":"init(resource:)","abstract":[],"fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"resource"},{"kind":"text","text":": "},{"text":"ImageResource","kind":"typeIdentifier","preciseIdentifier":"s:21DeveloperToolsSupport13ImageResourceV"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(resource:)"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSImage/init(imageLiteralResourceName:)":{"title":"init(imageLiteralResourceName:)","type":"topic","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"imageLiteralResourceName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(imageLiteralResourceName:)","abstract":[{"text":"Creates an image initialized with the specified resource name.","type":"text"}],"role":"symbol","url":"/documentation/appkit/nsimage/init(imageliteralresourcename:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSImage/init(symbolName:variableValue:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(symbolName:variableValue:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageWithSymbolName:variableValue:"}],"role":"symbol","type":"topic","title":"init(symbolName:variableValue:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"symbolName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"variableValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a symbol image with the symbol name and variable value you specify."}],"url":"/documentation/appkit/nsimage/init(symbolname:variablevalue:)"},"doc://com.apple.documentation/documentation/UIKit/configuring-and-displaying-symbol-images-in-your-ui":{"title":"Configuring and displaying symbol images in your UI","url":"/documentation/UIKit/configuring-and-displaying-symbol-images-in-your-ui","role":"article","identifier":"doc://com.apple.documentation/documentation/UIKit/configuring-and-displaying-symbol-images-in-your-ui","type":"topic","abstract":[{"text":"Create scalable images that integrate with your app’s text, and adjust the appearance of those images dynamically.","type":"text"}],"kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(named:)/title","op":"replace","value":"imageNamed:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(named:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"imageNamed:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1setName(_:)/title","value":"setName:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1setName(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setName:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1name()/title","value":"name","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1name()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"name"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(systemSymbolName:variableValue:accessibilityDescription:)/title","value":"imageWithSystemSymbolName:variableValue:accessibilityDescription:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(systemSymbolName:variableValue:accessibilityDescription:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"imageWithSystemSymbolName:variableValue:accessibilityDescription:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(systemSymbolName:accessibilityDescription:)/title","value":"imageWithSystemSymbolName:accessibilityDescription:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(systemSymbolName:accessibilityDescription:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"imageWithSystemSymbolName:accessibilityDescription:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(symbolName:bundle:variableValue:)/title","op":"replace","value":"imageWithSymbolName:bundle:variableValue:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(symbolName:bundle:variableValue:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"imageWithSymbolName:bundle:variableValue:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1Name-swift.typealias/title","op":"replace","value":"NSImageName"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1Name-swift.typealias/fragments","value":[{"text":"NSImageName","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1Name-swift.typealias/navigatorTitle","value":[{"text":"NSImageName","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/title","value":"NSImage","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/fragments","value":[{"kind":"identifier","text":"NSImage"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/navigatorTitle","value":[{"kind":"identifier","text":"NSImage"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(symbolName:variableValue:)/title","value":"imageWithSymbolName:variableValue:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(symbolName:variableValue:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"imageWithSymbolName:variableValue:","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}