{"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSSize","identifier":"doc://com.externally.resolved.symbol/c:@T@NSSize","preciseIdentifier":"c:@T@NSSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"flipped"},{"kind":"text","text":" "},{"kind":"internalParam","text":"drawingHandlerShouldBeCalledWithFlippedContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"drawingHandler"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"NSRect","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"size","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The size of the image, measured in points."}]}]},{"name":"drawingHandlerShouldBeCalledWithFlippedContext","content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true,"type":"reference"},{"text":" to apply a flip transformation to the graphics context before drawing or ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true,"type":"reference"},{"text":" to draw using the default Cocoa coordinate system orientation.","type":"text"}],"type":"paragraph"}]},{"name":"drawingHandler","content":[{"inlineContent":[{"type":"text","text":"A block that draws the contents of the image representation. The image representation copies the block and stores it for later use. It is not executed until you draw the image. Because the block is executed later, AppKit executes it on the same thread on which you draw the image itself, which can be any thread of your app. Therefore, the block must be safe to call from any thread. The block takes the following parameter:"}],"type":"paragraph"},{"type":"termList","items":[{"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The destination rectangle in which to draw. The coordinates of this rectangle are specified in points."}]}]},"term":{"inlineContent":[{"type":"text","text":"dstRect"}]}}]},{"inlineContent":[{"text":"The block returns a Boolean that indicates whether it drew the image successfully. Return ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference"},{"text":" from your block if it successfully drew the contents or ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference"},{"text":" if it did not.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"An initialized "},{"code":"NSImage","type":"codeVoice"},{"type":"text","text":" object."}],"type":"paragraph"}],"kind":"content"},{"content":[{"level":2,"text":"Discussion","anchor":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Use this method to generate an image that is correct at any resolution. This method creates an image object with a single "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCustomImageRep"},{"type":"text","text":" object to manage drawing. The image representation uses the block in the "},{"code":"drawingHandler","type":"codeVoice"},{"type":"text","text":" parameter to do the actual drawing."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"When you draw the image for the first time, the underlying image representation executes the "},{"code":"drawingHandler","type":"codeVoice"},{"type":"text","text":" block. The image object caches the results according to its usual caching policies; see the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/cacheMode-swift.property"},{"type":"text","text":" property. As long as the configuration of the destination graphics context does not change in a significant way, subsequent attempts to draw the image reuse the cached results whenever possible. If the pixel density or color space of the destination graphics context changes, though, the image representation throws away any caches and executes the block again to obtain a new version of the image. For example, if you drew the image on a standard resolution display but then draw it on a Retina display, AppKit executes the block again to obtain an image at the new resolution."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The most typical use for this method is to create an image based on vector-based content. In that case, your "},{"code":"drawingHandler","type":"codeVoice"},{"type":"text","text":" block would redraw its existing path objects when asked. If you draw a mixture of vectors and images, you need to do more work to ensure that your images are the appropriate resolution for the destination graphics context."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"abstract":[{"type":"text","text":"Creates and returns an image object whose contents are drawn using the specified block."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSImage"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(size:flipped:drawingHandler:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsimage/init(size:flipped:drawinghandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsimage/init(size:flipped:drawinghandler:)"]}],"kind":"symbol","metadata":{"symbolKind":"init","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSSize","text":"NSSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"flipped","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"drawingHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":[{"unavailable":false,"deprecated":false,"introducedAt":"10.8","name":"macOS","beta":false}],"title":"init(size:flipped:drawingHandler:)","roleHeading":"Initializer","externalID":"c:objc(cs)NSImage(cm)imageWithSize:flipped:drawingHandler:","role":"symbol","modules":[{"name":"AppKit"}],"navigatorTitle":[{"text":"imageWithSize:flipped:drawingHandler:","kind":"identifier"}]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSImage/cacheMode-swift.property":{"abstract":[{"text":"The image’s caching mode.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSImage","text":"NSImage"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSImageCacheMode","text":"CacheMode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cacheMode"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/cacheMode-swift.property","url":"/documentation/appkit/nsimage/cachemode-swift.property","title":"cacheMode"},"doc://com.apple.appkit/documentation/AppKit/NSImage/init(size:flipped:drawingHandler:)":{"abstract":[{"type":"text","text":"Creates and returns an image object whose contents are drawn using the specified block."}],"type":"topic","title":"init(size:flipped:drawingHandler:)","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSSize","text":"NSSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"flipped","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"drawingHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(size:flipped:drawingHandler:)","role":"symbol","url":"/documentation/appkit/nsimage/init(size:flipped:drawinghandler:)","navigatorTitle":[{"text":"imageWithSize:flipped:drawingHandler:","kind":"identifier"}]},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.appkit/documentation/AppKit/NSCustomImageRep":{"type":"topic","navigatorTitle":[{"text":"NSCustomImageRep","kind":"identifier"}],"role":"symbol","abstract":[{"text":"An object that uses a delegate object to render an image from a custom format.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCustomImageRep","title":"NSCustomImageRep","url":"/documentation/appkit/nscustomimagerep","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCustomImageRep","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.appkit/documentation/AppKit/NSImage":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage","url":"/documentation/appkit/nsimage","navigatorTitle":[{"text":"NSImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSImage","kind":"identifier"}],"type":"topic","title":"NSImage","role":"symbol","abstract":[{"text":"A high-level interface for manipulating image data.","type":"text"}]},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/c:@T@NSSize":{"abstract":[{"type":"text","text":"A two-dimensional size."}],"url":"/documentation/foundation/nssize","kind":"symbol","role":"symbol","title":"NSSize","identifier":"doc://com.externally.resolved.symbol/c:@T@NSSize","type":"topic","fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSSize"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/c:@T@NSRect":{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","role":"symbol","type":"topic","url":"/documentation/foundation/nsrect","abstract":[{"text":"A rectangle.","type":"text"}],"fragments":[{"text":"typealias ","kind":"text"},{"text":"NSRect","kind":"identifier"}],"title":"NSRect","kind":"symbol"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"introducedAt":"10.8","name":"macOS","unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Type Method"},{"op":"replace","path":"/metadata/title","value":"imageWithSize:flipped:drawingHandler:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"imageWithSize:flipped:drawingHandler:"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSImage"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"imageWithSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSSize","preciseIdentifier":"c:@T@NSSize","text":"NSSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"size"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipped:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"drawingHandlerShouldBeCalledWithFlippedContext"},{"kind":"text","text":" "},{"kind":"identifier","text":"drawingHandler:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"kind":"text","text":" (^)("},{"preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier","text":"NSRect","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dstRect"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"drawingHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]},"op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"size","content":[{"inlineContent":[{"type":"text","text":"The size of the image, measured in points."}],"type":"paragraph"}]},{"name":"drawingHandlerShouldBeCalledWithFlippedContext","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"type":"text","text":" to apply a flip transformation to the graphics context before drawing or "},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"type":"text","text":" to draw using the default Cocoa coordinate system orientation."}]}]},{"name":"drawingHandler","content":[{"type":"paragraph","inlineContent":[{"text":"A block that draws the contents of the image representation. The image representation copies the block and stores it for later use. It is not executed until you draw the image. Because the block is executed later, AppKit executes it on the same thread on which you draw the image itself, which can be any thread of your app. Therefore, the block must be safe to call from any thread. The block takes the following parameter:","type":"text"}]},{"type":"termList","items":[{"definition":{"content":[{"inlineContent":[{"type":"text","text":"The destination rectangle in which to draw. The coordinates of this rectangle are specified in points."}],"type":"paragraph"}]},"term":{"inlineContent":[{"type":"text","text":"dstRect"}]}}]},{"type":"paragraph","inlineContent":[{"text":"The block returns a Boolean that indicates whether it drew the image successfully. Return ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true"},{"text":" from your block if it successfully drew the contents or ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"text":" if it did not.","type":"text"}]}]}]},"path":"/primaryContentSections/1"},{"path":"/primaryContentSections/2","value":{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"An initialized ","type":"text"},{"type":"codeVoice","code":"NSImage"},{"text":" object.","type":"text"}]}]},"op":"replace"},{"op":"replace","value":"cacheMode","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1cacheMode-swift.property/title"},{"op":"replace","value":[{"kind":"identifier","text":"cacheMode"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1cacheMode-swift.property/fragments"},{"op":"replace","value":"imageWithSize:flipped:drawingHandler:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(size:flipped:drawingHandler:)/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"imageWithSize:flipped:drawingHandler:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(size:flipped:drawingHandler:)/fragments"},{"op":"replace","value":"NSCustomImageRep","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCustomImageRep/title"},{"op":"replace","value":[{"text":"NSCustomImageRep","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCustomImageRep/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSCustomImageRep"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCustomImageRep/navigatorTitle"},{"op":"replace","value":"NSImage","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSImage"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSImage"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}