{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(named:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSImage"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"text":"named","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSImage","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage","preciseIdentifier":"c:objc(cs)NSImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Name","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/Name-swift.typealias","preciseIdentifier":"c:@T@NSImageName","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The name associated with the desired image. This can be a name you assigned to the image or the name of an image file in your app bundle.","type":"text"}],"type":"paragraph"}],"name":"name"}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"NSImage"},{"type":"text","text":" object associated with the specified name or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no such image was found."}],"type":"paragraph"}],"kind":"content"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"This method searches for named images in several places, returning the first image it finds matching the given name. The order of the search is as follows:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Search for an object whose name was set explicitly using the "},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/setName(_:)","type":"reference"},{"type":"text","text":" method and currently resides in the image cache."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Search the app’s main bundle for a file whose name matches the specified string. (For information on how the bundle is searched, see “","type":"text"},{"type":"reference","isActive":true,"identifier":"https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/AccessingaBundlesContents/AccessingaBundlesContents.html#//apple_ref/doc/uid/10000123i-CH104"},{"text":"” in ","type":"text"},{"type":"reference","isActive":true,"identifier":"https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/Introduction/Introduction.html#//apple_ref/doc/uid/10000123i"},{"text":".)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Search the Application Kit framework for a shared image with the specified name."}]}]}],"type":"orderedList"},{"inlineContent":[{"type":"text","text":"When looking for files in the app bundle, it is better (but not required) to include the filename extension in the "},{"type":"codeVoice","code":"name"},{"type":"text","text":" parameter. When naming an image with the "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/setName(_:)","isActive":true},{"type":"text","text":" method, it is convention not to include filename extensions in the names you specify. That way, you can easily distinguish between images you have named explicitly and those you want to load from the app’s bundle."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"One particularly useful image you can retrieve is your app’s icon. This image is set by Cocoa automatically and accessible using the "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/applicationIconName","isActive":true},{"type":"text","text":" constant. Icons for other apps can be obtained through the use of methods declared in the "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWorkspace","isActive":true},{"type":"text","text":" class. You can also retrieve many of the standard system images using Cocoa defined constants; for more information, see the "},{"type":"codeVoice","code":"Image Template Constants"},{"type":"text","text":", "},{"type":"codeVoice","code":"Sharing Permissions Named Images"},{"type":"text","text":", "},{"type":"codeVoice","code":"System Entity Images"},{"type":"text","text":", "},{"type":"codeVoice","code":"Toolbar Named Images"},{"type":"text","text":", and "},{"type":"codeVoice","code":"View Type Template Images"},{"type":"text","text":" sections for applicable constants."}],"type":"paragraph"},{"inlineContent":[{"text":"If an app is linked on macOS 10.5 or later, images requested using this method and whose name ends in the word “Template” are automatically marked as template images.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"NSImage"},{"type":"text","text":" class may cache a reference to the returned image object for performance in some cases. However, the class holds onto cached objects only while the object exists. If all strong references to the image are subsequently removed, the object may be quietly removed from the cache. Thus, if you plan to hold onto a returned image object, you must maintain a strong reference to it like you would any Cocoa object. You can clear an image object from the cache explicitly by calling the object’s "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/setName(_:)","type":"reference","isActive":true},{"type":"text","text":" method and specifying "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for the image name."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSImage/imageFileTypes()","doc://com.apple.appkit/documentation/AppKit/NSWorkspace/icon(forFile:)"]},{"generated":true,"anchor":"Creating-Images-by-Name","title":"Creating Images by Name","identifiers":["doc://com.apple.documentation/documentation/UIKit/configuring-and-displaying-symbol-images-in-your-ui","doc://com.apple.appkit/documentation/AppKit/NSImage/init(systemSymbolName:accessibilityDescription:)","doc://com.apple.appkit/documentation/AppKit/NSImage/init(systemSymbolName:variableValue:accessibilityDescription:)","doc://com.apple.appkit/documentation/AppKit/NSImage/init(symbolName:variableValue:)","doc://com.apple.appkit/documentation/AppKit/NSImage/init(symbolName:bundle:variableValue:)","doc://com.apple.appkit/documentation/AppKit/NSImage/init(resource:)","doc://com.apple.appkit/documentation/AppKit/NSImage/setName(_:)","doc://com.apple.appkit/documentation/AppKit/NSImage/name()","doc://com.apple.appkit/documentation/AppKit/NSImage/Name-swift.typealias","doc://com.apple.appkit/documentation/AppKit/NSImage/init(imageLiteralResourceName:)"]}],"variants":[{"paths":["/documentation/appkit/nsimage/init(named:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsimage/init(named:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Returns the image object associated with the specified name."}],"metadata":{"navigatorTitle":[{"text":"imageNamed:","kind":"identifier"}],"title":"init(named:)","modules":[{"name":"AppKit"}],"symbolKind":"init","platforms":[{"beta":false,"unavailable":false,"deprecated":false,"name":"macOS"}],"roleHeading":"Initializer","role":"symbol","externalID":"c:objc(cs)NSImage(cm)imageNamed:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"named"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSImage","preciseIdentifier":"c:objc(cs)NSImage"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSImageName"},{"text":")","kind":"text"}]},"references":{"doc://com.apple.appkit/documentation/AppKit/NSImage/Name-swift.typealias":{"kind":"symbol","url":"/documentation/appkit/nsimage/name-swift.typealias","title":"NSImage.Name","navigatorTitle":[{"text":"Name","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Name","kind":"identifier"}],"type":"topic","abstract":[{"text":"Named images, defined by the system or you, for use in your app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/Name-swift.typealias","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSImage/applicationIconName":{"abstract":[{"type":"text","text":"The app’s icon."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationIconName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"/documentation/appkit/nsimage/applicationiconname","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/applicationIconName","role":"symbol","navigatorTitle":[{"text":"NSImageNameApplicationIcon","kind":"identifier"}],"type":"topic","kind":"symbol","title":"applicationIconName"},"doc://com.apple.appkit/documentation/AppKit/NSImage/setName(_:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/setName(_:)","role":"symbol","type":"topic","url":"/documentation/appkit/nsimage/setname(_:)","navigatorTitle":[{"text":"setName:","kind":"identifier"}],"abstract":[{"text":"Registers the image object under the specified name.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setName","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSImage","text":"NSImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSImageName","text":"Name","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"setName(_:)","kind":"symbol"},"doc://com.apple.documentation/documentation/UIKit/configuring-and-displaying-symbol-images-in-your-ui":{"title":"Configuring and displaying symbol images in your UI","url":"/documentation/UIKit/configuring-and-displaying-symbol-images-in-your-ui","role":"article","identifier":"doc://com.apple.documentation/documentation/UIKit/configuring-and-displaying-symbol-images-in-your-ui","type":"topic","abstract":[{"text":"Create scalable images that integrate with your app’s text, and adjust the appearance of those images dynamically.","type":"text"}],"kind":"article"},"doc://com.apple.appkit/documentation/AppKit/NSImage/init(symbolName:variableValue:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(symbolName:variableValue:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageWithSymbolName:variableValue:"}],"role":"symbol","type":"topic","title":"init(symbolName:variableValue:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"symbolName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"variableValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a symbol image with the symbol name and variable value you specify."}],"url":"/documentation/appkit/nsimage/init(symbolname:variablevalue:)"},"doc://com.apple.appkit/documentation/AppKit/NSImage/imageFileTypes()":{"title":"imageFileTypes()","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageFileTypes"},{"kind":"text","text":"() -> ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]"}],"url":"/documentation/appkit/nsimage/imagefiletypes()","deprecated":true,"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/imageFileTypes()","role":"symbol","kind":"symbol","abstract":[{"text":"Returns an array of strings identifying the image types supported by the registered image representation objects.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"imageFileTypes"}]},"doc://com.apple.appkit/documentation/AppKit/NSImage/name()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"NSImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSImage"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSImageName"},{"text":"?","kind":"text"}],"title":"name()","url":"/documentation/appkit/nsimage/name()","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/name()","type":"topic","abstract":[{"text":"Returns the name associated with the image, if any.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"name","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSImage/init(resource:)":{"url":"/documentation/appkit/nsimage/init(resource:)","kind":"symbol","role":"symbol","type":"topic","title":"init(resource:)","abstract":[],"fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"resource"},{"kind":"text","text":": "},{"text":"ImageResource","kind":"typeIdentifier","preciseIdentifier":"s:21DeveloperToolsSupport13ImageResourceV"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(resource:)"},"doc://com.apple.appkit/documentation/AppKit/NSImage/init(symbolName:bundle:variableValue:)":{"abstract":[],"fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"symbolName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bundle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"variableValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nsimage/init(symbolname:bundle:variablevalue:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(symbolName:bundle:variableValue:)","role":"symbol","navigatorTitle":[{"text":"imageWithSymbolName:bundle:variableValue:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"init(symbolName:bundle:variableValue:)"},"https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/Introduction/Introduction.html#//apple_ref/doc/uid/10000123i":{"titleInlineContent":[{"type":"text","text":"Bundle Programming Guide"}],"identifier":"https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/Introduction/Introduction.html#//apple_ref/doc/uid/10000123i","title":"Bundle Programming Guide","type":"link","url":"https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/Introduction/Introduction.html#//apple_ref/doc/uid/10000123i"},"doc://com.apple.appkit/documentation/AppKit/NSImage/init(systemSymbolName:variableValue:accessibilityDescription:)":{"url":"/documentation/appkit/nsimage/init(systemsymbolname:variablevalue:accessibilitydescription:)","title":"init(systemSymbolName:variableValue:accessibilityDescription:)","kind":"symbol","abstract":[{"type":"text","text":"Creates a symbol image with the system symbol name and variable value you specify."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(systemSymbolName:variableValue:accessibilityDescription:)","type":"topic","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"systemSymbolName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"variableValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessibilityDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"imageWithSystemSymbolName:variableValue:accessibilityDescription:"}],"role":"symbol"},"https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/AccessingaBundlesContents/AccessingaBundlesContents.html#//apple_ref/doc/uid/10000123i-CH104":{"titleInlineContent":[{"type":"text","text":"Accessing a Bundle’s Contents"}],"identifier":"https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/AccessingaBundlesContents/AccessingaBundlesContents.html#//apple_ref/doc/uid/10000123i-CH104","title":"Accessing a Bundle’s Contents","type":"link","url":"https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/AccessingaBundlesContents/AccessingaBundlesContents.html#//apple_ref/doc/uid/10000123i-CH104"},"doc://com.apple.appkit/documentation/AppKit/NSImage":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage","url":"/documentation/appkit/nsimage","navigatorTitle":[{"text":"NSImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSImage","kind":"identifier"}],"type":"topic","title":"NSImage","role":"symbol","abstract":[{"text":"A high-level interface for manipulating image data.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSImage/init(systemSymbolName:accessibilityDescription:)":{"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"systemSymbolName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accessibilityDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(systemSymbolName:accessibilityDescription:)","url":"/documentation/appkit/nsimage/init(systemsymbolname:accessibilitydescription:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(systemSymbolName:accessibilityDescription:)","type":"topic","abstract":[{"text":"Creates a symbol image with the system symbol name and accessibility description you specify.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageWithSystemSymbolName:accessibilityDescription:"}]},"doc://com.apple.appkit/documentation/AppKit/NSImage/init(named:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(named:)","role":"symbol","type":"topic","url":"/documentation/appkit/nsimage/init(named:)","navigatorTitle":[{"text":"imageNamed:","kind":"identifier"}],"abstract":[{"text":"Returns the image object associated with the specified name.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"named","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSImage","text":"NSImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSImageName","text":"Name","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(named:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSWorkspace":{"abstract":[{"type":"text","text":"A workspace that can launch other apps and perform a variety of file-handling services."}],"url":"/documentation/appkit/nsworkspace","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSWorkspace","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWorkspace","title":"NSWorkspace","navigatorTitle":[{"text":"NSWorkspace","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSWorkspace/icon(forFile:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"icon"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forFile"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSImage","kind":"typeIdentifier","text":"NSImage"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Returns an image containing the icon for the specified file."}],"url":"/documentation/appkit/nsworkspace/icon(forfile:)","navigatorTitle":[{"kind":"identifier","text":"iconForFile:"}],"title":"icon(forFile:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWorkspace/icon(forFile:)"},"doc://com.apple.appkit/documentation/AppKit/NSImage/init(imageLiteralResourceName:)":{"title":"init(imageLiteralResourceName:)","type":"topic","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"imageLiteralResourceName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/init(imageLiteralResourceName:)","abstract":[{"text":"Creates an image initialized with the specified resource name.","type":"text"}],"role":"symbol","url":"/documentation/appkit/nsimage/init(imageliteralresourcename:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"beta":false,"unavailable":false,"deprecated":false,"name":"macOS"}],"path":"/metadata/platforms","op":"replace"},{"value":"Type Method","path":"/metadata/roleHeading","op":"replace"},{"value":"imageNamed:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"imageNamed:"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSImage"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"anchor":"Related-Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSImage/imageFileTypes()","doc://com.apple.appkit/documentation/AppKit/NSWorkspace/icon(forFile:)"],"title":"Related Documentation"},{"anchor":"Creating-Images-by-Name","title":"Creating Images by Name","generated":true,"identifiers":["doc://com.apple.documentation/documentation/UIKit/configuring-and-displaying-symbol-images-in-your-ui","doc://com.apple.appkit/documentation/AppKit/NSImage/init(systemSymbolName:accessibilityDescription:)","doc://com.apple.appkit/documentation/AppKit/NSImage/init(systemSymbolName:variableValue:accessibilityDescription:)","doc://com.apple.appkit/documentation/AppKit/NSImage/init(symbolName:variableValue:)","doc://com.apple.appkit/documentation/AppKit/NSImage/init(symbolName:bundle:variableValue:)","doc://com.apple.appkit/documentation/AppKit/NSImage/setName(_:)","doc://com.apple.appkit/documentation/AppKit/NSImage/name()","doc://com.apple.appkit/documentation/AppKit/NSImage/Name-swift.typealias"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage","text":"NSImage","preciseIdentifier":"c:objc(cs)NSImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"imageNamed:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/Name-swift.typealias","text":"NSImageName","preciseIdentifier":"c:@T@NSImageName"},{"text":") ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name associated with the desired image. This can be a name you assigned to the image or the name of an image file in your app bundle."}]}],"name":"name"}]},"op":"replace","path":"/primaryContentSections/1"},{"value":{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"NSImage","type":"codeVoice"},{"text":" object associated with the specified name or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if no such image was found.","type":"text"}]}]},"path":"/primaryContentSections/2","op":"replace"},{"value":"NSImageName","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1Name-swift.typealias/title"},{"value":[{"kind":"identifier","text":"NSImageName"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1Name-swift.typealias/fragments"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1Name-swift.typealias/navigatorTitle","value":[{"kind":"identifier","text":"NSImageName"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1applicationIconName/title","value":"NSImageNameApplicationIcon"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1applicationIconName/fragments","value":[{"kind":"identifier","text":"NSImageNameApplicationIcon"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1setName(_:)/title","value":"setName:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1setName(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setName:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(symbolName:variableValue:)/title","value":"imageWithSymbolName:variableValue:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(symbolName:variableValue:)/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"imageWithSymbolName:variableValue:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imageFileTypes()/title","op":"replace","value":"imageFileTypes"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1imageFileTypes()/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"imageFileTypes"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1name()/title","op":"replace","value":"name"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1name()/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"name","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(symbolName:bundle:variableValue:)/title","op":"replace","value":"imageWithSymbolName:bundle:variableValue:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(symbolName:bundle:variableValue:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"imageWithSymbolName:bundle:variableValue:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(systemSymbolName:variableValue:accessibilityDescription:)/title","op":"replace","value":"imageWithSystemSymbolName:variableValue:accessibilityDescription:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(systemSymbolName:variableValue:accessibilityDescription:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"imageWithSystemSymbolName:variableValue:accessibilityDescription:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/title","op":"replace","value":"NSImage"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/fragments","op":"replace","value":[{"kind":"identifier","text":"NSImage"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/navigatorTitle","op":"replace","value":[{"text":"NSImage","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(systemSymbolName:accessibilityDescription:)/title","op":"replace","value":"imageWithSystemSymbolName:accessibilityDescription:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(systemSymbolName:accessibilityDescription:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"imageWithSystemSymbolName:accessibilityDescription:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(named:)/title","op":"replace","value":"imageNamed:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1init(named:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"imageNamed:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/title","op":"replace","value":"NSWorkspace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/fragments","op":"replace","value":[{"kind":"identifier","text":"NSWorkspace"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSWorkspace"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1icon(forFile:)/title","op":"replace","value":"iconForFile:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWorkspace~1icon(forFile:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"iconForFile:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}