{
  "abstract": [
    {
      "text": "A template image for rotating an item counterclockwise.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSImage"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarRotateLeftTemplateName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSImageNameTouchBarRotateLeftTemplate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "touchBarRotateLeftTemplateName"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSImageNameTouchBarRotateLeftTemplate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12.2",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "touchBarRotateLeftTemplateName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "touchBarRotateLeftTemplateName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2793537",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Touch Bar template images are exclusively for use in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchBarItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects and not in onscreen windows.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use template images for your ",
              "type": "text"
            },
            {
              "code": "NSTouchBarItem",
              "type": "codeVoice"
            },
            {
              "text": " images because, in the Touch Bar, template images respond automatically to system white-point changes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage": {
      "abstract": [
        {
          "text": "A high-level interface for manipulating image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "role": "symbol",
      "title": "NSImage",
      "type": "topic",
      "url": "/documentation/appkit/nsimage"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/Name-swift.typealias": {
      "abstract": [
        {
          "text": "Named images, defined by the system or you, for use in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/Name-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "role": "symbol",
      "title": "NSImage.Name",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/name-swift.typealias"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAddDetailTemplateName": {
      "abstract": [
        {
          "text": "A template image for showing additional detail for an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchBarAddDetailTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAddDetailTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameTouchBarAddDetailTemplate"
        }
      ],
      "role": "symbol",
      "title": "touchBarAddDetailTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/touchbaradddetailtemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAddTemplateName": {
      "abstract": [
        {
          "text": "A template image for creating a new item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchBarAddTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAddTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameTouchBarAddTemplate"
        }
      ],
      "role": "symbol",
      "title": "touchBarAddTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/touchbaraddtemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAlarmTemplateName": {
      "abstract": [
        {
          "text": "A template image for setting or showing an alarm.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchBarAlarmTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAlarmTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameTouchBarAlarmTemplate"
        }
      ],
      "role": "symbol",
      "title": "touchBarAlarmTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/touchbaralarmtemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioInputMuteTemplateName": {
      "abstract": [
        {
          "text": "A template image for muting audio input or denoting that audio input is muted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchBarAudioInputMuteTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioInputMuteTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameTouchBarAudioInputMuteTemplate"
        }
      ],
      "role": "symbol",
      "title": "touchBarAudioInputMuteTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/touchbaraudioinputmutetemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioInputTemplateName": {
      "abstract": [
        {
          "text": "A template image for denoting audio input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchBarAudioInputTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioInputTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameTouchBarAudioInputTemplate"
        }
      ],
      "role": "symbol",
      "title": "touchBarAudioInputTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/touchbaraudioinputtemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputMuteTemplateName": {
      "abstract": [
        {
          "text": "A template image for muting audio output or for denoting that audio output is muted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchBarAudioOutputMuteTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputMuteTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameTouchBarAudioOutputMuteTemplate"
        }
      ],
      "role": "symbol",
      "title": "touchBarAudioOutputMuteTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/touchbaraudiooutputmutetemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputVolumeHighTemplateName": {
      "abstract": [
        {
          "text": "A template image for setting the audio output volume to a high level, or for denoting that the audio is at the peak volume.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchBarAudioOutputVolumeHighTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputVolumeHighTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameTouchBarAudioOutputVolumeHighTemplate"
        }
      ],
      "role": "symbol",
      "title": "touchBarAudioOutputVolumeHighTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/touchbaraudiooutputvolumehightemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputVolumeLowTemplateName": {
      "abstract": [
        {
          "text": "A template image for setting the audio output volume to a low level, or for denoting that it is set to a low level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchBarAudioOutputVolumeLowTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputVolumeLowTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameTouchBarAudioOutputVolumeLowTemplate"
        }
      ],
      "role": "symbol",
      "title": "touchBarAudioOutputVolumeLowTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/touchbaraudiooutputvolumelowtemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputVolumeMediumTemplateName": {
      "abstract": [
        {
          "text": "A template image for setting the audio output volume to a medium level, or for denoting that it is set to a medium level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchBarAudioOutputVolumeMediumTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputVolumeMediumTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameTouchBarAudioOutputVolumeMediumTemplate"
        }
      ],
      "role": "symbol",
      "title": "touchBarAudioOutputVolumeMediumTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/touchbaraudiooutputvolumemediumtemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputVolumeOffTemplateName": {
      "abstract": [
        {
          "text": "A template image for setting the audio output volume to silent, or for denoting that it is set to silent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchBarAudioOutputVolumeOffTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputVolumeOffTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameTouchBarAudioOutputVolumeOffTemplate"
        }
      ],
      "role": "symbol",
      "title": "touchBarAudioOutputVolumeOffTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/touchbaraudiooutputvolumeofftemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarBookmarksTemplateName": {
      "abstract": [
        {
          "text": "A template image for showing app-specific bookmarks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchBarBookmarksTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarBookmarksTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameTouchBarBookmarksTemplate"
        }
      ],
      "role": "symbol",
      "title": "touchBarBookmarksTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/touchbarbookmarkstemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarColorPickerFillName": {
      "abstract": [
        {
          "text": "A template image for showing a color picker so the user can select a fill color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchBarColorPickerFillName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarColorPickerFillName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameTouchBarColorPickerFill"
        }
      ],
      "role": "symbol",
      "title": "touchBarColorPickerFillName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/touchbarcolorpickerfillname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarColorPickerFontName": {
      "abstract": [
        {
          "text": "A template image for showing a color picker so the user can select a text color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchBarColorPickerFontName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarColorPickerFontName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameTouchBarColorPickerFont"
        }
      ],
      "role": "symbol",
      "title": "touchBarColorPickerFontName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/touchbarcolorpickerfontname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarColorPickerStrokeName": {
      "abstract": [
        {
          "text": "A template image for showing a color picker so the user can select a stroke color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchBarColorPickerStrokeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarColorPickerStrokeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameTouchBarColorPickerStroke"
        }
      ],
      "role": "symbol",
      "title": "touchBarColorPickerStrokeName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/touchbarcolorpickerstrokename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarCommunicationAudioTemplateName": {
      "abstract": [
        {
          "text": "A template image for initiating or denoting audio communication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchBarCommunicationAudioTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarCommunicationAudioTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameTouchBarCommunicationAudioTemplate"
        }
      ],
      "role": "symbol",
      "title": "touchBarCommunicationAudioTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/touchbarcommunicationaudiotemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarRotateLeftTemplateName": {
      "abstract": [
        {
          "text": "A template image for rotating an item counterclockwise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "touchBarRotateLeftTemplateName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarRotateLeftTemplateName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageNameTouchBarRotateLeftTemplate"
        }
      ],
      "role": "symbol",
      "title": "touchBarRotateLeftTemplateName",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/touchbarrotatelefttemplatename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTouchBarItem": {
      "abstract": [
        {
          "text": "A UI control shown in the Touch Bar on supported models of MacBook Pro.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarItem"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTouchBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTouchBarItem"
        }
      ],
      "role": "symbol",
      "title": "NSTouchBarItem",
      "type": "topic",
      "url": "/documentation/appkit/nstouchbaritem"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "media-2793537": {
      "alt": "Template image for rotate left",
      "identifier": "media-2793537",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/157d903e4bd40e1f58751c12a42b9085/media-2793537@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Using-template-images",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAddDetailTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAddTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAlarmTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioInputMuteTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioInputTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputMuteTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputVolumeHighTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputVolumeLowTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputVolumeMediumTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputVolumeOffTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarBookmarksTemplateName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarColorPickerFillName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarColorPickerFontName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarColorPickerStrokeName",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarCommunicationAudioTemplateName"
      ],
      "title": "Using template images"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12.2",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSImageNameTouchBarRotateLeftTemplate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameTouchBarRotateLeftTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Using-template-images",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAddDetailTemplateName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAddTemplateName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAlarmTemplateName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioInputMuteTemplateName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioInputTemplateName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputMuteTemplateName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputVolumeHighTemplateName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputVolumeLowTemplateName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputVolumeMediumTemplateName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarAudioOutputVolumeOffTemplateName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarBookmarksTemplateName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarColorPickerFillName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarColorPickerFontName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarColorPickerStrokeName",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/touchBarCommunicationAudioTemplateName"
              ],
              "title": "Using template images"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/Name-swift.typealias",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSImageName",
                    "text": "NSImageName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSImageNameTouchBarRotateLeftTemplate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAudioOutputMuteTemplateName/title",
          "value": "NSImageNameTouchBarAudioOutputMuteTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAudioOutputMuteTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameTouchBarAudioOutputMuteTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAlarmTemplateName/title",
          "value": "NSImageNameTouchBarAlarmTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAlarmTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameTouchBarAlarmTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAddTemplateName/title",
          "value": "NSImageNameTouchBarAddTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAddTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameTouchBarAddTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarColorPickerStrokeName/title",
          "value": "NSImageNameTouchBarColorPickerStroke"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarColorPickerStrokeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameTouchBarColorPickerStroke"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarCommunicationAudioTemplateName/title",
          "value": "NSImageNameTouchBarCommunicationAudioTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarCommunicationAudioTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameTouchBarCommunicationAudioTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarBookmarksTemplateName/title",
          "value": "NSImageNameTouchBarBookmarksTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarBookmarksTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameTouchBarBookmarksTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAudioOutputVolumeLowTemplateName/title",
          "value": "NSImageNameTouchBarAudioOutputVolumeLowTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAudioOutputVolumeLowTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameTouchBarAudioOutputVolumeLowTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAudioInputMuteTemplateName/title",
          "value": "NSImageNameTouchBarAudioInputMuteTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAudioInputMuteTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameTouchBarAudioInputMuteTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarRotateLeftTemplateName/title",
          "value": "NSImageNameTouchBarRotateLeftTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarRotateLeftTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameTouchBarRotateLeftTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarColorPickerFontName/title",
          "value": "NSImageNameTouchBarColorPickerFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarColorPickerFontName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameTouchBarColorPickerFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAudioOutputVolumeHighTemplateName/title",
          "value": "NSImageNameTouchBarAudioOutputVolumeHighTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAudioOutputVolumeHighTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameTouchBarAudioOutputVolumeHighTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAudioOutputVolumeOffTemplateName/title",
          "value": "NSImageNameTouchBarAudioOutputVolumeOffTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAudioOutputVolumeOffTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameTouchBarAudioOutputVolumeOffTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAudioInputTemplateName/title",
          "value": "NSImageNameTouchBarAudioInputTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAudioInputTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameTouchBarAudioInputTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAudioOutputVolumeMediumTemplateName/title",
          "value": "NSImageNameTouchBarAudioOutputVolumeMediumTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAudioOutputVolumeMediumTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameTouchBarAudioOutputVolumeMediumTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/title",
          "value": "NSImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAddDetailTemplateName/title",
          "value": "NSImageNameTouchBarAddDetailTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarAddDetailTemplateName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameTouchBarAddDetailTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarColorPickerFillName/title",
          "value": "NSImageNameTouchBarColorPickerFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1touchBarColorPickerFillName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageNameTouchBarColorPickerFill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1Name-swift.typealias/title",
          "value": "NSImageName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1Name-swift.typealias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1Name-swift.typealias/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarItem/title",
          "value": "NSTouchBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTouchBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTouchBarItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsimage/touchbarrotatelefttemplatename"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsimage/touchbarrotatelefttemplatename"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
