{
  "abstract": [
    {
      "text": "Occurs when the app can’t access the sensor’s data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sensorkit/documentation/SensorKit",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRError",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/dataInaccessible"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SRErrorCode@SRErrorDataInaccessible",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dataInaccessible"
      }
    ],
    "modules": [
      {
        "name": "SensorKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SRErrorDataInaccessible"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SRError.Code.dataInaccessible"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dataInaccessible"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit": {
      "abstract": [
        {
          "text": "Retrieve data and derived metrics from sensors on an iPhone, or paired Apple Watch.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SensorKit",
      "type": "topic",
      "url": "/documentation/sensorkit"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRError": {
      "abstract": [
        {
          "text": "An error that SensorKit reports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SRError"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRError"
        }
      ],
      "role": "symbol",
      "title": "SRError",
      "type": "topic",
      "url": "/documentation/sensorkit/srerror"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code": {
      "abstract": [
        {
          "text": "The kinds of problems that stop a recording or a fetch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SRError.Code",
      "type": "topic",
      "url": "/documentation/sensorkit/srerror/code"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/dataInaccessible": {
      "abstract": [
        {
          "text": "Occurs when the app can’t access the sensor’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataInaccessible"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/dataInaccessible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRErrorDataInaccessible"
        }
      ],
      "role": "symbol",
      "title": "SRError.Code.dataInaccessible",
      "type": "topic",
      "url": "/documentation/sensorkit/srerror/code/datainaccessible"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/fetchRequestInvalid": {
      "abstract": [
        {
          "text": "Occurs when the app misconfigures a fetch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchRequestInvalid"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/fetchRequestInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRErrorFetchRequestInvalid"
        }
      ],
      "role": "symbol",
      "title": "SRError.Code.fetchRequestInvalid",
      "type": "topic",
      "url": "/documentation/sensorkit/srerror/code/fetchrequestinvalid"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/invalidEntitlement": {
      "abstract": [
        {
          "text": "Occurs when the app lacks the required entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidEntitlement"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/invalidEntitlement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRErrorInvalidEntitlement"
        }
      ],
      "role": "symbol",
      "title": "SRError.Code.invalidEntitlement",
      "type": "topic",
      "url": "/documentation/sensorkit/srerror/code/invalidentitlement"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/noAuthorization": {
      "abstract": [
        {
          "text": "Occurs when the user declines sensor access in the Settings app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noAuthorization"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/noAuthorization",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRErrorNoAuthorization"
        }
      ],
      "role": "symbol",
      "title": "SRError.Code.noAuthorization",
      "type": "topic",
      "url": "/documentation/sensorkit/srerror/code/noauthorization"
    },
    "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/promptDeclined": {
      "abstract": [
        {
          "text": "Occurs when the user cancels the sensor approval workflow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "promptDeclined"
        }
      ],
      "identifier": "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/promptDeclined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SRErrorPromptDeclined"
        }
      ],
      "role": "symbol",
      "title": "SRError.Code.promptDeclined",
      "type": "topic",
      "url": "/documentation/sensorkit/srerror/code/promptdeclined"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/promptDeclined",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/fetchRequestInvalid",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/invalidEntitlement",
        "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/noAuthorization"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SRErrorDataInaccessible"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRErrorDataInaccessible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sensorkit/documentation/SensorKit",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/promptDeclined",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/fetchRequestInvalid",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/invalidEntitlement",
                "doc://com.apple.sensorkit/documentation/SensorKit/SRError/Code/noAuthorization"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SRErrorDataInaccessible"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code~1noAuthorization/title",
          "value": "SRErrorNoAuthorization"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code~1noAuthorization/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRErrorNoAuthorization"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code/title",
          "value": "SRErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SRErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code~1invalidEntitlement/title",
          "value": "SRErrorInvalidEntitlement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code~1invalidEntitlement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRErrorInvalidEntitlement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code~1fetchRequestInvalid/title",
          "value": "SRErrorFetchRequestInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code~1fetchRequestInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRErrorFetchRequestInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code~1dataInaccessible/title",
          "value": "SRErrorDataInaccessible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code~1dataInaccessible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRErrorDataInaccessible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code~1promptDeclined/title",
          "value": "SRErrorPromptDeclined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sensorkit~1documentation~1SensorKit~1SRError~1Code~1promptDeclined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SRErrorPromptDeclined"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sensorkit/srerror/code/datainaccessible"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sensorkit/srerror/code/datainaccessible"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
