{
  "abstract": [
    {
      "text": "A response when the invitation times out because the player doesn’t answer it.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gamekit/documentation/GameKit",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/noAnswer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@GKInviteRecipientResponse@GKInviteRecipientResponseNoAnswer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "noAnswer"
      }
    ],
    "modules": [
      {
        "name": "GameKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GKInviteRecipientResponseNoAnswer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "GKInviteRecipientResponse.noAnswer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "noAnswer"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gamekit/documentation/GameKit": {
      "abstract": [
        {
          "text": "Enable players to interact with friends, compare leaderboard ranks, earn achievements, and participate in multiplayer games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameKit",
      "type": "topic",
      "url": "/documentation/gamekit"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse": {
      "abstract": [
        {
          "text": "A player’s response to an invitation to join a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponse"
        }
      ],
      "role": "symbol",
      "title": "GKInviteRecipientResponse",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/accepted": {
      "abstract": [
        {
          "text": "A response when the player accepts the invitation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accepted"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/accepted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponseAccepted"
        }
      ],
      "role": "symbol",
      "title": "GKInviteRecipientResponse.accepted",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/accepted"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/declined": {
      "abstract": [
        {
          "text": "A response when the player rejects the invitation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "declined"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/declined",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponseDeclined"
        }
      ],
      "role": "symbol",
      "title": "GKInviteRecipientResponse.declined",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/declined"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/failed": {
      "abstract": [
        {
          "text": "A response when the system fails to deliver the invitation to the player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failed"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/failed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponseFailed"
        }
      ],
      "role": "symbol",
      "title": "GKInviteRecipientResponse.failed",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/failed"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/incompatible": {
      "abstract": [
        {
          "text": "A response when the player isn’t running a compatible version of the game.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incompatible"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/incompatible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponseIncompatible"
        }
      ],
      "role": "symbol",
      "title": "GKInviteRecipientResponse.incompatible",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/incompatible"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/noAnswer": {
      "abstract": [
        {
          "text": "A response when the invitation times out because the player doesn’t answer it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noAnswer"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/noAnswer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponseNoAnswer"
        }
      ],
      "role": "symbol",
      "title": "GKInviteRecipientResponse.noAnswer",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/noanswer"
    },
    "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/unableToConnect": {
      "abstract": [
        {
          "text": "A response when the system can’t contact the player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unableToConnect"
        }
      ],
      "identifier": "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/unableToConnect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKInviteRecipientResponseUnableToConnect"
        }
      ],
      "role": "symbol",
      "title": "GKInviteRecipientResponse.unableToConnect",
      "type": "topic",
      "url": "/documentation/gamekit/gkinviterecipientresponse/unabletoconnect"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responses",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/accepted",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/declined",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/failed",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/incompatible",
        "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/unableToConnect"
      ],
      "title": "Responses"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "GKInviteRecipientResponseNoAnswer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponseNoAnswer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gamekit/documentation/GameKit",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responses",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/accepted",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/declined",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/failed",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/incompatible",
                "doc://com.apple.gamekit/documentation/GameKit/GKInviteRecipientResponse/unableToConnect"
              ],
              "title": "Responses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "GKInviteRecipientResponseNoAnswer"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1noAnswer/title",
          "value": "GKInviteRecipientResponseNoAnswer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1noAnswer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponseNoAnswer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1incompatible/title",
          "value": "GKInviteRecipientResponseIncompatible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1incompatible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponseIncompatible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1unableToConnect/title",
          "value": "GKInviteRecipientResponseUnableToConnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1unableToConnect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponseUnableToConnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1accepted/title",
          "value": "GKInviteRecipientResponseAccepted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1accepted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponseAccepted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse/title",
          "value": "GKInviteRecipientResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1declined/title",
          "value": "GKInviteRecipientResponseDeclined"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1declined/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponseDeclined"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1failed/title",
          "value": "GKInviteRecipientResponseFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gamekit~1documentation~1GameKit~1GKInviteRecipientResponse~1failed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKInviteRecipientResponseFailed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gamekit/gkinviterecipientresponse/noanswer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gamekit/gkinviterecipientresponse/noanswer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
