{
  "abstract": [
    {
      "text": "Prepares image representations of the specified assets for later use.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.photokit/documentation/Photos",
        "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager/startCachingImages(for:targetSize:contentMode:options:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)PHCachingImageManager(im)startCachingImagesForAssets:targetSize:contentMode:options:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "startCachingImages"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)PHAsset",
        "text": "PHAsset"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "targetSize"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGSize",
        "text": "CGSize"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "contentMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PHImageContentMode",
        "text": "PHImageContentMode"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "options"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)PHImageRequestOptions",
        "text": "PHImageRequestOptions"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "Photos"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "startCachingImagesForAssets:targetSize:contentMode:options:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "startCachingImages(for:targetSize:contentMode:options:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "startCachingImages"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "assets"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PHAsset",
              "text": "PHAsset"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "targetSize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGSize",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGSize",
              "text": "CGSize"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "contentMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageContentMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PHImageContentMode",
              "text": "PHImageContentMode"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PHImageRequestOptions",
              "text": "PHImageRequestOptions"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " objects for which to prepare image representations.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "assets"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The size of the images to be prepared.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "targetSize"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An option for how to fit the images to the aspect ratio of the requested size. For details, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageContentMode",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "contentMode"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Options specifying how Photos should handle the request, format the requested images, and notify your app of progress or errors. For details, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you call this method, Photos begins to fetch image data and generates thumbnail images on a background thread. At any time afterward, you can use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageManager/requestImage(for:targetSize:contentMode:options:resultHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to request individual images from the cache. If Photos has finished preparing a requested image, that method provides the image immediately.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Photos caches images with the exact target size, content mode, and options you specify in this method. If you later request an image with, for example, a different target size than you passed when calling this method, Photos cannot make use of the cache and so it must fetch or generate a new image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.photokit/documentation/Photos": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos",
      "kind": "symbol",
      "role": "collection",
      "title": "Photos",
      "type": "topic",
      "url": "/documentation/photos"
    },
    "doc://com.apple.photokit/documentation/Photos/PHAsset": {
      "abstract": [
        {
          "text": "A representation of an image, video, or Live Photo in the Photos library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHAsset"
        }
      ],
      "role": "symbol",
      "title": "PHAsset",
      "type": "topic",
      "url": "/documentation/photos/phasset"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager": {
      "abstract": [
        {
          "text": "An object that facilitates retrieving or generating preview thumbnails, optimized for batch preloading large numbers of assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHCachingImageManager"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHCachingImageManager"
        }
      ],
      "role": "symbol",
      "title": "PHCachingImageManager",
      "type": "topic",
      "url": "/documentation/photos/phcachingimagemanager"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager/startCachingImages(for:targetSize:contentMode:options:)": {
      "abstract": [
        {
          "text": "Prepares image representations of the specified assets for later use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startCachingImages"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAsset",
          "text": "PHAsset"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "targetSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHImageContentMode",
          "text": "PHImageContentMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHImageRequestOptions",
          "text": "PHImageRequestOptions"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager/startCachingImages(for:targetSize:contentMode:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startCachingImagesForAssets:targetSize:contentMode:options:"
        }
      ],
      "role": "symbol",
      "title": "startCachingImages(for:targetSize:contentMode:options:)",
      "type": "topic",
      "url": "/documentation/photos/phcachingimagemanager/startcachingimages(for:targetsize:contentmode:options:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager/stopCachingImages(for:targetSize:contentMode:options:)": {
      "abstract": [
        {
          "text": "Cancels image preparation for the specified assets and options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopCachingImages"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAsset",
          "text": "PHAsset"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "targetSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHImageContentMode",
          "text": "PHImageContentMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHImageRequestOptions",
          "text": "PHImageRequestOptions"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager/stopCachingImages(for:targetSize:contentMode:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopCachingImagesForAssets:targetSize:contentMode:options:"
        }
      ],
      "role": "symbol",
      "title": "stopCachingImages(for:targetSize:contentMode:options:)",
      "type": "topic",
      "url": "/documentation/photos/phcachingimagemanager/stopcachingimages(for:targetsize:contentmode:options:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager/stopCachingImagesForAllAssets()": {
      "abstract": [
        {
          "text": "Cancels all image preparation that is currently in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopCachingImagesForAllAssets"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager/stopCachingImagesForAllAssets()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopCachingImagesForAllAssets"
        }
      ],
      "role": "symbol",
      "title": "stopCachingImagesForAllAssets()",
      "type": "topic",
      "url": "/documentation/photos/phcachingimagemanager/stopcachingimagesforallassets()"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageContentMode": {
      "abstract": [
        {
          "text": "Options for fitting an image’s aspect ratio to a requested size, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageManager/requestImage(for:targetSize:contentMode:options:resultHandler:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHImageContentMode"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageContentMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHImageContentMode"
        }
      ],
      "role": "symbol",
      "title": "PHImageContentMode",
      "type": "topic",
      "url": "/documentation/photos/phimagecontentmode"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageManager/requestImage(for:targetSize:contentMode:options:resultHandler:)": {
      "abstract": [
        {
          "text": "Requests an image representation for the specified asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHAsset",
          "text": "PHAsset"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "targetSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PHImageContentMode",
          "text": "PHImageContentMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)PHImageRequestOptions",
          "text": "PHImageRequestOptions"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "resultHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PHImageRequestID",
          "text": "PHImageRequestID"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageManager/requestImage(for:targetSize:contentMode:options:resultHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestImageForAsset:targetSize:contentMode:options:resultHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestImage(for:targetSize:contentMode:options:resultHandler:)",
      "type": "topic",
      "url": "/documentation/photos/phimagemanager/requestimage(for:targetsize:contentmode:options:resulthandler:)"
    },
    "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions": {
      "abstract": [
        {
          "text": "A set of options affecting the delivery of still image representations of Photos assets you request from an image manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHImageRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PHImageRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "PHImageRequestOptions",
      "type": "topic",
      "url": "/documentation/photos/phimagerequestoptions"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGSize": {
      "abstract": [
        {
          "text": "A structure that contains width and height values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGSize",
      "type": "topic",
      "url": "/documentation/corefoundation/cgsize"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Preparing-Images",
      "generated": true,
      "identifiers": [
        "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager/stopCachingImages(for:targetSize:contentMode:options:)",
        "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager/stopCachingImagesForAllAssets()"
      ],
      "title": "Preparing Images"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "startCachingImagesForAssets:targetSize:contentMode:options:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startCachingImagesForAssets:targetSize:contentMode:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.photokit/documentation/Photos",
                "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Preparing-Images",
              "generated": true,
              "identifiers": [
                "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager/stopCachingImages(for:targetSize:contentMode:options:)",
                "doc://com.apple.photokit/documentation/Photos/PHCachingImageManager/stopCachingImagesForAllAssets()"
              ],
              "title": "Preparing Images"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "startCachingImagesForAssets:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<PHAsset *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "assets"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "targetSize:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGSize",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGSize",
                    "text": "CGSize"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "targetSize"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "contentMode:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageContentMode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@PHImageContentMode",
                    "text": "PHImageContentMode"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "contentMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "options:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)PHImageRequestOptions",
                    "text": "PHImageRequestOptions"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "options"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.photokit/documentation/Photos/PHAsset",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " objects for which to prepare image representations.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "assets"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The size of the images to be prepared.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "targetSize"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An option for how to fit the images to the aspect ratio of the requested size. For details, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageContentMode",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "contentMode"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Options specifying how Photos should handle the request, format the requested images, and notify your app of progress or errors. For details, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.photokit/documentation/Photos/PHImageRequestOptions",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "options"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCachingImageManager~1startCachingImages(for:targetSize:contentMode:options:)/title",
          "value": "startCachingImagesForAssets:targetSize:contentMode:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCachingImageManager~1startCachingImages(for:targetSize:contentMode:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startCachingImagesForAssets:targetSize:contentMode:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCachingImageManager/title",
          "value": "PHCachingImageManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCachingImageManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCachingImageManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCachingImageManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHCachingImageManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions/title",
          "value": "PHImageRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageManager~1requestImage(for:targetSize:contentMode:options:resultHandler:)/title",
          "value": "requestImageForAsset:targetSize:contentMode:options:resultHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageManager~1requestImage(for:targetSize:contentMode:options:resultHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestImageForAsset:targetSize:contentMode:options:resultHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCachingImageManager~1stopCachingImages(for:targetSize:contentMode:options:)/title",
          "value": "stopCachingImagesForAssets:targetSize:contentMode:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCachingImageManager~1stopCachingImages(for:targetSize:contentMode:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopCachingImagesForAssets:targetSize:contentMode:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCachingImageManager~1stopCachingImagesForAllAssets()/title",
          "value": "stopCachingImagesForAllAssets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHCachingImageManager~1stopCachingImagesForAllAssets()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopCachingImagesForAllAssets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageContentMode/title",
          "value": "PHImageContentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageContentMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageContentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHImageContentMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHImageContentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/title",
          "value": "PHAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PHAsset"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/photos/phcachingimagemanager/startcachingimages(for:targetsize:contentmode:options:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/photos/phcachingimagemanager/startcachingimages(for:targetsize:contentmode:options:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
