{
  "abstract": [
    {
      "text": "The location of each color in a multicolor gauge’s gradient.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "On watchOS 9.0 or later, use WidgetKit instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.clockkit/documentation/ClockKit",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider/gaugeColorLocations"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CLKGaugeProvider(py)gaugeColorLocations",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "gaugeColorLocations"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSNumber",
        "text": "NSNumber"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "ClockKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "gaugeColorLocations"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "5.0",
        "message": "On watchOS 9.0 or later, use WidgetKit instead",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "gaugeColorLocations"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gaugeColorLocations"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": "]? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property specifies the location of each color in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider/gaugeColors",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array. Each location must be a value between ",
              "type": "text"
            },
            {
              "code": "0.0",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "1.0",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A gauge with more than one color appears as a gradient. The provider specifies the colors using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider/gaugeColors",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider/gaugeColors",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider/gaugeColorLocations",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties must have the same number of elements.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.clockkit/documentation/ClockKit": {
      "abstract": [
        {
          "text": "Display app-specific data on the clock face.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClockKit",
      "type": "topic",
      "url": "/documentation/clockkit"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider": {
      "abstract": [
        {
          "text": "An abstract superclass that provides all the common behaviors for the gauge providers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLKGaugeProvider"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLKGaugeProvider"
        }
      ],
      "role": "symbol",
      "title": "CLKGaugeProvider",
      "type": "topic",
      "url": "/documentation/clockkit/clkgaugeprovider"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider/gaugeColorLocations": {
      "abstract": [
        {
          "text": "The location of each color in a multicolor gauge’s gradient.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gaugeColorLocations"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider/gaugeColorLocations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gaugeColorLocations"
        }
      ],
      "role": "symbol",
      "title": "gaugeColorLocations",
      "type": "topic",
      "url": "/documentation/clockkit/clkgaugeprovider/gaugecolorlocations"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider/gaugeColors": {
      "abstract": [
        {
          "text": "The colors of the gauge.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gaugeColors"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider/gaugeColors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gaugeColors"
        }
      ],
      "role": "symbol",
      "title": "gaugeColors",
      "type": "topic",
      "url": "/documentation/clockkit/clkgaugeprovider/gaugecolors"
    },
    "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider/style": {
      "abstract": [
        {
          "text": "The style that defines the gauge’s appearance.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CLKGaugeProviderStyle",
          "text": "CLKGaugeProviderStyle"
        }
      ],
      "identifier": "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider/style",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "style"
        }
      ],
      "role": "symbol",
      "title": "style",
      "type": "topic",
      "url": "/documentation/clockkit/clkgaugeprovider/style"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-the-Gauges-Appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider/gaugeColors",
        "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider/style"
      ],
      "title": "Setting the Gauge’s Appearance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "gaugeColorLocations"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gaugeColorLocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.clockkit/documentation/ClockKit",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-the-Gauges-Appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider/gaugeColors",
                "doc://com.apple.clockkit/documentation/ClockKit/CLKGaugeProvider/style"
              ],
              "title": "Setting the Gauge’s Appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSNumber *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "gaugeColorLocations"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "On watchOS 9.0 or later, use WidgetKit instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKGaugeProvider/title",
          "value": "CLKGaugeProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKGaugeProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKGaugeProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKGaugeProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLKGaugeProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKGaugeProvider~1style/title",
          "value": "style"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKGaugeProvider~1style/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "style"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKGaugeProvider~1gaugeColors/title",
          "value": "gaugeColors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKGaugeProvider~1gaugeColors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gaugeColors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKGaugeProvider~1gaugeColorLocations/title",
          "value": "gaugeColorLocations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.clockkit~1documentation~1ClockKit~1CLKGaugeProvider~1gaugeColorLocations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gaugeColorLocations"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/clockkit/clkgaugeprovider/gaugecolorlocations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/clockkit/clkgaugeprovider/gaugecolorlocations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
