{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/init(destinationHostEndpoint:protocol:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "NetworkExtension",
    "externalID": "s:So13NENetworkRuleC16NetworkExtensionE23destinationHostEndpoint8protocolAB0C010NWEndpointO_So0aB8ProtocolVtcfc",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "destinationHostEndpoint"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7Network10NWEndpointO",
        "text": "NWEndpoint"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NENetworkRule",
        "text": "NENetworkRule"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NENetworkRuleProtocol",
        "text": "Protocol"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(destinationHostEndpoint:protocol:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "destinationHostEndpoint"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "hostEndpoint"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7Network10NWEndpointO",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7Network10NWEndpointO",
              "text": "NWEndpoint"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NENetworkRule",
              "text": "NENetworkRule"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NENetworkRuleProtocol",
              "text": "Protocol"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule": {
      "abstract": [
        {
          "text": "A rule to match attributes of network traffic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NENetworkRule"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NENetworkRule"
        }
      ],
      "role": "symbol",
      "title": "NENetworkRule",
      "type": "topic",
      "url": "/documentation/networkextension/nenetworkrule"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol": {
      "abstract": [
        {
          "text": "A type to represent network protocols used by routing rules.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Protocol"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Protocol"
        }
      ],
      "role": "symbol",
      "title": "NENetworkRule.Protocol",
      "type": "topic",
      "url": "/documentation/networkextension/nenetworkrule/protocol"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/init(destinationHostEndpoint:protocol:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "destinationHostEndpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Network10NWEndpointO",
          "text": "NWEndpoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NENetworkRule",
          "text": "NENetworkRule"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NENetworkRuleProtocol",
          "text": "Protocol"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/init(destinationHostEndpoint:protocol:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(destinationHostEndpoint:protocol:)",
      "type": "topic",
      "url": "/documentation/networkextension/nenetworkrule/init(destinationhostendpoint:protocol:)"
    },
    "doc://com.externally.resolved.symbol/s:7Network10NWEndpointO": {
      "abstract": [
        {
          "text": "A local or remote endpoint in a network connection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NWEndpoint"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7Network10NWEndpointO",
      "kind": "symbol",
      "role": "symbol",
      "title": "NWEndpoint",
      "type": "topic",
      "url": "/documentation/Network/NWEndpoint"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1Protocol/title",
          "value": "NENetworkRuleProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1Protocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NENetworkRuleProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1Protocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NENetworkRuleProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule/title",
          "value": "NENetworkRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NENetworkRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NENetworkRule"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nenetworkrule/init(destinationhostendpoint:protocol:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
