{
  "abstract": [
    {
      "text": "The protocol that the rule matches.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchProtocol"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NENetworkRule(py)matchProtocol",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "matchProtocol"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NENetworkRule",
        "text": "NENetworkRule"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NENetworkRuleProtocol",
        "text": "Protocol"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "matchProtocol"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "matchProtocol"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "matchProtocol"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NENetworkRule",
              "text": "NENetworkRule"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NENetworkRuleProtocol",
              "text": "Protocol"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule": {
      "abstract": [
        {
          "text": "A rule to match attributes of network traffic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NENetworkRule"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NENetworkRule"
        }
      ],
      "role": "symbol",
      "title": "NENetworkRule",
      "type": "topic",
      "url": "/documentation/networkextension/nenetworkrule"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol": {
      "abstract": [
        {
          "text": "A type to represent network protocols used by routing rules.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Protocol"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Protocol"
        }
      ],
      "role": "symbol",
      "title": "NENetworkRule.Protocol",
      "type": "topic",
      "url": "/documentation/networkextension/nenetworkrule/protocol"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchDirection": {
      "abstract": [
        {
          "text": "The direction of network traffic that the rule matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NETrafficDirection",
          "text": "NETrafficDirection"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchDirection"
        }
      ],
      "role": "symbol",
      "title": "matchDirection",
      "type": "topic",
      "url": "/documentation/networkextension/nenetworkrule/matchdirection"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchLocalNetwork": {
      "abstract": [
        {
          "text": "The local network that the rule matches.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchLocalNetwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NWHostEndpoint",
          "text": "NWHostEndpoint"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchLocalNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchLocalNetwork"
        }
      ],
      "role": "symbol",
      "title": "matchLocalNetwork",
      "type": "topic",
      "url": "/documentation/networkextension/nenetworkrule/matchlocalnetwork"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchLocalPrefix": {
      "abstract": [
        {
          "text": "A number that specifies the local sub-network that the rule matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchLocalPrefix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchLocalPrefix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchLocalPrefix"
        }
      ],
      "role": "symbol",
      "title": "matchLocalPrefix",
      "type": "topic",
      "url": "/documentation/networkextension/nenetworkrule/matchlocalprefix"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchProtocol": {
      "abstract": [
        {
          "text": "The protocol that the rule matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchProtocol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NENetworkRule",
          "text": "NENetworkRule"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NENetworkRuleProtocol",
          "text": "Protocol"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchProtocol"
        }
      ],
      "role": "symbol",
      "title": "matchProtocol",
      "type": "topic",
      "url": "/documentation/networkextension/nenetworkrule/matchprotocol"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchRemoteEndpoint": {
      "abstract": [
        {
          "text": "The remote endpoint that the rule matches.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchRemoteEndpoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NWHostEndpoint",
          "text": "NWHostEndpoint"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchRemoteEndpoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchRemoteEndpoint"
        }
      ],
      "role": "symbol",
      "title": "matchRemoteEndpoint",
      "type": "topic",
      "url": "/documentation/networkextension/nenetworkrule/matchremoteendpoint"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchRemotePrefix": {
      "abstract": [
        {
          "text": "A number that specifies the remote sub-network that the rule matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "matchRemotePrefix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchRemotePrefix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "matchRemotePrefix"
        }
      ],
      "role": "symbol",
      "title": "matchRemotePrefix",
      "type": "topic",
      "url": "/documentation/networkextension/nenetworkrule/matchremoteprefix"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NETrafficDirection": {
      "abstract": [
        {
          "text": "A type to represent the direction of network traffic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NETrafficDirection"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NETrafficDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NETrafficDirection"
        }
      ],
      "role": "symbol",
      "title": "NETrafficDirection",
      "type": "topic",
      "url": "/documentation/networkextension/netrafficdirection"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matching-network-traffic-characteristics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchRemoteEndpoint",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchRemotePrefix",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchLocalNetwork",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchLocalPrefix",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchDirection",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NETrafficDirection"
      ],
      "title": "Matching network traffic characteristics"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "matchProtocol"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matchProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Matching-network-traffic-characteristics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchRemoteEndpoint",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchRemotePrefix",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchLocalNetwork",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchLocalPrefix",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/matchDirection",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NETrafficDirection"
              ],
              "title": "Matching network traffic characteristics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NENetworkRule/Protocol",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NENetworkRuleProtocol",
                    "text": "NENetworkRuleProtocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "matchProtocol"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule/title",
          "value": "NENetworkRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NENetworkRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NENetworkRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1matchLocalPrefix/title",
          "value": "matchLocalPrefix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1matchLocalPrefix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matchLocalPrefix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1Protocol/title",
          "value": "NENetworkRuleProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1Protocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NENetworkRuleProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1Protocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NENetworkRuleProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1matchProtocol/title",
          "value": "matchProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1matchProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matchProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NETrafficDirection/title",
          "value": "NETrafficDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NETrafficDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NETrafficDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NETrafficDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NETrafficDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1matchRemotePrefix/title",
          "value": "matchRemotePrefix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1matchRemotePrefix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matchRemotePrefix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1matchLocalNetwork/title",
          "value": "matchLocalNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1matchLocalNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matchLocalNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1matchRemoteEndpoint/title",
          "value": "matchRemoteEndpoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1matchRemoteEndpoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matchRemoteEndpoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1matchDirection/title",
          "value": "matchDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NENetworkRule~1matchDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "matchDirection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nenetworkrule/matchprotocol"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nenetworkrule/matchprotocol"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
