{
  "abstract": [
    {
      "text": "Creates a new document by reading the contents for the document from another URL, presents its user interface, and returns the document if successful.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/duplicateDocument(withContentsOf:copying:displayName:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSDocumentController(im)duplicateDocumentWithContentsOfURL:copying:displayName:error:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "duplicateDocument"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "withContentsOf"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation3URLV",
        "text": "URL"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "copying"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "displayName"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "?) "
      },
      {
        "kind": "keyword",
        "text": "throws"
      },
      {
        "kind": "text",
        "text": " -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSDocument",
        "text": "NSDocument"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "duplicateDocumentWithContentsOfURL:copying:displayName:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "duplicateDocument(withContentsOf:copying:displayName:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "duplicateDocument"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "withContentsOf"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "url"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation3URLV",
              "text": "URL"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "copying"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "duplicateByCopying"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "displayName"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "displayNameOrNil"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "?) "
            },
            {
              "kind": "keyword",
              "text": "throws"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSDocument",
              "text": "NSDocument"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The URL locating the document from which contents of the new document are copied.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "url"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/true",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", the contents located at the passed-in URL are copied into a file located in the directory used for the autosaved contents of untitled documents.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "duplicateByCopying"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If not ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": " then this value is used to derive a display name for the new document that does not match one that is already in use by an open document.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "displayNameOrNil"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The newly created ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if the document could not be created.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default implementation of this method copies the file if specified, determines the type of the document, calls ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocument(for:withContentsOf:ofType:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to instantiate it, sends the document ",
              "type": "text"
            },
            {
              "code": "setDisplayName:",
              "type": "codeVoice"
            },
            {
              "text": " to name it if ",
              "type": "text"
            },
            {
              "code": "displayNameOrNil",
              "type": "codeVoice"
            },
            {
              "text": " is not ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", calls ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/addDocument(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to record its opening, and sends the document ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/makeWindowControllers()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/showWindows()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " messages.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The default implementation of this method uses the file coordination mechanism introduced in OS X v10.7. It passes the document to the ",
              "type": "text"
            },
            {
              "code": "NSFileCoordinator",
              "type": "codeVoice"
            },
            {
              "text": " method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilecoordinator/1417120-addfilepresenter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " immediately after calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/addDocument(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. (The balancing invocation of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilecoordinator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilecoordinator/1414924-removefilepresenter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/close()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can override this method to customize how documents are duplicated. It is called by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/duplicate()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". It may also be called from other places in AppKit.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In most cases, an app does not need to call this method directly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In Swift, this method returns a nonoptional result and is marked with the ",
                  "type": "text"
                },
                {
                  "code": "throws",
                  "type": "codeVoice"
                },
                {
                  "text": " keyword to indicate that it throws an error in cases of failure.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "You call this method in a ",
                  "type": "text"
                },
                {
                  "code": "try",
                  "type": "codeVoice"
                },
                {
                  "text": " expression and handle any errors in the ",
                  "type": "text"
                },
                {
                  "code": "catch",
                  "type": "codeVoice"
                },
                {
                  "text": " clauses of a ",
                  "type": "text"
                },
                {
                  "code": "do",
                  "type": "codeVoice"
                },
                {
                  "text": " statement, as described in ",
                  "type": "text"
                },
                {
                  "identifier": "https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " in ",
                  "type": "text"
                },
                {
                  "identifier": "https://docs.swift.org/swift-book/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "About Imported Cocoa Error Parameters",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Handling Errors in Swift",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface for macOS documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDocument"
        }
      ],
      "role": "symbol",
      "title": "NSDocument",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/close()": {
      "abstract": [
        {
          "text": "Closes all of the document’s windows and removes the document from its document controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "close"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/close()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "close"
        }
      ],
      "role": "symbol",
      "title": "close()",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/close()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/duplicate()": {
      "abstract": [
        {
          "text": "Creates a new document whose contents are the same as the receiver and returns an error object if unsuccessful.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duplicate"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/duplicate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duplicateAndReturnError:"
        }
      ],
      "role": "symbol",
      "title": "duplicate()",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/duplicate()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/makeWindowControllers()": {
      "abstract": [
        {
          "text": "Creates the window controller objects that the document uses to display its content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeWindowControllers"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/makeWindowControllers()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeWindowControllers"
        }
      ],
      "role": "symbol",
      "title": "makeWindowControllers()",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/makewindowcontrollers()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/showWindows()": {
      "abstract": [
        {
          "text": "Displays all of the document’s windows, bringing them to the front and making them main or key as necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showWindows"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/showWindows()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showWindows"
        }
      ],
      "role": "symbol",
      "title": "showWindows()",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/showwindows()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController": {
      "abstract": [
        {
          "text": "An object that manages an app’s documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDocumentController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDocumentController"
        }
      ],
      "role": "symbol",
      "title": "NSDocumentController",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/addDocument(_:)": {
      "abstract": [
        {
          "text": "Adds the given document to the list of open documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addDocument"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/addDocument(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addDocument:"
        }
      ],
      "role": "symbol",
      "title": "addDocument(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/adddocument(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/document(for:)-i5zi": {
      "abstract": [
        {
          "text": "Returns, for a given URL, the open document whose file or file package is located by the URL, or ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " if there is no such open document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "document"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/document(for:)-i5zi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentForURL:"
        }
      ],
      "role": "symbol",
      "title": "document(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/document(for:)-i5zi"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/duplicateDocument(withContentsOf:copying:displayName:)": {
      "abstract": [
        {
          "text": "Creates a new document by reading the contents for the document from another URL, presents its user interface, and returns the document if successful.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duplicateDocument"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withContentsOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "copying"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "displayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/duplicateDocument(withContentsOf:copying:displayName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duplicateDocumentWithContentsOfURL:copying:displayName:error:"
        }
      ],
      "role": "symbol",
      "title": "duplicateDocument(withContentsOf:copying:displayName:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/duplicatedocument(withcontentsof:copying:displayname:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocument(for:withContentsOf:ofType:)": {
      "abstract": [
        {
          "text": "Instantiates a document located by a URL, of a specified type, but by reading the contents for the document from another URL, and returns it if successful.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeDocument"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "withContentsOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocument(for:withContentsOf:ofType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeDocumentForURL:withContentsOfURL:ofType:error:"
        }
      ],
      "role": "symbol",
      "title": "makeDocument(for:withContentsOf:ofType:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/makedocument(for:withcontentsof:oftype:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocument(withContentsOf:ofType:)": {
      "abstract": [
        {
          "text": "Instantiates a document located by a URL, of a specified type, and returns it if successful.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeDocument"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withContentsOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocument(withContentsOf:ofType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeDocumentWithContentsOfURL:ofType:error:"
        }
      ],
      "role": "symbol",
      "title": "makeDocument(withContentsOf:ofType:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/makedocument(withcontentsof:oftype:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeUntitledDocument(ofType:)": {
      "abstract": [
        {
          "text": "Instantiates a new untitled document of the specified type and returns it if successful.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeUntitledDocument"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeUntitledDocument(ofType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeUntitledDocumentOfType:error:"
        }
      ],
      "role": "symbol",
      "title": "makeUntitledDocument(ofType:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/makeuntitleddocument(oftype:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocument(withContentsOf:display:completionHandler:)": {
      "abstract": [
        {
          "text": "Opens a document located by a URL, optionally presents its user interface, and calls the passed-in completion handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openDocument"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withContentsOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "display"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocument(withContentsOf:display:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfURL:display:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "openDocument(withContentsOf:display:completionHandler:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/opendocument(withcontentsof:display:completionhandler:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openUntitledDocumentAndDisplay(_:)": {
      "abstract": [
        {
          "text": "Creates a new untitled document, presents its user interface if ",
          "type": "text"
        },
        {
          "code": "displayDocument",
          "type": "codeVoice"
        },
        {
          "text": " is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", and returns the document if successful.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openUntitledDocumentAndDisplay"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openUntitledDocumentAndDisplay(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openUntitledDocumentAndDisplay:error:"
        }
      ],
      "role": "symbol",
      "title": "openUntitledDocumentAndDisplay(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/openuntitleddocumentanddisplay(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/reopenDocument(for:withContentsOf:display:completionHandler:)": {
      "abstract": [
        {
          "text": "Reopens a document, optionally located by a URL, by reading the contents for the document from another URL, optionally presents its user interface, and calls the passed-in completion handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reopenDocument"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "withContentsOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "display"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/reopenDocument(for:withContentsOf:display:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reopenDocumentForURL:withContentsOfURL:display:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "reopenDocument(for:withContentsOf:display:completionHandler:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/reopendocument(for:withcontentsof:display:completionhandler:)"
    },
    "doc://com.apple.documentation/documentation/foundation/nsfilecoordinator": {
      "abstract": [
        {
          "text": "An object that coordinates the reading and writing of files and directories among file presenters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSFileCoordinator"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilecoordinator",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFileCoordinator",
      "type": "topic",
      "url": "/documentation/foundation/nsfilecoordinator"
    },
    "doc://com.apple.documentation/documentation/foundation/nsfilecoordinator/1414924-removefilepresenter": {
      "abstract": [
        {
          "text": "Unregisters the specified file presenter object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "removeFilePresenter"
        },
        {
          "kind": "text",
          "text": "(any NSFilePresenter)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilecoordinator/1414924-removefilepresenter",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeFilePresenter(_:)",
      "type": "topic",
      "url": "/documentation/foundation/nsfilecoordinator/1414924-removefilepresenter"
    },
    "doc://com.apple.documentation/documentation/foundation/nsfilecoordinator/1417120-addfilepresenter": {
      "abstract": [
        {
          "text": "Registers the specified file presenter object so that it can receive notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "addFilePresenter"
        },
        {
          "kind": "text",
          "text": "(any NSFilePresenter)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilecoordinator/1417120-addfilepresenter",
      "kind": "symbol",
      "role": "symbol",
      "title": "addFilePresenter(_:)",
      "type": "topic",
      "url": "/documentation/foundation/nsfilecoordinator/1417120-addfilepresenter"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSURL": {
      "abstract": [
        {
          "text": "An object representing the location of a resource that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSURL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSURL",
      "type": "topic",
      "url": "/documentation/foundation/nsurl"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation3URLV": {
      "abstract": [
        {
          "text": "A value that identifies the location of a resource, such as an item on a remote server or the path to a local file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
      "kind": "symbol",
      "role": "symbol",
      "title": "URL",
      "type": "topic",
      "url": "/documentation/foundation/url"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "https://docs.swift.org/swift-book/": {
      "identifier": "https://docs.swift.org/swift-book/",
      "title": "The Swift Programming Language",
      "titleInlineContent": [
        {
          "text": "The Swift Programming Language",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://docs.swift.org/swift-book/"
    },
    "https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html": {
      "identifier": "https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html",
      "title": "Error Handling",
      "titleInlineContent": [
        {
          "text": "Error Handling",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-and-Opening-Documents",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/document(for:)-i5zi",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocument(withContentsOf:display:completionHandler:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openUntitledDocumentAndDisplay(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocument(for:withContentsOf:ofType:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocument(withContentsOf:ofType:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeUntitledDocument(ofType:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/reopenDocument(for:withContentsOf:display:completionHandler:)"
      ],
      "title": "Creating and Opening Documents"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "duplicateDocumentWithContentsOfURL:copying:displayName:error:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "duplicateDocumentWithContentsOfURL:copying:displayName:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSDocumentController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-and-Opening-Documents",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/document(for:)-i5zi",
                "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocument(withContentsOf:display:completionHandler:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openUntitledDocumentAndDisplay(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocument(for:withContentsOf:ofType:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocument(withContentsOf:ofType:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeUntitledDocument(ofType:)",
                "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/reopenDocument(for:withContentsOf:display:completionHandler:)"
              ],
              "title": "Creating and Opening Documents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSDocument",
                    "text": "NSDocument"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "duplicateDocumentWithContentsOfURL:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSURL",
                    "text": "NSURL"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "url"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "copying:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "duplicateByCopying"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "displayName:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "displayNameOrNil"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "error:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "outError"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The URL locating the document from which contents of the new document are copied.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "url"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "If ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/swift/true",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", the contents located at the passed-in URL are copied into a file located in the directory used for the autosaved contents of untitled documents.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "duplicateByCopying"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "If not ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " then this value is used to derive a display name for the new document that does not match one that is already in use by an open document.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "displayNameOrNil"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "On return, if duplication is unsuccessful, a pointer to an error object that encapsulates the reason the document could not be created.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "outError"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The newly created ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " object, or ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if the document could not be created.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1openUntitledDocumentAndDisplay(_:)/title",
          "value": "openUntitledDocumentAndDisplay:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1openUntitledDocumentAndDisplay(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openUntitledDocumentAndDisplay:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsfilecoordinator~11417120-addfilepresenter/title",
          "value": "addFilePresenter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1duplicateDocument(withContentsOf:copying:displayName:)/title",
          "value": "duplicateDocumentWithContentsOfURL:copying:displayName:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1duplicateDocument(withContentsOf:copying:displayName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "duplicateDocumentWithContentsOfURL:copying:displayName:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1makeUntitledDocument(ofType:)/title",
          "value": "makeUntitledDocumentOfType:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1makeUntitledDocument(ofType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "makeUntitledDocumentOfType:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSURL/abstract",
          "value": [
            {
              "text": "An object that represents the location of a resource, such as an item on a remote server or the path to a local file. ",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1document(for:)-i5zi/title",
          "value": "documentForURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1document(for:)-i5zi/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentForURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1addDocument(_:)/title",
          "value": "addDocument:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1addDocument(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addDocument:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1duplicate()/title",
          "value": "duplicateAndReturnError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1duplicate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "duplicateAndReturnError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/title",
          "value": "NSDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1reopenDocument(for:withContentsOf:display:completionHandler:)/title",
          "value": "reopenDocumentForURL:withContentsOfURL:display:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1reopenDocument(for:withContentsOf:display:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "reopenDocumentForURL:withContentsOfURL:display:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsfilecoordinator~11414924-removefilepresenter/title",
          "value": "removeFilePresenter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1makeWindowControllers()/title",
          "value": "makeWindowControllers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1makeWindowControllers()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "makeWindowControllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1showWindows()/title",
          "value": "showWindows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1showWindows()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "showWindows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1makeDocument(for:withContentsOf:ofType:)/title",
          "value": "makeDocumentForURL:withContentsOfURL:ofType:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1makeDocument(for:withContentsOf:ofType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "makeDocumentForURL:withContentsOfURL:ofType:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1makeDocument(withContentsOf:ofType:)/title",
          "value": "makeDocumentWithContentsOfURL:ofType:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1makeDocument(withContentsOf:ofType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "makeDocumentWithContentsOfURL:ofType:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1openDocument(withContentsOf:display:completionHandler:)/title",
          "value": "openDocumentWithContentsOfURL:display:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1openDocument(withContentsOf:display:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openDocumentWithContentsOfURL:display:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController/title",
          "value": "NSDocumentController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocumentController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocumentController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1close()/title",
          "value": "close"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1close()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "close"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdocumentcontroller/duplicatedocument(withcontentsof:copying:displayname:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsdocumentcontroller/duplicatedocument(withcontentsof:copying:displayname:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
