{
  "abstract": [
    {
      "text": "Returns a selection of files chosen by the user in the Open panel.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/urlsFromRunningOpenPanel()",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileNamesFromRunningOpenPanel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSDocumentController(im)fileNamesFromRunningOpenPanel",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "fileNamesFromRunningOpenPanel"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "fileNamesFromRunningOpenPanel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.4",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "fileNamesFromRunningOpenPanel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSArray",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSArray",
              "text": "NSArray"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "fileNamesFromRunningOpenPanel"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each file in the returned ",
              "type": "text"
            },
            {
              "code": "NSArray",
              "type": "codeVoice"
            },
            {
              "text": " is a fully qualified path to the file’s location in the file system. This method is called by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocument(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and it calls ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/runModalOpenPanel(_:forTypes:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " after initializing the Open panel (which includes getting the starting directory with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/currentDirectory",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "). Returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if the user cancels the Open panel or makes no selection.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController": {
      "abstract": [
        {
          "text": "An object that manages an app’s documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDocumentController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDocumentController"
        }
      ],
      "role": "symbol",
      "title": "NSDocumentController",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/currentDirectory": {
      "abstract": [
        {
          "text": "The directory path to be used as the starting point in the Open panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentDirectory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/currentDirectory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentDirectory"
        }
      ],
      "role": "symbol",
      "title": "currentDirectory",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/currentdirectory"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/documentForFileName:": {
      "abstract": [
        {
          "text": "Returns the document object for the file in which the document data is stored.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "documentForFileName:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/documentForFileName:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentForFileName:"
        }
      ],
      "role": "symbol",
      "title": "documentForFileName:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/documentforfilename:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileExtensionsFromType:": {
      "abstract": [
        {
          "text": "Returns the allowable file extensions for the given document type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "fileExtensionsFromType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileExtensionsFromType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileExtensionsFromType:"
        }
      ],
      "role": "symbol",
      "title": "fileExtensionsFromType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/fileextensionsfromtype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileNamesFromRunningOpenPanel": {
      "abstract": [
        {
          "text": "Returns a selection of files chosen by the user in the Open panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "fileNamesFromRunningOpenPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileNamesFromRunningOpenPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileNamesFromRunningOpenPanel"
        }
      ],
      "role": "symbol",
      "title": "fileNamesFromRunningOpenPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/filenamesfromrunningopenpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfFile:ofType:": {
      "abstract": [
        {
          "text": "Creates and returns a document object of a given document type from the contents of a file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "makeDocumentWithContentsOfFile:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfFile:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeDocumentWithContentsOfFile:ofType:"
        }
      ],
      "role": "symbol",
      "title": "makeDocumentWithContentsOfFile:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/makedocumentwithcontentsoffile:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfURL:ofType:": {
      "abstract": [
        {
          "text": "Creates and returns a document object for the given document type from the contents of a given URL.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "makeDocumentWithContentsOfURL:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfURL:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeDocumentWithContentsOfURL:ofType:"
        }
      ],
      "role": "symbol",
      "title": "makeDocumentWithContentsOfURL:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/makedocumentwithcontentsofurl:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeUntitledDocumentOfType:": {
      "abstract": [
        {
          "text": "Creates and returns a document object for document type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "makeUntitledDocumentOfType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeUntitledDocumentOfType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeUntitledDocumentOfType:"
        }
      ],
      "role": "symbol",
      "title": "makeUntitledDocumentOfType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/makeuntitleddocumentoftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocument(_:)": {
      "abstract": [
        {
          "text": "An action method called by the Open menu command, it runs the modal Open panel and, based on the selected filenames, creates one or more ",
          "type": "text"
        },
        {
          "code": "NSDocument",
          "type": "codeVoice"
        },
        {
          "text": " objects from the contents of the files.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openDocument"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocument(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openDocument:"
        }
      ],
      "role": "symbol",
      "title": "openDocument(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/opendocument(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfFile:display:": {
      "abstract": [
        {
          "text": "Returns a document object created from the contents of a given file and optionally displays it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfFile:display:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfFile:display:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfFile:display:"
        }
      ],
      "role": "symbol",
      "title": "openDocumentWithContentsOfFile:display:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/opendocumentwithcontentsoffile:display:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:": {
      "abstract": [
        {
          "text": "Returns a document object created from the contents of a given URL and optionally displays it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfURL:display:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfURL:display:"
        }
      ],
      "role": "symbol",
      "title": "openDocumentWithContentsOfURL:display:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/opendocumentwithcontentsofurl:display:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:error:": {
      "abstract": [
        {
          "text": "Opens a document located by the given URL presents its user interface if requested, and returns the document if successful.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfURL:display:error:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfURL:display:error:"
        }
      ],
      "role": "symbol",
      "title": "openDocumentWithContentsOfURL:display:error:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/opendocumentwithcontentsofurl:display:error:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openUntitledDocumentOfType:display:": {
      "abstract": [
        {
          "text": "Returns a document object instantiated from the subclass of the given document type and optionally displays it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "openUntitledDocumentOfType:display:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openUntitledDocumentOfType:display:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openUntitledDocumentOfType:display:"
        }
      ],
      "role": "symbol",
      "title": "openUntitledDocumentOfType:display:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/openuntitleddocumentoftype:display:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/reopenDocumentForURL:withContentsOfURL:error:": {
      "abstract": [
        {
          "text": "Reopens an autosaved document located by a URL, by reading the contents for the document from another URL, presents its user interface, and returns ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " if successful.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "reopenDocumentForURL:withContentsOfURL:error:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/reopenDocumentForURL:withContentsOfURL:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reopenDocumentForURL:withContentsOfURL:error:"
        }
      ],
      "role": "symbol",
      "title": "reopenDocumentForURL:withContentsOfURL:error:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/reopendocumentforurl:withcontentsofurl:error:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/runModalOpenPanel(_:forTypes:)": {
      "abstract": [
        {
          "text": "Presents a modal Open dialog and limits selection to specific file types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModalOpenPanel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOpenPanel",
          "text": "NSOpenPanel"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forTypes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/runModalOpenPanel(_:forTypes:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalOpenPanel:forTypes:"
        }
      ],
      "role": "symbol",
      "title": "runModalOpenPanel(_:forTypes:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/runmodalopenpanel(_:fortypes:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/setShouldCreateUI:": {
      "abstract": [
        {
          "text": "Sets whether the window controllers of a document should be created when the document is created.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setShouldCreateUI:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/setShouldCreateUI:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setShouldCreateUI:"
        }
      ],
      "role": "symbol",
      "title": "setShouldCreateUI:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/setshouldcreateui:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/shouldCreateUI": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the window controllers of a document should be created when the document is created.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "shouldCreateUI"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/shouldCreateUI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldCreateUI"
        }
      ],
      "role": "symbol",
      "title": "shouldCreateUI",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/shouldcreateui"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/typeFromFileExtension:": {
      "abstract": [
        {
          "text": "Returns the document type associated with files having extension ",
          "type": "text"
        },
        {
          "code": "fileExtensionOrHFSFileType",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "typeFromFileExtension:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/typeFromFileExtension:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typeFromFileExtension:"
        }
      ],
      "role": "symbol",
      "title": "typeFromFileExtension:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/typefromfileextension:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/urlsFromRunningOpenPanel()": {
      "abstract": [
        {
          "text": "An array of URLs corresponding to the files selected in a running open panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "urlsFromRunningOpenPanel"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/urlsFromRunningOpenPanel()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URLsFromRunningOpenPanel"
        }
      ],
      "role": "symbol",
      "title": "urlsFromRunningOpenPanel()",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/urlsfromrunningopenpanel()"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSArray": {
      "abstract": [
        {
          "text": "An object representing a static ordered collection, for use instead of an  constant in cases that require reference semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSArray",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSArray",
      "type": "topic",
      "url": "/documentation/foundation/nsarray"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/documentForFileName:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileExtensionsFromType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeUntitledDocumentOfType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfURL:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfFile:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfFile:display:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:error:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openUntitledDocumentOfType:display:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/reopenDocumentForURL:withContentsOfURL:error:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/setShouldCreateUI:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/shouldCreateUI",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/typeFromFileExtension:"
      ],
      "title": "Deprecated Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1currentDirectory/title",
          "value": "currentDirectory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1currentDirectory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentDirectory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSArray/abstract",
          "value": [
            {
              "text": "A static ordered collection of objects.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1urlsFromRunningOpenPanel()/title",
          "value": "URLsFromRunningOpenPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1urlsFromRunningOpenPanel()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "URLsFromRunningOpenPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController/title",
          "value": "NSDocumentController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocumentController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocumentController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1runModalOpenPanel(_:forTypes:)/title",
          "value": "runModalOpenPanel:forTypes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1runModalOpenPanel(_:forTypes:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModalOpenPanel:forTypes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1openDocument(_:)/title",
          "value": "openDocument:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1openDocument(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openDocument:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdocumentcontroller/filenamesfromrunningopenpanel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
