{
  "abstract": [
    {
      "text": "Creates and returns a document object of a given document type from the contents of a file.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocument(withContentsOf:ofType:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfFile:ofType:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSDocumentController(im)makeDocumentWithContentsOfFile:ofType:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "makeDocumentWithContentsOfFile:ofType:"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "makeDocumentWithContentsOfFile:ofType:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.4",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "makeDocumentWithContentsOfFile:ofType:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "id"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "makeDocumentWithContentsOfFile:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "fileName"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ofType:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "type"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Creates and returns an ",
              "type": "text"
            },
            {
              "code": "NSDocument",
              "type": "codeVoice"
            },
            {
              "text": " object for document type ",
              "type": "text"
            },
            {
              "code": "docType",
              "type": "codeVoice"
            },
            {
              "text": " from the contents of the file ",
              "type": "text"
            },
            {
              "code": "fileName",
              "type": "codeVoice"
            },
            {
              "text": ", which must be a fully qualified path. The returned object is not retained. Returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if the ",
              "type": "text"
            },
            {
              "code": "NSDocument",
              "type": "codeVoice"
            },
            {
              "text": " subclass for ",
              "type": "text"
            },
            {
              "code": "docType",
              "type": "codeVoice"
            },
            {
              "text": " couldn’t be determined or if the object couldn’t be created. This method calls the ",
              "type": "text"
            },
            {
              "code": "NSDocument",
              "type": "codeVoice"
            },
            {
              "text": " method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfFile:ofType:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and is called by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfFile:display:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfFile:ofType:": {
      "abstract": [
        {
          "text": "Initializes and returns a document object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithContentsOfFile:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/initWithContentsOfFile:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithContentsOfFile:ofType:"
        }
      ],
      "role": "symbol",
      "title": "initWithContentsOfFile:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/initwithcontentsoffile:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController": {
      "abstract": [
        {
          "text": "An object that manages an app’s documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDocumentController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDocumentController"
        }
      ],
      "role": "symbol",
      "title": "NSDocumentController",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/documentForFileName:": {
      "abstract": [
        {
          "text": "Returns the document object for the file in which the document data is stored.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "documentForFileName:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/documentForFileName:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentForFileName:"
        }
      ],
      "role": "symbol",
      "title": "documentForFileName:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/documentforfilename:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileExtensionsFromType:": {
      "abstract": [
        {
          "text": "Returns the allowable file extensions for the given document type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "fileExtensionsFromType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileExtensionsFromType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileExtensionsFromType:"
        }
      ],
      "role": "symbol",
      "title": "fileExtensionsFromType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/fileextensionsfromtype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileNamesFromRunningOpenPanel": {
      "abstract": [
        {
          "text": "Returns a selection of files chosen by the user in the Open panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "fileNamesFromRunningOpenPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileNamesFromRunningOpenPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileNamesFromRunningOpenPanel"
        }
      ],
      "role": "symbol",
      "title": "fileNamesFromRunningOpenPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/filenamesfromrunningopenpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocument(withContentsOf:ofType:)": {
      "abstract": [
        {
          "text": "Instantiates a document located by a URL, of a specified type, and returns it if successful.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeDocument"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withContentsOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocument(withContentsOf:ofType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeDocumentWithContentsOfURL:ofType:error:"
        }
      ],
      "role": "symbol",
      "title": "makeDocument(withContentsOf:ofType:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/makedocument(withcontentsof:oftype:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfFile:ofType:": {
      "abstract": [
        {
          "text": "Creates and returns a document object of a given document type from the contents of a file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "makeDocumentWithContentsOfFile:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfFile:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeDocumentWithContentsOfFile:ofType:"
        }
      ],
      "role": "symbol",
      "title": "makeDocumentWithContentsOfFile:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/makedocumentwithcontentsoffile:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfURL:ofType:": {
      "abstract": [
        {
          "text": "Creates and returns a document object for the given document type from the contents of a given URL.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "makeDocumentWithContentsOfURL:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfURL:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeDocumentWithContentsOfURL:ofType:"
        }
      ],
      "role": "symbol",
      "title": "makeDocumentWithContentsOfURL:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/makedocumentwithcontentsofurl:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeUntitledDocumentOfType:": {
      "abstract": [
        {
          "text": "Creates and returns a document object for document type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "makeUntitledDocumentOfType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeUntitledDocumentOfType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeUntitledDocumentOfType:"
        }
      ],
      "role": "symbol",
      "title": "makeUntitledDocumentOfType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/makeuntitleddocumentoftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfFile:display:": {
      "abstract": [
        {
          "text": "Returns a document object created from the contents of a given file and optionally displays it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfFile:display:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfFile:display:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfFile:display:"
        }
      ],
      "role": "symbol",
      "title": "openDocumentWithContentsOfFile:display:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/opendocumentwithcontentsoffile:display:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:": {
      "abstract": [
        {
          "text": "Returns a document object created from the contents of a given URL and optionally displays it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfURL:display:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfURL:display:"
        }
      ],
      "role": "symbol",
      "title": "openDocumentWithContentsOfURL:display:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/opendocumentwithcontentsofurl:display:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:error:": {
      "abstract": [
        {
          "text": "Opens a document located by the given URL presents its user interface if requested, and returns the document if successful.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfURL:display:error:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfURL:display:error:"
        }
      ],
      "role": "symbol",
      "title": "openDocumentWithContentsOfURL:display:error:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/opendocumentwithcontentsofurl:display:error:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openUntitledDocumentOfType:display:": {
      "abstract": [
        {
          "text": "Returns a document object instantiated from the subclass of the given document type and optionally displays it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "openUntitledDocumentOfType:display:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openUntitledDocumentOfType:display:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openUntitledDocumentOfType:display:"
        }
      ],
      "role": "symbol",
      "title": "openUntitledDocumentOfType:display:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/openuntitleddocumentoftype:display:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/reopenDocumentForURL:withContentsOfURL:error:": {
      "abstract": [
        {
          "text": "Reopens an autosaved document located by a URL, by reading the contents for the document from another URL, presents its user interface, and returns ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " if successful.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "reopenDocumentForURL:withContentsOfURL:error:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/reopenDocumentForURL:withContentsOfURL:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reopenDocumentForURL:withContentsOfURL:error:"
        }
      ],
      "role": "symbol",
      "title": "reopenDocumentForURL:withContentsOfURL:error:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/reopendocumentforurl:withcontentsofurl:error:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/setShouldCreateUI:": {
      "abstract": [
        {
          "text": "Sets whether the window controllers of a document should be created when the document is created.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setShouldCreateUI:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/setShouldCreateUI:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setShouldCreateUI:"
        }
      ],
      "role": "symbol",
      "title": "setShouldCreateUI:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/setshouldcreateui:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/shouldCreateUI": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the window controllers of a document should be created when the document is created.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "shouldCreateUI"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/shouldCreateUI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldCreateUI"
        }
      ],
      "role": "symbol",
      "title": "shouldCreateUI",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/shouldcreateui"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/typeFromFileExtension:": {
      "abstract": [
        {
          "text": "Returns the document type associated with files having extension ",
          "type": "text"
        },
        {
          "code": "fileExtensionOrHFSFileType",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "typeFromFileExtension:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/typeFromFileExtension:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typeFromFileExtension:"
        }
      ],
      "role": "symbol",
      "title": "typeFromFileExtension:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/typefromfileextension:"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/documentForFileName:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileExtensionsFromType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileNamesFromRunningOpenPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeUntitledDocumentOfType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfURL:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfFile:display:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:error:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openUntitledDocumentOfType:display:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/reopenDocumentForURL:withContentsOfURL:error:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/setShouldCreateUI:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/shouldCreateUI",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/typeFromFileExtension:"
      ],
      "title": "Deprecated Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1makeDocument(withContentsOf:ofType:)/title",
          "value": "makeDocumentWithContentsOfURL:ofType:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1makeDocument(withContentsOf:ofType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "makeDocumentWithContentsOfURL:ofType:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController/title",
          "value": "NSDocumentController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocumentController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocumentController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdocumentcontroller/makedocumentwithcontentsoffile:oftype:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
