{
  "abstract": [
    {
      "text": "Opens a document located by the given URL presents its user interface if requested, and returns the document if successful.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocument(withContentsOf:display:completionHandler:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:error:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSDocumentController(im)openDocumentWithContentsOfURL:display:error:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "openDocumentWithContentsOfURL:display:error:"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "openDocumentWithContentsOfURL:display:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "openDocumentWithContentsOfURL:display:error:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "id"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "openDocumentWithContentsOfURL:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSURL",
              "text": "NSURL"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "url"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "display:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "displayDocument"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "error:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " * *) "
            },
            {
              "kind": "internalParam",
              "text": "outError"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If not  successful, the method returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " after setting ",
              "type": "text"
            },
            {
              "code": "outError",
              "type": "codeVoice"
            },
            {
              "text": " to point to an ",
              "type": "text"
            },
            {
              "code": "NSError",
              "type": "codeVoice"
            },
            {
              "text": " object that encapsulates the reason why the document could not be opened.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The default implementation of this method checks to see if the document is already open according to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/document(for:)-i5zi",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and if it is not open determines the type of the document, calls ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocument(withContentsOf:ofType:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to instantiate it, then calls ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/addDocument(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to record its opening, and sends the document ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/makeWindowControllers()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/showWindows()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " messages if ",
              "type": "text"
            },
            {
              "code": "displayDocument",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If the document is already open it is just sent a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/showWindows()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " message if ",
              "type": "text"
            },
            {
              "code": "displayDocument",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/makeWindowControllers()": {
      "abstract": [
        {
          "text": "Creates the window controller objects that the document uses to display its content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeWindowControllers"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/makeWindowControllers()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeWindowControllers"
        }
      ],
      "role": "symbol",
      "title": "makeWindowControllers()",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/makewindowcontrollers()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocument/showWindows()": {
      "abstract": [
        {
          "text": "Displays all of the document’s windows, bringing them to the front and making them main or key as necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showWindows"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocument/showWindows()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showWindows"
        }
      ],
      "role": "symbol",
      "title": "showWindows()",
      "type": "topic",
      "url": "/documentation/appkit/nsdocument/showwindows()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController": {
      "abstract": [
        {
          "text": "An object that manages an app’s documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDocumentController"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDocumentController"
        }
      ],
      "role": "symbol",
      "title": "NSDocumentController",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/addDocument(_:)": {
      "abstract": [
        {
          "text": "Adds the given document to the list of open documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addDocument"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/addDocument(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addDocument:"
        }
      ],
      "role": "symbol",
      "title": "addDocument(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/adddocument(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/document(for:)-i5zi": {
      "abstract": [
        {
          "text": "Returns, for a given URL, the open document whose file or file package is located by the URL, or ",
          "type": "text"
        },
        {
          "code": "nil",
          "type": "codeVoice"
        },
        {
          "text": " if there is no such open document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "document"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/document(for:)-i5zi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentForURL:"
        }
      ],
      "role": "symbol",
      "title": "document(for:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/document(for:)-i5zi"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/documentForFileName:": {
      "abstract": [
        {
          "text": "Returns the document object for the file in which the document data is stored.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "documentForFileName:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/documentForFileName:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentForFileName:"
        }
      ],
      "role": "symbol",
      "title": "documentForFileName:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/documentforfilename:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileExtensionsFromType:": {
      "abstract": [
        {
          "text": "Returns the allowable file extensions for the given document type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "fileExtensionsFromType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileExtensionsFromType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileExtensionsFromType:"
        }
      ],
      "role": "symbol",
      "title": "fileExtensionsFromType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/fileextensionsfromtype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileNamesFromRunningOpenPanel": {
      "abstract": [
        {
          "text": "Returns a selection of files chosen by the user in the Open panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "fileNamesFromRunningOpenPanel"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileNamesFromRunningOpenPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileNamesFromRunningOpenPanel"
        }
      ],
      "role": "symbol",
      "title": "fileNamesFromRunningOpenPanel",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/filenamesfromrunningopenpanel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocument(withContentsOf:ofType:)": {
      "abstract": [
        {
          "text": "Instantiates a document located by a URL, of a specified type, and returns it if successful.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeDocument"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withContentsOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocument(withContentsOf:ofType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeDocumentWithContentsOfURL:ofType:error:"
        }
      ],
      "role": "symbol",
      "title": "makeDocument(withContentsOf:ofType:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/makedocument(withcontentsof:oftype:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfFile:ofType:": {
      "abstract": [
        {
          "text": "Creates and returns a document object of a given document type from the contents of a file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "makeDocumentWithContentsOfFile:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfFile:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeDocumentWithContentsOfFile:ofType:"
        }
      ],
      "role": "symbol",
      "title": "makeDocumentWithContentsOfFile:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/makedocumentwithcontentsoffile:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfURL:ofType:": {
      "abstract": [
        {
          "text": "Creates and returns a document object for the given document type from the contents of a given URL.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "makeDocumentWithContentsOfURL:ofType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfURL:ofType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeDocumentWithContentsOfURL:ofType:"
        }
      ],
      "role": "symbol",
      "title": "makeDocumentWithContentsOfURL:ofType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/makedocumentwithcontentsofurl:oftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeUntitledDocumentOfType:": {
      "abstract": [
        {
          "text": "Creates and returns a document object for document type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "makeUntitledDocumentOfType:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeUntitledDocumentOfType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeUntitledDocumentOfType:"
        }
      ],
      "role": "symbol",
      "title": "makeUntitledDocumentOfType:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/makeuntitleddocumentoftype:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocument(withContentsOf:display:completionHandler:)": {
      "abstract": [
        {
          "text": "Opens a document located by a URL, optionally presents its user interface, and calls the passed-in completion handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openDocument"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withContentsOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "display"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDocument",
          "text": "NSDocument"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocument(withContentsOf:display:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfURL:display:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "openDocument(withContentsOf:display:completionHandler:)",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/opendocument(withcontentsof:display:completionhandler:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfFile:display:": {
      "abstract": [
        {
          "text": "Returns a document object created from the contents of a given file and optionally displays it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfFile:display:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfFile:display:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfFile:display:"
        }
      ],
      "role": "symbol",
      "title": "openDocumentWithContentsOfFile:display:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/opendocumentwithcontentsoffile:display:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:": {
      "abstract": [
        {
          "text": "Returns a document object created from the contents of a given URL and optionally displays it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfURL:display:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfURL:display:"
        }
      ],
      "role": "symbol",
      "title": "openDocumentWithContentsOfURL:display:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/opendocumentwithcontentsofurl:display:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:error:": {
      "abstract": [
        {
          "text": "Opens a document located by the given URL presents its user interface if requested, and returns the document if successful.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfURL:display:error:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openDocumentWithContentsOfURL:display:error:"
        }
      ],
      "role": "symbol",
      "title": "openDocumentWithContentsOfURL:display:error:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/opendocumentwithcontentsofurl:display:error:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openUntitledDocumentOfType:display:": {
      "abstract": [
        {
          "text": "Returns a document object instantiated from the subclass of the given document type and optionally displays it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "openUntitledDocumentOfType:display:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openUntitledDocumentOfType:display:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openUntitledDocumentOfType:display:"
        }
      ],
      "role": "symbol",
      "title": "openUntitledDocumentOfType:display:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/openuntitleddocumentoftype:display:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/reopenDocumentForURL:withContentsOfURL:error:": {
      "abstract": [
        {
          "text": "Reopens an autosaved document located by a URL, by reading the contents for the document from another URL, presents its user interface, and returns ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/swift/true",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " if successful.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "reopenDocumentForURL:withContentsOfURL:error:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/reopenDocumentForURL:withContentsOfURL:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reopenDocumentForURL:withContentsOfURL:error:"
        }
      ],
      "role": "symbol",
      "title": "reopenDocumentForURL:withContentsOfURL:error:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/reopendocumentforurl:withcontentsofurl:error:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/setShouldCreateUI:": {
      "abstract": [
        {
          "text": "Sets whether the window controllers of a document should be created when the document is created.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setShouldCreateUI:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/setShouldCreateUI:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setShouldCreateUI:"
        }
      ],
      "role": "symbol",
      "title": "setShouldCreateUI:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/setshouldcreateui:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/shouldCreateUI": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the window controllers of a document should be created when the document is created.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "shouldCreateUI"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/shouldCreateUI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldCreateUI"
        }
      ],
      "role": "symbol",
      "title": "shouldCreateUI",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/shouldcreateui"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/typeFromFileExtension:": {
      "abstract": [
        {
          "text": "Returns the document type associated with files having extension ",
          "type": "text"
        },
        {
          "code": "fileExtensionOrHFSFileType",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "typeFromFileExtension:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/typeFromFileExtension:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typeFromFileExtension:"
        }
      ],
      "role": "symbol",
      "title": "typeFromFileExtension:",
      "type": "topic",
      "url": "/documentation/appkit/nsdocumentcontroller/typefromfileextension:"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSURL": {
      "abstract": [
        {
          "text": "An object representing the location of a resource that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSURL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSURL",
      "type": "topic",
      "url": "/documentation/foundation/nsurl"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/documentForFileName:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileExtensionsFromType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/fileNamesFromRunningOpenPanel",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeUntitledDocumentOfType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfURL:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/makeDocumentWithContentsOfFile:ofType:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfFile:display:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openDocumentWithContentsOfURL:display:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/openUntitledDocumentOfType:display:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/reopenDocumentForURL:withContentsOfURL:error:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/setShouldCreateUI:",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/shouldCreateUI",
        "doc://com.apple.appkit/documentation/AppKit/NSDocumentController/typeFromFileExtension:"
      ],
      "title": "Deprecated Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1showWindows()/title",
          "value": "showWindows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1showWindows()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "showWindows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSURL/abstract",
          "value": [
            {
              "text": "An object that represents the location of a resource, such as an item on a remote server or the path to a local file. ",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1openDocument(withContentsOf:display:completionHandler:)/title",
          "value": "openDocumentWithContentsOfURL:display:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1openDocument(withContentsOf:display:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openDocumentWithContentsOfURL:display:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1makeWindowControllers()/title",
          "value": "makeWindowControllers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocument~1makeWindowControllers()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "makeWindowControllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController/title",
          "value": "NSDocumentController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocumentController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDocumentController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1makeDocument(withContentsOf:ofType:)/title",
          "value": "makeDocumentWithContentsOfURL:ofType:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1makeDocument(withContentsOf:ofType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "makeDocumentWithContentsOfURL:ofType:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1document(for:)-i5zi/title",
          "value": "documentForURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1document(for:)-i5zi/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentForURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1addDocument(_:)/title",
          "value": "addDocument:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDocumentController~1addDocument(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addDocument:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsdocumentcontroller/opendocumentwithcontentsofurl:display:error:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
