{
  "abstract": [
    {
      "text": "Constants that represent bitmap component formats.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSBitmapFormat",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Format"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Format"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSBitmapImageRep.Format"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Format"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can combine these values and pass them to the  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/init(bitmapDataPlanes:pixelsWide:pixelsHigh:bitsPerSample:samplesPerPixel:hasAlpha:isPlanar:colorSpaceName:bitmapFormat:bytesPerRow:bitsPerPixel:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method as the bitmap format. You can access them later in the  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/bitmapFormat",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NS16BitBigEndianBitmapFormat": {
      "abstract": [
        {
          "text": "A 16-bit, big endian format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NS16BitBigEndianBitmapFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NS16BitBigEndianBitmapFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "NS16BitBigEndianBitmapFormat",
      "type": "topic",
      "url": "/documentation/appkit/ns16bitbigendianbitmapformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NS16BitLittleEndianBitmapFormat": {
      "abstract": [
        {
          "text": "A 16-bit, little endian format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NS16BitLittleEndianBitmapFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NS16BitLittleEndianBitmapFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "NS16BitLittleEndianBitmapFormat",
      "type": "topic",
      "url": "/documentation/appkit/ns16bitlittleendianbitmapformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NS32BitBigEndianBitmapFormat": {
      "abstract": [
        {
          "text": "A 32-bit, big endian format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NS32BitBigEndianBitmapFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NS32BitBigEndianBitmapFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "NS32BitBigEndianBitmapFormat",
      "type": "topic",
      "url": "/documentation/appkit/ns32bitbigendianbitmapformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NS32BitLittleEndianBitmapFormat": {
      "abstract": [
        {
          "text": "A 32-bit, little endian format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NS32BitLittleEndianBitmapFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NS32BitLittleEndianBitmapFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "NS32BitLittleEndianBitmapFormat",
      "type": "topic",
      "url": "/documentation/appkit/ns32bitlittleendianbitmapformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAlphaFirstBitmapFormat": {
      "abstract": [
        {
          "text": "A format where the alpha value comes first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAlphaFirstBitmapFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlphaFirstBitmapFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAlphaFirstBitmapFormat",
      "type": "topic",
      "url": "/documentation/appkit/nsalphafirstbitmapformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAlphaNonpremultipliedBitmapFormat": {
      "abstract": [
        {
          "text": "A format where alpha values are not premultiplied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAlphaNonpremultipliedBitmapFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAlphaNonpremultipliedBitmapFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAlphaNonpremultipliedBitmapFormat",
      "type": "topic",
      "url": "/documentation/appkit/nsalphanonpremultipliedbitmapformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep": {
      "abstract": [
        {
          "text": "An object that renders an image from bitmap data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBitmapImageRep"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapImageRep"
        }
      ],
      "role": "symbol",
      "title": "NSBitmapImageRep",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format": {
      "abstract": [
        {
          "text": "Constants that represent bitmap component formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Format"
        }
      ],
      "role": "symbol",
      "title": "NSBitmapImageRep.Format",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/alphaFirst": {
      "abstract": [
        {
          "text": "A format where the alpha value comes first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alphaFirst"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBitmapFormat",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/alphaFirst",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapFormatAlphaFirst"
        }
      ],
      "role": "symbol",
      "title": "alphaFirst",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format/alphafirst"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/alphaNonpremultiplied": {
      "abstract": [
        {
          "text": "A format where alpha values are not premultiplied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alphaNonpremultiplied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBitmapFormat",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/alphaNonpremultiplied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapFormatAlphaNonpremultiplied"
        }
      ],
      "role": "symbol",
      "title": "alphaNonpremultiplied",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format/alphanonpremultiplied"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/floatingPointSamples": {
      "abstract": [
        {
          "text": "A format where samples are specified using floating-point numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "floatingPointSamples"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBitmapFormat",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/floatingPointSamples",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapFormatFloatingPointSamples"
        }
      ],
      "role": "symbol",
      "title": "floatingPointSamples",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format/floatingpointsamples"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new instance with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/sixteenBitBigEndian": {
      "abstract": [
        {
          "text": "A 16-bit, big endian format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sixteenBitBigEndian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBitmapFormat",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/sixteenBitBigEndian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapFormatSixteenBitBigEndian"
        }
      ],
      "role": "symbol",
      "title": "sixteenBitBigEndian",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format/sixteenbitbigendian"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/sixteenBitLittleEndian": {
      "abstract": [
        {
          "text": "A 16-bit, little endian format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sixteenBitLittleEndian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBitmapFormat",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/sixteenBitLittleEndian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapFormatSixteenBitLittleEndian"
        }
      ],
      "role": "symbol",
      "title": "sixteenBitLittleEndian",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format/sixteenbitlittleendian"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/thirtyTwoBitBigEndian": {
      "abstract": [
        {
          "text": "A 32-bit, big endian format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thirtyTwoBitBigEndian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBitmapFormat",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/thirtyTwoBitBigEndian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapFormatThirtyTwoBitBigEndian"
        }
      ],
      "role": "symbol",
      "title": "thirtyTwoBitBigEndian",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format/thirtytwobitbigendian"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/thirtyTwoBitLittleEndian": {
      "abstract": [
        {
          "text": "A 32-bit, little endian format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thirtyTwoBitLittleEndian"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBitmapFormat",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/thirtyTwoBitLittleEndian",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBitmapFormatThirtyTwoBitLittleEndian"
        }
      ],
      "role": "symbol",
      "title": "thirtyTwoBitLittleEndian",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/format/thirtytwobitlittleendian"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/bitmapFormat": {
      "abstract": [
        {
          "text": "The format of the bitmap image representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bitmapFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBitmapFormat",
          "text": "Format"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/bitmapFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bitmapFormat"
        }
      ],
      "role": "symbol",
      "title": "bitmapFormat",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/bitmapformat"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/bitsPerPixel": {
      "abstract": [
        {
          "text": "The number of bits allocated for each pixel in each plane of data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bitsPerPixel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/bitsPerPixel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bitsPerPixel"
        }
      ],
      "role": "symbol",
      "title": "bitsPerPixel",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/bitsperpixel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/bytesPerPlane": {
      "abstract": [
        {
          "text": "The number of bytes in each plane or channel of data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bytesPerPlane"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/bytesPerPlane",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bytesPerPlane"
        }
      ],
      "role": "symbol",
      "title": "bytesPerPlane",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/bytesperplane"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/bytesPerRow": {
      "abstract": [
        {
          "text": "The minimum number of bytes required to specify a scan line in each data plane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bytesPerRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/bytesPerRow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bytesPerRow"
        }
      ],
      "role": "symbol",
      "title": "bytesPerRow",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/bytesperrow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/init(bitmapDataPlanes:pixelsWide:pixelsHigh:bitsPerSample:samplesPerPixel:hasAlpha:isPlanar:colorSpaceName:bitmapFormat:bytesPerRow:bitsPerPixel:)": {
      "abstract": [
        {
          "text": "Initializes a newly allocated bitmap image representation so it can render the specified image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "bitmapDataPlanes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ">?>?, "
        },
        {
          "kind": "externalParam",
          "text": "pixelsWide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "pixelsHigh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "bitsPerSample"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "samplesPerPixel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "hasAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "isPlanar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "colorSpaceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSColorSpaceName",
          "text": "NSColorSpaceName"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "bitmapFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBitmapImageRep",
          "text": "NSBitmapImageRep"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBitmapFormat",
          "text": "Format"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "bytesPerRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "bitsPerPixel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/init(bitmapDataPlanes:pixelsWide:pixelsHigh:bitsPerSample:samplesPerPixel:hasAlpha:isPlanar:colorSpaceName:bitmapFormat:bytesPerRow:bitsPerPixel:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithBitmapDataPlanes:pixelsWide:pixelsHigh:bitsPerSample:samplesPerPixel:hasAlpha:isPlanar:colorSpaceName:bitmapFormat:bytesPerRow:bitsPerPixel:"
        }
      ],
      "role": "symbol",
      "title": "init(bitmapDataPlanes:pixelsWide:pixelsHigh:bitsPerSample:samplesPerPixel:hasAlpha:isPlanar:colorSpaceName:bitmapFormat:bytesPerRow:bitsPerPixel:)",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/init(bitmapdataplanes:pixelswide:pixelshigh:bitspersample:samplesperpixel:hasalpha:isplanar:colorspacename:bitmapformat:bytesperrow:bitsperpixel:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/isPlanar": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the image data is in a planar configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPlanar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/isPlanar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "planar"
        }
      ],
      "role": "symbol",
      "title": "isPlanar",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/isplanar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/numberOfPlanes": {
      "abstract": [
        {
          "text": "The number of separate planes into which the image data is organized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfPlanes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/numberOfPlanes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfPlanes"
        }
      ],
      "role": "symbol",
      "title": "numberOfPlanes",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/numberofplanes"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/samplesPerPixel": {
      "abstract": [
        {
          "text": "The number of components for each pixel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "samplesPerPixel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/samplesPerPixel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "samplesPerPixel"
        }
      ],
      "role": "symbol",
      "title": "samplesPerPixel",
      "type": "topic",
      "url": "/documentation/appkit/nsbitmapimagerep/samplesperpixel"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFloatingPointSamplesBitmapFormat": {
      "abstract": [
        {
          "text": "A format where samples are specified using floating-point numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFloatingPointSamplesBitmapFormat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFloatingPointSamplesBitmapFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFloatingPointSamplesBitmapFormat",
      "type": "topic",
      "url": "/documentation/appkit/nsfloatingpointsamplesbitmapformat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Information-About-Images",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/bitmapFormat",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/bitsPerPixel",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/bytesPerPlane",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/bytesPerRow",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/isPlanar",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/numberOfPlanes",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/samplesPerPixel"
      ],
      "title": "Getting Information About Images"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/alphaFirst",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/alphaNonpremultiplied",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/floatingPointSamples",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/sixteenBitBigEndian",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/sixteenBitLittleEndian",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/thirtyTwoBitBigEndian",
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/thirtyTwoBitLittleEndian"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSBitmapFormat"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/alphaFirst",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/alphaNonpremultiplied",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/floatingPointSamples",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/sixteenBitBigEndian",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/sixteenBitLittleEndian",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/thirtyTwoBitBigEndian",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/Format/thirtyTwoBitLittleEndian"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Deprecated-Constants",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAlphaFirstBitmapFormat",
                "doc://com.apple.appkit/documentation/AppKit/NSAlphaNonpremultipliedBitmapFormat",
                "doc://com.apple.appkit/documentation/AppKit/NSFloatingPointSamplesBitmapFormat",
                "doc://com.apple.appkit/documentation/AppKit/NS16BitLittleEndianBitmapFormat",
                "doc://com.apple.appkit/documentation/AppKit/NS32BitLittleEndianBitmapFormat",
                "doc://com.apple.appkit/documentation/AppKit/NS16BitBigEndianBitmapFormat",
                "doc://com.apple.appkit/documentation/AppKit/NS32BitBigEndianBitmapFormat"
              ],
              "title": "Deprecated Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Information-About-Images",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/bitmapFormat",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/bitsPerPixel",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/bytesPerPlane",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/bytesPerRow",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/isPlanar",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/numberOfPlanes",
                "doc://com.apple.appkit/documentation/AppKit/NSBitmapImageRep/samplesPerPixel"
              ],
              "title": "Getting Information About Images"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSBitmapFormat"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep/title",
          "value": "NSBitmapImageRep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapImageRep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1bytesPerRow/title",
          "value": "bytesPerRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1bytesPerRow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bytesPerRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1thirtyTwoBitBigEndian/title",
          "value": "NSBitmapFormatThirtyTwoBitBigEndian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1thirtyTwoBitBigEndian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormatThirtyTwoBitBigEndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1bitsPerPixel/title",
          "value": "bitsPerPixel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1bitsPerPixel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bitsPerPixel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1samplesPerPixel/title",
          "value": "samplesPerPixel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1samplesPerPixel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "samplesPerPixel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1init(bitmapDataPlanes:pixelsWide:pixelsHigh:bitsPerSample:samplesPerPixel:hasAlpha:isPlanar:colorSpaceName:bitmapFormat:bytesPerRow:bitsPerPixel:)/title",
          "value": "initWithBitmapDataPlanes:pixelsWide:pixelsHigh:bitsPerSample:samplesPerPixel:hasAlpha:isPlanar:colorSpaceName:bitmapFormat:bytesPerRow:bitsPerPixel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1init(bitmapDataPlanes:pixelsWide:pixelsHigh:bitsPerSample:samplesPerPixel:hasAlpha:isPlanar:colorSpaceName:bitmapFormat:bytesPerRow:bitsPerPixel:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithBitmapDataPlanes:pixelsWide:pixelsHigh:bitsPerSample:samplesPerPixel:hasAlpha:isPlanar:colorSpaceName:bitmapFormat:bytesPerRow:bitsPerPixel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1thirtyTwoBitLittleEndian/title",
          "value": "NSBitmapFormatThirtyTwoBitLittleEndian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1thirtyTwoBitLittleEndian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormatThirtyTwoBitLittleEndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1bytesPerPlane/title",
          "value": "bytesPerPlane"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1bytesPerPlane/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bytesPerPlane"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1numberOfPlanes/title",
          "value": "numberOfPlanes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1numberOfPlanes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfPlanes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1isPlanar/title",
          "value": "planar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1isPlanar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "planar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1sixteenBitBigEndian/title",
          "value": "NSBitmapFormatSixteenBitBigEndian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1sixteenBitBigEndian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormatSixteenBitBigEndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1sixteenBitLittleEndian/title",
          "value": "NSBitmapFormatSixteenBitLittleEndian"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1sixteenBitLittleEndian/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormatSixteenBitLittleEndian"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1alphaFirst/title",
          "value": "NSBitmapFormatAlphaFirst"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1alphaFirst/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormatAlphaFirst"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format/title",
          "value": "NSBitmapFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1floatingPointSamples/title",
          "value": "NSBitmapFormatFloatingPointSamples"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1floatingPointSamples/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormatFloatingPointSamples"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1bitmapFormat/title",
          "value": "bitmapFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1bitmapFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bitmapFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1alphaNonpremultiplied/title",
          "value": "NSBitmapFormatAlphaNonpremultiplied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSBitmapImageRep~1Format~1alphaNonpremultiplied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBitmapFormatAlphaNonpremultiplied"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbitmapimagerep/format"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsbitmapimagerep/format"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
