{
  "abstract": [
    {
      "text": "Deselects the currently selected text in the web document.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WebDocumentText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WebDocumentText/deselectAll()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)WebDocumentText(im)deselectAll",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "deselectAll"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "deselectAll"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.14",
        "introducedAt": "10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "deselectAll()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "deselectAll"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebDocumentText": {
      "abstract": [
        {
          "code": "WebDocumentText",
          "type": "codeVoice"
        },
        {
          "text": " is an optional protocol for document view objects that display text. This protocol defines methods for accessing document content as strings, and methods for text selection. Classes that adopt this protocol should also adopt ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDocumentView",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and inherit from ",
          "type": "text"
        },
        {
          "code": "NSView",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebDocumentText"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDocumentText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebDocumentText"
        }
      ],
      "role": "symbol",
      "title": "WebDocumentText",
      "type": "topic",
      "url": "/documentation/webkit/webdocumenttext"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebDocumentText/deselectAll()": {
      "abstract": [
        {
          "text": "Deselects the currently selected text in the web document.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deselectAll"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDocumentText/deselectAll()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deselectAll"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "deselectAll()",
      "type": "topic",
      "url": "/documentation/webkit/webdocumenttext/deselectall()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebDocumentText/selectAll()": {
      "abstract": [
        {
          "text": "Selects all the text in the web document.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectAll"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDocumentText/selectAll()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectAll"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "selectAll()",
      "type": "topic",
      "url": "/documentation/webkit/webdocumenttext/selectall()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebDocumentText/selectedAttributedString()": {
      "abstract": [
        {
          "text": "Returns the currently selected text in the web document as an attributed string.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedAttributedString"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDocumentText/selectedAttributedString()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedAttributedString"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "selectedAttributedString()",
      "type": "topic",
      "url": "/documentation/webkit/webdocumenttext/selectedattributedstring()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebDocumentText/selectedString()": {
      "abstract": [
        {
          "text": "Returns the currently selected text in the web document as a string.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedString"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDocumentText/selectedString()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedString"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "selectedString()",
      "type": "topic",
      "url": "/documentation/webkit/webdocumenttext/selectedstring()"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebDocumentView": {
      "abstract": [
        {
          "text": "This protocol is adopted by the document view of a ",
          "type": "text"
        },
        {
          "code": "WebFrameView",
          "type": "codeVoice"
        },
        {
          "text": ". You can extend WebKit to support additional MIME types by implementing your own document view and document representation classes to render data for specific MIME types. You register those classes using the WebFrame ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebView/registerClass(_:representationClass:forMIMEType:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method. Classes that adopt this protocol are expected to be subclasses of ",
          "type": "text"
        },
        {
          "code": "NSView",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebDocumentView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebDocumentView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebDocumentView"
        }
      ],
      "role": "symbol",
      "title": "WebDocumentView",
      "type": "topic",
      "url": "/documentation/webkit/webdocumentview"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Selecting-and-deselecting-text",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebDocumentText/selectAll()",
        "doc://com.apple.webkit/documentation/WebKit/WebDocumentText/selectedString()",
        "doc://com.apple.webkit/documentation/WebKit/WebDocumentText/selectedAttributedString()"
      ],
      "title": "Selecting and deselecting text"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.14",
              "introducedAt": "10.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "deselectAll"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deselectAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit",
                "doc://com.apple.webkit/documentation/WebKit/WebDocumentText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Selecting-and-deselecting-text",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WebDocumentText/selectAll()",
                "doc://com.apple.webkit/documentation/WebKit/WebDocumentText/selectedString()",
                "doc://com.apple.webkit/documentation/WebKit/WebDocumentText/selectedAttributedString()"
              ],
              "title": "Selecting and deselecting text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "deselectAll"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentText~1deselectAll()/title",
          "value": "deselectAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentText~1deselectAll()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deselectAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentText/title",
          "value": "WebDocumentText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDocumentText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentText/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDocumentText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentView/title",
          "value": "WebDocumentView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDocumentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebDocumentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentText~1selectedString()/title",
          "value": "selectedString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentText~1selectedString()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectedString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentText~1selectedAttributedString()/title",
          "value": "selectedAttributedString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentText~1selectedAttributedString()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectedAttributedString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentText~1selectAll()/title",
          "value": "selectAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebDocumentText~1selectAll()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectAll"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/webdocumenttext/deselectall()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/webdocumenttext/deselectall()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
