{
  "abstract": [
    {
      "text": "An invalid state transition error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.virtualization/documentation/Virtualization",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineStateTransition"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@VZErrorCode@VZErrorInvalidVirtualMachineStateTransition",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidVirtualMachineStateTransition"
      }
    ],
    "modules": [
      {
        "name": "Virtualization"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VZErrorInvalidVirtualMachineStateTransition"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "VZError.Code.invalidVirtualMachineStateTransition"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidVirtualMachineStateTransition"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This error occurs when you attempt to change the state of the virtual machine in an invalid way. For example, it occurs when you attempt to start a virtual machine when its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canStart",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.virtualization/documentation/Virtualization": {
      "abstract": [
        {
          "text": "Create virtual machines and run macOS and Linux-based operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization",
      "kind": "symbol",
      "role": "collection",
      "title": "Virtualization",
      "type": "topic",
      "url": "/documentation/virtualization"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError": {
      "abstract": [
        {
          "text": "Errors that you might encounter when configuring or using a VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VZError"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZError"
        }
      ],
      "role": "symbol",
      "title": "VZError",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code": {
      "abstract": [
        {
          "text": "Errors you might encounter when configuring or using a virtual machine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationFailed": {
      "abstract": [
        {
          "text": "An error occurred during installation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "installationFailed"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInstallationFailed"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.installationFailed",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/installationfailed"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationRequiresUpdate": {
      "abstract": [
        {
          "text": "The VM requires a software update in order to complete the installation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "installationRequiresUpdate"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationRequiresUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInstallationRequiresUpdate"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.installationRequiresUpdate",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/installationrequiresupdate"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/internalError": {
      "abstract": [
        {
          "text": "An internal error, such as the VM unexpectedly stopping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/internalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInternal"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.internalError",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/internalerror"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidDiskImage": {
      "abstract": [
        {
          "text": "An invalid disk-image error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidDiskImage"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidDiskImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInvalidDiskImage"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.invalidDiskImage",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/invaliddiskimage"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImage": {
      "abstract": [
        {
          "text": "The restore image is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidRestoreImage"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInvalidRestoreImage"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.invalidRestoreImage",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/invalidrestoreimage"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImageCatalog": {
      "abstract": [
        {
          "text": "The restore image catalog is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidRestoreImageCatalog"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImageCatalog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInvalidRestoreImageCatalog"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.invalidRestoreImageCatalog",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/invalidrestoreimagecatalog"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineConfiguration": {
      "abstract": [
        {
          "text": "An invalid configuration error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVirtualMachineConfiguration"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInvalidVirtualMachineConfiguration"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.invalidVirtualMachineConfiguration",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/invalidvirtualmachineconfiguration"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineState": {
      "abstract": [
        {
          "text": "An invalid state error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVirtualMachineState"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInvalidVirtualMachineState"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.invalidVirtualMachineState",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/invalidvirtualmachinestate"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineStateTransition": {
      "abstract": [
        {
          "text": "An invalid state transition error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidVirtualMachineStateTransition"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineStateTransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorInvalidVirtualMachineStateTransition"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.invalidVirtualMachineStateTransition",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/invalidvirtualmachinestatetransition"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkError": {
      "abstract": [
        {
          "text": "A network error, such as a failed connection error, occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkError"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorNetworkError"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.networkError",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/networkerror"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/noSupportedRestoreImagesInCatalog": {
      "abstract": [
        {
          "text": "The restore image catalog has no supported restore images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSupportedRestoreImagesInCatalog"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/noSupportedRestoreImagesInCatalog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorNoSupportedRestoreImagesInCatalog"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.noSupportedRestoreImagesInCatalog",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/nosupportedrestoreimagesincatalog"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/notSupported": {
      "abstract": [
        {
          "text": "The host computer or operating system isn’t supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/notSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorNotSupported"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.notSupported",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/notsupported"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/operationCancelled": {
      "abstract": [
        {
          "text": "The code that indicates user canceled the installation of Rosetta or the app canceled the installation of a guest OS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationCancelled"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/operationCancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorOperationCancelled"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.operationCancelled",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/operationcancelled"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/outOfDiskSpace": {
      "abstract": [
        {
          "text": "The host is out of disk space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfDiskSpace"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/outOfDiskSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorOutOfDiskSpace"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.outOfDiskSpace",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/outofdiskspace"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restoreImageCatalogLoadFailed": {
      "abstract": [
        {
          "text": "The restore image catalog failed to load.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restoreImageCatalogLoadFailed"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restoreImageCatalogLoadFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorRestoreImageCatalogLoadFailed"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.restoreImageCatalogLoadFailed",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/restoreimagecatalogloadfailed"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/virtualMachineLimitExceeded": {
      "abstract": [
        {
          "text": "Unable to create an additional VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "virtualMachineLimitExceeded"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/virtualMachineLimitExceeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VZErrorVirtualMachineLimitExceeded"
        }
      ],
      "role": "symbol",
      "title": "VZError.Code.virtualMachineLimitExceeded",
      "type": "topic",
      "url": "/documentation/virtualization/vzerror/code/virtualmachinelimitexceeded"
    },
    "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canStart": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can start the VM.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.virtualization/documentation/Virtualization/VZVirtualMachine/canStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canStart"
        }
      ],
      "role": "symbol",
      "title": "canStart",
      "type": "topic",
      "url": "/documentation/virtualization/vzvirtualmachine/canstart"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/internalError",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineConfiguration",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineState",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidDiskImage",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/virtualMachineLimitExceeded",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkError",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/notSupported",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/outOfDiskSpace",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/operationCancelled",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationFailed",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationRequiresUpdate",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImage",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImageCatalog",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/noSupportedRestoreImagesInCatalog",
        "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restoreImageCatalogLoadFailed"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VZErrorInvalidVirtualMachineStateTransition"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInvalidVirtualMachineStateTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.virtualization/documentation/Virtualization",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/internalError",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineConfiguration",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidVirtualMachineState",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidDiskImage",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/virtualMachineLimitExceeded",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/networkError",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/notSupported",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/outOfDiskSpace",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/operationCancelled",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationFailed",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/installationRequiresUpdate",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImage",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/invalidRestoreImageCatalog",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/noSupportedRestoreImagesInCatalog",
                "doc://com.apple.virtualization/documentation/Virtualization/VZError/Code/restoreImageCatalogLoadFailed"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "VZErrorInvalidVirtualMachineStateTransition"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code/title",
          "value": "VZErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidVirtualMachineState/title",
          "value": "VZErrorInvalidVirtualMachineState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidVirtualMachineState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInvalidVirtualMachineState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidDiskImage/title",
          "value": "VZErrorInvalidDiskImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidDiskImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInvalidDiskImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1canStart/title",
          "value": "canStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZVirtualMachine~1canStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidRestoreImageCatalog/title",
          "value": "VZErrorInvalidRestoreImageCatalog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidRestoreImageCatalog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInvalidRestoreImageCatalog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1networkError/title",
          "value": "VZErrorNetworkError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1networkError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorNetworkError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1outOfDiskSpace/title",
          "value": "VZErrorOutOfDiskSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1outOfDiskSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorOutOfDiskSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1internalError/title",
          "value": "VZErrorInternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1internalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInternal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidVirtualMachineConfiguration/title",
          "value": "VZErrorInvalidVirtualMachineConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidVirtualMachineConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInvalidVirtualMachineConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidVirtualMachineStateTransition/title",
          "value": "VZErrorInvalidVirtualMachineStateTransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidVirtualMachineStateTransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInvalidVirtualMachineStateTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidRestoreImage/title",
          "value": "VZErrorInvalidRestoreImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1invalidRestoreImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInvalidRestoreImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1installationRequiresUpdate/title",
          "value": "VZErrorInstallationRequiresUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1installationRequiresUpdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInstallationRequiresUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1noSupportedRestoreImagesInCatalog/title",
          "value": "VZErrorNoSupportedRestoreImagesInCatalog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1noSupportedRestoreImagesInCatalog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorNoSupportedRestoreImagesInCatalog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1installationFailed/title",
          "value": "VZErrorInstallationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1installationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorInstallationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1virtualMachineLimitExceeded/title",
          "value": "VZErrorVirtualMachineLimitExceeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1virtualMachineLimitExceeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorVirtualMachineLimitExceeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1operationCancelled/title",
          "value": "VZErrorOperationCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1operationCancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorOperationCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1restoreImageCatalogLoadFailed/title",
          "value": "VZErrorRestoreImageCatalogLoadFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1restoreImageCatalogLoadFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorRestoreImageCatalogLoadFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1notSupported/title",
          "value": "VZErrorNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.virtualization~1documentation~1Virtualization~1VZError~1Code~1notSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VZErrorNotSupported"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/virtualization/vzerror/code/invalidvirtualmachinestatetransition"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/virtualization/vzerror/code/invalidvirtualmachinestatetransition"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
