{
  "abstract": [
    {
      "text": "Support modern iOS features that result in a better user experience when running",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "on Apple silicon.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Apple-Silicon/documentation/apple-silicon"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Apple-Silicon/documentation/Apple-Silicon/adapting-ios-code-to-run-in-the-macos-environment"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Adapting iOS code to run in the macOS environment"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Most iOS apps require no modifications to run on Apple silicon. In macOS, the system",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "maps iOS behaviors to appropriate macOS behaviors using infrastructure already in",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "place to support Mac Catalyst. However, you might still want to update your code",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to account for differences between the iOS and macOS environments. For example, while",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the system matches touch events to mouse events, macOS supports only one such event",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "at a time, whereas iOS supports multiple simultaneous touches. Making minor adjustments",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for environment differences, and providing alternatives for missing capabilities,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "ensures your app runs well on both platforms.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For general information about how to create iOS apps that run in macOS, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Apple-Silicon/documentation/Apple-Silicon/running-your-ios-apps-in-macos",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Check-device-properties-and-hardware-availability-dynamically",
          "level": 3,
          "text": "Check device properties and hardware availability dynamically",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "macOS provides versions of all iOS frameworks for your app to link with, but some",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "features of those frameworks may be unavailable in macOS. In particular, frameworks",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "that interact with iOS-specific hardware, such as Core Motion and ARKit, return errors",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "when you try to use features that aren’t available. Similarly, macOS doesn’t support frameworks like HomeKit, and you receive errors when you use them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Before you attempt to use any sensor or feature in your iOS app, always check whether",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "it’s available. The following list includes some of the more common APIs to call:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Check the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreMotion/CMMotionManager/isAccelerometerAvailable",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ",",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreMotion/CMMotionManager/isGyroAvailable",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ",",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreMotion/CMMotionManager/isMagnetometerAvailable",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "properties of the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CoreMotion/CMMotionManager",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "object to determine the availability of those sensors.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Check for appropriate camera support in ARKit using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARConfiguration/isSupported",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "property of the appropriate ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARConfiguration",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "subclass.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Identify the available cameras on the device using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/DiscoverySession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "class. Don’t assume a device contains a front- or rear-facing camera.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use Core Location to fetch location data as you do in iOS. Core Location doesn’t",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "require GPS hardware to get the current location. However, the locations you receive",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "may not be as precise when GPS is unavailable.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Call the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkhealthstore/1614180-ishealthdataavailable",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "method of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/HealthKit/HKHealthStore",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "determine whether health-related data is available.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Check the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/HomeKit/HMHomeManager/authorizationStatus",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "property of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/HomeKit/HMHomeManager",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "see whether your app is able to access HomeKit.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Handle-unknown-device-types-gracefully",
          "level": 3,
          "text": "Handle unknown device types gracefully",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Some system APIs provide information about the underlying type of device, but such",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "information is rarely the best way to make decisions. A decision based on a device",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "type creates problems whenever your app runs on an unknown device, as might be the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "case for some lower-level system APIs. The better alternative is to use hard data",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "that relates directly to the current task. For example, use size classes to determine",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "whether to display an expanded or minimal version of your app’s interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you do need to know the device type, use higher-level APIs whenever possible.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "In macOS, the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UITraitCollection",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIDevice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " classes report the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "following iOS idiom types instead of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIUserInterfaceIdiom/mac",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For an app deployable on iPad, the idiom type is always ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIUserInterfaceIdiom/pad",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For an app deployable only on iPhone, and not on iPad, the idiom type is ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIUserInterfaceIdiom/phone",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Any time you use device-specific information to make decisions, provide reasonable",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "default behavior for unrecognized values. Although UIKit returns expected iOS values,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "other system APIs may not. In particular, lower-level APIs might return values that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "are appropriate for Mac devices, but may not be common on iOS devices. Run your app in macOS",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to see what kind of values you get for hardware-specific information, and use that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "information to determine a reasonable approach.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Support-multiple-windows-using-scenes",
          "level": 3,
          "text": "Support multiple windows using scenes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The macOS desktop makes it easy for an app to display multiple windows simultaneously,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and many apps use that support to display different documents side-by-side. Most",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "iOS apps display a single window, but the introduction of scenes in iOS 13 and iPadOS",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "13 provides an equivalent type of multiwindow support to iOS apps. Because supporting",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "multiple windows requires you to manage your data differently, you must tell the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "system that your app supports multiple scenes. If you opt in, your app gains automatic",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "support for multiple windows in macOS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To enable multiple scenes in iOS, add the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UIApplicationSupportsMultipleScenes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "key with the value of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your app’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file. The presence of this key tells macOS to enable multiple",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "window support for your app. For information about how to add scene support to your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/supporting-multiple-windows-on-ipad",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Make-your-windows-resizable-using-iPad-multitasking",
          "level": 3,
          "text": "Make your windows resizable using iPad multitasking",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In iPadOS, iPad multitasking lets a person display multiple apps onscreen at once,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "with each app occupying a specific portion of the available screen space. When they initiate this feature, or change the relative size of the apps, the system",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "resizes the app’s window accordingly. These resize events cause the app to lay out",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "its content using the new window size. macOS leverages this same infrastructure to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "support resizable windows for your apps.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your app already supports iPad multitasking, you don’t need to do any extra work",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to enable resizable windows in macOS. If your app doesn’t support iPad multitasking,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "add support by doing the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Implement view controllers that support both compact and regular size classes.",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "Size classes help you adapt your interface to particularly large or small window",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "sizes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Lay out your views to fit the current window size. Optimize your Auto Layout constraints",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "to improve resizing speeds.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Support all device orientations.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Don’t include the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIRequiresFullScreen",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "key in your app’s ",
                      "type": "text"
                    },
                    {
                      "code": "Info.plist",
                      "type": "codeVoice"
                    },
                    {
                      "text": " file.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An app that you build to deploy only on iPhone always runs in a fixed-size window.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about iPad multitasking, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/multitasking-on-ipad",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Support-native-resolution-of-a-Mac-display-in-full-screen-mode",
          "level": 3,
          "text": "Support native resolution of a Mac display in full-screen mode",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you choose to not support iPad multitasking in your app — for example, your iPad app is a game designed for full-screen mode — you can provide a pixel-perfect, edge-to-edge, full-screen experience on a Mac by including the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " keys in your app’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Dont-make-assumptions-about-system-provided-UI",
          "level": 3,
          "text": "Don’t make assumptions about system-provided UI",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "UIKit and other frameworks provide standard system alerts and view controllers for",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you to display from your apps. These interfaces include assorted pickers, such as",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "file and color pickers, and view controllers that display standard interfaces, such",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "as the activity view controller. At display time, macOS may present these interfaces",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "differently than iOS does. For example, macOS uses its standard Open and Save panels",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for picking files.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When displaying a system interface from your app, use only the provided APIs to display",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and interact with the interface. The implementation of system interfaces may change",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "from release to release, and from platform to platform. Don’t make assumptions about",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "how the system presents the interface, or about the size, position, or number of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "views in that interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Provide-keyboard-shortcuts-for-your-apps-features",
          "level": 3,
          "text": "Provide keyboard shortcuts for your app’s features",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Consider adding keyboard shortcuts to trigger common behaviors and features of your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "iOS app. Keyboard input is a common way to initiate actions in macOS, and it’s also",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a useful way to trigger actions on iOS devices with a connected keyboard. In addition,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "keyboard input is a way to work around the lack of custom multifinger gestures in",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "macOS. Use your keyboard code to trigger the same action as your custom gesture recognizer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can add keyboard support to any iOS app, not just apps you build with Mac Catalyst.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To handle specific key combinations, override the appropriate press-event methods",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIResponder",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. For",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "more information about how to add keyboard support to your app, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/handling-key-presses-made-on-a-physical-keyboard",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Look-for-files-in-well-known-directories",
          "level": 3,
          "text": "Look for files in well-known directories",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Be aware of differences between the iOS and macOS file systems, and take those differences",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "into account when accessing files and directories:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A person using iOS has limited access to files, but a person using macOS has access to all",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "files and directories in the Finder or Terminal. They may directly examine the contents",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "of any directory, including your app’s data container.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "On a Mac, a person may move apps anywhere.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Don’t assume that your app or data container is always at a specific location. When",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you write code to access the file system, always use Foundation APIs to get the URL",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for your app and data directories. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/filemanager/1407693-url",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "method of the default ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/filemanager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "object returns a URL that’s appropriate for the current platform.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Migrate-away-from-deprecated-technologies",
          "level": 3,
          "text": "Migrate away from deprecated technologies",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "macOS supports nearly all iOS frameworks, including many that are deprecated. However,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "deprecated frameworks don’t receive active updates and bug fixes, and might not behave",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "as expected in macOS. Therefore, migrate away from deprecated frameworks whenever",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "possible and use modern replacements instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following frameworks and features are deprecated with appropriate replacements:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AddressBook",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " — Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Contacts",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "instead.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AddressBookUI",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " — Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/ContactsUI",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "instead.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AssetsLibrary",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " — Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/PhotoKit",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "instead.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "OpenGLES — Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/Metal",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " instead.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.documentation/documentation/GLKit",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " — Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/MetalKit",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "instead.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Socket-based VoIP support — Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/PushKit",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "instead.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Xcode issues warnings when you build your code with deprecated APIs. The documentation",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and headers also include information about which frameworks and APIs are deprecated,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and what the appropriate replacements are. Update your iOS app to use the designated",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "replacements as soon as possible.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Apple-Silicon/documentation/Apple-Silicon/running-your-ios-apps-in-macos": {
      "abstract": [
        {
          "text": "Modernize the iOS apps you choose to run on a Mac with Apple silicon, or opt out of",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "running on a Mac altogether.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Apple-Silicon/documentation/Apple-Silicon/running-your-ios-apps-in-macos",
      "kind": "article",
      "role": "article",
      "title": "Running your iOS apps in macOS",
      "type": "topic",
      "url": "/documentation/apple-silicon/running-your-ios-apps-in-macos"
    },
    "doc://com.apple.Apple-Silicon/documentation/apple-silicon": {
      "abstract": [
        {
          "text": "Get the resources you need to create software for Macs with Apple silicon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Apple-Silicon/documentation/apple-silicon",
      "kind": "article",
      "role": "collection",
      "title": "Apple Silicon",
      "type": "topic",
      "url": "/documentation/apple-silicon"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARConfiguration": {
      "abstract": [
        {
          "text": "The base object that contains information about how to configure an augmented reality session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARConfiguration"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARConfiguration",
      "type": "topic",
      "url": "/documentation/ARKit/ARConfiguration"
    },
    "doc://com.apple.documentation/documentation/ARKit/ARConfiguration/isSupported": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the current device supports this session configuration class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit/ARConfiguration/isSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "isSupported",
      "type": "topic",
      "url": "/documentation/ARKit/ARConfiguration/isSupported"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/DiscoverySession": {
      "abstract": [
        {
          "text": "An object that finds capture devices that match specific search criteria.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DiscoverySession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/DiscoverySession",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVCaptureDevice.DiscoverySession",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCaptureDevice/DiscoverySession"
    },
    "doc://com.apple.documentation/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/AddressBook"
    },
    "doc://com.apple.documentation/documentation/AddressBookUI": {
      "abstract": [
        {
          "text": "Access users’ contacts and display them in a graphical interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AddressBookUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book UI",
      "type": "topic",
      "url": "/documentation/AddressBookUI"
    },
    "doc://com.apple.documentation/documentation/AssetsLibrary": {
      "abstract": [
        {
          "text": "Access the assets in a user’s media library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AssetsLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "Assets Library",
      "type": "topic",
      "url": "/documentation/AssetsLibrary"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UIApplicationSupportsMultipleScenes": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app supports two or more scenes simultaneously.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UIApplicationSupportsMultipleScenes",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplicationSupportsMultipleScenes",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest/UIApplicationSupportsMultipleScenes"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to launch your iPad app in full-screen mode when running on a Mac.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac",
      "kind": "symbol",
      "role": "symbol",
      "title": "UILaunchToFullScreenByDefaultOnMac",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIRequiresFullScreen": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an iPad app is capable of sharing the screen with other apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIRequiresFullScreen",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIRequiresFullScreen",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/UIRequiresFullScreen"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your iPad app supports arbitrary screen sizes and resolutions when running on a Mac.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac",
      "kind": "symbol",
      "role": "symbol",
      "title": "UISupportsTrueScreenSizeOnMac",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac"
    },
    "doc://com.apple.documentation/documentation/Contacts": {
      "abstract": [
        {
          "text": "Access the user’s contacts, and format and localize contact information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Contacts",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts",
      "type": "topic",
      "url": "/documentation/Contacts"
    },
    "doc://com.apple.documentation/documentation/ContactsUI": {
      "abstract": [
        {
          "text": "Provide an interface that allows people to display information about their contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ContactsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Contacts UI",
      "type": "topic",
      "url": "/documentation/ContactsUI"
    },
    "doc://com.apple.documentation/documentation/CoreMotion/CMMotionManager": {
      "abstract": [
        {
          "text": "The object for starting and managing motion services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMotionManager"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMotion/CMMotionManager",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMMotionManager",
      "type": "topic",
      "url": "/documentation/CoreMotion/CMMotionManager"
    },
    "doc://com.apple.documentation/documentation/CoreMotion/CMMotionManager/isAccelerometerAvailable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether an accelerometer is available on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAccelerometerAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMotion/CMMotionManager/isAccelerometerAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "isAccelerometerAvailable",
      "type": "topic",
      "url": "/documentation/CoreMotion/CMMotionManager/isAccelerometerAvailable"
    },
    "doc://com.apple.documentation/documentation/CoreMotion/CMMotionManager/isGyroAvailable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a gyroscope is available on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isGyroAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMotion/CMMotionManager/isGyroAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "isGyroAvailable",
      "type": "topic",
      "url": "/documentation/CoreMotion/CMMotionManager/isGyroAvailable"
    },
    "doc://com.apple.documentation/documentation/CoreMotion/CMMotionManager/isMagnetometerAvailable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a magnetometer is available on the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isMagnetometerAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreMotion/CMMotionManager/isMagnetometerAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "isMagnetometerAvailable",
      "type": "topic",
      "url": "/documentation/CoreMotion/CMMotionManager/isMagnetometerAvailable"
    },
    "doc://com.apple.documentation/documentation/GLKit": {
      "abstract": [
        {
          "text": "Speed up OpenGL ES or OpenGL app development. Use math libraries, background texture loading, pre-created shader effects, and a standard view and view controller to implement your rendering loop.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GLKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GLKit",
      "type": "topic",
      "url": "/documentation/GLKit"
    },
    "doc://com.apple.documentation/documentation/HealthKit/HKHealthStore": {
      "abstract": [
        {
          "text": "The access point for all data managed by HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKHealthStore"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/HealthKit/HKHealthStore",
      "kind": "symbol",
      "role": "symbol",
      "title": "HKHealthStore",
      "type": "topic",
      "url": "/documentation/HealthKit/HKHealthStore"
    },
    "doc://com.apple.documentation/documentation/HomeKit/HMHomeManager": {
      "abstract": [
        {
          "text": "The manager for a collection of one or more of a user’s homes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMHomeManager"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/HomeKit/HMHomeManager",
      "kind": "symbol",
      "role": "symbol",
      "title": "HMHomeManager",
      "type": "topic",
      "url": "/documentation/HomeKit/HMHomeManager"
    },
    "doc://com.apple.documentation/documentation/HomeKit/HMHomeManager/authorizationStatus": {
      "abstract": [
        {
          "text": "The current state of the app’s access to home data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HMHomeManagerAuthorizationStatus",
          "text": "HMHomeManagerAuthorizationStatus"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/HomeKit/HMHomeManager/authorizationStatus",
      "kind": "symbol",
      "role": "symbol",
      "title": "authorizationStatus",
      "type": "topic",
      "url": "/documentation/HomeKit/HMHomeManager/authorizationStatus"
    },
    "doc://com.apple.documentation/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/Metal"
    },
    "doc://com.apple.documentation/documentation/MetalKit": {
      "abstract": [
        {
          "text": "Build Metal apps quicker and easier using a common set of utility classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MetalKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalKit",
      "type": "topic",
      "url": "/documentation/MetalKit"
    },
    "doc://com.apple.documentation/documentation/PhotoKit": {
      "abstract": [
        {
          "text": "Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PhotoKit",
      "kind": "article",
      "role": "collection",
      "title": "PhotoKit",
      "type": "topic",
      "url": "/documentation/PhotoKit"
    },
    "doc://com.apple.documentation/documentation/PushKit": {
      "abstract": [
        {
          "text": "Respond to push notifications related to your app’s complications, file providers, and VoIP services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PushKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PushKit",
      "type": "topic",
      "url": "/documentation/PushKit"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIDevice": {
      "abstract": [
        {
          "text": "A representation of the current device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDevice"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIDevice",
      "type": "topic",
      "url": "/documentation/UIKit/UIDevice"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIResponder": {
      "abstract": [
        {
          "text": "An abstract interface for responding to and handling events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIResponder"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIResponder",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIResponder",
      "type": "topic",
      "url": "/documentation/UIKit/UIResponder"
    },
    "doc://com.apple.documentation/documentation/UIKit/UITraitCollection": {
      "abstract": [
        {
          "text": "A collection of data that represents the environment for an individual element in your app’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitCollection"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UITraitCollection",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitCollection",
      "type": "topic",
      "url": "/documentation/UIKit/UITraitCollection"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIUserInterfaceIdiom/mac": {
      "abstract": [
        {
          "text": "An interface designed for the Mac.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mac"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIUserInterfaceIdiom/mac",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIUserInterfaceIdiom.mac",
      "type": "topic",
      "url": "/documentation/UIKit/UIUserInterfaceIdiom/mac"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIUserInterfaceIdiom/pad": {
      "abstract": [
        {
          "text": "An interface designed for iPad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pad"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIUserInterfaceIdiom/pad",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIUserInterfaceIdiom.pad",
      "type": "topic",
      "url": "/documentation/UIKit/UIUserInterfaceIdiom/pad"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIUserInterfaceIdiom/phone": {
      "abstract": [
        {
          "text": "An interface designed for iPhone and iPod touch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phone"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIUserInterfaceIdiom/phone",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIUserInterfaceIdiom.phone",
      "type": "topic",
      "url": "/documentation/UIKit/UIUserInterfaceIdiom/phone"
    },
    "doc://com.apple.documentation/documentation/UIKit/handling-key-presses-made-on-a-physical-keyboard": {
      "abstract": [
        {
          "text": "Detect when someone presses and releases keys on a physical keyboard.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/handling-key-presses-made-on-a-physical-keyboard",
      "kind": "article",
      "role": "article",
      "title": "Handling key presses made on a physical keyboard",
      "type": "topic",
      "url": "/documentation/UIKit/handling-key-presses-made-on-a-physical-keyboard"
    },
    "doc://com.apple.documentation/documentation/UIKit/multitasking-on-ipad": {
      "abstract": [
        {
          "text": "Implement multitasking APIs to seamlessly integrate your app with iPadOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/multitasking-on-ipad",
      "kind": "article",
      "role": "article",
      "title": "Multitasking on iPad",
      "type": "topic",
      "url": "/documentation/UIKit/multitasking-on-ipad"
    },
    "doc://com.apple.documentation/documentation/UIKit/supporting-multiple-windows-on-ipad": {
      "abstract": [
        {
          "text": "Support side-by-side instances of your app’s interface and create new windows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/supporting-multiple-windows-on-ipad",
      "kind": "article",
      "role": "sampleCode",
      "title": "Supporting multiple windows on iPad",
      "type": "topic",
      "url": "/documentation/UIKit/supporting-multiple-windows-on-ipad"
    },
    "doc://com.apple.documentation/documentation/apple-silicon/providing_an_edge-to-edge_full-screen_experience_in_your_ipad_app_running_on_a_mac": {
      "abstract": [
        {
          "text": "Take advantage of the true native resolution of a Mac display when running your iPad app in full-screen mode on a Mac.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/apple-silicon/providing_an_edge-to-edge_full-screen_experience_in_your_ipad_app_running_on_a_mac",
      "kind": "article",
      "role": "sampleCode",
      "title": "Providing an edge-to-edge, full-screen experience in your iPad app running on a Mac",
      "type": "topic",
      "url": "/documentation/apple-silicon/providing_an_edge-to-edge_full-screen_experience_in_your_ipad_app_running_on_a_mac"
    },
    "doc://com.apple.documentation/documentation/apple-silicon/providing_touch_gesture_equivalents_using_touch_alternatives": {
      "abstract": [
        {
          "text": "Enable Touch Alternatives to provide keyboard, mouse, and trackpad equivalents to your iOS app when it runs on a Mac with Apple silicon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/apple-silicon/providing_touch_gesture_equivalents_using_touch_alternatives",
      "kind": "article",
      "role": "sampleCode",
      "title": "Providing touch gesture equivalents using Touch Alternatives",
      "type": "topic",
      "url": "/documentation/apple-silicon/providing_touch_gesture_equivalents_using_touch_alternatives"
    },
    "doc://com.apple.documentation/documentation/foundation/filemanager": {
      "abstract": [
        {
          "text": "A convenient interface to the contents of the file system, and the primary means of interacting with it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "FileManager"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/filemanager",
      "kind": "symbol",
      "role": "symbol",
      "title": "FileManager",
      "type": "topic",
      "url": "/documentation/foundation/filemanager"
    },
    "doc://com.apple.documentation/documentation/foundation/filemanager/1407693-url": {
      "abstract": [
        {
          "text": "Locates and optionally creates the specified common directory in a domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": FileManager.SearchPathDirectory, "
        },
        {
          "kind": "identifier",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": FileManager.SearchPathDomainMask, "
        },
        {
          "kind": "identifier",
          "text": "appropriateFor"
        },
        {
          "kind": "text",
          "text": ": URL?, "
        },
        {
          "kind": "identifier",
          "text": "create"
        },
        {
          "kind": "text",
          "text": ": Bool) -> URL"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/filemanager/1407693-url",
      "kind": "symbol",
      "role": "symbol",
      "title": "url(for:in:appropriateFor:create:)",
      "type": "topic",
      "url": "/documentation/foundation/filemanager/1407693-url"
    },
    "doc://com.apple.documentation/documentation/healthkit/hkhealthstore/1614180-ishealthdataavailable": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether HealthKit is available on this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "isHealthDataAvailable"
        },
        {
          "kind": "text",
          "text": "() -> Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/healthkit/hkhealthstore/1614180-ishealthdataavailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "isHealthDataAvailable()",
      "type": "topic",
      "url": "/documentation/healthkit/hkhealthstore/1614180-ishealthdataavailable"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "iOS-Apps-on-Mac",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Apple-Silicon/documentation/Apple-Silicon/running-your-ios-apps-in-macos",
        "doc://com.apple.documentation/documentation/apple-silicon/providing_touch_gesture_equivalents_using_touch_alternatives",
        "doc://com.apple.documentation/documentation/apple-silicon/providing_an_edge-to-edge_full-screen_experience_in_your_ipad_app_running_on_a_mac"
      ],
      "title": "iOS Apps on Mac"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1filemanager/title",
          "value": "NSFileManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1HomeKit~1HMHomeManager~1authorizationStatus/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@HMHomeManagerAuthorizationStatus",
              "text": "HMHomeManagerAuthorizationStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "authorizationStatus"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARConfiguration/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ARConfiguration"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1filemanager~11407693-url/title",
          "value": "URLForDirectory:inDomain:appropriateForURL:create:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIUserInterfaceIdiom~1mac/title",
          "value": "UIUserInterfaceIdiomMac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIUserInterfaceIdiom~1mac/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomMac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ARKit~1ARConfiguration~1isSupported/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isSupported"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMotion~1CMMotionManager~1isGyroAvailable/title",
          "value": "gyroAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMotion~1CMMotionManager~1isGyroAvailable/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "getter"
            },
            {
              "kind": "text",
              "text": "="
            },
            {
              "kind": "identifier",
              "text": "isGyroAvailable"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "gyroAvailable"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMotion~1CMMotionManager/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMMotionManager"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIUserInterfaceIdiom~1phone/title",
          "value": "UIUserInterfaceIdiomPhone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIUserInterfaceIdiom~1phone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomPhone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureDevice~1DiscoverySession/title",
          "value": "AVCaptureDeviceDiscoverySession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureDevice~1DiscoverySession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceDiscoverySession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIResponder/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIResponder"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIDevice/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIDevice"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1healthkit~1hkhealthstore~11614180-ishealthdataavailable/title",
          "value": "isHealthDataAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UITraitCollection/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITraitCollection"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMotion~1CMMotionManager~1isMagnetometerAvailable/title",
          "value": "magnetometerAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMotion~1CMMotionManager~1isMagnetometerAvailable/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "getter"
            },
            {
              "kind": "text",
              "text": "="
            },
            {
              "kind": "identifier",
              "text": "isMagnetometerAvailable"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "magnetometerAvailable"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMotion~1CMMotionManager~1isAccelerometerAvailable/title",
          "value": "accelerometerAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreMotion~1CMMotionManager~1isAccelerometerAvailable/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "getter"
            },
            {
              "kind": "text",
              "text": "="
            },
            {
              "kind": "identifier",
              "text": "isAccelerometerAvailable"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accelerometerAvailable"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1HealthKit~1HKHealthStore/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HKHealthStore"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIUserInterfaceIdiom~1pad/title",
          "value": "UIUserInterfaceIdiomPad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIUserInterfaceIdiom~1pad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomPad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1HomeKit~1HMHomeManager/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "HMHomeManager"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
