{
  "abstract": [
    {
      "text": "Modernize the iOS apps you choose to run on a Mac with Apple silicon, or opt out of",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "running on a Mac altogether.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Apple-Silicon/documentation/apple-silicon"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Apple-Silicon/documentation/Apple-Silicon/running-your-ios-apps-in-macos"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "role": "article",
    "roleHeading": "Article",
    "title": "Running your iOS apps in macOS"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "iOS Apps on Mac runs your unmodified iPhone and iPad apps on Apple silicon with no",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "porting process. Your apps use the same frameworks and infrastructure that Mac Catalyst",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "apps use to run, but without the need to recompile for the Mac platform.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "running-your-ios-apps-on-macos-1.png",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Although there is no porting process, consider updating your code anyway to provide",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a better user experience when your app runs in macOS. Adopting modern iOS features",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in your app makes the transition to macOS simpler because modern features map automatically",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to appropriate macOS behaviors.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In some cases, you might choose to prevent your app from running in macOS altogether.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For example, if you already have a macOS app, or your app relies on features available",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "only on iOS devices, you can choose not to run your app in macOS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Although you can run your iOS apps unmodified on a Mac with Apple silicon,",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Mac Catalyst lets you build your app specifically for macOS and customize your app’s",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "behavior on that platform. Mac Catalyst also supports deployment on both Apple silicon and Intel-based Mac computers. For more information about how to build",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "your app with Mac Catalyst, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UIKit/mac-catalyst",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Determine-whether-your-app-makes-sense-in-macOS",
          "level": 3,
          "text": "Determine whether your app makes sense in macOS",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "iOS and macOS support many of the same frameworks and features, and most iOS apps",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "run smoothly in macOS. However, you might choose to opt out of running your iOS app",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in macOS under the following circumstances:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You already created a Mac version of your app using AppKit or Mac Catalyst.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Your app relies heavily on iOS hardware that’s unavailable for Mac, such as accelerometers,",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "gyroscopes, magnetometers, depth-sensing cameras, or GPS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Your app requires frameworks, symbols, or features unavailable in macOS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Your app’s interactions rely extensively on touch input that you can’t replicate",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "with the keyboard or other input.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You don’t want users to have access to the content in your app’s bundle or data",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "container.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Your app communicates with custom hardware using the External Accessory framework.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The absence of specific hardware on a Mac doesn’t always require you to opt out.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "You can disable parts of your app that require device-specific hardware, allowing",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the user to use the rest of your app. Some technologies might also be capable of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "operating without specific hardware. For example, Core Location doesn’t require GPS",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to return location data. The best approach is to determine what features are available",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "on the current platform using technology-specific APIs, and enable or disable app-specific",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "features accordingly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You don’t need to opt out apps that rely on single-finger touch input or make occasional",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "use of multifinger gestures. The macOS system supports single-finger touch input and standard",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "multifinger gestures for scrolling, zooming, rotating, and pinching using a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "trackpad. The system also adds a Touch Alternatives tab automatically to your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app’s Settings window. Touch Alternatives enables keyboard alternatives for tap, swipe, and drag",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "gestures, and enables multifinger gestures using the Option key and a trackpad.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "However, consider opting out if your app relies extensively on custom, multifinger",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "touch input that has no practical alternative. For example, you might opt out if",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your app regularly tracks multiple fingers at precise locations on the screen.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/apple-silicon/providing_touch_gesture_equivalents_using_touch_alternatives",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you ultimately decide that it doesn’t seem beneficial for your app to run in macOS,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you can opt out in App Store Connect, as described below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Adopt-features-that-offer-a-better-user-experience",
          "level": 3,
          "text": "Adopt features that offer a better user experience",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Some iOS features make it easier for your app to run in macOS and improve the overall",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "user experience. Consider adopting the following features in your iOS apps whenever",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "possible:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Adopt iPad multitasking and Auto Layout to support resizable windows in macOS. iPad",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "multitasking involves resizing your view controllers to make room for other apps",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "onscreen. If you don’t adopt iPad multitasking, your iPad app runs in a fixed-size",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "window. iPhone apps always run in a fixed-size window.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Optimize your view layouts to improve the experience of live-window resizing. Optimal",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "layouts result in faster animations when the user resizes your window.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add iOS keyboard support to your app and create keyboard-based shortcuts for your",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "app’s features. Users can access these shortcuts on any iOS or macOS device with",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "a connected keyboard.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/bundle",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/filemanager",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "APIs to find files and standard system directories. These APIs always provide you",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "with path locations that are appropriate for the current system.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use standard gesture recognizers for pinch, scroll, rotate, and zoom effects. The",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "standard gesture recognizers map automatically to appropriate gestures in macOS.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If you design your iPad app for a full-screen experience (for instance, your app is a game), you can add the keys ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to your app’s ",
                  "type": "text"
                },
                {
                  "code": "Info.plist",
                  "type": "codeVoice"
                },
                {
                  "text": " file to provide a pixel-perfect, edge-to-edge, full-screen experience when the app runs on a Mac.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Audit-your-code-to-handle-environment-differences",
          "level": 3,
          "text": "Audit your code to handle environment differences",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When your iOS app runs in macOS, the system automatically maps iOS features to the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "appropriate replacements in macOS. If you make assumptions about the current environment",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or device, audit your code to remove those assumptions. If you perform any validation",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "checks, test on a Mac with Apple silicon to make sure those checks continue",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to work correctly. Specifically, don’t assume that:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Your iOS app’s window or other UI elements, including system alerts and pop-ups,",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "are a specific size or at a specific location.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Multifinger touch input is available.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "iOS-specific hardware is available.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A front- or rear-facing camera is present. Use ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/DiscoverySession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "to identify an appropriate camera.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Files reside at specific file paths.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Device-specific features are always available.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The current type of device is always iPhone, iPad, or iPod touch.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The app window matches the screen resolution.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "PushKit notifications launch your app in the background. In macOS, these notifications",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "launch your app in the foreground instead. Use a notification-service extension to",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "run your code in the background.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The presence (or absence) of a symbol conveys special meaning. For example, don’t",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "assume your app runs on a specific device or platform because of the presence or",
                      "type": "text"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "absence of a symbol.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When you check for specific features, fall back to reasonable default behaviors when",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "those features aren’t available. Ensure that the absence of a feature doesn’t cause unexpected",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "results, or prevent the user from doing something meaningful with your app. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/processinfo/3608556-isiosapponmac",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "property of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/processinfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "tells you whether your iOS app is running in macOS or iOS, but checking that property",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "should always be your last choice. It’s better to run the same code on both platforms.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about how to handle environment differences, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.Apple-Silicon/documentation/Apple-Silicon/adapting-ios-code-to-run-in-the-macos-environment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Test-your-app-in-macOS",
          "level": 3,
          "text": "Test your app in macOS",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Xcode supports debugging, testing, and profiling your iOS app natively on a Mac with",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Apple silicon. When you open your iOS project in Xcode 12 or later, you have the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "option to build your app and run it directly in macOS. This option doesn’t run your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app in a Simulator; it runs it as an iOS App on Mac. You can then test whether your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "app’s features work as expected.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "App Store features for iOS continue to work when your app runs in macOS, including:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In-app purchases and subscriptions",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "App capabilities and entitlements",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "On-demand resources",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "App thinning",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When you use ",
              "type": "text"
            },
            {
              "identifier": "https://help.apple.com/xcode/mac/current/#/devbbdc5ce4f",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to optimize your app for different devices and operating systems, the App Store selects",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the resources and content that offer the best fit for a Mac. It then removes any",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "other resources to create a streamlined installation of your app. When you export",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your app from Xcode 12 or later, you can test the thinning support using the Mac",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "virtual thinning target.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "identifier": "https://testflight.apple.com",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to distribute your app to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your testers, or create an archive and export it using the ad-hoc or development distribution",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "method. During the export process, Xcode creates an appropriately signed app for",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you to distribute to your testers. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Xcode/distributing-your-app-to-registered-devices",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Choose-whether-to-include-your-iOS-app-in-the-Mac-App-Store",
          "level": 3,
          "text": "Choose whether to include your iOS app in the Mac App Store",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After you sign the updated developer agreement, the App Store automatically makes",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "compatible iOS apps available to users of a Mac with Apple silicon. However, if you’re",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "planning to ship a macOS version of your app, or if your app doesn’t make",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "sense for a Mac, you can change your app’s availability in App Store Connect.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Open the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "text": "page in App Store Connect.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Disable the “Make this app available on Mac” option.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "After you remove your app’s availability for Mac, the Mac App Store stops offering",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "your app for sale. Users who previously downloaded the app for Mac can still use it,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "but can’t download it again.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Apple-Silicon/documentation/Apple-Silicon/adapting-ios-code-to-run-in-the-macos-environment": {
      "abstract": [
        {
          "text": "Support modern iOS features that result in a better user experience when running",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "on Apple silicon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Apple-Silicon/documentation/Apple-Silicon/adapting-ios-code-to-run-in-the-macos-environment",
      "kind": "article",
      "role": "article",
      "title": "Adapting iOS code to run in the macOS environment",
      "type": "topic",
      "url": "/documentation/apple-silicon/adapting-ios-code-to-run-in-the-macos-environment"
    },
    "doc://com.apple.Apple-Silicon/documentation/apple-silicon": {
      "abstract": [
        {
          "text": "Get the resources you need to create software for Macs with Apple silicon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Apple-Silicon/documentation/apple-silicon",
      "kind": "article",
      "role": "collection",
      "title": "Apple Silicon",
      "type": "topic",
      "url": "/documentation/apple-silicon"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/DiscoverySession": {
      "abstract": [
        {
          "text": "An object that finds capture devices that match specific search criteria.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DiscoverySession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVCaptureDevice/DiscoverySession",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVCaptureDevice.DiscoverySession",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVCaptureDevice/DiscoverySession"
    },
    "doc://com.apple.documentation/documentation/AppStoreConnectAPI": {
      "abstract": [
        {
          "text": "Automate the tasks you perform on the Apple Developer website and in App Store Connect.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppStoreConnectAPI",
      "kind": "symbol",
      "role": "collection",
      "title": "App Store Connect API",
      "type": "topic",
      "url": "/documentation/AppStoreConnectAPI"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to launch your iPad app in full-screen mode when running on a Mac.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac",
      "kind": "symbol",
      "role": "symbol",
      "title": "UILaunchToFullScreenByDefaultOnMac",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/UILaunchToFullScreenByDefaultOnMac"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your iPad app supports arbitrary screen sizes and resolutions when running on a Mac.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac",
      "kind": "symbol",
      "role": "symbol",
      "title": "UISupportsTrueScreenSizeOnMac",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/UISupportsTrueScreenSizeOnMac"
    },
    "doc://com.apple.documentation/documentation/UIKit/mac-catalyst": {
      "abstract": [
        {
          "text": "Create a version of your iPad app that users can run on a Mac device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/mac-catalyst",
      "kind": "article",
      "role": "article",
      "title": "Mac Catalyst",
      "type": "topic",
      "url": "/documentation/UIKit/mac-catalyst"
    },
    "doc://com.apple.documentation/documentation/Xcode/distributing-your-app-to-registered-devices": {
      "abstract": [
        {
          "text": "Register devices in your developer account and deploy your app to them for testing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Xcode/distributing-your-app-to-registered-devices",
      "kind": "article",
      "role": "article",
      "title": "Distributing your app to registered devices",
      "type": "topic",
      "url": "/documentation/Xcode/distributing-your-app-to-registered-devices"
    },
    "doc://com.apple.documentation/documentation/apple-silicon/providing_an_edge-to-edge_full-screen_experience_in_your_ipad_app_running_on_a_mac": {
      "abstract": [
        {
          "text": "Take advantage of the true native resolution of a Mac display when running your iPad app in full-screen mode on a Mac.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/apple-silicon/providing_an_edge-to-edge_full-screen_experience_in_your_ipad_app_running_on_a_mac",
      "kind": "article",
      "role": "sampleCode",
      "title": "Providing an edge-to-edge, full-screen experience in your iPad app running on a Mac",
      "type": "topic",
      "url": "/documentation/apple-silicon/providing_an_edge-to-edge_full-screen_experience_in_your_ipad_app_running_on_a_mac"
    },
    "doc://com.apple.documentation/documentation/apple-silicon/providing_touch_gesture_equivalents_using_touch_alternatives": {
      "abstract": [
        {
          "text": "Enable Touch Alternatives to provide keyboard, mouse, and trackpad equivalents to your iOS app when it runs on a Mac with Apple silicon.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/apple-silicon/providing_touch_gesture_equivalents_using_touch_alternatives",
      "kind": "article",
      "role": "sampleCode",
      "title": "Providing touch gesture equivalents using Touch Alternatives",
      "type": "topic",
      "url": "/documentation/apple-silicon/providing_touch_gesture_equivalents_using_touch_alternatives"
    },
    "doc://com.apple.documentation/documentation/foundation/bundle": {
      "abstract": [
        {
          "text": "A representation of the code and resources stored in a bundle directory on disk. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "Bundle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/bundle",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bundle",
      "type": "topic",
      "url": "/documentation/foundation/bundle"
    },
    "doc://com.apple.documentation/documentation/foundation/filemanager": {
      "abstract": [
        {
          "text": "A convenient interface to the contents of the file system, and the primary means of interacting with it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "FileManager"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/filemanager",
      "kind": "symbol",
      "role": "symbol",
      "title": "FileManager",
      "type": "topic",
      "url": "/documentation/foundation/filemanager"
    },
    "doc://com.apple.documentation/documentation/foundation/processinfo": {
      "abstract": [
        {
          "text": "A collection of information about the current process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "ProcessInfo"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/processinfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "ProcessInfo",
      "type": "topic",
      "url": "/documentation/foundation/processinfo"
    },
    "doc://com.apple.documentation/documentation/foundation/processinfo/3608556-isiosapponmac": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the process is an iPhone or iPad app running on a Mac.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "isiOSAppOnMac"
        },
        {
          "kind": "text",
          "text": ": Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/processinfo/3608556-isiosapponmac",
      "kind": "symbol",
      "role": "symbol",
      "title": "isiOSAppOnMac",
      "type": "topic",
      "url": "/documentation/foundation/processinfo/3608556-isiosapponmac"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://help.apple.com/xcode/mac/current/#/devbbdc5ce4f": {
      "identifier": "https://help.apple.com/xcode/mac/current/#/devbbdc5ce4f",
      "title": "app thinning",
      "titleInlineContent": [
        {
          "text": "app thinning",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/xcode/mac/current/#/devbbdc5ce4f"
    },
    "https://testflight.apple.com": {
      "identifier": "https://testflight.apple.com",
      "title": "TestFlight",
      "titleInlineContent": [
        {
          "text": "TestFlight",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://testflight.apple.com"
    },
    "running-your-ios-apps-on-macos-1.png": {
      "alt": "An illustration of an app running on an iPad and a Mac with Apple silicon.",
      "identifier": "running-your-ios-apps-on-macos-1.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b8882cf87eaa76d58f16819f18a145e1/running-your-ios-apps-on-macos-1@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "iOS-Apps-on-Mac",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Apple-Silicon/documentation/Apple-Silicon/adapting-ios-code-to-run-in-the-macos-environment",
        "doc://com.apple.documentation/documentation/apple-silicon/providing_touch_gesture_equivalents_using_touch_alternatives",
        "doc://com.apple.documentation/documentation/apple-silicon/providing_an_edge-to-edge_full-screen_experience_in_your_ipad_app_running_on_a_mac"
      ],
      "title": "iOS Apps on Mac"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1filemanager/title",
          "value": "NSFileManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1processinfo~13608556-isiosapponmac/title",
          "value": "iOSAppOnMac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1bundle/title",
          "value": "NSBundle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1processinfo/title",
          "value": "NSProcessInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureDevice~1DiscoverySession/title",
          "value": "AVCaptureDeviceDiscoverySession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFoundation~1AVCaptureDevice~1DiscoverySession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceDiscoverySession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
