{
  "abstract": [
    {
      "text": "Metadata keys for an image from a Canon camera.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/canon-camera-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Canon Camera Dictionary Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerAppleDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from an Apple camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerAppleDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerAppleDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerAppleDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerAppleDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerappledictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonAspectRatioInfo": {
      "abstract": [
        {
          "text": "The image aspect ratio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonAspectRatioInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonAspectRatioInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonAspectRatioInfo"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerCanonAspectRatioInfo",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakercanonaspectratioinfo"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonCameraSerialNumber": {
      "abstract": [
        {
          "text": "The camera serial number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonCameraSerialNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonCameraSerialNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonCameraSerialNumber"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerCanonCameraSerialNumber",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakercanoncameraserialnumber"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonContinuousDrive": {
      "abstract": [
        {
          "text": "The presence of a continuous drive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonContinuousDrive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonContinuousDrive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonContinuousDrive"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerCanonContinuousDrive",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakercanoncontinuousdrive"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Canon camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerCanonDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakercanondictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonFirmware": {
      "abstract": [
        {
          "text": "The firmware version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonFirmware"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonFirmware",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonFirmware"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerCanonFirmware",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakercanonfirmware"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonFlashExposureComp": {
      "abstract": [
        {
          "text": "The flash exposure compensation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonFlashExposureComp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonFlashExposureComp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonFlashExposureComp"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerCanonFlashExposureComp",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakercanonflashexposurecomp"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonImageSerialNumber": {
      "abstract": [
        {
          "text": "The image serial number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonImageSerialNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonImageSerialNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonImageSerialNumber"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerCanonImageSerialNumber",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakercanonimageserialnumber"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonLensModel": {
      "abstract": [
        {
          "text": "The lens model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonLensModel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonLensModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonLensModel"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerCanonLensModel",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakercanonlensmodel"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonOwnerName": {
      "abstract": [
        {
          "text": "The name of the camera’s owner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonOwnerName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonOwnerName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerCanonOwnerName"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerCanonOwnerName",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakercanonownername"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerFujiDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Fuji camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerFujiDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerFujiDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerFujiDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerFujiDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerfujidictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerMinoltaDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Minolta camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerMinoltaDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerMinoltaDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerMinoltaDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerMinoltaDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerminoltadictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerOlympusDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Olympus camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerOlympusDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerOlympusDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerOlympusDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerOlympusDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerolympusdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerPentaxDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image from a Pentax camera.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerPentaxDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerPentaxDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyMakerPentaxDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyMakerPentaxDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertymakerpentaxdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyRawDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image that contains minimally processed, or raw, data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyRawDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyRawDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyRawDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyRawDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyrawdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/nikon-camera-dictionary-keys": {
      "abstract": [
        {
          "text": "Metadata keys for an image from a Nikon camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/nikon-camera-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Nikon Camera Dictionary Keys",
      "type": "topic",
      "url": "/documentation/imageio/nikon-camera-dictionary-keys"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Manufacturer-Specific-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/nikon-camera-dictionary-keys",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerAppleDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerMinoltaDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerFujiDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerOlympusDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerPentaxDictionary",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyRawDictionary"
      ],
      "title": "Manufacturer-Specific Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Dictionary",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonDictionary"
      ],
      "title": "Dictionary"
    },
    {
      "anchor": "Program-Settings",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonFlashExposureComp",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonContinuousDrive",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonAspectRatioInfo"
      ],
      "title": "Program Settings"
    },
    {
      "anchor": "Camera-Details",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonOwnerName",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonCameraSerialNumber",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonImageSerialNumber",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonLensModel",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonFirmware"
      ],
      "title": "Camera Details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Dictionary",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonDictionary"
              ],
              "title": "Dictionary"
            },
            {
              "anchor": "Program-Settings",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonFlashExposureComp",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonContinuousDrive",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonAspectRatioInfo"
              ],
              "title": "Program Settings"
            },
            {
              "anchor": "Camera-Details",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonOwnerName",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonCameraSerialNumber",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonImageSerialNumber",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonLensModel",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerCanonFirmware"
              ],
              "title": "Camera Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Manufacturer-Specific-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/nikon-camera-dictionary-keys",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerAppleDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerMinoltaDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerFujiDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerOlympusDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyMakerPentaxDictionary",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyRawDictionary"
              ],
              "title": "Manufacturer-Specific Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonOwnerName/title",
          "value": "kCGImagePropertyMakerCanonOwnerName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonOwnerName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerCanonOwnerName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonCameraSerialNumber/title",
          "value": "kCGImagePropertyMakerCanonCameraSerialNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonCameraSerialNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerCanonCameraSerialNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerPentaxDictionary/title",
          "value": "kCGImagePropertyMakerPentaxDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerPentaxDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerPentaxDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonContinuousDrive/title",
          "value": "kCGImagePropertyMakerCanonContinuousDrive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonContinuousDrive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerCanonContinuousDrive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonImageSerialNumber/title",
          "value": "kCGImagePropertyMakerCanonImageSerialNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonImageSerialNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerCanonImageSerialNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonLensModel/title",
          "value": "kCGImagePropertyMakerCanonLensModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonLensModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerCanonLensModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonDictionary/title",
          "value": "kCGImagePropertyMakerCanonDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerCanonDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerOlympusDictionary/title",
          "value": "kCGImagePropertyMakerOlympusDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerOlympusDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerOlympusDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonAspectRatioInfo/title",
          "value": "kCGImagePropertyMakerCanonAspectRatioInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonAspectRatioInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerCanonAspectRatioInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonFlashExposureComp/title",
          "value": "kCGImagePropertyMakerCanonFlashExposureComp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonFlashExposureComp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerCanonFlashExposureComp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyRawDictionary/title",
          "value": "kCGImagePropertyRawDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyRawDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyRawDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonFirmware/title",
          "value": "kCGImagePropertyMakerCanonFirmware"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerCanonFirmware/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerCanonFirmware"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerAppleDictionary/title",
          "value": "kCGImagePropertyMakerAppleDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerAppleDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerAppleDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerMinoltaDictionary/title",
          "value": "kCGImagePropertyMakerMinoltaDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerMinoltaDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerMinoltaDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerFujiDictionary/title",
          "value": "kCGImagePropertyMakerFujiDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyMakerFujiDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyMakerFujiDictionary"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/canon-camera-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/canon-camera-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
