{
  "abstract": [
    {
      "text": "An opaque type that you use to read image data from a URL, data object, or data consumer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/CGImageSource"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CGImageSourceRef",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CGImageSource"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CGImageSource"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CGImageSource"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CGImageSource"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSource",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type to read data efficiently for most image file formats. The image source object manages the data buffers needed to load the image data and performs any operations on that data to turn it into a usable image. For example, it decompresses data stored in a compressed format. You can also use an image source to fetch or create thumbnail images and access metadata stored with the image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Create an image source object from a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfurl",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdata",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgdataprovider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " data type. The image source object reads data from the specified type and extracts the image information for you.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageIOGuide/imageio_intro/ikpg_intro.html#//apple_ref/doc/uid/TP40005462",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/corefoundation/cfdata": {
      "abstract": [
        {
          "text": "A reference to an immutable CFData object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFData"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdata",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFData",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdata"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfurl": {
      "abstract": [
        {
          "text": "A reference to a CFURL object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFURL"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfurl",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFURL",
      "type": "topic",
      "url": "/documentation/corefoundation/cfurl"
    },
    "doc://com.apple.documentation/documentation/coregraphics/cgdataprovider": {
      "abstract": [
        {
          "text": "An abstraction for data-reading tasks that eliminates the need to manage a raw memory buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CGDataProvider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgdataprovider",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGDataProvider",
      "type": "topic",
      "url": "/documentation/coregraphics/cgdataprovider"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageDestination": {
      "abstract": [
        {
          "text": "An opaque type that you use to write image data to a URL, data object, or data consumer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageDestination"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageDestination"
        }
      ],
      "role": "symbol",
      "title": "CGImageDestination",
      "type": "topic",
      "url": "/documentation/imageio/cgimagedestination"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSource": {
      "abstract": [
        {
          "text": "An opaque type that you use to read image data from a URL, data object, or data consumer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSource"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSource"
        }
      ],
      "role": "symbol",
      "title": "CGImageSource",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesource"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyAuxiliaryDataInfoAtIndex(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns auxiliary data, such as mattes and depth information, that accompany the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceCopyAuxiliaryDataInfoAtIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyAuxiliaryDataInfoAtIndex(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceCopyAuxiliaryDataInfoAtIndex"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceCopyAuxiliaryDataInfoAtIndex(_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcecopyauxiliarydatainfoatindex(_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyProperties(_:_:)": {
      "abstract": [
        {
          "text": "Returns the properties of the image source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceCopyProperties"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyProperties(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceCopyProperties"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceCopyProperties(_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcecopyproperties(_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyPropertiesAtIndex(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the properties of the image at a specified location in an image source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceCopyPropertiesAtIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyPropertiesAtIndex(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceCopyPropertiesAtIndex"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceCopyPropertiesAtIndex(_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcecopypropertiesatindex(_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyTypeIdentifiers()": {
      "abstract": [
        {
          "text": "Returns an array of uniform type identifiers that are supported for image sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceCopyTypeIdentifiers"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyTypeIdentifiers()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceCopyTypeIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceCopyTypeIdentifiers()",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcecopytypeidentifiers()"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateImageAtIndex(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an image object from the data at the specified index in an image source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceCreateImageAtIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateImageAtIndex(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceCreateImageAtIndex"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceCreateImageAtIndex(_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcecreateimageatindex(_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateIncremental(_:)": {
      "abstract": [
        {
          "text": "Creates an empty image source that you can use to accumulate incremental image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceCreateIncremental"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateIncremental(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceCreateIncremental"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceCreateIncremental(_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcecreateincremental(_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateThumbnailAtIndex(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a thumbnail version of the image at the specified index in an image source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceCreateThumbnailAtIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateThumbnailAtIndex(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceCreateThumbnailAtIndex"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceCreateThumbnailAtIndex(_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcecreatethumbnailatindex(_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateWithData(_:_:)": {
      "abstract": [
        {
          "text": "Creates an image source that reads from a Core Foundation data object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceCreateWithData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateWithData(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceCreateWithData"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceCreateWithData(_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcecreatewithdata(_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateWithDataProvider(_:_:)": {
      "abstract": [
        {
          "text": "Creates an image source that reads data from the specified data provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceCreateWithDataProvider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGDataProviderRef",
          "text": "CGDataProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateWithDataProvider(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceCreateWithDataProvider"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceCreateWithDataProvider(_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcecreatewithdataprovider(_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateWithURL(_:_:)": {
      "abstract": [
        {
          "text": "Creates an image source that reads from a location specified by a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceCreateWithURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateWithURL(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceCreateWithURL"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceCreateWithURL(_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcecreatewithurl(_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetCount(_:)": {
      "abstract": [
        {
          "text": "Returns the number of images (not including thumbnails) in the image source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceGetCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceGetCount"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceGetCount(_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcegetcount(_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetPrimaryImageIndex(_:)": {
      "abstract": [
        {
          "text": "Returns the index of the primary image for an High Efficiency Image File Format (HEIF) image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceGetPrimaryImageIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetPrimaryImageIndex(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceGetPrimaryImageIndex"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceGetPrimaryImageIndex(_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcegetprimaryimageindex(_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetStatus(_:)": {
      "abstract": [
        {
          "text": "Return the status of an image source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceGetStatus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CGImageSourceStatus",
          "text": "CGImageSourceStatus"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetStatus(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceGetStatus"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceGetStatus(_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcegetstatus(_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetStatusAtIndex(_:_:)": {
      "abstract": [
        {
          "text": "Returns the current status of an image at the specified location in the image source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceGetStatusAtIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CGImageSourceStatus",
          "text": "CGImageSourceStatus"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetStatusAtIndex(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceGetStatusAtIndex"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceGetStatusAtIndex(_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcegetstatusatindex(_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetType(_:)": {
      "abstract": [
        {
          "text": "Returns the uniform type identifier of the source container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceGetType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceGetType"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceGetType(_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcegettype(_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the unique type identifier of an image source opaque type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceGetTypeID()",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcegettypeid()"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus": {
      "abstract": [
        {
          "text": "The set of status values for images and image sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceStatus"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceStatus"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceStatus",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcestatus"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceUpdateData(_:_:_:)": {
      "abstract": [
        {
          "text": "Updates the data in an incremental image source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceUpdateData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceUpdateData(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceUpdateData"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceUpdateData(_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourceupdatedata(_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceUpdateDataProvider(_:_:_:)": {
      "abstract": [
        {
          "text": "Updates an incremental image source with a new data provider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceUpdateDataProvider"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGDataProviderRef",
          "text": "CGDataProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceUpdateDataProvider(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceUpdateDataProvider"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceUpdateDataProvider(_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourceupdatedataprovider(_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceCreateThumbnailFromImageAlways": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to always create a thumbnail image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageSourceCreateThumbnailFromImageAlways"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceCreateThumbnailFromImageAlways",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageSourceCreateThumbnailFromImageAlways"
        }
      ],
      "role": "symbol",
      "title": "kCGImageSourceCreateThumbnailFromImageAlways",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagesourcecreatethumbnailfromimagealways"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceCreateThumbnailFromImageIfAbsent": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to create a thumbnail image automatically if the data source doesn’t contain one.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageSourceCreateThumbnailFromImageIfAbsent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceCreateThumbnailFromImageIfAbsent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageSourceCreateThumbnailFromImageIfAbsent"
        }
      ],
      "role": "symbol",
      "title": "kCGImageSourceCreateThumbnailFromImageIfAbsent",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagesourcecreatethumbnailfromimageifabsent"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceCreateThumbnailWithTransform": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to rotate and scale the thumbnail image to match the image’s orientation and aspect ratio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageSourceCreateThumbnailWithTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceCreateThumbnailWithTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageSourceCreateThumbnailWithTransform"
        }
      ],
      "role": "symbol",
      "title": "kCGImageSourceCreateThumbnailWithTransform",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagesourcecreatethumbnailwithtransform"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceShouldAllowFloat": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether to use floating-point values in returned images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageSourceShouldAllowFloat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceShouldAllowFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageSourceShouldAllowFloat"
        }
      ],
      "role": "symbol",
      "title": "kCGImageSourceShouldAllowFloat",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagesourceshouldallowfloat"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceShouldCache": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to cache the decoded image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageSourceShouldCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceShouldCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageSourceShouldCache"
        }
      ],
      "role": "symbol",
      "title": "kCGImageSourceShouldCache",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagesourceshouldcache"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceShouldCacheImmediately": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether image decoding and caching happens at image creation time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageSourceShouldCacheImmediately"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceShouldCacheImmediately",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageSourceShouldCacheImmediately"
        }
      ],
      "role": "symbol",
      "title": "kCGImageSourceShouldCacheImmediately",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagesourceshouldcacheimmediately"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceSubsampleFactor": {
      "abstract": [
        {
          "text": "The factor by which to scale down any returned images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageSourceSubsampleFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceSubsampleFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageSourceSubsampleFactor"
        }
      ],
      "role": "symbol",
      "title": "kCGImageSourceSubsampleFactor",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagesourcesubsamplefactor"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceThumbnailMaxPixelSize": {
      "abstract": [
        {
          "text": "The maximum width and height of a thumbnail image, specified in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageSourceThumbnailMaxPixelSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceThumbnailMaxPixelSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageSourceThumbnailMaxPixelSize"
        }
      ],
      "role": "symbol",
      "title": "kCGImageSourceThumbnailMaxPixelSize",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagesourcethumbnailmaxpixelsize"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceTypeIdentifierHint": {
      "abstract": [
        {
          "text": "The uniform type identifier that represents your best guess for the image’s type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageSourceTypeIdentifierHint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceTypeIdentifierHint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageSourceTypeIdentifierHint"
        }
      ],
      "role": "symbol",
      "title": "kCGImageSourceTypeIdentifierHint",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagesourcetypeidentifierhint"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageIOGuide/imageio_intro/ikpg_intro.html#//apple_ref/doc/uid/TP40005462": {
      "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageIOGuide/imageio_intro/ikpg_intro.html#//apple_ref/doc/uid/TP40005462",
      "title": "Image I/O Programming Guide",
      "titleInlineContent": [
        {
          "text": "Image I/O Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageIOGuide/imageio_intro/ikpg_intro.html#//apple_ref/doc/uid/TP40005462"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Image-Management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageDestination"
      ],
      "title": "Image Management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-Image-Source",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateWithURL(_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateWithData(_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateWithDataProvider(_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateIncremental(_:)"
      ],
      "title": "Creating an Image Source"
    },
    {
      "anchor": "Extracting-Images-From-an-Image-Source",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateImageAtIndex(_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateThumbnailAtIndex(_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetPrimaryImageIndex(_:)"
      ],
      "title": "Extracting Images From an Image Source"
    },
    {
      "anchor": "Getting-Information-From-an-Image-Source",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetTypeID()",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetType(_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyTypeIdentifiers()",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetCount(_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyProperties(_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyPropertiesAtIndex(_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyAuxiliaryDataInfoAtIndex(_:_:_:)"
      ],
      "title": "Getting Information From an Image Source"
    },
    {
      "anchor": "Updating-an-Incremental-Image",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceUpdateData(_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceUpdateDataProvider(_:_:_:)"
      ],
      "title": "Updating an Incremental Image"
    },
    {
      "anchor": "Getting-the-Image-Status",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetStatus(_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetStatusAtIndex(_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus"
      ],
      "title": "Getting the Image Status"
    },
    {
      "anchor": "Specifying-the-Read-Options",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceTypeIdentifierHint",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceShouldAllowFloat",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceShouldCache",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceShouldCacheImmediately",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceCreateThumbnailFromImageIfAbsent",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceCreateThumbnailFromImageAlways",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceThumbnailMaxPixelSize",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceCreateThumbnailWithTransform",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceSubsampleFactor"
      ],
      "title": "Specifying the Read Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CGImageSourceRef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-an-Image-Source",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateWithURL(_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateWithData(_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateWithDataProvider(_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateIncremental(_:)"
              ],
              "title": "Creating an Image Source"
            },
            {
              "anchor": "Extracting-Images-From-an-Image-Source",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateImageAtIndex(_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCreateThumbnailAtIndex(_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetPrimaryImageIndex(_:)"
              ],
              "title": "Extracting Images From an Image Source"
            },
            {
              "anchor": "Getting-Information-From-an-Image-Source",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetTypeID()",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetType(_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyTypeIdentifiers()",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetCount(_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyProperties(_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyPropertiesAtIndex(_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyAuxiliaryDataInfoAtIndex(_:_:_:)"
              ],
              "title": "Getting Information From an Image Source"
            },
            {
              "anchor": "Updating-an-Incremental-Image",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceUpdateData(_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceUpdateDataProvider(_:_:_:)"
              ],
              "title": "Updating an Incremental Image"
            },
            {
              "anchor": "Getting-the-Image-Status",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetStatus(_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetStatusAtIndex(_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus"
              ],
              "title": "Getting the Image Status"
            },
            {
              "anchor": "Specifying-the-Read-Options",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceTypeIdentifierHint",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceShouldAllowFloat",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceShouldCache",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceShouldCacheImmediately",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceCreateThumbnailFromImageIfAbsent",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceCreateThumbnailFromImageAlways",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceThumbnailMaxPixelSize",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceCreateThumbnailWithTransform",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageSourceSubsampleFactor"
              ],
              "title": "Specifying the Read Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Image-Management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageDestination"
              ],
              "title": "Image Management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGImageSource",
                    "text": "CGImageSource"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "CGImageSourceRef"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus/title",
          "value": "CGImageSourceStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCopyProperties(_:_:)/title",
          "value": "CGImageSourceCopyProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCopyProperties(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceCopyProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceGetTypeID()/title",
          "value": "CGImageSourceGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSource/title",
          "value": "CGImageSourceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCreateIncremental(_:)/title",
          "value": "CGImageSourceCreateIncremental"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCreateIncremental(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceCreateIncremental"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceGetStatusAtIndex(_:_:)/title",
          "value": "CGImageSourceGetStatusAtIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceGetStatusAtIndex(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceGetStatusAtIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceGetType(_:)/title",
          "value": "CGImageSourceGetType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceGetType(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceGetType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestination/title",
          "value": "CGImageDestinationRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestination/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceThumbnailMaxPixelSize/title",
          "value": "kCGImageSourceThumbnailMaxPixelSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceThumbnailMaxPixelSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageSourceThumbnailMaxPixelSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCreateImageAtIndex(_:_:_:)/title",
          "value": "CGImageSourceCreateImageAtIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCreateImageAtIndex(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceCreateImageAtIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCreateWithURL(_:_:)/title",
          "value": "CGImageSourceCreateWithURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCreateWithURL(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceCreateWithURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceShouldAllowFloat/title",
          "value": "kCGImageSourceShouldAllowFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceShouldAllowFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageSourceShouldAllowFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfdata/title",
          "value": "CFDataRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceCreateThumbnailWithTransform/title",
          "value": "kCGImageSourceCreateThumbnailWithTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceCreateThumbnailWithTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageSourceCreateThumbnailWithTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceTypeIdentifierHint/title",
          "value": "kCGImageSourceTypeIdentifierHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceTypeIdentifierHint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageSourceTypeIdentifierHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCreateWithData(_:_:)/title",
          "value": "CGImageSourceCreateWithData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCreateWithData(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceCreateWithData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceCreateThumbnailFromImageIfAbsent/title",
          "value": "kCGImageSourceCreateThumbnailFromImageIfAbsent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceCreateThumbnailFromImageIfAbsent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageSourceCreateThumbnailFromImageIfAbsent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCopyTypeIdentifiers()/title",
          "value": "CGImageSourceCopyTypeIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCopyTypeIdentifiers()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceCopyTypeIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceShouldCache/title",
          "value": "kCGImageSourceShouldCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceShouldCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageSourceShouldCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfurl/title",
          "value": "CFURLRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceGetCount(_:)/title",
          "value": "CGImageSourceGetCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceGetCount(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceGetCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceShouldCacheImmediately/title",
          "value": "kCGImageSourceShouldCacheImmediately"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceShouldCacheImmediately/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageSourceShouldCacheImmediately"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCopyAuxiliaryDataInfoAtIndex(_:_:_:)/title",
          "value": "CGImageSourceCopyAuxiliaryDataInfoAtIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCopyAuxiliaryDataInfoAtIndex(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceCopyAuxiliaryDataInfoAtIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCopyPropertiesAtIndex(_:_:_:)/title",
          "value": "CGImageSourceCopyPropertiesAtIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCopyPropertiesAtIndex(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceCopyPropertiesAtIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceUpdateData(_:_:_:)/title",
          "value": "CGImageSourceUpdateData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceUpdateData(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceUpdateData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceGetStatus(_:)/title",
          "value": "CGImageSourceGetStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceGetStatus(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceGetStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceCreateThumbnailFromImageAlways/title",
          "value": "kCGImageSourceCreateThumbnailFromImageAlways"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceCreateThumbnailFromImageAlways/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageSourceCreateThumbnailFromImageAlways"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceGetPrimaryImageIndex(_:)/title",
          "value": "CGImageSourceGetPrimaryImageIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceGetPrimaryImageIndex(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceGetPrimaryImageIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCreateThumbnailAtIndex(_:_:_:)/title",
          "value": "CGImageSourceCreateThumbnailAtIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCreateThumbnailAtIndex(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceCreateThumbnailAtIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCreateWithDataProvider(_:_:)/title",
          "value": "CGImageSourceCreateWithDataProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCreateWithDataProvider(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceCreateWithDataProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceSubsampleFactor/title",
          "value": "kCGImageSourceSubsampleFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageSourceSubsampleFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageSourceSubsampleFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgdataprovider/title",
          "value": "CGDataProviderRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceUpdateDataProvider(_:_:_:)/title",
          "value": "CGImageSourceUpdateDataProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceUpdateDataProvider(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceUpdateDataProvider"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/cgimagesource"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/cgimagesource"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
