{
  "abstract": [
    {
      "text": "Constants that indicate the result of animating an image sequence.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CGImageAnimationStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CGImageAnimationStatus"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CGImageAnimationStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CGImageAnimationStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CGImageAnimationStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGAnimateImageAtURLWithBlock(_:_:_:)": {
      "abstract": [
        {
          "text": "Animate the sequence of images in the Graphics Interchange Format (GIF) or Animated Portable Network Graphics (APNG) file at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGAnimateImageAtURLWithBlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceAnimationBlock",
          "text": "CGImageSourceAnimationBlock"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGAnimateImageAtURLWithBlock(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGAnimateImageAtURLWithBlock"
        }
      ],
      "role": "symbol",
      "title": "CGAnimateImageAtURLWithBlock(_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cganimateimageaturlwithblock(_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGAnimateImageDataWithBlock(_:_:_:)": {
      "abstract": [
        {
          "text": "Animate the sequence of images using data from a Graphics Interchange Format (GIF) or Animated Portable Network Graphics (APNG) file file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGAnimateImageDataWithBlock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceAnimationBlock",
          "text": "CGImageSourceAnimationBlock"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGAnimateImageDataWithBlock(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGAnimateImageDataWithBlock"
        }
      ],
      "role": "symbol",
      "title": "CGAnimateImageDataWithBlock(_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cganimateimagedatawithblock(_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus": {
      "abstract": [
        {
          "text": "Constants that indicate the result of animating an image sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageAnimationStatus"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageAnimationStatus"
        }
      ],
      "role": "symbol",
      "title": "CGImageAnimationStatus",
      "type": "topic",
      "url": "/documentation/imageio/cgimageanimationstatus"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/allocationFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allocationFailure"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/allocationFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAnimationStatus_AllocationFailure"
        }
      ],
      "role": "symbol",
      "title": "CGImageAnimationStatus.allocationFailure",
      "type": "topic",
      "url": "/documentation/imageio/cgimageanimationstatus/allocationfailure"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/corruptInputImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "corruptInputImage"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/corruptInputImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAnimationStatus_CorruptInputImage"
        }
      ],
      "role": "symbol",
      "title": "CGImageAnimationStatus.corruptInputImage",
      "type": "topic",
      "url": "/documentation/imageio/cgimageanimationstatus/corruptinputimage"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/incompleteInputImage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incompleteInputImage"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/incompleteInputImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAnimationStatus_IncompleteInputImage"
        }
      ],
      "role": "symbol",
      "title": "CGImageAnimationStatus.incompleteInputImage",
      "type": "topic",
      "url": "/documentation/imageio/cgimageanimationstatus/incompleteinputimage"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimageanimationstatus/init(rawvalue:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/parameterError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameterError"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/parameterError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAnimationStatus_ParameterError"
        }
      ],
      "role": "symbol",
      "title": "CGImageAnimationStatus.parameterError",
      "type": "topic",
      "url": "/documentation/imageio/cgimageanimationstatus/parametererror"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/unsupportedFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedFormat"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/unsupportedFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAnimationStatus_UnsupportedFormat"
        }
      ],
      "role": "symbol",
      "title": "CGImageAnimationStatus.unsupportedFormat",
      "type": "topic",
      "url": "/documentation/imageio/cgimageanimationstatus/unsupportedformat"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceAnimationBlock": {
      "abstract": [
        {
          "text": "The block to execute for each frame of an image animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceAnimationBlock"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceAnimationBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceAnimationBlock"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceAnimationBlock",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourceanimationblock"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationDelayTime": {
      "abstract": [
        {
          "text": "The number of seconds to wait before displaying the next image in an animated sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAnimationDelayTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationDelayTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAnimationDelayTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAnimationDelayTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageanimationdelaytime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationLoopCount": {
      "abstract": [
        {
          "text": "The number of times to repeat the animated sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAnimationLoopCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationLoopCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAnimationLoopCount"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAnimationLoopCount",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageanimationloopcount"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationStartIndex": {
      "abstract": [
        {
          "text": "A property that specifies the index of the first frame of an animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageAnimationStartIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationStartIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageAnimationStartIndex"
        }
      ],
      "role": "symbol",
      "title": "kCGImageAnimationStartIndex",
      "type": "topic",
      "url": "/documentation/imageio/kcgimageanimationstartindex"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Animations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGAnimateImageAtURLWithBlock(_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGAnimateImageDataWithBlock(_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceAnimationBlock",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationStartIndex",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationDelayTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationLoopCount"
      ],
      "title": "Animations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Animation-Status",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/allocationFailure",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/corruptInputImage",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/incompleteInputImage",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/parameterError",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/unsupportedFormat"
      ],
      "title": "Animation Status"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CGImageAnimationStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageAnimationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageAnimationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Animation-Status",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/allocationFailure",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/corruptInputImage",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/incompleteInputImage",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/parameterError",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageAnimationStatus/unsupportedFormat"
              ],
              "title": "Animation Status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Animations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGAnimateImageAtURLWithBlock(_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGAnimateImageDataWithBlock(_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceAnimationBlock",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationStartIndex",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationDelayTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageAnimationLoopCount"
              ],
              "title": "Animations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CGImageAnimationStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1corruptInputImage/title",
          "value": "kCGImageAnimationStatus_CorruptInputImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1corruptInputImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAnimationStatus_CorruptInputImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus/title",
          "value": "CGImageAnimationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageAnimationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageAnimationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1allocationFailure/title",
          "value": "kCGImageAnimationStatus_AllocationFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1allocationFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAnimationStatus_AllocationFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1unsupportedFormat/title",
          "value": "kCGImageAnimationStatus_UnsupportedFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1unsupportedFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAnimationStatus_UnsupportedFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1incompleteInputImage/title",
          "value": "kCGImageAnimationStatus_IncompleteInputImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1incompleteInputImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAnimationStatus_IncompleteInputImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGAnimateImageAtURLWithBlock(_:_:_:)/title",
          "value": "CGAnimateImageAtURLWithBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGAnimateImageAtURLWithBlock(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGAnimateImageAtURLWithBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1parameterError/title",
          "value": "kCGImageAnimationStatus_ParameterError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageAnimationStatus~1parameterError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAnimationStatus_ParameterError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceAnimationBlock/title",
          "value": "CGImageSourceAnimationBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceAnimationBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceAnimationBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceAnimationBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceAnimationBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAnimationDelayTime/title",
          "value": "kCGImageAnimationDelayTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAnimationDelayTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAnimationDelayTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAnimationLoopCount/title",
          "value": "kCGImageAnimationLoopCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAnimationLoopCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAnimationLoopCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAnimationStartIndex/title",
          "value": "kCGImageAnimationStartIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageAnimationStartIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageAnimationStartIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGAnimateImageDataWithBlock(_:_:_:)/title",
          "value": "CGAnimateImageDataWithBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGAnimateImageDataWithBlock(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGAnimateImageDataWithBlock"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/cgimageanimationstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/cgimageanimationstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
