{
  "abstract": [
    {
      "text": "An opaque type that you use to write image data to a URL, data object, or data consumer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestination"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CGImageDestinationRef",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CGImageDestination"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CGImageDestination"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CGImageDestination"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CGImageDestination"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestination",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object provides an abstract interface for saving image data. Use an image destination to represent a single image, or multiple images packaged together. For example, you might create an image that also contains a thumbnail. You can also use the image destination to add metadata to your images.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "An image destination outputs data to a URL, a ",
              "type": "text"
            },
            {
              "code": "CFData",
              "type": "codeVoice"
            },
            {
              "text": " object, or a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgdataconsumer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, which you specify at creation time. After you create the image destination, add the image data and properties. When you are done, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationFinalize(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to finalize the image data and write it to the output location.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageIOGuide/imageio_intro/ikpg_intro.html#//apple_ref/doc/uid/TP40005462",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/coregraphics/cgdataconsumer": {
      "abstract": [
        {
          "text": "An abstraction for data-writing tasks that eliminates the need to manage a raw memory buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CGDataConsumer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgdataconsumer",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGDataConsumer",
      "type": "topic",
      "url": "/documentation/coregraphics/cgdataconsumer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageDestination": {
      "abstract": [
        {
          "text": "An opaque type that you use to write image data to a URL, data object, or data consumer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageDestination"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageDestination"
        }
      ],
      "role": "symbol",
      "title": "CGImageDestination",
      "type": "topic",
      "url": "/documentation/imageio/cgimagedestination"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationAddAuxiliaryDataInfo(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the auxiliary data, such as mattes and depth information, that accompany the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageDestinationAddAuxiliaryDataInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageDestinationRef",
          "text": "CGImageDestination"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationAddAuxiliaryDataInfo(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageDestinationAddAuxiliaryDataInfo"
        }
      ],
      "role": "symbol",
      "title": "CGImageDestinationAddAuxiliaryDataInfo(_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagedestinationaddauxiliarydatainfo(_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationAddImage(_:_:_:)": {
      "abstract": [
        {
          "text": "Adds an image to an image destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageDestinationAddImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageDestinationRef",
          "text": "CGImageDestination"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationAddImage(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageDestinationAddImage"
        }
      ],
      "role": "symbol",
      "title": "CGImageDestinationAddImage(_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagedestinationaddimage(_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationAddImageFromSource(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Adds an image from an image source to an image destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageDestinationAddImageFromSource"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageDestinationRef",
          "text": "CGImageDestination"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationAddImageFromSource(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageDestinationAddImageFromSource"
        }
      ],
      "role": "symbol",
      "title": "CGImageDestinationAddImageFromSource(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagedestinationaddimagefromsource(_:_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCopyTypeIdentifiers()": {
      "abstract": [
        {
          "text": "Returns an array of the uniform type identifiers that are supported for image destinations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageDestinationCopyTypeIdentifiers"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCopyTypeIdentifiers()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageDestinationCopyTypeIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "CGImageDestinationCopyTypeIdentifiers()",
      "type": "topic",
      "url": "/documentation/imageio/cgimagedestinationcopytypeidentifiers()"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCreateWithData(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an image destination that writes to a Core Foundation mutable data object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageDestinationCreateWithData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDataRef",
          "text": "CFMutableData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageDestinationRef",
          "text": "CGImageDestination"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCreateWithData(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageDestinationCreateWithData"
        }
      ],
      "role": "symbol",
      "title": "CGImageDestinationCreateWithData(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagedestinationcreatewithdata(_:_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCreateWithDataConsumer(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an image destination that writes to the specified data consumer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageDestinationCreateWithDataConsumer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGDataConsumerRef",
          "text": "CGDataConsumer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageDestinationRef",
          "text": "CGImageDestination"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCreateWithDataConsumer(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageDestinationCreateWithDataConsumer"
        }
      ],
      "role": "symbol",
      "title": "CGImageDestinationCreateWithDataConsumer(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagedestinationcreatewithdataconsumer(_:_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCreateWithURL(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an image destination that writes image data to the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageDestinationCreateWithURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageDestinationRef",
          "text": "CGImageDestination"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCreateWithURL(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageDestinationCreateWithURL"
        }
      ],
      "role": "symbol",
      "title": "CGImageDestinationCreateWithURL(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagedestinationcreatewithurl(_:_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationFinalize(_:)": {
      "abstract": [
        {
          "text": "Writes image data and properties to the data, URL, or data consumer associated with the image destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageDestinationFinalize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageDestinationRef",
          "text": "CGImageDestination"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationFinalize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageDestinationFinalize"
        }
      ],
      "role": "symbol",
      "title": "CGImageDestinationFinalize(_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagedestinationfinalize(_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the unique type identifier of an image destination opaque type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageDestinationGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageDestinationGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CGImageDestinationGetTypeID()",
      "type": "topic",
      "url": "/documentation/imageio/cgimagedestinationgettypeid()"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationSetProperties(_:_:)": {
      "abstract": [
        {
          "text": "Applies one or more properties to all images in an image destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageDestinationSetProperties"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageDestinationRef",
          "text": "CGImageDestination"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationSetProperties(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageDestinationSetProperties"
        }
      ],
      "role": "symbol",
      "title": "CGImageDestinationSetProperties(_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagedestinationsetproperties(_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSource": {
      "abstract": [
        {
          "text": "An opaque type that you use to read image data from a URL, data object, or data consumer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSource"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSource"
        }
      ],
      "role": "symbol",
      "title": "CGImageSource",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesource"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationBackgroundColor": {
      "abstract": [
        {
          "text": "The background color to use when the image has an alpha component, but the destination format doesn’t support alpha.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationBackgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationBackgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationBackgroundColor"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationBackgroundColor",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationbackgroundcolor"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationDateTime": {
      "abstract": [
        {
          "text": "The date and time information to associate with the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationDateTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationDateTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationDateTime"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationDateTime",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationdatetime"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEmbedThumbnail": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to embed a thumbnail for JPEG and HEIF images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEmbedThumbnail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEmbedThumbnail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationEmbedThumbnail"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationEmbedThumbnail",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationembedthumbnail"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationImageMaxPixelSize": {
      "abstract": [
        {
          "text": "The maximum width and height of the image, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationImageMaxPixelSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationImageMaxPixelSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationImageMaxPixelSize"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationImageMaxPixelSize",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationimagemaxpixelsize"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationLossyCompressionQuality": {
      "abstract": [
        {
          "text": "The desired compression quality to use when writing the image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationLossyCompressionQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationLossyCompressionQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationLossyCompressionQuality"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationLossyCompressionQuality",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationlossycompressionquality"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationMergeMetadata": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to merge new metadata with the image’s existing metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationMergeMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationMergeMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationMergeMetadata"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationMergeMetadata",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationmergemetadata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationMetadata": {
      "abstract": [
        {
          "text": "The metadata tags to include with the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationMetadata"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationMetadata",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationmetadata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationOptimizeColorForSharing": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to create the image using a colorspace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationOptimizeColorForSharing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationOptimizeColorForSharing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationOptimizeColorForSharing"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationOptimizeColorForSharing",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationoptimizecolorforsharing"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationOrientation": {
      "abstract": [
        {
          "text": "The orientation of the image, specified as an EXIF value in the range 1 to 8.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationOrientation"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationOrientation",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationorientation"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationPreserveGainMap": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to include a HEIF-embedded gain map in the image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageDestinationPreserveGainMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationPreserveGainMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageDestinationPreserveGainMap"
        }
      ],
      "role": "symbol",
      "title": "kCGImageDestinationPreserveGainMap",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagedestinationpreservegainmap"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataShouldExcludeGPS": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to exclude GPS metadata from EXIF data or the corresponding XMP tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataShouldExcludeGPS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataShouldExcludeGPS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataShouldExcludeGPS"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataShouldExcludeGPS",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatashouldexcludegps"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataShouldExcludeXMP": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to exclude XMP data from the destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImageMetadataShouldExcludeXMP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataShouldExcludeXMP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImageMetadataShouldExcludeXMP"
        }
      ],
      "role": "symbol",
      "title": "kCGImageMetadataShouldExcludeXMP",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagemetadatashouldexcludexmp"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageIOGuide/imageio_intro/ikpg_intro.html#//apple_ref/doc/uid/TP40005462": {
      "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageIOGuide/imageio_intro/ikpg_intro.html#//apple_ref/doc/uid/TP40005462",
      "title": "Image I/O Programming Guide",
      "titleInlineContent": [
        {
          "text": "Image I/O Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/ImageIOGuide/imageio_intro/ikpg_intro.html#//apple_ref/doc/uid/TP40005462"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Image-Management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSource"
      ],
      "title": "Image Management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-Image-Destination",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCreateWithURL(_:_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCreateWithData(_:_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCreateWithDataConsumer(_:_:_:_:)"
      ],
      "title": "Creating an Image Destination"
    },
    {
      "anchor": "Adding-Images-to-the-Destination",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationAddImage(_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationAddImageFromSource(_:_:_:_:)"
      ],
      "title": "Adding Images to the Destination"
    },
    {
      "anchor": "Adding-Metadata-to-the-Image",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationSetProperties(_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationAddAuxiliaryDataInfo(_:_:_:)"
      ],
      "title": "Adding Metadata to the Image"
    },
    {
      "anchor": "Finalizing-the-Image-Data",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationFinalize(_:)"
      ],
      "title": "Finalizing the Image Data"
    },
    {
      "anchor": "Getting-the-Image-Types",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCopyTypeIdentifiers()",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationGetTypeID()"
      ],
      "title": "Getting the Image Types"
    },
    {
      "anchor": "Configuring-the-Image-Behaviors",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationLossyCompressionQuality",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationBackgroundColor",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationDateTime",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEmbedThumbnail",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationImageMaxPixelSize",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationMetadata",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationMergeMetadata",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationOptimizeColorForSharing",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationOrientation",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationPreserveGainMap",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataShouldExcludeGPS",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataShouldExcludeXMP"
      ],
      "title": "Configuring the Image Behaviors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CGImageDestinationRef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-an-Image-Destination",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCreateWithURL(_:_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCreateWithData(_:_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCreateWithDataConsumer(_:_:_:_:)"
              ],
              "title": "Creating an Image Destination"
            },
            {
              "anchor": "Adding-Images-to-the-Destination",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationAddImage(_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationAddImageFromSource(_:_:_:_:)"
              ],
              "title": "Adding Images to the Destination"
            },
            {
              "anchor": "Adding-Metadata-to-the-Image",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationSetProperties(_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationAddAuxiliaryDataInfo(_:_:_:)"
              ],
              "title": "Adding Metadata to the Image"
            },
            {
              "anchor": "Finalizing-the-Image-Data",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationFinalize(_:)"
              ],
              "title": "Finalizing the Image Data"
            },
            {
              "anchor": "Getting-the-Image-Types",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCopyTypeIdentifiers()",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationGetTypeID()"
              ],
              "title": "Getting the Image Types"
            },
            {
              "anchor": "Configuring-the-Image-Behaviors",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationLossyCompressionQuality",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationBackgroundColor",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationDateTime",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationEmbedThumbnail",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationImageMaxPixelSize",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationMetadata",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationMergeMetadata",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationOptimizeColorForSharing",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationOrientation",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageDestinationPreserveGainMap",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataShouldExcludeGPS",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImageMetadataShouldExcludeXMP"
              ],
              "title": "Configuring the Image Behaviors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Image-Management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSource"
              ],
              "title": "Image Management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGImageDestination",
                    "text": "CGImageDestination"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "CGImageDestinationRef"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationPreserveGainMap/title",
          "value": "kCGImageDestinationPreserveGainMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationPreserveGainMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationPreserveGainMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEmbedThumbnail/title",
          "value": "kCGImageDestinationEmbedThumbnail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationEmbedThumbnail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationEmbedThumbnail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationAddImage(_:_:_:)/title",
          "value": "CGImageDestinationAddImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationAddImage(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationAddImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationOrientation/title",
          "value": "kCGImageDestinationOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationOptimizeColorForSharing/title",
          "value": "kCGImageDestinationOptimizeColorForSharing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationOptimizeColorForSharing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationOptimizeColorForSharing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationMetadata/title",
          "value": "kCGImageDestinationMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationAddImageFromSource(_:_:_:_:)/title",
          "value": "CGImageDestinationAddImageFromSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationAddImageFromSource(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationAddImageFromSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataShouldExcludeGPS/title",
          "value": "kCGImageMetadataShouldExcludeGPS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataShouldExcludeGPS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataShouldExcludeGPS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationGetTypeID()/title",
          "value": "CGImageDestinationGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataShouldExcludeXMP/title",
          "value": "kCGImageMetadataShouldExcludeXMP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageMetadataShouldExcludeXMP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageMetadataShouldExcludeXMP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationImageMaxPixelSize/title",
          "value": "kCGImageDestinationImageMaxPixelSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationImageMaxPixelSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationImageMaxPixelSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSource/title",
          "value": "CGImageSourceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationCopyTypeIdentifiers()/title",
          "value": "CGImageDestinationCopyTypeIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationCopyTypeIdentifiers()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationCopyTypeIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationLossyCompressionQuality/title",
          "value": "kCGImageDestinationLossyCompressionQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationLossyCompressionQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationLossyCompressionQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationCreateWithData(_:_:_:_:)/title",
          "value": "CGImageDestinationCreateWithData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationCreateWithData(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationCreateWithData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationBackgroundColor/title",
          "value": "kCGImageDestinationBackgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationBackgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationBackgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationMergeMetadata/title",
          "value": "kCGImageDestinationMergeMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationMergeMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationMergeMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationSetProperties(_:_:)/title",
          "value": "CGImageDestinationSetProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationSetProperties(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationSetProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationCreateWithURL(_:_:_:_:)/title",
          "value": "CGImageDestinationCreateWithURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationCreateWithURL(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationCreateWithURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestination/title",
          "value": "CGImageDestinationRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestination/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgdataconsumer/title",
          "value": "CGDataConsumerRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationDateTime/title",
          "value": "kCGImageDestinationDateTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImageDestinationDateTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImageDestinationDateTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationFinalize(_:)/title",
          "value": "CGImageDestinationFinalize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationFinalize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationFinalize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationAddAuxiliaryDataInfo(_:_:_:)/title",
          "value": "CGImageDestinationAddAuxiliaryDataInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationAddAuxiliaryDataInfo(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationAddAuxiliaryDataInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationCreateWithDataConsumer(_:_:_:_:)/title",
          "value": "CGImageDestinationCreateWithDataConsumer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationCreateWithDataConsumer(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationCreateWithDataConsumer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/cgimagedestination"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/cgimagedestination"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
