{
  "abstract": [
    {
      "text": "Return the status of an image source.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetStatus(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CGImageSourceGetStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CGImageSourceGetStatus"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CGImageSourceRef",
        "text": "CGImageSource"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CGImageSourceStatus",
        "text": "CGImageSourceStatus"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CGImageSourceGetStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CGImageSourceGetStatus(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CGImageSourceGetStatus"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "isrc"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSource",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGImageSourceRef",
              "text": "CGImageSource"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CGImageSourceStatus",
              "text": "CGImageSourceStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The image source that contains the image data.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "isrc"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns the current status of the image source. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for a list of possible values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Status information is particularly informative for incremental image sources, but it may also be useful on image sources that contain non-incremental data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSource": {
      "abstract": [
        {
          "text": "An opaque type that you use to read image data from a URL, data object, or data consumer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSource"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSource"
        }
      ],
      "role": "symbol",
      "title": "CGImageSource",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesource"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetStatus(_:)": {
      "abstract": [
        {
          "text": "Return the status of an image source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceGetStatus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CGImageSourceStatus",
          "text": "CGImageSourceStatus"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetStatus(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceGetStatus"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceGetStatus(_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcegetstatus(_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetStatusAtIndex(_:_:)": {
      "abstract": [
        {
          "text": "Returns the current status of an image at the specified location in the image source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceGetStatusAtIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CGImageSourceStatus",
          "text": "CGImageSourceStatus"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetStatusAtIndex(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceGetStatusAtIndex"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceGetStatusAtIndex(_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcegetstatusatindex(_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus": {
      "abstract": [
        {
          "text": "The set of status values for images and image sources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceStatus"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceStatus"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceStatus",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcestatus"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Image-Status",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetStatusAtIndex(_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus"
      ],
      "title": "Getting the Image Status"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CGImageSourceGetStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceGetStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Image-Status",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceGetStatusAtIndex(_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus"
              ],
              "title": "Getting the Image Status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@CGImageSourceStatus",
                    "text": "CGImageSourceStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CGImageSourceGetStatus"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSource",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGImageSourceRef",
                    "text": "CGImageSourceRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "isrc"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The image source that contains the image data.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "isrc"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "Returns the current status of the image source. See ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceStatus",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " for a list of possible values.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceGetStatusAtIndex(_:_:)/title",
          "value": "CGImageSourceGetStatusAtIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceGetStatusAtIndex(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceGetStatusAtIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSource/title",
          "value": "CGImageSourceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceGetStatus(_:)/title",
          "value": "CGImageSourceGetStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceGetStatus(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceGetStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus/title",
          "value": "CGImageSourceStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/cgimagesourcegetstatus(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/cgimagesourcegetstatus(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
