{
  "abstract": [
    {
      "text": "A value describing the intended display orientation for an image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CGImagePropertyOrientation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CGImagePropertyOrientation"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CGImagePropertyOrientation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CGImagePropertyOrientation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@frozen"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CGImagePropertyOrientation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Values of this type define the position of the pixel coordinate origin point (",
              "type": "text"
            },
            {
              "code": "0,0",
              "type": "codeVoice"
            },
            {
              "text": ") and the directions of the coordinate axes relative to the intended display orientation of the image. Orientation values are commonly found in image metadata, and specifying image orientation correctly can be important both for displaying the image and for certain image processing tasks such as face recognition.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, the pixel data for an image captured by an iOS device camera is encoded in the camera sensor’s native landscape orientation. When the user captures a photo while holding the device in portrait orientation, iOS writes an orientation value of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/right",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in the resulting image file. Software displaying the image can then, after reading that value from the file’s metadata, apply a 90° clockwise rotation to the image data so that the image appears in the photographer’s intended orientation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2948298",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Compatibility-with-UIImageOrientation",
          "level": 3,
          "text": "Compatibility with UIImageOrientation",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type covers the same set of orientation names available in from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImage/Orientation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type, but the underlying numeric values of each type do not match. (For example, the “left mirrored” orientation has an underlying value of 5 in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", but an underlying value of 7 in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImage/Orientation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".) If you have an orientation value in one type and need a semantically equivalent value in the other, use a function such as those below to produce the same-named value in the other type:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 1. Converting between CGImagePropertyOrientation and UIImageOrientation",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "extension CGImagePropertyOrientation {",
                    "    init(_ uiOrientation: UIImageOrientation) {",
                    "        switch uiOrientation {",
                    "            case .up: self = .up",
                    "            case .upMirrored: self = .upMirrored",
                    "            case .down: self = .down",
                    "            case .downMirrored: self = .downMirrored",
                    "            case .left: self = .left",
                    "            case .leftMirrored: self = .leftMirrored",
                    "            case .right: self = .right",
                    "            case .rightMirrored: self = .rightMirrored",
                    "        }",
                    "    }",
                    "}",
                    "extension UIImageOrientation {",
                    "    init(_ cgOrientation: UIImageOrientation) {",
                    "        switch cgOrientation {",
                    "            case .up: self = .up",
                    "            case .upMirrored: self = .upMirrored",
                    "            case .down: self = .down",
                    "            case .downMirrored: self = .downMirrored",
                    "            case .left: self = .left",
                    "            case .leftMirrored: self = .leftMirrored",
                    "            case .right: self = .right",
                    "            case .rightMirrored: self = .rightMirrored",
                    "        }",
                    "    }",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "CGImagePropertyOrientation CGImagePropertyOrientationForUIImageOrientation(uiOrientation) {",
                    "    switch (uiOrientation) {",
                    "        case UIImageOrientationUp: return kCGImagePropertyOrientationUp;",
                    "        case UIImageOrientationDown: return kCGImagePropertyOrientationDown;",
                    "        case UIImageOrientationLeft: return kCGImagePropertyOrientationLeft;",
                    "        case UIImageOrientationRight: return kCGImagePropertyOrientationRight;",
                    "        case UIImageOrientationUpMirrored: return kCGImagePropertyOrientationUpMirrored;",
                    "        case UIImageOrientationDownMirrored: return kCGImagePropertyOrientationDownMirrored;",
                    "        case UIImageOrientationLeftMirrored: return kCGImagePropertyOrientationLeftMirrored;",
                    "        case UIImageOrientationRightMirrored: return kCGImagePropertyOrientationRightMirrored;",
                    "    }",
                    "}",
                    "UIImageOrientation UIImageOrientationForCGImagePropertyOrientation(cgOrientation) {",
                    "    switch (cgOrientation) {",
                    "        case kCGImagePropertyOrientationUp: return UIImageOrientationUp;",
                    "        case kCGImagePropertyOrientationDown: return UIImageOrientationDown;",
                    "        case kCGImagePropertyOrientationLeft: return UIImageOrientationLeft;",
                    "        case kCGImagePropertyOrientationRight: return UIImageOrientationRight;",
                    "        case kCGImagePropertyOrientationUpMirrored: return UIImageOrientationUpMirrored;",
                    "        case kCGImagePropertyOrientationDownMirrored: return UIImageOrientationDownMirrored;",
                    "        case kCGImagePropertyOrientationLeftMirrored: return UIImageOrientationLeftMirrored;",
                    "        case kCGImagePropertyOrientationRightMirrored: return UIImageOrientationRightMirrored;",
                    "    }",
                    "}"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "anchor": "Working-with-Raw-TIFFExif-Numeric-Values",
          "level": 3,
          "text": "Working with Raw TIFF/Exif Numeric Values",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Some APIs describe image orientation with basic integer values, intended for interpretation according to the TIFF and Exif specifications. The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type simply defines symbolic names for those values, so you can convert to and from the raw numeric type with C type-cast syntax or the inherited ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/RawRepresentable/init(rawValue:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " initializer and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/RawRepresentable/rawValue-swift.property",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property in Swift.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Swift/RawRepresentable/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new instance with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/RawRepresentable/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable/init(rawValue:)"
    },
    "doc://com.apple.documentation/documentation/Swift/RawRepresentable/rawValue-swift.property": {
      "abstract": [
        {
          "text": "The corresponding value of the raw type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/RawRepresentable/rawValue-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable/rawValue-swift.property"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIImage/Orientation": {
      "abstract": [
        {
          "text": "Constants that specify the intended display orientation for an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Orientation"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImage/Orientation",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIImage.Orientation",
      "type": "topic",
      "url": "/documentation/UIKit/UIImage/Orientation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation": {
      "abstract": [
        {
          "text": "A value describing the intended display orientation for an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImagePropertyOrientation"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImagePropertyOrientation"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/down": {
      "abstract": [
        {
          "text": "The encoded image data is rotated 180° from the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "down"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/down",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientationDown"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation.down",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation/down"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/downMirrored": {
      "abstract": [
        {
          "text": "The encoded image data is vertically flipped from the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downMirrored"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/downMirrored",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientationDownMirrored"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation.downMirrored",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation/downmirrored"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation/init(rawvalue:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/left": {
      "abstract": [
        {
          "text": "The encoded image data is rotated 90° clockwise from the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientationLeft"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation.left",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation/left"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/leftMirrored": {
      "abstract": [
        {
          "text": "The encoded image data is horizontally flipped and rotated 90° counter-clockwise from the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftMirrored"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/leftMirrored",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientationLeftMirrored"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation.leftMirrored",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation/leftmirrored"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/right": {
      "abstract": [
        {
          "text": "The encoded image data is rotated 90° clockwise from the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientationRight"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation.right",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation/right"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/rightMirrored": {
      "abstract": [
        {
          "text": "The encoded image data is horizontally flipped and rotated 90° clockwise from the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightMirrored"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/rightMirrored",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientationRightMirrored"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation.rightMirrored",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation/rightmirrored"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/up": {
      "abstract": [
        {
          "text": "The encoded image data matches the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "up"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/up",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientationUp"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation.up",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation/up"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/upMirrored": {
      "abstract": [
        {
          "text": "The encoded image data is horizontally flipped from the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "upMirrored"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/upMirrored",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientationUpMirrored"
        }
      ],
      "role": "symbol",
      "title": "CGImagePropertyOrientation.upMirrored",
      "type": "topic",
      "url": "/documentation/imageio/cgimagepropertyorientation/upmirrored"
    },
    "doc://com.apple.imageio/documentation/ImageIO/individual-image-properties": {
      "abstract": [
        {
          "text": "Properties that apply to an individual image in an image source.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/individual-image-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Individual Image Properties",
      "type": "topic",
      "url": "/documentation/imageio/individual-image-properties"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImageCount": {
      "abstract": [
        {
          "text": "The number of images in the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyImageCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImageCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyImageCount"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyImageCount",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyimagecount"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImages": {
      "abstract": [
        {
          "text": "An array of dictionaries, each of which contains metadata for one of the images in the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyImages"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImages",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyImages"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyImages",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyimages"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsFloat": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the image contains floating-point pixel samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIsFloat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsFloat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIsFloat"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIsFloat",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyisfloat"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsIndexed": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the image contains indexed pixel samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIsIndexed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsIndexed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIsIndexed"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIsIndexed",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyisindexed"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOrientation": {
      "abstract": [
        {
          "text": "The intended display orientation of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyOrientation"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyOrientation",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyorientation"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPrimaryImage": {
      "abstract": [
        {
          "text": "The index of the primary image in the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPrimaryImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPrimaryImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyPrimaryImage"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyPrimaryImage",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyprimaryimage"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyThumbnailImages": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyThumbnailImages"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyThumbnailImages",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyThumbnailImages"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyThumbnailImages",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertythumbnailimages"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "media-2948298": {
      "alt": "To correct an image with right orientation for display, rotate it 90° clockwise.",
      "identifier": "media-2948298",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5f85393673d69bff25539fb1abf634d9/media-2948298.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a4de8a358cbf9a76800cc595fceb8892/media-2948298@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Image-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImageCount",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsIndexed",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImages",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyThumbnailImages",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPrimaryImage",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsFloat",
        "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOrientation",
        "doc://com.apple.imageio/documentation/ImageIO/individual-image-properties"
      ],
      "title": "Image Information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Image-Orientations",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/up",
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/upMirrored",
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/down",
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/downMirrored",
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/leftMirrored",
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/right",
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/rightMirrored",
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/left"
      ],
      "title": "Image Orientations"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CGImagePropertyOrientation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImagePropertyOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImagePropertyOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Image-Orientations",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/up",
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/upMirrored",
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/down",
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/downMirrored",
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/leftMirrored",
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/right",
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/rightMirrored",
                "doc://com.apple.imageio/documentation/ImageIO/CGImagePropertyOrientation/left"
              ],
              "title": "Image Orientations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Image-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImageCount",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsIndexed",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyImages",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyThumbnailImages",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyPrimaryImage",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIsFloat",
                "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyOrientation",
                "doc://com.apple.imageio/documentation/ImageIO/individual-image-properties"
              ],
              "title": "Image Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CGImagePropertyOrientation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1leftMirrored/title",
          "value": "kCGImagePropertyOrientationLeftMirrored"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1leftMirrored/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationLeftMirrored"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPrimaryImage/title",
          "value": "kCGImagePropertyPrimaryImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyPrimaryImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyPrimaryImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyImageCount/title",
          "value": "kCGImagePropertyImageCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyImageCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyImageCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIsIndexed/title",
          "value": "kCGImagePropertyIsIndexed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIsIndexed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIsIndexed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1downMirrored/title",
          "value": "kCGImagePropertyOrientationDownMirrored"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1downMirrored/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationDownMirrored"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1down/title",
          "value": "kCGImagePropertyOrientationDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1down/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation/title",
          "value": "CGImagePropertyOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImagePropertyOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImagePropertyOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyImages/title",
          "value": "kCGImagePropertyImages"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyImages/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyImages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyThumbnailImages/title",
          "value": "kCGImagePropertyThumbnailImages"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyThumbnailImages/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyThumbnailImages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyOrientation/title",
          "value": "kCGImagePropertyOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1rightMirrored/title",
          "value": "kCGImagePropertyOrientationRightMirrored"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1rightMirrored/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationRightMirrored"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIImage~1Orientation/title",
          "value": "UIImageOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIImage~1Orientation/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIImageOrientation"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1up/title",
          "value": "kCGImagePropertyOrientationUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1up/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1left/title",
          "value": "kCGImagePropertyOrientationLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1upMirrored/title",
          "value": "kCGImagePropertyOrientationUpMirrored"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1upMirrored/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationUpMirrored"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1right/title",
          "value": "kCGImagePropertyOrientationRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImagePropertyOrientation~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIsFloat/title",
          "value": "kCGImagePropertyIsFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIsFloat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIsFloat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/cgimagepropertyorientation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/cgimagepropertyorientation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
