{
  "abstract": [
    {
      "text": "Updates the value of the metadata tag assigned to the specified image property.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetValueMatchingImageProperty(_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CGImageMetadataSetValueMatchingImageProperty",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CGImageMetadataSetValueMatchingImageProperty"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CGMutableImageMetadataRef",
        "text": "CGMutableImageMetadata"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFTypeRef",
        "text": "CFTypeRef"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CGImageMetadataSetValueMatchingImageProperty"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CGImageMetadataSetValueMatchingImageProperty(_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CGImageMetadataSetValueMatchingImageProperty"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "metadata"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGMutableImageMetadata",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGMutableImageMetadataRef",
              "text": "CGMutableImageMetadata"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "dictionaryName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "propertyName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "value"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFTypeRef",
              "text": "CFTypeRef"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The metadata object that contains the tag.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "metadata"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The metadata subdictionary to which the image property belongs. For example, specify ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifDictionary",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for image properties that are part of the image’s EXIF metadata. This function doesn’t support all dictionaries.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "dictionaryName"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The name of the property. For example, specify ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFOrientation",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifDateTimeOriginal",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCKeywords",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". If the specified property is unsupported by the metadata object, this function logs a warning.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "propertyName"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The new value for the property. The new value’s type must match the XMP type of the metadata tag.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "value"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": " if this function set the tag successfully, or ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": " if a problem occurred.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this function to update the value of a property in the specified metadata collection. If you try to set the value of an EXIF or IPTC property, this function matches it to an appropriate XMP tag. For example, when you set the value of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifDateTimeOriginal",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, this function sets the value of the ",
              "type": "text"
            },
            {
              "code": "photoshop:DateTime",
              "type": "codeVoice"
            },
            {
              "text": " XMP tag.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the metdata object doesn’t contain the tag, this function creates it and populates it with appropriate XMP information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataRemoveTagWithPath(_:_:_:)": {
      "abstract": [
        {
          "text": "Removes the tag at the specified path from the metadata object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataRemoveTagWithPath"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGMutableImageMetadataRef",
          "text": "CGMutableImageMetadata"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageMetadataTagRef",
          "text": "CGImageMetadataTag"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataRemoveTagWithPath(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataRemoveTagWithPath"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataRemoveTagWithPath(_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadataremovetagwithpath(_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetTagWithPath(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the tag at the specified path in the metadata object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataSetTagWithPath"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGMutableImageMetadataRef",
          "text": "CGMutableImageMetadata"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageMetadataTagRef",
          "text": "CGImageMetadataTag"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageMetadataTagRef",
          "text": "CGImageMetadataTag"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetTagWithPath(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataSetTagWithPath"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataSetTagWithPath(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatasettagwithpath(_:_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetValueMatchingImageProperty(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Updates the value of the metadata tag assigned to the specified image property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataSetValueMatchingImageProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGMutableImageMetadataRef",
          "text": "CGMutableImageMetadata"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetValueMatchingImageProperty(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataSetValueMatchingImageProperty"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataSetValueMatchingImageProperty(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatasetvaluematchingimageproperty(_:_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetValueWithPath(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Update the value of an existing metadata tag, or create a new tag using the specified information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataSetValueWithPath"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGMutableImageMetadataRef",
          "text": "CGMutableImageMetadata"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageMetadataTagRef",
          "text": "CGImageMetadataTag"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetValueWithPath(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataSetValueWithPath"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataSetValueWithPath(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatasetvaluewithpath(_:_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGMutableImageMetadata": {
      "abstract": [
        {
          "text": "An opaque type for adding or modifying image metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGMutableImageMetadata"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGMutableImageMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGMutableImageMetadata"
        }
      ],
      "role": "symbol",
      "title": "CGMutableImageMetadata",
      "type": "topic",
      "url": "/documentation/imageio/cgmutableimagemetadata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifDateTimeOriginal": {
      "abstract": [
        {
          "text": "The original date and time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifDateTimeOriginal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifDateTimeOriginal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifDateTimeOriginal"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifDateTimeOriginal",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifdatetimeoriginal"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifDictionary": {
      "abstract": [
        {
          "text": "A dictionary of key-value pairs for an image that uses Exchangeable Image File Format (EXIF).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifDictionary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyExifDictionary"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyExifDictionary",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyexifdictionary"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCKeywords": {
      "abstract": [
        {
          "text": "Keywords relevant to the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCKeywords"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCKeywords",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyIPTCKeywords"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyIPTCKeywords",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertyiptckeywords"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFOrientation": {
      "abstract": [
        {
          "text": "The image orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCGImagePropertyTIFFOrientation"
        }
      ],
      "role": "symbol",
      "title": "kCGImagePropertyTIFFOrientation",
      "type": "topic",
      "url": "/documentation/imageio/kcgimagepropertytifforientation"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFTypeRef": {
      "abstract": [
        {
          "text": "An untyped \"generic\" reference to any Core Foundation object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFTypeRef"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFTypeRef",
      "type": "topic",
      "url": "/documentation/corefoundation/cftyperef"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-the-Values-of-Tags",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetValueWithPath(_:_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetTagWithPath(_:_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataRemoveTagWithPath(_:_:_:)"
      ],
      "title": "Setting the Values of Tags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CGImageMetadataSetValueMatchingImageProperty"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataSetValueMatchingImageProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-the-Values-of-Tags",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetValueWithPath(_:_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetTagWithPath(_:_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataRemoveTagWithPath(_:_:_:)"
              ],
              "title": "Setting the Values of Tags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:b",
                    "text": "bool"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CGImageMetadataSetValueMatchingImageProperty"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGMutableImageMetadata",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGMutableImageMetadataRef",
                    "text": "CGMutableImageMetadataRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "metadata"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "dictionaryName"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "propertyName"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFTypeRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFTypeRef",
                    "text": "CFTypeRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "value"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The metadata object that contains the tag.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "metadata"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The metadata subdictionary to which the image property belongs. For example, specify ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifDictionary",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for image properties that are part of the image’s EXIF metadata. This function doesn’t support all dictionaries.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "dictionaryName"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The name of the property. For example, specify ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyTIFFOrientation",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyExifDateTimeOriginal",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", or ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCGImagePropertyIPTCKeywords",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". If the specified property is unsupported by the metadata object, this function logs a warning.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "propertyName"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The new value for the property. The new value’s type must match the XMP type of the metadata tag.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "value"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "code": "true",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if this function set the tag successfully, or ",
                    "type": "text"
                  },
                  {
                    "code": "false",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if a problem occurred.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataSetValueWithPath(_:_:_:_:)/title",
          "value": "CGImageMetadataSetValueWithPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataSetValueWithPath(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataSetValueWithPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifDictionary/title",
          "value": "kCGImagePropertyExifDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataRemoveTagWithPath(_:_:_:)/title",
          "value": "CGImageMetadataRemoveTagWithPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataRemoveTagWithPath(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataRemoveTagWithPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFOrientation/title",
          "value": "kCGImagePropertyTIFFOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyTIFFOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyTIFFOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataSetValueMatchingImageProperty(_:_:_:_:)/title",
          "value": "CGImageMetadataSetValueMatchingImageProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataSetValueMatchingImageProperty(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataSetValueMatchingImageProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataSetTagWithPath(_:_:_:_:)/title",
          "value": "CGImageMetadataSetTagWithPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataSetTagWithPath(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataSetTagWithPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifDateTimeOriginal/title",
          "value": "kCGImagePropertyExifDateTimeOriginal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyExifDateTimeOriginal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyExifDateTimeOriginal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCKeywords/title",
          "value": "kCGImagePropertyIPTCKeywords"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCGImagePropertyIPTCKeywords/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyIPTCKeywords"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGMutableImageMetadata/title",
          "value": "CGMutableImageMetadataRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGMutableImageMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGMutableImageMetadataRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGMutableImageMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGMutableImageMetadataRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/cgimagemetadatasetvaluematchingimageproperty(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/cgimagemetadatasetvaluematchingimageproperty(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
