{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceSetAllowableTypes(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CGImageSourceSetAllowableTypes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CGImageSourceSetAllowableTypes"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFArrayRef",
        "text": "CFArray"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CGImageSourceSetAllowableTypes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CGImageSourceSetAllowableTypes(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CGImageSourceSetAllowableTypes"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "allowableTypes"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArray"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationAddImageAndMetadata(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageDestinationAddImageAndMetadata"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageDestinationRef",
          "text": "CGImageDestination"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageMetadataRef",
          "text": "CGImageMetadata"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationAddImageAndMetadata(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageDestinationAddImageAndMetadata"
        }
      ],
      "role": "symbol",
      "title": "CGImageDestinationAddImageAndMetadata(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagedestinationaddimageandmetadata(_:_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCopyImageSource(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageDestinationCopyImageSource"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageDestinationRef",
          "text": "CGImageDestination"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCopyImageSource(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageDestinationCopyImageSource"
        }
      ],
      "role": "symbol",
      "title": "CGImageDestinationCopyImageSource(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagedestinationcopyimagesource(_:_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyMetadataAtIndex(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceCopyMetadataAtIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageMetadataRef",
          "text": "CGImageMetadata"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyMetadataAtIndex(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceCopyMetadataAtIndex"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceCopyMetadataAtIndex(_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcecopymetadataatindex(_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceRemoveCacheAtIndex(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceRemoveCacheAtIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageSourceRef",
          "text": "CGImageSource"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceRemoveCacheAtIndex(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceRemoveCacheAtIndex"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceRemoveCacheAtIndex(_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourceremovecacheatindex(_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceSetAllowableTypes(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageSourceSetAllowableTypes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceSetAllowableTypes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageSourceSetAllowableTypes"
        }
      ],
      "role": "symbol",
      "title": "CGImageSourceSetAllowableTypes(_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagesourcesetallowabletypes(_:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFArrayRef": {
      "abstract": [
        {
          "text": "A reference to an immutable array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFArray",
      "type": "topic",
      "url": "/documentation/corefoundation/cfarray"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationAddImageAndMetadata(_:_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCopyImageSource(_:_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyMetadataAtIndex(_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceRemoveCacheAtIndex(_:_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.2",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CGImageSourceSetAllowableTypes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceSetAllowableTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationAddImageAndMetadata(_:_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageDestinationCopyImageSource(_:_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceCopyMetadataAtIndex(_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageSourceRemoveCacheAtIndex(_:_:)"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CGImageSourceSetAllowableTypes"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFArrayRef",
                    "text": "CFArrayRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "allowableTypes"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFArrayRef/title",
          "value": "CFArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceSetAllowableTypes(_:)/title",
          "value": "CGImageSourceSetAllowableTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceSetAllowableTypes(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceSetAllowableTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationAddImageAndMetadata(_:_:_:_:)/title",
          "value": "CGImageDestinationAddImageAndMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationAddImageAndMetadata(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationAddImageAndMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationCopyImageSource(_:_:_:_:)/title",
          "value": "CGImageDestinationCopyImageSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageDestinationCopyImageSource(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageDestinationCopyImageSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceRemoveCacheAtIndex(_:_:)/title",
          "value": "CGImageSourceRemoveCacheAtIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceRemoveCacheAtIndex(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceRemoveCacheAtIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCopyMetadataAtIndex(_:_:_:)/title",
          "value": "CGImageSourceCopyMetadataAtIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageSourceCopyMetadataAtIndex(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageSourceCopyMetadataAtIndex"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/cgimagesourcesetallowabletypes(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/cgimagesourcesetallowabletypes(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
