{
  "abstract": [
    {
      "text": "An opaque type for adding or modifying image metadata.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imageio/documentation/ImageIO"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imageio/documentation/ImageIO/CGMutableImageMetadata"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CGMutableImageMetadataRef",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CGMutableImageMetadata"
      }
    ],
    "modules": [
      {
        "name": "Image I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CGMutableImageMetadata"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CGMutableImageMetadata"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CGMutableImageMetadata"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGMutableImageMetadata",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " opaque type when you want to modify the metadata in an image. You may pass this type to any functions that take a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadata",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type as a parameter. This object stores the tag information as XMP data, which you can write back to the image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you access or modify EXIF or IPTC properties, the metadata functions automatically bridge those properties to appropriate XMP properties. This bridging behavior fills in any fields that are present only in the XMP data. For example, it fills in the namespace, prefix, and XMP type information in the corresponding ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataTag",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imageio/documentation/ImageIO": {
      "abstract": [
        {
          "text": "Read and write most image file formats, and access an image’s metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Image I/O",
      "type": "topic",
      "url": "/documentation/imageio"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadata": {
      "abstract": [
        {
          "text": "An immutable object that contains the XMP metadata associated with an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadata"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadata"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadata",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataCreateMutable()": {
      "abstract": [
        {
          "text": "Creates an empty, mutable image metdata opaque type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataCreateMutable"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGMutableImageMetadataRef",
          "text": "CGMutableImageMetadata"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataCreateMutable()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataCreateMutable"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataCreateMutable()",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatacreatemutable()"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataCreateMutableCopy(_:)": {
      "abstract": [
        {
          "text": "Creates a deep, mutable copy of the specified metadata information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataCreateMutableCopy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageMetadataRef",
          "text": "CGImageMetadata"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGMutableImageMetadataRef",
          "text": "CGMutableImageMetadata"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataCreateMutableCopy(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataCreateMutableCopy"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataCreateMutableCopy(_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatacreatemutablecopy(_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataErrors": {
      "abstract": [
        {
          "text": "Constants for errors that occur when getting or setting metadata information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataErrors"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataErrors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataErrors"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataErrors",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadataerrors"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataRegisterNamespaceForPrefix(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers the specified namespace and prefix with the metadata object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataRegisterNamespaceForPrefix"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGMutableImageMetadataRef",
          "text": "CGMutableImageMetadata"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataRegisterNamespaceForPrefix(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataRegisterNamespaceForPrefix"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataRegisterNamespaceForPrefix(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadataregisternamespaceforprefix(_:_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataRemoveTagWithPath(_:_:_:)": {
      "abstract": [
        {
          "text": "Removes the tag at the specified path from the metadata object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataRemoveTagWithPath"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGMutableImageMetadataRef",
          "text": "CGMutableImageMetadata"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageMetadataTagRef",
          "text": "CGImageMetadataTag"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataRemoveTagWithPath(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataRemoveTagWithPath"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataRemoveTagWithPath(_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadataremovetagwithpath(_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetTagWithPath(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the tag at the specified path in the metadata object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataSetTagWithPath"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGMutableImageMetadataRef",
          "text": "CGMutableImageMetadata"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageMetadataTagRef",
          "text": "CGImageMetadataTag"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageMetadataTagRef",
          "text": "CGImageMetadataTag"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetTagWithPath(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataSetTagWithPath"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataSetTagWithPath(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatasettagwithpath(_:_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetValueMatchingImageProperty(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Updates the value of the metadata tag assigned to the specified image property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataSetValueMatchingImageProperty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGMutableImageMetadataRef",
          "text": "CGMutableImageMetadata"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetValueMatchingImageProperty(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataSetValueMatchingImageProperty"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataSetValueMatchingImageProperty(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatasetvaluematchingimageproperty(_:_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetValueWithPath(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Update the value of an existing metadata tag, or create a new tag using the specified information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataSetValueWithPath"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGMutableImageMetadataRef",
          "text": "CGMutableImageMetadata"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageMetadataTagRef",
          "text": "CGImageMetadataTag"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetValueWithPath(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataSetValueWithPath"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataSetValueWithPath(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatasetvaluewithpath(_:_:_:_:)"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataTag": {
      "abstract": [
        {
          "text": "An immutable type that contains information about a single piece of image metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGImageMetadataTag"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageMetadataTag"
        }
      ],
      "role": "symbol",
      "title": "CGImageMetadataTag",
      "type": "topic",
      "url": "/documentation/imageio/cgimagemetadatatag"
    },
    "doc://com.apple.imageio/documentation/ImageIO/CGMutableImageMetadata": {
      "abstract": [
        {
          "text": "An opaque type for adding or modifying image metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CGMutableImageMetadata"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/CGMutableImageMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGMutableImageMetadata"
        }
      ],
      "role": "symbol",
      "title": "CGMutableImageMetadata",
      "type": "topic",
      "url": "/documentation/imageio/cgmutableimagemetadata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/kCFErrorDomainCGImageMetadata": {
      "abstract": [
        {
          "text": "The domain for metadata-related errors that originate in the Image I/O framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCFErrorDomainCGImageMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/kCFErrorDomainCGImageMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCFErrorDomainCGImageMetadata"
        }
      ],
      "role": "symbol",
      "title": "kCFErrorDomainCGImageMetadata",
      "type": "topic",
      "url": "/documentation/imageio/kcferrordomaincgimagemetadata"
    },
    "doc://com.apple.imageio/documentation/ImageIO/xmp-namespaces-and-prefixes": {
      "abstract": [
        {
          "text": "Discover the public namespaces and prefixes that exist in XMP metadata tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imageio/documentation/ImageIO/xmp-namespaces-and-prefixes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "XMP Namespaces and Prefixes",
      "type": "topic",
      "url": "/documentation/imageio/xmp-namespaces-and-prefixes"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadata"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "XMP-Metadata",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadata",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataTag",
        "doc://com.apple.imageio/documentation/ImageIO/xmp-namespaces-and-prefixes",
        "doc://com.apple.imageio/documentation/ImageIO/kCFErrorDomainCGImageMetadata",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataErrors"
      ],
      "title": "XMP Metadata"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Mutable-Metadata-Type",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataCreateMutable()",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataCreateMutableCopy(_:)"
      ],
      "title": "Creating a Mutable Metadata Type"
    },
    {
      "anchor": "Setting-the-Values-of-Tags",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetValueWithPath(_:_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetValueMatchingImageProperty(_:_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetTagWithPath(_:_:_:_:)",
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataRemoveTagWithPath(_:_:_:)"
      ],
      "title": "Setting the Values of Tags"
    },
    {
      "anchor": "Registering-a-Custom-Namespace",
      "identifiers": [
        "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataRegisterNamespaceForPrefix(_:_:_:_:)"
      ],
      "title": "Registering a Custom Namespace"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CGMutableImageMetadataRef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGMutableImageMetadataRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGMutableImageMetadataRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imageio/documentation/ImageIO"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Mutable-Metadata-Type",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataCreateMutable()",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataCreateMutableCopy(_:)"
              ],
              "title": "Creating a Mutable Metadata Type"
            },
            {
              "anchor": "Setting-the-Values-of-Tags",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetValueWithPath(_:_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetValueMatchingImageProperty(_:_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataSetTagWithPath(_:_:_:_:)",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataRemoveTagWithPath(_:_:_:)"
              ],
              "title": "Setting the Values of Tags"
            },
            {
              "anchor": "Registering-a-Custom-Namespace",
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataRegisterNamespaceForPrefix(_:_:_:_:)"
              ],
              "title": "Registering a Custom Namespace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "XMP-Metadata",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadata",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataTag",
                "doc://com.apple.imageio/documentation/ImageIO/xmp-namespaces-and-prefixes",
                "doc://com.apple.imageio/documentation/ImageIO/kCFErrorDomainCGImageMetadata",
                "doc://com.apple.imageio/documentation/ImageIO/CGImageMetadataErrors"
              ],
              "title": "XMP Metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGImageMetadata",
                    "text": "CGImageMetadata"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "CGMutableImageMetadataRef"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataErrors/title",
          "value": "CGImageMetadataErrors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataErrors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataErrors/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataErrors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataSetValueWithPath(_:_:_:_:)/title",
          "value": "CGImageMetadataSetValueWithPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataSetValueWithPath(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataSetValueWithPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGMutableImageMetadata/title",
          "value": "CGMutableImageMetadataRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGMutableImageMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGMutableImageMetadataRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGMutableImageMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGMutableImageMetadataRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataRegisterNamespaceForPrefix(_:_:_:_:)/title",
          "value": "CGImageMetadataRegisterNamespaceForPrefix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataRegisterNamespaceForPrefix(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataRegisterNamespaceForPrefix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataCreateMutableCopy(_:)/title",
          "value": "CGImageMetadataCreateMutableCopy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataCreateMutableCopy(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataCreateMutableCopy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCFErrorDomainCGImageMetadata/title",
          "value": "kCFErrorDomainCGImageMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1kCFErrorDomainCGImageMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCFErrorDomainCGImageMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadata/title",
          "value": "CGImageMetadataRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataCreateMutable()/title",
          "value": "CGImageMetadataCreateMutable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataCreateMutable()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataCreateMutable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataSetValueMatchingImageProperty(_:_:_:_:)/title",
          "value": "CGImageMetadataSetValueMatchingImageProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataSetValueMatchingImageProperty(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataSetValueMatchingImageProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataSetTagWithPath(_:_:_:_:)/title",
          "value": "CGImageMetadataSetTagWithPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataSetTagWithPath(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataSetTagWithPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataRemoveTagWithPath(_:_:_:)/title",
          "value": "CGImageMetadataRemoveTagWithPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataRemoveTagWithPath(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataRemoveTagWithPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataTag/title",
          "value": "CGImageMetadataTagRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataTagRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imageio~1documentation~1ImageIO~1CGImageMetadataTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CGImageMetadataTagRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imageio/cgmutableimagemetadata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imageio/cgmutableimagemetadata"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
